### ISSUE TITLE
Add orthologies to WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#1519]
When will worm mine deal with othrology?  I am really needing to have access to human homologs (hopefully in a way that worked better than wormmart).<br /><br />Any way I might get notified when this feature becomes available?  I understand it should be before years end from what I heard at the INWM in LA?

Reported by: bria********\* (krae***********)  (obscured for privacy)
Submitted From: Tools (/header)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36

**Comment by chris-grove** [comment]
PANTHER homologies have been added
