### ISSUE TITLE
Adding RNAi data to WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#1592]
WormMine is a great tool!<br />However the RNAi dataset seems to be missing.<br /><br />For instance, using a phenotype constraint, it would only search for allele phenotype and not RNAi phenotypes.<br /><br />Is it technically challenging to add RNAi dataset?

Reported by: Jeff******\* (jeff*****************)  (obscured for privacy)
Submitted From:  (/footer)

Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.72 Safari/537.36

**Comment by chris-grove** [comment]
RNAi data added as of im-254 version
