### ISSUE TITLE
Feature Request: Can the intellectual lineage be add...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#1736]
Can the intellectual lineage be added to a cytoscape view? I though we had a viewer before....

Reported by: Paul*********\* (worm****************)  (obscured for privacy)
Submitted From: Paul%20Sternberg%20(person) (/resources/person/WBPerson625#0132--10-1)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:23.0) Gecko/20100101 Firefox/23.0

**Comment by raymond91125** [comment]
Wow, @epaule good digging.
Yes We Can!
[Paul's Lineage Graph](http://www.wormbase.org/resources/person/WBPerson625#2--10)
