### ISSUE TITLE
wiki pages - are these worth preserving?

### ISSUE THREAD

**Issue by gw3** [WormBase/website#183]
The following wiki pages from the old 'Tools' wiki page contain a lot of information.
They are old and hard to maintain.
It looks like Chris Grove took a stab at updating them in 2010

http://wiki.wormbase.org/index.php/Mapped_Transgenes
http://wiki.wormbase.org/index.php/Tissue_Specific_Transgene_Markers
http://wiki.wormbase.org/index.php/Balancers

Do we need to update them and move them to the new User Guide?
I propose that they are not moved to the new User Guide pages.

**Comment by tharris** [comment]
The wiki isn't going away and we aren't in danger of losing any of the pages. Closing this ticket as there aren't any actionable items here.
