### ISSUE TITLE
How Do I ...?: I cannot see the sequence conservat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#1901]
I cannot see the sequence conservation tracks that we used to have.  How do I find them?

Reported by: Paul********** (worm****************)  (obscured for privacy)
Submitted From: Tools (/header)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:23.0) Gecko/20100101 Firefox/23.0

**Comment by epaule** [comment]
@tharris fixed the gbrowse-syn and we can also show halsnake tracks on the assembly hub (and PhastCons and PhyloP wiggles ... which we can pull into J/GBrowse).

Will create a separate ticket for updating gbrowse-syn to new alignment data
