### ISSUE TITLE
Display of GO term,  GO:0018987 

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#1940]
Hi,

On the GO term page:

http://www.wormbase.org/species/all/go_term/GO:0018987

The full term name is 'water homeostasis', but only 'water' is being displayed in the Overview.

Same is true of the display in GO section of this gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00004736

--Kimberly

**Comment by epaule** [comment]
looks like it was fixed in citace (and the script at Hinxton)
