### ISSUE TITLE
GBrowse for WS220 not working any more ?

### ISSUE THREAD

**Issue by gw3** [WormBase/website#1965]
Hello,

In order to synchronize the data analysis between several collaborators, we've agreed on working on a single genome build - CE10/WS220.
I realize it's not the latest build, but it's the most common one we have, with existing analysis already performed on this build.

Trying to view the "Data Freeze" for this build on "WormBase" gives an error.

visiting "http://ws220.wormbase.org/gb2/gbrowse/c_elegans/" gives:
---
"WormBase Server Error

We apologize, but a server error has just occurred. This is not your fault, and we would appreciate your informing us of this error. Please visit the Feedback Page to tell us the time and nature of the error, or return to the WormBase home page."
---

I'd like to ask if this is a temporary situation, and GBrowse/Workbase for WS220 will be fixed, or is this permanent?
If it permanent, is there a WormBase mirror which still hosts the "WS220" Browser?

Thank you,
 -gordon

**Comment by tharris** [comment]
I resurrected almost all of the frozen releases, including the WS220 genome browser.
