### ISSUE TITLE
RNASeq expression plot resolution scaling

### ISSUE THREAD

**Issue by gw3** [WormBase/website#1996]
This issue has been split away from #885 

When there are a set of points with a very high value (see AC3.3) the other values are all squashed down at the left of the scale. It would be good to have a scroll bar to dynamically zoom in to the lower end of the scale or otherwise rescale in some way, but @joejimbo says this is not easy to implement.

Maybe have a higher resolution image (or multiple resolutions)?

**Comment by tharris** [comment]
There has been considerable work on the FPKM images. I am closing this issue for now due to its age; relevant discussion should probably be continued on more current issues now.
