### ISSUE TITLE
Bug Report: when I go to the query builder > se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2034]
when I go to the query builder > select gene, select SUMMARY, i get the error below. It looks like it's looking for RNAi result. I think your mine doesn't have that and it's copied from flymine. Remove references to RNAi result from the webconfig-model.xml file.<br /><br />      org.intermine.pathquery.PathException: Unable to resolve path &#039;Gene.RNAiResult&#039;: field &#039;RNAiResult&#039; of class &#039;org.intermine.model.bio.Gene&#039; not found in model &#039;genomic&#039;<br />  at org.intermine.pathquery.Path.initialise(Path.java:217)<br /> at org.intermine.pathquery.Path.&lt;init&gt;(Path.java:161)<br />   at org.intermine.pathquery.PathQuery.makePath(PathQuery.java:1362)<br />    at org.intermine.web.struts.QueryBuilderChange.addToView(QueryBuilderChange.java:329)<br /> at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source)

Reported by: Juli\* (juli*************)  (obscured for privacy)
Submitted From: Tools (/header#anchor=Gene)

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:24.0) Gecko/20100101 Firefox/24.0

**Comment by chris-grove** [comment]
This has been fixed. Closing
