### ISSUE TITLE
WormMine : Lists

### ISSUE THREAD

**Issue by tuli** [WormBase/website#2126]
On http://www.wormbase.org/tools/wormmine/bag.do I select Type Strain and Organism C. elegans and enter VC40748, VC20646 in the Identifiers box. Hit Create List and I get  

"2 identifiers either i) did not match anything in the database, ii) matched a type that could not be converted to Strain or iii) did not match the selected Organism"

**Comment by chris-grove** [comment]
I will close this issue and make a more concise, updated ticket
