### ISSUE TITLE
Oligonucleotide sequence searches on GBrowse fail: not compatible with SeqFeature::Store

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2217]
When I search for a sequence in Landmark or region, I get this message:<br /><br />Internal Server Error<br /><br />The server encountered an internal error or misconfiguration and was unable to complete your request.<br /><br />Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.<br /><br />More information about this error may be available in the server error log.

Reported by: Juli********** (ja21***********)  (obscured for privacy)
Submitted From: Tools (/header)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:26.0) Gecko/20100101 Firefox/26.0

**Comment by scottcain** [comment]
Since it looks like this functionality will not be implemented for GFF3 databases, I'm closing this report.
