### ISSUE TITLE
: Why aren't the lesions of the allel...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2241]
Why aren't the lesions of the alleles shown in the genome browser (for the deletion mutants listed, which are available from the CGC)?  

Reported by: Juli*********\* (ja21***********)  (obscured for privacy)
Submitted From: set-2%20(gene) (/species/c_elegans/gene/WBGene00004782#0d9-634a8bc1f-10)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:26.0) Gecko/20100101 Firefox/26.0

**Comment by epaule** [comment]
as she hasn't replied for three years, I will close that one.
