### ISSUE TITLE
"Expand & Label" packing option for "ESTs (best)" GBrowse track displaying cramped labels

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#2483]
For the GBrowse track "ESTs (best)", when selecting the "Expand & Label" Packing option in the track configuration panel:

![screen shot 2014-03-04 at 3 17 15 pm](https://f.cloud.github.com/assets/611382/2327721/5ca3e4b2-a3f3-11e3-949c-139817ad40d7.png)

and selecting "Change" results in a cramped display of the EST names:

![screen shot 2014-03-04 at 3 17 01 pm](https://f.cloud.github.com/assets/611382/2327722/688fd128-a3f3-11e3-928b-10a5f9f3dd79.png)

**Comment by chris-grove** [comment]
@tharris 
I just pointed a user to GBrowse to visualize the coverage of a particular cDNA for a gene, but this issue still makes it difficult to see the different cDNAs clearly. Were we able to find a workable fix for this?
Thanks!

**Comment by tharris** [comment]
@scottcain Can you look into this?

**Comment by scottcain** [comment]
I hate this bug.  Yes, I'll see what I can do.

**Comment by scottcain** [comment]
@chris-grove and @tharris would it be ok if I spent time figuring out if I can add this functionality to JBrowse instead?  My recollection of how to work with BioGraphics is terrible (and I was never really that good at it to begin with).  I suspect I'd have better luck with JBrowse.

**Comment by chris-grove** [comment]
@scottcain 
Yes, that makes more sense. In fact, the JBrowse display of labels for cDNAs looks pretty good, except for the "Max height reached" bit:

http://www.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=II%3A7235302..7238784&tracks=Curated_Genes%2CESTs%20(best)&highlight=

Is there a way to expand the track so you can see everything?

**Comment by chris-grove** [comment]
@scottcain 
Ah, I figured it out, although we will need to explain to users how to expand the height of a track. I think JBrowse is a sufficient solution for this.

OK, let's close this #%^$ing ticket!  ;)

**Comment by tharris** [comment]
Come on! Emergent, dynamic display bugs are the most fun!

**Comment by scottcain** [comment]
OK, a few things: the bug in the GBrowse track is caused by "grouping", which is to say, the dashed lines that connect the 5' and 3' reads, so to really get this functionality reproduced in JBrowse, I'd have to figure out how to do that grouping (that's the thing that would take me a while).

On the other hand, making the track taller is easy--I just didn't realized that the height affected that track too.  I'll fix that shortly.

**Comment by chris-grove** [comment]
@scottcain 
Yes, that grouping (of 5' and 3' end reads) would be VERY helpful; I can make another ticket for that.

I also noticed that if I change the track height manually by editing the config file, none of the features link properly to their respective pages, even after changing the height back to the original:

https://www.dropbox.com/s/jh6p4q68l45wi24/JBrowse_bug_movie-links_to_cDNAs_break_after_resizing_track_height.mov?dl=0

I'll make a separate ticket for that as well.

**Comment by scottcain** [comment]
@chris-grove OK, I made the max height of the EST tracks much larger--I imagine in most cases it should be fine now.  If you dump the cache and reload you should see the change.

**Comment by chris-grove** [comment]
@scottcain 
Hmmmm, I just cleared my cache on both Firefox and Chrome and restarted each browser, but I'm still seeing the max height of 600 for the "ESTs (best)" track

**Comment by scottcain** [comment]
@chris-grove staging, right?

**Comment by chris-grove** [comment]
@scottcain 
OK, yes I see it on staging

**Comment by khowe** [comment]
Without wishing to go all 1990's you, I should point out that Fmap displays grouping of 5' and 3' pairs natively natively, based on the data that is already in Acedb. 

The GFF3 spec gives an example of how this information could be represented (and I say "could", because as ever, the spec is not prescriptive). See below. We do not currently represent our alignments in this way in our GFF3. But we could do that as a post-processing step. 

Another direction that might be worth exploring is to put the alignments in BAM files, which can represent paired alignments elegantly (the EST pairs are very much analogous to Illumina paired-end reads). 

ctg123 . cDNA_match  1200  9000  .        .  .    ID=cDNA00001
ctg123 . match_part  1200  3200  2.2e-30  +  .    ID=match00002;Parent=cDNA00001;Target=mjm1123.5 5 506;Gap=M301 D1499 M201
ctg123 . match_part  7000  9000  7.4e-32  -  .    ID=match00003;Parent=cDNA00001;Target=mjm1123.3 1 502;Gap=M101 D1499 M401

**Comment by chris-grove** [comment]
@khowe 
That's great, thanks! I'll add it to the ticket I created:

#5934

**Comment by scottcain** [comment]
@khowe I've often thought of putting ESTs in BAM files for a few reasons: presumably, the data in this track probably never changes (well, not anymore anyway) and the resulting BAM file would presumably be tiny and access very fast.  I'm not sure if we would lose anything going this route; the only thing "special" the EST track does is link to the feature page for the EST, and that can be done with the ID that would go into the BAM file.

**Comment by scottcain** [comment]
@chris-grove I'm fine with this being closed (actually, thrilled); I was just wondering if anybody knows where the "highest pile" of ESTs is, to see if the maxHeight parameter is sufficiently high.

**Comment by chris-grove** [comment]
@scottcain 
Right. I'll take a look and let you know. I'm imagining that the max height you set as default (5000) should be plenty, but I'll investigate.

**Comment by chris-grove** [comment]
@scottcain 
OK, so I was wrong that 5000 would be plenty in all cases. Looks like the gene ant-1.1 takes winner of the "has most matching cDNAs" contest at.... drum roll... 1,966 matching cDNAs:

http://www.wormbase.org/species/c_elegans/gene/WBGene00006439#0d--10

So far I've upped the JBrowse track height to 10,000 and that was still insufficient for this gene, and JBrowse is already responding very sluggishly. If I try to up the track height to 20,000 JBrowse essentially becomes unresponsive, although I'm still looking into it.

**Comment by chris-grove** [comment]
@scottcain 
OK, just tried 15,000 and JBrowse was still functional, albeit very slow, but still not sufficient for this gene. At this point I think it's pretty unrealistic to expect that any user is going to manually inspect these matching cDNAs using JBrowse, or any genome browser. So, we should probably just leave it at 5000 and call it a day. For these extreme cases, we'll need to offer users a different approach, or come up with some way to compress all these cDNAs in the genome browser view. It would probably be good if we could offer statistics on cDNA coverage for such large lists.

**Comment by chris-grove** [comment]
Ah, I found a gene with more cDNAs: eef-1A.1 (WBGene00001168) has 3,170 matching cDNAs

**Comment by scottcain** [comment]
I think you are right about 5000 being fine in most cases.  When a user wants to see more, I suspect they would want the raw GFF anyway.  In those cases, the "save track data" for the visible regions saves all the data, not just the visible data that got cut off by the max height, which is good.  So I say leave it as is (with 5000) and move on.
