### ISSUE TITLE
Improve readability of search results in WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2504]
On this page<br /><br />http://www.wormbase.org/tools/wormmine/keywordSearchResults.do?searchTerm=aap-1&searchSubmit=search<br /><br />the absence of white space, especially (but not only) between fields, and the use of bold text, both decrease readability.  

Reported by: Paul******\* (pker*************)  (obscured for privacy)
Submitted From: Tools (/header)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko) Version/7.0.2 Safari/537.74.9

**Comment by chris-grove** [comment]
I think this has been fixed with recent Intermine updates. Closing.
