### ISSUE TITLE
WS245 Clone Sequence link display changes.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#2712]
This issues about incorrect sequence display has come in a few times now and also leads to confusion for the user as we store different sequence connections under the same tag in the ?Clone model.

For WS245 I am proposing to move the sequenced read ends on the C. elegans Vancouver fosmid library to their own tag structure.

Not a finalised model:

```
?Clone  Evidence #Evidence
        Species UNIQUE ?Species
        Reference ?Paper XREF Clone
        Produced_by Person ?Person              // Paul D. WS244
                    Author ?Author              // Paul D. WS244
        Sequences Sequence ?Sequence XREF Clone
                  End_sequence ?Sequence XREF Clone_end_seq_read // New Tag for distinguishing between the full sequence and the end reads
```

This will require a small addition to the Overview widget
![fosmid_end_sequences](https://cloud.githubusercontent.com/assets/717707/2943869/5473ab26-d9ca-11e3-87e3-d434e0def05c.png)

This should help the web code be cleaner.

Thanks

Paul

**Comment by sibyl229** [comment]
Hi @Paul-Davis This is from a long time ago... So there is a link from the Sequence Overview back to the Clone: http://staging.wormbase.org/species/c_elegans/sequence/WRM0635aF10#04--10 And the Clone Overview displays only Corresponding sequence, while the Sequences widget has both Corresponding sequence and End reads: the http://staging.wormbase.org/species/c_elegans/clone/WRM0635aF10#04--10

**Comment by epaule** [comment]
not pretty, but functional
