### ISSUE TITLE
How Do I : submit meeting abstracts for inclusion in WormBase?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2854]
Dear WormBase People<br /><br />I am one of the organizers of the Evolution Worm Meeting 2014 which took place in Hinxton, Cambridge last month. We wondered how to best submit the abstracts to WormBase. Could you please contact Emily Rees from Welcome Trust Scientific Conferences (emily.rees@hinxton.wellcome.ac.uk) with instructions.<br /><br />Thank you very much,<br /><br />Adrian.<br />

Reported by: Adri********* (adri**************************)  (obscured for privacy)
Submitted From: home (/)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.76.4 (KHTML, like Gecko) Version/6.1.4 Safari/537.76.4

**Comment by tharris** [comment]
User query addressed. Considering this resolved.
