### ISSUE TITLE
Bug Report: LInks from BLAT does not go anywher...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2908]
LInks from BLAT does not go anywhere<br />T. suis protein

Reported by: Paul********** (worm****************)  (obscured for privacy)
Submitted From: blast_blat (/tools/blast_blat/run)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:30.0) Gecko/20100101 Firefox/30.0

**Comment by epaule** [comment]
we removed T.suis/A.suum and P.redivivus from WS249 onward (and S.ratti became a full-blown core species), so it should be fine in two weeks.
