### ISSUE TITLE
Searching SAGE tags in GBrowse

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2948]
Hi, I'm wondering if searching for SAGE tags works.  The links from GBrowse's SAGE tag track always seem to result in a 404 on the production site and it's not obvious to me from the main site how to search for SAGE tags.<br /><br />PS: I wanted to ask this from the main site just to see how it looks to users; thanks for bearing with me :-)

Reported by: Scot****** (scot**********)  (obscured for privacy)
Submitted From:  (/resources/sage/)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4

**Comment by tharris** [comment]
This is the sequence search, which I don't think was ever implemented for Bio::DB::SeqFeature::Store databases. I think this issue should be closed as it seems unlikely to ever be implemented at this point.

**Comment by scottcain** [comment]
I agree--it won't be fixed without somebody putting a significant amount of time in to writing BioPerl code.  Since the links were removed from the GBrowse config several months ago, I'll close this.
