### ISSUE TITLE
WormMine returns blank entries for "Gene > Transcripts > CDSs > Protein > Length" 

### ISSUE THREAD

**Issue by gw3** [WormBase/website#3066]
Note: ; there are some artifactual entries since WormMine returns blank entries for "Gene > Transcripts > CDSs > Protein > Length" for certain GPCR gene isoforms. It's not clear why. The full list of these is at the bottom of the message.

WormMine returns blank entries for "Gene > Transcripts > CDSs > Protein > Length" for these GPCR gene isoforms.

Gene > Transcripts > Sequence Name
F53F4.9b
F15A2.4
T04C12.2a
T04C12.2b
Y60A3A.4b
T04A11.12b
F14F8.5
C25F9.1d
W05B10.5b
T23D5.6
F10A3.8
C15H11.2b
C50H2.1b
C56A3.3d
F07B10.4a
F07B10.4b
R02D5.6d
R10E11.7
T10G3.4b
Y44A6B.2b
Y47D3B.1
Y81G3A.3a
Y81G3A.3b
Y116A8B.5
ZC412.1b
ZK1037.11
C03G6.13
C16D9.7
C48C5.1
Y9C9A.8
Y9C9A.15
Y39A3B.5e
Y39A3B.5f
Y55F3C.2
ZK418.6
C06B3.14

**Comment by epaule** [comment]
that looks like it has been fixed with the last WormMine update
