### ISSUE TITLE
Rethink permissions requested for login through Google 

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3169]
...register without going through Google or Facebook? When registering I only have these options, not a regular log in option.<br />John

Reported by: John******* (jpil******************)  (obscured for privacy)
Submitted From: password/email (/password/email)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36

**Comment by tharris** [comment]
Closing in favor of other issues tracking improvements to the system. Login via Google has been converted to Open ID Connect.
