### ISSUE TITLE
Hi,  I have 2 questions:   1) I'd like to download...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3205]
Hi,<br /><br />I have 2 questions:<br /> <br />1) I'd like to download the complete list of CB4856 variants from the WS240 release of WormBase. I couldn't see how to do this from WormMine, so I downloaded the WS240 GFF3 file and grep'd for CB4856. This gives several different classes (sources?) of polymorphisms and I'd like some description of what these are and which I should filter out in order to have the complete set of WS240 polymorphisms that I need:<br /><br />Allele_Polymorphism<br />CGH_Allele_Polymorphism<br />PCoF_Allele_Polymorphism<br />PCoF_CGH_Allele_Polymorphism<br />PCoF_Variation_Project<br />PCoF_Variation_Project_Polymorphism<br />Variation_Project<br />Variation_Project_Polymorphism<br /><br /><br />2) What are the raw sources of data for these CB4856 variants and can I download those?<br /><br /><br />Thank you very much,<br /><br />Greg<br />(Hobert Lab)<br /><br />

Reported by: Greg************ (gm21***************)  (obscured for privacy)
Submitted From: home (/)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36

**Comment by epaule** [comment]
was helped by
