### ISSUE TITLE
three new sets of ncRNAs for C. elegans

### ISSUE THREAD

**Issue by SchwarzEM** [WormBase/website#321]
Hi all,

WormBase currently contains ~9K ncRNA genes that were published as being of high confidence by the modENCODE Consortium, and then added to WormBase.  They were described in most detail here:

http://genome.cshlp.org/content/21/2/276.full

Over the last year, there's been three more studies published on intermediate-to-large C. elegans ncRNAs.  Two are from the laboratory of Runsheng Chen, and were published in March 2011 and February 2012:

http://nar.oxfordjournals.org/content/39/12/5203.long
http://rnajournal.cshlp.org/content/18/4/626.long

The third one was published by the Bartel lab just last week (6/15/2012) as a preprint:

http://genome.cshlp.org/content/early/2012/06/15/gr.140475.112.abstract

Possibly these data have already been submitted to WormBase -- the Bartel paper mentions having given its highest-confidence ncRNAs the gene names linc-* and anr-* -- but if they haven't been, they might be worth adding (at least as alternative ncRNA predictions like those for RNAz which WormBase already offers as alternative GBrowse tracks). In particular, I think it'd be useful if multiple ncRNA prediction sets existed in WormBase so that cross-comparisons of the ncRNA predictions became easier.

--Erich

**Comment by tharris** [comment]
Can we close this @Paul-Davis? I'm trying to clear out ancient tickets.

**Comment by Paul-Davis** [comment]
I have recorded the outstanding elements else where.
