### ISSUE TITLE
From the FAQ:  I'd like to create a diagram of a g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3212]
From the FAQ:<br /><br />I'd like to create a diagram of a genomic region similar to that shown on the Genome Browser. How can I do this?<br /><br />One approach is to write your own scripts in Perl using the Bio::Graphics modules that are part of BioPerl. <br /><br />---<br /><br />this seems unhelpful and also unnecessary, given you can directly the download the images from the site anyway. is it legacy advice from a long time ago?

Reported by: Paul******* (pker*************)  (obscured for privacy)
Submitted From: Frequently%20asked%20questions (/about/Frequently_asked_questions#54c3798eb2ad061--10)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10

**Comment by epaule** [comment]
that was for rendering your own custom gene models ... but it might be easier to just upload a custom track to your browser of choice.
