### ISSUE TITLE
Please create a molecule widget and show data.  

...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3218]
Please create a molecule widget and show data. <br />

Reported by: Kare****** (kare**************)  (obscured for privacy)
Submitted From: Unfolded%20protein%20response%20-%20ER%20(wbprocess) (/resources/wbprocess/WBbiopr:00000046#0-6754321a-10-06754)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:32.0) Gecko/20100101 Firefox/32.0

**Comment by epaule** [comment]
@kyook can we close that one?

**Comment by kyook** [comment]
Yes, we can revisit this later.
