### ISSUE TITLE
(From SAB): Is it possible to ensure that the side...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3221]
(From SAB): Is it possible to ensure that the sidebar always stays visible?

Reported by: Thom******* (thom********************)  (obscured for privacy)
Submitted From: home (/)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36

**Comment by sibyl229** [comment]
Fixed
