### ISSUE TITLE
The genetic information of the chromosome I defici...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3234]
The genetic information of the chromosome I deficiency eDf3 is not accessible.  All other Df's in this region open just fine. Thanks for your help.

Reported by: Stev************ (bios************)  (obscured for privacy)
Submitted From: eDf3%20(rearrangement) (/species/all/rearrangement/eDf3#0--10)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:31.0) Gecko/20100101 Firefox/31.0

**Comment by tharris** [comment]
It's choking on Mapping data. My guess is that one of the mapping experiments is a circular reference to eDf3 (or something along those lines). You might short circuit the mapping_data method incrementally to try and pinpoint the offending experiment.

**Comment by tuli** [comment]
I don't really know where to start hunting down the problem.

There are 40 pos_neg_data objects associated with this Deficiency. A quick
look shows that nothing has been newly added - though I suspect any problem
has existed for a while but has just not been spotted.

Is there anything I can do to locate the problem?



On 7 January 2015 at 19:35, Todd Harris <notifications@github.com> wrote:

> It's choking on Mapping data. My guess is that one of the mapping
> experiments is a circular reference to eDf3 (or something along those
> lines). You might short circuit the mapping_data method incrementally to
> try and pinpoint the offending experiment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3234#issuecomment-69078023>.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tharris** [comment]
I think it's a problem with the web code itself, particularly if the data hasn't changed. =

**Comment by sibyl229** [comment]
eDf3 Overview is working on production: http://www.wormbase.org/species/all/rearrangement/eDf3#0--10

**Comment by chris-grove** [comment]
@sibyl229 I still keep getting a time-out error on the eDf3 Overview widget on production

**Comment by tharris** [comment]
Should be fixed now.

**Comment by chris-grove** [comment]
@tharris yep! fixed, thanks
