### ISSUE TITLE
Tree Display Summary - strange link

### ISSUE THREAD

**Issue by tuli** [WormBase/website#3236]
I'm playing around a bit and have come across the following:

http://www.wormbase.org/tools/tree/run?name=WBGene00002457;class=Gene

Click on the WBGene within the top "WormBase Tree Display for Gene: WBGene00002457" and it tries to go to http://celeganskoconsortium.omrf.org/variation.aspx?allele=WBGene00002457 which of course is wrong.

**Comment by tharris** [comment]
Tested. Resolved. Closing.
