### ISSUE TITLE
Linking to ParaSite from WormBase

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#3311]
I've been having a think about the best way of linking to ParaSite from the main WormBase website.  At the moment, we only have the news story, which will drop off the main site once it reaches position #4.

We have come up with these as possible implementations:
1. Link in the black footer at the bottom
2. Static link to ParaSite homepage under one of the drop-down menus, e.g. "Species"
3. Dynamic menus (linking directly to the ParaSite species pages) under the "Species" drop-down, e.g. ParaSite --> Nematoda --> Clade I --> [List of species in Clade I]

My preference would be for something along the lines of #3, with the same navigation options as the grey expanding boxes on the ParaSite homepage.  I would be able to provide a XML file hosted on the ParaSite server from which the menu would be populated, so once the code has been implemented once, it will get updated automatically as ParaSite provide new releases.

**Comment by tharris** [comment]
This seems to be resolved. Am creating a new issue for deeper link of entities.
