### ISSUE TITLE
The Interactions section of pop-1 gene gave an err...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3353]
The Interactions section of pop-1 gene gave an error.

Reported by: Leon******** (leon******************)  (obscured for privacy)
Submitted From: pop-1 (/species/c_elegans/gene/WBGene00004077)

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by sibyl229** [comment]
Hi @tharris, it seems that **any page** that has a link to gene pry-1 times out on the proxy. For example, lin-39, pop-1, mig-1, and rearrangement eDf3. I also looked at a few genes whose interaction widgets are fine, and none of them interacts with pry-1.

I remember that pry-1 gene page was targeted by some attack and you blocked its URL. But it's still puzzling that it would have this kind of side effect :/ I don't think any of these pages sends request to the pry-1 url.

**Comment by sibyl229** [comment]
pop-1 interaction widget is working on production now: http://www.wormbase.org/species/c_elegans/gene/WBGene00004077#0-8-3

**Comment by chris-grove** [comment]
@sibyl229 I still keep getting a time-out error on the pop-1 Interactions widget on production

**Comment by sibyl229** [comment]
@chris-grove Ahh, sorry. The pry-1 page is getting thousands of visits again. I guess Todd has blocked the page, and it's affecting pages with links to pry-1.

**Comment by chris-grove** [comment]
@sibyl229  I see. That's such a weird phenomenon.

**Comment by tharris** [comment]
yes, the pry-1 gene page was targeted (it could have actually been any page on the site) for a ill-conceived redirect that would redirect ANY page it was passed even if it was not on the WormBase site.  I’ve now gotten more clever at blocking this specific traffic although it’s a bit of an arms race.

I still don’t understand why the pop-1 interactions widget is effected by this (it no longer is with the traffic shaping strategy I am using…)

**Comment by tharris** [comment]
Should be fixed now.

**Comment by chris-grove** [comment]
@tharris  OK, nice! It's working now.
