### ISSUE TITLE
gene display on staging

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3420]
http://staging.wormbase.org/species/b_malayi/gene/WBGene00233940

shows nothing in the sequences or location widget, also the RNASeq graph display is broken.

**Comment by tharris** [comment]
This is fixed in WS248 on staging now; it was partially resolved in WS247.

**Comment by epaule** [comment]
looks fine on staging.
Should we close the ticket or keep it open for 247?

**Comment by tharris** [comment]
I see no reason to keep it open.
