### ISSUE TITLE
...add a comment? I can see the place to type in a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3424]
...add a comment? I can see the place to type in a comment, but there is no submit button.

Reported by: Holl********* (hjoh************)  (obscured for privacy)
Submitted From: n1891%20(variation) (/species/c_elegans/variation/WBVar00090286#02-45b-4)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36

**Comment by epaule** [comment]
fixed by @sibyl229 last year
