### ISSUE TITLE
Rearrangement Summary - Overview - Strain table

### ISSUE THREAD

**Issue by tuli** [WormBase/website#3431]
http://www.wormbase.org/species/all/rearrangement/hDp36

Could the value in the Genotype column be changed so it populates the width of the column rather than line wrapping after only a few characters. It's quite hard to read. 

It's the same in Safari and Chrome. 

![screen shot 2014-12-01 at 12 54 02](https://cloud.githubusercontent.com/assets/1359170/5245951/47ad9a7a-795a-11e4-8c29-d7d613ef2c39.png)

**Comment by sibyl229** [comment]
Looks like this has been tested. Closing~
