### ISSUE TITLE
Distinguishing Interaction-based phenotypes from directly caused phenotypes in Phenotypes widget

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3432]
Attn @kyook  and @Gschindelman 

As discussed with Todd, we would like to make a distinction between phenotypes that are directly the result of RNAi or an allele versus those phenotypes that are indirectly caused or affected by some perturbation of the gene in the context of a genetic interaction (interaction-based).

@tharris  and I discussed two potential options:

1) Pull the genetic interaction phenotype data from the build of the interaction widget, modify the formatting, and redisplay in a slightly different format in a SEPARATE table in the Phenotypes widget which would be called something like "Interaction-based Phenotypes" with an indication of the Interaction (by ID), the interaction type, the phenotype, and the interaction remark

2) Instead of creating a separate interaction-based phenotypes table in the Phenotypes widget, there could be some indicator in the usual phenotypes table that the phenotype is interaction-based. This could be done with highlighted rows indicating interaction-based phenotypes and/or a column header that indicates "Interaction-based" in which each phenotype that is derived from an interaction has some sort of Boolean True/False entry like "Interaction-based" or "True", etc.

It should be added that any RNAi objects that had been redundantly created with a genetic interaction object should be purged from the curation databases as they are no longer necessary.

**Comment by sibyl229** [comment]
Hi @chris-grove and @kyook Is this the interaction-based phenotype table you are looking for? The Remark tag on an Interaction seems to be sparsely populated, do you want it shown here as a separate column? Does any citation need to be shown? Thanks!

**Comment by chris-grove** [comment]
@kyook Apologies; I never responded, this fell through the cracks
@sibyl229  I love it!! I think it looks really good as you have it. I don't think the Remark needs to be shown. As for citation, it's already there. Maybe I'm missing something?

**Comment by kyook** [comment]
Hi @sibyl229, I agree with @chris-grove. It looks very nice and clean!  One minor point though, is it possible to collapse the citations to only show one unique citation? For example for the eight interactions that have the same phenotype of engulfment variation all come from the same reference,  it might make the display a little cleaner.  I can understand if this is not doable, and it is certainly low priority. 
Thanks again for your help.

**Comment by chris-grove** [comment]
@sibyl229 @kyook  I'm going to close this issue and open another ticket for the compaction of citations as I think the original ticket issue has been resolved. Thanks Sibyl!!
