### ISSUE TITLE
How do I get the list of all the human homologs fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3462]
How do I get the list of all the human homologs for C. elegans. <br /><br />I went to the ftp server and the latest release but not sure which file is the one for the compared homology. <br /><br />Thanks a lot<br /><br />Best Wishes,<br />Aneet

Reported by: Anee* (anee******************)  (obscured for privacy)
Submitted From: home (/)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

**Comment by brucebolt** [comment]
User has responded directly to me asking if it is possible to get the human orthologues of a short list of C. elegans genes.  They have done this using WormMart WS220, but would like more up to date data.

As far as I can see, this is not possible using the current implementation of WormMine.

The download file I suggested in a previous email contains the data, but as the data for each gene runs over several lines, it isn't necessarily the simplest file to work with (e.g. a simple grep -f against a file of gene names would not give particularly useable results).  In this case, the user has attempted to tabulate the data themselves in Excel so they can use the built-in search function.

**Comment by epaule** [comment]
you could point them to the EnsMart, as it just has been updated with WS235
data, and Thomas has a very quick way to pull it from the database.

**Comment by tharris** [comment]
I'm assuming this is resolved and so am closing...
