### ISSUE TITLE
Hi, Not sure under what category to report this (e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3478]
Hi,<br />Not sure under what category to report this (eventually decided to frame it as a request for a content correction).<br />The lin-15 locus (as lin-15, lin-15A, or lin-15B) has issues: there's a page for "lin-15" that explains the situation, and a page for lin-15A, but not obviously a page for lin-15B, and there's no Genetic Position and no link to the Genome Browser, although of course the coordinates are known.<br /><br />Thanks! And Happy Holidays!

Reported by: Hill*********** (hill*********************)  (obscured for privacy)
Submitted From: lin-15%20(gene) (/species/c_elegans/gene/WBGene00003004#0a-9e1c6db4j5-10)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by tharris** [comment]
This is just one of those issues that keeps coming up again and again with no obvious resolution that satisfies all parties or database requirements.

I'm closing the report here, in reference to other tickets that discuss this exact same issue (#3486)
