### ISSUE TITLE
using 'lin-15b' as a search term brings the user t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3485]
using 'lin-15b' as a search term brings the user to a page of 550+ search results.  Using 'lin-15B' however, correctly places the user on the lin-15B page. Case does seem to matter for lin-15A- both  'lin-15a' goes to the lin-15 page; when it shouldn't

Reported by: Kare****** (kare**************)  (obscured for privacy)
Submitted From: lin-15b%20-%20search (/search/gene/lin-15b)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by sibyl229** [comment]
Hi @kyook the lin-15a and lin-15b gene search should redirect to the right page now.

**Comment by kyook** [comment]
Hi @sibyl229, it works like a charm!  Thanks!
