### ISSUE TITLE
n765 affects lin-15A, even though it doesn't molec...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3487]
n765 affects lin-15A, even though it doesn't molecularly map to lin-15A, genetically, it is considered an allele of lin-15A.  This aspect of these alleles has been brought up before, perhaps it is something that we can discuss again in order to reflect the community knowledge for alleles like these.  

Reported by: Kare****** (kare**************)  (obscured for privacy)
Submitted From: n765%20(variation) (/species/c_elegans/variation/WBVar00089736#026-45-5-4)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by tuli** [comment]
I have removed n765 from lin-15. It is associated with lin-15A and lin-15B.
