### ISSUE TITLE
Can't sign in

Reported by: Robe*********** (Robe*...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3506]
Can't sign in

Reported by: Robe*********** (Robe*************************)  (obscured for privacy)
Submitted From: home (/)

Mozilla/5.0 (PlayStation 4 2.03) AppleWebKit/537.73 (KHTML, like Gecko)

**Comment by kyook** [comment]
Don't see person's name or e-mail, so can't follow up.
