### ISSUE TITLE
For two different anatomic expression patterns and...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3509]
For two different anatomic expression patterns and I have only attempted to look at two (I am on apr-1 right now) For this one, in expression patterns I clicked on Expr4600 picture icon, got the 4 panel miniature that you cannot see anything on and when I click on the micro figure to enlarge it to view it - as I did in the past - it now sends me to another page saying that the picture is not available!   This also happened for the other one but I was looking at an expression profile graph  but I do not remember which gene I was looking at then. Can you check into it for me?  Thanks!  Laura 

Reported by: Laur************ (biol**************)  (obscured for privacy)
Submitted From: apr-1%20(gene) (/species/c_elegans/gene/WBGene00000156#01--10)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by sibyl229** [comment]
Hello Laura,

Thanks for bringing this up. The failure to access the enlarged image is definitely a bug, and it affects many expression profile graphs. 

A temporary solution would be to visit the Expression Pattern page (follow the link is above the picture icon). Click on the thumbnail image in the Overview widget, wait until a pop up window opens, then click on the thumbnail image in the pop up - this will take you to the full image. This is more complicated than it should be, but for now it’s the only workaround that I know of. Sorry for the inconvenience.

I will fix it for the WS247 WormBase website release, as the development for WS246 has been completed/frozen. The WS247 release will be out in approximately 2 months.

Please let me know if there’s any confusion.

Sibyl

**Comment by draciti** [comment]
Thanks sibyl!
