### ISSUE TITLE
Cite information on a gene? 

Reported by: Soud***...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3511]
Cite information on a gene? 

Reported by: Soud************* (soud***********************)  (obscured for privacy)
Submitted From: home (/)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by tuli** [comment]
Dear Soudabeh,

Thank you for writing to WormBase.

Please can you give us a little more information as to what exactly
you are trying to do.

Is there a specific gene you are interested in?

Thank you,

Mary Ann



~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Will open again if user responds.

**Comment by tuli** [comment]
Personal communication with user. Helped her and she is very happy.
