### ISSUE TITLE
Hi there, I just noticed from the lab code tweet f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3512]
Hi there,<br />I just noticed from the lab code tweet for my lab that there is old/incorrect info. Strangely, the info is correct for my person page (Asher D. Cutter), but not the corresponding lab code page (VX). Namely, could you please update the VX page info for...<br />email should be: asher.cutter@utoronto.ca<br />lab webpage should be: http://labs.eeb.utoronto.ca/cutter<br /><br />thanks,<br />Asher

Reported by: Ashe******** (ashe******************)  (obscured for privacy)
Submitted From:  (/resources/person/WBPerson1712)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by tuli** [comment]
Hi Asher,

Thank you for bringing this to our attention.  I have updated the
email address and the URL of your website in the VX Laboratory
objects. The update will be available in release WS247 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
