### ISSUE TITLE
  Two widgets on this page (Overview an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3513]
<p>&nbsp;&nbsp;Two widgets on this page (Overview and Sequence) give "Internal Server Error".  Both widgets seem to be fine on staging so not obvious what has gone wrong.</p>

Reported by: thom********************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by dasmoth** [comment]
Sorry, thought the URL would be captured by the issue submission system, but apparently didn't happen in this case.  The page I was looking at is:

      http://www.wormbase.org/species/c_elegans/pcr_oligo/GPL14144_F26C11.1_1121-1180_0.948_1_A#0231--10

**Comment by tharris** [comment]
You have to be submit from the page These two examples are fixed. I'm checking to see how widespread the issue may be.
