### ISSUE TITLE
  I am trying to find the sequence for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3516]
<p>&nbsp;&nbsp;I am trying to find the sequence for the dop-6 CDS (C24A8.1); It says an internal server error has occurred. </p>

Reported by: tjed******************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by tharris** [comment]
Fixed and user contacted.
