### ISSUE TITLE
  let-363 (CeTOR) is currently listed a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3517]
<p>&nbsp;&nbsp;let-363 (CeTOR) is currently listed as let-603 in WS246.  I assume this is an error?  If not, there will be contradictions in the literature, so perhaps not a good idea. I'll let you folks sort it out. :)  Cheers,<br/>Dave R</p>

Reported by: Dave******* (worm*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by tuli** [comment]
Mary Ann looking at with Tim

**Comment by kyook** [comment]
This appears to have been dealt with- 

Tim Schedl <ts@genetics.wustl.edu>
1/8/15

to wormboy2000, WormBase: 
Hi Dave,

Thank you for contacting WormBase and bringing to our attention the issue with gene names let-363 and let-603.  

The primary gene name for B0261.2 has been restored back to let-363, which is the name known by the community for the worm TOR ortholog, with let-526 and let-603 listed as other names.  

Thanks,

Tim
