### ISSUE TITLE
  Hi there, I am looking at the protein...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3518]
<p>&nbsp;&nbsp;Hi there, I am looking at the protein isoforms of sas-5. Could you tell me what the data is for the alternative translation start site leading to the production of sas-5 isoform c? <br/>Thanks for your help!</p>

Reported by: N Br*** (nico****************)  (obscured for privacy))
Submitted From: F35B12.5a (transcript) <a href="http://www.wormbase.org//species/c_elegans/transcript/F35B12.5a#043--10">/species/c_elegans/transcript/F35B12.5a#043--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by gw3** [comment]
Nicola,

The alternative translation start site leading to the production of 
sas-5 isoform c is based on the SL1 sites (defined as the Features 
WBsf130780 and WBsf966185).

These two SL1 sites are based on RNASeq reads which start with at least 
8 bases of the SL1 trans-spliced leader sequence and the rest of the 
RNASeq read are then mapped to the genome at these two positions. The 
first SL1 site (WBsf130780) has 78 reads (which is a comparatively large 
number of reads for SL1 sites). The second site (WBsf966185) does not 
have a lot of evidence: it only has 2 RNASeq reads supporting it.

The SL1 sites both give transcripts that are trans-spliced after the 
first intron of the full-length transcript.

This trans-spliced transcipt has a initiation (START) codon in the 
second exon of the trans-spliced transcript. I used this initiation 
codon to start the CDS structure F35B12.5c which produces sas-5 isoform c.

Gary Williams
WormBase
