### ISSUE TITLE
  How do I enter a list of genes and ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3520]
<p>&nbsp;&nbsp;How do I enter a list of genes and generate a list of all tissue expression data (specifically, what tissues show expression) for each gene?<br/>Thanks!</p>

Reported by: Aile** (asew****************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#--6">/#--6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10

**Comment by draciti** [comment]
Hi Aileen

you can use WormMine to do that.
Go to the Wormbase home page, click on tools, WormMine

once you are on the WormMine page go to Analyze a list. Put in the list of genes you are interested in, click on Analyze, click on 'save the list of your genes'.

you will see a table. Click on Manage columns on the top left side. Click on add a new column -> expression patterns -> anatomy terms-> Name

Do it again if you want to include Life stages

Add a new column expression patterns -> life stages -> Public name

let me know if you have any questions

Daniela

**Comment by draciti** [comment]
Hi Aileen

you can use WormMine to do that.
Go to the Wormbase home page, click on tools, WormMine

once you are on the WormMine page go to Analyze a list. Put in the list of genes you are interested in, click on Analyze, click on 'save the list of your genes'.

you will see a table. Click on Manage columns on the top left side. Click on add a new column -> expression patterns -> anatomy terms-> Name

Do it again if you want to include Life stages

Add a new column expression patterns -> life stages -> Public name

let me know if you have any questions

Daniela

**Comment by draciti** [comment]
Hi Aileen

you can use WormMine to do that.
Go to the Wormbase home page, click on tools, WormMine

once you are on the WormMine page go to Analyze a list. Put in the list of genes you are interested in, click on Analyze, click on 'save the list of your genes'.

you will see a table. Click on Manage columns on the top left side. Click on add a new column -> expression patterns -> anatomy terms-> Name

Do it again if you want to include Life stages

Add a new column expression patterns -> life stages -> Public name

let me know if you have any questions

Daniela

**Comment by draciti** [comment]
user's happy
Excellent, thank you!
Aileen
