### ISSUE TITLE
Phenotypes show as HASH in search index snippets

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3528]
Search for a RNAi, e.g. 

http://www.wormbase.org/search/all/WBRNAi00093999

In the resulting SERP, some (but not all) phenotypes names are being displayed incorrectly.

![image](https://cloud.githubusercontent.com/assets/209047/5680881/cb6e278e-980a-11e4-9458-412099fd476c.png)

(A quick look at the underlying Phenotype objects doesn't give me any immediate clues as to why some get proper names and others get HASH(...) strings -- possibly a caching issue somewhere...?)

**Comment by sibyl229** [comment]
Thanks @dasmoth. I found it quite puzzling for a while too. It's fixed now: http://staging.wormbase.org/search/all/WBRNAi00093999 There were actually two bugs: fetching phenotype name by ID alone (without a class) isn't sensitive, when it fails to find an exact match, it produce a hash that are handled poorly by the template code. Should be good now. Thanks for letting me know =)

**Comment by dasmoth** [comment]
Looks good to me.
