### ISSUE TITLE
  External links to Neuralnet requires ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3529]
<p>&nbsp;&nbsp;External links to Neuralnet requires a "#" before "c=..." in the URL.<br/>"#" is encoded as "%23" but that doesn't seem to be interpreted correctly by wormweb.org.<br/>example: <http://www.wormbase.org/species/all/anatomy_term/WBbt:0004003>.</p>

Reported by: Raym******* (raym****************)  (obscured for privacy))
Submitted From: ADFL (anatomy_term) <a href="http://www.wormbase.org//species/all/anatomy_term/WBbt:0004003#0342--10">/species/all/anatomy_term/WBbt:0004003#0342--10</a>

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by raymond91125** [comment]
wormbase.org does not translate %23 to # either. c.f.
[URL with %23 ](http://www.wormbase.org/%23)
[URL with # ](http://www.wormbase.org/#)

**Comment by raymond91125** [comment]
it works! thanks.
