### ISSUE TITLE
  I'd like to get a gff file of current...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3530]
<p>&nbsp;&nbsp;I'd like to get a gff file of current annotations of transcripts.  I found the gff3 file for the whole release - is there a gff file somewhere that just has transcripts?<br/>Thanks, Julie</p>

Reported by: Juli********** (ja21***********)  (obscured for privacy))
Submitted From: magi-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00010444#0ad5e7cfb4--10">/species/c_elegans/gene/WBGene00010444#0ad5e7cfb4--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by chris-grove** [comment]
Hi Julie, 

It is straightforward to extract specific feature types from the master GFF3. Furthermore, slicing up the GFF3 by feature type would create a proliferation of files on the FTP site and make it more difficult for users to find what they are looking for. For these reasons, it has been our policy (up to now) to only provide the single, master GFF3 file. 

However, I have to admit that you are not the first person to ask for the canonical gene set to be provided in its own file. And it could be argued that the majority of people downloading the GFF are after the genes and transcripts, so we should provide them with an easy/quick way of getting that (and just that). We'll discuss providing that from our next release. Until then, you can extract the canonical gene set from the master GFF as follows:

gunzip -c c_elegans.PRJNA13758.WS245.annotations.gff3.gz | awk '$2 == "WormBase"'  

Best wishes, 

Kevin
