### ISSUE TITLE
  For bli-1, is it known whether this m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3532]
<p>&nbsp;&nbsp;For bli-1, is it known whether this mutant can mate properly?</p>

Reported by: Youn***** (yyoo************)  (obscured for privacy))
Submitted From: bli-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00000251#0-9e17-10">/species/c_elegans/gene/WBGene00000251#0-9e17-10</a>

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)

**Comment by raymond91125** [comment]
Hi Young,

C. elegans I has ME2 (mating efficiency) for bli-1 (if you click on 
"From C. elegans I and II"). Thus one could mate with it. In general, 
it's a number's game: try many and you'll get some to work.

You may also pose this question to the forum to see if anyone has 
personal experience to comment of.

Good Luck.

Raymond


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
