### ISSUE TITLE
  Is there any information on whether d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3533]
<p>&nbsp;&nbsp;Is there any information on whether dpy-10 can mate properly?</p>

Reported by: Youn***** (yyoo************)  (obscured for privacy))
Submitted From: dpy-10 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00001072#0-9e-3">/species/c_elegans/gene/WBGene00001072#0-9e-3</a>

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)

**Comment by chris-grove** [comment]
Hello Young, 
 
 As my colleague Raymond mentioned for bli-1, you can find mating efficiency (ME) scores under the "From C. elegans I and II" section of the Overview widget on a gene page. It seems that dpy-10 has a mating efficiency score of ME1, suggesting that it is likely very difficult (but not impossible) to mate.

Best,

Chris Grove
