### ISSUE TITLE
  Needing to know vab-1 isoform A codin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3534]
<p>&nbsp;&nbsp;Needing to know vab-1 isoform A coding sequence. Query informs on an internal server error.</p>

Reported by: cory********************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by chris-grove** [comment]
Confirmed:
![screen shot 2015-01-12 at 2 37 42 pm](https://cloud.githubusercontent.com/assets/611382/5712618/d52354c4-9a68-11e4-8b74-7676f3f1d6a0.png)

Clicking on the sequence icon for the CDS of vab-1 isoform a gives an error.

**Comment by chris-grove** [comment]
Hello Cory,

 Thanks for reporting the error. Our web team will look into it.

In the meantime I've attached a text file with the VAB-1 isoform A coding
sequence (the open reading frame). Please let us know if you need anything
else.

Best,

Chris Grove

**Comment by draciti** [comment]
Todd, there is also this issue related to sequences not loading -same as for ccm-3. ccm-3 is working fine for me but vab-1 still gives an error

**Comment by sibyl229** [comment]
Hi @draciti and @chris-grove the CDS for ccm-3 and vab-1 are working now. I have applied the general fix to this type of problem, that will be in the WS247 web release. For now, I probably have to fix them individually, by deleting the cache for these broken widgets.

**Comment by chris-grove** [comment]
Yep, looks good @sibyl229
