### ISSUE TITLE
  Can I order c. Elegans that model spi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3535]
<p>&nbsp;&nbsp;Can I order c. Elegans that model spinocerebellar ataxia?</p>

Reported by: Hill*** (Hill*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53

**Comment by chris-grove** [comment]
Hello Hillary,
C. elegans atx-2 and atx-3 are orthologs of human ataxin 2 and 3,  genes implicated in spinocerebellar ataxia, you can look on the gene pages of atx-2 and atx-3 in WormBase, and see strains and allele information in the ‘Genetics’ widget, you can browse these, and see which one suits your purposes best.  When you click on the strain, you can see ordering information on the Strain report page.  There is also a list of strains under the ‘Strains’ heading under the 'Polymorphisms & Natural variants’ table for atx-3.
 
I would also look at the publications for atx-2 and atx-3 as they may not model all the phenotypes of human spinocerebellar ataxia, for example in elegans, atx-2 is involved in  embryonic patterning and germline proliferation.

Hope this helps
Ranjana Kishore
WormBase
