### ISSUE TITLE
  How do I run an older release of worm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3539]
<p>&nbsp;&nbsp;How do I run an older release of wormbase? Thanks</p>

Reported by: Kons*************** (kkag*******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by xdwang** [comment]
In the bottom section of wormbase homepage, there is a 'Data Freezes' box. You can choose the older release from dropdown list. It will take you to wormbase legacy site of the release of your choice. Let us know if you need further help.
