### ISSUE TITLE
Interactions widget not loading on lin-12 gene page on staging or live site

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3540]
Widget is timing out:

![screen shot 2015-01-13 at 5 20 21 pm](https://cloud.githubusercontent.com/assets/611382/5732539/801c4dce-9b48-11e4-94c6-a975e83fee6b.png)

**Comment by chris-grove** [comment]
same problem on egl-20 gene page

**Comment by tharris** [comment]
Fixed in WS247.

**Comment by chris-grove** [comment]
Looks good, thanks @tharris
