### ISSUE TITLE
  Hello, I´m new in this model and I do...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3541]
<p>&nbsp;&nbsp;Hello, I´m new in this model and I don´t have any  idea, how I can  know about my interest gene, that is Lin35/rb, because, when I put  the name of the gene alwas said me that  there are no match for my gene, there are avaliable some instructions?</p>

Reported by: Alan********** (al@c***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36

**Comment by tuli** [comment]
Dear Alan,

Thank you for writing to WormBase. The gene you are interested in is named
lin-35 in WormBase and can be seen here:
http://www.wormbase.org/species/c_elegans/gene/WBGene00003020

For nomenclature in nematodes I suggest you read our Nomenclature
guidelines: http://www.wormbase.org/about/userguide/nomenclature

Please let us know if you have more questions.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
