### ISSUE TITLE
WS247 Primary data bugs

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#3542]
Data conflicts when dumping from the primary databases I think these are just for me ( @paul-davis ) and @tuli 

dumping Gene from /nfs/wormpub/BUILD/PRIMARIES/geneace
Gene_info	  Allele  "WBVar02141311"  Paper_evidence  "WPaper00045601" 
 contains invalid WBPaper_evidence

Gene_info	  Allele  "WBVar02141310"  Paper_evidence  "WPaper00045601" 
 contains invalid WBPaper_evidence

dumping Variation from /nfs/wormpub/BUILD/PRIMARIES/geneace
Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/geneace/geneace_Variation.ace
Variation : "WBVar02125778"
Reference WBPaper000412219

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/geneace/geneace_Variation.ace
Variation : "WBVar02125780"
Reference WBPaper000412219

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/geneace/geneace_Variation.ace
Variation : "WBVar02141310"
Reference WPaper00045601

Evidence	  Paper_evidence  "WPaper00045601" 
 contains invalid WBPaper_evidence

Sequence_details	  Type_of_mutation  Substitution  "g"  "a"  Paper_evidence  "WPaper00045601" 
 contains invalid WBPaper_evidence

Evidence	  Paper_evidence  "WPaper00045601" 
 contains invalid WBPaper_evidence

Sequence_details	  Type_of_mutation  Substitution  "c"  "t"  Paper_evidence  "WPaper00045601" 
 contains invalid WBPaper_evidence

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/geneace/geneace_Variation.ace
Variation : "WBVar02141311"
Reference WPaper00045601

dumping CDS from /nfs/wormpub/BUILD/PRIMARIES/camace
Properties	  Isoform  Paper_evidence  "WBpaper00026850" 
 contains invalid WBPaper_evidence

**Comment by Paul-Davis** [comment]
Added the CDS Isoform evidence in autoace as it had beed stripped out, and patched the primary for WS248

**Comment by tuli** [comment]
I don't know what the problem with WBPaper00045601 is. It appears in http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/generic.cgi?action=WpaXref & http://tazendra.caltech.edu/~postgres/cgi-bin/paper_editor.cgi?

**Comment by tuli** [comment]
Fixed the other problem (WBPaper000412219) @Paul-Davis, I will send you a patch for this.

**Comment by Paul-Davis** [comment]
no but there is a problem with WPaper00045601 note no W"B"Paper

**Comment by tuli** [comment]
Ah ha. Another patch in /PATCHES

**Comment by Paul-Davis** [comment]
I think these were all resolved for the release of WS247
