### ISSUE TITLE
  Hi, just a quick question. Is there a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3543]
<p>&nbsp;&nbsp;Hi,<br/>just a quick question. Is there any place in wormbase where I can check whether each specific mutation on a gene predicts a deletereous mutation?</p>

Reported by: Paol******** (paol*******************)  (obscured for privacy))
Submitted From: C18A3.1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00015939#0d4-9e6b817fac-10">/species/c_elegans/gene/WBGene00015939#0d4-9e6b817fac-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by epaule** [comment]
if you go to the "genetics" section of the gene page, you will see a table with all curated variations.
In that table you can also sort the data by "effect" and "location", by clicking on the light-blue arrows.

We do not classify "deleterious", but we do classify "premature stops" and "frameshifts". In addition large deletions covering the coding exons of the gene should also affect the functionality.

You can also sort by the number of observed phenotypes, but that depends on where you would hope to see changes if the function of the protein was changed.
