### ISSUE TITLE
  I was trying to look at the DNA seque...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3544]
<p>&nbsp;&nbsp;I was trying to look at the DNA sequence of ccm-3 (C14A4.11), but it would not load. Saying "internal server error". <br/>The protein sequence loads fine. </p>

Reported by: scma**************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by draciti** [comment]
Hi,
thanks for reporting the issue.
Our webteam will look into the problem as soon as possible. You can follow the progress on github here https://github.com/WormBase/website/issues/3544

Daniela

**Comment by draciti** [comment]
Can reproduce the error

![screen shot 2015-01-14 at 9 59 24 am](https://cloud.githubusercontent.com/assets/901243/5744303/6d6f16a2-9bd4-11e4-87ed-29b90ced46b5.png)

**Comment by tharris** [comment]
Resolved.

**Comment by draciti** [comment]
thanks Todd
