### ISSUE TITLE
"Default" Page settings button selecting "Overview", "Location", and "Sequence features" widgets

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3545]
Is that right? It used to be the "Sequences" widget instead of the "Sequence features" widget

**Comment by sibyl229** [comment]
Ah, the default widgets are identified by a position key. That was messed up, when Sequence Feature widget is added. It's fixed now on staging. Thanks @chris-grove

**Comment by chris-grove** [comment]
OK looks good. Thanks @sibyl229 !
