### ISSUE TITLE
  Two questions. Tim Schedl approved th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3548]
<p>&nbsp;&nbsp;Two questions. Tim Schedl approved the name fitm-2 for gene ZK265.9. Has he communicated that to WormBase?<br/>I cannot login and would love some help. The password I have written down does not work for my email address: andyg@mail.nih.gov.<br/>thanks!</p>

Reported by: Andy******* (andy**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4

**Comment by tuli** [comment]
Dear Andy,

Regarding your question about the fitm-2 gene. I can confirm that this has
been added to WormBase and will appear in release WS247.

Someone from the webteam will be along to answer your password query.

Best wishes,

Mary Ann
WormBase

On 14 January 2015 at 22:21, Golden, Andy (NIH/NIDDK) [E] <
AndyG@intra.niddk.nih.gov> wrote:

> I got this email when I asked to reset my password, and then got a message
> that this link expired.
>
>
> Thank you for using WormBase!
>
> To reset your password, please click on the following link:
>
> https://www.wormbase.org/password/index?id=6CBE8884-9C3B-11E4-8CA0-F46B8BAEB934
>
> Thank you,
>
> The WormBase Consortium
> help@wormbase.org<mailto:help@wormbase.org>
>
>
>
> How can I reset my password since the old one no longer works.
>
> Thanks so much!!
>
> Andy
> -----------------------------------------------------------
> Andy Golden
> Laboratory of Biochemistry and Genetics
> NIDDK/NIH
> 8 Center Drive, MSC 0840
> Building 8, Room 323
> Bethesda, MD 20892-0840
> 301-594-4367 (office)
> 301-402-0053 (fax)
>
> http://www.niddk.nih.gov/about-niddk/staff-directory/intramural/andy-golden/pages/research-summary.aspxcan
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by draciti** [comment]
Hi Andy, 

yes fitm-2 is an approved name for ZK265.9 and Wormbase is aware of that.

Somebody from the webteam will get back to you regarding login issues asap
thanks,

Daniela

**Comment by sibyl229** [comment]
Hi Andy,

Sorry about the problems. The WormBase site is having problems with
password login, and we are working on a solution for it.

In the mean time, the alternative is to use the sign in with Google option,
and it will create a new account for you, and allow you to save Favorite
and browsing history. Data stored with your old account won't be accessible
for now, but we are working on a way to merge accounts, that will bring
those data into your new account.

We are in the process of replacing our current login method with Sign in
with Google. This will make the integration with WormMine, another service
that we provide, easier.

Sorry again about the difficulty. Please let me know if there's any other
problem.

Sibyl

**Comment by draciti** [comment]
Sybil, can I close this one or you want to keep it open for the login issue?

**Comment by sibyl229** [comment]
Hi @draciti could you leave it open for now?

**Comment by draciti** [comment]
sure sibyl, thanks

**Comment by raymond91125** [comment]
@sibyl229 should this have a assignee?

**Comment by epaule** [comment]
@sibyl229 do you want to keep it open?

**Comment by sibyl229** [comment]
Thanks @epaule. I will close the issue as password reset for existing account works fine now.
