### ISSUE TITLE
  Hello, I have had a small problem wit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3550]
<p>&nbsp;&nbsp;Hello,<br/>I have had a small problem with my genome browser since Christmas - the 'landmark' row for the chromosome no longer shows any annotations, making it unusable to perform quick searches for genes linked to a gene of interest. I use a Mac, with OSX 10.9.5 installed (Mavericks), and have tried using Safari, Firefox and Chrome, all with the same result. I have tried readjusting the presentation of 'landmarks' using the preferences given, and also zooming in on my web browser, but nothing seems to make the annotations come back.<br/>I use this feature frequently, so would be very grateful if anything could be done about this.<br/>Best wishes,<br/>Sophie</p><p>What were you doing? <br />&nbsp;&nbsp;Looking for a gene linked to unc-119 on LGIII.</p>

Reported by: Soph********** (soph*************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by sibyl229** [comment]
Hi Sophie,

Sorry about the problem! Our genome browser expert is looking into it, and will contact you ASAP when it’s fixed. 

Thanks for letting us know.

Sibyl
