### ISSUE TITLE
  I cannot access to the sequence of th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3553]
<p>&nbsp;&nbsp;I cannot access to the sequence of the gene rib-2.<br/>It is the second day that i am trying and I don't know why.<br/>Could you fix that?<br/>Thanks</p>

Reported by: Alba******** (alba*******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by chris-grove** [comment]
Confirmed; CDS sequence icon button throwing error. Other buttons OK:

![screen shot 2015-01-15 at 10 29 33 am](https://cloud.githubusercontent.com/assets/611382/5763804/50ee777e-9ca2-11e4-9c22-b56de318afc4.png)

**Comment by chris-grove** [comment]
Hello Alba,

 Sorry for the inconvenience and thank you for reporting the error. The problem has been reported to our web team. I can see the problem with the sequence button under CDS (right arrow, attached screenshot) but the "Transcript" sequence button should work fine (left arrow, screenshot).

Let us know if you still have trouble and we can send you the sequence directly.

Best,

Chris Grove

**Comment by sibyl229** [comment]
Hi @chris-grove some caching issue affected that specific CDS sequences widget. It's fixed on production now: http://www.wormbase.org/species/c_elegans/gene/WBGene00004361#f--10

**Comment by chris-grove** [comment]
Thanks @sibyl229 , looks good
