### ISSUE TITLE
  Dear People at WormBase I would appre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3554]
<p>&nbsp;&nbsp;Dear People at WormBase<br/>I would appreciate very much if you could include the following publications on my WBPerson page, although they are not C. elegans (but nematode) papers.<br/>Hildebrandt, J. C., Eisenbarth, A., Renz, A. and Streit, A. (2014). Reproductive biology of Onchocerca ochengi, a nodule forming filarial nematode in zebu cattle. Veterinary Parasitology 205, 318-329.<br/>Streit, A. (2014). How to become a parasite without sex chromosomes: a hypothesis for the evolution of Strogyloides sp. and related nematodes. Parasitology 141, 1244-1254 (Review).<br/>Schär, F., Guo. L., Streit, A., Khieu, V., Sinuon, M., Marti, H and Odermatt, P. (2014). Strongyloides stercoralis genotypes in humans in Cambodia. Parasitology Inernational 63, 533-536.<br/>Kulkarni, A., Dyka, A., Nemetschke, L., Grant, W. N. and Streit, A. (2013). Parastrongyloides trichosuri suggests that XX/XO sex determination is ancestral in Strongyloididae (Nematode). Parasitology 140, 1822-1830.<br/>Eisenbarth, A., Ekale, D., Hildebrandt, J. C., Achukwi, M. D, Streit, A. and Renz, A. (2013). Molecular evidence of ‘Siisa form’, a new genotype related to Onchocerca ochengi in cattle from North Cameroon. Acta Tropica 127, 261-265.<br/>Rödelsperger, C., Streit, A. and Sommer, R. J. (2012). Structure, function and evolution of the nematode genome. In: eLS. John Wiley & Sons Ltd, Chichester. http://www.els.net/ DOI: 10.1002/9780470015902.a0024603 (Review).<br/>Hildebrandt, J. C., Eisenbarth, A., Renz, A. and Streit, A. (2012). Single worm genotyping demonstrates that Onchocerca ochengi females simultaneously produce progeny sired by different males. Parasitology Research 111, 2217-2221.</p>

Reported by: Adri*********************** (adri**************************)  (obscured for privacy))
Submitted From: Adrian Streit (person) <a href="http://www.wormbase.org//resources/person/WBPerson629#013--10">/resources/person/WBPerson629#013--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by ceciliaWBPerson1** [comment]
Dear Adrian:
Thanks for the updates.
Kimberly: plz review papers from list below to add to our collection.
Please let me know to add them to Adrian's Person page.
thanks,
have a great weekend!
Cecilia

**Comment by vanaukenk** [comment]
Hi Adrian and Cecilia,

I've added these papers to the WB curation database as follows (PubMed ID or DOI first, then WB Paper ID):

24986433 is creating WBPaper00046346
24530857 is creating WBPaper00046347
23953590 is creating WBPaper00046348
23727461 is creating WBPaper00046349
22706958 is creating WBPaper00046350
24829037 is creating WBPaper00046351
DOI: 10.1002/9780470015902.a0024603  is WBPaper00046352

Best,
--Kimberly
