### ISSUE TITLE
  So not everything is broken, but the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3556]
<p>&nbsp;&nbsp;So not everything is broken, but the sequence box for ZC132.2 (http://www.wormbase.org/species/c_elegans/cds/ZC132.2#05--10) and ZC132.7 (http://www.wormbase.org/species/c_elegans/cds/ZC132.7#05--10) keeps saying there is an "internal server error". This is the second day I've had trouble with these two pages. The page said to let you know, so I did!<br/>Thanks!</p>

Reported by: Sugg************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8) AppleWebKit/534.50.2 (KHTML, like Gecko) Version/5.0.6 Safari/533.22.3

**Comment by sibyl229** [comment]
Hi, 

The caching issue of the two CDS pages has been fixed. The underlying cause is still unclear, but it seems to be isolated occurrences. If you still have issues with this or other pages, feel free to let us know. 

Thanks for reporting the issue.

Sibyl

**Comment by draciti** [comment]
Hi,
the webteam fixed the issue, you can now access the sequences for ZC132.7.
Please keep us posted if it will happen again
Thanks
Daniela

**Comment by draciti** [comment]
thanks sibyl, closing
