### ISSUE TITLE
  Dear web team: Missing data from Pers...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3557]
<p>&nbsp;&nbsp;Dear web team:<br/>Missing data from Person/Lineage<br/>Data is ok on Tree display, but not in the Main page,<br/>Example: Alexander G. Eberhardt (WBPerson9306) connection to Adrian Streit shows only Phd connection, and missed Masters connection. Same as Julia Hildebrandt WBPerson20260 shows only 1 connection<br/>These 2 Persons have double lineage connections, as Phd and Masters, but only 1 is showing.<br/>http://www.wormbase.org/resources/person/WBPerson629#0125--10<br/>Please fix it to include all lineage connections not only one.<br/>thanks,<br/>cecilia</p>

Reported by: ceci************ (ceci************************)  (obscured for privacy))
Submitted From: Adrian Streit (person) <a href="http://www.wormbase.org//resources/person/WBPerson629#0125--10">/resources/person/WBPerson629#0125--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by sibyl229** [comment]
Hi Cecilia, the missing data display on lineage is fixed now http://staging.wormbase.org/resources/person/WBPerson629#0125--10

**Comment by ceciliaWBPerson1** [comment]
Thank you very much Sibyl!!!!
