### ISSUE TITLE
  Convert/integrate IDs from different ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3559]
<p>&nbsp;&nbsp;Convert/integrate IDs from different wormbase versions: I need to integrate different datasets and get them all up to date to the latest IDs?<br/>What is the procedure you advise?<br/>Where can I find the Wormbase ID, Sequence and gene symbol IDs of different wormbase versions?<br/>I need to do this genome-wide.</p>

Reported by: Vane*************** (vane************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by tharris** [comment]
Hi Vanessa - 

There are many ways to do this.

Personally, I’d pick a programming language that you’re familiar with and create hash table mappings between your various IDs.  You can find a wide variety of ID-to-object entity mappings on the FTP site for different releases.

Todd
