### ISSUE TITLE
  Dear he or she, I notice that we can ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3560]
<p>&nbsp;&nbsp;Dear he or she,<br/>I notice that we can see one particular gene's mRNA level from the RNASeq of sequence feature. But, the question is how to compare mRNA level between two genes that are on different chromosomes? Is it possible to show the exact percentage of mRNA level of one gene so that we could compare two far away genes mRNA level quantitatively(roughly).<br/>Best regards,<br/>Xianglin </p>

Reported by: Xian******* (pgxl************)  (obscured for privacy))
Submitted From: vha-6 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00006915#0-9e-3">/species/c_elegans/gene/WBGene00006915#0-9e-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

**Comment by WenChenWormBase** [comment]
Dear Xianglin:

You may do this in SPELL: http://spell.caltech.edu:3000/search

1. From the menu on the left, choose "show expression levels"
2. type in search box names of the genes that you are interested.
3. Open "Options for Filtering Results by Dataset Tags[image:
Green_new_window_icon] <http://spell.caltech.edu:3000/search/tag_details>
select "Method: RNAseq"

You will be able to see the expression levels in all RNAseq datasets. The
expression level shown on the website are normalized, so you can compare
them. If you need their FKLM, you will need to download the whole datasets
from "Dataset Listing" menu, and pull out the value via a script. Or you
can search for them in their gene pages on WormBase.

Let me know if you have additional questions.


Wen Chen







On Mon, Jan 19, 2015 at 6:48 PM, WormBase Helpdesk <notifications@github.com
> wrote:

>   Dear he or she,
> I notice that we can see one particular gene's mRNA level from the RNASeq
> of sequence feature. But, the question is how to compare mRNA level between
> two genes that are on different chromosomes? Is it possible to show the
> exact percentage of mRNA level of one gene so that we could compare two far
> away genes mRNA level quantitatively(roughly).
> Best regards,
> Xianglin
>
> Reported by: Xian******* (pgxl************) (obscured for privacy))
> Submitted From: vha-6 (gene) /species/c_elegans/gene/WBGene00006915#0-9e-3
> <http://www.wormbase.org//species/c_elegans/gene/WBGene00006915#0-9e-3>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5
> (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3560>.
>



-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by raymond91125** [comment]
@WenChenWormBase i'm assuming no more question from user.

**Comment by WenChenWormBase** [comment]
@raymond91125 you are right. I forgot to close this ticket.
