### ISSUE TITLE
  I am a high school student attempting...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3561]
<p>&nbsp;&nbsp;I am a high school student attempting to put together a project on spinocerebellar ataxia type 2. This is my first time using c. elegans and I would like to be able to do so to model the disease but due to my resources, I may only monitor changes in movement. <br/>Under the atx-2 gene, under the phenotypes tab, I do not see any phenotypes involving movement. <br/>Is it possible I may acquire a strain that mirrors movement or should I use another gene to mirror SCA2? If I use another gene, will it hinder my results?<br/>Thank you in advance!</p>

Reported by: Hill*** (hill*********************)  (obscured for privacy))
Submitted From: atx-2 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00000231#07bf-e4-3">/species/c_elegans/gene/WBGene00000231#07bf-e4-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10

**Comment by xdwang** [comment]
Dear Hillary,

Due to the embryonic lethality of atx-2, unfortunately there is no worm strain available for you to track movement.

I will suggest you to read through paper evidence under atx-2 gene overview, and see what other researchers have done on this gene. You may be able find some other hints from the readings. 

Good luck,

Xiaodong Wang
Wormbase curator

> On Jan 20, 2015, at 4:28 AM, no-reply@wormbase.org wrote:
> 
> How Do I ...? 
>   I am a high school student attempting to put together a project on spinocerebellar ataxia type 2. This is my first time using c. elegans and I would like to be able to do so to model the disease but due to my resources, I may only monitor changes in movement. 
> Under the atx-2 gene, under the phenotypes tab, I do not see any phenotypes involving movement. 
> Is it possible I may acquire a strain that mirrors movement or should I use another gene to mirror SCA2? If I use another gene, will it hinder my results?
> Thank you in advance!
> 
> Submitted From: 
>   atx-2 (gene) /species/c_elegans/gene/WBGene00000231#07bf-e4-3 <http://www.wormbase.org//species/c_elegans/gene/WBGene00000231#07bf-e4-3>
> This issue has been assigned ticket number: #3561. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3561>.
> 
> 
> Reported by: Hillary (hillary.aderemi@gmail.com <mailto:hillary.aderemi@gmail.com>) 
> 20 Jan 15 09:28 
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125
