### ISSUE TITLE
  T07A9.9 is now called nog-1. PMID: 24...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3562]
<p>&nbsp;&nbsp;T07A9.9 is now called nog-1.<br/>PMID:<br/>24552710</p>

Reported by: Dave******* (worm*****************)  (obscured for privacy))
Submitted From: T07A9.9 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00020297#0964fb1cd--10-964fb1cd">/species/c_elegans/gene/WBGene00020297#0964fb1cd--10-964fb1cd</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by tuli** [comment]
Tim.

The nog gene class already exists as "NO Germ line", but with only one
old_member (nog-1)

Here's some history from 2005
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Dear Mary Ann

I believe that nog-1 has not been used in any publications, but
there may well be other nog- genes which will be valid names.
It would be best to retain nog-1 as an other name, with Jane Hubbard
as person_evidence.

Jonathan

On Mon, 5 Sep 2005, Mary Ann Tuli wrote:

> Dear Jonathan,
> Tracey has curated allele ar228 which lies in sequence T22F3.4 (rpl-11.1

> WBGene00004422).
> The allele was already connected to nog-1 (WBGene00003781) which include
the
> Remark "This is a temporary gene. The properties of the allele ar228 may

> dictate use of another gene acronym. The mapping data has therefore been

> moved to the Allele. [sdm 0107]"
>
> Should nog-1 now be merged into rpl-11.1 and included as an other_name?
The
> nog gene class belongs to Jane Hubbard, but nog-1 has not been connected
to
> it. I got no Textpresso hits with nog-1 so perhaps the gene name has not
been
> used at all?
>
> Thanks,
>
> Mary Ann

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

It seems that the existing gene class has not been further populated
so perhaps it should be renamed to
"Novel Ortholog of NOG-1" and this new assignment made (T07A9.9 =
nog-1) and appropriate Remarks added to both the nog gene class and
the current nog-1 gene (which exists as an other name of rpl-11.1).

The last author of PMID 24552710 (paper attached) is not associated
with a lab so does not have a lab code. The other authors are from a
number of different labs and some authors look like they need their
information updated - I will look into that. I don't know whether you
want to contact Jeong Hoon Cho or assign nog to a different lab (maybe
GNW?).

Thanks,

M.A.










On 20 January 2015 at 22:30, <no-reply@wormbase.org> wrote:
>
> Content Correction
>
>   T07A9.9 is now called nog-1.
> PMID:
> 24552710
>
> Submitted From:
>   T07A9.9 (gene) /species/c_elegans/gene/WBGene00020297#0964fb1cd--10-964fb1cd
>
> This issue has been assigned ticket number: #3562. Follow progress on our issue tracker.
>
> Reported by: Dave Reiner (wormboy2000@gmail.com)
> 20 Jan 15 22:32
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101 Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Mary Ann, 

Lots of confusion here. 

The paper from Joeng Hoon Cho refers to T07A9.9, which encodes a nucleolar protein orthologous to human GTPBP4 ENSG00000107937 ; which has NOG1 as a synonym. 
Absent approval from WormBase, they called T07A9.9 nog-1. 

T22F3.4 = rpl-11.1 (ribosomal protein), was called nog-1, with the gene class name "nog" for NO Germline; however there are no publications using this gene class name. 

I will contact Jane Hubbard to see if there are plans to use the "nog" gene class name in the near future. 
However, even if there are no plans in the future to use the NO Germline gene class (thus leaving it open for an alternative use), it is not clear that it is a useful way to refer to T07A9.9. 

Thanks, 

Tim 

----- Original Message -----

**Comment by tuli** [comment]
Dear Dave,

Thank you for writing to WormBase.

I am not sure whether you are following the ticket in our issue tracker
https://github.com/WormBase/website/issues/3562 so I include Tim's comments
below.

-------------------------------------------------------------------------------------------------
Lots of confusion here. The paper from Joeng Hoon Cho refers to T07A9.9,
which encodes a nucleolar protein orthologous to human GTPBP4
ENSG00000107937 ; which has NOG1 as a synonym. Absent approval from
WormBase, they called T07A9.9 nog-1. T22F3.4 = rpl-11.1 (ribosomal
protein), was called nog-1, with the gene class name "nog" for NO Germline;
however there are no publications using this gene class name. I will
contact Jane Hubbard to see if there are plans to use the "nog" gene class
name in the near future. However, even if there are no plans in the future
to use the NO Germline gene class (thus leaving it open for an alternative
use), it is not clear that it is a useful way to refer to T07A9.9. Thanks,
Tim
-------------------------------------------------------------------------------------------------

We will keep you informed with updates.

Best wishes,

Mary Ann

On 20 January 2015 at 22:30, <no-reply@wormbase.org> wrote:

> Content Correction
>
>   T07A9.9 is now called nog-1.
> PMID:
> 24552710
>
> Submitted From:
>   T07A9.9 (gene)
> /species/c_elegans/gene/WBGene00020297#0964fb1cd--10-964fb1cd
> <http://www.wormbase.org//species/c_elegans/gene/WBGene00020297#0964fb1cd--10-964fb1cd>
>
> This issue has been assigned ticket number: #3562. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3562>.
>
>  Reported by: Dave Reiner (wormboy2000@gmail.com)
> 20 Jan 15 22:32
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101
> Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi,

Just an update wrt the reference.

Our automated script associated the Cho paper with rpl-11.1 via the nog-1
synonym.

I've removed this gene-paper association and added T07A9.9 to the Cho paper.

--Kimberly


> Dear Dave,
>
> Thank you for writing to WormBase.
>
> I am not sure whether you are following the ticket in our issue tracker
> https://github.com/WormBase/website/issues/3562 so I include Tim's
> comments
> below.
>
> -------------------------------------------------------------------------------------------------
> Lots of confusion here. The paper from Joeng Hoon Cho refers to T07A9.9,
> which encodes a nucleolar protein orthologous to human GTPBP4
> ENSG00000107937 ; which has NOG1 as a synonym. Absent approval from
> WormBase, they called T07A9.9 nog-1. T22F3.4 = rpl-11.1 (ribosomal
> protein), was called nog-1, with the gene class name "nog" for NO
> Germline;
> however there are no publications using this gene class name. I will
> contact Jane Hubbard to see if there are plans to use the "nog" gene class
> name in the near future. However, even if there are no plans in the future
> to use the NO Germline gene class (thus leaving it open for an alternative
> use), it is not clear that it is a useful way to refer to T07A9.9. Thanks,
> Tim
> -------------------------------------------------------------------------------------------------
>
> We will keep you informed with updates.
>
> Best wishes,
>
> Mary Ann
>

**Comment by raymond91125** [comment]
@tuli should this ticket be closed?

**Comment by tuli** [comment]
Dear Dave,

Apologies for the delay in following up on this issue.

The following changes have been made:
- The nog gene class has been renamed "homolog of yeast NucleOlar G-protein"
- T07A9.9 has been assigned nog-1
- nog-1 remains as an other name of rpl-11.1 (T22F3.4)

You'll see these changes in release WS248 of WormBase.

Best wishes,

Mary Ann

On 22 January 2015 at 09:20, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
> Dear Dave,
>
> Thank you for writing to WormBase.
>
> I am not sure whether you are following the ticket in our issue tracker
> https://github.com/WormBase/website/issues/3562 so I include Tim's comments
> below.
>
> -------------------------------------------------------------------------------------------------
> Lots of confusion here. The paper from Joeng Hoon Cho refers to T07A9.9,
> which encodes a nucleolar protein orthologous to human GTPBP4
> ENSG00000107937 ; which has NOG1 as a synonym. Absent approval from
> WormBase, they called T07A9.9 nog-1. T22F3.4 = rpl-11.1 (ribosomal protein),
> was called nog-1, with the gene class name "nog" for NO Germline; however
> there are no publications using this gene class name. I will contact Jane
> Hubbard to see if there are plans to use the "nog" gene class name in the
> near future. However, even if there are no plans in the future to use the NO
> Germline gene class (thus leaving it open for an alternative use), it is not
> clear that it is a useful way to refer to T07A9.9. Thanks, Tim
> -------------------------------------------------------------------------------------------------
> We will keep you informed with updates.
>
> Best wishes,
>
> Mary Ann
>
> On 20 January 2015 at 22:30, <no-reply@wormbase.org> wrote:
>>
>> Content Correction
>>
>>   T07A9.9 is now called nog-1.
>> PMID:
>> 24552710
>>
>> Submitted From:
>>   T07A9.9 (gene)
>> /species/c_elegans/gene/WBGene00020297#0964fb1cd--10-964fb1cd
>>
>> This issue has been assigned ticket number: #3562. Follow progress on our
>> issue tracker.
>>
>> Reported by: Dave Reiner (wormboy2000@gmail.com)
>> 20 Jan 15 22:32
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101
>> Firefox/35.0
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
It should now :-)
