### ISSUE TITLE
Strain Summary not listing all Variations

### ISSUE THREAD

**Issue by tuli** [WormBase/website#3563]
e.g. http://www.wormbase.org/species/c_elegans/strain/AGD397

Contains widget should list ok524 and tm1944 but only includes ok524

I've looked at a few more and they all seem OK so I'm not sure what the problem is.

**Comment by sibyl229** [comment]
Hi @tuli tm1944 isn't in the tree display either. The web code doesn't do any other filtering on the list of variations, except when there are >= 500 variations - at that point it will link to search page instead compiling a list.

**Comment by tuli** [comment]
OK thanks @sibyl229 
The problem is in the source data. I'll close.
