### ISSUE TITLE
  Hi, Just a comment, when finding a hu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3564]
<p>&nbsp;&nbsp;Hi,<br/>Just a comment, when finding a human homologue of a C. elegans´ protein, there is sometimes a link such as:  ENSEMBL:ENSP00000333556. I find difficult to find the info with this code. My suggestion is that, if possible, at some point, this could be replaced by a uniprot code, or an easier link. If I am missing something, and this is the best link possible, please let me know.<br/>Thanks,<br/>Paola</p>

Reported by: p j (paol*******************)  (obscured for privacy))
Submitted From: Y75B8A.6 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00013543#0d4-9e6b817fa-10">/species/c_elegans/gene/WBGene00013543#0d4-9e6b817fa-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by epaule** [comment]
Oour homology section are from blasts against collected proteins of a species from various sources.
The ENSEMBL: are proteins from the EnsEMBL databases.
If you click on the name, it should get you to the respective database.

It is a bit iffy for the EnsEMBL ones, as you have to then click on  the respective species if you can't spot it in the hits, but as we can't guarantee that the protein is still in the live gene set, it is a good way to cover all bases.

Depending on what was used by the EnsEMBL genebuild, there should be also more information on the respective gene/transcripts/etc pages , and at least for most human gene models there, a link to uniprot.

We are actually considering using the new uniprot species sets instead, but that is still in the pro/con discussion phase.
