### ISSUE TITLE
  There's something wrong of CEP-1 sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3568]
<p>&nbsp;&nbsp;There's something wrong of CEP-1 sequence flies, especially CDS 	<br/>F52B5.5a, could not show any details.</p><p>What were you doing? <br />&nbsp;&nbsp;I were checking the CDS and would design the RNAi primers.</p>

Reported by: Ain ***** (ain.****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by raymond91125** [comment]
Hi Ain,

Thanks for reporting the problem. For the time being, you could perhaps 
use the transcript sequence (spliced) to design RNAi primers.

Apologies for the inconvenience.

Raymond


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
Fixed for WS246.
