### ISSUE TITLE
  Hello! I'm interested in ranking C. e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3569]
<p>&nbsp;&nbsp;Hello!<br/>I'm interested in ranking C. elegans neuron popularity and was wondering if there was any data available on page views for each neuron's WormBase page? Thanks for any advice!<br/>Evan</p>

Reported by: Evan******* (eard************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by raymond91125** [comment]
@tharris Is it correct if I reply that we are not supporting such inquiries?

**Comment by epaule** [comment]
@raymond91125 , @tharris while I don't think we actually gave him the data, I will close that ticket. If you want to reopen it for policy discussions, feel free to.

**Comment by raymond91125** [comment]
Fine by me. Thanks.
