### ISSUE TITLE
Searching for gene "cep-1" doesn't return cep-1 gene page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3570]
Although "cep-1" comes up as an autocomplete option, typing in "cep-1" in the search box when searching for a gene and hitting Return gives a bunch of irrelevant results.

![screen shot 2015-01-26 at 11 01 27 am](https://cloud.githubusercontent.com/assets/611382/5906216/c178daec-a54a-11e4-9d10-b85da9b9f654.png)

**Comment by tuli** [comment]
Same as #3526

**Comment by sibyl229** [comment]
Hi @chris-grove http://staging.wormbase.org/search/gene/cep-1 cep-1 is showing up on top now :)

**Comment by chris-grove** [comment]
OK, thanks @sibyl229
