### ISSUE TITLE
  Hi, I need some (or all) of the genet...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3572]
<p>&nbsp;&nbsp;Hi,<br/>I need some (or all) of the genetic interaction data but can't find it in the worm base datasets or Worm Mart. Could you help?<br/>Ben</p>

Reported by: Benj**** (bouc*****************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by kyook** [comment]
Raymond replied: 

Raymond Lee
Jan 28 (7 days ago)

to reply+00097400., boucher.benjam., help 
HI Ben,

All interactions are compiled in a gene_interactions.txt file, for WS246, here <ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/annotation/>.

Let us know if that's not sufficient.

Cheers,

Raymond
