### ISSUE TITLE
  Do you provide consensus sequences fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3573]
<p>&nbsp;&nbsp;Do you provide consensus sequences for the 43 transposon families listed on your database or have any recommendations on where to obtain the most up-to-date version of such information? I could not find a corresponding sequence for each transposon family in Repbase. <br/>Thank you.</p>

Reported by: klar******************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by epaule** [comment]
we currently do not create consensus sequences for the transposon families.
Internally we have created a repeatmasker library containing each single sequence, which you can also get by grabbing them from the GBrowse/fasta.
I do believe the transposon family descriptions came from early work done at the beginning of the project. There is actually a nice description in WormBook http://www.wormbook.org/chapters/www_transposons/transposons.html
