### ISSUE TITLE
  Hi, I am working from home in New Jer...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3575]
<p>&nbsp;&nbsp;Hi,<br/>I am working from home in New Jersey, near Rutgers, and the wormbase website is continually timing out on me when I am searching for a gene. Occasionally something will load, but it's taking a REALLY long time (on the order of minutes) and then I'll only get certain sections to load, i.e. phenotypes but not overview, etc. I just wanted to make the wormbase team aware of the issue, and also find out if there is a potential timeline of when it might be resolved?  Thank you for your help!<br/>Sincerely,<br/>Stephanie</p>

Reported by: Step************** (pyon************************)  (obscured for privacy))
Submitted From: enol-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00011884#0ba1-cd49f-10-a">/species/c_elegans/gene/WBGene00011884#0ba1-cd49f-10-a</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by chris-grove** [comment]
Hi Stephanie,

 Thank you for reporting the issue. The WormBase website appears to be having issues currently. We are aware of the problem and are working to restore service as soon as possible.

Best,

Chris Grove

**Comment by chris-grove** [comment]
Just to weigh in. I’ve resolved the issue and service has been restored to full
capacity.
 
My apologies for the difficulties.

Todd
