### ISSUE TITLE
  how do i load contigs of a new isolat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3576]
<p>&nbsp;&nbsp;how do i load contigs of a new isolated nematode?</p>

Reported by: hope******* (hope****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by epaule** [comment]
@khowe was already in contact
