### ISSUE TITLE
  submit contigs of new nematode on wor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3577]
<p>&nbsp;&nbsp;submit contigs of new nematode on wormbase.org?</p>

Reported by: hope******* (hope****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by kyook** [comment]
repeat of #3576
