### ISSUE TITLE
C.japonica GBrowse

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3578]
It looks like the C.japonica GBrowse is broken on live and staging, affecting also the location and sequence widgets of the respective genes.

http://www.wormbase.org/tools/genome/gbrowse/c_japonica_PRJNA12591/?name=CJA09395
![screenshot from 2015-01-30 15 25 01](https://cloud.githubusercontent.com/assets/20523/5977981/366c1ab6-a894-11e4-82cd-70485b87e840.png)

http://staging.wormbase.org/species/c_japonica/gene/WBGene00124277#0-f96-10
![screenshot from 2015-01-30 15 23 04](https://cloud.githubusercontent.com/assets/20523/5977987/3af4ff3a-a894-11e4-80a1-5a45c252ac37.png)

**Comment by scottcain** [comment]
I think this a problem with the mysql database.  The primary GBrowse database for C. japonica is mostly empty: the database named c_japonica_PRJNA12591_WS246 on dev.wormbase.org as zero entries in the feature and sequence tables.

**Comment by scottcain** [comment]
This is fixed in the mysql database c_japonica_PRJNA12591_WS246.  It's unclear to me if it needs to be fixed in the 246 database as well, or if this can be closed.  @tharris ?

**Comment by epaule** [comment]
I think it would be great if we could fix that also for WS246, as else the C.japonica functionality of the website is a bit limited, as it affects the sequence widget in addition to the location one and the GBrowse.
But I will leave the decision for Todd

**Comment by tharris** [comment]
I've replaced the database for WS246 in production. Please test and close if sufficient.

**Comment by epaule** [comment]
the GBworse looks fine, and the widgets are sadly cached, so I guess we can't "unbreak" them without doing the whole caching everything ringmarole, or is there a species and class/widget specific way to do it?

**Comment by tharris** [comment]
Correct. I cannot currently expire specific species because the cache uses a key format of : class _  widget _ ID

It wouldn’t be hard to write a script to purge specific subset of the cache that is limited to species.
