### ISSUE TITLE
  Wormmine returned "NO RESULTS" for list of Brugia genes

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3579]
<p>&nbsp;&nbsp;Wormmine reurned this messge "NO RESULTS This query returned 0 results" when trying to create a list to run a query. How do I create a list from WB gene names?</p>

Reported by: Maeg*** (maeg*************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by raymond91125** [comment]
Hi Maeghan,

When I tried with the sample list of genes (Analyze a 
list->advanced->click to see an example), it seemed to work fine just 
now. Please try again or provide us with examples of your list.

Thanks.

Raymond


On 01/30/2015 11:42 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Wormmine reurned this messge "NO RESULTS This query returned 0 
> results" when trying to create a list to run a query. How do I create 
> a list from WB gene names?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3579. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3579>.
>
> Reported by: Maeghan (maeghan.oneill@mail.mcgill.ca)
> 30 Jan 15 19:44
>
> Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi Maeghan,

 Just to add to Raymond's comment, there is a bug in WormMine that if you
select the species in the list upload form, many (or all) of the objects
entered won't be properly recognized. I would suggest that if you
specified the species for the gene list, try again but without specifying
the species (as in attached screenshot) and let us know if that works or
not.

Apologies for the difficulty.

Best,

Chris Grove



> Hi Maeghan,
>
> When I tried with the sample list of genes (Analyze a
> list->advanced->click to see an example), it seemed to work fine just
> now. Please try again or provide us with examples of your list.
>
> Thanks.
>
> Raymond
>
>
> On 01/30/2015 11:42 AM, no-reply@wormbase.org wrote:
>> How Do I ...?
>>
>>   Wormmine reurned this messge "NO RESULTS This query returned 0
>> results" when trying to create a list to run a query. How do I create
>> a list from WB gene names?
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #3579. Follow progress on
>> our issue tracker <https://github.com/WormBase/website/issues/3579>.
>>
>> Reported by: Maeghan (maeghan.oneill@mail.mcgill.ca)
>> 30 Jan 15 19:44
>>
>> Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>>
>> This question was reported via the web interface at wormbase.org. You
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> To unsubscribe from this group and stop receiving emails from it, send
>> an email to help+unsubscribe@wormbase.org
>> <mailto:help+unsubscribe@wormbase.org>.
>
>
> --
> __
> Raymond Lee
> raymond@caltech.edu
> http://www.WormBase.org/
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send an
> email to help+unsubscribe@wormbase.org.
>


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Chris Grove, PhD
Associate Biologist, Curator, www.Wormbase.org
Office Phone: (626) 395-5904
E-mail: cgrove@caltech.edu
E-mail: chris@wormbase.org
Skype name: christian_grove
Mailing Address:
Division of Biology
Mail Code 156-29
California Institute of Technology
1200 E. California Blvd.
Pasadena, CA 91125

**Comment by chris-grove** [comment]
It seems that Brugia malayi genes are not being recognized by the WormMine list upload. For example, Maeghan was attempting to create a list of the following genes:

WBGene00221268
WBGene00223091
WBGene00224415
WBGene00223780
WBGene00222025
WBGene00224809
WBGene00235054
WBGene00228148
WBGene00227662
WBGene00233670
WBGene00234981
WBGene00227545
WBGene00223078
WBGene00223153
WBGene00233941
WBGene00227431
WBGene00221515
WBGene00229798
WBGene00234222
WBGene00226297
WBGene00222181

each of which individually appears to be present in WormMine as I can query them out using the QueryBuilder; however, they won't enter into any list, nor will WormMine throw any errors to indicate a problem; it will just show a list with no results.

**Comment by chris-grove** [comment]
Here's a screen capture video demonstrating what I mean:

https://dl.dropboxusercontent.com/u/4290782/WormMine_List_Error_1-30-2015.mov

**Comment by chris-grove** [comment]
No longer an issue. Closing
