### ISSUE TITLE
  find SNP between N2 and CB4856 worn i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3582]
<p>&nbsp;&nbsp;find SNP between N2 and CB4856 worn in new version of wormbase website. In the old version, i can easily find it, but in the new one, there are many different SNP in different strains, it is hardly it isolate what i want! thanks very  much!</p>

Reported by: Yuan*** (liyu*************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by tuli** [comment]
Dear Yuan Li,

Thank you for writing to WormBase.

Your best bet is to use our GFF files. Here is a link to the GFF3 for
our latest development release:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS246.annotations.gff3.gz

To get all variations reported in CB4858, you can do:

zcat c_elegans.PRJNA13758.WS242.annotations.gff3.gz | awk '$1 ==
"Variation_project_Polymorphism" | grep CB4858

Thank you,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
