### ISSUE TITLE
production release symlinks need updating on FTP site

### ISSUE THREAD

**Issue by khowe** [WormBase/website#3584]
Web-site is now on WS246, but production release symlinks on FTP site still point to WS245.

**Comment by sibyl229** [comment]
Hi Todd, there's an issue about production release link on ftp site still linking to WS245. Do that link reflect where the symlink on file system points to? Thanks! 

Sibyl

**Comment by tharris** [comment]
Thanks, @khowe! I relocated the FTP site over the Christmas holiday. It looks like the remote command that keeps the symlinks in place failed. I have since fixed.
