### ISSUE TITLE
  How to become a member? 

Reported by...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3586]
<p>&nbsp;&nbsp;How to become a member?</p>

Reported by: fang****** (zumb*******************)  (obscured for privacy))
Submitted From: password/index <a href="http://www.wormbase.org//password/index">/password/index</a>

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.45 Safari/537.36

**Comment by kyook** [comment]
This appears to be spam.
