### ISSUE TITLE
  Excuse me, i need SNP information of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3588]
<p>&nbsp;&nbsp;Excuse me, i need SNP information of CB4856(like cb4856_snp_ws246 file), but i can not to find it. Could someone provide me a link where i can download it?<br/>thank you very much</p>

Reported by: chua*************************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko) Version/7.0.2 Safari/537.74.9

**Comment by tuli** [comment]
Hello,

Thank you for writing to WormBase.

Your best bet is to use our GFF files. Here is a link to the GFF3 for
our latest development release:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS246.annotations.gff3.gz

To get all variations reported in CB4856, you can do:

zcat c_elegans.PRJNA13758.WS246.annotations.gff3.gz | awk '$1 ==
"Variation_project_Polymorphism" | grep CB4856

I hope this helps,

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
