### ISSUE TITLE
  Hi am trying to access the sequence t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3589]
<p>&nbsp;&nbsp;Hi am trying to access the sequence to the act-1 coding sequence and it says there is an "Internal Server Error". I need this sequence ASAP so your help would be much appreciated!</p>

Reported by: Math******* (mat.****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by chris-grove** [comment]
@sibyl229 
This seems to be related to #3544 , #3558 , and #3556

**Comment by chris-grove** [comment]
Hi Mathew,

 Apologies for difficulty.

 Here is the act-1 open reading frame (for transcript T04C12.6.1):

ATGTGTGACGACGAGGTTGCCGCTCTTGTTGTAGACAATGGATCCGGAATGTGCAAGGC
CGGATTCGCCGGAGACGACGCTCCACGCGCCGTGTTCCCATCCATTGTCGGAAGACCACGTCATCAAGGAGTCATGGTCG
GTATGGGACAGAAGGACTCGTACGTCGGAGACGAGGCCCAATCCAAGAGAGGTATCCTTACCCTCAAGTACCCAATTGAG
CACGGTATCGTCACCAACTGGGATGATATGGAGAAGATCTGGCATCACACCTTCTACAATGAGCTTCGTGTTGCCCCAGA
AGAGCACCCAGTCCTCCTCACTGAAGCCCCACTCAATCCAAAGGCTAACCGTGAAAAGATGACCCAAATCATGTTCGAGA
CCTTCAACACCCCAGCCATGTATGTCGCCATCCAAGCTGTCCTCTCCCTCTACGCTTCCGGACGTACCACCGGAGTCGTC
CTCGACTCTGGAGATGGTGTCACCCACACCGTCCCAATCTACGAAGGATATGCCCTCCCACACGCCATCCTCCGTCTTGA
CTTGGCTGGACGTGATCTTACTGATTACCTCATGAAGATCCTTACCGAGCGTGGTTACTCTTTCACCACCACCGCTGAGC
GTGAAATCGTCCGTGACATCAAGGAGAAGCTCTGCTACGTCGCCCTCGACTTCGAGCAAGAAATGGCCACCGCCGCTTCT
TCCTCTTCCCTCGAGAAGTCCTACGAACTTCCTGACGGACAAGTCATCACCGTCGGAAACGAACGTTTCCGTTGCCCAGA
GGCTATGTTCCAGCCATCCTTCTTGGGTATGGAGTCCGCCGGAATCCACGAGACTTCTTACAACTCCATCATGAAGTGCG
ACATTGATATCCGTAAGGACTTGTACGCCAACACTGTTCTTTCCGGAGGAACCACCATGTACCCAGGAATTGCTGATCGT
ATGCAGAAGGAAATCACCGCTCTTGCCCCATCAACCATGAAGATCAAGATCATCGCCCCACCAGAGCGCAAGTACTCCGT
CTGGATCGGAGGATCTATCCTCGCTTCCCTCTCCACCTTCCAACAGATGTGGATCTCCAAGCAAGAATACGACGAGTCCG
GCCCATCCATCGTTCACCGCAAGTGCTTCTAA

We hope to have the bug fixed soon.

Thanks!


Chris Grove

**Comment by sibyl229** [comment]
Thanks @chris-grove http://www.wormbase.org/species/c_elegans/cds/T04C12.6#05--10 The web code that caused that bad cache is fixed now, so I think this kind of problem won't happen in the next release. But for now I still have to refresh the cache for every instance.

**Comment by chris-grove** [comment]
@sibyl229  OK, looks good. Thanks!
