### ISSUE TITLE
  Good morning representative. Please I...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3590]
<p>&nbsp;&nbsp;Good morning representative. Please I need help in choosing the type of gene I can select from WormBase for my study which involves identifying the genes that are affected either by inducing them or downregulating them as a result of interaction with a mycotoxin.</p><p>What were you doing? <br />&nbsp;&nbsp;Going through wormbase website to select candidate genes for my gene expression studies.</p>

Reported by: Kabi** (ksun************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by kyook** [comment]
Hi Kabira,

There are a number of ways you can approach this problem:

1. Do a search for mycotoxin on PubMed and see if there has been any
gene studied in C. elegans, in relation to the toxin.
2. Do a search for mycotoxin within the "Anything" class on the front
page of WormBase
3. Use AmiGO to search for mycotoxin related terms and any associated genes.


From any of these searches you should be able to find relevant genes,
if they are not in C. elegans then you should look for C. elegans
orthologs/homologs.

You can do orthology searches using any number of gene analysis
webtools, this site: http://www.ncbi.nlm.nih.gov/gene has many common
tools depending on what information you are starting with (gene name,
protein name, sequence, etc.).


Best wishes,
Karen








On Thu, Feb 5, 2015 at 8:35 AM,  <no-reply@wormbase.org> wrote:
> Question:
>
>   Good morning representative. Please I need help in choosing the type of
> gene I can select from WormBase for my study which involves identifying the
> genes that are affected either by inducing them or downregulating them as a
> result of interaction with a mycotoxin.
>
> What were you doing?
>   Going through wormbase website to select candidate genes for my gene
> expression studies.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3590. Follow progress on our
> issue tracker.
>
> Reported by: Kabiru (ksunmola@uga.edu)
> 05 Feb 15 16:38
>
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/40.0.2214.93 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
