### ISSUE TITLE
  Hi, i am new to using wormbase and am...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3592]
<p>&nbsp;&nbsp;Hi, i am new to using wormbase and am trying to understand some of its features. Is there an option to see what possible structures are found in a protein (eg C. elegans SRA-37 has 7 TM domains). Also is there an option to see where a protein has been reported to be expressed, eg head or tail neurons?</p>

Reported by: Kayl****** (u501***************)  (obscured for privacy))
Submitted From: fars-2 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00013361#0-91bef-10">/species/c_elegans/gene/WBGene00013361#0-91bef-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by draciti** [comment]
Hi Kayla,

thanks for writing to WormBase

for protein structure you can browse the Homology widget. 
e.g. for fars-2-the gene you were looking up: go to the fars-2 gene page, click on Homology on the left sidebar, scroll down till
 
 Protein domains:
Phenylalanine-tRNA ligase, beta subunit, ferrodoxin-fold anticodon-binding
Phenylalanyl-tRNA synthetase
Phenylalanyl-tRNA synthetase, class IIc, mitochondrial

For expression, click on the Expression widget -again on the left side of the screen from the gene page. 
If there are tissue/cell specific data available you will be able to see it. The fars-2 gene does not have any curated information though.

let us know if you have additional questions
Daniela
