### ISSUE TITLE
  I am trying to find the expression pr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3593]
<p>&nbsp;&nbsp;I am trying to find the expression profile of spo-11 gene in L1 stage and not sure how to read it from here? Can you point me out in the right direction?<br/>Thank you!!!</p>

Reported by: Meli** (meli*******************)  (obscured for privacy))
Submitted From: spo-11 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00004985#01-9e3b4a-10">/species/c_elegans/gene/WBGene00004985#01-9e3b4a-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by draciti** [comment]
Hi Melina,

thanks for writing to WormBase.
sorry we are having some troubles with the RNAseq graph display

you can check the staging site for the time being:
http://staging.wormbase.org//species/c_elegans/gene/WBGene00004985#01-9e3b4a-10

thanks

Daniela
