### ISSUE TITLE
  How can I down load the sequences abo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3596]
<p>&nbsp;&nbsp;How can I down load the sequences about C. elegans neuropeptide genes ,C. elegans in vitro RNA interference (RNAi)-related genes from WormBase (version WS236)?</p>

Reported by: Mei *** (08lu************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; MALNJS)

**Comment by kyook** [comment]
Hi Mei,

It seems there are two parts to your question:
first, how do you find a list of specific genes and second, how to do
you retrieve the sequences for all the genes on your list?

To find a list of genes, you can try many things, the easiest is by
far just to search for a keyword in the search box of the WormBase
front page.  You can narrow searches to specific data classes, such as
gene. From the search results page you can use pick a download file
format option for the left sidebar menu.

If you click on the magnifying glass on the far right of the search
tab, you can get to an expanded list of classes and filtering options
to do your search, in your case you perhaps you could narrow your
search to CDS and in species C. elegans although it is not exactly
clear what you are searching for, so I cannot give you better
instructions, but I hope that you will be able to play with the search
parameters to get what you want.

Once you get a list of genes, you can retrieve sequences through
EnsemblMetazoa BioMart:
http://metazoa.ensembl.org/biomart/martview/c60fe2f591ca0eb79168719eb1dbd0d6
Unfortunately this database is a couple releases behind WS246.  If you
need current sequences you can either download each sequence by
visiting each gene page, or download the genome sequence file for C.
elegans from our FTP site


On Sun, Feb 8, 2015 at 5:31 AM,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   How can I down load the sequences about C. elegans neuropeptide genes ,C.
> elegans in vitro RNA interference (RNAi)-related genes from WormBase
> (version WS236)?
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3596. Follow progress on our
> issue tracker.
>
> Reported by: Mei Luo (08luomei@163.com)
> 08 Feb 15 13:33
>
> Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0;
> Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR
> 3.0.30729; Tablet PC 2.0; InfoPath.3; MALNJS)
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
Hi Mei,

I accidently send a truncated message.

To finish, I wanted to include the link to our ftp site where you can
download the sequence file you want:
ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/
and pick out the sequences for each gene there.

I hope this helps. Good luck.

Best wishes,
Karen

On Mon, Feb 9, 2015 at 12:38 PM, Karen Yook <kyook@wormbase.org> wrote:
> Hi Mei,
>
> It seems there are two parts to your question:
> first, how do you find a list of specific genes and second, how to do
> you retrieve the sequences for all the genes on your list?
>
> To find a list of genes, you can try many things, the easiest is by
> far just to search for a keyword in the search box of the WormBase
> front page.  You can narrow searches to specific data classes, such as
> gene. From the search results page you can use pick a download file
> format option for the left sidebar menu.
>
> If you click on the magnifying glass on the far right of the search
> tab, you can get to an expanded list of classes and filtering options
> to do your search, in your case you perhaps you could narrow your
> search to CDS and in species C. elegans although it is not exactly
> clear what you are searching for, so I cannot give you better
> instructions, but I hope that you will be able to play with the search
> parameters to get what you want.
>
> Once you get a list of genes, you can retrieve sequences through
> EnsemblMetazoa BioMart:
> http://metazoa.ensembl.org/biomart/martview/c60fe2f591ca0eb79168719eb1dbd0d6
> Unfortunately this database is a couple releases behind WS246.  If you
> need current sequences you can either download each sequence by
> visiting each gene page, or download the genome sequence file for C.
> elegans from our FTP site
>
>
> On Sun, Feb 8, 2015 at 5:31 AM,  <no-reply@wormbase.org> wrote:
>> How Do I ...?
>>
>>   How can I down load the sequences about C. elegans neuropeptide genes ,C.
>> elegans in vitro RNA interference (RNAi)-related genes from WormBase
>> (version WS236)?
>>
>> Submitted From:
>>   support /tools/support
>>
>> This issue has been assigned ticket number: #3596. Follow progress on our
>> issue tracker.
>>
>> Reported by: Mei Luo (08luomei@163.com)
>> 08 Feb 15 13:33
>>
>> Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0;
>> Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR
>> 3.0.30729; Tablet PC 2.0; InfoPath.3; MALNJS)
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 626.395.5878
> e-mail: kyook@caltech.edu
> e-mail: kyook@wormbase.org
> skype name: wbkaren



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
