### ISSUE TITLE
  can you please update this gene with ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3598]
<p>&nbsp;&nbsp;can you please update this gene with data from this publication: doi:10.1016/j.cell.2015.01.010</p>

Reported by: alex************ (alex********************)  (obscured for privacy))
Submitted From: ZC477.5 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00022620#04-9ec5db-10">/species/c_elegans/gene/WBGene00022620#04-9ec5db-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML, like Gecko) Version/6.1 Safari/537.71

**Comment by kyook** [comment]
Hi Alexandra,

Great timing! Our nomenclature curators had been alerted last week to
this paper and the assignment of ZC477.5 to rde-8; this information
will be in the WS248 release of WormBase due this summer.  I've also
been in the process of curating the variation phenotypes for the genes
mentioned in the paper.  Further, I'm cc'ing our concise description
curators to alert them about this gene and the relevant paper.

Bottom line is that there will be much more information about
ZC477.5/rde-8 on our website this summer.
Thank you for writing to WormBase!

Best wishes,
Karen

On Mon, Feb 9, 2015 at 3:28 AM,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   can you please update this gene with data from this publication:
> doi:10.1016/j.cell.2015.01.010
>
> Submitted From:
>   ZC477.5 (gene) /species/c_elegans/gene/WBGene00022620#04-9ec5db-10
>
> This issue has been assigned ticket number: #3598. Follow progress on our
> issue tracker.
>
> Reported by: alexandra bezler (alexandra.bezler@unil.ch)
> 09 Feb 15 11:30
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML,
> like Gecko) Version/6.1 Safari/537.71
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
