### ISSUE TITLE
  Hi, I have two issues/questions: 1) I...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3600]
<p>&nbsp;&nbsp;Hi,<br/>I have two issues/questions:<br/>1) I and people in my lab have been noticing a number of data tracks in the genome browser fail to appear (the track itself is there but there is no data in it). In addition the following error message appears at the bottom of the browser: "Can't connect to www.wormbase.org:80 (Bad hostname) LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at /usr/share/perl5/LWP/Protocol/http.pm line 51."<br/>Some examples of tracks that give this error are:<br/>"Embryo Fax-sorted cells Signal"<br/>"TSS (Chen) Forward"<br/>2) The available modENCODE datasets are surprisingly out of date. Is there a plan to include more recent modENCODE data (e.g. most of the data)? While in theory these data are available through modencode.org, in practice that website seems to be very slow and often nonfunctional. </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to look at certain tracks</p>

Reported by: John******* (jisa******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by kyook** [comment]
related to #3591 and #3594

**Comment by gw3** [comment]
John,

Could you give an example of two of any modENCODE datasets that you 
expect to see which are in modencode.org and not in the WormBase genome 
browser?
This will give us a better idea of where the problem lies.

Thanks,
Gary Williams

**Comment by gw3** [comment]
Well, for example the NHR-2 (GFP ChIP) Binding Sites/Combined/Replicates
tracks. There are ~91 TFs listed at modENCODE.org (also see Araya et al,
Nature 2014):
[image: Inline image 3]
If I am looking in the right place, I only see 28 at wormbase:
[image: Inline image 2]

**Comment by gw3** [comment]
Hi John,

I see that my colleague Gary is addressing your second issue.  In
regards to your first issue, others have reported similar problems,
which has now been solved for them.  Please let us know if you are
still unable to see the tracks you want.  I've attached a screen shot
of the tracks you mentioned, opened for the oma-1 gene.

Karen

On Mon, Feb 9, 2015 at 11:22 AM,  <no-reply@wormbase.org> wrote:
> Bug Report
>
>   Hi,
> I have two issues/questions:
> 1) I and people in my lab have been noticing a number of data tracks in the
> genome browser fail to appear (the track itself is there but there is no
> data in it). In addition the following error message appears at the bottom
> of the browser: "Can't connect to www.wormbase.org:80 (Bad hostname)
> LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at
> /usr/share/perl5/LWP/Protocol/http.pm line 51."
> Some examples of tracks that give this error are:
> "Embryo Fax-sorted cells Signal"
> "TSS (Chen) Forward"
> 2) The available modENCODE datasets are surprisingly out of date. Is there a
> plan to include more recent modENCODE data (e.g. most of the data)? While in
> theory these data are available through modencode.org, in practice that
> website seems to be very slow and often nonfunctional.
>
> What were you doing?
>   Trying to look at certain tracks
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3600. Follow progress on our
> issue tracker.
>
> Reported by: John Murray (jisaacmurray@gmail.com)
> 09 Feb 15 19:25
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101
> Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by raymond91125** [comment]
TSS (Chen) and Embryo Fax-sorted cells Signal have reappeared.
