### ISSUE TITLE
  How do I find all the deficiencies th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3601]
<p>&nbsp;&nbsp;How do I find all the deficiencies that cover the 0.0 to 0.6 on chromosome II?<br/>Thanks for your help.</p><p>What were you doing? <br />&nbsp;&nbsp;I copied and pasted your example for chromosome IV and simply changed the values, but that did not work.  I kept getting the following error: 
AQL error 700 around: ', right i[rigp[righ'</p>

Reported by: K Su********* (subb************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by kyook** [comment]
Hi K Subramaniam,

It sounds like you need to be looking at the genetic map.  You can
find it by going to the Tools menu on the front page and choosing
Genetic map from the list that shows (see the scree shot I attached).

From there you can choose chromosome II then put in the coordinates
for the region you want to see. The deficiencies should show on the
left side of the chromosome.

Let me know if you this doesn't work for you.

Best wishes,
Karen


On Mon, Feb 9, 2015 at 9:27 PM,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   How do I find all the deficiencies that cover the 0.0 to 0.6 on chromosome
> II?
> Thanks for your help.
>
> What were you doing?
>   I copied and pasted your example for chromosome IV and simply changed the
> values, but that did not work. I kept getting the following error: AQL error
> 700 around: ', right i[rigp[righ'
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3601. Follow progress on our
> issue tracker.
>
> Reported by: K Subramaniam (subbu@iitm.ac.in)
> 10 Feb 15 05:30
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
User wrote: 
K Subramaniam
12:42 AM (6 hours ago)

to kyook 
Hi Karen,
Thanks for the prompt response.  Your instructions were helpful, and I have identified the relevant deficiencies.
Thanks again,
Subramaniam

**Comment by raymond91125** [comment]
Hi,

It looks like there's a problem parsing the query texts. While our team 
works on resolving that, please use this one-line string to query:

"select r, left, right from r in class Rearrangement, map in r->Map 
where map = "II", left in map[Left] where left > 0.0, right in 
map[right] where right < 0.6"

It may still report problems but the query appears to work. If you hit 
Submit "HTML output" a few times, the error code changes.

Thanks for reporting the problem.

Raymond


On 02/09/2015 09:27 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I find all the deficiencies that cover the 0.0 to 0.6 on 
> chromosome II?
> Thanks for your help.
>
> What were you doing?
>   I copied and pasted your example for chromosome IV and simply 
> changed the values, but that did not work. I kept getting the 
> following error: AQL error 700 around: ', right i[rigp[righ'
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3601. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3601>.
>
> Reported by: K Subramaniam (subbu@iitm.ac.in)
> 10 Feb 15 05:30
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
i'm reopening this issue because there appears to be a genuine problem with query parsing that needs to be fixed.

**Comment by kyook** [comment]
Thank you Raymond.

On Tue, Feb 10, 2015 at 8:38 AM, Raymond Lee <notifications@github.com>
wrote:

> i'm reopening this issue because there appears to be a genuine problem
> with query parsing that needs to be fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3601#issuecomment-73733066>.
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by raymond91125** [comment]
AQL example appears working now, magically.
