### ISSUE TITLE
  Can't connect to www.wormbase.org:80 ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3602]
<p>&nbsp;&nbsp;Can't connect to www.wormbase.org:80 (Bad hostname) LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at /usr/share/perl5/LWP/Protocol/http.pm line 51. </p>

Reported by: bcht************  (obscured for privacy)
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Windows NT 5.1; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by tharris** [comment]
Confirmed and resolved. DNS accessibility issue.
