### ISSUE TITLE
  How do I search for a single allele o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3606]
<p>&nbsp;&nbsp;How do I search for a single allele of a gene?</p>

Reported by: shaw*************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by raymond91125** [comment]
Hi Shawn,

If you know the allele name, you can just type it in the top right search box and chose Variation.

Raymond
