### ISSUE TITLE
  I have a protein whose function I wis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3607]
<p>&nbsp;&nbsp;I have a protein whose function I wish to determine.</p><p>What were you doing? <br />&nbsp;&nbsp;Does worm base give information on the putative functions of proteins</p>

Reported by: Robe******* (shey*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by vanaukenk** [comment]
Dear Robert,

Thanks for writing to WormBase.

There are several different types of data in WormBase that can inform gene
function.

In the Overview section of each gene page, there are often free text
summaries of a gene's molecular identity, its phenotypes and hence,
biological processes in which it may be involved, its regulatory
interactions, and its expression and subcellular localization.

Along the left side of each gene page are widgets for individual data
types that provide more details.  The Expression, Gene Ontology, Homology,
Interactions, and Phenotypes widgets would be of particular interest for
gene function information.  There is also a References widget that lists
papers that WormBase has indexed for relevant genes.

I hope that helps; please feel free to contact us if you have questions
about specific genes or data types.

Best,
--Kimberly Van Auken


>
> Question:
>   I have a protein whose function I wish to determine.
> What were you doing?
>   Does worm base give information on the putative functions of proteins
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #3607. Follow progress on our
> issue tracker.
>
>   Reported by: Robert Shey (sheynce@gmail.com)
>  12 Feb 15 11:51
>
>  Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
>    This question was reported via the web interface at wormbase.org. You
> can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
