### ISSUE TITLE
  The registration question about worm ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3608]
<p>&nbsp;&nbsp;The registration question about worm picks is faulty. Despite answering the question correctly it will not let me register! Is the metal used for Worm Picks not Platinum, Pt being the chemical symbol??</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to register for wormbase forum</p>

Reported by: Kath (Whit*******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by tharris** [comment]
Hi Kath - 

It looks like the captcha answer had capitalization auto-corrected to lower case. This has been fixed.

Please try registering again.

Best,

Todd
