### ISSUE TITLE
  Were I can get C elegans antimicrobia...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3609]
<p>&nbsp;&nbsp;Were I can get C elegans antimicrobial gene construct. I want to express and purify the protein for my Research work</p><p>What were you doing? <br />&nbsp;&nbsp;Research scholar</p>

Reported by: Dila******* (dila***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.2; MASPJS)

**Comment by kyook** [comment]
Hi Dilawer,

I'm assuming you are asking for a construct that has already been made. If
you know the name of the gene or construct, you can see if it is in the CGC
(https://www.cbs.umn.edu/research/resources/cgc).  If it isn't, you can ask
the authors that have published it.

Hope this helps,
Karen


On Fri, Feb 13, 2015 at 1:47 AM, <no-reply@wormbase.org> wrote:

> Feature Request
>
>   Were I can get C elegans antimicrobial gene construct. I want to express
> and purify the protein for my Research work
>
> What were you doing?
>   Research scholar
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3609. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3609>.
>
>  Reported by: Dilawer Mir (dilawerjk@gmail.com)
> 13 Feb 15 09:49
>
> Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0;
> .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR
> 3.0.30729; InfoPath.2; MASPJS)
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
