### ISSUE TITLE
  Hi is it possible to see the paper/st...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3610]
<p>&nbsp;&nbsp;Hi is it possible to see the paper/study/group that contributed a particular transcript?</p>

Reported by: Kayl* (u501***************)  (obscured for privacy))
Submitted From: Y60A3A.13b (transcript) <a href="http://www.wormbase.org//species/c_elegans/transcript/Y60A3A.13b#06--10">/species/c_elegans/transcript/Y60A3A.13b#06--10</a>

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)

**Comment by Paul-Davis** [comment]
Dear Kayla,

All of the transcripts associated with coding genes are generated by an 
automatic pipeline by us.

The curated coding sequence (CDS) is use as a seed and then overlapping 
EST/mRNA data is used to build/extend the Coding_transcript to give a 
better view of the Transcripts coming from the loci. SL1/2 data is also 
utilised to generate the alternate 5' end transcripts you see on 
different genes.

So to answer your question WormBase should be cited or informed of any 
discrepancy you see in the annotation of these transcripts.

I will look into getting this information added to the Transcript 
summary pages to make the origin more obvious.

Thank you for contacting WormBase

Paul
