### ISSUE TITLE
  I'm trying to find the "gene model ta...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3611]
<p>&nbsp;&nbsp;I'm trying to find the "gene model table" which is said to be on the top of the page in the Identification table of the gene I'm looking at. I'm not quite sure where this is and I need it to get the coding to enter into my BLAST for an assignment. Thank you!</p><p>What were you doing? <br />&nbsp;&nbsp;Assignment for school involving C Elegans and RNAi</p>

Reported by: Madi********* (madi******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by kyook** [comment]
Hi Madison,

The gene model is the cartoon of the exon and intron structure of the gene
aligned with the genome sequence. You can see these models on the Gene
Browser.  You can get access the gene model depictions in a number of
ways.  The easiest would be for you to go to the page of the gene you are
interested in  (do a search for the gene in the top right search box of the
main WormBase page) then open the Location widget from the left sidebar
menu. You can click on the gene model to get more information.

If you are just looking for gene sequence you should be able to get that
from the Sequence widget also from the left sidebar on the gene page.

It would help you a lot to explore the different widgets and links within
them to orient yourself with WormBase and the extensive amount of
information we curate for a given gene.  Be aware that there are usually
many ways to get to the information you want, so you should be able to find
the route to it that makes the most sense to you.

Hope this helps,
Karen

On Mon, Feb 16, 2015 at 2:13 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I'm trying to find the "gene model table" which is said to be on the top
> of the page in the Identification table of the gene I'm looking at. I'm not
> quite sure where this is and I need it to get the coding to enter into my
> BLAST for an assignment. Thank you!
>
> What were you doing?
>   Assignment for school involving C Elegans and RNAi
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3611. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3611>.
>
>  Reported by: Madison Elzey (madisonelzey@yahoo.com)
> 16 Feb 15 22:16
>
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/40.0.2214.111 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by tharris** [comment]
Seems resolved. Closing.
