### ISSUE TITLE
  atn-1 isoform b is inaccessible   Wha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3612]
<p>&nbsp;&nbsp;atn-1 isoform b is inaccessible </p><p>What were you doing? <br />&nbsp;&nbsp;I was determining a primer sequence to use for atn-1 promotor, and I want to consider all isomers. </p>

Reported by: agat* (lond********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; BRI/2; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Hello,

 Apologies for the inconvenience. Our web team is working to fix the
issue. In the meantime, clicking on the "CDS" sequence icon gives an error, but the "Transcript" sequence icon should still work and gives the exact same information (see attached screenshot). Let us know if you need anything else.

Cheer,

Chris Grove

![screen shot 2015-02-19 at 11 45 08 am](https://cloud.githubusercontent.com/assets/611382/6274515/f7b6d858-b82c-11e4-8482-87f499398f0c.png)

**Comment by chris-grove** [comment]
@sibyl229  could you take a look at this? It's the same issue as the others.

**Comment by sibyl229** [comment]
@chris-grove thanks for the screenshot. Sequence widget for CDS W04D2.1b is fix now: http://www.wormbase.org/species/c_elegans/cds/W04D2.1b#05--10

**Comment by chris-grove** [comment]
@sibyl229 Looks good! Thanks!
