### ISSUE TITLE
  When showing a chromosomal region wit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3615]
<p>&nbsp;&nbsp;When showing a chromosomal region with the gene structure, etc., the "overview" shows where the region is on the whole chromosome. This used to show landmark genes. Now it just shows dashes with no labels. How do I get the landmark genes back on the overview?</p>

Reported by: Paul (main*************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by chris-grove** [comment]
Duplicate #3550 , #3551

**Comment by raymond91125** [comment]
@scottcain Should this and duplicates be closed?

**Comment by scottcain** [comment]
I would rather it stay open until the fix I committed goes live on staging, just to make sure.  @tharris : if you want to give me some docs, I'll try the build myself :-)
