### ISSUE TITLE
  Good afternoon,  I have been using wo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3616]
<p>&nbsp;&nbsp;Good afternoon,  I have been using wormbase all day without issue, and just recently it has become very slow and largely unresponsive. Other websites are loading fine for me, so I think this may be a wormbase specific issue. Thank you so much for your help! </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to look up a gene and then an expression pattern.</p>

Reported by: Step***** (pyon************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by chris-grove** [comment]
Confirmed

**Comment by kyook** [comment]
Hi Stephanie,

Sorry for our troubles.  We are aware of the problem and hope to be
accessible soon.
In the meantime, when you check back onto the site, you might want to clear
your cache first.
Please bear with us.

Karen

On Tue, Feb 17, 2015 at 1:26 PM, <no-reply@wormbase.org> wrote:

> Question:
>
>   Good afternoon, I have been using wormbase all day without issue, and
> just recently it has become very slow and largely unresponsive. Other
> websites are loading fine for me, so I think this may be a wormbase
> specific issue. Thank you so much for your help!
>
> What were you doing?
>   Trying to look up a gene and then an expression pattern.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3616. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3616>.
>
>  Reported by: Stephanie (pyonteck@waksman.rutgers.edu)
> 17 Feb 15 21:27
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/40.0.2214.111 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
Thank you so much for the follow-up, Karen. I really appreciate it!

Best,
Stephanie
