### ISSUE TITLE
  Dear wormbase helpers, I am looking f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3619]
<p>&nbsp;&nbsp;Dear wormbase helpers,<br/>I am looking for the Hawaii CB4856 genome sequence, I can't find where to download this from. Will I need to contact a lab where they've sequenced it (is it not publicly available?)<br/>Best wishes<br/>Barney</p>

Reported by: Barn********* (barn***********************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by tuli** [comment]
Dear Barney,

Thank you for writing to WormBase.

WormBase does not have the full version of CB4856, but you can
download the SNPs from WormMine.

You can also look at the the supplemental table from this paper:
http://genome.cshlp.org/content/17/3/337.abstract?cited-by=yes&legid=genome;17/3/337

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
