### ISSUE TITLE
  snb-1 sequence is not showing up.  th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3620]
<p>&nbsp;&nbsp;snb-1 sequence is not showing up.  there is an error.</p>

Reported by: Natt* (nata***********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by chris-grove** [comment]
@sibyl229  Could you take a look at this? This is the same issue as we had before.

**Comment by chris-grove** [comment]
Hello Natty,

 Apologies for the inconvenience. Our web team is working to fix the issue. In the meantime, clicking on the "CDS" sequence icon gives an error, but the "Transcript" sequence icon should still work and gives the exact same information (see attached screenshot). Let us know if you need anything else.

Cheer,

Chris Grove

![screen shot 2015-02-19 at 10 01 17 am](https://cloud.githubusercontent.com/assets/611382/6272782/37d8dcdc-b81f-11e4-8854-2514939f8151.png)

**Comment by chris-grove** [comment]
Same issue as #3612

**Comment by sibyl229** [comment]
Thanks @chris-grove, the cds sequence of snb-1 is working now. http://www.wormbase.org/species/c_elegans/cds/T10H9.4#05--10
Sorry about the delay. I will be back from vacation next Monday and have regular access to my email then.

**Comment by chris-grove** [comment]
@sibyl229  No worries at all! I hope you had a nice vacation.
Works fine now, thanks!
