### ISSUE TITLE
  There is a problem with the gff3 file...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3621]
<p>&nbsp;&nbsp;There is a problem with the gff3 file being distributed at:<br/>ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS246.annotations-processed.gff3.gz<br/>Line 7610901 contains only 8 fields instead of 9. It is missing either the start position or stop position. <br/>That line has a single position given of 12176071, in case that helps you find it. <br/>Would it be possible for you to address this? <br/>Please just let me know if you need further details from me.</p><p>What were you doing? <br />&nbsp;&nbsp;Using the CLC Genomics Workbench to download the C. elegans genome and its annotations. The annotation with the gff file fails due to the issue with line 7610901. </p>

Reported by: Bela******* (bela******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by epaule** [comment]
yes, it looks off. I am trying to find out what went wrong in our code.
Due to it having an additional tab at the end it seems to have passed the qc test :-(

We will give a shout when we know more.

thanks for reporting it,

**Comment by epaule** [comment]
that was a mistake in our balancer curation. According to WormBook (http://www.wormbook.org/chapters/www_geneticbalancers/geneticbalancers.html) chapter 5.2.7 mIn1 balances rol-1 to lin-31 and not lin-13.

It will be fixed in the next WormBase release WS248

**Comment by Paul-Davis** [comment]
This issue is also being discussed in #3629

**Comment by raymond91125** [comment]
@Paul-Davis is this and #3629 resolved?
