### ISSUE TITLE
  Hi there. We have a paper accepted in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3623]
<p>&nbsp;&nbsp;Hi there. We have a paper accepted in which we determined the molecular nature of 7 legacy embryonic lethal mutations (from the early 80s) by whole genome sequencing. We verified our findings by complementation tests, and in one case, by CRISPR-mediated rescue. I see there are lots of forms. which would be best for us? We have the sequence of specific alleles of emb-6, emb-17, emb-10, zyg-2, mel-2, emb-14, and emb-29, and the complementation data for each (testing them against ok and tm deletion alleles). Can you please suggest the forms we should be filling out for each so that we can have this data put into wormbase. Thanks very much for the help!!</p>

Reported by: Andy******* (andy**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4

**Comment by tuli** [comment]
Dear Andy,

Congratulations on the acceptance of your paper.

Please use the Allele Submission Form at
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele.cgi to
submit the sequence details of the 7 alleles. The experimental details
of how these alleles were verified should either be added under
Isolation or as "Other allele comments" as appropriate.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by kyook** [comment]
Hi Andy,

The allele submission form:
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele.cgi
should be able to take most of the data you mention.  Although there is not
specific spot for complementation data, you can put it in the comment field
at the bottom of the form.

We also will want the CRISPR construct information, unfortunately, there is
no form for that, you can send that information to me directly.

Sorry for any duplication in messages from WB.
Best wishes,
Karen

On Thu, Feb 19, 2015 at 8:02 AM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Hi there. We have a paper accepted in which we determined the molecular
> nature of 7 legacy embryonic lethal mutations (from the early 80s) by whole
> genome sequencing. We verified our findings by complementation tests, and
> in one case, by CRISPR-mediated rescue. I see there are lots of forms.
> which would be best for us? We have the sequence of specific alleles of
> emb-6, emb-17, emb-10, zyg-2, mel-2, emb-14, and emb-29, and the
> complementation data for each (testing them against ok and tm deletion
> alleles). Can you please suggest the forms we should be filling out for
> each so that we can have this data put into wormbase. Thanks very much for
> the help!!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3623. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3623>.
>
>  Reported by: Andy Golden (andyg@mail.nih.gov)
> 19 Feb 15 16:05
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.77.4
> (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
