### ISSUE TITLE
Ontology Browser fails to load Alzheimer's disease upon clicking said term

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#3625]
expanding the ontology tree from
<http://www.wormbase.org/tools/ontology_browser#o_browser>
expand on disease (DOID:4) -> disease of mental health (DOID:150) -> cognitive disorder (DOID:1561) -> dementia (DOID:1307) -> Alzheimer's disease (DOID:10652). clicking on the term Alzheimer's 

focus moves to bottom of page but nothing more happens.

**Comment by azurebrd** [comment]
@raymond91125 This should work now, please sign off.  Pull request is in.

**Comment by raymond91125** [comment]
yes, issue fiexed on dev site.
