### ISSUE TITLE
  I just finished and published a genet...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3626]
<p>&nbsp;&nbsp;I just finished and published a genetic screen. I want to enter in data in wormbase to indicate which genes/alleles led to mutant phenotypes (dendrite defects in the PVD neuron in this case) and which ones did not have the phenotype. I did not see an online form for this kind of information. How should I do that?</p>

Reported by: Darr*********** (darr*******************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by kyook** [comment]
Hi Darrell,

You can enter these data in the allele submission form:
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele.cgi

This form takes sequence information as well, which would be very helpful
to us if you have it.

Note that this form takes one allele at a time. If you have many alleles,
you can just send me a table of the data and I will work on it with my
colleague to enter them.

On Thu, Feb 19, 2015 at 2:29 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I just finished and published a genetic screen. I want to enter in data
> in wormbase to indicate which genes/alleles led to mutant phenotypes
> (dendrite defects in the PVD neuron in this case) and which ones did not
> have the phenotype. I did not see an online form for this kind of
> information. How should I do that?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3626. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3626>.
>
>  Reported by: Darrell Killian (darrell.killian@coloradocollege.edu)
> 19 Feb 15 22:32
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/40.0.2214.93 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
Darrell sent me a table of these data and it was processed in time for the WS248 citace upload.
