### ISSUE TITLE
S. ratti assembly data patch WS247

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#3630]
Hi Todd et al.

For WS247 S. ratti was updated to a new assembly but unfortunately the "Sequence collection" wasn't updated in the primary database that was loaded into the build. As a result a cosmetic patch needs to be applied to the WS247 db once it has been unpacked and reconstituted at OICR. 

The file is currently here ftp://ftp.sanger.ac.uk/pub/wormbase/releases/WS247/acedb/PATCHES/s_ratti.sequence_collection.ace on the Saner FTP, but I guess will be synced to ftp://ftp.wormbase.org/pub/wormbase/releases/WS247/WS247/acedb/PATCHES/s_ratti.sequence_collection.ace soon??

There are also small changes to the /nfs/disk69/ftp/pub/consortia/wormbase/releases/WS247/species/ASSEMBLIES.WS247.json file that reflect the changes contained in the patch file.

Thanks

Paul

**Comment by tharris** [comment]
Patch applied.
