### ISSUE TITLE
  I download the gff3 file for RNA-seq ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3632]
<p>&nbsp;&nbsp;I download the gff3 file for RNA-seq analysis. I have some questions about the file: c_elegans.PRJNA13758.WS246.annotations-processed.gff3.gz. After converting to gtf format with cufflinks, I saw many lines labeled with history exon or UTRom without gene_id or gene_name. What are the lines? They can not be recognized by some RNA-seq analysis programs. I wonder if i will lost gene information if removing all lines without gene_name or gene_id.<br/>Thanks.<br/>Yong Guang</p>

Reported by: yong*********** (2009*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by epaule** [comment]
the history exon lines are exons from CDSes that have been retired for various reasons (usually you can find a comment about why on the current CDS page on the website).
the UTRome lines are from an experiment conducted to sequence the UTRs of gene models and are rather supporting evidence than gene models.

So unless you need the above information, you can strip it from your GFF file.
