### ISSUE TITLE
  Expr3014 typo. Says "VSP" instead of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3633]
<p>&nbsp;&nbsp;Expr3014 typo. Says "VSP" instead of 'SVP'?</p>

Reported by: ravi***** (rnat*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

**Comment by draciti** [comment]
Hi Ravi,

it's not a typo. The annotation is correct:
Table1, page 544
flp-13 expressed in ventral spicule protractor muscle, VSP
let us know if you have additional comments/questions
Daniela



>
>
> Content
> Correction
>   Expr3014 typo. Says "VSP" instead of 'SVP'?
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #3633. Follow progress on our
> issue tracker.
>
>   Reported by: ravi nath (rnath@caltech.edu)
>  24 Feb 15 00:54
>
>  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18
> (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18     This question was
> reported via the web interface at wormbase.org. You can also email us
> directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
