### ISSUE TITLE
  I'm trying to find the "gene models t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3634]
<p>&nbsp;&nbsp;I'm trying to find the "gene models table" for unc-22 and it says it should be in the identification section at the top of the page. I still cannot find this. </p><p>What were you doing? <br />&nbsp;&nbsp;Homework assignment </p>

Reported by: Madi********* (madi******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by epaule** [comment]
WormBase uses a
one protein coding gene with one or more CDSes (Coding Sequences), which in turn have one or more transcript
model.

Have a look in the Location and Sequences section of the respective gene, and it will become a bit clearer. Then identify the bits you need, and you should be fine.
