### ISSUE TITLE
  Back in October, I was able to find t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3635]
<p>&nbsp;&nbsp;Back in October, I was able to find the sid-2 nucleotide sequence for C. japonica. But, now when I look for the C. japonica sid-2 mRNA (transcript) nucleotide sequence under nematode orthologs, I am not able to find it.<br/>Could you help me locate it?<br/>Thanks!</p><p>What were you doing? <br />&nbsp;&nbsp;I search for sid-2 gene in the search bar. Then I look for sid-2 nematode orthologs under C. elegans. I then click on the C. japonica hyperlink and look under sequences. </p>

Reported by: Sony******** (sony*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

**Comment by epaule** [comment]
duplicate of #3578

**Comment by tharris** [comment]
Closing, as duplicate reported issue.
