### ISSUE TITLE
  Hi, I was wondering how I can view RN...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3637]
<p>&nbsp;&nbsp;Hi, I was wondering how I can view RNAseq data for a particular gene. Specifically I am trying to view the actual sequence obtained from the RNAseq. Thank you</p>

Reported by: Mitc********** (moak**********************)  (obscured for privacy))
Submitted From: npr-9 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00013974#0f4-9e-3">/species/c_elegans/gene/WBGene00013974#0f4-9e-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

**Comment by gw3** [comment]
We do not provide the actual short-read sequences of any RNASeq 
libraries as tracks on the genome browser.
The best you can do is to run a viewer like IGV on your local machine 
and look at the data in that.

I have a collection of the BAM files for all alignments of non-genomic 
SRA Experiment libraries.
If you let me know the SRA Experiment ID of any particular data that you 
are interested in looking at, I can make the BAM file available on FTP 
for you to copy.

Gary Williams
