### ISSUE TITLE
  Hello, I would like to know it is is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3638]
<p>&nbsp;&nbsp;Hello,<br/>I would like to know it is is posible to retrieve fasta file of specific contig. I aligned my sequences with H. bacteriophora via Wormbase BLAST, it aligned nicely, but I need to see the rest of the contig to estimate the gene ends.<br/>Thanks in advance !</p><p>What were you doing? <br />&nbsp;&nbsp;evolutionary genetics</p>

Reported by: Mart***** (mart***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by epaule** [comment]
I think I found a way without parsing the genome fasta file:
if you go to parasite.wormbase.org and go to a gene on the contig you want, as example:
http://parasite.wormbase.org/Heterorhabditis_bacteriophora_prjna13977/Location/View?db=core;g=Hba_12524;r=Scaffold1250:29645-32693;t=Hba_12524

![screenshot from 2015-02-26 13 31 06](https://cloud.githubusercontent.com/assets/20523/6392762/e5fc91b8-bdbb-11e4-953e-962850cb5ced.png)

you can click in the genome browser on the name of the contig and export it as fasta.
