### ISSUE TITLE
  The "Interactions" section of the mig...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3640]
<p>&nbsp;&nbsp;The "Interactions" section of the mig-5 gene page is busted.  Just gives me an "error occurred" message and the option to open the widget directly doesn't work any better.</p>

Reported by: Aust********** (aust**********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by chris-grove** [comment]
Confirmed time out

**Comment by raymond91125** [comment]
bump

**Comment by sibyl229** [comment]
Duplicate #3353. I'm working on it.

**Comment by sibyl229** [comment]
mig-1 is working on production now: http://www.wormbase.org/species/c_elegans/gene/WBGene00003238#01-9e-3

**Comment by chris-grove** [comment]
@sibyl229  I still keep getting a time-out error on the mig-1 Interactions widget on production

**Comment by chris-grove** [comment]
OK, seems to be loading now without issue. Thanks!

**Comment by chris-grove** [comment]
Sorry, actually I take that back, mig-5 Interactions widget (original issue) is not loading properly on production.

**Comment by chris-grove** [comment]
I'll add, the widget seems to be "hit or miss" as to whether it loads properly.

**Comment by chris-grove** [comment]
OK, now it loads consistently (strange)

**Comment by chris-grove** [comment]
E-mail to user:
"Hello Austin,

 Apologies for the errors. The Interactions widget for mig-5 has been fixed. Please let us know if you encounter any more errors.

Best,

Chris Grove"
