### ISSUE TITLE
  How many Nobel Prizes have been award...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3641]
<p>&nbsp;&nbsp;How many Nobel Prizes have been awarded for work on C.elegans?<br/>Thank you</p>

Reported by: Lizz******** (eec3***********)  (obscured for privacy))
Submitted From: C. elegans <a href="http://www.wormbase.org//species/c_elegans#014--9">/species/c_elegans#014--9</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by chris-grove** [comment]
Hi Lizzie,

 There have been 2 and a third (sort of) Nobel Prizes awarded for work on C. elegans:

2002 Nobel Prize in Medicine:
http://www.nobelprize.org/nobel_prizes/medicine/laureates/2002/

2006 Nobel Prize in Medicine:
http://www.nobelprize.org/nobel_prizes/medicine/laureates/2006/

2008 Nobel Prize in Chemistry:
http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2008/

The 2002 and 2006 prizes in medicine were awarded to entirely C. elegans biologists. The 2008 prize in chemistry was awarded to Martin Chalfie (a C. elegans biologist) and two other (non-C. elegans) biologists/chemists.

Best,

Chris Grove
