### ISSUE TITLE
  Dear Wormbase, What are genetic posit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3642]
<p>&nbsp;&nbsp;Dear Wormbase,<br/>What are genetic positions relative to? I expected to each chromosome to be 0-50 cM.<br/>Some genes i.e. aap-1 show a genetic position that is negative (i.e. aap-1). Are the values relative to the centre of the chromosome, or some historically defined point?<br/>Best wishes<br/>Barney</p>

Reported by: Barn********* (barn***********************)  (obscured for privacy))
Submitted From: aap-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00000001#0-9e3fc16-10-e">/species/c_elegans/gene/WBGene00000001#0-9e3fc16-10-e</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by tuli** [comment]
Dear Barney,

The following paragraph is taken from C. elegans II, 2nd edition.
http://www.ncbi.nlm.nih.gov/books/NBK19976/

I hope it answers your question.

Best wishes,

Mary Ann

Each of the six chromosomes is shown in vertical orientation, with the
left end at the top and right end at the bottom. Numerical map
coordinates, based on recombinational distances in centimorgans, are
shown; these are defined relative to a zero position on each
chromosome. All positions to the left (upward) of this have negative
coordinates, and all positions to the right (downward) have positive
coordinates. There are no defined centromeres on C. elegans
chromosomes, so these zero positions were originally chosen
arbitrarily, each corresponding to a standard marker located at the
approximate middle of each linkage group.
