### ISSUE TITLE
  Hello,  I noticed that since version ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3655]
<p>&nbsp;&nbsp;Hello, <br/>I noticed that since version WS246 you provide automatically generated gene descriptions, but I cannot find them in the provided files on the FTP.<br/>For example, WBGene00006514 has such a description, but I can not find it here:<br/>ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS246.functional_descriptions.txt.gz<br/>I tried also WomMine:<br/><query name="query_1" model="genomic" view="CDS.gene.description" longDescription="" sortOrder="CDS.gene.description asc"><br/><constraint path="CDS.gene.primaryIdentifier" op="=" value="WBGene00006514"></constraint><br/></query><br/>Could you provide these descriptions through FTP?<br/>Thank you in advance,<br/>Best regards,<br/>Georgi Radoslavov</p>

Reported by: Geor************* (ggec********)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by raymond91125** [comment]
Hi Georgi,

Thanks for bringing this to our attention. We will be working on adding 
these descriptions to FTP. Hope to get them out by the next release (WS248).

Raymond


On 03/05/2015 06:57 AM, no-reply@wormbase.org wrote:
> Feature Request
>
>   Hello,
> I noticed that since version WS246 you provide automatically generated 
> gene descriptions, but I cannot find them in the provided files on the 
> FTP.
> For example, WBGene00006514 has such a description, but I can not find 
> it here:
> ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS246.functional_descriptions.txt.gz
> I tried also WomMine:
>
>
>
> Could you provide these descriptions through FTP?
> Thank you in advance,
> Best regards,
> Georgi Radoslavov
>
> Submitted From:
>   Tools /header <http://www.wormbase.org//header>
>
> This issue has been assigned ticket number: #3655. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3655>.
>
> Reported by: Georgi Radoslavov (ggeca@bas.bg)
> 05 Mar 15 15:01
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Dear Raymond,

Thank you for the answer and for the resource that you and your team provide.

Best regards,
Georgi

> Hi Georgi,
>
> Thanks for bringing this to our attention. We will be working on adding
> these descriptions to FTP. Hope to get them out by the next release
> (WS248).
>
> Raymond
>
>

**Comment by raymond91125** [comment]
I added the automatic descriptions to the functional descriptions file for the upcoming WS247 release.

You can find them in the file:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS247/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS247.functional_descriptions.txt.gz

Todd

**Comment by raymond91125** [comment]
Thanks.
