### ISSUE TITLE
could not connect to database mysql clustal_WS247

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#3657]
Hi @tharris, the clustal_WS247 mysql database doesn't seem to be loaded. I'm not sure what's using it, but a test is failing. Thanks!

**Comment by tharris** [comment]
Thanks @sibyl229, should be in place now. Please check and close if working for you.

**Comment by tharris** [comment]
Whoops, closed it already!

**Comment by sibyl229** [comment]
haha. Works for me too. Closing.
