### ISSUE TITLE
  what does the gray color, green/light...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3660]
<p>&nbsp;&nbsp;what does the gray color, green/light blue color, arrows between green colors  represent? (showing the location of isoforms) How do I know where is C and N- terminus? for expl for ZK381.4. Thanks. </p>

Reported by: ND (doda**************)  (obscured for privacy))
Submitted From: pgl-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00003992#0-9efb-10">/species/c_elegans/gene/WBGene00003992#0-9efb-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by raymond91125** [comment]
3' end of the gene model has an arrow head. Green part is coding whereas 
gray is non-coding. Lines connecting the boxes represent intronic sequences.

raymond


On 03/05/2015 12:59 PM, no-reply@wormbase.org wrote:
> Feature Request
>
>   what does the gray color, green/light blue color, arrows between 
> green colors represent? (showing the location of isoforms) How do I 
> know where is C and N- terminus? for expl for ZK381.4. Thanks.
>
> Submitted From:
>   pgl-1 (gene) /species/c_elegans/gene/WBGene00003992#0-9efb-10 
> <http://www.wormbase.org//species/c_elegans/gene/WBGene00003992#0-9efb-10> 
>
>
> This issue has been assigned ticket number: #3660. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3660>.
>
> Reported by: ND (dodanoro@gmail.com)
> 05 Mar 15 21:03
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
