### ISSUE TITLE
  How do I get promoter region and sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3664]
<p>&nbsp;&nbsp;How do I get promoter region and sequence for ttx-3 gene? </p>

Reported by: Bila* (bila*********************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36 OPR/27.0.1689.76

**Comment by gw3** [comment]
If you look at
http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?name=X%3A11763471..11771000
you will see the ttx-3 gene (it is in the reverse sense, so the 5' end 
is to the right) displayed with regulatory regions described in the 
paper Bertrand V et al. (2009) PMID: 19386265
Right-clicking and dragging across the second scale will give you a 
pop-up menu allowing you to dump the selected region as a FASTA file.
