### ISSUE TITLE
  Hi, the search function in wormbase i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3665]
<p>&nbsp;&nbsp;Hi, the search function in wormbase is case-sensitive. I think this is not useful and it would be handier to have it work case-insensitive if possible (try lin-15B vs lin-15b search)</p>

Reported by: alex************ (alex********************)  (obscured for privacy))
Submitted From: sas-6 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00012888#04-9ec5db8-10">/species/c_elegans/gene/WBGene00012888#04-9ec5db8-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML, like Gecko) Version/6.1 Safari/537.71

**Comment by kyook** [comment]
This is a repeat of #3485

**Comment by raymond91125** [comment]
Hi Alexandra,

Thanks for the report. We are aware of this problem. However, the search 
function is not straight forward to optimize at the moment. Sorry for 
the inconvenience.

Best,

Raymond


On 03/06/2015 01:59 AM, no-reply@wormbase.org wrote:
> Question:
>
>   Hi, the search function in wormbase is case-sensitive. I think this 
> is not useful and it would be handier to have it work case-insensitive 
> if possible (try lin-15B vs lin-15b search)
>
> Submitted From:
>   sas-6 (gene) /species/c_elegans/gene/WBGene00012888#04-9ec5db8-10 
> <http://www.wormbase.org//species/c_elegans/gene/WBGene00012888#04-9ec5db8-10> 
>
>
> This issue has been assigned ticket number: #3665. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3665>.
>
> Reported by: alexandra bezler (alexandra.bezler@unil.ch)
> 06 Mar 15 10:03
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 
> (KHTML, like Gecko) Version/6.1 Safari/537.71
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
An easy workaround is to use the drop down menu to search for a specific class.

**Comment by tharris** [comment]
I don't think we should make the search case insensitive. UNC-22 and unc-22 are two different things.

**Comment by tharris** [comment]
I'm closing this issue. I don't believe that the search function should be case-insensitive. We have distinct biological identifiers that case of which matters.
