### ISSUE TITLE
  Hi, I have an account but have left t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3666]
<p>&nbsp;&nbsp;Hi, I have an account but have left the company I worked for and so cant pick up the password verification email. I'm happy to set up a new log-in but the only options that I can find are to log in with Facebook or Google. I certainly don't want to do either of those things. So my question is: how can I recover my log-in if I don't have access to the email prompt anymore OR how can set up a new account without having to use facebook of google?</p>

Reported by: Chri******** (c.j.******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by sibyl229** [comment]
Hi Chris,

Sorry to hear that you have trouble signing in. New account registration isn’t supported on WormBase site right now, but we are exploring a few login options that people will feel comfortable using.

I understand your concern with using Google to sign in. Let me explain what information is exchanged in our current Sign in with Google, and see if it helps. First, we only use Google to authenticate users, getting proof that the user is who they claim to be. It's similar to sending confirmation email to ensure the user is providing their own email addresses. We don’t share your WormBase activity with Google. Second, when we redirect you to Google sign in page, you are asked by Google to grant us permission to view your public google profile and email address. The information we actually collect is your name (on your public google profile), email address, and profile url.  Last, at anytime you can revoke WormBase's permission to access your Google profile, then we won’t be able to request your profile information from Google. To do this, you visit your account setting on Google, and look for “connected apps and services”.

We are also looking into having ORCID as an alternative to Google for user authentication. Will you be more comfortable using that instead?

Thanks for writing to us.

Sibyl

**Comment by tharris** [comment]
Considering this resolved. User concern addressed, no further follow up requests.
