### ISSUE TITLE
  Hi,  There is an error on the gcy-35 ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3667]
<p>&nbsp;&nbsp;Hi, <br/>There is an error on the gcy-35 "phenotype" field. An allele (ok769) is listed as "cell cleavage variant" with reference to WBPaper00038432. The allele in this paper is actually ok796, which is an allele of arf-1.2 - not gcy-35. Thus, there is no "cell cleavage variant" associated with gcy-35. <br/>Thanks,<br/>Mike O'Donnell</p>

Reported by: Mich************* (mike**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by kyook** [comment]
Hi Mike,

Thank you for finding and reporting this error.  I've fixed the annotation
in our local database, which will find its way to the website for WS249.

Thanks again for contacting us.
Best wishes,
Karen

On Fri, Mar 6, 2015 at 11:01 AM, <no-reply@wormbase.org> wrote:

> Question:
>
>   Hi,
> There is an error on the gcy-35 "phenotype" field. An allele (ok769) is
> listed as "cell cleavage variant" with reference to WBPaper00038432. The
> allele in this paper is actually ok796, which is an allele of arf-1.2 - not
> gcy-35. Thus, there is no "cell cleavage variant" associated with gcy-35.
> Thanks,
> Mike O'Donnell
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3667. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3667>.
>
>  Reported by: Michael O'Donnell (mikeod38@gmail.com)
> 06 Mar 15 19:05
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/41.0.2272.76 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
