### ISSUE TITLE
plg-1 gene curation

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#3668]
Hello,

It seems that the plg-1 gene is only half curated, despite having been identified quite a few years ago.
The molecular identification and genome location are missing. Data are from:
http://www.wormbase.org/resources/paper/WBPaper00032027#0--10 
The gene is knocked out by a retrotransposon insertion in the reference genome N2, but it can be molecularly anchored.  The start of it is F44E2.11. It would be good to update the curation.

The presence of the retr-1 gene is an indel polymorphism in some C. elegans wild isolates.

With best wishes,
Marie-Anne

**Comment by raymond91125** [comment]
Hi Marie-Anne,

Thanks for the note. I've entered a github ticket <https://github.com/WormBase/website/issues/3668>. You can track our follow ups there.

All the best,

raymond

**Comment by tuli** [comment]
Merge of plg-1 and  F44E2.11 pending with Tim

**Comment by tuli** [comment]
Dear Marie-Anne,

Thank you for brining this to our attention.
F44E2.11 has been assigned as plg-1. The update will be available in
release WS248 of WormBase.

As far as I can see, the location of the e2001 insertion is not specified.

Best wishes,

Mary Ann

On 6 March 2015 at 18:29, Marie Anne Felix <felix@biologie.ens.fr> wrote:
> Hello,
>
> It seems that the plg-1 gene is only half curated, despite having been
> identified quite a few years ago.
> The molecular identification and genome location are missing. Data are from:
> http://www.wormbase.org/resources/paper/WBPaper00032027#0--10
> The gene is knocked out by a retrotransposon insertion in the reference
> genome N2, but it can be molecularly anchored.  The start of it is F44E2.11.
> It would be good to update the curation.
>
> The presence of the retr-1 gene is an indel polymorphism in some C. elegans
> wild isolates.
>
> With best wishes,
> Marie-Anne
>
> --
> Marie-Anne Felix
> Institute of Biology of the Ecole Normale Supérieure (IBENS)
> 46 rue d'Ulm, 75230 Paris cedex 05, France
> 8th floor. Office: Room 801. Lab: Room 817.
> mail: felix@biologie.ens.fr
> Tel: +33-1-44-32-39-44
> http://www.ibens.ens.fr/?rubrique29&lang=en
> STRAINS: http://www.justbio.com/worms/index.php
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Mary Ann,

This is great, thanks. Note that e2001 is a _deletion _of the Cer1 
retrotransposon (named the /retr-1/ gene), not an insertion. The WBVar 
deletions at this locus have very different estimated sizes but the one 
that looks about right for CB4856 is WBVar02075632.
It seems from the Palopoli paper that they got the exact sequence of the 
junction.
see Supplements
"We assayed for the presence of the retrotransposon in the third exon of 
plg-1 by
performing paired PCRs on genomic DNA from each strain. Primers *e2.2F1 
and e2.2R1**
**amplify 599 bp in the absence of the insertion*, and primers e2.2F2 
and plgretro_e2.2R
amplify 658 bp in its presence."
*e2.2F1 CGCATAAAACGTCAGCAGAA**
**e2.2R1 ATTCGGAGTAGTCGGGTCCT*
e2.2F2 TCCACAAAACCTGCTGACTG

Matt Rockman (cc') may be the person to ask for the direct information.
This should allow to have the prediction of the full-length protein for 
PLG-1, even if pseudogenized in N2, with other exons continuing after 
retr-1.

Best wishes,
Marie-Anne


Le 09/03/2015 15:30, Mary Ann Tuli a écrit :
> Dear Marie-Anne,
>
> Thank you for brining this to our attention.
> F44E2.11 has been assigned as plg-1. The update will be available in
> release WS248 of WormBase.
>
> As far as I can see, the location of the e2001 insertion is not specified.
>
> Best wishes,
>
> Mary Ann
>
> On 6 March 2015 at 18:29, Marie Anne Felix <felix@biologie.ens.fr> wrote:
>> Hello,
>>
>> It seems that the plg-1 gene is only half curated, despite having been
>> identified quite a few years ago.
>> The molecular identification and genome location are missing. Data are from:
>> http://www.wormbase.org/resources/paper/WBPaper00032027#0--10
>> The gene is knocked out by a retrotransposon insertion in the reference
>> genome N2, but it can be molecularly anchored.  The start of it is F44E2.11.
>> It would be good to update the curation.
>>
>> The presence of the retr-1 gene is an indel polymorphism in some C. elegans
>> wild isolates.
>>
>> With best wishes,
>> Marie-Anne
>>
>> --
>> Marie-Anne Felix
>> Institute of Biology of the Ecole Normale Supérieure (IBENS)
>> 46 rue d'Ulm, 75230 Paris cedex 05, France
>> 8th floor. Office: Room 801. Lab: Room 817.
>> mail: felix@biologie.ens.fr
>> Tel: +33-1-44-32-39-44
>> http://www.ibens.ens.fr/?rubrique29&lang=en
>> STRAINS: http://www.justbio.com/worms/index.php
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>

-- 
Marie-Anne Felix
Institute of Biology of the Ecole Normale Supérieure (IBENS)
46 rue d'Ulm, 75230 Paris cedex 05, France
8th floor. Office: Room 801. Lab: Room 817.
mail: felix@biologie.ens.fr
Tel: +33-1-44-32-39-44
http://www.ibens.ens.fr/?rubrique29&lang=en
STRAINS: http://www.justbio.com/worms/index.php

**Comment by Paul-Davis** [comment]
Dear Marie-Anne,

I have also extended the annotation to contain the additional exon 
sequences and reclassified the gene as a Pseudogene because of the 
disruption caused by the transposon integration.

Thank you

Paul
