### ISSUE TITLE
  Hi, I am trying check protein aligner...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3669]
<p>&nbsp;&nbsp;Hi,<br/>I am trying check protein aligner for a few genes, but there is no way I can download as a file. Would be great if you can guide me as to how I can download it. Is there a way that I can submit a list of genes and be able to get protein aligner output downloaded for each of these genes.<br/>Thanks.</p>

Reported by: Ariz********* (amoh************************)  (obscured for privacy))
Submitted From: XNP-1 (protein) <a href="http://www.wormbase.org//species/c_elegans/protein/WP:CE17314#80637--10">/species/c_elegans/protein/WP:CE17314#80637--10</a>

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by raymond91125** [comment]
Hi Ariz,

I don't think you can download the alignment as vector graphics - texts, 
yes by copy and paste; color, no. Nor do I think you can submit multiple 
genes at once.

My colleagues may have more to add.

Sorry.

Raymond


On 03/06/2015 12:01 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> I am trying check protein aligner for a few genes, but there is no way 
> I can download as a file. Would be great if you can guide me as to how 
> I can download it. Is there a way that I can submit a list of genes 
> and be able to get protein aligner output downloaded for each of these 
> genes.
> Thanks.
>
> Submitted From:
>   XNP-1 (protein) /species/c_elegans/protein/WP:CE17314#80637--10 
> <http://www.wormbase.org//species/c_elegans/protein/WP:CE17314#80637--10>
>
> This issue has been assigned ticket number: #3669. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3669>.
>
> Reported by: Ariz Mohammad (amohammad@genetics.wustl.edu)
> 06 Mar 15 20:04
>
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) 
> Chrome/41.0.2272.76 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi Ariz,

I sent Tim the human-elegans bits, give a shout if need more.

Michael
