### ISSUE TITLE
  Which daf-16 isoform is deleted in da...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3671]
<p>&nbsp;&nbsp;Which daf-16 isoform is deleted in daf-16(mu86)I? </p>

Reported by: isab***************************  (obscured for privacy)
Submitted From: mu86 (variation) <a href="http://www.wormbase.org//species/c_elegans/variation/WBVar00089216#02-45-3">/species/c_elegans/variation/WBVar00089216#02-45-3</a>

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E)

**Comment by tuli** [comment]
Dear Isabelle,

Thank you for writing to WormBase.

mu86 is a large deletion and deletes parts of all the daf-16 isoforms.
You can see this in the Location widget of the
daf-16 Gene Summary page, and also (by clicking on that image) in the
Genome Browser. The Genome Browser gives you more information on each
isoform if you hover over it with your mouse.

I hope this answers your query.

Best wishes,

Mary Ann

On 9 March 2015 at 14:03,  <no-reply@wormbase.org> wrote:
> Question:
>
>   Which daf-16 isoform is deleted in daf-16(mu86)I?
>
> Submitted From:
>   mu86 (variation) /species/c_elegans/variation/WBVar00089216#02-45-3
>
> This issue has been assigned ticket number: #3671. Follow progress on our
> issue tracker.
>
> Reported by: Anonymous (isabelle.hellwig@zfp-zentrum.de)
> 09 Mar 15 14:06
>
> Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR
> 2.0.50727; .NET4.0C; .NET4.0E)
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
