### ISSUE TITLE
Proposal to retire the GFF post-processing script

### ISSUE THREAD

**Issue by tharris** [WormBase/website#3672]
CSHL and later OICR has always had a post-processing script of the build-supplied GFF files. 

For many years, this script was critical to providing a functioning genome browser. For example, creating appropriate gene -> transcript -> cds hierarchies with suitable names and labels.

With the release of the gene model and then much later GFF3, the need for this script has declined. It now only does this:

Here are the remnants of what the processing script does:

  next if $source eq 'assembly_tag'; # don't want 'em, don't need 'em                                                                                                    
  next if $method eq 'HOMOL_GAP';    # don't want that neither                                                                                                           
  next if $method eq 'intron' && $source ne 'RNASeq_splice';
  next if $source eq 'intron';

  # Fix the Chromosome IDs                                                                                                                                               
  $ref    =~ s/^CHROMOSOME_//;
  $group  =~ s/CHROMOSOME_//;

I suggest we remove this script from the workflow entirely. The GFF produced by the build team willl end up as the sole file used to drive the genome browser.

This has two consequences:

1. The web team will no longer be able to intervene at late stage to fix a broken GFF file. Any fixes will need to be processed at Hinton, redistributed to OICR and reloaded to new databases.

2. The databases for the genome browsers will contain ~500K more entries. I think this is okay.

**Comment by scottcain** [comment]
That would be fine with JBrowse, as it only processes the data it needs as opposed to GBrowse where all of the data are loaded.

**Comment by tharris** [comment]
I've disabled this step for WS248.
