### ISSUE TITLE
   

Reported by: Hann*****************...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3673]
<p>&nbsp;&nbsp;</p>

Reported by: Hann***************** (usto***************)  (obscured for privacy))
Submitted From: oac-50 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00020864#0137de94f-685a-3">/species/c_elegans/gene/WBGene00020864#0137de94f-685a-3</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by raymond91125** [comment]
page appears to be working fine.
