### ISSUE TITLE
  When I go to "dump a selection in FAS...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3674]
<p>&nbsp;&nbsp;When I go to "dump a selection in FASTA" on GBrowse, all that happens is the sequence zooms in. How do I fix this?</p>

Reported by: Mari* (mg30***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by scottcain** [comment]
Can you please give us a little more information, like what organism and region you were looking at, and specifically how you were trying to down load the FASTA?  Where you using the "Download Decorated FASTA File" option from the menu? Or the "export as ... FASTA" from the file menu?

**Comment by raymond91125** [comment]
Hi Marie,

We tried with three different browsers (Chrome, Firefox and Safari) on 
an iMac and each one produced an sequence output. Since "Zoom in" is the 
choice right above "Dump selection as FASTA", is it possible that you 
missed the selection?

If not, please provide specific parameters so that we can better 
reproduce the problem.

Thanks.

Raymond


On 03/10/2015 09:17 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   When I go to "dump a selection in FASTA" on GBrowse, all that 
> happens is the sequence zooms in. How do I fix this?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3674. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3674>.
>
> Reported by: Marie (mg3088@columbia.edu)
> 10 Mar 15 16:20
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 
> (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
![gb_areaselection](https://cloud.githubusercontent.com/assets/619520/6581514/a784945a-c714-11e4-8985-4494cb228cae.png)

**Comment by raymond91125** [comment]
@scottcain FYI

**Comment by raymond91125** [comment]
Hi,

> We tried with three different browsers (Chrome, Firefox and Safari) on an iMac and each one produced an sequence output. Since "Zoom in" is the choice right above "Dump selection as FASTA", is it possible that you missed the selection?
> 
No because on other computers than mine I manage to access the « Dump selection as FASTA » 

> If not, please provide specific parameters so that we can better reproduce the problem.
I tried with Chrome Firefox and Safari.
I have the latest version for all of them.

I manage to get the FASTA seq when I hit the button launch

I have erased all the cookies.

Don’t know why is it doing that.

Thanks

Marie


> 
> On 03/10/2015 09:17 AM, no-reply@wormbase.org <mailto:no-reply@wormbase.org> wrote:
>> Bug Report
>>   When I go to "dump a selection in FASTA" on GBrowse, all that happens is the sequence zooms in. How do I fix this?
>> 
>> Submitted From: 
>>   support /tools/support <http://www.wormbase.org//tools/support>
>> This issue has been assigned ticket number: #3674. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3674>.
>> 
>> 
>> Reported by: Marie (mg3088@columbia.edu <mailto:mg3088@columbia.edu>) 
>> 10 Mar 15 16:20 
>> 
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12 
>> 
>> This question was reported via the web interface at wormbase.org. You can also email us <mailto:help@wormbase.org> directly.
>> 
>> -- 
>> -- 
>> You received this message because you are subscribed to the "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
>> 
>> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.
> 
> 
> -- 
> __
> Raymond Lee
> raymond@caltech.edu <mailto:raymond@caltech.edu>
> http://www.WormBase.org/ <http://www.wormbase.org/>
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687
> 
> 

-------------------------------------------------------------------------------
Marie Gendrel, PhD
Post Doctoral Research Scientist, Hobert lab
Columbia University College of Physicians and Surgeons
Department of Biochemistry and Molecular Biophysics
701W.168St; HHSC 724
10032 New York, NY
Phone: 212-305-0065
Fax: 212-342-1810
-------------------------------------------------------------------------------

**Comment by raymond91125** [comment]
Hi Marie,

Thanks for the clarification. What you describe sounds like a problem 
specific to your computer. I can't reproduce it from my end.

One last ditch. When you mouse over a piece of hypertext, you may see 
the URL displayed at the bottom of the browser window (left bottom 
corner). Try moving your mouse around in the pull down menu to see if 
there is mis-alignment and what not.

Cheers,

Raymond


On 03/11/2015 12:00 PM, Gendrel Marie wrote:
> Hi,
>
>> We tried with three different browsers (Chrome, Firefox and Safari) 
>> on an iMac and each one produced an sequence output. Since "Zoom in" 
>> is the choice right above "Dump selection as FASTA", is it possible 
>> that you missed the selection?
>>
> No because on other computers than mine I manage to access the « Dump 
> selection as FASTA »
>
>> If not, please provide specific parameters so that we can better 
>> reproduce the problem.
> I tried with Chrome Firefox and Safari.
> I have the latest version for all of them.
>
> I manage to get the FASTA seq when I hit the button launch
>
> I have erased all the cookies.
>
> Don’t know why is it doing that.
>
> Thanks
>
> Marie
>
>
>>
>> On 03/10/2015 09:17 AM,no-reply@wormbase.orgwrote:
>>> Bug Report
>>>
>>>   When I go to "dump a selection in FASTA" on GBrowse, all that 
>>> happens is the sequence zooms in. How do I fix this?
>>>
>>> Submitted From:
>>>   support/tools/support <http://www.wormbase.org//tools/support>
>>>
>>> This issue has been assigned ticket number: #3674. Follow progress 
>>> on ourissue tracker <https://github.com/WormBase/website/issues/3674>.
>>>
>>>
>>> Reported by: Marie (mg3088@columbia.edu)
>>> 10 Mar 15 16:20
>>>
>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 
>>> (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12
>>>
>>> This question was reported via the web interface at wormbase.org 
>>> <http://wormbase.org>. You can alsoemail us 
>>> <mailto:help@wormbase.org>directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the 
>>> "WormBase: help" group.
>>> To post to this group, send email tohelp@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>> To unsubscribe from this group and stop receiving emails from it, 
>>> send an email tohelp+unsubscribe@wormbase.org 
>>> <mailto:help+unsubscribe@wormbase.org>.
>>
>>
>> -- 
>> __
>> Raymond Lee
>> raymond@caltech.edu
>> http://www.WormBase.org/
>> California Institute of Technology
>> Division of Biology and Biological Engineering
>> Mail Code 156-29
>> Pasadena, CA 91125
>> USA
>> tel: 626.395.2687
>>
>>
>
> -------------------------------------------------------------------------------
> Marie Gendrel, PhD
> Post Doctoral Research Scientist, Hobert lab
> Columbia University College of Physicians and Surgeons
> Department of Biochemistry and Molecular Biophysics
> 701W.168St; HHSC 724
> 10032 New York, NY
> Phone: 212-305-0065
> Fax: 212-342-1810
> -------------------------------------------------------------------------------
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
close for now because there's anything concrete we could do.
