### ISSUE TITLE
  I was told to come to this site to ut...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3675]
<p>&nbsp;&nbsp;I was told to come to this site to utilize a certain tool pertaining to C. elegans growth patterns according to what temperature they are incubated at.  However, I do not know where this tool is on this site.  Could you help me locate the tool?<br/>Thanks</p>

Reported by: eeba*******************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; HPNTDF; .NET4.0C; .NET CLR 1.1.4322; rv:11.0) like Gecko

**Comment by raymond91125** [comment]
Hi,

Your description does not ring any bells for me either. Is it possible 
for you to get more specific instructions? From Professor Song?

Thanks.

Raymond


On 03/11/2015 12:11 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I was told to come to this site to utilize a certain tool pertaining 
> to C. elegans growth patterns according to what temperature they are 
> incubated at. However, I do not know where this tool is on this site. 
> Could you help me locate the tool?
> Thanks
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3675. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3675>.
>
> Reported by: Anonymous (eebartnicki@oakland.edu)
> 11 Mar 15 19:14
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 
> 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 
> 6.0; HPNTDF; .NET4.0C; .NET CLR 1.1.4322; rv:11.0) like Gecko
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
no reply.
