### ISSUE TITLE
  Hi, I would like to know if you have ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3676]
<p>&nbsp;&nbsp;Hi,<br/>I would like to know if you have several whole genomes (sequenced and aligned) of different strains (at least 30) of C. elegant ?<br/>I thank you very much.<br/>Gabrielle</p>

Reported by: Gabr***** (gabr************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.74.9 (KHTML, like Gecko) Version/6.1.2 Safari/537.74.9

**Comment by tuli** [comment]
Dear Gabrielle,

Thank you for writing to WormBase.

The only C. elegans strain we have the whole genome sequence of is N2.

The gff files hold the SNP information for other sequenced strains
which enables users to extract the information they need.

ftp://ftp.wormbase.org/pub/wormbase/releases/WS247/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS247.annotations.gff3.gz

I hope this answers you question,

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
