### ISSUE TITLE
wordpress

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3677]
it seems like the admin interface to the wordpress blog is not reacting whatsoever, so I can't put in new non-parasite posts at the moment ;-)

**Comment by epaule** [comment]
![screenshot from 2015-03-13 16 59 19](https://cloud.githubusercontent.com/assets/20523/6643258/dd662b98-c9a2-11e4-8291-8eed4d85ca25.png)

**Comment by tharris** [comment]
Should be fixed!
