### ISSUE TITLE
  how do i find the most match gene hom...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3678]
<p>&nbsp;&nbsp;how do i find the most match gene homolog to my test human protein sequence </p><p>What were you doing? <br />&nbsp;&nbsp;I put the protein sequence: 
MPRPGRNTYSDQKPPYSYISLTAMAIQSSPEKMLPLSEIYKFIMDRFPYYRENTQRWQNSLRHNLSFNDCFIKIPRRPDQPGKGSFWALHPSCGDMFENGSFLRRRKRFKVLKSDHLAPSKPADAAQYLQQQAKLRLSALAASGTHLPQMPAAAYNLGGVAQPSGFKHPFAIENIIAREYKMPGGLAFSAMQPVPAAYPLPNQLTTMGSSLGTGWPHVYGSAGMIDSATPISMASGDYSAYGVPLKPLCHAAGQTLPAIPVPIKPTPAAVPALPALPAPIPTLLSNSPPSLSPTSSQTATSQSSPATPSETLTSPASALHSVAVH  

and i wanted to know the molecular name of the of the C. elegans gene that is the best match</p>

Reported by: Marw* (zakw*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by raymond91125** [comment]
Hi Marwa,

You can use the Blast/Blat tool.

Raymond

On 03/12/2015 05:15 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   how do i find the most match gene homolog to my test human protein 
> sequence
>
> What were you doing?
>   I put the protein sequence: 
> MPRPGRNTYSDQKPPYSYISLTAMAIQSSPEKMLPLSEIYKFIMDRFPYYRENTQRWQNSLRHNLSFNDCFIKIPRRPDQPGKGSFWALHPSCGDMFENGSFLRRRKRFKVLKSDHLAPSKPADAAQYLQQQAKLRLSALAASGTHLPQMPAAAYNLGGVAQPSGFKHPFAIENIIAREYKMPGGLAFSAMQPVPAAYPLPNQLTTMGSSLGTGWPHVYGSAGMIDSATPISMASGDYSAYGVPLKPLCHAAGQTLPAIPVPIKPTPAAVPALPALPAPIPTLLSNSPPSLSPTSSQTATSQSSPATPSETLTSPASALHSVAVH 
> and i wanted to know the molecular name of the of the C. elegans gene 
> that is the best match
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3678. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3678>.
>
> Reported by: Marwa (zakwani44@hotmail.com)
> 12 Mar 15 12:19
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 
> (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Lower E-value means less likely to happen by chance.

Raymond
