### ISSUE TITLE
  I noticed a recent paper on plp-1 in ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3681]
<p>&nbsp;&nbsp;I noticed a recent paper on plp-1 in which they used a deletion allele to describe a sterile phenotype and an Unc phenotype.<br/>Lalani et al.<br/>The American Journal of Human Genetics 95, 579–583, November 6, 2014</p>

Reported by: Andy******* (andy**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4

**Comment by raymond91125** [comment]
Karen,
I was able to access from here at Caltech.
Attached are the paper and Supplemental files.
Gary

I forgot to download mmc3.mp4....just wt movement.  mmc4.mp4 is the plp-1
mutant...barely moves...

> Dear Andy,
>
> Thank you for alerting us to this paper; it would not be picked up by our
> paper pipeline since the authors do not mention elegans in their abstract.
> Unfortunately I can't get access to this paper, I can't tell if it is
> because I am not on the Caltech campus or if the journal actually does
> require a subscription.
>
> Kimberly or Daniel,  do you know if we can get this article?
>
> Karen

**Comment by vanaukenk** [comment]
This paper has been added to postgres as WBPaper00046541.
