### ISSUE TITLE
  PAR-2 sequences are not present. I'm ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3682]
<p>&nbsp;&nbsp;PAR-2 sequences are not present. I'm instead getting an error message.</p>

Reported by: Shaw******** (snj2****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by sibyl229** [comment]
Hi Shawn,

Sorry about the inconvenience. The error on par-2 sequences is fixed now. http://www.wormbase.org/species/c_elegans/gene/WBGene00003917#0f--3 <http://www.wormbase.org/species/c_elegans/gene/WBGene00003917#0f--3> 

Thanks for reporting the issue.

Sibyl
