### ISSUE TITLE
  I deleted the tracks that are found i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3685]
<p>&nbsp;&nbsp;I deleted the tracks that are found in the genome browser under "select track" mistakenly, and i want to return them but i didn't know how to do that. <br/>I also want to ask, how do I use the genome browser to find the restriction enzymes used to cut a gene ? I tried to use the scroll-zoom controls to see a specific site but they don't work with me.  </p>

Reported by: marw* (zakw*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by xdwang** [comment]
Hi Marwa,
I am attaching a few screen shots for you to understand the steps:
1. search your region first, and configure annotate restriction sites



2. select enzymes of your interests:




3. on the bottom of this page, select tracks. ‘Restriction Sites’ is on the last line and back to browser, you should see all sites on GBrowse.


Good luck and let us know if you have further issues.

Xiaodong


Xiaodong Wang, Ph.D
Wormbase Curator
xdwang@caltech.edu
http://www.wormbase.org
California Institute of Technology
Division of Biology 156-29
Pasadena, CA 91125
USA
