### ISSUE TITLE
  Is there a way to get the promoter se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3686]
<p>&nbsp;&nbsp;Is there a way to get the promoter sequence and size for the genes in this database?! <br/>I would like to get the promoter sequence for the ttx-3, cat-1, fax-1 and various other genes.. </p>

Reported by: bila*********************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Linux; Android 4.2.2; Micromax A177 Build/MicromaxA177) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36

**Comment by vanaukenk** [comment]
Hello,

Thanks for writing to WormBase.

For retrieving promoter sequences you can use the Genome Browser (GBrowse).

To use the Genome Browser, first go to the gene summary page and then
click on the Location widget on the left side of the page.  In the
location widget, click on the gene model to go to the GBrowse view (you
can also go directly to GBrowse from the Tools menu at the top of each WB
page).

Select the region upstream of each gene that you want by clicking on the
scale bar in the Details section of the browser and then dragging the
resulting box from the first exon of the gene to the point at which you've
outlined all of the sequence you need.  When you've finished you'll then
automatically be given the option to 'Dump selection as FASTA' in the
resulting pop-up window.

Best,
--Kimberly Van Auken





>
> Question:
>   Is there a way to get the promoter sequence and size for the genes in
> this database?!
> I would like to get the promoter sequence for the ttx-3, cat-1, fax-1 and
> various other genes..
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #3686. Follow progress on our
> issue tracker.
>
>   Reported by: Anonymous (bilaljamadar489@gmail.com)
>  15 Mar 15 07:54
>
>  Mozilla/5.0 (Linux; Android 4.2.2; Micromax A177 Build/MicromaxA177)
> AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile
> Safari/537.36     This question was reported via the web interface at
> wormbase.org. You can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
