### ISSUE TITLE
  Hi, I have a suggestion/request:  Can...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3688]
<p>&nbsp;&nbsp;Hi, I have a suggestion/request:  Can you make it possible to customize which RNAseq datasets are displayed in the "expression" widget?  This widget used to be really useful, but as the number of RNAseq datasets has grown, the bar graph has gotten harder and harder to read, and it's difficult to make sense of the table below because there are so many entries. <br/>Thanks for all your hard work!</p>

Reported by: Dan ********* (ddic*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Dan,

Thanks very much for your feedback and the feature request.

The WormBase web team has been working on improving the display for the
RNAseq datasets and a new display is now visible on the gene pages on our
staging site: http://staging.wormbase.org

Please take a look and let us know what you think.

I'll let the web team comment more about the feasibility of customizing
the display.

Best,
--Kimberly Van Auken


>
> Feature
> Request
>   Hi, I have a suggestion/request:  Can you make it possible to customize
> which RNAseq datasets are displayed in the "expression" widget?  This
> widget used to be really useful, but as the number of RNAseq datasets
> has grown, the bar graph has gotten harder and harder to read, and it's
> difficult to make sense of the table below because there are so many
> entries.
> Thanks for all your hard work!
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #3688. Follow progress on our
> issue tracker.
>
>   Reported by: Dan Dickinson (ddickins@live.unc.edu)
>  17 Mar 15 13:02
>
>  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/41.0.2272.89 Safari/537.36     This question was
> reported via the web interface at wormbase.org. You can also email us
> directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>

**Comment by vanaukenk** [comment]
Hi Kimberly, 

Thanks for getting back to me.  I like the new display much better! It's a lot easier to read.  My only suggestion would be to add a descriptive title instead of (or in addition to) the accession numbers that are currently shown.  For example, in the left column it would say "Hillier modENCODE deep sequencing" in place of "SRP000401."  The ability to display only certain data sets would be nice, too, but this is already a big improvement. 

Thanks, 
Dan 

***********************************************
Daniel J. Dickinson, Ph.D.
Postdoctoral fellow, Goldstein Lab
University of North Carolina
650-815-1923
ddickins@live.unc.edu
