### ISSUE TITLE
  Are the numbers below the sequence fe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3690]
<p>&nbsp;&nbsp;Are the numbers below the sequence features for base pairs?</p>

Reported by: brat*************  (obscured for privacy)
Submitted From: acn-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00000039#0-9e-10">/species/c_elegans/gene/WBGene00000039#0-9e-10</a>

Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by xdwang** [comment]
Hi,

Can you be more specific? What numbers are you referring to?

Xiaodong Wang
> On Mar 17, 2015, at 2:13 PM, no-reply@wormbase.org wrote:
> 
> Question: 
>   Are the numbers below the sequence features for base pairs?
> 
> Submitted From: 
>   acn-1 (gene) /species/c_elegans/gene/WBGene00000039#0-9e-10 <http://www.wormbase.org//species/c_elegans/gene/WBGene00000039#0-9e-10>
> This issue has been assigned ticket number: #3690. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3690>.
> 
> 
> Reported by: Anonymous (brathwad@kean.edu <mailto:brathwad@kean.edu>) 
> 17 Mar 15 18:17 
> 
> Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E; rv:11.0) like Gecko 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125
