### ISSUE TITLE
  I have a list of wormbase ids (i.e. W...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3692]
<p>&nbsp;&nbsp;I have a list of wormbase ids (i.e. WBGene00226448, WBGene00223031, WBGene00227024, WBGene00220530, WBGene00228076, WBGene00223708)  is there any way to automatically extract gene ontology information given these data?  I tried David but it didn't recognize my names.  I tried Wormbase Converter, to get gene names that I would then try to use in David, but that didn't work either.  I can cut and paste them one by one in your site and get the informatin I need, but I have several hundred.  Can I script to access that information?  Thank you!!</p>

Reported by: Jess********* (jgra************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by mwatts15** [comment]
What data do you need? Most of the widgets have a download link. If you open up the developer console in Chrome, and look under the network tag, when you click on any of the radio buttons (json, html, yaml, xml) you should see the URL corresponding to the data in that widget. From there, if you have some scripting knowledge, it should be fairly easy to do in Python.

I can post an example if you would like.

**Comment by vanaukenk** [comment]
Dear Jessica,

Thanks for writing to WormBase.

You have a couple of different options for retrieving GO annotations for
WB genes.

The first is to work directly with the Gene Association File (GAF) that is
submitted to the GO Consortium.  This file has the most complete set of GO
annotations for C. elegans and is available here:

http://geneontology.org/page/download-annotations

Note that in this file there is a mixture of both UniProtKB and WB Gene
identifiers; the UniProtKB identifiers can be converted to WB Gene
identifiers using the gp2protein.wb mapping file available here:

http://www.geneontology.org/gp2protein/

or the xrefs.txt file available here:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/

With the coming WS248 release of WormBase, all annotations in the WB GAF
file will be mapped solely to WBGene IDs, so you won't need to do the
conversion in the near future.

You can also use WormMine to retrieve basic GO annotation information. 
WormMine is accessible under the Tools menu at the top left of each WB
page, and under the Templates tab there is a sample query for retrieving
GO terms, Evidence Codes, and References for a gene.  In your case, you
would need to substitute the specific gene in the template with your list
of WBGene IDs.

If you are interested in performing enrichment analyses with your gene
lists, I would recommend using the Panther tools for gene analysis, as
they have the most up-to-date annotation and ontology files:

http://pantherdb.org/

Please feel free to contact me if you need any additional help.

Best,
--Kimberly Van Auken


>
> How
> Do
> I
> ...?
>   I have a list of wormbase ids (i.e. WBGene00226448, WBGene00223031,
> WBGene00227024, WBGene00220530, WBGene00228076, WBGene00223708)  is
> there any way to automatically extract gene ontology information given
> these data?  I tried David but it didn't recognize my names.  I tried
> Wormbase Converter, to get gene names that I would then try to use in
> David, but that didn't work either.  I can cut and paste them one by one
> in your site and get the informatin I need, but I have several hundred.
> Can I script to access that information?  Thank you!!
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #3692. Follow progress on our
> issue tracker.
>
>   Reported by: Jessica Grant (jgrant@smith.edu)
>  18 Mar 15 18:15
>
>  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/41.0.2272.89 Safari/537.36     This question was
> reported via the web interface at wormbase.org. You can also email us
> directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>

**Comment by vanaukenk** [comment]
Thank you!  This is exactly what I needed.

:)

Jessica

On Wed, Mar 18, 2015 at 2:44 PM, <vanauken@caltech.edu> wrote:

> Dear Jessica,
>
> Thanks for writing to WormBase.
>
> You have a couple of different options for retrieving GO annotations for
> WB genes.
>
> The first is to work directly with the Gene Association File (GAF) that is
> submitted to the GO Consortium.  This file has the most complete set of GO
> annotations for C. elegans and is available here:
>
> http://geneontology.org/page/download-annotations
>
> Note that in this file there is a mixture of both UniProtKB and WB Gene
> identifiers; the UniProtKB identifiers can be converted to WB Gene
> identifiers using the gp2protein.wb mapping file available here:
>
> http://www.geneontology.org/gp2protein/
>
> or the xrefs.txt file available here:
>
>
> ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/
>
> With the coming WS248 release of WormBase, all annotations in the WB GAF
> file will be mapped solely to WBGene IDs, so you won't need to do the
> conversion in the near future.
>
> You can also use WormMine to retrieve basic GO annotation information.
> WormMine is accessible under the Tools menu at the top left of each WB
> page, and under the Templates tab there is a sample query for retrieving
> GO terms, Evidence Codes, and References for a gene.  In your case, you
> would need to substitute the specific gene in the template with your list
> of WBGene IDs.
>
> If you are interested in performing enrichment analyses with your gene
> lists, I would recommend using the Panther tools for gene analysis, as
> they have the most up-to-date annotation and ontology files:
>
> http://pantherdb.org/
>
> Please feel free to contact me if you need any additional help.
>
> Best,
> --Kimberly Van Auken
>
>
> >
> > How
> > Do
> > I
> > ...?
> >   I have a list of wormbase ids (i.e. WBGene00226448, WBGene00223031,
> > WBGene00227024, WBGene00220530, WBGene00228076, WBGene00223708)  is
> > there any way to automatically extract gene ontology information given
> > these data?  I tried David but it didn't recognize my names.  I tried
> > Wormbase Converter, to get gene names that I would then try to use in
> > David, but that didn't work either.  I can cut and paste them one by one
> > in your site and get the informatin I need, but I have several hundred.
> > Can I script to access that information?  Thank you!!
> > Submitted From:
> >   support /tools/support
> >  This issue has been assigned ticket number: #3692. Follow progress on
> our
> > issue tracker.
> >
> >   Reported by: Jessica Grant (jgrant@smith.edu)
> >  18 Mar 15 18:15
> >
> >  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36
> (KHTML,
> > like Gecko) Chrome/41.0.2272.89 Safari/537.36     This question was
> > reported via the web interface at wormbase.org. You can also email us
> > directly.
> >   --
> >  --
> >  You received this message because you are subscribed to the "WormBase:
> > help" group.
> >  To post to this group, send email to help@wormbase.org
> >  To unsubscribe from this group, send email to
> >  help+unsubscribe@wormbase.org
> >  For more options, visit this group at
> >  http://groups.google.com/a/wormbase.org/group/help?hl=en
> >
> >
> >   To unsubscribe from this group and stop receiving emails from it, send
> > an email to help+unsubscribe@wormbase.org.
> >
>
>
>


-- 
Jessica Grant
Research Associate, Williams Lab

205C Ford Hall
Smith College
Northampton, MA
413-585-4341
