### ISSUE TITLE
Collapse redundant citations in Interaction-based Phenotypes table in Phentoypes widget on gene pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3693]
As an extension of issue #3432 

from @kyook 

Is it possible to collapse the citations to only show one unique citation? For example for the eight interactions that have the same phenotype of engulfment variation all come from the same reference, it might make the display a little cleaner. I can understand if this is not doable, and it is certainly low priority.
Thanks again for your help.

**Comment by chris-grove** [comment]
Just to add a screenshot for clarification:

![screen shot 2015-03-18 at 2 58 35 pm](https://cloud.githubusercontent.com/assets/611382/6720333/580da30a-cd7f-11e4-9da1-16aef80f4a8d.png)

@kyook @sibyl229  
I'm wondering whether it might be better, actually, to keep all the citations in line with the associated interactions because, if there are multiple citations for the same phenotype and each is compacted, it may be very difficult to ascertain which citation corresponds to which interaction. Thoughts?

**Comment by tharris** [comment]
Sometimes citations aren't displayed directly, but hidden behind a toggle. I've always thought they created a lot of visual noise and would be best as a mouseover. With a display like that, we can display all the unique pieces of evidence supporting any assumption without having to collate.

**Comment by dasmoth** [comment]
I agree about the toggles adding visual noise.  However, please don't go down the important-information-in-mouseovers route: it's a disaster for users on touch-screens, and can be hard to discover for everyone else.

**Comment by tharris** [comment]
@chris-grove it sounds like you have changed your mind on this and would prefer each interaction to be directly annotated as it is with its supporting citation(s), instead of collapsing citations. If that is so, please close this ticket.

**Comment by chris-grove** [comment]
@tharris  This original issue was requested by @kyook so I don't want to close it without her go ahead or input

**Comment by kyook** [comment]
I still vote for collapsing the citations when they are the same.

However, I'd like to see an example where there are multiple citations for
the same interaction.  I'm thinking in that case there should be
concatenation of the citations inline with the specific interaction.

Karen


On Wed, Mar 18, 2015 at 3:01 PM, Chris Grove <notifications@github.com>
wrote:

> Just to add a screenshot for clarification:
>
> [image: screen shot 2015-03-18 at 2 58 35 pm]
> <https://cloud.githubusercontent.com/assets/611382/6720333/580da30a-cd7f-11e4-9da1-16aef80f4a8d.png>
>
> @kyook <https://github.com/kyook> @sibyl229 <https://github.com/sibyl229>
>
> I'm wondering whether it might be better, actually, to keep all the
> citations in line with the associated interactions because, if there are
> multiple citations for the same phenotype and each is compacted, it may be
> very difficult to ascertain which citation corresponds to which
> interaction. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3693#issuecomment-83200351>.
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
