### ISSUE TITLE
Jbrowse tracks for C.remanei

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3699]
I think the C.remanei version on JBrowse lost quite a few of its gene tracks.

**Comment by scottcain** [comment]
Odd.  It's not clear what happened, though I imagine it must have been during the build.  The JBrowse instance at jbrowse.wormbase.org is for build 246; the JBrowse instance at http://dev.wormbase.org:9003/ is for 248 and it has five gene tracks for remanei, so whatever it was appears to have been fixed.  

Side note: GBrowse has six gene tracks, but JBrowse doesn't support the "Coding segments" glyph, so it only has five.
