### ISSUE TITLE
GFF2 updates for WS247

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3700]
we fixed some problems with Tier 2 GFF2 files found on the FTP server. Can you resync the files from one of the Hinxton servers?

* release/WS247/species/c_japonica/PRJNA12591/c_japonica.PRJNA12591.WS247.annotations.gff2.gz 
* release/WS247/species/c_remanei/PRJNA53967/c_remanei.PRJNA53967.WS247.annotations.gff2.gz 
* release/WS247/species/c_briggsae/PRJNA10731/c_briggsae.PRJNA10731.WS247.annotations.gff2.gz 
* release/WS247/species/c_brenneri/PRJNA20035/c_brenneri.PRJNA20035.WS247.annotations.gff2.gz
* release/WS247/CHECKSUMS

**Comment by epaule** [comment]
you can add to the list of files that need resyncing:
* releases/WS247/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS247.annotations.gff2.gz
* releases/WS247/species/b_malayi/PRJNA10729/b_malayi.PRJNA10729.WS247.annotations.gff2.gz
* releases/WS247/species/o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS247.annotations.gff2.gz

**Comment by tharris** [comment]
Done.
