### ISSUE TITLE
  Hello, I know that with the previous ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3701]
<p>&nbsp;&nbsp;Hello,<br/>I know that with the previous version of the site and previous release cycle of WormBase every 10-th or 5-th release was sort of stable, suitable for citing and you provided a freeze of the website. Is it still so with the current site or every release can be used?<br/>Thank you in advance for the support. I looked at recent publications and the wiki, but I could not find this data.<br/>Best regards<br/>Georgi</p>

Reported by: ggec********  (obscured for privacy)
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by vanaukenk** [comment]
Dear Georgi,

Thanks for writing to WormBase.

WormBase no longer officially designates periodic releases as "frozen"
releases.

For each release of the database, all files are retained should users need
to verify the result of any analysis.

Our ftp site contains files for WB releases here:

ftp://ftp.wormbase.org/../pub/wormbase/releases/

If there is any data that you are specifically looking for, please let us
know.

Best,
--Kimberly Van Auken




>
> Question:
>   Hello,
> I know that with the previous version of the site and previous release
> cycle of WormBase every 10-th or 5-th release was sort of stable, suitable
> for citing and you provided a freeze of the website. Is it still so with
> the current site or every release can be used?
> Thank you in advance for the support. I looked at recent publications and
> the wiki, but I could not find this data.
> Best regards
> Georgi
> Submitted From:
>   home /#01-23-6
>  This issue has been assigned ticket number: #3701. Follow progress on our
> issue tracker.
>
>   Reported by: Anonymous (ggeca@bas.bg)
>  23 Mar 15 13:42
>
>  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
>    This question was reported via the web interface at wormbase.org. You
> can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
