### ISSUE TITLE
  this paper should be cited as well do...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3702]
<p>&nbsp;&nbsp;this paper should be cited as well<br/>doi:10.1038/nsmb.2557</p>

Reported by: alex************ (alex********************)  (obscured for privacy))
Submitted From: shc-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00018788#04-9ec5db8-10-9e">/species/c_elegans/gene/WBGene00018788#04-9ec5db8-10-9e</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML, like Gecko) Version/6.1 Safari/537.71

**Comment by vanaukenk** [comment]
Dear Alexandra,

Thanks very much for bringing this paper to our attention.

We get most of our papers from PubMed and this one had not been indexed
for C. elegans.

I'll add it to the WormBase bibliography and it will be included in
WormBase release WS249.

Best,
--Kimberly Van Auken


>
> Content
> Correction
>   this paper should be cited as well
> doi:10.1038/nsmb.2557
> Submitted From:
>   shc-1 (gene) /species/c_elegans/gene/WBGene00018788#04-9ec5db8-10-9e
>  This issue has been assigned ticket number: #3702. Follow progress on our
> issue tracker.
>
>   Reported by: alexandra Bezler (alexandra.bezler@unil.ch)
>  24 Mar 15 16:07
>
>  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML,
> like Gecko) Version/6.1 Safari/537.71     This question was reported via
> the web interface at wormbase.org. You can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
