### ISSUE TITLE
  Hi, I am interested on finding DNA mo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3704]
<p>&nbsp;&nbsp;Hi,<br/>I am interested on finding DNA motif patterns of 5 to 10 bases in C. elegans genome not coincident with restriction enzymes sequences. Is there a way to do that? I need more than 10 bases for blast...<br/>Many thanks,<br/>Paola</p>

Reported by: p j (paol*******************)  (obscured for privacy))
Submitted From: Blast/Blat <a href="http://www.wormbase.org//tools/blast_blat">/tools/blast_blat</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by xdwang** [comment]
Hi Paola,

If you have motif PWM or PFM, you can refer to the following instruction to find the motif in the genome region of your interest. This is a wormbook chapter we are working on.
2.4 PWM/PFM in GBrowse

With the MotifFinder plugin, GBrowse will find sequence-specific motifs using PWM/PFM and display results graphically as tracks in the genome browse. First, open up GBrowse with the region of your interests. Choose ‘Annotate Sequence Motif’ from dropdown list and configure.


Then you can copy and paste of your own defined PFM, or choose WormBase annotated PFM, and select tracks on the bottom of the page.



You will get all motifs of interest showing up in the region.


You can also try to find your motif on JBrwose, which is under development right now:

http://jbrowse.wormbase.org/?data=data%2Fc_elegans_PRJNA13758&loc=I%3A6037110..9051595&tracks=DNA&highlight= <http://jbrowse.wormbase.org/?data=data/c_elegans_PRJNA13758&loc=I:6037110..9051595&tracks=DNA&highlight=>




Good luck,

Xiaodong Wang 

Wormbase Curator

**Comment by scottcain** [comment]
Does this work currently for GBrowse?  Unless I'm doing something wrong, I don't think so.  (I think the plugin is crashing, but I haven't been able to verify what's really happening--I'll take a look on my own server.)

Also, about JBrowse: you can't search with PWMs but you can search with regular expressions.  To add a sequence search track, select "Add sequence search track" from the file menu at the top of the window.  If you'd like help writing a regular expression to look for the motif of interest let me know.

**Comment by xdwang** [comment]
GBrowse MotifFinder is not working right now. It worked a few days ago. Can someone from web team have a look please? Thanks.

**Comment by scottcain** [comment]
@tharris do you have any idea why this might have stopped working (a library update or the like)?

**Comment by scottcain** [comment]
This works as expected.

I do not even want to document what the problem was, nor how many hours I spent trying to debug, but here goes: when you hit "go" next to the plugin dropdown menu, I expected a track to be created but that doesn't happen (which is why I thought there was buggy behavior).  What actually happens is that GBrowse adds a track that you can select to add to the display, requiring you to go to the "select tracks" tab, scroll to the bottom of the list of tracks, and check the box next to "Sequence Motif" label in the Analysis section.  This works on both staging and production right now.
