### ISSUE TITLE
Cis_regulatory_element type

### ISSUE THREAD

**Issue by draciti** [WormBase/website#3705]
Hi Sibyl,

in WS247 we have some Expression objects that have as 'Type' tag Reporter_gene AND Cis_regulatory
_element-see screenshot.

could you please display also Cis_regulatory_element in the Type column in the table in the Expression widget on the gene page?
http://www.wormbase.org/species/c_elegans/gene/WBGene00000437#1--10

![screen shot 2015-03-25 at 10 48 44 am](https://cloud.githubusercontent.com/assets/901243/6832554/947f8078-d2e4-11e4-89b4-cc8392507580.png)

thanks!

**Comment by draciti** [comment]
Sybil, when you have a moment could you please take a look at this? thanks

**Comment by sibyl229** [comment]
Hi @draciti the Type column in expression pattern tables should now display multiple type, if they exists. For example here: http://staging.wormbase.org/species/c_elegans/gene/WBGene00000437#1--10
I will be working on the broken expression image next :)

**Comment by draciti** [comment]
thanks Sibyl! Closing
