### ISSUE TITLE
Searching for conserved miRNAs in other species

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#3715]
I was trying to find a gene page for Cbr-, Cre-, and Cbn-let-7 but the searches come up empty.

Are there WB gene IDs for these conserved miRNA genes?

Thanks,
--Kimberly

**Comment by epaule** [comment]
Hi Kimberley,

we used RFam models to predict ncRNAs in Tier II worms.
But the existing let-7 data in Brugia came from miRBase and not from RFam,
so I guess the let-7 RFam model is a bit "suboptimal".
Also the miRBase annotation of Bma-let-7 missed the second mature
transcript forming half of the stem, as you can see in the attached
screenshot.

And, while I can't speak about Caenorhabditis (as the HAL file with their
multiple alignments still needs some postprocessing), it looks quite
conserved in the clade III nematodes.
As there are a very few mutations in the stem for Ascaris, but all the
other ones have none. Even the loop on top has only 1 and 4 mutations.

M

**Comment by khowe** [comment]
@Paul-Davis , can you provide any insight as to why Rfam let-7 (RF00027) gives no hits to any Caenorhabditis genome outside C. elegans (as appears to be the case)?

**Comment by Paul-Davis** [comment]
@khowe Not sure why it was excluded but they are all in there now apart from C. japonica which appears to be missing it from the assembly.
