### ISSUE TITLE
  create a  Laboratory designation?? 

...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3716]
<p>&nbsp;&nbsp;create a  Laboratory designation??</p>

Reported by: Hann***************** (usto***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by sibyl229** [comment]
Hello Hanno,

Thanks for writing to WormBase. There isn’t a web interface for users to create a lab designation. Could you please send us the information about the lab that you’d like to be listed? So we can add it for you.

Cheers,

Sibyl

**Comment by xdwang** [comment]
Hi,

Please also refer to the following page on how to register a new lab:

http://www.wormbase.org/about/userguide/nomenclature#01--10 <http://www.wormbase.org/about/userguide/nomenclature#01--10>

Thanks,

Xiaodong Wang
