### ISSUE TITLE
  I recently emailed wormbase about inf...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3717]
<p>&nbsp;&nbsp;I recently emailed wormbase about information regarding the mapping of a gene and I received no response so I am just writing to check in and see if someone will respond to my request.  Thank you.</p>

Reported by: Chri*************** (chri*****************************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36

**Comment by chris-grove** [comment]
Corresponded with Christopher, issue has been resolved
