### ISSUE TITLE
  Hi, Under each gene in sequence featu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3718]
<p>&nbsp;&nbsp;Hi,<br/>Under each gene in sequence features you can find the transcription factor binding regions. Now I have found that in my gene of interest (F20C5.3) there is a transcription factor binding region for dpl-1. Now my question is: how do I search for a list of genes that would have dpl-1 transcription factor binding site? The info is in the system - there must be a way to get a list of all the genes, right? Please, help:)<br/>Cheers - Karolina</p>

Reported by: Karo**** (k_an*******************)  (obscured for privacy))
Submitted From: efl-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00001161#0f-9e7b68-10">/species/c_elegans/gene/WBGene00001161#0f-9e7b68-10</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by xdwang** [comment]
Hi Karolina,

On dpl-1 gene page, if you open tree display widget (under Tools, on left panel), you will see there are 11248 sequence features DPL-1 binds to. These data are from large scale modEncode project from Synder lab. You can get detailed info on these data:
http://staging.wormbase.org/tools/tree/run?name=WBsf324198;class=Feature <http://staging.wormbase.org/tools/tree/run?name=WBsf324198;class=Feature>
and download Chip-seq data set and process further as you need:
http://staging.wormbase.org/tools/tree/run?name=modENCODE_3075_Snyder_TF_DPL-1;class=Analysis <http://staging.wormbase.org/tools/tree/run?name=modENCODE_3075_Snyder_TF_DPL-1;class=Analysis>

Let us know if you need more help. Our sequence curator may be able to provide further assistance.

Thanks,

Xiaodong Wang



> On Mar 31, 2015, at 11:31 AM, no-reply@wormbase.org wrote:
> 
> How Do I ...? 
>   Hi,
> Under each gene in sequence features you can find the transcription factor binding regions. Now I have found that in my gene of interest (F20C5.3) there is a transcription factor binding region for dpl-1. Now my question is: how do I search for a list of genes that would have dpl-1 transcription factor binding site? The info is in the system - there must be a way to get a list of all the genes, right? Please, help:)
> Cheers - Karolina
> 
> Submitted From: 
>   efl-1 (gene) /species/c_elegans/gene/WBGene00001161#0f-9e7b68-10 <http://www.wormbase.org//species/c_elegans/gene/WBGene00001161#0f-9e7b68-10>
> This issue has been assigned ticket number: #3718. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3718>.
> 
> 
> Reported by: Karolina (k_andralojc@hotmail.com <mailto:k_andralojc@hotmail.com>) 
> 31 Mar 15 15:36 
> 
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125

**Comment by xdwang** [comment]
WOW that was fast:)

Thank you so much Xiaodong - that is all I needed.

Have a great day - Karolina

**Comment by xdwang** [comment]
Karolina - 

Your best bet for fetching these data in a more parseable format is via modMINE:

http://intermine.modencode.org/release-33/experiment.do?experiment=ChIP-Seq%20Identification%20of%20C.%20elegans%20TF%20Binding%20Sites <http://intermine.modencode.org/release-33/experiment.do?experiment=ChIP-Seq%20Identification%20of%20C.%20elegans%20TF%20Binding%20Sites>

The Tree display is HTML and — if you can get it to load before it times out — isn’t going to be very fun to parse.

Todd
