### ISSUE TITLE
  tree display is not showing. 

Report...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3719]
<p>&nbsp;&nbsp;tree display is not showing.</p>

Reported by: xiao********* (xdwa**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25

**Comment by sibyl229** [comment]
Hi @xdwang which page is this? Thanks.

**Comment by xdwang** [comment]
@sibyl229 I've looked on both staging and live sites, many genes tree displays are not showing. Here is one:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00001061#8e-g-3
and another one:
http://www.wormbase.org/species/c_elegans/gene/WBGene00001204#8-eg-10

Thanks,

Xiaodong

**Comment by tharris** [comment]
Fixed.
