### ISSUE TITLE
  How can I bulk download retrotranspos...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3720]
<p>&nbsp;&nbsp;How can I bulk download retrotransposon sequences? They are mostly unannotated and the few that are annotated do not contain links with actual sequence information.</p>

Reported by: Stef********** (taub***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10

**Comment by Paul-Davis** [comment]
Dear Stefan,

Thank you for contacting WormBase concerning C. elegans retrotransposons.

Unfortunately, not all transposons have been curated so the data 
available is a little incomplete. I have deposited 2 files on an ftp for 
you to pick up.

ftp://ftp.sanger.ac.uk/pub2/wormbase/STAFF/pad/taubert

c_elegans.lib - This is the repeat library file that we currently use to 
mask the reference genome so contains a lot of retrotransposon sequences
WS247_Curated_WBTransposons.dna - The WS247 Transposon sequences as 
curated on the reference genome.

I hope this helps and apologies for the delay in getting back to you.

Paul



On 31/03/2015 18:52, WormBase Helpdesk wrote:
>
>   How can I bulk download retrotransposon sequences? They are mostly 
> unannotated and the few that are annotated do not contain links with 
> actual sequence information.
>
> Reported by: Stef********** (taub***************) (obscured for privacy))
> Submitted From: support /tools/support 
> <http://www.wormbase.org//tools/support>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 
> (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/3720>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
