### ISSUE TITLE
 Server Error: 500 at  tools/tree/run   
  Error M...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3721]
<p>Server Error: 500 at <a href="http://staging.wormbase.org/tools/tree/run?name=WBsf324198%3Bclass=Feature">tools/tree/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "must call fetch() with the -class or -query arguments at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API.pm line 273." </p>

Reported by: Karo**** (k_an*******************)  (obscured for privacy))
Submitted From: tree <a href="http://staging.wormbase.org//tools/tree/run">/tools/tree/run</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by tharris** [comment]
This was a double report. User was directed to the tree display to download a large list of modencode data. I pointed her to ModMine.
