### ISSUE TITLE
  cite a specific gene page in a lab re...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3722]
<p>&nbsp;&nbsp;cite a specific gene page in a lab report?</p><p>What were you doing? <br />&nbsp;&nbsp;lab report </p>

Reported by: Cait************ (cait************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by tuli** [comment]
Dear Caitlin,

Thank you for writing to WormBase.

You may cite WormBase gene page in your publication. Please refer to our
guideline http://www.wormbase.org/about/citing_wormbase which describe how
to cite a specific page.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
