### ISSUE TITLE
  I am a PhD candidate at Drexel Univer...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3724]
<p>&nbsp;&nbsp;I am a PhD candidate at Drexel University. We are currently interested in c. elegans research. However, we would like to perform a particular type of analysis. We would like to restrict the methionine content in these worms (down to at least 80% normal methionine ingested). I am wondering whether this would be possible. As I understand, c. elegans acquire their food/nutrients from irradiated bacteria/e. coli. There are strains of methionine-deficient e. coli. However, i believe they require methionine in order to grow. I am curious whether you have any suggestions for performing this type of analysis.<br/>Thank you,<br/>Tim Nacarelli</p><p>What were you doing? <br />&nbsp;&nbsp;Would like to perform research in c. elegans</p>

Reported by: Tim (tn72*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by raymond91125** [comment]
Hi Tim,

It seems that you have an interesting question perfectly suited for the 
community forum <http://forums.wormbase.org/>. There you get a much 
broader perspective from worm biologists.

You may also consider using our literature search tool 
<http://www.textpresso.org/celegans/>.

Cheers,

Raymond


On 04/01/2015 08:51 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I am a PhD candidate at Drexel University. We are currently 
> interested in c. elegans research. However, we would like to perform a 
> particular type of analysis. We would like to restrict the methionine 
> content in these worms (down to at least 80% normal methionine 
> ingested). I am wondering whether this would be possible. As I 
> understand, c. elegans acquire their food/nutrients from irradiated 
> bacteria/e. coli. There are strains of methionine-deficient e. coli. 
> However, i believe they require methionine in order to grow. I am 
> curious whether you have any suggestions for performing this type of 
> analysis.
> Thank you,
> Tim Nacarelli
>
> What were you doing?
>   Would like to perform research in c. elegans
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3724. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3724>.
>
> Reported by: Tim (tn72316@gmail.com)
> 01 Apr 15 15:54
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 
> (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
