### ISSUE TITLE
  I need the sequences for 30 C. briggs...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3725]
<p>&nbsp;&nbsp;I need the sequences for 30 C. briggsae genes.  I have the chromosome, start, and stop for each.  Instead of doing these one at a time, is there a way to enter the whole list and get a FA file back with each sequence having a unique name e.g chromosome.location</p>

Reported by: Edwa************* (eral*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10

**Comment by raymond91125** [comment]
Hi Ed,

I don't know that we have an online tool for you to do this. One thing 
you perhaps can try is to download the genomic fasta files on ftp and do 
the sequence extraction locally. See this page 
<https://www.biostars.org/p/10469/>.

Samtools seems pretty easy to use.

Cheers,

Raymond


On 04/01/2015 03:11 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I need the sequences for 30 C. briggsae genes. I have the 
> chromosome, start, and stop for each. Instead of doing these one at a 
> time, is there a way to enter the whole list and get a FA file back 
> with each sequence having a unique name e.g chromosome.location
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3725. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3725>.
>
> Reported by: Edward J. Ralston (eralston@berkeley.edu)
> 01 Apr 15 22:15
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 
> (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by brucebolt** [comment]
Dear Edward

This is actually possible to do with the WormBase ParaSite BioMart (which includes C. briggsae).

You can enter a list of Gene Stable IDs (WBGene…) or a list of chromosomal regions on the “Filters” page.  Note that positions must be in the format Chr:Start:End:Strand.  On the “Attributes” page, select “Sequence” from the top then choose the type of sequence you would like to return.  Click “Results" to return the sequences.

This link should load an example query to return unspliced transcript sequence from a list of regions: http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart_2&ATTRIBUTES=wbps_eg_gene.default.sequences.production_name_1010|wbps_eg_gene.default.sequences.ensembl_gene_id|wbps_eg_gene.default.sequences.chromosome_name|wbps_eg_gene.default.sequences.transcript_start|wbps_eg_gene.default.sequences.transcript_end|wbps_eg_gene.default.sequences.transcript_exon_intron&FILTERS=wbps_eg_gene.default.naive_filters.species_id_1010."cbriggsae"|wbps_eg_gene.default.naive_filters.chromosomal_region."I:47522:71392:1"&VISIBLEPANEL=attributepanel

Best regards

Bruce
