### ISSUE TITLE
  The display of the tra-1 reference al...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3732]
<p>&nbsp;&nbsp;The display of the tra-1 reference alleles is not correct.  There are two separate reference alleles, e1099 is the loss-of-function reference allele, e1575 is the gain-of-function reference allele. These alleles need to be displayed as individual alleles and not as one compound allele.</p>

Reported by: Kare****** (kare**************)  (obscured for privacy))
Submitted From: tra-1 (gene) <a href="http://staging.wormbase.org//species/c_elegans/gene/WBGene00006604#0-4-3">/species/c_elegans/gene/WBGene00006604#0-4-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36

**Comment by tuli** [comment]
@sibyl229 

When there is more than one reference allele, can you display them on separate lines, or (less preferable) put some space between the allele names so they don't look like a single entity?

**Comment by tuli** [comment]
FYI there are 12 such gene objects with > 1 Reference allele.
I've just checked WBGene00000488 and it has the same display issue.

**Comment by khowe** [comment]
Heading should also ideally say "Reference alleles" when there is more than one.

**Comment by chris-grove** [comment]
@kyook Can we close this? It looks resolved

**Comment by kyook** [comment]
Yes, thank you Chris.
