### ISSUE TITLE
  how do i annotate the genome region w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3740]
<p>&nbsp;&nbsp;how do i annotate the genome region wiht intron/exons shaded</p>

Reported by: madv*********************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by chris-grove** [comment]
Hello,

 Could you clarify what it is you are trying to do? Do you have evidence for a gene model that you'd like to submit?

Best,


Chris Grove

**Comment by epaule** [comment]
no response
