### ISSUE TITLE
  How do I get a gene's introns and UTR...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3741]
<p>&nbsp;&nbsp;How do I get a gene's introns and UTR</p>

Reported by: mgun******************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by chris-grove** [comment]
Hello,

 You can find the intron and UTR sequence by clicking on the sequence icon in the "Sequences" widget on the gene page of interest. Make sure to expand the section titled "view unspliced + UTR". The UTR sequence is lowercase and gray font, whereas introns are lowercase black font.

Best,

Chris Grove
