### ISSUE TITLE
  Hello. I am trying to get the identit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3744]
<p>&nbsp;&nbsp;Hello.<br/>I am trying to get the identity of a C. elegans protein of 22kDa in size. Kindly assist me with the procedure to follow.<br/>Thanks so much</p>

Reported by: Rich************ (rich*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by epaule** [comment]
you might do some additional analysis, as of WS247 there are 851 proteins annotated with a molecular weight between 21 kDa and 23kDa. So molecular weight alone is not the greatest differentiator.
