### ISSUE TITLE
GBrowse view of miRNA loci are a bit misaligned

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3745]
Not sure if there's an easy fix for this, but I just noticed that for let-7 and lin-4 miRNAs, the GBrowse view (both in the Location widget and GBrowse itself) have somewhat misaligned labels that makes it a bit difficult to read and interpret:

http://www.wormbase.org/species/c_elegans/gene/WBGene00002285#0f9--10
![screen shot 2015-04-07 at 2 47 40 pm](https://cloud.githubusercontent.com/assets/611382/7034291/74ae0886-dd35-11e4-87a9-18dbb26ee76d.png)

http://www.wormbase.org/species/c_elegans/gene/WBGene00002993#0f9--10
![screen shot 2015-04-07 at 2 48 27 pm](https://cloud.githubusercontent.com/assets/611382/7034308/87f272ba-dd35-11e4-8678-1808d05a21cc.png)

**Comment by chris-grove** [comment]
Note both the horizontal and vertical misalignment of the labels

**Comment by scottcain** [comment]
This is closely related to https://github.com/WormBase/website/issues/3624

**Comment by chris-grove** [comment]
@scottcain  Yes, I see. You can close this one if you think they are redundant. I'll leave it up to you. Thanks!

**Comment by Paul-Davis** [comment]
closed to allow comments in just the one ticket #3624
