### ISSUE TITLE
  How Do I Get Promoter Region and Sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3746]
<p>&nbsp;&nbsp;How Do I Get Promoter Region and Sequence for the gene "gcy-6"?? </p>

Reported by: Bila********* (bila*********************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36 OPR/28.0.1750.48

**Comment by chris-grove** [comment]
Hi Bilal,

 You can find sequence information for gcy-6 on the gcy-6 gene page, in the "Sequences" widget:

http://www.wormbase.org/species/c_elegans/gene/WBGene00001533#0f9--10

By clicking on the sequence icons for each CDS/transcript you can see get the unspliced or spliced gene sequence (including UTRs) as well as the amino acid sequence of the protein.

As for the promoter sequence, this is a bit more tricky. Click on the genome browser cartoon in the "Location" widget to open up GBrowse around gcy-6. You can then click and drag along the chromosome location marker (where it says "10313k","10314k", etc.) to select the "promoter" region you are interested in; this will then give you an option to "Dump selection as FASTA" (see attached screenshot). You can download the sequence that way, although you may want to compare it to the CDS/transcript sequence to demarcate where the promoter ends in the sequence.

Hope that helps.

Chris Grove

**Comment by chris-grove** [comment]
Yet another example of why it would be good to have pre-canned "promoter" sequences for genes

**Comment by Paul-Davis** [comment]
I think what you are refering to is the ability to dump a specified region upstream of a gene.....this was possible with WormMart, but was never implemented in WormMine....but is available in the 2 marts that WormBase contributes data to.

http://parasite.wormbase.org/biomart/martview/ (WS245)
http://metazoa.ensembl.org/biomart/martview/  (WS245)

**Comment by chris-grove** [comment]
@Paul-Davis  The comment I just made in #3756 was that the BioMart services are great, but don't allow a user to specify intergenic upstream only (not including any upstream coding exons), which is often what people want, in my experience.
