### ISSUE TITLE
  Expr7825 mentions RIC in the summary,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3747]
<p>&nbsp;&nbsp;Expr7825 mentions RIC in the summary, but it is not included in the expression list. </p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
Hi Barry,

thanks for reporting this. I have updated the information in our database.
The changes will be effective online in WS249.

thanks

Daniela
