### ISSUE TITLE
  ser-5 gene overview lists expression ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3748]
<p>&nbsp;&nbsp;ser-5 gene overview lists expression in ASH & AWB. This data is not in the expression list.<br/>Reference for ser-5 expression in ASH & AWB: WBPaper00032881</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
paper added
