### ISSUE TITLE
  Trying to load expression data for se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3749]
<p>&nbsp;&nbsp;Trying to load expression data for ser-7 is returning "Internal Server Error"</p><p>What were you doing? <br />&nbsp;&nbsp;http://www.wormbase.org/species/c_elegans/gene/WBGene00004780#0-9e1-10</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by chris-grove** [comment]
Hi Barry,

 Thanks for reporting this and apologies for the inconvenience. For now,
you can look at the staging site page for ser-7:

http://staging.wormbase.org/species/c_elegans/gene/WBGene00004780#01--10-0

Please keep in mind that the staging site is not intended for regular use,
so please use the regular (www) site for other use.

Thanks,

Chris Grove

**Comment by tharris** [comment]
No resolved on www.wormbase.org.

**Comment by draciti** [comment]
thanks todd, I confirm is working well and close
