### ISSUE TITLE
miRBase External links url update

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#3750]
Could this be tested on staging and then pulled into for WS248?

https://github.com/WormBase/website/commit/6050597f313f460fad9ac381bc02b7c5251dbbb3#diff-5911b28b588fc612de7f252256887b6c

**Comment by sibyl229** [comment]
Hi @Paul-Davis the miRBase links look fine on staging site: http://staging.wormbase.org/species/b_malayi/gene/WBGene00255612#02-g-3
Thanks.
