### ISSUE TITLE
  Expr3047 should include PVD 

Reporte...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3751]
<p>&nbsp;&nbsp;Expr3047 should include PVD</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
added
