### ISSUE TITLE
  WBPaper00036167 should be given an Ex...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3752]
<p>&nbsp;&nbsp;WBPaper00036167 should be given an Expr entry for tph-1, as it provides evidence of expression in ASG, ADF & NSM </p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
Paper added
