### ISSUE TITLE
  htp-1 cds is not opening and crashes....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3753]
<p>&nbsp;&nbsp;htp-1 cds is not opening and crashes.<br/>F41H10.10<br/>http://www.wormbase.org/species/c_elegans/cds/F41H10.10#052--10</p>

Reported by: hyun***************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by tharris** [comment]
This is now resolved on www.wormbase.org.

**Comment by chris-grove** [comment]
@tharris  Have you responded to the user?

**Comment by tharris** [comment]
No.

**Comment by chris-grove** [comment]
Hello,

 Thank you for reporting the error. This has now been resolved.

Best,

Chris Grove
