### ISSUE TITLE
  Expr8275 should include SIA (see cura...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3754]
<p>&nbsp;&nbsp;Expr8275 should include SIA (see curated image)</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
added
