### ISSUE TITLE
  WBPaper00041278 contains data for exp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3755]
<p>&nbsp;&nbsp;WBPaper00041278 contains data for expression of ser-5 in AVJ. This is not included on the ser-5 entry.</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
WBPaper00041278 added
