### ISSUE TITLE
  WBPaper00031006 contains evidence tha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3757]
<p>&nbsp;&nbsp;WBPaper00031006 contains evidence that tyra-3 (M03F4.3) is expressed in PVT (see Fig. 7)</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by draciti** [comment]
added

**Comment by draciti** [comment]
user is happy:
Hi Daniela,
Thank you for adding the changes, and for all the work maintaining the expression database. It's a fantastic resource!
