### ISSUE TITLE
Change "Anatomic Expression Patterns" header to "Spatio-temporal Expression Patterns" in Expression Widget

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3758]
In the "Expression" widget on gene pages, can we change the first section header from "Anatomic Expression Patterns" to "Spatio-Temporal Expression Patterns"?

Thanks!

**Comment by draciti** [comment]
Todd, the ticket is closed but I don't see the header change on staging
thanks

**Comment by draciti** [comment]
Apparently it is working in some pages and not in others (and in some computers and not in others..)
Chris sees it ok consistently. I see it fine for few genes and not for others (e.g. egl-1-screenshot). I tried to shift+reload my page and still do not see it right.

**Comment by draciti** [comment]
![screen shot 2015-05-08 at 10 38 15 am](https://cloud.githubusercontent.com/assets/901243/7542049/bbe863a8-f56e-11e4-8e45-2a789db964f0.png)

**Comment by draciti** [comment]
restarting the computer did the trick..closing
