### ISSUE TITLE
  Please reference our paper Cinkornpum...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3759]
<p>&nbsp;&nbsp;Please reference our paper Cinkornpumin et al in eLife 2014 for results on C06G1.1 and obi-1, its ortholog in Pristionchus pacificus. Thanks!</p>

Reported by: Ray **** (ray.*************)  (obscured for privacy))
Submitted From: C06G1.1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00015545#04-9e1c635bad-10">/species/c_elegans/gene/WBGene00015545#04-9e1c635bad-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by vanaukenk** [comment]
Dear Ray,

Thanks very much for writing to WormBase and alerting us to these
gene-paper connections.

I've added the connections for the C. elegans and P. pacificus genes, as
well as the other nematode genes, corresponding to the ortholog alignment
in Figure 4 - figure supplement 1.

Best,
--Kimberly Van Auken



>
> Feature
> Request
>   Please reference our paper Cinkornpumin et al in eLife 2014 for results
> on C06G1.1 and obi-1, its ortholog in Pristionchus pacificus. Thanks!
> Submitted From:
>   C06G1.1 (gene) /species/c_elegans/gene/WBGene00015545#04-9e1c635bad-10
>  This issue has been assigned ticket number: #3759. Follow progress on our
> issue tracker.
>
>   Reported by: Ray Hong (ray.hong@csun.edu)
>  09 Apr 15 08:03
>
>  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101
> Firefox/36.0     This question was reported via the web interface at
> wormbase.org. You can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
