### ISSUE TITLE
Gene Summary - Genetics widget - Allele table

### ISSUE THREAD

**Issue by tuli** [WormBase/website#3760]
Please can you combine columns 5 and 6 into a single column.

Column 5 is Protein change 
Column 6 is Amino acid position

e.g. http://www.wormbase.org/species/c_elegans/gene/WBGene00001595
For gk115480 Protein change is S -> P and Amino acid position is 85

I would like it to be in a single column called "Protein change" with a value  "S85P"

This is the widely accepted format for describing mutations. 

Nonsense mutations e.g q365 should be written as Q238Amber

This change is in anticipation of @kyook adding a new column "Allele nature"

**Comment by tharris** [comment]
There are several reasons those columns are distinct. But the main reason is if we use that notation the table will no longer be sortable by position which is a useful thing to do if one is very familiar with the location of protein domains. But if you're okay with that, it's an easy change.

**Comment by tuli** [comment]
Thanks for that insight @tharris 

I have no idea how many users sort by position so it's hard to know whether losing it will be a problem. I guess if we do it, we will find out! 

What are the other reasons?

Do you think it's worth losing this functionality if favour of keeping the table a manageable size?

**Comment by kyook** [comment]
I realized the position was providing a valuable sorting function.
However, the "S58P" format is the common, recognizable and used format for
reporting these data.  I think if people are looking for specific mutations
in known protein domains, I think the way forward is to report the actual
protein domain (yes, another column).

I think this also can address some of the engineered alleles, as the
introduced mutations specifically target predicted protein domains or
sequence features. This information should be displayed up front.

Karen



On Thu, Apr 9, 2015 at 6:25 AM, tuli <notifications@github.com> wrote:

> Thanks for that insight @tharris <https://github.com/tharris>
>
> I have no idea how many users sort by position so it's hard to know
> whether losing it will be a problem. I guess if we do it, we will find out!
>
> What are the other reasons?
>
> Do you think it's worth losing this functionality if favour of keeping the
> table a manageable size?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3760#issuecomment-91230804>.
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by tharris** [comment]
Okay, we will merge these columns. Users can check the Genome Browser if they want to map mutations to domains for now.

**Comment by kyook** [comment]
Is there a way to map mutations to protein domains automatically, and show affected domain, when appropriate, in the table?
