### ISSUE TITLE
www.wormbase.org Species drop down

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#3761]
Just wondering what the purpose of the "Others" is on the Species drop down 

![screen shot 2015-04-09 at 11 37 45](https://cloud.githubusercontent.com/assets/717707/7065671/180c5834-deb2-11e4-8a14-a4040c1695fd.png)

as you end on a page with nothing to browse and a generic search box widget.

![others](https://cloud.githubusercontent.com/assets/717707/7065705/7a7b8940-deb2-11e4-9b04-f4a2ccdc5bb5.png)

Could/Should it be removed?

**Comment by tharris** [comment]
It was originally to house species that we thought were important enough to place into WormBase but not important enough to warrant a place on the drop down menu.

**Comment by khowe** [comment]
Perhaps this warrants another ticket, but I'd like to propose a change to the Species drop-down menu: list each core species in its entirety (i.e. without the genus-based entry point), and then have "Others", which contains the others (maintaining the genus-based entry-point, if we think it's useful, and possibly having the ParaSite species in there). Core species (species for which we have responsibility for administering the genome and annotation) are:

C. elegans
C. briggsae
C. brenneri
C. japonica
C. remanei
P. pacificus
B. malayi
O. volvulus

...with S. ratti to be added in WS249.

**Comment by tharris** [comment]
Good suggestion. We will look into this for WS248.

**Comment by sibyl229** [comment]
Hi @Paul-Davis the Others sub-menu under species now has items in there: http://staging.wormbase.org/search/gene/  I removed the link to the 'Others' search/browse page, because I don't think there's a way to browse only those "Others" species. Does this make more sense now?

**Comment by Paul-Davis** [comment]
The initial ticket issue has been resolved thanks @sibyl229 

I will have to defer to @khowe to comment on the changes he requested.

**Comment by khowe** [comment]
Looks good. Small thing: the core species are list both at the top level and in "Others".  This may annoy pedants, but I guess is not a big deal.

**Comment by sibyl229** [comment]
Thanks @khowe @Paul-Davis . That makes sense. Now a species is listed once only in the menu. http://staging.wormbase.org/#01-23-6
