### ISSUE TITLE
  WBPaper00032490 refers to Y23B4A.2 as...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3767]
<p>&nbsp;&nbsp;WBPaper00032490 refers to Y23B4A.2 as nlp-44</p>

Reported by: Barr********* (bntl************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by tuli** [comment]
Hi Tim,

Paper is attached.

Do you approve Y23B4A.2 = nlp-44

Thanks,

Mary Ann

On 10 April 2015 at 21:24,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   WBPaper00032490 refers to Y23B4A.2 as nlp-44
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3767. Follow progress on our
> issue tracker.
>
> Reported by: Barry Bentley (bntlyb@gmail.com)
> 10 Apr 15 20:28
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101
> Firefox/37.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Barry,

Thank you for bringing this paper to our attention.

The gene name association will need to be approved by Tim Schedl. I
will contact you again once we have made the update.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Mary Ann, 

This is a release from Jonathan's confidential list: 

*capa GNW CAPA (insect neuropeptide) related 
*capa-1 (main name) = nlp-44 (other name) = Y23B4A.2 Person_evidence [Marleen Lindemans] 

Thanks, 

Tim 

----- Original Message -----

**Comment by tuli** [comment]
Dear Barry,

Further to Tim's approval I would like to confirm the following changes.


Y23B4A.2 has been assigned the gene name capa-1, a member of the capa
- "CAPA (insect neuropeptide) related" gene class, with nlp-44
assigned as an other name.

The geneID for capa-1 is WBGene00021268

This update will be available in release WS249 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
