### ISSUE TITLE
 Server Error: 500 at  rest/widget/person/WBPerson...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3768]
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/person/WBPerson14414/overview">rest/widget/person/WBPerson14414/overview</a></p><p></p><p>Error Message:<br> undef error - Can't use string ("Catalyst::Authentication::Store:"...) as a HASH ref while "strict refs" in use at accessor Catalyst::Authentication::Store::DBIx::Class::User::_user (defined at /usr/local/wormbase/extlib/lib/perl5/Catalyst/Authentication/Store/DBIx/Class/User.pm line 12) line 5.<br> </p><p>What were you doing? <br />&nbsp;&nbsp;Looking at WBPerson14414 summary page</p>

Reported by: Mary********* (mary*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by sibyl229** [comment]
Thanks @tuli the person summery page looks fine now on production: http://www.wormbase.org/resources/person/WBPerson14414#0123--10

**Comment by tuli** [comment]
Great. Thanks.
