### ISSUE TITLE
  Dear, I would like to obtain the list...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3769]
<p>&nbsp;&nbsp;Dear, I would like to obtain the list of all transposon of C. elegans in fasta format (sequences of DNA), but I have managed to to obtain only the number of access for all transposon, in at link: http://www.wormbase.org/species/c_elegans/transposon#1-0-5 or download each sequences one at a time. Is the any way to obtain all this sequences in fasta format, I didn't found such data in ftp (ftp://ftp.wormbase.org/pub/wormbase/). Please could you give me any help or suggestions. Thanks in advance for you attention. Best, Leandro de Mattos.</p>

Reported by: Lean*** (matt***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; InfoPath.1)

**Comment by Paul-Davis** [comment]
Dear Leandro,

Thank you for contacting WormBase concerning C. elegans transposons.

Unfortunately, not all transposons have been curated so the data 
available is a little incomplete. I have deposited 2 files on an ftp for 
you to pick up.

ftp://ftp.sanger.ac.uk/pub2/wormbase/STAFF/pad/Leandro

c_elegans.lib - This is the repeat library file that we currently use to 
mask the reference genome so contains a lot of transposon sequences
WS247_Curated_WBTransposons.dna - The WS247 Transposon sequences as 
curated on the reference genome.

I hope this helps.

Paul

On 13/04/2015 14:51, WormBase Helpdesk wrote:
>
>   Dear, I would like to obtain the list of all transposon of C. 
> elegans in fasta format (sequences of DNA), but I have managed to to 
> obtain only the number of access for all transposon, in at link: 
> http://www.wormbase.org/species/c_elegans/transposon#1-0-5 or download 
> each sequences one at a time. Is the any way to obtain all this 
> sequences in fasta format, I didn't found such data in ftp 
> (ftp://ftp.wormbase.org/pub/wormbase/). Please could you give me any 
> help or suggestions. Thanks in advance for you attention. Best, 
> Leandro de Mattos.
>
> Reported by: Lean*** (matt***************) (obscured for privacy))
> Submitted From: support /tools/support 
> <http://www.wormbase.org//tools/support>
>
> Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET 
> CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 
> 3.0.4506.2152; .NET CLR 3.5.30729; InfoPath.1)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/3769>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
