### ISSUE TITLE
JBrowse tracks

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3770]
Hi Scott,

the C.elegans JBrowse looks very clean and streamlined at the moment ... could you see if you can get some things to reappear?

thanks,

M

**Comment by epaule** [comment]
.... actually it seems to be that the first genome works and for further it doesn't

**Comment by epaule** [comment]
![screenshot from 2015-04-13 16 59 08](https://cloud.githubusercontent.com/assets/20523/7119588/7f0ddc2a-e1fe-11e4-8b5e-e544c4deab93.png)

**Comment by scottcain** [comment]
"Streamlined"; I like it :-)

JBrowse at jbrowse.wormbase.org is working for me currently, including these tracks.  What do you mean that it seems to be the first genome works and further it doesn't?  I tried changing organisms and chromosomes and it still worked.

**Comment by epaule** [comment]
it seems the first genome you go to on JBrowse is fine and the next one not working until you clean the cookies. In my case, brugia was fine and a lot of the others not, and in Kev's elegans was fine but brugia not.

**Comment by scottcain** [comment]
And that is continuing to happen?  I did update the organisms drop down menu a few days ago, so I imagine there might be some "residual" affects due to that, but after a hard reload (or presumably dumping the cookies, but I'm not sure about that), it should be fine again.

**Comment by khowe** [comment]
I discovered that my Brugia problem was due to all of the tracks being switched off (for me, every species that I visited for the first time had all tracks switched off. Is this the expected default?)

Once I'd worked that out, it seemed to be working as expected for me.

**Comment by scottcain** [comment]
There aren't any default tracks turned on; I'm reasonably sure that JBrowse supports default tracks, so I'll turn on the same defaults as GBrowse.  Of course, clearing cookies will turn all of the tracks off since there are no defaults.

**Comment by scottcain** [comment]
I had to fix a bug along the way, but I configured JBrowse to show the polymorphisms, classical alleles and curated genes tracks by default on the first visit to a species, which are the same defaults as GBrowse.
