### ISSUE TITLE
  When I enter unc-4 in the upper right...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3778]
<p>&nbsp;&nbsp;When I enter unc-4 in the upper right search box, I get sent to the page for the Dmel ortholog, and not the C. elegans gene also known as F26C11.2... So far, I have not noticed this for any other gene.<br/>On another note, picture links (for anatomic expression patterns) are systematically broken; I only have access to thumbnails.<br/>Thanks!<br/>Antoine</p>

Reported by: anto************************  (obscured for privacy)
Submitted From: unc-4 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00006744#01-9f4b-4-9f">/species/c_elegans/gene/WBGene00006744#01-9f4b-4-9f</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by tuli** [comment]
Looks like we've got a fly in the ointment 

#3775 ;-)

**Comment by tharris** [comment]
Haha. Funny. 

Fixed for WS247 and WS248; marking this as under testing so we can close all of these reports. See the new parent issue at #3820.
