### ISSUE TITLE
Remove stale annotations-processed.gff3 and annotations-sorted.gff3 symlinks on FTP site

### ISSUE THREAD

**Issue by khowe** [WormBase/website#3784]
In here:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/

...and probably for other species too. We no longer produce the annotations-processed and annotations-sorted GFF3 files, so the current development and production symlinks point to old files. They need to be removed (should probably remove all "processed" and "sorted" links for clarity).

**Comment by tharris** [comment]
Complete.
