### ISSUE TITLE
  I am submitting an abstract for the w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3787]
<p>&nbsp;&nbsp;I am submitting an abstract for the worm meeting there is a section on wormbase gene symbol.  I have no idea what that is?  For example, I mention tph-1 and mod-5?<br/>Thanks,<br/>Lucinda</p>

Reported by: Luci*********** (carn************)  (obscured for privacy))
Submitted From: Nomenclature <a href="http://www.wormbase.org//about/userguide/nomenclature#k17af09cjd4eilg52386bh--10">/about/userguide/nomenclature#k17af09cjd4eilg52386bh--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by tuli** [comment]
Dear Lucinda,

Thank you for writing to WormBase.

If tph-1 and mod-5 are mentioned in your abstract you should enter
those in Gene Information section of your abstract submission. The
organisers ask that authors provide this information as the Program
book contains a list of all genes authors discuss and it also ensures
that authors are using only approved gene names in their abstracts.

I hope this helps.

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
