### ISSUE TITLE
  I realize no-one will greatly care, b...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3789]
<p>&nbsp;&nbsp;I realize no-one will greatly care, but I just now realized the pull-down list of search topics is out of alphabetical order; that is, it's almost in alphabetical order but with three errors (antibody before anatomy, phenotype before person, and both phenotype and person before paper). Thought I'd mention it, jsut because it was bugging me trying to find "person" for just a couple moments longer than I expected.</p>

Reported by: Hill*********** (hill*********************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6f">/#01-23-6f</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by sibyl229** [comment]
Hi Hillel,

Thanks for bringing it up. I’m certain the issue bothers others as well. I’m glad you pointed it out.

It’s fixed on our staging (development) site, and will be out in the next release in early June.

Thanks again.

Sibyl
