### ISSUE TITLE
  cOMPARE n2 c.ELEGAND WITH cb4856 One ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3790]
<p>&nbsp;&nbsp;cOMPARE n2 c.ELEGAND WITH cb4856<br/>One gene that codes for a specific protein that is different and one that is the same (gene-protein)</p>

Reported by: sind* (shax**********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by chris-grove** [comment]
Wrote to user:
"

Hello Sindi,

 I don't know if anyone had gotten back to you about this. If not,
apologies. What exactly is it you are trying to do?

Best,

Chris Grove"

will close now, and reopen if necessary
