### ISSUE TITLE
  Gene F53A2.7 is called acca-2 and aca...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3791]
<p>&nbsp;&nbsp;Gene F53A2.7 is called acca-2 and acaa-2 on the same page. Which one is correct?</p>

Reported by: Alex********** (aba7*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by tuli** [comment]
Dear Alex,

Thank you for bringing this mistake to our attention.

The correct name for F53A2.7 is acaa-2. I have fixed the mistake and
you will see it in WormBase release WS249.

Apologies for the confusion.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
