### ISSUE TITLE
  Hi, I was in touch with some people a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3793]
<p>&nbsp;&nbsp;Hi,<br/>I was in touch with some people at wormbase before because I have assembled a genome sequence for an inbred strain of C. remanei, built a partial genetic map (covering chromsomes X, II, IV) and annotated miRNA and protein-coding genes, and I would like to submit the new genome to wormbase. I am preparing the sequence for submission to ncbi and would like to start working with wormbase for submission as well. What files do you need from me, and how should they be formatted? Can you get the files from the ncbi submission or do you prefer we work on the wormbase submission first? Thanks! -Janna Fierst </p>

Reported by: Jann******** (jfie***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by khowe** [comment]
In conversation with the user off-line. Leaving open for now.

**Comment by chris-grove** [comment]
@khowe  Should we keep this open?
