### ISSUE TITLE
rnaseq patch for WS248

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3794]
Hi @tharris  / @sibyl229,

could you load:
ftp://ftp.sanger.ac.uk/pub/consortia/wormbase/releases/WS248/acedb/PATCHES/SRP006033.ace
or
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS248/acedb/PATCHES/SRP006033.ace
into the staging acedb database?

That should sort out some display issues seen on the C.briggsae RNASeq widgets.

**Comment by tharris** [comment]
Patched.
