### ISSUE TITLE
  the unc-104 page is displaying no inf...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3795]
<p>&nbsp;&nbsp;the unc-104 page is displaying no information </p>

Reported by: Gaut** (gaut************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/7.1.5 Safari/537.85.14

**Comment by epaule** [comment]
you were probably looking at the Drosophila unc-104 gene page (in the overview section is the Species).

I added some more identifiers to our non-wormbase genes and sadly some are the same as CGC approved gene symbols (notably the fly people used quite often the CGC-name of the C.elegans ortholog as gene symbol for fly genes).

Our web-search currently doesn't weight the search hits by species, so quite often the non-wormbase genes come up first.

We are working on fixing that in #3775

**Comment by tharris** [comment]
Fixed for WS247 and WS248; marking this as under testing so we can close all of these reports. See the new parent issue at #3820.

**Comment by tharris** [comment]
User contacted that issue resolved.
