### ISSUE TITLE
  Hi, I just sent a report about unc-10...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3796]
<p>&nbsp;&nbsp;Hi, I just sent a report about unc-104. I later realized that when I search for unc-104, I get two options in the category "gene". Choosing the first gives me no info, but when I chose the 2nd option for unc-104, I was directed to a page with all the information. Same for unc-119.</p>

Reported by: gaut** (gaut************)  (obscured for privacy))
Submitted From: unc-104 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00006831#0f-9ed-10">/species/c_elegans/gene/WBGene00006831#0f-9ed-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/7.1.5 Safari/537.85.14

**Comment by epaule** [comment]
you were probably looking at the Drosophila unc-104 gene page (in the overview section is the Species).

I added some more identifiers to our non-wormbase genes and sadly some are the same as CGC approved gene symbols (notably the fly people used quite often the CGC-name of the C.elegans ortholog as gene symbol for fly genes).

Our web-search currently doesn't weight the search hits by species, so quite often the non-wormbase genes come up first.

We are working on fixing that in #3775

**Comment by tharris** [comment]
Fixed for WS247 and WS248; marking this as under testing so we can close all of these reports. See the new parent issue at #3820.

**Comment by tharris** [comment]
user contacted that issue resolved.
