### ISSUE TITLE
  Institution tag in Person class is st...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3797]
<p>&nbsp;&nbsp;Institution tag in Person class is still showing only one. Model was changed to not be unique, but it is  still not displayed correctly, as in Tree Display/Address/Institution.<br/>http://staging.wormbase.org/resources/person/WBPerson77#0152--10</p>

Reported by: ceci*** (ceci*******************)  (obscured for privacy))
Submitted From: Sydney Brenner (person) <a href="http://staging.wormbase.org//resources/person/WBPerson77#0152--10">/resources/person/WBPerson77#0152--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by ceciliaWBPerson1** [comment]
Webteam:
Web Page tag is also displaying only 1 instead of all like in Tree Display.
Please display all "Institution" and all "Webpage"
http://staging.wormbase.org/resources/person/WBPerson77#0152--10
thanks

**Comment by sibyl229** [comment]
Hi @ceciliaWBPerson1 Sorry for the delay in fixing the issue. The display for multiple institutions and webpages is working now on staging: http://staging.wormbase.org/resources/person/WBPerson77#0123--10 Please let me know if there's any problem. Thank you!

**Comment by ceciliaWBPerson1** [comment]
Beautiful!  thanks
