### ISSUE TITLE
  1. How do I become a member? 2. How c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3800]
<p>&nbsp;&nbsp;1. How do I become a member?<br/>2. How can I get the file of miRNA annotations?<br/>Thanks,<br/>Ying</p>

Reported by: yjin (yjin*********)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by sibyl229** [comment]
Hi Ying,

The “Sign in with Google” option will create an account for you on WormBase, and let you work with member functionalities, such as saving bookmarks and history. The register function is disabled at the moment, as we explore options to handle authentication. Please let me know if you have more questions or feedback about the login.  

Thanks for your question. My colleague will be able to help you about your other question about downloading miRNA annotations.

Sibyl
web dev

**Comment by chris-grove** [comment]
Hi Ying,

 I don't know if anyone had gotten back to you about the miRNA annotations; if not, apologies. You may parse the ncRNA or GFF files from our FTP site:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS249/species/c_elegans/PRJNA13758/

Hope that helps.

Best,

Chris Grove
