### ISSUE TITLE
  Hi- Am trying to learn how to use Wor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3802]
<p>&nbsp;&nbsp;Hi-<br/>Am trying to learn how to use WormMine. Was able to compile a list of C. elegans genes. How can I retrieve 1.5 kb promoter region upstream of a bunch of genes? I saw that there are instructions for this using the older service (WormMart: http://wiki.wormbase.org/index.php/FAQs#How_can_I_retrieve_1.5_kb_promoter_region_upstream_of_a_bunch_of_genes.3F), but that doesn't seem to work with WormMine. Also, I am having trouble obtaining lists of the same genes but in related nematode species (searching for let-70 or Cbr-Let-70 brings up no search results). Thanks so much!<br/>Jennifer</p>

Reported by: Jenn************** (jzuc******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by chris-grove** [comment]
Hi Jennifer, 

 I don't believe we have non-elegans species data in WormMine yet, unfortunately.

As for the 1.5 kb promoter sequences, I would recommend a tool recently pointed out to me by a colleague:

http://metazoa.rsat.eu/

If you click on the "Sequence tools" header in the left-hand side bar and then on the inset "retrieve sequence" option, you will be taken to a form where you can specify the species, a list of gene names, and the amount of sequence you would like for each gene. Note that the tool is quite finicky with respect to gene name used, so you may want to play around with the settings before trying a large query. I would also recommend using the "Caenorhabditis elegans" species selection, not the "Caenorhabditis elegans WBcel235" as I was having trouble getting that to work.

To specify 1.5kb of upstream sequence, select Sequence type "upstream" from the drop down menu and type in "-1500" and "-1" respectively in the following "From" and "To" fields. You may also want to check the box for "Prevent overlap with neighbour genes (noorf)" (checked by default) to ignore upstream sequences that overlap with other genes.

Let me know if you have any questions.

Best,

Chris Grove
