### ISSUE TITLE
  I'm trying to determine wether then u...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3804]
<p>&nbsp;&nbsp;I'm trying to determine wether then unc-76 mutation is dominant or recessive in the C. elegans species. Please help. </p>

Reported by: rhl7************  (obscured for privacy)
Submitted From: unc-76 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00006808#0-1-3">/species/c_elegans/gene/WBGene00006808#0-1-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

**Comment by chris-grove** [comment]
Hello,

 Which unc-76 mutation are you referring to? There are 90 mutations for unc-76 in WormBase.


Best,

Chris Grove

**Comment by chris-grove** [comment]
Contacted user, issue resolved
