### ISSUE TITLE
  Dear wormbase team I am the author of...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3811]
<p>&nbsp;&nbsp;Dear wormbase team<br/>I am the author of WormNet and I found that WormBase distribute edge information of WormNet version 2, but cite the version 1 network paper as a reference (Lee et al. Nature Genetics 2008).<br/>I think the reference for wormnet links need to be replaced by Lee et al. Genome Research 2010 (pmid 20538624).<br/>Best regards </p>

Reported by: Insu***** (insu*****************)  (obscured for privacy))
Submitted From: nlp-8 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00003746#08d47-9f1-3">/species/c_elegans/gene/WBGene00003746#08d47-9f1-3</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by chris-grove** [comment]
Hi Dr. Lee,

 Thanks for contacting us about this issue. I'd be happy to work with you
to sort this all out. We can discuss in a separate e-mail thread.

Best,

Chris Grove

**Comment by chris-grove** [comment]
I will communicate with him directly to sort this out.
