### ISSUE TITLE
  searching for nrx-1 gene pulls up the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3813]
<p>&nbsp;&nbsp;searching for nrx-1 gene pulls up the drosophila homologue but not the c. elegans gene.</p>

Reported by: mich************************  (obscured for privacy)
Submitted From: nrx-1 (gene) <a href="http://www.wormbase.org//species/drosophila_melanogaster/gene/FBgn0038975#064-9ed1c5f-10">/species/drosophila_melanogaster/gene/FBgn0038975#064-9ed1c5f-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by chris-grove** [comment]
Hi Mike,

 Thanks for reporting the issue and sorry for the inconvenience. My colleagues can correct me if I'm wrong, but I believe we recently imported a number of Drosophila genes that have (unfortunately) adopted the exact same name as the C. elegans ortholog (e.g. unc-13, unc-104). Our search tool has not been accordingly updated and so the default search result returns the Drosophila gene page. This is currently being worked on but I don't know when the fix will be live on the site.

The easiest way to get the C. elegans gene is to search for the gene in the search box and click on the SECOND result of nrx-1 in the autocomplete drop down menu that appears.

Again, apologies for the inconvenience.

Best,

Chris Grove

**Comment by chris-grove** [comment]
Duplicate #3775
