### ISSUE TITLE
  When I type in "unc-13" as a search t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3814]
<p>&nbsp;&nbsp;When I type in "unc-13" as a search term "for a gene," the search took me to flybase. I tried this twice, using a new window. I got around the problem by searching for "e51" "for a variation. "I did not have this problem when searching for "dpy-14" "for a gene.".  </p>

Reported by: Pame******** (pame******************)  (obscured for privacy))
Submitted From: e1214 (variation) <a href="http://www.wormbase.org//species/c_elegans/variation/WBVar00143837#02-45-3">/species/c_elegans/variation/WBVar00143837#02-45-3</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/20100101 Firefox/17.0

**Comment by chris-grove** [comment]
Hi Pamela,

 Thanks for reporting the issue. We are aware of the problem and are
working to fix it. For now, you can select the second suggested gene from
the autocomplete list that pops up below the search box when you enter
"unc-13". This affects other genes as well, e.g. unc-104, nrx-1. The
issue, I believe, was a recent import of Drosophila gene names that have
been giving names identical to the worm genes.

We hope to have this issue fixed ASAP.

Thanks again and apologies for the inconvenience.

Best,

Chris Grove

**Comment by chris-grove** [comment]
Duplicate #3775
