### ISSUE TITLE
  Hi, I want to ask how can I get the c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3815]
<p>&nbsp;&nbsp;Hi, I want to ask how can I get the cDNA with the EC as the start, for example:EC000238, wher can I order them? thank you!</p>

Reported by: maxi***** (zzya**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by raymond91125** [comment]
answered:
Hi Yongzhi,

The source of this sequence can be found here <http://www.ncbi.nlm.nih.gov/nucest/EC000238>.

Raymond
