### ISSUE TITLE
  Hi! I am trying to design primers to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3817]
<p>&nbsp;&nbsp;Hi! I am trying to design primers to check mRNA levels of the siRNA transgenic C. elegans. I am hoping to design the primers for a sequence that is on the mRNA but not in the siRNA plasmid so I have quantification of only mRNA levels in C. elegans. <br/>How should I begin this? I know I need to align the plasmid sequence with the gene sequence to identify what segment to amplify, but I am not sure where to find this information. <br/>Thanks!</p>

Reported by: Hele***** (hele**************)  (obscured for privacy))
Submitted From: sjj_Y57G11C.11 (pcr_oligo) <a href="http://www.wormbase.org//species/all/pcr_oligo/sjj_Y57G11C.11#02--10">/species/all/pcr_oligo/sjj_Y57G11C.11#02--10</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36

**Comment by chris-grove** [comment]
Hi Helen,

 Are you looking for the sequence for a particular gene? We don't carry plasmid sequences.

Best,

Chris Grove

**Comment by chris-grove** [comment]
User contacted and happy with results.
