### ISSUE TITLE
  I've had my gmail account (adele.baru...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3819]
<p>&nbsp;&nbsp;I've had my gmail account (adele.barugahare@monash.edu) linked to Wormbase for around 1 year. However, I've recently had difficulty accessing my WormMine data. When I use WormMine and click the link to connect my gmail account, it takes me back to the Wormbase home screen. When I access WormMine after this, my gmail account is still disconnected and I cannot access the lists I have saved to it. What can I do to fix this problem?<br/>Kind regards,<br/>Adele</p>

Reported by: Adel************ (adel***********************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by chris-grove** [comment]
This is related to issue #3774

**Comment by chris-grove** [comment]
Hi Adele,

 Apologies for the delay in response. Unfortunately, WormMine is not currently supporting WormMine login, although our web team is working to restore this functionality. In the meantime, WormMine should remember recent list and query entries when using the same computer, so at least you can store and track queries and lists on any given computer you use.

You can track the progress of the web team on resolving this issue on the GitHub issue tracker here:

https://github.com/WormBase/website/issues/3819


Best,

Chris Grove

**Comment by chris-grove** [comment]
I will contact user when WormMine is live and supports logins again

**Comment by chris-grove** [comment]
@tharris  Can stable logins be registered for WormMine now, or will we need to wait until we are beyond the current beta version of WormMine?

**Comment by chris-grove** [comment]
Contacted user about WormMine login updates (logins should be stable now). Closing
