### ISSUE TITLE
  1   what are the different glutaredox...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3821]
<p>&nbsp;&nbsp;1   what are the different glutaredoxins in c. elegans?<br/>2   the sequence alignment of Glutaredoxins in C. elegans</p>

Reported by: hila****************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by chris-grove** [comment]
Hello,

 If you let us know what you have already tried, we may be able to help guide you in the right direction. 

Best,

Chris Grove

**Comment by chris-grove** [comment]
Contacted user and resolved
