### ISSUE TITLE
  I am analyzing RNAseq data generated ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3825]
<p>&nbsp;&nbsp;I am analyzing RNAseq data generated from the N2 strain and the CB4856 strain, and am concerned that using the standard genome reference (derived from N2) will lead to loss of information when mapping CB4856 reads. Are there any data available on WormBase that could be used to build a CB4856-specific reference index? Thank you for your help!</p>

Reported by: Keir (kbal***********)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17

**Comment by azurebrd** [comment]
From Kevin Howe : 

Hi Keir, 

If you really think this is the best approach, you can produce a "virtual" genome sequence for CB4856 by taking the N2 reference and "swapping in" the variants, which can be extracted from our GFF3:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS248.annotations.gff3.gz

(look for lines with the "variation" attribute set, and CB4856 as one of the values for the strain attribute). 

However, I would advise against this approach for two reasons. Firstly, it is not correct to assume that CB4856 matches the N2 reference sequence at every position that does not have a variant for CB4856 in the GFF. Those positions could agree with N2, or it could be that there was not enough high-quality data covering them to make a call. Secondly, the virtual CB4856 genome that you produce would be on a different coordinate system to annotated N2 genome. This means that you will not be able to use the N2 reference annotation in the interpretation of RNASeq alignments (e.g. calculating FPKM expression values for transcripts and genes). Instinctively, I think you should be fine aligning CB4856 RNASeq reads to the N2 reference. I would certainly try that in the first instance. 

Best,

Kevin
