### ISSUE TITLE
  How can I view all of the ChIP-seq bi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3827]
<p>&nbsp;&nbsp;How can I view all of the ChIP-seq binding regions on a track? right now, they are completely overlapping and illegible, unfortunately. Many annotations can be read through "ChIP-seq TF binding region for" and then the key information overlaps with another annotation! Is there a way to stagger the Y positions of the items in the track, or change the display settings so I can more easily see the labels? Thanks!</p>

Reported by: Erik******** (etil************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by chris-grove** [comment]
Adding a screenshot:
![iv-14790466 14794066](https://cloud.githubusercontent.com/assets/611382/7399592/b9679ad6-ee6b-11e4-9778-fed1bcefa55e.png)

I feel like there is another related issue open; I'll make a reference to it if I find it

**Comment by chris-grove** [comment]
@scottcain  Could you weigh in on this? Do you remember if there's a related issue open? Thanks!

**Comment by scottcain** [comment]
Oh, the first time I saw this issue, I looked that picture but not very closely and assumed that you'd fixed showed the user what to do and it was a done deal.  There are some issues with BioGraphics (the perl underbelly of GBrowse) that is causing this, but I don't recall if it's been fixed.  We might be able to force it to do better at the expense of some vertical screen real estate (that is, a tall image will get taller).  I'll play around with it to see what I can do.

**Comment by scottcain** [comment]
Hi @chris-grove I have a solution in place, though I don't like it much.  I've configured that track for C. elegans on staging to put only one feature on a horizontal line, so the labels shouldn't ever overlap now, but it does make the track taller for most cases.  @tharris do you have an opinion?

For reference, to see the problem that @chris-grove highlighted above with the screenshot, you have to select "expand & label" from the "spacing" menu in the track configuration pop up you get when you click on the configure track wrench in the details panel.

**Comment by chris-grove** [comment]
@scottcain  Thanks this looks better, and I totally get your point about the height of the track.

@tharris  It seems that we could benefit from some more granular breakdown/categorization of all these different binding regions?

**Comment by chris-grove** [comment]
@scottcain  We seem to have reverted back to the jumbled labeling on staging GBrowse? I was about to confirm with Erik and close this ticket when I found that the problem seems to be back:
![screen shot 2015-05-13 at 11 38 40 am](https://cloud.githubusercontent.com/assets/611382/7618101/ad42fc6a-f964-11e4-891c-b8484a93f292.png)

I did notice that staging now says WS247 instead of WS248 as it did a few days ago, so maybe a build process is underway?

**Comment by scottcain** [comment]
Oh, I bet I forgot to commit something.  I'll revert it and make sure I commit everything.

**Comment by chris-grove** [comment]
Looks good. Thanks @scottcain @sibyl229

**Comment by chris-grove** [comment]
Hello again Erik,

 Thanks again for reporting the issue. We have resolved this for now on our staging site instance of GBrowse:

http://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/

The titles should all now be visible, although now the track is quite tall. We will look into ways to make the track more manageable in size, perhaps by breaking the tracks into categories.

Please note that our staging site is not intended for regular use and can be prone to instability. This version of the site will go live in our WS248 release, sometime in early June.

Thanks,

Chris Grove
