### ISSUE TITLE
  The paper given as evidence for a phe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3828]
<p>&nbsp;&nbsp;The paper given as evidence for a phenotype caused by RNAi of a particular gene did not discuss that gene anywhere in it. Would it be under a different name in the paper? (looking at the BAF-1 gene and Lethal phenotype)</p>

Reported by: tori*****************  (obscured for privacy)
Submitted From: Frequently asked questions <a href="http://www.wormbase.org//about/Frequently_asked_questions#b9582ec36d017a4--10">/about/Frequently_asked_questions#b9582ec36d017a4--10</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by chris-grove** [comment]
The lethal phenotype results for baf-1 RNAi can be found in the
supplemental Table 1B.
