### ISSUE TITLE
  How do I scyence? 

Reported by: Ever...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3831]
<p>&nbsp;&nbsp;How do I scyence?</p>

Reported by: Ever******** (16co**************)  (obscured for privacy))
Submitted From: dpy-11 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00001073#0-9f-3">/species/c_elegans/gene/WBGene00001073#0-9f-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by raymond91125** [comment]
One way to scyence is through the misspelling of science.

Raymond


On 04/29/2015 11:41 AM, WormBase Helpdesk wrote:
>
>   How do I scyence?
>
> Reported by: Ever******** (16co**************) (obscured for privacy))
> Submitted From: dpy-11 (gene) 
> /species/c_elegans/gene/WBGene00001073#0-9f-3 
> <http://www.wormbase.org//species/c_elegans/gene/WBGene00001073#0-9f-3>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 
> (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/3831>.
>


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
