### ISSUE TITLE
 Server Error: 500 at  tools/ontology_browser/run ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3832]
<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/ontology_browser/run?inline=1&class=go_term&name=GO:0004518">tools/ontology_browser/run</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools->tools "malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/ontology_browser.pm line 829." </p>

Reported by: Jere*** (jl57***********)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.9 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.9

**Comment by dasmoth** [comment]
Confirmed.  I'm seeing this for all GO terms I've tried, on both live and staging.

**Comment by azurebrd** [comment]
Thank you for letting us know.  It looks like there was a problem with
the solr server before, and it's back to working now.  The admin is
looking into why it happenned.

Juancarlos, Help Desk
