### ISSUE TITLE
  I'm wondering are eat-18 and lev-10 s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3835]
<p>&nbsp;&nbsp;I'm wondering are eat-18 and lev-10 supposed to have the same sequence identifier (Y105E8A.7)? I had thought that each gene had a different sequence identifier?<br/>Regards,<br/>Avril</p>

Reported by: Avri********* (alc@************)  (obscured for privacy))
Submitted From: lev-10 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00002977#0-9e-3">/species/c_elegans/gene/WBGene00002977#0-9e-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Firefox/31.0

**Comment by xdwang** [comment]
Hi Avril,

If you open ‘Tree Display’ widget, you will see in ‘Remark’, it says: 

This single locus has two gene products, lev-10 and eat-18


Xiaodong Wang





> Hi Avril,On May 1, 2015, at 8:19 AM, no-reply@wormbase.org wrote:
> 
> Content Correction 
>   I'm wondering are eat-18 and lev-10 supposed to have the same sequence identifier (Y105E8A.7)? I had thought that each gene had a different sequence identifier?
> Regards,
> Avril
> 
> Submitted From: 
>   lev-10 (gene) /species/c_elegans/gene/WBGene00002977#0-9e-3 <http://www.wormbase.org//species/c_elegans/gene/WBGene00002977#0-9e-3>
> This issue has been assigned ticket number: #3835. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3835>.
> 
> 
> Reported by: Avril Coghlan (alc@sanger.ac.uk <mailto:alc@sanger.ac.uk>) 
> 01 May 15 12:20 
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Firefox/31.0 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125

**Comment by xdwang** [comment]
Dear Xiaodong Wang,

Thanks very much for your helpful reply.

Kind Regards,

Avril
