### ISSUE TITLE
  Hello, I'm looking for a reliable pro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3839]
<p>&nbsp;&nbsp;Hello,<br/>I'm looking for a reliable protein sequence file for the entire C. elegans proteome. Do you have a file containing the sequences for all known proteins in C. elegans? <br/>I'd also like to avoid including dubious proteins in my analysis if possible (i.e. proteins encoded by dubious open reading frames and therefore likely do not exist).<br/>If someone could let me know I'd greatly appreciate it.<br/>Best,<br/>Michael Vincent</p>

Reported by: Mich*********** (vinc*************)  (obscured for privacy))
Submitted From: Protein <a href="http://www.wormbase.org//species/c_elegans/protein#1-0-5">/species/c_elegans/protein#1-0-5</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11

**Comment by epaule** [comment]
have a look at: http://www.wormbase.org/species/c_elegans
in the Downloads section is a link to the proteins.

The one linked is the current set, without any historical proteins.

At least for C.elegans all of our genes were manually checked and are continuously curated, so they represent the current state of art of C.elegans research.

If you encounter any protein you think looks dubious, feel free to contact us.
