### ISSUE TITLE
  We are interested in studying the exp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3840]
<p>&nbsp;&nbsp;We are interested in studying the expression of the two prpf-4 (F22D6.5) isoforms during C. elegans development.<br/>We would like to know further details about the experiment that lead to the identification of these two isoforms, that is, the developmental stage in which RNAseq was performed and how these two transcripts were confirmed by cDNA, as it is indicated in the annotation.<br/>Thank you very much for your attention.</p>

Reported by: Xèni* (xeni********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by gw3** [comment]
The two isoforms have been curated as:
isoform 'a' with a final, seventh intron based on the evidence of many ESTs
isoform 'b' with a retained seventh intron based on the evidence of the EST
'AU214183'.

There is mass-spec peptide evidence that the 'a' isoform is translated.
(i.e. peptide MSP:TLLDGMLILDPSKR matching in the final exon)
There is no mass-spec evidence that the 'b' isoform is translated. (i.e. no
mass-spec peptides matching against the very short unique region of 30
bases at the end of isoform 'b')

There is some RNASeq evidence in many libraries across all life stages of a
partially retained seventh intron.
The evidence for the retained seventh intron is complicated however by the
snoRNA gene (F22D6.16) in this intron in the same sense as F22D6.5a/b .
It is probable that the EST and RNAseq evidence for a retained intron comes
from incomplete splicing of the intron during processing to produce the
snoRNA transcript.

Our curators have curated the F22D6.5b isoform based on the cautious
assumption that the transcripts with the retained intron are processed as
coding transcripts and are not just incompletely spliced.
Until we get further confirmation from experiments to test this, I believe
that this locus is curated correctly.

Gary Williams
