### ISSUE TITLE
  How do I find protein expression -- t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3844]
<p>&nbsp;&nbsp;How do I find protein expression -- tissue specificity.<br/>On older version of WormBase if the tissue specificity information was available it was noted and there was picture of worm with expression data in green.<br/>Many thanks!</p>

Reported by: Nidh******** (nidh*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; AskTbORJ/5.15.23.36191; .NET4.0E)

**Comment by draciti** [comment]
Hi Nidhi,

you can access expression data -tissue specificity and images- from the gene page by clicking on the Expression widget on the left side bar and then by selecting individual expression objects in the anatomic expression patterns table. See attached screenshot.

To access the gene page type the name of the gene on the top right corner of the Wormbase homepage.

Do not hesitate to contact us if you have any additional questions.

Daniela

**Comment by draciti** [comment]
Thanks a lot.

Great help.

Nidhi

________________________________________
From: Daniela Raciti <draciti@caltech.edu>
Sent: May 6, 2015 3:31 PM
To: Nidhi Sharma
Subject: Re: Wormbase Gene expression

Hi Nidhi,,
go to wormbase

https://www.wormbase.org

type ugt-8 top right where is written 'search'. you will be directed to this page:

https://www.wormbase.org/species/c_elegans/gene/WBGene00019234#01--10


click on Expr6282, you will be directed to:

https://www.wormbase.org/species/all/expr_pattern/Expr6282#012--10

you should do the same for any other gene.

let me know if you have any additional question.

thanks,
Daniela



On May 6, 2015, at 1:10 PM, Nidhi Sharma wrote:

Hi Daniela,

Thanks for mail. I am looking for UGT gene family tissue specific expression profile. If possible could you please send me the link how to see the expression of any of these UGTs.UGT-8/UGT-33/UGT-14.

Many thanks
Nidhi
