### ISSUE TITLE
  How to register the wormbase ? I only...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3845]
<p>&nbsp;&nbsp;How to register the wormbase ?<br/>I only find the login.</p>

Reported by: Kang**** (xiek**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36

**Comment by tharris** [comment]
User duplicated request; addressed on mailing list:

You will need to sign in using a Google or Facebook account now. Click on either of those buttons, authenticate at the respective site, and you will be signed in to WormBase.
