### ISSUE TITLE
The Protein Motifs track on GBrowse is empty

### ISSUE THREAD

**Issue by tharris** [WormBase/website#3847]
The Protein Motifs track is empty. I haven't triaged to see if this is loss of data, changed data format, or problem with the configuration generator.

**Comment by scottcain** [comment]
Hmm, this command:
```
gzip -dc c_elegans.PRJNA13758.WS248.annotations.gff3 | grep -P "\ttranslated_feature\tsequence_motif\t"
```
turned up nothing, as far as GBrowse is concerned, the data has gone missing.  I'm digging in the GFF file to see if it's been renamed or if it's just plain gone.

**Comment by tharris** [comment]
maybe try a less specific grep for just source or type?

**Comment by khowe** [comment]
sequence_motif was changed to polypeptide_motif, on advice from the Sequence Ontology people. This happened in WS246, and was reported in issue #3307

**Comment by tharris** [comment]
It looks like the gbrowse_246 branch was never merged. @scottcain you should merge changes from that branch into a gbrowse branch for WS248 as it will fix the other modified features.

**Comment by tharris** [comment]
Sorry, let me clarify. @scottcain do you have the newest version of the website-admin repo?  You should also check the config stubs in the includes/ path.

**Comment by scottcain** [comment]
After looking at this commit: https://github.com/WormBase/website/commit/ea7216089aa558b2e3e1862663a194faeb40e1e3 it looks to me like the only modified track configs were those that had to do with protein motifs.  The only thing that looked a little odd to me about that commit is that some species that had protein motifs had them removed.  I'll double check that the 248 agrees, but if the ones that had the protein motif tracks removed don't have those features, then I don't think there is anything else to do.

**Comment by tharris** [comment]
Some commits addressing changes to some variation entries also.

**Comment by scottcain** [comment]
True, but it doesn't look to me like those "affect" anything, which is to say, the gbrowse configurations don't change do they?  Those changes are in generated files and presumably have already be superseded by the files generated for 247 and 248 (based on my still limited understanding of what's going on).

Also, it seems that some organisms GFF files have "polypeptide_motif" and some are still using "sequence_motif"; that's a bit of a hassle and I'm wondering if that's expected.  @khowe, do you have an opinion?  If it helps, I'm creating a list of the which GFF files use which type.

**Comment by scottcain** [comment]
Uses sequence_motif in 248:
c_japonica
c_brenneri
c_briggsae
p_pacificus

Uses polypeptide motif:
b_malayi
c_elegans
c_remanei
o_volvulus

**Comment by khowe** [comment]
Hmm, yes, this is unfortunate and unintended. GFF for a species is only redumped when we include that species in the build (which we do when we have accumulated enough gene model changes, or other new data, for a species to make an update worthwhile). Since those 4 species have not been rebuilt since WS246, they still have the old "sequence_motif" in their GFF. 

We should have been (and should be) more careful about propagating changes such as this to all GFFs. Will do this for the 4 species above for WS248, so that they are consistent.

**Comment by khowe** [comment]
Updated GFF3 files now available on Sanger FTP:

ftp://ftp.sanger.ac.uk/pub/consortia/wormbase/releases/WS248

I think that this is mirrored automatically to ftp.wormbase.org ( @tharris to confirm).

**Comment by tharris** [comment]
Mirroring is currently only automatic for staging purposes. The main FTP site is created late during staging (and updated as needed). I had to do this simply because of its size (and the capacity of the existing FTP site).

Have mirrored updates and will recreate GFF databases shortly.

**Comment by scottcain** [comment]
The 249 GBrowse instance has all of the above mentioned organism's protein motif tracks as expected, closing.
