### ISSUE TITLE
  obtain a  mutant strain for IGF/insul...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3851]
<p>&nbsp;&nbsp;obtain a  mutant strain for IGF/insulin</p><p>What were you doing? <br />&nbsp;&nbsp;I am interested in determining if an inhibitor of PKC-1 improves the metabolism of lipids in this mutant.</p>

Reported by: mari**** (ahum**********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by chris-grove** [comment]
Hello Marisela,

 Strains can be ordered from the CGC:

https://www.cbs.umn.edu/research/resources/cgc

Best,

Chris Grove
