### ISSUE TITLE
JBrowse gene popup

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3852]
The gene popup is missing the root of the URL or points to a wrong one:

![screenshot 2015-05-08 at 15 12 52](https://cloud.githubusercontent.com/assets/20523/7537999/d46ae038-f594-11e4-809d-8943d666a9f5.png)

**Comment by scottcain** [comment]
Hi @epaule Sorry about that--I'm transitioning jbrowse to live on the same subdomain as the rest of WB so the configurations are set to use relative URLs now.  If you want to try it out while I'm working on it, you can point your browser on staging to /tools/genome/jbrowse.

**Comment by epaule** [comment]
that explains it.
Are you pushing it out onto the main site too or just staging?
And give a shout to staff@ if you need specific pre-release testing

**Comment by scottcain** [comment]
@epaule It should go live on the main site when 248 is promoted (assuming nothing goes massively wrong).  I'll send a call out for testing when it's ready; thanks.
