### ISSUE TITLE
  Hi there, I was wondering how we can ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3853]
<p>&nbsp;&nbsp;Hi there,<br/>I was wondering how we can find and download the nucleotide sequence of any C. elegans gene on Wormbase. We have tried multiple links for a gene (ugt-15 as an example) and can only every find the protein sequence. It seems that the nucleotide sequence does not exist for genes on this site?<br/>Thanks!<br/>Andrew</p>

Reported by: andr************ (arez****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by raymond91125** [comment]
If you go to the ugt-15 gene page 
<http://www.wormbase.org/species/c_elegans/gene/WBGene00020593>, go to 
the widget "Sequences"  (link found on the left under "Page Content"), 
and click on a little double helix icon, and then tick the triangle in 
front of specific sequences, you should then see the sequence strings.

Write again if you get stuck.

Raymond


On 05/08/2015 10:56 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi there,
> I was wondering how we can find and download the nucleotide sequence 
> of any C. elegans gene on Wormbase. We have tried multiple links for a 
> gene (ugt-15 as an example) and can only every find the protein 
> sequence. It seems that the nucleotide sequence does not exist for 
> genes on this site?
> Thanks!
> Andrew
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3853. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3853>.
>
> Reported by: andrew rezansoff (arezansoff@gmail.com)
> 08 May 15 17:57
>
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/42.0.2311.135 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
oops, the page linked is for ugt-11. just to be pedantic.

raymond


On 05/08/2015 11:03 AM, Raymond Lee wrote:
> If you go to the ugt-15 gene page 
> <http://www.wormbase.org/species/c_elegans/gene/WBGene00020593>, go to 
> the widget "Sequences"  (link found on the left under "Page Content"), 
> and click on a little double helix icon, and then tick the triangle in 
> front of specific sequences, you should then see the sequence strings.
>
> Write again if you get stuck.
>
> Raymond
>
>
> On 05/08/2015 10:56 AM, no-reply@wormbase.org wrote:
>> How Do I ...?
>>
>>   Hi there,
>> I was wondering how we can find and download the nucleotide sequence 
>> of any C. elegans gene on Wormbase. We have tried multiple links for 
>> a gene (ugt-15 as an example) and can only every find the protein 
>> sequence. It seems that the nucleotide sequence does not exist for 
>> genes on this site?
>> Thanks!
>> Andrew
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #3853. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/3853>.
>>
>> Reported by: andrew rezansoff (arezansoff@gmail.com)
>> 08 May 15 17:57
>>
>> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like 
>> Gecko) Chrome/42.0.2311.135 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> To unsubscribe from this group and stop receiving emails from it, 
>> send an email to help+unsubscribe@wormbase.org 
>> <mailto:help+unsubscribe@wormbase.org>.
>
>
> -- 
> __
> Raymond Lee
> raymond@caltech.edu
> http://www.WormBase.org/
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Great thanks Raymond, they were hiding in plain sight. Didn't see the drop down.

Andrew
