### ISSUE TITLE
  Hello, How do I convert a list of Wor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3855]
<p>&nbsp;&nbsp;Hello,<br/>How do I convert a list of Wormbase identifiers to gene names?  I tried using the Wormbase converter http://www.ciml.univ-mrs.fr/applications/WB_converter/ but it doesn't seem like it's working.<br/>Thanks.</p>

Reported by: mcow********  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3

**Comment by epaule** [comment]
have you tried WormMine?
http://www.wormbase.org/tools/wormmine/bag.do
