### ISSUE TITLE
Homology/Orthology Data In WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3856]
<p>&nbsp;&nbsp;What happened to homology function in wormmine?  It would be very nice to list human homologs, etc. in worm mine.<br/>Thanks,<br/>Brian</p>

Reported by: Bria**********\* (krae*********************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by epaule** [comment]
I don't know the current state of the WormMine plans,
but if it is just a filter by homologs, you can abuse the parasite.wormbase.org BioMart, as it also includes for comparative reasons, C.elegans.
So you can pick C.elegans -> Genes and your filter of choice.

**Comment by epaule** [comment]
refers to #1519

**Comment by Paul-Davis** [comment]
This looks like something that should be prioritised for inclusion in WormMine as the "MOD Uniform Gene Model" initiative will need this data to be included if our mine data is to be included in the project.

**Comment by chris-grove** [comment]
PANTHER homologies have been added
