### ISSUE TITLE
  How do I perform a query with a list ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3857]
<p>&nbsp;&nbsp;How do I perform a query with a list of phenotypes to return a list of genes.<br/>I would like to combine the phenotype list using an 'or' operator, so that I get a list of genes containing any of my listed phenotypes.</p><p>What were you doing? <br />&nbsp;&nbsp;Attempted to add multiple constraints to phenotype while querying for a gene.  It automatically combined them with the 'and' operator. When I attempt to change this to an 'or' operator I get an error. </p>

Reported by: Vale*******\* (vsap**********)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by chris-grove** [comment]
Hello Valerie,

 Apologies for the error. I assume you're using WormMine to retrieve this information? You may get better results if you create and save a WormMine list of phenotypes and then use that list as the constraint for the query. I believe it will automatically use the "OR" operator in that context. Let me know if you need help with this and I'd be happy to assist.

Best,

Chris Grove

**Comment by chris-grove** [comment]
@tharris  There is an error when constraining on phenotypes and updating the Boolean operation for multiple constraints. I'm not sure if this problem exists for other data types

**Comment by raymond91125** [comment]
Just to add that another way to do this, in a more manual manner is to 
use the ontology browser to look up genes for each phenotype then 
combine the lists afterwards. The benefit is that the phenotype ontology 
browser not only returns genes annotated with the focus term but also 
any term that is a 'transitive descendant'. Taking for example, for the 
"early embryonic lethal" phenotype 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001100>, in 
the Ontology Browser widget, there are 41 genes directly annotated but 
937 genes total (direct+indirect).

Single-phenotype lists of genes can be combined using the List tool in 
WormMine 
(<http://www.wormbase.org/tools/wormmine/bag.do?subtab=upload>); paste 
all genes in the box and the outcome is OR-combined.

Raymond

**Comment by raymond91125** [comment]
Thanks Raymond. I had also been running into issues withe the 'transitive descendant' terms. This is now working well for me.

Thanks!

**Comment by chris-grove** [comment]
This appears to be fixed in im-254 version of WormMine
