### ISSUE TITLE
D. immitis genome browsers are broken

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3859]
See, e.g.:

        http://www.wormbase.org/species/d_immitis/gene/PRJEB1797:nDi.2.2.2.g04442#0-9-10

If you try to fetch the browser image URL, you get a server error:
 
       http://www.wormbase.org/tools/genome/gbrowse_img/c_elegans_PRJNA13758/?name=nDi.2.2.scaf00088%3A112420..119921;t=GENES;t=VARIATIONS_CLASSICAL_ALLELES;t=CLONES

On the other hand, if you click on the broken image to link out to the main genome browser, you get a very weird redirection to B. malayi.

Staging behaves the same as live, except that the redirect goes to H. contortus instead...

Could possibly be related to #3514...

**Comment by scottcain** [comment]
Hmm, the broken image url in that page is trying to fetch a C. elegans gene and is failing since there isn't a C. elegans gene named nDi.2...  It looks like there is some misconfiguration that is causing the image url to be written incorrectly.  @sibyl229 any idea what's going on there?

**Comment by scottcain** [comment]
Also, as a side note, the D. immitis browser itself appears to be working correctly: if I search for nDi.2.2.2.g04442 in GBrowse's search bar, GBrowse does return the correct image on both production and staging.

**Comment by tharris** [comment]
@scottcain, yes the browser isn't broken, just generating the gbrowse_ing URL. It's likely that the gene page does not know it is dealing with a D. inmmitis gene and this default to elegans. This is likely due to an unspecified Species tag. That's my top guess.

**Comment by tharris** [comment]
Should self resolve in WS249

**Comment by dasmoth** [comment]
Thanks, I understand a bit better why the image is broken now.

However, I'm  still puzzled why the link (<a> tag) associated with the image isn't working.  This *does* appear to get the species right, but when you try to follow it, it's redirected to another species (Brugia on live, H. contortus on staging).  The inconsistency between live and staging is kind-of odd in itself.

**Comment by scottcain** [comment]
That's weird: both links on production (the text "Genomic position" link and clicking on the broken image) take me to the D. immitis browser for me.  Maybe there is a caching problem?

**Comment by dasmoth** [comment]
I've just tried it from a different machine, and this time got redirected to C. elegans!

A bit more experimentation suggests that I'm getting redirected to whichever species I last viewed in GBrowse.  This might mean that it's working for @scottcain because you've just been looking at D. immitis sequences, having navigated to that species within GBrowse?

**Comment by sibyl229** [comment]
Hi @scottcain I also observed what Thomas described: the redirect retains memory of last visited GBrowse URL. It's puzzling thought, that theres's a 302 redirect response at all, when visiting the D. immitis gene. It probably should be a 404 or 200.

Here's my browser network log: 
![screen shot 2015-05-13 at 12 27 03 pm](https://cloud.githubusercontent.com/assets/1753893/7615383/630bdcdc-f96b-11e4-96b0-cbdef9886365.png)

**Comment by tharris** [comment]
FYI: GBrowse emits the 302 because it tries to redirect to the default species.

**Comment by dasmoth** [comment]
Thanks @tharris, it's working nicely now.
