### ISSUE TITLE
Develop strategy and protocol for mirroring ParaSite FTP to ftp.wormbase.org

### ISSUE THREAD

**Issue by tharris** [WormBase/website#3865]

**Comment by khowe** [comment]
ParaSite FTP site is here:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases

**Comment by khowe** [comment]
Notes: 

- the data for Brugia and Onchocerca comprises symlinks to the corresponding files on WormBase (we host the WormBase release data on the same server). This is a nod towards that fact that WormBase central is the authoritative home for these species, and also makes it obvious that the B. mal and O.vol data for ParaSite release WBPS2 (for example) was drawn from WormBase release WS245. These symlinks are relative, so should still work (and be correct) in the mirror.

**Comment by tharris** [comment]
Complete. Scheduled for routine mirroring once a day.
