### ISSUE TITLE
  The gene currently named col-70 does ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3866]
<p>&nbsp;&nbsp;The gene currently named col-70 does not appear to encode a collagen; the predicted protein lacks a signal sequence and does not have the Gly-X-Y repeat that defines collagens. It contains a repeating GGxG motif and is closely related to the two adjacent genes, which seem to be nematode specific. (I can't think of a good name for these genes, but col-70 is misleading).</p>

Reported by: Andr*********** (chis*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17

**Comment by gw3** [comment]
The structure of col-70 needs some urgent attention.

The first two exons are wrong - they should be removed.
This will give a signal sequence at the start.

This doesn't affect the motif, of course.

Gary Williams

**Comment by gw3** [comment]
I can confirm that the 1st 2 exons have been removed from the gene 
structure for the WS250 release of WormBase.

Thanks

Paul


On 14/05/2015 16:33, Gary Williams wrote:
> The structure of col-70 needs some urgent attention.
>
> The first two exons are wrong - they should be removed.
> This will give a signal sequence at the start.
>
> This doesn't affect the motif, of course.
>
> Gary Williams
>
> On Thu, May 14, 2015 at 4:22 PM, <no-reply@wormbase.org 
> <mailto:no-reply@wormbase.org>> wrote:
>
>     Content Correction
>
>       The gene currently named col-70 does not appear to encode a
>     collagen; the predicted protein lacks a signal sequence and does
>     not have the Gly-X-Y repeat that defines collagens. It contains a
>     repeating GGxG motif and is closely related to the two adjacent
>     genes, which seem to be nematode specific. (I can't think of a
>     good name for these genes, but col-70 is misleading).
>
>     Submitted From:
>       support /tools/support <http://www.wormbase.org//tools/support>
>
>     This issue has been assigned ticket number: #3866. Follow progress
>     on our issue tracker
>     <https://github.com/WormBase/website/issues/3866>.
>
>     Reported by: Andrew Chisholm (chisholm@ucsd.edu
>     <mailto:chisholm@ucsd.edu>)
>     14 May 15 15:23
>
>     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3)
>     AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5
>     Safari/600.5.17
>
>     This question was reported via the web interface at wormbase.org
>     <http://wormbase.org>. You can also email us
>     <mailto:help@wormbase.org> directly.
>
>     -- 
>     -- 
>     You received this message because you are subscribed to the
>     "WormBase: help" group.
>     To post to this group, send email to help@wormbase.org
>     <mailto:help@wormbase.org>
>     To unsubscribe from this group, send email to
>     help+unsubscribe@wormbase.org <mailto:help%2Bunsubscribe@wormbase.org>
>     For more options, visit this group at
>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
gah, thought I could assign 2 people but maybe not :(

**Comment by tuli** [comment]
Hi Tim,

Please can you take a look at this.

Sequence curators have already updated the structure of the gene.

Thank you,

Mary Ann

On 14 May 2015 at 16:22, WormBase Helpdesk <notifications@github.com> wrote:

>   The gene currently named col-70 does not appear to encode a collagen;
> the predicted protein lacks a signal sequence and does not have the Gly-X-Y
> repeat that defines collagens. It contains a repeating GGxG motif and is
> closely related to the two adjacent genes, which seem to be nematode
> specific. (I can't think of a good name for these genes, but col-70 is
> misleading).
>
> Reported by: Andr*********** (chis*************) (obscured for privacy))
> Submitted From: support /tools/support
> <http://www.wormbase.org//tools/support>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17
> (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3866>.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Mary Ann, 

I agree with Andrew, H17B01.2 is not a collagen, and thus the name is misleading. 
We should eliminate the gene name "col-70", revert back to the Seqeunce name H17B01.2 and list col-70 as other name. 

Thanks, 
Tim 

----- Original Message -----

**Comment by tuli** [comment]
Dear Andrew,

Further to Tim's approval I have removed col-70 from H17B01.2.

The update will be available in release WS250 of WormBase.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
