### ISSUE TITLE
Community Curation Portal - Website

### ISSUE THREAD

**Issue by tuli** [WormBase/website#3867]
Initial ideas which were discussed at the CalTech call 7th May 2015

1) Add a tab on the website next to Parasite. 
The tab should be called "Submit Data" and "Allele Phenotype" will (for the moment) be the only option on the drop down from this tab. 
It should be in an eye-catching colour. 

2) If users click on "Allele Phenotype" they go straight to Allele Phenotype form (on tazendra)

3) If users click on "Submit Data" they go to a landing page (the current http://www.wormbase.org/about/userguide/submit_data) 

a) /submit_data (or /community_curation) needs a massive overhaul. 

b) The focus of this page (for the moment at least) will be Allele Phenotype data. This is what the user should see when they arrive on the page. A massive red button titled "Submit Allele Phenotype Data". This takes users to the tazendra form. 

c) I think we could rename /submit data to http://www.wormbase.org/community_curation
There should be a small amount of explanation text. 

d) The lower part of /submit_data (or /community_curation) should list both the new Micropublication and Gene (Concise) Description form, as well as submission forms already listed*
- the list needs updating to remove some which are never used and then some reorganisation. 

This part of the page will also contain links to Community Curation guidelines/help and an About link which explains our goals and what's in it for the community.

**Comment by tuli** [comment]
@sibyl229 
Do you think you could have a look at this. It's something we'd like to have available before the Worm Meeting next month.

**Comment by tharris** [comment]
We will take a look at this once we finish the data development for WS248 (due May 22nd).

I'm not sure about renaming "submit" to "community curation". First, it isn't really a term or concept used by biologists (yet?). Second, submitting data isn't really the same as community curation, which implies (to me at least) something different -- collecting, collating, examining, and correcting existing annotations.

**Comment by tuli** [comment]
@tharris 
Thanks. 
I understand what you're saying regarding submit vs community curation. The naming of the pages is something we can discuss later.

**Comment by sibyl229** [comment]
Hi @tuli here is what I have for the submit data link http://staging.wormbase.org/about/userguide/submit_data#0--10 The actually link isn't correct though. Could you please send me the links for allele phenotype, micropublication, and gene concise description that you'd like to add?

In the submit data Overview, many forms are grouped by categories. Do you want Allele phenotype (or any of the other forms) to be listed as a top-level category?

**Comment by tuli** [comment]
Thank you @sibyl229 

The URL for Allele-Phenotype data is http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/allele_phenotype.cgi
The URL for Expression data Micropublication form is http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/mpub.cgi
The URL for Gene Description form is http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/community_gene_description.cgi 

nb. mangolassi is a development URL, so these will change (to tazendra) when they are complete. 

I didn't describe what I wanted http://staging.wormbase.org/about/userguide/submit_data to look like very well so I shall try again. 

Question: since this page currently only lists submission forms, do they need to contained within the Overview widget? I mean, can we just not have the Overview widget and simply list the links etc?

The focus of this page (for the moment at least) will be Allele Phenotype data. This is what the user should see when they arrive on the page. A massive red button titled "Submit Allele Phenotype Data". 
This link should be right at the top of the page, even before the "WormBase Online Data Submission forms" title and intro paragraph. 

Please make the Allele Phenotype Data link larger. 

Add a horizontal line 

Below the horizontal line please add a sub-heading "Community Curation" and leave some space for a paragraph of text.

Below the paragraph of text please link "Expression Data Micropublication form" http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/mpub.cgi 
e.g.
Expression Data Micropublication [Fill out online form]
[Help] - goes to http://mangolassi.caltech.edu/~acedb/draciti/Micropublication/Guidelines.htm

Below the Micropublication form please link "Gene Descriptionhttp://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/community_gene_description.cgi
e.g. 
Gene Description  [Fill out online form]
[Help] - not yet written. 

Add a horizontal line

Below this line have the sub-heading "WormBase Online Data Submission forms" and the following paragraph of text.

Below the text list all the forms as they appear now, starting with General. 

In answer to your question about categories, no - just leave the three new forms as stand-alone for the moment, and the existing forms as they appear.

I hope this is clear.

**Comment by tharris** [comment]
The About/submit_data page is editable by anyone with a wormbase.org account. The content and formatting of this page is probably best and most directly handled by a curator.

**Comment by tuli** [comment]
Ohhhh, I didn't know that! Off I go then! @sibyl229, no need for you to do anything until I've played with the page myself.

**Comment by sibyl229** [comment]
Hi @tuli I edited the Submit data page to include the links you provided. You could use those as examples when adding more content. Just let me know if anything doesn't work.

The widget doesn't have to be called Overview, but it requires a name. You can modify it any time.

**Comment by tuli** [comment]
Note for @azurebrd and @sibyl229 - make sure we change links to submission forms from development to live at the appropriate time.

**Comment by chris-grove** [comment]
@sibyl229  @tuli    Just to confirm: We will want to go live with the Allele-Phenotype form in WS248 when it goes live with a link to:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele_phenotype.cgi

@azurebrd  and I will make sure things are up and running on the Tazendra machine over the next day or two. I hope we can discuss on the site-wide conference call tomorrow.

**Comment by dasmoth** [comment]
Playing with the Allele-Phenotype form...  The "Can't find your phenotype?" labels have what look like checkbox controls next to them.  However, if I click one of these it causes an irreversible change to the page -- adding some new fields and removing the checkbox.  This seems unnecessarily alarming -- can you leave the checkbox so it's possible to reverse the change.  Better still, show the "Suggest Observed Phenotype" fields by default (maybe inactive/greyed out until you select a "Can't find my phenotype?" checkbox), so users can see immediately what they're getting into.

**Comment by dasmoth** [comment]
It's not entirely obvious when you start that the form is going to allow you to enter more than on phenotype.  Worth adding a note somewhere that this is possible?

Also, a minor bug I think.  Enter one phenotype, get an extra phenotype field.  But then hit "Preview" to see how things are going, and you're back down to a single phenotype field.  Had to delete and re-enter the last character of my existing phenotype before I could enter another one.

**Comment by chris-grove** [comment]
@dasmoth  Thanks for your comments! I've reposted them in a separate ticket #3929 
I will respond to you there

**Comment by rankishore** [comment]
@tuli and @sibyl229: Great work on the community curation page. 

 I had a couple of comments, looks like the staging page hasn't been completely ported over to the live WS248 site as yet.  I don't see the page that @tuli has edited, but from what I see--
http://www.wormbase.org/about/userguide/submit_data#0--10
Does 'Submit Data' have to be under 'User guide', can we do away with the 'User guide', as there's nothing related to the User guide here (the link 'User guide' itself goes to an empty page).

2.  If we are going to replicate http://www.wormbase.org/about/userguide/submit_data#10--10 for the live WS248 site, would it be better to put the whole Community curation part, on top of the page so that people see the new stuff first?  

3.  Could the widget be called Community Curation?  Now it's called 'Overview', the Allele Phenotype form is on top and then followed by the heading 'Community Curation' and then the 'Expression Data Micropublication' and the 'Gene Description' forms.  Shouldn't all three forms be under 'Community Curation'?

**Comment by sibyl229** [comment]
Hi @rankishore those widgets aren't ported over from staging automatically, but can be edited by WormBase staff any time (login to on WormBase site is needed though). You can also copy the widget content from staging to production site.

**Comment by rankishore** [comment]
Thanks @sibyl229 for your quick response!  I'll let @tuli comment and take the lead as she's been working on this.

**Comment by tuli** [comment]
@rankishore is right, the version of /submit_data I had created on staging did not make it to the live site. The Community Curation widget was missing. I have added it now, and copied the html (exactly) from staging to live, BUT it does not look nice at all! nb we've removed the buttons as they looked very odd. @sibyl229, is html code different between staging and live? 

I have changed the name of Overview to Community Curation and have removed the Community Curation sub-heading from this widget. 

@sibyl229, am I able to change the order of the widgets in the left hand menu? I would like it to be Community Curation and then Submit other data. 

www.wormbase.org/about/userguide exists and has a link in the bottom black banner. 

todo: I will update the Submit Data widget within /userguide. 

todo: The Submit data link within the black banner needs to go to: http://www.wormbase.org/about/userguide/submit_data

**Comment by tuli** [comment]
DONE - Allele Phentoype form link in Community Curation widget updated to tazendra

**Comment by tuli** [comment]
@sibyl229 Thank you for the changes you have made. It looks a lot better, but still not quite right. 

1) Please can you make "Fill out online form" look on live look this they do on staging ie Allele Phenotype a deep red button and the other two a grey button. As I said, even though I copied the html exactly from staging to live, the buttons did not come out right. 

Thank you for changing the order of the widgets. 

2) The Submit data link within the black banner needs to go to: http://www.wormbase.org/about/userguide/submit_data

@rankishore I see Gene Desc form has been updated to tazendra.

**Comment by sibyl229** [comment]
Hi @tuli 

I edited the button style in Community curation widget on production. It looks like what's on staging now. http://www.wormbase.org/about/userguide/submit_data#01--10

I updated the footer link http://staging.wormbase.org/about/userguide/submit_data#01--10 .  I will ask Todd to merge it to production later this week along with other hot fixes.

**Comment by tuli** [comment]
@sibyl229 just noticed on safari that repeat refreshing of the page sometimes shows bad buttons. 
![screen shot 2015-06-25 at 21 42 59](https://cloud.githubusercontent.com/assets/1359170/8370850/2b6d4da8-1b83-11e5-9c76-a9b336998ee0.png)

**Comment by sibyl229** [comment]
Done.
