### ISSUE TITLE
ePCR link is throwing 504 Gateway Time-out error

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3869]

**Comment by chris-grove** [comment]
Now it's throwing a 502 Bad Gateway error

**Comment by tharris** [comment]
Hi Chris. I am working on the issue. Will report back when complete.

**Comment by chris-grove** [comment]
@tharris  Sounds good thanks!

**Comment by tharris** [comment]
Please test...

**Comment by chris-grove** [comment]
Looks good! Thanks Todd!
