### ISSUE TITLE
  Hello, I am looking for spp mutants a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3873]
<p>&nbsp;&nbsp;Hello,<br/>I am looking for spp mutants and found 4 ssp5 homozygous viable mutants at the shigen.nig. Now I have a problem in getting more information about the alles, because in 3 of these four mutants I am getting no results in wormbase for further information. The missing allels are tm7122, tm7123 and tm6956.<br/>Do you have any ideas, advances or others to help me?<br/>Best regards<br/>J. Rabsch<br/>Dr. Jessica Gewiese Rabsch<br/>Zoologisches Institut der CAU Kiel<br/>Vergleichende Immunbiologie<br/>Am Botanischen Garten 3-9<br/>24118 Kiel<br/>Germany<br/>0431 880 4193</p>

Reported by: Dr. ********************** (jrab************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by tuli** [comment]
Dear Jessica,

Thank you for writing to WormBase.

The deletions you are looking for were only recently submitted to
WormBase and will visible in release WS249 (Aug 2015).

The information available about deletions on the NBP site is quite
comprehensive - what WormBase does is to map the deletion to the
genome, giving specific details as to where in a transcript a deletion
targets, as well as showing the deletion on the genome browser.

Looking at the data, it seems that only tm7122 deletes part of the
spp-5 transcript, and I have included the mapping information here
which I hope is of use to you.

Neither tm7123 or tm6956 delete part of spp-5

Variation : "WBVar02144346"
Public_name      "tm7122"
Predicted_CDS    "T08A9.9" Coding_exon Inferred_automatically "map_Alleles.pl"
Transcript       "T08A9.9.1" UTR_5 Inferred_automatically "map_Alleles.pl"
Transcript       "T08A9.9.2" UTR_5 Inferred_automatically "map_Alleles.pl"

best wishes,

Mary Ann



On 18 May 2015 at 07:10, <no-reply@wormbase.org> wrote:
>
> How Do I ...?
>
>   Hello,
> I am looking for spp mutants and found 4 ssp5 homozygous viable mutants at the shigen.nig. Now I have a problem in getting more information about the alles, because in 3 of these four mutants I am getting no results in wormbase for further information. The missing allels are tm7122, tm7123 and tm6956.
> Do you have any ideas, advances or others to help me?
> Best regards
> J. Rabsch
> Dr. Jessica Gewiese Rabsch
> Zoologisches Institut der CAU Kiel
> Vergleichende Immunbiologie
> Am Botanischen Garten 3-9
> 24118 Kiel
> Germany
> 0431 880 4193
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3873. Follow progress on our issue tracker.
>
> Reported by: Dr. Jessica Gewiese-Rabsch (jrabsch@zoologie.uni-kiel.de)
> 18 May 15 06:12
>
> Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
