### ISSUE TITLE
  Blast/blat tool seems to be down. Any...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3876]
<p>&nbsp;&nbsp;Blast/blat tool seems to be down. Any idea why?</p>

Reported by: Davi********* (davi*******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by ceciliaWBPerson1** [comment]
Hi David - 

Thanks for reporting the problem. It has now been resolved.
