### ISSUE TITLE
  Hello, it's not clear to me which ass...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3877]
<p>&nbsp;&nbsp;Hello, it's not clear to me which assembly is displayed in the GBrowse viewer, and consequently which version the annotation tracks belong to. Specifically, I want to download the most recent annotated splice leader junctions. The only place I can find them is on the GBrowse viewer, but I can't tell which assembly version they are annotated to. Thanks!</p>

Reported by: Sara****** (sara****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by gw3** [comment]
In addition to looking at the GBrowse display, you can find the splice
leader junctions in the GFF2 or GFF3 file:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/

c_elegans.PRJNA13758.current.annotations.gff2.gz
<ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/c_elegans.PRJNA13758.current.annotations.gff2.gz>


 c_elegans.PRJNA13758.current.annotations.gff3.gz
<ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/c_elegans.PRJNA13758.current.annotations.gff3.gz>
You will have to search for the lines with SL1 or SL2 in them:

For example:
CHROMOSOME_I    SL1     SL1_acceptor_site       2446    2447    .
+       .       Feature "WBsf947625"
or
CHROMOSOME_I    SL2     SL2_acceptor_site       3210    3211    .
+       .       Feature "WBsf947929"


Gary Williams

**Comment by gw3** [comment]
Hi Gary,

Thanks for your reply. I downloaded both the splice leader junctions from
GBrowse and the gff3 of current annotations, and actually the two don't
match! The current annotation gff3 file seems correct (the junctions map to
the starts of exons/5' UTRs according to the WS247 gene model annotations),
while the junctions I downloaded from GBrowse are shifted almost 100 bp
upstream, suggesting that they are actually from a different assembly.

I can use the annotations from the gff3 file, but the splice junctions
there are not classified by stage, which they are in GBrowse. Is there
anywhere I can find that information?

Thanks again!
Sarah

**Comment by gw3** [comment]
Hi Sarah,

This sounds like a bug with the genome browser. Would you mind telling us
the id of an SL feature (WBsf.....) that appears be in the wrong position
on the genome browser?

Thanks,

Kevin

**Comment by gw3** [comment]
Sarah,

I think you must be looking at the GBrowse track for the old modENCODE
data, because we don't classify the splice leader junctions by life-stage
in our analysis.

The modENCODE data is probably from release WS220.

**Comment by gw3** [comment]
Hi Gary and Kevin,

I checked again, and yes, the track I was using from GBrowse is from
modENCODE. I didn't realize it was mapped to a different release - that
would explain the discrepancy. Looking a few more sites, they are sometimes
shifted and sometimes not (for example, at the SL1 junctions WBsf125271 and
WBsf125272, the corresponding splice junctions in the modENCODE data are
about 80bp upstream), but I suppose that also has to do with how the
assemblies changed.

Thanks for the help!

Best,
Sarah

**Comment by tharris** [comment]
Apparently resolved?
