### ISSUE TITLE
Tree View out of action on the live site

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3880]
Both the in-page widgets and the stand alone view are dead, giving "502 Bad Gateway" errors.  I'm seeing this even for some pretty small/simple objects (e.g. [Analysis](http://www.wormbase.org/tools/tree/run?name=Million_mutation_project_reanalysis;class=Analysis)), so it's not just a case of timing out on huge objects.

Seems to be fine on staging.

**Comment by tharris** [comment]
Fixed.
