### ISSUE TITLE
  Hello just to inform you that the lat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3883]
<p>&nbsp;&nbsp;Hello just to inform you that the latest paper analysing starvation response on celegans has already been published. Ill add the link: http://mcponline.org/content/early/2015/05/11/mcp.M114.044289.abstract<br/>Furthermore the data is hosted in the Lamond Lab's Encyclopedia of Proteome Dynamics (EPD) available at peptracker.com/epd. Additionally we will be adding an ageing dataset and an additional starvation vs mutant response. If you are interested in linking into the datasets in the EPD feel free to contact me.<br/>Kind Regards<br/>Alejandro</p>

Reported by: Alej************ (a.j.**************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by WenChenWormBase** [comment]
Dear Alejandro:

Thank you for notifying WormBase about your recent publication. I will get
the differentially expressed protein information to WormBase release WS250.
I will email you in the next couple of weeks for more questions.


Wen Chen, Ph.D.
Curator, WormBase


On Thu, May 21, 2015 at 7:33 AM, WormBase Helpdesk <notifications@github.com
