### ISSUE TITLE
  Hallo, when I want tree display of AB...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3885]
<p>&nbsp;&nbsp;Hallo, when I want tree display of AB or P0 or whatever anatomy it answears me Sorry, an error has occured! (since yesterday)<br/>Thank you very much!<br/>Jitka</p>

Reported by: Jitk* (jitk************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by xdwang** [comment]
Tod is working on this issue.

**Comment by tharris** [comment]
The Tree Display is working; note, however, that the Anatomy_term objects corresponding to AB and PO have many XREFed objects. These items may time out when viewed in the Tree Display

**Comment by tharris** [comment]
Who's on the help desk? Can you please test/resolve?

**Comment by xdwang** [comment]
@tharris Both AB and P0 tree display work. Timeout is not happening. I close the issue.

**Comment by xdwang** [comment]
Thanks, Todd.
