### ISSUE TITLE
Mixed content errors on the front page

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3887]
Accessing https://www.wormbase.org/ in recent versions of FireFox or Chrome/ium has a couple of glitches due to dynamically-loaded components that are being accessed over unencrypted HTTPS.  Browsers are now rather strict about mixed HTTPS/plain-HTTP content, and the major browser vendors have stated that they're not going to get any more relaxed about this in the future.

In this case, I suspect the issue can be resolved by using protocol-relative URLs.

![image](https://cloud.githubusercontent.com/assets/209047/7766750/545132d2-0064-11e5-9f10-42b33f4e4013.png)

**Comment by tharris** [comment]
Please see #3888. We plan to adopt https full time for authenticated sessions shortly.
