### ISSUE TITLE
Exact matches in the search field always get redirected to an HTTP URL.

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3888]
1. Browse to the [HTTPS site](https://www.wormbase.org/#01-23-6).
2. Enter a valid gene name (e.g. "pha-4") in the search field.
3. You'll be unceremoniously dumped back onto the unencrypted (HTTP) site.

This seems to be a specific issue with the "exact match" redirect.  If you end up on a disambiguation page, that's still HTTPS.

**Comment by tharris** [comment]
You'll notice that https is used only to support the authentication phase of the log in process. This was the standard at the time before websites (even such sites as Facebook and Google) began using https throughout the session.

Thus, it is not expected that users would navigate to https. We do have plans to extend https through the entire browsing session for authenticated users in the future.
