### ISSUE TITLE
  the genetic map is destroyed. I can n...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3889]
<p>&nbsp;&nbsp;the genetic map is destroyed. I can not get the gene's genetic map. the webpage is broken for two days.</p><p>What were you doing? <br />&nbsp;&nbsp;I am an graduate.</p>

Reported by: zhan****** (xiao*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by sibyl229** [comment]
The genetic map widget takes a long time to load on staging. And it times out on production. @tharris

**Comment by tharris** [comment]
Thanks for letting us know of the problem.  This issue is now resolved.

Please don’t hesitate to contact us if you have additional questions or difficulties.

Best,

Todd
