### ISSUE TITLE
  the genetic map of worm tools seems n...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3892]
<p>&nbsp;&nbsp;the genetic map of worm tools seems not working. can you fix it. thanks!</p>

Reported by: Xian********** (xmwa*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by tharris** [comment]
Thanks for letting us know of the problem.  This issue is now resolved.

Please don’t hesitate to contact us if you have additional questions or difficulties.

Best,

Todd
