### ISSUE TITLE
  Hi, Is there a way to get a FASTA fil...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3893]
<p>&nbsp;&nbsp;Hi,<br/>Is there a way to get a FASTA file with all the protein sequences from a gene list?<br/>Thanks</p><p>What were you doing? <br />&nbsp;&nbsp;I created a list of my genes.
I tried to manage the columns, but could not find the protein sequence option.
</p>

Reported by: Yona******** (yona**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by raymond91125** [comment]
Hi, Yonatan

One way to do this is through BioMart. From WormBase front page, click 
on the ParaSite banner-> Tools: BioMart Data Mining Tool. There you can 
paste a gene list and get protein sequences.

Raymond
