### ISSUE TITLE
  Genetic map still cannot be used. is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3894]
<p>&nbsp;&nbsp;Genetic map still cannot be used. is the genetic interval which in old version applicable? how can I get the DNA sequence(such as promoter and gene interval) easily using wormbase?</p>

Reported by: Xian***** (xmwa*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by dasmoth** [comment]
Confirmed.

Having worked for a while yesterday, Genetic Map, Tree Display, and the expression FPKM graphs are all broken again this morning.

**Comment by tharris** [comment]
Fixed (for now). User contacted and acknowledged.
