### ISSUE TITLE
  Hi! I was wondering if the FPKM Expre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3896]
<p>&nbsp;&nbsp;Hi! I was wondering if the FPKM Expression Data is still available. It used to be accessed by searching for a gene - Expression - (last entry) FPKM Expression Data. <br/>Thank you so much for the great work!<br/>Lucy</p>

Reported by: Lucy (Lucy******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Lucy,

Thank you for your email. This is a known issue with the website and is 
being looked at by the web developers. Hopefully this functionality will 
be restored shortly.

Paul


On 25/05/2015 17:53, no-reply@wormbase.org wrote:
> Question:
>
>   Hi! I was wondering if the FPKM Expression Data is still available. 
> It used to be accessed by searching for a gene - Expression - (last 
> entry) FPKM Expression Data.
> Thank you so much for the great work!
> Lucy
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3896. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3896>.
>
> Reported by: Lucy (Lucy.chao@umassmed.edu)
> 25 May 15 16:54
>
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/43.0.2357.65 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by tharris** [comment]
Fixed. User contacted
