### ISSUE TITLE
  I am trying to get a list of all the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3897]
<p>&nbsp;&nbsp;I am trying to get a list of all the genes with a sterile phenotype from Wormmine. I generate a list of the 1298 genes that Wormmine lists as sterile, but I notice that some genes which I know are sterile are not on this list.  For example fkh-6 is sterile, it is noted as having a sterile phenotype on wormbase, but I don't see it in the sterile list.  What am I doing wrong?</p>

Reported by: Mary (kroe************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by xdwang** [comment]
Hi Mary,

The list of 1298 genes are all from natural variants with sterile phenotypes. and I noticed fkh-6 sterile phenotype is from RNAi experiments. Wormbase unfortunately may not have RNAi phenotype built in wormmine at this moment yet. I will have our phenotype curator double check on this and get back to you asap.

Thanks,

Xiaodong Wang
Help desk officer


> On May 25, 2015, at 2:13 PM, no-reply@wormbase.org wrote:
> 
> How Do I ...? 
>   I am trying to get a list of all the genes with a sterile phenotype from Wormmine. I generate a list of the 1298 genes that Wormmine lists as sterile, but I notice that some genes which I know are sterile are not on this list. For example fkh-6 is sterile, it is noted as having a sterile phenotype on wormbase, but I don't see it in the sterile list. What am I doing wrong?
> 
> Submitted From: 
>   support /tools/support <http://www.wormbase.org//tools/support>
> This issue has been assigned ticket number: #3897. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3897>.
> 
> 
> Reported by: Mary (kroet006@umn.edu <mailto:kroet006@umn.edu>) 
> 25 May 15 18:14 
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:38.0) Gecko/20100101 Firefox/38.0 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125

**Comment by xdwang** [comment]
Hi Mary,

Just to add that another, arguably the best tool for getting at all 
genes that affect the sterile phenotype is the worm ontology browser. On 
the corresponding phenotype page 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000688>, in 
the Ontology Browser widget, it's noted that there are 3236 associated 
gene products, of which 2574 are direct. The longer list includes genes 
associated by inference (e.g. male sterile is sterile). Clicking on the 
link opens up a new tag on which genes are listed in sections. fkh-6 is 
included in the first (direct, RNAi) section of 1351 genes.

Let us know if we can clarify further.

Cheers,


Raymond


On 05/26/2015 07:12 AM, Xiaodong Wang wrote:
> Hi Mary,
>
> The list of 1298 genes are all from natural variants with sterile 
> phenotypes. and I noticed fkh-6 sterile phenotype is from RNAi 
> experiments. Wormbase unfortunately may not have RNAi phenotype built 
> in wormmine at this moment yet. I will have our phenotype curator 
> double check on this and get back to you asap.
>
> Thanks,
>
> Xiaodong Wang
> Help desk officer
>
>
>> On May 25, 2015, at 2:13 PM, no-reply@wormbase.org 
>> <mailto:no-reply@wormbase.org> wrote:
>>
>> How Do I ...?
>>
>>   I am trying to get a list of all the genes with a sterile phenotype 
>> from Wormmine. I generate a list of the 1298 genes that Wormmine 
>> lists as sterile, but I notice that some genes which I know are 
>> sterile are not on this list. For example fkh-6 is sterile, it is 
>> noted as having a sterile phenotype on wormbase, but I don't see it 
>> in the sterile list. What am I doing wrong?
>>
>> Submitted From:
>>   support/tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #3897. Follow progress on 
>> ourissue tracker <https://github.com/WormBase/website/issues/3897>.
>>
>>
>> Reported by: Mary (kroet006@umn.edu <mailto:kroet006@umn.edu>)
>> 25 May 15 18:14
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:38.0) Gecko/20100101 
>> Firefox/38.0
>>
>> This question was reported via the web interface atwormbase.org 
>> <http://wormbase.org/>. You can alsoemail us 
>> <mailto:help@wormbase.org>directly.
>>
>>
>> --
>> --
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email tohelp@wormbase.org 
>> <mailto:help@wormbase.org>
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>
>> To unsubscribe from this group and stop receiving emails from it, 
>> send an email tohelp+unsubscribe@wormbase.org 
>> <mailto:help+unsubscribe@wormbase.org>.
>
> Xiaodong Wang, Ph.D
> Wormbase Curator
> 626-395-8079
> Biology Division
> California Institute of Technology
> 1200 E. California Blvd
> Pasadena, CA 91125
>
>
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by xdwang** [comment]
Hi,

 Yes, that's correct. RNAi phenotypes are not yet available in WormMine.

Chris Grove


> Hi Mary,
>
> The list of 1298 genes are all from natural variants with sterile
> phenotypes. and I noticed fkh-6 sterile phenotype is from RNAi
> experiments. Wormbase unfortunately may not have RNAi phenotype built in
> wormmine at this moment yet. I will have our phenotype curator double
> check on this and get back to you asap.
>
> Thanks,
>
> Xiaodong Wang
> Help desk officer
>
>

**Comment by xdwang** [comment]
Thank you everyone for your prompt help!!  Your answers have been extremely useful!!

Mary
Mary B. Kroetz, Ph.D
Zarkower Laboratory
Department of Genetics, Cell Biology & Development
University of Minnesota
5-143 Moos Tower
515 Delaware St SE
Minneapolis MN 55455
612-626-4259 (lab)
