### ISSUE TITLE
  Looking at this strain and others on ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3901]
<p>&nbsp;&nbsp;Looking at this strain and others on lmn-1 page LW0697, there is no genotype or other info displayed.</p>

Reported by: http**************************************************************************** (ja21***********)  (obscured for privacy))
Submitted From: LW0697 (strain) <a href="http://www.wormbase.org//species/c_elegans/strain/LW0697#02--10">/species/c_elegans/strain/LW0697#02--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by chris-grove** [comment]
Hello,

 Thanks for the feedback. It looks like LW0697 is actually a (mostly)
empty duplicate strain object copied from LW697, which has more info
prominently displayed. We will look into retiring this strain name if it
is deprecated.

Thank you!

Chris Grove

**Comment by chris-grove** [comment]
@tuli  I just e-mailed you. Can we remove this strain if it is no good? Thanks!

**Comment by xdwang** [comment]
@chris-grove but in WBPaper00026936, the strain is indeed called LW0697. People will not find the strain info if we just simply remove it.

**Comment by chris-grove** [comment]
@xdwang  You're right. I think 'LW0697' should be added as an other name of 'LW697', but then the independent object 'LW0697' should be deprecated.

**Comment by xdwang** [comment]
@chris-grove I agree. Another thing, I wonder why all the references associated with ccIs4810, the trangene that LW697 contains, are not showing on strain page?

**Comment by chris-grove** [comment]
@xdwang  Are you looking at the LW697 page? I can see them there:

http://www.wormbase.org/species/c_elegans/strain/LW697#025431--10

**Comment by xdwang** [comment]
@chris-grove hum, for me, it says, 'No references data for LW697'?

**Comment by xdwang** [comment]
![screen shot 2015-05-27 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/1660722/7845784/24493f86-0487-11e5-9b19-9c7e9a3015df.png)

**Comment by chris-grove** [comment]
@xdwang I see what you mean. Let's take this conversation offline, so as not to clog up this issue.

**Comment by tuli** [comment]
Dear Julie,

As my colleagues have already alluded to, strain LW0697 should be LW697 (we
do not precede strain numbers with a 0).
We have a full record for LW697 sent to us from the CGC, whereas the LW0697
(as you have seen) is not fully curated. I have therefore made LW0697 an
other name of LW697 and removed LW0697 from WormBase. Users searching
WormBase for either name will reach the same record.

I have done the same for the LW709/LW0709 pair. The other LW0 strains
mentioned in PMID 16269543 do not have corresponding LW objects.

You'll see this update in release WS250.

Best wishes,

Mary Ann



On 27 May 2015 at 19:07, <no-reply@wormbase.org> wrote:

> Bug Report
>
>   Looking at this strain and others on lmn-1 page LW0697, there is no
> genotype or other info displayed.
>
> Submitted From:
>   LW0697 (strain) /species/c_elegans/strain/LW0697#02--10
> <http://www.wormbase.org//species/c_elegans/strain/LW0697#02--10>
>
> This issue has been assigned ticket number: #3901. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/3901>.
>
>  Reported by:
> https://www.google.com/accounts/o8/id?id=AItOawnlFL4K81DLIml4JNrbWmqP_MQNi-toQdk
> (ja219@cam.ac.uk)
> 27 May 15 18:08
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/42.0.2311.152 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
