### ISSUE TITLE
  Hi, I have a list of genes from C. el...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3902]
<p>&nbsp;&nbsp;Hi,<br/>I have a list of genes from C. elegans and would like to know which ones have orthologs in human/mammals and which ones might be nematode specific. I tried using ensembl biomart because they have orthologs among their filters. The problem is that when I get the results, usually does not match what worm base has annotated. </p><p>What were you doing? <br />&nbsp;&nbsp;I tried using ensembl biomart because they have orthologs among their filters. The problem is that when I get the results, usually does not match what worm base has annotated. Can I do it in wormart? Thanks!!</p>

Reported by: Dani*********** (hoch************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10

**Comment by brucebolt** [comment]
Dear Daniel

The orthology data in Ensembl may appear to be slightly different to WormBase as the species tree used to generate the comparative alignments is different in the two resources.

We also have orthology data in the WormBase ParaSite BioMart (http://parasite.wormbase.org/biomart/martview/ <http://parasite.wormbase.org/biomart/martview/>), which includes both C. elegans and human.  This orthology data is imported into WormBase and displayed under “Nematode Orthologs” —> “ParaSite-Compara” label on the main WormBase website.

Best wishes

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
