### ISSUE TITLE
  Where can I find the mapping from cel...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3904]
<p>&nbsp;&nbsp;Where can I find the mapping from cell name (ASER etc.) to anatomy term?</p><p>What were you doing? <br />&nbsp;&nbsp;Mining WormBase!</p>

Reported by: Chri******** (clus********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by xdwang** [comment]
Hi,

ASER is a cell name as well as an anatomy term.

Would you please explain more what you are trying to do?

Please let us know so that we can help you.

Thanks,

Xiaodong Wang
wormbase help desk officer

> On May 28, 2015, at 7:07 AM, no-reply@wormbase.org wrote:
> 
> How Do I ...? 
>   Where can I find the mapping from cell name (ASER etc.) to anatomy term?
> 
> What were you doing? 
>   Mining WormBase!
> 
> Submitted From: 
>   support /tools/support <http://www.wormbase.org//tools/support>
> This issue has been assigned ticket number: #3904. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3904>.
> 
> 
> Reported by: Chris Barnes (cluster.barnes@gmail.com <mailto:cluster.barnes@gmail.com>) 
> 28 May 15 11:09 
> 
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125

**Comment by raymond91125** [comment]
Hi Chris,

You can use WormMine to translate ASER to WBbt:0003903. On this page 
<http://www.wormbase.org/tools/wormmine/bag.do>, Select Type Anatomy 
Term, paste in a list containing names like ASER and click on "Create List".

Raymond


On 05/28/2015 04:07 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Where can I find the mapping from cell name (ASER etc.) to anatomy term?
>
> What were you doing?
>   Mining WormBase!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #3904. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3904>.
>
> Reported by: Chris Barnes (cluster.barnes@gmail.com)
> 28 May 15 11:09
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/43.0.2357.81 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
