### ISSUE TITLE
Genetic map and Tree Display are broken again

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3907]
Same "bad gateway" errors as before.

RNAseq FPKM images are still working, though.

**Comment by tharris** [comment]
I fixed the FPKM images a few days ago. The Genetic Map and Tree Display are susceptible to very large queries. Are you trying to view large regions or objects with many, many XREFs?

**Comment by dasmoth** [comment]
I don't use the Genetic Map myself, except for testing.

I don't think I've requested Tree Views for anything especially big/complex myself this morning.  However, once it's been knocked over (presumably by a big request) it seems to stay dead for everyone.

**Comment by tharris** [comment]
Yep, well aware :) The many joys of administrating acedb.

**Comment by dasmoth** [comment]
Not sure exactly what's happening on the server, but given that the acedb instance is (I assume) read-only, would a watchdog process that restarts it after, say, 30s of non-responsiveness help matters, or just cause further problems?

**Comment by tharris** [comment]
Have you ever started up acedb?

**Comment by dasmoth** [comment]
Yes.  I know it's not instant (!), if that's what you mean?

I guess the concern is that if the server is being hammered by acedb-killing requests, the watchdog will repeatedly restart acedb and degrade other services?

**Comment by tharris** [comment]
Yes, exactly. In general, it leads to a race condition. Falls overs, gets restarted (can be very slow). Incoming queries then immediately "lock" acedb again. It isn't really locked of course, just processing very, very long running queries in the absence of multithreading. I've tweaked fail2ban and iptables to drop some egregious bots which should help.
