### ISSUE TITLE
  How can I get a WormBase antibody? Th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3908]
<p>&nbsp;&nbsp;How can I get a WormBase antibody? The antibody in question is: [cgc2045]:glp-1 | Anti-GLP-1 polyclonal rat antibodies against recombinant protein. Is this commercially available or do I need to contact one of the corresponding authors?</p>

Reported by: Mame*************************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; MS-RTC LM 8; InfoPath.3; Bellevue Hospital Center)

**Comment by tharris** [comment]
WormBase doesn’t supply antibodies. Your best (and most cost-effective) bet would be to contact the corresponding authors.
