### ISSUE TITLE
  Hello, How can I get orthologs of lis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3909]
<p>&nbsp;&nbsp;Hello,<br/>How can I get orthologs of list of genes? I could not find this feature in wormine. <br/>Thanks<br/>Nishant</p>

Reported by: Nish********** (nish*********************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36

**Comment by chris-grove** [comment]
Hi Nishant,

 I believe this would be best done using the WormBase ParaSite BioMart. If you click on the "ParaSite" link on the WormBase homepage, then click on "BioMart" at the top of the ParaSite homepage, you should arrive at the BioMart page. From there you can provide a list of genes and, I believe, pull out orthologs from whichever species you prefer.

Let us know if you need any help or encounter any problems.

Cheers,

Chris

**Comment by chris-grove** [comment]
Thanks Chris, this is all what I wanted. perfect !

Regards
Nishant
