### ISSUE TITLE
Brittle front page layout

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3912]
Currently, the www.wormbase.org front page layout is  less than optimal when:

- Viewing in Chrome or Safari (FireFox seems to be okay, haven't tried IE)
- Have a window width of less than 1235px

The content won't fit beside the toolbar (see attached screenshot).

This was fine a couple of days ago.  I'm pretty sure the proximal cause is the long link in the "Liquid NGM" discussion post, currently at the top of the discussion widget.  Deleting this discussion post snipped in Chrome's DOM inspector seems to fix the layout.

![image](https://cloud.githubusercontent.com/assets/209047/7908669/c41ad1ea-083e-11e5-9003-d7dadf5f5202.png)

**Comment by sibyl229** [comment]
Hi @dasmoth Thanks a lot for the troubleshooting. The front page seems good now on staging site. I tested it with Chrome, Safari, and Firefox. http://staging.wormbase.org/#01-23-6

**Comment by xdwang** [comment]
@sibyl229 can we close this issue now?

**Comment by sibyl229** [comment]
@xdwang sure.

**Comment by dasmoth** [comment]
Thanks @sibyl229.
