### ISSUE TITLE
Updating hyperlinks on Reagents Resource page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3914]
On our Resources/Reagents page:

http://www.wormbase.org/resources/reagents#2--10

We need to update the following hyperlink URLs:

1)
"RNAi libraries (Open BioSystems)"
http://www.openbiosystems.com/GeneExpression/Non-Mammalian/Worm/CelegansORF-RNAi/
to
http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-rnai/

2)
"Orfeome v1.1 (Open BioSystems)"
http://www.openbiosystems.com/GeneExpression/Non-Mammalian/Worm/C_%20elegans%20ORFs/
to
http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-orf-collection/

3)
"Promoterome (Open BioSystems)"
http://www.openbiosystems.com/GeneExpression/Non-Mammalian/Worm/CelegansPromoters/
to
http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-promoter-collection/

4)
"Transcription Factor Clones (Open BioSystems)"
http://www.openbiosystems.com/GeneExpression/Non-Mammalian/Worm/TranscriptionFactors/
to
http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-transcription-factors/

and we could maybe even link to the general C. elegans landing page for GE/Dharmacon:

http://dharmacon.gelifesciences.com/gene-expression-cdnas-orfs/non-mammalian-cdnas-and-orfs/c-elegans/

**Comment by xdwang** [comment]
@tharris and @sibyl229 are looking into this.

**Comment by sibyl229** [comment]
Hi @chris-grove I updated the links in reagent libraries widget on production. http://www.wormbase.org/resources/reagents#2--10. Could you double check they are correct? Thanks!

**Comment by chris-grove** [comment]
Hey @sibyl229  thanks! Sorry, I just realized I could have done this myself. They look good, thanks!

**Comment by sibyl229** [comment]
No problem Chris :)
