### ISSUE TITLE
RefSeq URL needs updating

### ISSUE THREAD

**Issue by khowe** [WormBase/website#3915]
See email from NCBI below. The base URL for RefSeq external references needs to be fixed.

They also want us to link to RefSeq protein entries. In the database, this is easy. Where we currently have this:

Database "RefSeq" "mRNA" "NM_059121"

...we would simply add this:

Database "RefSeq" "protein" "NP_012345"

i.e. same database, different fields. However, each has a different base URL, which our system (https://github.com/WormBase/website/blob/master/root/templates/config/external_urls) does not currently support. Here is the RefSeq entry:

RefSeq = {
	description = 'RefSeq is a comprehensive, integrated, non-redundant set of sequences, including genomic DNA, transcript (RNA), and protein products.'
	maintainer  = 'NCBI',
	base        = 'http://www.ncbi.nlm.nih.gov/RefSeq/',
	email       = '',
	search      = 'http://www.ncbi.nlm.nih.gov/%s'
	}

Ideally, we would be able to specify something like the following:

RefSeq = {
	description = 'RefSeq is a comprehensive, integrated, non-redundant set of sequences, including genomic DNA, transcript (RNA), and protein products.'
	maintainer  = 'NCBI',
	base        = 'http://www.ncbi.nlm.nih.gov/RefSeq/',
	email       = '',
	search     =  {
             mRNA = 'http://www.ncbi.nlm.nih.gov/nuccore/%s',
             protein = 'http://www.ncbi.nlm.nih.gov/protein/%s
	}

========================
From RefSeq:

The links to RefSeq on the WormBase gene pages contain an incomplete URL. The base URL should be http://www.ncbi.nlm.nih.gov/nuccore/ followed by the RefSeq transcript identifier, e.g., http://www.ncbi.nlm.nih.gov/nuccore/NM_058261
 
Example in WormBase: Y74C9A.4 (NM_058261) 
WormBase link for NM_058261: http://www.ncbi.nlm.nih.gov/NM_058261

Similarly, you could add a link to the RefSeq proteins using the base URL: http://www.ncbi.nlm.nih.gov/protein/

**Comment by khowe** [comment]
Hi, this one seems to have slipped through the cracks for WS249. The RefSeq links are still of the old form on staging.wormbase.org

**Comment by khowe** [comment]
Sorry, I just re-read the original ticket and realised that it was not clearly defined. There are two tasks here:

1. (Immediate) Update the links for RefSeq to point directly to entries at http://www.ncbi.nlm.nih.gov/nuccore/%s

2. (Longer term) Provide a mechanism for having different URLs for different entity-types within the same databases/resource.

**Comment by sibyl229** [comment]
Hi @khowe thanks for the reminder, I had this fix on another feature branch that I didn't merge. 
http://staging.wormbase.org/species/c_elegans/gene/WBGene00022278#02--3

The entity based url is in place. Here is an example:
```  
RefSeq = {
 	description = 'RefSeq is a comprehensive, integrated, non-redundant set of sequences, including genomic DNA, transcript (RNA), and protein products.'
 	maintainer  = 'NCBI',
 	base        = 'http://www.ncbi.nlm.nih.gov/RefSeq/',
 	email       = '',
 	search      = 'http://www.ncbi.nlm.nih.gov/%s'
	mRNA      = 'http://www.ncbi.nlm.nih.gov/nuccore/%s'
	protein      = 'http://www.ncbi.nlm.nih.gov/protein/%s'
 	}
```

**Comment by khowe** [comment]
Looks good @sibyl229 , thanks!
