### ISSUE TITLE
  I would like to find strains with lar...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3916]
<p>&nbsp;&nbsp;I would like to find strains with large deletions (25 kb or more) on the X chromosome of C. elegans. Is there anyway to search for such deletion containing strains?  </p>

Reported by: Edwa************* (eral*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3

**Comment by xdwang** [comment]
Hi Edward,

Please copy and paste the following query:

<query name="" model="genomic" view="Allele.method Allele.symbol Allele.gene.symbol Allele.gene.chromosomeLocation.end Allele.gene.chromosomeLocation.start Allele.gene.chromosome.primaryIdentifier" longDescription="" sortOrder="Allele.method asc" constraintLogic="A and B">
  <constraint path="Allele.method" code="A" op="=" value="Deletion_allele"/>
  <constraint path="Allele.gene.chromosome.primaryIdentifier" code="B" op="=" value="CHROMOSOME_X"/>
</query>
onto this page using wormmine:
http://www.wormbase.org/tools/wormmine/importQueries.do?query_builder=yes <http://www.wormbase.org/tools/wormmine/importQueries.do?query_builder=yes>
You should get a list of 182 genes with deletion allele on chromosome X. I will suggest you download the list and process the data further using spreadsheet to get allele with deletion >25kb. I am attaching a list I did for you. I found only two allele with 37kb deletion. You can play around in wormmine with the query I send you to set up other criteria.

Let us know if you need further assistance.

Best,

Xiaodong Wang
wormbase helpdesk officer



> On Jun 1, 2015, at 6:09 PM, no-reply@wormbase.org wrote:
> 
> How Do I ...? 
>   I would like to find strains with large deletions (25 kb or more) on the X chromosome of C. elegans. Is there anyway to search for such deletion containing strains? 
> 
> Submitted From: 
>   support /tools/support <http://www.wormbase.org//tools/support>
> This issue has been assigned ticket number: #3916. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3916>.
> 
> 
> Reported by: Edward J. Ralston (eralston@berkeley.edu <mailto:eralston@berkeley.edu>) 
> 01 Jun 15 22:11 
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125

**Comment by chris-grove** [comment]
Hi Ed,

 I've attached a spreadsheet with all known deficiencies on the X-chromosome and their genetic limits. I don't know the exact physical sizes without doing more calculations, but eDf44 is a 100kb deletion on X:

http://www.wormbase.org/species/all/rearrangement/eDf44#0123--10

Hope that helps,

Chris Grove
