### ISSUE TITLE
  Purchase/get a GAPDH mutant of C. ele...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3917]
<p>&nbsp;&nbsp;Purchase/get a GAPDH mutant of C. elegans please?</p><p>What were you doing? <br />&nbsp;&nbsp;Searching worm base</p>

Reported by: Leya (leya********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17

**Comment by xdwang** [comment]
Hi Leya,
WormBase does not provide strains, but you can find several strain
sources on our Reagents page:

http://www.wormbase.org/resources/reagents#3--10 <http://www.wormbase.org/resources/reagents#3--10>

The most common place to order strains from is the Caenorhabditis Genetics
Center (CGC):

http://www.cbs.umn.edu/research/resources/cgc <http://www.cbs.umn.edu/research/resources/cgc>

Their website has step by step instructions on how to properly order a
strain.

Good luck!

Xiaodong Wang
wormbase help desk officer


Xiaodong Wang, Ph.D
Wormbase Curator
xdwang@caltech.edu
http://www.wormbase.org
California Institute of Technology
Division of Biology 156-29
Pasadena, CA 91125
USA

**Comment by chris-grove** [comment]
Hi Leya,

 There are four GAPDH genes in C. elegans, gpd-1 through gpd-4:

http://www.wormbase.org/resources/gene_class/gpd#01--10

You may review the strains carrying mutations in these genes by going to
their respective gene page, e.g. gpd-1:

http://www.wormbase.org/species/c_elegans/gene/WBGene00001683#04--10

and reviewing strains listed in the "Genetics" widget.

Let us know if you have further questions.

Best,

Chris Grove
