### ISSUE TITLE
Tools > Queries link not loading

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3918]
I'm getting a 502 Bad Gateway error message

**Comment by chris-grove** [comment]
Same for ePCR

**Comment by chris-grove** [comment]
Same for ACeDB Image

**Comment by tharris** [comment]
They are all contained on the same instance. It's fixed now. There have been several bots crawling the open-ended services that these pages provide.

**Comment by chris-grove** [comment]
Still getting the 502 Bad Gateway on Queries

**Comment by chris-grove** [comment]
Fixed, closing. Thanks

**Comment by chris-grove** [comment]
Getting the 502 Bad Gateway on Queries again

**Comment by tharris** [comment]
more bot indexing; i've isolated these queries from MOST other services. Should be working again and more stable.

**Comment by chris-grove** [comment]
OK great, thanks!
