### ISSUE TITLE
  I have a list of Drosophila genes (CG...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3919]
<p>&nbsp;&nbsp;I have a list of Drosophila genes (CG4145 etc) for which I would like to get the C. elegans homologs. Is there a tool that I can use to get the whole list in one go?</p>

Reported by: Gert******* (g.ja*****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by brucebolt** [comment]
Dear Gert

This can be done using the WormBase ParaSite BioMart (from the main WormBase page, click “ParaSite”, then choose “BioMart” from the header links).

On the filters page, choose Drosophila as the species and enter your list of genes.

On the attributes page, choose Homologues —> Orthologues —>  Caenorhabditis elegans [WS245] gene stable ID.

This will give you a list of C. elegans orthologues.

Best regards

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
