### ISSUE TITLE
Synteny viewer timing out

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3923]
Getting a 504 Gateway time-out when trying to load the synteny browser from the Tools menu

Sorry @tharris , I'm not trying to be a pain in the #@$  ;)

**Comment by tharris** [comment]
@scottcain  Did you change/update the gbrowse libraries (particularly any that gbrowse_syn may rely) on the development instance? It's no longer correctly parsing the authorization parameters in the configuration files.

**Comment by scottcain** [comment]
I haven't touched GBrowse other than to modify config files, so no new bioperl or gbrowse libraries.  When I try to go to synteny under the tools menu, I get a 404 not a 504.  It's trying to open http://staging.wormbase.org/tools/synteny/mercator

**Comment by tharris** [comment]
I was looking at the production instance which can no longer connect to the remote synteny databases. You might check the apache conf on staging to see where it is pointing. And remember: staging.wormbase.org passes through a proxy...

**Comment by scottcain** [comment]
I looked on the production instance.  The problematic line of code is this:

    $dbh       = DBI->connect($dsn,@_) or die "$dsn: Can't open; ",DBI->errstr;

which is a pretty generic DBI connection command, from /usr/local/wormbase/extlib/lib/perl5/x86_64-linux-gnu-thread-multi/Legacy/DB/SyntenyIO.pm.  The $dsn that is passed in the method and then is emitted to the page with the error (displaying the password--nice!) is well formatted.

I think there is something much more fundamentally wrong here.  As a test, I wrote this very simple perl script on the production instance:
```PERL
#!/usr/bin/perl
use strict;
use warnings;
use DBI;
my $dsn = 'dbi:mysql:database=gbrowse_syn_join_mercater_WS204;host=mysql.wormbase.org;user=wormbase;pass=********';
my $dbh       = DBI->connect($dsn) or die "$dsn: Can't open; ",DBI->errstr;
```
and when I run it, I get exactly the same error:
```
DBI connect('database=gbrowse_syn_join_mercater_WS204;host=mysql.wormbase.org;user=wormbase;pass=*********','',...) failed: Access denied for user 'wormbase'@'ip-10-65-147-6.ec2.internal' (using password: NO) at testdbi.pl line 8.
```
Even though I can use that connection information on the command line to connect to that mysql database.  It implies to me that something has happened with DBI or DBD::mysql, or possibly mysql itself, like a change in permissions for the wormbase user (? I'm not much of a mysql person, but in postgresql, being able to connect on the command line and being able to connect via DBI are separate permissions).

**Comment by tharris** [comment]
what if you use named parameter style for DSN string? or "password" instead of "pass"?

**Comment by scottcain** [comment]
I 'fixed' gbrowse_syn by editing /usr/local/wormbase/extlib/lib/perl5/x86_64-linux-gnu-thread-multi/Legacy/DB/SyntenyIO.pm to make the offending line look this this:
```PERL
$dbh = DBI->connect($dsn,'wormbase','****') or die "$dsn: Can't open; ",DBI->errstr;
```
which is an alternate representation, where the username and password go in as separate arguments instead of going in as part of the dsn string.  I have no idea why one way works where the other doesn't.  I'll look at fixing this more generically now (perhaps a change to the config file will do the trick).

**Comment by tharris** [comment]
I've noticed this before in where named params work but the concatenated string does not. Not sure if DBI, DBD::mysql, or gbrowse config parsing (seems doubtful).

**Comment by scottcain** [comment]
Definitely odd.  When I changed "pass" to "password" in the dsn string as you suggested, it works.  I'll fix on staging and close.

**Comment by tharris** [comment]
Excellent. Thanks.
