### ISSUE TITLE
  In WormMine, I entered a list of gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3927]
<p>&nbsp;&nbsp;In WormMine, I entered a list of genes and while a quarter of them returned with a brief description, many of them displayed "No value" in the brief description column. However, when I click on "No Value" it takes me to the gene's page where there is actually a description available in the overview section. This feature is really useful but I'm not sure why it isn't working for all genes. </p>

Reported by: Euni****** (eula***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by xdwang** [comment]
Hi Eunice,

Wormmine is using old data that we haven’t got chance to update yet.  I am assuming that’s the reason you don’t see some updated gene description. 
Can you submit the gene list with genes that you can’t find values in wormmine please? We will see if we can help you at our end.

Sorry for the inconvenience.

Xiaodong Wang
wormbase help desk officer



Xiaodong Wang, Ph.D
Wormbase Curator
xdwang@caltech.edu
http://www.wormbase.org
California Institute of Technology
Division of Biology 156-29
Pasadena, CA 91125
USA

**Comment by xdwang** [comment]
At the same time, you can download all gene descriptions from this site:

ftp://ftp.wormbase.org/pub/wormbase//releases/WS248/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS248.functional_descriptions.txt.gz

and process further to get the genes of your interests.

Best,

Xiaodong

**Comment by xdwang** [comment]
Thanks so much, Xiaodong. That was very helpful. 
Best,
Eunice

Chalasani Lab
Salk Institute
