### ISSUE TITLE
Gene Ontology widget won't switch between summary and full views

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3933]
New-style GO displays are broken on the live site.  "Summary view" and "Full view" radio buttons appear, but don't do anything.

Possibly-related new error in the JS console:

         Uncaught TypeError: WB.partitioned_table is not a function

..which makes me suspect that some required JS isn't getting loaded (and yes, I have tried refreshing the page).

**Comment by sibyl229** [comment]
I think the wormbase.min.js is an older version. I didn't realize that I
have to update it manually.

**Comment by vanaukenk** [comment]
Hi @sibyl229,

Is this issue something that can be fixed for WS248 or will we need to wait for the next release?

Thanks,
--Kimberly

**Comment by tharris** [comment]
We are working on it now.

**Comment by vanaukenk** [comment]
Okay, great.  Thanks.

**Comment by tharris** [comment]
Resolved. :) Please test.

**Comment by vanaukenk** [comment]
Looks good!  Thanks for the fix, guys.  Now I can make screenshots for the IWM :-)
