### ISSUE TITLE
Incorrect labelling/grouping of ortholog data in homology widget

### ISSUE THREAD

**Issue by khowe** [WormBase/website#3934]
In homology widget, the "nematode orthologs" table contains all orthologs (including human and other model organisms), not just nematode orthologs.

This was reported in April (#3779), and marked as a WS248 milestone to fix. However, it is still broken. To re-iterate, the the correct fix is to split the data out into a separate table (e.g.. orthologs in human and other model organisms). However, probably a more achievable fix at this stage would be to relabel the table as "Orthologs".

**Comment by tharris** [comment]
@khowe This is resolved for WS248. We will reference the original ticket for further development as this one seems unnecessarily snarky and should probably be buried.
