### ISSUE TITLE
nc_primary_transcript not showing up in genome browser

### ISSUE THREAD

**Issue by khowe** [WormBase/website#3937]
http://www.wormbase.org/species/c_elegans/gene/WBGene00001949#0f9--10

This gene has two transcripts, one coding ("mRNA" in GFF3) and one non-coding "nc_primary_transcript" in GFF3). The latter does not appear in the location widget, nor on the "curated gene" track of the main genome browser.

**Comment by tharris** [comment]
Hmm. I don't think we have ever displayed ncRNA transcripts in the "Curated Genes" track (in C. elegans). This uses the gene glyph of Bio::DB::SeqFeature::Store which aggregates gene>mRNA. This might require subclassing the glyph.

**Comment by khowe** [comment]
The track selection page has:

Curated genes
Curated genes (protein coding)
Curated genes (non-coding)
Curated genes (pseudogenes)

Presumably the first is a composite of the rest. But I guess it doesn't account for "protein coding" genes having non-coding transcripts.

**Comment by scottcain** [comment]
@khowe @tharris This is a "bug" in BioGraphics.  The gene glyph has a list of transcript types that it knows about: mRNA tRNA snRNA snoRNA miRNA ncRNA pseudogene transcript.  I can add nc_primary_transcript to that list.  I'm guessing there are probably others that ought to be added to that list as well.  Looking at the GBrowse config, I think these should probably be added too: rRNA, scRNA, piRNA, lincRNA, antisense_RNA and pseudogenic_transcript.

Would anybody like to add to or subtract from that list?

**Comment by khowe** [comment]
Here's a complete list"

antisense_RNA
lincRNA
miRNA
miRNA_primary_transcript
mRNA
nc_primary_transcript
ncRNA
piRNA
pre_miRNA
pseudogenic_transcript
rRNA
scRNA
snoRNA
snRNA
tRNA

**Comment by scottcain** [comment]
@khowe I believe I've fixed this on staging:

http://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?start=7190041;stop=7194292;ref=I;width=800;version=100;flip=0;grid=on;id=0e64448f783c71df9bcc5f6c7c26f4c6;l=GENES_PROTEIN_CODING%1EGENES%1ELOCI%3Aoverview;h_feat=y16b4a.2%40yellow

Do you know of any other instances like this that I can look at just to make sure they look OK?

**Comment by khowe** [comment]
I've looked at a couple myself:

one antisense_RNA -  WBGene00236797
- one miRNA, with corresponding miRNA_primary_transcript and pre_miRNA - WBGene00195833

All looks to be in order.

**Comment by scottcain** [comment]
Fixed on production now too; closing.
