### ISSUE TITLE
  How do i design Gene architecture of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3938]
<p>&nbsp;&nbsp;How do i design Gene architecture of a particular gene?</p>

Reported by: rini******* (rini****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by chris-grove** [comment]
Hello Rini, could you be more specific?

Best,

Chris Grove

**Comment by epaule** [comment]
user didn't reply, closing.
