### ISSUE TITLE
  Hi, In the overview on the Gene page ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3945]
<p>&nbsp;&nbsp;Hi,<br/>In the overview on the Gene page for ceh-51 there is one instance in which it is written as ceg-51.</p>

Reported by: Jona*********** (jrum**********************)  (obscured for privacy))
Submitted From: ceh-51 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00013583#0cd-9f-3">/species/c_elegans/gene/WBGene00013583#0cd-9f-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0

**Comment by vanaukenk** [comment]
Dear Jonathan,

Thanks for catching this and reporting it.

I've fixed the typo and the corrected version will be included in WormBase
release WS250.

Best,
--Kimberly Van Auken


>
> Content
> Correction
>   Hi,
> In the overview on the Gene page for ceh-51 there is one instance in which
> it is written as ceg-51.
> Submitted From:
>   ceh-51 (gene) /species/c_elegans/gene/WBGene00013583#0cd-9f-3
>  This issue has been assigned ticket number: #3945. Follow progress on our
> issue tracker.
>
>  Reported by: Jonathan Rumley (jrumley@mail.med.upenn.edu)
>  10 Jun 15 18:21
>
>  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101
> Firefox/32.0     This question was reported via the web interface at
> wormbase.org. You can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
