### ISSUE TITLE
  Hello, My lab previously deposited to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3953]
From Itai Yanai <yanai@technion.ac.il>
reply-to:	yanai@technion.ac.il
to:	help@wormbase.org
cc:	Martin Feder <martin_feder@yahoo.com>,
Tamar hashimshony <thashimi@tx.technion.ac.il>
date:	11 June 2015 at 02:01
subject:	[wormbase-help] Spatiotemporal expression profiles for C. elegans

<p>&nbsp;&nbsp;Hello,<br/>My lab previously deposited to Wormbase the temporal gene expression of thousands of genes (for hlh-1 it is: http://www.wormbase.org/species/all/expr_pattern/Expr1019379#021--10 ).<br/>Recently, we determined also the location of expression in the embryo – see for example figure 1D in the attached manuscript summarizing the results of this dataset. Since the previous dataset continues to be used by the community we propose to also provide these new improved expression profiles to Wormbase.<br/>I would be interested in knowing if Wormbase would be interested in these.<br/>With best wishes,<br/>Itai<br/>Itai Yanai<br/>Associate Professor<br/>Technion – Israel Institute of Technology<br/>yanailab.technion.ac.il<br/>Currently on leave at the Radcliffe Institute for Advanced Study at Harvard University</p>

Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by tuli** [comment]
Dear Itai,

Thanks for writing to wormbase. Daniela Raciti, our expression curator, is out of town until Friday. She will get back to you as soon as she comes back online.

Best,

Xiaodong

**Comment by tuli** [comment]
@draciti see original message to help@wormbase for attached file.

**Comment by tuli** [comment]
@draciti, can you have a look at this please.

**Comment by draciti** [comment]
thanks Mary Ann. I am in touch with Itai. Closing
