### ISSUE TITLE
Change width of GO Term ID column in Gene Ontology table

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#3954]
Hi @sibyl229,

Would it be possible to narrow the width of the GO Term ID column in the Summary view of the Gene Ontology table?
The column currently takes up a lot of space, most of which is unused.
On staging, it looks like the column is narrower for some entries, but not all.  Where it is narrower, though, the display looks much nicer.
Compare:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00006959
with:
http://www.wormbase.org/species/c_elegans/gene/WBGene00006959

Thx,
--Kimberly

**Comment by sibyl229** [comment]
Hi @vanaukenk the GO table should look okay now. And Todd fixed the discrepancy in style between staging and production over the weekend.

**Comment by vanaukenk** [comment]
Awesome; looks good now.  
Thanks, @sibyl229  and @tharris!
