### ISSUE TITLE
  There is a spelling mistake for hypod...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3955]
<p>&nbsp;&nbsp;There is a spelling mistake for hypodermis:<br/>ceh-43 (C. Elegans Homeobox )<br/>hypdermis hypdodermis</p>

Reported by: isab****************************  (obscured for privacy)
Submitted From: ceh-43 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00000463#0b-9f6d17a-10">/species/c_elegans/gene/WBGene00000463#0b-9f6d17a-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by rankishore** [comment]
Fixed for WS250.
