### ISSUE TITLE
Links to Allele-Phenotype Form from WormBase pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3956]
I'd like to make hyperlinks to our new Allele-Phenotype form from within certain WormBase pages, namely gene pages (from the phenotypes widget), variation pages (from the phenotype widget), and phenotype pages (from the variations widget).

I'm thinking the links would be just above or below the tables with phenotype data (in phenotype widgets on gene and variation pages) and variation data (on phenotype pages) with text along the lines of: "Know of an allele phenotype that is missing from this table? Please let us know here" for phenotype widgets and "Know of an allele that is missing from this table? Please let us know here" for the variations widget, where "here" contains the hyperlink to the Allele-Phenotype form:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele_phenotype.cgi

**Comment by tharris** [comment]
This will not be possible before the IWM. Have assigned to WS249 release.

**Comment by chris-grove** [comment]
@tharris  Just checking in, is this something we can act on soon?

**Comment by chris-grove** [comment]
@tharris or @sibyl229 
We would very much like to get a link to the phenotype form from phenotype widgets on gene pages, allele pages and transgene pages. The current link is:

http://www.wormbase.org/submissions/phenotype.cgi

The link text could read: "Notice a missing phenotype? Please let us know via our Phenotype Form"

**Comment by sibyl229** [comment]
Hi @chris-grove sorry about that. I have the allele-phenotype submission link added:
- gene page: http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#0c-g-3
- variation page: http://staging.wormbase.org/species/c_elegans/variation/WBVar00249536#0-6-3
- transgene page: http://staging.wormbase.org/species/all/transgene/WBTransgene00005010#03--9

**Comment by chris-grove** [comment]
@sibyl229  That's perfect!! Thanks!!
