### ISSUE TITLE
  To whom it may concern, Hello! My nam...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3958]
<p>&nbsp;&nbsp;To whom it may concern,<br/>Hello! My name is Pavan Anand, I’m an undergraduate at Vanderbilt and am working on analyzing gene expression during different larval stages of C. elegans. I have uploaded a list of genes I want to mine the database for to the WormMine tool on WormBase and needed some help displaying the relevant information in the query results table.<br/>At the current moment, what I need to do in order to gather the desired data is locate a gene within my list, click on the “Gene Name” link for the specific gene I want information for, and scroll down the individual gene information page to the table labeled “FPKM expression data: Control Statistics”. In essence, I am looking for a way to list these mean/median FPKM values within the “List Analysis” page itself. I have tried using QueryBuilder to generate some macro to help me with this but I can’t locate the relevant option that will display this information as a column next to the gene name. All I need within the query results table is the gene name and the FPKM mean/median values (preferably both, though only either mean or median is fine) in a separate column next to the gene name column. Is there any way to do this, and if so, what options should I select within the QueryBuilder panel? If that’s not possible through QueryBuilder, how else can I extract these data so that I don’t have to dig through each individual gene page to get to the FPKM values?<br/>Thank you!<br/>—<br/>Pavan Ashwini Anand<br/>Vanderbilt University 2017<br/>Ecology, Evolution & Organismal Biology<br/>Cell: 606-620-8598</p>

Reported by: Pava*************** (pava************************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by chris-grove** [comment]
@WenChenWormBase  and I answered the original help desk e-mail
