### ISSUE TITLE
  I am not sure that the correct refere...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3959]
<p>&nbsp;&nbsp;I am not sure that the correct reference is associated with spr-5 Expr2274 expression pattern - what is given is "[Expression and significance of bcl-2 and bcl-xL in rat neuron after acute brain trauma]<br/>Yang X, Yang S, Zhang J, Xue L<br/>[Zhonghua Wai Ke Za Zhi, 2002]"<br/>Is this what you meant to associate with this?  <br/>Thanks, Laura</p>

Reported by: Laur************ (biol**************)  (obscured for privacy))
Submitted From: Expr2274 (expr_pattern) <a href="http://www.wormbase.org//species/all/expr_pattern/Expr2274#021--10">/species/all/expr_pattern/Expr2274#021--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3

**Comment by draciti** [comment]
Hi Laura,

thanks for pointing this out.

the correct reference for Expr2274 is WBPaper00005564
The correction will be displayed in the next WormBase release -WS250

here's a link to the WBpaper page
http://www.wormbase.org/resources/paper/WBPaper00005564?from=http://www.wormbase.org/db/misc/paper?name=WBPaper00005564;class=Paper#03--10

Daniela
