### ISSUE TITLE
Lists of sequences render poorly in WS248

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3960]
E.g. the "Isoform" column in

![image](https://cloud.githubusercontent.com/assets/209047/8131146/36987356-1110-11e5-9c17-f213925fc198.png)

I unfortunately don't have a pre-248 screenshot for comparison purposes, but it certainly wasn't talking three lines per isoform before.

Almost certain this is an unintended consequence of dfdf0a6b8200ff53eeec01d107e9a25839d53c0c.  This otherwise looks like a good change, but interacts badly with the current code for sequence links (which relies on CSS before and after rules, and really doesn't seem happy in a list-item context).

**Comment by dasmoth** [comment]
Looking much better now, thanks @sibyl229.

**Comment by sibyl229** [comment]
@dasmoth Thanks for the bug report.
