### ISSUE TITLE
  blos-2 (Y37B6BL.30) and Y37B6BL.289 a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3961]
<p>&nbsp;&nbsp;blos-2 (Y37B6BL.30) and Y37B6BL.289 are one complex locus with the .289 exons being alternative exon3 and exon4s of blos-2.  Thus, Y37B6BL.289 should be merged into blos-2.<br/>I am sure if you look at the RNA seq data you will agree. </p>

Reported by: Mich********* (none************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2

**Comment by gw3** [comment]
Well spotted :-)
Y37B6BL.289 is not actually part of a complex locus with blos-2 (Y37B6BL.30).
Y37B6BL.289 is a copy of the end of blos-2 (Y37B6BL.30), probably duplicated as part of the relocation of the upstream transposon.

The RNASeq alignments make it look like there are a couple of introns linking these two genes, but this is a commonly seen artefact of the RNASeq data. The reads half align both to the first and half to the second copy of a duplicated region, making it look like there is an intron.

Gary Williams
