### ISSUE TITLE
  Hello, is there a way to retrieve the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3962]
<p>&nbsp;&nbsp;Hello,<br/>is there a way to retrieve the sequences of the flanking regions of all the annotated genes in C.briggsae?<br/>thanks</p>

Reported by: Isan* (Isan********************************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by brucebolt** [comment]
Dear Isana

This is possible using the WormBase ParaSite BioMart (from the main website website, click “ParaSite" in the header, then click “BioMart”).

On the filters page, choose C. briggsae as the species.  On the attributes page, select Sequence —> Flank (Gene) —> Enter the distance up/down-stream you would like to retrieve.

For example, this query will give 50bp upstream of each gene: http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart_2&ATTRIBUTES=wbps_eg_gene.default.sequences.production_name_1010|wbps_eg_gene.default.sequences.ensembl_gene_id|wbps_eg_gene.default.sequences.gene_flank|wbps_eg_gene.default.sequences.upstream_flank."50"&FILTERS=wbps_eg_gene.default.naive_filters.species_id_1010."cbriggsae"&VISIBLEPANEL=resultspanel

Given that this query will be slow to process, I would strongly recommend you use the “Compressed web file (notify by email)” option (which is located under “Export all results to” on the results page).

Best regards

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
