### ISSUE TITLE
  If possible, it seems like it might b...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3965]
<p>&nbsp;&nbsp;If possible, it seems like it might be better to have the 'reference allele' tag in the mail overview space. It would be be good to have a line that says 'Reference allele for deg-1' ( as an example for the u38 allele). The current placement of the 'reference allele' status in the side window is a bit confusing.</p>

Reported by: Kare****** (kare**************)  (obscured for privacy))
Submitted From: u38 (variation) <a href="http://staging.wormbase.org//species/c_elegans/variation/WBVar00266506#0-6-3">/species/c_elegans/variation/WBVar00266506#0-6-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by tharris** [comment]
Good point. It looks broken. The original intent was to display the actual reference allele for *other* alleles that are not the reference. We will fix/clarify.

**Comment by chris-grove** [comment]
@kyook  @tharris 
 Looks like we can close this?

**Comment by kyook** [comment]
Yes, thanks everyone!
