### ISSUE TITLE
GBrowse lost style sheet for footer

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#3966]
I'm working on the gene glyph issue (#3937) but I don't want to forget about this: on ******.wormbase.org (the production version of GBrowse), the footer div seems to have misplaced it's css (I'm guessing it's a relative versus absolute url issue).  If anybody ( @tharris or @sibyl229 ) happens to know what the issue is, have at it :-)

**Comment by tharris** [comment]
@scottcain I don't think this is related to relative/absolute URL addressing per se. If you are visiting that instance through that hostname, you are going direct to the instance. In production, stylesheets, js, images (eg static content) are served via proxy for speed.  I also blocked out the name of this host -- you shouldn't be able to contact it directly via http. I will be locking that down shortly.

**Comment by scottcain** [comment]
I was accessing it via www.wormbase.org; are you saying it looks OK for you?  If so, it could be a cookie or caching issue for me.  Actually, I just tried with a different browser and it looks OK, so it must be something with my main browser.  Sorry for the confusion.
