### ISSUE TITLE
a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3973]
*Help Desk query collected when no chat operators were online. Follow up required.*

a
    
**Reported by:** pers** (emai****************)
**Submitted from:** <a target="_blank" href="http://todd.wormbase.org/http://staging.wormbase.org/#01-23-6">http://staging.wormbase.org/#01-23-6</a>
**Browser:** Firefox 38.0

**Comment by tharris** [comment]
Hi Hinxton! 

Thanks for testing! Yes, it is possible to spam the chat system, just like it is possible to spam any online form. There is no email verification required. The barrier for participation is intentionally low, but not so low that we cannot respond to interested users if necessary.

This makes me think a separate triage step would probably be worthwhile...

**Comment by khowe** [comment]
I tried this morning, but it sounds like this was not me. I gave my full name and email. I also it did it on todd.wormbase.org rather than staging. 

Should we now be testing on staging?

**Comment by tharris** [comment]
Yes, I was logged in to the chat client. Chats time out eventually if not addressed. I need to play with those settings a little.

@sibyl229 and I are testing on staging now.

**Comment by tharris** [comment]
@khowe, I see what happened this morning. You posted a question and closed your browser window a minute later before the chat timed out. Conversations like this (operator online, but not available) persist in the chat interface until addressed; operators can forward to GitHub if warranted.
