### ISSUE TITLE
Search on community submissions forms

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#3974]
When on the community submission forms (e.g. http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi), the search box at the top right in the header submits to the current URL rather than the correct location, so you end up back at the submission form instead of the search results.

Also, when hovering over "All", none of the options in the popup menu are selectable.

**Comment by azurebrd** [comment]
Removed search box, might later make submission link to http://www.wormbase.org/search/all/<input>
