### ISSUE TITLE
  Hi, I was trying to find a figure tha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3978]
<p>&nbsp;&nbsp;Hi, I was trying to find a figure that breaks down the worm genome into different components (e.g. protein coding, introns, transposable elements, etc.) similar to this figure for the human genome:<br/>http://www.nature.com/nrg/journal/v6/n9/box/nrg1674_BX3.html<br/>Could you please advise where I would be able to get such information (e.g. the % breakdown of various components).  Thanks!</p>

Reported by: Sand************ (sand********************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/43.0.2357.56 Mobile/12F69 Safari/600.1.4 (000283)

**Comment by epaule** [comment]
in theory you can parse it out of our GFF3 files, but you need to watch out for overlapping features on the positive and negative strand.
Also a pie chard is most likely not very good at representing the categories, as a base pair can fall into multiple.

As cheap alternative, I can recommend using our intergenic fasta file from the FTP server and do a coding/non-coding base pair graph, as they are mutually exclusive.
