### ISSUE TITLE
  want to know various strains availabl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3979]
<p>&nbsp;&nbsp;want to know various strains available for sirtuin gene in C.elegans?</p><p>What were you doing? <br />&nbsp;&nbsp;research scholar</p>

Reported by: tanv*****************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by tuli** [comment]
Hello,

Thank you for writing to WormBase.

C. elegans has 4 sir genes, which can be seen here:
http://www.wormbase.org/resources/gene_class/sir

To see which strains are available for each gene, click on the gene of
interest (e.g. http://www.wormbase.org/species/c_elegans/gene/WBGene00004800)
and go to the Genetics widget. The available strains are at the bottom
of this widget.

I hope this answers your query.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
