### ISSUE TITLE
   

Reported by:  sal******* (sali****...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3980]
<p>&nbsp;&nbsp;</p>

Reported by:  sal******* (sali****************)  (obscured for privacy))
Submitted From: CDS - search <a href="http://www.wormbase.org//search/all/CDS">/search/all/CDS</a>

Mozilla/5.0 (X11; U; Linux i686; zh-CN; rv:1.2.3.4) Gecko/

**Comment by chris-grove** [comment]
Hello Salini,

 Did you have a question for WormBase?

Best,

Chris Grove

**Comment by chris-grove** [comment]
Closing for now. Will reopen if necessary.
