### ISSUE TITLE
   

Reported by: suba** (suba*********...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3981]
<p>&nbsp;&nbsp;</p>

Reported by: suba** (suba********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by tuli** [comment]
Dear Subala,

Did you mean to include some content in your report to WormBase helpdesk?

Please write to us again if we can help you with anything.

Best wishes,

Mary Ann

On 19 June 2015 at 11:24,  <no-reply@wormbase.org> wrote:
> Feature Request
>
>
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3981. Follow progress on our
> issue tracker.
>
> Reported by: subala (subalachitra91@gmail.com)
> 19 Jun 15 10:24
>
> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/43.0.2357.124 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Give it a few days and then close if no reply.

**Comment by tuli** [comment]
Dear Subala,

WormBase is a database for C. elegans and other nematodes.

Mary Ann



On 19 June 2015 at 11:53, Subala Chitra <subalachitra91@gmail.com> wrote:
> Respected Madam,
>
> Good Afternoon., Shall I know abt wormbase.,, what content abt insects
> include..?
>
>
> Best Regards..)
>
> S.P.SUBALA
> Research Scholar
> Molecular Entomology Laboratory
> Department of Biotechnology
> Periyar University, Salem-636 011, Tamil Nadu, India
>
> =========================================================
> "எழுந்து நில். தைரியமாக இரு. வாழ்வில் எந்த அளவுக்கு உயர நினைக்கிறாயோ,
> அந்த அளவுக்கு நீ கடுமையான சோதனைகளையும்  கடந்தாக வேண்டும்."
>                                                      - விவேகானந்தர்
>
> “The scientist is not a person who gives the right answers, he's one
> who asks the right questions.”
>                                                - Claude Levi-Strauss
> ==========================================================
>
>
> On Fri, Jun 19, 2015 at 6:37 AM, Mary Ann Tuli
> <maryann.tuli@wormbase.org> wrote:
>> Dear Subala,
>>
>> Did you mean to include some content in your report to WormBase helpdesk?
>>
>> Please write to us again if we can help you with anything.
>>
>> Best wishes,
>>
>> Mary Ann
>>
>> On 19 June 2015 at 11:24,  <no-reply@wormbase.org> wrote:
>>> Feature Request
>>>
>>>
>>>
>>> Submitted From:
>>>   support /tools/support
>>>
>>> This issue has been assigned ticket number: #3981. Follow progress on our
>>> issue tracker.
>>>
>>> Reported by: subala (subalachitra91@gmail.com)
>>> 19 Jun 15 10:24
>>>
>>> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
>>> Chrome/43.0.2357.124 Safari/537.36
>>>
>>> This question was reported via the web interface at wormbase.org. You can
>>> also email us directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the "WormBase: help"
>>> group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>
>>
>>
>> --
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
