### ISSUE TITLE
WormMine is down

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3982]
504 Gateway Time-out

**Comment by tharris** [comment]
Have you been running large queries against it today? It's been processing some long running ones all afternoon.

**Comment by tharris** [comment]
Okay, back up. Weird.

**Comment by dasmoth** [comment]
Down again now.

(And no big queries from me -- is there a query log that might give some indication of what's doing this?)

**Comment by tharris** [comment]
I don't think your language is very precise. I just ran a query with no problems.  I don't know much about scaling Intermine at the moment -- it's a third party project. It's something to look at once we have our cloud instance running.
