### ISSUE TITLE
Cannot upload images to the WormBase Wiki

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3984]
I keep getting the following error message:

![screen shot 2015-06-19 at 2 40 35 pm](https://cloud.githubusercontent.com/assets/611382/8263631/6d344cba-1691-11e5-80f5-ede4b526d6bc.png)

**Comment by tharris** [comment]
What is the file format you are trying to upload?

**Comment by chris-grove** [comment]
@tharris   PNG

**Comment by tharris** [comment]
Should be working now.

**Comment by chris-grove** [comment]
Now I'm getting this error:
![screen shot 2015-06-19 at 3 37 45 pm](https://cloud.githubusercontent.com/assets/611382/8264318/6a4d1678-1699-11e5-9df5-d44c47147b12.png)

**Comment by tharris** [comment]
Sorry @chris-grove! Really, should be working now. I just tested. If it isn't working for you, please send the file you are trying to upload.

**Comment by chris-grove** [comment]
@tharris OK it's working now!
