### ISSUE TITLE
  Hey there...what's the best way for m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3986]
<p>&nbsp;&nbsp;Hey there...what's the best way for me to go about getting a list of genes that are expressed only in the adult male, i.e. not in the adult hermaphrodite? I'm guessing a query using WQL, although I don't know what the life stage codes for adult male and adult hermaphrodite are...<br/>the wiki help files talk about using the "Advanced search" option - i can't for the life of me find an advanced search panel!!!<br/>Any help would be much appreciated!<br/>Cheers<br/>Vikram</p>

Reported by: Vikr********** (v.na******************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1

**Comment by dasmoth** [comment]
Dear Vikram, thank you for writing to WormBase.

>   Hey there...what's the best way for me to go about getting a list of
> genes that are expressed only in the adult male, i.e. not in the adult
> hermaphrodite? I'm guessing a query using WQL, although I don't know what
> the life stage codes for adult male and adult hermaphrodite are...
>
Querying using WQL should work.  You may also want to take a look at
WormMine <http://www.wormbase.org/tools/wormmine/begin.do>.

Assuming you're working with C. elegans, the life stage codes you are
looking for are:

        WBls:0000056
<http://www.wormbase.org/species/all/life_stage/WBls:0000056#021--10>
(adult male Ce)
        WBls:0000057
<http://www.wormbase.org/species/all/life_stage/WBls:0000057#021--10>
(adult hermaphrodite Ce)

Do let me know if you run into any issues writing your queries, and I'll
try to get you in touch with an expert in whichever query interface you're
using.

> the wiki help files talk about using the "Advanced search" option - i
> can't for the life of me find an advanced search panel!!!
>
Are you referring to:

          http://wiki.wormbase.org/index.php/UserGuide:Advanced_Search

In the new website, AQL and WQL queried can be executed by selecting the
"Queries" option from the "Tools" menu in the top bar, or by going directly
to:

           http://www.wormbase.org/tools/queries

Best wishes,

          Thomas.

**Comment by WenChenWormBase** [comment]
Dear Vikram:

There is only one expression pattern annotated WBls:0000056 (adult male
Ce), and the gene is lov-1.

Sometimes authors do not specify life stages, so the gene can be annotated
to all stages (WBls:0000002) or no life stage information were included. If
you only query for WBls:0000056, you will miss a lot of genes.

A WQL query that can help you to pull out all genes that expressed in males
is:

Find Anatomy_term Term = *male*; follow Expr_pattern; follow Gene

I found 177 genes in WS249 falling into this category. You may take the
list of genes and look up their associated anatomy parts in WormMine, and
filter out those that also showed hermaphrodite expression. I think this
will give a complete answer to your question.

Please let us know if you have problem with WQL or WormMine. At the end of
this email is the list of 177 genes that I dumped out from WS249, just for
your reference.


Wen Chen
Curator, WormBase


------------------------------------

KeySet : "male_expressed.ace"
Gene_name : "acn-1"
Gene_name : "apl-1"
Gene_name : "aqp-8"
Gene_name : "cat-1"
Gene_name : "cat-2"
Gene_name : "cav-2"
Gene_name : "Cbr-fog-3"
Gene_name : "ccr-4"
Gene_name : "cct-1"
Gene_name : "cdc-42"
Gene_name : "cdh-3"
Gene_name : "ceh-7"
Gene_name : "ceh-13"
Gene_name : "ceh-63"
Gene_name : "cgh-1"
Gene_name : "clec-197"
Gene_name : "cnb-1"
Gene_name : "col-19"
Gene_name : "cpr-1"
Gene_name : "Cre-fog-3"
Gene_name : "Cre-spe-44"
Gene_name : "csr-1"
Gene_name : "daf-21"
Gene_name : "daz-1"
Gene_name : "dbl-1"
Gene_name : "din-1"
Gene_name : "dop-2"
Gene_name : "dyf-5"
Gene_name : "efn-4"
Gene_name : "egl-1"
Gene_name : "egl-5"
Gene_name : "egl-46"
Gene_name : "elt-1"
Gene_name : "elt-2"
Gene_name : "etr-1"
Gene_name : "exc-9"
Gene_name : "far-1"
Gene_name : "far-2"
Gene_name : "far-3"
Gene_name : "far-5"
Gene_name : "far-6"
Gene_name : "far-7"
Gene_name : "fem-1"
Gene_name : "fem-3"
Gene_name : "fer-1"
Gene_name : "fox-1"
Gene_name : "gei-8"
Gene_name : "glb-26"
Gene_name : "gld-1"
Gene_name : "gld-3"
Gene_name : "gpa-7"
Gene_name : "gsa-1"
Gene_name : "him-4"
Gene_name : "hlh-2"
Gene_name : "hlh-8"
Gene_name : "hst-2"
Gene_name : "ida-1"
Gene_name : "ina-1"
Gene_name : "ins-31"
Gene_name : "inx-12"
Gene_name : "inx-13"
Gene_name : "ketn-1"
Gene_name : "kgb-1"
Gene_name : "lag-2"
Gene_name : "let-711"
Gene_name : "let-767"
Gene_name : "lev-11"
Gene_name : "lin-29"
Gene_name : "lin-35"
Gene_name : "lin-39"
Gene_name : "lnkn-1"
Gene_name : "lov-1"
Gene_name : "mab-3"
Gene_name : "mab-23"
Gene_name : "mom-2"
Gene_name : "mpz-3"
Gene_name : "msp-3"
Gene_name : "msp-10"
Gene_name : "msp-19"
Gene_name : "msp-24"
Gene_name : "msp-29"
Gene_name : "msp-31"
Gene_name : "msp-32"
Gene_name : "msp-33"
Gene_name : "msp-36"
Gene_name : "msp-37"
Gene_name : "msp-38"
Gene_name : "msp-40"
Gene_name : "msp-41"
Gene_name : "msp-42"
Gene_name : "msp-45"
Gene_name : "msp-46"
Gene_name : "msp-47"
Gene_name : "msp-48"
Gene_name : "msp-49"
Gene_name : "msp-50"
Gene_name : "msp-51"
Gene_name : "msp-52"
Gene_name : "msp-53"
Gene_name : "msp-54"
Gene_name : "msp-55"
Gene_name : "msp-56"
Gene_name : "msp-57"
Gene_name : "msp-58"
Gene_name : "msp-59"
Gene_name : "msp-60"
Gene_name : "msp-61"
Gene_name : "msp-62"
Gene_name : "msp-63"
Gene_name : "msp-64"
Gene_name : "msp-65"
Gene_name : "msp-70"
Gene_name : "msp-71"
Gene_name : "msp-72"
Gene_name : "msp-74"
Gene_name : "msp-76"
Gene_name : "msp-77"
Gene_name : "msp-78"
Gene_name : "msp-79"
Gene_name : "msp-81"
Gene_name : "msp-113"
Gene_name : "msp-142"
Gene_name : "msp-152"
Gene_name : "myo-3"
Gene_name : "nhr-25"
Gene_name : "nlp-5"
Gene_name : "nlp-10"
Gene_name : "nlp-14"
Gene_name : "nmy-2"
Gene_name : "ntr-2"
Gene_name : "odc-1"
Gene_name : "odr-10"
Gene_name : "old-1"
Gene_name : "pam-1"
Gene_name : "plg-1"
Gene_name : "plx-1"
Gene_name : "pmr-1"
Gene_name : "pros-1"
Gene_name : "pry-1"
Gene_name : "puf-8"
Gene_name : "rme-8"
Gene_name : "scc-1"
Gene_name : "set-1"
Gene_name : "shn-1"
Gene_name : "sma-3"
Gene_name : "smp-1"
Gene_name : "smz-1"
Gene_name : "spe-4"
Gene_name : "spe-12"
Gene_name : "spe-26"
Gene_name : "spe-27"
Gene_name : "spe-39"
Gene_name : "spe-44"
Gene_name : "spp-14"
Gene_name : "sra-1"
Gene_name : "sra-6"
Gene_name : "srd-1"
Gene_name : "srp-2"
Gene_name : "ssp-16"
Gene_name : "stam-1"
Gene_name : "ten-1"
Gene_name : "tni-1"
Gene_name : "tni-3"
Gene_name : "try-5"
Gene_name : "ubc-9"
Gene_name : "unc-15"
Gene_name : "unc-17"
Gene_name : "unc-27"
Gene_name : "unc-29"
Gene_name : "unc-38"
Gene_name : "unc-54"
Gene_name : "unc-63"
Gene_name : "unc-68"
Gene_name : "unc-71"
Gene_name : "unc-103"
Gene_name : "unc-119"
Gene_name : "vbh-1"






On Sun, Jun 21, 2015 at 11:51 PM, WormBase Helpdesk <
notifications@github.com> wrote:

>   Hey there...what's the best way for me to go about getting a list of
> genes that are expressed only in the adult male, i.e. not in the adult
> hermaphrodite? I'm guessing a query using WQL, although I don't know what
> the life stage codes for adult male and adult hermaphrodite are...
> the wiki help files talk about using the "Advanced search" option - i
> can't for the life of me find an advanced search panel!!!
> Any help would be much appreciated!
> Cheers
> Vikram
>
> Reported by: Vikr********** (v.na******************) (obscured for
> privacy))
> Submitted From: Tools /header <http://www.wormbase.org//header>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/536.30.1
> (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3986>.
>



-- 
Wen Chen, Ph.D.
Curator, WormBase
