### ISSUE TITLE
  Dear WormBasePeeps - Now that there a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3989]
<p>&nbsp;&nbsp;Dear WormBasePeeps -<br/>Now that there are more genomes/gene predictions available for other species, it would be great to have better sequence searching tools... for example, the BLAST server within WormBase could be configured to allow searching multiple species/clades at once, not just one-species-at-a-time, and it would also be great to implement newer algorithms (e.g., PSI-BLAST, other HMM-based iterative methods) to enable searching. There doesn't seem to be a web-based tool anywhere that's designed for this purpose, and NCBI doesn't seem to have all of the nematode genomic or gene data.<br/>Thanks for your consideration!</p>

Reported by: Abby********* (afde**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3

**Comment by dasmoth** [comment]
Dear Abby,

Thanks for your suggestion -- we will certainly take this into account when
considering any future revision of our BLAST services.

Best wishes,

          Thomas.

**Comment by dasmoth** [comment]
Hi Abby,

if you are at the IWM in UCLA, have a talk with Bruce Bolt, as he has some
prototypes going for what exactly propose.

Michael

**Comment by dasmoth** [comment]
Thanks! I'm here and will seek him out. 

Abby

**Comment by chris-grove** [comment]
@epaule @brucebolt  Can we close this ticket now that we have ParaSite BLAST services, or is there still something being worked on?

**Comment by brucebolt** [comment]
Multi-species BLAST has been been rolled out (about three months ago).
