### ISSUE TITLE
  Hi, I would like to download the C. e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3991]
<p>&nbsp;&nbsp;Hi,<br/>I would like to download the C. elegant Cell and Anatomy Ontology (WBbt:0000100) to cross reference with my sequencing data. I can't seem to find the files. Where can I get them?<br/>Thanks!<br/>Sarah</p>

Reported by: Sara****** (sali***********)  (obscured for privacy))
Submitted From: ontology_browser <a href="http://www.wormbase.org//tools/ontology_browser/show_genes">/tools/ontology_browser/show_genes</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3

**Comment by dasmoth** [comment]
Dear Sarah, thank you for writing to WormBase.

Are you looking for a list of genes associated with one specific term, or
are you looking for a complete set of gene <--> term associations for
further analysis?

If you haven't already done so, you may want to look at this directory on
our FTP server:

             ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/ONTOLOGY/

In particular, the "anatomy_association" file -- does that contain the
information you are looking for?

Do let me know if we can be of further assistance,

              Thomas.

**Comment by dasmoth** [comment]
Dear Hao, thank you for writing to WormBase.

The reason we aren't showing any location information for this operon is
that is has been marked as deprecated and doesn't have any genomic
coordinates in our database.  It appears that this historical operon has
been merged into CEOP5557
<http://www.wormbase.org/species/c_elegans/operon/CEOP5557#012--10>, which
does have genomic coordinates (and thus a working Location widget).

Thanks for bringing the error message on location-less operons to our
attention -- I will pass this on to our web team.

Best wishes,

           Thomas.
