### ISSUE TITLE
  Hello, I am looking to download the f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3995]
<p>&nbsp;&nbsp;Hello,<br/>I am looking to download the full set of C. elegans protein sequences in FASTA format to perform a blast against (with the standalone version). I looked up "protein" under C. elegans but I was not sure which file corresponds to protein sequences. Thanks for any advice.</p>

Reported by: Jigi*** (anup*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

**Comment by dasmoth** [comment]
On Tue, Jun 23, 2015 at 1:10 PM, <no-reply@wormbase.org> wrote:
>
>   Hello,
> I am looking to download the full set of C. elegans protein sequences in
> FASTA format to perform a blast against (with the standalone version). I
> looked up "protein" under C. elegans but I was not sure which file
> corresponds to protein sequences. Thanks for any advice.
>
 Dear Jigisha, thank you for writing to WormBase.

A range of downloadable data is available from our FTP site at:

             ftp://ftp.wormbase.org/pub/wormbase

C. elegans protein sequences for the current release (WS248) can be
downloaded from:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS248.protein.fa.gz

Do let me know if you need further assistance.

Best wishes,

           Thomas.

**Comment by dasmoth** [comment]
Hi Thomas,

Thanks for the links. The FTP site does not open for me. I am on a OSX
using safari browser and I get an "unknown error". I tried on google chrome
as well, with no luck.

Jigisha

**Comment by dasmoth** [comment]
Hi again Thomas,

Its all ok now, thanks a lot.

Jigisha
