### ISSUE TITLE
  So is there no way to sign up without...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3996]
<p>&nbsp;&nbsp;So is there no way to sign up without using facebook or google. Im not comfortable with that options due to privavcy concerns</p>

Reported by: nate******* (exec************************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by dasmoth** [comment]
Todd has responded on-list
