### ISSUE TITLE
Consider making a jbrowse build where the assembly version corresponds to what is in ucsc

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#4000]
It would make life easier for people exchanging coordinates from people moving back and forth between the two browsers.

**Comment by epaule** [comment]
Hi Scott, do you mean the ce8 / ce10 ones or the one from the assembly hub?

**Comment by khowe** [comment]
UCSC has old data, on an old assembly. If you want to make a Jbrowse consistent with it, you'll need to go back to old fasta/GFF files (e.g. WS220, from 2010). The GFF files looked quite different then (our GFF3 was a hacked post-processing of GFF2), so I doubt it will work out of the box. 

However, isn't it a bit of a backward step to make Jbrowses for data that is 5 years old? IMO, a better way to get to consistency between WormBase-Jbrowse and UCSC is to provide a way for people to view the latest WormBase data on UCSC (which is what @epaule has been doing with the assembly hub).

**Comment by scottcain** [comment]
I made this post in response to a conversation with a user at IWM; I think it makes little sense to do this, particularly with the assembly hub work; closing.
