### ISSUE TITLE
Separate million mutation project alleles into a separate table in Genetics widget on gene pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4001]
We've heard several (emphatic) independent requests at the IWM to separate the million mutation project alleles into a separate table when displaying alleles for a gene, e.g. in the Genetics widget on a gene page.

**Comment by xdwang** [comment]
Actually you can sort out MMP alleles by ordering 'Method' column differently. Maybe it's just not very obvious to users.

**Comment by chris-grove** [comment]
@xdwang  Yes, but apparently this was very much not satisfactory to people... The separate table was much preferred.

**Comment by khowe** [comment]
Also, I don't think there's any way of sorting the table such that all of the classical alleles appear first and all of the MMP alleles appear last.

**Comment by xdwang** [comment]
I though clicking on the arrowhead on side of 'Method' sorting alleles somehow.

**Comment by khowe** [comment]
Yes, it sorts alphabetically on the Method. But the classical alleles have methods like "Allele", "Substitiution_allele", "NBP_allele" etc. For a typical gene, sorting will result in classical alleles at the beginning AND the end of the list.

**Comment by xdwang** [comment]
that's what I mean by 'sorting'. but anyway, separation classical and non-classical alleles into different table might be more intuitive to users.

**Comment by tharris** [comment]
What is the method for Million Mutation alleles?

**Comment by tuli** [comment]
Method = Million_mutation

On 5 February 2016 at 09:19, Todd Harris <notifications@github.com> wrote:

> What is the method for Million Mutation alleles?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4001#issuecomment-180449402>.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by khowe** [comment]
The genome browser has this "classical alleles" track. Should the top table show that same set of alleles, to be consistent with the genome browser?

**Comment by tharris** [comment]
The "Classical Alleles" track is comprised of: 

feature      = deletion:Allele                                                                                                                                                                                     
               insertion_site:Allele                                                                                                                                                                               
               substitution:Allele                                                                                                                                                                                 
               complex_substitution:Allele  

There *shouldn't* be any million mutation tracks there.

**Comment by khowe** [comment]
Right. I was proposing a "Classical alleles" table in the orthology widget, with these types. 

Of course, some people have stated that they don't understand what "Classical alleles" actually means, but that's a different issue....

**Comment by sibyl229** [comment]
Hi @chris-grove @khowe I put the million mutation project alleles into a separate table. The new table is currently hidden behind a toggle, and only expands when requested: http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#4--10 Is that okay?

**Comment by chris-grove** [comment]
@sibyl229  This looks great! Thanks! One thing: I can't seem to load the Genetics widget for daf-2 now. This may be unrelated. If it is unrelated, I will close the ticket.

**Comment by sibyl229** [comment]
Hi @chris-grove the issue with the Genetics widget for daf-2 should be unrelated. I tried to cache and then load the widget, and that works (still pretty slow, but doesn't timeout). So I think it should work on production with cache.

**Comment by chris-grove** [comment]
OK, I will close then. Thanks Sibyl!

**Comment by tuli** [comment]
This is *much* better @sibyl229 
I just have a couple of comments in display.

My eyes were not immediately drawn to the "Load the million mutation project alleles" text.

May I suggest that the line is written in bold as "Load the Million Mutation Project alleles" and that there is  a little more space underneath it, to more clearly associate them with the Allele table.

**Comment by khowe** [comment]
Looks good. Although the "Method" column in the MMP table is now redundant. 

Actually, as discussed in other contexts, the "Method" is not the right thing to be showing here. The column should be called "Source" (for example), and should link to either a publication (for classical alleles) or an ?Analysis page (e.g. http://www.wormbase.org/resources/analysis/Million_mutation_project_reanalysis). Will create another ticket for that.

**Comment by kyook** [comment]
This is great Sibyl, but one concern is that any MMP allele as well as any Polymorphism allele that has a phenotype will be only viewable if people make an effort to look and sort these respective tables.  Allele- phenotype analysis is very important information that should be highlighted upfront. 

So if possible, would you make sure that any allele with a phenotype is placed in the first allele table?  For example gk454899 on page  http://staging.wormbase.org/species/c_elegans/gene/WBGene00021921#4--10

It should be included in the MMP table, but it should also be in the top table - I'm open to suggestions on other ways to make sure people know this allele has been further characterized.

**Comment by tharris** [comment]
This is, in fact, what started this whole discussion with OH long ago. It was requested that variations be split into two tables not precisely on the method by which they were generated (eg MMP) but on whether they result in a phenotype.

**Comment by khowe** [comment]
I recall the OH  specifying several criteria he wanted to use to differentiate. One was phenotype. Another was "classical" alleles (forward genetics) vs. high-throughput reverse-genetics screens. Figuring the "best" way to split the data up became a challenge, which is why (I believe) the work stalled.  

Phenotype vs. non-phenotype seems like a clean, unambiguous way of distinguishing, without drawing us into trying to classify alleles by source/type. So how about these tables:

- Alleles and polymorphisms with associated phenotype 
- Other alleles (with currently no associated phenotype)
- Polymorphisms in wild isolate strains.

**Comment by khowe** [comment]
Oh, and as an aside, there are 7 (seven) MMP alleles with associated phenotype. But this may increase in future.

**Comment by tharris** [comment]
Very good points @khowe, absolutely right on what has been the stumbling block. And good point, too, about the extent of MMPs with phenotypes. I do think it is important to gauge effort vs return.

**Comment by kyook** [comment]
In this case, I would posit that because there are so few MMPs with
phenotypes, they will certainly be overlooked if they do not show up in
more visible table.  I suspect people won't be looking or expecting MMPs
with phenotypes, so it would be more important to make sure that those few
are among the alleles with associated phenotype table.



~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Wed, Feb 24, 2016 at 4:10 AM, Todd Harris <notifications@github.com>
wrote:

> Very good points @khowe <https://github.com/khowe>, absolutely right on
> what has been the stumbling block. And good point, too, about the extent of
> MMPs with phenotypes. I do think it is important to gauge effort vs return.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4001#issuecomment-188223662>.
>

**Comment by sibyl229** [comment]
Hi @khowe @kyook Here's the new variations table based on what Kevin described: http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#4--10 A few questions: 
- I'm not sure how to name these tables concisely, what do you think? 
- Should the "# of phenotypes" columns be removed from the two tables where it's always 0? 
- Should the these two tables without associated phenotypes both hide behind toggles? Doing that helps speed up the widget loading a bit.
Please let me know what you think. Thank you!

**Comment by chris-grove** [comment]
@sibyl229  The staging link you've posted is consistently timing out for me (504 Gateway Time-out error)

**Comment by chris-grove** [comment]
@sibyl229  I think staging is generally down for production

**Comment by sibyl229** [comment]
Hi @chris-grove Staging is up now. Sorry about that. The link above should also be working.

**Comment by chris-grove** [comment]
@sibyl229  OK thanks, it's working now

**Comment by khowe** [comment]
Hi @sibyl229 , 

- I think that table 1 will contain alleles where the phenotype has been assayed but not observed. I think this is correct, but then we should be careful how we label the table. Perhaps "Alleles with phenotype data"?  And simply "Other alleles" for the second table?

- yes, the "# of phenotypes" column should be removed from table 2 (will always be 0, by construction)

- Tables 2 and 3 are of secondary importance/interest. But, IMO, equally so. So they should either both be open by default, or both minimised. 

I note also that you've changed the "Method" column to the paper/analysis, which I like. I'm not sure "Source" is the perfect name for this column, but I can't think of anything better.

**Comment by sibyl229** [comment]
Hi @khowe The 3 alleles tables now has appropriate names. Table 2 and 3 are collapsed by default, and no longer show # of phenotypes. http://staging.wormbase.org/species/c_elegans/gene/WBGene00000912#4--10

For the Source column, I leave it at that for now. It doesn't have to be single word, something like "Publication / Study" will wrap around after the "/"?

**Comment by kyook** [comment]
It looks good,  it would be good to show Ann Villeneuve and Tim Schedl to
get their opinion.

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Tue, Mar 1, 2016 at 3:09 PM, Sibyl G <notifications@github.com> wrote:

> Hi @khowe <https://github.com/khowe> The 3 alleles tables now has
> appropriate names. Table 2 and 3 are collapsed by default, and no longer
> show # of phenotypes.
> http://staging.wormbase.org/species/c_elegans/gene/WBGene00000912#4--10
>
> For the Source column, I leave it at that for now. It doesn't have to be
> single word, something like "Publication / Study" will wrap around after
> the "/"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4001#issuecomment-190954935>.
>

**Comment by tharris** [comment]
One problem with this approach is that KO alleles can get lost in the Other Alleles table. Hopefully, the table labels will prevent encourage users interested in such reagents to dig deeper. 

I've always thought we should denote what we (or the literature) believes to be the canonical null as well as display some degree of allelic series.

**Comment by khowe** [comment]
@todd Perhaps we can put the KO alleles in (yet) another separate table? If it is minimised by default, it will not take up any screen real estate. 

@sibyl229 As displayed, it appears that any polymorphism with a phenotype will appear in table 1. Since "Allele" is most commonly used to refer to mutant alleles rather than polymorphisms, perhaps the label for table 1 should be "Alleles and polymorphisms with phenotype data".

Re: the "Source" column, I think any publication the refers to an allele will be linked it. That includes papers that have, e.g. assayed for phenotypes of that allele, but did not produce the strain. @kyook @tuli is that correct? If so, "Source" is definitely the wrong title for that column in table. Maybe it should just say "References"? For links to studies (Analysis objects), it's not a big deal that these are not strictly references

**Comment by tuli** [comment]
Yes, please put KO alleles in another table. 

I agree with "Alleles and polymorphisms with phenotype data"

Yes, Source is misleading. References is fine.

**Comment by chris-grove** [comment]
@tharris @sibyl229 
I'd just like to point out that the label for the alleles with no phenotype may be a great place to add a link to the phenotype form, as requested in #3956

**Comment by chris-grove** [comment]
Just to add, the lablel could read: 
"Load other alleles (currently with no associated phenotype)
Notice a missing phenotype annotation? Submit an update through our Phenotype form"

or something?

**Comment by tuli** [comment]
I'm looking at the Genetics widget on the act-2 gene summary page http://staging.wormbase.org/species/c_elegans/gene/WBGene00000064

This gene has no alleles with phenotype data and the labelling within the widget looks a bit odd because it says "Alleles with phenotype data:" and then there is no table, just collapsed links to 
"Load other alleles (currently with no associated phenotype)" &
"Load other polymorphisms & natural variants (currently with no associated phenotype)"

I imagine it is not possible to change the labels according to whether there are any alleles with phenotypes so I think we need to change the labels for the 'no associated phenotype' tables.

Saying "load other alleles...." doesn't make sense when there were no alleles displayed in the first place. 

![screen shot 2016-05-26 at 10 23 36](https://cloud.githubusercontent.com/assets/1359170/15570040/e782bafe-232b-11e6-90f1-b147f79e377b.png)

**Comment by kyook** [comment]
I agree with @tuli, would it be possible when there are no values for the "Allele and Polymorphisms with Phenotype" table that instead there is a place holder that says "No alleles and Polymorphisms with Phenotypes", and continue on with the other tables?

**Comment by chris-grove** [comment]
I'm going to close this issue and create a new ticket for the remaining issue of how to display the alleles when there are no alleles with phenotype

**Comment by kyook** [comment]
ok

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, Jun 16, 2016 at 11:21 AM, Chris Grove <notifications@github.com>
wrote:

> I'm going to close this issue and create a new ticket for the remaining
> issue of how to display the alleles when there are no alleles with phenotype
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/WormBase/website/issues/4001#issuecomment-226570039>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAlVGmRoTEi0jELALsl5S7--bSjMgpdSks5qMZQmgaJpZM4FM4_o>
> .
>
