### ISSUE TITLE
WS249 intermine release to-do

### ISSUE THREAD

**Issue by tharris** [WormBase/website#4002]
For the WS249 release due at the end of July, here’s what needs to happen.
1. Figure out solution for adding the wormbase branding (header and footer)
2. Export / import userdatbase from current instance (at oicr)
3. Clarify / fix log in between intermine / wormbase /google
4. Build WS249 with the following species. Non C. elegans species will mostly be sequence feature annotations like genes

b_malayi
c_angaria
c_brenneri
c_briggsae
c_elegans
c_japonica
c_remanei
c_sinica
c_tropicalis
o_volvulus
p_pacificus
p_redivivus
1. Prioritize outstanding intermine issues 
2. Develop production workflow for creating image of development instance, launching new smaller capacity production instance, mirroring user database,

**Comment by nuin** [comment]
Number 4 was completed last week. Working on number 2.

**Comment by nuin** [comment]
Number 2 was performed today.

**Comment by epaule** [comment]
historical
