### ISSUE TITLE
  Hi At the workshop on wormbase, there...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4006]
<p>&nbsp;&nbsp;Hi<br/>At the workshop on wormbase, there was mention of slides being available to the community?  Can you share them by email or is there a link?<br/>THanks a lot!<br/>Brian</p>

Reported by: Bria********* (krae***********)  (obscured for privacy))
Submitted From: workshop 2015 - search <a href="http://www.wormbase.org//search/all/workshop 2015">/search/all/workshop 2015</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by dasmoth** [comment]
@epaule currently dealing with this on-list:

Hi Brian,

I put links to the assembly hub / parasite slides into the blog post: http://blog.wormbase.org/2015/06/wormbase-hubs/


Thanks Michael,  those are great.
 
Do you also have the Van Auken Slides on Go terms & geneset analysis, etc?

**Comment by chris-grove** [comment]
Hi Brian,

 Sure thing!

https://dl.dropboxusercontent.com/u/4290782/IWM_2015_WormBase_Workshop.zip

We will be posting them to an FTP site soon.

Best,

Chris Grove

**Comment by raymond91125** [comment]
Hi Brian,

All of the workshop presentations can also be found at:

1.  SlideShare 
<http://www.slideshare.net/search/slideshow?searchfrom=header&q=%22wormbase+workshop%22>
2.  FTP 
<ftp://caltech.wormbase.org/pub/wormbase/presentations/IWM_2015_WormBase_Workshop/>

raymond



On 06/29/2015 01:10 PM, Christian A Grove wrote:
> Hi Brian,
>
>   Sure thing!
>
> https://dl.dropboxusercontent.com/u/4290782/IWM_2015_WormBase_Workshop.zip
>
> We will be posting them to an FTP site soon.
>
> Best,
>
> Chris Grove
>
>
>> How
>> Do
>> I
>> ...?
>>    Hi
>> At the workshop on wormbase, there was mention of slides being available
>> to the community?  Can you share them by email or is there a link?
>> THanks a lot!
>> Brian
>> Submitted From:
>>    workshop 2015 - search /search/all/workshop 2015
>>   This issue has been assigned ticket number: #4006. Follow progress on our
>> issue tracker.
>>
>>   Reported by: Brian Kraemer (kraemerb@uw.edu)
>>   28 Jun 15 14:42
>>
>>   Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
>> Gecko) Chrome/43.0.2357.130 Safari/537.36     This question was reported
>> via the web interface at wormbase.org. You can also email us directly.
>>    --
>>   --
>>   You received this message because you are subscribed to the "WormBase:
>> help" group.
>>   To post to this group, send email to help@wormbase.org
>>   To unsubscribe from this group, send email to
>>   help+unsubscribe@wormbase.org
>>   For more options, visit this group at
>>   http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>
>>    To unsubscribe from this group and stop receiving emails from it, send
>> an email to help+unsubscribe@wormbase.org.
>>
>
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> Chris Grove, PhD
> Associate Biologist, Curator, www.Wormbase.org
> Office Phone: (626) 395-5904
> E-mail: cgrove@caltech.edu
> E-mail: chris@wormbase.org
> Skype name: christian_grove
> Virtual Worm website: http://caltech.wormbase.org/virtualworm/
> Mailing Address:
> Division of Biology
> Mail Code 156-29
> California Institute of Technology
> 1200 E. California Blvd.
> Pasadena, CA 91125
>


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
