### ISSUE TITLE
Display Gene cluster in Overview Widget on Gene Summary.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4014]
Hi,

I just noticed that I/We never pushed a ticket to get the Gene_cluster info added to the Gene summary Overview widget.

If a Gene_cluster is attached to a gene, could this be displayed dynamically below the Gene class: information please?

Example Gene:

http://www.wormbase.org/species/c_elegans/gene/WBGene00004512#0a-9f-3

Connects to the rDNA_cluster via the following tags.
```
Gene_info In_cluster rDNA_cluster
```

Gene cluster object: (currently not dumped from the database with all info will resolve for WS250).

http://www.wormbase.org/species/all/gene_cluster/rDNA_cluster#02--10

Thanks

Paul

**Comment by sibyl229** [comment]
Hi @Paul-Davis the display for Gene cluster is added to the highlight box in Gene Overview: http://staging.wormbase.org/species/c_elegans/gene/WBGene00000898#0--3 Sorry I forgot about this ticket :(

**Comment by sibyl229** [comment]
@Paul-Davis sorry, that was the wrong link. It should be http://staging.wormbase.org/species/c_elegans/gene/WBGene00004512#0-h-3. I just updated it.

**Comment by Paul-Davis** [comment]
Looks good to me @sibyl229

**Comment by sibyl229** [comment]
Thanks @Paul-Davis. Closing.
