### ISSUE TITLE
  I noticed a bug on a couple of gene p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4016]
<p>&nbsp;&nbsp;I noticed a bug on a couple of gene pages - apparently restricted to single exon genes? See for example med-1, in the "sequences" tab: while there's clearly a protein, the coding sequence length is null, and if I try to view the spliced sequence, I only get the UTR.</p>

Reported by: anto************************  (obscured for privacy)
Submitted From: med-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00003180#0f916d-4b-2-916db">/species/c_elegans/gene/WBGene00003180#0f916d-4b-2-916db</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by dasmoth** [comment]
Dear Antoine,

Thank you for  writing to WormBase.

There does appear to be a problem with the display of this transcript -- we
are looking into it.

Best wishes,

            Thomas.
