### ISSUE TITLE
  How can I download the codes and sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4017]
<p>&nbsp;&nbsp;How can I download the codes and sequences for each C. elegans gene involved in the RNAi pathway?</p>

Reported by: Paul* (pvie*************)  (obscured for privacy))
Submitted From: Process&Pathway <a href="http://www.wormbase.org//resources/wbprocess#0--10">/resources/wbprocess#0--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by vanaukenk** [comment]
Dear Paul,
Thanks for writing to WormBase.
Can you please explain what you mean by codes?  I am working on putting together a list of genes involved in the RNAi pathway, but wasn't quite sure what you meant by codes.
Thanks,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
Corresponded directly with user.  Codes = CGC gene names.
Sent him to BioMart to download names and protein sequences of genes annotated to RNAi-related GO terms.
