### ISSUE TITLE
  find out the record creation date for...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4023]
<p>&nbsp;&nbsp;find out the record creation date for this entry https://www.wormbase.org/species/c_elegans/variation/WBVar00266573#02-45-3 ?</p><p>What were you doing? <br />&nbsp;&nbsp;curating some allele data </p>

Reported by: mpri***********  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by chris-grove** [comment]
Hi there,

 Are you looking for the date the allele was added to the WormBase database? I'm not sure we have this information immediately available. The single reference for the allele is from 1989, which you can see by opening up the "References" widget for the allele:

https://www.wormbase.org/species/c_elegans/variation/WBVar00266573#027-563-3


Was it something else you were looking for?

Best,

Chris Grove

**Comment by chris-grove** [comment]
Chris,

Yes, I was looking for the date the allele record I was looking at was added to
Wormbase, not the reference.  Does that information exist at all?   Perhaps in a
hidden field attached to the record, but just not viewable in the public view of
wormbase for that entry?

Michelle

**Comment by chris-grove** [comment]
Options:   	View Full Header |  View Printable Version  | Download this as a file

Hi Michelle,

 We have timestamps (in ACEDB) for this allele that go back as early as
July 2003, so it was probably introduced into the database around then,
maybe earlier.

Chris
