### ISSUE TITLE
  Hello! I have a mac and I'm trying to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4024]
<p>&nbsp;&nbsp;Hello! I have a mac and I'm trying to copy and paste gene sequences into MacVector, although when I do this, I lose the differentiation between introns and exons AKA the introns become uppercase. Is there a way to keep the integrity of the data from your website when using a tool like this? Let me know, and thank you for your time!</p>

Reported by: Dana (dlyn**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by dasmoth** [comment]
From @chris-grove:

Hi Dana,

 I don't know how MacVector differentiates between exons and introns or
how, generally, sequences are to be imported into MacVector to preserve
this information, but if you copy and paste the sequences from WormBase
directly into any rich-text editor, that should preserve the exon/intron
information. There may be some additional sequence tagging that needs to
be done for MacVector.

**Comment by chris-grove** [comment]
Haven't heard back from user. Closing.
