### ISSUE TITLE
  Dear Wormbase, I am Le Tho Son. I am ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4031]
<p>&nbsp;&nbsp;Dear Wormbase,<br/>I am Le Tho Son. I am a Vietnamese person.<br/>I want to start a long-term project that is to translates the WormBook from English to Vietnamese for Vietnamese students in Viet Nam.<br/>Could you let me know how to get the rights for this project?<br/>Sincerely,<br/>Son </p><p>What were you doing? <br />&nbsp;&nbsp;A C. elegans biologist</p>

Reported by: Le T****** (sona**************************************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by gw3** [comment]
Could someone with some knowledge of the WormBook project care to reply to Le Tho Son?

**Comment by epaule** [comment]
I do believe WormBook is covered by a Creative Commons licences (CC BY 2.5)
http://creativecommons.org/licenses/by/2.5/ unless otherwise noted.

M

**Comment by paulwsternberg** [comment]
I will forward to Jane and Marty so there is a strong connection
