### ISSUE TITLE
  I was lucky enough to attend a semina...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4034]
<p>&nbsp;&nbsp;I was lucky enough to attend a seminar at the recent UCLA worm meeting where the newer capabilities, especially those regarding publishing/mini publishing localization patterns in new gfp tagged strains etc, were shared in one of the sessions.  I would very much like to share the entire pptx presented during the session with my lab mates unable to attend the session or meeting.  I am hoping I am contacting the correct group, and if not that I might find guidance in the proper direction to access such documents?  Thank you very much in advance for your assistance!<br/>Best,<br/>Katryn Harwood </p>

Reported by: Kate****************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4

**Comment by raymond91125** [comment]
Hi,

Thanks for your kind words. We have shared the presentation slides in 
several ways which are listed in the News section on WormBase front 
page. Let us know if you have trouble accessing the files.

Best regards,

Raymond

**Comment by raymond91125** [comment]
Hi Kate,

glad you like it

As Raymond pointed out the presentations are on the site but to make it
quicker, here's the direct link.

http://www.slideshare.net/raymond91105/micropublication-wormbase-workshop-international-worm-meeting-2015?qid=e2904867-6602-4ff7-80cb-084c2c0f187c&v=default&b=&from_search=5

Fell free to get in contact any time if you or your lab mates have questions

thanks

Daniela


>                                                                                     .fade{font-size:.9em;color:#999}
>
> Question:
>   I was lucky enough to attend a seminar at the recent UCLA worm meeting
> where the newer capabilities, especially those regarding publishing/mini
> publishing localization patterns in new gfp tagged strains etc, were
> shared in one of the sessions.  I would very much like to share the
> entire pptx presented during the session with my lab mates unable to
> attend the session or meeting.  I am hoping I am contacting the correct
> group, and if not that I might find guidance in the proper direction to
> access such documents?  Thank you very much in advance for your
> assistance!
> Best,
> Katryn Harwood
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #4034. Follow progress on our
> issue tracker.
>
>  Reported by: Kate.harwood@nih.gov
>  08 Jul 15 02:24
>
>  Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML,
> like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4     This question was
> reported via the web interface at wormbase.org. You can also email us
> directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>
