### ISSUE TITLE
  I was looking for a reference for the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4036]
<p>&nbsp;&nbsp;I was looking for a reference for the ncam-1::gfp ( cmEx17 [F02G3.1::gfp) using the Expr1764 and I could not find a reference. Could you add one? Or tell me how I should cite it? </p>

Reported by: Srim********** (sgho**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by chris-grove** [comment]
Hi Srimoyee,

 On the Expr1764 page: 

http://www.wormbase.org/species/all/expr_pattern/Expr1764#0215--10 

If you click on "Curatorial remarks" in the "Overview" widget, you can see that this information refers to a personal communication with Oliver Hobert, but there doesn't appear to be any other references.

This "MIGHT"(?) be citable as an indirect personal communication with Oliver, but it's probably best to contact Oliver.

Best,

Chris Grove

**Comment by draciti** [comment]
Hi Srimoyee,

that specific pattern is a personal communication from Oliver Hobert.

From the records:
Reference: personal communication from Oliver Hobert 2002-12-07.

Published evidence of ncam-1 pharyngeal expression is in WBPaper00033047

Let me know if we can help with anything 

Daniela
