### ISSUE TITLE
Update of WBGene00022599

### ISSUE THREAD

**Issue by gw3** [WormBase/website#4037]
Hello,

I noticed that the following wormbase entry has been characterised:

WormBase ID: WBGene00022599

It has been characterised in the following publication:

PubMed=25830239
Horikawa M., Sural S., Hsu A.L., Antebi A.
Co-chaperone p23 regulates C. elegans Lifespan in Response to Temperature.
journal article: PLoS Genet. 11:E1005023-E1005023 (2015)

I was wondering whether this is also going to be updated on Wormbase?

Please let me know if you need any further information.

Best wishes,

Hema

**Comment by gw3** [comment]
The paper refers to a gene name 'daf-41' which they did not go through gene-names to get assigned.

Textpresso will have trouble picking this up as the name is appended to the gene-id.

**Comment by tuli** [comment]
It's in our confidential files @gw3 
The authors of the paper did go through genenames.

**Comment by tuli** [comment]
Textpresso seems to have coped with it.

**Comment by tuli** [comment]
Dear Hema,

Thank you for bringing this publication to our attention.

The daf-41 name was being held in confidence. I have now released it
and made the update in WormBase and it will be available in release
WS250.

Best wishes,

Mary Ann



On 9 July 2015 at 14:35, Hema Bye-A-Jee <hbye@ebi.ac.uk> wrote:
> Hello,
>
> I noticed that the following wormbase entry has been characterised:
>
> WormBase ID: WBGene00022599
>
> It has been characterised in the following publication:
>
> PubMed=25830239
> Horikawa M., Sural S., Hsu A.L., Antebi A.
> Co-chaperone p23 regulates C. elegans Lifespan in Response to Temperature.
> journal article: PLoS Genet. 11:E1005023-E1005023 (2015)
>
> I was wondering whether this is also going to be updated on Wormbase?
>
> Please let me know if you need any further information.
>
> Best wishes,
>
> Hema
>
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
