### ISSUE TITLE
  Tree display not available for http:/...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4038]
<p>&nbsp;&nbsp;Tree display not available for http://www.wormbase.org/species/all/strain/daf-2(e1370)#02--10<br/>Bad gateway error</p>

Reported by: Mary********* (mary*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by tharris** [comment]
That isn't actually a strain, is it?  Where did you find that link? I can't find it on the daf-2 gene page.

**Comment by tuli** [comment]
It isn't, that's what I am trying to investigate. I can see the tree view for it on Staging, so I have the info I need, was just reporting the broken tree view on the live site.

**Comment by tharris** [comment]
Is there any thing else to do on this?

**Comment by tuli** [comment]
I think not.
