### ISSUE TITLE
  Dear WormBase curators, (sorry for ad...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4039]
<p>&nbsp;&nbsp;Dear WormBase curators,<br/>(sorry for addressing this in a general manner, but I couldn’t figure out which/if any of the online forms are suitable for this kind of feedback)<br/>Looking up information on emr-1 I got surprised when I saw that it is listed as having an aldicarb resistant phenotype based on RNAi experiments (e.g. WBRNAi00060383). We have observed that emr-1(gk119) mutants have just the opposite phenotype: they are hypersensitive to aldicarb (WBPaper00044786).<br/>I checked the paper that is listed as evidence for the aldicarb resistant RNAi phenotype and it actually doesn’t mention emr-1. Instead, it focuses the downstream gene nlp-12. The RNAi construct used in their experiments (sjj_M01D7.5 (Source BioScience: I-1A18)) covers nlp-12 and apparently also the last exon of emr-1 transcript M01D7.6.2. However, as far as I can tell from the information on WormBase, this particular exon consists of five nucleotides only (aaaaa) and it is therefore highly unlikely that the spliced M01D7.6.2 transcript is targeted by the RNAi clone I-1A18. The two shorter emr-1 transcripts (M01D7.6.1 and M01D7.6.3) are not targeted by RNAi clone I-1A18. Based on this I suggest,<br/>1) emr-1 is not listed as primary target in the experiment involving this RNAi construct.<br/>2) the aldicarb resistant phenotype is removed from the emr-1 gene page to avoid confusion. Rather, I suggest that emr-1 is listed as aldicarb hypersensitive based on our data.<br/>Thanks for doing a great job!!<br/>Peter (WBPerson1780)</p>

Reported by: Pete********* (pask*******)  (obscured for privacy))
Submitted From: Submit data <a href="http://www.wormbase.org//about/userguide/submit_data#01--10">/about/userguide/submit_data#01--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/7.1.7 Safari/537.85.16

**Comment by Paul-Davis** [comment]
Dear Peter (WBPerson1780),

Thank you for using your correct designation.

I have added a 5bp masking feature to the 454 read cluster that causes 
the incorrect prediction of this five nucleotide (aaaaa) exon for  emr-1 
transcript M01D7.6.2.

This should prevent the incorrect mapping of the RNAi clone and the 
downstream association with incorrect phenotype data.

Thank you for pointing this out.

Paul (WBPerson1983)
[Sequence curation]

On 10/07/2015 10:51, no-reply@wormbase.org wrote:
> Content Correction
>
>   Dear WormBase curators,
> (sorry for addressing this in a general manner, but I couldn’t figure 
> out which/if any of the online forms are suitable for this kind of 
> feedback)
> Looking up information on emr-1 I got surprised when I saw that it is 
> listed as having an aldicarb resistant phenotype based on RNAi 
> experiments (e.g. WBRNAi00060383). We have observed that emr-1(gk119) 
> mutants have just the opposite phenotype: they are hypersensitive to 
> aldicarb (WBPaper00044786).
> I checked the paper that is listed as evidence for the aldicarb 
> resistant RNAi phenotype and it actually doesn’t mention emr-1. 
> Instead, it focuses the downstream gene nlp-12. The RNAi construct 
> used in their experiments (sjj_M01D7.5 (Source BioScience: I-1A18)) 
> covers nlp-12 and apparently also the last exon of emr-1 transcript 
> M01D7.6.2. However, as far as I can tell from the information on 
> WormBase, this particular exon consists of five nucleotides only 
> (aaaaa) and it is therefore highly unlikely that the spliced M01D7.6.2 
> transcript is targeted by the RNAi clone I-1A18. The two shorter emr-1 
> transcripts (M01D7.6.1 and M01D7.6.3) are not targeted by RNAi clone 
> I-1A18. Based on this I suggest,
> 1) emr-1 is not listed as primary target in the experiment involving 
> this RNAi construct.
> 2) the aldicarb resistant phenotype is removed from the emr-1 gene 
> page to avoid confusion. Rather, I suggest that emr-1 is listed as 
> aldicarb hypersensitive based on our data.
> Thanks for doing a great job!!
> Peter (WBPerson1780)
>
> Submitted From:
>   Submit data /about/userguide/submit_data#01--10 
> <http://www.wormbase.org//about/userguide/submit_data#01--10>
>
> This issue has been assigned ticket number: #4039. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4039>.
>
> Reported by: Peter Askjaer (pask@upo.es)
> 10 Jul 15 09:53
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.7.12 
> (KHTML, like Gecko) Version/7.1.7 Safari/537.85.16
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
@khowe  @Paul-Davis 
This is actually a more systemic problem, that we've discussed, with the RNAi mapping pipeline. We really need to make a change to the pipeline so that small matches (as small as a single overlapping base pair) do not trigger a match as a target for a dsRNA sequence in an RNAi experiment.

**Comment by khowe** [comment]
@chris-grove Changes to the RNAi mapping pipeline were put on ice, in anticipation of the whole thing being reimagined in the CloneMapper philosophy. 

However, given the considerable amount of work that will involve (and lack of resources to do it right now), let's unfreeze the current pipeline for important fixes such as this.

We're agreed that a 5bp overlap shouldn't register. So what should be the cutoff? Shall we say 100bp? i.e. at least 100bp of the transcript should be covered by the RNAi sequence (alignment)?

We should also decide whether to treat CDSs and full-length transcripts differently this case. What if the RNAi sequence has a healthy overlap with the UTR of a transcript, but only small (e.g. 5bp) overlap  with the CDS? Should we still form a connection between the RNAi and the CDS in these cases?

**Comment by chris-grove** [comment]
@khowe 
OK, yes, I think we should fix this ASAP.

As for cutoffs, any matches to the entire transcript (UTR or CDS) are valid and should be considered part of the official match; there really need not be any distinction. For now, we can stick to the same cutoffs we have been using (primary targets exhibit 100bp or greater match at 90% or greater identity, secondary targets exhibit 200bp or greater match at 80-90% identity) but matching the transcript, not just the genome.

**Comment by chris-grove** [comment]
@khowe  We could potentially add another criteria for a primary target that is 50bp or greater match at 100% identity.

**Comment by khowe** [comment]
It's not quite as simple as that. We are using an alignment tool to produce mappings (BLAT). The tool may report a longer, lower identity alignment that may or may not contain within it a shorter region of perfect matching. 

The simplest thing to do, achievable for WS250, is to persist with the to-genome mappings, but when assessing whether a genome alignment overlaps with a transcript, require that the overlap be > X bases of the transcript. I propose 50 for now. 

In the meantime, I will start work on a direct to-transcript mapping pipeline.

**Comment by chris-grove** [comment]
@khowe 
OK, that sounds good for now. Thanks!

**Comment by chris-grove** [comment]
Hi Peter,

 Many apologies for the delay. You're absolutely right. We're now in the process of fixing the RNAi mapping pipeline to require a minimum overlap of 50bp.

Thanks for letting us know!

Chris Grove

**Comment by chris-grove** [comment]
Hi Peter,

 Just to follow up: the erroneous "aldicarb resistant" phenotype is now no longer attributed to emr-1. I have entered the emr-1(gk119) "aldicarb hypersensitive" phenotype from your paper into our curation database.

Thanks a lot for your help!


Chris Grove
WormBase

**Comment by chris-grove** [comment]
Sorry, I meant to send you the emr-1 URL for our staging site:

http://staging.wormbase.org/species/c_elegans/gene/WBGene00001309#0-b-3

This will be live on WormBase next week.

Best,

Chris
