### ISSUE TITLE
  In WormMine is there an easy way to t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4042]
<p>&nbsp;&nbsp;In WormMine is there an easy way to take a gene list and generate a list of observed RNAi phenotypes? The Gene --> Phenotype gives you mutant phenotypes (which is great!) but I'd also like to have a list of observed RNAi phenotypes for my given gene list. I know I could do this in the old database browser "back in the day"<br/>THANKS!</p>

Reported by: davi**********************  (obscured for privacy)
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by WenChenWormBase** [comment]
Hi David:

WormMine does not have RNAi phenotype at this moment. If you can do a
little programming, you can download the RNAi Phenotype file from our ftp
site, then pull out the phenotype information of your favourite genes.

Here is a table of RNAi phenotypes in N2 background. Please let me know if
you have additional question:
ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/
RNAiPhenotype.csv
<ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/RNAiPhenotype.csv>


Wen.


On Fri, Jul 10, 2015 at 11:07 AM, WormBase Helpdesk <
notifications@github.com> wrote:

>   In WormMine is there an easy way to take a gene list and generate a list
> of observed RNAi phenotypes? The Gene --> Phenotype gives you mutant
> phenotypes (which is great!) but I'd also like to have a list of observed
> RNAi phenotypes for my given gene list. I know I could do this in the old
> database browser "back in the day"
> THANKS!
>
> Reported by: davi********************** (obscured for privacy)
> Submitted From: Tools /header <http://www.wormbase.org//header>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101
> Firefox/38.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4042>.
>



-- 
Wen Chen, Ph.D.
Curator, WormBase
