### ISSUE TITLE
Micropublication: URLs for incoming DOIs

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4043]
Hi Todd and Sibyl,
before the IWM we briefly discussed what would be the best way to go for assigning URLs to DOIs.

For each Micropublication submission I will generate a DOI and I will need a corresponding landing page. With the current database structure the URL for the landing page will be:

www.wormbase.org/species/all/expr_pattern/Exprnnnnn

being Exprnnnnn the ExprID corresponding to a specific micropublication

Todd, you had something different in mind? I might generate a DOI in the near future so I am double checking which is the best way forward. 

thanks
Daniela

**Comment by draciti** [comment]
Hi guys, I need to generate a DOI for a micropublication submission and I will attach it to the .ace file that I am uploading today. as I wrote in the previous message I am generating the doi linking it to this landing page
http://www.wormbase.org/species/all/expr_pattern/Expr12292
if you need me to change this please let me know asap
thanks

**Comment by sibyl229** [comment]
Hi @draciti @tharris how about `http://www.wormbase.org/micropub?id=Expr12292&class=Expr_pattern`?  I'm including the class name for now, as I'm not confident our search (as it's currently implemented) can always identify the object without the class name. In the future, we might make the class parameter optional (like, `http://www.wormbase.org/micropub?id=Expr12292`).

**Comment by draciti** [comment]
thanks  Sibyl, I have absolutely have no preference, as long as the landing page will be the expression pattern page (like this one for example http://www.wormbase.org/species/all/expr_pattern/Expr11092). thanks

**Comment by sibyl229** [comment]
Hi @draciti No problem. I have had the expr_pattern object pages mapped to /micropub?id=[ID]&class=Expr_pattern. It's up on staging. If you try http://staging.wormbase.org/micropub?id=Expr8549&class=Expr_pattern, it will redirect to the page for Expr8549. Though, currently it doesn't check whether the expr_pattern object is in fact a micropublication. I think this is probably okay? as you only create DOI links for those that are micropublications.

**Comment by draciti** [comment]
Sounds good Sibyl, thanks. It does not matter that it checks if it's a Micropublication. And yes, I do generate DOI links only for micropublications. I will generate the DOI-page link as 
http://www.wormbase.org/micropub?id=Expr12292&class=Expr_pattern
thanks again

**Comment by draciti** [comment]
I have done it Sibyl, thanks. We have our first DOI :)
closing

![citation_preview](https://cloud.githubusercontent.com/assets/901243/8813139/f35ba238-2fb5-11e5-8064-6f520a6d7d06.png)

**Comment by raymond91125** [comment]
nice.
