### ISSUE TITLE
WormBase blog title change

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4044]
maybe we can edit the title?

===== feedback from a user ====
Hi Michael,

Don't know whether this is your department or whether I should file a /wormbase/website ticket...

However, at some point in the last few weeks, the title of the blog (in the h1 element, and also as baked into the RSS feed) has changed from "M9: The Official WormBase Blog" to "The Official Blog of WormBase".

(The <title> element in the blog HTML remains "M9: The Official WormBase Blog".).

The new title is a disaster.  In my preferred RSS reader, it shows up as "The Official Blog Of..." -- useless!

If the words "Blog" and "Official" are both essential, can it at least be "WormBase Official Blog"?

Better still something like "WormBase News"....

**Comment by rankishore** [comment]
What about changing it to WormBase Newsletter ( its sort of a live changing newsletter!); of course WormBase News works too.

**Comment by tharris** [comment]
It's not just the WormBase Newsletter though. When I created the blog years and years ago, I called it, some stupidly, M9. I'm repurposing the blog now and will have a new variant ready in a few weeks.

**Comment by epaule** [comment]
That sounds great, so what new developments do you have in mind?
maybe we could use staff@wormbase to get feedback on any ideas/prototypes/etc.

**Comment by tharris** [comment]
I'm rebuilding It, happy to share when complete of course.
