### ISSUE TITLE
  Is there a way to align to similar se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4046]
<p>&nbsp;&nbsp;Is there a way to align to similar sequences between C. briggsae and C. elegans on the browser which pictures the whole genome. I ask because a page on wormbook mentioned this was a possibility.  The link to the page in question is http://www.wormbook.org/chapters/www_genomesCbriggsae/genomesCbriggsae.html and the alignment section in question is about a quarter down the page under the heading "Orthologs between C. briggsae and C. elegans" Thank you for any help!</p>

Reported by: Robe******** (smit**************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by raymond91125** [comment]
Hi Robert,

The Synteny Browser can be found under Tools->More tools->Synteny on 
WormBase front page.

Raymond


On 07/14/2015 12:58 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Is there a way to align to similar sequences between C. briggsae and 
> C. elegans on the browser which pictures the whole genome. I ask 
> because a page on wormbook mentioned this was a possibility. The link 
> to the page in question is 
> http://www.wormbook.org/chapters/www_genomesCbriggsae/genomesCbriggsae.html 
> and the alignment section in question is about a quarter down the page 
> under the heading "Orthologs between C. briggsae and C. elegans" Thank 
> you for any help!
>
> Submitted From:
>   Tools /header <http://www.wormbase.org//header>
>
> This issue has been assigned ticket number: #4046. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4046>.
>
> Reported by: Robert Smith (smith.9689@osu.edu)
> 14 Jul 15 19:58
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 
> (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
