### ISSUE TITLE
  I'm trying to download a list of spli...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4050]
<p>&nbsp;&nbsp;I'm trying to download a list of spliced full length transcripts, but I can't get http://www.wormbase.org/db/searches/info_dump to work or open.  don't know if the link is broken or disabled, or what.  can you help?  thanks pb</p>

Reported by: Perr************ (blac******************)  (obscured for privacy))
Submitted From:  <a href="http://www.wormbase.org//resources/info_dump/">/resources/info_dump/</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

**Comment by tharris** [comment]
Hi Perry - 

You’ve followed a link that we haven’t supported in over three years or so.

You might wish to try our replacement data mining tool, WormMine:

http://www.wormbase.org/tools/wormmine

WormMine is a little dated at the moment but we will be launching an updated version in a few weeks.

Todd

**Comment by dasmoth** [comment]
Note that there's currently a link to /resources/info_dump/ on the FAQ page, which should probably be removed:

        https://www.wormbase.org/about/Frequently_asked_questions#1d36be8ac254907--10

Also (maybe obsolete, but still very much showing up in searches):

        http://wiki.wormbase.org/index.php/FAQs
        http://www.its.caltech.edu/~wormbase/userguide/FAQ/
