### ISSUE TITLE
  Hi! Is there a way to get the exact s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4052]
<p>&nbsp;&nbsp;Hi!<br/>Is there a way to get the exact sequence of specific RNAseq introns and variants from wormbase? Clicking on them doesn't seem to do anything useful.<br/>Thanks!<br/>Ron Ellis (ellisre@rowan.edu)</p>

Reported by: elli*************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10

**Comment by epaule** [comment]
I think the best way (especially since the number of RNASeq introns is quite high), is to approach it computationally and use the ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/c_elegans.PRJNA13758.WS248.annotations.gff3.gz as input for whatever analysis you would want to do.
