### ISSUE TITLE
  Just a comment: When choosing a mutan...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4055]
<p>&nbsp;&nbsp;Just a comment: When choosing a mutant for a gene, in case of having many options, I have heard from some people of choosing a consensus allele, usually a large deletion. I know that this is optional for every researcher but is a practical way to choose an agreed knockout if you do not need a specific mutation. Maybe it is already there and I missed it, but it would be nice to have a mark in those consensus mutant alleles, which would be the one most used in exintent literature. Also, since nowadays we have so many different mutants for each gene, it would be really nice to order them by relevance. Right now, I think that the most useful ones (knockouts) are at the end of the list...<br/>Cheers!<br/>Paola</p>

Reported by: p j (paol*******************)  (obscured for privacy))
Submitted From: unc-103 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00006830#0d4-9e6b817fac-10">/species/c_elegans/gene/WBGene00006830#0d4-9e6b817fac-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by chris-grove** [comment]
Hi Paola,

 Thank you for the feedback. We are now reviewing the allele display and are working towards separating the Million Mutation project alleles from the others to help distinguish between these two classes of alleles.

We currently display a reference allele, if available, for a gene at the top of the "Genetics" widget of a gene page. See the daf-2 gene page for an example:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0-4-10

In the meantime, while we sort out a new display method, you can filter the contents of the Alleles table by typing match criteria in the upper right search box. For example, typing "deletion", will filter down to alleles designated with the "Deletion" molecular change.

Hope that helps.

Best,

Chris Grove
