### ISSUE TITLE
  There is some confusion in Wormbase w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4058]
<p>&nbsp;&nbsp;There is some confusion in Wormbase with respect to the gene term "hip-1". There is hip-1/T12D8.8 which encodes an Hsp-70 interacting protein. However, in the Overview for this gene, under "Also refers to", it says "hip-1 has also been used to refer to: hipr-1" with a link to the page for hipr-1/ZK370.3, which is a completely different, unrelated gene and protein. The relationship/non-relationship between these two genes should be clarified. Thank you. </p>

Reported by: Jim ********* (jlis**************)  (obscured for privacy))
Submitted From: hip-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00011735#0d3ebc-981f-5-c">/species/c_elegans/gene/WBGene00011735#0d3ebc-981f-5-c</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36

**Comment by tuli** [comment]
Dear Jim,

Thank you for writing to WormBase.

It is never easy to deal with curatorial anomalies in a way which
doesn't cause more confusion. When a gene name has been incorrectly
published we need to find a way to enable users to find their way to
the correct gene.

The correct hip-1 gene is T12D8.8

Haycraft CJ et al. (2003) Exp Cell Res "Identification of CHE-13, a
novel intraflagellar transport protein required ...." also refers to
hip-1, but as ZK370.3 NOT T12D8.8 ie incorrect.

Users reading the Haycraft paper and then querying WormBase for hip-1
will be taken to the correct hip-1 page, in which they will see the
remark stating that  the hip-1 referred to in the Haycraft paper is
not correct. They can then be guided to hipr-1, which the actual gene
described in the Haycraft paper.

Users may also arrive at hipr-1 or hip-1 via the Haycraft publications
or other data types, and so we need to be a comprehensive as possible.

I have tried to explain the situation in both genes, but if you think
we can make it more clear please can you let me know.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Jim,

There is a curatorial remark within the Overview of the hip-1 page
which states "This publication refers to ZK370.3 as hip-1. hip-1 is
T12D8.8. ZK370.3 is hipr-1" with the Haycraft paper as evidence.

The exact same curatorial remark is attached to the hipr-1 page.

We try to keep remarks as concise as we can, and point users to
relevant publications rather than go into lengthy explanations on the
website. We also need to be mindful of the fact that the authors of
the correct and original hip-1 gene may not be too happy about
extensive reference to a completely unrelated paper.

I believe our curatorial remark gives enough information for users to
understand why hipr-1 is an other name of hip-1.

Best wishes,

Mary Ann



On 21 July 2015 at 14:27, Jim Lissemore <jlissemore@jcu.edu> wrote:
> Thanks for your quick reply, Mary Ann. Perhaps there could be a notation on
> the hip-1 and hipr-1 pages noting that there are two genes that have been
> called hip-1 at various points and that these are completely different genes
> that are not related by sequence similarity or function?
>
> --Jim
>
> Jim Lissemore
> Professor of Biology
> Biology Department
> Dolan W241
> John Carroll University
> 1 John Carroll Blvd.
> University Heights, OH 44118
> jlissemore@jcu.edu
> PHONE: 216-397-4196
> FAX: 216-397-4482
>
> On Tue, Jul 21, 2015 at 3:05 AM, Mary Ann Tuli <maryann.tuli@wormbase.org>
> wrote:
>>
>> Dear Jim,
>>
>> Thank you for writing to WormBase.
>>
>> It is never easy to deal with curatorial anomalies in a way which
>> doesn't cause more confusion. When a gene name has been incorrectly
>> published we need to find a way to enable users to find their way to
>> the correct gene.
>>
>> The correct hip-1 gene is T12D8.8
>>
>> Haycraft CJ et al. (2003) Exp Cell Res "Identification of CHE-13, a
>> novel intraflagellar transport protein required ...." also refers to
>> hip-1, but as ZK370.3 NOT T12D8.8 ie incorrect.
>>
>> Users reading the Haycraft paper and then querying WormBase for hip-1
>> will be taken to the correct hip-1 page, in which they will see the
>> remark stating that  the hip-1 referred to in the Haycraft paper is
>> not correct. They can then be guided to hipr-1, which the actual gene
>> described in the Haycraft paper.
>>
>> Users may also arrive at hipr-1 or hip-1 via the Haycraft publications
>> or other data types, and so we need to be a comprehensive as possible.
>>
>> I have tried to explain the situation in both genes, but if you think
>> we can make it more clear please can you let me know.
>>
>> Best wishes,
>>
>> Mary Ann
>>
>>
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>>
>> On 20 July 2015 at 21:10,  <no-reply@wormbase.org> wrote:
>> > Content Correction
>> >
>> >   There is some confusion in Wormbase with respect to the gene term
>> > "hip-1".
>> > There is hip-1/T12D8.8 which encodes an Hsp-70 interacting protein.
>> > However,
>> > in the Overview for this gene, under "Also refers to", it says "hip-1
>> > has
>> > also been used to refer to: hipr-1" with a link to the page for
>> > hipr-1/ZK370.3, which is a completely different, unrelated gene and
>> > protein.
>> > The relationship/non-relationship between these two genes should be
>> > clarified. Thank you.
>> >
>> > Submitted From:
>> >   hip-1 (gene) /species/c_elegans/gene/WBGene00011735#0d3ebc-981f-5-c
>> >
>> > This issue has been assigned ticket number: #4058. Follow progress on
>> > our
>> > issue tracker.
>> >
>> > Reported by: Jim Lissemore (jlissemore@jcu.edu)
>> > 20 Jul 15 20:11
>> >
>> > Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like
>> > Gecko)
>> > Chrome/43.0.2357.134 Safari/537.36
>> >
>> > This question was reported via the web interface at wormbase.org. You
>> > can
>> > also email us directly.
>> >
>> > --
>> > --
>> > You received this message because you are subscribed to the "WormBase:
>> > help"
>> > group.
>> > To post to this group, send email to help@wormbase.org
>> > To unsubscribe from this group, send email to
>> > help+unsubscribe@wormbase.org
>> > For more options, visit this group at
>> > http://groups.google.com/a/wormbase.org/group/help?hl=en
>> >
>
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by Paul-Davis** [comment]
I'm guessing this can be closed? please reopen if there is still work to do on this.
