### ISSUE TITLE
  Is it possible that the genetic map (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4060]
<p>&nbsp;&nbsp;Is it possible that the genetic map (Under Tools/More Tools) is not accessible anymore?<br/>Thank you!<br/>Sarah</p>

Reported by: Sara* (s.of**********************)  (obscured for privacy))
Submitted From: ttr-33 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00016505#0-9f-3">/species/c_elegans/gene/WBGene00016505#0-9f-3</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by tuli** [comment]
Dear Sarah,

Thank you for writing to WormBase and bringing this problem to our
attention. The Genetic Map should indeed be available.

Until the problem has been fixed you may use the version available on
our development server: http://staging.wormbase.org/tools/gmap

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Note to @sibyl229  I'm getting a 502 Bad Gateway error on http://www.wormbase.org/tools/gmap

Staging is fine.

**Comment by sibyl229** [comment]
Hi @tuli I think Todd has fixed the bad gateway error on genetic map http://www.wormbase.org/tools/gmap

**Comment by tuli** [comment]
Dear Sarah,

Further to my message on the 21st July, I am writing to let you know
that the genetic map on the main web site is now available again.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Thanks @sibyl229 & @tharris
