### ISSUE TITLE
  how can I check the RAD-54 gene？ how ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4063]
<p>&nbsp;&nbsp;how can I check the RAD-54 gene？ how many ways can I use for checking the gene？the last question is how can I know which gene translate response protein？</p>

Reported by: YUJI****** (zhou**************)  (obscured for privacy))
Submitted From: rad-54 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00004298#0-9f-3">/species/c_elegans/gene/WBGene00004298#0-9f-3</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by epaule** [comment]
waiting for user response

**Comment by epaule** [comment]
Thank you for your information.I will read more reference about this field.so thank you for your message.
