### ISSUE TITLE
Wiki server is down

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#4064]
All wiki.wormbase.org URLs are currently giving me a "502 Bad Gateway" error.

**Comment by dasmoth** [comment]
Also affecting blog.wormbase.org as well.

**Comment by epaule** [comment]
from Dave: seems like the forum is affected too:
=============
Hoping that you can fix the Forum soon?  Look like a hardware failure.

**Comment by tharris** [comment]
Not a hardware failure at all actually.
