### ISSUE TITLE
  Bm4517 CDS looks frame-shifted and re...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4066]
<p>&nbsp;&nbsp;Bm4517 CDS looks frame-shifted and real start site seems to be several positions downstream relative to current definition.</p>

Reported by: Isab********* (isab*************************)  (obscured for privacy))
Submitted From: Bm4517 (cds) <a href="http://www.wormbase.org//species/b_malayi/cds/Bm4517#05--10">/species/b_malayi/cds/Bm4517#05--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by epaule** [comment]
the underlying scaffold 255 is a bit dodgy therefore you can't see the more likely N-terminus in the missing upstream bit (it is in the v3 assembly on scaffold 5166 and basically Bm13317 is part of it).
I put a picture below to explain my point, and hopefully resolve that issue in a future release on the new assembly.

![image](https://cloud.githubusercontent.com/assets/20523/8871106/ca4e143e-31ea-11e5-91f4-d08b5696c695.png)

**Comment by epaule** [comment]
fixed in WS252
