### ISSUE TITLE
  the sequence given on the website is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4067]
<p>&nbsp;&nbsp;the sequence given on the website is different from the current CDS transcripts fasta file on the FTP server:<br/>>Bm7394 gene=WBGene00227655<br/>gagaagttaacagtgtttttattctcattttatccaatcgtatgtgcaaa<br/>atttggactttatttatcaagtttgaataatatgtctccgaatttcttcc<br/>gagaaatttctcgggtgttattctcgaacgaaggtgcactgattgatgtt<br/>tcaataccagtgatcgttgttggtgatattcatggacaggtatacgtgga<br/>tttgcaacggatttttgcggcggttggccggccaggtcgaacacgctttc<br/>tgtttcttggtgattatgtcgatcgtggaccgcagtctcttgaatgtata<br/>tgttcacttgtcgcttggaaaatcgcatatccgaaaagaatatttttact<br/>tcgtggcaatcatgaatttgcctctgtgaatcgagaatacggcttttatg<br/>atgaattagctgcaagatttagcgttggtaagtattgccttaaattcaac<br/>gatctattttcaattttccccttttccgctttaataaaaaatagaatact<br/>ctgcatgcacggtggtctcagcccacatctcgagtcgctgaacgatattc<br/>gcaatataaaaatgcctgtaatggaggtgttcccagatacattagaacag<br/>gatttagtttggtcggatccgaaattagacatcaaaggttacgaacctaa<br/>caaattgcgtaatgtgagcgtggcatttggtgaggatattgtctataaaa<br/>catgcaagcgcttaaacttggatcttattatacgggcacatcaggtgatg<br/>gaaaatgggtatggattttttgctggtcgtaaactagttacaattttctc<br/>agcaccgttatatgcagaactggtaagtttcattacgtga</p>

Reported by: Isab********* (isab*************************)  (obscured for privacy))
Submitted From: Bm7394 (cds) <a href="http://www.wormbase.org//species/b_malayi/cds/Bm7394#05--10">/species/b_malayi/cds/Bm7394#05--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by epaule** [comment]
ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release
still points to WS247 instead of WS248 which would be the current production release.

**Comment by epaule** [comment]
the download widgets are therefore also pointing to the wrong release files

**Comment by khowe** [comment]
@epaule , can you give an example of a Download widget linking to out-of-date data? All the ones I have found link to files in the file-type organised side (pub/wormbase/species) rather than the release-organised side (pub/wormbase/releases). And that seems to be up-to-date. 

@todd, do you mirror the whole of wormbase/releases as-as from Hinxton? If so, we can take over the maintenance of those symlinks.

**Comment by chris-grove** [comment]
@epaule @khowe Have either of you (or anyone) responded to the original e-mail on this? If not could you?

@tharris looks like @khowe was asking about mirroring FTP from Hinxton

**Comment by epaule** [comment]
I did reply to her in early July @chris-grove .
@tharris also updated the symlink for WS248 and it seemed to automatically update for WS249.
But the discussion about syncing symlinks is still ongoing.

**Comment by tharris** [comment]
The symlinks are updated in sync with the staging and production releases. Since we also create some files at OICR, I think it makes more sense to keep this tied to the OICR workflow.

**Comment by chris-grove** [comment]
@epaule @tharris  OK I'll leave it to one of you to close when appropriate.

**Comment by epaule** [comment]
I think we can close close it for now
