### ISSUE TITLE
  Use WormMine to create a list searchi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4068]
<p>&nbsp;&nbsp;Use WormMine to create a list searching "all" criteria to output WormBase IDs or cosmid/sequence names?  My input list is from an Affymetrix array, and about 400 of their "identifiers" (e.g. AF151645.1) will identify a specific sequence in WormBase when I search "All" but not under criteria on the menu found in WormMine.</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to complete the WormBase IDs for a C elegans Affymetrix array output.</p>

Reported by: bret******** (bk74***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by epaule** [comment]
I think if you use the query builder, then pick the genes as things to query.
The fields you want to pick are "WormBase Gene ID" and "Sequence Name" and if you want, you can put a contraint on the name of the species for "Caenorhabditis elegans".

I can send you the XML query file, if you want.

**Comment by chris-grove** [comment]
Hi Brett,

 Yes, I see the problem. We don't have very good mappings between these
types of Affymetrix identifiers and WormBase genes. Maybe you could send
the list of identifiers and we could take a look?

Best,

Chris Grove
