### ISSUE TITLE
  Hi,  I would like to know whether any...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4071]
<p>&nbsp;&nbsp;Hi, <br/>I would like to know whether anyone has found out specific ligands for guanylyl cyclase receptors.. I am interested in finding new ligands through insilico approach. If inislico results come out good, then I will try practical approach. please help me out here. <br/>Thank You</p>

Reported by: Bila* (bila*******************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36

**Comment by chris-grove** [comment]
Hello Bilal,

 The guanylyl cyclase receptors are represented in WormBase by the gcy gene class:

http://www.wormbase.org/resources/gene_class/gcy#012--10

There are currently 32 genes in C. elegans that belong to the class. Although we don't explicitly capture associated ligands (very little is known, I believe), you can look at each respective gene page for clues in the Phenotypes and Interactions widgets, e.g.:

http://www.wormbase.org/species/c_elegans/gene/WBGene00001528#08-b-3

gcy-1, for example, has a deletion mutant (tm2669) that has been associated to a "potassium chemotaxis defective" phenotype.

Best,

Chris Grove
