### ISSUE TITLE
  How can I screen a list of genes with...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4072]
<p>&nbsp;&nbsp;How can I screen a list of genes with a defined phenotype after RNAi in WormBase? i.e. "embryonic lethality". Thank you.</p>

Reported by: sunk************  (obscured for privacy)
Submitted From: home <a href="http://www.wormbase.org//#014-23-6">/#014-23-6</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by chris-grove** [comment]
Hello,

If you visit our FTP site:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/ONTOLOGY/

You can find several flat files with compiled information for a given release. Specifically, the "rnai_phenotypes.WS248.wb" file is a tab delimited file with all gene-to-RNAi-phenotype connections. Importing into Excel and using filtering gives a list of genes with an embryonic lethal RNAi phenotype (attached).

Hope that helps,

Chris Grove
