### ISSUE TITLE
  How do I download the C elegans Prote...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4073]
<p>&nbsp;&nbsp;How do I download the C elegans Proteome in FASTA format? I do have access to uniprot reference proteome and just wondered if wormbase has better organized FASTA proteome sequence.<br/>Best Regards,<br/>Ajay</p><p>What were you doing? <br />&nbsp;&nbsp;I am anlyzing an IP experiment done on a C elegans protein to identify the associated protein complexes.</p>

Reported by: Ajay********* (ajay**********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36

**Comment by raymond91125** [comment]
Hi Ajay,

Here 
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS249/species/c_elegans/PRJNA13758/>, 
you can find the file "c_elegans.PRJNA13758.WS249.protein.fa.gz".

Raymond
