### ISSUE TITLE
  Hi, I am in the process of submitting...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4074]
<p>&nbsp;&nbsp;Hi,<br/>I am in the process of submitting the newly sequenced genome of a rhabditid nematode to NCBI.<br/>We would like, if possible, to make it available as well on Wormbase.<br/>What would be the requirements?<br/>In particular, should the protein names follow a particular nomenclature?<br/>Thanks!<br/>Helene Fradin</p>

Reported by: Hele********\* (hf47*********)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by epaule** [comment]
I do not think we enforce any specific nomenclature for worms we do not actively curate.
Personally, I think IDs should be used in a way to uniquely identify things, but it is not a popular position in BioInformatics.

If you have a bioproject and a Genome Accession number, that would be good. And I do recommend getting the geneset through the GenBank/ENA submission process first, before sending it to us, as quite often changes need to be made to get them submitted, and then we have to redo everything here.

... oh, and I am supposed to ask you if it is a parasitic nematode or  a freeliving one.

**Comment by chris-grove** [comment]
@epaule  Has there been any follow up on this?

**Comment by epaule** [comment]
I will check with her @chris-grove
