### ISSUE TITLE
  . . . run a query for a reported phen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4075]
<p>&nbsp;&nbsp;. . . run a query for a reported phenotype? For example, what gene knockdowns result in larval arrest?<br/>I had query instructions to do this through Tools/Queries, but it doesn't seem to work now. <br/>Thanks for the help!</p>

Reported by: Aile********* (asew****************)  (obscured for privacy))
Submitted From: select a from a in class gene where a->RNAi_result->phenotype = "WBPhenotype:0000081"   - search <a href="http://www.wormbase.org//tools/queries/run">/tools/queries/run</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by raymond91125** [comment]
Hi,

You can use the phenotype ontology browser. e.g. on the page for "L1 
arrest" 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000081#03--10>. 
In the Ontology Browser widget, to the right of the focus term (green 
color), there are two numbers and a hyperlink leads to a page of lists 
of genes whose RNAi or mutant phenotype is L1 arrest via direct 
annotation or by inference (annotation to a sub-type of L1 arrest).

Raymond
