### ISSUE TITLE
  I was trying to download all genes wi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4076]
<p>&nbsp;&nbsp;I was trying to download all genes with a specific phenotype, such as lethal, using WormMine. However, WormMine only provides me with phenotypes supported by Allelles, not included RNAi evidence. I wonder how I can get RNAi as well.<br/>Also, I was looking for the information about phenotype from ftp://ftp.wormbase.org/. I did not find any file related. <br/>Could you please let me know where I can find these information?<br/>Thanks.<br/>Joyce</p>

Reported by: Joyc* (qzha***************)  (obscured for privacy))
Submitted From: Nomenclature <a href="http://www.wormbase.org//about/userguide/nomenclature#1k5gb92e0dlfh347cj8a6i--10">/about/userguide/nomenclature#1k5gb92e0dlfh347cj8a6i--10</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36

**Comment by raymond91125** [comment]
Hi,

You can use the phenotype ontology browser. e.g. on the page for "L1 
arrest" 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000081#03--10>. 
In the Ontology Browser widget, to the right of the focus term (green 
color), there are two numbers and a hyperlink leads to a page of lists 
of genes whose RNAi or mutant phenotype is L1 arrest via direct 
annotation or by inference (annotation to a sub-type of L1 arrest).

On FTP, you'd probably find the file "phenotype_association.WS248.wb" 
useful <ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/ONTOLOGY/>.

Raymond
