### ISSUE TITLE
  How do I find the number of protein-c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4078]
<p>&nbsp;&nbsp;How do I find the number of protein-coding genes located on each of the chromosomes for C elegans?   I found the information for the WS133 build at http://www.wormbook.org/chapters/www_overviewgenestructure/overviewgenestructure.html<br/>I was wondering if I can find this info for any newer builds?  <br/>Thanks in advance for your help!</p>

Reported by: Mary (kroe************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by epaule** [comment]
we don't have the numbers precalculated, but there are quite a few ways who you can find them out:
a.) you can query WormMine for genes that are on a particular chromosome
b.) you can download the annotation as GFF file and use grep to count the genes for each chromosome
c.) you can use external data mining tools like biomart to query in a similar way to WormMine
... and i am sure there are more.

**Comment by Paul-Davis** [comment]
Dear Mary,

Just to add to what my colleague said, the gff method should give you 
the following results when parsing the data from the C. elegans gff 
files available here:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/c_elegans.PRJNA13758.WS249.annotations.gff3.gz

Lines of this type:
IV      WormBase        gene    520210  523757  .       - . 
ID=Gene:WBGene00000213;Name=WBGene00000213;locus=asm-3;sequence_name=W03G1.7;biotype=protein_coding;Alias=asm-3,W03G1.7
IV      WormBase        gene    524654  526479  .       + . 
ID=Gene:WBGene00021010;Name=WBGene00021010;interpolated_map_position=-25.8479;sequence_name=W03G1.2;biotype=protein_coding;Alias=W03G1.2

WS249 Counts of protein coding genes:

I - 2891
II - 3527
III - 2678
IV - 3313
V - 5146
X - 2811
MTCE - 12

Thanks

Paul







On 02/08/2015 23:45, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I find the number of protein-coding genes located on each of 
> the chromosomes for C elegans? I found the information for the WS133 
> build at 
> http://www.wormbook.org/chapters/www_overviewgenestructure/overviewgenestructure.html
> I was wondering if I can find this info for any newer builds?
> Thanks in advance for your help!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4078. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4078>.
>
> Reported by: Mary (kroet006@umn.edu)
> 02 Aug 15 22:47
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:39.0) Gecko/20100101 
> Firefox/39.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Thank you Paul and Michael for your help!!

I greatly appreciate it!

Mary

Mary B. Kroetz, Ph.D
Zarkower Laboratory
Department of Genetics, Cell Biology & Development
University of Minnesota
5-143 Moos Tower
515 Delaware St SE
Minneapolis MN 55455
612-626-4259 (lab)
