### ISSUE TITLE
  Hello, i'm looking at the page for pr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4079]
<p>&nbsp;&nbsp;Hello,<br/>i'm looking at the page for protein CBD-1 in C.elegans, http://www.wormbase.org/species/c_elegans/protein/WP:CE37527#06--10, it shows Pfam domains but it doesn't say what they are - it would be nice if it said what are the domains, or you could mouse over and see the domain name. Just an idea, otherwise the page is very nice!<br/>Regards,<br/>Avril</p>

Reported by: Avri*************** (alc@************)  (obscured for privacy))
Submitted From: CBD-1 (protein) <a href="http://www.wormbase.org//species/c_elegans/protein/WP:CE37527#06--10">/species/c_elegans/protein/WP:CE37527#06--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by khowe** [comment]
Replied:
Hi Avril,
If you open up the "Motif details" panel, it has a table with the details of all of the domains. But I agree that it would be better if the basic domain details were visible (by some means) on the image itself.

**Comment by khowe** [comment]
User happy (see below). This might require some development, created a new ticket for that (#4080)

---------
Thanks for this!

That wasn't obvious to me, perhaps it would be good to put a sentence there saying to look at the 'Motif details' link for domain identities?

Regards,

Avril
