### ISSUE TITLE
  I was asked by my mentor to find out ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4082]
<p>&nbsp;&nbsp;I was asked by my mentor to find out what causes the rap-1 and rab-30 mutations in c. elegans and I honestly can't figure your website out to find these things! I also need to find which chromosomes these genes are located on. Any help?? I'm lost!</p>

Reported by: laur** (lwhi***************)  (obscured for privacy))
Submitted From: rab-30 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00004282#01-9f3876b4-3">/species/c_elegans/gene/WBGene00004282#01-9f3876b4-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by chris-grove** [comment]
Hi Lauren,

 I'm not sure what you mean by "what causes the mutations"; are you asking what mutagens were used to induce mutations in these genes in the laboratory? In any case, you'll probably want to look at the "Location" widget (for chromosomes), "Genetics" widget for a list of alleles/mutations, and the "Phenotypes" widget if you're looking for phenotypes, for each gene:

http://www.wormbase.org/species/c_elegans/gene/WBGene00004282#09-b4-3
http://www.wormbase.org/species/c_elegans/gene/WBGene00004307#09-b4-3

Let us know if you need more help.


Best,

Chris Grove
