### ISSUE TITLE
  Is there a way to pull pseudogenes ou...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4083]
<p>&nbsp;&nbsp;Is there a way to pull pseudogenes out of WormMine?</p>

Reported by: Virg********* (vsla***********)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by chris-grove** [comment]
Hi Virginia,

 WormMine doesn't currently support querying genes on the basis of pseudogene status. I've generated a list of pseudogenes in the WS249 release of WormBase (attached).

Let us know if you need anything else.

Best,

Chris Grove
