### ISSUE TITLE
  Hi, I have moved my laboratory (code ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4084]
<p>&nbsp;&nbsp;Hi,<br/>I have moved my laboratory (code AHS) to another department but still within Uppsala University. I updated my person information but don't know how to update the lab info? My new lab info should be:<br/>Dept. of Cell and Molecular Biology, Uppsala University, Box 596, 751 24 Uppsala, Sweden.<br/>Thank you in advance!<br/>Best regards,<br/>Andrea</p>

Reported by: Andr******** (andr******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:16.0) Gecko/20100101 Firefox/16.0

**Comment by tuli** [comment]
Dear Andrea,

Thank you for writing to WormBase. I have updated the AHS record as
requested and it will be available in release WS251 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Andrea:

In your Person update form, the Department data was:

'Department of Cell and Molecular Biology, Microbiology'.

Should it be 'Dept. of Cell and Molecular Biology' as per this email?
Please confirm.

Thanks,
Have a great day!
Cecilia

Cecilia Nakamura
WormBase
California Institute of Technology
Division of Biology 156-29
Pasadena, CA 91125 USA
(626)395 2688
cecilia@tazendra.caltech.edu
