### ISSUE TITLE
  I have a question about sequencing de...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4085]
<p>&nbsp;&nbsp;I have a question about sequencing details - I did not know which type of question to choose that i why I have chosen content. How many C. elegans individuals are being used to determine the genome sequence? Which strains are being used? How many assemblies of C.elegans are available (I mean if there only is a consensus assembly, or from different individuals, different strains)? Thank You very much for Your response.   </p>

Reported by: kaja*********** (kmil**********************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by epaule** [comment]
have a look at http://www.sciencemag.org/content/282/5396/2012.full , which is the sequencing paper published a while ago in Science. It describes the sequencing and assembly process quite well. http://www.wormbook.org/ is also a good resource for information on C.elegans.

Basically, the assembly was done from cosmid and YAC libraries, which are parts of sequence cloned into bacterias and yeast respectively. The origin of the genomic DNA used for cloning was the inbred reference strain that everybody uses : N2

As you can read on wormbook, etc., hermaphroditic C.elegans is perfect for inbreeding, as you can self them and  with their fast reproductive cycle, produce a population of worms with identical genomes. So the problem with individual specific differences does not apply for inbred lab strains.

The number of available assemblies, you can easily find by following the species on the dropdown menu. When you clock on it's name, there should be a page showing available assemblies.
