### ISSUE TITLE
  Hello, For the last few days I notice...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4088]
<p>&nbsp;&nbsp;Hello,<br/>For the last few days I noticed that the "genetic map" option under the gene page is not working.<br/>It says "sorry an error has occurred" and "bad gateway"<br/>I tried a different browser and different computer and I haven't changed anything in the browser.<br/>I'm a Mac user, but I also tried PC, it is the same.<br/>Can you please help?<br/>Thanks,<br/>Sarit</p>

Reported by: Sari*********** (sari*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by tuli** [comment]
Dear Sarit,

Thank you for writing to WormBase. I am sorry you are experiencing
problems with the genetic map. There does indeed seem to be a problem
which our webteam will look into. Meanwhile you may access the genetic
map on our development site (which may not be stable at all times) at:
http://staging.wormbase.org

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tharris** [comment]
Resolved.

**Comment by tuli** [comment]
Dear Sarit,

Further to my message last week, I can now confirm that the genetic
map has been fixed on the main WormBase site, so you should use that
for further work.

Thank you,

Mary Ann

On 7 August 2015 at 11:32, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
> Dear Sarit,
>
> Thank you for writing to WormBase. I am sorry you are experiencing
> problems with the genetic map. There does indeed seem to be a problem
> which our webteam will look into. Meanwhile you may access the genetic
> map on our development site (which may not be stable at all times) at:
> http://staging.wormbase.org
>
> Best wishes,
>
> Mary Ann
>
>
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>
> On 6 August 2015 at 00:04,  <no-reply@wormbase.org> wrote:
>> Bug Report
>>
>>   Hello,
>> For the last few days I noticed that the "genetic map" option under the gene
>> page is not working.
>> It says "sorry an error has occurred" and "bad gateway"
>> I tried a different browser and different computer and I haven't changed
>> anything in the browser.
>> I'm a Mac user, but I also tried PC, it is the same.
>> Can you please help?
>> Thanks,
>> Sarit
>>
>> Submitted From:
>>   support /tools/support
>>
>> This issue has been assigned ticket number: #4088. Follow progress on our
>> issue tracker.
>>
>> Reported by: Sarit Smolikove (sarit-smolikove@uiowa.edu)
>> 05 Aug 15 23:07
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML,
>> like Gecko) Chrome/44.0.2403.125 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
