### ISSUE TITLE
  Hi, my name is Vahid, and working wit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4089]
<p>&nbsp;&nbsp;Hi, my name is Vahid, and working with the OpenWorm community. I want to be able to have access to data related to ion channel genes and proteins via some "Python" code. <br/>Currently, the REST APIs for accessing protein data is not working (as described here: https://www.wormbase.org/about/userguide/for_developers/API-REST/Protein#0--10)<br/>What is the preferred method for accessing data via some Python script?</p>

Reported by: Vahi* (vahi*******************)  (obscured for privacy))
Submitted From: For developers <a href="http://www.wormbase.org//about/userguide/for_developers#124053--10">/about/userguide/for_developers#124053--10</a>

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by sibyl229** [comment]
This ticket has been addressed. Closing.

>Sorry, the documentation may be a little bit out of date. 
>It’s a REST api — it’s language agnostic. You can use Perl, Python, or whatever language you choose.
>If you’re having problems with some of the endpoints, look at protein pages of interest using the developer console of your browser.  You will see the REST calls that our application makes to populate specific pages.

>Best,
>Todd


>
>Unfortunately I’m not aware of anything like that. Generally the two options to get data from wormbase are: the RESTful API and the ftp site, where you download the data and parse them yourself.

>Good luck!

>Sibyl
