### ISSUE TITLE
  Hello!  I have a long list of primer ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4090]
<p>&nbsp;&nbsp;Hello!  I have a long list of primer pairs and I would like match the primer pairs to the specific gene they target in WS238.  The primer pairs were the ones used to create the Ahringer RNAi library.  I find that I can query them one by one in the search box, but I didn't know if I can do a batch query where I can input the whole list at once and get the corresponding target genes for the entire list.  Would you happen to know if that is something that I can do?  Thanks!  -Cristina </p>

Reported by: Cris***************** (c.ag*******************)  (obscured for privacy))
Submitted From: Frequently asked questions <a href="http://www.wormbase.org//about/Frequently_asked_questions#7cab6e021d34958--10">/about/Frequently_asked_questions#7cab6e021d34958--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

**Comment by chris-grove** [comment]
Hi Cristina,

 Apologies for the delay in response. I'd be happy to discuss with you what options we have available. Just to clarify: what format is your list in? Is each primer pair listed in the "sjj_*" format? If so, I can send you a Python script to pull out all genes that are mapped to each primer pair in your list based on the latest release of WormBase.

Best,

Chris Grove
