### ISSUE TITLE
  Hello, I'm using the wormmine page, a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4094]
<p>&nbsp;&nbsp;Hello, I'm using the wormmine page, and am looking at gene->phenotype results for all C. elegans genes. When I hover over some of the column headings, it says I can click on an 'x' symbol to delete the column from the display, but this doesn't seem to work for me?<br/>Regards,<br/>Avril</p>

Reported by: Avri*************** (alc@************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by WenChenWormBase** [comment]
Dear Avril:

I created an excel table listing RNAi and allele phenotype data for each gene from WS249. Feel free to download it if it is useful.

ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/RNAiAllelePheno_WS249.csv

Wen Chen, Ph.D.
Curator, WormBase

**Comment by chris-grove** [comment]
Duplicate of  #1945
