### ISSUE TITLE
  Hello dear wormbase. I just realized ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4095]
<p>&nbsp;&nbsp;Hello dear wormbase. I just realized that I had forgotten to point out the content I want to add to wormbase: Y111B2A.24 is sas-1 (sas-1 already exists on the wormbase, but is not linked to the gene). Also, there is a comment that Y111.. is an ortholog fo RPH3a. In my paper I make the argument that Y111... is actually an ortholog of C2CD3. Could my paper be linked to that entry? Thx, Lukas</p>

Reported by: Luka*********** (luka******************)  (obscured for privacy))
Submitted From: Y111B2A.24 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00013742#0-9ebc4f-10">/species/c_elegans/gene/WBGene00013742#0-9ebc4f-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by tuli** [comment]
Dear Lukas,

Thank you for writing to WormBase.

The Y111B2A.24 <-> sas-1 gene connection will need to be approved by
Tim Schedl (cc'ed here) before I can update WormBase.

We will have a look at the orthology to D. rerio C2CD3.

I will write back to you soon.

Best wishes,

Mary Ann

On 10 August 2015 at 12:09,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hello dear wormbase. I just realized that I had forgotten to point out the
> content I want to add to wormbase: Y111B2A.24 is sas-1 (sas-1 already exists
> on the wormbase, but is not linked to the gene). Also, there is a comment
> that Y111.. is an ortholog fo RPH3a. In my paper I make the argument that
> Y111... is actually an ortholog of C2CD3. Could my paper be linked to that
> entry? Thx, Lukas
>
> Submitted From:
>   Y111B2A.24 (gene) /species/c_elegans/gene/WBGene00013742#0-9ebc4f-10
>
> This issue has been assigned ticket number: #4095. Follow progress on our
> issue tracker.
>
> Reported by: Lukas von Tobel (lukas.vontobel@epfl.ch)
> 10 Aug 15 11:11
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/40.0.2214.115 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
