### ISSUE TITLE
  Using the old WormMart feature, it wa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4098]
<p>&nbsp;&nbsp;Using the old WormMart feature, it was very easy to take a list of genes and download sequence features (like e.g. 2000 nucleotides upstream of the transcription start site or whatnot). <br/>Is something like this possible with WormMine or other features of WormBase? I can get location information, but then it's more steps to turn those genome coordinates into raw sequence data... So I'm wondering if I'm missing something.<br/>Thanks much!</p>

Reported by: Zach********** (zpin*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by raymond91125** [comment]
Hi Zachary,

Have you tried using the BioMart at parasite.wormbase.org 
<http://parasite.wormbase.org/biomart/martview>? It has an interface 
much like the old WormMart that we are going to unplug soon due to the 
lack of updates.

Raymond
