### ISSUE TITLE
  The gene F53B1.6 has now been publish...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4099]
<p>&nbsp;&nbsp;The gene F53B1.6 has now been published in J. Neuroscience (Hardaway et al, 2015) with the approved name swip-10. You cannot obtain this name or search with it in Wormbase. The reference should also be linked.</p>

Reported by: Rand********* (rand************************)  (obscured for privacy))
Submitted From: F53B1.6 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00018738#0b4-9e16-10">/species/c_elegans/gene/WBGene00018738#0b4-9e16-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by timschedl** [comment]
The confidential swip-10 = F53B1.6 gene association was placed into the
WormBase public domain in mid-July and should appear in an upcoming release
of WormBase.

On Tue, Aug 11, 2015 at 6:40 PM, WormBase Helpdesk <notifications@github.com

**Comment by tuli** [comment]
Dear Randy,

Thank you for writing to WormBase. This gene connection was made in
WormBase in July and will be available in release WS250.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125



On Tue, Aug 11, 2015 at 6:40 PM, WormBase Helpdesk <notifications@github.com
> wrote:

> The gene F53B1.6 has now been published in J. Neuroscience (Hardaway et
> al, 2015) with the approved name swip-10. You cannot obtain this name or
> search with it in Wormbase. The reference should also be linked.
>
> Reported by: Rand********* (rand************************) (obscured for
> privacy))
> Submitted From: F53B1.6 (gene)
> /species/c_elegans/gene/WBGene00018738#0b4-9e16-10
> <
http://www.wormbase.org//species/c_elegans/gene/WBGene00018738#0b4-9e16-10>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12
> (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4099>.

>

—
Reply to this email directly or view it on GitHub
<https://github.com/WormBase/website/issues/4099#issuecomment-130140261>.
