### ISSUE TITLE
  Hello - could someone please look int...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4101]
<p>&nbsp;&nbsp;Hello - could someone please look into Million Mutation allele gk963311? Wormbase seems to think that it's a 17.4 MB deletion that apparently removes nearly all of chr X. This seems unlikely :)<br/>Thanks,<br/>Doug Portman<br/>douglas.portman@rochester.edu</p>

Reported by: Doug******** (doug******************)  (obscured for privacy))
Submitted From: gk963311 (variation) <a href="http://www.wormbase.org//species/c_elegans/variation/WBVar01498554#02-45-3">/species/c_elegans/variation/WBVar01498554#02-45-3</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by tuli** [comment]
Dear Doug,

Thank you for writing to WormBase.

The data is correct, but you are not the first person to query the
size of some of the Million Mutation variations.

We have recently added an explanation to the strains carrying these
large copy number variations but the update has not yet made it to the
website.

The remark associated with strain VC30127 states:

Remark "Million Mutation Project strain. This strain was isolated
after ENU mutagenesis of VC2010, propagated clonally through F10 to
drive mutations to homozygosity, and subjected to whole-genome
sequencing. It is homozygous for a large number of mutations
determined from sequence data. It may also carry large copy number
variations that are not homozygous. Alleles numbered between gk100000
and gk962522 are homozygous; those numbered from gk962523 up should be
assumed to be non-homozygous. A graphical representation of these
large copy number differences can be seen in the Plot section for each
strain on the MMP web site ( URL: genome.sfu.ca/mmp/)."
Inferred_automatically "From CGC strain data"

I hope this explains the nature of gk963311.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
