### ISSUE TITLE
  Hello, I had part of daf-22(m130) seq...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4102]
<p>&nbsp;&nbsp;Hello,<br/>I had part of daf-22(m130) sequenced and discovered that the nucleotide sequence provided by WormBase isn't completely correct.  WormBase claims there is a C to G nucleotide substitution, however, from the sequencing I got back it looks to be a C to T substitution.  This would still lead to a change from glycine to arginine in the amino acid sequence, I believe.<br/>I can send you the trace files I have for confirmation.  You can contact me at hannah.steinert@rochester.edu.<br/>Hannah</p><p>What were you doing? <br />&nbsp;&nbsp;I was making a daf-22; him-5 strain and to confirm they indeed were homozygous for daf-22(m130) I used PCR to amplify the part of the allele containing the substitution and sent it in for sequencing at Genewiz. In addition to sending in samples from my crosses, I also sent in multiple samples from daf-22(m130) and him-5 as controls.</p>

Reported by: Hann*********** (hann*****************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36

**Comment by tuli** [comment]
Dear Hannah,

Thank you for writing to WormBase and for sending us your findings.

I have updated the m130 record and you'll see the update in release
WS251 of WormBase.

I would like to add your name as evidence for this curation but see
that you do not have a WormBase PersonID.  I have cc'ed this email to
Cecilia, who is responsible for assigning PersonIDs in WormBase. Once
she has assigned you an ID I will update the record.

(Cecilia, Hannah is a member of the Portman lab - UR).

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Mary Ann:

I have created Hannah's WBPerson page/id.
Hannah Steinert = WBPerson30788

Cecilia

Cecilia Nakamura
WormBase
California Institute of Technology
Division of Biology 156-29
Pasadena, CA 91125 USA
(626)395 2688
cecilia@tazendra.caltech.edu
