### ISSUE TITLE
  Dear Wormbase, My name is Arturo Papa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4103]
<p>&nbsp;&nbsp;Dear Wormbase,<br/>My name is Arturo Papaluca, PhD candidate at Université de Montréal working with C. elegans. I am keen to look at the microarray data for certain genes of interest, however I am not able to pull the information out.<br/>Would you be kind to help me regarding this request?<br/>I deeply acknowledge your time and effort,<br/>Best regards,<br/>Arturo Papaluca.</p>

Reported by: Artu*********** (artu********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36

**Comment by WenChenWormBase** [comment]
Dear Arturo:

You can get all worm microarray data from our SPELL server:
http://spell.caltech.edu:3000/

The section "Dataset Listing"
<http://spell.caltech.edu:3000/search/dataset_listing> lists all datasets.
You may download all or just certain datasets.

Let me know if you have additional help.

Wen.


On Wed, Aug 12, 2015 at 5:32 PM, WormBase Helpdesk <notifications@github.com
> wrote:

>   Dear Wormbase,
> My name is Arturo Papaluca, PhD candidate at Université de Montréal
> working with C. elegans. I am keen to look at the microarray data for
> certain genes of interest, however I am not able to pull the information
> out.
> Would you be kind to help me regarding this request?
> I deeply acknowledge your time and effort,
> Best regards,
> Arturo Papaluca.
>
> Reported by: Artu*********** (artu********************) (obscured for
> privacy))
> Submitted From: support /tools/support
> <http://www.wormbase.org//tools/support>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/44.0.2403.155 Safari/537.36
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4103>.
>



-- 
Wen Chen, Ph.D.
Curator, WormBase
