### ISSUE TITLE
 Server Error: 500 at  rest/widget/all/all/assembl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4105]
<p>Server Error: 500 at <a href="https://www.wormbase.org/rest/widget/all/all/assemblies?download=1&amp;content-type=text%2Fhtml">rest/widget/all/all/assemblies</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "Can't locate object method "new" via package "WormBase::API::Object::All" (perhaps you forgot to load "WormBase::API::Object::All"?) at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API.pm line 326." </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to find where to download the B. malay genome. </p>

Reported by: alek**********************  (obscured for privacy)
Submitted From:  <a href="http://www.wormbase.org//rest/widget/all/all/assemblies">/rest/widget/all/all/assemblies</a>

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0

**Comment by sibyl229** [comment]
Hi,

Sorry, the REST API doesn’t support downloading of a whole genome. Does the FTP site have what you are looking for? ftp://ftp.wormbase.org/pub/wormbase/releases/current-development-release/species/b_malayi/PRJNA10729/ <ftp://ftp.wormbase.org/pub/wormbase/releases/current-development-release/species/b_malayi/PRJNA10729/> 

Thanks for the bug report!

Sibyl

**Comment by brucebolt** [comment]
Hi @sibyl229 

It seems the user may have ended up at this REST URL by going to https://www.wormbase.org/species/b_malayi#012--10 then clicking "Download" in the "Genome Assemblies" widget.  Presumably they expected to download the genome by clicking this.  Maybe a link to the FTP site in the "Current Assemblies" table could be useful?

Cheers

Bruce

**Comment by sibyl229** [comment]
Thanks Bruce! Ah that’s definitely a bug. I will fix that. 

Yeah it’s nice to have links to the FTP site from that table. I’m a bit confused where the directories are on the FTP site for the corresponding assembly. For example, the B_malayi-3.0 WS236-WS244, shall I link it to ftp://ftp.wormbase.org/pub/wormbase/releases/WS244/species/b_malayi/ <ftp://ftp.wormbase.org/pub/wormbase/releases/WS244/species/b_malayi/> ? As it’s the most recent release that uses the same assembly. Is that how to look at it?

Thank you.

Sibyl

**Comment by brucebolt** [comment]
The *.genomic.fa.gz file should be the identical for WS244 to WS248 (inclusive).  Therefore I would link to the current version (b_malayi.PRJNA10729.WS244.genomic.fa.gz).

Cheers

Bruce

**Comment by sibyl229** [comment]
Got it. Thank you Bruce!

Sibyl

**Comment by tharris** [comment]
We also create symlinks on the ftp site to the most current versions so it isn't necessary to update links for every new assembly.

**Comment by sibyl229** [comment]
The links to download genomes are working on species index page: http://staging.wormbase.org/species/b_malayi#012--10
Closing.
