### ISSUE TITLE
  Dear Colleagues:  I would like to dow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4111]
<p>&nbsp;&nbsp;Dear Colleagues:  I would like to download a short list of spliced mRNA sequences (say 200-300) that contain full UTR sequences.  The various links suggested by your FAQ page don't seem to work.  Any suggestions?  Ideally I would paste in a list of gene names.  Thanks! Perry Blackshear, NIEHS</p>

Reported by: Perr************ (blac******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

**Comment by raymond91125** [comment]
Hi Perry,

You may want to try our BioMart instance at 
<http://parasite.wormbase.org/biomart/martview>. The desired attribute 
is probably Sequences->cDNA.

Let us know if you have trouble.

Cheers,

Raymond
