### ISSUE TITLE
  Dear Support, this question is Wormmi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4113]
<p>&nbsp;&nbsp;Dear Support, this question is Wormmine related. Is it possible to get RNAi phenotypes for each gene, for all genes via Wormmine? <br/>I think so far I could only manage to get allele phenotypes...<br/>Best regards, <br/>Johnny<br/>graduate student in the lab or Nikolaus Rajewsky, Berlin. </p>

Reported by: jona************** (jona****************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by xdwang** [comment]
Hi Johnny,

We haven’t integrated RNAi phenotype data into WormMine yet.

My colleague Wen created an excel table listing RNAi and allele phenotype data for each gene from WS249. Feel free to download it if it is useful.
ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/RNAiAllelePheno_WS249.csv <ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/RNAiAllelePheno_WS249.csv>
Let us know if you need further help.

Thanks,

Xiaodong

Xiaodong Wang, Ph.D
Wormbase Curator
xdwang@caltech.edu
http://www.wormbase.org
California Institute of Technology
Division of Biology 156-29
Pasadena, CA 91125
USA
