### ISSUE TITLE
Between Wormbase CDS and Uniprot IDs

### ISSUE THREAD

**Issue by Gschindelman** [WormBase/website#4115]
Entering from help desk email 
Hi,

I'm a graduate student in the Clemons lab here at Caltech.

I am trying to retrieve the mRNA sequences for every membrane protein in the C. elegans genome together with the Uniprot sequence identifiers. Is there an intuitive way to do rather the mRNA sequences? 

I am able to gather Wormbase gene and protein ids from Uniprot's website and mapping service, but the CDS identifiers in Wormbase don't correspond in an obvious way to me.

I can identify membrane proteins given the mRNA sequences.

Thanks for the help,
Shyam

--
Shyam Saladi
Lab of William Clemons
California Institute of Technology

**Comment by Gschindelman** [comment]
email is "Shyam Saladi" <saladi@caltech.edu>

**Comment by epaule** [comment]
Hi Gary,

can you grab Shyam (i guess he is in walking distance from CalTech
WormBase) and show him how to do it in the ParaSite biomart?
There should be queriable GO-Terms in there for C.elegans, as well as
UniProt xrefs.
Maybe point out that the upcoming new version of WormMine should be also
usable for such queries.

M

**Comment by chris-grove** [comment]
Hi Shyam,

What format are your mRNA/CDS IDs in? 

You can use the WormBase ParaSite BioMart tool to convert mRNA/CDS IDs into UniProt IDs. The tool can be found on WormBase ParaSite:

http://parasite.wormbase.org/index.html

under the "BioMart" tool in the header:

http://parasite.wormbase.org/biomart/martview/eb6ef36a3472fecb70fa9bc71551cea7

Where are you located at Caltech? If you'd like, I can come over to your lab and show you how to use the tool to retrieve UniProt accession IDs using C. elegans CDS IDs as input.

Best,

Chris Grove
