### ISSUE TITLE
  Could you help me to explain what is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4116]
<p>&nbsp;&nbsp;Could you help me to explain what is the gray bar region before and after a gene annotation under "gene Location". I probably understand the 3'-gray region is UTR, how about the 5'-gray region? And, sometimes for one single gene isoform, ex acox-1b, it has several different 5'-gray region, what does that mean? Thanks for your help!</p>

Reported by: Xinx********* (xxzh******************)  (obscured for privacy))
Submitted From: acox-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00008564#04-9fd-10">/species/c_elegans/gene/WBGene00008564#04-9fd-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by xdwang** [comment]
Hi, 

If you mouse over the question mark icon on GBrowse for this gene, a popup window will explain all the colored area means.

I am attaching the screen shot here.


Please let us know if you have further question.

Xiaodong




> On Aug 19, 2015, at 10:21 AM, no-reply@wormbase.org wrote:
> 
> How Do I ...? 
>   Could you help me to explain what is the gray bar region before and after a gene annotation under "gene Location". I probably understand the 3'-gray region is UTR, how about the 5'-gray region? And, sometimes for one single gene isoform, ex acox-1b, it has several different 5'-gray region, what does that mean? Thanks for your help!
> 
> Submitted From: 
>   acox-1 (gene) /species/c_elegans/gene/WBGene00008564#04-9fd-10 <http://www.wormbase.org//species/c_elegans/gene/WBGene00008564#04-9fd-10>
> This issue has been assigned ticket number: #4116. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/4116>.
> 
> 
> Reported by: Xinxing Zhang (xxzhang0603@ad.ufl.edu <mailto:xxzhang0603@ad.ufl.edu>) 
> 19 Aug 15 14:23 
> 
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125
