### ISSUE TITLE
Genetic Map not available

### ISSUE THREAD

**Issue by tuli** [WormBase/website#4117]
Just that. Was not available this morning and still not available now. Bad gateway

**Comment by tharris** [comment]
This is a recurring problem related to trying to load big intervals (or entire chromosomes). It's fixed for now but may recur.

**Comment by tuli** [comment]
Both this and 4106 have been closed but I still cannot see the Tree Display

**Comment by tharris** [comment]
See my comment above.

**Comment by tuli** [comment]
OK, then maybe we should just remove it entirely. For me at least it seems to be unavailable about 80% of the time. It's not when I look at large intervals - just gene or variation summary pages usually.
