### ISSUE TITLE
  The phylogenetic tree is not shown. P...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4119]
<p>&nbsp;&nbsp;The phylogenetic tree is not shown.<br/>Please help. Thanks</p><p>What were you doing? <br />&nbsp;&nbsp;srb-13 tree searching</p>

Reported by: Hieu****** (hdho***********)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by chris-grove** [comment]
Hello Hieu,

 I'm not having any trouble viewing the phylogenetic tree for srb-13:

http://www.wormbase.org/species/c_elegans/gene/WBGene00019028#0-6-3

I've attached a screenshot. Can you let us know if you are still having trouble viewing the tree?

Thanks,

Chris Grove
