### ISSUE TITLE
WormMart Sunset Period

### ISSUE THREAD

**Issue by tharris** [WormBase/website#4120]
1. Add link to the ParaSite Biomart under the Tools Menu. Due: WS250.
2. Todd: Generate blog post explaining the imminent demise of WormMart (I think we are the last MOD actually offering Biomart anymore). Due 8/28.
3. At the end of WS250 remove the link to WormMart.

**Comment by sibyl229** [comment]
I added the menu link to ParaSite BioMart.

**Comment by raymond91125** [comment]
yeah.

**Comment by brucebolt** [comment]
Also, the image on the homepage (when not logged in) will need to be updated as it still references WormMart.
![screen shot 2015-10-12 at 14 40 50](https://cloud.githubusercontent.com/assets/6329861/10429299/6b85f2fc-70ef-11e5-966a-d556f33f020f.png)

**Comment by tharris** [comment]
@sibyl229 last two things for this are 

1. Remove the link to WormMart from the tools menu

2. Remove / replace the static image on the home page (let's discuss -- I think this should probably be a rotating lightbox or some other more useful feature)

**Comment by tuli** [comment]
I just accidentally clicked on WormMart from the tools menu and I get a big error. Should this link have been removed now?

**Comment by tharris** [comment]
Whoops! Yep, we will remove it.

**Comment by janelomax** [comment]
Looks like the link to WormMart is still there - we just got another ticket to the helpdesk. Can it be removed please? Cheers.

**Comment by brucebolt** [comment]
As mentioned earlier in this ticket, there is a large WormMart advert when you're not logged in.  Users will probably assume WormMart is still supported after seeing this.
![screen shot 2016-01-28 at 09 45 52](https://cloud.githubusercontent.com/assets/6329861/12640834/06bd77f0-c5a4-11e5-8ea4-7df336eea306.png)

**Comment by tharris** [comment]
@sibyl229 can you please remove the link as a hotfix? We will deal with the image later which I want to replace altogether. @raymond can you either redirect incoming requests for the dead WormMart to the blog post or put up some informative error message?

**Comment by raymond91125** [comment]
redirect to blog post done. the machine crashed with more than one hardware pieces failing. so wormmart is literally RIP.

**Comment by sibyl229** [comment]
Hi @tharris here's the hotfix (to production) to remove the wormmart link: https://github.com/WormBase/website/issues/4575
