### ISSUE TITLE
  When using the QueryBuilder and displ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4121]
<p>&nbsp;&nbsp;When using the QueryBuilder and displaying the code to replicate the query, the JavaScript information is out of date.  Some of the links to the libraries on the CDN are dead.  The newer libraries are at:<br/>http://cdn.intermine.org/api<br/>AND<br/>http://cdn.intermine.org/js/intermine/imjs/3.14.0/im.js</p>

Reported by: Shea****** (lova***************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.46 Safari/537.36

**Comment by Gschindelman** [comment]
Todd answered:
Hi Shea - 

Thanks for the report!  We have a brand-spanking new version of WormMine/Intermine
that we will be launching in the *very* near future. This should rectify problems
with obsolete JS URIs. We’ll see if we can’t patch the existing instance in the
meantime.

That said, have you found what you need?

Todd

**Comment by tharris** [comment]
Resolved in the new instance, launching soon.
