### ISSUE TITLE
  Hello, I'd like to have a list of the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4122]
<p>&nbsp;&nbsp;Hello,<br/>I'd like to have a list of the GO terms for all C. elegans genes. I tried using wormmine and it gave me a list of GO terms for genes, but seems to be missing some terms that I can see on the wormbase website for genes, eg. 'DNA repair' for polk-1, why is that?<br/>Regards,<br/>Avril</p>

Reported by: Avri*************** (alc@************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by vanaukenk** [comment]
Hi Avril,

In the meantime, you can access the corresponding WS248 file of GO annotations from our ftp site:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/ONTOLOGY/

The C. elegans file is listed about half-way down the page as:  

File:gene_association.WS248.wb.c_elegans

Let me know if you need any other assistance.

Best,
--Kimberly Van Auken

**Comment by janelomax** [comment]
Hi Avril

You can also use the ParaSite BioMart to do this - choose C. elegans from the SPECIES menu and then add biological process, cellular component and molecular function in the GENE ONTOLOGY menu. You can specify the output format under Attributes.

cheers

Jane


On Aug 24, 2015, at 3:30 PM, WormBase Helpdesk <notifications@github.com> wrote:

>   Hello,
> I'd like to have a list of the GO terms for all C. elegans genes. I tried using wormmine and it gave me a list of GO terms for genes, but seems to be missing some terms that I can see on the wormbase website for genes, eg. 'DNA repair' for polk-1, why is that?
> Regards,
> Avril
> 
> Reported by: Avri*************** (alc@************) (obscured for privacy))
> Submitted From: Tools /header
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0
> 
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by chris-grove** [comment]
First response by Todd:
"Hi Avril -

The existing WormMine instance isn't up-to-date with the current release. It will be very, very shortly. 

Todd"

**Comment by chris-grove** [comment]
Second response from Michael P:

HI Avril,

have a look at that directory on the FTP server, which holds files with for the current WS248 release for the GO-term connections:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS248/ONTOLOGY/

The C.elegans go-terms from the protein motifs are also in the BioMart for parasite.wormbase.org

... or we can just dump them for you in whatever format you want.

Michael

**Comment by chris-grove** [comment]
Dear Michael,

Thanks for this! I will download from there.

I didn't see that place on the ftp site (I was looking in ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/, but it seems that was the wrong place)

By the way, I did try worm-mart, but kept getting an error message, I'm not sure why. I could try again and send you the error message if you like?

Regards,

Avril
