### ISSUE TITLE
new "species" for WS250

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4124]
we added the C.elegans Hawaiian strain to the new WS250 release as Tier 3 "species".
the data will be in: species/c_elegans/PRJNA275000/
It does not yet have any gene-models, but they might come with WS251

**Comment by tharris** [comment]
Adding a stand-alone gbrowse doesn't really seem like the most useful application for the sequence of this strain. Are there alignments?

**Comment by khowe** [comment]
Yes, there are protein BLASTs, repeats, and cDNAs (aligned with STAR). 

The gene models are to come in WS251.  We can defer the provision of a genome browser until then, if you prefer.

**Comment by epaule** [comment]
I do have a HAL file (http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/current-development-release/COMPARATIVE_ANALYSIS/hub/ws250.hal) with whole genome alignments from Cactus, that I use for the UCSC snake tracks.
It does look something like that on UCSC:
![image](https://cloud.githubusercontent.com/assets/20523/9876927/a00e5f30-5bb1-11e5-94d1-b4dd32a22a78.png)

you can also see it in the development hub (as track on C.elegans N2):
http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/current-development-release/COMPARATIVE_ANALYSIS/hub/hub.txt

**Comment by scottcain** [comment]
He @epaule and @khowe ,

While I'd heard the talk about the Hawaiian strain, I didn't put two and two together that it is PRJNA275000 (which I had just assumed was a new assembly of the N2 strain (that's the standard strain, right?).

At the moment, I have G/JBrowse configs for Hawaiian (not labeled that of course) in the 250 release.  In addition to the relatively tiny amount of annotation data, I have the modEncode data tracks, but I'm not sure that makes much sense given that it's a different strain.  Please let me know if I'm right about that and I'll remove them.  Also, how should it be labeled in G/JBrowse?  Currently, it's "C. elegans (BioProject PRJNA275000)" but that feels like it might be a little confusing (hey, it confused me).  Should it be something more like "C. elegans (Hawaiian strain-BioProject PRJNA275000)"? It's an awfully long label but is at least clear.

As for the HAL file: I'm unfamiliar with that format--is it something that can be converted to bigwig?

**Comment by epaule** [comment]
It is a UCSC binary format for multiple genome alignments.
If I convert it to bigwig, it either looks like the alignability track if I take all genomes, 
or if I only take the two C.elegans, it would only show black boxes where the variations are.

**Comment by epaule** [comment]
If you want, you can add a (Hawaiian strain) to it, but I guess we should then spread the naming in a similar way across the website (dropdown menus, etc)

**Comment by sibyl229** [comment]
Hi @epaule the Hawaiian strain is added to the species dropdown menu with an access point to the species index page and gbrowse. It's under Others -> Caenorhabditis -> C. elegans (CB4856). Is that okay? Is there anything more to be done for this issue? Thanks!

**Comment by epaule** [comment]
it should also appear in the blast databases, as well as the species dropdown and J/GBrowse.

**Comment by epaule** [comment]
J/GBrowse seem to be working, so you can ignore that.

**Comment by epaule** [comment]
sorry, I didn't look there. So I guess only the blast is missing?

**Comment by scottcain** [comment]
It looks like everything is in place for these as well (blast, gbrwose, jbrowse).  Closing...
