### ISSUE TITLE
  Hello, In the Molecular Details secti...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4126]
<p>&nbsp;&nbsp;Hello,<br/>In the Molecular Details section of the page for osm-3(p802), p802's sequence appears to be reported on the (-) strand instead of the (+) stand - that is, the sequence displayed is actually the reverse compliment of what it is reported to be.</p>

Reported by: Loga* (loga*******************)  (obscured for privacy))
Submitted From: p802 (variation) <a href="http://www.wormbase.org//species/c_elegans/variation/WBVar00095126#02-45-10">/species/c_elegans/variation/WBVar00095126#02-45-10</a>

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by tuli** [comment]
Dear Logan,

Thank you for writing to WormBase.

All variations in WormBase are reported on the positive strand.

The osm-3 gene lies on the negative strand so the curation has been
reverse complimented on the website display. I have checked that the
effect on the protein matches what is described in the association
publication and it all seems fine to me.

I hope this answers your query, but please write back to me if I have
misunderstood.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
