### ISSUE TITLE
WS250 GFF changes

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4127]
due to curation work on the better classification of pseudogenes and alleles C.elegans got some new types:

KO_consortium sequence_alteration
PCoF_KO_consortium sequence_alteration
rRNA_Pseudogene exon
rRNA_Pseudogene pseudogenic_rRNA
tRNA_Pseudogene exon
tRNA_Pseudogene pseudogenic_tRNA

and we removed the GenblastG from P.pacificus (so it is now properly resticted to the Clade Vc species):
genBlastG CDS

**Comment by tharris** [comment]
@scottcain take particular note of these changes -- you will need to add some config for the rRNA and tRNA pseudogenes (probably independent tracks but also in the all encompassing all genes track) and update the variation tracks, then rebuild the conf files for WS250.

**Comment by khowe** [comment]
@scottcain there is (or was) an error in the GFF3. It's fixed now, and it could be that the fixed file is already in place by the time you start work on this:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz

The rRNA pseudogene features now have source "WormBase" (as with all other genic features in the canonical gene set), and a top-level transcript feature type of "pseudogenic_rRNA" and "pseudogenic_tRNA".

The sequence_alteration changes can be ignored for WS250. This was a curation oversight for a single feature, and will go away for WS251.

**Comment by scottcain** [comment]
OK, I'll work on GBrowse first for these changes and then JBrowse.

**Comment by scottcain** [comment]
@tharris @khowe @epaule Should the psuedogenic tRNA and rRNA genes go in a separate track from the other psuedogenes or in with them (I can see arguments either way, but lumped in with them makes the most sense to me)?

**Comment by khowe** [comment]
There is only one rRNA pseudogene. Giving it its own track gives it inappropriate importance :-)

Agree that they should be lumped in with other pseudogenes.

**Comment by scottcain** [comment]
Hi @khowe Just to be clear: both the pseudogenic rRNA and tRNA features should have WormBase as the source, right?  You didn't mention tRNA above so I wanted to be sure.  The GFF files on the wormbase ftp site and the mysql database both still have [rt]RNA_Pseudogene as the source, so they both need to be updated before I can really work on this. ( eh hem @tharris )

**Comment by khowe** [comment]
@scottcain yes. All features part of the canonical gene set (which includes coding and non-coding pseudogenes) should have source WormBase (and do in the patched GFF3).

**Comment by scottcain** [comment]
I updated JBrowse on staging to support pseudogenic [tr]RNA, see for example:

http://staging.wormbase.org/tools/genome/jbrowse/full.html?data=data%2Fc_elegans_PRJNA13758&loc=I%3A12719201..12738980&tracks=Curated%20Genes%20(pseudogenes)%2CCurated_Genes

This region has a pseudogenic transcript and pseudogenic tRNA.  Changes I made include:

*Changing the shade for gray for tRNA and rRNA pseudogenes in the pseudogene track; tRNAs are lighter gray and rRNA gene(s) are darker gray than the pseudogenic transcripts.
*Changing the description in the pseudogenes track to indicate the type of pseudogene.
*Modifying the color picking function of the gene track to get the color right for the t and rRNA genes (was assigning the violet or teal, which is reserved for protein coding genes).

**Comment by scottcain** [comment]
And the same is done for GBrowse.  See for example the one and only pseudogenic rRNA:

http://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?start=15050725;stop=15070724;ref=I;width=800;version=100;flip=0;grid=on;id=0e64448f783c71df9bcc5f6c7c26f4c6;l=GENES_PSEUDOGENES%1EGENES%1ELOCI%3Aoverview;h_feat=t25d1%40yellow
