### ISSUE TITLE
Citation display in Expr_pattern

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4133]
Hi Sibyl,

the citation display for WBPicture0000009882 on the expression page is not correct

It should display
'Reprinted from Current Biology, Hsu & Wu, 2010, Copyright 2010, with permission from Elsevier.'

here's the link
http://www.wormbase.org/species/all/expr_pattern/Expr9010#0213--10

thanks
Daniela

**Comment by sibyl229** [comment]
Hi @draciti is the citation problem still happening on the expression page: http://www.wormbase.org/species/all/expr_pattern/Expr9010#0213--10?

**Comment by draciti** [comment]
nope, looks good now sibyl, thanks. closing
