### ISSUE TITLE
Lidia (Lidia.Park@tufts.edu): wormbase not working...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4134]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Lidia (Lidia.Park@tufts.edu): wormbase not working</br>Lidia (Lidia.Park@tufts.edu): wormblast</br>Lidia (Lidia.Park@tufts.edu): there's a error page that says 502 page not working</br>Todd: Hi Lidia. I am checking on the problem now.</br>Todd: The problem with BLAST should now be fixed. Do you mind trying again?</br>Lidia (Lidia.Park@tufts.edu): yes it looks like it's working again.</br>Lidia (Lidia.Park@tufts.edu): thanks</br>Todd: Thanks for letting us know. Have a good day :)
    
**Reported by:** Lidi* (Lidi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#01-23-6">https://www.wormbase.org/#01-23-6</a>
**Browser:** Firefox 40.0

**Comment by tharris** [comment]
< issue reported and resolved in online chat >
