### ISSUE TITLE
  Find promoters in sequence? Thank you...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4137]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Find promoters in sequence?<br/>Thank you!</p>
    
**Reported by:** Kiri** (axea******)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by chris-grove** [comment]
Hello Kirill,

 What exactly do you want to do?

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Hello!

I want to find the  sequence of promoters, in genes like : zcIs4,gpIs1,zSi3001.

How do i find the sequence?

**Comment by chris-grove** [comment]
OK, no problem. The entities you are referring to (zcIs4, gpIs1 and
zSi3001) are actually transgenes. If you open up WormBase and search in
the search box "for a transgene" using these names, you'll get to the
respetive transgene pages:

http://www.wormbase.org/species/all/transgene/WBTransgene00005180#01--10

http://www.wormbase.org/species/all/transgene/WBTransgene00000572#01--10

http://www.wormbase.org/species/all/transgene/WBTransgene00010321#01--10

The latter two URLs provide construct details of how the promoter sequence
was obtained, although the description of zSi3001 is a bit cryptic. The
first mentioning of zSi3001 is in this paper:

http://www.ncbi.nlm.nih.gov/pubmed/?term=22227523

although the description isn't all that straightforward either.

For zcIs4 (the first URL), you'll need to navigate to the "Construct" page
by clicking on the "Expr11091_Ex" in the "Construction details" widget to
get to the corresponding construct page:

http://www.wormbase.org/species/all/construct/WBCnstr00005157#10--10

You'll need to get the sequences of each gene from the gene page or genome
browser to figure out the exact sequence.

Let me know if you need further assistance.

Best,

Chris Grove

**Comment by chris-grove** [comment]
Hi again Kirill,

 I meant to mention: you may find Textpresso for C. elegans:

http://www.textpresso.org/celegans/

useful for looking up construction details for transgenes.

Chris
