### ISSUE TITLE
  Three days ago I found the C. elegans...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4139]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Three days ago I found the C. elegans gene Y54G9A.3 in your database. Today it's gone.  Do these things get deleted?</p>
    
**Reported by:** dla@****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by tharris** [comment]
Hi dla - 

Y54G9A.3 is sequence name (using the original cosmid.transcript notation dating back to cloning and sequencing of the genome) for a gene now known by three alternatively spliced transcripts: Y54G9A.3a, Y54G9A.3b, and Y54G9A.3c.

The corresponding gene is here
  http://www.wormbase.org/species/c_elegans/gene/WBGene00002235

In general, no, things aren’t deleted. Sometimes genes are merged or split, or new alternative splices added resulting in identifiers like those listed above. These events are usually captured in the curatorial history. 

Todd
