### ISSUE TITLE
li (dsadasd@dasdasd.com): hi Todd: Hello. li (dsad...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4140]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

li (dsadasd@dasdasd.com): hi</br>Todd: Hello.</br>li (dsadasd@dasdasd.com): just checking...</br>Todd: Yes, I see that.</br>Todd: You’re from Pasadena, yes?
    
**Reported by:** li (dsad***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 43.0.2357.134

**Comment by tharris** [comment]
WormBaser from Pasadena testing.
