### ISSUE TITLE
  Dear webmaster of the wormbase websit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4142]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear webmaster of the wormbase website,<br/>I was trying to find tRNA’s sequences in our most cherished website and I could not. Is it that I am not entering the proper keyword (“tRNA”)? <br/>Thank you very much in advance for all your help.<br/>Kind regards,<br/>Diana</p>
    
**Reported by:** dian*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by tharris** [comment]
You might try WormMine. Here’s a direct link to search for tRNA genes constrained to Genes:

http://www.wormbase.org/tools/wormmine/keywordSearchResults.do?searchTerm=tRNA&searchBag=&facet_Category=Gene

Note that this is an older version of the database (not that the tRNA annotation has changed much if at all). We’ll be releasing a new version of WormMine very shortly.
