### ISSUE TITLE
The Tree display for Y53G8AR.7 is not working :( O...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4143]
*Help Desk query collected when no chat operators were online. Follow up required.*

The Tree display for Y53G8AR.7 is not working :( Or the genetic map
    
**Reported by:** yee **** (yche*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021814#0b4gh-9f1-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00021814#0b4gh-9f1-3</a>
**Browser:** Chrome 44.0.2403.157

**Comment by tharris** [comment]
Resolved and user contacted.

 Thanks for bringing this to our attention. I just wanted to drop you a line to let you know the problem has been fixed.

**Comment by chris-grove** [comment]
This issue appears to have resurfaced. I'm getting a (502) Bad Gateway  error on the Tree Display and Genetic Map on the gene page and when clicking links in the schema, as @rankishore  reported.

**Comment by tharris** [comment]
I have fixed this (again). It's an ongoing arms race with a family of bots. I've done three things to constrain their access.

**Comment by chris-grove** [comment]
OK, thanks @tharris !!
