### ISSUE TITLE
Staging.wormbase down...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4146]
*Help Desk query collected when no chat operators were online. Follow up required.*

Staging.wormbase down
    
**Reported by:** Raym*** (Raym****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/support">https://www.wormbase.org/tools/support</a>
**Browser:** Chrome 44.0.2403.133

**Comment by tharris** [comment]
Staging is ... being staged....

**Comment by tuli** [comment]
Staging is down

404 Not Found

**Comment by sibyl229** [comment]
Hi @tuli staging should be up now

**Comment by tuli** [comment]
Thanks.

**Comment by tuli** [comment]
Staging down again. 

504 Gateway Time-out

**Comment by tuli** [comment]
Staging down. Maybe WS250 is being built?

**Comment by tharris** [comment]
Maybe. Staging isn't guaranteed to be available 100% because we are doing a variety of things. Plus WS249 has problems with the Homol_data which is causing sgfiacserver to crash repeatedly.

**Comment by khowe** [comment]
What's the Homol_data problem? And is the same problem present in WS250?

**Comment by tharris** [comment]
I'm saying 1000s of reports that Homol_data is being clipped. Then sgifaceserver crashes. I haven't tested WS250 under load yet.

**Comment by khowe** [comment]
We see these messages all the time. It happens when you view/dump a sequence region with alignments that extends beyond the limits. The clipping is normal and correct, but Acedb chooses to warn about it anyway. Annoying, but I'm doubtful that it's related to the crash. What's the query that's causing the crash?

**Comment by tharris** [comment]
Weird, I rarely see these but they are flooding the logs for WS249.

**Comment by khowe** [comment]
Also, what version of the Acedb software version does the web-site use? Ed Griffiths has made numerous fixes and efficiency improvements in the past 5 years (although the most recent update was a few years ago now).

**Comment by tharris** [comment]
4.9.52 an 4.9.60.

**Comment by khowe** [comment]
Build uses 4.9.60 too.

**Comment by chris-grove** [comment]
@tharris @khowe   Can we close this ticket? Or create a new ticket if necessary?
