### ISSUE TITLE
How to report a new isoform for a gene? Thanks!...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4147]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to report a new isoform for a gene? Thanks!
    
**Reported by:** Shao******* (snow******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#01--10">http://www.wormbase.org/about/userguide/submit_data#01--10</a>
**Browser:** Chrome 44.0.2403.157

**Comment by gw3** [comment]
Shaohe,

Please send a description of the proposed new isoform to 
help@wormbase.org and a curator will make the appropriate change.

Please include any evidence you have for the proposed new isoform, such 
as transcript evidence.

If you have transcript evidence, please also submit your sequence to the 
INSDC databases (http://www.insdc.org/). This helps in the confirmation 
and evidence for the wormbase gene prediction as we automatically 
retrieve sequence data from the public databases. This also makes the 
data public, allowing appropriate reference and acknowledgment to yourself.

Thanks,
Gary Williams

**Comment by tharris** [comment]
User contacted with how to proceed.
