### ISSUE TITLE
Hey, this page (http://www.wormbase.org/species/c_...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4148]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hey, this page (http://www.wormbase.org/species/c_elegans/gene/WBGene00018812#016-9abdc3e7f4-10) states there are 12 papers in References section of the gene, when in reality, there are just 3 repeated 4 times each.  Just FYI, not causing me any problems...Thanks for all you do!!!-B
    
**Reported by:** Bob ******* (ohag**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00018812#016-9abdc3e7f4-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00018812#016-9abdc3e7f4-10</a>
**Browser:** Chrome 44.0.2403.155

**Comment by tharris** [comment]
Problem found and fixed (by @sibyl229) and pushed to production. User contact, issue closed.
