### ISSUE TITLE
  Gbrowse appears broken. help  What we...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4149]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Gbrowse appears broken.<br/>help</p><p>What were you doing? <br />&nbsp;&nbsp;trying to look at acy-2 in gbrowse</p>
    
**Reported by:** bria* (krae***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Creative AutoUpdate v1.40.01; rv:11.0) like Gecko

**Comment by scottcain** [comment]
GBrowse was misconfigured after the 249 release; it's fixed now and I sent an email to the reporter.
