### ISSUE TITLE
  On http://www.wormbase.org/species/al...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4150]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;On<br/>http://www.wormbase.org/species/all#01--10<br/>Caenorhabditis drosophilae is indicated as Genome coming soon, being sequenced at the Sanger, linking to Matt Berriman's lab web page. Just talking with him at a meeting, this seems a mistake as they have no plans to sequence it.<br/>More generally the "Genomes coming soon" paragraph seems outdated.<br/>Above, change C species 9 to C. nigoni.</p>
    
**Reported by:** Mari************ (feli*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by brucebolt** [comment]
Also, a large number of genomes on that page marked as "Coming Soon" are already available in ParaSite.

**Comment by khowe** [comment]
Page needs a massive update, the current content is very old. This is also a good place to describe what we mean by "core" species. 

Co-assigning to Hinxton. Since it seems that we cannot self-edit this widget, we will need to provide new content to web-team.

**Comment by tharris** [comment]
You *should* be able to edit all widgets on that page except for the Downloads widget (which we generate programatically).

**Comment by khowe** [comment]
You're right. I thought the edit button was at the top of the widget, but it's at the bottom. Removed webteam label.

**Comment by khowe** [comment]
Updated. Non-core species now maintained in a google sheet which is is displayed in the widget.
