### ISSUE TITLE
  Hello, I am not sure anyone has infor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4151]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am not sure anyone has informed WormBase that Caenorhabditis sp. 5 has been now named C. sinica.<br/>Huang R, Ren X, Qiu Y, Zhao Z (2014) Description of Caenorhabditis sinica sp. n. (Nematoda:Rhabditidae),<br/>a nematode species used in comparative biology for C. elegans. PLoS ONE 9: e110957. doi: 10.<br/>1371/journal.pone.0110957 PMID: 25375770<br/>All the best<br/>Marie-Anne</p>
    
**Reported by:** Mari************ (feli*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by tharris** [comment]
Addressed by Kevin, and in issue #4150.
