### ISSUE TITLE
  Hi what is daf-2 mutant in C elegans ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4152]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi what is daf-2 mutant in C elegans ? Does it mean that daf-2 gene in C elegans is knocked out ? </p>
    
**Reported by:** Giri************ (giri*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by tuli** [comment]
Dear Girish,

Thank you for writing to WormBase.

A daf-2 mutant is a strain in which the daf-2 gene has been mutated in
some way. It may be a knockout or it may be some other mutation such
as a substitution of a single base pair.
If you look at the Genetics widget of daf-2
http://www.wormbase.org/species/c_elegans/gene/WBGene00000898 you will
see all the many mutations (Variations) which have been curated in
daf-2.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
