### ISSUE TITLE
  Hi, are most of mutant strains of C.e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4153]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, are most of mutant strains of C.elegans called as deletion mutants ?<br/>I just want to know the principles and to make my concepts clear because I am just a novice in the field of C.elegans research.</p>
    
**Reported by:** Giri************ (giri*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by raymond91125** [comment]
Hi Girish,

The answer is no. This chapter could be a good start for you 
<http://wormbook.org/chapters/www_frmutagenesis/frmutagenesis.html>.

Cheers,

Raymond
