### ISSUE TITLE
  We have identified a new isoform for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4154]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We have identified a new isoform for the gene "noca-1", but didn't find a way to report it. Please let me know how. My email is:<br/>snownontrace@gmail.com<br/>You may also contact:<br/>Karen Oegema, koegema@ucsd.edu<br/>Thanks!<br/>Shaohe</p>
    
**Reported by:** Shao******* (snow******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by gw3** [comment]
Shaohe,

Please send a description of the proposed new isoform to 
help@wormbase.org and a curator will make the appropriate change.

Please include any evidence you have for the proposed new isoform, such 
as transcript evidence.

If you have transcript evidence, please also submit your sequence to the 
INSDC databases (http://www.insdc.org/). This helps in the confirmation 
and evidence for the wormbase gene prediction as we automatically 
retrieve sequence data from the public databases. This also makes the 
data public, allowing appropriate reference and acknowledgment to yourself.

Thanks,
Gary Williams
