### ISSUE TITLE
Small changes needed for Species drop-down

### ISSUE THREAD

**Issue by khowe** [WormBase/website#4155]
- S. ratti is now a core species and should be promoted to top-level
- C. species 5 is now called C. sinica. Others->Caenorhabditis-> C. sp. 5 needs to be updated accordingly.

**Comment by tharris** [comment]
See also #4081

**Comment by sibyl229** [comment]
Hi @khowe the S. ratti are in top-level of species dropdown and the C. sinica name is updated. Can this be closed?

**Comment by khowe** [comment]
Looks good to me.
