### ISSUE TITLE
There is a deletion allele tm1817 in wdr-23. It wo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4156]
*Help Desk query collected when no chat operators were online. Follow up required.*

There is a deletion allele tm1817 in wdr-23. It would be great if this information could be posted in the next version of wormbase. Thanks.
    
**Reported by:** Gaut****** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008419#04-9dac1be8f5-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00008419#04-9dac1be8f5-10</a>
**Browser:** Firefox 31.0

**Comment by tuli** [comment]
Dear Gautam,

Thank you for writing to WormBase.

I may have not understood your query correctly, as the tm1817 deletion
is available from WormBase and is curated as a deletion of wdr-23.

It is visible from the Genetics widget (if you click on the Allele
column the order will reverse and you will see tm1817 at the top) and
if you click on the tm1817 link you
will be taken to the Variation summary page for tm1817. If you are
looking at the genome browser you'll need to ensure the
High-throughput Allele track is selected.

I hope this answers your query, but please let me know if I can help further.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
