### ISSUE TITLE
Bogus files on FTP site for WS250

### ISSUE THREAD

**Issue by khowe** [WormBase/website#4160]
Some files were included in the WS250 distribution that should not have been. These have been removed from the Sanger/EBI FTP site. I don't know if Sanger->ftp.wormbase.org mirrroring respects file deletions. In case it does not and these need to be deleted by hand, here they are (all in ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/):

c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.coding_transcripts.fa.gz
c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.Coding_transcripts.fa.gz
c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.GBrowse.gff2.gz
c_briggsae/PRJNA10731/c_briggsae.PRJNA10731.WS250.GBrowse.gff2.gz
c_brenneri/PRJNA20035/c_brenneri.PRJNA20035.WS250.GBrowse.gff2.gz
p_pacificus/PRJNA12644/p_pacificus.PRJNA12644.WS250.GBrowse.gff2.gz
s_ratti/PRJEB125/s_ratti.PRJEB125.WS250.GBrowse.gff2.gz
o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS250.GBrowse.gff2.gz
c_japonica/PRJNA12591/c_japonica.PRJNA12591.WS250.GBrowse.gff2.gz
b_malayi/PRJNA10729/b_malayi.PRJNA10729.WS250.GBrowse.gff2.gz
c_remanei/PRJNA53967/c_remanei.PRJNA53967.WS250.GBrowse.gff2.gz

**Comment by tharris** [comment]
Removed.
