### ISSUE TITLE
GO term display

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4161]
while testing the Expression data display I have noticed that GO terms on the Gene page, expression widget are displayed with GO ID instead of name. e.g. GO:0005634 instead of nucleus

http://staging.wormbase.org/species/c_elegans/gene/WBGene00000912#01-f-3

this is the case also on the 'Details' widget on the expression page

http://staging.wormbase.org/species/all/expr_pattern/Expr11340#012--10

thanks

**Comment by vanaukenk** [comment]
Hi,
This has now been fixed.  Thanks, @sibyl229 !
