### ISSUE TITLE
Please update the nomenclature Transgene section t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4162]
*Help Desk query collected when no chat operators were online. Follow up required.*

Please update the nomenclature Transgene section to include Si alleles - for MosSCI insertions. thx!
    
**Reported by:** Jane******** (jane********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b7f3--10">http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b7f3--10</a>
**Browser:** Firefox 31.0

**Comment by tuli** [comment]
Dear Jane,

Thank you for writing to WormBase. We will get this added to the
Nomenclature guidelines in the next day or so and I will write to you
again when it's done. Do you need to advice on naming Mosci insertions
or are you just informing us of the omission?

Best wishes,

Mary Ann

On 8 September 2015 at 16:33,  <no-reply@wormbase.org> wrote:
> offline chat Please update the nomenclature Transgene section to include Si
> alleles - for MosSCI insertions. thx!
>
> Submitted From:
>
> http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b7f3--10
> http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b7f3--10
>
> This issue has been assigned ticket number: #4162. Follow progress on our
> issue tracker.
>
> Reported by: Jane Hubbard (jane.hubbard@med.nyu.edu)
> 08 Sep 15 15:35
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Jane,

Further to my message last week, I can now confirm that we have
updated the Nomenclature guidelines to include Si alleles.

Please see the Transgene widget at
http://www.wormbase.org/about/userguide/nomenclature

Best wishes,

Mary Ann

On 8 September 2015 at 16:57, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
> Dear Jane,
>
> Thank you for writing to WormBase. We will get this added to the
> Nomenclature guidelines in the next day or so and I will write to you
> again when it's done. Do you need to advice on naming Mosci insertions
> or are you just informing us of the omission?
>
> Best wishes,
>
> Mary Ann
>
> On 8 September 2015 at 16:33,  <no-reply@wormbase.org> wrote:
>> offline chat Please update the nomenclature Transgene section to include Si
>> alleles - for MosSCI insertions. thx!
>>
>> Submitted From:
>>
>> http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b7f3--10
>> http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b7f3--10
>>
>> This issue has been assigned ticket number: #4162. Follow progress on our
>> issue tracker.
>>
>> Reported by: Jane Hubbard (jane.hubbard@med.nyu.edu)
>> 08 Sep 15 15:35
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Thanks Mary Ann!
Jane

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E. Jane Albert Hubbard, Ph.D.
Professor

CONTACT INFO:
email: jane.hubbard@med.nyu.edu
office: 212.263.7154
lab: 212.263.7533
assistant: 212.263.7595
website: http://jhubbardlab.med.nyu.edu <http://jhubbardlab.med.nyu.edu/>


LAB ADDRESS:
New York University School of Medicine
Skirball Institute for Biomolecular Medicine, 4th Floor, Lab 7
540 First Avenue   New York, NY   10016
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




On 9/15/15, 4:04 AM, "Mary Ann Tuli" <maryann.tuli@wormbase.org> wrote:

>Dear Jane,
>
>Further to my message last week, I can now confirm that we have
>updated the Nomenclature guidelines to include Si alleles.
>
>Please see the Transgene widget at
>http://www.wormbase.org/about/userguide/nomenclature
>
>Best wishes,
>
>Mary Ann
>
>On 8 September 2015 at 16:57, Mary Ann Tuli <maryann.tuli@wormbase.org>
>wrote:
>> Dear Jane,
>>
>> Thank you for writing to WormBase. We will get this added to the
>> Nomenclature guidelines in the next day or so and I will write to you
>> again when it's done. Do you need to advice on naming Mosci insertions
>> or are you just informing us of the omission?
>>
>> Best wishes,
>>
>> Mary Ann
>>
>> On 8 September 2015 at 16:33,  <no-reply@wormbase.org> wrote:
>>> offline chat Please update the nomenclature Transgene section to
>>>include Si
>>> alleles - for MosSCI insertions. thx!
>>>
>>> Submitted From:
>>>
>>> 
>>>http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b
>>>7f3--10
>>> 
>>>http://www.wormbase.org/about/userguide/nomenclature#261hgd80lkji49ace5b
>>>7f3--10
>>>
>>> This issue has been assigned ticket number: #4162. Follow progress on
>>>our
>>> issue tracker.
>>>
>>> Reported by: Jane Hubbard (jane.hubbard@med.nyu.edu)
>>> 08 Sep 15 15:35
>>>
>>> This question was reported via the web interface at wormbase.org. You
>>>can
>>> also email us directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the "WormBase:
>>>help"
>>> group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>
>>
>>
>> --
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>
>
>
>-- 
>~ Mary Ann Tuli
>
>~ email: maryann.tuli@wormbase.org
>~ Database Curator, WormBase
>
>~ Biology Division
>~ California Institute of Technology
>~ 1200 E. California Blvd
>~ Pasadena, CA 91125


------------------------------------------------------------
This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain information that is proprietary, confidential, and exempt from disclosure under applicable law. Any unauthorized review, use, disclosure, or distribution is prohibited. If you have received this email in error please notify the sender by return email and delete the original message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.
=================================
