### ISSUE TITLE
Image caption in pop-up

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4163]
On the expression page, in the overview widget -both staging and live site:
http://staging.wormbase.org/species/all/expr_pattern/Expr437#012--10

if you click on the image, the caption of the pop-up image displays 'No reference data'. It should display the same caption showed in the overview: 'Courtesy of Ian Hope'
thanks

**Comment by sibyl229** [comment]
Hi @draciti the missing citation is fixed on staging http://staging.wormbase.org/species/all/expr_pattern/Expr437#012--10

**Comment by draciti** [comment]
perfect Sibyl, thanks! closing
