### ISSUE TITLE
Fix and rebuild GBrowse config for new C.elegans assembly

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#4164]
Several items need to be touched to get a GBrowse config for the new C. elegans assembly.

**Comment by scottcain** [comment]
I believe the JBrowse config is done on staging: http://staging.wormbase.org/tools/genome/jbrowse/?data=data%2Fc_elegans_PRJNA275000

**Comment by epaule** [comment]
staging jbrowse throws an: Error reading from name store.

**Comment by scottcain** [comment]
I noticed that and haven't figured out what the problem is yet, but after dismissing it, all of the functionality is present.

**Comment by scottcain** [comment]
@epaule I think I sorted it out--there are no tracks in the new assembly that would get "name indexed"--for jbrowse, I only index for name searching the tracks that people would conceivably want to search by text.  There are no other assemblies like that, so the script that writes the config just assumes that the index will be there.

Now that I've loaded the protein similarity tracks though, they seem rather ugly and uninformative :-/

**Comment by scottcain** [comment]
The last two releases have had the Hawaiian assembly; closing...
