### ISSUE TITLE
Accession_evidence missing database value

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#4165]
Looks like some data problem here. The screenshots are taken from the CDS tree display. The database value is missing in some accession evidence. 

Ex 1.
![screen shot 2015-09-08 at 2 23 32 pm](https://cloud.githubusercontent.com/assets/1753893/9743658/76a02a9c-5635-11e5-9890-99fee414fb53.png)

Ex 2
![screen shot 2015-09-08 at 2 29 37 pm](https://cloud.githubusercontent.com/assets/1753893/9743823/44840da2-5636-11e5-8288-4006757e6cda.png)

**Comment by khowe** [comment]
@sibyl229 good catch. We spotted that during the build, and thought we squashed it, but it seems to have leaked back in. 

@tharris This patch will fix it:

ftp://ftp.sanger.ac.uk/pub/consortia/wormbase/releases/WS250/acedb/PATCHES/CDS_brief_identification_accession_evidence.ace

**Comment by sibyl229** [comment]
@khowe Thanks for the patch :)

**Comment by tharris** [comment]
Patched. Please test and close if resolved.

**Comment by sibyl229** [comment]
Thank you :) Accession evidence patch works. And test cases is put back.
