### ISSUE TITLE
JBrowse links for gene pages in 250

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#4166]
Hi @sibyl229 

Writing JBrowse links is pretty easy; they look like this:

http://www.wormbase.org/tools/genome/jbrowse/?data=data%2FSPECIES&BIOPROJECT&loc=REFSEQ%3ASTART..END

So an example would be:

http://www.wormbase.org/tools/genome/jbrowse/?data=data%2Fc_elegans_PRJNA13758&loc=III%3A4679650..4692604

If we don't supply a tracks= parameter, it will use the default tracks, which are the same as GBrowse, and I think that's what we do for the gene page links for GBrowse now anyway.

I guess the other decision to make is where the anchor should go.  My initial thought is on the same line as the GBrowse link but justified right in the widget, but I am hardly wedded to that idea.

**Comment by sibyl229** [comment]
Hi @scottcain the link to JBrowse is added to location widgets of Gene, CDS and Transcript:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9f-3

A few things still needs to be done. I'd like hear your thoughts on whether to include them in this release or in a later release:
- The browse genome from the menu 
![screen shot 2015-09-10 at 5 12 59 pm](https://cloud.githubusercontent.com/assets/1753893/9801129/379f52c2-57df-11e5-9205-ca5aeeca629b.png)
- The search result for things that has coordinates
![screen shot 2015-09-10 at 5 13 11 pm](https://cloud.githubusercontent.com/assets/1753893/9801167/6afc38b0-57df-11e5-944e-5a7efb8df36e.png)
- jBrowse iframe will go out in a later release as you suggested
- There's also a species page like http://staging.wormbase.org/species/c_elegans#3-2-5 maybe we can include an iframe there

**Comment by scottcain** [comment]
Hi @sibyl229, to create an JBrowse image that runs well inside an iframe, just use the same JBrowse url as the link for location widget as the src for the iframe, but add these three GET parameters:

```
tracklist=0&nav=0&overview=0
```

which hides those UI pieces, leaving you with just the details panel equivalent of GBrowse.

I don't see why we wouldn't add the JBrowse links to search results, right after the GBrowse link.  Todd seems to think there isn't much point in adding the JBrowse link to the species dropdown, though I'm not sure what harm it would do either.  I think his point was just that we probably wouldn't get much traffic from it..

**Comment by sibyl229** [comment]
Hi @scottcain the JBrowse view is up now. 
http://staging.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9-3

Is there anything you'd like to change? I kept the Select Tracks, as I think it's quite helpful that people can do that without leaving the gene page. 

A side note, maybe only one of the Full-screen view and Full page button is needed on this view. I think the full-screen view is the better choice.

**Comment by scottcain** [comment]
Hi @sibyl229 Nice work.  Things we might want to think about:

1. Specifying the tracks to display explicitly in the URL for the iframe.  If we don't do that and the user has already been to jbrowse, it will inherit the track list from the previous visit's cookie, resulting in a potentially confusing display.  The track list parameters would look like this:
```
tracks=Curated_Genes%2CClassical_alleles%2CYACs%2C%20Fosmids%2C%20%26%20Cosmids
```
Is this why you left the track selector active in the iframe?

2.  I need to either a) suppress the "full screen" button somehow, or ii) intercept the URL and add the UI attributes back in.  If we do nothing, users get a full screen JBrowse with no navigation and search tools, which might be confusing.  I think (ii) will be easier than (a).

**Comment by scottcain** [comment]
Nice, github in it's infinite wisdom has decided to renumber my item 2 as item 1.  Thanks github!  Also, how amazing is it that I posted my response to you 14 seconds after you posted.  Impressive, no? :-)

I was thinking about the first item 1, and it's possible that specifying the track list in the url will rewrite the cookie for a user that has been to JBrowse before, also causing pain and suffering for a user that may have jbrowse configured exactly the way she likes.  I don't like either option.

**Comment by sibyl229** [comment]
Haha. I couldn't come up with an reply that fast. 

About your first item 1, my reason for leaving the select tracks button is simply to emphasize: this view is interactive, you can choose tracks you like to see. Yeah it does look like a dilemma. Maybe if there's a easy way to keep default tracks on top, and include customized ones after, that might make some users happy. If there's no easy way, then my preference is to showing the default tracks - as this is still the gene page, and people would expect curated information, not customized. If the user likes lots customization, they can do it with the full jbrowse view :)

Your solution to item 2 sounds good to me.

Btw I noticed a bug with the iframe, if I backbutton it shows blank now.. I'm trying to fix it.

**Comment by sibyl229** [comment]
Hi @scottcain I forgot to @ you. Any additional thoughts on the JBrowse frame?

**Comment by scottcain** [comment]
Hi @sibyl229 I'm mostly happy with it.  I hacked the JBrowse js code directly (which I was hoping to avoid) to take out the link for "full page" and left my button in place.  One thing that might be nice is to give a slightly larger buffer for the coordinates, since it seems like the left side of the gene is always under the track label in my browser (though that's going to be a function of the browser window width I think).

**Comment by sibyl229** [comment]
@scottcain Sure, I will add the coordinate buffer. Any additional thoughts on whether it's okay to set default tracks in the url (hence overwrite the user customization of tracks)?

**Comment by scottcain** [comment]
@sibyl229 Unless @tharris overrules me, I'm willing to leave track/cookie issue as is for the moment.  If people complain we can look at alternate solutions then.
