### ISSUE TITLE
  I would like to get a list of all of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4167]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to get a list of all of the genes whose KO/knockdown results in the 'fat content reduced' phenotype. All I can find is a list of the RNAi IDs (http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001183#40--10). When I searched for all the genes related to that phenotype through wormmine, only genes with known alleles are shown. Is there a better way to get this info? If not, could you direct me to the master list connecting RNAi IDs to their targets?</p>
    
**Reported by:** Sean (smac***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by raymond91125** [comment]
Hi Sean,

Your question can be answered by the Ontology Browser. In this widget on 
the phenotype page, top panel, to the right of the focus term there are 
two numbers 440 and 417. If you click on them, you'll get to a new page 
with lists of genes that have been annotated with this phenotype via 
RNAi or variation. 440 includes genes annotated with phenotypes that are 
'subtypes' of "fat content reduced".

BR,

Raymond



On 09/09/2015 09:07 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I would like to get a list of all of the genes whose KO/knockdown 
> results in the 'fat content reduced' phenotype. All I can find is a 
> list of the RNAi IDs 
> (http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001183#40--10). 
> When I searched for all the genes related to that phenotype through 
> wormmine, only genes with known alleles are shown. Is there a better 
> way to get this info? If not, could you direct me to the master list 
> connecting RNAi IDs to their targets?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4167. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4167>.
>
> Reported by: Sean (smack14@umd.edu)
> 09 Sep 15 16:09
>
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/45.0.2454.85 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
User contacted with an approach for fetching requested data; considering resolved.
