### ISSUE TITLE
Hi there. I would like to get all the genomic vari...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4169]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there. I would like to get all the genomic variations listed in wormbase concerning the wild isolate PB306.
I get them when I ask for "PB306" and "for a variation" in the top right-hand search bar. But results are to big to be all downloaded and I am asked to use the ftp. However I couldn't find where in the ftp are the variation databases...
Could you please help me with this issue ?
Thank you very much,

Fabrice
    
**Reported by:** fabr*********** (fbes********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/variation/PB306">http://www.wormbase.org/search/variation/PB306</a>
**Browser:** Firefox 40.0

**Comment by tuli** [comment]
Dear Fabrice

Your best bet is to use our GFF files. Here is a link to the GFF3 for
our latest development release:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz

To get all variations reported in PB306, you can do:

zcat c_elegans.PRJNA13758.WS250.annotations.gff3.gz | awk '$1 ==
"Variation_project_Polymorphism" | grep PB306

I hope this helps,

Best wishes,

Mary Ann

On 10 September 2015 at 08:08,  <no-reply@wormbase.org> wrote:
> offline chat Hi there. I would like to get all the genomic variations listed
> in wormbase concerning the wild isolate PB306. I get them when I ask for
> "PB306" and "for a variation" in the top right-hand search bar. But results
> are to big to be all downloaded and I am asked to use the ftp. However I
> couldn't find where in the ftp are the variation databases... Could you
> please help me with this issue ? Thank you very much, Fabrice
>
> Submitted From:
>   http://www.wormbase.org/search/variation/PB306
> http://www.wormbase.org/search/variation/PB306
>
> This issue has been assigned ticket number: #4169. Follow progress on our
> issue tracker.
>
> Reported by: fabrice besnard (fbesnard@biologie.ens.fr)
> 10 Sep 15 07:10
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
From the user: 

Great !
Thank you very much, i didn't know that this information was in gff file.

regards,
Fabrice
