### ISSUE TITLE
  I noticed that the exon/intron descri...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4170]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I noticed that the exon/intron description of gene R09E10.4 is likely wrong.  Although we have not identified a cDNA (its just a prediction), the following cDNA is probably more correct as the translation product is a good match for a fatty acid co-ligase suggesting R09e10.4 should probably be given an acs gene name.<br/>>predicted cdna<br/>ATGCTCAATCAAGGTCTCGGGATTTTGGCTCGCAGAGCAAGTTCTCAAACTCGCTATGGTAACCTTCTCATTCTGAATAATACCTCACTCGCGGTTCAAGATCGTAGCTTCTTTTTTGGCAAACGTCGTGAACCAAAATGTGACTTGAAAAATCAATCCATTGTTCAAGCTGATGGAAGTAGAAAATCAGCATGGCTTGGAGATGAACCACTTCGACATGAATGGTTCAGTGGAATATTGACTACTTATACCGGGATCCGTCGTGGACCAACTGTTGGCGGGAAAGAAATGTTGGGGAAGAGAGTGATGAAGAATGGGAAATTGGAATGGGAATGGATTACATATGATCAAGCATTTGAAATATCTGATAATGTATCTCAAGCTATCAGAAAGTTGGGAATTGATACTGGCGATGAAACAAACATTGGTATTTATTCGAAGAATAGACCAGAGTGGATACTATCGGATATGGCAATTCACAACTTCAGCAATGTTTCTGTTCCGCTTTACGATACCATAACAAATGATGATATGCATTACATAACCAATCTCTGTGAAATCTCTTTGATTTTTGCTGATAGTGAAGATAAAACTACTCAACTCGTCAGAGATAAAAGCTACTTGTCAAATTTGAAATACATTGTACAATTTGACAATGTGTCTGATGAGATGAAGAGAGTGGCGGAGAAGAATAACTTCCAGTTATGGAGTTTCAATGAGTTTGTTGAAATGGGAAAAAAACAAAAGCATCGTCCACATGTTCCACCAACACCTGAAACATTGGCAACAATTTCATTCACTTCTGGAACAACTGGACGTCCTAAAGGAGTTATGCTGACCCATTTAAACTTGTGCTCCACAACAATGGCATTTGAAGAATTCGAGCATGTCGAAGGAGAACAGGATTCGTATCTATCTTATCTTCCGTTGGCTCATATGTACGAAAGACACTGTACTCTAGAGCACACTTTAAAATCGGATCgtaagattattttctcGAAAATTGGGTTTTCTCGAGGTGATCCAGATCTTTTAGtggaagacattcaggcactgggtccacgtacatttgctaccgttccccgcgttttagacaagatttataagtctgtaatgaagcaaatacaaaataaacctgtgaaaaagatgattctaaactctgccattgcatacaaattgtatcattacaaaataaccggaaaagctactcgggatactttggtggacaagtatattctgcacaagattcaaatgatgctcggtcctaacatcaagcaatttctgatagcggctgcaaaaacagataaatcattgttgaaatttgctcgtggagcttttgggattgaagttcttgagttatatggacaaactga<br/>Translation:<br/>MLNQGLGILARRASSQTRYGNLLILNNTSLAVQDRSFFFGKRREPKCDLKNQSIVQADGSRKSAWLGDEPLRHEWFSGILTTYTGIRRGPTVGGKEMLGKRVMKNGKLEWEWITYDQAFEISDNVSQAIRKLGIDTGDETNIGIYSKNRPEWILSDMAIHNFSNVSVPLYDTITNDDMHYITNLCEISLIFADSEDKTTQLVRDKSYLSNLKYIVQFDNVSDEMKRVAEKNNFQLWSFNEFVEMGKKQKHRPHVPPTPETLATISFTSGTTGRPKGVMLTHLNLCSTTMAFEEFEHVEGEQDSYLSYLPLAHMYERHCTLEHTLKSDRKIIFSKIGFSRGDPDLLVEDIQALGPRTFATVPRVLDKIYKSVMKQIQNKPVKKMILNSAIAYKLYHYKITGKATRDTLVDKYILHKIQMMLGPNIKQFLIAAAKTDKSLLKFARGAFGIEVLELYGQTE</p>
    
**Reported by:** Anto************ (Cola***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by gw3** [comment]
Hi Antonio,

Thanks for looking at the structure of R09E10.4.
I agree that your proposed structure would be a good match to the rest of
the 'acs' gene family, however the available evidence shows that the
current structure in WormBase is correct.
There is both RNASeq evidence and transcription evidence from the OST
project which matches the current structure and no evidence which matches
your proposed structure.

The damage to the gene structure in the second half results in the last
three exons of any likely gene transcript containing premature termination
codons, so I am now going to change R09E10.4 into a pseudogene.

If you do find any cDNA transcript evidence or proteomics evidence that
supports the possibility that this is a coding gene, I would be very
interested in hearing from you.

I agree that this gene should be given an 'acs' gene name, even though it
will now be a pseudogene, and I will submit a request for this now.

Regards,
Gary Williams

**Comment by Paul-Davis** [comment]
Dear Antonio,

The predicted cDNA you have submitted matches what WormBase used to have 
for this gene up until WS120 when the OST sequence accession CB394579 
suggested that the intron utilised by the old annotation was incorrect 
and that the CDS should be modified to produce the truncated coding 
transcript we see today. Subsequently RNASeq data has corroborated the 
OSTs evidence and there are now over 1000 reads supporting the current 
inclusion of the changed intron. However this does appear to be a 
unusual gene with a complex potentially spliced 3' UTR. To demonstrate 
this our curators have also annotated a non_coding_transcript isoform 
R09E10.4b with the following comment: "[061011 gw3] Added this 
non-coding transcript isoform to include the downstream protein homology 
data. It is very likely that this whole gene is a pseudogene, but the 
OST data defines the other isoform which could be a real CDS.".

I hope this explains why we have the locus annotated as it is, if you 
have additional data suggesting how we can improve our annotation or 
evidence to suggest that we should re-classify the gene we would be more 
than happy to incorporate it.

Thanks again for contacting WormBase.

Paul
[Sequence curation]


On 10/09/2015 10:38, no-reply@wormbase.org wrote:
> Content Correction
>
>   I noticed that the exon/intron description of gene R09E10.4 is 
> likely wrong. Although we have not identified a cDNA (its just a 
> prediction), the following cDNA is probably more correct as the 
> translation product is a good match for a fatty acid co-ligase 
> suggesting R09e10.4 should probably be given an acs gene name.
> >predicted cdna
> ATGCTCAATCAAGGTCTCGGGATTTTGGCTCGCAGAGCAAGTTCTCAAACTCGCTATGGTAACCTTCTCATTCTGAATAATACCTCACTCGCGGTTCAAGATCGTAGCTTCTTTTTTGGCAAACGTCGTGAACCAAAATGTGACTTGAAAAATCAATCCATTGTTCAAGCTGATGGAAGTAGAAAATCAGCATGGCTTGGAGATGAACCACTTCGACATGAATGGTTCAGTGGAATATTGACTACTTATACCGGGATCCGTCGTGGACCAACTGTTGGCGGGAAAGAAATGTTGGGGAAGAGAGTGATGAAGAATGGGAAATTGGAATGGGAATGGATTACATATGATCAAGCATTTGAAATATCTGATAATGTATCTCAAGCTATCAGAAAGTTGGGAATTGATACTGGCGATGAAACAAACATTGGTATTTATTCGAAGAATAGACCAGAGTGGATACTATCGGATATGGCAATTCACAACTTCAGCAATGTTTCTGTTCCGCTTTACGATACCATAACAAATGATGATATGCATTACATAACCAATCTCTGTGAAATCTCTTTGATTTTTGCTGATAGTGAAGATAAAACTACTCAACTCGTCAGAGATAAAAGCTACTTGTCAAATTTGAAATACATTGTACAATTTGACAATGTGTCTGATGAGATGAAGAGAGTGGCGGAGAAGAATAACTTCCAGTTATGGAGTTTCAATGAGTTTGTTGAAATGGGAAAAAAACAAAAGCATCGTCCACATGTTCCACCAACACCTGAAACATTGGCAACAATTTCATTCACTTCTGGAACAACTGGACGTCCTAAAGGAGTTATGCTGACCCATTTAAACTTGTGCTCCACAACAATGGCATTTGAAGAATTCGAGCATGTCGAAGGAGAACAGGATTCGTATCTATCTTATCTTCCGTTGGCTCATATGTACGAAAGACACTGTACTCTAGAGCACACTTTAAAATCGGATCgtaagattattttctcGAAAATTGGGTTTTCTCGAGGTGATCCAGATCTTTTAGtggaagacattcaggcactgggtccacgtacatttgctaccgttccccgcgttttagacaagatttataagtctgtaatgaagcaaatacaaaataaacctgtgaaaaagatgattctaaactctgccattgcatacaaattgtatcattacaaaataaccggaaaagctactcgggatactttggtggacaagtatattctgcacaagattcaaatgatgctcggtcctaacatcaagcaatttctgatagcggctgcaaaaacagataaatcattgttgaaatttgctcgtggagcttttgggattgaagttcttgagttatatggacaaactga
> Translation:
> MLNQGLGILARRASSQTRYGNLLILNNTSLAVQDRSFFFGKRREPKCDLKNQSIVQADGSRKSAWLGDEPLRHEWFSGILTTYTGIRRGPTVGGKEMLGKRVMKNGKLEWEWITYDQAFEISDNVSQAIRKLGIDTGDETNIGIYSKNRPEWILSDMAIHNFSNVSVPLYDTITNDDMHYITNLCEISLIFADSEDKTTQLVRDKSYLSNLKYIVQFDNVSDEMKRVAEKNNFQLWSFNEFVEMGKKQKHRPHVPPTPETLATISFTSGTTGRPKGVMLTHLNLCSTTMAFEEFEHVEGEQDSYLSYLPLAHMYERHCTLEHTLKSDRKIIFSKIGFSRGDPDLLVEDIQALGPRTFATVPRVLDKIYKSVMKQIQNKPVKKMILNSAIAYKLYHYKITGKATRDTLVDKYILHKIQMMLGPNIKQFLIAAAKTDKSLLKFARGAFGIEVLELYGQTE
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4170. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4170>.
>
> Reported by: Antonio Colavita (Colavita@uottawa.ca)
> 10 Sep 15 09:40
>
> Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
