### ISSUE TITLE
  I am trying to access to BioProject P...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4171]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to access to BioProject PRJEA64437 (Bursaphelenchus xylophilus) through species menu but it goes directly to the C. elegans project (BioProject PRJNA13758). Also when I try to do a Blast search the option for that species disappeared, as well as many other things that a used to have access (in July 2015) and now I cannot find. Could you please help me with that? Thank you very much.<br/>Joana Cardoso</p>
    
**Reported by:** Joan********* (joan***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by tharris** [comment]
That species (and others) have been removed from WormBase and are now available exclusively at ParaSite. 

Additional details are described in this blog post:

http://blog.wormbase.org/2015/07/27/ws249-reorganisation-of-parasitic-non-core-species/

We still have a few things to clean up the user interface with respect to this change in organization. We plan to put these fixes in place in the next release of WormBase.

Hope this helps.

Todd
