### ISSUE TITLE
 Server Error: 500 at  rest/widget/static/0     Er...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4172]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://staging.wormbase.org/rest/widget/static/0">rest/widget/static/0</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget_static "Can't call method "page_id" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 1068." </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to create a test widget on staging</p>
    
**Reported by:** Kevi****** (kevi*******************)
**Submitted from:** <a target="_blank" href="http://staging.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by tharris** [comment]
The URI reporter seems to have failed. From what page?

**Comment by chris-grove** [comment]
@khowe  Could you clarify which page is/was giving the error?

**Comment by Paul-Davis** [comment]
removing helpdesk as this was a staff ticket.

**Comment by Paul-Davis** [comment]
Unknown page source as submitted via feedback form.
