### ISSUE TITLE
Hello there, im trying to get my API KEY but wormm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4174]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello there, im trying to get my API KEY but wormmine is no logging in with my account. Can you help me pls?
    
**Reported by:** Manu*********** (mane*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/me#1-0-5">http://www.wormbase.org/me#1-0-5</a>
**Browser:** Chrome 45.0.2454.85

**Comment by tharris** [comment]
User contacted. Not possible to provision API key in old version of WormMine because of log in issue.
