### ISSUE TITLE
Brugia gene patch

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4177]
This patch file tidies up the status of 2 brugia genes where the patch didn't stick during the WS250 build.

ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS250/acedb/PATCHES/patch_brugia_gene.ace

**Comment by tharris** [comment]
Loaded. Please test and close if resolved.

**Comment by epaule** [comment]
looks good (all dead)
