### ISSUE TITLE
  Hi,  I noticed that F33H2.5 was chang...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4178]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,  I noticed that F33H2.5 was changed to pole-1.  Thank you for changing the  name.  However, I noticed that the wrong Sarah Robinson was attributed to the gene.  I am a new member of the Kimble lab and not yet listed on the website.  Can you fix this?<br/>Thank you!<br/>Sarah Robinson</p>
    
**Reported by:** Sara********** (srob****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by rankishore** [comment]
Cecilia took care of the user's lab connection:
Dear Sarah: Thank you very much for your help.
I have added your lab connection to Judith Kimble lab, aka 'Sarah Robinson', 2nd email and old_institution 'West Virginia University; Morgantown WV, United States of America'.
Updates will appear in your WBPerson report in WS251 release of WormBase.

**Comment by tuli** [comment]
Dear Sarah,

Further to Cecilia's message, I would like to confirm that I have
updated the attribution for the pole-1 gene to the right Sarah
Robinson (WBPerson30389). You'll see the update in release WS251 of
WormBase.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
