### ISSUE TITLE
Molecule display page: requests for fixes in External Links Table

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4180]
1. What is the "Maintainer" column
2. Column header "Description" is misleading as the info reported is info about the external database rather than the molecule, would you change the name of the column to "Database Focus" ?

**Comment by tharris** [comment]
The external links table is generically created. The labels may be appropriate for some representations of links but not others, if these database fields are not consistently used.

**Comment by kyook** [comment]
Ok,  I've updated the maintainers for the molecule page external links.
