### ISSUE TITLE
Molecule page display: Phentoype Affected table requests

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4181]
Ideally the table should be focused on the phenotype and evidences grouped through that term and then on gene. 

For example, gene pages group by phenotype in the phenotype widget (ex. http://staging.wormbase.org/species/c_elegans/gene/WBGene00002994#0-b-3)

The columns should be 
Phenotype | Gene | Supporting evidence
For all, alleles and transgenes, the associated gene name should show. For Transgenes, please use the gene value in the tag Caused_by or Caused_by_other values.  

For RNAi objects, please include the Primary targets (up to 4). 

Good pages to use for adapting this table are: 
http://www.wormbase.org/resources/molecule/WBMol:00004596#02--10
http://www.wormbase.org/resources/molecule/WBMol:00004019#02--10 (actually this one might have too much stuff to work with initially)
http://www.wormbase.org/resources/molecule/WBMol:00004563#02--10

**Comment by sibyl229** [comment]
Hi @kyook I have done a little bit work on the phenotypes affected table. I still need to group the rows by phenotype, if that's what you like. Here's is the WIP http://staging.wormbase.org/resources/molecule/WBMol:00004019#024--10

There are a few things I'm not sure about:

- Phenotype_not_observed: do they need to be displayed differently?
- Primary targets for RNAi: do Predicted_gene and Transcripts need to be included? What if there are more than 4 entries?
- Multiple entries of Gene: I have seen multiple genes per RNAi and multiple genes per allele. I wonder if we group by genes (under the same phenotype term), do we split them?

Thank you Karen!

**Comment by kyook** [comment]
Hi Sibyl,

Sorry for not getting in touch sooner. I can't access the staging page.

Karen

On Thu, Oct 1, 2015 at 1:45 PM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> I have done a little bit work on the
> phenotypes affected table. I still need to group the rows by phenotype, if
> that's what you like. Here's is the WIP
> http://staging.wormbase.org/resources/molecule/WBMol:00004019#024--10
>
> There are a few things I'm not sure about:
>
>    - Phenotype_not_observed: do they need to be displayed differently?
>    - Primary targets for RNAi: do Predicted_gene and Transcripts need to
>    be included? What if there are more than 4 entries?
>    - Multiple entries of Gene: I have seen multiple genes per RNAi and
>    multiple genes per allele. I wonder if we group by genes (under the same
>    phenotype term), do we split them?
>
> Thank you Karen!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4181#issuecomment-144842871>.
>



-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by sibyl229** [comment]
Hi @kyook sorry, staging is up now.

**Comment by kyook** [comment]
Thanks Sibyl,

Do you have time tomorrow to go over it with me?

Karen

On Thu, Oct 8, 2015 at 1:51 PM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> sorry, staging is up now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4181#issuecomment-146681614>.
>



-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by sibyl229** [comment]
Hi @kyook I have implemented most of the molecule page changes that we discussed: http://staging.wormbase.org/resources/molecule/WBMol:00004019#0245--10 I haven't merged that tables yet. Do we need to make a note whether an experiment is with a transgene or an allele? Should the RNAi table be separate? 

And could you check the widget and field names (and tooltips), and let me know if anything needs to be changed? Thanks.

**Comment by kyook** [comment]
Hi Sibyl,

I love it!  You will need to talk to Chris to make any changes to the RNAi
stuff. For now, I would leave the RNAi table separate and as it was, if
that is possible.
I don't think it is absolutely necessary to make a note if the experiment
is with a transgene or allele, but for new users, that might be useful,
 would you show me how that would look if you did?


On Wed, Oct 14, 2015 at 1:55 PM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> I have implemented most of the
> molecule page changes that we discussed:
> http://staging.wormbase.org/resources/molecule/WBMol:00004019#0245--10 I
> haven't merged that tables yet. Do we need to make a note whether an
> experiment is with a transgene or an allele? Should the RNAi table be
> separate?
>
> And could you check the widget and field names (and tooltips), and let me
> know if anything needs to be changed? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4181#issuecomment-148197488>.
>



-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by sibyl229** [comment]
Hi @kyook Glad you like it :) Here is the last few pieces of the Phenotype Affected widget:
- merging the transgene and variation table (I made a note of the whether it's with a transgene or allele in the details column, please let me know if you want it there)
- putting RNAi table to what it was, I will ask Chris when doing the PATO stuff for WS251

http://staging.wormbase.org/resources/molecule/WBMol:00004019#024--10

**Comment by kyook** [comment]
It's great Sibyl. Please still use the Genes Affected label for the phenotype widget. 

Cheers, 
Karen

**Comment by sibyl229** [comment]
@kyook I was just worried that as the RNAi table doesn’t list any genes, it might be confusing to call it Genes Affected widget. Do you think that’s okay?

**Comment by kyook** [comment]
I think it's ok, rnai objects are based on gene knockouts. Chris can comment when you follow through with him. 

-mobile-

**Comment by sibyl229** [comment]
@kyook Sure. I have it changed to Genes affected.

**Comment by kyook** [comment]
Thanks Sibyl!

-mobile-

**Comment by sibyl229** [comment]
No problem Karen! Closing.
