### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by tuli** [WormBase/website#4184]
I don't recall seeing any instances where a WormBase person has actually helped someone in real time, only via Offline chat. 

Who are the chat operators and do you think we have enough? Do we have some on both sides of the Atlantic, and someone on the US East Coast?

**Comment by tharris** [comment]
Yes, we have. I think we are sufficiently staffed at the moment. This isn't a feature that I want to burden curators with. It's primarily a way for the web team to intervene and interject ourselves into support requests, resolving at least some of them more quickly.

You will note that ALL offline and online transcripts become issues as well.

**Comment by tuli** [comment]
Yes, I notice all the transcripts become issues.

Thanks for clarifying.
