### ISSUE TITLE
  Dear Wormbase administrators, As a bi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4186]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase administrators,<br/>As a bioinformatician in the group of Alexander van Oudenaarden (Hubrecht Institute), I was asked to look at sequencing data from c.elegans. This is gene expression data, and currently the data I have is at the level of sequence names (e.g. B0019.1). I would like to convert this to gene names (e.g. amx-2) but I am unable to find something like a table that would do that for me. Programs such as the wormbase converter, or BioGPS, are able to do this but I would need the full conversion table and that is very hard to get from these programs.<br/>Could you maybe point me in the direction of a table that has all sequence names and the corresponding gene names?<br/>Thanks in advance,<br/>Bastiaan Spanjaard</p>
    
**Reported by:** Bast************** (b.sp*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9

**Comment by epaule** [comment]
if you don't mind that the data is from WS245, you can try the ParaSite BioMart. something like that:
http://goo.gl/u6c1Tp

**Comment by brucebolt** [comment]
Dear Bastiaan,

You can download a file containing all the mappings between sequence names and gene names for the latest release (WS249) from the WormBase FTP server: ftp://ftp.wormbase.org/pub/wormbase/releases/WS249/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS249.geneIDs.txt.gz <ftp://ftp.wormbase.org/pub/wormbase/releases/WS249/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS249.geneIDs.txt.gz>

Best regards,

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD

**Comment by brucebolt** [comment]
Reply from user:

>Dear Bruce,
>
>Thank you very much for your reply! This is very helpful.
>
>Best regards,
>Bastiaan
