### ISSUE TITLE
such-1 needs updating in description, allele+ refs...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4193]
*Help Desk query collected when no chat operators were online. Follow up required.*

such-1 needs updating in description, allele+ refs:
    
**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00013443#04-95db81-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00013443#04-95db81-10</a>
**Browser:** Safari 6.1

**Comment by tuli** [comment]
Dear Alexandra,

Thank you for writing to WormBase.

Could you please send more detail on what updates you are suggesting
we make to the description, allele and references?  I have had a look
in Textpresso and PubMed for recent publications, but have not found
anything, though very new papers may not yet be indexed.

Many thanks,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Alexandra,

Thank you for clarifying your suggestion. I have cc'ed this reply to
the colleagues who are responsible for curation the Descriptions in
WormBase. They will get back to you directly.

Best wishes,

Mary Ann



~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
@rankishore  for you aswell! Sorry, I toggled the assignee.

**Comment by rankishore** [comment]
Corresponding with the User to get a satisfactory description for such-1.

**Comment by rankishore** [comment]
Done, new description will go into WS251.
