### ISSUE TITLE
  I am wondering how to determine the p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4194]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am wondering how to determine the pattern of inheritance for particular alleles that are listed in the database. If it doesn't state the inheritance, can I assume that it is recessive? I notice that sometimes I see it state semi-dominant or dominant. I guess I am wondering if the default is recessive and if it is not recessive then it will state otherwise.<br/>Thanks for your help.<br/>Best,<br/>Jennell</p>
    
**Reported by:** Jenn*** (jtal***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

**Comment by kyook** [comment]
Hi Jennell,

We report what the authors publish, unfortunately, it is often the case
that the authors do not report inheritance patterns of phenotypes- however,
they tend to report dominant or semi-dominant, so it is fair to assume when
the inheritance is not reported, it is probably recessive.

Hope that helps.
Karen

On Fri, Sep 18, 2015 at 10:06 AM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I am wondering how to determine the pattern of inheritance for
> particular alleles that are listed in the database. If it doesn't state the
> inheritance, can I assume that it is recessive? I notice that sometimes I
> see it state semi-dominant or dominant. I guess I am wondering if the
> default is recessive and if it is not recessive then it will state
> otherwise.
> Thanks for your help.
> Best,
> Jennell
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4194. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4194>.
>
> Reported by: Jennell (jtalley@ggc.edu)
> 18 Sep 15 17:08
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/45.0.2454.93 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by rankishore** [comment]
Guess the User is satisfied with the reply, closing this issue.
