### ISSUE TITLE
  Tree display broken -on staging and l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4195]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Tree display broken -on staging and live site</p>
    
**Reported by:** Dani********** (dani*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by draciti** [comment]
I was trying to access it from
https://www.wormbase.org/species/c_elegans/gene/WBGene00003322#01-f365e2g-10

**Comment by rankishore** [comment]
tree display is still broken

**Comment by tharris** [comment]
@ranjana, this was fixed long ago but can become unreponsive if there is heavy data mining activity.
