### ISSUE TITLE
  the website doesn't work  What were y...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4199]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;the website doesn't work</p><p>What were you doing? <br />&nbsp;&nbsp;searching genes</p>
    
**Reported by:** rach*** (rach********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by rankishore** [comment]
Todd replied: 
I’m not seeing anything out of the ordinary. Are you searching for something specific and unable to find it?
