### ISSUE TITLE
  Is there a way to query homology for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4203]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a way to query homology for a list of WB IDs?  <br/>I'd like to see if a subset of pseudogenes are conserved in briggsae or other (non-elegans) Caenorhabditis species.</p>
    
**Reported by:** Virg**** (vsla***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36

**Comment by chris-grove** [comment]
Hi Virginia,

 You can perform this task using the WormBase ParaSite BioMart:

http://parasite.wormbase.org/biomart/martview/a254b58b11ec079344f76d4098541cc9

Under "Filters" provide the list of gene IDs or gene names, and under
"Attributes" select the "Homologues" radio button. Under the "ORTHOLOGUES"
selection list, scroll down to which species you would like orthology data
for and check the corresponding "... gene stable ID" box for each species.
Click on "Results" at the top and you should get a table of orthologs.

Let me know if you need any help with this process. I'd be happy to guide
you through it.

Best,

Chris Grove
