### ISSUE TITLE
  Hi,  How can I get the sequence of a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4204]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>How can I get the sequence of a custom list of genes?  <br/>I tried to use the "analyze list" feature in WormMine using the "add column" button, but when I select "sequence" it doesn't work.<br/>It would be good if the "analyze list" feature would make it easy to display any of the information that appears on the gene page, but in a batch way that we can download.</p>
    
**Reported by:** Simo** (simo***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36

**Comment by chris-grove** [comment]
Hi Simona,

 You can do this currently using the WormBase ParaSite BioMart:

http://parasite.wormbase.org/biomart/martview/ea3d43c39530b104188d181d2d050fc5

Under the "Filters" heading, enter your list of genes. Under "Attributes", select the "Sequences" radio button, then open the "+SEQUENCES" section below and specify what sequences you would like for each gene.

Hope that helps. Let me know if you need any help.

Best,

Chris Grove
