### ISSUE TITLE
I have a question about bulk downloading ortholog ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4205]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have a question about bulk downloading ortholog group sequence data.  I'm not sure who at wormbase I should talk to.

Thanks,

Lisa
    
**Reported by:** Lisa********* (lisa****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Safari 6.2.6

**Comment by epaule** [comment]
from Chris:

I'd be happy to discuss options with you. Currently, I would recommend
using the WormBase ParaSite BioMart tool:

http://parasite.wormbase.org/biomart/martview/ea3d43c39530b104188d181d2d050fc5

for retrieving orthologs, and then sequences for the orthologs retrieved.
