### ISSUE TITLE
  more for information, from a series o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4207]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;more for information, from a series of posts on the forum:<br/>http://forums.wormbase.org/index.php?topic=2622.msg6654;topicseen#msg6654<br/>it's likely that F54D7.6 which is annotated as a pseudogene is actually a gene.</p>
    
**Reported by:** Stev************ (stev***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)

**Comment by gw3** [comment]
Converted to a CDS.
