### ISSUE TITLE
I appreciate if you tell me which C. elegans genom...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4210]
*Help Desk query collected when no chat operators were online. Follow up required.*

I appreciate if you tell me which C. elegans genome release is using in this database.
    
**Reported by:** Hito************* (nish************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-3-6">http://www.wormbase.org/#012-3-6</a>
**Browser:** Chrome 45.0.2454.99

**Comment by Paul-Davis** [comment]
Hi Hitoshi,

We are using the current assembly WBcel235 which came into existence in 
WS235

http://www.wormbase.org/species/c_elegans#3--10

Thanks

Paul



On 25/09/2015 10:08, no-reply@wormbase.org wrote:
> offline chat I appreciate if you tell me which C. elegans genome 
> release is using in this database.
>
> Submitted From:
>   http://www.wormbase.org/#012-3-6 http://www.wormbase.org/#012-3-6 
> <http://www.wormbase.org/http://www.wormbase.org/#012-3-6>
>
> This issue has been assigned ticket number: #4210. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4210>.
>
> Reported by: Hitoshi Nishimura (nishimura@lif.setsunan.ac.jp)
> 25 Sep 15 09:10
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
