### ISSUE TITLE
  Hello, why when I download data from ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4211]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>why when I download data from the variants call in the gff3 format I don't see the variants from the mutated strains from the The million mutation project? <br/>These ones:<br/>VC10xxx strains were isolated after UV/TMP mutagenesis<br/>VC20xxx strains were isolated after EMS mutagenesis<br/>VC30xxx strains were isolated after ENU mutagenesis<br/>VC40xxx strains were isolated after EMS+ENU mutagenesis<br/>Thank you in advance.</p>
    
**Reported by:** Mich*** (mish**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by tuli** [comment]
Dear Michael,

Thank you for writing to WormBase. I apologise for the delay in my response.

I have checked the file c_elegans.PRJNA13758.WS250.annotations.gff3
and I see e.g.

I Million_mutation point_mutation 722 722 . + .
variation=WBVar00323243;public_name=gk100000;strain=VC40072;substitution=C/T

Perhaps I have misunderstood the nature of you query. If so please
write again giving details of which file you are looking at.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
User happy.
