### ISSUE TITLE
Julie Ahringer (ja219@cam.ac.uk): The genes B0348....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4212]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Julie Ahringer (ja219@cam.ac.uk): The genes B0348.6a.1 and B0348.6a.2 encode the same proteins, but have different transcripts (the .2 isoform has an intron in the 3'UTR).  So these should have different transcript lengths.  But both are annotated to have a transcript length of 1234nt.  This must be an error.  Does this happen systematically?</br>Julie Ahringer (ja219@cam.ac.uk): Sorry, I don't have time to chat on this, you can email me back!
    
**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002061#06e-9fbd-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00002061#06e-9fbd-3</a>
**Browser:** Chrome 45.0.2454.99

**Comment by Paul-Davis** [comment]
Dear Julie,

Thank you for pointing this out.

It would appear that the length calculation is taking the start and end 
co-ordinate of the transcript and calculating a span length rather than 
calculating the length of the transcript.

We will get this fixed asap.

Paul


On 25/09/2015 17:14, WormBase Helpdesk wrote:
>
> /Help Desk chat transcript. Issue can be closed if question was 
> resolved in chat./
>
> Julie Ahringer (ja219@cam.ac.uk <mailto:ja219@cam.ac.uk>): The genes 
> B0348.6a.1 and B0348.6a.2 encode the same proteins, but have different 
> transcripts (the .2 isoform has an intron in the 3'UTR).  So these 
> should have different transcript lengths.  But both are annotated to 
> have a transcript length of 1234nt.  This must be an error.  Does this 
> happen systematically?
> Julie Ahringer (ja219@cam.ac.uk <mailto:ja219@cam.ac.uk>): Sorry, I 
> don't have time to chat on this, you can email me back!
>
> *Reported by:* Juli********** (ja21*********/)
> */Submitted from:* 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00002061#06e-9fbd-3
> *Browser:* Chrome 45.0.2454.99
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/4212>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
It looks like the method for calculating the transcript length is only doing a span, rather than using the individual transcript exons to generate a transcript length.

**Comment by sibyl229** [comment]
Hi @Paul-Davis Are these the transcript exons? I re-made the table (attached below) with sum of the exon lengths. Could you check if it's correct now? Thanks!

```$VAR1 = bless( {
  'source' => 'WormBase',
  'stop' => '6754',
  'store' => bless( {
    'dumpdir' => '/tmp',
    'settings_cache' => {
      'serializer' => 'Storable',
      'compress' => '0',
      'autoindex' => '1',
      'index_subfeatures' => '1'
    },
    'namespace' => undef,
    'writeable' => undef,
    'seqfeatureclass' => 'Bio::DB::SeqFeature',
    'dbh' => bless( {}, 'DBI::db' ),
    'is_temp' => undef,
    'class_loaded' => {
      'Bio::DB::SeqFeature' => 76
    }
  }, 'Bio::DB::SeqFeature::Store::DBI::mysql' ),
  'primary_id' => '13553561',
  'ref' => 'V',
  'name' => undef,
  'is_circular' => 0,
  'score' => undef,
  'phase' => undef,
  'strand' => -1,
  'type' => 'exon',
  'attributes' => {
    'load_id' => [],
    'parent_id' => [
      'Transcript:B0348.6c.2'
    ]
  },
  'start' => '6589'
}, 'Bio::DB::SeqFeature' );
$VAR2 = bless( {
  'source' => 'WormBase',
  'stop' => '7110',
  'store' => $VAR1->{'store'},
  'primary_id' => '13553797',
  'ref' => 'V',
  'name' => undef,
  'is_circular' => 0,
  'score' => undef,
  'phase' => undef,
  'strand' => -1,
  'type' => 'exon',
  'attributes' => {
    'load_id' => [],
    'parent_id' => [
      'Transcript:B0348.6c.2'
    ]
  },
  'start' => '6913'
}, 'Bio::DB::SeqFeature' );
$VAR3 = bless( {
  'source' => 'WormBase',
  'stop' => '7390',
  'store' => $VAR1->{'store'},
  'primary_id' => '13554063',
  'ref' => 'V',
  'name' => undef,
  'is_circular' => 0,
  'score' => undef,
  'phase' => undef,
  'strand' => -1,
  'type' => 'exon',
  'attributes' => {
    'load_id' => [],
    'parent_id' => [
      'Transcript:B0348.6c.2'
    ]
  },
  'start' => '7158'
}, 'Bio::DB::SeqFeature' );
$VAR4 = bless( {
  'source' => 'WormBase',
  'stop' => '7609',
  'store' => $VAR1->{'store'},
  'primary_id' => '13554326',
  'ref' => 'V',
  'name' => undef,
  'is_circular' => 0,
  'score' => undef,
  'phase' => undef,
  'strand' => -1,
  'type' => 'exon',
  'attributes' => {
    'load_id' => [],
    'parent_id' => [
      'Transcript:B0348.6c.2'
    ]
  },
  'start' => '7433'
}, 'Bio::DB::SeqFeature' );
$VAR5 = bless( {
  'source' => 'WormBase',
  'stop' => '7822',
  'store' => $VAR1->{'store'},
  'primary_id' => '13554474',
  'ref' => 'V',
  'name' => undef,
  'is_circular' => 0,
  'score' => undef,
  'phase' => undef,
  'strand' => -1,
  'type' => 'exon',
  'attributes' => {
    'load_id' => [],
    'parent_id' => [
      'Transcript:B0348.6c.2'
    ]
  },
  'start' => '7651'
}, 'Bio::DB::SeqFeature' );```

![screen shot 2015-09-28 at 11 00 56 am](https://cloud.githubusercontent.com/assets/1753893/10139313/4738766a-65d0-11e5-8c3f-cbc49a17f094.png)

**Comment by Paul-Davis** [comment]
Hi @sibyl229,

Thanks for the fast action :)

Yes, looks great.

Paul

**Comment by sibyl229** [comment]
Hi @Paul-Davis Thank you for checking the draft. the transcript length issue should be fixed on staging: http://staging.wormbase.org/species/c_elegans/gene/WBGene00002061#0-f-3 This includes gene, cds, transcript, and protein page, where transcript length is displayed.

**Comment by chris-grove** [comment]
@Paul-Davis  can we close this issue?

**Comment by Paul-Davis** [comment]
I guess it can as it's fixed on staging.....what's the procedure for pushing the change for WS250?

Do I assign the WS250 milestone and leave the ticket open?

**Comment by tharris** [comment]
It's already part of the WS250 release. The "under testing" tag is added once we believe development is ready for testing and ask that stakeholders test and close issue when complete. (They may also sometimes be closed by branch merges if the developer has specifically closed the issue in commit, although this isn't always feasible).

**Comment by chris-grove** [comment]
OK, I will close then.
