### ISSUE TITLE
Trying to programmatically access gene info. Anyth...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4213]
*Help Desk query collected when no chat operators were online. Follow up required.*

Trying to programmatically access gene info. Anything using the field denotation is broken. Server Error: 500 everytime.
    
**Reported by:** Jare********* (jare*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_developers/API-REST/Feature#0--10">http://www.wormbase.org/about/userguide/for_developers/API-REST/Feature#0--10</a>
**Browser:** Chrome 45.0.2454.99

**Comment by rankishore** [comment]
From Todd:
My apologies for the difficulties. The data mining server is currently under heavy load which can sometimes lead to 500 errors like you’ve encountered.

Please note that the documentation isn’t entirely current. I would encourage you to open the developer console on your browser and inspect the REST requests that the website makes. It does this on a per-widget basis which is much more convenient (and rapid) for fetching related data than through individual fields.

**Comment by rankishore** [comment]
Hi Todd,

Thanks for such a quick response. One last question - how can I return the widget overview as XML or JSON to make it easier to parse the field I want (description in this case). I've tried every way I've used for other databases to no avail.

Thanks again,
-Jared

**Comment by tharris** [comment]
Contacted user 9/29. No response.

Hi Jared -

Have you tried simply passing the Content-Type header for the format of data you prefer? This is the defacto standard for RESTful APIs.

curl -X GET -H "Content-Type: application/json" http://www.wormbase.org/rest/widget/gene/WBGene00006763/overview

Or if you prefer:
 text/xml
 text/yaml

Hope this helps.

Todd
