### ISSUE TITLE
I do not find this transcript in the paper from th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4214]
*Help Desk query collected when no chat operators were online. Follow up required.*

I do not find this transcript in the paper from the "life span variant" phenotype. The transcript F43D9.4 is in that paper and has the exact value (88) under the conditions reported for F43D9.6. I believe this is a mistake for F43D9.6, but if I'm wrong please let me know.
    
**Reported by:** mike****** (wals****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004798#fbci2345679-08d1aeg-5">http://www.wormbase.org/species/c_elegans/gene/WBGene00004798#fbci2345679-08d1aeg-5</a>
**Browser:** Chrome 41.0.2272.118

**Comment by chris-grove** [comment]
Hi Mike,

 This is most likely an artifact of our RNAi mapping pipeline, as the
Ahringer clone used for this annotation partly overlaps the F43D9.6 gene:

http://www.wormbase.org/species/all/pcr_oligo/sjj_F43D9.4#01--10-0

This artifact of mapping is currently being fixed. Thanks for the report.

Best,

Chris Grove
