### ISSUE TITLE
  Is the legacy site gone for good? Had...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4217]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is the legacy site gone for good? Had some very useful stuff I can't reach anymore.</p>
    
**Reported by:** Bill******* (mohl********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by chris-grove** [comment]
Hi Bill,

 I am still able to access the legacy site via the WormBase homepage
footer (under the "About" header). Please keep in mind that the data on
the legacy site is more than 3 years old (frozen at the WS230 release,
March 2012).

What functionality are you still using?

Thanks!

Chris Grove
