### ISSUE TITLE
GO_term names on staging

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#4220]
Hi,

WS250 included a change to the GO_term model that removed the Term tag and now placed the GO term name in the Name tag.

This may be causing some issues with GO_term display, as the GO widget on staging now shows the GO term ID in both the Term ID and Term columns:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00001980

The same thing also is happening on pages that reference GO terms, e.g., paper pages:
http://staging.wormbase.org/resources/paper/WBPaper00030820

Thanks,
--Kimberly

**Comment by sibyl229** [comment]
Hi @vanaukenk The GO term label now displays based on the Name tag. Thanks

**Comment by vanaukenk** [comment]
Looks great; thanks, @sibyl229 !

**Comment by vanaukenk** [comment]
Hi,

It looks like the GO term model change from Term -> Name is also causing an error with the display of GO terms in the Gene Ontology widget of WBProcess pages:

For an example, see the Gene Ontology widget here:
http://www.wormbase.org/resources/wbprocess/WBbiopr:00000001

Error Message:
Caught exception in WormBase::Web::Controller::REST->widget "Invalid object tag "Term" at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Wbprocess.pm line 320." 

Thanks,
--Kimberly

**Comment by sibyl229** [comment]
Done.
