### ISSUE TITLE
Display of entity-quality phenotype annotations

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4221]
@sibyl229  @tharris 
I'd like to start the discussion about how to best display the new phenotype annotation style that we've added. As a reminder, the ?Phenotype_info model, usually used as a hash in phenotype annotations, has recently had some tags added to allow phenotype curators to annotate entities and associated qualities to phenotype annotations, in addition to the existing WBPhenotype term. The WS250 ?Phenotype_info model had:

?Phenotype_info
    Anatomy_term  ?Anatomy_term  #Evidence
    Phenotype_assay  Life_stage  ?Life_stage  #Evidence 

and WS251 now has:

?Phenotype_info
    EQ_annotations  Anatomy_term  ?Anatomy_term  ?PATO_term   #Evidence
                                Life_stage  ?Life_stage  ?PATO_term   #Evidence
                                GO_term  ?GO_term  ?PATO_term  #Evidence
                                Molecule_affected   ?Molecule   ?PATO_term   #Evidence

The point of this is to allow us to specifically annotate to various entities affected as part of the phenotype without having to create all permutations of phenotype terms. Currently, anatomy and life stage terms are displayed on gene page "Phenotypes" widgets. For an anatomy example see the ced-12 distal tip cell migration variant phenotype:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000426#0-b-3

It would be good if we could somehow extend the existing anatomy term display to include the PATO  term (generally defaults to "abnormal") and similar displays for life stage, GO term, and molecule affected.

**Comment by sibyl229** [comment]
Hi @chris-grove do you have an example of PATO_term in ace format? When I try to retrieve PATO_term objects from ACeDB (WS251), all I get is its ID. None of the other attributes shown in the schema are populated. I'm not sure if this is the expected the outcome. Thank you very much!

@tharris

**Comment by chris-grove** [comment]
@sibyl229  There was a PATO.ace file that we uploaded with the Citace upload that should have all PATO terms and their information. Here's an example of an entry:

```
PATO_term : "PATO:0000460"
Name	"abnormal"
Definition	"A quality inhering in a bearer by virtue of the bearer's deviation from normal or average."
Synonym	"aberrant"
Status	"Valid"
Parent	"PATO:0000069"
Version	"PATO ontology releases/2015-04-09"
```

**Comment by chris-grove** [comment]
test
'''
testing
'''

**Comment by sibyl229** [comment]
Thank you @chris-grove !

**Comment by chris-grove** [comment]
@sibyl229  No problem. I'm looking at WS251 now and see that it looks like the PATO.ace file maybe didn't get into the build as I had planned. I'll need to investigate.

As for your first layout proposal, that looks good. The EQ annotations could probably be under a column header "Entities Affected" with the ?Anatomy, ?Life_stage, ?GO_term, or ?Molecule listed first, followed by the PATO term, like:

"vulva, abnormal"
or
"axon, mislocalised"

**Comment by sibyl229** [comment]
@chris-grove sounds good! I will implement the changes you suggested :)

**Comment by chris-grove** [comment]
@khowe @Paul-Davis 
Can you see if the ?PATO_term class objects were read into WS251? I uploaded a "pato.ace" file for citace; I probably should have communicated with you to make sure it made it into the build.

**Comment by chris-grove** [comment]
@sibyl229  OK, sounds good! Thanks!

**Comment by chris-grove** [comment]
@sibyl229  For what it's worth, here's a Dropbox link to the pato.ace file:

https://dl.dropboxusercontent.com/u/4290782/pato.ace

**Comment by khowe** [comment]
The PATO_term class *was* included in the citace upload for WS251. However, the build config contains an explicit list of classes to include from citace (legacy from when citace included many more things than were needed/relevant for the final database). When a new class gets added, it needs to be explicitly added to the config. This didn't happen for ?PATO_term. 

This is fixed for WS252. @Paul-Davis , this needs to be added to the models SOP (i.e. when the models are finalised, any new classes need to be added to elegans.config)

**Comment by chris-grove** [comment]
@khowe  OK, thanks for the explanation. @sibyl229  I suppose we can wait for WS252 to display these, but in the meantime we could always make the default PATO term "abnormal" which will very likely be the most common PATO term used anyway.

**Comment by sibyl229** [comment]
Hi @chris-grove I put up the phenotype table with PATO information on staging now. It defaults to abnormal. http://staging.wormbase.org/species/c_elegans/gene/WBGene00000426#0-c-3 Is it okay? Thank you!

**Comment by chris-grove** [comment]
Hi @sibyl229 , OK cool!  It's getting there.
It looks like the current display on staging only has two columns, Entity and Supporting Evidence, instead of three (Phenotype, Entities Affected, Supporting Evidence):

![screen shot 2015-12-17 at 2 47 48 pm](https://cloud.githubusercontent.com/assets/611382/11884265/56c2700e-a4cd-11e5-9d3f-8c5e43995114.png)

Could the table have those three columns: Phenotype, Entities Affected, Supporting Evidence ?

Also, it isn't clear which phenotype annotation (in-line supporting evidence) the entity is associated with. In this case, "DTC, abnormal" is associated with each of these annotations (to 6 different alleles), but they could potentially each have their own annotation. Could there be a display where each allele (or RNAi or transgene) has it's own Entity line? In this case, we would see "DTC, abnormal" 6 times, one for each annotation.

Thanks!!!

**Comment by sibyl229** [comment]
Hi @chris-grove  Thanks for the quick response!

It can have three columns. Actually without any extra processing, it would have 3 columns. But I extracted the Phenotype out into the grey row. Basically the grey row partitions the table based on the phenotype. This is the first level grouping.

The normal row groups all the supporting evidences that share the Same annotation (same the entity and PATO term). So the six allele only show up in the same row Because they share the annotation: DTC, abnormal. Suppose if some of them have "DTC, abnormal number 2", there would be another row in the distal tip cell migration variant phenotype partition, that include these alleles. This is the second level grouping, but I couldn't find an example to show that. Do you have an example?

The reason to do the grouping is to avoid having users read through repetitive wordings just to figure out which part differs. Similar things were done for the Gene Ontology widget on Gene page, and a widget on Molecule page. I should have explained these earlier. Please let me know what you think. Thanks a lot!

**Comment by chris-grove** [comment]
@sibyl229   Oh, OK, that sounds great! I'm a little concerned that the "Entity" column header will confuse people. Could we possibly push the "Entity" into the box with the entities displayed, similar to how "Allele" shows up just above the alleles to the right? And then keep the column header "Phenotype" at the top where "Entity" is now? Does that make any sense?

**Comment by sibyl229** [comment]
Hi @chris-grove Right, the column should be named Phenotype. Is this what you have in mind? http://staging.wormbase.org/species/c_elegans/gene/WBGene00000426#0-c-10 Is there anything else?

**Comment by chris-grove** [comment]
@sibyl229  Yes, looks good. Can we also change the "Entity" to "Entities Affected"?

**Comment by chris-grove** [comment]
@sibyl229 
It seems the PATO name reference has reverted to a PATO ID, which is unreadable to users:

![screen shot 2016-01-04 at 12 05 10 pm](https://cloud.githubusercontent.com/assets/611382/12099140/7604b99c-b2db-11e5-867f-83fc1ec696cd.png)

Perhaps you're in the middle of working on it.

Also, can we change "Entity" to "Entities affected"?

**Comment by chris-grove** [comment]
@sibyl229 @tharris 
FYI, now the phenotype widgets on the live site are showing different column displays for different genes. For example, daf-3 phenotypes widget looks like this:
![screen shot 2016-01-04 at 3 22 46 pm](https://cloud.githubusercontent.com/assets/611382/12103460/3edbc282-b2f7-11e5-8d79-7ab973265826.png)
with three columns, the first two labeled as "_Phenotype" and "Phenotype", whereas eat-5 looks like this:
![screen shot 2016-01-04 at 3 23 01 pm](https://cloud.githubusercontent.com/assets/611382/12103477/576c6d7e-b2f7-11e5-9771-7a0da9950565.png)
which looks more like what we talked about in this issue above.

**Comment by tharris** [comment]
We will have to systematically expire ALL phenotype widgets from the cache if we want to fix. Do note that the "->name" problem related to those that lacked any PATO term; if a PATO term was present, the display was showing "$pato_term->name"

**Comment by chris-grove** [comment]
OK thanks @tharris 
I'll just note that the "PATO->name" issue only exists on staging. Compare:
http://www.wormbase.org/species/c_elegans/gene/WBGene00000426#0c--3
to
http://staging.wormbase.org/species/c_elegans/gene/WBGene00000426#0c--3

**Comment by tharris** [comment]
Yes, I ficed that in production

**Comment by chris-grove** [comment]
OK, great, thanks!

**Comment by chris-grove** [comment]
@sibyl229  I'd like to revisit this issue, but I'll close this ticket and create a new one, referencing this one
