### ISSUE TITLE
 Server Error: 500 at  rest/widget/all/all/downloa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4224]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/all/all/downloads?download=1&amp;content-type=text%2Fhtml">rest/widget/all/all/downloads</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "Can't locate object method "new" via package "WormBase::API::Object::All" (perhaps you forgot to load "WormBase::API::Object::All"?) at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API.pm line 326." </p>
    
**Reported by:** mits**************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//rest/widget/all/all/downloads">rest/widget/all/all/downloads</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/6.2.6 Safari/537.85.15

**Comment by sibyl229** [comment]
Closed for duplication with #4105 
Trying to download widgets from species index used to incorrectly request for rest/widget/all/all/ . That issue has be resolved in #4105
