### ISSUE TITLE
Hillel Schwartz (hillels@caltech.edu): 1) If I'm l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4231]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Hillel Schwartz (hillels@caltech.edu): 1) If I'm logged in to WormBase, why do I need to provide my name and email at the start of this bug report / get help procedure?</br>Hillel Schwartz (hillels@caltech.edu): 2) Why is there an inescapable default to chat when I'd really prefer to write a bug report and it would probably be easier for the WormBase person to handle a bug report than to interact on chat?</br>Hillel Schwartz (hillels@caltech.edu): 3) The actual reason I opened the bug-report (now replaced with chat) interface in the lower right of the window: I'm having a problem with accessing some of the old mapping data in the Tree Display (eg http://www.wormbase.org/tools/tree/run?name=WBGene00006756;class=Gene;expand=2_point#2_point ). To the right of Mapping_data, to the right of 2_point, there is a series of numbers. Each of these represents the report of one mapping experiment, and each SHOULD be a hyperlink to that report. They aren't, though they are on the legacy WormBase site. I assume this is a bug of some kind.</br>Hillel Schwartz (hillels@caltech.edu): 4) Further: at some point in likely the very distant past, examining the ACeDB-style mapping data would actually give a list of experiments with some headline description of their contents (I don't recall the format, but on the main page for the gene you could at least see a list of experiments where each item in the list named the other genes involved). Now on the WormBase 2.0 site and on the Legacy site I get only a blind list of numbers that on the Legacy site I can use as links to the experiment. This is obviously hugely inferior to being able to see at a glance which ones might be useful to me. What happened to that old display? Am I merely looking in the wrong place?</br>Hillel Schwartz (hillels@caltech.edu): 5) And I note that no-one is chatting back to me. Quite right, too: it's dinner time on the West Coast and absurd times most everywhere else WormBase has people. But wouldn't it have been better if I still had access to the bug report interface, instead of only having the option of "chatting"?</br>Hillel Schwartz (hillels@caltech.edu): 6) If I close the chat window I have to reenter my name and email, even though as I noted before I'm logged in to WormBase and even though I've previously logged in to Chat.</br>Hillel Schwartz (hillels@caltech.edu): 7) Possibly disregard my previous question about being able to look at the mapping information in a more clearly explained, tabular form - that seems to be available in "Mapping data", separate from the Tree Display.</br>Hillel Schwartz (hillels@caltech.edu): 8) I now see some of the issue with logins could be a result of using multiple tabs. But who doesn't use multiple tabs?
    
**Reported by:** Hill*********** (hill***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/tree/run?name=WBGene00006756;class=Gene;expand=2_point#2_point">http://www.wormbase.org/tools/tree/run?name=WBGene00006756;class=Gene;expand=2_point#2_point</a>
**Browser:** Chrome 45.0.2454.101

**Comment by brucebolt** [comment]
Response from Todd:

>Hi Hillel -
>
>Thanks for your feedback. Some explanation is in order, then I'll address your comments in turn below. The "chat" function is really just he same old feedback form we have had for three years.
>
>Normally, in off hours, operators log off, and the chat just becomes a plain old submission form. If an operator is online, you'll be prompted with the option to chat. In this case, I was online but downstairs making dinner. In either case, transcripts are posted to our issue tracker so we can follow up.
>
>The intent? Short circuit some queries and get users help faster, and establish greater rapport with users. It's incredibly hard to get feedback from users in this business.
>
>I address your points below:
>
