### ISSUE TITLE
peter (peter.roy@utoronto.ca): you still there Chr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4235]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

peter (peter.roy@utoronto.ca): you still there Chris- lost you</br>Chris: Hello, yep, I'm here</br>Chris: I was just saying...</br>Chris: If you click on either of the SL glyphs in the genome browser, you will be directed to the "Sequence Feature" pages for each splice leader</br>Chris: http://www.wormbase.org/species/c_elegans/feature/WBsf132067#034125--10</br>Chris: http://www.wormbase.org/species/c_elegans/feature/WBsf006401#012345--10</br>Chris: In the "Molecular Details" widget is listed the flanking sequences</br>Chris: Which should, at the sequence level at least, pinpoint the splice location</br>peter (peter.roy@utoronto.ca): I see!  Thanks!  If I have more questions, will you be around for a bit?</br>Chris: Yes indeed :)</br>peter (peter.roy@utoronto.ca): On the first jpeg, there are grey SL1 dots- what are those?</br>peter (peter.roy@utoronto.ca): SL1_X_12749500</br>Chris: Hmmmm, I'm not sure, but let me take a look</br>Chris: I'm still trying to pull up the right GBrowse tracks to see what you sent me</br>peter (peter.roy@utoronto.ca): I clicked a bunch of transplice tracks to get it</br>Chris: OK got it</br>Chris: Hmm, yeah, I can't really tell what these are as there is no more information available</br>Chris: but I'll send an e-mail to our sequence team and CC you to see if they can better explain</br>peter (peter.roy@utoronto.ca): I can explain why it is important if need be.</br>Chris: OK sure</br>peter (peter.roy@utoronto.ca): We engineered an N-terminal RFP tag on a fosmid, but suspect that it is not contiguous with the PGP-14 coding sequence.  One thought was that the transcript is being transpliced after the RFP coding sequence.  The gray SL1 dots in the first jpeg, if the site of transpliing would be consistent with that.  The red and green SL1 and SL2 marks, however, would not.</br>Chris: I see</br>Chris: Well, it would seem strange to me if those were valid splice sites since it clearly seems that the open reading frame begins upstream of that location</br>peter (peter.roy@utoronto.ca): predicted by some computer though!</br>peter (peter.roy@utoronto.ca): the gray dots may represent real data</br>Chris: Yes, I'm not sure which features here are predicted versus evidence-based</br>Chris: are you saying that the open reading frame is only a prediction?</br>Chris: I would have to look more closely</br>Chris: I don't see another ATG in the first exon</br>peter (peter.roy@utoronto.ca): yes, the start codon of the ORF is almost certainly based on prediction and not evidence</br>Chris: I see</br>peter (peter.roy@utoronto.ca): correct, but there is an inframe ATG in the second one.</br>Chris: got it</br>peter (peter.roy@utoronto.ca): and if the grey dot represents transplicing, then that in frame one could be real</br>Chris: OK, our sequence team should certainly be able to clarify what's going on here.</br>Chris: Right, I see what you mean</br>peter (peter.roy@utoronto.ca): Thanks Chris</br>Chris: No problem Peter</br>Chris: OK, I've just sent the e-mail</br>Chris: They are all in England, so we may not hear back until tomorrow (or possibly Monday)</br>Chris: Sorry, I couldn't be of more help</br>peter (peter.roy@utoronto.ca): No- you are very helpful- thank you.  I'll sit tight until Monday to learn about those grey features.</br>peter (peter.roy@utoronto.ca): Thanks and have a nice weekend!</br>Chris: OK sounds good</br>Chris: Thank you! You too!
    
**Reported by:** pete* (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#01-23-6">https://www.wormbase.org/#01-23-6</a>
**Browser:**

**Comment by chris-grove** [comment]
Screenshot of the splice leader annotations in question (SL1_X_12749500_12749501(-)):

![x_12749149 12750149](https://cloud.githubusercontent.com/assets/611382/10255024/52986a36-68fc-11e5-9fd0-46968d05d763.png)

E-mailed Hinxton, CC'ed Peter

**Comment by chris-grove** [comment]
FWIW, here's another view of the locus with mid-larval stage RNA-Seq data (containing the 5'-most reads I could see among all the RNA-Seq tracks):
![pgp-14_splice_leaders](https://cloud.githubusercontent.com/assets/611382/10259507/f4239fee-691d-11e5-84cb-bcbc794bd475.png)

**Comment by chris-grove** [comment]
@khowe and @gw3  responded to Peter, resolved
