### ISSUE TITLE
Hi, 

How can I retrieve name, description, and ch...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4238]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, 

How can I retrieve name, description, and chromosome location for a gene list using Wormbase?

Thanks!
Sandra
    
**Reported by:** sand** (sand***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide#234150--10">http://www.wormbase.org/about/userguide#234150--10</a>
**Browser:** Chrome 45.0.2454.101

**Comment by chris-grove** [comment]
Hi Sandra,

 You can use our WormMine tool to get this. You can find a link to WormMine under the WormBase homepage "Tools" menu:

http://www.wormbase.org/tools/wormmine/begin.do

Click on the "QueryBuilder" tab, and click on the "Import query from XML" link in the "QueryBuilder" panel at the left on the resulting page. Paste the following query XML into the search box:

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.strand Gene.chromosomeLocation.start Gene.chromosomeLocation.end Gene.briefDescription" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>
```

This query will return the information for all genes. To specify a list of genes, use the WormMine Lists functionality. Create a list of genes and then constrain the query to that list of genes.

If you need help with any of this, let me know.


Best,

Chris Grove
