### ISSUE TITLE
dpy-17 search is incorrectly redirected

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4239]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;A recent thread on the forum (http://forums.wormbase.org/index.php?topic=2631) uncovered some issues with the search function to identify balancers that cover a gene of interest. It appears that the data are incomplete and/or the search function not working as expected. For example, searching 'dpy-17' under Rearrangement returns hT2 only. However, the mT1 summary page explicitly lists dpy-17 as a positive marker.</p>
    
**Reported by:** Haro******** (smit******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/6.2.5 Safari/537.85.14

**Comment by tuli** [comment]
Webteam, I've looked at the data in acedb and cannot fathom why a Rearrangement query for dpy-17 only brings up hT2

Could you have a look please.

**Comment by tuli** [comment]
@sibyl229 
Have you been able to have a look at this?

**Comment by sibyl229** [comment]
Hi @tuli searching for dpy-17 should work correctly now: http://staging.wormbase.org/search/rearrangement/dpy-17 Luckily this isn't a problem with indexing, but with how to identify search result as exact match and redirect. And thanks for the reminder :)

**Comment by tuli** [comment]
Thanks @sibyl229 
Fab. Tested and closing. 

User sent response.
