### ISSUE TITLE
  How can I download ALL CURRENT gene e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4240]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I download ALL CURRENT gene expression patterns from wormbase?</p>
    
**Reported by:** Xiao******* (sdum*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36

**Comment by draciti** [comment]
Hi Xiaopeng,
you can download all current gene expression patterns from our ftp site.

this is the link for WS251
ftp://caltech.wormbase.org/pub/wormbase/expr_dump/expr_pattern.ace.20150928

Let us know if you have any questions.

Thanks,
Daniela


>
> Question:
>   How can I download ALL CURRENT gene expression patterns from wormbase?
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #4240. Follow progress on our
> issue tracker.
>
>  Reported by: Xiaopeng Ma (sdumaxiaopeng@163.com)
>  05 Oct 15 03:32
>
>  Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like
> Gecko) Chrome/33.0.1750.154 Safari/537.36     This question was reported
> via the web interface at wormbase.org. You can also email us directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>

**Comment by draciti** [comment]
user's reply 
Great! I got it. Thank you very much for such kind help! :-)
With best wishes!

-xiaopeng
