### ISSUE TITLE
Balancer track on Gbrowse - labels need work

### ISSUE THREAD

**Issue by khowe** [WormBase/website#4241]
Relates to #1717. In Gbrowse, the balancers are being displayed but have no labels, and switching on labels has no effect. On mouse-over, the pop-up refers to lots of "ARRAY(...)". 

Labels also missing from Jbrowse.

**Comment by scottcain** [comment]
I 'fixed' the labels (above the glyph) and descriptions (below), but they are a little goofy.  If the attribute "balancer_type" is set (which I assume it always or nearly always is), then the label and description will be the same.  I'm guessing that's not really the desired behavior.  Perhaps the label should be the feature's "balancer" attribute?

**Comment by khowe** [comment]
Yes, perhaps we should have chosen a better name for that "balancer" attribute. Its value corresponds to an Acedb object reference (class:name), where the class is always Rearrangement in this case. But the the most useful label would be a composite of the name and type, e.g.

hT2 (Translocation)

...with the name linked to the WormBase page for the Rearrangement object hT2. 

The summary descriptions are long, so best to restrict those to pop-up only.

**Comment by scottcain** [comment]
Hi @khowe In GBrowse parlance, the description is the blue text under the glyph, and other tracks use the features "type" for that, so balancer_type could go there, and the balancer attribute could be the label/name.  If you'd like for it to look like hT2 (Translocation) instead and not have any blue text below, I can do that instead.

**Comment by khowe** [comment]
Not fussed personally. The important thing is to have the name somewhere in one of the labels. Given that, I'm happy with the solution is most maintainable (and consistency of config w.r.t. other tracks seems like a good thing to aim for).

**Comment by scottcain** [comment]
@khowe, I believe the balancer track looks good on staging in GBrowse.  Please let me know if you're happy with the results and all push it to production and do the same for JBrowse.

**Comment by khowe** [comment]
@scottcain , the mouseover pop-up now looks good, but I'm still not seeing any labels on the track itself. See image below. I've tried switching to "Expand and label", that didn't have any effect. 

![test](https://cloud.githubusercontent.com/assets/708483/10302899/c7dd4a92-6c07-11e5-841b-4d9f2802b4dc.png)

**Comment by scottcain** [comment]
@khowe , unfortunately, there's nothing I can do about that--if you scroll over to the left end of the details panel (use the mouse to "grab" in white space and pull over to it), you'll find the label and description.  This is the biggest down side of using GBrowse's "detail multiplier" to make the details panel smoothly scrollable.

JBrowse suffers from the same problem, only it's worse.  It only puts the label and description on the glyph at the true left end of the glyph, no matter how many megabases away that is.

**Comment by khowe** [comment]
Hmm, I see. That's a particular bummer for these balancer features, because many of them are really long (like, half the length of a chromosome). 

Is this acknowledged as an issue by the JBrowse developers? Or does no-one else care about it?

**Comment by scottcain** [comment]
I don't recall anyone ever complaining about it.  I could imagine a way (but don't know how to code it up) that the label and description would float on the left edge of the display.  I'll hit the mailing list to see if anybody has considered this or come up with a solution.

**Comment by scottcain** [comment]
Forgot to mention this issue in these commits:

https://github.com/WormBase/website/commit/7bf03a0d5e1dd9e5d7932fccd5e1047c65a2856b

https://github.com/WormBase/website-admin/commit/8d370d33595d14eda81f0776154cf063a45c9ddc

**Comment by scottcain** [comment]
@khowe I made a few changes:

1) I created a new glyph that allows the labels to float and so will always be on the left side of the display if the feature flows of the left side.  Not thrilled with placement at the moment (I think it could use a few pixels buffer, but that's a minor detail).  We can use this on really big features but probably don't want to use it in general.

b) Added a button (the one with an eyeball) that lets you show/hide the track labels (so that you can read the feature name of the top feature in the track).

http://dev.wormbase.org/full.html?data=data%2Fc_elegans_PRJNA13758&loc=I%3A3056746..6071231&tracks=Balancers&highlight= 

Let me know what you think.

**Comment by khowe** [comment]
@scottcain Like it.

**Comment by scottcain** [comment]
Implemented for JBrowse and GBrowse on staging (WS250).  Closing...
