### ISSUE TITLE
Hello. Is it possible to obtain a sample of a stra...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4245]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello. Is it possible to obtain a sample of a strain I'm interested in? Thank you, I appreciate a lot this information.
    
**Reported by:** Gabr************* (agui************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 45.0.2454.101

**Comment by chris-grove** [comment]
Hello Gabriela,

 WormBase does not store or provide strains. You can contact the Caenorhabditis Genetics Center (CGC) to request strains ($7 per strain, for academic/non-profit organizations):

http://cbs.umn.edu/cgc/home

Best,

Chris Grove
WormBase
