### ISSUE TITLE
  Hi, I am a graduae student and follow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4246]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am a graduae student and follow wormbase on twitter as i want to get news from wormbase.  Can i remove know your genes and know your pi's posts from the news feed?</p><p>What were you doing? <br />&nbsp;&nbsp;browsing twitter</p>
    
**Reported by:** Wei **** (weic**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by tharris** [comment]
Hi Wei -

No you cannot. I’ve reduced the frequency of these posts so as not to occlude other postings.

Hope this helps,

Todd
