### ISSUE TITLE
Request for change to the Gene Overview widget when it is a Pseudogene

### ISSUE THREAD

**Issue by gw3** [WormBase/website#4247]
There has been a discussion on the wormbase-genenames mailing list about the display of Gene information when the Gene is a Pseudogene.

It is not as obvious as it might be to users when looking on the gene page that the gene is a Pseudogene and the Remark for Pseudogenes is rather uninformative.

The box in the Overview widget does state when the gene is a Pseudogene, but this is not very noticeable.

Many Pseudogenes have the same rather uninformative block of text in their 'Remark':
"Map position created from combination of previous interpolated map position (based on known location of sequence) and allele information. Therefore this is not a genetic map position based on recombination frequencies or genetic experiments. This was done on advice of the CGC." 

The suggestion is that 
     - the Overview widget display the word 'Pseudogene' prominently.
     - the 'Remarks' text be collapsed by default in Pseudogenes as we think it distracts the user. 

So the Overview for Pseudogenes would look like:
(The box on the right in the Overview widget should still be there, unchanged, but I can't easily indicate it using just text)

-------------------------------------------------------------

Overview
abt-3 (ABC Transporter family )

Pseudogene

Remarks:

-------------------------------------------------------------

**Comment by khowe** [comment]
Or perhaps:

Overview
abt-3 (ABC Transporter family Pseudogene)

**Comment by gw3** [comment]
Yes, that looks good.

**Comment by tuli** [comment]
I'm not so keen on abt-3 (ABC Transporter family Pseudogene) because the bracketed text is the Gene Class name and "ABC Transporter family Pseudogene" is not the Gene Class name.

Maybe 
abt-3 (ABC Transporter family) pseudogene or
abt-3 pseudogene (ABC Transporter family)

**Comment by gw3** [comment]
Also, don't forget that many Pseudogenes do not have a CGC name, and so no gene-class description.
e.g.:

Overview
B0344.1

**Comment by tuli** [comment]
Good point. Another reason for not trying to tie it in with the Gene Class name then.

**Comment by khowe** [comment]
All good points. My point was that the class membership is misleading because it's a pseudogene. The fact that it is a pseudogene is more important than the class membership, so should be at least as prominent.

**Comment by tharris** [comment]
Maybe the Remark in the database should be made more informative instead of loading up the presentation layer with logic to describe the data?

**Comment by tuli** [comment]
The Remark itself isn't wrong, it's just (IMO) too high profile for these Gene objects. nb this Remark is not unique to Pseudogenes. 

I would much rather NOT use the Remark to identify genes as pseudogenes or otherwise. 

Pseudogenes don't have much associated data, so I don't think there will be an issue of the presentation layer (by this do you mean the website display?) becoming overloaded. In fact I would say there was quite a bit of white space in the Overview widget which could easily be populated.

**Comment by tharris** [comment]
What I'm saying is that I don't believe the presentation layer shouldn't be responsible for classifying data. The type of a gene is a perfect example of this. 

Back to the issue at hand:

We will append the type of a gene (for Psuedogenes ONLY) to the description of the gene in the overview.

**Comment by sibyl229** [comment]
Hi @gw3 @tuli I added the gene type for pseudogene. Here is abt-3 and B0344.1: http://staging.wormbase.org/species/c_elegans/gene/WBGene00000021#0-9g-3
http://staging.wormbase.org/species/c_elegans/gene/WBGene00023226#0h-9g-3
Here is an example of "non-pseudogene", unc-22:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3

**Comment by gw3** [comment]
Hi @sibyl229 - This is good.  The first thing the user sees after looking at the gene name in the Overview is a big, clear indication that this is a pseudogene.

**Comment by sibyl229** [comment]
Cool @gw3. Closing.
