### ISSUE TITLE
  Hello, Just wanted to let you know th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4249]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>Just wanted to let you know that the Blast/Blat tool feature in the webpage is not working.<br/>Thanks<br/>Nelson </p>
    
**Reported by:** Nels********** (nels******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by chris-grove** [comment]
Confirmed on live site, when I click on the BLAST/BLAT under tools I get a 502 Bad Gateway:

![screen shot 2015-10-06 at 10 12 11 am](https://cloud.githubusercontent.com/assets/611382/10316159/d737c69c-6c12-11e5-9e2b-99ba9de2b81f.png)

and on staging I get:

![screen shot 2015-10-06 at 10 12 16 am](https://cloud.githubusercontent.com/assets/611382/10316166/dc84071e-6c12-11e5-837a-fc9e0d8718e6.png)

**Comment by chris-grove** [comment]
Hello Nelson,

 Apologies, the BLAST/BLAT service was offline for a bit. It should be up
and running again. Let us know if you have any trouble.

Chris Grove
WormBase
