### ISSUE TITLE
  Well, not everything, but I can't see...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4250]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Well, not everything, but I can't seem to get the Blast/Blat program to work. It says "Bad gateway". Is it a problem on my end? <br/>Thanks!</p>
    
**Reported by:** Brit**** (Sugg************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:16.0) Gecko/20100101 Firefox/16.0

**Comment by chris-grove** [comment]
Duplicate #4249

**Comment by chris-grove** [comment]
Hello Brittany,

 Apologies, the BLAST/BLAT service was offline for a bit. It should be up and running again. Let us know if you have any trouble.

Chris Grove
WormBase
