### ISSUE TITLE
Chris: Hi Jeff, how can I help? Jeff Gruntmeir (je...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4253]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Jeff, how can I help?</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): so I am new to bioinformatics and I'm trying to figure out how to find a specific gene nucleotide sequence and protein sequence from Dirofilaria immitis</br>Chris: OK</br>Chris: I'm not familiar with the species</br>Chris: OK got it</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): DIMM03355 is the protein name</br>Chris: OK</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): β-1,4-Mannosyltransferase</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): how do I find that in these annotated genomes</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): not in NCBI</br>Chris: OK I see</br>Chris: where did you get the identifier DIMM03355?</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): from a paper hold on</br>Chris: OK</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): http://www.fasebj.org/content/26/11/4650.full</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): table 3</br>Chris: OK</br>Chris: got it</br>Chris: I can't find what database that would be an accession number for</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): right that's my problem</br>Chris: Hmmm, let me take a closer look</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): http://nematodes.org/genomes/dirofilaria_immitis/</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): this is where I think I need to start but I have no idea where to even begin to get from those identifiers to what I'm looking for in those files</br>Chris: yeah</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): I saw the popup and thought I would ask but no worries if u don't know</br>Chris: Yeah, I would e-mail the corresponding author and ask</br>Chris: All my usual search options are coming up blank</br>Jeff Gruntmeir (jeff.gruntmeir@okstate.edu): ok thanks for your help and taking a look. I appreciate it, take care</br>Chris: You might want to try KEGG looking for the enzyme name</br>Chris: and from there see if you can find it for this species</br>Chris: Good luck</br>Chris: thanks you too
    
**Reported by:** Jeff********** (jeff**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/d_immitis#0--10">http://www.wormbase.org/species/d_immitis#0--10</a>
**Browser:** Chrome 42.0.2311.135

**Comment by brucebolt** [comment]
Hi Jeff

Following on from your conversation with Chris, I have looked into this protein name.  The names in the format DIMMnnnnn were used in freeze v1.3 of the genome assembly.  We have v2.2 in WormBase ParaSite.

The protein sequence (from http://nematodes.org/downloads/959nematodegenomes/bbaGTffddf45kkl7_dirofilaria_immitis/dimmitis.v1.3.contigs.maker.v0.9.proteins.fasta.gz <http://nematodes.org/downloads/959nematodegenomes/bbaGTffddf45kkl7_dirofilaria_immitis/dimmitis.v1.3.contigs.maker.v0.9.proteins.fasta.gz>) is:
>DimmContig51_DIMM03355    protein AED:0.29912093133761 eAED:0.29912093133761 QI:97|1|0.9|1|0.88|0.8|10|199|464
MNINAETKHAIHVASFFCWLVLFEVICGTIPLFSQTHSRYVSTASLIDRYGYFGTFVLYIIRIASLLVLPQCIFNMLGLVLFNGFREKVRLKAAPLLAPLVCFRVVTRGDYPELVKQNVNYNMTKCREVGMENFFFEVVTDKAICLPSKPRLREVIVPSAYRTKSGAQFKSRALQYCLEDGVNILQDDDWIVHLDEETLLTNNSICGILNFCEDGKHQFGQGIITYANGDIVNWITTLSDSFRVADDMGKLRFQFRFFHKPLFGWKGSFVVTQVGAERNVSFDHGREGSIAEDCFFSMIAFRDGYTFDFIEGEMLEKSPFTFWDFLQQRKRWLQGIFLTVHAKQIPTRNKILLGLSFYAWASMPVTTLQMYLFHAFPLPPCFIFDFLVAFVAAVNLYMYIYGVLKSFSHKYRHSPFRLCLYMIGALLTIPFNVCIENIAVIWGMLGNKNGFYVVKKDERMISVL

I have carried out a BLASTP search (http://parasite.wormbase.org/Multi/Tools/Blast/Results?tl=9k245YzFkkBTURzW-2182298 <http://parasite.wormbase.org/Multi/Tools/Blast/Results?tl=9k245YzFkkBTURzW-2182298>) which reveals there is one protein with 100% identity in the new assembly: nDi.2.2.2.t00300 <http://parasite.wormbase.org/Dirofilaria_immitis_prjeb1797/Transcript/ProteinSummary?db=core;t=nDi.2.2.2.t00300;tl=9k245YzFkkBTURzW-2182298-44992487>.

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD

**Comment by brucebolt** [comment]
Thank you very much! This is exactly what I needed.
 
Best regards,
 
Jeff
