### ISSUE TITLE
  Hi, I was wondering why there is a la...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4254]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I was wondering why there is a large version/release  discrepancy between the current primary version of WormBase (WS249) and the dataset that WormMine is currently based on (WS238). I understand that new versions of WormBase a released fairly frequently, but at the point it seems that WormMine is based on a version that is two years old. Thanks.</p>
    
**Reported by:** Adam********* (adam****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by chris-grove** [comment]
We are working to release a new version of WormMine very shortly (within the next few weeks). Stay tuned. 

Todd
