### ISSUE TITLE
How can I get the worm base name for a gene given ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4255]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I get the worm base name for a gene given the NCBI reference or the gi number?
    
**Reported by:** Jess*** (jess******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/protein/NP_504755.2">http://www.wormbase.org/search/protein/NP_504755.2</a>
**Browser:** Chrome 45.0.2454.101

**Comment by epaule** [comment]
that ID is a refseq id, which in turn is derived from the GenBankID which you can get from here:
http://www.ncbi.nlm.nih.gov/protein/NP_504755.2

then you can either grab the WBGeneID (WBGene00021963) or the GenBankID (CCD72909) or the WormBase SeqeunceID (Y57E12B.3) and use it on WormBase to search (the CCD is a protein/CDS id).
