### ISSUE TITLE
Dear wormbase,
Is there a plan to update the refer...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4256]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear wormbase,
Is there a plan to update the reference in wormmart from WS220 to a more recent version? Thanks a lot. 
Mintie
    
**Reported by:** Mint***** (mp67*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#015-23-6">https://www.wormbase.org/#015-23-6</a>
**Browser:** Chrome 45.0.2454.101

**Comment by chris-grove** [comment]
Hi Mintie,

What information are you trying to obtain? The answer is yes and no, it 
depends. Part of the information there is replaced by BioMart at 
parasite.wormbase.org, some is going to be in WormMine and the balance 
not yet planned but we may provide users with one-off assistance.

Hope that's not too unclear.

Raymond

**Comment by raymond91125** [comment]
Thanks Raymond. That's very clear and directs me to ParaSite.

Mintie
