### ISSUE TITLE
Dear staff,
     I have compare the WS235 and WS25...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4257]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear staff,
     I have compare the WS235 and WS250, and I found lots of differeces between these two versions.
	C_elegan_235	C_elegan_250
Genes	43824	47089
Transcripts	55244	96130
Transcripts Per	1.26	2.04
Total Exons	169208	208751
unique Exons	131049	131674
UTR5	42039	133809
UTR3	41250	35767
SL1	18495	43160
SL2	7476	13350
operon	1391	1498
polyA_site	44052	85690
ncRNA	70433	11559
tandem	53037	53024
Transposon	738	2396
TSS_region	0	73499

you will see that the the differeces of transcripts, The UTR5, the SL1 and TSS_region. I just want to know whether you have add other transcripts annotation based on new data, or updated the old version totally, and the second how to defined TSS in the new version. the last one why ncRNA reduecd much in the new vwesion?

    Best,
    minghui
    
**Reported by:** ming******** (mw72*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#015-23-6">https://www.wormbase.org/#015-23-6</a>
**Browser:** Chrome 44.0.2403.155

**Comment by gw3** [comment]
Hi,

The TSS_region Features were made from data in the paper:
WBPaper00042246
PubMed 23550086
The landscape of RNA polymerase II transcription initiation in C. 
elegans reveals promoter and enhancer architectures.
Genome Res (2013) 23 1339-47

Are you counting coding transcripts?
How are you doing this?

Gary Williams

**Comment by gw3** [comment]
Just to add to my colleagues response, it could be that there have been 
a large number of gff method/source changes in the last 3 years that may 
account for some of the changes? Some of your numbers seem a little 
higher than expected.

If you could explain the process you used to generate this comparative 
release data.

Thanks

Paul


On 08/10/2015 08:59, Gary Williams wrote:
> Hi,
>
> The TSS_region Features were made from data in the paper:
> WBPaper00042246
> PubMed 23550086
> The landscape of RNA polymerase II transcription initiation in C. 
> elegans reveals promoter and enhancer architectures.
> Genome Res (2013) 23 1339-47
>
> Are you counting coding transcripts?
> How are you doing this?
>
> Gary Williams
>
>
> On 07/10/15 18:15, no-reply@wormbase.org wrote:
>>       I have compare the WS235 and WS25... (minghui Wang)
>> Content-type: text/html; charset="utf-8"
>> Date: Wed, 7 Oct 2015 17:18:32 +0000
>> MIME-Version: 1.0
>> Content-Transfer-Encoding: 7bit
>>
>>
>> <style type="text/css">.fade{font-size:.9em;color:#999}</style> 
>> offline chat Dear staff,
>>       I have compare the WS235 and WS250, and I found lots of 
>> differeces between these two versions.
>>     C_elegan_235    C_elegan_250
>> Genes    43824    47089
>> Transcripts    55244    96130
>> Transcripts Per    1.26    2.04
>> Total Exons    169208    208751
>> unique Exons    131049    131674
>> UTR5    42039    133809
>> UTR3    41250    35767
>> SL1    18495    43160
>> SL2    7476    13350
>> operon    1391    1498
>> polyA_site    44052    85690
>> ncRNA    70433    11559
>> tandem    53037    53024
>> Transposon    738    2396
>> TSS_region    0    73499
>>
>> you will see that the the differeces of transcripts, The UTR5, the 
>> SL1 and TSS_region. I just want to know whether you have add other 
>> transcripts annotation based on new data, or updated the old version 
>> totally, and the second how to defined TSS in the new version. the 
>> last one why ncRNA reduecd much in the new vwesion?
>>
>>      Best,
>>      minghui  <p>Submitted From:
>> <br>&nbsp;&nbsp;https://www.wormbase.org/#015-23-6 <a 
>> href="http://www.wormbase.org/https://www.wormbase.org/#015-23-6">https://www.wormbase.org/#015-23-6</a>
>> </p>
>>
>> <p>
>> This issue has been assigned ticket number: #4257. Follow progress on 
>> our <a href="https://github.com/WormBase/website/issues/4257">issue 
>> tracker</a>.
>> <p>
>>
>> <p>
>> Reported by: minghui Wang (mw729@cornell.edu) <br />
>> <span class="fade">07 Oct 15 17:18 </span><br /><br />
>> <span class="fade"> </span>
>> </p>
>>
>> <p class="fade">
>> This question was reported via the web interface at wormbase.org. You 
>> can also <a href="mailto:help@wormbase.org">email us</a> directly.
>> </p>
>>
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by gw3** [comment]
Hi Paul,
     Thanks for your reply.
     I just used get_general_stats.pl from eval-2.2.8 software, and it reports me all the statistics of gtf file. Is there something wrong or some bug of that software, please let me know it? 
          Best,
     minghui
-----Original Message-----
