### ISSUE TITLE
  Wormbase Blast does not work since ye...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4258]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Wormbase Blast does not work since yersterday. Could you please fix it?</p>
    
**Reported by:** Joy (qin.********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by chris-grove** [comment]
Hi Joy - 

My apologies for the difficulties. The BLAST service has been experiencing some
instability over the past 12 hours. I’ve fixed the problem. Can you please try your
query again?

Thanks,

Todd
