### ISSUE TITLE
Hello, I was looking at some of the million mutati...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4259]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I was looking at some of the million mutation strains, and when I clicked on the "contains" section, for example "456 mutations found", I was directed to a page with a list. When I want to click "download all" on the left side of the page, there's a message indicating that I need to use an FTP site. I did a similar thing about a year ago, and was able to download a spreadsheet file easily. Would you mind helping me solve the issue? Thank you very much.
    
**Reported by:** Pete********* (kula************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/variation/VC40890">http://www.wormbase.org/search/variation/VC40890</a>
**Browser:** Chrome 45.0.2454.101

**Comment by tuli** [comment]
Dear Pete,

Thank you for contacting WormBase.

The size of some files is now so large that we prefer to point users
to our FTP site.

The GFF3 file for the latest release is here:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz

We recognise that searching for individual strains is not straight
forward. WormMine will be the preferred resource to extract this data
but until it is fully populated I am happy to extract the data you
need directly from the database.

It would be very helpful if you could let me know what data you are
interested in e.g type of mutation, nature of the change, effect on
protein etc.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Pete,

I've just had a better look at the gff3 file and see that strain names
are included e.g.

I Million_mutation point_mutation 88892 88892 . + .
variation=WBVar00604822;public_name=gk867106;strain=VC40890;substitution=T/A;consequence=Intron

so in fact you can grep through the gff3 file for the strain in
question. Apologies for the confusion.

Mary Ann

On 8 October 2015 at 19:18, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
> Dear Pete,
>
> Thank you for contacting WormBase.
>
> The size of some files is now so large that we prefer to point users
> to our FTP site.
>
> The GFF3 file for the latest release is here:
>
> ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz
>
> We recognise that searching for individual strains is not straight
> forward. WormMine will be the preferred resource to extract this data
> but until it is fully populated I am happy to extract the data you
> need directly from the database.
>
> It would be very helpful if you could let me know what data you are
> interested in e.g type of mutation, nature of the change, effect on
> protein etc.
>
> Best wishes,
>
> Mary Ann
>
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>
>
> On 8 October 2015 at 16:47,  <no-reply@wormbase.org> wrote:
>> offline chat Hello, I was looking at some of the million mutation strains,
>> and when I clicked on the "contains" section, for example "456 mutations
>> found", I was directed to a page with a list. When I want to click "download
>> all" on the left side of the page, there's a message indicating that I need
>> to use an FTP site. I did a similar thing about a year ago, and was able to
>> download a spreadsheet file easily. Would you mind helping me solve the
>> issue? Thank you very much.
>>
>> Submitted From:
>>   http://www.wormbase.org/search/variation/VC40890
>> http://www.wormbase.org/search/variation/VC40890
>>
>> This issue has been assigned ticket number: #4259. Follow progress on our
>> issue tracker.
>>
>> Reported by: Pete Kulalert (kulalert@mit.edu)
>> 08 Oct 15 15:50
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
![screen shot 2015-10-08 at 20 00 41](https://cloud.githubusercontent.com/assets/1359170/10376721/46b529e8-6df7-11e5-87a5-4c31092983c5.png)

User has asked whether downloads which used to be available have been archived somewhere. 

Screenshot attached.

**Comment by tuli** [comment]
User is happy. 

Dear Mary Ann,

    Thank you very much for your help! I really appreciate it!

Regards,
Pete Kulalert

**Comment by tuli** [comment]
No, they are not archived. User informed.
