### ISSUE TITLE
FTP irregularity 

### ISSUE THREAD

**Issue by tuli** [WormBase/website#4260]
I have noticed that if I download c_elegans.PRJNA13758.WS250.annotations.gff.gz from ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/ it fails (message is No Data received), whereas if I download the same file from ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/ it is successful. 

Same issue in safari and chrome

**Comment by epaule** [comment]
which one? The GFF2 or the GFF3?

**Comment by epaule** [comment]
which one? The GFF2 or the GFF3?

**Comment by tuli** [comment]
3

**Comment by epaule** [comment]
gff3 / WS250 download on both sites .... is bit slow (around 1Mbps), but working for me

**Comment by tharris** [comment]
I can't replicate this issue either. Can we close?

**Comment by tuli** [comment]
[sulks] OK then.
