### ISSUE TITLE
  Tree display broken on http://www.wor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4269]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Tree display broken on http://www.wormbase.org/species/p_pacificus/transcript/PPA21290#0438--10</p><p>What were you doing? <br />&nbsp;&nbsp;Looking</p>
    
**Reported by:** Mary********* (mary*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by tharris** [comment]
Fixed for now, but sgifaceserver extremely unstable with WS249.
