### ISSUE TITLE
Jessica (jessica.leete@duke.edu): Is there a way t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4272]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Jessica (jessica.leete@duke.edu): Is there a way to download by blast results?</br>Chris: Hello Jessica, how can I help?</br>Chris: Yes</br>Jessica (jessica.leete@duke.edu): How?</br>Chris: Let me check</br>Chris: I don't believe you can do it in bulk</br>Chris: but you should be able to do so for individual results</br>Chris: OK, so I think it depends on the format you're looking for</br>Chris: You can copy paste the alignment results from the results page, or download the image from GBrowse</br>Chris: that includes the alignment to the genome</br>Chris: I just sent you a PNG image of the BLAST result for lin-1</br>Chris: What format are you looking for?</br>Chris: This may be something we can add as a feature request</br>Jessica (jessica.leete@duke.edu): I have a long list of drosophila genes to blast against c. elegans. I really just need the gene names or ids and e-value for the top few hits of each drosophila gene.</br>Chris: I see</br>Chris: Well you can do this more easily using our ParaSite BioMart tool</br>Chris: On the WormBase homepage, click on "ParaSite" at the top of the page</br>Chris: then click on</br>Chris: "BioMart" at the top of that page</br>Chris: Actually, BLAST, sorry, not BioMart</br>Jessica (jessica.leete@duke.edu): ok I'm there</br>Chris: You can BLAST up to 30 sequences at a time</br>Chris: and specify the target species</br>Chris: You can paste the sequences in FASTA format into the search box</br>Chris: or you can upload a file</br>Chris: then under "Search against"</br>Chris: you can click on the radio button for "Custom species list"</br>Chris: then search for "elegans"</br>Jessica (jessica.leete@duke.edu): found it! I have one running now</br>Chris: OK great!</br>Chris: Once the BLAST is done you can view the results and then click on "Download results file"</br>Chris: which should download all the results into a text file</br>Chris: Is there anything else I can help you with?</br>Jessica (jessica.leete@duke.edu): I got that working. This will produce 1 text file for each drosophila gene I blast, correct?</br>Chris: The default will collect them all in one text file, I believe</br>Chris: but you have the option to download them individually</br>Jessica (jessica.leete@duke.edu): I would rather have them all in one file. Where is that option?</br>Chris: There is an Excel spreadsheet looking icon at the right of the results</br>Chris: one of the options is "download what you see" or "download whole table"</br>Jessica (jessica.leete@duke.edu): I see a floppy disk image that says I can save to my account, but not the excel icon</br>Chris: Have you already clicked on "view results"</br>Chris: ?</br>Chris: although that may only work for individual results</br>Chris: I need to check</br>Jessica (jessica.leete@duke.edu): I clicked on view results, and now I see the excel icon, I downloaded the whole table, but that was only the results for 1.</br>Chris: OK, it looks like you need to download each individual result</br>Chris: Yes, I see</br>Chris: I don't know of a way to download everything in one go</br>Chris: but I can post a feature request</br>Jessica (jessica.leete@duke.edu): That would be wonderful. Thank you!</br>Chris: OK, sounds good</br>Chris: anything else I can help you with today?</br>Jessica (jessica.leete@duke.edu): No, thanks again. You saved me a lot of time.</br>Chris: OK great! Thanks for using WormBase. Have a nice day!
    
**Reported by:** Jess*** (jess******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run">http://www.wormbase.org/tools/blast_blat/run</a>
**Browser:** Chrome 45.0.2454.101

**Comment by chris-grove** [comment]
Jessica would like a way to download all results from a multiple BLAST search in a single file

**Comment by brucebolt** [comment]
The EBI's BLAST service that we use in the ParaSite BLAST only allows one sequence to be submitted with each job, therefore one text file is generated for each sequence.

The only solution would be to concatenate the text files and offer a "Download all" option when more than one sequence has been queried.  I'm not sure how useful that would be to other users.

**Comment by chris-grove** [comment]
@brucebolt 
I think this would be generally useful to users, as I think many people want to upload a batch of sequences, run the tool, download all the results in one click, and then do analysis offline

**Comment by tharris** [comment]
You can batch blast multiple sequences at WB but we do not offer a facility to download the alignments.

**Comment by brucebolt** [comment]
The next release of ParaSite will have an option to download the results for all sequences in a single file.
