### ISSUE TITLE
Chris: Hello Jessica Chris: How can I help? Jessic...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4273]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Jessica</br>Chris: How can I help?</br>Jessica (jessica.leete@duke.edu): I have a long list of NCBI ids, is there a way to find the wormbase names for the genes? I can find them on NCBI by looking them up one by one, but that is impractical for my list.</br>Chris: I think this may be possible using ParaSite BioMart</br>Chris: could you give me a few example IDs?</br>Chris: I'll take a look</br>Jessica (jessica.leete@duke.edu): gi|392919369|ref|NP_504755.2|</br>Chris: We can definitely take Ensembl IDs, UniProt IDs, and Wiki Gene IDs</br>Jessica (jessica.leete@duke.edu): gi|17561400|ref|NP_506229.1|</br>Chris: OK, thanks</br>Chris: Sorry, Entrez, not Ensembl</br>Chris: OK, ParaSite BioMart doesn't accept these IDs, unfortunately</br>Chris: I believe we have mappings in a file on our FTP site</br>Chris: I'm looking there now</br>Chris: Yeah, the FTP site doesn't have this either I think</br>Chris: You may be able to upload these IDs into the Entrez Batch tool</br>Chris: http://www.ncbi.nlm.nih.gov/sites/batchentrez</br>Chris: and get back UniProt IDs, which should be queryable through ParaSite BioMart</br>Jessica (jessica.leete@duke.edu): Ok. I will play with that for a while. Thanks again Chris!</br>Chris: OK sure thing. Sorry I couldn't be more help</br>Chris: Anything else I can help with?</br>Jessica (jessica.leete@duke.edu): No, that's enough for now :)</br>Chris: OK, take care
    
**Reported by:** Jess*** (jess******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 45.0.2454.101

**Comment by chris-grove** [comment]
for the batch querying with NCBI IDs, I figured out what works:

1) Create a text file (*.txt) with either GI accession numbers or the
"NP_*" IDs (not both on the same line)

2) Save the file to your computer, and remember where you saved it

3) At the Batch Entrez tool:

http://www.ncbi.nlm.nih.gov/sites/batchentrez

Choose the "Protein" database

4) Click on the "Browse..." button and select your file for upload

5) Click on the "Retrieve" button

6) On the results page, click on the hyperlinked "Retrieve records for #
UID(s)"

7) Under the "Find related data" section of the NCBI results page, in the
"Database" drop down menu, select "Gene" and click on the "Find Items"
button

8) On this results page, click on "Send to", choose "File" and click on
"Create File"

This will generate a text file with all the results in tabular format,
including the WormBase gene name and identifier "CELE_*"


Hope that helps!

Best,

Chris

**Comment by chris-grove** [comment]
@tharris @sibyl229 
This is a recurring issue: conversion of NCBI gene and protein IDs to WormBase IDs. Is there a way to do this that I'm just not thinking/aware of? If not, would be good to have

**Comment by tharris** [comment]
This is a planned enhancement for Intermine but we are just trying to get the core version released now. If we are able to resolve remaining issues in next few days we will add this (and other IDs) for WS250.

**Comment by chris-grove** [comment]
OK, excellent! Thanks

**Comment by khowe** [comment]
You *can* do this in ParaSite BioMart. It allows you to generate a big table of WormBase gene ids to RefSeq protein ids ("RefSeq protein ID" attribute). 

What you cannot do is upload a list of RefSeq ids. But  if you have the complete mapping, you don't need the mapping for a subset of gene only.

**Comment by brucebolt** [comment]
I have updated the ParaSite BioMart to include RefSeq Protein ID as a filter.  The data was there and available to query, but the UI never included the option to select it.

**Comment by chris-grove** [comment]
Hi Jessica,

 Following up on the request to query WormBase genes in batch using RefSeq IDs: I'm happy to report that Bruce on our team has added RefSeq IDs as a filter that can be used in ParaSite BioMart to pull out worm genes:

http://parasite.wormbase.org/biomart/martview/5c57e3e34ada4385a0e6865fe0c3146b

(Reachable from the ParaSite homepage, which is reachable from the WormBase homepage)

For the examples you gave me yesterday, simply use the RefSeq IDs without the decimal and following digit like this:

NP_504755
NP_506229

I can confirm that this BioMart correctly identifies these as lipl-1 and lipl-6.


Hope that helps!

Best,

Chris

**Comment by chris-grove** [comment]
Thanks @brucebolt !!!
