### ISSUE TITLE
Chris: Hello Toni, how can I help? Toni (antoniblt...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4275]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Toni, how can I help?</br>Toni (antonibltrn@gmail.com): Hi, apparently the link for Heterorhabditis bacteriophora genome assembly and annotations is broken.</br>Chris: Oh OK, I'll look into it</br>Chris: which link are you referring to?</br>Toni (antonibltrn@gmail.com): this one</br>Toni (antonibltrn@gmail.com): ftp://ftp.wormbase.org/pub/wormbase/species/h_bacteriophora/sequence/genomic/h_bacteriophora.PRJNA13977.WS249.genomic.fa.gz</br>Chris: Thanks. Let me investigate a bit</br>Toni (antonibltrn@gmail.com): Thank you!</br>Chris: No problem! :)</br>Chris: Did you reach this link from this FTP site:</br>Chris: ftp://ftp.wormbase.org/pub/wormbase/species/h_bacteriophora/sequence/genomic/</br>Chris: ?</br>Chris: The link from there seems to be working OK</br>Chris: from my end, at least
    
**Reported by:** Toni (anto*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/h_bacteriophora#021--10">https://www.wormbase.org/species/h_bacteriophora#021--10</a>
**Browser:** Safari 9.0

**Comment by chris-grove** [comment]
Hi Toni,

 It seems we were disconnected. I just wanted to follow up and make sure
that you were able to get what you were looking for.

Is there anything else I can help you with?

Best,

Chris Grove

**Comment by chris-grove** [comment]
Hi Chris,

I have been able to access the genome files from the ftp site directly, but the link
from wormbase is still not working.

Thanks a lot!

Toni

**Comment by chris-grove** [comment]
OK. Can you point me to the link that isn't working? I'll make sure that
we fix that link.

Thanks!

Chris

**Comment by brucebolt** [comment]
There is no WS249 file on the FTP site for this genome as it is one of the species that has been "moved" to ParaSite.

Link is here: http://www.wormbase.org/species/all#01--10
But this table has been changed for WS250 to link to the ParaSite section of the FTP site: http://staging.wormbase.org/species/all#01--10

**Comment by sibyl229** [comment]
That's right. Thanks @brucebolt !

**Comment by chris-grove** [comment]
@brucebolt @sibyl229 
According to the user, there is still a link somewhere on WormBase that incorrectly links to the WS249 version of the file. I was waiting for a response to tell me where the link is, but it doesn't look like it's coming. Closing.

**Comment by chris-grove** [comment]
Toni got back to me: On this page:

http://www.wormbase.org/species/h_bacteriophora#01--10

The links in the Download widget for "Genomic Sequence", "GFF3" and "Protein" are all hard linked to the WS249 release, causing an error to load each page/document.

**Comment by chris-grove** [comment]
@tharris  Could you take a look when you get a chance? I think this is simply a matter of changing the FTP URL reference on this page to "current" instead of "WS249"

**Comment by chris-grove** [comment]
Todd's looking into it. This may be related to problems with the pry-1 gene page (site attack)

**Comment by chris-grove** [comment]
no longer an issue
