### ISSUE TITLE
Hi! I'm wondering how the Homology BLASTP match...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4277]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! I'm wondering how the Homology&gt;BLASTP matches are obtained. Specifically, 
1) What database is searched? 
2) What are the organisms included in the search? 
3) What is the algorithm used?
Thank you so much!
Best,
Lucy
    
**Reported by:** Lucy (lucy******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008085?from=http://www.wormbase.org/db/gene/gene?name=WBGene00008085;class=Gene#-1069f-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00008085?from=http://www.wormbase.org/db/gene/gene?name=WBGene00008085;class=Gene#-1069f-10</a>
**Browser:** Chrome 45.0.2454.101

**Comment by epaule** [comment]
3.) the algorithm used is BLASTP (basically the Alschul one of protein versus proteins)
2.) & 1.) we search multiple protein databases from species specific ones (all core WormBase species' proteomes and some selected model organisms like fruitfly, yeast and human) to more generic ones like UniProt, which contain a vast range of species.
