### ISSUE TITLE
Variation summary - Linked_to 

### ISSUE THREAD

**Issue by tuli** [WormBase/website#4278]
I have populated the Linked_to tag in a number of Variation objects. 

This tag allows me to link individual Variation objects from cis double and cis triple mutants e.g. WBVar0008851 (m118m221) and the individual Variations are also linked to the cis mutant e.g. m118 is linked to m118m221.

I would like this information to be displayed in the Variation Summary page. 

I think the Genetics widget is the right place for this information so I'd like to ask for them to be displayed just beneath the Gene and Reference allele (if present) listing and before the Strain list/table.

e.g. for m118m221

Genetics widget
Gene: ama-1
Reference allele: m118
                            Reference allele for: ama-1
[details]
Linked to: m118m221
                 m118m236
                [another 12]

I guess if the list of Linked_to variations is longer than say 5, it should be collapsed.

**Comment by tuli** [comment]
@sibyl229  will look next week.

**Comment by sibyl229** [comment]
Hi @tuli sorry for getting back to you late on this Linked_to issue. I noticed that you marked this as WS252, and I doubled checked that the data hasn't made to the staged WS251 release yet. So I will work on this whenever this data get staged. I think once we have the data, adding the links will be straightforward. Is there anything else that you want me to think about on this issue? Thanks!

**Comment by tuli** [comment]
Thank you @sibyl229 
Yes, the data will be in WS252 and I hope is indeed straightforward. No, I don't think there's anything else to think about.

**Comment by sibyl229** [comment]
Hi @tuli Could you clarify on this? On the m118m221 page, do you want the variations under Linked_to tag of both m118 and m221 to be listed? Should both m118 and m221 be listed as reference allele? Thank you!

**Comment by tuli** [comment]
@sibyl229 
The Variations listed under Linked_to should be the ones which you can see in the Tree_display (in staging at the moment - WS252)
So yes, for m118m221 it will be m118 and m221

You do not need to make any changes to the Reference_allele display.

**Comment by sibyl229** [comment]
Hi @tuli does something like this work? And what field name and tooltip would you like shown? Thanks
![screen shot 2016-02-23 at 11 33 43 am](https://cloud.githubusercontent.com/assets/1753893/13258496/5d2b1174-da21-11e5-9ccc-441a919f5297.png)
![screen shot 2016-02-23 at 11 33 31 am](https://cloud.githubusercontent.com/assets/1753893/13258498/5f00e3d4-da21-11e5-872e-7a4a341f5dc6.png)

**Comment by tuli** [comment]
@sibyl229 

So the top example is for Variation m118m221 (WBVar00088581). 
Yes, that's the data and layout I'd like. I don't think it needs to be a bullet point list though.

The bottom example is for Variation m118 (WBVar00088580).
Yes, this looks good. 

I am not sure what you mean about the tooltip. No other links appear to have tooltips on Summary pages. Please can you explain.

Also, what do you mean by field name?

**Comment by sibyl229** [comment]
Hi @tuli by "field name" I meant if the display should say "Linked to: " or be called something else. We refer to the sub sections of the widget as "field", such as the Gene field, Reference allele field in this Genetics widget. The tooltip is a short text description on what the field is about, and it shows up when you mouse over the field name. The tooltip for the Gene field is: "gene in which this variation is found (if any)". Do you want to write anything for Linked to field?

**Comment by tuli** [comment]
@sibyl229 Thanks for clarifying. 
The field name "Linked to" is fine. 

I don't think my tool tips are working in either Chrome or Safari. I don't see anything when I mouse over any field names anywhere!

**Comment by sibyl229** [comment]
Hi @tuli here's the Linked to variation with your suggested changes: http://staging.wormbase.org/species/c_elegans/variation/WBVar00088581#02--3
Now tooltip for field name has shorter latency, I think you should be able to see them. Could you send me a tooltip description for the Linked to field? Thanks!

**Comment by sibyl229** [comment]
Hi @tuli could you check again if the tooltip is working? And what tooltip should be displayed for Linked_to field? Thanks!

**Comment by tuli** [comment]
The tooltips are working for me in Chrome now, thank you. 

The tooltip for Linked_to should say "Paired substitutions as part of the same allele"

**Comment by tuli** [comment]
The changes you've made look fine.
