### ISSUE TITLE
  Hi,  I would like to post and add for...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4280]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I would like to post and add for a postdoc position using the Worm Community Forum. I have registered already but I cannot find where to create my Job Posting. Could you please tell me how to post a job position?</p><p>What were you doing? <br />&nbsp;&nbsp;using worm community forum  to post a job</p>
    
**Reported by:** Vale*********** (vvr@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56

**Comment by brucebolt** [comment]
Dear Valeria

Use this form to create a new job posting: http://forums.wormbase.org/index.php?action=post;board=1.0 <http://forums.wormbase.org/index.php?action=post;board=1.0>

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
