### ISSUE TITLE
Begoña (Bego_Ayuda@usal.es): question Begoña (Bego...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4281]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Begoña (Bego_Ayuda@usal.es): question</br>Begoña (Bego_Ayuda@usal.es): How could I Know the sequence of pb of my mutacion of interest and the sequence of pb in WT in the position of the mutation? thanks
    
**Reported by:** Bego** (Bego**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/cds/C12D8.5#05--10">http://www.wormbase.org/species/c_elegans/cds/C12D8.5#05--10</a>
**Browser:** Chrome 45.0.2454.101

**Comment by brucebolt** [comment]
Dear Begoña

On each Variation page, the ‘Molecular Details’ widget contains both the wild type and mutant sequence.  For example: http://www.wormbase.org/species/c_elegans/variation/WBVar00000002#0-5-10 <http://www.wormbase.org/species/c_elegans/variation/WBVar00000002#0-5-10>

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
