### ISSUE TITLE
Proposed fusion of two gene models

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4283]
Hi wonderful wormbase folks!
	I’d like to propose fusion of two adjacent C. elegans gene models. The fusion has transcript support across the boundary of the two current gene models, and the domain structure of the fused gene is also congruent with orthologs in other species.

The gene models in question are tag-83 (5’) and M01E11.7 (3’). M01E11.7. tag-83 encodes a PTEN-family phosphatase domain and is homologous to tensins from other species. M01E11.7 encodes a protein containing SH2 and PTB domains that are also found in other tensins, and the sequences of these domains (as well as the overall protein) also marks it as a tensin C-terminal protein. Most other Caenorhabditids also have this gene split, but Ascaris (gb|ERG79816.1|) has a gene model covering both halves, as do many more distant organisms. A pair of ESTs (FN872528.1, FN872530.1) span the gap between these two original gene models (UCSC browser: http://genome.ucsc.edu/cgi-bin/hgTracks?db=ce6&position=chrI%3A5583737-5603484&hgsid=448775841_u8CS7qILZFHoBUxtuPmc1W2Ad82D).

I would also like to propose that the fused gene be renamed as tns-1, as it is the sole tensin homolog in C. elegans. Human homologs are known as TNS1, TNS2, TNS3.

If you agree with these changes, and have a slot to attribute them, please attribute to Jinan Chen, a postdoc in my group who discovered the fusion.

Thanks!

-Gerard.

**Comment by brucebolt** [comment]
Gerard,

I agree  that M01E11.7 looks as if it should have isoforms that extend up to F46F11.3, merging these two loci.
There could prossibly also be isoforms that extend up to F46F11.11 to merge this in.

There is a slight complication in that it is possible that the upstream operon might extend to include these loci and what we are seeing are incomplete splicing of the operon.
We will discuss this and analyse the structures in detail to resolve what is happening in this region.
We will let you know of any changes to the gene structures, soon.

We will pass on your suggestion for a gene name of the merged locus to the gene-name expert.


Gary Williams
WormBase

**Comment by Paul-Davis** [comment]
Dear Gerard, Jinan

Just to confirm, I have merged the 3 gene loci into a single gene 
M01E11.7(WBGene00006508) with  isoforms designated M01E11.7a-h based on 
SL1/2 feature data and the unusual alternate 3' end Isoform M01E11.7d.

This will be visible in the WS252 release of WormBase.

Thanks

Paul



On 16/10/2015 13:40, Bruce Bolt wrote:
>
> Gerard,
>
> I agree that M01E11.7 looks as if it should have isoforms that extend 
> up to F46F11.3, merging these two loci.
> There could prossibly also be isoforms that extend up to F46F11.11 to 
> merge this in.
>
> There is a slight complication in that it is possible that the 
> upstream operon might extend to include these loci and what we are 
> seeing are incomplete splicing of the operon.
> We will discuss this and analyse the structures in detail to resolve 
> what is happening in this region.
> We will let you know of any changes to the gene structures, soon.
>
> We will pass on your suggestion for a gene name of the merged locus to 
> the gene-name expert.
>
> Gary Williams
> WormBase
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/4283#issuecomment-148705955>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
