### ISSUE TITLE
becca (rebeccanewmark2016@u.northwestern.edu): que...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4285]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

becca (rebeccanewmark2016@u.northwestern.edu): question about "phenotypes"
    
**Reported by:** becc* (rebe*********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004413#0-9f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004413#0-9f-3</a>
**Browser:** Firefox 41.0

**Comment by brucebolt** [comment]
Does anyone know if the user got a response through the online chat, before I follow this up?

**Comment by brucebolt** [comment]
Dear Becca

It looks as though the online chat may have disconnected.  Did you receive a response to your query?

Best regards

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
