### ISSUE TITLE
Online chat - user emails becoming public

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4286]
I notice that normal helpdesk tickets submitted through the website help form mask the users email address when they are posted to GitHub (e.g. https://github.com/WormBase/website/issues/4243).  This does not seem to be the case for transcripts of online chats (e.g. https://github.com/WormBase/website/issues/4285).  Is there a way the email can be masked so the requestor's email address is not publicised on the web?

**Comment by brucebolt** [comment]
Also, should there be a disclaimer before users send a message and/or start an online chat that the contents of that chat will be published on the web?  A naive user could assume the conversation would be private.

**Comment by sibyl229** [comment]
Thanks @brucebolt ! I have taken a screenshot of the issues exposing emails and messaged @tharris. And I will delete all the user emails that are currently in those transcripts.

**Comment by sibyl229** [comment]
I don't have permission to modify those transcripts posts containing user emails @brucebolt @tharris

**Comment by tharris** [comment]
Full name and emails are now masked in both on- and off-line chat transcripts.
