### ISSUE TITLE
When did C. elegans appear in evolution?

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4290]
Question:
  When did C. elegans appear in evolution? Alternately, when did this worm and humans separate in evolution? I ask because there is a protein in the worm that appears to have a human ortholog. Thanks
Richard Stevens, Ph.D.
Prof., Dept. Med., Harvard Med. Sch.

What were you doing? 
  I am trying to understand why a gene my group cloned and its translated product is conserved in evolution.

Submitted From: 
  support /tools/support

This issue has been assigned ticket number: #. Follow progress on our issue tracker.

Reported by: Richard Stevens (***@hotmail.com) 
18 Oct 15 21:00 

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; .NET4.0E; GWX:DOWNLOADED; rv:11.0) like Gecko

This question was reported via the web interface at wormbase.org. You can also email us directly.

[[For some reason, this help request did not get a ticket number of get added to GitHub]]

**Comment by gw3** [comment]
See:
http://www.wormbook.org/chapters/www_intermetabolism/intermetabolism.html#sec2

"Recent estimates for the last common ancestor to vertebrates and 
nematodes range from 800 million to over one billion years ago (Hedges 
and Kumar, 2003 
<http://www.wormbook.org/chapters/www_intermetabolism/intermetabolism.html#bib59>; 
Hedges, 2002 
<http://www.wormbook.org/chapters/www_intermetabolism/intermetabolism.html#bib58>; 
Ureta-Vidal et al., 2003 
<http://www.wormbook.org/chapters/www_intermetabolism/intermetabolism.html#bib156>; 
Blaxter, 1998 
<http://www.wormbook.org/chapters/www_intermetabolism/intermetabolism.html#bib11>)."

This chapter of Wormbook, also has much to say about the conservation of 
metabolic pathways.
