### ISSUE TITLE
eri-12 phenotypes

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4291]
offline chat in eri-12 phenotypes please add enhanced RNAi (Fischer + Ruvkun 2013). same for gene arl-8
Submitted From: 
  http://www.wormbase.org/species/c_elegans/gene/WBGene00007091#04-95db81c-10 http://www.wormbase.org/species/c_elegans/gene/WBGene00007091#04-95db81c-10

This issue has been assigned ticket number: #. Follow progress on our issue tracker.

Reported by: alexandra (********) 
19 Oct 15 13:03 

This question was reported via the web interface at wormbase.org. You can also email us directly.

**Comment by kyook** [comment]
Dear Alexandra,

Thank you for bringing these papers to our attention.  I will add Fischer
and Ruvkun 2013 to my priority list for phenotype curation for WS252.

Best,
Karen

On Mon, Oct 19, 2015 at 5:59 AM, <no-reply@wormbase.org> wrote:

> offline chat in eri-12 phenotypes please add enhanced RNAi (Fischer +
> Ruvkun 2013). same for gene arl-8
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00007091#04-95db81c-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00007091#04-95db81c-10
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00007091#04-95db81c-10>
>
> This issue has been assigned ticket number: #. Follow progress on our issue
> tracker.
>
> Reported by: alexandra (alexandra.bezler@unil.ch)
> 19 Oct 15 13:03
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
Thanks Chris. This paper and related ones are highlighting the need for a better small rna branch of the phenotype ontology, so I'm delayed there. 

It should be done by ws252. 

-mobile-

**Comment by chris-grove** [comment]
@kyook  OK sounds good!

**Comment by kyook** [comment]
allele phenotypes have been entered for WS252 for this paper WBPaper00044603, unfortunately, eri-12(gk214100) was missed and will be in WS243.  This paper also has RNAi phenotypes that need curating.

**Comment by raymond91125** [comment]
@kyook should this be closed now?

**Comment by kyook** [comment]
I'm done with my part, there were no changes to the rna branch needed for
allele phenotypes. the paper still has RNAi phenotype data, of which I
informed Chris, and Gary.

karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, Feb 19, 2016 at 8:32 AM, Raymond Lee <notifications@github.com>
wrote:

> @kyook <https://github.com/kyook> should this be closed now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4291#issuecomment-186289668>.
>

**Comment by raymond91125** [comment]
@kyook  OK. Thanks. Leave open.

**Comment by chris-grove** [comment]
The specific request was for those alleles to be curated for "enhanced RNAi", so we can close this
