### ISSUE TITLE
sid-3 phenotype

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4292]
offline chat sid-3: phenotype add RNAi defective (Jose+ Hunter 2013). also add this paper to the reference list
Submitted From: 
  http://www.wormbase.org/species/c_elegans/gene/WBGene00002207#04-95db81c-10 http://www.wormbase.org/species/c_elegans/gene/WBGene00002207#04-95db81c-10

This issue has been assigned ticket number: #. Follow progress on our issue tracker.

Reported by: alexandra (alexa*****) 
19 Oct 15 13:16 

This question was reported via the web interface at wormbase.org. You can also email us directly.

**Comment by vanaukenk** [comment]
Hi,
I've made the appropriate gene-paper connections for Jose, et al., from 2012 (PMID:22912399) which I think is the paper Alexandra is referring to in this request.
--Kimberly

**Comment by kyook** [comment]
Dear Alexandra,

Thank you for bringing these papers to our attention.  I will curate the
phenotypes for sid-1, -2, and -3 from the backlog, these should be curated
and available online in the WS252 release.

Best,
Karen

On Mon, Oct 19, 2015 at 6:12 AM, <no-reply@wormbase.org> wrote:

> offline chat sid-3: phenotype add RNAi defective (Jose+ Hunter 2013). also
> add this paper to the reference list
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00002207#04-95db81c-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00002207#04-95db81c-10
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002207#04-95db81c-10>
>
> This issue has been assigned ticket number: #. Follow progress on our issue
> tracker.
>
> Reported by: alexandra (alexandra.bezler@unil.ch)
> 19 Oct 15 13:16
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
