### ISSUE TITLE
Annotations to anatomy terms P6.p, P7.p and P8.p

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#4293]
Annotations to anatomy term P6.p are problematic because when computed on, one cannot arrive at it's vulval or non-vulval nature; Annotations need to be changed to either 'P6.p hermaphrodite' or 'P6.p male', depending on the context in the paper.
Affects gene tissue-expression, gene regulation and phenotype data.

**Comment by draciti** [comment]
Karen: Looking at the postgres app tables (allele phenotype), there are 21 annotations that with P6.p as an anatomy annotation; 9/21 are concurrently annotated with a larval life stage. The default for all 21 annotations is that they are for hermaphrodites. 2/21 of the annotations are to hermaphrodite specific terms (e.g., vulval cell fate specification and VPC cell division variant).

In addition to using male specific anatomy terms, phenotype sex-based anatomy discrimination is and can be supported by using the
*lifestage ontology (e.g., adult male (WBls:0000056), L4 larval male Ce (WBls:0000073))
*male specific phenotype terms - male behavior variant (WBPhenotype:0000888) and male physiology variant (WBPhenotype:0000928), male tail development variant (WBPhenotype:0001297)

If male specific cell lineages were included in the anatomy ontology, I should think that would be the cleanest way forward.

**Comment by draciti** [comment]
Daniela: Please note this is true for all VPCs (p3.p-p8.p) not just P6.p -as stated above

Wen: 1. Classes with Pn.p entry:

Expr_pattern (Daniela will look up them)
Interaction (via #GR_condition -> Anatomy_term) (Xiaodong will look up them)

Anatomy_function (5 objects for Raymond):
Anatomy_function : "WBbtf0053"
Anatomy_function : "WBbtf0054"
Anatomy_function : "WBbtf0146"
Anatomy_function : "WBbtf0147"
Anatomy_function : "WBbtf0234"

WBProcess (1 object for Karen):
WBProcess : "WBbiopr:00000020"

    Classes with Anatomy_term tag but no entry for Pn.p:

Condition
Expression_cluster
GO_term
Paper
Strain (via #Phenotype_info -> Anatomy_term)
Variation (via #Phenotype_info -> Anatomy_term)
Transgene (via #Phenotype_info -> Anatomy_term)
RNAi (via #Phenotype_info -> Anatomy_term)

**Comment by kyook** [comment]
Fixed allele-phenotype annotations for all VPC Pn.p entries to their respective Pn.p hermaphrodite term.

**Comment by draciti** [comment]
Xiaodong: I’ve changed all P3.p - P8.p to P3.p -P8.p hermaphrodite for objects in regulation OA.

**Comment by draciti** [comment]
Expression_pattern: 120 annotations made to VPC Pn.p terms in postgres for expression pattern. 
only in 3 cases expression was assessed in both sexes, in 1 case just in male.
all annotations changed accordingly

Pictures: All VPC (pn.p) entries in pictures (~30) have been changed into pn.p hermaphrodite. No male instances

**Comment by raymond91125** [comment]
anatomy functions updated.

**Comment by draciti** [comment]
Closing this. All relevant curators modified data
