### ISSUE TITLE
  I'm trying to find a place to get Hae...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4295]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm trying to find a place to get Haemonchus contortus. I need them for my senior research at my college and I'm not sure where to get them. Located in central Florida.<br/>Thank you,<br/>Chloe</p>
    
**Reported by:** Chlo* (chlo******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by brucebolt** [comment]
Dear Chloe

In the genome paper (http://europepmc.org/articles/PMC4054779 <http://europepmc.org/articles/PMC4054779>) published by the Sanger/Calgary sequencing project for this species, they state "Both the MHco3(ISE) and the MHco3(ISE).N1 are viably cryopreserved and available on request”.

The corresponding authors for this paper are John Gilleard (jsgillea@ucalgary.ca <mailto:jsgillea@ucalgary.ca>) and James Cotton (james.cotton@sanger.ac.uk <mailto:james.cotton@sanger.ac.uk>).

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
