### ISSUE TITLE
WormBase ID to gene name conversion

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4297]
By email:

Hello, 
I'd like to input several WormBase ID's at once and get the gene name or cosmid name if the gene name is unavailable. For example, WBGene00004795 is sid-1. Is there any way to do that efficiently? I've looked at the WormMine tools, but haven't found exactly what I am looking for. 
Thanks!
Olga

**Comment by brucebolt** [comment]
Dear Olga

You can do this mapping on the WormBase ParaSite BioMart (http://parasite.wormbase.org/biomart/martview/).  In the ‘Filters’ section, choose C. elegans as the species then add your list of WormBase gene IDs in the ‘Gene’ section.  On the ‘Attributes’ section, choose ‘Gene name’.  Click ‘Results’ to get the complete list.

Best regards

Bruce

**Comment by tharris** [comment]
Hi Olga - 

Just to add to what Bruce has said, you can do this *very* easily in WormMine.

1. Visit WormMine (http://www.wormbase.org/tools/wormmine)
2. Paste in your list of identifiers into the "Analyse a List" text box.
3. Click Analyze
4. Save your list so you can repeat your analysis later (Click "save a list of genes")

You'll be presented with a sortable, exportable table showing WormBase ID, Gene name (locus), Sequence name, and a variety of other useful information.

Todd
