### ISSUE TITLE
  Just the tree display actually. nb. m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4303]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Just the tree display actually.<br/>nb. maybe we need a "Something is broken" option. </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to look at tree display for Variation by134</p>
    
**Reported by:** mary*********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

**Comment by tuli** [comment]
Still down today

**Comment by tharris** [comment]
The tree display shares resources with data mining facilities. If those are under heavy load, the tree display may not function in a timely manner.
