### ISSUE TITLE
Molecule page display of RNAi genes

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4304]
Carry over from issue #4181 

@sibyl229 

As for the RNAi experiments, we should be able to display the genes affected in the RNAi experiment from the "Inhibits  Gene  ?Gene  #Evidence" line in the RNAi object in ACEDB. I realize that there may be multiple genes that are considered primary or secondary targets. I would suggest that we pull all genes in the "Inhibits" tag with the qualifier "Inferred_automatically  RNAi_primary" as the genes to display in the "Genes affected" RNAi table on the molecule page. It could be formatted as the other genes are, with the WBRNAi ID in the "Details" column, meaning there could be just one table inside the "Genes Affected" widget.

Does that make sense?

**Comment by sibyl229** [comment]
Hi @chris-grove Here's the Genes Affected widget on Molecule page, with the RNAi related data merged into the big table as everything else: http://staging.wormbase.org/resources/molecule/WBMol:00004019#02--10
Thanks!

**Comment by chris-grove** [comment]
Excellent! Thanks @sibyl229 !!
