### ISSUE TITLE
Hello
Can't access Wormbase FTP website, need logi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4306]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello
Can't access Wormbase FTP website, need login details, is it normal ?
Thanks
Nishant
    
**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 45.0.2454.101

**Comment by tharris** [comment]
User contacted me directly too. FTP site was under some maintenance this weekend that took longer than expected. 

Issue resolved, user contacted, issue resolved. Closing.
