### ISSUE TITLE
Is wormmine brken?

"502 Bad Gateway"...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4307]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is wormmine brken?

"502 Bad Gateway"
    
**Reported by:** Wei **** (weic**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 46.0.2490.80

**Comment by brucebolt** [comment]
Reply from Todd:

Hi Wei -

Unfortunately, do to a system upgrade over the weekend, the current incarnation of WormMine is no longer functional.

We will be launching a (beta) test version of WormMine this week. Stay tuned.

Todd
