### ISSUE TITLE
Genome browsers for C. tropicalis and C. sinica not working

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4308]
The links for the C. tropicalis (sp. 11) and C. sinica (sp. 5) genome browsers in the main Species menu take me to the browser for brenneri, rather than the correct species.

**Comment by scottcain** [comment]
@brucebolt can you tell me what you did/were doing when it didn't work? It seems fine to me.

**Comment by Paul-Davis** [comment]
@scottcain 

I believe it is from the species dropdown on the main page

screencast of the issue
https://app.box.com/s/ncobbtz8gg3v6xtsy7fmm8t298rles8e

seems to just reload the genome browser of the species you last viewed?

Hopefully this is it @brucebolt

**Comment by scottcain** [comment]
Ah, I see--I think this is close to right on staging/WS250.  The "other" menu correctly names c_sp5 C. sinica and the link correctly goes to the sinica GBrowse page.  I noticed that C. tropicalis isn't mentioned on the staging Species menu at all.  Should I drop it from GBrowse and JBrowse?

**Comment by epaule** [comment]
as the G/JBrowse is one of the very few places where you can actually see
the C.tropicalis data, I would like if we could keep a G/JBrowse version of
it.

**Comment by khowe** [comment]
Related issue: S. ratti should appear at the top level in the Species drop-down. At the moment, it is under Others.

**Comment by sibyl229** [comment]
Yes. It's a drop-down menu problem. The C sinica menu link on staging site already works. I will fix the C. tropicalis one - it's probably a configuration issue on the website that it's still using the old name c_sp11 as key. I will make S. ratti show up in the top level menu.

**Comment by sibyl229** [comment]
The species menu link to GBrowse issue is fixed on staging. Could someone please help double check? And please note the until WS250 website release, the WormBase branded GBrowse staging pages still uses the WS249 website branding (like the header and menu). So those will appears as the buggy version for now. Thank you!

**Comment by brucebolt** [comment]
Menu links to GBrowse are working on staging, thanks @sibyl229.

**Comment by scottcain** [comment]
Yep, looks good to me too.  The way GBrowse pulls in the WB branding on staging does result in some confusion, at least for me.  At least once during a release cycle, I think there is something wrong until I remember that :-)  I'll go ahead and close this.
