### ISSUE TITLE
  Not a biologist. where can I find the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4309]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Not a biologist. where can I find the size of the daf2 gene or number of base pairs and the molecular mass in Daltons?<br/>Thanks</p><p>What were you doing? <br />&nbsp;&nbsp;Would like to see the size and general structure of the daf-2, age-1, hsf-1, and sir-2 genes and interested in the polarity of these genes.</p>
    
**Reported by:** Eric (etra*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by chris-grove** [comment]
Hello Eric,

 You can find this information on the daf-2 gene page and respective protein pages. The daf-2 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0-f9-3

shows 6 recognized transcripts that each produce different protein products. If you click on the link for a given protein product, e.g. "DAF-2, isoform a", you will be directed to the corresponding protein page:

http://www.wormbase.org/species/c_elegans/protein/WP:CE46852#06--10

where you can see information for estimated (predicted) molecular weight and estimated (predicted) iso-electric point for that particular protein.

The same applies to the other genes you mention. Let us know if you have trouble finding what you're looking for.


Best,

Chris Grove
WormBase Help Desk
