### ISSUE TITLE
I have a set of microarray data that is derived fr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4310]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have a set of microarray data that is derived from differential polyribosome vs free mRNA.  The data are in Excel spreadsheets. We are submitting to J Cell Sci, and they ask that we get the data submitted and a provisional accession # before resubmitting the manuscript.  Can I get instructions for submitting?  Can the data be "embargoed" prior to the article publication?

  Thanks, Brett
    
**Reported by:** Bret******** (keip***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#10--10">http://www.wormbase.org/about/userguide/submit_data#10--10</a>
**Browser:** Firefox 41.0

**Comment by WenChenWormBase** [comment]
Dear Brett,

Please consider submitting  your microarray data to Gene Expression Omnibus
(GEO). We have a pipeline to get them from there and then display them in
WormBase. You data can be "embargoed" in GEO.


Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
User reply: 

Thanks,

 

I’ve looked into that as well.  I’ll contact GEO.

 

Brett D. Keiper, Ph.D.

Associate Professor & Graduate Director

Biochemistry & Molecular Biology

Brody School of Medicine at East Carolina University

600 Moye Blvd., Greenville, NC 27834
