### ISSUE TITLE
  How do upload information about new a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4313]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do upload information about new alleles available. </p><p>What were you doing? <br />&nbsp;&nbsp;publishing information about new worm strains created</p>
    
**Reported by:** Jess**** (jsul***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by chris-grove** [comment]
Hello Jessica,

To submit new allele information you can use our Allele-Sequence submission web form:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele_sequence.cgi

You can find this form by clicking on the "Submit Data" header on the WormBase homepage, and clicking on the "Fill out online form" button to the right of "Allele Sequence Data Submission" on the subsequent page.

I'm also CC'ing Mary Ann Tuli, the WormBase strain and allele-sequence curator.

Let us know if you have any further questions.

Best,

Chris Grove
WormBase Help Desk
