### ISSUE TITLE
  Interaction map for wrm-1 would not l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4314]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Interaction map for wrm-1 would not load. </p><p>What were you doing? <br />&nbsp;&nbsp;using Chrome and listening to Pandora  </p>
    
**Reported by:** NaTa************ (nata************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

**Comment by chris-grove** [comment]
Hi Natasha,

 I can replicate the problem here as well. Apologies.

 Our web team will take a look as soon as they can. I'll touch base with
you again tomorrow.

Chris Grove
WormBase Help Desk

**Comment by chris-grove** [comment]
Confirmed on live site and staging.

**Comment by sibyl229** [comment]
Hi Chris,

It seems that the proxy is blocking the interaction widget of wrm-1, so I can only access it from the un-proxied URI. I will ask Todd about it. I’m attaching you a copy of the wrm-1 interactions table via email. github doesn’t seem to accept html as attachment.

**Comment by chris-grove** [comment]
User e-mailed html file of wrm-1 interactions table. Thanks @sibyl229 !

Will leave open until issue is resolved.

**Comment by chris-grove** [comment]
Todd looking into. May be related to the pry-1 gene page problem (site attack)

**Comment by tharris** [comment]
This should now be resolved (see #4358 for description)

**Comment by chris-grove** [comment]
user contacted
