### ISSUE TITLE
WormMine Sequence bug

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4315]
Hi,

It looks like when trying to retrieve the sequence of a CDS you are presented with a table that only contains the sequence of the last exon.

Query XML

```
<query name="" model="genomic" view="CDS.sequence.residues CDS.primaryIdentifier CDS.symbol" longDescription="" sortOrder="CDS.sequence.residues asc">
  <constraint path="CDS.gene.symbol" op="=" value="lev-10"/>
</query>
```

Example CDS summary page:
http://www.wormbase.org/species/c_elegans/cds/Y105E8A.7b#05--10

**Comment by nuin** [comment]
Can we close this?

**Comment by Paul-Davis** [comment]
Original query is no longer valid and the updated query

```
<query name="" model="genomic" view="CDS.primaryIdentifier CDS.symbol CDS.length" longDescription="" sortOrder="CDS.primaryIdentifier asc">
  <constraint path="CDS.gene.symbol" op="=" value="lev-10"/>
</query>
```
 Gives no length information so maybe a non-issue now unless the CDS lengths should be accessible.

**Comment by chris-grove** [comment]
Duplicate with #6166
