### ISSUE TITLE
WormMine filter for "has a value"

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4316]
seems to be broken for Gene > Brief Descriptions

![screenshot from 2015-10-27 10 29 32](https://cloud.githubusercontent.com/assets/20523/10756707/e283944a-7c9d-11e5-9d57-10c64760fe58.png)

meaning: I cannot query for genes with a Brief Description.

**Comment by tharris** [comment]
You have to click on the text that says "Filter query results..." to enable that option.

**Comment by epaule** [comment]
ah ... that explains it.
