### ISSUE TITLE
chromosome lookup

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4319]
I don't think the chromosome lookup works ... unless it is not supposed to propose sequence names in the autocomplete.

![screenshot from 2015-10-27 14 14 39](https://cloud.githubusercontent.com/assets/20523/10760610/47a4cdaa-7cb5-11e5-906b-eda936451f87.png)

**Comment by sibyl229** [comment]
Hi @epaule unfortunately I don't think the autocomplete comes from WormMine. It probably comes from your browser? I checked http://www.flymine.org/flymine/query.do and they don't have this feature either.
