### ISSUE TITLE
Hi i have noticed the SL1 and SL2 red and green tr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4321]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi i have noticed the SL1 and SL2 red and green triangles some times face in one direction and some times face in another, does this mean something?
    
**Reported by:** Kayl* (kayl******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001016#20e356d-9f1478abcihg-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001016#20e356d-9f1478abcihg-3</a>
**Browser:** Chrome 46.0.2490.71

**Comment by epaule** [comment]
yes, it is the strand of the SL splice acceptor site. Similar to regular splicing sites, they are strand specific.
