### ISSUE TITLE
How to create templates in intermine/wormmine.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4322]
From email:

Todd,

It's really great to see the update, well done you guys

Could you remind staff/me how to create an account with the necessary permissions to produce templates and publish them as we could on the old instance.

Thanks

Paul

**Comment by tharris** [comment]
You need to a) be a super user and b) add tags of `im:frontpage` and  `im:public` (and any other of the tags for appropriate categorization). If you've logged in with Google, I have no way of seeing who you are and promoting you to super user status. If you log in via an email address, I can do so.

**Comment by Paul-Davis** [comment]
@tharris I have created an account with my pad@ebi.ac.uk email address, am I worthy of a super user account :)

**Comment by chris-grove** [comment]
@Paul-Davis  I think this got lost in the mix. You're now a super user if you login with that e-mail address.

**Comment by Paul-Davis** [comment]
Thanks @chris-grove

**Comment by chris-grove** [comment]
@tharris 
I'm now able to login and produce templates with the appropriate tags to make them official templates, but two issues remain:
1) I still cannot edit existing templates, only new ones that I create
2) I made a testing template and deleted it, but it is still showing up in the templates list

**Comment by tharris** [comment]
The templating aspect of Intermine seems a bit wonky wrt to some functions. I will raise with Intermine developers

**Comment by chris-grove** [comment]
@tharris  OK, thanks for the heads up.

**Comment by vanaukenk** [comment]
@tharris 
I would like to be able to add a GO-related template query to WormMine.  I just created a new account with vanauken at caltech email address.  Thx.

**Comment by chris-grove** [comment]
@vanaukenk  I just made you a WormMine super user. You should be able to make templates and put them on the front page by adding the tags `im:frontpage` and `im:public`
