### ISSUE TITLE
species -> protein template broken for non-elegans worms

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4323]
the species -> protein template

http://im-dev.wormbase.org/tools/wormmine/template.do?name=species_proteins&scope=all

works for C.elegans, but not for C.briggsae, etc. ...

**Comment by nuin** [comment]
It seems that the FASTA files for all other species are not being loaded correctly. I am checking the project file to define the reason.

**Comment by nuin** [comment]
@epaule I did some test build adding a couple of more FASTA sources and it worked fine. I should be able roll in the next build.

**Comment by epaule** [comment]
still broken for B.malayi protein and the WS266 WormMine

**Comment by nuin** [comment]
@epaule I am working on adding protein sequences from 

b_malayi  
c_brenneri
c_remanei
c_tropicalis
p_pacificus
s_ratti
c_angaria 
c_briggsae
c_japonica 
c_sinica
o_volvulus
p_redivivus
t_muris

A full test build should be ready in a day or so. Any other species I should add?

**Comment by epaule** [comment]
Ah, ok.
I think we have some zombie CDSes for proteins who were retired between the
current release and when the respective species was last built.

M

**Comment by epaule** [comment]
Looks like it does what it is supposed to do.
And maybe we can split off the species dropdown thing into a separate ticket for a future release.

**Comment by nuin** [comment]
OK, I discussed the dropdown with InterMine some time ago and it wasn't straightforward. I will try to get the information again and check.

**Comment by nuin** [comment]
@epaule Is it OK if we close this? For most of the core species the template works fine.

**Comment by epaule** [comment]
yup, I think we can close it.
