### ISSUE TITLE
Overview widget on "Variant" phenotype page on staging isn't loading

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4326]
http://staging.wormbase.org/species/all/phenotype/WBPhenotype:0000886#03--9

**Comment by sibyl229** [comment]
Hi @chris-grove the 'Variant' Phenotype Overview is working on staging now: http://staging.wormbase.org/species/all/phenotype/WBPhenotype:0000886#03--9. Please take a look. Thank you!

**Comment by chris-grove** [comment]
Great thanks @sibyl229 !
