### ISSUE TITLE
  I am setting up my new lab and would ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4329]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am setting up my new lab and would like to apply for strain and allele designations.  Please advice. </p>
    
**Reported by:** Ron **** (r.a.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by raymond91125** [comment]
Hi Ron,

Congrats. You can find guidelines under "How to apply for new names", 
here 
<http://www.wormbase.org/about/userguide/nomenclature#7c2gfbihe9j685d31kma0l4--10>.

Cheers,

Raymond
