### ISSUE TITLE
  Dear editor,  I am a postgraduate wit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4331]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear editor, <br/>I am a postgraduate with Sun yat-sen University in China. I am searching for some information  about nematode strains for my furthur experiment. But I meet some problems. I realy need your help.<br/>I know the name of the transgene of the c elegans,but I can't get the strains' name when I searched them in wormbase. The transgene is  "jgIs6" ,"jgIs25","let-23","let-60" and "lin-15". Could you please tell me the exact name of the strains? I really appreciate your help!<br/>Thank you very much! Looking forward for your reply soon. <br/>Best wishes,<br/>Daisy</p>
    
**Reported by:** Dais* (huan********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by chris-grove** [comment]
Hello Daisy,

 It looks like we don't have any strain information about the transgenes jgIs6 or jgIs25. Sometimes authors only reference the transgene name in a paper, and don't mention the strain. Your best option is probably to e-mail the corresponding author of the paper that introduced them and ask. For other transgenes, if we have the strain ID, you may find it in the "Overview" widget of the transgene page, like this one:

http://www.wormbase.org/species/all/transgene/WBTransgene00001874#0--10

Good luck and let us know if you need help with anything else.

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
User responded, was happy with information
