### ISSUE TITLE
GenBlastG tracks

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4332]
could we have a track on G/JBrowse showing the GenBlastG features in the GFF3:
as example:

```
Crem_Contig18	genBlastG	CDS	163321	163592	.	-	0	ID=CDS:GBG_remanei_C46A5.3b
```

and it would be good if the ID could show up.

We have them also in the GFF2 if needed, but we want to extend the GenBlastG to the Tier 3 worms of clade V, and also show them for the C.elegans Hawaii strain.

**Comment by scottcain** [comment]
Hi @epaule ,

Here's the first stab at it for JBrowse:

http://staging.wormbase.org/tools/genome/jbrowse/full.html?data=data%2Fc_remanei_PRJNA53967&loc=Crem_Contig0%3A83997..89210&tracks=Curated_Genes%2CProtein%20motifs%2CgenBlastG%20CDS%20predictions&highlight=

Several questions:

1. Do you have preferences for colors or anything else about the glyph (fat versus skinny, etc)?

2. Is there somewhere clicking on these features should link to?

3. Is there a description of what the data are?

**Comment by draciti** [comment]
thanks James!

**Comment by epaule** [comment]
1.) something gene like ... like the glyph you used, and I don't mind the colour (... unless it is a very pale blue, as I can't differentiate it from white)

2.) if you feel motivated, they could be linked up to the respective C.elegans gene through the last bit of their name ... but to be fair, having them visible and show the id is already very useful.

3.) it is from WBPaper00040677, "an efficient algorithm, that directly uses the HSPs reported by BLAST to define high-quality gene models." basically a poshed up alignment of the C.elegans proteins in our case. It has its issues with very diverged genomes, but within clade V it is quite useable.

**Comment by scottcain** [comment]
Hi @epaule 

This is the current iteration of this track for C. remanei:

http://staging.wormbase.org/tools/genome/jbrowse/full.html?data=data%2Fc_remanei_PRJNA53967&loc=Crem_Contig0%3A84012..89225&tracks=Curated_Genes%2CProtein%20motifs%2CgenBlastG%20CDS%20predictions&highlight=

I added links, a track description and made the glyph a little skinnier.  If you're good with it, I'll start working on the infrastructure bits to recreate it for future releases, as well as "back porting" it to GBrowse.  Are there other organisms for which this data exist in WormBase?

**Comment by epaule** [comment]
it looks very much like they vanished:
[image: Inline images 1]

**Comment by scottcain** [comment]
Oops! I was moving things around and forgot to fix a path.  It's back now.

**Comment by epaule** [comment]
looks fancy .... nice :-)

**Comment by epaule** [comment]
i think it looks good to spread to C.briggsae, C.brenneri and C.japonica?

**Comment by scottcain** [comment]
Hi @epaule 

I added a genBlastG track to the C. remanei GBrowse instance on staging:

http://staging.wormbase.org/tools/genome/gbrowse/c_remanei_PRJNA53967/?start=57015;stop=58600;ref=Crem_Contig0;width=800;version=100;flip=0;grid=on;id=0e64448f783c71df9bcc5f6c7c26f4c6;l=CDS%1EGENBLASTG%1EPROTEIN_MOTIFS%1EGENES

It's not likely to stick around for long, as we'll be building 251 on staging soon, but if you could take a look and comment, that would be great.

**Comment by epaule** [comment]
Hi @scottcain , hmm ... I can't see them.

**Comment by scottcain** [comment]
@epaule I think I was bitten by an automatic rebuild of the config, try again now.

**Comment by epaule** [comment]
that looks nicer :-)
From an aesthetic point of view, I would probably change the default glyph
to gene, but else it looks fine.

**Comment by scottcain** [comment]
Hi @epaule I wasn't sure if you'd want to take advantage of the reading frame aspect of the cds glyph (to show if there are differences in the reading frame between these features and the annotated CDSes).  I changed it to the gene glyph with strand-based coloring like the gene annotations.

**Comment by epaule** [comment]
hmm ... you got a point. But I think the gene glyph looks nicer.

**Comment by scottcain** [comment]
This has been included in GBrowse and JBrowse for the last two releases.  Closing...
