### ISSUE TITLE
 Server Error: 500 at  rest/widget/laboratory/KR/m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4336]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/laboratory/KR/members">rest/widget/laboratory/KR/members</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "Can't call method "row" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Laboratory.pm line 256." </p><p>What were you doing? <br />&nbsp;&nbsp;Looking at the lab members of the KR (Ann Rose) Lab. </p>

**Reported by:** Mary********* (mary*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//rest/widget/laboratory/KR/members">members</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by tharris** [comment]
This looks to be a data model / data population problem. @sibyl229 we *might* be able to hotfix this.

**Comment by Paul-Davis** [comment]
@tharris could you advise on the data model/  data population problem if this needs input from curators/build team?

**Comment by Paul-Davis** [comment]
removing helpdesk as ticket was created staff

**Comment by sibyl229** [comment]
Duplicated of #4347. And fixed in production http://www.wormbase.org/resources/laboratory/KR#03--10
