### ISSUE TITLE
expression widget for non-elegans genes

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4343]
It looks like the expression widget for Bma-eat-4 is empty:
http://www.wormbase.org/species/b_malayi/gene/WBGene00227744

but it technically has FPKM values, etc. (as you can see in the treeview)

**Comment by sibyl229** [comment]
Hi @epaule I think the Expression widget for Bma-eat-3 is working now: http://staging.wormbase.org/species/b_malayi/gene/WBGene00227744#-019-10

**Comment by epaule** [comment]
sweet :-)
I might be tempted to add more RNASeq libraries to it in the next few releases
