### ISSUE TITLE
  Hi,  I would like to create a text fi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4345]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I would like to create a text file containing a brief description for all the C. elegans genes, for example, the information that appears in the "overview" section when you search for a gene.  Is such a file available?  If so, can you direct me to where I should download it?  If it's not available, can you guide me through the the steps I would take to compile the information?  Thanks so much!</p><p>What were you doing? <br />&nbsp;&nbsp;Searching the wormbase site for such a list.  Also, starting to manually compile my own based on truncated bits I've started compiling from various publications.</p>

**Reported by:** Kris*** (kste*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by raymond91125** [comment]
Hi Kristan,

You can find much of the information in a file from our FTP server. For 
WS250, <c_elegans.PRJNA13758.WS250.functional_descriptions.txt.gz>

at
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/annotation/>

Let us know if you need something else.

Raymond
