### ISSUE TITLE
 Server Error: 500 at  rest/widget/laboratory/JJ/m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4347]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/laboratory/JJ/members">rest/widget/laboratory/JJ/members</a><p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "row" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Laboratory.pm line 256." </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to see the lab members page for the JJ lab</p>

**Reported by:** Mark******* (edgl**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Thanks for the report Mark! Our web team will look into the issue, which you can follow on GitHub here:

https://github.com/WormBase/website/issues/4347

Best,

Chris Grove

**Comment by chris-grove** [comment]
Confirmed on live site and staging site:
![screen shot 2015-11-09 at 11 10 26 am](https://cloud.githubusercontent.com/assets/611382/11043763/359b3a86-86d3-11e5-8fa1-e2db4de713db.png)

**Comment by Paul-Davis** [comment]
also reported here #4336

**Comment by Paul-Davis** [comment]
@sibyl229 looks to be fixed on staging but I guess the widgets are cached for WS250 on the www site?
