### ISSUE TITLE
PCR_product mv_ZK688.foo

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4352]
Hi @chris-grove ,

As you are one of the main consumers of the PCR_product data in the team, do you think this is a real reagent or something invented by the person from Lincoln's team who was testing out the import of the MV data?

PCR_product: mv_ZK688.foo
Oligo: mv_ZK688.foo_b
Oligo: mv_ZK688.foo_f

Looks like a classic perl programmers object ;)

Cheers

Paul

**Comment by chris-grove** [comment]
@Paul-Davis 

Haha, yeah, I was looking for mv_ZK689.bar   ;)

It actually looks like a legitimate PCR product, according to the WORFdb website:

http://worfdb.dfci.harvard.edu/searchallwormorfs.pl?by=name&sid=ZK688.foo

**Comment by Paul-Davis** [comment]
@chris-grove  ha...must pre-date wormbase and was an error in the original library generation ;)
