### ISSUE TITLE
Wormbase site very slow/not loading

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4355]
I am having problems to open the site (firefox and safari)

**Comment by chris-grove** [comment]
I've experienced the same

**Comment by tharris** [comment]
I'm working on it. :(

**Comment by draciti** [comment]
thanks Todd

**Comment by tharris** [comment]
we're being indexed by Google and a few others at the moment. I normally trap these queries and send to a sandboxed environment where they won't disturb our main users. Some of these queries were escaping -- I've fixed this problem and performance should be back to normal.

66.249.64.147 - - [10/Nov/2015:22:20:20 +0000] "GET /search/all/CBG15968 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:21 +0000] "GET /species/s_ratti/gene/WBGene00260535 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:22 +0000] "GET /species/c_elegans/transcript/C25A11.1.1 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:22 +0000] "GET /species/c_elegans/transcript/C04E6.13 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:23 +0000] "GET /species//go_term/GO:0043374 HTTP/1.0" 307 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:23 +0000] "GET /species/all/protein/MSP:IATALPGIVQEETPEQPNIVIMNPPKDAEESQGR HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:24 +0000] "GET /species/p_pacificus/gene/WBGene00093477 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:24 +0000] "GET /species/b_malayi/gene/WBGene00231402 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:24 +0000] "GET /species/s_ratti/gene/WBGene00256548 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.147 - - [10/Nov/2015:22:20:25 +0000] "GET /search?q=BJ772710 HTTP/1.0" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**Comment by draciti** [comment]
seems to be faster than ever..thanks. closing

**Comment by raymond91125** [comment]
@draciti, spoke too soon?

**Comment by tharris** [comment]
Sigh. It would be great if we had a running issue for uptime. But then nobody would notice.
