### ISSUE TITLE
Huma (hkhan15@luc.edu): How can I reference this w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4357]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Huma (hkhan15@luc.edu): How can I reference this website to use as a citation</br>Huma (hkhan15@luc.edu): hello??

**Reported by:** Huma (hkha***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006797#0-9f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006797#0-9f-3</a>
**Browser:** Chrome 46.0.2490.80

**Comment by chris-grove** [comment]
Hello Huma,

 Apologies for missing you on the online chat. Thank you for citing
WormBase in your paper. You may either acknowledge WormBase.org in the
Acknowledgements section, or better, refer to our 2014 Nucleic Acids
Research paper:


Harris TW, Baran J, Bieri T, Cabunoc A, Chan J, Chen WJ, Davis P, Done J,
Grove C, Howe K, Kishore R, Lee R, Li Y, Muller HM, Nakamura C, Ozersky P,
Paulini M, Raciti D, Schindelman G, Tuli MA, Van Auken K, Wang D, Wang X,
Williams G, Wong JD, Yook K, Schedl T, Hodgkin J, Berriman M, Kersey P,
Spieth J, Stein L, Sternberg PW. WormBase 2014: new views of curated
biology. Nucleic Acids Res. 2014 Jan;42(Database issue):D789-93. doi:
10.1093/nar/gkt1063. Epub 2013 Nov 4. PubMed PMID: 24194605; PubMed
Central PMCID: PMC3965043.


Best regards,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Also, you may refer to our "How to Cite" page:

http://www.wormbase.org/about/citing_wormbase#0123--10

at the bottom of the WormBase homepage, if you ever forget.

Thanks again,

Chris

**Comment by chris-grove** [comment]
User is happy
