### ISSUE TITLE
  Finding pry-1?  What were you doing? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4358]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Finding pry-1?</p><p>What were you doing? <br />&nbsp;&nbsp;WB is choking on finding gene 'pry-1' via gene search or other method. Some widget problem. </p>

**Reported by:** Curt******* (cloe**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Curtis,

Thanks for reporting this problem. There have been problems with 
accessing this gene before as the specific url was targeted and had 
1000s of requests. This was resolved, but something seems to be broken 
again. The web team are now aware and will hopefully get is resolved asap.

Paul
[HelpDesk]

#3353


On 11/11/2015 01:34, no-reply@wormbase.org wrote:
> Bug Report
>
>   Finding pry-1?
>
> What were you doing?
>   WB is choking on finding gene 'pry-1' via gene search or other 
> method. Some widget problem.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4358. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4358>.
>
> Reported by: Curtis Loer (cloer@sandiego.edu)
> 11 Nov 15 01:35
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Any update on the pry-1 url issue?

**Comment by Paul-Davis** [comment]
@sibyl229 can you see anything in the web code that would prevent the user searching for this gene?

Thanks

helpdesk

**Comment by scottcain** [comment]
I am pretty sure this doesn't stay "fixed"; @tharris will periodically unblock this page when someone complains, but the attacker always comes back, the page has to blocked again.

**Comment by Paul-Davis** [comment]
@scottcain thanks for the update, Is there anything that we can do?

**Comment by tharris** [comment]
I have put in place more sophisticated checks for this (and other) problems. If certain thresholds are crossed, access to specific resources will be blocked for a limited time. I've also blacklisted a huge group of URIs. So this should be resolved.  We don't, of course, handle things like this at the application level.

**Comment by chris-grove** [comment]
@Paul-Davis  It seems to be working fine for me. Is it still giving you problems?

**Comment by Paul-Davis** [comment]
no closed the ticket as it seemed to come good after a short while.

**Comment by Paul-Davis** [comment]
Dear Curtis,

Thanks again for reporting this problem. The gene should be back now.

Paul





On 11/11/2015 10:16, Paul Davis wrote:
> Dear Curtis,
>
> Thanks for reporting this problem. There have been problems with 
> accessing this gene before as the specific url was targeted and had 
> 1000s of requests. This was resolved, but something seems to be broken 
> again. The web team are now aware and will hopefully get is resolved asap.
>
> Paul
> [HelpDesk]
>
> #3353
>
>
> On 11/11/2015 01:34, no-reply@wormbase.org wrote:
>> Bug Report
>>
>>   Finding pry-1?
>>
>> What were you doing?
>>   WB is choking on finding gene 'pry-1' via gene search or other 
>> method. Some widget problem.
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #4358. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/4358>.
>>
>> Reported by: Curtis Loer (cloer@sandiego.edu)
>> 11 Nov 15 01:35
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 
>> (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
