### ISSUE TITLE
  find how many exons an organism has f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4363]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;find how many exons an organism has from the information on your website?</p>

**Reported by:** Trea*** (lmpz****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by Paul-Davis** [comment]
Hi,

Thanks for your question.

You can bulk download all of the annotation features from our FTP site 
for any give species we have in our database.

This file can then be used to parse out the exon features, but it really 
depends what type of exon you are interested in.

This is the C. elegans file
c_elegans.PRJNA13758.WS250.annotations.gff3.gz

found here: 
ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/

Once you have the file you can pull out "exon" lines and count how many 
there are, but as I said there are exons for coding genes, non-coding 
genes, pseudogene etc.

If you have a look at the file and have specific requirements, please 
feel free to get back to us and we can give further advice.

Paul

On 11/11/2015 16:32, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   find how many exons an organism has from the information on your 
> website?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4363. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4363>.
>
> Reported by: Trease (lmpzpd@mail.umsl.edu)
> 11 Nov 15 16:33
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
User corresponded privately
