### ISSUE TITLE
how do I find out what causes a certain phenotype?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4366]
*Help Desk query collected when no chat operators were online. Follow up required.*

how do I find out what causes a certain phenotype?

**Reported by:** Stel** (Sjil***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006#0--10">http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006#0--10</a>
**Browser:** Chrome 46.0.2490.80

**Comment by Paul-Davis** [comment]
Dear Stella,

You were on the right lines looking on this Phenotype summary page.

http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006#0456--10

Turning on a few more of the panels you can see that there are a variety 
of experiments that have been done that are associated with this phenotype.

Gene knockdown via RNAi results in the egg laying defective 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006> 
phenotype.

Transgenes associated with this phenotype:

Variations associated with this phenotype:

It seems that there are quite a few genes associated with this phenotype.

An additional resource is http://www.wormbook.org/ which might give 
additional context to this complicated phenotype.

I hope this helps.

Paul
[HelpDesk]



On 12/11/2015 05:04, no-reply@wormbase.org wrote:
> offline chat how do I find out what causes a certain phenotype?
>
> Submitted From:
>   http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006#0--10 
> http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006#0--10 <http://www.wormbase.org/http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000006#0--10> 
>
>
> This issue has been assigned ticket number: #4366. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4366>.
>
> Reported by: Stella (Sjiler.2017@saintannsny.org)
> 12 Nov 15 05:05
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Closing as no further contact from user.
