### ISSUE TITLE
  I apologize if this is not the correc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4369]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I apologize if this is not the correct way to notify you, but I wanted to let you know that the molecular nature of the e1605 allele of the mec-12 gene ( currently unannotated), which is also identical to the u50 alelle (also unannotated), has been identified in the following paper: "The Multipurpose 15-Protofilament Microtubules in C. elegans Have<br/>Specific Roles in Mechanosensation" from the Chalfie lab. The nature of the mutation is a point mutation of C4357T which results in the amino acid change H192Y. Please feel free to let me know if you have any questions. Thanks for running Wormbase!</p><p>What were you doing? <br />&nbsp;&nbsp;Researching tubulin alleles to identify potential nulls. </p>

**Reported by:** Dean********* (lock*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by tuli** [comment]
Dear Dean,

Thank you for contacting WormBase.

I have updated e1605 and u50 according to the information you have
provided. You'll see the updated records in release WS252
of WormBase.

Writing to help@wormbase.org email is fine, you can be sure your query
will find its way to the right person. For future reference though
you may submit variation data via our online form:
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele_sequence.cgi
The advantage of using the form is that it ensures we have all the
information we need and it provides hints for more complicated
submissions.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
