### ISSUE TITLE
  how can I know how many exons and int...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4370]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how can I know how many exons and introns are represented for this gene?</p>

**Reported by:** grul*************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by tharris** [comment]
Hello grulloyr - 

Either 

a) vist the Genome Browser and view the region of the genome for the gene of interest, or 

b) check the Sequence widget of the gene page

Both will provide you the information you seek.

Todd
