### ISSUE TITLE
  When translating or looking for ident...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4374]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;When translating or looking for identifiers do you have a wildcard character.<br/>For example how can I get all info related to WBGene0000432* (where * is any numbers)</p>

**Reported by:** Adri************* (pasc*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by Paul-Davis** [comment]
Dear Adrian,

Thanks you for your question.

I'm not sure I full understand what you are requesting, but yes, you can 
query the website (Main search box) with wild cards.

http://www.wormbase.org/search/gene/WBGene0000432*

Page 1 returns all the results for the term you have specified, the 
other pages contain hits where there are connections to the primary 
genes returned by your query.

here are a list of gene pages that summarise the information about the 
main genes returned by your query.

http://www.wormbase.org/species/c_elegans/gene/WBGene00004320#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004321#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004322#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004323#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004324#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004325#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004326#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004327#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004328#094f--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00004329#094f--10

I hope that helps.

Paul

On 13/11/2015 15:28, no-reply@wormbase.org wrote:
> Question:
>
>   When translating or looking for identifiers do you have a wildcard 
> character.
> For example how can I get all info related to WBGene0000432* (where * 
> is any numbers)
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4374. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4374>.
>
> Reported by: Adrian Pasculescu (pasculescu@lunenfeld.ca)
> 13 Nov 15 15:28
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:42.0) Gecko/20100101 
> Firefox/42.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
