### ISSUE TITLE
  How do I get a list of protein coding...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4375]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get a list of protein coding genes in C. elegans?<br/>Current version (WS250) entails 20359 protein-coding genes, and what are they?<br/>Thank you,<br/>visitor_name</p>

**Reported by:** Byun********* (byun*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi and thank you for your question.

If you would like sequence data for the C. elegans protein coding genes 
this can be retrieved from package of files called WormPep

c_elegans.PRJNA13758.WS250.wormpep_package.tar.gz 
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.wormpep_package.tar.gz>

If you would like to try and get additional insight into gene function 
you can explore our data mining platform WormMine

http://im-dev.wormbase.org/tools/wormmine

Here you can access information starting with protein identifiers but 
traverse the data structure to extract a variety of information 
including gene descriptions.

Example XML query that you can import into wormmine:

  <query name="" model="genomic" view="Protein.primaryIdentifier 
Protein.symbol Protein.organism.name Protein.primaryAccession 
Protein.CDSs.gene.primaryIdentifier 
Protein.CDSs.gene.secondaryIdentifier Protein.CDSs.gene.description" 
longDescription="" sortOrder="Protein.primaryIdentifier asc"> 
<constraint path="Protein.organism" op="LOOKUP" value="Caenorhabditis 
elegans"/> </query>

Importer: http://im-dev.wormbase.org/tools/wormmine/importQueries.do

Example output of above query:

WP:CE00072    HSP-12.2    Caenorhabditis elegans    WP:CE00072 
WBGene00002011    C14B9.1    hsp-12.2 encodes a small heat-shock protein 
that forms heterotetramers with HSP-12.3 and has no chaperone-like 
activity; structurally, HSP-12.2 is mostly a beta-sheet; at least one 
HSP-12 (which may or may not be HSP-12.2) is ubiquitously expressed in 
L1 larvae, and later expressed in adult spermatids (and perhaps 
spermatocytes), and some adult vulval cells.

Full Query results:
http://goo.gl/NqQsrX


I hope this helps.

Paul
[HelpDesk]



On 13/11/2015 16:54, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I get a list of protein coding genes in C. elegans?
> Current version (WS250) entails 20359 protein-coding genes, and what 
> are they?
> Thank you,
> Byunghyuk Kim
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4375. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4375>.
>
> Reported by: Byunghyuk Kim (byunghyuk.kim@einstein.yu.edu)
> 13 Nov 15 16:55
>
> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) 
> Chrome/46.0.2490.86 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
closing as no further contact from user.
