### ISSUE TITLE
  Got an error when I was trying to dow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4376]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Got an error when I was trying to download:<br/>c_elegans.PRJNA13758.WS250.CDS_transcripts.fa.gz<br/>from the download area:<br/>Index of ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/<br/>The error was: Alert<br/>550: Failed to change directory</p>

**Reported by:** Adri************* (pasc*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by Paul-Davis** [comment]
Dear Adrian,

Thanks again for your bug report, It looks like there is a problem with 
the synchronisation of our ftp site, while we look into what's gone 
wrong a copy of the file can be downloaded from here:

ftp://ftp.sanger.ac.uk/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.CDS_transcripts.fa.gz

Paul



On 13/11/2015 17:16, no-reply@wormbase.org wrote:
> Bug Report
>
>   Got an error when I was trying to download:
> c_elegans.PRJNA13758.WS250.CDS_transcripts.fa.gz
> from the download area:
> Index of 
> ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/
> The error was: Alert
> 550: Failed to change directory
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4376. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4376>.
>
> Reported by: Adrian Pasculescu (pasculescu@lunenfeld.ca)
> 13 Nov 15 17:16
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:42.0) Gecko/20100101 
> Firefox/42.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
This turned out to be a data production issue, recrecreated the file and placed in the release WS250 FTP dir which should be synced to the WB FTP on the cron.

Communicated error and fix to user.
