### ISSUE TITLE
The "Search for the clones" link for searching fos...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4377]
*Help Desk query collected when no chat operators were online. Follow up required.*

The "Search for the clones" link for searching fosmids from Don Moerman´s library does not work for some time

**Reported by:** Henn*********** (Henn********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/reagents#24301--10">http://www.wormbase.org/resources/reagents#24301--10</a>
**Browser:** Safari 5.1.9

**Comment by Paul-Davis** [comment]
Dear Henning,

Thank you for reporting the issue with the link in our documentation. It 
appears that this external tool has been retired so I have updated the 
link to point to the Source BioScience GenomeCUBE clone finder tool.

The data for this clone resource is also contained within WormBase 
itself and report pages can be generated by limiting the main search to 
clone and using the WRM clone identifiers.

Examples:
Search - WRM061aC06

http://www.wormbase.org/species/c_elegans/clone/WRM061aC06#054--10

Search - WRM061aA01
http://www.wormbase.org/species/c_elegans/clone/WRM061aA01#054--10

I hope this helps and thank you again for reporting the invalid link.

Paul

On 16/11/2015 12:05, no-reply@wormbase.org wrote:
> offline chat The "Search for the clones" link for searching fosmids 
> from Don Moerman´s library does not work for some time
>
> Submitted From:
>   http://www.wormbase.org/resources/reagents#24301--10 
> http://www.wormbase.org/resources/reagents#24301--10 
> <http://www.wormbase.org/http://www.wormbase.org/resources/reagents#24301--10> 
>
>
> This issue has been assigned ticket number: #4377. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4377>.
>
> Reported by: Henning Schmidt (Henning.Schmidt@tu-bs.de)
> 16 Nov 15 12:05
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
