### ISSUE TITLE
  Is it possible to download the "Contr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4378]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is it possible to download the "Control median" and the "Control mean" values (under Expresion->Control statistics) for all the genes?</p>

**Reported by:** Hila******** (Hila***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by Paul-Davis** [comment]
@gw3 I don't think this data is available to download via the site, but I'm guessing you have the data in a handy file, sould you take a look for me?

Thanks

HelpDesk

**Comment by Paul-Davis** [comment]
still outstanding, I'll have a look at generating this.

**Comment by Paul-Davis** [comment]
for some reason reply didn't appear on the ticket??


Dear Hila,

Apologies for the delay in replying to you. Unfortunately this data cannot be downloaded for all genes directly from the website, but I am generating the data now and will pass it to you when available.

Paul

**Comment by Paul-Davis** [comment]
Dear Hila,

I have deposited the data here:

ftp://ftp.sanger.ac.uk/pub2/wormbase/STAFF/pad/c_elegans_WS251_Control_median_mean_values.txt.gz

It might take a short while to be publicly accessible.

Paul
