### ISSUE TITLE
visitor_name (visitor_email): Why is the site not ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4380]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Why is the site not working ugh</br>Chris: Hello visitor_name, how can I help?</br>Chris: Is WormBase acting up for you?</br>Chris: Apologies if so</br>visitor_name (visitor_email): yes, is it down?</br>Chris: It's been getting hit with large queries and/or web crawlers recently which may be affecting performance</br>Chris: At least that's my understanding</br>Chris: I'll discuss with our web team ASAP</br>Chris: What exactly are you experiencing?</br>visitor_name (visitor_email): it won't allow me search and all the content fields say Sorry! An error has occured</br>Chris: OK, yes it seems slow to say the least. Again, apologies. I will contact you by e-mail as soon as we can clear it up</br>Chris: Is that OK?

**Reported by:** Kath** (kwat*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://wormbase.net/about/wormbase_release_WS246#10--10">http://wormbase.net/about/wormbase_release_WS246#10--10</a>
**Browser:** Firefox 42.0

**Comment by chris-grove** [comment]
Site is very slow/not working

**Comment by tharris** [comment]
Fixed.

**Comment by chris-grove** [comment]
Contacted user
