### ISSUE TITLE
HelpDesk: Question about WormMart feature availability

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4381]
Hi.
I saw the notice about the switch from WormMart to WormMine. I use WormMart to find 5' upstream region (promoters) of genes. I tried looking on WormMine for this same info, but couldn't seem to find where it would be.

Is this type of info not available on WormMine, or am I simply not looking in the right place?

Thanks
Laura

**Comment by chris-grove** [comment]
Hi Laura,

 You can now find this functionality in the ParaSite BioMart, listed under
Tools on the WormBase homepage. We hope to have this functionality in
future versions of WormMine.

Best,

Chris

**Comment by chris-grove** [comment]
User is happy

**Comment by tharris** [comment]
Availability in WormMine likely concomitant with retirement of WormMart.
