### ISSUE TITLE
  What are the column names and descrip...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4382]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;What are the column names and descriptions for the following:<br/>c_elegans.PRJNA13758.WS250.geneIDs.txt.gz (ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/geneIDs/)<br/>Taxonomy Id, WB_Gene_Id, gene name ???, sequence id ???, status (???)<br/>What does 'Live' or Dead or Suppressed exactly mean?    </p><p>What were you doing? <br />&nbsp;&nbsp;Downloading the files from the ftp site and trying to understand what the fields are exactly</p>

**Reported by:** Adri************* (pasc*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by chris-grove** [comment]
Hello Adrian,

 The "gene name" column displays the public gene name of the gene, usually a three or four letter code (for a gene class) followed by a hyphen and a number, e.g. "abf-1" or "aars-1". The sequence id is in reference to the specific gene within a genomic clone (cosmid/fosmid). The C. elegans gene nomenclature is described here:

http://www.wormbase.org/about/userguide/nomenclature#g2lh0dc584361--10

You can reach this page from the "Nomenclature" link at the bottom of the WormBase homepage.

Although someone else could explain "status" better than I can, this is the gist of it: "Live" indicates that the gene is considered to be a real gene based on prediction or evidence. "Dead" is applied to genes that are no longer considered to be real genes in the database (by name), as gene predictions have changed or new evidence has emerged. This can happen when gene models merge or evidence indicates that what we thought was a gene really isn't. "Suppressed" is reserved for special cases, I believe mostly transposons, that we don't recognize as legitimate C. elegans 'host' genes.

Best,

Chris

**Comment by chris-grove** [comment]
@Paul-Davis  You can probably explain the "status" much better than I can

**Comment by khowe** [comment]
You have summarised it completely accurately @chris-grove

**Comment by Paul-Davis** [comment]
Yeah I can't really add anything @chris-grove

**Comment by chris-grove** [comment]
OK, thanks @Paul-Davis @khowe
