### ISSUE TITLE
  Why are locus information missing in ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4383]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Why are locus information missing in the protein fasta headers <br/>for example: <br/>>AC3.12	CE46597	WBGene00077503	status:Confirmed	UniProt:H2L2B5	protein_id:CCE72024.1<br/>file:  c_elegans.PRJNA13758.WS250.protein.fa<br/>folder:  ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/protein/<br/>while others have the locus(eg:<br/>>AC7.2b	CE31275	WBGene00004929	locus:soc-2	status:Confirmed	UniProt:Q22875	protein_id:CCD61152.1	Leucine-rich repeat protein soc-2)</p>

**Reported by:** Adri************* (pasc*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by chris-grove** [comment]
Hello again Adrian,

 Not all genes have a common/public gene name, such as "soc-2", but rather only have a "sequence name" as I explained in my last e-mail. There are quite a few genes that still don't have a public gene name, as the gene has not been classified by gene product type, mutant phenotype, or some other criteria.

Best,

Chris
