### ISSUE TITLE
Any idea when wormbase will be working properly?
T...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4385]
*Help Desk query collected when no chat operators were online. Follow up required.*

Any idea when wormbase will be working properly?
Thanks!

**Reported by:** sand** (sand***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004412#0-9b6f1-10-09b6f1">http://www.wormbase.org/species/c_elegans/gene/WBGene00004412#0-9b6f1-10-09b6f1</a>
**Browser:** Chrome 46.0.2490.86

**Comment by chris-grove** [comment]
Hello Sandra,

 Apologies for any problems you may be experiencing. Are you still having trouble with the WormBase website? If so, can you explain exactly what problem you're experiencing?

I cannot find any problems on the site at the moment.

Thanks,

Chris

**Comment by draciti** [comment]
user did not get back specifying what problem she had
