### ISSUE TITLE
literature...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4387]
*Help Desk query collected when no chat operators were online. Follow up required.*

literature

**Reported by:** Xibi****** (6953************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001517#0-9f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001517#0-9f-3</a>
**Browser:** Chrome 31.0.1650.63

**Comment by Paul-Davis** [comment]
believe to be spam?
