### ISSUE TITLE
visitor_name (visitor_email): CHR IV unc-5 (e53) w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4390]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): CHR IV unc-5 (e53) with a ts dpy-20 (1282 ts)</br>visitor_name (visitor_email): need to know the genetics of this mutation of C. elegans

**Reported by:** afsh********** (alak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006745#0-9f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006745#0-9f-3</a>
**Browser:** Chrome 46.0.2490.86

**Comment by khowe** [comment]
Response:
Hi Afshan, 

If you search for the e53 Variation, you will get directed to a page of information about it:

http://www.wormbase.org/species/c_elegans/variation/WBVar00142936

Of particular interest to you may be the "Genetics" panel (which details all of the strains carrying this mutation), and the "Molecular details" panel (which details the genome sequence change ). 

I hope this helps.
