### ISSUE TITLE
visitor_name (visitor_email): Do we tell our users...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4391]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Do we tell our users what the basic content of WormBase is anywhere, i.e. what data (types) we have available, etc.  I'm looking at the user guide right now, and the section "individual pages" is empty, and the section on "basic search tools" is reporting an error, while the "general description" links only to the mission statement.

**Reported by:** Paul******* (pker*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_users#3210--10">http://www.wormbase.org/about/userguide/for_users#3210--10</a>
**Browser:** Safari 9.0.1

**Comment by khowe** [comment]
Replied: 

Thank you for writing to WormBase. 

The main user-guide was traditionally maintained on the WormBase wiki:

http://wiki.wormbase.org/index.php/User_Guide

This was never fully migrated to the main site. It is also in need of an major update. 

Two things we are working on may be of interest. The first is the set of WormMethods chapters that cover the basics of WormBase (how the data is organised and curated, the main entry points to different kinds of data etc). A number of these chapters have been written and sent out for review. You may recall hearing about this on our Thursday conference calls. 

The second thing is that we are about to embark on an overhaul of the way in which we manage documentation (see https://github.com/WormBase/website/issues/4373). User guide, tutorials etc will be part of this.
