### ISSUE TITLE
visitor_name (visitor_email): Hey there...do you h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4392]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hey there...do you have any advice for how I go about mining non-coding transcripts that are not any known small RNAs? I guess I'm looking for a list of transcripts that might have been mis-annotated owing to a lack of protein information. I have this huge proteomics dataset (that I will publish + send to worm base shortly) and I'm curious to see if there are any unique peptides on there that are from transcripts that are believed to be non-coding... Any help would be much appreciated!

**Reported by:** Vikr** (vikr********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/non-coding">http://www.wormbase.org/search/gene/non-coding</a>
**Browser:** Safari 8.0.8

**Comment by khowe** [comment]
Hi Vikram, 

You can obtain the current complete set of non-coding transcripts in C. elegans here:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/c_elegans.PRJNA13758.current.ncRNA_transcripts.fa.gz

The fasta header of each entry contains a biotype attribute. The list of biotypes is below. I've tried to sort them according to confidence that they are indeed non-coding. Of most interest to you I think will be those annotated with the generic "ncRNA". Most of these are speculative non-coding transcripts from the modENCODE project. Some of these could well be coding transcripts. The "nc_primary_transcript" biotype is what we use for non-coding transcript isoforms of protein-coding genes. You can probably exclude these from your analysis. 

Best wishes, 

Kevin

biotype=tRNA
biotype=rRNA
biotype=miRNA_primary_transcript
biotype=pre_miRNA
biotype=miRNA
biotype=snoRNA
biotype=piRNA
biotype=scRNA
biotype=snRNA
biotype=asRNA
biotype=lincRNA
biotype=ncRNA
biotype=nc_primary_transcript
