### ISSUE TITLE
analyse list 

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4394]
I tried to get GO_terms for a list of genes, but even if I limit them to only 3 ids, it gets stuck already in the first stage of uploading. (I tried the simple and advanced options, but both hang the same)

WBGene00238597
WBGene00238598
WBGene00238599

![screenshot from 2015-11-25 14 36 17](https://cloud.githubusercontent.com/assets/20523/11399882/f5522276-9381-11e5-97e6-665621eb8d17.png)

**Comment by khowe** [comment]
Lots of WormMine operations seem to require cdn.intermine.org, which is slow/down at the moment.

**Comment by tharris** [comment]
I have contacted the intermine group. We will look into hosting these files locally.

**Comment by chris-grove** [comment]
For what it's worth, I'm not having any trouble loading these genes as a list.

**Comment by epaule** [comment]
Seems to be working again.

**Comment by chris-grove** [comment]
@epaule  I will close this issue. Please reopen if necessary.
