### ISSUE TITLE
  Since the wormbase biomart is being r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4395]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Since the wormbase biomart is being replaced by wormmine, I'm trying to recapitulate a biomart query using wormmine.  I want to access the wormbase attributes rnai_phenotype_phenotype_label, rnai_phenotype_rnai_count and rnai_phenotype_rnai_observed_count fields that are associated with a given wormbase id but can't work out how to do this.   Within the WormMine model, if I do a gene search then the fields I think I need - 'Phenotypes Observed' - only show up if I click the 'show empty' box.<br/>So I'm wondering how in the WormMine model I link genes to RNAi phenotypes?<br/>To see the data I'm trying to access try searching for WBGene00000003 in WormBase and add 'Phenotypes' in the gene content section.  There will be  a series of Not Observed phenotypes for this gene and no Observed phenotypes. <br/>Previously, using the biomaRt R package this was my query:<br/>wormbase.data <- getBM ( attributes = listAttributes(wormbase)[c(2,4,54,55,60:63),1],<br/>filters = 'gene',<br/>values = worm.gene.ids,<br/>mart = wormbase)<br/>Thanks</p>

**Reported by:** Phil******** (phil******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by khowe** [comment]
Replied:
Dear Phil,

It sounds like your approach is along the right lines. However, WormMine underwent a major overhaul recently, and we are yet to add several data types to the system, including RNAi experiments and phenotypes. These will be added in the near future. RNAi phenotypes have been identified as high priority and will be added in the next one or two releases.

Allele-based phenotypes *are* included in the current release. However, it seems that you got unlucky with your test gene, WBGene00000003. That gene only has RNAi-derived phenotypes and no allele-derived ones, explaininng your lack of results.

I hope this helps.
