### ISSUE TITLE
WS251 patches [was: patch for WS251 ENA xrefs]

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4397]
could you load : ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS251/acedb/PATCHES/ena_scaffold_id_update.ace
into the acedb database, so the links to ENA on staging get fixed?

thanks,

M

**Comment by epaule** [comment]
the O.volvulus xrefs are also broken. The patch below should fix that:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS251/acedb/PATCHES/ovo_xref_patch.ace

**Comment by tharris** [comment]
Loaded.

**Comment by tharris** [comment]
Closing, since WS251 is now in production.
