### ISSUE TITLE
CB4856/Hawaii Blast results on live site contain images from the N2 genome browser

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4399]
Blasting this sequence:

atgctcaaaatgatattgtcagcactatttctaatcccagcaagtcaggg
attcatagattttaacccaatttgtacaaaattggtagaatataaagact
cacagaatactgttctggagggatatttggcgtatcctgtaattactggg
ttcttccgtaagcgccctgctgtcatcatcttccatgctttcactggacg
taccgaatttgataatcagaaggctagggatttggctaaggtagctcggc
tacgtagcttttgccgcagatacctatggaaaaggaaaagccgctccaga
tgtgaatggaaattttgccattatgggagaaccacaaccctccgcagctg
gattctgagtgcctggaactatgtaagaggtctaaaatatgtccaaacta
acaatatcgggtcaattgggttctgttttggcgggctttgtactttggat
ttggcccgtttcaatgttggactaaaagctgctgtgtcattccatggaac
acttacggattacccgggaaatggaaccacaatcgacgcttcaatccaag
ctcatcacggagatgcagaccctcacactacaaatcaaaacgccgatgat
ttcattgaagaaatgaggagaagaaacggtgattggatgttcagtagata
cgcccacgccgtccacgccttcactctccccggagttgagaattgggaaa
ttccaggagccgcatttgatcctattgcttctaatagatcttggagtgct
atgaaatcatttttgacggagaagctgagcaattga

Against PRJNA275000
http://www.wormbase.org/tools/blast_blat/

Gives correct blast sequence results, but the hits embedded image is from the N2 genome using the Hawaii co-ordinates so makes no sense and is confusing.

![hawaii](https://cloud.githubusercontent.com/assets/717707/11500502/7df1bb4e-9825-11e5-85ee-8aff400950ca.png)

If you click through to the genome browser, you are definitely on the wrong genome

http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/ with the hits displayed as in the embedded image on the blast results.

**Comment by scottcain** [comment]
Hi @sibyl229 ,

The fix for this should be pretty easy--the blast result page is writing a url that points at c_elegans_PRJNA13758, whereas it just has to use the bioproject that is the thing blasted against (c_elegans_PRJNA275000).  So, the URL looks like this:

http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758?name=II:1108791..1115049;add=II+Hits+Hits+1111791-1112049,1110437-1110636,1112764-1112980,1109375-1109514,1113634-1113761,1109561-1109664,1114677-1114780,1110294-1110380,1113900-1113984,1114834-1114878

but it should look like this:

http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA275000?name=II:1108791..1115049;add=II+Hits+Hits+1111791-1112049,1110437-1110636,1112764-1112980,1109375-1109514,1113634-1113761,1109561-1109664,1114677-1114780,1110294-1110380,1113900-1113984,1114834-1114878

**Comment by epaule** [comment]
also the links from the output default to N2 rather than Hawaii

**Comment by sibyl229** [comment]
Hi @Paul-Davis @epaule the original problem of wrong gbrowse image when blasting against PRJNA275000 is fixed now http://staging.wormbase.org/tools/blast_blat/run 

@epaule is it more beneficial for the user to default to a single strain when multiple strains exists? 

Thanks!

**Comment by epaule** [comment]
@sibyl229 each strain has a different bioproject, which you pick in the blast dropdown. So I would think most people would expect that that is the only one that shows up.

**Comment by sibyl229** [comment]
Hi @epaule currently the blast dropdown is a multi-select box, and defaulting to select all strains matching a species. I think the intention is that if the user isn't familiar with bioproject and is only interested in finding a match in a species, they don't have to worry about making a choice just yet. Do you think it would be more useful to select a better studied strain as default? If so, I can do that as well.

**Comment by khowe** [comment]
Hi @sibyl229 . We define a canonical bioproject for each species in the ASSEMBLIES.json file. Is this available to the BLAST code? If so, it would be better if only the canonical bioproject were selected by default.

**Comment by khowe** [comment]
And (as an aside), we could also do with better human-readable descriptions/handles for the BioProject. For C. elegans, it would be better if the selection box showed something like:

Reference genome, N2 (PRJNA13758, C. elegans sequencing consortium)
Hawaiian strain genome (PRJNA27500, University of Washington)

We'll discuss this more at Hinxton, and make appropriate changes to ASSEMBLIES.json.

**Comment by sibyl229** [comment]
Hi @khowe ASSEMBLIES.json is fetched and parsed by the web code. I can get bioproject description and assembly name to construct a tooltip. For now, I will change the default to the canonical strain.

**Comment by epaule** [comment]
was fixed and is working
