### ISSUE TITLE
  Why is the site so slow? Nothing is l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4401]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Why is the site so slow? Nothing is loading.</p><p>What were you doing? <br />&nbsp;&nbsp;searching for genes</p>

**Reported by:** clay********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by chris-grove** [comment]
Hello Clayton,

 Apologies. Is the site still slow for you? On my end, gene searches
appear to be working smoothly now. Could you check and let us know?

Thanks!

Chris Grove
WormBase

**Comment by tuli** [comment]
It's been slow all day for me, too.
Chrome. I've been using staging.

M.A.

On Wednesday, 2 December 2015, Chris Grove <notifications@github.com> wrote:

> Hello Clayton,
>
> Apologies. Is the site still slow for you? On my end, gene searches
> appear to be working smoothly now. Could you check and let us know?
>
> Thanks!
>
> Chris Grove
> WormBase
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4401#issuecomment-161363355>.
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by chris-grove** [comment]
User responded, site is now working OK for him
