### ISSUE TITLE
  Dear wormbase support, I'm interested...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4405]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase support,<br/>I'm interested in looking at the patterns of gene expression of different genes at the stages of the worm.  When I contacted you for assistance you advised me to use the SPELL tool from the Wormbase to download the dataset. However I cannot enter SPELL now. When I downloaded datasets the files contained values that I would like to know what it stand for, Its doesnt looke like normalized counts.<br/>Thank you</p>

**Reported by:** nett******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by WenChenWormBase** [comment]
Hi, I have restarted the SPELL search engine. It should be accessible now.
Would you let me know which datasets you are downloading? There are several
different types of experiments, the meaning of expression value will depend
on whether you are looking at microarray or RNAseq data.

Wen Chen
Curator, WormBase

On Thu, Dec 3, 2015 at 2:01 AM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Dear wormbase support,
> I'm interested in looking at the patterns of gene expression of different
> genes at the stages of the worm. When I contacted you for assistance you
> advised me to use the SPELL tool from the Wormbase to download the dataset.
> However I cannot enter SPELL now. When I downloaded datasets the files
> contained values that I would like to know what it stand for, Its doesnt
> looke like normalized counts.
> Thank you
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4405. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4405>.
>
> Reported by: nettashemesh@gmail.com
> 03 Dec 15 10:03
>
> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101
> Firefox/42.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by draciti** [comment]
Wen, have you heard back from the user? If not, we can close
