### ISSUE TITLE
  I ma looking for a cDNA clone that co...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4407]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I ma looking for a cDNA clone that contains the ORF for the c. elegans gene F18A1. Is there a source for c. elegans clones? Where can I purchase them?</p>

**Reported by:** VINO******** (vasu****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by chris-grove** [comment]
Hello Vinod,

 You can purchase ORF clones from Dharmacon/GE Life Sciences:

http://dharmacon.gelifesciences.com/gene-expression-cdnas-orfs/non-mammalian-cdnas-and-orfs/c-elegans/

Best,

Chris Grove
WormBase
