### ISSUE TITLE
Wormbase page is not opening only browsing from th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4408]
*Help Desk query collected when no chat operators were online. Follow up required.*

Wormbase page is not opening only browsing from the last three days

**Reported by:** supi**** (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 46.0.2490.86

**Comment by chris-grove** [comment]
From Todd:
"Hi Supinder - 

Can you be more specific about the problem?  I can't test the site from your precise
location but from one not far away and everything looks fine.

You might try clearing your browser cache for wormbase.org as we recently updated
some of the core javascript files.

Todd"
