### ISSUE TITLE
flat_files_info

### ISSUE THREAD

**Issue by khowe** [WormBase/website#4409]
Sent to help@wormbase:

Dear Wormbase,

I like to ask you about some changes in gene xref info which I have seen
in release 250 in comparison with release 240.
For Instance:
For gene "WBGene00043985" in old release you have [XrefAccession] =
NM_001029289 and [XrefDatabase] = mRNA
in new release
For gene "WBGene00043985" you have [XrefAccession] = XM328 and
[XrefDatabase] = gene
on the website in external links section you still provide refseq xrefs
along with uniprot, Aceview and etc.
(http://www.wormbase.org/species/c_elegans/gene/WBGene00043985#1-f032-3)

my question is: did you stillprovide xref REFSEQ info on ftp because i
need this information but i cant find it?

**Comment by draciti** [comment]
Kevin, this is labeled as helped. Can we close?

**Comment by khowe** [comment]
Had lengthy conversation with user off-line.

**Comment by draciti** [comment]
thanks
