### ISSUE TITLE
  I am trying to identify where it is i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4416]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to identify where it is indicated how many nucleotides are found in the sequence of "unspliced + UTR" and "spliced + UTR" for "R03D7.7 (WormBase transcript)"<br/>http://www.wormbase.org/species/c_elegans/transcript/R03D7.7#06--10</p>

**Reported by:** jsol*****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by chris-grove** [comment]
Hello jsolano2891, 

 In the "Sequences" widget on the transcript page:

http://www.wormbase.org/species/c_elegans/transcript/R03D7.7#06--10

The numbers in parentheses after the "view unspliced + UTR" indicates "1562 bp" and after "view spliced + UTR" indicates "1211 bp", where bp refers to "base pairs". Technically these are nucleotides (nt) for a transcript, but map back to that many base pairs in the genome.

Hope that helps!

Chris Grove
WormBase
