### ISSUE TITLE
missing link for submit your data

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4417]
http://www.wormbase.org/about/userguide/submit_data

there is a link missing behind the "Addresses of Authors"

**Comment by ceciliaWBPerson1** [comment]
Addresses of Authors should be deleted. Author data:  its contact data is
no longer updated.

We keep Person and lineage data updated.

Updating contact informationFill out online form
<http://tazendra.caltech.edu/%7Eazurebrd/cgi-bin/forms/person.cgi>Updating
intellectual lineage informationFill out online form
<http://tazendra.caltech.edu/%7Eazurebrd/cgi-bin/forms/person_lineage.cgi>

**Comment by chris-grove** [comment]
I've deleted the "Addresses of Authors" line from the widget. Closing.
