### ISSUE TITLE
visitor_name (visitor_email): I am trying to searc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4419]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): I am trying to search up a gene and the information will take a long time to load then it will say "error has occurred"</br>Chris: I'm sorry for the trouble</br>visitor_name (visitor_email): hello?</br>Chris: Does reloading the page help?</br>Chris: Which data are you not able to load?</br>Chris: Yes, it's loading slowly</br>Chris: I'll let the web team know right away</br>Chris: I can send you an e-mail as soon as we can resolve the issue</br>Chris: apologies for the inconvenience</br>Chris: and thanks for letting us know</br>Chris: Can I help you get some particular data?</br>visitor_name (visitor_email): is there something wrong with the whole website?</br>Chris: It's possible</br>Chris: the site gets attacked by bots occassionally</br>Chris: and the performance of the site suffers</br>Chris: unfortunately</br>Chris: but this usually clears up in a matter of minutes</br>visitor_name (visitor_email): alright, well I guess I'll try again in an hour or so</br>visitor_name (visitor_email): would everything be fixed by then?</br>Chris: I imagine much sooner, but I'll have to ask our web team to be sure</br>Chris: I'll be sure to e-mail as soon as the site is back up</br>Chris: is that OK?</br>visitor_name (visitor_email): that's fine. thank you for your assistance and have a good night.</br>Chris: OK, thank you!</br>Chris: have a good evening

**Reported by:** Khri***** (khri******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/support?url=/species/c_elegans/gene/WBGene00018330">http://www.wormbase.org/tools/support?url=/species/c_elegans/gene/WBGene00018330</a>
**Browser:** Chrome 47.0.2526.73

**Comment by chris-grove** [comment]
The site is loading quite slowly right now

**Comment by chris-grove** [comment]
Although slow, most of the data seems to be loading, at least after refresh. will close
