### ISSUE TITLE
Hello,
The WormBase website seems very slow today....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4420]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
The WormBase website seems very slow today. Is there a mirror I can use? Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002990#0f-9e63bg1-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00002990#0f-9e63bg1-10</a>
**Browser:** Firefox 38.0

**Comment by chris-grove** [comment]
From Todd:
"""
Hi Avril - 

Sorry for the difficulties. 

I've added some additional capacity and fixed an issue that should alleviate the
bottleneck.  We no longer maintain mirrors due to both expense and demand. Please
let me know if you have additional problems.

Todd
"""

**Comment by chris-grove** [comment]
Dear Todd,

Thanks for this! That's great.

Regards,

Avril
