### ISSUE TITLE
  Download the sequence of the segment ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4421]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Download the sequence of the segment of genome which I have on the browser, for example C.brig-chrII:15732001..15732800<br/>Thank you for your help.</p>

**Reported by:** juan*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by chris-grove** [comment]
Hello Juan,

 Here's a short video demonstrating two ways to download the sequence of
the genome that you are currently browsing using the genome browser:

https://dl.dropboxusercontent.com/u/4290782/Downloading_genome_segment_sequence_12-10-2015.mov

There's also a third way: Click on the small 'save' icon (looks like a
little computer disk) to the left of the track name and select FASTA for
that region to download a file with the same sequence.

I hope that helps. Let us know if you have any further questions.

Best,

Chris Grove
WormBase
