### ISSUE TITLE
Wanted: email list for all lab heads

### ISSUE THREAD

**Issue by tuli** [WormBase/website#4424]
Discussed at CalTech conf call. 

We need an email list containing all the lab heads. 
Ann (CGC) would make use of this list to email the community.

The info is stored the Laboratory objects.
Representative
E_mail

As of today (in geneace), there are 997 Lab objects which have both a Representative and E_mail.

The list should be generated every release.

Is there a way to avoid it being abused ie someone hitting "reply"?

**Comment by tharris** [comment]
Probably better handled by Caltech than the webteam.

**Comment by tuli** [comment]
Can anyone create an email list then? labheads@wormbase.org for example?

**Comment by tharris** [comment]
Do we *really* want to a create a mailing list of people that haven't opted in?

**Comment by tuli** [comment]
I think as long as the list is not abused then it's fine.
I trust Ann (CGC) to use such a list wisely. 
Perhaps another way to word the question is "what's the best way for WormBase and our collaborators to contact all Worm Labs"?

**Comment by tharris** [comment]
If someone provides me the list I will set it up.

**Comment by tuli** [comment]
Thanks. Will it be OK to be generate the list by a table maker query at each release? I can write the table maker def.

**Comment by tuli** [comment]
Handed over to @ceciliaWBPerson1

**Comment by tuli** [comment]
Thank you Todd.

Please can you add Ann Rougvie rougv001@umn.edu to the list of people
who can post to the list?

Draft initial message:

============================================================================
This message is being sent to all lab heads listed in WormBase.
We have created this distribution list as a way to communicate matters
of interest to the Worm Community.
e.g. The CGC may wish to inform the community of changes that affect
the ordering of strains, or there may be an upcoming meeting a lab
head would like to promote.
If you would like to be able to post to this list please contact ????????????
============================================================================

If anyone can do better than this please do....it's not my forte!

M.A.

**Comment by tuli** [comment]
Hi All,
  It is not my intent to have the Worm PI email list emailed to all PIs,
but rather to have it ready to go for justified uses when specific needs
arise.  We don't want to have PIs spamming other PIs for reagent requests,
job postings, etc, that are much more appropriate for posting on the worm
base site.  What I would propose is that the head of the Worm Board,
currently being organized by Andy Chisolm, have access to it (and maybe
select other groups for limited use WB, CGC). The Worm Board could provide
some gate-keeping about when it is used.  I don't think we should just send
it out to all - my opinion only, other views are welcomed.

Ann Rougvie

**Comment by tharris** [comment]
I set up this list over the holidays and have contacted list managers on it's administration.
