### ISSUE TITLE
WormBase ftp requesting username and password config problem.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4426]
Paul,

This is Claire from DRSC (Drosophila RNAi Screen Center) at Harvard Medical School.  As we knew, that genome annotation is an on going effort, which is the reflected by frequent updates at WormBase, FlyBase, RefSeq et al.  To address this issue, we implemented UP-TORR, an online tool for accurate and up-to-date
annotation of RNAi reagents (publication is attached).    At up-torr back end, we need to automatically get annotation files from WormBase, FlyBase et al.  Recently we noticed that the automatic update code does not work with WormBase because of the requirement of a ID/password, which is new to us.  I am wondering if it is possible to set up an account for us.  Please let me know if you have any questions and thank you so much!

Claire (Yanhui)

**Comment by Paul-Davis** [comment]
Dear Claire,

This might be some misconfiguration with our ftp site as I believe there should be no account/password requirement. I have created a ticket to get this resolved.

https://github.com/WormBase/website/issues/4426

Thanks for reporting the issue.

Paul

**Comment by tharris** [comment]
Depending on your client:

user: ftp, no pass required

**Comment by scottcain** [comment]
For the old-school among us, user anonymous works as well with no password.

**Comment by Paul-Davis** [comment]
so something must have changed recently as I've never had to tinker with preferences to access the wormbase ftp?

**Comment by Paul-Davis** [comment]
The issue appears to be resolved as the ftp no longer requests any details by default, I'll let the user know.
