### ISSUE TITLE
  So I have a set of gene lists I'd lik...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4434]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;So I have a set of gene lists I'd like to analyze to do Ontology and basically just figure out what types of genes might be present in this list (of about 500 genes for two sets).<br/>I feel like importing lists from the available annotations (either Ontology or Phenotypes) will be my best bet.  <br/>I've got the lists made for my genes.  What I'm having trouble with is putting together a list of genes associated with a phenotype. So for instance, if I wanted to get a list of genes that have a daur formation phenotype, how would I go about doing that?<br/>Thanks,<br/>visitor_name</p>

**Reported by:** Joe (jmz4*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by raymond91125** [comment]
Hi Joe,

On the phenotype term page for "dauer formation variant" 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000637#03--10>, 
in the Ontology Browser widget, to the right of the focus term (in 
green), there are two numbers 193 and 56, which are counts of gene 
annotations that are direct or direct+inferred, respectively.

If you click on them, you can get lists of specific gene names.

Cheers,

Raymond



On 12/16/2015 02:40 PM, WormBase Helpdesk wrote:
>
> /Submitted from the feedback form on the WormBase website./
>
>   So I have a set of gene lists I'd like to analyze to do Ontology and 
> basically just figure out what types of genes might be present in this 
> list (of about 500 genes for two sets).
> I feel like importing lists from the available annotations (either 
> Ontology or Phenotypes) will be my best bet.
> I've got the lists made for my genes. What I'm having trouble with is 
> putting together a list of genes associated with a phenotype. So for 
> instance, if I wanted to get a list of genes that have a daur 
> formation phenotype, how would I go about doing that?
> Thanks,
> visitor_name
>
> *Reported by:* Joe (jmz4***********/)
> */Submitted from:* /tools/support <http://www.wormbase.org//tools/support>
> *Browser:* Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 
> Firefox/42.0
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/4434>.
>


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by draciti** [comment]
closing this raymond. If you have anything against, reopen :)
