### ISSUE TITLE
how to find list of different mutants of c elegnas...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4436]
*Help Desk query collected when no chat operators were online. Follow up required.*

how to find list of different mutants of c elegnas?

**Reported by:** neha (khag*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/strain/diabetic mutant of c elegans">http://www.wormbase.org/search/strain/diabetic mutant of c elegans</a>
**Browser:** Chrome 49.0.2587.3

**Comment by tuli** [comment]
Hello,

Thank you for writing to WormBase.

There are different ways to find mutants in WormBase and the best
method depends on what information you want to find and what you want
to do with that information.

If you can give us a little more detail about what exactly you would
like to find we will be better able to advise you.

Best wishes,

Mary Ann

On 17 December 2015 at 05:13,  <no-reply@wormbase.org> wrote:
> offline chat how to find list of different mutants of c elegnas?
>
> Submitted From:
>   http://www.wormbase.org/search/strain/diabetic mutant of c elegans
> http://www.wormbase.org/search/strain/diabetic mutant of c elegans
>
> This issue has been assigned ticket number: #4436. Follow progress on our
> issue tracker.
>
> Reported by: neha (khagwalneha@gmail.com)
> 17 Dec 15 05:13
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by draciti** [comment]
seems user did not get back. Closing
