### ISSUE TITLE
Hi  there,
i ned help please , any information in ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4439]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi  there,
i ned help please , any information in gab-1 GABA receptor subunit  in 	Caenorhabditis elegans

**Reported by:** na (nass********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001512#0d234567e-9f1-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001512#0d234567e-9f1-3</a>
**Browser:** Chrome 47.0.2526.106

**Comment by kyook** [comment]
The first step to get information would be to do a search for the gab-1
gene, that search will take you to the gab-1 gene page:
http://www.wormbase.org/species/c_elegans/gene/WBGene00001512#0-4-3
You can peruse different types of information about gab-1 through the
widget menu on the left hand of the page.

I hope that helps.
Best wishes,
Karen

On Fri, Dec 18, 2015 at 8:21 AM, <no-reply@wormbase.org> wrote:

> i ned help please , any information in ... (na)
> Content-type: text/html; charset="utf-8"
> Date: Fri, 18 Dec 2015 16:21:55 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>
>
>         <style type="text/css">.fade{font-size:.9em;color:#999}</style>
> offline chat Hi  there,
> i ned help please , any information in gab-1 GABA receptor subunit  in
> Caenorhabditis elegans  <p>Submitted From:
> <br>&nbsp;&nbsp;
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001512#0d234567e-9f1-3
> <a href="
> http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001512#0d234567e-9f1-3
> ">
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001512#0d234567e-9f1-3
> </a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4439. Follow progress on our
> <a href="https://github.com/WormBase/website/issues/4439">issue
> tracker</a>.
> <p>
>
> <p>
> Reported by: na (nasserfaeinosh@yahoo.com) <br />
> <span class="fade">18 Dec 15 16:21 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can
> also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by draciti** [comment]
closing
