### ISSUE TITLE
  I'd like to add exon structure inform...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4440]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'd like to add exon structure information to a list/table of genes on WormMine and I receive the following message "This collection is disabled because all exons collections on objects of type Gene are empty." I tried changing to object to transcript (and a few others) and could never add the exon data. I eventually retreated to WormMart where I was able to obtain the exon data I was looking for... but I'd like to do this in WormMine because WormMart doesn't appear to be around for much longer, and the genome releases are relatively old.  <br/>Thanks for your help!<br/>visitor_name</p>

**Reported by:** Dan (dpag****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by raymond91125** [comment]
Hi Dan,

Have you tried using Tools->Parasite BioMart for this purpose? C. 
elegans is included there. I believe your request is on our WormMine 
developer's priority list, though.

Thanks.

Raymond



On 12/18/2015 10:45 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I'd like to add exon structure information to a list/table of genes 
> on WormMine and I receive the following message "This collection is 
> disabled because all exons collections on objects of type Gene are 
> empty." I tried changing to object to transcript (and a few others) 
> and could never add the exon data. I eventually retreated to WormMart 
> where I was able to obtain the exon data I was looking for... but I'd 
> like to do this in WormMine because WormMart doesn't appear to be 
> around for much longer, and the genome releases are relatively old.
> Thanks for your help!
> Dan
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4440. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4440>.
>
> Reported by: Dan (dpagano@genetics.med.harvard.edu)
> 18 Dec 15 18:46
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 
> Firefox/42.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
