### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4443]
From Curtis Loer:

Hi WB folks,

I can't seem to get into my account; what I thought my password was doesn't seem to work. I logged in via Facebook, but that didn't seem to connect to my account with all my favorites, etc.

Perhaps you could use a password reset link on the site? (If it's there I couldn't find it.)

In the meantime, I need a password reset.

Best,
Curtis

**Comment by draciti** [comment]
Hi Curtis,

sorry you are experiencing difficulties,
someone from the Web Team will get back to you promptly.

Thanks,

Daniela

**Comment by raymond91125** [comment]
bump

**Comment by sibyl229** [comment]
Replied.
