### ISSUE TITLE
  I am interested in how the 5'UTR and ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4444]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am interested in how the 5'UTR and 3'UTR sequences are annotated in all the transcript sequences that contain them. Do they come from experimental data (RNA-seq or other methods) or computational prediction? </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to design primers in the UTR region. </p>

**Reported by:** Chao******** (cz21***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by gw3** [comment]
HI,

The UTR regions are generated as follows:

The CDS structures are manually curated.
The EST and mRNA transcripts are then automatically aligned to the genome
and a program compares the transcript alignments to the CDS structures.
Where the transcript alignments match the curated CDS structure and extend
to the 5' or 3' of the CDS structure, the program generates the 5' and 3'
UTR regions based on the transcript alignment.

We are working on adding the RNASeq data into this process.

Gary Williams
WormBase
