### ISSUE TITLE
  Hi, I am trying to find different all...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4447]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am trying to find different alleles for a given list of genes and I am not able to get that output. If you can help me that would be great. Thanks.</p>

**Reported by:** meet*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by kyook** [comment]
Hi Meetu,

You can create a list of alleles for a given list of genes through
WormMine.

You can access WormMine from the Tools tab on the main WormBase site.
Choose the Lists tab along the top menu.
Enter in your list of genes. Create list.
The next page will show you potential genes that match the genes on your
query list, choose the correct ones and when done click on Save List of <#>
Genes button.

The results page will allow you to add information to the list of genes you
entered, you do this by clicking on the Manage Columns button.  You will be
able to delete as well as add new columns of data.

To get the alleles for the genes, click on add column, scroll down until
you see >Alleles, choose it, then choose Public_name in the pop up sublist.
Apply the modifications and you will be taken to a results table that lists
the genes with all their alleles.
It might also be helpful to add a column - Method (can be found in the
sublist popup also) to help with sorting.

You should be able to do further processing and manipulations through an
excel- like app after downloading the table.
I hope that helps, please don't hesitate to write back if you need further
help.

Best wishes,
Karen


On Mon, Dec 28, 2015 at 8:33 AM, <no-reply@wormbase.org> wrote:

> Question:
>
>   Hi,
> I am trying to find different alleles for a given list of genes and I am
> not able to get that output. If you can help me that would be great. Thanks.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4447. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4447>.
>
> Reported by: meetu.seth@umassmed.edu
> 28 Dec 15 16:33
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101
> Firefox/43.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
