### ISSUE TITLE
  Dear Sirs/Madams: I am willing to reg...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4448]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sirs/Madams:<br/>I am willing to register as a member so that I can start to order strains and accesories of worms. I used to register an account for Experimental Gerontology of National Institute on Aging. Now I need to register as an international user from P R China and need to order strains from you and make them mailed to China. <br/>I would be very appreciative if you could let me know the following:<br/>1) what would be steps to register the account (right now Google and Facebook could not be used in China as a vehicle to register)?<br/>2) curently, how much is the cost for the first time registration in Wormbase and how much for the order of each worm strain?  Plus, if my request is to mail to China, is there additional charge?<br/>3) do your institute offer the RNAi genes?<br/>If there is any additional request for successfully ordering from your institute, please let me know.<br/>Ilook forward to hearing from you. <br/>Sincerely<br/>Garrick<br/>Garrick D. Lee, Ph. D. <br/>Professor of University of Henan, P.R. China.</p><p>What were you doing? <br />&nbsp;&nbsp;Professor of University of Henan, P.R. China.
Order request</p>

**Reported by:** Garr******* (Garr******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by tuli** [comment]
Dear Garrick,

Thank you for writing to WormBase. I have answered your queries in line.

> I am willing to register as a member so that I can start to order strains
> and accesories of worms. I used to register an account for Experimental
> Gerontology of National Institute on Aging. Now I need to register as an
> international user from P R China and need to order strains from you and
> make them mailed to China.

Strains are ordered from the CGC. You can find details here:
https://cbs.umn.edu/research/resources/cgc/how-order-strains.

> I would be very appreciative if you could let me know the following:
> 1) what would be steps to register the account (right now Google and
> Facebook could not be used in China as a vehicle to register)?

You do not need to register with WormBase to order strains from the
CGC. WormBase collaborate with the
CGC but we are separate organisations.

> 2) curently, how much is the cost for the first time registration in
> Wormbase and how much for the order of each worm strain? Plus, if my request
> is to mail to China, is there additional charge?

I have cc'ed the CGC this reply. Aric Daul will be able to answer
these specific questions.

> 3) do your institute offer the RNAi genes?

Details of RNAi libraries can be found
http://www.wormbase.org/resources/reagent (look at the Libraries
widget).

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

> If there is any additional request for successfully ordering from your
> institute, please let me know.


> Ilook forward to hearing from you.
> Sincerely
> Garrick
> Garrick D. Lee, Ph. D.
> Professor of University of Henan, P.R. China.
>
> What were you doing?
>   Professor of University of Henan, P.R. China. Order request
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #4448. Follow progress on our
> issue tracker.
>
> Reported by: Garrick Lee (Garricklee@foxmail.com)
> 29 Dec 15 15:45
>
> Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

**Comment by tuli** [comment]
Hi Garrick,

Please send me a complete billing address, and the name and contact info 
(email address) of whomever handles the billing and payments for the 
lab.  Once I have that information, I will assign a lab code.

Orders must be placed through our website (http://www.cbs.umn.edu/CGC/). 
Strains are $7 each and there is a $25 lab fee that covers your lab for 
one year from the date of your first order. The $25.00 annual lab fee 
will automatically be added to your order when you proceed to check out 
(if due). Most orders take 1-2 weeks for processing; orders ship by 
regular US post at no cost to you. We will ship via FedEx or DHL upon 
request, but only if you provide a FedEx or DHL number for us to use 
when setting up the shipment.  We cannot use our FedEx account and bill 
you for our costs.  You have the option of paying at the time of 
purchase with a credit card, or using a purchase order.  If using a 
purchase order, the formal invoice (see attached sample) will be sent to 
your billing address for payment.  We can send invoices by email as 
PDFs; please let me know if you would like to use this option.

You should receive a confirmation email for your order, and a second 
confirmation if using a credit card. Let us know if you do not receive 
the order confirmation, as a few users have had trouble with their 
orders not recording properly in the system.

Thank you,

Aric
