### ISSUE TITLE
  Hi,  I want to download the "Protein ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4449]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I want to download the "Protein Length (aa)" for all the genes, but I failed to find the information from Download ftp server. Could you please help me with it?<br/>Thanks.</p>

**Reported by:** Joyc* (qin@******)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by tharris** [comment]
User directed to Intermine template. Satisified.
