### ISSUE TITLE
visitor_name (visitor_name.bojanala@gmail.com): On...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4450]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_name.bojanala@gmail.com): On what basis 2 isoforms for hlb-1 were encoded</br>visitor_name (visitor_name.bojanala@gmail.com): there is a mention that SL1 splicing is involved</br>visitor_name (visitor_name.bojanala@gmail.com): but we do see that the isoforms differ in the exon 10</br>visitor_name (visitor_name.bojanala@gmail.com): which publication it refers to?</br>visitor_name (visitor_name.bojanala@gmail.com): 4 types of sequences at transcript level and 2 at coding sequence that results in 2 isoforms of 920 and 962 AA

**Reported by:** gire*** (gire**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/undefined">undefined</a>
**Browser:** Chrome 47.0.2526.106

**Comment by chris-grove** [comment]
Dear Gireesh,

Thank you for your enquiry. Looking at hlb-1 there should actually be 6 alternate Isoforms, the 2 existing that differ in coding exon 9 (exon 10 of the transcript) which is based on RNASeq read data and EST data:

AV194648 - confirms the short exon of T21H8.1a
EC035274 - partially confirms the long exon of T21H8.1b

The additional 4 Isoforms (c-f that will be in WS253) have the following differences from the existing annotations:

T21H8.1c - Identical to T21H8.1a but skips coding exon 5 (exon 6 of the long transcripts) seen at approximately 20% frequency of the non-skip form
T21H8.1d - Identical to T21H8.1b but skips coding exon 5 (exon 6 of the long transcripts) seen at approximately 20% frequency of the non-skip form
T21H8.1e - Identical to T21H8.1a but utilises SL1 on exon 6 (exon 7 of the long transcripts) seen in 6 RNASeq libraries
T21H8.1f - Identical to T21H8.1b but utilises SL1 on exon 6 (exon 7 of the long transcripts) seen in 6 RNASeq libraries

If you are looking for a citation for these annotations you can use the information here as a guide:
http://www.wormbase.org/about/citing_wormbase#012--10

I have attached the following 2 files containing the new sequence data:
Protein_sequences: hlb-1.peps
DNA sequences (coding region only): hlb-1.fa

I hope this helps

Paul
