### ISSUE TITLE
 Server Error: 500 at  tools/gmap/run   
  Error M...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4453]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/gmap/run">tools/gmap/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "Could not connect to database acedb _WS251, host: prod-mining.wormbase.org" </p><p>What were you doing? <br />&nbsp;&nbsp;trying to use the genetic map and look for chromosomal deletion and rearrangement mutants</p>

**Reported by:** Chao******** (cz21***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/gmap/run">/tools/gmap/run</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by tharris** [comment]
Fixed, user contacted.
