### ISSUE TITLE
I sent a message a while ago. Apparently the probl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4455]
*Help Desk query collected when no chat operators were online. Follow up required.*

I sent a message a while ago. Apparently the problem is that your Blat only works with short input sequences? With 400 bases it wotked,but BLAT is supposed toaccept up to 20000 bases.
Please advise

Juan

**Reported by:** Juan************ (juan*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run">http://www.wormbase.org/tools/blast_blat/run</a>
**Browser:** Firefox 43.0

**Comment by kyook** [comment]
Hi Juan,

I am wondering if you are still having trouble with BLAT and if it is the
same trouble. If you are still having trouble, would you let us know what
parameters you are using?

Apologies for the delay in getting back in touch with you.

Best wishes,
Karen

On Mon, Jan 4, 2016 at 3:45 AM, <no-reply@wormbase.org> wrote:

> offline chat I sent a message a while ago. Apparently the problem is that
> your Blat only works with short input sequences? With 400 bases it
> wotked,but BLAT is supposed toaccept up to 20000 bases. Please advise Juan
>
> Submitted From:
>   http://www.wormbase.org/tools/blast_blat/run
> http://www.wormbase.org/tools/blast_blat/run
> <http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run>
>
> This issue has been assigned ticket number: #4455. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4455>.
>
> Reported by: Juan A. Subirana (juan.a.subirana@upc.edu)
> 04 Jan 16 11:46
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by raymond91125** [comment]
Hi Juan,

I'm following up on this issue. I just tried blat with a DNA of 20450 
letters without hitch. If you still have trouble with your query, please 
provide us with your exact input to trouble shoot.

Thanks and sorry for the delay.

Raymond


On 01/04/2016 03:45 AM, no-reply@wormbase.org wrote:
> offline chat I sent a message a while ago. Apparently the problem is 
> that your Blat only works with short input sequences? With 400 bases 
> it wotked,but BLAT is supposed toaccept up to 20000 bases. Please 
> advise Juan
>
> Submitted From:
>   http://www.wormbase.org/tools/blast_blat/run 
> http://www.wormbase.org/tools/blast_blat/run 
> <http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run>
>
> This issue has been assigned ticket number: #4455. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4455>.
>
> Reported by: Juan A. Subirana (juan.a.subirana@upc.edu)
> 04 Jan 16 11:46
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Closed for now until user has more to add.
