### ISSUE TITLE
Hello,
I see the description for T16G1.7 says it's...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4456]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I see the description for T16G1.7 says it's orthologous to human DLC1, but I think that this isn't the case, as that human gene doesn't appear in the list of blast hits? Also, this worm gene has a nematode-specific Pfam domain, so I think it's unlikely to have a human ortholog?

Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00011801#0f-9e63bg1c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00011801#0f-9e63bg1c-10</a>
**Browser:** Firefox 38.0

**Comment by Paul-Davis** [comment]
Dear Avril,

Thanks for reporting this.

Yes, it seems that this 11 year old description is no longer valid as we 
also don't see the OMIM associations.

This will be removed/updated shortly.

Paul




On 04/01/2016 14:18, WormBase Helpdesk wrote:
>
> /Help Desk query collected when no chat operators were online. Follow 
> up required./
>
> Hello,
> I see the description for T16G1.7 says it's orthologous to human DLC1, 
> but I think that this isn't the case, as that human gene doesn't 
> appear in the list of blast hits? Also, this worm gene has a 
> nematode-specific Pfam domain, so I think it's unlikely to have a 
> human ortholog?
>
> Regards, Avril
>
> *Reported by:* Avri********* (alc@**********/)
> */Submitted from:* 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00011801#0f-9e63bg1c-10
> *Browser:* Firefox 38.0
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/4456>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by vanaukenk** [comment]
Hi Avril,
Thanks for alerting us to this.
I've flagged this concise description so it will no longer be included in the upload.  I'll look into possible Gene Ontology annotations for this gene so that it might be included in the new automated description pipeline.  
--Kimberly
