### ISSUE TITLE
New phenotype graph not loading in Chrome browser

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4460]
The new gene page Phenotype Graph widget is opening nicely on Firefox and Safari but not in Chrome (on my office iMac at least).

**Comment by azurebrd** [comment]
I'm not seeing a problem on Chrome on my machine, can you skype me later and show me on your screen ? Using this page 
http://www.wormbase.org/species/c_elegans/gene/WBGene00006374#b8--10

**Comment by chris-grove** [comment]
OK, it seems to be resolved now. Thanks!

**Comment by chris-grove** [comment]
Seems to be a problem again

**Comment by chris-grove** [comment]
For the record, the graph is loading properly on Chrome on staging, just not the live site

**Comment by sibyl229** [comment]
Hi @chris-grove the phenotype graph on live site is currently loading for me on Chrome. Are you still experiencing any issue?

**Comment by chris-grove** [comment]
@sibyl229  Yes, it is still not loading on Chrome (on the live site) for me.

**Comment by sibyl229** [comment]
@chris-grove can you help me try something with the built-in Chrome Developer Tool? There are two things that I'm interested in that you can find in the Developer Tool: if there's any error messages and if any resource isn't loaded. 

To check them, first open the Chrome Developer Tool (View->Developer->Developer Tool), there's a tab called 'Console' in this view. If there's any error message, they would be shown in red color there. 

If there's no error message, another likely cause would be some resource isn't received from the server. To check that find another tab in Developer Tool view called 'Network' and refresh the page. You will see a list of resources requested, mostly with "status 200 OK" within a few seconds of page refresh, I'd like you to look for resources with a status other than 200 OK, in particular status like pending that doesn't change to 200 OK after a few seconds of waiting.

Could you try these things for me? Thank you :)

**Comment by chris-grove** [comment]
@sibyl229  I'm on Skype now if that would be easier. I am getting an error message on the Console tab:
![screen shot 2016-01-12 at 11 20 02 am](https://cloud.githubusercontent.com/assets/611382/12274191/99bfb550-b91e-11e5-9cc8-ec58a94d0954.png)
The Network tab seemed to look OK (all 200's except for one that seemed to be a partial load related to the Olark chat service):
![screen shot 2016-01-12 at 11 22 10 am](https://cloud.githubusercontent.com/assets/611382/12274226/c88461ce-b91e-11e5-8d02-ea8bc7e49fbe.png)
This was all while I was on the dbl-1 page:
http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#0-b-3

**Comment by sibyl229** [comment]
@chris-grove Thanks a lot! One more thing: could you show me what this page look like to you? http://www.wormbase.org/rest/widget/gene/WBGene00000936/phenotype_graph_json

**Comment by chris-grove** [comment]
That link looks like this:
![screen shot 2016-01-12 at 12 15 58 pm](https://cloud.githubusercontent.com/assets/611382/12275691/500ee518-b926-11e5-945d-1ad229446502.png)

...and it looks like the graph is now loading on Chrome for me :D

**Comment by chris-grove** [comment]
@sibyl229  OK, so an interesting development. It looks like if I'm logged in to WormBase with my chris@wormbase.org account, I cannot get the graph to load on Chrome, but if I logout I can load the graph without trouble. @raymond91125  pointed out that it may have something to do with a loading time statement I get on all pages and widgets while I'm logged in as chris@wormbase.org. For example, when I'm logged in with my wormbase.org account, I always see this type of statement on widgets:
![screen shot 2016-01-12 at 12 22 09 pm](https://cloud.githubusercontent.com/assets/611382/12275853/39c0a1ba-b927-11e5-9684-4242a403fd63.png)
saying "Generated by...raw | futon". Also, when I'm logged in and load the json link you sent, I see the same message at the top of the page but behind the other text, like this:
![screen shot 2016-01-12 at 12 24 28 pm](https://cloud.githubusercontent.com/assets/611382/12275886/74ddcc8c-b927-11e5-9665-34956f7a4c10.png)
Maybe that's the issue?

**Comment by sibyl229** [comment]
@chris-grove Yup, I agree that's the issue. So the content of link above needs to be in JSON format to work. When you are logged in, the extra text messes up the format. I think Juancarlos has changed the code since WS251 and no longer uses that link, and what's on staging right now should be fine even when you login as administrator.

**Comment by chris-grove** [comment]
@sibyl229  OK great! Thanks! I'll close the issue then.
