### ISSUE TITLE
  Hello! How do I generate the nucleoti...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4461]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello!<br/>How do I generate the nucleotide sequence for my gene of interest, along with "x" amounts of upstream(promoter) and downstream basepairs, now that WormMart is no longer supported?<br/>Thank you!</p><p>What were you doing? <br />&nbsp;&nbsp;I usually used WormMart to get a nucleotide sequence for specific genes, as well as upstream/promoter sequences, but it appears to no longer be supported.</p>

**Reported by:** Mano* (mgui****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by chris-grove** [comment]
Handled over chat. User happy
