### ISSUE TITLE
Great site, thank you! But:
pop-up window with seq...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4464]
*Help Desk query collected when no chat operators were online. Follow up required.*

Great site, thank you! But:
pop-up window with sequences cuts area on the right side, and there is no way to scroll, so that 3-4 letters on the right are not visible.
Ubuntu 14.04 LTS 64-bit
Chrome Version 47.0.2526.106 (64-bit)

**Reported by:** Leon******** (leon******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00009706#0b1-9ed2f68c457gha3-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00009706#0b1-9ed2f68c457gha3-10</a>
**Browser:** Chrome 47.0.2526.106

**Comment by chris-grove** [comment]
Confirmed:
![screen shot 2016-01-06 at 9 31 28 am](https://cloud.githubusercontent.com/assets/611382/12149456/b02fcd86-b458-11e5-84f0-c60ff7bb3490.png)
This is a consistent problem for all genes I've checked on all browsers.

**Comment by chris-grove** [comment]
Hello Leon,

 Thanks for the bug report and apologies for the inconvenience. Our web team is working on this now. In the meantime, you can select all, copy and paste the text into a separate document to look at the sequence.

Best,

Chris Grove
WormBase

**Comment by sibyl229** [comment]
Hi @chris-grove thanks for testing. The sequence popup is no longer cut off on staging: http://www.wormbase.org/species/c_elegans/gene/WBGene00009706#0-g-10

**Comment by chris-grove** [comment]
@sibyl229 
Looks good, thanks!!
