### ISSUE TITLE
Discussion topic about data submission forms

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4465]
Hi,

I've thought this before, but always forget to raise it as it's not really a major issue but something that seems a little disjointed with our resource.

Should we have a more centralised place or have some form of webforwarding for the user submission forms rather than exposing the machine and username of one of the WormBase Caltech staff?

The following is used as the root of most/all user submission forms.

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/

Paul

Good anti hacker message BTW

![antihacker_message](https://cloud.githubusercontent.com/assets/717707/12141499/e5c74ac8-b467-11e5-91bb-1d1bc4b4b689.png)

**Comment by azurebrd** [comment]
Thanks Paul =)

We've had the forms on tazendra ~azurebrd since 2001 (tazendra was minerva at the time, until 03 or 04) and haven't had any problems, so I'm okay with leaving things as they are (if the issue is the safety and privacy of my account and machine).

A lot of the forms interact with the local postgreSQL server directly, and for speed and potential network issues, it's nice that they're in the same machine.  If we wanted to move things to a different centralised place for user submission, we could, but I don't know where it would be, and how much benefit we'd get from it.  If someone wants to pilot that, I could move some non-postgreSQL forms and see how that works.

**Comment by Paul-Davis** [comment]
Hi Juancarlos,

Glad you haven't had any security issue, I just thought I'd voice that element but that is the minor point.
Maybe there is a web solution to make it feel more cohesive? I thought I would raise this as you guys are really developing and pushing the community collaboration at the moment.

I guess this will all be solved when we have a single database instance in the cloud and the forms can be located anywhere we choose.
thanks

P

**Comment by tharris** [comment]
Personally, I think it looks more professional to have everything hosted from the same domain.

**Comment by khowe** [comment]
I agree with @tharris . The service could still be physically hosted on tazendra (and maintained by @azurebrd ), but have a WormBase domain URL root, right? e.g. www.wormbase.org/submissions, or even submissions.wormbase.org.

**Comment by tharris** [comment]
Yep! It could be configured either way. The first would require a transparent reverse proxy, the second either proxy or direct traffic to host.

**Comment by Paul-Davis** [comment]
Great...thats what I was hoping for :)

**Comment by azurebrd** [comment]
I don't know how to do that, but if Todd does, that's great.  I don't have a preference for the new domain, but it seems someone needs to decide what it should be before implementing it.

**Comment by tharris** [comment]
Moving forward on this:

wormbase.org/submissions is this easiest to set up. It doesn't require you @azurebrd to change anything. I have set this up.

eg:
http://www.wormbase.org/submissions/person.cgi

Thoughts? Different base name? Subdomain (submissions.wormbase.org, which will require config changes on tazendra) instead?

**Comment by Paul-Davis** [comment]
On my part that looks great!

My only suggested improvement is to have a page detailing the data that users can submit on the: http://www.wormbase.org/submissions url.

Probably another redirect from to here: http://www.wormbase.org/about/userguide/submit_data#01--10

And on that page update the urls to follow your new http://www.wormbase.org/submissions/person.cgi format.

P

**Comment by chris-grove** [comment]
@tharris 
I like the http://www.wormbase.org/submissions/person.cgi type of layout. Can we implement this now for the new phenotype form?

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/phenotype.cgi

**Comment by chris-grove** [comment]
@tharris 
Ooops, looks like it already works. Can we just start using this type of URL format from now on?

**Comment by chris-grove** [comment]
@tharris 
OK, sorry, I keep jumping the gun. Looks like we'll need more configuration first.

**Comment by tharris** [comment]
it should be fine from the proxy end. Where do you think the additional
config is required?

**Comment by chris-grove** [comment]
@tharris 
Oh, well when I loaded the page:

http://www.wormbase.org/submissions/phenotype.cgi

the form is not behaving properly, e.g. the autocomplete fields are not working. Compare to the original:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/phenotype.cgi

**Comment by tharris** [comment]
That needs to be fixed/updated by juancrlos. The easiest thing would be to
place all forms at document root and we could dispense with the proxy
altogether.

**Comment by chris-grove** [comment]
@tharris  OK
@azurebrd  Is this something we can do?

**Comment by azurebrd** [comment]
The relative paths pointing to the javascript and images weren't working, I've changed them the phenotype.cgi on tazendra to find the hostfqdn and generate the URL src based on that.  If this seems good we should put that on the sandbox and go through the other forms that are meant to be there and fix their .js and image sources.

**Comment by chris-grove** [comment]
@azurebrd   OK the form at:

http://www.wormbase.org/submissions/phenotype.cgi

Is now working properly. I suppose we can now put that on the sandbox for more thorough testing?

**Comment by azurebrd** [comment]
It's on the sandbox now, but I just meant that we should keep those in sync if they're working properly.  I don't think we can test the proxying from WormBase on the sandbox, since it points at tazendra. (Unless you ask Todd to have the proxying point to mangolassi for testing, then change it back when you're done)

**Comment by Paul-Davis** [comment]
I've updated all the links on the userguide submit_data page: http://www.wormbase.org/about/userguide/submit_data#01--10

**Comment by chris-grove** [comment]
Thanks @Paul-Davis !

**Comment by azurebrd** [comment]
@tharris The forms are tracking user IP addresses to remember their name/email, and also to track abusive users. When going through wormbase/submissions/  the form is seeing it as coming from 50.19.112.56 (amazonaws).  Is there a way to pass through the user's original IP to tazendra ?  (We're getting the IP address from  $query = new CGI;  and  $ip   = $query->remote_host(); ).

**Comment by tuli** [comment]
From the top WormBase page, the links to the submission forms from within the Submit tab need to be updated to the new URLs

**Comment by chris-grove** [comment]
@tuli  This is being addressed in issue #4511

**Comment by brucebolt** [comment]
The community phenotype form at http://www.wormbase.org/submissions/phenotype.cgi is autopopulated with Chris Grove's name and email address.  Results in the user having to delete this entry to enter their own details.

**Comment by azurebrd** [comment]
Yeah, that's from the form remembering the user based on who last used the IP address accessing the form, and because of the proxy, it all looking like it's coming from the wormbase proxy IP.  Todd said he'd change it soon to pass the original IP in the header, then I can change the code to get the user based on that.

**Comment by tharris** [comment]
Try reading the "X-Real-IP" and/or "X-Forwarded-For" headers. I think it would be something like 

`// fake code

$cgi->header('X-Real-IP)
`

**Comment by azurebrd** [comment]
Thanks @tharris .
@chris-grove I've updated that on tazendra for the phenotype.cgi , let me know how it's looking, and we can update the other forms for @draciti @rankishore @tuli .

**Comment by chris-grove** [comment]
@azurebrd   OK, thanks, the form is now remembering based on IP and not just remembering the last submitter in general. I think you can extend this to the other forms now

**Comment by azurebrd** [comment]
Sounds good, I've changed the other forms. @draciti @rankishore @tuli please let me know when you've checked they work well, and we can copy to sandbox and close this issue.

**Comment by chris-grove** [comment]
@azurebrd  The forms are all remembering me when I switch to a "fresh" browser, so remembering by IP looks to be working fine. Also, can we update the link at the bottom of the Optional section of the Phenotype Form page?

http://www.wormbase.org/submissions/phenotype.cgi

The current link still points to the tazendra URL instead of wormbase.org/submissions

@draciti @rankishore @tuli 
I've added my name to each form on all my browsers and clicked the Preview button to register the name. Can you check to see if my name is coming up on your browsers as well?

**Comment by chris-grove** [comment]
@azurebrd   Clarification: the link at the bottom of the phenotype form I'm referring to is the link to the allele-sequence form, which needs to be updated

**Comment by azurebrd** [comment]
Sure, done.  Let me know to sync to sandbox.

**Comment by draciti** [comment]
the microp form is working well. After submission remembers my name so I am signing off. Chris, to answer your question, your name did not come up on my browser

**Comment by chris-grove** [comment]
@azurebrd   the link looks good, thanks. You can sync.

**Comment by rankishore** [comment]
@azurebrd, the gene description form here:
http://www.wormbase.org/submissions/community_gene_description.cgi
seems not to be filling in my e-mail, though when I first came to it, my details were filled in.  To test it, I deleted the pre-filled info and started again with my name, this is when it doesn't auto-fill my e-mail.

**Comment by azurebrd** [comment]
@draciti great, that's as it should be.
@chris-grove cool, done.
@rankishore Did it ever do that ? I mean, before we did these last changes, was it doing that ? At some point when we talked about how it should work it wasn't supposed to do that. Did we subsequently decide that it should, and then it did, but now it doesn't ?

**Comment by rankishore** [comment]
@azurebrd, as discussed, let's leave the gene description form as is, it's working fine, and no one has complained that they have to enter their e-mail manually (the purpose of this form behavior being to collect e-mails that we may not have associated with a WBPerson).
