### ISSUE TITLE
  strain search doesn't work:  (for exa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4466]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;strain search doesn't work: <br/>(for example)<br/>http://www.wormbase.org/species/c_elegans/strain/VC1925#--10</p>

**Reported by:** Kyun********* (kwki************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by tharris** [comment]
User contacted. They had no widgets enabled.
