### ISSUE TITLE
Hi! I was wondering if you could tell me where the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4471]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! I was wondering if you could tell me where the data from the  "Polymorphisms and natural variants" section on Genetics is acquire from. Thank you!

**Reported by:** Nata********** (nata*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003807#395b-04-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00003807#395b-04-3</a>
**Browser:** Chrome 47.0.2526.106

**Comment by tuli** [comment]
Dear Natalia,

Thank you for writing to WormBase.

Polymorphism and natural variant data in WormBase comes from different
sources with the majority being from Whole Genome Sequencing projects.

Clicking on an individual Variant will give you more detail about it.

The whole dataset is very large so if you can give me more detail
about what you are interested in then I will be happy to help you
further.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
