### ISSUE TITLE
  ... find a list of genes that all giv...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4473]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;... find a list of genes that all give a common phenotype?</p>

**Reported by:** Matt******** (w.ma***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by kyook** [comment]
---------- Forwarded message ----------
From: Karen Yook <kyook@wormbase.org>
Date: Thu, Jan 7, 2016 at 6:46 PM
Subject: Re: [wormbase-help] How Do I ...?: ... find a list of genes that
all giv... (Matt Michael)
To: w.matthew.michael@gmail.com
Cc: "help@wormbase.org" <help@wormbase.org>


Hi Matt,

You can find a list of genes with the same phenotype by searching for the
phenotype on the front page. In the search window, make sure you choose
Phenotype from the drop down search tag list. You will be taken to the
phenotype page where you can browse objects that have been assigned that
phenotype. One way to get a list is to open the Ontology Browser widget,
after the phenotype term in the ontology you will see the number of genes
(in brackets) annotated for that phenotype. See attached screen shot for
genes annotated.

Hope this helps.
Best wishes,
Karen

On Thu, Jan 7, 2016 at 6:07 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   ... find a list of genes that all give a common phenotype?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4473. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4473>.
>
> Reported by: Matt Michael (w.matthew.michael@gmail.com)
> 08 Jan 16 02:08
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/47.0.2526.106 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
