### ISSUE TITLE
Hello, I think that this is a BEL-like retroelemen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4476]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I think that this is a BEL-like retroelement -- ie. a transposable element gene.
This gene ZC132.4 has similarity (blast match with e-20) to a phlebovirus protein from Uukuniemi virus (UniProt P09613). It was published  by Frame et al 2001 (PMID:11223261) that the C. elegans clone ZC132 contains a Bel-like LTR-retrotransposon called 'Cer7' which has similarity to this phlebovirus, and they suggested that the BEL-like element has captured an envelope gene from a phlebovirus. I think that the gene ZC132.4 is the Cer7 BEL-like retroelement.

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00022523#0f-9e63bg1c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00022523#0f-9e63bg1c-10</a>
**Browser:** Firefox 38.0

**Comment by gw3** [comment]
Thanks Avril,
I've just had a look at this region and I think you are correct.
It looks like it should be merged with the upstream 
ZC132.5/WBTransposon00000732 locus.
We'll make the change for WS253.
Gary
