### ISSUE TITLE
  Hi, is there a way to limit a nucleot...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4478]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, is there a way to limit a nucleotide BLAST search to just the 3'UTRs of annotated genes?  I'm trying to see if there is any sequence homology between the 3'UTR of my gene of interest and any other 3'UTRs is the elegans genome.</p>

**Reported by:** Matt******** (matt*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by chris-grove** [comment]
Hello Matt,

 The WormBase BLAST service does not provide an option to search against
only 3'UTRs. Using WormBase tools, I think you're best bet may be to
download all annotated 3'UTRs using the WormBase ParaSite BioMart tool
(available under the Tools menu on any WormBase page) and try to perform
sequence alignments with those, although there may be a better way to do
this.

Best,

Chris Grove
WormBase
