### ISSUE TITLE
Hello there,
Please i wish to inquire if i can use...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4486]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello there,
Please i wish to inquire if i can use Wormbase to construct a phylogenetic tree. Thanks

**Reported by:** Ferd***** (fnga*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run">http://www.wormbase.org/tools/blast_blat/run</a>
**Browser:** Chrome 47.0.2526.106

**Comment by chris-grove** [comment]
Hello Ferdinand,

 WormBase does not have a tool to generate phylogenetic trees de novo, although some gene pages display a tree in the Homology widget, for example:

http://www.wormbase.org/species/c_elegans/gene/WBGene00006743#6--7

I would suggest using tools at the TreeFam website:

http://www.treefam.org/

Best,

Chris Grove
WormBase
