### ISSUE TITLE
Hello,
I was wondering how Wormbase assign Interac...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4488]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I was wondering how Wormbase assign Interaction type for interaction data, do we have a documentation for this ? If a genetic interaction is assigned to "Suppression" type, will also appear in "Complete_suppression" subtype?
http://www.wormbase.org/tools/schema/run?class=Interaction&amp;view=expand​

Thanks
visitor_name

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/schema/run?class=Interaction&amp;view=expand">http://www.wormbase.org/tools/schema/run?class=Interaction&amp;view=expand</a>
**Browser:** Chrome 46.0.2490.80

**Comment by chris-grove** [comment]
Hi Nishant,

 The genetic interaction terms are still in a bit of flux at the moment,
but to answer your question, "Complete Suppression" was intended to be a
sub-type of the more general "Suppression". The terms and the
documentation are still being worked out, but I'm happy to answer any
questions you have about them.

Chris Grov
