### ISSUE TITLE
Gene Ontology widget not loading on Topics/Pathways pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4489]
I just noticed that the Gene Ontology widget is throwing an error on any topics pages that I've tried that have at least one GO term associated. For example, on this page:

http://www.wormbase.org/resources/wbprocess/WBbiopr:00000008#3--10

I get this error:

![screen shot 2016-01-12 at 12 06 01 pm](https://cloud.githubusercontent.com/assets/611382/12275450/09cbfd1c-b925-11e5-9daa-de4954f1370d.png)

**Comment by sibyl229** [comment]
Hi @chris-grove the GO widget on Topic page is working now. http://staging.wormbase.org/resources/wbprocess/WBbiopr:00000008#3--10 Thanks for bringing up the problem.

**Comment by chris-grove** [comment]
@sibyl229 
Perfect! Thanks!
