### ISSUE TITLE
FPKM data retrieval request

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4490]
Continuing from issue #4452, user is requesting a feature. 
Hi Karen,
 Thank you for getting back to me. I had another curiosity question. On worm base, expression of a gene across stages is indicated with a graph that is labeled FPKM expression data from selected modENCODE libraries. Could you please let me know precisely what libraries were used? Also, is there a way to get the data across stages for all genes as a downloadable file for those datasets or their average? Thank you.
Best,
  Antony

**Comment by kyook** [comment]
Hi Antony, 

I am not familiar with these data; however my colleague has answered a similar question. 

"You can download all the FPKM data from our SPELL server. You may find the dataset that you are interested from the dataset list, and download specific datasets. SPELL contains RNAseq, tiling array and microarray data for six nematode species, so you may want to use 
Plus Options for Filtering Results by Dataset TagsGreen_new_window_icon   to find the datasets that you are interested. 

Here is the URL for WormBase SPELL: 
http://spell.caltech.edu:3000/search/dataset_listing"


I've Cc'd my colleagues for them to help you with the details of all your questions. 

Best,
Karen

**Comment by kyook** [comment]
Thank you all. I see that the Gerstein et al. 2010 paper from which the worm base graphs are derived is downloadable as a .csv file from SPELL. 
Best,
 Antony

**Comment by kyook** [comment]
Hi Antony, 

I'm wondering if this means that you got all the information you are looking for.  Please let us know if you need any more information, so my colleagues can help you more if you need it.

**Comment by kyook** [comment]
Hello All,
  I have managed with the .csv file and some text manipulation. The one piece of information that would be wonderful to have is a .csv or tab delimited text file that has the data that is used for generating the plot on the Wormbase page for each gene - but organized in a gene-centric view as one file. The Gerstein et al. dataset has some 224 individual RNA-seq experiments in it. But, in the Wormbase one multiple datasets from different stages have been conveniently averaged. So, for people who may be interested in looking at a list of genes and how their expression looks across development (like me), such a file would be very useful.
 Thank you for all your help!
Cheers,
 Antony

**Comment by WenChenWormBase** [comment]
@kyook the wormbase graph was done by Gary Williams. He is also the one who provided data for me to display in SPELL, so I am reassigning this ticket to him so that he can figure out how to improve this feature on WormBase display.

**Comment by kyook** [comment]
Thanks Wen.

Karen

On Tue, Jan 12, 2016 at 3:05 PM, Wen Chen <notifications@github.com> wrote:

> @kyook <https://github.com/kyook> the wormbase graph was done by Gary
> Williams. He is also the one who provided data for me to display in SPELL,
> so I am reassigning this ticket to him so that he can figure out how to
> improve this feature on WormBase display.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4490#issuecomment-171090829>.
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by gw3** [comment]
Anthony,

The subset of modENCODE libraries that were used to produce the graph was
selected in collaboration with Julie Ahringer to try to avoid non-standard
conditions.

The set of SRA Experiment IDs and their Libraries used in the graph is
attached in a CSV file.

Gary

**Comment by gw3** [comment]
Hi Gary,
 Thank you for the information!
Best,
 Antony
