### ISSUE TITLE
  How do I cite wormbase?  What were yo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4491]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I cite wormbase?</p><p>What were you doing? <br />&nbsp;&nbsp;Looking up genes</p>

**Reported by:** Bett* (teba**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by kyook** [comment]
Hi Betty,

Thank for you for writing to WormBase. There are a few ways to cite
WormBase, you can choose which way works for your publication from this
page:
http://www.wormbase.org/about/citing_wormbase#012--10

Let me know if you need further help.
Best wishes,
Karen

On Tue, Jan 12, 2016 at 6:11 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   How do I cite wormbase?
>
> What were you doing?
>   Looking up genes
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4491. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4491>.
>
> Reported by: Betty (tebasebe@gmail.com)
> 13 Jan 16 02:12
>
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/47.0.2526.106 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
