### ISSUE TITLE
please tell me how to download a paper,and the Fre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4492]
*Help Desk query collected when no chat operators were online. Follow up required.*

please tell me how to download a paper,and the Freeze-stored liquid formula of C.elegans

**Reported by:** Jian* (jian*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/paper/frozen freezing">http://www.wormbase.org/search/paper/frozen freezing</a>
**Browser:** Chrome 31.0.1650.63

**Comment by kyook** [comment]
Hi Jiang,

Papers can be downloaded from PubMed if they are open access.  If they are
not, you might want to look it up in your university's library and retrieve
it from there. That said, if you are after a protocol for freezing worms,
you might find the information you want in WormBook, in particular the
Methods reports. This chapter in particular,
http://www.wormbook.org/chapters/www_strainmaintain/strainmaintain.html#d0e920
discusses the maintenance and freezing of worms.  You should be able to
download this using your browser.

Hope this helps.
Best,
Karen

On Tue, Jan 12, 2016 at 6:48 PM, <no-reply@wormbase.org> wrote:

> offline chat please tell me how to download a paper,and the Freeze-stored
> liquid formula of C.elegans
>
> Submitted From:
>   http://www.wormbase.org/search/paper/frozen freezing http://www.wormbase.org/search/paper/frozen
> freezing
> <http://www.wormbase.org/http://www.wormbase.org/search/paper/frozen%20freezing>
>
> This issue has been assigned ticket number: #4492. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4492>.
>
> Reported by: Jiang (jiangd136@nenu.edu.cn)
> 13 Jan 16 02:48
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
