### ISSUE TITLE
  We are trying to find a simple way to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4495]
_Submitted from the feedback form on the WormBase website._

<p>&nbsp;&nbsp;We are trying to find a simple way to identify ncRNAs in our RNA-seq data on Wormbase. We tried using WormMine, which gave us a total of 2,070 nc transcripts (link below). However, it seems like this search provides only a small proportion of nc transcripts - using the general search tab in WormBase (for a gene) querried many more ncRNAs. Can you please tell me what the criteria is for the compiled nc transcripts in WormMine? Is there a way to download a "complete" list of ncRNAs?<br/>Thank you!<br/>http://im-dev.wormbase.org/tools/wormmine/results.do?trail=%7Cquery</p><p>What were you doing? <br />&nbsp;&nbsp;We are trying to identify all non-coding RNAs from our RNA-seq in Wormbase. Is there a quick way?</p>

**Reported by:** Jung***\* (jdoh********_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by chris-grove** [comment]
Hi Jung, 

You can retrieve a file of all ncRNA transcripts from our ftp site here: 
ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/species/c_elegans/PRJNA13758/

There are 25756 transcripts listed, they include ncRNA, piRNA, miRNA, lincRNA, nc_primary_transcript etc.
16680 are associated with a locus name. 

Hopefully the tags included for each entry can help you parse the file as you need. 

Unfortunately I cannot answer you question about nc transcripts in WormMine, but while we wait for my colleagues to address your question, perhaps the file I pointed you to will help. 

Best,
Karen

**Comment by chris-grove** [comment]
Hi Jung,

Just to add to Karen's comments...


It looks like there was a division of the ncRNA class of transcripts into "ncRNA" and "7kncRNA" as a result of findings from this paper:


http://genome.cshlp.org/content/21/2/276.long

You can find a more complete list of C. elegans transcripts from WormMine by modifying your original query to include all non-coding transcript types. Try importing this XML using the "Import query from XML" option in the WormMine QueryBuilder page:

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.transcripts.method Gene.transcripts.symbol Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="B and A">
  <constraint path="Gene.transcripts.method" code="A" op="ONE OF">
    <value>7kncRNA
    </value>
    <value>asRNA
    </value>
    <value>lincRNA
    </value>
    <value>miRNA
    </value>
    <value>miRNA_primary_transcript
    </value>
    <value>ncRNA
    </value>
    <value>non_coding_transcript
    </value>
    <value>piRNA
    </value>
    <value>pre_miRNA
    </value>
    <value>rRNA
    </value>
    <value>scRNA
    </value>
    <value>snRNA
    </value>
    <value>snlRNA
    </value>
    <value>snoRNA
    </value>
    <value>tRNA
    </value>
  </constraint>
  <constraint path="Gene.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>
</query>
```

That should return all non-coding transcripts that we currently have in WormMine (which runs off of the WS250 release of WormBase). These should correspond to the WS250 FTP file:


c_elegans.PRJNA13758.WS250.ncRNA_transcripts.fa


located at:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/


with the exception that the FTP file does not differentiate between "ncRNA" and "7kncRNA".


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
@khowe 
I'm not sure if you're the one to ask, but is there a formal set of descriptions for each transcript type anywhere? It also seems a bit confusing that there are "non_coding_transcript", "ncRNA" and now "7kncRNA"; is "ncRNA" just a tag we give a transcript when we know it isn't coding but doesn't fit in any other category? And what's the difference between "non_coding_transcript" and "ncRNA"? It does seem that these are all mutually exclusive categories.

**Comment by Paul-Davis** [comment]
@chris-grove there are some descriptions in the methods that could be used but in some cases it's just the SO term. I'll have a think on where we could store this data and have a go at fleshing them out.

P

**Comment by Paul-Davis** [comment]
@kyook @chris-grove  did you both respond privately to the user are I can't see an email from either of you with the users contact details in the To/cc?

**Comment by Paul-Davis** [comment]
@chris-grove the non_coding_transcript method should be removed from the xml query as these are non_coding_transcripts coming from coding loci. Do you want to pass this info along so they aren't swamped with another curator contact.

**Comment by khowe** [comment]
I think the problem here is that WormMine is using the Method name as a proxy for biological transcript type. We use the Methods for internal data management, and they should  not be relied upon to have any biological meaning. For the non-coding transcripts, they mostly do, but not always. 

The Method for each Transcript is associated with a SO term (through Method->GFF_SO). This is a term from the Sequence Ontology describing the biological type of the transcript. This is what WormMine should be presenting as the transcript "type", IMO. 

This will involve a fix to the WormMine build, but not a big one hopefully. @Paul-Davis will create a new ticket for that.

**Comment by chris-grove** [comment]
@khowe @Paul-Davis 
Thanks! I've always disliked the reference to "Method" for gene or transcript type, although I understand why it has been that way; it just isn't end-user friendly. Paul, I didn't realize that's what "non_coding_transcript" meant. What did you mean by "pass this info along so they aren't swamped with another curator contact"? You mean tell the Jung, the original issue submitter?

**Comment by Paul-Davis** [comment]
@chris-grove yes if you don't mind passing the information on the Jung. I always think it looks a bit wrong to have more that 1/2 curators in contact with a user unless it's really necessary.

Thanks

**Comment by chris-grove** [comment]
@Paul-Davis 
Got it. Will do. Thanks for clarifying.

**Comment by chris-grove** [comment]
@Paul-Davis @khowe 
I emailed Jung a new query. Just to be clear, are the transcripts tagged with the method "non_coding_transcripts" uninformative or unreliable in some way? Should these be entirely excluded from WormMine? Could we copy all of the relevant transcript types from the Method tag to the Biotype tag?

**Comment by khowe** [comment]
Transcripts with Method "Non_coding_transcript" are non-coding transcripts of protein-coding genes. So they are not functional ncRNA genes in the traditional sense. Most often with these, there is evidence (EST, RNASeq) for that transcript structure being expressed as an isoform, but no sensible ORF can be found. 

When people are using WormMine to pull out the complement of C. elegans ncRNA genes, there are probably not interested in these. That would be my guess.

**Comment by Paul-Davis** [comment]
Thanks @chris-grove 

I think @khowe has covered all the bases.

**Comment by chris-grove** [comment]
@khowe  OK, thanks for the explanation. Could we possibly come up with a different name for these special non-coding transcripts, like "coding loci non-coding transcripts (clnc)" or something else distinct? Also, what about copying over the transcript types from the Method to the Biotype tag for each gene? The Biotype tag seems to be the most relevant place in the gene model to place this information, but it is currently only being populated with four SO_terms: "protein_coding_gene", "ncRNA_gene", "pseudogene", and "transposable_element_gene". Can we also add the other types (e.g. snoRNA, tRNA, rRNA) where appropriate to the Biotype tag?

**Comment by Paul-Davis** [comment]
Biotype was updated for known examples of different sub-types of ncRNA a while ago so if Biotype is used in the wormmine build this should make things cleaner.
