### ISSUE TITLE
How to register a new worm lab?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4498]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to register a new worm lab?

**Reported by:** Suho***** (shxu***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/laboratory#23-10-5-1">http://www.wormbase.org/resources/laboratory#23-10-5-1</a>
**Browser:** Chrome 47.0.2526.106

**Comment by raymond91125** [comment]
Hi Suhong,

Congrats. Please consult this page 
<http://www.wormbase.org/about/userguide/nomenclature#0--10>, under the 
heading "How to apply for new names".

Thanks.

Raymond
