### ISSUE TITLE
Hello,
I'm thinking it would be nice to have a sum...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4500]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I'm thinking it would be nice to have a summary of the expression pattern in the description at the top of a gene's page, eg. for T19D12.5 the ENCODE data shows a big peak of male expression. On the flybase website they have a summary of expression pattern for a gene, which is useful when little is known about the gene. Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00020580#0f-9e63bg1c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00020580#0f-9e63bg1c-10</a>
**Browser:** Firefox 38.0

**Comment by draciti** [comment]
Hi Avril, 
thanks for your suggestion. It is a very good idea and at WormBase we are already discussing about implementing something similar, i.e. consolidating large scale expression data into human-readable summaries.
We will keep you posted.
Best,
Daniela
