### ISSUE TITLE
Ontology Browser test case failure

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#4502]
Hi @azurebrd the test case for Ontology Browser has a fail test. 

```
# Subtest: test_anatomy_ontology_browser
    ok 1 - contains WBbt:0001002
    ok 2 - contains run link WBbt:0001002
    not ok 3 - contains child_nucleus_of
    #   Failed test 'contains child_nucleus_of'
    #   at t/rest_tests/anatomy.t line 49.
    #          got: ''
    #     expected: '1'
    1..3
    # Looks like you failed 1 test of 3.
not ok 4 - test_anatomy_ontology_browser
```

Here's the test case code: https://github.com/WormBase/website/blob/staging/t/rest_tests/anatomy.t#L49

I'm not sure if it's due to a data change or something else. Could you take a look please? Thank you!

**Comment by raymond91125** [comment]
It was my fault. I messed up the config file for building the solr document store. Should be fixed now. Thanks for the alert.

**Comment by sibyl229** [comment]
Thanks @raymond91125 ! Yes, the test is passing now. Closing.
