### ISSUE TITLE
  I want a complete list of ubiquitin E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4504]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want a complete list of ubiquitin E3 ligases in the C. elegans genome. How can I do it? Thank you.</p>

**Reported by:** Hiro** (hses************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:16.0) Gecko/20100101 Firefox/16.0

**Comment by janelomax** [comment]
Hi Hiromi

Thank you for contacting WormBase. 

To get a complete list of ubiquitin E3 ligases, you can search for the GO term 'ubiquitin protein ligase activity ; GO:0061630' in the main search box. This will return a list of all C. elegans genes annotated with this term. Note that the gene set you return may include a few E2 genes, but should be comprehensive for E3.

best wishes

Jane Lomax
WormBase Helpdesk
