### ISSUE TITLE
lifestage patch for WS252

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4506]
could you load ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS252/acedb/acedb/PATCHES/lifestage_patch.ace

to fix one problem with the expression widget?

thanks,

M

**Comment by tharris** [comment]
Loaded. Please confirm that it resolves the issue.

**Comment by epaule** [comment]
Almost. There are some datapoints populated not through xrefs but during the build.
that patch should catch them: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS252/acedb/PATCHES/life_stage_patch2.ace.gz

**Comment by tharris** [comment]
Loaded.
