### ISSUE TITLE
  Hello- I noticed that the wdr-81 gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4508]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello-<br/>I noticed that the wdr-81 gene designation has been linked to the wrong gene.<br/>Currently wdr-81 = F52C9.10 <br/>It should be linked to F52C9.1<br/>Thanks!<br/>visitor_name<br/>visitor_email</p>

**Reported by:** Greg******** (herm**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by tuli** [comment]
Dear Greg,

Thank you for writing to WormBase.

You are quite right, wdr-81 was erroneously assigned to F52C9.10
I apologise for this mistake.

I have corrected the connection (wdr-81 = F52C9.1) and have added a
Remark in F52C9.10 to document the mistake as it will be present in
WS251 and WS252 of WormBase.

Please be assured that the correct assignment will be available in
release WS253.

Best wishes,

Mary Ann

On 19 January 2016 at 14:51,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hello-
> I noticed that the wdr-81 gene designation has been linked to the wrong
> gene.
> Currently wdr-81 = F52C9.10
> It should be linked to F52C9.1
> Thanks!
> Greg Hermann
> hermann@lclark.edu
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #4508. Follow progress on our
> issue tracker.
>
> Reported by: Greg Hermann (hermann@lclark.edu)
> 19 Jan 16 14:52
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101
> Firefox/38.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
