### ISSUE TITLE
  the data on wormbase for e1410 does n...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4510]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;the data on wormbase for e1410 does not match the data presented in the paper Malone et al Development 1999. e140 should be C994Y and what is e1401 on wormbase is n1410 in the Malone et al paper</p>

**Reported by:** Dan ***** (dast***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by tuli** [comment]
Dear Daniel,

Thank you for writing to WormBase and for alerting us to this mistake.

I have updated the records as requested.

e1410 (WBVar02145377) is now C994Y
n1410 (WBVar00143985) is now Q104Amber

This update will be available in release WS253 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
