### ISSUE TITLE
Updating title and link to phenotype submission form

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4511]
@sibyl229 
@azurebrd  and I have finished updating the "Allele-Phenotype Form" to accommodate RNAi and transgenes. We would like to change the link under "Submit Data" from "Allele phenotype":

![screen shot 2016-01-19 at 4 05 22 pm](https://cloud.githubusercontent.com/assets/611382/12436028/7c1abe3e-bec6-11e5-9498-36e58133cff9.png)

to simply "Phenotypes" and the link should point to:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/phenotype.cgi

I've made the necessary changes on the Submit Data page.

**Comment by sibyl229** [comment]
Hi @chris-grove I updated the phenotype submit data link on staging site.

**Comment by chris-grove** [comment]
@sibyl229  That's great! Thanks Sibyl!

**Comment by chris-grove** [comment]
@sibyl229  Apologies, can we now make the URL:

http://www.wormbase.org/submissions/phenotype.cgi

This is to accommodate the new URL we just made for submission forms. Thanks!

**Comment by chris-grove** [comment]
@sibyl229  Would it be OK to update the link on staging to the new ".../submissions/phenotype.cgi" URL? Thanks!

**Comment by sibyl229** [comment]
@chris-grove Hi, yes, it was just updated.

**Comment by chris-grove** [comment]
Perfect! Thanks @sibyl229
