### ISSUE TITLE
  In WormBase, I would like to print co...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4512]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;In WormBase, I would like to print contents about certain genes. But resulting printed pages exhibit imperfect contents, excluding the "Overview section". How can I print them perfectly? </p>

**Reported by:** hkoj*********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by tharris** [comment]
Contacted user and referred to print as pdf function of browser/OS.
