### ISSUE TITLE
Escaped backslashes

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4513]
Hi webteam,
on this page
http://www.wormbase.org/species/c_elegans/expr_pattern/Expr12292#012--10
under curatorial remarks 

the DOI has backslashes escaped. Could you please change it?
thanks

**Comment by sibyl229** [comment]
Hi @draciti the DOI url in the remark is backslash escaped in the database, and I think it probably shouldn't. The DOI in Paper class isn't backslash escaped. It's probably good to have a consist way to handle URL in the database. What do you think?

**Comment by draciti** [comment]
hi sibyl, in the .ace file the backslashes should be escaped otherwise acedb does not read the whole line

**Comment by Paul-Davis** [comment]
But the data looks to have too many so some remain when the file is loaded back into the database

```
Remark   -O "2015-12-04_12:29:58_daniela" "To cite this work: Ghosh, Srimoyee\; Inoue, Takao\; Sternberg, Paul (2015): ina-1::gfp expression. WormBase. Dataset. DOI: http:\\\/\\\/dx.doi.org\\\/10.17912\\\/W2159J. Reviewed by Bhagwati Gupta. Funding: National Institutes of Health USPHS training grant GM07616." -O "2015-12-04_12:29:58_daniela"
```

**Comment by draciti** [comment]
good catch Paul, thanks. there were extra slashes. I tested the dumper and it works properly so the next file should work well. thanks both. closing
