### ISSUE TITLE
Predicted SL signals (i.e., sites) may be wrongly ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4514]
*Help Desk query collected when no chat operators were online. Follow up required.*

Predicted SL signals (i.e., sites) may be wrongly displayed in gbrowse. Many SL sites are within genes (e.g., III:10,092,980..10,093,079) and do not correspond to trans-splicing acceptor sites (i.e., AG). I suspect that there is a version issue. 

Thank you for your attention. 

visitor_name

**Reported by:** Jack***** (chen********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 47.0.2526.106

**Comment by Paul-Davis** [comment]
Dear Jack,

I think you are referring to the modENCODE data tracks, unfortunately 
the modENCODE data is still on the WS220 reference co-ordinates, on the 
whole the data does fit the majority of the genome, but I think you have 
raised a good point and we need to discuss what to do with this data.

Thanks

Paul




On 20/01/2016 20:15, no-reply@wormbase.org wrote:
> offline chat Predicted SL signals (i.e., sites) may be wrongly 
> displayed in gbrowse. Many SL sites are within genes (e.g., 
> III:10,092,980..10,093,079) and do not correspond to trans-splicing 
> acceptor sites (i.e., AG). I suspect that there is a version issue. 
> Thank you for your attention. Jack Chen
>
> Submitted From:
>   http://www.wormbase.org/#01-23-6 http://www.wormbase.org/#01-23-6 
> <http://www.wormbase.org/http://www.wormbase.org/#01-23-6>
>
> This issue has been assigned ticket number: #4514. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4514>.
>
> Reported by: Jack Chen (chenn@sfu.ca)
> 20 Jan 16 20:15
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Jack,

I should have also mentioned that we realign all of the modENCODE RNASeq 
data and use this to mark up TSL sites in the "Trans-spliced acceptor 
track found under the Transcription section of the gbrowse track selector.

Paul


On 21/01/2016 10:20, Paul Davis wrote:
>
> Dear Jack,
>
> I think you are referring to the modENCODE data tracks, unfortunately 
> the modENCODE data is still on the WS220 reference co-ordinates, on 
> the whole the data does fit the majority of the genome, but I think 
> you have raised a good point and we need to discuss what to do with 
> this data.
>
> Thanks
>
> Paul
>
>
>
>
> On 20/01/2016 20:15, no-reply@wormbase.org wrote:
>> offline chat Predicted SL signals (i.e., sites) may be wrongly 
>> displayed in gbrowse. Many SL sites are within genes (e.g., 
>> III:10,092,980..10,093,079) and do not correspond to trans-splicing 
>> acceptor sites (i.e., AG). I suspect that there is a version issue.  
>> Thank you for your attention.  Jack Chen
>>
>> Submitted From:
>> http://www.wormbase.org/#01-23-6 http://www.wormbase.org/#01-23-6 
>> <http://www.wormbase.org/http://www.wormbase.org/#01-23-6>
>>
>> This issue has been assigned ticket number: #4514. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/4514>.
>>
>> Reported by: Jack Chen (chenn@sfu.ca)
>> 20 Jan 16 20:15
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
