### ISSUE TITLE
GBrowse/Jbrowse track layout tweak

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4516]
I'm mainly talking about the Gbrowse layout, but the corrseponding Jbrowse modifications should also be considered.

As a follow on from Jack Chen's emails about TSL sites #4514 we noticed that the curated/high confidence set are quite hard to find as they are under Transcription->Signals->(PolyA sites and signal sequences/Trans-spliced acceptor/Transcription end site).

Could I propose a bit of a re-ordering of the data.

We could remove the top level Transcription and fit the data that is currently under this branch into other sections.

1) Create a top level Gene Structures section.
       a) Move the current Genes under here, could give it a new Genes (curated) or similar
       b) Move the Ab-initio predictions under here.
       c) Move the Supporting Evidence under here.

2) Move the Transcription->Signals under Sequence features
      a) Probably add them to the current Sequence Features->﻿﻿Signals & Motifs

![gbrowse_tracks](https://cloud.githubusercontent.com/assets/717707/12478900/b803fcfc-c02f-11e5-82ab-48788d1aaf4f.png)

Thanks

Paul

**Comment by scottcain** [comment]
Hi @Paul-Davis I don't have an opinion about this one way or the other (well, other than what you say makes sense). @tharris , do you have an opinion? Change can be difficult.  Unfortunately, neither GBrowse nor JBrowse have the ability to put tracks in two different places in the track selector at the same time, so moving thing around may disorient people who are used to finding things where they are now.

**Comment by scottcain** [comment]
Hi @Paul-Davis and @tharris I made these changes on staging for C. elegans only at the moment:

http://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/

Please let me know if you'd like for it to stay this way and I'll make it permanent.

**Comment by scottcain** [comment]
With the general lack of feedback on the GBrowse changes, I went ahead and made the same changes to JBrowse on staging.  With the other changes I've made to JBrowse, it now loads nice and snappy, and has an option to show the track selector on the left side of the page, shown here:

http://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=X%3A8850618..8862507&tracks=Prediction%3A%20mSplicer&highlight=

@Paul-Davis if you're happy with this, please feel free to close this ticket.

**Comment by epaule** [comment]
is there somewhere a button/link/thing to close the track selector?

**Comment by scottcain** [comment]
Not built in to JBrowse, but the "Track selector" button in the right corner is a plugin I wrote to shift between two instances of JBrowse--one with the faceted track selector (which we've been using all along) and the hierarchical selector that is always on the left.

**Comment by Paul-Davis** [comment]
All looks good to me on GBrowse.....sorry for the late response.
