### ISSUE TITLE
  The Genetic Map widget is currently b...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4517]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The Genetic Map widget is currently broken - it shows a "Gateway Timeout" error. </p>

**Reported by:** Dan (ddic*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Comment by chris-grove** [comment]
Confirmed

**Comment by chris-grove** [comment]
Is working again. Will re-open if necessary.

**Comment by chris-grove** [comment]
I've contacted the user
