### ISSUE TITLE
  Hi there Under all registered worm la...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4521]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there<br/>Under all registered worm labs my affiliation is with the University of Copenhagen. This has changed to Monash University.<br/>How do I change that?</p>

**Reported by:** roge*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Comment by tuli** [comment]
Dear Roger,

Thank you for writing to WormBase.

Changes in Laboratory can be sent to genenames@wormbase.org

However, I found your details and have updated the RJP lab as follows:

New address: Monash University, Victoria, Australia
Email: Roger.Pocock@monash.edu
URL: http://www.med.monash.edu.au/anatomy/staff/roger-pocock.html
Lab members: Roger Pocock
Agnieszka Podolska
Sandeep Gopal
Gregory Davis
Steffen Norgaard
Vaida Juozaityte
Teresa Rojo
Goda Snieckute

Past lab members: Konstantinos Kagias
Nanna Torpe
Jakob G Petersen
Mikael Pedersen
Alba Redo Riveiro

Please send your phone number if you would like this to be added. and
let me know if any of the new details are incorrect.

This update will be available in release WS253 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Mary Ann

These details are correct but when I go to the 'All registered C. elegans'
link through wormbook my old details appear. Also, I have not received an
invitation to the Worm Board announcements. Todd - is that something you
could possibly help me with?

Cheers
Roger

Roger Pocock DPhil
*veski* Innovation Fellow
Head, Neuronal Development and Plasticity Laboratory
Biomedicine Discovery Institute
Department of Anatomy and Developmental Biology
Building 75, Level 3, Room 328a
Monash University
VIC 3800
Australia

Telephone: +61 3 990 50654

Website -
http://www.med.monash.edu.au/anatomy/research/neuronal-development-and-plasticity-laboratory.html

**Comment by tuli** [comment]
Dear Dr. Roger Pocock:

This is your data in your Person page in  WS251 release of WormBase
<http://www.wormbase.org/about/wormbase_release_WS251>
http://www.wormbase.org/resources/person/WBPerson1725#01--10

I have updated your lab members data and lineage in Person class.
WBPerson14483 Mikael Pedersen oldlab : RJP
WBPerson19157 Steffen Norgaard lab : RJP
WBPerson28790 Sandeep Gopal lab : RJP
WBPerson32601 Leelee Ng lab : RJP
WBPerson25230 Agnieszka Podolska lab : RJP
WBPerson14503 Vaida Juozaityte oldlab : RJP
WBPerson14475 Nanna Torpe oldlab : RJP
WBPerson1725 Roger Pocock lab : RJP
WBPerson14484 Goda Snieckute lab : RJP
WBPerson32597 Matilda Haas lab : RJP
WBPerson28239 Lorenzo Rella oldlab : RJP
WBPerson14594 Jakob G Petersen oldlab : RJP
WBPerson32599 Mohammed Hatem oldlab : RJP
WBPerson13824 Gregory Davis lab : RJP
WBPerson6792 Konstantinos Kagias oldlab : RJP
WBPerson14499 Teresa Rojo lab : RJP
WBPerson32600 Mikael Pederson oldlab : RJP
WBPerson21799 Alba Redo Riveiro oldlab : RJP
WBPerson30807 Tian Xia oldlab : RJP
WBPerson14498 Kasper Langebeck-Jensen oldlab : RJP
WBPerson32598 David Pladevall Morera lab : RJP

Please add starting years of your current lab members:
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person_lineage.cgi?action=Display&number=WBPerson1725

Updates will appear in WS253 release of WormBase.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule#01--10

Thanks,
Have a great day!

cecilia
