### ISSUE TITLE
visitor_name (visitor_email): how can i find a bac...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4523]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): how can i find a background for a specific gene

**Reported by:** SARO* (hana****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/pcr_oligo/171721_x_at#02--10">https://www.wormbase.org/species/c_elegans/pcr_oligo/171721_x_at#02--10</a>
**Browser:** Safari 9.0.2

**Comment by chris-grove** [comment]
Emailed submitter, haven't heard back. Closing. Will reopen if necessary.
