### ISSUE TITLE
  I am trying to register an account in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4525]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to register an account in WormBase, and then download the protein database of C. elegans for my research project. But I could not find the place for registration. Could you please tell me how to do it? Thank you very much!</p>

**Reported by:** Chun********** (chun***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1

**Comment by janelomax** [comment]
Dear Chunguang Wang

You can register for a WormBase account here:

http://www.wormbase.org/register

thanks

Jane Lomax
WormBase helpdesk
