### ISSUE TITLE
Sync ParaSite 5 to ftp.wormbase.org

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4532]
Would it be possible to have the latest ParaSite release files synched from ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/WBPS5/ to ftp://ftp.wormbase.org/pub/wormbase/parasite/releases/WBPS5/

Thanks

Bruce

**Comment by tharris** [comment]
Syncing complete!

**Comment by tharris** [comment]
Ok, closing.

**Comment by brucebolt** [comment]
Thank you, Todd.
