### ISSUE TITLE
  WormMart doesn't seem to be working o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4533]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormMart doesn't seem to be working on any type of computer/internet browser combination I try. Will it be up again soon?</p><p>What were you doing? <br />&nbsp;&nbsp;Identify promotor sequences for upregulated genes in a mutant strain of c. elegans</p>

**Reported by:** cep3**********
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17

**Comment by raymond91125** [comment]
Hi,

WormMart services hosted at caprica.caltech.edu have been discontinued 
as their functionality is being replaced by Parasite BioMart or WormMine 
(both listed under Tools). Please give them a try and let us know if you 
cannot get what you want.

Apologies for the inconvenience.


Raymond


On 01/27/2016 10:52 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   WormMart doesn't seem to be working on any type of computer/internet 
> browser combination I try. Will it be up again soon?
>
> What were you doing?
>   Identify promotor sequences for upregulated genes in a mutant strain 
> of c. elegans
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4533. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4533>.
>
> Reported by: cep336@nyu.edu
> 27 Jan 16 18:54
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 
> (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
