### ISSUE TITLE
  Hello,  I am wondering if you have a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4535]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>I am wondering if you have a list of all of the C. elegans genes (both coding and non-coding) that were predicted by not confirmed in by transcript evidence. <br/>Thanks for your help, again!</p>

**Reported by:** Jung**** (jdoh*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Comment by epaule** [comment]
we have various data in our database that might be of help to you:
* we got expression levels per life-stage -> which you can see in the Expression widget
* we got supporting ESTs/cDNAs -> which you can see in the Reagents widget
* and we got the EST/cDNA coverage status for the CDSes (fully covered/partially covered/unconfirmed)

most of the data is not yet available through our data-mining tools, but if you can tell us what you need, we can provide you with it.
