### ISSUE TITLE
Hi! I can't figure out how to get upstream promote...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4537]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! I can't figure out how to get upstream promoter regions in wormmine. I know how to do this in wormmart, but it is down. Two questions, can I use wormmine to get upstream regulatory regions and will wormmart be fixed. Cheers,

Vic

**Reported by:** Vict** (vjen**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 48.0.2564.82

**Comment by chris-grove** [comment]
[wormbase-help] offline chat transcript: Hi! I can't figure out how to get upstream promote... (Victor)
Grove, Christian A. (Chris) <cgrove@caltech.edu>
vjensen@sfu.ca;help@wormbase.org;Thu 1/28/2016 4:28 PM
Hi Vic,

 WormMart is no longer supported, and this cannot be done in WormMine currently, but we have a WormBase-ParaSite BioMart tool (available under the Tools menu) that can perform the function of retrieving upstream sequences for a gene or list of genes:

http://parasite.wormbase.org/biomart/martview/bc2030a4bc26ad5d41a71514959b5a65

This BioMart is supported and will be so for the foreseeable future.

Best,

Chris Grove
WormBase
