### ISSUE TITLE
Hey guys,
it's a couple of days I am trying to use...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4539]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hey guys,
it's a couple of days I am trying to use WormMart without success (it gives an error when I try to open the page). Apparently it's a common problem, I've tried to ask to other colleagues in other European countries and it seems they encounter the same problem.
Thanks for your attention!

Best regards,

-Cris

**Reported by:** Cris************* (cris***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Safari 9.0.2

**Comment by janelomax** [comment]
Hi Cris


WormMart is no longer supported (apologies, we’ll remove the dead link to WormMart from the menu) but we do have a WormBase-ParaSite BioMart tool (available under the Tools menu) that you can use instead.
http://parasite.wormbase.org/biomart/martview/bc2030a4bc26ad5d41a71514959b5a65

This BioMart is supported and will be so for the foreseeable future.

You can also use WormMine:

http://im-dev.wormbase.org/tools/wormmine/begin.do
 
hope this helps

Jane







On Jan 29, 2016, at 8:52 AM, WormBase Helpdesk <notifications@github.com> wrote:

> Help Desk query collected when no chat operators were online. Follow up required.
> 
> Hey guys,
> it's a couple of days I am trying to use WormMart without success (it gives an error when I try to open the page). Apparently it's a common problem, I've tried to ask to other colleagues in other European countries and it seems they encounter the same problem.
> Thanks for your attention!
> 
> Best regards,
> 
> -Cris
> 
> Reported by: Cris************* (cris********************)
> *Submitted from: http://www.wormbase.org/#01-23-6
> Browser: Safari 9.0.2
> 
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
