### ISSUE TITLE
  The BLAST seems to be broken - I keep...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4541]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The BLAST seems to be broken - I keep getting a "bad gateway timeout" message. Would be great if someone had time to look into this.<br/>Thanks<br/>Christian</p>

**Reported by:** Chri********************* (chri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Comment by tharris** [comment]
Fixed, user contacted.
