### ISSUE TITLE
  How do I come up with a list of C. br...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4543]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I come up with a list of C. brenneri, C. remanei, and C. briggsae 1:1:1 orthologs? I see the old FAQ answer to the same question for C. elegans:C. briggsae orthologs, but the links there seem broken and I also cannot seem to access WormMart (at least via Google Chrome browser).</p>

**Reported by:** Mike********* (mpal****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Comment by epaule** [comment]
we retired WormMart a while ago: http://blog.wormbase.org/2015/11/13/wormmart-sunset-period-to-be-retired-01-jan-2016/

Sadly, we haven't yet added the orthology querying to WormMine and our ParaSite BioMart.
On the positive side, you can get actually all orthologs from the ParaSite BioMart, they are just not filtered by type (1:1/1:many).

You could therefore grab the one from the BioMart, filter them and do a union with a small script, or if you give us a list of the species you would like to have included, we can also do that for you.
