### ISSUE TITLE
  phenotype graph does not display  Wha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4549]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;phenotype graph does not display</p><p>What were you doing? <br />&nbsp;&nbsp;let-23 gene page.  no response in several attempts</p>

**Reported by:** Paul********** (worm****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by raymond91125** [comment]
Hi Paul,

It seems to be working with no hitch for me right now. Let us know if 
the problem persists for you.

Thanks.

Raymond


On 02/02/2016 10:36 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   phenotype graph does not display
>
> What were you doing?
>   let-23 gene page. no response in several attempts
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4549. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4549>.
>
> Reported by: Paul Sternberg (wormraiser@gmail.com)
> 02 Feb 16 18:37
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:43.0) Gecko/20100101 
> Firefox/43.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
