### ISSUE TITLE
Can I rearrange my favorites into a list in my pre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4552]
*Help Desk query collected when no chat operators were online. Follow up required.*

Can I rearrange my favorites into a list in my preferred order?  And/or can one create folders for different classes of favorites?

**Reported by:** Curt******* (cloe**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/me#12-0-5">http://www.wormbase.org/me#12-0-5</a>
**Browser:** Chrome 48.0.2564.97

**Comment by scottcain** [comment]
Did anybody ever answer this?  My thinking is that the answer is "no" in both cases, but I want to double check before I answer.  @sibyl229 ?

**Comment by sibyl229** [comment]
Hi @scottcain I don't think we can right now. I guess the user probably saved a lot of items in My Favourites and have trouble finding things. We can probably add a feature to allow users to add tag to each favourite items and filter by tags.

**Comment by scottcain** [comment]
User contacted and created this feature request in response: https://github.com/WormBase/website/issues/4586
