### ISSUE TITLE
My 'Institution' information is incorrect - you wi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4553]
*Help Desk query collected when no chat operators were online. Follow up required.*

My 'Institution' information is incorrect - you will see it does not match up with my address

**Reported by:** Curt******* (cloe**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/person/WBPerson384#013--10">http://www.wormbase.org/resources/person/WBPerson384#013--10</a>
**Browser:** Chrome 48.0.2564.97

**Comment by scottcain** [comment]
Who fixes this sort of thing?  Is it not up the the user to fix?

**Comment by tuli** [comment]
Dear Curtis,

Thank you for contacting WormBase. We'll make sure you're Person
details are fixed.

Mary Ann

On 4 February 2016 at 08:42,  <no-reply@wormbase.org> wrote:
> offline chat My 'Institution' information is incorrect - you will see it
> does not match up with my address
>
> Submitted From:
>   http://www.wormbase.org/resources/person/WBPerson384#013--10
> http://www.wormbase.org/resources/person/WBPerson384#013--10
>
> This issue has been assigned ticket number: #4553. Follow progress on our
> issue tracker.
>
> Reported by: Curtis Loer (cloer@sandiego.edu)
> 04 Feb 16 16:44
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by ceciliaWBPerson1** [comment]
Dear Curtis: I apologize, I fixed the error on   2015-12-21 10:20:07.
Updates will appear in WS253 release of WormBase.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule#01--10
cecilia

**Comment by tuli** [comment]
Dear Curtis: I apologize, I fixed the error on 2015-12-21 10:20:07.
Updates will appear in WS253 release of WormBase.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule#01--10
cecilia
