### ISSUE TITLE
Add ORCID visibility on the Person summary pages.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4555]
Could we add a field to the Overview widget that contains the linkes ORCID?

http://www.wormbase.org/resources/person/WBPerson1983#014357--10

as an example.

P

**Comment by tuli** [comment]
I think it would be best placed in the summary box within the Overview widget, just under the WormBase ID

**Comment by Paul-Davis** [comment]
![orcid](https://cloud.githubusercontent.com/assets/717707/12828761/632ea42c-cb3b-11e5-9287-4c090f0fd64e.png)

**Comment by ceciliaWBPerson1** [comment]
Hi Paul,
Sounds good to me.
Some people have multiple ORCIDs, do we want to display as many as people
want to give us, or force users to choose a unique value?
Cecilia

**Comment by Paul-Davis** [comment]
How many users have multiple ORCIDs....I thought the ORCID concept was you register with them once and attach all your publications to that profile. Maybe if there are multiple values, we display both/all?

**Comment by ceciliaWBPerson1** [comment]
Sorry, in Oct 2013 we were in talks with ORCID to give them the information
of our Person objects and their associated publications, and at the time an
ORCID search for various Caltech curators would each give multiple IDs
splitting the information.  Looking again now, it's cleaned up with single
entries.

We have only had 22 updates from users that sent us their ORCID.  Do we
want to actively search for more, or programmatically try to map the
standard names we have to ORCID pages and hope that it's the correct person
?

Juancarlos and Cecilia

**Comment by ceciliaWBPerson1** [comment]
Todd:
Could you add ORCID data, it is already in the Tree display.

*DB_info**Database*ORCIDAccession_number0000-0001-5545-0824



Thanks,
Cecilia

**Comment by Paul-Davis** [comment]
It seems that even when looking for Paul S. there are 2 ORCIDs in the ORCID database

http://orcid.org/0000-0003-3820-6867 - incorrect?
http://orcid.org/0000-0002-7699-0173 - correct

**Comment by ceciliaWBPerson1** [comment]
Let's ask him 😀

**Comment by Paul-Davis** [comment]
I was just trying to illustrate that unless we can get access to large scale ORCID data, it will be troublesome to connect WBPersons with ORCIDs.

**Comment by tharris** [comment]
Can we (well, @azurebrd) make a simple form: "Have an ORCID ID? Associate it with your WormBase account!", then we can post a link to it periodically?

**Comment by Paul-Davis** [comment]
and add a field to the emails/forms that go out to WBPersons to update 
their details.


On 05/02/2016 10:18, Todd Harris wrote:
>
> Can we (well, @azurebrd <https://github.com/azurebrd>) make a simple 
> form: "Have an ORCID ID? Associate it with your WormBase account!", 
> then we can post a link to it periodically?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/4555#issuecomment-180479831>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by epaule** [comment]
@Paul-Davis I think one issue with OrcID is, that they are uncurated, so they will not necessary be unique. Maybe we can offload that to OrcID, so they can import our WBPersonIDs instead?

**Comment by sibyl229** [comment]
Hi @Paul-Davis I added the ORCID link in the highlight box in Person Overview. The display should work even if multiple ORCID ID entries are associated to a WBPerson. http://staging.wormbase.org/resources/person/WBPerson1983#045762--10 Thanks!

**Comment by Paul-Davis** [comment]
Thanks @sibyl229 looks good

**Comment by sibyl229** [comment]
Tested. Closing :)
