### ISSUE TITLE
  Hello, I'd like to edit my lab conten...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4559]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I'd like to edit my lab content, but I don't see how to do that. Could you please let me know how I can edit the lab information for ECA?<br/>Thanks,<br/>Erik</p>

**Reported by:** Erik********* (erik*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by tuli** [comment]
Dear Eric,

Thank you for writing to WormBase.

You can tell us about changes in your contact details via the Person Update
form: http://www.wormbase.org/submissions/person.cgi

Thank you,

Mary Ann

On 6 February 2016 at 08:14, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Hello, I'd like to edit my lab content, but I don't see how to do that.
> Could you please let me know how I can edit the lab information for ECA?
> Thanks,
> Erik
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4559. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4559>.
>
> Reported by: Erik Andersen (erik.andersen@gmail.com)
> 06 Feb 16 16:14
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4
> (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Mary Ann,

Thank you for your quick responses.

My contact details associated with me are fine. The problem is the lab
website for ECA is not correct. Also, I'm missing some lab members. I can
have them add themselves to the lab, but I would like to get the lab
website for ECA corrected. It should be www.andersenlab.org

Please let me know how to change that.

Thanks,
Erik

**Comment by tuli** [comment]
Dear Erik,

I've updated your lab URL. You'll see it in release WS253 of WormBase.

Mary Ann

ps sorry I misspelt your name in my last message.



On 6 February 2016 at 08:25, Erik Andersen <erik.andersen@gmail.com> wrote:

>
> Hi Mary Ann,
>
> Thank you for your quick responses.
>
> My contact details associated with me are fine. The problem is the lab
> website for ECA is not correct. Also, I'm missing some lab members. I can
> have them add themselves to the lab, but I would like to get the lab
> website for ECA corrected. It should be www.andersenlab.org
>
> Please let me know how to change that.
>
> Thanks,
> Erik
>
> On Sat, Feb 6, 2016 at 10:24 AM, Mary Ann Tuli <maryann.tuli@wormbase.org>
> wrote:
>
>> Dear Eric,
>>
>> Thank you for writing to WormBase.
>>
>> You can tell us about changes in your contact details via the Person
>> Update form: http://www.wormbase.org/submissions/person.cgi
>>
>> Thank you,
>>
>> Mary Ann
>>
>> On 6 February 2016 at 08:14, <no-reply@wormbase.org> wrote:
>>
>>> How Do I ...?
>>>
>>>   Hello, I'd like to edit my lab content, but I don't see how to do
>>> that. Could you please let me know how I can edit the lab information for
>>> ECA?
>>> Thanks,
>>> Erik
>>>
>>> Submitted From:
>>>   support /tools/support <http://www.wormbase.org//tools/support>
>>>
>>> This issue has been assigned ticket number: #4559. Follow progress on
>>> our issue tracker <https://github.com/WormBase/website/issues/4559>.
>>>
>>> Reported by: Erik Andersen (erik.andersen@gmail.com)
>>> 06 Feb 16 16:14
>>>
>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4
>>> (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
>>>
>>> This question was reported via the web interface at wormbase.org. You
>>> can also email us <help@wormbase.org> directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the "WormBase:
>>> help" group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>>
>>
>>
>> --
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>>
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Thank you! We'll look for the update.

Erik

**Comment by tuli** [comment]
Dear Eric:

I have assigned WBPerson ids to people from your lab that are not currently
registered in WormBase and linked them to your lab in Person page.

I have updated Tyler Shimko as alumni.

Updates will appear in WS253 release of WormBase.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule#01--10

Mary Ann: Please update in lab class.

Have a great day!
Cecilia

**Comment by scottcain** [comment]
@tuli can this be closed?
