### ISSUE TITLE
  Hi, in wormine, if I have a list of g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4563]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, in wormine, if I have a list of genes, is there any way to download the phenotype information entries for the entire list?  If I go to manage columns and select Phenotype>NAME, or any of the other offerings there, I get a message saying that  "this query returned 0 results".   This doesn't happen when I do the same thing for Ontologies, but I'd like to get some actual phenotypic data.</p>

**Reported by:** Jose** (jose******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by chris-grove** [comment]
Contacted user, sent instructions. Closing, will reopen if necessary.
