### ISSUE TITLE
Hi, there used to be in worm base a page where we ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4564]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, there used to be in worm base a page where we could see graphically the ESTs 5`and 3`aligned to the gene so that it was easy to select full length cDNAs. Where is this page now, if still accessible? thanks a lot,
visitor_name

**Reported by:** Moni** (moni*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004143#0b-9cdf82e64hi1g-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00004143#0b-9cdf82e64hi1g-10</a>
**Browser:** Safari 9.0.1

**Comment by Paul-Davis** [comment]
Dear Monica,

This data can be accessed on the "Reagents" widget but is better 
visualised on the WormBase genome browser.

 From the gene page you submitted this ticket from if you browse to the 
"Location" widget

http://www.wormbase.org/species/c_elegans/gene/WBGene00004143#-90d-10

and click on the "Genomic position: I:379073..381902 
<http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758?name=I:378507..382071>" 
link

You are taken to the correct location on the genome, now you can select 
the ESTs (best) track (I have configured the track to be expanded and 
labelled).

www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?start=379073;stop=381902;ref=I;width=800;version=100;flip=0;grid=1;id=5bae777fee9d49f0e0caf3aeef9f75d9;l=GENES%1EEST_BEST%1EORFEOME_SEQUENCE_TAGS%1EMRNA_BEST%1ECLONES%1ELOCI%3Aoverview

There are a lot of ESTs for this gene so the track is quite large.

Hope this helps.

Paul




On 09/02/2016 09:29, no-reply@wormbase.org wrote:
> offline chat Hi, there used to be in worm base a page where we could 
> see graphically the ESTs 5`and 3`aligned to the gene so that it was 
> easy to select full length cDNAs. Where is this page now, if still 
> accessible? thanks a lot, Monica
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00004143#0b-9cdf82e64hi1g-10 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00004143#0b-9cdf82e64hi1g-10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004143#0b-9cdf82e64hi1g-10> 
>
>
> This issue has been assigned ticket number: #4564. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4564>.
>
> Reported by: Monica (monica.gotta@unige.ch)
> 09 Feb 16 09:30
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Thanks a lot for your quick reply!

Monica
-------------------------------------------------------
Monica Gotta
CMU
PHYM Department
1, Rue Michel Servet
1211 Geneva 4
Switzerland
