### ISSUE TITLE
  how do you sign up as a worm research...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4565]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do you sign up as a worm researcher and register as part of a lab?<br/>thanks.</p>

**Reported by:** Stef************* (stef***********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by tuli** [comment]
Dear Stefan,

Thank you for writing to WormBase.

You were added as a member of the Andersen lab in release WS252 of
WormBase. This will be publicly available at the beginning of March, but
you can see the connection on our development site here:
http://staging.wormbase.org/resources/person/WBPerson31857

Please let us know if there are further updates to make.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
