### ISSUE TITLE
  Hello to the wormbase team, I am plyi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4567]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello to the wormbase team,<br/>I am plying a bit with WormMine  with the hope it will help me to collect all the RNAi phenotype  of a list of genes of interest. I made a list of these genes (11 in total) in wormmine but when I am trying to add a filter of "Observed Phenotypes" things get a bit unclear. <br/>Is there a way to do that in WormMine? <br/>I tired "Obsolete" and "Description" but it always gives me 0 results....<br/>I guess I am missing something but not sure what- can you guys help me to figure it out? <br/>Many thanks in advance,<br/>Amir </p>

**Reported by:** Amir****** (amir****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by chris-grove** [comment]
Hi Amir,


 RNAi phenotypes are not in WormMine currently, but are expected to be there in the next release.


Only allele-based phenotypes are in WormMine now, so you'll need to pull out observed phenotypes from under the Allele section of columns using the Manage Columns tool. Try importing this query XML via the "Import query from XML" option on the QueryBuilder tab:

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.alleles.symbol Gene.alleles.phenotypesObserved.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="Gene list for all organisms 28 Jan 2016 15.6"/>
</query>
```

change the constraint list to your list and you should see all genes and any alleles that have phenotypes observed.


Best,


Chris
