### ISSUE TITLE
In the Carolina Biological RNAi kit, it asks us to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4568]
*Help Desk query collected when no chat operators were online. Follow up required.*

In the Carolina Biological RNAi kit, it asks us to look under the Phenotype section for information on the dpy-1 allele in C. elegans.  I am not finding this allele.  Please advise.  Thank you.

**Reported by:** chan*** (Chan********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0123456789abcdefg--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0123456789abcdefg--10</a>
**Browser:** Microsoft Internet Explorer 10.0

**Comment by epaule** [comment]
isn't it dpy-11 and bli-1 ?

In any case, you can just type the name into the search box on the top right, and as both have cloned genes, you can see the observed phenotypes on the page.
