### ISSUE TITLE
  how to make solid dietary restriction...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4570]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how to make solid dietary restriction plate for c.elegans ?</p><p>What were you doing? <br />&nbsp;&nbsp;Master Degree Student</p>

**Reported by:** Indr********** (moda************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36

**Comment by epaule** [comment]
we do more the bioinformatic side of C.elegans research at WormBase than wet lab work.
But you can find some articles on lab methods at wormbook.org as well as forums.wormbase.org
