### ISSUE TITLE
visitor_name (visitor_email): Oops - I seem to hav...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4573]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Oops - I seem to have lost you Chris</br>Chris: Oh, no problem</br>Chris: I'm here</br>visitor_name (visitor_email): ah cool</br>visitor_name (visitor_email): i'll have a look at the worm mine tutorial; i'm guessing it's pretty straight forward?</br>Chris: Yes, usually, but it seems something changed recently so I'm a bit thrown off</br>Chris: apologies for the delay</br>visitor_name (visitor_email): no worries at all</br>Chris: Here you go</br>Chris: &lt;query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.organism.species Gene.goAnnotation.ontologyTerm.name Gene.goAnnotation.ontologyTerm.namespace Gene.transcripts.method" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B and C"&gt;
  &lt;constraint path="Gene.organism.species" code="A" op="=" value="elegans"/&gt;
  &lt;constraint path="Gene.goAnnotation.ontologyTerm.namespace" code="B" op="=" value="cellular_component"/&gt;
  &lt;constraint path="Gene.transcripts.method" code="C" op="=" value="Coding_transcript"/&gt;
&lt;/query&gt;</br>Chris: you can just copy and paste that into the "Import query from XML" link on the QueryBuilder tab of WormMine (which itself is available under the Tools menu)</br>Chris: Then click on "Show results" on the resulting QueryBuilder page</br>Chris: You can download in a number of formats</br>Chris: Also, you learn a bit about WormMine by exploring the query construction in the Query Overview at the right and the Model Browser tree to the left</br>visitor_name (visitor_email): nice; works like a charm!</br>Chris: great!</br>visitor_name (visitor_email): i'm guessing this is based on the latest WB release of the genome?</br>Chris: if you have any questions about WormMine let me know</br>Chris: yes</br>Chris: Our WS250 release</br>Chris: is there anything else I can help with?</br>Chris: feel free to email me any questions at cgrove@caltech.edu</br>visitor_name (visitor_email): nope; it's just that; thanks! I'll have a quick look at WS250 to see how many coding transcripts are estimated</br>visitor_name (visitor_email): thanks loads Chris - you're a star!</br>Chris: Cool, sounds good. Thanks visitor_name!</br>Chris: Take care</br>visitor_name (visitor_email): thanks, you too!

**Reported by:** Vikr** (vikr*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00012750#01cg4-9f67b3j-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00012750#01cg4-9f67b3j-3</a>
**Browser:** Chrome 43.0.2357.134

**Comment by Paul-Davis** [comment]
Closing and the other half of the conversation in Issue #4572
