### ISSUE TITLE
Hi, I think that gene F01D4.9 is orthologous to hu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4574]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I think that gene F01D4.9 is orthologous to human B4GA1, which has been shown to have β-1,4-glucuronyltransferase activity (not N-acetyllactosaminide beta-1,3-N-acetylglucosaminyltransferase).
See this paper: PMID:
    25279697
Regards,
Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10</a>
**Browser:** Firefox 38.0

**Comment by Paul-Davis** [comment]
Thanks Avril,

The current description we have states " F01D4.9 is predicted to have 
N-acetyllactosaminide beta-1 
<http://www.wormbase.org/search/gene/beta-1>,3-N-acetylglucosaminyltransferase 
activity, based on protein domain information.*Date last updated*: 
2015-9-22" So I'm sure the curators will be happy to take a look.

Paul

On 11/02/2016 10:45, no-reply@wormbase.org wrote:
> offline chat Hi, I think that gene F01D4.9 is orthologous to human 
> B4GA1, which has been shown to have β-1,4-glucuronyltransferase 
> activity (not N-acetyllactosaminide 
> beta-1,3-N-acetylglucosaminyltransferase). See this paper: PMID: 
> 25279697 Regards, Avril
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10> 
>
>
> This issue has been assigned ticket number: #4574. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4574>.
>
> Reported by: Avril Coghlan (alc@sanger.ac.uk)
> 11 Feb 16 10:47
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Avril,

This assignment has come from a GO annotation assigned by InterPro.
Specifically, the protein has a PTHR19297:SF78 domain from Panther (
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR19297:SF78),
which has been integrated into InterPro entry IPR026603 (
http://www.ebi.ac.uk/interpro/entry/IPR026603), which in turn has been
associated with GO term GO:0008532 N-acetyllactosaminide
beta-1,3-N-acetylglucosaminyltransferase activity.

What exactly in this chain is incorrect, in your opinion?

Kevin

**Comment by Paul-Davis** [comment]
Dear Kevin, 

I think that the InterPro domain is indicating a particular glycosyl
transferase activity with a particular substrate
(β-1,3-N-acetylglucosaminyltransferase with catalytic activity towards
β-galactose). However, I'm guessing that the set of seed proteins used
to build the InterPro domain had this activity/substrate, but there may
be proteins that have this domain but have a slightly different
activity/substrate and the InterPro curators didn't realise that. 

The human ortholog (B4GAT1, which also has the same InterPro domain) has
been shown to have a slightly different activity/substrate (a
β-1,4-glucuronyltransferase towards both α- and β-anomers of xylose),
despite having that domain PMID: 25279697. In our 50HG compara database,
we see 8 C. elegans orthologs of that human gene (I can give you the
list if you want), one of which is F01D4.9. I guess it's possible that
one or more of the C. elegans orthologs don't have the same activity as
its human ortholog. But it might be worth noting on the wormbase page
that the human ortholog has this activity, if you think that would be
useful for users to know? 

Regards, 

Avril 

On 2016-02-11 11:08, Kevin Howe wrote: 

> Hi Avril, 
> 
> This assignment has come from a GO annotation assigned by InterPro. Specifically, the protein has a PTHR19297:SF78 domain from Panther (http://www.pantherdb.org/panther/family.do?clsAccession=PTHR19297:SF78 [1]), which has been integrated into InterPro entry IPR026603 (http://www.ebi.ac.uk/interpro/entry/IPR026603 [2]), which in turn has been associated with GO term GO:0008532 N-acetyllactosaminide beta-1,3-N-acetylglucosaminyltransferase activity. 
> 
> What exactly in this chain is incorrect, in your opinion? 
> 
> Kevin 
> 
> On 11 February 2016 at 11:06, Paul Davis <paul.davis@wormbase.org> wrote:
> 
> Thanks Avril,
> 
> The current description we have states " F01D4.9 is predicted to have N-acetyllactosaminide beta-1 [3],3-N-acetylglucosaminyltransferase activity, based on protein domain information. DATE LAST UPDATED: 2015-9-22" So I'm sure the curators will be happy to take a look.
> 
> Paul 
> 
> On 11/02/2016 10:45, no-reply@wormbase.org wrote: 
> 
> offline chat Hi, I think that gene F01D4.9 is orthologous to human B4GA1, which has been shown to have β-1,4-glucuronyltransferase activity (not N-acetyllactosaminide beta-1,3-N-acetylglucosaminyltransferase). See this paper: PMID: 25279697 Regards, Avril 
> 
> Submitted From: 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10 [4] http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10 [5] 
> 
> This issue has been assigned ticket number: #4574. Follow progress on our issue tracker [6]. 
> 
> Reported by: Avril Coghlan (alc@sanger.ac.uk) 
> 11 Feb 16 10:47 
> 
> This question was reported via the web interface at wormbase.org [7]. You can also email us directly. -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en [8]
> 
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom 
> ===========================================
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en [8]

 

Links:
------
[1]
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR19297:SF78
[2] http://www.ebi.ac.uk/interpro/entry/IPR026603
[3] http://www.wormbase.org/search/gene/beta-1
[4]
http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10
[5]
http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008491#0f-9e63bg1c-10
[6] https://github.com/WormBase/website/issues/4574
[7] http://wormbase.org
[8] http://groups.google.com/a/wormbase.org/group/help?hl=en



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by Paul-Davis** [comment]
Hi Avril,

I see. I'll leave it to our Caltech incorporate this in to our gene summary
paragraph. But since the InterPro annotation seems to be the underlying
problem here, perhaps you might also want to report the issue to them?

Best,

Kevin

**Comment by Paul-Davis** [comment]
Hi Avril
Thanks for your comments. I’d like to step back a bit and describe how this works—we’ve stopped writing manual descriptions for genes due to shortages in staff and time, and as you probably know, we’ve implemented an automatic pipeline to generate gene summaries based on whatever data is already in WormBase. We'd rather not make manual edits to the automatically generated gene descriptions as these get overwritten with whatever data is in WormBase for the next release. 

If you have expert knowledge about this C. elegans gene, we would really like you to contribute this via our gene description submission form:

http://www.wormbase.org/submissions/community_gene_description.cgi

This form will show you what description WormBase has for the gene of interest and then allow you to edit it.  Please remember to enter the proper evidences.

I think we are going to soon move towards a model in WormBase where we display the automated description which is based on certain core data in WormBase, as well as edits made by experts in the field.

Thanks very much
Ranjana Kishore

**Comment by vanaukenk** [comment]
Hi,
Just wanted to add that there is a specific github tracker GO uses to communicate potential InterPro2GO mapping issues here:
https://github.com/geneontology/go-annotation/issues
Avril, if you haven't already alerted InterPro, this is a good place to add your comments about the existing mapping.
Best,
--Kimberly

**Comment by raymond91125** [comment]
NOP? (not our problem) 8-)
