### ISSUE TITLE
Hi, 
Just letting you know that the hyperlink give...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4577]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, 
Just letting you know that the hyperlink given for the V4R embryonic right side seam cell leads to the overview of V3R.

**Reported by:** Will********** (will******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/anatomy_term/WBbt:0004876#01--10">http://www.wormbase.org/species/all/anatomy_term/WBbt:0004876#01--10</a>
**Browser:** Chrome 48.0.2564.103

**Comment by raymond91125** [comment]
Hi William,

Thanks for the note. However, I can't seem to figure out which hyperlink 
you're referring to. Is it possible that you can send us a screen shot 
of the problem?

Thanks.

Raymond


On 02/11/2016 10:56 AM, no-reply@wormbase.org wrote:
> Just letting you know that the hyperlink give... (William Duncan)
> Content-type: text/html; charset="utf-8"
> Date: Thu, 11 Feb 2016 18:58:32 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>     
>                                                                                       <style type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat Hi,
> Just letting you know that the hyperlink given for the V4R embryonic right side seam cell leads to the overview of V3R.  <p>Submitted From:
> <br>&nbsp;&nbsp;http://www.wormbase.org/species/all/anatomy_term/WBbt:0004876#01--10 <a href="http://www.wormbase.org/http://www.wormbase.org/species/all/anatomy_term/WBbt:0004876#01--10">http://www.wormbase.org/species/all/anatomy_term/WBbt:0004876#01--10</a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4577. Follow progress on our <a href="https://github.com/WormBase/website/issues/4577">issue tracker</a>.
> <p>
>
> <p>
> Reported by: William Duncan (william.duncan@nih.gov) <br />
> <span class="fade">11 Feb 16 18:58 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by chris-grove** [comment]
Issue is with a WormAtlas link. Emailed WormAtlas to let them know.
