### ISSUE TITLE
  I teach a genomics class and when I i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4581]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I teach a genomics class and when I introduce biomart, I like to have students connect to wormbase in addition to ensembl.<br/>Since Worm Mart is retired, is this possible? Could this be done through Worm Mine?</p><p>What were you doing? <br />&nbsp;&nbsp;Here are my unsuccessful R commands.

wormbase = useMart("WS251",dataset="wormbase_gene", host = "http://www.wormbase.org")

wormbase = useMart("WS250",dataset="wormbase_gene", host = "http://im-dev.wormbase.org/")
Request to BioMart web service failed. Verify if you are still connected to the internet.  Alternatively the BioMart web service is temporarily down.  Check http://www.biomart.org and verify if this website is available.
Error: XML content does not seem to be XML: </p>

**Reported by:** Bob ******* (less***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36

**Comment by epaule** [comment]
the user has been redirected to an alternative BioMart
