### ISSUE TITLE
How do I find the FASTA sequence for a gene I am l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4584]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I find the FASTA sequence for a gene I am looking at?

**Reported by:** Maya****** (mtma***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#b1a762ed59c8403--10">http://www.wormbase.org/about/Frequently_asked_questions#b1a762ed59c8403--10</a>
**Browser:** Chrome 48.0.2564.109

**Comment by scottcain** [comment]
I believe this is a suitable answer:

For each gene, there will be an option "Sequences" on the left panel.  If that isn't already turned on in your display, click it to open the Sequences panel.  In that panel there generally be one or more links to the transcript pages for that gene.  Click on the one you want, and it will take you to a new page for the transcript.  Again on the left hand side there is the "Sequences" option; click to turn it on if it's not already.  In the Sequences panel on the right there will generally be several options for getting the sequence you want, like spliced, unspliced or AA translation.  Please let us know if you need any more help with this.
