### ISSUE TITLE
  The meetings widget on the front page...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4585]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The meetings widget on the front page is missing a title.  Should it be something like "Meetings", or "Announcements"</p>

**Reported by:** Kare****** (kare**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by raymond91125** [comment]
@chris-grove added the title.
