### ISSUE TITLE
  download information for recording  t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4589]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;download information for recording  targets of C elegasn RNAi. <br/>Say, given a C elegasn RNAi, whether it targets one or multiple targets?</p>

**Reported by:** Tian (isut*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by raymond91125** [comment]
Hello Tian,


 We don't have an official tool to do this, but I've written a script that processes a file from our FTP site to list all genes targeted for a given RNAi ID. I've attached a compressed/zipped directory containing the script "RNAi_list_to_gene_mapping.py", a sample input file "RNAi_list.txt" and the file from our FTP site "rnai_phenotypes.WS251.wb". This last file can, for future releases, be download from:


ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/


where "WS251" will be replaced by subsequent releases of WormBase, e.g. WS252, WS253, etc.


You can run the script using Python from the command line, like this "$ python RNAi_list_to_gene_mapping.py" and it will take all RNAi IDs from your input file and list all RNAi IDs with their corresponding targeted genes. Keep in mind this includes both "primary" and "secondary targets". "Primary targets" are those genes that have greater than 90% sequence identity over 100bp compared to the dsRNA sequence and "secondary targets" are those genes that have greater than 80-90% sequence identity over 200bp compared to the dsRNA sequence.


Let us know if you have any questions.


Best,

Chris Grove

WormBase
