### ISSUE TITLE
  How can I download the FPKM value of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4594]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I download the FPKM value of all genes in all stages of modENCODE Integrative analysis (RNASeq_Study.SRP000401, Gerstein 2010). Thank you very much!</p>

**Reported by:** Xiao******* (sdum*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36

**Comment by gw3** [comment]
You can download this as a CSV file from:

ftp://caltech.wormbase.org/pub/wormbase/spell_download/datasets/WBPaper00037953.ce.rs.csv

Gary Williams
