### ISSUE TITLE
The cmk-1(oy20) mutant is listed as a nonsense all...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4596]
*Help Desk query collected when no chat operators were online. Follow up required.*

The cmk-1(oy20) mutant is listed as a nonsense allele on Wormbase but as a missense allele in the paper from the Sengupta lab, which is correct?

CaMKI-Dependent Regulation of Sensory Gene Expression Mediates Experience-Dependent Plasticity in the Operating Range of a Thermosensory Neuron
Yanxun V. Yu,1,2,5 Harold W. Bell,1,2,5 Dominique A. Glauser,3 Stephen D. Van Hooser,2 Miriam B. Goodman,4 and Piali Sengupta1,2,*

**Reported by:** Step*********** (nurr**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000553#09gf4-61dbce-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000553#09gf4-61dbce-10</a>
**Browser:** Firefox 44.0

**Comment by raymond91125** [comment]
Hello Stephen,


Our automated pipeline predicted this to be nonsense allele. Looking more closely at the current transcript information, this appears to be correct. It's possible that there has been a gene model change since the publication. Our variation and/or sequence curators will be able to provide you with more details on Monday.


Best,

Chris Grove

**Comment by raymond91125** [comment]
@tuli The original paper <http://www.sciencedirect.com/science/article/pii/S0960982203009503> says in Fig2B, G31->E. That would imply GGA->GAA, instead of GGA->TGA

**Comment by gw3** [comment]
There has been no gene model change. The structure looks good.

**Comment by chris-grove** [comment]
@gw3  Can you see a reason for the discrepancy between the published effects of the allele (G to E) and the WormBase predicted effects (G to OPAL)?

**Comment by tuli** [comment]
It's more than likely a citation mistake by the allele curator.....that'll
be me then!

On Monday, 22 February 2016, Chris Grove <notifications@github.com> wrote:

> @gw3 <https://github.com/gw3> Can you see a reason for the discrepancy
> between the published effects of the allele (G to E) and the WormBase
> predicted effects (G to OPAL)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4596#issuecomment-187401680>.
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by chris-grove** [comment]
@tuli  I'm not so sure. The original 2004 paper has a figure (Figure 2B) depicting oy20 as a G->E transition at amino acid 31:
![screen shot 2016-02-22 at 3 56 51 pm](https://cloud.githubusercontent.com/assets/611382/13236985/f92e2ed0-d97c-11e5-9513-af349ecec496.png)

**Comment by tuli** [comment]
Dear Stephen,

Thank you for writing to WormBase. I apologise that it has taken me a
few days to address the issue you raise.

You are quite right, oy20 is incorrectly described in WormBase.

I have updated the curation which will now show that oy20 is a g to a
substitution resulting in a G(31)E mutation. This update will be
available in release WS254 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Exactly...what we have in WormBase is wrong.

All fixed now.



On 22 February 2016 at 23:57, Chris Grove <notifications@github.com> wrote:

> @tuli <https://github.com/tuli> I'm not so sure. The original 2004 paper
> has a figure (Figure 2B) depicting oy20 as a G->E transition at amino acid
> 31:
> [image: screen shot 2016-02-22 at 3 56 51 pm]
> <https://cloud.githubusercontent.com/assets/611382/13236985/f92e2ed0-d97c-11e5-9513-af349ecec496.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4596#issuecomment-187443573>.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
