### ISSUE TITLE
  How do I submit my reagents to your R...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4602]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I submit my reagents to your Resources page (http://www.wormbase.org/resources/reagents#231450--10)?<br/>Dear Wormbase Team, <br/>I saw you listed some organisations' reagents on page http://www.wormbase.org/resources/reagents#231450--10, such as <br/>Affymetrix<br/>Agilent<br/>under Microarrays. By checking the link, I found the info has outdated (become 404 page), and my Company, Creative Biomart (http://www.creativebiomart.net/) just has corresponding resources, how can I submit our info to you? <br/>Best,<br/>Dynah Lopez<br/>Creative Biomart</p>

**Reported by:** cont***************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36

**Comment by raymond91125** [comment]
Hi Dynah,

Thanks for your inquiry in our services. Our resources/reagents 
collection is presently rather limited to C. elegans/Nematode-specific 
reagents that are of defined interests to our users. When we expand this 
section to include a more general collection of services, we surely will 
be sending your company an invitation.

Best,

Raymond

**Comment by raymond91125** [comment]
Hi Raymond,

Thank you.

Best,
Dynah Lopez

On Tue, Feb 23, 2016 at 12:41 PM, Raymond Lee <raymond@caltech.edu> wrote:

> Hi Dynah,
>
> Thanks for your inquiry in our services. Our resources/reagents collection
> is presently rather limited to C. elegans/Nematode-specific reagents that
> are of defined interests to our users. When we expand this section to
> include a more general collection of services, we surely will be sending
> your company an invitation.
>
> Best,
>
> Raymond
>
>
>
> On 02/22/2016 07:31 PM, no-reply@wormbase.org wrote:
>
> How Do I ...?
>
>   How do I submit my reagents to your Resources page (
> http://www.wormbase.org/resources/reagents#231450--10)?
> Dear Wormbase Team,
> I saw you listed some organisations' reagents on page
> http://www.wormbase.org/resources/reagents#231450--10, such as
> Affymetrix
> Agilent
> under Microarrays. By checking the link, I found the info has outdated
> (become 404 page), and my Company, Creative Biomart (
> http://www.creativebiomart.net/) just has corresponding resources, how
> can I submit our info to you?
> Best,
> Dynah Lopez
> Creative Biomart
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4602. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4602>.
>
> Reported by: contact@creative-proteomics.com
> 23 Feb 16 03:34
>
> Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/48.0.2564.103 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google Groups
> "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to help+unsubscribe@wormbase.org.
>
>
>


-- 

CONFIDENTIALITY NOTICE: This e-mail, including any previous messages and/or
files attached to it, is private, confidential, and solely for the use of
the intended recipient(s) and corresponding intentions.  Any review,
retransmission, dissemination, reproduction or other use of, or taking of
any action in reliance upon, this information by persons or entities other
than the intended recipient(s), or by a person responsible for delivering
it to the intended recipient(s), is unauthorized and strictly prohibited.
