### ISSUE TITLE
Hi, I am a Ph.D. student from Tel Aviv University....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4603]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I am a Ph.D. student from Tel Aviv University. I would like to order the clone WRM0621bE04. I have gone through wormbase. It will be greatly helpful if you could guide me the correct method for it.
Thanking you,
Asha Raju

**Reported by:** ASHA***** (asha*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/clone/WRM0621bE04#02--10">https://www.wormbase.org/species/c_elegans/clone/WRM0621bE04#02--10</a>
**Browser:** Chrome 48.0.2564.116

**Comment by chris-grove** [comment]
Hello Asha,


 I would recommend looking at the WormBase reagent page:


http://www.wormbase.org/resources/reagents#204513--10

From there you can find several links to various resources from which you can order the clones you are looking for. Let us know if you need further assistance.


Best,


Chris Grove

WormBase
