### ISSUE TITLE
  Hi, I am a Ph.D. student from Tel Avi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4604]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am a Ph.D. student from Tel Aviv University. I would like to order few clones: F15E6 as well as WRM0621bE04. It will be greatly helpful if you could suggest me the correct way to do the same.<br/>Thanking you<br/>Asha Raju<br/>Ph.D. student <br/>Tel Aviv University</p><p>What were you doing? <br />&nbsp;&nbsp;Ph.D. student 
Tel Aviv University</p>

**Reported by:** ASHA***** (asha*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by raymond91125** [comment]
Hello Asha,


 I would recommend looking at the WormBase reagent page:


http://www.wormbase.org/resources/reagents#204513--10

From there you can find several links to various resources from which you can order the clones you are looking for. Let us know if you need further assistance.


Best,


Chris Grove

WormBase
