### ISSUE TITLE
  Hello, how do I get a list of all the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4605]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, how do I get a list of all the alternatively spliced genes in C. elegans? Or, is there a program that we could run to identify genes that are alternatively spliced?<br/>Thank you, Noelle </p>

**Reported by:** Noel*********** (noel*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by raymond91125** [comment]
Hi Noelle,

I don't believe we have a ready list or tool to generate such list. 
Although the transcript file (e.g. 
ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS252.mRNA_transcripts.fa.gz) 
includes what we think are alternative transcripts.

Let us know if you need more information.

Best regards,

Raymond



On 02/23/2016 01:47 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello, how do I get a list of all the alternatively spliced genes in 
> C. elegans? Or, is there a program that we could run to identify genes 
> that are alternatively spliced?
> Thank you, Noelle
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4605. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4605>.
>
> Reported by: Noelle L'Etoile (noelle.letoile@ucsf.edu)
> 23 Feb 16 21:48
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 
> (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Noelle,

All of the CDS structures that are alternately spliced have a letter at 
the end of their ID.
A quick way to get most of these is to go to WormMine (from the Tools 
menu in WormBase),
then click on "CDS -> Gene and Protein"
then in the field under "CDS > Sequence Name" enter:
*a
and click on the green "Show results" button.

There may be a few Genes which lack a CDS having a name that ends in 'a'.
you should maybe try searching for '*b' and '*c' as well if you wish to 
be thorough.

Gary Williams
