### ISSUE TITLE
  I want to know how to filter out the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4610]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to know how to filter out the RNAi phenotypes on wormmine platform?  there are too much  different between wormmine and wormmart，i know how to do in wormmart， but   it was not available to now.  thanks!</p>

**Reported by:** Peng*** (hpen************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by raymond91125** [comment]
Hi Penghua,

Actually at the moment, WormMine does not have RNAi data. All the 
gene->phenotype information is from mutant alleles. We plan to add RNAi 
data.

In case you haven't explored it, there is a template for Genes- -> 
Phenotypes on WormMine front page under the Tab "PHENOTYPES". The 
example is for unc-26 but you can import a list of genes and use the 
gene list in place of unc-26 in the query.

Let us know if you have more questions.

Best regards,

Raymond


On 02/24/2016 01:04 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I want to know how to filter out the RNAi phenotypes on wormmine 
> platform? there are too much different between wormmine and 
> wormmart，i know how to do in wormmart， but it was not available to 
> now. thanks!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4610. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4610>.
>
> Reported by: Penghua (hpeng@ippcaas.cn)
> 24 Feb 16 09:05
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/31.0.1650.63 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
