### ISSUE TITLE
  I found out that the wrong atg is ann...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4611]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I found out that the wrong atg is annotated for the myosin gene hum-2. I was not sure where to submit this info on wormbase. Please tell me which form to use if you prefer me to submit this info online.<br/>I was trying to clone hum-2a/b from the atg onwards but was not successful. Checking the protein alignment to other worms I found that the N-terminus is completely different although the rest is very similar. Taking out the 8bp Exon2 in splice variant a or b puts another atg in frame (at bp77 of the current splice variant) and makes the N-terminus similar to the other worm sequences. Additionally this small Exon2 was not identified by RNAseq (on wormbase). Cloning from this new atg now works fine for me, which I also described in the suplementals of Harterink et al. (current biology, 2016).<br/>Best Regards, <br/>visitor_name Harterink<br/>Hoogenraad lab<br/>Utrecht University<br/>The Netherlands</p>

**Reported by:** Mart** (m.ha*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by Paul-Davis** [comment]
Dear Martin,

Thank you for submitting your findings, unfortunately there was a 
published mRNA in 1996 that appears to be erroneous and contained this 
small exon (2). Looking at all other sequence and protein data it is 
clear that we should be ignoring this old mRNA. I have corrected the 
annotation which will appear in WS254.

Paul


On 24/02/2016 12:22, no-reply@wormbase.org wrote:
> Content Correction
>
>   I found out that the wrong atg is annotated for the myosin gene 
> hum-2. I was not sure where to submit this info on wormbase. Please 
> tell me which form to use if you prefer me to submit this info online.
> I was trying to clone hum-2a/b from the atg onwards but was not 
> successful. Checking the protein alignment to other worms I found that 
> the N-terminus is completely different although the rest is very 
> similar. Taking out the 8bp Exon2 in splice variant a or b puts 
> another atg in frame (at bp77 of the current splice variant) and makes 
> the N-terminus similar to the other worm sequences. Additionally this 
> small Exon2 was not identified by RNAseq (on wormbase). Cloning from 
> this new atg now works fine for me, which I also described in the 
> suplementals of Harterink et al. (current biology, 2016).
> Best Regards,
> Martin Harterink
> Hoogenraad lab
> Utrecht University
> The Netherlands
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4611. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4611>.
>
> Reported by: Martin (m.harterink@uu.nl)
> 24 Feb 16 12:22
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by epaule** [comment]
fixed it in B.malayi too ;-)
