### ISSUE TITLE
  I have a question about annotation of...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4612]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a question about annotation of gene structure. Based upon RNAseq and RNAseq asymmetry data, K07B1.7 appears to have only one isoform but it is annotated to have two isoforms. How was the structure of this gene determined?</p>

**Reported by:** Dori***** (dlui*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by gw3** [comment]
Yes, you are correct.
There should be only one coding isoform.
I will make the change and this will appear in release WS254.
There is evidence for retained introns in the second half of the locus, so I will make a non-coding transcript isoform as well.

So we will have the 'a' isoform as a coding isoform and the 'b' isoform as a non-coding isoform with retained introns.
