### ISSUE TITLE
  How can I remove a post on the wormba...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4613]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I remove a post on the wormbase help?</p>

**Reported by:** hype****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by raymond91125** [comment]
Which post and why, and I presume you mean from the help@wormbase.org mailing list archives?

Todd
