### ISSUE TITLE
  Hi, I'm having trouble finding the RN...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4615]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm having trouble finding the RNAi phenotypes.  Basically, I want to return a list of all genes with "extended life span" as a phenotype, but when I do the Phenotype->Gene query it looks like all I'm getting are the allele variants that have this phenotype.<br/>Is there a way to get the RNAi phenotypes. Trying to download them from the Wormbase phenotype page returns an error that the set is to large, and to use the ftp server.  But I can't find the folder in the ftp server.</p>

**Reported by:** jmz4 (yank*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by raymond91125** [comment]
Hi jmz4,

We plan to add RNAi data to WormMine. On the ftp, you can find RNAi 
phenotypes, for example, here 
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/ONTOLOGY/>.

For one-gene-at-a-time queries, one simple way is to go to the phenotype 
page with the Ontology Browser widget open 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000061#03--10>. 
To the right of the focus term, there are numbers indicating gene counts 
for direct and direct+inferred annotations. Clicking on the hypertext 
brings you to a page with four different lists of genes, two for RNAi 
and two for mutant analysis.

Let us know if you need more information.

Best regards,

Raymond


On 02/25/2016 09:19 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi, I'm having trouble finding the RNAi phenotypes. Basically, I 
> want to return a list of all genes with "extended life span" as a 
> phenotype, but when I do the Phenotype->Gene query it looks like all 
> I'm getting are the allele variants that have this phenotype.
> Is there a way to get the RNAi phenotypes. Trying to download them 
> from the Wormbase phenotype page returns an error that the set is to 
> large, and to use the ftp server. But I can't find the folder in the 
> ftp server.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4615. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4615>.
>
> Reported by: jmz4 (yanknerlab858@gmail.com)
> 25 Feb 16 17:22
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
