### ISSUE TITLE
How do you find the phenotypes chart on genes? I l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4619]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do you find the phenotypes chart on genes? I looked for the phenotypes on Bath-9. It showed up on my friend's Mac, but it wouldn't show up on anyone else's.

**Reported by:** jami* (jree***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/ontology_browser">http://www.wormbase.org/tools/ontology_browser</a>
**Browser:** Chrome 48.0.2564.109

**Comment by kyook** [comment]
Hi Jamie,

In general, you should be able to see phenotypes for a gene by opening the
Genetics widget, the Phenotypes widget, or the Phenotype Graph widget (all
in the left side bar menu). In the Genetics widget, you will need to sort
the table based on the Phenotype column.

Unfortunately, there are no observed phenotypes for bath-9. There are
however, reported phenotypes that were looked for but not observed.  You
can see these by opening the Phenotypes widget, then clicking on the arrow
after "Phenotypes not observed".

I hope this answers your question. I'm not exactly sure what you mean by
the "phenotype chart", so please get back to me if you need further help.

Best wishes,
Karen





~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, Feb 26, 2016 at 2:55 PM, <no-reply@wormbase.org> wrote:

> offline chat How do you find the phenotypes chart on genes? I looked for
> the phenotypes on Bath-9. It showed up on my friend's Mac, but it wouldn't
> show up on anyone else's.
>
> Submitted From:
>   http://www.wormbase.org/tools/ontology_browser
> http://www.wormbase.org/tools/ontology_browser
> <http://www.wormbase.org/http://www.wormbase.org/tools/ontology_browser>
>
> This issue has been assigned ticket number: #4619. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4619>.
>
> Reported by: jamie (jreed065@marian.edu)
> 26 Feb 16 22:58
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
