### ISSUE TITLE
  Hello, I was wondering if  I could ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4621]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I was wondering if  I could get help citing a page? I cannot find a way to cite a specific article using APA/ </p>

**Reported by:** Deni*** (deni*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by raymond91125** [comment]
Hi Denisse,

This page <http://www.wormbase.org/about/citing_wormbase#0123--10> may 
be helpful.

Cheers,

Raymond
