### ISSUE TITLE
GBrowse track description update "Trans-spliced acceptor"

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4624]
Hi, It seems that the track description needs an update as it is very out of date.

"Trans-spliced acceptor"

This track contains SL1 and SL2 trans-spliced acceptors from a variety of sources:
SL1 and SL2 trans-spliced acceptors published by Blumenthal et al, Nature (2002),
Trans-Spliced Exon Coupled RNA End Determination (TEC-RED) Hwang et al, PNAS (2004),
EST/mRNA sequence data,
RNASeq read data from ENA.
SL1 acceptors are show in red, SL2 in green. Direction of transcription is indicated by arrow direction.

**Comment by Paul-Davis** [comment]
I've made the changes in the staging branch, but can't get staging to test.

**Comment by scottcain** [comment]
That's because GBrowse on dev is running off of my checkout of the website repo.  I'll switch it back since I'm not touching GBrowse at nearly the rate a was a few months ago.

**Comment by Paul-Davis** [comment]
ah @scottcain that would explain things ;)

**Comment by Paul-Davis** [comment]
If no-one else has any objection can https://github.com/WormBase/website/commit/d03bd2efba85de259a6b064fb5abaa560fc8a51b be merged in?

**Comment by scottcain** [comment]
Hi @Paul-Davis I've already moved the change into the conf files for GBrowse for WS252 and JBrowse, both of which are live on staging (though I'm currently getting a 504 error making GBrowse difficult to test).  Since 252 will go live soon, I figured it could wait to update the production site rather than editing the configs for 251 right now.

**Comment by Paul-Davis** [comment]
Hey @scottcain Thanks, fine to wait for the change to push with WS252.

P
