### ISSUE TITLE
Worm Community Forum: SMF Database Error!

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#4626]
From WB help list:

There has been a problem with the database!

This is a notice email to let you know that SMF could not connect to the database, contact your host if this continues.

**Comment by vanaukenk** [comment]
Second notice came through on 2016-03-03:

There has been a problem with the database!

This is a notice email to let you know that SMF could not connect to the database, contact your host if this continues.

**Comment by tharris** [comment]
Transient issue related to database upgrades. Resolved.
