### ISSUE TITLE
Please display tree view data missing from molecule page

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4627]
There was a large model change in WS252 for the molecule class. It's time to work on displaying the new data available for this class.

Some sample pages to work with are 
http://staging.wormbase.org/resources/molecule/WBMol:00005495#0214356--10
http://staging.wormbase.org/resources/molecule/WBMol:00000001#0214356--10
http://staging.wormbase.org/resources/molecule/WBMol:00006108#0214356--10

**Comment by sibyl229** [comment]
Hi @kyook I guess the IUPAC, SMILES, InChi, InChiKey will go into the highlight box (the grey box in overview widget)? For the **other** fields, could you write a short tooltip description that will show up as tooltip when mouseover the field name? Thanks!

**Comment by kyook** [comment]
Sorry, I'm a bit confused. Do you want me to write a tooltip for the IUPAC,
SMILES etc. fields? Or are there other fields I should do this for.
There is also monoisotopic mass , etc, such as the data on this page:
http://staging.wormbase.org/resources/molecule/WBMol:00005131#025--10

Karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, May 6, 2016 at 1:17 PM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> I guess the IUPAC, SMILES, InChi,
> InChiKey will go into the highlight box (the grey box in overview widget)?
> For the *other* fields, could you write a short tooltip description that
> will show up as tooltip when mouseover the field name? Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-217547731>
>

**Comment by sibyl229** [comment]
@kyook Ah sorry, hmm, actually could you please do all of them? I just realized that they all use the tooltip if available. But if you think the name is self explanatory, I will just write "___ of the molecule".

**Comment by kyook** [comment]
no worries, I'll do them all (at least what would make sense)

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, May 6, 2016 at 2:40 PM, Sibyl G <notifications@github.com> wrote:

> @kyook <https://github.com/kyook> Ah sorry, hmm, actually could you
> please do all of them? I just realized that they all use the tooltip if
> available. But if you think the name is self explanatory, I will just write
> "___ of the molecule".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-217565326>
>

**Comment by kyook** [comment]
Hi @sibyl229 

I put together this wiki table for you to use to get tooltips for the molecule page tags. I hope it is easy enough to read. 
http://wiki.wormbase.org/index.php/Molecule#Molecule_page
Karen

**Comment by sibyl229** [comment]
Hi @kyook such a thorough table! Thank you so much! It's my first time seeing curation documentation, so impressed with the amount of detail and organization :)

**Comment by kyook** [comment]
I actually cut some out, I'm sorry to include so much, but if you have
questions, I need to be able to reference my internal tables.  Let me know
if it is too confusing.

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Wed, May 11, 2016 at 11:31 AM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> such a thorough table! Thank you so
> much! It's my first time seeing curation documentation, so impressed with
> the amount of detail and organization :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-218548600>
>

**Comment by sibyl229** [comment]
@kyook I don't think it's confusing. I can find the tooltip you wrote easily. I'm working on it right now, will probably have some questions for you tomorrow. Thanks!

**Comment by sibyl229** [comment]
Hi @kyook I added all the missing fields to molecule page, with the exception of Essential_for and Endogenous_in. I didn't find an example for Essential_for, but for Endogenous_in, the species identifier in tree display doesn't seem to links to actual species object. Here is an example: http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10 I think it intends to link to http://staging.wormbase.org/tools/tree/run?name=Caenorhabditis%20elegans;class=Species . Could you take a look please?

By the way I added the "on mouseover, expand image" ability to the structure image, as sometimes the image is too small to read. Hope it's okay.

**Comment by kyook** [comment]
hi @sibyl229, you are great!  Can all the things with evidence attached be put into a different widget as a table?  (Sorry, I know this doesn't address the question you asked).

**Comment by kyook** [comment]
Hi @sibyl229, yes the 6239 should be Caenorhabditis elegans, which is the name that should show up. I think this is a problem with my dumper.  So for now, it would be good to just not show that data until I can fix the dumper. It should be ready in the next upload.

**Comment by sibyl229** [comment]
Hi @kyook I think the group by evidence part seems a bit odd. I think users probably looks at the evidence **after** they considered the information. But to group information by evidence makes the grouping itself the first think they look at, seems contrary to people's browsing habit. What do you think?

Would a table with field names as headers, and content displaced in the cell underneath work? Basically, it would take what's displayed and lay them out horizontally. And which widget would you like to include the information? Thanks!

**Comment by kyook** [comment]
Hi @sibyl229, 

"Would a table with field names as headers, and content displaced in the cell underneath work? Basically, it would take what's displayed and lay them out horizontally."
Yes, this would be ideal, with each row in the table reporting information from one reference. 

"And which widget would you like to include the information?" -> can we make a new widget? 'Biological Role'

**Comment by sibyl229** [comment]
Hi @kyook is this table what you have in mind? So the fields that it includes will be Biofunction role, status, detection method and extraction method? 
![screen shot 2016-05-17 at 6 25 26 pm](https://cloud.githubusercontent.com/assets/1753893/15341454/c1b0d3f4-1c5c-11e6-96fd-6a8f85591cdb.png)

**Comment by kyook** [comment]
hi @sibyl229, yes, but the details should actually the the citation, which
should occur in its own column in the same row as these data -- something
like this table:


​Where the column headers would be Biofunction role, Status, Detection
method, Extraction method, Evidence (or citation, or reference)

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Tue, May 17, 2016 at 3:30 PM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> is this table what you have in mind?
> So the fields that it includes will be Biofunction role, status, detection
> method and extraction method?
> [image: screen shot 2016-05-17 at 6 25 26 pm]
> <https://cloud.githubusercontent.com/assets/1753893/15341454/c1b0d3f4-1c5c-11e6-96fd-6a8f85591cdb.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-219873794>
>

**Comment by sibyl229** [comment]
Hi @kyook I added an Evidence column (which accumulates all the paper evidence from the other columns). I kept the collapsible evidence associated with each field, because the evidence could contain other information in addition to the reference. ![screen shot 2016-05-18 at 12 58 42 pm](https://cloud.githubusercontent.com/assets/1753893/15367721/493c580c-1cf8-11e6-98ca-b1300930950e.png)  Is this okay?

**Comment by kyook** [comment]
There shouldn't be any other information associated with each field that
would be different from the evidence, so you should remove the collapsible
evidence in each field.

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Wed, May 18, 2016 at 10:39 AM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> I added an Evidence column (which
> accumulates all the paper evidence from the other columns). I kept the
> collapsible evidence associated with each field, because the evidence could
> contain other information in addition to the reference. [image: screen
> shot 2016-05-18 at 12 58 42 pm]
> <https://cloud.githubusercontent.com/assets/1753893/15367721/493c580c-1cf8-11e6-98ca-b1300930950e.png>
> Is this okay?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-220102659>
>

**Comment by sibyl229** [comment]
@kyook is this okay? http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10 I didn't create a separate widget for the table, because the overview widget seems relatively sparse right now, and can fit the table.

**Comment by kyook** [comment]
It would be better for the experimental results to be in their own widget
since only a fraction of the molecules have these data: ex.
http://staging.wormbase.org/resources/molecule/WBMol:00004937#056--10

I'm also concerned about the size of the grey window in the overview
widget, it gets expanded quite a bit by the structure codes and
identifiers,  maybe those can be in a table in the overview window under
the image?  Would that fill out the overview widget better?


~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Wed, May 18, 2016 at 1:48 PM, Sibyl G <notifications@github.com> wrote:

> @kyook <https://github.com/kyook> is this okay?
> http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10 I
> didn't create a separate widget for the table, because the overview widget
> seems relatively sparse right now, and can fit the table.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-220153395>
>

**Comment by sibyl229** [comment]
@kyook ahh, sorry, my fault, that empty table should not have shown up. Please check again: http://staging.wormbase.org/resources/molecule/WBMol:00004937#056--10 It only appears if there is at least one column is present, http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10 

I find the biological role table very readable and informative, while the various machine format structure code unreadable, so personally I would prefer the biological role in the Overview rather than the structure to save user some extra navigation. If the grey box is getting too long, maybe an alternative solution is to move some structure code to another widget? Maybe the InChi and SMILES can go there?

**Comment by sibyl229** [comment]
And @kyook I'm wrapping up WS253 development right now, so I might not be able to do everything related to this for the WS253. Please let me know what is minimal to go live with. Thanks!

**Comment by kyook** [comment]
On Wed, May 18, 2016 at 2:50 PM, Sibyl G <notifications@github.com> wrote:

> @kyook <https://github.com/kyook> ahh, sorry, my fault, that empty table
> should not have shown up. Please check again:
> http://staging.wormbase.org/resources/molecule/WBMol:00004937#056--10 It
> only appears if there is at least one column is present,
> http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10
>
ok, looks good


> I find the biological role table very readable and informative, while the
> various machine format structure code unreadable, so personally I would
> prefer the biological role in the Overview rather than the structure to
> save user some extra navigation.
>


> If the grey box is getting too long, maybe an alternative solution is to
> move some structure code to another widget? Maybe the InChi and SMILES can
> go there?
>
> Yes, all of that can go in another widget - InChi, InChiKey, IUPAC,
SMILES, Formula and Monoisotopic mass

Thanks Sibyl.  If you don't have time to do this last part, then that can
wait until the next release.

**Comment by sibyl229** [comment]
Hi @kyook is the structure widget okay?http://staging.wormbase.org/resources/molecule/WBMol:00004937#05--10 
http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10

**Comment by kyook** [comment]
Hi Sibyl,

Yes, it is great. All ready to go!

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, May 19, 2016 at 10:36 AM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> is the structure widget okay?
> http://staging.wormbase.org/resources/molecule/WBMol:00004937#05--10
> http://staging.wormbase.org/resources/molecule/WBMol:00005131#05--10
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4627#issuecomment-220397403>
>

**Comment by sibyl229** [comment]
Closing. For followups, please refer to #4838
