### ISSUE TITLE
Chris: Hi Colin Chris: How can I help? visitor_nam...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4628]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Colin</br>Chris: How can I help?</br>visitor_name (visitor_email): Question:  Within expression data, under FPKM expression, for a given gene in a given RNAseq dataset, a FPKM value and statistics are given;however, it does not indicate how that value relates to the experimental (wild type) control.  How am I supposed to interpret this number? Thanks</br>Chris: Let me take a look</br>Chris: I don't know if I can answer your question directly and may ask a colleague via e-mail for help, but have you looked at the "FPKM expression control statistics"?</br>visitor_name (visitor_email): That's what I thought to check but those values are not from the same experiment</br>Chris: Right, these seem to only reflect life stages</br>Chris: One minute while I look further...</br>Chris: Hi Colin, it's not quite clear to me either. I will send an email to Gary Williams, who manages all of this data, and will CC you and see what he has to say.</br>visitor_name (visitor_email): thanks for your help!</br>Chris: Sure, no problem. Sorry I couldn't explain this</br>Chris: OK, email sent. Gary is in Cambridge, England, so will probably get back to us in 12 hours or so</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): that's it, thanks again. I look forward to hearing more</br>Chris: OK, sounds good. One parting thought: It's not clear to me that there is always a "wild type" control, and some of the values/ranges may reflect total absolute measurement rather than relative. But, hopefully Gary can clarify</br>Chris: Have a nice day!

**Reported by:** coli********* (cede**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000411#04f5-9eacb1g-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000411#04f5-9eacb1g-10</a>
**Browser:** Safari 6.2.8

**Comment by gw3** [comment]
Hi Colin,

As Chris says, the data displayed under "FPKM expression" is from a lot of
different RNA-seq projects. Most of these have been performed for very
specific purposes and you should read the appropriate papers to find the
details of the experimental conditions and protocols used, with
descriptions of the controls used, if any.

You may find it more helpful to look at the table titled "FPKM expression
control statistics".
This is a group of data selected from many different experiments, but where
the data was intended to be an unbiased baseline, control value with no
special experimental condition, except for the life-stage. The details
column gives the number of Experiment values used to calculate the median
or mean value.

If you trust the modENCODE data, done five years ago now, you should look
at the graph "FPKM expression data from selected modENCODE libraries".

Gary
