### ISSUE TITLE
Renaming label 'FPKM expression control statistics'?

### ISSUE THREAD

**Issue by janelomax** [WormBase/website#4629]
I don't think the label 'FPKM expression control statistics' in the expression widget is very easy to interpret (this has come from a complaint from a user).

Their comment was: "(I don't even know) What even FPKM expression control statistics  means; what is expression control?"

Could we name this something like 'baseline expression values' or 'expression values by life-stage' instead? There's a full explanation in the details menu, so the label doesn't need to tell the whole story.

**Comment by gw3** [comment]
Yes, good idea.
How about "Baseline expression values"

**Comment by janelomax** [comment]
Excellent - @sibyl229 please could you change the label 'FPKM expression control statistics' to 'Baseline expression values' in the expression widget? Thanks!

**Comment by khowe** [comment]
I believe "Baseline" is EBI expression Atlas jargon, and I'm not sure its meaning is any more instantly understandable than "control". 

Whatever the label, we definitely need a tool-tip with a paragraph of text explaining exactly what these data are. So how about  "Aggregate expression estimates" for the label, and the following for the tool-tip: "Estimates of expression calculated by averaging the FPKMs for all control (untreated) samples for each life-stage".  Given this, I would also change the column headings to simply "Mean" and "Median".

**Comment by janelomax** [comment]
I'd be happy with that...so the tool tip would replace the text in the details panel?

**Comment by gw3** [comment]
The text in the details gives information on how many Experiments were used to make each mean and median value.

**Comment by khowe** [comment]
@gw3 Ah yes, I hadn't spotted that.

**Comment by janelomax** [comment]
Okay, so perhaps we leave the details panels as they are and just change the label to "Aggregate expression estimates" and the column headers to "Mean" and "Median"?

**Comment by sibyl229** [comment]
Hi @janelomax the field name tooltip and header for "Aggregate expression estimates" table has been changed. Could you take a look please? And close the issue if you think it's ready. Thanks!

**Comment by janelomax** [comment]
Looks good - thanks @sibyl229

**Comment by sibyl229** [comment]
Thanks @janelomax. Closing
