### ISSUE TITLE
I recently noticed a visual glitch In the sequence...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4631]
*Help Desk query collected when no chat operators were online. Follow up required.*

I recently noticed a visual glitch In the sequence widget, if you click the little helix symbol to view a sequence, an overlay will pop-up to show the sequences. Unfortunately this overlay is cut off on the right side and hides the 2 "rightmost" letters of all text. Theres is plenty of free space on the left. You can still select the hidden letters ans work with the sequence, but working just by visual inspection is "broken". Have a nice day!

**Reported by:** mark (mark*********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004789#0-9g4ce1f65-10-4ce1">http://www.wormbase.org/species/c_elegans/gene/WBGene00004789#0-9g4ce1f65-10-4ce1</a>
**Browser:** Safari 9.0.3

**Comment by vanaukenk** [comment]
Dear Mark,

Thanks for reporting this glitch to WormBase.  
I can confirm that the pop-up window is cutting off the view of the right-most sequence.
I've assigned this ticket to our web team who will take a look to see if it can be fixed.

Best,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
Dear Mark,

Thanks again for reporting this glitch to WormBase.


Just wanted to let you know that the issue has been addressed and the corrected view is visible on our staging site which is scheduled to go live this weekend.  Here's a link to the unc-104 page on staging in case you want to take a representative look:


http://staging.wormbase.org/species/c_elegans/gene/WBGene00006831


Best,

--Kimberly Van Auken
