### ISSUE TITLE
Question about BLASTP table in gene page

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#4633]
Hi,

I'm wondering if I could get more details about how the tables of BLASTP
hits on gene pages are obtained (e.g. how is BLAST run? which databases
are used?) For example, I'm looking at the gene W04A8.6
(http://www.wormbase.org/species/c_elegans/gene/WBGene00012241) and
there is a S. cerevisiae hit with a fairly low e-value, but if I run
BLASTP with the nr database I don't get the S. cerevisiae hit at all,
and doing a pairwise global alignment results in around 10% sequence
identity. I know that e-value varies depending on many parameters, such
as the database used.

Thanks!

Shirley

**Comment by vanaukenk** [comment]
Hi Shirley,

Thanks for writing to WormBase.

The matches in the BLASTP tables are generated during the WormBase database builds at the EBI, so someone from our EBI team will be able to answer your question about the specific parameters used in the BLAST searches.

Best,
--Kimberly Van Auken

**Comment by epaule** [comment]
we run the blastp on separate databases and show the "best" match per database on the widget.
As the p-value is dependent on database size, using the NCBI nr database with millions of entries will shift it significantly away from what it is in a small database of a few thousand yeast proteins.

Basically the probability of a getting a random match is much higher in nr.
