### ISSUE TITLE
on-the-fly chemical structure generation

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4636]
Can we generate chemical structures on molecule pages?
On ChEBI (a main source of molecule data we slurp up), these structures are generated on the fly-on-the site using Marvin (free for academic use) or more currently Ketcher (http://lifescience.opensource.epam.com/ketcher/)

Otherwise instructions to get the image files from ChEBI are included below) from my conversation with Gareth Owen from ChEBI. 

"I believe that the images of the structures in ChEBI are rendered by Marvin or Indigo. They can be taken directly from ChEBI as follows:
a) In the ChEBI website, go to the entity whose structure you need (eg CHEBI:223316), hover the cursor over the chemical structure, then right-click and select the 'copy image location' option.
b) Paste this location into the address bar of your internet browser. It is a long text string, ending with 'chebiId=223316&dimensions=400'
c) Go to this address. It will generate an image of the structure, dimensions 400 x 400. By varying the number in the address bar to a larger (anything up to about 1000 seems to work) or smaller number, you can generate an image as large or small as you wish.
d) When you have the size you need, right click on the generated image and choose 'save image as'
e) If you don't want the white background to the structure, there is an option to generate just the structure." 

Please let me know if displaying these structures is possible and what is the best way forward in terms of generating them and displaying them.

**Comment by sibyl229** [comment]
Hi @kyook is the ChEBI ID for chemicals stored in ACeDB?

**Comment by kyook** [comment]
Not that I know of.  I use it in Molecule curation so it is dumped as part
of that at every release.



~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, May 5, 2016 at 10:21 AM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> is the ChEBI ID for chemicals stored
> in ACeDB?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4636#issuecomment-217216019>
>

**Comment by khowe** [comment]
@kyook @sibyl229 I might be misunderstanding something, but as far as I can tell, the ChEBI ID *is* caputured/stored in AceDB, as an attribute of the ?Molecule:

Molecule : "Phosphatidylinositols" 
Public_name     "phosphatidylinositols" 
Formula  "C11H17O13PR2" 
Synonym  "PI" 
DB_info   Database "ChEBI" "CHEBI_ID"  "28874"

**Comment by kyook** [comment]
But the ontology itself? I haven't loaded that into acedb. It comes through the molecule.ace every upload

-mobile-

**Comment by kyook** [comment]
I should add that that file isn't just chebi entities. 

-mobile-

**Comment by sibyl229** [comment]
@kyook ah right, the ChEBI link in External links is working as well. Maybe we can promote the link to somewhere more noticeable. I'm not sure about whether we could embed those images on WB site. It really depends on whether ChEBI has got something made that would allow that. I didn't find anything when I checked their website, but I didn't look too carefully. Do you know?

**Comment by kyook** [comment]
Hi @sibyl229 Gareth from Chebi detailed the use of Marvin (a free chem modeler for making the images): 
2) Structures. We used to use Marvin for creating structures - it is commercial, but is free for academic use. In the last year, we have switched to Ketcher, which is free and open source.
I believe that the images of the structures in ChEBI are rendered by Marvin or Indigo. They can be taken directly from ChEBI as follows:
a) In the ChEBI website, go to the entity whose structure you need (eg CHEBI:223316), hover the cursor over the chemical structure, then right-click and select the 'copy image location' option.
b) Paste this location into the address bar of your internet browser. It is a long text string, ending with 'chebiId=223316&dimensions=400'
c) Go to this address. It will generate an image of the structure, dimensions 400 x 400. By varying the number in the address bar to a larger (anything up to about 1000 seems to work) or smaller number, you can generate an image as large or small as you wish.
d) When you have the size you need, right click on the generated image and choose 'save image as'
e) If you don't want the white background to the structure, there is an option to generate just the structure. But I can't remember what it is. I will find out when I'm back to the office on Friday and let you know (I'm currently in the Netherlands!).

Kind regards,
Gareth

I can get you in touch with them if you want to learn more.

**Comment by sibyl229** [comment]
@kyook right, sorry, so I can embed this image like this: http://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=true&imageIndex=0&chebiId=10443&dimensions=400 .

**Comment by kyook** [comment]
yeah!  is that easy enough? will it be a hassle to play with the dimensions to fit it in a widget?

**Comment by sibyl229** [comment]
@kyook that should be easy enough :) How about having a pre-set dimension for the structure image, and let the WB widget fit to that?

**Comment by kyook** [comment]
sure, whatever is easier

**Comment by kyook** [comment]
can the image  be downloadable?

**Comment by sibyl229** [comment]
Yes, just right click and download them.

**Comment by sibyl229** [comment]
Hi @kyook I added the ChEBI image to the molecule overview widget. Right now the image has a lot of space around it. I wonder if it's possible to access ChEBI for cropped images to fit the exact structure. http://staging.wormbase.org/resources/molecule/WBMol:00000005#021534--10

**Comment by kyook** [comment]
Hi @sibyl229 <https://github.com/sibyl229>,  Yes, I noticed the white
space.  Gareth gave some instructions on getting the images in with
different dimensions to limit the white space. I don't know how easy that
is to script. The instructions for retrieving smaller/larger images are in
c and d below.  There is also an option for retrieving the images without
the white background, which might be the best for out website.

Gareth can you help us with instructions on how to retrieve chemical images
from your website without the white background?


"2) Structures. We used to use Marvin for creating structures - it is
commercial, but is free for academic use. In the last year, we have
switched to Ketcher, which is free and open source.
I believe that the images of the structures in ChEBI are rendered by Marvin
or Indigo. They can be taken directly from ChEBI as follows:
a) In the ChEBI website, go to the entity whose structure you need (eg
CHEBI:223316),
hover the cursor over the chemical structure, then right-click and select
the 'copy image location' option.
b) Paste this location into the address bar of your internet browser. It is
a long text string, ending with 'chebiId=223316&dimensions=400'
c) Go to this address. It will generate an image of the structure,
dimensions 400 x 400. By varying the number in the address bar to a larger
(anything up to about 1000 seems to work) or smaller number, you can
generate an image as large or small as you wish.
d) When you have the size you need, right click on the generated image and
choose 'save image as'
e) If you don't want the white background to the structure, there is an
option to generate just the structure. But I can't remember what it is. I
will find out when I'm back to the office on Friday and let you know (I'm
currently in the Netherlands!)."

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, May 6, 2016 at 1:06 PM, Sibyl G <notifications@github.com> wrote:

> Hi @kyook <https://github.com/kyook> I added the ChEBI image to the
> molecule overview widget. Right now the image has a lot of space around it.
> I wonder if it's possible to access ChEBI for cropped images to fit the
> exact structure.
> http://staging.wormbase.org/resources/molecule/WBMol:00000005#021534--10
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4636#issuecomment-217545298>
>

**Comment by sibyl229** [comment]
@kyook Yes. I understand the "dimension" attribute he described. Varying the dimension changes the number of pixels used to create the initial drawing. It doesn't fix the white space issue though. I guess I should have explained the problem better. So, suppose ChEBI generates an image of 100x100, the molecule drawing occupies a 80x70 rectangular region in the centre of the image, this is fine. The issue is that if a drawing occupies 80X30, it will still generate a 100x100 square image leaving lots white space on the page. I guess it's a minor issue. I'm just wondering if ChEBI images cropped at the drawing area that we can link to. Then I can pad the image by a constant white space padding.

**Comment by kyook** [comment]
Gareth suggested that we can get the image without the white space, would
that help? At least I'm supposing that that would mean there are no set
image dimensions, if so, then we can wait for him to get back to us.

If that isn't the case, I hope Gareth can point us to the person who can
help with finding the cropped images.

So far, the pages look good enough, so if we don't hear back, I'm happy to
go live.

One thing I noticed though is that for some molecules, the synonym list is
HUGE and unhelpfully expands the info box in the overview widget, do you
guys have a way to limit the size of the list view, so say the first 5
synonyms?

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, May 6, 2016 at 2:23 PM, Sibyl G <notifications@github.com> wrote:

> @kyook <https://github.com/kyook> Yes. I understand the "dimension"
> attribute he described. Varying the dimension changes the number of pixels
> used to create the initial drawing. It doesn't fix the white space issue
> though. I guess I should have explained the problem better. So, suppose
> ChEBI generates an image of 100x100, the molecule drawing occupies a 80x70
> rectangular region in the centre of the image, this is fine. The issue is
> that if a drawing occupies 80X30, it will still generate a 100x100 square
> image leaving lots white space on the page. I guess it's a minor issue. I'm
> just wondering if ChEBI images cropped at the drawing area that we can link
> to. Then I can pad the image by a constant white space padding.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4636#issuecomment-217562071>
>

**Comment by sibyl229** [comment]
@kyook Yes, would be good to clarify with Gareth about what "without white background" means: whether it means no set image dimension or transparent background. Thank you! 

Right now there is a way to hide a list of items behind a toggle that says "5 Found". Does that work?

**Comment by kyook** [comment]
On Fri, May 6, 2016 at 3:18 PM, Sibyl G <notifications@github.com> wrote:

> @kyook <https://github.com/kyook> Yes, would be good to clarify with
> Gareth about what "without white background" means: whether it means no set
> image dimension or transparent background. Thank you!
>
> Right now there is a way to hide a list of items behind a toggle that says
> "5 Found". Does that work?
>

would the number in the "5 found" reflect the actual numbers of items? So
it could read "50 found" if there are 50 names not showing?  If so, then
yes, that might make things cleaner.

**Comment by kyook** [comment]
Hi Karen,

Sorry that this slipped out of the radar!

After the ...&dimensions=300 (or whatever the size you need), add 
&transbg=true

(transbg is short for transparent background)

The resulting image can then be copied and pasted into other 
applications without any white background.

Hope this helps - let me know if you have any problems.

Sorry again for not get back to you as I had promised.

Kind regards,
Gareth

On 06/05/2016 21:42, Karen Yook wrote:
> Hi @sibyl229 <https://github.com/sibyl229>,  Yes, I noticed the white
> space.  Gareth gave some instructions on getting the images in with
> different dimensions to limit the white space. I don't know how easy
> that is to script. The instructions for retrieving smaller/larger images
> are in c and d below.  There is also an option for retrieving the images
> without the white background, which might be the best for out website.
>
> Gareth can you help us with instructions on how to retrieve chemical
> images from your website without the white background?
>
>
> "2) Structures. We used to use Marvin for creating structures - it is
> commercial, but is free for academic use. In the last year, we have
> switched to Ketcher, which is free and open source.
> I believe that the images of the structures in ChEBI are rendered by
> Marvin or Indigo. They can be taken directly from ChEBI as follows:
> a) In the ChEBI website, go to the entity whose structure you need (eg
> CHEBI:223316), hover the cursor over the chemical structure, then
> right-click and select the 'copy image location' option.
> b) Paste this location into the address bar of your internet browser. It
> is a long text string, ending with 'chebiId=223316&dimensions=400'
> c) Go to this address. It will generate an image of the structure,
> dimensions 400 x 400. By varying the number in the address bar to a
> larger (anything up to about 1000 seems to work) or smaller number, you
> can generate an image as large or small as you wish.
> d) When you have the size you need, right click on the generated
> image and choose 'save image as'
> e) If you don't want the white background to the structure, there is an
> option to generate just the structure. But I can't remember what it is.
> I will find out when I'm back to the office on Friday and let you know
> (I'm currently in the Netherlands!)."
>
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 415.306.4150
> e-mail: kyook@caltech.edu <mailto:kyook@caltech.edu>
> e-mail: karen@wormbase.org <mailto:karen@wormbase.org>
> skype name: wbkaren
>
>
> On Fri, May 6, 2016 at 1:06 PM, Sibyl G <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>     Hi @kyook <https://github.com/kyook> I added the ChEBI image to the
>     molecule overview widget. Right now the image has a lot of space
>     around it. I wonder if it's possible to access ChEBI for cropped
>     images to fit the exact structure.
>     http://staging.wormbase.org/resources/molecule/WBMol:00000005#021534--10
>
>     —
>     You are receiving this because you were mentioned.
>     Reply to this email directly or view it on GitHub
>     <https://github.com/WormBase/website/issues/4636#issuecomment-217545298>
>
>

-- 
ChEBI team,
European Bioinformatics Institute (EMBL-EBI),
European Molecular Biology Laboratory,
Wellcome Genome Campus,
Hinxton, Cambridge,
CB10 1SD, United Kingdom

**Comment by sibyl229** [comment]
Thanks @kyook for the follow up. Hmm I tried the transbg=true paramter (and deployed to staging), but as Gareth said it means transparent background, so the space is still present just transparent, which is different from a cropped image. I don't think I can crop the image myself because some drawing fits the image almost exactly like this one: http://staging.wormbase.org/resources/molecule/WBMol:00000006#021534--10 while others don't: http://staging.wormbase.org/resources/molecule/WBMol:00002883#021534--10

**Comment by kyook** [comment]
Hi @sibyl229, I think both of those pages are fine as is.  The only thing that might make it better is to scale the images down a bit if possible and easy; if not it is not a big deal.

**Comment by sibyl229** [comment]
Hi @kyook so I reduced the display size to 180x180 (pixels) from 250x250. Is this okay now?http://staging.wormbase.org/resources/molecule/WBMol:00000006#021534--10 http://staging.wormbase.org/resources/molecule/WBMol:00002883#021534--10
I noticed that previous if ChEBI doesn't have an image for the molecule, a broken image was showing up. It should be fixed now: http://staging.wormbase.org/resources/molecule/Phosphatidylinositols#025--10

**Comment by kyook** [comment]
It looks great @sibyl229.  Issue is good to close.
Thanks!
