### ISSUE TITLE
flcn-1 isoform query

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#4639]
From wormbase-help

Hello,

The following sequence is a new mRNA submission for flcn-1 (WormBase
ID:WBGene00017699) from PMID:23566034:

EMBL=HE963850; mRNA; CCJ34850.1

This sequence doesn't seem to correspond to any of the isoforms listed
for flcn-1 in Wormbase at present. I was wondering whether this sequence
is going to be added as a new isoform in Wormbase?

Bet wishes,

Hema

**Comment by azurebrd** [comment]
Did anyone ever reply to this ? I no longer have the original email to know who to contact.

**Comment by Paul-Davis** [comment]
Hi,

I have added the alternative Isoform for WS255.

Thanks for pointing it out.

Paul


On 04/03/2016 12:26, Hema Bye-A-Jee wrote:
> Hello,
>
> The following sequence is a new mRNA submission for flcn-1 (WormBase 
> ID:WBGene00017699) from PMID:23566034:
>
> EMBL=HE963850; mRNA; CCJ34850.1
>
> This sequence doesn't seem to correspond to any of the isoforms listed 
> for flcn-1 in Wormbase at present. I was wondering whether this 
> sequence is going to be added as a new isoform in Wormbase?
>
> Bet wishes,
>
> Hema
>


-- 
===========================================
Paul Davis
Senior Technical Officer [WormBase Bioinformatician]
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
