### ISSUE TITLE
caspase-like 3 = pseudogene

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#4640]
From wormbase-help:

hi wormbase folks,

We are writing up a paper on the role of caspases in axon degeneration.  there are four annotated caspases: ced-3, csp-1 csp-2 csp-3. 

CSP-3 is just a short C-terminal fragment containing part of the CASc domain, nearly identical to the C-terminus of CSP-2.  I think csp-3 is probably a pseudo gene caused by duplication of csp-2, because: 
• First, the upstream ORF Y47H9C.15 from csp-3 also has homology to CSP-2. it was probably identified as a separate gene because of stop codons that broke the gene apart without splice sites.
• Second, CSP-2 tBLASTn indicates that the N-terminus section of the csp-2 duplication is 3’ of the csp-3 ORF. 

- the ship broke in half when it hit bottom, and the front part landed behind the stern.

erik jorgensen

**Comment by gw3** [comment]
Erik,

I agree that csp-3 looks like a pseudogene.
We will make the change to this locus from CDS to Pseudogene for release 
WS254.

Gary Williams

**Comment by gw3** [comment]
Dear Erik,

My colleague passed this to me to make the change for WS254, however 
while looking at it I was a little uneasy converting the existing csp-3 
structure into a Pseudogene. There is alternative splicing present 
giving rise to a novel exon (exon 1 of current anno) which in turn 
appears to have an RNASeq asymmetry signal. This suggesting that it is 
the 5' of a transcript Isoform and I can't rule out that this isn't 
functional based on the data that is available.

What I have done is to merge the 2 loci (Y47H9C.15 and Y47H9C.6 - csp-3) 
as you suggest based on fragmented protein homology and domain 
architecture, retaining the current csp-3 coding Isoform and creating a 
long non-coding transcript isoform to illustrate the fully extent of the 
loci. This also contains an explanation of why this loci might be a 
complexed old duplication that has partially recovered/evolved novel 
function.

I hope this works with what you are publishing. If you would like to 
discuss this further, please feel free to email me.

Thanks

Paul


On 04/03/2016 16:48, Gary Williams wrote:
> Erik,
>
> I agree that csp-3 looks like a pseudogene.
> We will make the change to this locus from CDS to Pseudogene for 
> release WS254.
>
> Gary Williams
>
> On 03/03/16 11:51, Erik Jorgensen wrote:
>> hi wormbase folks,
>>
>> We are writing up a paper on the role of caspases in axon 
>> degeneration.  there are four annotated caspases: ced-3, csp-1 csp-2 
>> csp-3.
>>
>> CSP-3 is just a short C-terminal fragment containing part of the CASc 
>> domain, nearly identical to the C-terminus of CSP-2.  I think csp-3 
>> is probably a pseudo gene caused by duplication of csp-2, because:
>> • First, the upstream ORF Y47H9C.15 from csp-3 also has homology to 
>> CSP-2. it was probably identified as a separate gene because of stop 
>> codons that broke the gene apart without splice sites.
>> • Second, CSP-2 tBLASTn indicates that the N-terminus section of the 
>> csp-2 duplication is 3’ of the csp-3 ORF.
>>
>> - the ship broke in half when it hit bottom, and the front part 
>> landed behind the stern.
>>
>> erik jorgensen
>>
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by gw3** [comment]
Hi Paul,

that seems reasonable; once a gene gets declared as a pseudogene it is hard to bring it back from the dead, even if it has evolved a new function.  

Just to make sure i assembled the bits correctly, do you also see the N-terminus of the 'csp-2 duplication' downstream of ‘csp-3’ by tBLASTn?

erik

**Comment by Paul-Davis** [comment]
Hi Erik,

Here is a regular blast of the csp-2 cdna
![csp-2_blast_csp-3](https://cloud.githubusercontent.com/assets/717707/13609558/5e090052-e551-11e5-9387-3b10a86dcb8c.png)

and a tblastn

![csp-2_tblastn_csp-3](https://cloud.githubusercontent.com/assets/717707/13609565/65e1d628-e551-11e5-8e5e-256709bdcbf5.png)

I don't seem to be able to see the missing piece you refer to downstream of csp-3.

WS254 annotation overview:
![csp-3_new](https://cloud.githubusercontent.com/assets/717707/13609959/470d2692-e553-11e5-9756-235251a9d082.png)

I hope this helps make things clear.

Paul

**Comment by Paul-Davis** [comment]
Hi Erik,

I have added a summary to the ticket that is tracking this issue: 
https://github.com/WormBase/website/issues/4640#issuecomment-193340698

I couldn't really see the additional sequence outside of the current 
annotation of the 2 genes.

Paul

On 07/03/2016 16:49, gw3 wrote:
> Hi Paul,
>
> that seems reasonable; once a gene gets declared as a pseudogene it is 
> hard to bring it back from the dead, even if it has evolved a new 
> function.
>
> Just to make sure i assembled the bits correctly, do you also see the 
> N-terminus of the 'csp-2 duplication' downstream of ‘csp-3’ by tBLASTn?
>
> erik
>
> > On Mar 7, 2016, at 9:06 AM, Paul Davis <paul.davis@wormbase.org> wrote:
> >
> >
> > Dear Erik,
> >
> > My colleague passed this to me to make the change for WS254, however 
> while looking at it I was a little uneasy converting the existing 
> csp-3 structure into a Pseudogene. There is alternative splicing 
> present giving rise to a novel exon (exon 1 of current anno) which in 
> turn appears to have an RNASeq asymmetry signal. This suggesting that 
> it is the 5' of a transcript Isoform and I can't rule out that this 
> isn't functional based on the data that is available.
> >
> > What I have done is to merge the 2 loci (Y47H9C.15 and Y47H9C.6 - 
> csp-3) as you suggest based on fragmented protein homology and domain 
> architecture, retaining the current csp-3 coding Isoform and creating 
> a long non-coding transcript isoform to illustrate the fully extent of 
> the loci. This also contains an explanation of why this loci might be 
> a complexed old duplication that has partially recovered/evolved novel 
> function.
> >
> > I hope this works with what you are publishing. If you would like to 
> discuss this further, please feel free to email me.
> >
> > Thanks
> >
> > Paul
> >
> >
> > On 04/03/2016 16:48, Gary Williams wrote:
> >> Erik,
> >>
> >> I agree that csp-3 looks like a pseudogene.
> >> We will make the change to this locus from CDS to Pseudogene for 
> release WS254.
> >>
> >> Gary Williams
> >>
> >> On 03/03/16 11:51, Erik Jorgensen wrote:
> >>> hi wormbase folks,
> >>>
> >>> We are writing up a paper on the role of caspases in axon 
> degeneration. there are four annotated caspases: ced-3, csp-1 csp-2 csp-3.
> >>>
> >>> CSP-3 is just a short C-terminal fragment containing part of the 
> CASc domain, nearly identical to the C-terminus of CSP-2. I think 
> csp-3 is probably a pseudo gene caused by duplication of csp-2, because:
> >>> • First, the upstream ORF Y47H9C.15 from csp-3 also has homology 
> to CSP-2. it was probably identified as a separate gene because of 
> stop codons that broke the gene apart without splice sites.
> >>> • Second, CSP-2 tBLASTn indicates that the N-terminus section of 
> the csp-2 duplication is 3’ of the csp-3 ORF.
> >>>
> >>> - the ship broke in half when it hit bottom, and the front part 
> landed behind the stern.
> >>>
> >>> erik jorgensen
> >>>
> >>
> >
> >
> > --
> > ===========================================
> > WormBase
> > European Bioinformatics Institute (EMBL-EBI)
> > European Molecular Biology Laboratory
> > Wellcome Trust Genome Campus
> > Hinxton
> > Cambridge CB10 1SD
> > United Kingdom
> > ===========================================
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WormBase/website/issues/4640#issuecomment-193340698>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
