### ISSUE TITLE
  Hello,  can you please direct me to i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4641]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>can you please direct me to information on how to order a c. elegans genomic cosmid? </p>

**Reported by:** Anne (alan*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by chris-grove** [comment]
Hi Anne,


 If you click on the "Reagent" link under the "Resources" menu header on the WormBase home page, you will be directed here:


http://www.wormbase.org/resources/reagents#321054--10


In the "Clone information" section you will find links and instructions on how and where to order clones.


Hope that helps!


Best,

Chris Grove

WormBase
