### ISSUE TITLE
  Hi,  I have recently switched to Wind...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4645]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I have recently switched to Windows 10, and for whatever reason I cannot obtain sequences by highlighting a chromosomal region from the genome browser window (where it would normally ask you if you want to dump it on FASTA, etc). Do you have any idea how I can fix this? Right now I have no idea how to obtain sequence information from any given genomic region... <br/>Thanks! <br/>Sandra</p>

**Reported by:** Sand********** (savi******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by scottcain** [comment]
Does anybody have a Win10 machine they can try GBrowse on? This the first I've heard of problems with Windows 10

**Comment by scottcain** [comment]
No word in over a week, and no confirmation from anybody else that there is a problem, so I'm closing this.
