### ISSUE TITLE
  Is there any specific tool to analyze...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4646]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there any specific tool to analyze cis-regulatory elements on C.elegans promoter sequence</p>

**Reported by:** karu** (karu**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Karuna,


Thanks for writing to WormBase.


One tool available in WormBase for analyzying cis-regulatory regions is the Genome Browser (GBrowse).


You can access the Genome Browser by clicking on the Tools link at the top of each page, or from a specific gene page, by clicking on the Location widget on the left side of the page and then on the resulting physical map graphic in the widget.


Once you are on the Genome Browser page you can click on the 'Select Tracks' link that will take you to a list of various Seuquence Features that you can display.


Note that you can also try the new JBrowse tool that is listed under the Tools drop-down menu, as well.


Please let us know if you need any further assistance.

Best,

--Kimberly Van Auken
