### ISSUE TITLE
How can I determine what chromosome this gene is l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4649]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I determine what chromosome this gene is located on?

**Reported by:** Anna (ache***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_brenneri/gene/WBGene00164493#082456def-9g317abc-3">http://www.wormbase.org/species/c_brenneri/gene/WBGene00164493#082456def-9g317abc-3</a>
**Browser:** Chrome 48.0.2564.116

**Comment by raymond91125** [comment]
Hi Anna,

If you open the Location widget, there's line that states " Genomic 
position:Cbre_Contig0:3337374..3340938". That's the information our 
database has. I don't know if there's any external information to 
connect contig0 to chromosome.

Let us know if you have more questions.

Cheers,

Raymond
