### ISSUE TITLE
  Hi, I was wondering if someone could ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4651]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I was wondering if someone could  help me to identify the approximate size of the largest annotated intron in C. elegans? I am not sure of the best way to do this. Thank you for your help.<br/>Sincerely,<br/>visitor_name</p>

**Reported by:** Step************** (smpy****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by epaule** [comment]
you can get a GFF file for C.elegans which includes all introns from http://www.wormbase.org/species/c_elegans.
If you grep all WormBase intron lines out, each has the start and end positions in the 4th and 5th column.

**Comment by epaule** [comment]
hia,

you can get a GFF file for C.elegans which includes all introns from
http://www.wormbase.org/species/c_elegans.
If you grep all WormBase intron lines out, each has the start and end
positions in the 4th and 5th column.

Michael
