### ISSUE TITLE
  Hi, I asked a question before about t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4652]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I asked a question before about the maximum annotated intron size in C. elegans. I realized that I also need to know the minimum annotated intron size. What is the best way to locate this information? Thank you!<br/>Sincerely,<br/>Stephanie</p>

**Reported by:** Step************** (smpy****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by epaule** [comment]
you can get a GFF file for C.elegans which includes all introns from http://www.wormbase.org/species/c_elegans.
If you grep all WormBase intron lines out, each has the start and end positions in the 4th and 5th column.
