### ISSUE TITLE
Sequence summary external links widget circular linking

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4653]
http://www.wormbase.org/species/c_brenneri/sequence/Cbre_Contig0#1--10

Links to genbank produce a circular url link

**Comment by sibyl229** [comment]
Hi @Paul-Davis Could you tell me what the GenBank link would be? URL for each external database needs to configured individually. When in doubt, you could check which ones are already configured here: https://github.com/WormBase/website/blob/staging/root/templates/config/external_urls Please let me the URL. Thanks!

**Comment by sibyl229** [comment]
Hi @Paul-Davis I added the GenBank link to external_urls configuration. The fix is deployed to staging: http://staging.wormbase.org/species/c_brenneri/sequence/Cbre_Contig0#15--10 
I used: 'http://www.ncbi.nlm.nih.gov/nuccore/?term=%s' for the link, do you think it's correct? Thanks

**Comment by Paul-Davis** [comment]
Hi @sibyl229 it works well for a specific accession, but the "Scfld02_0" returns both brenneri and remanei entries, don't know if it would be workable, but if it searched with a species it would be ok www.ncbi.nlm.nih.gov/nuccore/?term=brenneri Scfld02_0 but maybe it's not worth worrying about?

P

**Comment by sibyl229** [comment]
Thanks @Paul-Davis Hmm I think since Scfld02_0 isn't a unique identifier, trying to resolve the ambiguity in the web code will probably result in complex code. I think it's probably easier to stick with unique identifiers in external databases. Is that okay?

**Comment by Paul-Davis** [comment]
@sibyl229 Sure.......or just leave it as you have it now?

**Comment by sibyl229** [comment]
@Paul-Davis Sure. Let's leave it as it :) Closing.
