### ISSUE TITLE
  Dear WormBase staff, I am looking for...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4654]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase staff,<br/>I am looking for a way to get the RNAi phenotype for each C.elegans gene, but I could not find RNAi or knockdown information in WormMine. Could you help me to get the RNAi phenotype of all genes,please?<br/>Thanks a lot!<br/>Cheers,<br/>visitor_name</p><p>What were you doing? <br />&nbsp;&nbsp;For example, if I search daf-19 in WormBase, I got the "dauer formation variant" & "RNAi"  in "Phenotypes" section, . However, if I search daf-19 in WormMine, this information was not listed.</p>

**Reported by:** Jiar***** (jiar************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by chris-grove** [comment]
Hello Jiarui,


You can find current RNAi phenotype summary files on our FTP site here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/

Please note that there are two file with RNAi phenotypes, each with slightly different formats.


Let us know if you need anything else.


Best,


Chris Grove

WormBase
