### ISSUE TITLE
OMIM xref file to be produced during the build

### ISSUE THREAD

**Issue by khowe** [WormBase/website#4656]
It seems that OMIM are inferring links back to WormBase from a file on our FTP site that is 5 years old:

ftp://ftp.wormbase.org/pub/wormbase/outgoing/ncbi_omim/current

We need to create a current version of this file each release, and provide a stable "current" link for OMIM to pick up.

I suggest we create the file here:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WSXXX/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WSXXX.omim_xrefs.txt

It should end up here automatically (although this will need to be checked):

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/omim_xrefs/c_elegans.PRJNA13758.WSXXX.omim_xrefs.txt.gz

...and have the following stable symlink to the latest current file:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/omim_xrefs/c_elegans.canonical_bioproject.current.omim_xrefs.txt

 Once this is in place, we can notify OMIM of the new location.

**Comment by khowe** [comment]
Actually, once the file is in place, we can simply make ftp://ftp.wormbase.org/pub/wormbase/outgoing/ncbi_omim/current symlink to it. That way, OMIM don't have to do anything.

**Comment by Paul-Davis** [comment]
Script done and in git, just needs final tweaks before pushing

File generated for WS253 - /nfs/wormpub/BUILD/autoace/MISC_OUTPUT/WS253_OMIMXREF.dat

**Comment by Paul-Davis** [comment]
Things left to do......make_FTP_site.pl needs to be made aware of the new source and target
Then I guess when WS253 is released we need to talk to @tharris about adding the symlink to the new build file.

**Comment by Paul-Davis** [comment]
- Make_FTP_site.pl - done
- autoace_builder.pl for the script call - done

Reassigning to web team for WS253 release

**Comment by sibyl229** [comment]
Hi @khowe I think Todd has added the OMIM xref file to the ftp site: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/omim_xrefs/c_elegans.PRJNA13758.WS253.omim_xrefs.txt . Can this ticket be closed? Thanks

**Comment by khowe** [comment]
Looks good. Closing.
