### ISSUE TITLE
  How do I search for deficiency strain...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4657]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I search for deficiency strain of specific gene systematically?</p><p>What were you doing? <br />&nbsp;&nbsp;I looked for deficiency strain of one specific gene, but I can only search in 'reaarangement' column by Df names  one by one. I want to konw whether there is a map or list in which I can find the corresponding Df strain name directly.</p>

**Reported by:** Xia ** (xia.**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by tuli** [comment]
Dear Xia,

Thank you for writing to WormBase.

I believe the Strain table, which is in the Genetics widget of the
Gene Summary page will give you the information you need.

This table lists the strain name and the genotype.

Please let me know if I can help further.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
