### ISSUE TITLE
Login issue - email account not available

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#4659]
From help desk:

Hi –

I’m a lapsed worm breeder (Bargmann and Ashrafi labs) who recently changed companies in industry.  My wormbase account seems to be linked to my old employer [akahn-kirby@fibrogen.com], and I can’t remember my password.  Is it possible to 1) reset the password, and 2) change the email address to my current email, akahn-kirby@edisonpharma.com?

Cheers,
Amanda

Amanda H. Kahn-Kirby PhD  |  Group Leader, MoA

**Comment by vanaukenk** [comment]
@tharris 
Have you had a chance to help Amanda?
Thx.

**Comment by azurebrd** [comment]
Hi Kimberly/Helpdesk –

 

I was wondering if this item has been resolved on your end?  I have not yet received a password reset notice.  I am unable to access my prior email address (akahn-kirby@fibrogen.com), and would like to access wormbase through my new work email (akahn-kirby@edisonpharma.com).

 

Kind thanks,

Amanda

**Comment by sibyl229** [comment]
A new account is created for her. Closing.
