### ISSUE TITLE
Invalid WBPeople being Tweeted

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#4664]
Just spotted this on Twitter.  WBPerson20531 is invalid and doesn't have any data, hence the ironic reply from a follower.

![screen shot 2016-03-11 at 09 42 22](https://cloud.githubusercontent.com/assets/6329861/13698717/c5078fbc-e76d-11e5-9e6c-241332357d9f.png)

**Comment by epaule** [comment]
technically the entry was merged into WBPerson5694

**Comment by sibyl229** [comment]
Hi @brucebolt Thanks. Hmm I'm guessing the twitter account is using the same random object endpoint as the homepage Activity widget. It's a good idea to filter it to include only current objects. @epaule do you know if Merge_into tag is an acceptable way to identify legacy items? Thank you

**Comment by epaule** [comment]
I don't think we have a tag to cover all classes, but as far as people go, you could filter on Status Valid.

To be fair, you could restrict it even further to ones with Papers ...

**Comment by sibyl229** [comment]
@epaule Sounds good. Thanks
