### ISSUE TITLE
  wormmine is down. I'm sure this is al...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4665]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;wormmine is down. I'm sure this is all planned, but I thought I'd mention it in the unlikely event that noone has noticed.</p><p>What were you doing? <br />&nbsp;&nbsp;attempting to access wormmine via the service API</p>

**Reported by:** Vive****** (vvi@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by chris-grove** [comment]
Hello Vivek,


 Thanks for the heads up and apologies for the inconvenience. We're aware of the issue and are working to restore services. You can follow progress on this issue on GitHub here:


https://github.com/WormBase/website/issues/4665



Best,


Chris Grove

WormBase

**Comment by tharris** [comment]
Hello Vivek - 

Thanks for reporting the issue.

I'm happy to report that we've restored service to WormMine. Thank you for your patience.

Todd
