### ISSUE TITLE
Chris: Hello Kalpana, how can I help? visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4667]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Kalpana, how can I help?</br>visitor_name (visitor_email): Just noticed that WormMine is down (from tools menu) - not sure if you are already aware of it</br>Chris: Oh, hmmmm, no I was not aware</br>visitor_name (visitor_email): just thought of letting you know and tying this online chat feature!! - very nice</br>Chris: Glad you like it :)</br>Chris: OK it looks like WormMine is down for maintenance</br>Chris: I imagine it will be back up soon</br>visitor_name (visitor_email): please let whoever is in charge of that know</br>Chris: I will do</br>visitor_name (visitor_email): in case it is not intentional</br>visitor_name (visitor_email): thanks!</br>Chris: I can email you when it is back up</br>Chris: sure</br>Chris: Maybe I can help you get the info you need in the meantime?

**Reported by:** Kalp********* (kkar***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/queries">http://www.wormbase.org/tools/queries</a>
**Browser:** Chrome 48.0.2564.116

**Comment by chris-grove** [comment]
WormMine is down right now, in case it isn't already known

**Comment by chris-grove** [comment]
OK, I just realized this was reported in #4665. Closing this one to make #4665 the primary ticket.
