### ISSUE TITLE
  I am looking for phenotype descriptio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4669]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am looking for phenotype descriptions of C. elegans mutants: bli-1, bli-4, bli-6, dpy-1, dpy-6, dpy-9, dyp-11, lon-2, rol-1, rol-6, unc-1, unc-4, unc-7, unc-13, unc-22, unc-32 and unc-42. However I can only find descriptions of the genes on your website, please can you to direct me as to where I can find phenotype descriptions.<br/>Many thanks</p>

**Reported by:** Elle********* (ll13***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by Gschindelman** [comment]
I responded with:

Ellen,
If you go to the gene page of one of the gene pages listed below (e.g. bli-1) 
http://www.wormbase.org/species/c_elegans/gene/WBGene00000251#0-9g4ce1f65-10-4ce1
on the lefthand side you will see a list of the "page contents"; here you will see a phenotype tab (widget)…click on it and you should be able to get the data you want.
Hope this helps
Gary
