### ISSUE TITLE
Yanai large scale display

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4670]
Hi Sibyl,
I would like to have all the objects that have RNASeq in type, displayed in the 'Expression profiling graphs' section.
For example: Expr1149515 on this page
http://www.wormbase.org/species/c_elegans/gene/WBGene00006744#0f-9ebg1c8-10 

should be displayed below Expr1024616.
Happy to skype if you have questions.
thanks!

**Comment by draciti** [comment]
Hey Sibyl, that is somewhat related to the previous issue, could you please take a look?
thanks

**Comment by sibyl229** [comment]
Hi @draciti the expression pattern by RNASeq is move to the Expression Profiling Graphs table. http://staging.wormbase.org/species/c_elegans/gene/WBGene00006744#0-1-3

**Comment by draciti** [comment]
thanks Sibyl!
