### ISSUE TITLE
  I need to get the sequences for all o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4673]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I need to get the sequences for all of the transposable elements in C.elegans (TC1-5, FB1, etc). How would I do this?  <br/>Is it possible to get the Transposable element sequences from other nematode species?<br/>Thanks,<br/>Ed Ralston<br/>visitor_email</p>

**Reported by:** Edwa************* (eral*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by chris-grove** [comment]
Hi Ed,

 You can find transposon sequences on our FTP site transcripts directory:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/


look for the "transposon_transcripts.fa.gz" files; you'll probably want the current version:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/c_elegans.PRJNA13758.current.transposon_transcripts.fa.gz

You can browse the other FTP directories to see if other species have transposon sequences, although at first glance it looks like we only have them for C. elegans.


Best,


Chris Grove

WormBase

**Comment by sibyl229** [comment]
Thanks Chris for answering!

Sibyl

**Comment by chris-grove** [comment]
I actually need to reopen this as it is not resolved.

**Comment by Paul-Davis** [comment]
I'm looking at generation this data.

**Comment by Paul-Davis** [comment]
Dear Ed,

I have been working on the problem of Transposon sequence access from 
WormBase and have prepared a file containing curated Transposons 
(WBTransposon) and a filtered set of predicted Transposon regions of the 
genome. This file will now be a standard part of our production pipeline 
and available with each release.

The file can be downloaded from here: http://goo.gl/pPB4pW

The predicted Transposons have been derived from the alignment of the C. 
elegans repeat library to the reference genome, then any match not 
classified as a Type I or Type II transposon was removed and finally a 
minimum size limit of 150bp was imposed.

If you have any suggestions on how we could improve or concerns about 
this data, please feel free to get back in tough.

Apologies that this has been such a long time coming.

Paul



On 14/03/2016 22:39, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I need to get the sequences for all of the transposable elements in 
> C.elegans (TC1-5, FB1, etc). How would I do this?
> Is it possible to get the Transposable element sequences from other 
> nematode species?
> Thanks,
> Ed Ralston
> eralston@berkeley.edu
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4673. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4673>.
>
> Reported by: Edward J. Ralston (eralston@berkeley.edu)
> 14 Mar 16 22:39
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 
> (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Consider this closed.
