### ISSUE TITLE
  Hi, I need wiki write access to http:...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4674]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I need wiki write access to http://wiki.wormbase.org/index.php/TransgeneOme_import in order to document our collaboration. Desired user name: janosch.<br/>Thx,<br/>Stephan</p><p>What were you doing? <br />&nbsp;&nbsp;Developping an API for data exchange with worm base</p>

**Reported by:** Step*********** (jano**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/537.86.4

**Comment by tharris** [comment]
Account created and credentials emails to Stephan.

**Comment by StephanJanosch** [comment]
Works fine now! :-)
