### ISSUE TITLE
addgene link on clone pages broken

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4675]
http://www.wormbase.org/species/c_elegans/clone/pAA173#02143--10
addgene link points to http://www.wormbase.org/species/c_elegans/clone/www.addgene.org/21743
link should be http://www.addgene.org/<plasmid id>  ex. http://www.addgene.org/21743

**Comment by kyook** [comment]
Also I was informed that Addgene should be written as "Addgene" not AddGene.

**Comment by sibyl229** [comment]
Hi @kyook the Addgene link should be working on staging now: http://staging.wormbase.org/species/c_elegans/clone/pAA173#015--10 . The link label still uses 'addgene' (all lower case) right now as it shows what the database has.

**Comment by kyook** [comment]
Hi @sibyl229  the link in the overview window goes to http://staging.wormbase.org/species/c_elegans/clone/www.addgene.org/21743, which isn't a page, would you fix that?  The link in the external links widget is great.  thanks!

**Comment by sibyl229** [comment]
Hi @kyook the link in the overview is also working now: http://staging.wormbase.org/species/c_elegans/clone/pAA173#01--10

**Comment by kyook** [comment]
Thanks Sibyl!
