### ISSUE TITLE
Hello,
 for your c.elegan mutant egl-4(ks62) strai...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4678]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
 for your c.elegan mutant egl-4(ks62) strain FK234 I see that it is described under overview as "Allele:substitution"I have found no further information on what this substitution is on. Are you guys able to tell me? I have also looked in the original paper evidence by Hirose et.al,2003 and it is not described there either. Thank  you!

**Reported by:** Kare******** (k.se****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088291#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00088291#02-45-3</a>
**Browser:** Chrome 49.0.2623.87

**Comment by tuli** [comment]
Dear Karen,

Thank you for writing to WormBase.

The details of the ks62 substitution are available under the Molecular
Details widget within the page you were looking at.
You can see the nature of the lesion (g/a substitution), the flanking
sequence, strains carrying the allele and details of the Features
Affected.

The Hirose paper describes ks62 in fig 3C.

Best wishes,

Mary Ann

On 17 March 2016 at 03:44,  <no-reply@wormbase.org> wrote:
>  for your c.elegan mutant egl-4(ks62) strai... (Karen Segura)
> Content-type: text/html; charset="utf-8"
> Date: Thu, 17 Mar 2016 03:44:38 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>
>                                                                                       <style type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat Hello,
>  for your c.elegan mutant egl-4(ks62) strain FK234 I see that it is described under overview as "Allele:substitution"I have found no further information on what this substitution is on. Are you guys able to tell me? I have also looked in the original paper evidence by Hirose et.al,2003 and it is not described there either. Thank  you!  <p>Submitted From:
> <br>&nbsp;&nbsp;http://www.wormbase.org/species/c_elegans/variation/WBVar00088291#02-45-3 <a href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088291#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00088291#02-45-3</a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4678. Follow progress on our <a href="https://github.com/WormBase/website/issues/4678">issue tracker</a>.
> <p>
>
> <p>
> Reported by: Karen Segura (k.segura96@gmail.com) <br />
> <span class="fade">17 Mar 16 03:44 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
