### ISSUE TITLE
  Expression data missing for frpr-4 Pa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4680]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Expression data missing for frpr-4<br/>Paper shows expression in RIA, PVM, AVE, I1, DVA :<br/>http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0142938</p>

**Reported by:** Barr********* (bntl************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by draciti** [comment]
Hi Barry,

thank you for writing to WormBase. The expression pattern for the paper has been already curated  and will be available on the live site with the WS253 release- scheduled for May 2016.

Thank you for your feedback,

Daniela
