### ISSUE TITLE
  Hi, Is a way to download all RNAi dat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4681]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>Is a way to download all RNAi data from WormBase? how?<br/>Thanks for your help!<br/>Best,<br/>Jinmin</p>

**Reported by:** Jinm****** (jinm******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by chris-grove** [comment]
Hi Jinmin,


 You can download WormBase RNAi data from our FTP site:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/ONTOLOGY/


The last two files in that directory have the RNAi data. It's the same data but in two different formats.


Best,


Chris Grove

WormBase
