### ISSUE TITLE
  WHAT IS THE FUNCTION OF HSP90B1? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4682]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WHAT IS THE FUNCTION OF HSP90B1?</p>

**Reported by:** roho*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by epaule** [comment]
from the name I would guess some kind of heat shock protein?
But as it is zebrafish gene, you might want to turn on the external links widget and see if ZFIN or EnsEMBL knows more about ti.
