### ISSUE TITLE
  I'm looking at mass spec data in the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4683]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm looking at mass spec data in the genome browser, and occasionally I see peptide sequences like "ERS_EDEE", i.e. with an underscore. Am I correct in assuming that this denotes a modified amino such as a phosphoserine? </p>

**Reported by:** Benj************* (worm****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by gw3** [comment]
Yes, these are markers for post-translational modifications.
The display of mass-spec data is not very detailed on the web-site, so 
if you wish to have more information about a mass-spec peptide, please 
get back to me and I'll see what we know about it in our curation database.

Gary Williams
