### ISSUE TITLE
  Dear Wormbase/Wormmine team, I was us...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4686]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase/Wormmine team,<br/>I was using wormmart and in particular retrieving genes annotated for a given phenotype (as in http://wiki.wormbase.org/index.php/Data_mining:WormMart:Example_3). I had some attempt with wormmine but clearly unsuccessful. Indeed, Gene/Alleles/Phenotype Observed returned as expected only Alleles with the annotation not RNAi experiments. I observed the model.xml and made a second attempt using Gene/Data sets/Bioentitites/Phenotypes observed but got 300k+ results for WBPhenotype:0000365. I probably mis-understood the use of it but did not find http://wiki.wormbase.org/index.php/WormMine very helpful with respect to that issue. I would be very grateful if you could put me on the way or send me a python example script for example.<br/>Thank you very much for the very useful wormbase and for your help!<br/>Best regards<br/>Jacques</p>

**Reported by:** Jacq************ (jacq****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by chris-grove** [comment]
Hi Jacques,

 The easiest way to get a list of genes attributed to a given phenotype via RNAi or alleles is to use the ontology browser on the respective phenotype page. For example, on the phenotype page for "embryo osmotic integrity defective early emb" (WBPhenotype:0000365):

http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000365#03--10

You can see that there are 134 genes/gene-products annotated to this phenotype in the "Ontology Browser" widget. If you click on the link "134 gene products (134 direct)" in the widget, you will be directed to a page that lists all the genes directly or indirectly annotated to this phenotype term, separated by genetic perturbation type (RNAi vs. allele):

http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=embryo%20osmotic%20integrity%20defective%20early%20emb&focusTermId=WBPhenotype:0000365

RNAi results are not currently in WormMine (only allele phenotypes are there now), but are intended to be soon. In general, I would avoid building a query in WormMine that uses the "Data sets" or "Bioentities" from the model browser as I think they give complicated and unintuitive results.

Let me know if you have any questions.

Best,

Chris Grove
WormBase
