### ISSUE TITLE
Chris: Hi Jim, how can I help? visitor_name (visit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4691]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Jim, how can I help?</br>visitor_name (visitor_email): Hi Chris, BLAST/BLAT tool is not working. Browser hangs up and then times out. Any idea how long before it's back up? Thanks.</br>Chris: Hmmm, sorry about that</br>Chris: I'm not sure when it'll be back up, but it's likely that our web team is working on it now. I'll make sure they know if not.</br>visitor_name (visitor_email): Great, thanks for the quick reply!</br>Chris: I'd imagine it will be back up in 10-15 minutes (hopefully)</br>Chris: You're welcome :)</br>visitor_name (visitor_email): Good. I'll check back later.</br>Chris: OK, I can send you an email as soon as I know it's back up</br>visitor_name (visitor_email): Terrific, that will be great. Many thanks!</br>Chris: Sure thing. Anything else I can help with?</br>visitor_name (visitor_email): Not right now, thanks.</br>Chris: OK take care

**Reported by:** Jim ********* (jlis**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans#014--9">http://www.wormbase.org/species/c_elegans#014--9</a>
**Browser:** Chrome 49.0.2623.87

**Comment by chris-grove** [comment]
Getting a 504 Gateway Time-out when trying to load from any browser

**Comment by tharris** [comment]
Should be resolved.

**Comment by chris-grove** [comment]
Yep! Thanks Todd!

**Comment by chris-grove** [comment]
Hey Jim,

BLAST/BLAT should be back up again. Let us know if you have any trouble.

Best,
Chris

**Comment by chris-grove** [comment]
Working fine now, Chris. Thanks a lot and please than your crew for the quick work. 

--Jim
