### ISSUE TITLE
Clustal database missing for WS253

### ISSUE THREAD

**Issue by tharris** [WormBase/website#4693]

**Comment by khowe** [comment]
We created a new top-level folder for miscellenanous "multi species" files that cannot be placed in the per-species folders. The Clustal file is in that folder. 

ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/MULTI_SPECIES/wormpep_clw.WS253.sql.gz

Sorry, should we forgot that the web staging process does something with this file, so should have created a ticket.
