### ISSUE TITLE
  Blast is not working ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4694]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Blast is not working</p>

**Reported by:** Chao******** (cz21***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by raymond91125** [comment]
Hi Chaogu,

I just tested blast using the sample sequence successfully. Could you 
give it another go and if you encounter problems still please give us 
details about your query so that we can better troubleshoot?

Thanks.

Raymond

On 03/25/2016 07:07 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   Blast is not working
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4694. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4694>.
>
> Reported by: Chaogu Zheng (cz2199@columbia.edu)
> 25 Mar 16 14:08
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/48.0.2564.116 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi Chaogu,

Appreciate your feedback! The blast utility is not as stable as we'd hope.

Cheers,

Raymond


On 03/25/2016 09:15 AM, cz2199@columbia.edu wrote:
>
> It is working now. But it was definitely not working earlier today and 
> yesterday.
>
> Thanks for the message.
>
> Chaogu Zheng, Ph.D.
> Department of Biological Sciences,
> Columbia University at the City of New York
> Martin Chalfie's lab, 1012 Fairchild Center,
> 530W 120th street, New York, NY 10027
> Email: cz2199@columbia.edu
> Phone: 212-854-3388 (Lab)
>
> *From: *Raymond Lee <mailto:raymond@caltech.edu>
> *Sent: *Friday, March 25, 2016 12:09 PM
> *To: *cz2199@columbia.edu <mailto:cz2199@columbia.edu>
> *Cc: 
> *reply@reply.github.com 
> <mailto:reply@reply.github.com>; 
> help@wormbase.org <mailto:help@wormbase.org>
> *Subject: *Re: [wormbase-help] Bug Report: Blast is not working ... 
> (ChaoguZheng)
>
> Hi Chaogu,
>
> I just tested blast using the sample sequence successfully. Could you 
> give it another go and if you encounter problems still please give us 
> details about your query so that we can better troubleshoot?
>
> Thanks.
>
> Raymond
>
> On 03/25/2016 07:07 AM, no-reply@wormbase.org 
> <mailto:no-reply@wormbase.org> wrote:
>
>     Bug Report
>
>       Blast is not working
>
>     Submitted From:
>       support /tools/support <http://www.wormbase.org/tools/support>
>
>     This issue has been assigned ticket number: #4694. Follow progress
>     on our issue tracker
>     <https://github.com/WormBase/website/issues/4694>.
>
>     Reported by: Chaogu Zheng (cz2199@columbia.edu
>     <mailto:cz2199@columbia.edu>)
>     25 Mar 16 14:08
>
>     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
>     (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
>
>     This question was reported via the web interface at wormbase.org.
>     You can also email us <mailto:help@wormbase.org> directly.
>
>     -- 
>     -- 
>     You received this message because you are subscribed to the
>     "WormBase: help" group.
>     To post to this group, send email to help@wormbase.org
>     <mailto:help@wormbase.org>
>     To unsubscribe from this group, send email to
>     help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>     For more options, visit this group at
>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>     ---
>     You received this message because you are subscribed to the Google
>     Groups "WormBase: help" group.
>     To unsubscribe from this group and stop receiving emails from it,
>     send an email to help+unsubscribe@wormbase.org
>     <mailto:help+unsubscribe@wormbase.org>.
>
>
>
>
> -- 
> __
> Raymond Lee
> raymond@caltech.edu <mailto:raymond@caltech.edu>
> http://www.WormBase.org/
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687
>


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
Resolved and user contacted.
