### ISSUE TITLE
  Hi, I was wondering where I can downl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4699]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I was wondering where I can download the most complete set of orthologies for the worm (c. elegans) to human?  I'd like the maximum options (e.g. a worm gene can map to multiple human genes, not just the best fits).</p>

**Reported by:** Joe (jmz4*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by epaule** [comment]
we do provide files of predicted orthologs for each species, as example for C.elegans N2:
ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

the File is in record format with records separated by "=\n"

#      Sample Record
#      WBGeneID \t PublicName \n
#      Species \t Ortholog \t Public_name \t MethodsUsedToAssignOrtholog \n

it is per C.elegans gene, and includes predictions from multiple sources (as you can see in the last column).
Different sources use different methods to determine orthologs, but all of them can predict N:N relations.
