### ISSUE TITLE
  Hi, is there a way to find out all th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4700]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, is there a way to find out all the *null* alleles available? I'm looking to get null mutants for a variety of genes and I'm having a hard time systematically finding null strains. I can see the various strains available per gene, but I have no idea whether they are null or not, unless I go to google and search for the strain names and see if it has been shown to be a null strain.<br/>Thank you!<br/>-A</p>

**Reported by:** Alej**************** (aemo**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 5.1; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by kyook** [comment]
Hi Alejandro,

Unfortunately, there is no straightforward way to get this list.  The
"null" state of a gene is only annotated in reference to an allele that has
been shown to abrogate all function for a given gene; therefore you will
only create this list by perusing alleles.

That said, I've been working on getting you a list of alleles, and their
respective genes, that have been annotated as nulls. I will send it as soon
as I can. In the mean time, let me know if there are particular genes you
are interested in.

Apologies for the delay.
Karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Mon, Mar 28, 2016 at 3:29 PM, <no-reply@wormbase.org> wrote:

> Question:
>
>   Hi, is there a way to find out all the *null* alleles available? I'm
> looking to get null mutants for a variety of genes and I'm having a hard
> time systematically finding null strains. I can see the various strains
> available per gene, but I have no idea whether they are null or not, unless
> I go to google and search for the strain names and see if it has been shown
> to be a null strain.
> Thank you!
> -A
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4700. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4700>.
>
> Reported by: Alejandro Montenegro (aemonten@gmail.com)
> 28 Mar 16 22:30
>
> Mozilla/5.0 (Windows NT 5.1; rv:44.0) Gecko/20100101 Firefox/44.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

**Comment by kyook** [comment]
Alejandro Montenegro-Montero
Apr 6 (1 day ago)

to me 
Dear Karen,

Thank you very much for your reply.

Having such list will surely be useful for plenty of people, so I really appreciate your efforts. 

At present, particularly, I'm interested in NHR genes, but as I told you, having a list for all null alleles available, would surely be a tremendous help for plenty of people.

Please let me know when you have a list and if you need me to help out, let me know.

Best,

-A

**Comment by kyook** [comment]
Karen Yook <karen@wormbase.org>
AttachmentsApr 6 (1 day ago)

to Alejandro, Mary 
Hi Alejandro and Mary Ann, 

I generated a list of alleles that were annotated with "Null", "Predicted_null_via_sequence", or "Probable_null_via_phenotype". My next step was to use in the WormMine to gather all other data (allele name and gene) for these variations, but WormMine is currently down.  

Mary Ann, would you be able to use this as a key set to get the other data for Alejandro? Otherwise, I will be waiting until WormMine is back up to finish generating this file.

**Comment by kyook** [comment]
Mary Ann Tuli
Attachments5:04 AM (10 hours ago)

to Alejandro, me 
Dear Alejandro,

Attached is a file as requested.

The columns are:
WBVarID; Var Public Name; WBGeneID; Gene Public Name

I hope this helps.

**Comment by kyook** [comment]
Alejandro Montenegro-Montero
1:29 PM (2 hours ago)

to me, Mary 
Thanks!
Super helpful!

Best,

-A
