### ISSUE TITLE
Please give description of each...green box refer ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4701]
*Help Desk query collected when no chat operators were online. Follow up required.*

Please give description of each...green box refer to....it could be helpful new users without any assistance

**Reported by:** sara****** (skal****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00241556#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00241556#02-45-3</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by epaule** [comment]
the bold text on top of the boxes describe what they represent:
strains carrying rh148 alone in blue 
and
strains carrying rh148 that are available from the CGC in yellow

The overlap (as in CGC strains that only carry the allele and no other one) is in green (as yellow overlaid with blue become green).
It is supposed to be similar to the Venn diagrams used in Mathematics, but I guess picking green as a colour of importance is suboptimal.
