### ISSUE TITLE
Tijsterman + Plasterk 2004 should be cited in phen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4703]
*Help Desk query collected when no chat operators were online. Follow up required.*

Tijsterman + Plasterk 2004 should be cited in phenotypes (RNAi resistant germline)

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004682#0-c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00004682#0-c-10</a>
**Browser:** Safari 6.2.8

**Comment by chris-grove** [comment]
Hello Alexandra,


 Thanks for the info. Would you mind submitting this annotation using our new Phenotype Form?


http://www.wormbase.org/submissions/phenotype.cgi


You can link to this form from the "Phenotypes" link under the "Submit data" menu on the WormBase homepage. You would just need to enter your name, the paper PubMed ID, the allele and the phenotype.


When the information goes live on the website, you will be credited with the annotation.


Thanks!


Chris Grove

WormBase
