### ISSUE TITLE
layout phenotypes: I have been going through pheno...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4704]
*Help Desk query collected when no chat operators were online. Follow up required.*

layout phenotypes: I have been going through phenotypes the whole day and find some of the layout disturbing. The gray background helps to focus on phenotypes, that is useful. Individual RNAi experiments are alternated in white and blue background- but not always, sometimes several experiments from different papers are all white. Did not find why. I think with the grey for phenotypes it may even be sufficient to have all RNAi experiments with white bachground and remove the blue. 
 Readibility can be further improved by removing for example details like "Entity: adult Ce, abnormal" from the row of the phenotypes- better to remove it altogether or squeeze into details. I also think that RNAi experiment number can stand at the end after paper in details
thanks for taking note of those ideas, I appreciate your work!

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00022850#0-c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00022850#0-c-10</a>
**Browser:** Safari 6.2.8

**Comment by chris-grove** [comment]
Hi Alexandra,


 Thanks for the feedback and the suggestions. The blue/white alternating pattern is basically for any similar set of phenotype analysis experiments, whether they differ by phenotype, genetic perturbation type (RNAi vs. allele, for example), or by distinct sets of entities affected. It's possible that we could replace this alternating color row view with just a table with all the relevant information clearly separated into distinct rows.


The entities affected display is brand new and we are still playing around with what works best. We would like to make it clear to users which life stages and anatomy objects are affected as a result of the phenotype without too much digging into the details, as this may be of particular interest to those browsing the phenotypes. However, if we find that many people prefer these to be hidden, as you've suggested, then we can do that instead.


Best,


Chris Grove

WormBase

**Comment by sibyl229** [comment]
Hi @chris-grove  For the phenotype table, @miyukimouse and I have made some changes, and hopefully this helps the user understand that the entities is the secondary grouping of the rows, and why the color changes for RNAi corresponds to the change in entity. http://staging.wormbase.org/species/c_elegans/gene/WBGene00022850#0c-4-3 Do you think this works? Do you have additional thoughts on this? Thank you!

**Comment by chris-grove** [comment]
@sibyl229  Thanks, I think it looks fine as is. I'll close the issue.
