### ISSUE TITLE
  for toca-1, the yc20 allele informati...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4707]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;for toca-1, the yc20 allele information is correct. However, yc3 is listed exactly the same as yc20. We do not know what the lesion is in yc3. In fact, there is no evidence that yc3 is an allele of toca-1. Please delete all the yc3 information on wormbase.<br/>Thanks<br/>visitor_name</p>

**Reported by:** Dan ***** (dast***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by tuli** [comment]
Dear Dan,

Thank you for writing to WormBase.

I have removed all the sequence information associated with yc3 and
apologise for the mistake.

You'll see the update in release WS254 of WormBase.

Best wishes,

Mary Ann

On 31 March 2016 at 17:31,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   for toca-1, the yc20 allele information is correct. However, yc3 is listed
> exactly the same as yc20. We do not know what the lesion is in yc3. In fact,
> there is no evidence that yc3 is an allele of toca-1. Please delete all the
> yc3 information on wormbase.
> Thanks
> Dan Starr
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #4707. Follow progress on our
> issue tracker.
>
> Reported by: Dan Starr (dastarr@ucdavis.edu)
> 31 Mar 16 16:32
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101
> Firefox/44.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
