### ISSUE TITLE
  Hello,  We used the F32D8.11 RNAi fro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4709]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>We used the F32D8.11 RNAi from the ORF library and are confused what your remarks mean when you list it as "dead." Could you please elaborate? <br/>Thank you, <br/>visitor_name</p>

**Reported by:** Kevi******** (kmde********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9

**Comment by raymond91125** [comment]
Hi Kevin,

F32D8.11 appears to be a valid gene because it has been "Resurrected" 
(In Overview->Remarks, [091009 pad] Resurrected based on further 
analysis ...).

Let us know if you have further questions.

Thanks.

Raymond





On 04/01/2016 10:45 AM, no-reply@wormbase.org wrote:
> Question:
>
>   Hello,
> We used the F32D8.11 RNAi from the ORF library and are confused what 
> your remarks mean when you list it as "dead." Could you please elaborate?
> Thank you,
> Kevin Deehan
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4709. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4709>.
>
> Reported by: Kevin Deehan (kmdeeh16@g.holycross.edu)
> 01 Apr 16 17:45
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 
> (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tuli** [comment]
@Paul-Davis @gw3 

I think there is sound argument for having Status in the grey summary box within Overview.
It's tedious to read Remarks and it's especially tedious to have to read them all to find out the current Status. I can easily see why this user thought the Gene was Dead.

**Comment by Paul-Davis** [comment]
These are all gene comments @tuli this is something for you to discuss with the webteam so I'm not sure why you CC'd Gary and I?....unfortunately not all the comments in WBGenes have a date stamp to give any sort of order context.

**Comment by tuli** [comment]
I just wanted your opinion.

**Comment by Paul-Davis** [comment]
Didn't the live dead suppressed used to be in the overview? Maybe there could be some Status with a description of the meaning of Live/Dead/Suppressed instead of just exposing the tag (again)?
