### ISSUE TITLE
  How can I delete Email addresses from...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4710]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I delete Email addresses from "My Profile"?<br/>My new primary Email address is Andrea.Schlotterer@t-online.de<br/>Please delete my two old Email addresses:<br/>visitor_email<br/>Andreas.Schlotterer@t-online.de</p>

**Reported by:** Andr************** (Andr*************************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by tuli** [comment]
Response from Juancarlos.

FAO @ceciliaWBPerson1 

Hello Andrea,

The "Person" curator is on vacation for a week, but she will remove
those email addresses when she returns.

best wishes,
Juancarlos
