### ISSUE TITLE
Natural variants and polymorphisms no longer displayed in Genetics widget

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4711]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Stefan, how can I help?</br>visitor_name (visitor_email): hello, i am wondering what happened to the natural variation section under the "genetics" tab</br>visitor_name (visitor_email): ..when looking at a gene</br>Chris: I think it may have been merged with polymorphisms, but let me take a look</br>visitor_name (visitor_email): polymorphisms is also gone</br>Chris: Hmmm, yes I see that</br>visitor_name (visitor_email): i noticed this two weeks ago</br>Chris: This may have changed with the latest WormBase release, WS252</br>Chris: Let me take a look at our internal records and see what I can find</br>visitor_name (visitor_email): great, thanks</br>Chris: no problem</br>Chris: Hi Stefan, this looks to be a bug</br>Chris: Apologies. Is there specific data I can get for you while we fix this?

**Reported by:** stef** (szdr**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00077563#0g6-49f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00077563#0g6-49f-3</a>
**Browser:** Chrome 49.0.2623.87

**Comment by tuli** [comment]
Related to #4001 
Staging is down, so I can't check the status.

**Comment by tuli** [comment]
@tharris 
Can you look into this please. Related to new help ticket #4760

**Comment by tuli** [comment]
@chris-grove 
Do you want to point the user to staging or did they maybe get back to you personally and you helped them?

**Comment by chris-grove** [comment]
@tuli  I had not sent them to staging. I will do that now.

**Comment by chris-grove** [comment]
Hello Stefan,


Thanks for letting us know about the missing polymorphism data in the Genetics widget of the gene page. This has now been fixed on our staging site:


http://staging.wormbase.org/species/c_elegans/gene/WBGene00077563#0-4-10


This will go live on our website at the end of May. In the meantime, you can use the staging site to get this type of information if you need it, but please note that our staging site is not always stable and is not intended for regular use.


Thanks again!


Chris Grove

WormBase
