### ISSUE TITLE
  Hello -  I would like to generate a l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4713]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello - <br/>I would like to generate a list of phenotypes (RNAi and/or mutant) associated with a list a ~300 genes.  But I only have the sequence name (not the gene name for these genes).   I find wormmine extremely confusing so the more detail the better!!  Thank you so much!</p><p>What were you doing? <br />&nbsp;&nbsp;Using wormmine, genes --> phenotypes.  I can only get it to work if I put in a single gene name.  Can I use sequence names?  How should list of sequence names (or gene names, if I can figure out how to convert the list) be separated? </p>

**Reported by:** Mega********* (mega*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by chris-grove** [comment]
Hi Megan,


 WormMine is currently being serviced, but in the meantime you can try this tool:


http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/fraqmine.cgi


Just paste in your list of genes and click on "query list". This will return tab-delimited text, which can be imported into a spreadsheet (like Excel) and will have a column for allele-based phenotypes and another for RNAi-based phenotypes.


Hope that helps!


Best,


Chris Grove

WormBase

**Comment by WenChenWormBase** [comment]
User had problem opening the csv file, helped her by sending her the file in .xlsx format. 

----------------------------
Dear Wen –

    Many, many thanks for your help with this.  The list you sent me is great – exactly what I needed. 

Best wishes –

megan
