### ISSUE TITLE
Re-sync of WS253 FTP directory from EBI to ftp.wormbase.org

### ISSUE THREAD

**Issue by khowe** [WormBase/website#4714]
We have updated the OMIM xref file in the WS253 release distribution:

ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS253

(the CHECKSUMS files has also been updated accordingly). I believe that this will sync automatically to ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/. I will check tomorrow to see if this has happened, and reassign to @tharris if not.

**Comment by tharris** [comment]
Remirrored / confirmed.
