### ISSUE TITLE
  In the WB FAQ section found here: htt...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4715]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;In the WB FAQ section found here: http://www.wormbase.org/about/Frequently_asked_questions#6e59c24dab31078--10<br/>There is this section:  How can I retrieve the best blast_p scored homologies of worm genes?<br/>The best_blastp_hits are described as having 15 columns; however, the same file for B_malayi (WS249) has 25 columns.  While some are obvious (Ensembl, FlyBase, UniProt) many of the database prefixes for example, JA:  RP:  SGD:  OV:  etc... are not described, nor can I find any information/ReadMe file that describes such within the Annotation dir on the ftp site.<br/>Would you kindly point me to where I can get this column info. for DB results, or send it to me directly?<br/>Best,<br/>visitor_name</p>

**Reported by:** Walt******* (wlor***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by epaule** [comment]
the protein prefixes are:

C.elegans => 'WP',
EnsEMBL  => 'ENSEMBL',
D.melanogaster => 'FLYBASE',
S. cerevisiae => 'SGD',
UniProt/SW => 'SW',
UniProt/TR => 'TR',
C.briggsae => 'BP',
Human - IPI  => 'IP',
C.remanei => 'RP',
P.pacificus  => 'PP',
C.japonica  => 'JA',
C.brenneri => 'CN',
B.malayi => 'BM',
O.volvulus  => 'OV',
S.ratti  => 'SRP',
H-Invitational => 'HI',

WS252 has as example 29 columns:
the first column is the query protein, then followed by 14 pairs of id / e-value per database.
