### ISSUE TITLE
  I want to get the sequence of the gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4724]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to get the sequence of the gene cct-2 of c elegans.But I coudn't see the page where I can copy the sequence?</p>

**Reported by:** Abdi***** (abdi******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by chris-grove** [comment]
Hi Abdi,


 You can find this information in the "Sequences" widget on the cct-2 gene page:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000378#0g--10


Just click on the little double-helix icon for the transcript or CDS or protein to get the sequence.


Let me know if you have any questions.


Best,

Chris Grove

WormBase
