### ISSUE TITLE
  Hello Overview at  http://www.wormbas...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4726]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>Overview at <br/>http://www.wormbase.org/species/all/interaction/WBInteraction000501296<br/>is not for the interaction cyn-4 : dpy-10 as it should be:<br/>"The dpy-10 unspliced variant was more abundant in mog-6 dpy-10 animals compared to dpy-10 animals alone".</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by kyook** [comment]
Hi Jonathan,

I've corrected the error, the incorrect allele was entered by mistake
leading to cyn-4 being linked to these data.  This correction will be in
the WS254 release of WormBase.

Thank you for pointing out this error.
Best wishes,
Karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, Apr 7, 2016 at 2:16 AM, <no-reply@wormbase.org> wrote:

> Content Correction
>
>   Hello
> Overview at
> http://www.wormbase.org/species/all/interaction/WBInteraction000501296
> is not for the interaction cyn-4 : dpy-10 as it should be:
> "The dpy-10 unspliced variant was more abundant in mog-6 dpy-10 animals
> compared to dpy-10 animals alone".
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4726. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4726>.
>
> Reported by: Jonathan J Ewbank (ewbank@ciml.univ-mrs.fr)
> 07 Apr 16 09:17
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101
> Firefox/45.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
