### ISSUE TITLE
visitor_name (visitor_email): Hi, I wonder if I ca...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4730]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I wonder if I can get the longest isoform for a long list of genes from Wormbase.

**Reported by:** Joyc* (qzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#01-23-6">https://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 49.0.2623.110

**Comment by chris-grove** [comment]
Duplicate #4731 closing
