### ISSUE TITLE
  Dear WormBase curator, I have provide...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4732]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase curator,<br/>I have provided large amounts of reporter expression pattern data to WormBase through the years. I have just noticed that the first expression pattern object, Expr162, for unc-68 is incorrectly assigned. This is one of the expression pattern descriptions that I provided. As it states in the expression pattern object, this description belongs to F41E7.1, not unc-68. I am concerned that many of my expression pattern descriptions may be wrongly assigned again. Something along these lines happened several years ago now and I am concerned that the same things has happened again. I haven't gone searching to see if others are similarly wrongly assigned so I do not know if this is a problem just for the unc-68 expression pattern object or more extensive.  The earlier problem before was corrected for all my contributions, but this took some effort. It was as if a look up table had been messed up, or as if a column of a spreadsheet had been sorted in isolation. These data were all correct in WormBase previously and I do not know when the problem has arisen, but I have only just noticed it and it must be a WormBase data handling / presentation problem. Hopefully you can see how extensive the problem is easier than I can and can solve the issue. <br/>Yours,  Ian.</p>

**Reported by:** Ian **** (i.a.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

**Comment by draciti** [comment]
Dear Ian,

thanks for bringing this to our attention.

I have checked Expr162 and both F41E7.1 and unc-68 were listed as gene connections
I have deleted unc-68.
Expr162 is correctly listed on the F41E7.1 gene page

http://www.wormbase.org/species/c_elegans/gene/WBGene00009617#0-13-10

I spot checked the expression patterns for genes submitted by your lab and there seem to be only one gene assigned per pattern, which is good.
I will do a more systematic search but my impression is that this is an isolated case. If you noticed other pattern-gene connections that seem odd please send them our way.

Many thanks!

Daniela

**Comment by draciti** [comment]
Hello Daniela,

It is good to hear from you. I trust you are well. 

It would be great if it is an isolated problem and thanks for checking it through. I don’t understand how this could have occurred but then I don’t know how WormBase works from other than the front end. 

Best wishes, Ian.

**Comment by draciti** [comment]
Hello Ian

I confirm this was an isolated case. According to the history tables, I have 'touched' that annotation on July 2015 to conform it to current curation standard- which require the use of 'certain' 'uncertain' 'partial' qualifiers.

F41E7.1 was described to be expressed certainly in the excretory cell and canal and possibly in the g2 gland cell. For some reason, when generating another row in the database to capture the uncertainty of expression in g2, unc-68 (the gene associated to the row immediately before) got inserted.

I double checked all your curated papers and everything seems to be ok.

Thanks again for reporting this and please keep informing us should you notice something off again.

Thanks!

Daniela
