### ISSUE TITLE
visitor_name (mrvisitor_name94@gmail.com): hello v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4734]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (mrvisitor_name94@gmail.com): hello</br>visitor_name (mrvisitor_name94@gmail.com): Can i get the draft genome of wuchereria bancrfti

**Reported by:** bhag** (mrbh****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 49.0.2623.112

**Comment by brucebolt** [comment]
Dear Bhagya

The draft genome of Wuchereria bancrofti is available through the WormBase ParaSite website: http://parasite.wormbase.org/Wuchereria_bancrofti_prjeb536/Info/Index/

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
