### ISSUE TITLE
visitor_name (visitor_email): Do you post the cDNA...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4737]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Do you post the cDNA for a particular gene?

**Reported by:** Dani******* (mdma*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0c27eg-9386-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0c27eg-9386-3</a>
**Browser:** Safari 9.0.2

**Comment by Paul-Davis** [comment]
Dear Daniel,

Unfortunately does not stock or provide any biological reagents. 
Information on how to obtain these reagents can be found on this page:

http://www.wormbase.org/resources/reagents#4--10

Under the cDNA section.

If you require any further information, please feel free to email.

Thanks

Paul

On 11/04/2016 22:41, no-reply@wormbase.org wrote:
> online chat Daniel Mann (mdmann@eagles.usi.edu): Do you post the cDNA 
> for a particular gene?
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0c27eg-9386-3 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0c27eg-9386-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0c27eg-9386-3> 
>
>
> This issue has been assigned ticket number: #4737. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4737>.
>
> Reported by: Daniel Mann (mdmann@eagles.usi.edu)
> 11 Apr 16 21:42
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
