### ISSUE TITLE
  How do I download all protein (or gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4742]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I download all protein (or gene) fasta files for proteomics database searching?</p>

**Reported by:** Eric (spoo**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by azurebrd** [comment]
From Todd : 
Try the FTP site:

For example for the WS253 release of WormBase:
ftp://ftp.wormbase.org/pub/wormbase/species/releases/WS253/species/c_elegans/PRJNA13758

Or to always fetch the most current version:
ftp://ftp.wormbase.org/pub/wormbase/species/releases/current-production-release/species/c_elegans/PRJNA13758

Protein:
ftp://ftp.wormbase.org/pub/wormbase/species/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS252.protein.fa.gz

Genes:
ftp://ftp.wormbase.org/pub/wormbase/species/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS252.mRNA_transcripts.fa.gz
