### ISSUE TITLE
Adding species column to list of proteins on Motif pages

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4743]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Cristina, how can I help?</br>visitor_name (visitor_email): Hello!  In the search box on the Wormbase home page, I can't seem to be able to search by "motif".  Is it possible to add this feature?</br>Chris: Because of the large number of types, the drop down list on the homepage is limited</br>Chris: but I agree it would be convenient to have it readily available</br>Chris: How are you getting the list of genes exactly?</br>visitor_name (visitor_email): Sorry!  I think I got it!  I think this page that you directed me to is exactly what I was looking for!</br>Chris: OK, great!</br>Chris: Is there anything else I can help you with?</br>Chris: How are you trying to narrow down the search?</br>Chris: Oh, nevermind, I see what you mean</br>Chris: Unfortunately, we can't narrow down the results to one species directly, but I will create a ticket to display the species of the resulting protein lists that you could then sort or filter on</br>Chris: Sure, you're welcome. In the meantime, I think sorting the list of protein names and scanning by eye for the protein names that don't start with a prefix for one of the other species should work</br>Chris: You're welcome. Is there anything else I can help you with?</br>visitor_name (visitor_email): I think I'm all set!  Thanks, again, and have a great day!</br>Chris: OK, thanks. You too!

**Reported by:** Cris***************** (cagu*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002717#0d8c7-961-5">http://www.wormbase.org/species/c_elegans/gene/WBGene00002717#0d8c7-961-5</a>
**Browser:** Safari 8.0.2

**Comment by chris-grove** [comment]
On any given Motif page, say:

http://www.wormbase.org/resources/motif/INTERPRO:IPR016197#01--10

![screen shot 2016-04-12 at 12 46 17 pm](https://cloud.githubusercontent.com/assets/611382/14473397/a2087c44-00ac-11e6-9a78-124872988fb1.png)

There is a list of proteins that have the motif, but there's no way to sort or filter for proteins from a particular species. Can we add a species column so that users can sort and filter on species?
Thanks!

**Comment by sibyl229** [comment]
Hi @chris-grove The species column has been added to the homolog table in Motif Overview widget http://staging.wormbase.org/resources/motif/INTERPRO:IPR016197#012--10 Thanks for checking!

**Comment by chris-grove** [comment]
Looks good @sibyl229 !! Thanks!!
