### ISSUE TITLE
xrefs to NCBI Gene looping back to WormBase rather than NCBI

### ISSUE THREAD

**Issue by tuli** [WormBase/website#4746]
Looking at unc-119 http://www.wormbase.org/species/c_elegans/gene/WBGene00006843

External links has link to NCBI gene 176519, which should go to http://www.ncbi.nlm.nih.gov/gene/?term=176519 but actually goes to http://www.wormbase.org/species/c_elegans/gene/WBGene00006843 (both the NCBI and the 176519 links).

Timestamps state: [date]_load_refseq_xrefs 

I'm not sure whether this is a build or website issue.

**Comment by khowe** [comment]
Looking at the Tree view, the data looks correct. 

This is probably an issue with the mapping between database names and URLs. These are maintained in a file in the website repo I think.

**Comment by sibyl229** [comment]
Hi @tuli the NCBI gene link is working on staging:  http://staging.wormbase.org/species/c_elegans/gene/WBGene00006843#02-9gh-3 . Here is where you can check the currently configured external urls. https://github.com/WormBase/website/blob/staging/root/templates/config/external_urls

**Comment by tuli** [comment]
Thanks. Shall I close the ticket or will you @sibyl229 (not sure whether there are still things you need to do).

**Comment by sibyl229** [comment]
Thanks @tuli . I don't think there is more about the ticket. Closing.
