### ISSUE TITLE
  ftp://ftp.wormbase.org/pub/wormbase/s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4748]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/c_elegans.PRJNA13758.WS250.CDS_transcripts.fa.gz<br/>cant download, error said there is no such file</p>

**Reported by:** Joyc* (qzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by khowe** [comment]
This is a symlink to a file in this folder:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/

...which seems to be missing one or two files, including the one the user is trying to download. This folder should be a direct mirror of this one at the EBI:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS250/species/c_elegans/PRJNA13758/

...which contains the missing files. So it seems like the mirror partially failed.

**Comment by azurebrd** [comment]
From #4749 
 another error
ftp://ftp.wormbase.org/pub/wormbase/species/c_briggsae/sequence/transcripts/c_briggsae.PRJNA10731.WS250.CDS_transcripts.fa.gz
No content after download

**Comment by chris-grove** [comment]
Email message to zhaozhao:
"Hi Zhaozhao,

 Thanks for reporting the problems with the FTP site. It appears there was a problem with a handful of files being populated. Our team is working on a fix for it now. We'll let you know when it's fixed.

Best,
Chris"

**Comment by tharris** [comment]
I remirrored from Hinxton and picked up the missing files.
