### ISSUE TITLE
  another error ftp://ftp.wormbase.org/...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4749]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;another error<br/>ftp://ftp.wormbase.org/pub/wormbase/species/c_briggsae/sequence/transcripts/c_briggsae.PRJNA10731.WS250.CDS_transcripts.fa.gz<br/>No content after download</p>

**Reported by:** qzha***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by azurebrd** [comment]
merge into #4748
