### ISSUE TITLE
Tissue enrichment analysis reverse proxy setup

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#4750]
We have ready a CGI for the tissue enrichment analysis that Paul S. mentioned in the last meeting that will need a reverse proxy so that it can be offered to WormBase users with a proper URL.
The CGI is at <http://wobr.caltech.edu:81/~azurebrd/cgi-bin/tissue_enrichment_analysis.cgi>
We suggest a WormBase URL <http://www.wormbase.org/enrichment/tea>

**Comment by tharris** [comment]
Are you intending there to be other tools available under enrichment/?

**Comment by paulwsternberg** [comment]
I think the idea is to have this location handle
enrichemnt//tissue enrichmet (TEA)
/phenotype enrichment
/gene ontology
+ potentially others but these three for now


On Apr 21, 2016, at 6:40 AM, Todd Harris <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Are you intending there to be other tools available under enrichment/?

**Comment by tharris** [comment]
This is in place now at:

http://wormbase.org/tools/enrichment/tea

Your cgi is revealing the name of the back end host. can you fix so that users stay on wormbase.org?

**Comment by tharris** [comment]
Thanks @paulwsternberg. That makes sense. The pedant in me hates to introduce extra layers to hierarchies unless they are meaningful.

**Comment by raymond91125** [comment]
@tharris, Please change the upstream to "http://wobr.caltech.edu:81/tools/enrichment/tea". Parenthetically, this target is a folder which contains cgi and a data folder in which stores files that user can fetch.

**Comment by raymond91125** [comment]
@tharris, we have submitted a manuscript thus eager to see the wormbase link working. The googleanalytics code has been implemented as well. Let me know what else we need to do.

**Comment by tharris** [comment]
It doesn't work. Your configuration is still broken.  The CGI doesn't load even going directly to the URL.

**Comment by azurebrd** [comment]
I think he wants it at 
http://wobr.caltech.edu:81/tools/enrichment/tea/tea.cgi

**Comment by tharris** [comment]
I didn't know the name of the CGI.  That's different from the request above which is this:

       /tools/enrichment/tea -> /tools/enrichment/tea/tea.cgi

Would you rather have the name of the cgi displayed?
       
       /tools/enrichment/tea/tea.cgi -> /tools/enrichment/tea/tea.cgi

**Comment by tharris** [comment]
And the analytics tracker isn't installed...

**Comment by azurebrd** [comment]
I don't know what Raymond wants about the CGI.

The analytics tracker was added on April 21st.  Your email said "No, it's still not working. I think you need to fix your server name issue first."  I replied with "Is it working on the other pages that don't have the server name issue ? e.g. http://www.wormbase.org/submissions/allele_sequence.cgi"  When I didn't hear back, the daily cronjob updated the header and footer back to the version without google analytics.  I've added that version back, but the cronjob is going to get rid of it at 4am.  If the analytics is working let me know to make it part of the cronjob.  If it isn't, let me know how to change it.

**Comment by raymond91125** [comment]
What we need is not a proxy to the CGI script directly but to the folder that contains it. FYI, the CGI is here <http://wobr.caltech.edu:81/tools/enrichment/tea/tea.cgi>.
We also need to proxy for files in the data folder, e.g. <http://wobr.caltech.edu:81/tools/enrichment/tea/data/hyperGeo/hyperGeo1461793280.62377.txt>. The data files are dynamically generated. I hope this is clear and doable. If not, we probably should talk in a conf call.

**Comment by tharris** [comment]
Ok! @raymond91125 thank you for clarifying what you want. 

`wormbase.org/tools/enrighment/tea` now loads `/tools/enrichment/tea/tea.cgi`

and

`wormbase.org/tools/enrighment/tea/data` now loads the data dir `/tools/enrichment/tea/data`

I have confirmed the reappearance of the tracker. Please remove your crontab entry that strips it.

**Comment by azurebrd** [comment]
Sure thing, I've updated the cronjob that gets the header and footer from WormBase (to maintain appearance for new releases) to also add the google analytics to the header.  The header is slightly different, but should be functionally the same.  So I think it should still work, but let me know if it doesn't.

**Comment by azurebrd** [comment]
For clarity, after talking to Raymond, the URL that people should refer to for this form should be : 
http://www.wormbase.org/tools/enrichment/tea/tea.cgi

**Comment by tharris** [comment]
Okay, wait, so you DO want the name of the CGI concealed now?

**Comment by azurebrd** [comment]
I don't think I do.

**Comment by azurebrd** [comment]
I think it's fine as it is, and people should go to http://www.wormbase.org/tools/enrichment/tea/tea.cgi  or  http://www.wormbase.org/tools/enrichment/tea/    but  http://www.wormbase.org/tools/enrichment/tea doesn't work (it loads, but it doesn't post properly)

**Comment by azurebrd** [comment]
I made that "clarifying" statement because I realized the actual URL that users should use wasn't anywhere in the ticket.

**Comment by raymond91125** [comment]
That should do it. Thanks everyone.
