### ISSUE TITLE
find PWM/PFM data with JBrowse

### ISSUE THREAD

**Issue by xdwang** [WormBase/website#4751]
PWM and PFM data can be found using GBrwose, but not with JBrowse yet. Please refer to this website to see how to look for wormbase annotated PWM/PFM motifs:  http://gmod.org/wiki/MotifFinder.pm

**Comment by scottcain** [comment]
Reimplementing the motiffinder plugin for JBrowse would be a fairly significant development effort.  I'm pretty sure it can be done, but I'm not positive.

**Comment by scottcain** [comment]
Related: https://github.com/WormBase/website/issues/4913

@xdwang and @chris-grove I think I have the motif finder implemented for JBrowse.  Please take a look on staging at http://staging.wormbase.org/tools/genome/jbrowse/full.html and then select "add motif search track" from the File menu in JBrowse.  I'm not exactly happy with the user interface, but i think all of the required items are present (ability to set cutoff percentage and ability to add custom matrix).  Please take a look and let me know if you agree that it works as expected.

**Comment by chris-grove** [comment]
@scottcain 
Yes, it looks good. I'm getting all the hits that I would expect. @xdwang is currently not working for WormBase, so I wouldn't wait for a response from her.

**Comment by scottcain** [comment]
Old ticket made obsolete by development of a pwm plugin for jbrowse.  Closing...
