### ISSUE TITLE
To whom it may concern:
Hello! I'm a senior at Roc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4752]
*Help Desk query collected when no chat operators were online. Follow up required.*

To whom it may concern:
Hello! I'm a senior at Rock Canyon High School and this year me and my classmates conducted individual research projects on topics of our choosing. My group researched how coffee and Namzaric affect the toxicity of Alzheimer's disease in C. elegans strain CL2006. Our journal article will be published and featured in our high school journal. For the cover, we were asked to find a professional image of C. elegans which will be displayed along with other photographs. We found a photo that was credited to your website (link: http://wormclassroom.org/image/c-elegans-and-c-briggsae) that we would love to use. It is a photo of a C. elegans and C. briggsae intertwined. Would we have your permission to use this image? Are there any steps we would need to complete in order to use this image? 

Thank you so much!
visitor_name

**Reported by:** Alli********* (alli******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 49.0.2623.110

**Comment by draciti** [comment]
does anyone know who 'produced' the image originally? this website credits WormBase but I am not sure is the right attribution. thanks
http://wormclassroom.org

**Comment by azurebrd** [comment]
Hello Allie, and thank you for contacting us about the proper way to
give us attribution.  I do see that wormclassroom.org credit us for
the picture, but our picture curator cannot find where that picture
came from.  I can only say that I don't think we have the rights to
the picture, and we don't know who does.  I suppose you could credit
wormclassroom.org for it, even though they credit us.

I'm sorry we couldn't give you a definitive helpful response, and best
wishes with your research and publications.

Juancarlos, Help Desk


> To whom it may concern:
> Hello! I'm a senior at Rock Canyon High School and this year me and my
> classmates conducted individual research projects on topics of our
> choosing. My group researched how coffee and Namzaric affect the
> toxicity of Alzheimer's disease in C. elegans strain CL2006. Our
> journal article will be published and featured in our high school
> journal. For the cover, we were asked to find a professional image of
> C. elegans which will be displayed along with other photographs. We
> found a photo that was credited to your website (link:
> http://wormclassroom.org/image/c-elegans-and-c-briggsae) that we would
> love to use. It is a photo of a C. elegans and C. briggsae
> intertwined. Would we have your permission to use this image? Are
> there any steps we would need to complete in order to use this image? 
> 
> Thank you so much!

**Comment by azurebrd** [comment]
I made that image about 15 years ago, although it has been variously credited to a variety of people since then. I still have the photoshop layers kicking around somewhere.

Todd

**Comment by azurebrd** [comment]
Thanks Todd.

In looking at the instructions for Citing Wormbase
http://www.wormbase.org/about/citing_wormbase#--10

It looks like you can just "Include in your acknowledgments, a
statement thanking WormBase, ‘We thank WormBase’."

Thanks again Allie, and good luck,
Juancarlos


Todd Harris writes:
> I made that image about 15 years ago, although it has been variously
> credited to a variety of people since then. I still have the
> photoshop layers kicking around somewhere.
> 
> Todd
>
