### ISSUE TITLE
  Hi, I would like to know if there is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4757]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I would like to know if there is a simple protocol to fix in a 6-well plate and stain liver fat in C. elegans with Oil Red O?</p>

**Reported by:** Bele* (bbio***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by epaule** [comment]
WormBase focuses mainly on the bioinformatic side of C.elegans research. But we have a collection of lab protocols as section of WormBook (www.wormbook.org).
You could also try the WormBase forum (forums.wormbase.org), as there is a very active community exchanging lab knowledge.
