### ISSUE TITLE
How to download clec gene class (264 members) of C...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4758]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to download clec gene class (264 members) of C. elegans ?

**Reported by:** Chai******** (bhat*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/gene_class/clec#01--10-0">http://www.wormbase.org/resources/gene_class/clec#01--10-0</a>
**Browser:** Microsoft Internet Explorer 10.0

**Comment by azurebrd** [comment]
Dear Chaitra,

Thank you for writing to WormBase. To download a list of all elegans
clec gene class members, please go to the clec Gene Class Summary
page: http://www.wormbase.org/resources/gene_class/ then click on
"Caenorhabditis elegans(264 members)" within the Current Genes widget.
This will expand the list and you'll see a "Save Table" option. Click
on this to see different options on how to save the list.  I hope this
answers your query, but please write back if you need further help.

Best wishes,

Mary Ann
