### ISSUE TITLE
  On gene pages, the genetics section u...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4760]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;On gene pages, the genetics section used to have a table containing natural genetic variation. This seems to have gone and I can't find that information anywhere else. Is it still available somewhere?</p>

**Reported by:** Simo******** (simo*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/537.86.4

**Comment by tuli** [comment]
Related to #4711 

Still unable to check whether this is fixed in staging (gateway timeout on genetics widget)

**Comment by tuli** [comment]
Dear Simon,

Thank you for writing to WormBase.

The information should be available within the Genetics section. I
have alerted the web team to the problem and you will be contacted
soon with an update.

I apologise for the inconvenience. I may be able to get the data you
are looking for by other means if you'd like to write back and tell me
what you're looking for.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tharris** [comment]
@tuli what does it look like in production?

**Comment by tuli** [comment]
Can't you see that yourself? 
Err...well it's just got the "Alleles with phenotype data" table. I wanted to see whether it was fixed in staging, but haven't been able to.

**Comment by tharris** [comment]
It looks fine to me on staging.

http://staging.wormbase.org/species/c_elegans/gene/WBGene00006763#0-4-3

**Comment by tuli** [comment]
Great. Staging must be fixed then.

**Comment by tharris** [comment]
It would probably be good if you confirm. You might try using a gene that doesn't have a ton of variations. The staging server doesn't benefit from caching like production does.

**Comment by tuli** [comment]
It looks fine on Staging, I have checked a few genes. 

Thank you

**Comment by tuli** [comment]
Dear Simon,

Further to my previous message. The web team are aware of this issue
and have fixed it on our development site. This can be accessed here:
http://staging.wormbase.org/
Please note that this site is not stable.
The fix will be visible on the main site at the end of May.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by sibyl229** [comment]
Hi @tharris The issue with missing natural variations field in Genetics widget is due to old cache. I got the genetics widget for the unc-26 working by deleting its cache and reloading the page http://www.wormbase.org/species/c_elegans/gene/WBGene00006763#0-4-3. Can we delete all the genetics widget cache and have it regenerated on demand (so no precaching)?

**Comment by tharris** [comment]
Unfortunately, no. The genetics widget can require minutes to load. It will completely bring the site to its knees. We can expire them but we would also want to start generating them again in the background.

**Comment by sibyl229** [comment]
Genetics widget is working and tested on staging. Production cache will update in the coming release. Closing.
