### ISSUE TITLE
Hi,
I was working with a C. elegans gene called Y5...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4761]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
I was working with a C. elegans gene called Y57B8A.6, but it does not apper anymore in wormbase. Do you know if the name has been changed?
 Thanks! visitor_name

**Reported by:** Paol* (pjur***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/all/Y57B8A.6">http://www.wormbase.org/search/all/Y57B8A.6</a>
**Browser:** Firefox 45.0

**Comment by Paul-Davis** [comment]
Dear Paola,

Thank you for your enquiry. I have checked the complete history of C. 
elegans peptides in the wormpep resource and cannot locate any gene ever 
existing with this name or any even on this clone.
Checking the YAC clone ID Y57B8A this does not appear to be a valid ID.

Could I get you to check your records and get back to us if you are 
still experiencing issues location information about your gene on WormBase.

Thanks

Paul

On 21/04/2016 11:31, no-reply@wormbase.org wrote:
> I was working with a C. elegans gene called Y5... (Paola)
> Content-type: text/html; charset="utf-8"
> Date: Thu, 21 Apr 2016 10:33:13 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>     
>                                                                                        <style type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat Hi,
> I was working with a C. elegans gene called Y57B8A.6, but it does not apper anymore in wormbase. Do you know if the name has been changed?
>   Thanks! Paola  <p>Submitted From:
> <br>&nbsp;&nbsp;http://www.wormbase.org/search/all/Y57B8A.6 <a href="http://www.wormbase.org/http://www.wormbase.org/search/all/Y57B8A.6">http://www.wormbase.org/search/all/Y57B8A.6</a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4761. Follow progress on our <a href="https://github.com/WormBase/website/issues/4761">issue tracker</a>.
> <p>
>
> <p>
> Reported by: Paola (pjurado@idibell.cat) <br />
> <span class="fade">21 Apr 16 10:33 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
User confirmed that they were actually looking for Y75B8A.6. This gene was missing an exon and also 2 alternative Isoforms, so this update will go live in WS254

Sent the user the peptide sequences of the new annotations as well as a diagram to illustrate the changes.

![paola](https://cloud.githubusercontent.com/assets/717707/14707770/4aed53bc-07be-11e6-821d-b9ab5756e489.png)


>Y75B8A.6a
MNMMHMGAPMNGGPPPPQMLQMHHPLPHHVAVFAHGSSSQNSQAPPLQAA
SATPPVPSSMNRSQSRASCPQSTREMSSHRSTTSRRCGVCRGCQCKPCGQ
CTYCQDSPQFGGPGVKKQSCIERRCLRVLENRLQRDAPTFKARVGCNACE
DCRMQDCQICLVCLDKRFFENRHIPGAMCAKKRCNNAQSIECVPSLMSQN
PADFVQRAPKRSYELINPVISQQQQQQQSQMHFDVKRVQYMTGPPPQMMQ
QMQMQAPPQQQIPQPQTPQQQVQQHQQRPNSNSSHSQGPSPPRNGVSQQQ
QQQTPPQQQNGVAHQIKTDVNVENLEQHQQQQQQQQQQLQQQQQRMIFQP
APYPDLSVHARLMVQAPPQVITAPAPIPLPQGQMTHMPQHGLDIPYLIPT
SFVQAVQGQADPFYPSKFELDFEHNGDPFVPPSYAQDMKGQVVLQQL
>Y75B8A.6b
MNMMHMGAPMNGGPPPPQMLQMHHPLPHHVAVFAHGSSSQNSQAPPLQAA
SATPPVPSSMNRSQRASCPQSTREMSSHRSTTSRRCGVCRGCQCKPCGQC
TYCQDSPQFGGPGVKKQSCIERRCLRVLENRLQRDAPTFKARVGCNACED
CRMQDCQICLVCLDKRFFENRHIPGAMCAKKRCNNAQSIECVPSLMSQNP
ADFVQRAPKRSYELINPVISQQQQQQQSQMHFDVKRVQYMTGPPPQMMQQ
MQMQAPPQQQIPQPQTPQQQVQQHQQRPNSNSSHSQGPSPPRNGVSQQQQ
QQTPPQQQNGVAHQIKTDVNVENLEQHQQQQQQQQQQLQQQQQRMIFQPA
PYPDLSVHARLMVQAPPQVITAPAPIPLPQGQMTHMPQHGLDIPYLIPTS
FVQAVQGQADPFYPSKFELDFEHNGDPFVPPSYAQDMKGQVVLQQL
>Y75B8A.6c
MNMMHMGAPMNGGPPPPQMLQMHHPLPHHVAVFAHGSSSQNSQAPPLQAA
SATPPVPSSMNRSQRCGVCRGCQCKPCGQCTYCQDSPQFGGPGVKKQSCI
ERRCLRVLENRLQRDAPTFKARVGCNACEDCRMQDCQICLVCLDKRFFEN
RHIPGAMCAKKRCNNAQSIECVPSLMSQNPADFVQRAPKRSYELINPVIS
QQQQQQQSQMHFDVKRVQYMTGPPPQMMQQMQMQAPPQQQIPQPQTPQQQ
VQQHQQRPNSNSSHSQGPSPPRNGVSQQQQQQTPPQQQNGVAHQIKTDVN
VENLEQHQQQQQQQQQQLQQQQQRMIFQPAPYPDLSVHARLMVQAPPQVI
TAPAPIPLPQGQMTHMPQHGLDIPYLIPTSFVQAVQGQADPFYPSKFELD
FEHNGDPFVPPSYAQDMKGQVVLQQL
