### ISSUE TITLE
  Download a dataset of WBIDs and corre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4762]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Download a dataset of WBIDs and corresponding "Gene Overview" information from wormbase. I found that the worm-mine gene description field only contains descriptions for a subset of the genes that have been characterized to some extent.<br/>Thanks a lot and keep up the great work!</p>

**Reported by:** G.J.********* (gert*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

**Comment by azurebrd** [comment]
Dear G.J Hendriks

If what WormMine gives you is not satisfactory, give the data files on our FTP file a try:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/species/c_elegans/PRJNA13758/annotation/

the c_elegans.PRJNA13758.WS253.functional_descriptions.txt.gz  is the complete file for WS253, note this is not yet released on the website.
the 4th line from the top of the file tells you what the different types of descriptions are.

If you need the current release, just substitute WS253 with WS252.

Note that for website purposes, in the ‘Overview’ widget, we always show the concise_description, if it doesn’t exist, we show the automated_description and the provisional_description is legacy ‘extra’ information that we no longer curate.  

The last field is the gene_class_description, eg. 'phosphoinositide kinase AdAPter subunit', which might be of use to you as well.

Hope this helps.
Regards
Ranjana Kishore
WormBase
