### ISSUE TITLE
Todd: Hi Peter visitor_name (visitor_email): Hi To...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4763]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Todd: Hi Peter</br>visitor_name (visitor_email): Hi Todd, this is visitor_name.</br>Todd: Yep :)</br>visitor_name (visitor_email): I got your email, and was testing around in your account.</br>Todd: Any word?</br>visitor_name (visitor_email): It seems like only visitors who have filled out the survey will show up on your site.</br>visitor_name (visitor_email): i mean, will show up in the Visitors list.</br>visitor_name (visitor_email): that's not usually the case for your site, is it?</br>Todd: Weird, someone must have changed the setting?</br>Todd: No, that is not normally the case.</br>Todd: I don’t think we have a survey running</br>visitor_name (visitor_email): yeah, that doesn't seem normal to me either.</br>visitor_name (visitor_email): Thanks for confirming, I think we'll have to look into this further.</br>visitor_name (visitor_email): But we'll be sharing more updates soon.</br>visitor_name (visitor_email): Thanks &gt;)</br>Todd: ok, thanks for checking.</br>visitor_name (visitor_email): :)</br>visitor_name (visitor_email): no problem! Also, when did you start noticing that your visitors list was empty?</br>visitor_name (visitor_email): and not showing visitors?</br>Todd: about one day ago.</br>Todd: Today, certainly.</br>Todd: Possibly yesterday? But I’m pretty sure I saw visitors listed then.</br>visitor_name (visitor_email): ahh ic ic.</br>visitor_name (visitor_email): but you're also seeing a steady stream of chatting visitors, right?</br>Todd: You guys are over the breaking things left and right.</br>Todd: Chat works fine.</br>visitor_name (visitor_email): oh, sorry.</br>visitor_name (visitor_email): okay cool.</br>Todd: Just cannot see current site visitors in IM client.</br>visitor_name (visitor_email): we'll be in touch again soon, thanks for answering my questions :)</br>Todd: Only those that have current chats.</br>visitor_name (visitor_email): and you're using chat.olark.com to chat?</br>Todd: I’m using IM right now. Messages on OS X</br>visitor_name (visitor_email): okay np, i saw the same thing in chat.olark.com though.</br>visitor_name (visitor_email): thanks again!</br>Todd: Ok, cool.</br>Todd: np!

**Reported by:** Pete************ (supp*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 50.0.2661.86

**Comment by azurebrd** [comment]
@tharris should this issue be closed, or do you still want it open ?

**Comment by tharris** [comment]
Resolved
