### ISSUE TITLE
visitor_name (visitor_email): Hi! How can access t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4765]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi! How can access the data for a paper?</br>visitor_name (visitor_email): This is the paper</br>visitor_name (visitor_email): Proprioceptive Coupling within Motor Neurons Drives C. elegans Forward Locomotion</br>visitor_name (visitor_email): Hello?

**Reported by:** Iran (iran*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/paper#1-0-5">http://www.wormbase.org/resources/paper#1-0-5</a>
**Browser:** Safari 8.0.8

**Comment by tuli** [comment]
Dear Iran,

Thank you for writing to WormBase.

The WormBase paper ID for this paper is WBPaper00041768
http://www.wormbase.org/resources/paper/WBPaper00041768

This paper has Transgene data associated with it.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

On 22 April 2016 at 04:05,  <no-reply@wormbase.org> wrote:
> online chat Iran (iran@stnaofrd.edu): Hi! How can access the data for a
> paper?Iran (iran@stnaofrd.edu): This is the paperIran (iran@stnaofrd.edu):
> Proprioceptive Coupling within Motor Neurons Drives C. elegans Forward
> LocomotionIran (iran@stnaofrd.edu): Hello?
>
> Submitted From:
>   http://www.wormbase.org/resources/paper#1-0-5
> http://www.wormbase.org/resources/paper#1-0-5
>
> This issue has been assigned ticket number: #4765. Follow progress on our
> issue tracker.
>
> Reported by: Iran (iran@stnaofrd.edu)
> 22 Apr 16 03:06
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-

**Comment by tuli** [comment]
Dear Iran,

Further to my previous message, to locate this information yourself
you can enter the title of the paper in the WormBase search box (top
right), and select Paper. This takes you to
http://www.wormbase.org/resources/paper/WBPaper00041768

The widgets on the left hand side indicate what data types are
associated with that paper.

Best wishes,

Mary Ann

On 22 April 2016 at 09:04, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
> On 22 April 2016 at 09:03, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
>> Dear Iran,
>>
>> Thank you for writing to WormBase.
>>
>> The WormBase paper ID for this paper is WBPaper00041768
>> http://www.wormbase.org/resources/paper/WBPaper00041768
>>
>> This paper has Transgene data associated with it.
>>
>> Best wishes,
>>
>> Mary Ann
>>
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>>
>> On 22 April 2016 at 04:05,  <no-reply@wormbase.org> wrote:
>>> online chat Iran (iran@stnaofrd.edu): Hi! How can access the data for a
>>> paper?Iran (iran@stnaofrd.edu): This is the paperIran (iran@stnaofrd.edu):
>>> Proprioceptive Coupling within Motor Neurons Drives C. elegans Forward
>>> LocomotionIran (iran@stnaofrd.edu): Hello?
>>>
>>> Submitted From:
>>>   http://www.wormbase.org/resources/paper#1-0-5
>>> http://www.wormbase.org/resources/paper#1-0-5
>>>
>>> This issue has been assigned ticket number: #4765. Follow progress on our
>>> issue tracker.
>>>
>>> Reported by: Iran (iran@stnaofrd.edu)
>>> 22 Apr 16 03:06
>>>
>>> This question was reported via the web interface at wormbase.org. You can
>>> also email us directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the "WormBase: help"
>>> group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>
>>
>>
>> -
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi!

Thanks for your reply.

I am very sorry, but I just don't see it. Is there a way to access the raw or preprocessed data investigators used in that paper?

Thanks
Ir�n

________________________________________

**Comment by tuli** [comment]
Nevermind,

Is it just Transgene data what these researchers have available then?

Thanks
Ir�n

________________________________________

**Comment by tuli** [comment]
Dear Iran,

Thank you for your reply.

Transgene data is what we in WormBase have curated from this paper.

The paper is available from PubMed
http://www.ncbi.nlm.nih.gov/pubmed/23177960?dopt=abstract

I have not read the paper myself so it may contain other datatypes
which should be included in WormBase.

I would advise you to read the paper and contact the authors if you
have specific questions.

I hope I have understood your question.

Best wishes,

Mary Ann


On 22 April 2016 at 15:14, Iran Rafael Roman <iran@stanford.edu> wrote:
> Nevermind,
>
> Is it just Transgene data what these researchers have available then?
>
> Thanks
> Irán
>
> ________________________________________
> From: Iran Rafael Roman
> Sent: Friday, April 22, 2016 7:12 AM
> To: Mary Ann Tuli
> Cc: help@wormbase.org; WormBase/website
> Subject: Re: [wormbase-help] online chat transcript: visitor_name (visitor_email): Hi! How can access t... (Iran)
>
> Hi!
>
> Thanks for your reply.
>
> I am very sorry, but I just don't see it. Is there a way to access the raw or preprocessed data investigators used in that paper?
>
> Thanks
> Irán
>
> ________________________________________
> From: Mary Ann Tuli <maryann.tuli@wormbase.org>
> Sent: Friday, April 22, 2016 2:00 AM
> To: Iran Rafael Roman
> Cc: help@wormbase.org; WormBase/website
> Subject: Re: [wormbase-help] online chat transcript: visitor_name (visitor_email): Hi! How can access t... (Iran)
>
> Dear Iran,
>
> Further to my previous message, to locate this information yourself
> you can enter the title of the paper in the WormBase search box (top
> right), and select Paper. This takes you to
> http://www.wormbase.org/resources/paper/WBPaper00041768
>
> The widgets on the left hand side indicate what data types are
> associated with that paper.
>
> Best wishes,
>
> Mary Ann
>
> On 22 April 2016 at 09:04, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
>> On 22 April 2016 at 09:03, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
>>> Dear Iran,
>>>
>>> Thank you for writing to WormBase.
>>>
>>> The WormBase paper ID for this paper is WBPaper00041768
>>> http://www.wormbase.org/resources/paper/WBPaper00041768
>>>
>>> This paper has Transgene data associated with it.
>>>
>>> Best wishes,
>>>
>>> Mary Ann
>>>
>>> ~ Mary Ann Tuli
>>>
>>> ~ email: maryann.tuli@wormbase.org
>>> ~ Database Curator, WormBase
>>>
>>> ~ Biology Division
>>> ~ California Institute of Technology
>>> ~ 1200 E. California Blvd
>>> ~ Pasadena, CA 91125
>>>
>>> On 22 April 2016 at 04:05,  <no-reply@wormbase.org> wrote:
>>>> online chat Iran (iran@stnaofrd.edu): Hi! How can access the data for a
>>>> paper?Iran (iran@stnaofrd.edu): This is the paperIran (iran@stnaofrd.edu):
>>>> Proprioceptive Coupling within Motor Neurons Drives C. elegans Forward
>>>> LocomotionIran (iran@stnaofrd.edu): Hello?
>>>>
>>>> Submitted From:
>>>>   http://www.wormbase.org/resources/paper#1-0-5
>>>> http://www.wormbase.org/resources/paper#1-0-5
>>>>
>>>> This issue has been assigned ticket number: #4765. Follow progress on our
>>>> issue tracker.
>>>>
>>>> Reported by: Iran (iran@stnaofrd.edu)
>>>> 22 Apr 16 03:06
>>>>
>>>> This question was reported via the web interface at wormbase.org. You can
>>>> also email us directly.
>>>>
>>>> --
>>>> --
>>>> You received this message because you are subscribed to the "WormBase: help"
>>>> group.
>>>> To post to this group, send email to help@wormbase.org
>>>> To unsubscribe from this group, send email to
>>>> help+unsubscribe@wormbase.org
>>>> For more options, visit this group at
>>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>>
>>>
>>>
>>>
>>> -
>>
>>
>>
>> --
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
