### ISSUE TITLE
  I have developed and tested a databas...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4766]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have developed and tested a database query application that has been tested on the online Ensembl Genomes databases. Located at http://ensemblgenomes.org/info/access/mysql<br/>I think it might help your organization. There is a demo download available at www.aditware.com in the download page.<br/>Please let me know what you think.<br/>Thank you,<br/>visitor_name<br/>Founder Aditware, LLC</p>

**Reported by:** Bria*********** (adit*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by sibyl229** [comment]
This looks like spam email. Closing.
