### ISSUE TITLE
FTP server woes

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4767]
ERROR: ftp server error on cmd=[] response=[500 OOPS: cannot read banner file:/disk1/ftp/welcome_banner ] ftp server error on cmd=[USER anonymous ] response=[] Couldn't open 

the FTP server is asking for a username/password and breaks the US UCSC assembly hub.

**Comment by epaule** [comment]
erm ... on ftp://ftp.wormbase.org

**Comment by sibyl229** [comment]
Hi @tharris Looks like FTP site is not accessible [ftp://ftp.wormbase.org/pub/wormbase/](ftp://ftp.wormbase.org/pub/wormbase/) :(

**Comment by sibyl229** [comment]
Hi @epaule I think Todd has got FTP site up now. Is it working for you with the UCSC assembly hub?

**Comment by tharris** [comment]
The FTP server died yesterday. I restored it from backup today and it should be running as expected.

**Comment by epaule** [comment]
works again
