### ISSUE TITLE
  Hi, Can you tell me if there is a way...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4768]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, Can you tell me if there is a way of determining how many C. elegans<br/>genes are associated with a particular RNAi phenotype? For example, how many C.elegans genes have an embryonic lethal RNAi phenotype (WBPhenotype:0000050)? </p>

**Reported by:** Cris**************** (cris*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by epaule** [comment]
have you tried the RNAi section of the respective Phenotype page?
http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000050
