### ISSUE TITLE
  Dear Colleagues,  Thank you for putti...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4771]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Colleagues, <br/>Thank you for putting together the WormBase with so many helminth genomics data. <br/>I have been working with data Platyhelminthes and during download through FTP I had soe doubts:<br/>1. The folder releases doesn't has data for all species. Is it correct?<br/>2. Looking at the parasite folder, after opening the releases folder, it is possible to find WBPS1 to WBPS5. However, all of them appears to have the same information. What is the difference between them?<br/>Thank you very much for your kind support. <br/>Best regards,<br/>visitor_name</p>

**Reported by:** Lari*** (lari********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9

**Comment by brucebolt** [comment]
Dear Larissa

The folder ‘releases’ contains the species that are available on the main WormBase (www.wormbase.org) website.  The ‘parasite’ folder contains all species from WormBase ParaSite (parasite.wormbase.org) - this is a more comprehensive coverage of the parasitic nematodes and platyhelminthes.

The data within WBPS1 through WBPS6 represent each release of WormBase ParaSite.  There have been six releases to date, with WBPS6 being the most recent.  An additional option ‘current’ (ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/current) will always provide the most up-to-date data.  However, most genomes in WormBase ParaSite have remained unchanged between releases.  Full details of the assembly and annotation updates for each release can be found in our release log: http://parasite.wormbase.org/info/about/release-log.html

Please let me know if you have any further questions.

Best regards

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
