### ISSUE TITLE
  Dear WormBase Help, I would like to k...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4773]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase Help,<br/>I would like to know if there is an intron reference (N2- Bristol c.elegans worms).</p><p>What were you doing? <br />&nbsp;&nbsp;I'm working at ETH (energy metabolism Lab), I would like to run an alternative splicing analysis using the RNA-seq data.</p>

**Reported by:** Mari********** (mari*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by epaule** [comment]
we do have flafiles with our annotations available for download.
As example the WS252 release of the C.elegans N2 reference can be found here: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS252.annotations.gff3.gz

The WormBase[[:space:]]introns are the one you probably want. We also got RNASeq introns from Star alignments, but not all of them are part of our curated genes.
