### ISSUE TITLE
visitor_name (visitor_email): I was looking for th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4774]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): I was looking for the sequence of ced-7(n2094)III and it is not available. How early can it be available.

**Reported by:** Ruby******** (ruby*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00090351#02-45-4-">http://www.wormbase.org/species/c_elegans/variation/WBVar00090351#02-45-4-</a>
**Browser:** Chrome 49.0.2623.110

**Comment by raymond91125** [comment]
Hi Ruby,

A Textpresso.org search for the text "n2094 sequence" found one 
publication with several ced-7 allele sequences. We will add the 
sequence information to our database.

Table 2 from 
<http://www.sciencedirect.com/science/article/pii/S0092867400812015>

Allele 	Nucleic Acid and Amino Acid Changes 	Codon Position 	No. 
Persistent Corpses (n = 20)^b 
<http://www.sciencedirect.com/science/article/pii/S0092867400812015#TBL2FNB> 

/n1996/ 	Full-size image (<1 K)GA (R)→Full-size image (<1 K)GA 
(stop) 	5 	34 ± 4
/n2094/ 	Full-size image (<1 K)AA (Q)→Full-size image (<1 K)AA 
(stop) 	116 	36 ± 4
/n3072/ 	GFull-size image (<1 K)A (E)→GFull-size image (<1 K)A (G) 
639 	33 ± 6
/n1997/ 	Full-size image (<1 K)GA (R)→Full-size image (<1 K)GA 
(stop) 	1074 	34 ± 3
/n2690/ 	aFull-size image (<1 K)|AGT→aFull-size image (<1 K)|AGT 	1200 
16 ± 5
/n1998/ 	TGFull-size image (<1 K) (W)→TGFull-size image (<1 K) 
(stop) 	1300 	30 ± 3
/n3073/ 	Full-size image (<1 K)GA (R)→Full-size image (<1 K)AG 
(stop) 	1332 	33 ± 5
/n2001/ 	TGFull-size image (<1 K) (W)→TGFull-size image (<1 K) 
(stop) 	1540 	32 ± 4


Cheers,

Raymond





On 04/26/2016 01:22 PM, no-reply@wormbase.org wrote:
> online chat Ruby Boateng (ruby.boateng@bison.howard.edu): I was 
> looking for the sequence of ced-7(n2094)III and it is not available. 
> How early can it be available.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar00090351#02-45-4- 
> http://www.wormbase.org/species/c_elegans/variation/WBVar00090351#02-45-4- 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00090351#02-45-4-> 
>
>
> This issue has been assigned ticket number: #4774. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4774>.
>
> Reported by: Ruby Boateng (ruby.boateng@bison.howard.edu)
> 26 Apr 16 20:24
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tuli** [comment]
Dear Ruby,

Further to Raymond's message I would like to confirm that I have added
the molecular details of the n2094 allele as requested. This update
will be available in release WS254 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
User query is resolved.

Some problems with the other alleles in this paper, which are pending with the author. Issue can be closed though.
