### ISSUE TITLE
visitor_name (visitor_email): hi visitor_name (vis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4775]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): hi</br>visitor_name (visitor_email): good day</br>visitor_name (visitor_email): i need a  article</br>visitor_name (visitor_email): about: rna-seq in phylogeny plant parasit nematodes</br>visitor_name (visitor_email): can you help me?</br>visitor_name (visitor_email): ?

**Reported by:** ana (mahs*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/analysis/RNASeq.elegans.N2.WBls:0000002.Hermaphrodite.WBbt:0007833.SRP003783.SRX028190#0--10">http://www.wormbase.org/resources/analysis/RNASeq.elegans.N2.WBls:0000002.Hermaphrodite.WBbt:0007833.SRP003783.SRX028190#0--10</a>
**Browser:** Chrome 49.0.2623.112

**Comment by chris-grove** [comment]
Hello Ana,

 WormBase does not provide articles. You will need to download the article from the publisher's website or from PubMed (or other public resource) that may offer open-access versions of the articles. If you have a specific paper in mind, I may be able to point you to the appropriate resource.

Best wishes,

Chris Grove
WormBase
