### ISSUE TITLE
visitor_name (visitor_email): How do I access Worm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4776]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): How do I access WormMine or what used to be 'Batch Sequences'?</br>visitor_name (visitor_email): I want to download specific upstream &amp; downstream sequences from given genes.

**Reported by:** Curt******* (cloe**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/biomart/martview/">http://www.wormbase.org/biomart/martview/</a>
**Browser:** Chrome 49.0.2623.112

**Comment by chris-grove** [comment]
Email sent to Curtis, pointing him to ParaSite BioMart
