### ISSUE TITLE
Why is the sequence of clone F15C11 not available ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4778]
*Help Desk query collected when no chat operators were online. Follow up required.*

Why is the sequence of clone F15C11 not available for download? Anywhere else I can get it? Thanks

**Reported by:** qinf******** (qs47************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004773#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004773#0-9g-3</a>
**Browser:** Chrome 49.0.2623.110

**Comment by raymond91125** [comment]
HI Qinfang,

On the sem-4 gene page, the link for the clone and its sequence is in 
fact to that of E02H2, albeit the text shows F15C11. That's something we 
need to investigate.

As you've seen, E02H2 sequence is not available but that of F15C11 is on 
this page 
<http://www.wormbase.org/species/c_elegans/sequence/F15C11#0452--10>.

However, on the genome browser, if you turn on the tracks for "Curated 
Genes" and "YACs, Fosmids, & Cosmids", you'd notice that sem-4 is not 
entirely enclosed by the F15C11 sequence (reported sequence, not 
necessary reflecting the full insert in the cosmid, I think).

Let us know if you have further questions.

Raymond


On 04/28/2016 06:43 AM, no-reply@wormbase.org wrote:
> offline chat Why is the sequence of clone F15C11 not available for 
> download? Anywhere else I can get it? Thanks
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00004773#0-9g-3 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00004773#0-9g-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004773#0-9g-3> 
>
>
> This issue has been assigned ticket number: #4778. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4778>.
>
> Reported by: qinfang shen (qs47@cornell.edu)
> 28 Apr 16 13:45
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
User satisfied. There's the issue of incorrect URL linking to be resolved.

Raymond



-------- Forwarded Message --------
Subject: 	Re: [wormbase-help] offline chat transcript: Why is the 
sequence of clone F15C11 not available ... (qinfang shen)
Date: 	Thu, 28 Apr 2016 16:51:15 +0000
From: 	Qinfang Shen <qs47@cornell.edu>
To: 	Raymond Lee <raymond@caltech.edu>



Thanks very much, Raymond.

**Comment by sibyl229** [comment]
Hi @raymond91125 the problem with Clone link in Gene Overview should be fixed now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00004773#0-g-10 Thanks!

**Comment by epaule** [comment]
looks fine on staging
