### ISSUE TITLE
visitor_name (visitor_email): The unspliced transc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4779]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): The unspliced transcript of unc-82 does not have one of the exons marked. I have a Word file with the missing exon highlighted which I could send by email if I was given an email address.

**Reported by:** Pame******** (pame******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/comments">http://www.wormbase.org/tools/comments</a>
**Browser:** Chrome 49.0.2623.112

**Comment by raymond91125** [comment]
Hi Pam,

The current unc-82 transcript models indicate that the exon you 
highlighted in the Word file is present in transcripts of isoforms 
b/f/g/h/i but not in others. Are you suggesting that the e isoform (what 
you have in the Word file) should contain that extra exon as well?

Thanks.

Raymond


On 04/29/2016 10:40 AM, no-reply@wormbase.org wrote:
> online chat Pamela Hoppe (pamela.hoppe@wmich.edu): The unspliced 
> transcript of unc-82 does not have one of the exons marked. I have a 
> Word file with the missing exon highlighted which I could send by 
> email if I was given an email address.
>
> Submitted From:
>   http://www.wormbase.org/tools/comments 
> http://www.wormbase.org/tools/comments 
> <http://www.wormbase.org/http://www.wormbase.org/tools/comments>
>
> This issue has been assigned ticket number: #4779. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4779>.
>
> Reported by: Pamela Hoppe (pamela.hoppe@wmich.edu)
> 29 Apr 16 17:43
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
exon in question

aacctcacaaacaaaccttctattccgtccgtctgcctatagggaatcggatttgtatcgcaggataaacgc

**Comment by raymond91125** [comment]
Hi Raymond,
No, I made a mistake. I thought the file would have all exons from the gene. 
...

Pam
