### ISSUE TITLE
visitor_name (visitor_email): Hi, I think there is...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4782]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I think there is something missing in the GO term "DNA methylation" http://www.wormbase.org/species/all/go_term/GO:0006306#012--10</br>visitor_name (visitor_email): Only 2 genes appear under this term.</br>visitor_name (visitor_email): But I think this should be included to? http://www.wormbase.org/species/all/go_term/GO:0032775#012--10</br>visitor_name (visitor_email): hello?

**Reported by:** Paol* (pjur***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/go_term/GO:0032775#012--10">http://www.wormbase.org/species/all/go_term/GO:0032775#012--10</a>
**Browser:** Firefox 46.0

**Comment by chris-grove** [comment]
Hi Paola,


 Apologies that no one was able to answer your chat. The 2 genes listed in the "Associations" widget for the GO term "DNA methylation" (CRE21673 and dcp-66) are the only genes that are directly annotated to that term (GO:0006306). The other page you point to is for the term "DNA methylation on adenine" which is only directly associated to C18A3.1. To find all genes associated to a term or any of its descendant terms (i.e. not just directly annotated genes) you may want to use the "Ontology Browser" widget as you can find all directly associated genes as well as genes associated by inference to one or more child terms of the GO term you are looking at.

So, for example, if you look at the Ontology Browser for the GO term "DNA methylation" you can see that there are 3 gene products associated, 2 of which are directly associated:


"DNA methylation (GO:0006306) [3 gene products (2 direct)]"


If you click on the "3 gene products", you will see all 3 genes associated to the term GO term "DNA methylation" or any of its descendant terms (in this case "DNA methylation on adenine").


I hope that is clear. Let us know if you have any other questions about this.


Best,


Chris Grove

WormBase
