### ISSUE TITLE
Hello,

I am trying to find the resultant protein ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4800]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,

I am trying to find the resultant protein fkh-2 in C. elegans in ok683 variation but I realized that the wild-type sequence (for example: http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10) 
does not seem to match with the mutant (http://www.wormbase.org/species/c_elegans/variation/WBVar00091967#02-45-3).

Thanks,

visitor_name

**Reported by:** Laia (lcol**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10">http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10</a>
**Browser:** Chrome 50.0.2661.94

**Comment by raymond91125** [comment]
Hi Laia,

I'm not sure what you mean. Have you tried to match the reverse complement?

Cheers,

Raymond


On 05/09/2016 08:01 AM, no-reply@wormbase.org wrote:
> offline chat Hello, I am trying to find the resultant protein fkh-2 in 
> C. elegans in ok683 variation but I realized that the wild-type 
> sequence (for example: 
> http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10) 
> does not seem to match with the mutant 
> (http://www.wormbase.org/species/c_elegans/variation/WBVar00091967#02-45-3). 
> Thanks, Laia
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10 http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/T14G12.4a#06--10> 
>
>
> This issue has been assigned ticket number: #4800. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4800>.
>
> Reported by: Laia (lcolls@idibell.cat)
> 09 May 16 15:03
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tuli** [comment]
Dear Laia,

As Raymond already said, we are not sure whether you are reporting a
problem or asking a question.

I can tell you how to find the resulting protein in the ok683 strain (RN853):

Go to the Molecular Details widget of the ok682 page:
http://www.wormbase.org/species/c_elegans/variation/WBVar00091967

At the bottom of that widget you will see Features Affected. Click on
Predicted CDSs (there are 2), which will expand a table. Clicking on
the double helix button to the left of the 'item' (e.g. T14G12.4a)
will open a box showing sequence information; the conceptual
translation is I believe the sequence you are interested in.

Do let us know if this is not what you were asking and we will be
happy to help you.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Keep open for a little while in case this is not what she wants.

**Comment by lcolls** [comment]
Hello,

I have tried to match the reverse complement and it worked.

Thank you,

Laia
