### ISSUE TITLE
Is it possible to access gene pages from previous ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4803]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is it possible to access gene pages from previous reference genome releases either through the website or the API?

Thank you,
Evan

**Reported by:** Evan******** (evan******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_developers/api-rest#10--10">http://www.wormbase.org/about/userguide/for_developers/api-rest#10--10</a>
**Browser:** Chrome 50.0.2661.94

**Comment by epaule** [comment]
not currently. But we are aware that people want that functionality back.
As we will be saving the whole data history trail in our next database, it might actually come back in the not too far future (most likely there will be at least API access).
