### ISSUE TITLE
Chris: Hello Lucie, how can I help? visitor_name (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4807]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Lucie, how can I help?</br>visitor_name (visitor_name.kozllowski@umassmed.edu): hi I have a list of genbank name and to convert them into gene name but don't now how to doit</br>Chris: OK, can you give me a few examples? Then I can look at the best way to convert</br>visitor_name (visitor_name.kozllowski@umassmed.edu): NM_059093
NM_001276652
NM_001136372</br>Chris: OK thanks</br>Chris: I think there's no easy way to convert these IDs currently, but let me look into it a bit further and email you back. Is that OK?</br>visitor_name (visitor_name.kozllowski@umassmed.edu): yes absolutly</br>visitor_name (visitor_name.kozllowski@umassmed.edu): thanks !</br>Chris: OK, I'll email you soon. No problem!

**Reported by:** luci* (luci*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 50.0.2661.94

**Comment by chris-grove** [comment]
I've pointed Lucie to the UniProt ID mapping tool:

http://www.uniprot.org/uploadlists/

where she can paste in a list of RefSeq nucleotide IDs and output UniProtKB IDs, which can then be used in WormBase ParaSite BioMart as a filter. This would clearly be a use case to add RefSeq Nucleotide/Gene IDs as a possible filter in BioMart in addition to the existing RefSeq protein ID filtering.

**Comment by tuli** [comment]
@chris-grove can this be closed?

**Comment by brucebolt** [comment]
This filter will be added to ParaSite release 7 (due August).

I have attached a tab seperated file containing mappings between gene ID and RefSeq ID for C. elegans (in WS252), in case other users want to use them.
[mart_export.txt.gz](https://github.com/WormBase/website/files/262781/mart_export.txt.gz)
