### ISSUE TITLE
  Hi, I was requesting gene location in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4809]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I was requesting gene location info via curl with Content-Type: application/json<br/>http://www.wormbase.org/rest/widget/gene/WBGene00001067/location<br/>gives the following error:<br/>Content-Type application/json had a problem with your request.<br/>***ERROR***<br/>encountered object '0', but neither allow_blessed enabled nor TO_JSON method available on it at /usr/local/wormbase/extlib/lib/perl5/Catalyst/Action/Serialize/JSON.pm line 39.<br/>But Content-Type: application/xml worked fine</p>

**Reported by:** Seba***** (lueh************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by tuli** [comment]
@sibyl229 
Could you have a look at this please?

**Comment by tuli** [comment]
Dear Sebastian,

Thank you for writing to WormBase.
I have alerted our Web Team to your problem and you should hear from them soon.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Sebastian,

That was a problem with the web code. Sorry about that. I fixed it on our internal testing site, which you can curl with:

curl http://staging.wormbase.org/rest/widget/gene/WBGene00001067/location -H 'Content-Type: application/json'

The fix will go live on the actual WormBase site with the WS253 release (in around a week or two). And please note that the staging.wormbase.org <http://staging.wormbase.org/> is mostly intended for testing, and will likely to be unstable.

And thanks for the bug report!

Sibyl

**Comment by tuli** [comment]
@sibyl229 can this be closed?

**Comment by sibyl229** [comment]
Thanks @tuli. Closing
