### ISSUE TITLE
Hello,
I was looking for the description about the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4810]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I was looking for the description about these files,
ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/ONTOLOGY/
There are no header and its hard to understand what are different column corresponds t. Can you provide the link for this information ?

Thanks
visitor_name

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-2-">http://www.wormbase.org/#01-23-2-</a>
**Browser:** Chrome 48.0.2564.82

**Comment by raymond91125** [comment]
Hi Nishant,

The association files follow the format of GAF 2.0 
<http://geneontology.org/page/go-annotation-file-format-20> as much as 
we can. Thus the GO association file follows the format strictly whereas 
other ontology association files may depart slightly. Let us know if you 
have questions about specific columns.

Thanks.

Raymond
