### ISSUE TITLE
  Hi, I have a long list of genes with ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4813]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I have a long list of genes with sequence ID I want to get the WormBase ID for. I can do that using Wormmine, but the problem is that it ignores dead genes. Is there a way to get the WormBase ID for all the genes in my list, including dead ones?<br/>Thank you,<br/>Yonatan</p><p>What were you doing? <br />&nbsp;&nbsp;uploaded the list with sequence name to wommine and asked for WormBase ID.</p>

**Reported by:** Yona******** (yona**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by tuli** [comment]
In discussion with the user.

**Comment by chris-grove** [comment]
@tuli Have you pointed the user to FraqMine?

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/fraqmine.cgi

**Comment by tuli** [comment]
@chris-grove  I don't think fraqmine works for dead genes, does it? 

Though Dead genes don't have Sequence_name, only Public_name (if a name at all) so I'm not quite sure what the user means (am checking). 

Dead genes can have a sequence name as the Public_name e.g. C07E3.7 , which is not found in fraqmine. 

Searching faqmine for Dead genes which have been merged into other genes gives the merged into gene e.g. C01B12.1

**Comment by chris-grove** [comment]
@tuli  Ah, yeah OK, you're right. Fraqmine won't work

**Comment by WenChenWormBase** [comment]
@tuli and @chris-grove I skipped dead genes when preparing fragmine data. If you want I can add them into the building pipeline tomorrow. Do you have another way to help the user?

**Comment by chris-grove** [comment]
@WenChenWormBase  No, I don't know how else to do it without an acedb dump and scripting

**Comment by WenChenWormBase** [comment]
@chris-grove  and @tuli  I have added dead genes into fragmine. Now I can find the record of dead gene C07E3.7. Please give it a try and let me know if you see any problem.

**Comment by tuli** [comment]
Thank you @WenChenWormBase 

I think this is not so straight forward. 

C01B12.1 is the Sequence_name of WBGene00005017 - a live gene
C01B12.1 is the Public_name of WBGene00000643 - dead gene, merged into WBGene00005017

If I enter C01B12.1 into fraqmine I get the dead gene (WBGene00000643) 
Yesterday it took me to the live gene (WBGene00005017)

I suppose it should now give me two hits? That will get confusing for a long list of genes.

Small thing - can you add a 'clear' or 'refresh' button?

**Comment by tuli** [comment]
@chris-grove 
I asked the user to send me his list. I can easily pull out what he wants using table maker, which is fine if it's a one-off task.

**Comment by chris-grove** [comment]
@tuli OK sounds good

**Comment by WenChenWormBase** [comment]
@tuli and @chris-grove I  have a dead gene list generated for each WS release. Feel free to use it or send it to users if you find it helpful:
ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/DeadGeneList.csv

**Comment by chris-grove** [comment]
@WenChenWormBase  Thanks. Are these going to be integrated into the FraqMine search? I think the batch query functionality is the key here.

**Comment by WenChenWormBase** [comment]
@chris-grove or @tuli now SimpleMine has the function to get gene IDs for dead genes, are you going to contact the user and direct him to SimpleMine?

**Comment by tuli** [comment]
@WenChenWormBase  I have not heard back from the user. I will point him that way if he responds.

**Comment by YonatanT** [comment]
Hi,
I am the "user" and I apologize for not responding earlier. I didn't get an email from tuli, so I didn't know all this activity is going on just to help me.

WenChen: Can you please send me a link to SimpleMine so I could test it?

tuli: Can you please send me an email to yonatant@gmail.com, so I could send you the list?

Also, I would like to make a point regarding "dead genes". Getting information regarding them is very valuable. First, old datasets still has them. So when one tries to get information about groups of genes from those datasets, genes that have been merged to others simply does not show up. Second from our recent transcription work we find that several interesting genes are annotated as "transposons". These are not converted in Wormmine as well.
Thus, I believe the community could benefit by getting an option to add those those list that are handled by Wormmine.
Thank you,
Yonatan

**Comment by tuli** [comment]
Dear Yonatan,

Below is the email I sent you last week, which maybe you don't need to do
now.

++++++++++++++++++++++++++++++++++++++++++++++++++++

There is no easy way to do this, but if you would like to send me your
list I will pull the IDs directly out of the database
for you and send you a file. If this is a one-off task then this is
probably the most efficient way to do it.

I look forward to hearing from you.

Mary Ann

++++++++++++++++++++++++++++++++++++++++++++++++++++

The URL for Simple Mine is
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

Please have a look. We are interested in your opinion.

Thank you,

Mary Ann


On 23 May 2016 at 15:13, YonatanT <notifications@github.com> wrote:

> Hi,
> I am the "user" and I apologize for not responding earlier. I didn't get
> an email from tuli, so I didn't know all this activity is going on just to
> help me.
>
> WenChen: Can you please send me a link to SimpleMine so I could test it?
>
> tuli: Can you please send me an email to yonatant@gmail.com, so I could
> send you the list?
>
> Also, I would like to make a point regarding "dead genes". Getting
> information regarding them is very valuable. First, old datasets still has
> them. So when one tries to get information about groups of genes from those
> datasets, genes that have been merged to others simply does not show up.
> Second from our recent transcription work we find that several interesting
> genes are annotated as "transposons". These are not converted in Wormmine
> as well.
> Thus, I believe the community could benefit by getting an option to add
> those those list that are handled by Wormmine.
> Thank you,
> Yonatan
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4813#issuecomment-220991853>
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by YonatanT** [comment]
Dear Mary Ann,
Thank you fro the quick reply and the helpful link. Simplemine is indeed much better, although it still has some difficulties. For example it could retrieve Y54G2A.9.
Using SimpleMine I can continue with our analyses, and as far as I am concerned this issue can be closed.
Many thanks,
Yonatan

PS
Although not a priority, I still think that the community could benefit from a builtin option within wormmine
