### ISSUE TITLE
  Please change the address associated ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4815]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Please change the address associated with my name.<br/>Old:<br/>Columbia University<br/>Department of Biochemistry & Molecular Biophysics<br/>701 W. 168th Street<br/>HHSC 724, Box 140<br/>New York, NY 10032<br/>United States of America<br/>New:<br/>Columbia University<br/>Department of Biological Sciences<br/>1212 Amsterdam Avenue Fairchild Building, Room 805A<br/>Mail Code 2431 New York, NY 10027 <br/>USA</p>

**Reported by:** Oliv********* (or38*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36

**Comment by ceciliaWBPerson1** [comment]
I apologize for the delayed reply, I was on sick family leave.
Updated. I can't find original email from user, I will email him directly.
Updates will be available in release WS255 of WormBase.
cecilia

**Comment by ceciliaWBPerson1** [comment]
Dear Oliver:

I apologize for the delayed reply, I was on family sick leave.

- I have updated your contact information.

- I will also update address data  of you lab members

- Updates will be available in release WS255 of WormBase.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule

Thanks again,
Have a great day!

Cecilia


On Sat, May 14, 2016 at 8:32 PM, WormBase Helpdesk <notifications@github.com
