### ISSUE TITLE
B.malayi JBrowse error

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4816]
![screenshot from 2016-05-16 11 01 39](https://cloud.githubusercontent.com/assets/20523/15286545/a9ae942e-1b55-11e6-9ceb-3e37f2ec8293.png)

**Comment by scottcain** [comment]
@epaule 502 errors tend to be transient sorts of things--is it still happening for you?  I works for me at the moment.

**Comment by epaule** [comment]
hmm ... works again.
