### ISSUE TITLE
  Hi, Could you please tell me if it is...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4818]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>Could you please tell me if it is possible to get the Caenorhabditis elegans Protein Stats (number of predicted, confirmed, and partially confirmed proteins) for the earlier releases (from WS4 to WS224)?<br/>Thanks,<br/>visitor_name</p>

**Reported by:** Irem (irem*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by tuli** [comment]
@tharris Do you know?

**Comment by tuli** [comment]
Dear Irem,

Thank you for writing to WormBase.

Database releases going back to WS100 can be found on our FTP site
ftp://ftp.wormbase.org/pub/wormbase/releases/

I am afraid we do not go back further than this. WS100 was released in
2003 so this gives you 13 years of data which I hope is sufficient for
your needs.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
