### ISSUE TITLE
  The "Expression Pattern" image for C4...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4819]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The "Expression Pattern" image for C41G7.9 doesn't seem to work. Would you mind looking into it? Many thanks!</p><p>What were you doing? <br />&nbsp;&nbsp;I am trying to check what tissue expresses C41G7.9.</p>

**Reported by:** Maxw********* (leun*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by draciti** [comment]
Hi Maxwell,

the images are down but will be up for the next release.
In the meanwhile I paste them below- microarray and RNAseq profiling graphs.

let us know if you need anything else 
Best
Daniela

**Comment by draciti** [comment]
![microarray_graph_2](https://cloud.githubusercontent.com/assets/901243/15304342/a654c3a4-1b71-11e6-8255-345c4438fff0.png)
![rnaseq_graph_2](https://cloud.githubusercontent.com/assets/901243/15304344/a92aad64-1b71-11e6-8883-86b19ea6ac9e.png)
