### ISSUE TITLE
Hello,
I was looking at expression cluster data av...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4822]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I was looking at expression cluster data available at ftp website, "ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/". The number of cluster in "ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/ExprClusterTable.csv" (~1650) does not match with "ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv" (~700) , is this some kind of technical error.

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10</a>
**Browser:** Chrome 48.0.2564.82

**Comment by WenChenWormBase** [comment]
Dear Nishant,

Thank you very much for pointing out the mistake. The GeneExprCluster.csv
file on the ftp site was truncated. I have replaced it with the complete
version. Please give it a try and let me know if you see any problem.

Wen.


On Wed, May 18, 2016 at 6:55 AM, <no-reply@wormbase.org> wrote:

> I was looking at expression cluster data av... (Nishant)
> Content-type: text/html; charset="utf-8"
> Date: Wed, 18 May 2016 13:57:35 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>
>
>             <style
> type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat
> Hello,
> I was looking at expression cluster data available at ftp website, "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/". The
> number of cluster in "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/ExprClusterTable.csv"
> (~1650) does not match with "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv"
> (~700) , is this some kind of technical error.  <p>Submitted From:
> <br>&nbsp;&nbsp;
> http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> <a href="
> http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> ">http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> </a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4822. Follow progress on our
> <a href="https://github.com/WormBase/website/issues/4822">issue
> tracker</a>.
> <p>
>
> <p>
> Reported by: Nishant (thakur@ciml.univ-mrs.fr) <br />
> <span class="fade">18 May 16 13:57 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can
> also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
?Thanks Wen,

It works fine, no problem this time.


Best regards
Nishant
________________________________

**Comment by WenChenWormBase** [comment]
Hello Wen,

I am Sorry, but I missed it first time, I found many expression cluster for which either paper id missing or "Expression Cluster​" name is missing. Is there any specific reason for this missing information ?

example  :

cgc4489_hermaphrodite_enriched_transcription_factors(No paper ID)

WBPaper00029359_1217 (No expression cluster names)

WBPaper00029359_1280
WBPaper00029359_1444
WBPaper00029359_1504
WBPaper00029359_1604
cgc4489_group_14
cgc4489_group_8
cgc4386_cluster_6_3
cgc4386_cluster_3_5
cgc4386_cluster_5_5
cgc4489_group_3
cgc4489_group_9
cgc4489_group_12
cgc4386_cluster_6_5
cgc4489_group_22
cgc4386_cluster_2_2
cgc4489_group_17
cgc4489_group_11
cgc4489_group_16
cgc4489_group_10
WBPaper00029359_1291
cgc4386_cluster_2_3
cgc4489_group_24
cgc4489_group_19
cgc4489_group_6
cgc4489_group_2
cgc4386_cluster_2_4
cgc4386_cluster_2_5
cgc4489_group_4
cgc4386_cluster_5_6
cgc4489_group_23
cgc4489_group_18
WBPaper00029359_1166
WBPaper00029359_1197
WBPaper00029359_1546
WBPaper00029359_1557
WBPaper00029359_1599
cgc4489_group_13
cgc4489_group_15
cgc4386_cluster_5_4
WBPaper00029359_1310
WBPaper00029359_1364
WBPaper00029359_1578
cgc4386_cluster_6_6
cgc4386_cluster_1_4
cgc4489_group_20
WBPaper00029359_1194
WBPaper00029359_1240
WBPaper00029359_1243
WBPaper00029359_1336
WBPaper00029359_1549
cgc4386_cluster_5_3
WBPaper00029359_1678
WBPaper00029359_1681
WBPaper00029359_1168
WBPaper00029359_1225
WBPaper00029359_1494
cgc4386_cluster_5_1
WBPaper00029359_1353
WBPaper00029359_1419
WBPaper00029359_1548
cgc4386_cluster_5_2
cgc4489_group_25
cgc4489_group_21
cgc4386_cluster_6_4
cgc4386_cluster_1_3
cgc4386_cluster_1_2
cgc4489_group_1
cgc4489_group_5
cgc4386_cluster_6_1
cgc4489_group_7
cgc4386_cluster_6_2
WBPaper00029359_1182
cgc4386_cluster_4_4
WBPaper00029359_1124
WBPaper00029359_1141
WBPaper00029359_1304
WBPaper00029359_1351
WBPaper00029359_1497
WBPaper00029359_1525
cgc4386_cluster_3_6
cgc4386_cluster_3_3
WBPaper00029359_1208
WBPaper00029359_1242
WBPaper00029359_1367
WBPaper00029359_1483
WBPaper00029359_1561
WBPaper00029359_1692
cgc4386_cluster_4_5
cgc4386_cluster_1_5
cgc4386_cluster_4_2
WBPaper00029359_1135
WBPaper00029359_1320
WBPaper00029359_1326
WBPaper00029359_1345
WBPaper00029359_1439
WBPaper00029359_1458
cgc4386_cluster_3_1
WBPaper00029359_1174
WBPaper00029359_1289
WBPaper00029359_1312
WBPaper00029359_1330
WBPaper00029359_1553
WBPaper00029359_1618
WBPaper00029359_1128
WBPaper00029359_1209
WBPaper00029359_1229
WBPaper00029359_1253
WBPaper00029359_1283
WBPaper00029359_1466
WBPaper00029359_1473
WBPaper00029359_1488
cgc4386_cluster_3_4
cgc4386_cluster_2_6
WBPaper00029359_1145
WBPaper00029359_1442
cgc4386_cluster_4_6
WBPaper00029359_1311
WBPaper00029359_1357
cgc4386_cluster_1_6
cgc4386_cluster_2_1
WBPaper00029359_1639
cgc4386_cluster_4_3
WBPaper00029359_1362
WBPaper00029359_1587
WBPaper00029359_1271
cgc4386_cluster_4_1
WBPaper00029359_1227
WBPaper00029359_1682
cgc4386_cluster_1_1
cgc4386_cluster_3_2
WBPaper00029359_1183
WBPaper00029359_1296
WBPaper00029359_1297
cgc4489_hermaphrodite_enriched_transcription_factors
WBPaper00029359_1636
WBPaper00029359_1655
cgc4489_male_enriched_transcription_factors
WBPaper00029359_1325
WBPaper00029359_1629
WBPaper00029359_1538
WBPaper00029359_1609
WBPaper00029359_1187
WBPaper00029359_1524
cgc4489_male_enriched_neuronal_genes
WBPaper00029359_1600
WBPaper00029359_1659
WBPaper00029359_1626
WBPaper00029359_1435
WBPaper00029359_1519
WBPaper00029359_1258
WBPaper00029359_1465
WBPaper00029359_1417
WBPaper00029359_1652
WBPaper00029359_1181
WBPaper00029359_1582
WBPaper00029359_1661
WBPaper00029359_1662
WBPaper00029359_1426
cgc4489_hermaphrodite_enriched_neuronal_genes
WBPaper00029359_1492
WBPaper00029359_1376



Thanks .


Best regards
Nishant
________________________________

**Comment by WenChenWormBase** [comment]
Dear Nishant,

Were you talking about the nomenclature of the expression clusters? The
actual reference information and biological meaning of them are stored
inside their objects in WormBase, instead of their names shown on the
tables that you downloaded from SPELL.

Our paper ID system switched from cgc to WBPaper about ten years ago, and
we never renamed expression clusters that were curated before that. cgc4489
correspond to WBpaper00004489.

Some expression clusters are "co-expression clusters". They do not have any
specific functional meaning, just a group of genes that showed similar
expression profile in various conditions. That is why you see some objects
with names like "WBPaper00029359_1376". Most of these expression clusters
were published more than ten years ago,

Wen.





On Fri, May 20, 2016 at 7:41 AM, Nishant THAKUR <thakur@ciml.univ-mrs.fr>
wrote:

> Hello Wen,
>
> I am Sorry, but I missed it first time, I found many expression cluster
> for which either paper id missing or "Expression Cluster​" name is missing.
> Is there any specific reason for this missing information ?
>
> example  :
>
> cgc4489_hermaphrodite_enriched_transcription_factors(No paper ID)
>
> WBPaper00029359_1217 (No expression cluster names)
>
> WBPaper00029359_1280
> WBPaper00029359_1444
> WBPaper00029359_1504
> WBPaper00029359_1604
> cgc4489_group_14
> cgc4489_group_8
> cgc4386_cluster_6_3
> cgc4386_cluster_3_5
> cgc4386_cluster_5_5
> cgc4489_group_3
> cgc4489_group_9
> cgc4489_group_12
> cgc4386_cluster_6_5
> cgc4489_group_22
> cgc4386_cluster_2_2
> cgc4489_group_17
> cgc4489_group_11
> cgc4489_group_16
> cgc4489_group_10
> WBPaper00029359_1291
> cgc4386_cluster_2_3
> cgc4489_group_24
> cgc4489_group_19
> cgc4489_group_6
> cgc4489_group_2
> cgc4386_cluster_2_4
> cgc4386_cluster_2_5
> cgc4489_group_4
> cgc4386_cluster_5_6
> cgc4489_group_23
> cgc4489_group_18
> WBPaper00029359_1166
> WBPaper00029359_1197
> WBPaper00029359_1546
> WBPaper00029359_1557
> WBPaper00029359_1599
> cgc4489_group_13
> cgc4489_group_15
> cgc4386_cluster_5_4
> WBPaper00029359_1310
> WBPaper00029359_1364
> WBPaper00029359_1578
> cgc4386_cluster_6_6
> cgc4386_cluster_1_4
> cgc4489_group_20
> WBPaper00029359_1194
> WBPaper00029359_1240
> WBPaper00029359_1243
> WBPaper00029359_1336
> WBPaper00029359_1549
> cgc4386_cluster_5_3
> WBPaper00029359_1678
> WBPaper00029359_1681
> WBPaper00029359_1168
> WBPaper00029359_1225
> WBPaper00029359_1494
> cgc4386_cluster_5_1
> WBPaper00029359_1353
> WBPaper00029359_1419
> WBPaper00029359_1548
> cgc4386_cluster_5_2
> cgc4489_group_25
> cgc4489_group_21
> cgc4386_cluster_6_4
> cgc4386_cluster_1_3
> cgc4386_cluster_1_2
> cgc4489_group_1
> cgc4489_group_5
> cgc4386_cluster_6_1
> cgc4489_group_7
> cgc4386_cluster_6_2
> WBPaper00029359_1182
> cgc4386_cluster_4_4
> WBPaper00029359_1124
> WBPaper00029359_1141
> WBPaper00029359_1304
> WBPaper00029359_1351
> WBPaper00029359_1497
> WBPaper00029359_1525
> cgc4386_cluster_3_6
> cgc4386_cluster_3_3
> WBPaper00029359_1208
> WBPaper00029359_1242
> WBPaper00029359_1367
> WBPaper00029359_1483
> WBPaper00029359_1561
> WBPaper00029359_1692
> cgc4386_cluster_4_5
> cgc4386_cluster_1_5
> cgc4386_cluster_4_2
> WBPaper00029359_1135
> WBPaper00029359_1320
> WBPaper00029359_1326
> WBPaper00029359_1345
> WBPaper00029359_1439
> WBPaper00029359_1458
> cgc4386_cluster_3_1
> WBPaper00029359_1174
> WBPaper00029359_1289
> WBPaper00029359_1312
> WBPaper00029359_1330
> WBPaper00029359_1553
> WBPaper00029359_1618
> WBPaper00029359_1128
> WBPaper00029359_1209
> WBPaper00029359_1229
> WBPaper00029359_1253
> WBPaper00029359_1283
> WBPaper00029359_1466
> WBPaper00029359_1473
> WBPaper00029359_1488
> cgc4386_cluster_3_4
> cgc4386_cluster_2_6
> WBPaper00029359_1145
> WBPaper00029359_1442
> cgc4386_cluster_4_6
> WBPaper00029359_1311
> WBPaper00029359_1357
> cgc4386_cluster_1_6
> cgc4386_cluster_2_1
> WBPaper00029359_1639
> cgc4386_cluster_4_3
> WBPaper00029359_1362
> WBPaper00029359_1587
> WBPaper00029359_1271
> cgc4386_cluster_4_1
> WBPaper00029359_1227
> WBPaper00029359_1682
> cgc4386_cluster_1_1
> cgc4386_cluster_3_2
> WBPaper00029359_1183
> WBPaper00029359_1296
> WBPaper00029359_1297
> cgc4489_hermaphrodite_enriched_transcription_factors
> WBPaper00029359_1636
> WBPaper00029359_1655
> cgc4489_male_enriched_transcription_factors
> WBPaper00029359_1325
> WBPaper00029359_1629
> WBPaper00029359_1538
> WBPaper00029359_1609
> WBPaper00029359_1187
> WBPaper00029359_1524
> cgc4489_male_enriched_neuronal_genes
> WBPaper00029359_1600
> WBPaper00029359_1659
> WBPaper00029359_1626
> WBPaper00029359_1435
> WBPaper00029359_1519
> WBPaper00029359_1258
> WBPaper00029359_1465
> WBPaper00029359_1417
> WBPaper00029359_1652
> WBPaper00029359_1181
> WBPaper00029359_1582
> WBPaper00029359_1661
> WBPaper00029359_1662
> WBPaper00029359_1426
> cgc4489_hermaphrodite_enriched_neuronal_genes
> WBPaper00029359_1492
> WBPaper00029359_1376
>
>
>
> Thanks .
>
>
> Best regards
> Nishant
> ________________________________
> From: Nishant THAKUR
> Sent: Thursday, May 19, 2016 7:41 PM
> To: Wen Chen; WormBase/website
> Cc: help@wormbase.org
> Subject: Re: [wormbase-help] offline chat transcript: Hello,
>
>
> ​Thanks Wen,
>
> It works fine, no problem this time.
>
>
> Best regards
> Nishant
> ________________________________
> From: Wen Chen <wen@wormbase.org>
> Sent: Wednesday, May 18, 2016 11:46 PM
> To: WormBase/website
> Cc: help@wormbase.org; Nishant THAKUR
> Subject: Re: [wormbase-help] offline chat transcript: Hello,
>
> Dear Nishant,
>
> Thank you very much for pointing out the mistake. The GeneExprCluster.csv
> file on the ftp site was truncated. I have replaced it with the complete
> version. Please give it a try and let me know if you see any problem.
>
> Wen.
>
>
> On Wed, May 18, 2016 at 6:55 AM, <no-reply@wormbase.org<mailto:
> no-reply@wormbase.org>> wrote:
> I was looking at expression cluster data av... (Nishant)
> Content-type: text/html; charset="utf-8"
> Date: Wed, 18 May 2016 13:57:35 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>
>
>             <style
> type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat
> Hello,
> I was looking at expression cluster data available at ftp website, "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/". The
> number of cluster in "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/ExprClusterTable.csv"
> (~1650) does not match with "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv"
> (~700) , is this some kind of technical error.  <p>Submitted From:
> <br>&nbsp;&nbsp;
> http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> <a href="
> http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> ">http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> </a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4822. Follow progress on our
> <a href="https://github.com/WormBase/website/issues/4822">issue
> tracker</a>.
> <p>
>
> <p>
> Reported by: Nishant (thakur@ciml.univ-mrs.fr<mailto:
> thakur@ciml.univ-mrs.fr>) <br />
> <span class="fade">18 May 16 13:57 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org<
> http://wormbase.org>. You can also <a href="mailto:help@wormbase.org
> <mailto:help@wormbase.org>">email us</a> directly.
> </p>
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org<mailto:
> help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org<mailto:help%2Bunsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>
>
>
> --
> Wen Chen, Ph.D.
> Curator, WormBase
>



-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Hello Chen,

​Thanks for explanation, I am sorry, I did not make it clear, what I meant was, in "ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv" file, each gene is linked to expression cluster and each cluster name is associated with the WBPaper/source for example.

gene "WBGene00001061" is associated with "WBPaper00031040:TGF-beta_adult_downregulated​" with WBPaper ID, but for example expression cluster "gc4489_hermaphrodite_enriched_transcription_factors​" there is no associated WBPaper in the "ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv" file. In some cases there is no Expression cluster name for example gene "WBGene00002056​" with paper ID "WBPaper00029359_1135​". Is it possible to add this information in "WBPaper:TGF-beta_adult_downregulated" format for the list I sent you last time?



Best regards
Nishant
________________________________

**Comment by WenChenWormBase** [comment]
Dear Nishant,

There is another table on the same ftp directory:
ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/
ExprClusterTable.csv
<ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/ExprClusterTable.csv>,
all the information that you talked about are listed on this table,
including reference information for expression cluster objects like
cgc4489_hermaphrodite_enriched_transcription_factors

WBPaper00029359_1135 is the name of the expression cluster object. This
object does not have a biologically meaningful name because it is a
co-expression cluster.

Wen.

On Mon, May 23, 2016 at 2:03 AM, Nishant THAKUR <thakur@ciml.univ-mrs.fr>
wrote:

> Hello Chen,
>
> ​Thanks for explanation, I am sorry, I did not make it clear, what I meant
> was, in "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv"
> file, each gene is linked to expression cluster and each cluster name is
> associated with the WBPaper/source for example.
>
> gene "WBGene00001061" is associated with
> "WBPaper00031040:TGF-beta_adult_downregulated​" with WBPaper ID, but for
> example expression cluster
> "gc4489_hermaphrodite_enriched_transcription_factors​" there is no
> associated WBPaper in the "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv"
> file. In some cases there is no Expression cluster name for example gene
> "WBGene00002056​" with paper ID "WBPaper00029359_1135​". Is it possible to
> add this information in "WBPaper:TGF-beta_adult_downregulated" format for
> the list I sent you last time?
>
>
>
> Best regards
> Nishant
> ________________________________
> From: Wen Chen <wen@wormbase.org>
> Sent: Friday, May 20, 2016 8:11 PM
> To: Nishant THAKUR
> Cc: WormBase/website; help@wormbase.org
> Subject: Re: [wormbase-help] offline chat transcript: Hello,
>
>
> Dear Nishant,
>
> Were you talking about the nomenclature of the expression clusters? The
> actual reference information and biological meaning of them are stored
> inside their objects in WormBase, instead of their names shown on the
> tables that you downloaded from SPELL.
>
> Our paper ID system switched from cgc to WBPaper about ten years ago, and
> we never renamed expression clusters that were curated before that. cgc4489
> correspond to WBpaper00004489.
>
> Some expression clusters are "co-expression clusters". They do not have
> any specific functional meaning, just a group of genes that showed similar
> expression profile in various conditions. That is why you see some objects
> with names like "WBPaper00029359_1376". Most of these expression clusters
> were published more than ten years ago,
>
> Wen.
>
>
>
>
>
> On Fri, May 20, 2016 at 7:41 AM, Nishant THAKUR <thakur@ciml.univ-mrs.fr
> <mailto:thakur@ciml.univ-mrs.fr>> wrote:
> Hello Wen,
>
> I am Sorry, but I missed it first time, I found many expression cluster
> for which either paper id missing or "Expression Cluster​" name is missing.
> Is there any specific reason for this missing information ?
>
> example  :
>
> cgc4489_hermaphrodite_enriched_transcription_factors(No paper ID)
>
> WBPaper00029359_1217 (No expression cluster names)
>
> WBPaper00029359_1280
> WBPaper00029359_1444
> WBPaper00029359_1504
> WBPaper00029359_1604
> cgc4489_group_14
> cgc4489_group_8
> cgc4386_cluster_6_3
> cgc4386_cluster_3_5
> cgc4386_cluster_5_5
> cgc4489_group_3
> cgc4489_group_9
> cgc4489_group_12
> cgc4386_cluster_6_5
> cgc4489_group_22
> cgc4386_cluster_2_2
> cgc4489_group_17
> cgc4489_group_11
> cgc4489_group_16
> cgc4489_group_10
> WBPaper00029359_1291
> cgc4386_cluster_2_3
> cgc4489_group_24
> cgc4489_group_19
> cgc4489_group_6
> cgc4489_group_2
> cgc4386_cluster_2_4
> cgc4386_cluster_2_5
> cgc4489_group_4
> cgc4386_cluster_5_6
> cgc4489_group_23
> cgc4489_group_18
> WBPaper00029359_1166
> WBPaper00029359_1197
> WBPaper00029359_1546
> WBPaper00029359_1557
> WBPaper00029359_1599
> cgc4489_group_13
> cgc4489_group_15
> cgc4386_cluster_5_4
> WBPaper00029359_1310
> WBPaper00029359_1364
> WBPaper00029359_1578
> cgc4386_cluster_6_6
> cgc4386_cluster_1_4
> cgc4489_group_20
> WBPaper00029359_1194
> WBPaper00029359_1240
> WBPaper00029359_1243
> WBPaper00029359_1336
> WBPaper00029359_1549
> cgc4386_cluster_5_3
> WBPaper00029359_1678
> WBPaper00029359_1681
> WBPaper00029359_1168
> WBPaper00029359_1225
> WBPaper00029359_1494
> cgc4386_cluster_5_1
> WBPaper00029359_1353
> WBPaper00029359_1419
> WBPaper00029359_1548
> cgc4386_cluster_5_2
> cgc4489_group_25
> cgc4489_group_21
> cgc4386_cluster_6_4
> cgc4386_cluster_1_3
> cgc4386_cluster_1_2
> cgc4489_group_1
> cgc4489_group_5
> cgc4386_cluster_6_1
> cgc4489_group_7
> cgc4386_cluster_6_2
> WBPaper00029359_1182
> cgc4386_cluster_4_4
> WBPaper00029359_1124
> WBPaper00029359_1141
> WBPaper00029359_1304
> WBPaper00029359_1351
> WBPaper00029359_1497
> WBPaper00029359_1525
> cgc4386_cluster_3_6
> cgc4386_cluster_3_3
> WBPaper00029359_1208
> WBPaper00029359_1242
> WBPaper00029359_1367
> WBPaper00029359_1483
> WBPaper00029359_1561
> WBPaper00029359_1692
> cgc4386_cluster_4_5
> cgc4386_cluster_1_5
> cgc4386_cluster_4_2
> WBPaper00029359_1135
> WBPaper00029359_1320
> WBPaper00029359_1326
> WBPaper00029359_1345
> WBPaper00029359_1439
> WBPaper00029359_1458
> cgc4386_cluster_3_1
> WBPaper00029359_1174
> WBPaper00029359_1289
> WBPaper00029359_1312
> WBPaper00029359_1330
> WBPaper00029359_1553
> WBPaper00029359_1618
> WBPaper00029359_1128
> WBPaper00029359_1209
> WBPaper00029359_1229
> WBPaper00029359_1253
> WBPaper00029359_1283
> WBPaper00029359_1466
> WBPaper00029359_1473
> WBPaper00029359_1488
> cgc4386_cluster_3_4
> cgc4386_cluster_2_6
> WBPaper00029359_1145
> WBPaper00029359_1442
> cgc4386_cluster_4_6
> WBPaper00029359_1311
> WBPaper00029359_1357
> cgc4386_cluster_1_6
> cgc4386_cluster_2_1
> WBPaper00029359_1639
> cgc4386_cluster_4_3
> WBPaper00029359_1362
> WBPaper00029359_1587
> WBPaper00029359_1271
> cgc4386_cluster_4_1
> WBPaper00029359_1227
> WBPaper00029359_1682
> cgc4386_cluster_1_1
> cgc4386_cluster_3_2
> WBPaper00029359_1183
> WBPaper00029359_1296
> WBPaper00029359_1297
> cgc4489_hermaphrodite_enriched_transcription_factors
> WBPaper00029359_1636
> WBPaper00029359_1655
> cgc4489_male_enriched_transcription_factors
> WBPaper00029359_1325
> WBPaper00029359_1629
> WBPaper00029359_1538
> WBPaper00029359_1609
> WBPaper00029359_1187
> WBPaper00029359_1524
> cgc4489_male_enriched_neuronal_genes
> WBPaper00029359_1600
> WBPaper00029359_1659
> WBPaper00029359_1626
> WBPaper00029359_1435
> WBPaper00029359_1519
> WBPaper00029359_1258
> WBPaper00029359_1465
> WBPaper00029359_1417
> WBPaper00029359_1652
> WBPaper00029359_1181
> WBPaper00029359_1582
> WBPaper00029359_1661
> WBPaper00029359_1662
> WBPaper00029359_1426
> cgc4489_hermaphrodite_enriched_neuronal_genes
> WBPaper00029359_1492
> WBPaper00029359_1376
>
>
>
> Thanks .
>
>
> Best regards
> Nishant
> ________________________________
> From: Nishant THAKUR
> Sent: Thursday, May 19, 2016 7:41 PM
> To: Wen Chen; WormBase/website
> Cc: help@wormbase.org<mailto:help@wormbase.org>
> Subject: Re: [wormbase-help] offline chat transcript: Hello,
>
>
> ​Thanks Wen,
>
> It works fine, no problem this time.
>
>
> Best regards
> Nishant
> ________________________________
> From: Wen Chen <wen@wormbase.org<mailto:wen@wormbase.org>>
> Sent: Wednesday, May 18, 2016 11:46 PM
> To: WormBase/website
> Cc: help@wormbase.org<mailto:help@wormbase.org>; Nishant THAKUR
> Subject: Re: [wormbase-help] offline chat transcript: Hello,
>
> Dear Nishant,
>
> Thank you very much for pointing out the mistake. The GeneExprCluster.csv
> file on the ftp site was truncated. I have replaced it with the complete
> version. Please give it a try and let me know if you see any problem.
>
> Wen.
>
>
> On Wed, May 18, 2016 at 6:55 AM, <no-reply@wormbase.org<mailto:
> no-reply@wormbase.org><mailto:no-reply@wormbase.org<mailto:
> no-reply@wormbase.org>>> wrote:
> I was looking at expression cluster data av... (Nishant)
> Content-type: text/html; charset="utf-8"
> Date: Wed, 18 May 2016 13:57:35 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>
>
>             <style
> type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat
> Hello,
> I was looking at expression cluster data available at ftp website, "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/". The
> number of cluster in "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/ExprClusterTable.csv"
> (~1650) does not match with "
> ftp://caltech.wormbase.org/pub/wormbase/spell_download/tables/GeneExprCluster.csv"
> (~700) , is this some kind of technical error.  <p>Submitted From:
> <br>&nbsp;&nbsp;
> http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> <a href="
> http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> ">http://www.wormbase.org/species/c_elegans/gene/WBGene00000936#06g581--10
> </a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4822. Follow progress on our
> <a href="https://github.com/WormBase/website/issues/4822">issue
> tracker</a>.
> <p>
>
> <p>
> Reported by: Nishant (thakur@ciml.univ-mrs.fr<mailto:
> thakur@ciml.univ-mrs.fr><mailto:thakur@ciml.univ-mrs.fr<mailto:
> thakur@ciml.univ-mrs.fr>>) <br />
> <span class="fade">18 May 16 13:57 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org<
> http://wormbase.org><http://wormbase.org>. You can also <a href="mailto:
> help@wormbase.org<mailto:help@wormbase.org><mailto:help@wormbase.org
> <mailto:help@wormbase.org>>">email us</a> directly.
> </p>
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org<mailto:
> help@wormbase.org><mailto:help@wormbase.org<mailto:help@wormbase.org>>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org<mailto:help%2Bunsubscribe@wormbase.org
> ><mailto:help%2Bunsubscribe@wormbase.org<mailto:
> help%252Bunsubscribe@wormbase.org>>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>
>
>
> --
> Wen Chen, Ph.D.
> Curator, WormBase
>
>
>
> --
> Wen Chen, Ph.D.
> Curator, WormBase
>



-- 
Wen Chen, Ph.D.
Curator, WormBase
