### ISSUE TITLE
homologue list for intermod needed

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4823]
We need to supply a homologue list for the intermod project. Would someone be able to put this together? 

Julie Sullivan sent us these directions:
REQUIRED (for tool)

        Gene1   Gene2   DataSet

At the minimum you need the homologue relationship -- so two gene identifiers.

The data converter will also need to add the "data set" which will inform the user where the data came from, e.g. "Panther data set". This is the name that will appear on the GO tool next to the query results.

OPTIONAL (for tool)

        Homologue.type Homologue.evidence

Panther has a "type":

    static {
        TYPES.put("LDO", "least diverged orthologue");
        TYPES.put("O", "orthologue");
        TYPES.put("P", "paralogue");
        TYPES.put("X", "horizontal gene transfer");
        TYPES.put("LDX", "least diverged horizontal gene transfer");
    }

Since not all data sets have this information now, we are not going to include this in the GO tool.

Also homologue has "evidence" which consists of a publication and an evidence code. Not used in the tool but useful! Seems like that information should be in the tool somewhere, maybe in the next version.

There are lots of examples of data loaders for homologues so writing the parser should be straightforward, but I am happy to help.

Might be worth releasing a dev wormmine now with just panther so we can start testing, with the idea to load other data sets later.

**Comment by khowe** [comment]
Hi @kyook , maybe I'm misunderstanding. Hinxton has already provided this data. It's in AceDB, and it's been there for years (what we do not have is the different Panther ortholog types, because we don't have a clean way of storing that in our models, but it sounds like InterMOD is not going to use that anyway). 

So what's needed is for the wormMine build process to be extended to support loading orthologs. Before now, that has been the remit of the web-team. Is the proposal now that other teams chip-in with writing wormMine loaders? I'm not against that in principle, but @tharris and I should have a discussion about that first.

**Comment by kyook** [comment]
@Paul-Davis should know what I'm asking about, but basically, Julie needs these homologs to include WB in the intermod demo, I'm not talking about our own wormmine.

**Comment by epaule** [comment]
Just to add my 2 cents (EUR):
we do put out the ortholog files for each species, as example:
http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/species/b_malayi/PRJNA10729/annotation/b_malayi.PRJNA10729.WS254.orthologs.txt.gz

Which contains all the data she wants (including supporting evidence), so
all she would need to do is reformat it to her column format (and
potentially convert ids to whatever is the latest and greatest interMod ID
schema) and be good.

M

**Comment by Paul-Davis** [comment]
Thanks Karen, I'll look at generating the file for Julie.

P

**Comment by Paul-Davis** [comment]
Emailed Julie S.

I'm planing on limiting it to C. elegans::Human orthology but was
wondering what ID type would be preferred/required?

The following is easy to do:

"WBGene00000001"        "ENSG00000105647"       "Inparanoid_8"
"WBGene00000001"        "ENSG00000105647"       "ParaSite-Compara"
"WBGene00000001"        "ENSG00000117461"       "Inparanoid_8"
"WBGene00000001"        "ENSG00000117461"       "ParaSite-Compara"
"WBGene00000001"        "ENSG00000145675"       "Inparanoid_8"
"WBGene00000001"        "ENSG00000145675"       "ParaSite-Compara"
"WBGene00000001"        "ENSG00000268173"       "ParaSite-Compara"
"WBGene00000001"        "ENSG00000278139"       "ParaSite-Compara"

If alternative ID types are required it is a bit more work, but will be
a priority.

Also, I'm a little confused as to why this file is required as I thought
all the data was going to be queried from the modmines to maintain data
integrity.

**Comment by Paul-Davis** [comment]
Response:

Hi Paul, (Karen and Todd CC'ed)

You are correct! All of the data that will populate the GO tool will be queried directly from the mines, e.g. wormmine.

In March, Paulo asked me for help on Panther but I haven't heard anything since, or seen these data loaded in a mine.

Maybe Karen wanted these other ("better"?) orthologs loaded into WormMine as well?

My preference would be to deploy a (dev?) mine with orthologs now so we can test, then load this additional data set before the conference if there is time.

And Entrez gene ID is required for the primary identifier of human genes.

Does that make more sense? Sorry for the confusion!

Julie

**Comment by Paul-Davis** [comment]
So it seems that we don't need to supply a file to Intermine, but we need a working wormmine on the latest Intermine code with WS253 and data inclusion extended to have all the Orthology.

Paulo suggested he was going to test the loader with Panther 1st.

**Comment by Paul-Davis** [comment]
@kyook does this all make sense to you now?

**Comment by kyook** [comment]
yes, thank you for clarifying the situation

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, May 19, 2016 at 3:51 AM, Paul Davis <notifications@github.com>
wrote:

> @kyook <https://github.com/kyook> does this all make sense to you now?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4823#issuecomment-220290982>
>

**Comment by kyook** [comment]
I should add that Julie only needs a pared down list for the demo, so would
it be quicker and easier to just load pared down list of orthologs in a
dev-wormmine instance, or would that be the same amount of work?

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, May 19, 2016 at 8:26 AM, Karen Yook <karen@wormbase.org> wrote:

> yes, thank you for clarifying the situation
>
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 415.306.4150
> e-mail: kyook@caltech.edu
> e-mail: karen@wormbase.org
> skype name: wbkaren
>
>
> On Thu, May 19, 2016 at 3:51 AM, Paul Davis <notifications@github.com>
> wrote:
>
>> @kyook <https://github.com/kyook> does this all make sense to you now?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WormBase/website/issues/4823#issuecomment-220290982>
>>
>
>

**Comment by tharris** [comment]
At this juncture I do not think it would be easier to create a pared down mine. Paulo now has the Intermine code up-to-date and will work on 253 build with orthology data.

**Comment by Paul-Davis** [comment]
@tharris that's great news, closing this ticket as the original issue has been dealt with.
