### ISSUE TITLE
List of top community curators on WB homepage

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4827]
As discussed on today's CIT call, we would like to have a widget on the WB homepage that lists the top 20 (or so) community curation contributors, listing the person's name with a link to their person page, as well as the number of annotations that person has contributed. This could be updated manually on a weekly basis to start with a more automated pipeline in the future.

**Comment by epaule** [comment]
While I think it is a good idea, it probably should be only rolled out when we actually have more than 20 community curators/contributors ;-)

**Comment by chris-grove** [comment]
@epaule  We currently have had contributions from 221 distinct community curators.

**Comment by epaule** [comment]
impressive, that is way more than I expected

**Comment by sibyl229** [comment]
Hi @chris-grove @miyukimouse and I created a Google sheet for you to enter the top community contributors. Here it is https://docs.google.com/a/wormbase.org/spreadsheets/d/1u2EuEEeeo5pa7hLZ_mw08qhS1yJQKyRZxCNTYm90ULQ/edit?usp=sharing 

If you look at the bottom of that google sheets, you will see a Curator view and a Public view. You can edit the Curator view, and the public view is generated semi-automatically.  Public view contains computed cells, so it's recommended to avoid editing them except to add more rows. I wrote more documentation in the google sheets.

The plan is that we can eventually embed this google sheet in a widget on the WormBase home page. What do you think? Thank you!

**Comment by chris-grove** [comment]
@sibyl229  @miyukimouse  That's great! Thanks for doing this!
I'll work on filling out the sheet today. I'll let you know if I have any questions.

**Comment by sibyl229** [comment]
@chris-grove Great! Thank you

**Comment by chris-grove** [comment]
@sibyl229 @miyukimouse 
Thanks again for setting this up. I've filled in the Google spreadsheet with the top 20 contributors and the number of annotations for each. @sibyl229  As I mentioned by e-mail, @azurebrd  (Juancarlos) may be able to setup an automated cron job to populate the data at a place of your convenience for future updates. Let me know what you think.

**Comment by sibyl229** [comment]
Hi @chris-grove do you want to insert this code into the widget for top community curators? `<iframe src="https://docs.google.com/spreadsheets/d/1u2EuEEeeo5pa7hLZ_mw08qhS1yJQKyRZxCNTYm90ULQ/pubhtml?gid=873251968&amp;single=true&amp;widget=true&amp;headers=false"></iframe>`

**Comment by chris-grove** [comment]
@sibyl229  OK, sure, but where am I supposed to do that? Do you mean once the widget is live on the site?

**Comment by sibyl229** [comment]
@chris-grove We can put the code in an editable widget. If you are going to put it on the submit data page, you can create that widget now or anytime here: http://www.wormbase.org/about/userguide/submit_data#01--10 When you create or edit a widget, the change will appear on both production and staging immediately.

**Comment by chris-grove** [comment]
@sibyl229  OK, I can go ahead and put this on the submit data page, but the plan was to also have it on the WB homepage; is that still doable?

**Comment by chris-grove** [comment]
@sibyl229 
OK, I just put the table on the submit data page, but the table is very small and requires scrolling around to see everything. Is there a way to expand the widget to display the entire table at once?

**Comment by chris-grove** [comment]
I meant to add a screenshot:
![screen shot 2016-09-20 at 11 06 16 am](https://cloud.githubusercontent.com/assets/611382/18682818/8ba58966-7f22-11e6-95d2-468aaa4ea487.png)

**Comment by sibyl229** [comment]
@chris-grove I styled the table, so it should look better now: http://staging.wormbase.org/about/userguide/submit_data#012--10 You can do exactly the same thing to create a widget on home page. I will create a link to submit data page from the widget, if you decide to move it to home page.

**Comment by chris-grove** [comment]
@sibyl229 
Ah, I see. OK, I've just put it on the homepage. Can you adjust the style on this one now too? Also, a link to the Submit Data page would be great.

**Comment by chris-grove** [comment]
@sibyl229 
OK, sorry, but I think I messed up. I tried to add the widget, but now it's throwing an error message, and when I try to edit it everything in the widget gets erased.

**Comment by chris-grove** [comment]
@sibyl229 
Also, should I only be trying to create the widget on staging for now?

**Comment by sibyl229** [comment]
@chris-grove could you delay putting up the widget on home page? The reason is that if we put the widget up on homepage now, the production one will look a bit weird until stylesheet makes to production. I will move the widget when WS255 goes out. 

For now, this is what it looks like http://staging.wormbase.org/about/userguide/submit_data#2--10  is there any description you want to add to the Top Community Curator widget? Like who are the community curators and how to do it.

**Comment by chris-grove** [comment]
@sibyl229 
Yes, I can definitely delay putting it on the home page; whatever works best. Can you remove what I've added to the home page?

The widget looks good on the staging submit data page. Here's some text that can introduce the widget:

"Here's a list of our top community curators! Click on "Submit data" below to make your data contribution to WormBase."

**Comment by sibyl229** [comment]
Hi @chris-grove I removed the widget on home page for now, and I will add it back when WS255 goes live. I added the intro you wrote http://staging.wormbase.org/about/userguide/submit_data#2--10 Thanks!

**Comment by chris-grove** [comment]
@sibyl229  That looks great! Thanks Sibyl! Shall I close the ticket?

**Comment by sibyl229** [comment]
@chris-grove no problem! I will close the ticket after I move the widget to homepage.

**Comment by chris-grove** [comment]
@sibyl229  OK, sounds good

**Comment by chris-grove** [comment]
@sibyl229  I lost track of this issue. Is it still possible to put the top community curators widget on the homepage? As per #5873 ?

We discussed today at CIT the possibility of showing only 5-10 community curator names (top contributors from last 3 months or so), omitting number of contributions, and possibly showing their lab affiliation. I can do the calculations and update the Google doc:

https://docs.google.com/spreadsheets/d/1u2EuEEeeo5pa7hLZ_mw08qhS1yJQKyRZxCNTYm90ULQ/edit#gid=0

Thanks!

**Comment by sibyl229** [comment]
Done
