### ISSUE TITLE
Erroneous expression data in WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4831]
_Help Desk query collected when no chat operators were online. Follow up required._

Hi, 
I'm trying to use wormmine to find expression patterns for a list of genes. For one of them I get Expr3720 and &gt;600 expression patterns. However, when I look for Expr3720 and the paper reference most of the neurons from the wormmine list are not described. I was wondering where the data from wormmine is coming from and if it is reliable then. Thanks!

**Reported by:** Nata*********\* (nata******************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/paper/WBPaper00025119#0--10">http://www.wormbase.org/resources/paper/WBPaper00025119#0--10</a>
**Browser:** Chrome 50.0.2661.94

**Comment by draciti** [comment]
Hi Natalia,

thanks for reporting the issue. You are right, for nphp-4 the list retrieved by WormMine is far longer than what described in the paper, and in WormBase.

I could not check the other expression object as the number was not dispayed correctly in your message. Could you please send it again?

I will check the data source file with the web team and get back to you.
In the meanwhile, refer to
http://www.wormbase.org/species/all/expr_pattern/Expr3720#0213--10

for the correct annotations.

Thanks,
Daniela

**Comment by draciti** [comment]
Hi Webteam. Who is the WormMine point person? It seems that there are wrong associations for Expr3720 and wanted to check where/and why this originates. thanks

**Comment by sibyl229** [comment]
Hi Paulo,

Daniela, one of our curators, has questions about expression pattern data in WormMine. Are you able to help her with that? 

I’m not sure if you subscribe to Github issue notification, so just forwarding the message here.

Thank you!

Sibyl

**Comment by draciti** [comment]
thanks Sibyl! :)

I hope you are well!

**Comment by sibyl229** [comment]
Hi Paulo,

let me know if you need additional info

Expr3720, gene nphp-4, gives more than  >600 anatomy associations. there should be only 9.

thanks,
Daniela


.

**Comment by nuin** [comment]
I will check the XML files, but I don't think I have control over the data into it. I will grep the Anatomy file and see what comes up for that gene.

**Comment by draciti** [comment]
ok, which source do the xml files use? in acedb I see only the 9 associations

**Comment by nuin** [comment]
We use AceDB. And you are right we should have only 9 associations. But at the same time, I don't know if InterMine adds more associations based on other factors, from different sources. 

Another thing is that the current version of InterMine on the site is not the newest one, what might make there problem larger. I have an install of the newest InterMine and I will check the gene for these associations and report back.

**Comment by draciti** [comment]
sounds good Paulo, thanks

**Comment by draciti** [comment]
Hi Daniela,

Thanks for your prompt reply. I don't think there was another expression object. All the expression patterns from wormmine referred to Expr3720.

Thanks for your help!

Natalia

Natalia Martin, PhD
Postdoctoral Associate
Aballay Laboratory
270 Jones Building
Duke University Medical Center
27710 Durham, NC
United States of America

________________________________________

**Comment by draciti** [comment]
Sound good Natalia,
our developer is looking into it.
Let us know if you need further assistance.
Best,
Daniela
________________________________________

**Comment by nuin** [comment]
Just an update, with the new version I still see about 600 entries returned. I am investigating the source.

**Comment by draciti** [comment]
ok, thanks Paulo

**Comment by draciti** [comment]
Hi Paulo, any news on this? thanks

**Comment by nuin** [comment]
Hi @draciti 

I checked the input files and it seems that they don't have these many expression associated to each  item. It might be a merge problem somewhere in the build process. I am working on fixing some GFF3 errors that might help solve this and I will report and re-check when I have a working solution for the build and ability to query the database.

Sorry for the delay

**Comment by draciti** [comment]
Sounds good, thanks Paulo

**Comment by draciti** [comment]
Hi Paulo, WormMine is keeping retrieving wrong results for expression data. Another user wanted to check expression in AFD neurons and we cannot get the right answer. Can we please expedite this issue?

thanks
Daniela

**Comment by draciti** [comment]
Paulo, a couple of practical examples that were pulled by Chris are these:
 abf-1, abf-2 and ace-1 come up with an AFD query

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.expressionPatterns.lifeStages.anatomyTerms.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.lifeStages.anatomyTerms.name" op="CONTAINS" value="AFD"/>
</query>

but seem to have nothing to do with AFD, not even in the GAF file

thanks
d

**Comment by draciti** [comment]
query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.expressionPatterns.lifeStages.anatomyTerms.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.lifeStages.anatomyTerms.name" op="CONTAINS" value="AFD"/

**Comment by nuin** [comment]
Hi @draciti 

Sorry for the delay in getting back to you. I have tried the latest query you sent and I see results for AFDL and AFDR in the newest version of WormMine that we are working on. Checking my source file, I see that all 3 are represented

```
    <Anatomy_name>AFDR</Anatomy_name>
    <Anatomy_name>AFDL</Anatomy_name>
     <Anatomy_name>AFD</Anatomy_name>
```

but the two on top have actual information on expression patterns while AFD itself does not. I am trying   to check if this a merging error, and I will try running the queries manually. What are the results I am supposed to see?

Thanks

**Comment by draciti** [comment]
thanks Paulo,
it is correct that AFD does not have any direct associations.
let me know if you need more info on AFDR and AFDL

**Comment by nuin** [comment]
@draciti So, technically the output of the query seems correct, or is still too large to what is supposed to be for AFD?

![wormmine__query_results_page](https://cloud.githubusercontent.com/assets/6273/20689686/f14af250-b583-11e6-8323-93e23968e061.png)

**Comment by draciti** [comment]
it seems to be too large. 
is Wormmine reading into the anatomy_association file?
Even if so it seems to be no association, for example between aap-1 and AFDL in the expression pattern curation in postgres nor in the anatomy_association file that considers also enrichment.

Which are the source files you are using?

**Comment by chris-grove** [comment]
@nuin @draciti 
For what it's worth, there seems to be a systemic problem of Expr objects in WormMine not having the proper anatomy associations. One issue (which may be an aside) is that the Anatomy attributes of Expr objects are buried underneath the Life Stages attribute in the Model Browser for this class. The Life Stages and Anatomy attributes should be siblings, not a parent-child relationship. I can create a separate ticket for that.

Also, there seems to be an issue where almost every Expr object I check has some erroneous annotation to I6 neuron, excretory cell, gonad, intestine, and hypodermis, for some reason. So, we definitely need to nail down what the source files are, but it seems there may be other issues at play as well.

**Comment by draciti** [comment]
thanks Chris,
Paulo-let me know if you need anything from my side
d

**Comment by chris-grove** [comment]
Here's a comparison of the results of the "Gene --> Expression Pattern" template search in im-254 WormMine using the gene lin-1 as the query focus compared to the data for Expr5464 on the live WormBase website.
im-254 WormMine:
![screen shot 2016-11-29 at 1 30 33 pm](https://cloud.githubusercontent.com/assets/611382/20729783/5fff1942-b638-11e6-975f-b7561679d6ae.png)
live WB website:
![screen shot 2016-11-29 at 1 31 06 pm](https://cloud.githubusercontent.com/assets/611382/20729788/66a39778-b638-11e6-8f00-1ff0f4837a42.png)
As you can see there is a clear discrepancy and the terms that are coming up for lin-1 (Expr5464) in im-254 WormMine are these terms that seem to keep cropping up (erroneously) with other genes as well: I6 neuron, excretory cell, hypodermis, intestine

**Comment by nuin** [comment]
Thanks @chris-grove. It seems the problem here is at the source, not on the XML but parsing and treating the data correctly. I am working on the other issues in the next couple of days, and I am willing to prepare a map of the relationships between each datasource and see where we are making the mistakes.

**Comment by chris-grove** [comment]
@nuin 
OK, that sounds great, thanks!

**Comment by chris-grove** [comment]
@nuin 
Could we put this at the top of the priority list for things to deal with in WormMine? This is not just missing or misformatted data, it is actually incorrect data, which is far more concerning. We don't have any disclaimer anywhere indicating that the anatomy expression data in WormMine may actually be false, so I'm worried that people are downloading data from WormMine without realizing that the anatomical expression data may be (in many cases is) wrong.

**Comment by nuin** [comment]
@chris-grove I will focus on this. I should have another build going tonight, and this will be my next issue to track

**Comment by chris-grove** [comment]
@nuin 
Great! Thanks!

**Comment by nuin** [comment]
@chris-grove In the current dev build, with the limited dataset, there's not enough data to determine if it is still wrong. I will continue to check and discuss with InterMine people in order to solve this, but it might be only available after a full build is prepared.

**Comment by chris-grove** [comment]
@nuin 
OK

**Comment by chris-grove** [comment]
Hi @nuin ,

Has there been any progress on this issue? I'm concerned that people using WormMine for tissue expression data are going to be downloading incorrect data. Case in point is the "Cell/Tissue --> Expression" template, which by default queries for all genes expressed in the anchor cell. The result table lists 1,760 genes annotated to anchor cell, but the WS257 release on the live WormBase website only lists 94 genes associated with the anchor cell:

http://www.wormbase.org/species/all/anatomy_term/WBbt:0004522#01--10

I'm fairly certain that the vast majority of the 1,760 genes listed in WormMine as expressed in the anchor cell are not and have no data to support the association.

**Comment by nuin** [comment]
Sorry @chris-grove but I still need more time to work on this. I believe the new build improved a bit the results displayed, but I need to spend more time on it. I will create a full build of WS258 this weekend and hope to get back to it.

**Comment by chris-grove** [comment]
@nuin 
Ok, thanks

**Comment by nuin** [comment]
I have some updates on this issue. I am positive I found the possible error and I will run a limited build today and do some tests, if you, @chris-grove, can check later I will let you know when to check. If the limited build works, we can proceed to a full build and check how the data behaves then

**Comment by chris-grove** [comment]
@nuin 
OK, sure thing. Just let me know.

**Comment by nuin** [comment]
@chris, the build is set, please take a look on instance 259. I used this ID WBGene00000898 and got these results

![screen shot 2017-05-08 at 1 45 54 pm](https://cloud.githubusercontent.com/assets/6273/25822070/afad1b44-33f4-11e7-9df9-a598dac4acec.png)

**Comment by chris-grove** [comment]
@nuin 
Sorry, but the same problem is persisting. In your example, Expr7058 is associated with the anatomy terms "hypodermis", "I6 neuron", "excretory cell", "intestine", "neuron" and "pharyngeal muscle cell" but in the curation database and on the live WormBase website this expression pattern object is only annotated to "intestine", "head neuron", and "nervous system". Likewise, Expr9913 on im-259 is associated with anatomy terms that do not agree with what is stored in our curation database or what's on the live WB site.

I'm pretty sure the problem is due to the fact that anatomy terms are nested under life stages in WormMine (an issue I raised in #5289 ). I can actually do a query (in im-259) for anatomy terms associated with each life stage:

`<query name="" model="genomic" view="LifeStage.publicName LifeStage.primaryIdentifier LifeStage.anatomyTerms.name LifeStage.anatomyTerms.primaryIdentifier LifeStage.anatomyTerms.synonym" longDescription="" sortOrder="LifeStage.publicName asc">
</query>`

which is essentially just returning anatomy terms that exist during that life stage; this query returns 3,826 rows listing off the anatomy terms that I keep seeing cropping up erroneously in other expression patterns, like "I3 neuron", "gonad", "pharyngeal muscle cell", "I6 neuron", etc.

I think what is happening is that the expression pattern life stages are accurate, but the problem is that the actual anatomy terms associated with an expression pattern are being ignored by the WormMine data loader and only the anatomy terms associated with the life stages of that expression pattern are being displayed. So, anatomy terms need to be pulled directly from the Expr_pattern objects in ACEDB, not from the life stage objects. The data hierarchy needs to be

Expression pattern
> Anatomy term
> Life Stage

and NOT

Life Stage
> Anatomy term

which leads to 

Expression pattern
> Life stage
>> Anatomy term

which only returns anatomy terms associated with the life stage, which we should essentially be ignoring for now. I hope that makes sense.

**Comment by nuin** [comment]
Thanks Chris, I will double check Anatomy Terms loading too, there might be changes required there.

**Comment by chris-grove** [comment]
Fixed. Just awaiting update to template query, as in ticket #5628
