### ISSUE TITLE
meetings widget on staging

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4832]
the meetings widget vanished from the staging.wormbase.org front page

**Comment by sibyl229** [comment]
Hi @epaule I think it might be that the meetings widget was never created on staging site. I just created it for testing.

**Comment by epaule** [comment]
is the testing site accessible from outside?

**Comment by sibyl229** [comment]
Hi @epaule Sorry I missed your message. You can view the staging site from anywhere, and the curator created widgets (for example the Meetings widget on homepage) can also be viewed from anywhere. Just remember that the content for these curator created widgets on staging site aren't synced to production.
