### ISSUE TITLE
Where can I get the stable IDs of all the protein ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4833]
*Help Desk query collected when no chat operators were online. Follow up required.*

Where can I get the stable IDs of all the protein coding genes (CE) for every release of Wormbase on FTP website? I could find this in peptide fasta sequence file, but not as separate file.

Thanks 
visitor_name

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/wormbase_release_WS252#01--10">http://www.wormbase.org/about/wormbase_release_WS252#01--10</a>
**Browser:** Chrome 48.0.2564.82

**Comment by epaule** [comment]
if you are interested just in the protein history, you can have a look at that tarball: ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS252.wormpep_package.tar.gz

It contains a wormpep history file with a list of when which protein appeared/disappeared/reappeared.
