### ISSUE TITLE
I was looking at the Homology section of the "WBGe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4834]
_Help Desk query collected when no chat operators were online. Follow up required._

I was looking at the Homology section of the "WBGene00000556" gene and it is showing hits in many nematodes ... for example hit for the O. volvulus gene :OV:OVP09665  with evalue:1.6e-06.  When I blast protein sequence of WBGene00000556 against the O. volvulus proteome on wormbase blastp tool, there is no hit. I also blasted two sequences on my system and even on NCBI blast server using " Align two or more sequences" , there is no similarity between these two sequences.
Is it technical problem? I found several cases like this.

Thanks
visitor_name

**Reported by:** Nish**\* (thak******************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat">http://www.wormbase.org/tools/blast_blat</a>
**Browser:** Chrome 48.0.2564.82

**Comment by epaule** [comment]
that is actually a really nice example on the behaviour of different BLAST implementations.
* our pipeline that creates the table on the website uses WU-BLASTP from 2006 and comes up with what you see (the e-4 values)
* our website blast in contrast uses NCBI BLASTP 2.2.20 from 2009 which doesn't find any matches
* the NCBI website uses NCBI BLASTP+ 2.2.30 with composition adjusted scoring, and finds 2 mathes with corrected evalues around 4
* on parasite.wormbase.org there is a NCBI BLASTP+2.2.29 without the scoring adjustment, and that in turn behaves more like the old WU-BLAST.

... I think there is a case for us to revisit which versions of what we use across our site.

**Comment by epaule** [comment]
will try to roll in James code into our build, which should get us in line with NCBI

**Comment by epaule** [comment]
added to WS260 build
