### ISSUE TITLE
  Now I have a list of genes, but I wan...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4840]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Now I have a list of genes, but I want to know if it is protein-coding or non-coding RNAs. Which FTP file I should use to fetch the data?<br/>Thanks!</p>

**Reported by:** Joyc* (qzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by epaule** [comment]
you can try the C.elegans part of the WormBase-ParaSite BioMart (http://parasite.wormbase.org/biomart/martview/):
pick as species C.elegans and upload your list of ids, then pick in the output the biotype.

**Comment by chris-grove** [comment]
Hi Joyce,

 You can use WormMine to get this information. First, create a gene list by uploading your list of genes via the "Lists" tab (let me know if you need help with this).

Then import the following XML query on the "QueryBuilder" tab (click on the "Import query from XML" link):

` 
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.transcripts.symbol Gene.transcripts.method" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="Gene list for all organisms 23 May 2016 10.7"/>
</query>
` 

and replace the constraint to your list of genes. The transcript "Method" column will display the type of transcript ("coding" vs "non-coding") for each transcript of each gene in your list.

I'm happy to guide you through this process if needed.

Chris
