### ISSUE TITLE
hello,
how i finde the informations ti knocking do...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4841]
*Help Desk query collected when no chat operators were online. Follow up required.*

hello,
how i finde the informations ti knocking down the ras pathways Genes with rani? thank you

**Reported by:** Saad (kosa****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/clone/ras pathway">http://www.wormbase.org/search/clone/ras pathway</a>
**Browser:** Safari 9.1

**Comment by epaule** [comment]
if you go to the respective pathway page: http://www.wormbase.org/resources/wbprocess/WBbiopr:00000070
you can see a list of genes, and each gene should have information on RNAi/knockouts/etc. if you follow the links.
