### ISSUE TITLE
aptf-2 image display

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4843]
hi sibyl,
on staging:
I noticed that on the aptf-2 gene page, expression widget, Expr7734 has no associated images
http://www.wormbase.org/species/c_elegans/gene/WBGene00013383#-1803c64e7dg-10

but it should
http://www.wormbase.org/species/c_elegans/gene/WBGene00013383#-1803c64e7dg-10

could you please take a look?
May have something to do with #4671?  

I had tested the ticket for the large scale study that was giving the problem and was then working fine: http://staging.wormbase.org/species/all/expr_pattern/Expr1149308#012--10

but it might be that something else got affected by the change?
thanks
d

**Comment by draciti** [comment]
Hi, adding another example of missing pictures
Expr9821, WBPicture0000010470
name of the file: 3dmdTranBL1.jpg

**Comment by draciti** [comment]
works great on staging thanks! Should I keep this open till is working on production?

**Comment by sibyl229** [comment]
I'm gonna close this for now, since it's working on staging.
