### ISSUE TITLE
Chris: Hello Lourds, how can I help? visitor_name ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4844]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Lourds, how can I help?</br>visitor_name (visitor_email): I cannot find rpn-13 for C. elegans is there another name</br>Chris: Hmm, let me check</br>Chris: I can't find an rpn-13 gene</br>Chris: Where did you see this gene referenced?</br>visitor_name (visitor_email): for a transcript?</br>visitor_name (visitor_email): yes</br>visitor_name (visitor_email): should I send you the link to the paper</br>Chris: sure</br>visitor_name (visitor_email): http://www.sciencedirect.com/science/article/pii/S2211124713002295#bib39</br>Chris: OK, give me a minute to take a look</br>Chris: OK, I'm not entirely sure yet, but it looks like the gene C56G2.7</br>visitor_name (visitor_email): That's the closest I got too</br>visitor_name (visitor_email): but it doesn't say it's a proteasome component</br>Chris: It's unfortunate, but sometimes authors do not confirm the naming of a gene with WormBase, making this type of identification difficult</br>visitor_name (visitor_email): Is there anyother site I can visit</br>Chris: If you look at the Homology widget of the gene page, you can see that it has homology to known RPN13's and proteasomal subunits of other species</br>Chris: http://www.wormbase.org/species/c_elegans/gene/WBGene00016981#-06-10</br>visitor_name (visitor_email): yeah I have that</br>visitor_name (visitor_email): Thank you any way</br>Chris: WormBase is the official curator of gene names, so I don't know where else you could find the match</br>visitor_name (visitor_email): hmm</br>visitor_name (visitor_email): Thank you</br>Chris: If the paper, does not have any specific sequence information, then we can only try to contact the authors of the paper</br>Chris: You may want to write the authors to confirm</br>visitor_name (visitor_email): ok Thank you</br>Chris: Is there anything else I can help you with?

**Reported by:** Lour******************** (lour*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/support?url=/">http://www.wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 49.0.2623.112

**Comment by chris-grove** [comment]
Sent email to genenames@wormbase.org about naming issue
