### ISSUE TITLE
  Hi, I am trying to obtain the complet...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4845]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am trying to obtain the complete set of C. elegans 3'UTR sequences, including the chromosome location coordinates. Is there a way to do this through Wormmine or some other method?<br/>Thank you!</p>

**Reported by:** hych***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by raymond91125** [comment]
Hi,

You can use WormBase Parasite BioMart (under Tools).

For illustration, here's an example query XML:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Query>
<Query  virtualSchemaName = "parasite_mart" formatter = "FASTA" header = 
"0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" >

     <Dataset name = "wbps_eg_gene" interface = "default" >
         <Filter name = "species_id_1010" value = "celegans"/>
         <Attribute name = "production_name_1010" />
         <Attribute name = "ensembl_gene_id" />
         <Attribute name = "3utr" />
         <Attribute name = "3_utr_start" />
         <Attribute name = "3_utr_end" />
     </Dataset>
</Query>

Let us know if you have any trouble.

Cheers,

Raymond

**Comment by raymond91125** [comment]
Hi Cindy,

My colleagues will have definitive answers to your questions. Thus I'm 
routing this thread back to the help desk github ticket.

I'd offer you my personal *guess*:

1. If you look at the track selections for Genome Browser 
(Tools->GBrowse), you'd see there are many 3UTR data tracks from Piano 
group, including UTRome. Thus I think it is included in WB analysis.

2. Rows have to be identical to be considered redundant.

Raymond


On 05/24/2016 10:25 AM, Cindy Chang wrote:
> Hi Raymond,
>
> Thank you for your help! This is what I was looking for.
>
> I have some additional questions:
>
> 1) Do you know the source of the 3'UTR annotations in Wormbase and 
> whether they incorporate data from projects like the 3'UTRome?
>
> 2) In the results page of ParaSite Biomart, by clicking the 'Unique 
> Results Only', would I be filtering out only the rows that are 
> completely identical, or would I be filtering out different results 
> for a same gene as well (i.e. would I be loosing 3'UTR isoforms of the 
> same gene) ?
>
> Thanks again!
>
>
> Best,
> Cindy
>
> On Mon, May 23, 2016 at 4:41 PM, Raymond Lee <raymond@caltech.edu 
> <mailto:raymond@caltech.edu>> wrote:
>
>     Hi,
>
>     You can use WormBase Parasite BioMart (under Tools).
>
>     For illustration, here's an example query XML:
>
>     <?xml version="1.0" encoding="UTF-8"?>
>     <!DOCTYPE Query>
>     <Query  virtualSchemaName = "parasite_mart" formatter = "FASTA"
>     header = "0" uniqueRows = "0" count = "" datasetConfigVersion =
>     "0.6" >
>
>         <Dataset name = "wbps_eg_gene" interface = "default" >
>             <Filter name = "species_id_1010" value = "celegans"/>
>             <Attribute name = "production_name_1010" />
>             <Attribute name = "ensembl_gene_id" />
>             <Attribute name = "3utr" />
>             <Attribute name = "3_utr_start" />
>             <Attribute name = "3_utr_end" />
>         </Dataset>
>     </Query>
>
>     Let us know if you have any trouble.
>
>     Cheers,
>
>     Raymond
>
>
>
>     On 05/23/2016 01:19 PM, no-reply@wormbase.org
>     <mailto:no-reply@wormbase.org> wrote:
>>     How Do I ...?
>>
>>       Hi, I am trying to obtain the complete set of C. elegans 3'UTR
>>     sequences, including the chromosome location coordinates. Is
>>     there a way to do this through Wormmine or some other method?
>>     Thank you!
>>
>>     Submitted From:
>>       support /tools/support <http://www.wormbase.org//tools/support>
>>
>>     This issue has been assigned ticket number: #4845. Follow
>>     progress on our issue tracker
>>     <https://github.com/WormBase/website/issues/4845>.
>>
>>     Reported by: hychang61@gmail.com <mailto:hychang61@gmail.com>
>>     23 May 16 20:21
>>
>>     Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:47.0)
>>     Gecko/20100101 Firefox/47.0
>>
>>     This question was reported via the web interface at wormbase.org
>>     <http://wormbase.org>. You can also email us
>>     <mailto:help@wormbase.org> directly.
>>
>>     -- 
>>     -- 
>>     You received this message because you are subscribed to the
>>     "WormBase: help" group.
>>     To post to this group, send email to help@wormbase.org
>>     <mailto:help@wormbase.org>
>>     To unsubscribe from this group, send email to
>>     help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>>     For more options, visit this group at
>>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>     ---
>>     You received this message because you are subscribed to the
>>     Google Groups "WormBase: help" group.
>>     To unsubscribe from this group and stop receiving emails from it,
>>     send an email to help+unsubscribe@wormbase.org
>>     <mailto:help+unsubscribe@wormbase.org>.
>
>


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by epaule** [comment]
as far as I know the combination of all fasta header columns are considered for uniqueness and not the actual sequence.
But there are some tools out there to collapse redundant fasta sequences (as example: nrdb from WashU).

And while we do show UTRome data on our Genome Browsers for curation purposes, they have not been included in our automated UTR building process, as we unsuccessfully tried to get our hands on the raw sequences.
For WS253 and newer we started to build UTRs from Trinity with RNASeq data, so you will see some quite impressive changes when it goes live.

**Comment by raymond91125** [comment]
Hi Cindy,

as far as I know the combination of all fasta header columns are considered
for uniqueness and not the actual sequence.
But there are some tools out there to collapse redundant fasta sequences
(as example: nrdb from WashU).

And while we do show UTRome data on our Genome Browsers for curation
purposes, they have not been included in our automated UTR building
process, as we unsuccessfully tried to get our hands on the raw sequences.
For WS253 and newer we started to build UTRs from Trinity with RNASeq data,
so you will see some quite impressive changes when it goes live.

Michael
