### ISSUE TITLE
  How do I convert a series of gene nam...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4846]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I convert a series of gene name like, srg-38, to corresponding sequence name, like "T19C4.8 "</p>

**Reported by:** Xinl*** (xinl*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by WenChenWormBase** [comment]
Dear Xinlian,

You can do this using our WormMine tool.

We also have another tool that is under testing, it is called Simple Mine.
The URL for Simple Mine is
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

Please have a look. We are interested in your opinion.

Wen.

On Tue, May 24, 2016 at 8:53 PM, WormBase Helpdesk <notifications@github.com
> wrote:

> *Submitted from the feedback form on the WormBase website.*
>
>   How do I convert a series of gene name like, srg-38, to corresponding
> sequence name, like "T19C4.8 "
>
> *Reported by:* Xinl*** (xinl****************
> *) *Submitted from:* /tools/support
> <http://www.wormbase.org//tools/support>
> *Browser:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0)
> Gecko/20100101 Firefox/46.0
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4846>
>



-- 
Wen Chen, Ph.D.
Curator, WormBase
