### ISSUE TITLE
  Hi,  I just started a new lab and I w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4847]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I just started a new lab and I was wondering how I can get a lab code for naming strains and alleles? Is this done through you guys or through CGC?<br/>Thank you!<br/>Adriana</p>

**Reported by:** Adri************** (asan***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by raymond91125** [comment]
Congrats! Tim Schedl is the person coordinating lab strain/allele names. 
More nomenclature guide can be found here 
<http://www.wormbase.org/about/userguide/nomenclature#0--10>.

Cheers,

Raymond


On 05/25/2016 11:14 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> I just started a new lab and I was wondering how I can get a lab code 
> for naming strains and alleles? Is this done through you guys or 
> through CGC?
> Thank you!
> Adriana
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4847. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4847>.
>
> Reported by: Adriana San Miguel (asanmiguel@ncsu.edu)
> 25 May 16 18:17
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
