### ISSUE TITLE
  could i download the RNAi data of c_e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4848]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;could i download the RNAi data of c_elegans with the ftp?</p>

**Reported by:** fang******** (dong****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.2; rv:11.0) like Gecko

**Comment by epaule** [comment]
have a look into ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/ONTOLOGY/
there are phenotype - RNAi - gene association files, which might be what you were looking for.
