### ISSUE TITLE
Picture links in 'referenced' widget

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4852]
The pictures links in the 'referenced' widget are not working
http://www.wormbase.org/resources/paper/WBPaper00006177#3--10
thanks

**Comment by sibyl229** [comment]
Hi @draciti could you check the picture thumbnails in referenced widget? http://www.wormbase.org/resources/paper/WBPaper00006177#3--10 Thanks!

**Comment by draciti** [comment]
Looks great Sybil, thanks!
that was the link to the live site. I paste here staging for future reference
http://staging.wormbase.org/resources/paper/WBPaper00006177#3--10
