### ISSUE TITLE
Pathway DB update interval

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4857]
Just wondering when the databases in your pathway tool was last updated?

**Comment by chris-grove** [comment]
Hello Luyao,


 We currently use WikiPathways (http://www.wikipathways.org/index.php/WikiPathways) to capture C. elegans biological pathways.


Each of the pathways is updated as curators have time to do so, so there is no regular updating schedule currently. For each individual pathway, for example:


http://www.wikipathways.org/index.php/Pathway:WP2226


You can see date last updated at the bottom of the page.


Best,


Chris Grove

WormBase
