### ISSUE TITLE
images for expression pattern missing

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4868]
Expression pattern for lfi-1

WormBase ID:
Expr1162452
Developmental gene expression time-course. Raw data can be downloaded from ftp://caltech.wormbase.org/pub/wormbase/datasets-published/hashimshony2015
Curated Images:
WormBase thanks Hashimshony, Feder, Levin, Hall, & Yanai, 2015 for providing the pictures.

Gives a broken link report

**Comment by draciti** [comment]
hi Marc,

thanks for reporting the issue. We are aware of it and is already fixed on the staging site, which will be released very soon.
In the meanwhile, attached the image you wee trying to retrieve.

Let us know if you need anything else.

Thanks
Daniela
