### ISSUE TITLE
[wormbase-help] TSSes not viewable in classic Genome Browser

### ISSUE THREAD

**Issue by gw3** [WormBase/website#4871]
Hi all,

I am trying to use the classic Genome Browser to find possible 
Transcription Start Sites (TSSes) in the genomic region around 
srx-96 (V:13711360..13713171).  However, GBrowse is refusing to let 
me see the TSSes (see the attached TIFF for a screenshot of the 
problem).

Also, the alternative genome browser JBrowse is not allowing me to 
specify and zoom in on the genomic region of srx-96, which makes it 
completely unusable as even a 'beta' alternative.

If there's a way to get the TSSes working in GBrowse, please do so!  
Thanks.

--Erich

Erich Schwarz
Senior Research Associate
Cornell University
Department of Molecular Biology and Genetics
Biotechnology, Room 351
Ithaca, NY   14853-2703
Web: http://www.emstech.org
Actual e-mail: ems@emstech.org
Official e-mail: ems394@cornell.edu
Phone: 626-394-7078

**Comment by scottcain** [comment]
Both GBrowse and JBrowse had (unrelated) problems with the TSS tracks.  For GBrowse, I accidentally deleted the wiggle files while making room for some disk use changes.  They've been restored from the dev server.  For JBrowse, I actually noticed while building 253 that the TSS tracks weren't included (and haven't been up until now) and fixed it for 253.  I retroactively applied the fix to 252 now.  The user has been contacted.
