### ISSUE TITLE
Create WormBase URL for Simple Mine

### ISSUE THREAD

**Issue by WenChenWormBase** [WormBase/website#4874]
Dear Web team,

Please create a WormBase URL for SimpleMine tool and place it under "Tool" menu: 
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

Wen.

**Comment by tharris** [comment]
What would you like the URL to be?

**Comment by WenChenWormBase** [comment]
Todd, how about www.wormbase.org/simplemine
?

Wen.

On Tuesday, June 7, 2016, Todd Harris <notifications@github.com> wrote:

> What would you like the URL to be?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WormBase/website/issues/4874#issuecomment-224462066>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABlK0Kmv8FKVyrqL-nlBfyD3BYO0nFqlks5qJhoegaJpZM4Isuzb>
> .
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by tharris** [comment]
That doesn't match the URI scheme for our other tools. Are either of the above sufficient?

**Comment by WenChenWormBase** [comment]
Yes, http://www.wormbase.org/tools/mine/simplemine.cgi looks good to me. Sorry your proposed URL was not displayed in the email. I did not see it until I opened the github page. 

When will the link be live under Tools menu? 

Wen.

**Comment by raymond91125** [comment]
When will the link be live under Tools menu? @tharris

**Comment by WenChenWormBase** [comment]
@tharris I do not see SimpleMine under the Tools menu of either official or staging WormBase sites. Would you let us know when you will add it, so that we can prepare news item?

**Comment by tharris** [comment]
WS254.

**Comment by WenChenWormBase** [comment]
@tharris Now WormBase is on WS254, but I did not see SimpleMine listed under Tool menu. Would you add the SimpleMine link there?

**Comment by tharris** [comment]
Thank you for checking wen. @sibyl229 can you add?

**Comment by sibyl229** [comment]
Hi @WenChenWormBase @azurebrd I will add the the link to http://www.wormbase.org/tools/mine/simplemine.cgi . I just noticed that the URL is showing Gateway timeout, could you double check your server is running? Thanks

**Comment by sibyl229** [comment]
Hi @WenChenWormBase I added the SimpleMine link to the dropdown menu. The change is on staging, would you like to check? And please check with @azurebrd to see if the simple mine server needs restarting. 

Sorry about not noticing your ticket. Next time, could you tag the issue with the "Webteam" label? That will help me find issues that I need to work on. Thank you!

Hi @tharris I created a pull request to production with the SimpleMine link change. We can merge it to production after @WenChenWormBase has taken a look at it.
