### ISSUE TITLE
WS254 release patch

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4876]
Hi Todd,

For WS254 there was a problem with some of the new ncRNA genes for 2 species and because of the way we dump the data I missed that there was only partial representation in the gff3  and that they were  completely missing from the gff2.

I have fixed the data issue and provide 2 patch files in the PATCHES dir on the WS254 ftp release 

```
ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS254/PATCHES/ovolvulus_patch.ace
ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS254/PATCHES/sratti_patch.ace
```

- Could you load them into your acedb database as there may be inplications for the web app behaviour/staging? 

I have also regenerated the gff2 and gff3 files from scratch and have swapped these in.

```
ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS254/species/o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS254.annotations.gff2.gz
ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS254/species/o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS254.annotations.gff3.gz
ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS254/species/s_ratti/PRJEB125/s_ratti.PRJEB125.WS254.annotations.gff2.gz
ftp://ftp.sanger.ac.uk/pub2/wormbase/releases/WS254/species/s_ratti/PRJEB125/s_ratti.PRJEB125.WS254.annotations.gff3.gz

```
- Could the new gff3 be used for the sratti and ovolvulus J/Gbrowse instances for WS254?

Thanks

Paul

**Comment by tharris** [comment]
patched in ace and mysql databases rebuilt.
