### ISSUE TITLE
I would like to get the information on C elegans G...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4877]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to get the information on C elegans GSP 4

**Reported by:** Rudr********** (bane******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/gsp4">http://www.wormbase.org/search/gene/gsp4</a>
**Browser:** Chrome 50.0.2661.102

**Comment by chris-grove** [comment]
Hello Rudra,


 What type of information are you looking for? You can find most information on the gene page here:


http://www.wormbase.org/species/c_elegans/gene/WBGene00020187#0-9g-3


Note that there are data panels to the left that can be turned on and off to show or hide data for the gene.


Best,


Chris Grove

WormBase
