### ISSUE TITLE
Hi I would like to identify a mutation, please con...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4881]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi I would like to identify a mutation, please contact me and I will send you a proper document.

Identification of mutation in DH235 zyg-8 (b235) Exon8

N2 WT
gcaaaattcacggatcgatcgtttaaatagaagcaggagcattaaaaaaatcgaatttttcagGTCTCTTGGTCAGTGCGACATCTGATAATGTGTCTCATTCATACGGATCCATTCCATCGGTATTCAGCCGGTGAGCTTCTCAATGACGAATGGATGGTGgtaagctttcgaaaaaaaaaattgattttccgaaaaatagcttgaaattctggatttttgg

zyg-8 mut (DH235)
gcaaaattcacggatcgatcgtttaaatagaagcaggagcattaaaaaaatcgaatttttcagGTCTCTTGGTCAGTGCGACATCTGATAATGTGTTTCATTCATACGGATCCATTCCATCGGTATTCAGCCGGTGAGCTTCTCAATGACGAATGGATGGTGgtaagctttcgaaaaaaaaaattgattttccgaaaaatagcttgaaattctggatttttgg

Mutation C&gt;T

Change of  Leucine to Phenilalanine

Also I am calling this gene in a next manuscript dclk-1 since it is an orthologue of Isoform 1 of Serine/threonine-protein kinase DCLK1.

**Reported by:** Paol* (pjur***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006993#0d4-9e6b817facg-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00006993#0d4-9e6b817facg-10</a>
**Browser:** Firefox 46.0

**Comment by tuli** [comment]
Dear Paola,

Thank you for writing to WormBase. Before I update the molecular
details of the b235 allele I would be grateful if you more fully
identify yourself.
I do not see your last name in your submission and we do not have a
record of anyone using your email address of pjurado@idibell.cat
Are you a member of a recognised C. elegans laboratory?

Do you have associated evidence for your findings?

Regarding the dclk-1 gene. I would like to refer you to our gene
naming guidelines:
http://www.wormbase.org/about/userguide/nomenclature (see the section
titled "How to apply for new names"). We urge you to only publish gene
names which have been approved by our nomenclature curator.

I look forward to hearing from you.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

On 8 June 2016 at 11:34,  <no-reply@wormbase.org> wrote:
> offline chat Hi I would like to identify a mutation, please contact me and I
> will send you a proper document. Identification of mutation in DH235 zyg-8
> (b235) Exon8 N2 WT
> gcaaaattcacggatcgatcgtttaaatagaagcaggagcattaaaaaaatcgaatttttcagGTCTCTTGGTCAGTGCGACATCTGATAATGTGTCTCATTCATACGGATCCATTCCATCGGTATTCAGCCGGTGAGCTTCTCAATGACGAATGGATGGTGgtaagctttcgaaaaaaaaaattgattttccgaaaaatagcttgaaattctggatttttgg
> zyg-8 mut (DH235)
> gcaaaattcacggatcgatcgtttaaatagaagcaggagcattaaaaaaatcgaatttttcagGTCTCTTGGTCAGTGCGACATCTGATAATGTGTTTCATTCATACGGATCCATTCCATCGGTATTCAGCCGGTGAGCTTCTCAATGACGAATGGATGGTGgtaagctttcgaaaaaaaaaattgattttccgaaaaatagcttgaaattctggatttttgg
> Mutation C>T Change of Leucine to Phenilalanine Also I am calling this gene
> in a next manuscript dclk-1 since it is an orthologue of Isoform 1 of
> Serine/threonine-protein kinase DCLK1.
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00006993#0d4-9e6b817facg-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00006993#0d4-9e6b817facg-10
>
> This issue has been assigned ticket number: #4881. Follow progress on our
> issue tracker.
>
> Reported by: Paola (pjurado@idibell.cat)
> 08 Jun 16 10:36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Paola,

Thank your for the information.

By associated evidence I mean whether the details of the allele have
been published or whether you intend to publish.

I have cc'ed this reply to Tim Schedl who is responsible for gene
names in WormBase. He will consider your proposal and get back to you,
maybe with more questions.
We quite often rename genes so it's absolutely fine to discuss this with us.

Best wishes,

Mary Ann


On 8 June 2016 at 13:40, Paola Jurado <paola.idibell@gmail.com> wrote:
>
> Hi Mary Ann,
>
> I am sorry, my full name is Paola Jurado. This is the link to my wormbase
> profile:
>
> http://www.wormbase.org/resources/person/WBPerson5539#013--10
>
> I do not understand what you mean by associated evidence...
>
> As for the name of the gene, this was more or less a consult. The gene has a
> name already (zyg-8) and there are publications under this name. I just
> think that dclk-1 would have been a better name since it refers to its
> function and is the name that was given in most of the species, but I
> understand that if all suggest different names for the genes wormbase would
> be a mess. I do not know which would be the best way to proceed in this
> case.
>
> Best,
> Paola
>
>
>
>
> El 08/06/2016 a las 13:22, Mary Ann Tuli escribió:
>>
>> Dear Paola,
>>
>> Thank you for writing to WormBase. Before I update the molecular
>> details of the b235 allele I would be grateful if you more fully
>> identify yourself.
>> I do not see your last name in your submission and we do not have a
>> record of anyone using your email address of pjurado@idibell.cat
>> Are you a member of a recognised C. elegans laboratory?
>>
>> Do you have associated evidence for your findings?
>>
>> Regarding the dclk-1 gene. I would like to refer you to our gene
>> naming guidelines:
>> http://www.wormbase.org/about/userguide/nomenclature (see the section
>> titled "How to apply for new names"). We urge you to only publish gene
>> names which have been approved by our nomenclature curator.
>>
>> I look forward to hearing from you.
>>
>> Best wishes,
>>
>> Mary Ann
>>
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>>
>> On 8 June 2016 at 11:34,  <no-reply@wormbase.org> wrote:
>>>
>>> offline chat Hi I would like to identify a mutation, please contact me
>>> and I
>>> will send you a proper document. Identification of mutation in DH235
>>> zyg-8
>>> (b235) Exon8 N2 WT
>>>
>>> gcaaaattcacggatcgatcgtttaaatagaagcaggagcattaaaaaaatcgaatttttcagGTCTCTTGGTCAGTGCGACATCTGATAATGTGTCTCATTCATACGGATCCATTCCATCGGTATTCAGCCGGTGAGCTTCTCAATGACGAATGGATGGTGgtaagctttcgaaaaaaaaaattgattttccgaaaaatagcttgaaattctggatttttgg
>>> zyg-8 mut (DH235)
>>>
>>> gcaaaattcacggatcgatcgtttaaatagaagcaggagcattaaaaaaatcgaatttttcagGTCTCTTGGTCAGTGCGACATCTGATAATGTGTTTCATTCATACGGATCCATTCCATCGGTATTCAGCCGGTGAGCTTCTCAATGACGAATGGATGGTGgtaagctttcgaaaaaaaaaattgattttccgaaaaatagcttgaaattctggatttttgg
>>> Mutation C>T Change of Leucine to Phenilalanine Also I am calling this
>>> gene
>>> in a next manuscript dclk-1 since it is an orthologue of Isoform 1 of
>>> Serine/threonine-protein kinase DCLK1.
>>>
>>> Submitted From:
>>>
>>>
>>> http://www.wormbase.org/species/c_elegans/gene/WBGene00006993#0d4-9e6b817facg-10
>>>
>>> http://www.wormbase.org/species/c_elegans/gene/WBGene00006993#0d4-9e6b817facg-10
>>>
>>> This issue has been assigned ticket number: #4881. Follow progress on our
>>> issue tracker.
>>>
>>> Reported by: Paola (pjurado@idibell.cat)
>>> 08 Jun 16 10:36
>>>
>>> This question was reported via the web interface at wormbase.org. You can
>>> also email us directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the "WormBase:
>>> help"
>>> group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>
>>
>
> --
> Paola Jurado, Ph.D.
> Programa d'Epigenètica i Biologia del Càncer (PEBC)
> Fundació Institut d'Investigació Biomèdica de Bellvitge (IDIBELL)
>  Av.Gran Via de L'Hospitalet, 199 - 203
> 08908 L'Hospitalet de Llobregat
> Barcelona, Spain
> Tel:+34 93 260 72 46  Fax:+34 93 260 72 19
> email: pjurado@idibell.cat.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Tim and user discussing gene name issue separately.

**Comment by Paul-Davis** [comment]
For future reference: This is the lab website.
http://www.idibell.cat/modul/cancer-epigenetics/en

**Comment by tuli** [comment]
Hi Mary Ann, Paola is WBPerson5539, that email address is in her Person 
page.

cecilia
