### ISSUE TITLE
  Hello, is it possible to download the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4882]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>is it possible to download the CDS/protein sequences used as database for the similarity search (BLAST)? I would like to blast around 28k proteins against WormBase and the graphical interface is not suitable for it.<br/>Best regards,<br/>Mihaela</p>

**Reported by:** Miha********** (miha******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by epaule** [comment]
if you pick Species -> C. elegans in the top menu, you should end up here:
http://www.wormbase.org/species/c_elegans
the downloads widget there, should include the C.elegans protein set.
