### ISSUE TITLE
  Hi, I found ftp file "c_briggsae.PRJN...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4883]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I found ftp file "c_briggsae.PRJNA10731.WS250.CDS_transcripts.fa" is empty. Is there a reason why?<br/>Thanks.</p>

**Reported by:** Zhao**** (qzha****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by khowe** [comment]
Assigned to @epaule (build manager for WS250).

**Comment by epaule** [comment]
fixed the file (and checksum) on WTSI/EBI ftp site, needs syncing to the main WB FTP
