### ISSUE TITLE
wikipathways link check

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4887]
Hi @sibyl229 Wikipathways moved to a new webservice a year ago and has made an announcement to everyone to make sure they've updated any connections to their site.  It looks like we are ok, at least the pathways are showing on their respective pages, however, I am confused about the urls we are using. 

Using the Aging process as an example (http://www.wormbase.org/resources/wbprocess/WBbiopr:00000001#034725689--10-3425689)
Do you think we need to update any links to wikipathways? 

------------
Original message: 
"alex.pico" <alex.pico@gladstone.ucsf.edu>: Jun 09 11:51AM -0700 

Just over a year ago, we upgraded the WikiPathways Web Service to a faster 
and more stable version. We kept the old service running as long as we 
could to support existing users while they upgraded their client code. The 
old service was finally retired last week. We have a handful of temporary 
redirects in place, but these will go away eventually as well.
 
*If you suspect that your site or software tools are still using the old 
service calls, please let us know right away and we can help you migrate.* 
 
The New WikiPathways web service is most popular way to access our content. *It 
give you free and fast access to all our content, which is guaranteed to 
remain free and open access.* If you are considering writing tools that 
need pathway information, now is also great time to plug into our new 
services. 
*Read more about it here:*
http://wikipathways.org/index.php/Help:WikiPathways_Webservice/API
*Try it out here:*
http://webservice.wikipathways.org/
--------------------------------
My question to wikipathways: 
Karen Yook <karen@wormbase.org>: Jun 09 04:25PM -0700 

With the change in webservice, what is the URL constructor for our database
to access and show pathways on our site?
 
http://webservice.wikipathways.org/getPathway?pwId=WP4&revision=40020 
or
http://webservice.wikipathways.org/index.php?fileType=gpml&pwId=WP4&revision=0&method=getPathwayAs
 
Assuming we replace use the correct ids and or format
Karen

--------
Alex's answer: 
Hi Karen,
Looks like you updated to the new web service already! It’s not a surprise since we made the switch over a year ago :)
Problematic web service calls will contain “wpi.php” or “webservice.php” in their URL constructors.
If you are concerned about any other cases, however, it’s easy to confirm the correct syntax to use with the new Swagger site, e.g.,
http://webservice.wikipathways.org/ui/dist/#!/All_functions/get_getPathway <http://webservice.wikipathways.org/ui/dist/#!/All_functions/get_getPathway>
 
Here you can put in example variables, click, “Try it out!” and see both the correct URL constructor and the result, e.g.,
http://webservice.wikipathways.org/getPathway?pwId=WP4&revision=400200&format=xml <http://webservice.wikipathways.org/getPathway?pwId=WP4&revision=400200&format=xml> (&format=xml is optional since xml is the default)
and
http://webservice.wikipathways.org/getPathwayAs?fileType=gpml&pwId=WP4&revision=0&format=xml <http://webservice.wikipathways.org/getPathwayAs?fileType=gpml&pwId=WP4&revision=0&format=xml> (&format=xml is optional and the order is not strict)
 
Thanks for checking!
- Alex

**Comment by sibyl229** [comment]
Hi @kyook I updated the wikipathway link prior to the WS253 development freeze (here it is: https://github.com/WormBase/website/pull/4859/files). Staging site is using the http://webservice.wikipathways.org/ url for the pathway image. It will be live soon. I think the pathway image is the only place that uses the Wikipathway webservice right?

**Comment by kyook** [comment]
Yes, as far as I know the process pages are the only ones that use the wikipathways link. 
Thanks for taking care of things @sibyl229 !

**Comment by kyook** [comment]
Sorry, did see that you might still need this issue open.

**Comment by sibyl229** [comment]
Thanks @kyook . It's fine to close the issue. We can reopen it later if needed.
