### ISSUE TITLE
I am trying to associate phenotypes with alleles t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4888]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am trying to associate phenotypes with alleles that are shown under the gene map. If, for example, I see that slo-1 has been isolated as a JUD mutant, How can I determine which alleles were found to be ethanol resistant (on worm base)? 

Thanks

**Reported by:** Rudi***** (rudi**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004830#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004830#0-9g-3</a>
**Browser:** Safari 9.1.1

**Comment by raymond91125** [comment]
If you open the "Phenotypes" widget on the left under "Page Content", 
you can see the seven alleles that have this phenotype.

Raymond
