### ISSUE TITLE
Jbrowse on live site

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4891]
Hia,

it seems like the JBrowse in the location view is not too happy:

http://www.wormbase.org/species/b_malayi/gene/WBGene00227744

![screenshot from 2016-06-13 12 23 49](https://cloud.githubusercontent.com/assets/20523/16005924/dfb26290-3161-11e6-8a0f-1a89a49b15a9.png)

**Comment by scottcain** [comment]
I'm working on it now.  G and JBrowse get updated semi-manually after a new release of WormBase, so I'm catching up with what @tharris did yesterday.

**Comment by scottcain** [comment]
This is mostly fixed now, but an unrelated javascript problem is preventing it from working some of the time.  We should have that sorted out shortly.

**Comment by scottcain** [comment]
The javascript issue has been resolved and jbrowse is now working as expected on production.
