### ISSUE TITLE
  hi there. In proofreading a manuscrip...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4893]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;hi there. In proofreading a manuscript, i was double checking the emb-14/fasn-1 connection and noticed that our reference was missing. I believe we were the ones to verify that emb-14 codes for the fasn-1 gene. If I am wrong, please let me know.  thanks!!<br/>Jaramillo-Lambert, A., Fuchsman, A. S., Fabritius, A. S., Smith, H. E., and Golden, A. Rapid and efficient identification of Caenorhabditis elegans legacy mutations using Hawaiian SNP-based mapping and whole genome sequencing. G3: Genes, Genomes, Genetics 5, 1007-1019 (2015).</p>

**Reported by:** Andy******* (andy**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/6.2.8 Safari/537.85.17

**Comment by vanaukenk** [comment]
Dear Andy,


Thanks for writing to WormBase.


I've added the appropriate gene-paper connections for the G3 manuscript and they will be included in the upcoming database build for WormBase release WS255.


Best,

--Kimberly Van Auken
