### ISSUE TITLE
tRNA and rRNA GFF problems for S. ratti (and possibly others)

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#4894]
While building JBrowse for WS254, I noticed several errors when processing the S. ratti GFF3 file, and it's possible this problem exists for other species too (S. ratti was at the bottom of the log, so that's the one I got to first).  The problem is that for C. elegans and other species that have annotated t and rRNAs, the structure is gene->RNA->exon, and both G and JBrowse are going to expect that to be the case for the gene tracks to work.  In the S. ratti GFF file, there is no gene parent feature, so those features won't be found in the browsers.

**Comment by Paul-Davis** [comment]
Hey @scottcain it might be that this issue hasn't been seen by the web team??

#4876 

Paul

**Comment by Paul-Davis** [comment]
Example gff3 data for s_ratti in the new files:
```
chr1
------
SRAE_chr1       WormBase        gene    1256227 1256348 .       +       .       ID=Gene:WBGene00269798;Name=WBGene00269798;sequence_name=SRAE_1000600045;biotype=tRNA;Alias=SRAE_1000600045
SRAE_chr1       WormBase        tRNA    1256227 1256348 .       +       .       ID=Transcript:SRAE_1000600045;Parent=Gene:WBGene00269798;Name=SRAE_1000600045
SRAE_chr1       WormBase        exon    1256227 1256264 .       +       .       Parent=Transcript:SRAE_1000600045
SRAE_chr1       WormBase        gene    2235847 2235961 .       -       .       ID=Gene:WBGene00269791;Name=WBGene00269791;sequence_name=SRAE_1000600038;biotype=rRNA;Alias=SRAE_1000600038
SRAE_chr1       WormBase        rRNA    2235847 2235961 .       -       .       ID=Transcript:SRAE_1000600038;Parent=Gene:WBGene00269791;Name=SRAE_1000600038
SRAE_chr1       WormBase        exon    2235847 2235961 .       -       .       Parent=Transcript:SRAE_1000600038

chr2
-----
SRAE_chr2       WormBase        gene    124496  124568  .       -       .       ID=Gene:WBGene00269992;Name=WBGene00269992;sequence_name=SRAE_2000600120;biotype=tRNA;Alias=SRAE_2000600120
SRAE_chr2       WormBase        tRNA    124496  124568  .       -       .       ID=Transcript:SRAE_2000600120;Parent=Gene:WBGene00269992;Name=SRAE_2000600120
SRAE_chr2       WormBase        exon    124496  124568  .       -       .       Parent=Transcript:SRAE_2000600120
SRAE_chr2       WormBase        gene    1983168 1983282 .       +       .       ID=Gene:WBGene00269906;Name=WBGene00269906;sequence_name=SRAE_2000600034;biotype=rRNA;Alias=SRAE_2000600034
SRAE_chr2       WormBase        rRNA    1983168 1983282 .       +       .       ID=Transcript:SRAE_2000600034;Parent=Gene:WBGene00269906;Name=SRAE_2000600034
SRAE_chr2       WormBase        exon    1983168 1983282 .       +       .       Parent=Transcript:SRAE_2000600034
```

**Comment by khowe** [comment]
When we provide new/patched versions of the GFF files post data release, we need to prioritise the sync of these files to ftp.wormbase.org (e.g. by setting the status of the ticket to urgent, if this is possible).

**Comment by Paul-Davis** [comment]
I thought the sync process was automatic and if the syncing cron at OICR spots a new date stamp they are automatically pulled over?

**Comment by khowe** [comment]
@Paul-Davis There is a way to check: pull down one of the GFF3 from ftp.wormbase.org

**Comment by Paul-Davis** [comment]
@khowe I have checked the ftp.wormbase.org files and they are the old ones......I just don't know why as I was always lead to believe that there is automatic mirroring on a cron so that new/updated files are just there as they become available. @scottcain if you could arrange for the updated files to be pulled and any patch files (#4876) loaded into the acedb instance, would be appreciated :)

**Comment by scottcain** [comment]
@Paul-Davis: I remember seeing that issue but had quite forgotten about it.  I copied the GFF2 and 3 files to /usr/local/ftp on dev so that I can rebuild the GBrowse and JBrowse datasets. @tharris or @sibyl229  can you take care of the other aspects of #4876.

**Comment by tharris** [comment]
Syncing the GFF files is secondary to the core of this issue but they were re-synced weeks ago, regardless. Even if they are patched and synced automatically it wouldnt have fixed this issue. The underlying databases have to be rebuilt. Which they have been (about a week ago). @scottcain can you confirm that the gbrowse issue is reaolved? I will patch #4876

**Comment by scottcain** [comment]
I rebuilt those databases more like a month ago, so since the syncing is kosher, I'm closing this.
