### ISSUE TITLE
bug report: search for gene 'alg-2' gives Drosophi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4898]
*Help Desk query collected when no chat operators were online. Follow up required.*

bug report: search for gene 'alg-2' gives Drosophila gene (even if I select species elegans). In the suggestion menu there are 2 alg-2, one links to worm, the other to fly. I think the fly should be removed, confusing

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/drosophila_melanogaster/gene/FBgn0086378#0-cg1d46239-10-d">http://www.wormbase.org/species/drosophila_melanogaster/gene/FBgn0086378#0-cg1d46239-10-d</a>
**Browser:** Safari 6.2.8

**Comment by sibyl229** [comment]
Duplicate issue of #4912 Closing.
