### ISSUE TITLE
WS253 orthologs file

### ISSUE THREAD

**Issue by mjsteinbaugh** [WormBase/website#4899]
The c_elegans.PRJNA13758.WS253.orthologs.txt.gz file appears to be empty on the FTP server.

**Comment by epaule** [comment]
@tharris can you resync that file from Sanger/EBI?

thanks,

M

**Comment by epaule** [comment]
Hi Michael,

thanks for reporting it, looks like our FTP syncing didn't work for that
one.
Until we resynched it, you can pick up the correct file here:
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS253/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS253.orthologs.txt.gz

M

**Comment by tharris** [comment]
Done.
