### ISSUE TITLE
why aren't the alleles for pgp-14 showing up?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4900]
*Help Desk query collected when no chat operators were online. Follow up required.*

why aren't the alleles for pgp-14 showing up?

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004008#01ba-9e4d675fgih8c-10-h">http://www.wormbase.org/species/c_elegans/gene/WBGene00004008#01ba-9e4d675fgih8c-10-h</a>
**Browser:** Chrome 51.0.2704.84

**Comment by chris-grove** [comment]
Hi Peter,

 I was able to load the "Genetics" widget on the pgp-14 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00004008#0-4-3

You can click on the "Load other alleles" header to view alleles.

Best,

Chris Grove
WormBase
