### ISSUE TITLE
Text with links to phenotype form are misformatted

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4903]
Minor issue, I noticed that the text with the link to the Phenotype form in the Phenotypes widget on allele and gene pages is improperly formatted, for example:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000063#0c--3

![screen shot 2016-06-16 at 11 16 33 am](https://cloud.githubusercontent.com/assets/611382/16128024/d43d5e84-33b3-11e6-9fba-acffd2bf139c.png)

It looks fine on staging:

http://staging.wormbase.org/species/c_elegans/gene/WBGene00000063#0c--3

![screen shot 2016-06-16 at 11 17 52 am](https://cloud.githubusercontent.com/assets/611382/16128072/06de1bda-33b4-11e6-9781-01261532af24.png)

**Comment by sibyl229** [comment]
Hi @chris-grove there was a transient issue with the stylesheet wasn't updated when the production site went live. The links to "Phenotype form" should appear fine now on production. Thanks!

**Comment by chris-grove** [comment]
@sibyl229  Yep! Looks good, thanks!
