### ISSUE TITLE
Fix display of alleles in Genetics widget when there are no alleles with phenotype

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4904]
As a carry over from issue #4001 

As an example, on the act-2 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000064#0-4-3

In the Genetics widget:

![screen shot 2016-06-16 at 11 22 53 am](https://cloud.githubusercontent.com/assets/611382/16128255/cbf5d21e-33b4-11e6-8f01-715ddb85a254.png)

There are no alleles with phenotype reported for act-2, so the table looks odd with the label "Alleles with phenotype data" and only the drop down headers "Load other alleles (currently with no associated phenotype)". I think maybe a good solution is to create another drop down label "Load alleles with phenotype" that is opened by default to display alleles with phenotypes (or indicate no data) and change the existing section header "Alleles with phenotype data" to simply "Alleles".

Maybe @tuli and @kyook  have other suggestions? I think the earlier proposal to have the labels change depending on whether or not there is data (as proposed in #4001) may be too difficult to implement.

@sibyl229  Do you have an opinion on this?

Thanks!

**Comment by sibyl229** [comment]
Hi @chris-grove the case of empty alleles with phenotype table is now handled: http://staging.wormbase.org/species/c_elegans/gene/WBGene00000064#0-4-3 Do you think it works? Thanks

**Comment by chris-grove** [comment]
@sibyl229  Yes! Perfect! Thanks Sibyl!
