### ISSUE TITLE
Hello,
I was comparing GO annotation for different...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4906]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I was comparing GO annotation for different releases of Wormbase, I found this bit confusing that with increase in release number of GO annotation are going down, 
Gene::GO connections: 
WS235  =266374
WS250 =126496
WS251=138849
WS252= 114093

Is it normal ?
Regards
visitor_name

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/wormbase_release_WS252#01--10">http://www.wormbase.org/about/wormbase_release_WS252#01--10</a>
**Browser:** Chrome 48.0.2564.82

**Comment by vanaukenk** [comment]
Summary:
In general, GO annotations tend to rise steadily with each release.  For the WS251 - WS252 comparison, there was a glitch in the Release Notes that under-reported the InterPro2GO annotations, although the content of the actual GAF was okay.  Also, there was a decrease in the number of phylogenetically based PAINT annotations for WS252.  In the future, any real major changes in annotation numbers could be reported in the README file sent to the GOC.
