### ISSUE TITLE
~2000 C. elegans genes lost their human orthologs in WS254 orthologs file?

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#4907]
@khowe: I am not reporting this so much as a problem, but more of an observation. I was Qc-ing our automated gene summaries from today, as we are getting ready for WS255, noticed that we lost 2,467 orthology statements of C. elegans genes to their human orthologs. When I spot-checked about 10 of these genes, I noticed that the human orthologs are missing from Panther (as the method). See ftp://ftp.wormbase.org/../pub/wormbase/releases/WS254/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS254.orthologs.txt.   The human orthologs are there in the WS253 file. See as examples, abt-5, aat-4 to aat-9 and acr-20.

Was wondering if you folks tightened orthology rules, or were they lost at the original source, e.g. Panther? Anyway, thought I'd ask about this, as 2000+ is an appreciable number.

**Comment by epaule** [comment]
Hi Ranjana,

I updated our PantherDB orthologs from version 9 to 10 in WS254, as you can
see here: http://www.wormbase.org/about/wormbase_release_WS254

As we actually support having multiple evidences/analysis on the orthology
connections, the ones that vanish would have had only Panther-9
predictions, else they would be still there.

But I had a look through the data, and it looks like I missed some UniProt
accessions (notably TrEMBL ones) when I imported them, so there should be a
few more in WS255.

On the positive side,
abt-5 actually lost the human ortholog in Panther 10:
http://www.pantherdb.org/genes/gene.do?acc=CAEEL|WormBase=WBGene00000023|UniProtKB=Q9XW49
and acr-20 too:
http://www.pantherdb.org/genes/gene.do?acc=CAEEL|WormBase=WBGene00000059|UniProtKB=B1Q281

Michael

**Comment by rankishore** [comment]
@epaule: Thanks for the explanation, relieved that it wasn't script errors on our side!  but perhaps there could be an internal as well as external announcement somewhere, as to what was the implications for switching from Panther 9 to 10, as there are internal (us at Caltech) and perhaps external consumers of the data? Just a thought.

**Comment by epaule** [comment]
I did. It is in the release letter for WS254.
And the in depth detail is in the Panther 10 NAR database paper.
But I can put a short version of it in a blog post and schedule it roughly
when WS254 might go live, if you want.

M

**Comment by rankishore** [comment]
Sure, a blog post would be good, since you know the details, feel free to do it. Thanks!

**Comment by epaule** [comment]
I just updated the file on the FTP site
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS254.orthologs.txt.gz

have a look if that one looks nicer.

M

**Comment by rankishore** [comment]
@epaule: You'll have to tell me if it's nicer :) I can only spot-check again by eye, do you know what the changes are? Please let me know what this patch addresses.  Does this mean some C. elegans genes got their human orthologs back? so the number is not 2000+ anymore?  We've just finished running our automated gene summaries pipeline, importing files into our curation tool and qc-ing them etc, etc.. to get them ready for WS255, so we are done this time.  We don't plan to run the pipeline again,  unless your patch has brought about a massive change that affects us.

**Comment by epaule** [comment]
The pantherdb xml links contains uniprot ids from the orthologs, and I must
have downloaded only a part of the UniProt <-> EnsEMBL xrefs.

The patch adds about 6000 H.sapiens connections that are anyway predicted
by some other source and about 8000 that are "Panther specific".

... and I also saw that they just released version 11 like yesterday. No
clue what the difference between 10 and 11 is :-(

M

**Comment by rankishore** [comment]
@epaule: Did a simple comparison between the old and new orthologs files (WS254) using grep for lines with 'Homo' looks like 8000+ lines with human orthologs have now been restored? probably accounting for the 2000+ orthology statements to human genes, that we lost for the C. elegans gene summaries. This forces us to rerun the entire pipeline and redo everything.  Would it be worthwhile for Hinxton to institute an alert, if there is a big change in numbers when you run your scripts for orthologs, would be helpful I think.  Anyway, thanks for fixing the files.

**Comment by epaule** [comment]
Yup, you got a point.

I also got the Panther-11 update already lined up for WS255, which looks
very similar to Panther-10 ... except that it has another 1000 C.elegans
<-> H.sapiens connections. As they didn't include any information in
regards to what datasets they used or what is different, I can't tell you
why.

M

**Comment by epaule** [comment]
btw. Panterh 11 got officially released on Friday, the "release notes" are
here: http://www.pantherdb.org/news/news20160715.jsp

From them I cannot see anything changed, except the underlying proteins.
I will try to come up with some fluff for our release letter.

M
