### ISSUE TITLE
Hi,
we are working in the lab with mutant gbb-1(tm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4908]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
we are working in the lab with mutant gbb-1(tm1406). Although in the wormbase page for this gene indicates that this mutant abnormally fast (http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10). We see a normal locomotion in our hands. The same is described at the National Bioresorce Project for this mutant (https://shigen.nig.ac.jp/c.elegans/mutants/DetailsSearch?lang=english&amp;seq=1406). I think there might have been, possibly, a lack of precision when anotating this mutant since the double mutant gbb-1/gbb-2 has the phenotype of fast movement and few changes of direction indicated. That is what is shown at the evidence paper from Dittman &amp; Kaplan, 2008 (http://www.jneurosci.org.sire.ub.edu/content/28/28/7104.full.pdf+html).
Thanks!

**Reported by:** Paol* (pjur***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10</a>
**Browser:** Firefox 47.0

**Comment by kyook** [comment]
Hi Paola,

Thank you for contacting WormBase with this curation discrepancy.  It
appears the phenotype curation for the tm1406 has been annotated as having
no locomotion defects. I've attached a screen shot of the phenotypes along
with filtered "NOT OBSERVED" phentoypes from the phenotype widget, where
this information has been curated.

However, I see that the concise description of gbb-1 could use some
updating?  I'm including our concise description curator on this message to
see if she can take a look.

Best,
Karen


~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Mon, Jun 20, 2016 at 1:23 AM, <no-reply@wormbase.org> wrote:

> we are working in the lab with mutant gbb-1(tm... (Paola)
> Content-type: text/html; charset="utf-8"
> Date: Mon, 20 Jun 2016 08:22:35 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>
>
>               <style
> type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat Hi,
> we are working in the lab with mutant gbb-1(tm1406). Although in the
> wormbase page for this gene indicates that this mutant abnormally fast (
> http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10).
> We see a normal locomotion in our hands. The same is described at the
> National Bioresorce Project for this mutant (
> https://shigen.nig.ac.jp/c.elegans/mutants/DetailsSearch?lang=english&amp;seq=1406).
> I think there might have been, possibly, a lack of precision when anotating
> this mutant since the double mutant gbb-1/gbb-2 has the phenotype of fast
> movement and few changes of direction indicated. That is what is shown at
> the evidence paper from Dittman &amp; Kaplan, 2008 (
> http://www.jneurosci.org.sire.ub.edu/content/28/28/7104.full.pdf+html).
> Thanks!  <p>Submitted From:
> <br>&nbsp;&nbsp;
> http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10
> <a href="
> http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10
> ">
> http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10
> </a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #4908. Follow progress on our
> <a href="https://github.com/WormBase/website/issues/4908">issue
> tracker</a>.
> <p>
>
> <p>
> Reported by: Paola (pjurado@idibell.cat) <br />
> <span class="fade">20 Jun 16 08:22 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can
> also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>

**Comment by kyook** [comment]
Hi Karen,

thanks for your reply and the shot of the phenotypes. Yes, definitively, 
the concise description needs to be fixed.

Regards,
Paola


El 20/06/2016 a las 19:42, Karen Yook escribió:
> Hi Paola,
>
> Thank you for contacting WormBase with this curation discrepancy.  It 
> appears the phenotype curation for the tm1406 has been annotated as 
> having no locomotion defects. I've attached a screen shot of the 
> phenotypes along with filtered "NOT OBSERVED" phentoypes from the 
> phenotype widget, where this information has been curated.
>
> However, I see that the concise description of gbb-1 could use some 
> updating?  I'm including our concise description curator on this 
> message to see if she can take a look.
>
> Best,
> Karen
>
>
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 415.306.4150
> e-mail: kyook@caltech.edu <mailto:kyook@caltech.edu>
> e-mail: karen@wormbase.org <mailto:karen@wormbase.org>
> skype name: wbkaren
>
>
> On Mon, Jun 20, 2016 at 1:23 AM, <no-reply@wormbase.org 
> <mailto:no-reply@wormbase.org>> wrote:
>
>     we are working in the lab with mutant gbb-1(tm... (Paola)
>     Content-type: text/html; charset="utf-8"
>     Date: Mon, 20 Jun 2016 08:22:35 +0000
>     MIME-Version: 1.0
>     Content-Transfer-Encoding: 7bit
>
>
>
>                                 <style
>     type="text/css">.fade{font-size:.9em;color:#999}</style> offline
>     chat Hi,
>     we are working in the lab with mutant gbb-1(tm1406). Although in
>     the wormbase page for this gene indicates that this mutant
>     abnormally fast
>     (http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10).
>     We see a normal locomotion in our hands. The same is described at
>     the National Bioresorce Project for this mutant
>     (https://shigen.nig.ac.jp/c.elegans/mutants/DetailsSearch?lang=english&amp;seq=1406).
>     I think there might have been, possibly, a lack of precision when
>     anotating this mutant since the double mutant gbb-1/gbb-2 has the
>     phenotype of fast movement and few changes of direction indicated.
>     That is what is shown at the evidence paper from Dittman &amp;
>     Kaplan, 2008
>     (http://www.jneurosci.org.sire.ub.edu/content/28/28/7104.full.pdf+html).
>     Thanks!  <p>Submitted From:
>     <br>&nbsp;&nbsp;http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10
>     <a
>     href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00021528#0d4-9e6b817facg-10</a>
>     </p>
>
>     <p>
>     This issue has been assigned ticket number: #4908. Follow progress
>     on our <a
>     href="https://github.com/WormBase/website/issues/4908">issue
>     tracker</a>.
>     <p>
>
>     <p>
>     Reported by: Paola (pjurado@idibell.cat
>     <mailto:pjurado@idibell.cat>) <br />
>     <span class="fade">20 Jun 16 08:22 </span><br /><br />
>     <span class="fade"> </span>
>     </p>
>
>     <p class="fade">
>     This question was reported via the web interface at wormbase.org
>     <http://wormbase.org>. You can also <a
>     href="mailto:help@wormbase.org <mailto:help@wormbase.org>">email
>     us</a> directly.
>     </p>
>
>     --
>     --
>     You received this message because you are subscribed to the
>     "WormBase: help" group.
>     To post to this group, send email to help@wormbase.org
>     <mailto:help@wormbase.org>
>     To unsubscribe from this group, send email to
>     help+unsubscribe@wormbase.org <mailto:help%2Bunsubscribe@wormbase.org>
>     For more options, visit this group at
>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>

-- 
Paola Jurado, Ph.D.
Programa d'Epigenètica i Biologia del Càncer (PEBC)
Fundació Institut d'Investigació Biomèdica de Bellvitge (IDIBELL)
  
Av.Gran Via de L'Hospitalet, 199 - 203
08908 L'Hospitalet de Llobregat
Barcelona, Spain
Tel:+34 93 260 72 46  Fax:+34 93 260 72 19
email: pjurado@idibell.cat.
