### ISSUE TITLE
  Hi, if I want to browse the C. elegan...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4909]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, if I want to browse the C. elegans genome for a (TF binding) consensus site (say 8 nt), and possibly with some woobling allowed at certain positions, how would I do this???<br/>Thanks a lot for your imput!!!!<br/>sophie</p><p>What were you doing? <br />&nbsp;&nbsp;trying to ID loci that bear a/several consensus sites for my favorite TF - Blast would not do for this</p>

**Reported by:** Soph************ (soph***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by brucebolt** [comment]
Did anyone reply to Sophie?  I can see no response on this ticket or on the help@wormbase email list.

**Comment by raymond91125** [comment]
Hi Sophie,

Sorry for the late response. We currently don't have a tool to do this genome wide. For small regions, you can use JBrowse: File -> Add sequence search track -> (tick "Treat as regular expression").

Cheers,

Raymond

**Comment by scottcain** [comment]
Hi Sophie,

Just to add/expand on what Raymond wrote.  In JBrowse, say you wanted to look for an 8 nt sequence that looked like AATAGCTA but wanted to allow the first A to be optionally replaced with a T and the last A to optionally be replaced with a G, you could write this:

  [AT]ATAGCT[AG]

and then tick "Treat as a regular expression" as Raymond suggested.  If you wanted an N, you'd put in [ATGC] to match any nucleotide.  

Also, I'm not positive about this, but I think that you can use this track on whole chromosomes at a time, so you could find all positions in the C. elegans genome pretty quickly.

If you'd like regular expression help, please let us know.

Scott
