### ISSUE TITLE
FTP softlinks for multi-bioproject species

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4910]
I think putting all files from all the bioprojects into one large directory makes navigation a bit difficult. It might be easier, if there would be one folder per bioproject.

ftp://ftp.wormbase.org/pub/wormbase/species/c_remanei/sequence/genomic/

**Comment by tharris** [comment]
So you want:
species/sequence/genomic/bioproject
or
species/bioproject/sequence/genomic

I'm a little reluctant to do this since releases prior to WS237 had no bioprojects. All of those symlinks would still be in the main species directories unless reorganized manually.

**Comment by tharris** [comment]
Okay, @epaule if you can provide updated ASSEMBLIES.json files for all old releases, I can reorganize the FTP site.

**Comment by epaule** [comment]
I just saw, that you actually do it already in ftp://ftp.wormbase.org/pub/wormbase/species/c_remanei ... so it is probably more a case of trawling through documentation to point to the correct directory.

Will do that in a calm moment.

**Comment by tharris** [comment]
Yeah, I just set it up. The problem is that files pre WS237 cannot be managed in the same manner without the bioproject IDs and the ASSEMBLIES.json file.
