### ISSUE TITLE
Hi 

slight glitch on searching for che-13 in "gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4912]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi 

slight glitch on searching for che-13 in "gene", links to the drosophila gene page rather then the C. elegans one.  You can find the CE che-13 gene page if you search for che-13 in "all". Just a minor problem,

**Reported by:** Deli* (deli************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000492#0123456789abcdefg--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000492#0123456789abcdefg--10</a>
**Browser:** Firefox 46.0

**Comment by epaule** [comment]
that is kind of a duplicate of #4898 and would be probably solved if the autocomplete would show the species after the id.

**Comment by khowe** [comment]
We did put a workaround in place in the build to cover for this: if the fly/zfish gene etc has the same public name as a worm gene, then put a species prefix in front of it. 

However, in this case, the fly gene is called "Che-13" (upper case "c"), so our code treated is as distinct from "che-13". Acedb, unfortunately, normalised both to "che-13" on storage. 

We will put in a fix for this in WS255.

**Comment by sibyl229** [comment]
Hi @epaule I think the problem with searching for che-13 and alg-2 has been fixed. I have prevented search redirect on everything except ones associated with c_elegans and ones that aren't associated with any species (like GO, paper, etc). Do you think this works?

There is a related issue #4898 that can probably be closed, when this issue is ready.

Thanks!

**Comment by epaule** [comment]
You fix works on the live site, but staging behaves in the old way.
Technically it solves the behaviour of the search, but personally I think it would be nice if the species would appear in the autocomplete so people can disambiguate themselves.

**Comment by sibyl229** [comment]
Hi @epaule the autocomplete on staging now includes the species name in suggestion (if applicable) with @miyukimouse 's help. Autocompleting to entities not associated with a species (like GO term, person, etc) works just as before. Could you take a look please? Thank you!

**Comment by epaule** [comment]
nice :-)

**Comment by sibyl229** [comment]
@epaule Yay. Closing
