### ISSUE TITLE
WS254 panther patch

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4917]
could you:

sync these ones:
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS254.orthologs.txt.gz
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/CHECKSUMS

and the whole of
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/PATCHES

and load ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS254.orthologs.txt.gz

into the acedb database.

it is the website follow-up of #4907

thanks,

M

**Comment by tharris** [comment]
synced and patched.

**Comment by epaule** [comment]
should have been: load ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS254/PATCHES/orthologs.panther.ace.gz ... as the other one is a plain text dump

**Comment by tharris** [comment]
Yes i loaded the ace file in the patches dir
