### ISSUE TITLE
Hello
I have bunch of WBPaper IDs and I want to ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4918]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello
I have bunch of WBPaper IDs and I want to get associated PMIDs. Where can I get this information.
Thanks
visitor_name

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-4-">http://www.wormbase.org/#01-23-4-</a>
**Browser:** Chrome 48.0.2564.82

**Comment by tuli** [comment]
Dear Nishant,

Thank you for writing to WormBase.

Is this a one-off task? If so, then I am very happy to get the
information you need. If you can just send me a plain text list of
WBPaperIDs.

If it's something you think you will need to do more frequently then I
will need to find the best way for you to run the query yourself.

Please let me know.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Sent user link to http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/generic.cgi?action=WpaXref and he's happy.
