### ISSUE TITLE
Hi,
I hope this is a simple question, but I can't ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4919]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
I hope this is a simple question, but I can't find best_blastp_hits.WS130.gz on the ftp site. Could you please send me a link to the file.
Kind regards,
visitor_name

**Reported by:** Patt* (p.ku********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#876254cb30da1e9--10">http://www.wormbase.org/about/Frequently_asked_questions#876254cb30da1e9--10</a>
**Browser:** Chrome 51.0.2704.103

**Comment by epaule** [comment]
have you tried: ftp://ftp.wormbase.org/pub/wormbase/releases/WS130/species/c_elegans/c_elegans.WS130.best_blast_hits.txt.gz
?
