### ISSUE TITLE
I'm looking for the multiple sequence alignment fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4920]
_Help Desk query collected when no chat operators were online. Follow up required._

I'm looking for the multiple sequence alignment for cutl-21 but cannot find it?  Can you point me in the right direction?

**Reported by:** Pete****\* (pete****************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00018861#0a9cdefjh-41g6-3-h">http://www.wormbase.org/species/c_elegans/gene/WBGene00018861#0a9cdefjh-41g6-3-h</a>
**Browser:** Chrome 51.0.2704.103

**Comment by epaule** [comment]
could the webteam load:
for the live site ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/MULTI_SPECIES/wormpep_clw.WS253.sql.gz

and for staging:
ftp://ftp.wormbase.org/pub/wormbase/releases/WS254/MULTI_SPECIES/wormpep_clw.WS254.sql.gz

while it will only partially fix the observed problem on live, it will fix it on staging.

**Comment by WenChenWormBase** [comment]
Hi Peter,

thanks for reporting that, I think it was a side effect of us renaming some files. It should look better once the correct files are at the correct place. Feel free to follow https://github.com/WormBase/website/issues/4920 to see any progress.

Michael Paulini

**Comment by khowe** [comment]
@tharris : Protein Aligner widget is broken due to this issue.
