### ISSUE TITLE
Hi there, I am trying to extract information about...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4921]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there, I am trying to extract information about the human monologues (if present) of a bunch of genes (around 5000 genes). I tried WormMine but it doesn't seem to have that information. Can you please give me any hint as to how to do it? I have the genes in a WormBase ID format. Thank you in advance!

**Reported by:** Kons*************** (kkag*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008690#01-9gecb364-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00008690#01-9gecb364-10</a>
**Browser:** Firefox 45.0

**Comment by chris-grove** [comment]
Resolved via chat
