### ISSUE TITLE
  Hi there, I just found that the mutat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4929]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there,<br/>I just found that the mutations described on wormbase for pig-1(gm344) and toe-2(gm407) are incorrect. My sequencing results (also consistent with the actual published details for the alleles) show that:<br/>1. pig-1(gm344) is a 524 bp deletion (and not a b562 bp deletion, as mentioned on wormbase) <br/>and<br/>2. toe-2(gm407) is a 6bp deletion (instead of a 3bp deletion, as described on wormbase).<br/>Kindly correct the errors.<br/>Thanks<br/>Nikhil</p>

**Reported by:** Nikh********* (mish*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by tuli** [comment]
Dear Nikhil,

Thank you for writing to WormBase and for bringing these mistakes to
our attention.

I would like to confirm that I have corrected the curation of the
molecular details of both gm344 and gm407. You will see the update in
release WS255 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
