### ISSUE TITLE
  Hi, a query does not work in WormMine...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4930]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, a query does not work in WormMine. Wormine quitted with an error message, that a table could not be loaded<br/>And the WormMine contact page (it links at http://intermine.wormbase.org/tools/support) is broken. <br/>Thanks,<br/>Stephan</p><p>What were you doing? <br />&nbsp;&nbsp;<query name="query_12" model="genomic" view="Transcript.symbol Transcript.primaryIdentifier Transcript.gene.primaryIdentifier Transcript.gene.secondaryIdentifier Transcript.gene.symbol Transcript.sequence.residues Transcript.method Transcript.chromosome.locatedFeatures.end Transcript.chromosome.locatedFeatures.start Transcript.chromosome.locatedFeatures.strand" longDescription="" sortOrder="Transcript.symbol asc">
  <constraint path="Transcript.gene.secondaryIdentifier" op="=" value="B0041.8"/>
</query></p>

**Reported by:** Step*********** (jano**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/537.86.6

**Comment by StephanJanosch** [comment]
The "what were you doing section" was not transferred into the ticket, so here is there query

```xml
<query name="query_12" model="genomic" view="Transcript.symbol Transcript.primaryIdentifier Transcript.gene.primaryIdentifier Transcript.gene.secondaryIdentifier Transcript.gene.symbol Transcript.sequence.residues Transcript.method Transcript.chromosome.locatedFeatures.end Transcript.chromosome.locatedFeatures.start Transcript.chromosome.locatedFeatures.strand" longDescription="" sortOrder="Transcript.symbol asc">
  <constraint path="Transcript.gene.secondaryIdentifier" op="=" value="B0041.8"/>
</query>

```

**Comment by chris-grove** [comment]
Thanks @StephanJanosch that helps a lot. We'll look into the problem. In the meantime, I think you'll have better luck querying from the Gene perspective. Try this query:
```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.transcripts.method Gene.transcripts.symbol Gene.chromosomeLocation.start Gene.chromosomeLocation.end Gene.chromosomeLocation.strand Gene.transcripts.sequence.residues" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.secondaryIdentifier" op="=" value="B0041.8"/>
</query>
```

**Comment by chris-grove** [comment]
Hi again @StephanJanosch 
Apologies, WormMine is now having trouble with the previous query I suggested. I can confirm that this query is best to use for now:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.transcripts.method Gene.transcripts.symbol Gene.transcripts.chromosome.primaryIdentifier Gene.transcripts.chromosomeLocation.start Gene.transcripts.chromosomeLocation.end Gene.transcripts.chromosomeLocation.strand" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.secondaryIdentifier" op="=" value="B0041.8"/>
</query>`

I hope that helps.

**Comment by chris-grove** [comment]
I'm closing this ticket as I think the underlying issues are being handled by a number of other tickets
