### ISSUE TITLE
  Is there a query that will return the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4931]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a query that will return the number values that go into the graph labelled "FPKM expression data from selected modENCODE libraries:" in the Expression tab?  I would like to do this for a list of genes.</p>

**Reported by:** Dave********** (eise*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Gschindelman** [comment]
Does anybody have an answer for Dave? This helpdesk ticket was submitted one week ago.
Gary S
Helpdesk officer

**Comment by raymond91125** [comment]
There's not a query tool that i know of. however,  #4892 shows how one can download the data, one study at a time.

**Comment by WenChenWormBase** [comment]
No respond from the user after emailing him on July 18. 

-------------------------------
Dear Dave,

Sorry that your email fell through the cracks if no one has responded to you. You can download FPKM data from our SPELL
search engine, if you know which paper the data come from:

http://spell.caltech.edu:3000/search/dataset_listing


Let me know if you need further help,
