### ISSUE TITLE
Hi

Could you please add me to the labheads@wormba...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4938]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi

Could you please add me to the labheads@wormbase.org mailing list. I am a professor at Simon Fraser University. 

Thanks! 

visitor_name

**Reported by:** Jack***** (chen********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#01--10">http://www.wormbase.org/about/userguide/submit_data#01--10</a>
**Browser:** Chrome 51.0.2704.103

**Comment by tharris** [comment]
Hi Jack - 

You've been subscribed to the list since Jan 13, 2016 at this email address.

Todd
