### ISSUE TITLE
  How do I retrieve the type of transcr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4942]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I retrieve the type of transcript (eg. protein coding, ncRNA, snoRNA) of a gene through WormMine?</p>

**Reported by:** stev* (sfre**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by epaule** [comment]
I don't think that is yet indexed by WormMine, but you can give our BioMart installation a spin:
http://goo.gl/rAuWNP gives a biotype for eat-4, just change the filter to whatever ids you want, and it should return their biotypes.

**Comment by chris-grove** [comment]
Hi Steve,


 You can get at the transcript type by querying for the "Method" attribute of the transcript, as in this example query:


```<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.transcripts.method Gene.transcripts.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>```

You can import the above XML via the "import query via XML" link on the QueryBuilder page of WormMine.


Best,


Chris Grove

WormBase
