### ISSUE TITLE
  Hi,  It looks like the Genetic Map to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4944]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>It looks like the Genetic Map tool is currently not working - when I attempt to access it, either from the "Tools" drop-down menu or from a gene page, I get a "504 Gateway time-out" error.  <br/>Thanks,<br/>Dan</p>

**Reported by:** Dan ********** (ddic*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by tharris** [comment]
Hello Dan - 

Thank you for reporting the issue. This should now be resolved. 

My apologies for the difficulties.

Todd
