### ISSUE TITLE
  I keep getting, "04 Gateway Time-out"...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4945]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I keep getting, "04 Gateway Time-out" when I try and use the Wormbase Blast</p>

**Reported by:** Hila************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by tharris** [comment]
Hello Hillary - 

Thank you for reporting the issue. This should now be resolved. 

My apologies for the difficulties.

Todd
