### ISSUE TITLE
  Is there a quick way to obtain the pr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4947]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a quick way to obtain the promoter sequence for specific genes (without going through BLAST)? The "sequence" information only provides coding region and the 3'UTR.</p>

**Reported by:** pame******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML, like Gecko) Version/6.1 Safari/537.71

**Comment by Gschindelman** [comment]
Pamela,
perhaps the following threads on our issue tracker will help:

https://github.com/WormBase/website/issues/3756
https://github.com/WormBase/website/issues/4706
https://github.com/WormBase/website/issues/4537

Please let me know if this was helpful
Gary S
WormBase Helpdesk

**Comment by chris-grove** [comment]
Hi Pamela,


 You can use WormBase ParaSite BioMart to get the promoter sequences of a list of genes. You can find a link to ParaSite BioMart under the WormBase Tools menu at the top of any WormBase page.


If you need any assistance, please let me know.


Best,

Chris Grove

WormBase
