### ISSUE TITLE
visitor_name (visitor_email): Good work, WormBase!...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4952]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Good work, WormBase!</br>Todd: Thanks, visitor_name!

**Reported by:** Fran*** (fran***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004958#0134679acdefg--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00004958#0134679acdefg--10</a>
**Browser:** Safari 9.0

**Comment by Gschindelman** [comment]
I guess we are good
