### ISSUE TITLE
Hello,
I've downloaded a list of genes with 'letha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4953]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I've downloaded a list of genes with 'lethal' or 'sterile' phenotypes in C. elegans from WormMine. I'm wondering whether these phenotypes come from knockouts, or knockdown (eg. RNAi) or other information (eg. allele phenotypes)?
Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000232#0f-9e63bg1c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000232#0f-9e63bg1c-10</a>
**Browser:** Firefox 38.0

**Comment by Gschindelman** [comment]
Avril,
The information currently on WormMine only includes information from allele variations (Not all are null).

To get the RNAi phenotypes you can visit

ftp://ftp.wormbase.org/pub/wormbase/releases/WS254/ONTOLOGY/

You can find several flat files with compiled information for a given release. Specifically, the "rnai_phenotypes.WS254.wb" file is a tab delimited file with all gene-to-RNAi-phenotype connections.


 

we also created a resource for phenotype searches until we include RNAi data in WormMine:

 http://www.wormbase.org/tools/mine/simplemine.cgi

 Hope this helps

Gary S
