### ISSUE TITLE
How do I cite the 'FPKM expression data from selec...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4954]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I cite the 'FPKM expression data from selected modENCODE libraries' data represented in the Life stages vs Expression (FPKM) graph? Thanks!

**Reported by:** Coli* (cede**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004267#014-9gc-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004267#014-9gc-3</a>
**Browser:** Firefox 47.0

**Comment by Gschindelman** [comment]
Colin,
The information on how to cite WormBase can be found here:
http://www.wormbase.org/about/citing_wormbase#012--10

Hope this helps
Gary S
Help desk
