### ISSUE TITLE
images not showing

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4955]
http://www.wormbase.org/species/all/expr_pattern/Expr1149308#01--10

**Comment by sibyl229** [comment]
Hi @draciti I think Todd has fixed the images for http://www.wormbase.org/species/all/expr_pattern/Expr1149308#01--10

**Comment by draciti** [comment]
ok cool, thanks to both of you. closing

**Comment by draciti** [comment]
i confirm they display correctly
