### ISSUE TITLE
Through wormmine I want to determine for a list of...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4956]
*Help Desk query collected when no chat operators were online. Follow up required.*

Through wormmine I want to determine for a list of genes (kinesins) the orthologs in Drosophila, mouse and humans. Is there a way to do that?

**Reported by:** Rash** (ee08************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** MSEdge 13.10586

**Comment by epaule** [comment]
we haven't yet added the orthology data to WormBase,
but if you are happy with basing your query on Compara output, you can try the BioMart on WormBase-ParaSite: http://parasite.wormbase.org/biomart/martview/
While it so doesn't allow you to chain queries, you can get list of ortholog genes between species pairs.

we also have a flatfile with orthology data, if you would rather process it through scripts:
ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS253.orthologs.txt.gz

**Comment by brucebolt** [comment]
Are there any action items from this helpdesk ticket, or can it be closed?

**Comment by raymond91125** [comment]
Unless WormMine wants to keep this open ...
