### ISSUE TITLE
Display image thumbnails on the gene page

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4957]
On the gene page, expression widget, display _200 thumbnails below the Expr object number, instead of the 'view images' text-see screenshot.
<img width="424" alt="screen shot 2016-07-15 at 2 31 20 pm" src="https://cloud.githubusercontent.com/assets/901243/16886283/d711b1c2-4a98-11e6-8491-a17192e4c5ef.png">

Todd just agreed to that ;)

**Comment by sibyl229** [comment]
Hi @draciti is it okay if I fit the image thumbnails in the first column of the table, instead of having it occupying the bottom part of the first two columns? Otherwise, it seems to deviate a lot from the current implementation from these tables, and will introduce problems (with sorting by column for example).

**Comment by draciti** [comment]
sure, let's try it. thanks Sibyl
Also, would it be possible to extend the width of the 'description' column?

**Comment by sibyl229** [comment]
Hi Daniela,

Here is the view of the expression widget with the thumbnails http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#01-9g-3 <http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#01-9g-3>. I create this with help from Miyuki, who is an web designer helping at WormBase. Please let us know what you think.

Sibyl

**Comment by sibyl229** [comment]
@draciti has looked at this and thinks it's ready to close. Closing.

**Comment by draciti** [comment]
Just want to leave a comment: it looks awesome Sibyl, thank you
![screen shot 2016-08-08 at 8 35 50 am](https://cloud.githubusercontent.com/assets/901243/17485855/c56fdb98-5d43-11e6-886e-a06f0aa4fc1c.png)
