### ISSUE TITLE
I would like to have phenotype data for all c. ele...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4961]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to have phenotype data for all c. elegans genes. How can I do that in WormMine?

**Reported by:** Clai** (clai******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Safari 9.1

**Comment by Gschindelman** [comment]
Claire,
The information currently on WormMine only includes phenotype information from allele variations.

You can get information about alleles and their phenotypes from WormMine. From the WormMine QueryBuilder tab:

http://im-dev.wormbase.org/tools/wormmine/customQuery.do

click on the link "Import query from XML" and paste in the following XML to query for all alleles and their observed phenotypes:

<query name="" model="genomic" view="Allele.method Allele.naturalVariant
Allele.primaryIdentifier Allele.symbol Allele.gene.symbol
Allele.phenotypesObserved.name" longDescription=""
sortOrder="Allele.method asc">
</query>

Alternatively, for NOT observed phenotypes use this:

<query name="" model="genomic" view="Allele.method Allele.naturalVariant
Allele.primaryIdentifier Allele.symbol Allele.gene.symbol
Allele.phenotypesNotObserved.name" longDescription=""
sortOrder="Allele.method asc">
</query>


To get the RNAi phenotypes you can visit

ftp://ftp.wormbase.org/pub/wormbase/releases/WS254/ONTOLOGY/

You can find several flat files with compiled information for a given release. Specifically, the "rnai_phenotypes.WS254.wb" file is a tab delimited file with all gene-to-RNAi-phenotype connections

we also created a resource for phenotype searches until we include RNAi data in WormMine:

http://www.wormbase.org/tools/mine/simplemine.cgi


You can follow your issue at:
https://github.com/WormBase/website/issues/4961

Hope this helps
Gary S
