### ISSUE TITLE
 Server Error: 500 at  db/misc/paper   
  Error Me...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4962]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/db/misc/paper?name=WBPaper00049362;class=Paper">db/misc/paper</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::ClassicCompatibility-&gt;misc "mkdir /tmp/wormbase/: Permission denied at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Role/Service.pm line 248." </p>

**Reported by:** smit******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//db/misc/paper">paper</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/6.2.8 Safari/537.85.17

**Comment by tharris** [comment]
Legacy URI; problem fixed, and user contacted to update to "new" format.
