### ISSUE TITLE
Dear Sir/Madam,
I am glad to write to you. May I h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4963]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear Sir/Madam,
I am glad to write to you. May I have some questions? How to design the primers of miRNAs for RT-PCR? Which software and websites will be used? Such as mir-235 in C.elegans?
 How to design the primers of miRNAs for making new vectors? Which software and websites will be used? For example, I want to make a new vector for connecting dpy-7 and mir-235 in C.elegans?

Hope for your reply. Thanks for your attention.

Best regards,
zhifei

**Reported by:** feie* (5422************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** MSEdge 13.10586

**Comment by Gschindelman** [comment]
Zhifei,
On the Wormbase gene page you can find information about the sequences that interest you, for example the location and sequences widgets on the mir-235 gene page.

http://www.wormbase.org/species/c_elegans/gene/WBGene00003328#0-9gcdfe63b1-10

We do not have any tool for primer design or vector construction, but there are many publicly available tools.


Hope this helps

Gary S

**Comment by Gschindelman** [comment]
Zhifel responded

Dear Gary S,

 Thanks for your reply. It is very useful for my
study.
Thanks for your attention.
Best regards,

Zhifei
