### ISSUE TITLE
 Server Error: 500 at  species/c_elegansc_elegans/...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4964]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/species/c_elegansc_elegans/protein/WP:CE23757">species/c_elegansc_elegans/protein/WP:CE23757</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Species-&gt;object_report "mkdir /tmp/wormbase/: Permission denied at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Role/Service.pm line 248." </p><p>What were you doing? <br />&nbsp;&nbsp;Searching for a protein sequence</p>

**Reported by:** Deep*** (deep********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//species/c_elegansc_elegans/protein/WP:CE23757">/species/c_elegansc_elegans/protein/WP:CE23757</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by tharris** [comment]
Resolved, user cntacted.
