### ISSUE TITLE
How to determine if any gene present on a particul...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4966]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to determine if any gene present on a particular chromosome involve in the vulva development? If it is database mining. How to learn it?

**Reported by:** Ish **** (jain*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003040#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00003040#0-9g-3</a>
**Browser:** Chrome 51.0.2704.103

**Comment by raymond91125** [comment]
You can fetch a list of genes that have been annotated to affect vulval 
development in the Ontology browser widget on  phenotype page 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000699#03--10>.
Then you could get at those gene chromosomal locations using Parasite 
Biomart (under Tools).

Cheers

Raymond



On 07/17/2016 06:03 PM, no-reply@wormbase.org wrote:
> offline chat How to determine if any gene present on a particular 
> chromosome involve in the vulva development? If it is database mining. 
> How to learn it?
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00003040#0-9g-3 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00003040#0-9g-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003040#0-9g-3> 
>
>
> This issue has been assigned ticket number: #4966. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4966>.
>
> Reported by: Ish Jain (jaini@mcmaster.ca)
> 18 Jul 16 01:03
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
User contacted; no response. Closing.
