### ISSUE TITLE
  I would like to download a complete g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4967]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to download a complete gene list with genetic and physical positions. Is this possible to do?<br/>Or would you possibly be able to send me this?<br/>Thanks and best regards,<br/>Steven</p>

**Reported by:** Stev******** (s.zu*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by epaule** [comment]
you can easily get the genetic map positions from the GFF3 files.
As example:  ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS253.annotations.gff3.gz

We do have cloned genetic map loci, which are the "absolute_pmap_position" lines, but also have for convenience interpolated genetic map positions for  Alleles, Genes, etc.
