### ISSUE TITLE
  for rhgf-1, the phenotypic informatio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4968]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;for rhgf-1, the phenotypic information below citing our paper is incorrect. Interactions tested were only for rhgf-2 and we did no experiments with rhgf-1 (in fact, I'm just about to start the rhgf-1 experiments).<br/>early elongation arrest	fem-2 : rhgf-1 : rhgf-2	Enhancement	Chan, Rocheleau, Smit, & Mains, 2015<br/>hypercontracted	mel-11 : rhgf-1 : rhgf-2	Epistasis	Chan, Rocheleau, Smit, & Mains, 2015</p>

**Reported by:** Paul****** (main*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by chris-grove** [comment]
Hi Paul,

 Apologies for the error and thanks for letting us know. I've fixed these interactions in our curation database. The changes will be visible in the WS256 release of WormBase.

Thanks again.

Best,

Chris Grove
WormBase
