### ISSUE TITLE
search on staging

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4976]
I seem not to be able to access WBGene00244073 on staging. Neither directly wit the gen page, nor through the search.

**Comment by sibyl229** [comment]
Hi @epaule Yes, I know about this. Gonna fix it today. Thanks for logging it!

**Comment by sibyl229** [comment]
Hi @epaule Sorry, I made a mistake when fixing the search redirect. The problem with accessing the WBGene00244073 gene page should be fixed now. http://staging.wormbase.org/species/o_volvulus/gene/WBGene00244073#04-1-3  Could you take a look please? Thanks

**Comment by epaule** [comment]
seems to work.
thanks
