### ISSUE TITLE
  List function in WormMine does not wo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4978]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;List function in WormMine does not work. I paste my gene list and then click "Create list". After that, it keep showing "Please wait" and would not continue.<br/>Can you check it?</p>

**Reported by:** Yong*** (yy3@*******)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

**Comment by chris-grove** [comment]
Confirmed

**Comment by chris-grove** [comment]
Hello Yong,


 Thanks for reporting the issue, and apologies for the problem. Our team is working on a fix.


Thanks for your patience!


Chris Grove

WormBase

**Comment by chris-grove** [comment]
From Todd on Jul 22:
"Yong -

For now, click on the "advanced" link below the list input box. On the next screen, constrain your search to a given species, then create your list. 

This Is on our list of fixes for WS254

Todd"
