### ISSUE TITLE
  I bought from you, then sent over the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4986]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I bought from you, then sent over the nematode can survive long?</p>

**Reported by:** Lin (s095*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by brucebolt** [comment]
Dear Lin

WormBase does not provide worms.  Could you perhaps clarify your question.

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
