### ISSUE TITLE
How could I Know when a mutant of c.elegans is kno...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4987]
*Help Desk query collected when no chat operators were online. Follow up required.*

How could I Know when a mutant of c.elegans is knockout for this gene? On the contrary, the mutant is not a null mutant. Thanks very much.
visitor_name

**Reported by:** Bego******** (bego**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/cb1270">http://www.wormbase.org/search/gene/cb1270</a>
**Browser:** Chrome 51.0.2704.103

**Comment by tuli** [comment]
Dear Begona,

Thank you for writing to WormBase. Please can you confirm which C.
elegans gene you are interested in?

Thank you,

Mary Ann

On 26 July 2016 at 12:24,  <no-reply@wormbase.org> wrote:
> offline chat How could I Know when a mutant of c.elegans is knockout for
> this gene? On the contrary, the mutant is not a null mutant. Thanks very
> much. Begoña Ayuda
>
> Submitted From:
>   http://www.wormbase.org/search/gene/cb1270
> http://www.wormbase.org/search/gene/cb1270
>
> This issue has been assigned ticket number: #4987. Follow progress on our
> issue tracker.
>
> Reported by: Begoña Ayuda (bego_ayuda@usal.es)
> 26 Jul 16 11:24
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by brucebolt** [comment]
Can this ticket be closed, pending a user response?

**Comment by raymond91125** [comment]
Probably user not following up.

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: MARÍA BEGOÑA AYUDA DURÁN <bego_ayuda@usal.es>
Date: 27 July 2016 at 13:56
Subject: Re: [wormbase-help] offline chat transcript: How could I Know when
a mutant of c.elegans is kno... (Begoña Ayuda)
To: Mary Ann Tuli <maryann.tuli@wormbase.org>


Dear Mary,
My mutants are :
skn-1(zu67)IV/nT1[unc-?(n754)let-?](IV;V)
daf-16 (mu86)I CF1038
daf-18 (e1375)IV CB1375
hsf-1(sy441)p53551

I would like to learn to look for this kind of information in the wormbase.
 Thanks you very much
Begoña Ayuda







2016-07-26 17:25 GMT+02:00 Mary Ann Tuli <maryann.tuli@wormbase.org>:

> Dear Begona,
>
> Thank you for writing to WormBase. Please can you confirm which C.
> elegans gene you are interested in?
>
> Thank you,
>
> Mary Ann
>
> On 26 July 2016 at 12:24,  <no-reply@wormbase.org> wrote:
> > offline chat How could I Know when a mutant of c.elegans is knockout for
> > this gene? On the contrary, the mutant is not a null mutant. Thanks very
> > much. Begoña Ayuda
> >
> > Submitted From:
> >   http://www.wormbase.org/search/gene/cb1270
> > http://www.wormbase.org/search/gene/cb1270
> >
> > This issue has been assigned ticket number: #4987. Follow progress on our
> > issue tracker.
> >
> > Reported by: Begoña Ayuda (bego_ayuda@usal.es)
> > 26 Jul 16 11:24
> >
> > This question was reported via the web interface at wormbase.org. You
> can
> > also email us directly.
> >
> > --
> > --
> > You received this message because you are subscribed to the "WormBase:
> help"
> > group.
> > To post to this group, send email to help@wormbase.org
> > To unsubscribe from this group, send email to
> > help+unsubscribe@wormbase.org
> > For more options, visit this group at
> > http://groups.google.com/a/wormbase.org/group/help?hl=en
> >
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>



-- 

Begoña Ayuda Durán

Dpto. QUÍMICA ANALÍTICA, NUTRICIÓN Y BROMATOLOGÍA

Facultad de Farmacia

UNIVERSIDAD DE SALAMANCA

Campus Miguel de Unamuno

37007 - Salamanca

ESPAÑA

Tlf: +34 923294537 // Fax: +34 923294515

e-mail: Bego_Ayuda@usal.es

grupo de investigación en polifenoles: http://campus.usal.es/~gip/




-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Mary Ann Tuli <maryann.tuli@wormbase.org>
Date: 28 July 2016 at 10:52
Subject: Re: [wormbase-help] offline chat transcript: How could I Know when
a mutant of c.elegans is kno... (Begoña Ayuda)
To: MARÍA BEGOÑA AYUDA DURÁN <bego_ayuda@usal.es>


Dear Begona,

Thank you for your reply.

I suggest you look at both the strain and the variation data that you are
interested in.

e.g. for strain CF1038 go to
http://www.wormbase.org/species/c_elegans/strain/CF1038
Expand the Curatorial remarks field within the Overview widget to give you
more information. The go down to the Contains widget to see a list of
alleles carried by that strain.

You can click on the allele of interest e.g. mu86, which will take you to
http://www.wormbase.org/species/c_elegans/variation/WBVar00089216
Within this Variation page, go to the Molecular Details widget, and within
there go down to Features Affected, click on Predicted CDSs to expand the
table, where you will see how specific alleles affect different isoforms of
the gene of interest.

I hope this helps.

Best wishes,

Mary Ann

On 27 July 2016 at 13:56, MARÍA BEGOÑA AYUDA DURÁN <bego_ayuda@usal.es>
wrote:

> Dear Mary,
> My mutants are :
> skn-1(zu67)IV/nT1[unc-?(n754)let-?](IV;V)
> daf-16 (mu86)I CF1038
> daf-18 (e1375)IV CB1375
> hsf-1(sy441)p53551
>
> I would like to learn to look for this kind of information in the wormbase.
>  Thanks you very much
> Begoña Ayuda
>
>
>
>
>
>
>
> 2016-07-26 17:25 GMT+02:00 Mary Ann Tuli <maryann.tuli@wormbase.org>:
>
>> Dear Begona,
>>
>> Thank you for writing to WormBase. Please can you confirm which C.
>> elegans gene you are interested in?
>>
>> Thank you,
>>
>> Mary Ann
>>
>> On 26 July 2016 at 12:24,  <no-reply@wormbase.org> wrote:
>> > offline chat How could I Know when a mutant of c.elegans is knockout for
>> > this gene? On the contrary, the mutant is not a null mutant. Thanks very
>> > much. Begoña Ayuda
>> >
>> > Submitted From:
>> >   http://www.wormbase.org/search/gene/cb1270
>> > http://www.wormbase.org/search/gene/cb1270
>> >
>> > This issue has been assigned ticket number: #4987. Follow progress on
>> our
>> > issue tracker.
>> >
>> > Reported by: Begoña Ayuda (bego_ayuda@usal.es)
>> > 26 Jul 16 11:24
>> >
>> > This question was reported via the web interface at wormbase.org. You
>> can
>> > also email us directly.
>> >
>> > --
>> > --
>> > You received this message because you are subscribed to the "WormBase:
>> help"
>> > group.
>> > To post to this group, send email to help@wormbase.org
>> > To unsubscribe from this group, send email to
>> > help+unsubscribe@wormbase.org
>> > For more options, visit this group at
>> > http://groups.google.com/a/wormbase.org/group/help?hl=en
>> >
>>
>>
>>
>> --
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>>
>
>
>
> --
>
> Begoña Ayuda Durán
>
> Dpto. QUÍMICA ANALÍTICA, NUTRICIÓN Y BROMATOLOGÍA
>
> Facultad de Farmacia
>
> UNIVERSIDAD DE SALAMANCA
>
> Campus Miguel de Unamuno
>
> 37007 - Salamanca
>
> ESPAÑA
>
> Tlf: +34 923294537 // Fax: +34 923294515
>
> e-mail: Bego_Ayuda@usal.es
>
> grupo de investigación en polifenoles: http://campus.usal.es/~gip/
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
