### ISSUE TITLE
  I have a list of 17,000 proteins. I w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4988]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a list of 17,000 proteins. I want to sort them by tissue expression. What is the best way to do that?</p><p>What were you doing? <br />&nbsp;&nbsp;I tried feeding them into WormMine as a List. Even just trying 100 at a time was unsuccessful. The site kept getting stuck when I wanted to save the table.</p>

**Reported by:** asew****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by WenChenWormBase** [comment]
Dear Aileen,

We are working on a new tool SimpleMine that can help you to get the tissue
information. Do you want to give it a try and let us know how you feel
about it?

http://www.wormbase.org/tools/mine/simplemine.cgi

You can enter UniProt or WormPep ID for the proteins. Let me know if you
encounter any problem.


Wen Chen, Ph.D.
Curator, WormBase

On Tue, Jul 26, 2016 at 5:50 AM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I have a list of 17,000 proteins. I want to sort them by tissue
> expression. What is the best way to do that?
>
> What were you doing?
>   I tried feeding them into WormMine as a List. Even just trying 100 at a
> time was unsuccessful. The site kept getting stuck when I wanted to save
> the table.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4988. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4988>.
>
> Reported by: asewell@colorado.edu
> 26 Jul 16 12:50
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:47.0) Gecko/20100101
> Firefox/47.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
We have developed a new tool called Tissue Enrichment Analysis (TEA). It is not yet public but you may be interested in giving it a test run at <http://www.wormbase.org/tools/enrichment/tea/tea.cgi>. It takes into account the hierarchical relationships of anatomical features that a flat file cannot.


Raymond


________________________________
