### ISSUE TITLE
Hello,

I have a suggestion that I think may help ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4990]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,

I have a suggestion that I think may help the field. 
 
With the advent of CRISPR and other technologies, it has become more popular to make fusion proteins at the endogenous locus. Due to this, I think it would be helpful if Wormbase were to add a "transgene/Reporter/Fusion" section to each gene as another tab (like phenotype,location, etc.). In this tab, labs could submit lines they have made that fit into the category. This way, worm labs will be able to quickly identify if what they want to make already exists, and therefore save time by not making the same thing. I think this would help tremendously for the field. Thanks for your time. 

Best Regards, 
visitor_name
Post-Bac IRTA
Andy Golden Lab
NIDDK/NIH
8 Center Drive, Rm 323
Bethesda, MD 20892

**Reported by:** Tyle******** (tyle****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#d1c294eb08a6735--10">http://www.wormbase.org/about/Frequently_asked_questions#d1c294eb08a6735--10</a>
**Browser:** Chrome 50.0.2661.94

**Comment by kyook** [comment]
Hi Tyler,

Is it that you can't find these data on WormBase, or that you would like to
promote their accessibility from the gene page?

CRISPR and other reporters/fusions are currently listed in the Reagent
widget of each gene page.  The CRISPR constructs themselves include if
there the reporter is an engineered construct used for gene replacement,
please see example on this knl-1 page
http://www.wormbase.org/species/c_elegans/gene/WBGene00002231#0d--10

Make sure to open the reagent widget if it isn't opened already.

This widget includes all reagents created for assaying gene or gene product
function or expression including antibodies.

In addition if you search for knl-1 (as an example) within the Transgene
class (choose transgene from the dropdown menu of the search box), you will
see all reporter/reencoded constructions for that gene.

If you are suggesting further enhancements for finding these reagents let
me know and perhaps we can work something out to alert people to where
these reagents can be found or as you suggest see if we can promote them to
their own widget (I'm not sure how easy this would be I'm afraid).

Best,
karen


~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Tue, Jul 26, 2016 at 6:50 AM, <no-reply@wormbase.org> wrote:

> offline chat Hello, I have a suggestion that I think may help the field.
> With the advent of CRISPR and other technologies, it has become more
> popular to make fusion proteins at the endogenous locus. Due to this, I
> think it would be helpful if Wormbase were to add a
> "transgene/Reporter/Fusion" section to each gene as another tab (like
> phenotype,location, etc.). In this tab, labs could submit lines they have
> made that fit into the category. This way, worm labs will be able to
> quickly identify if what they want to make already exists, and therefore
> save time by not making the same thing. I think this would help
> tremendously for the field. Thanks for your time.  Best Regards, Tyler
> Hansen Post-Bac IRTA Andy Golden Lab NIDDK/NIH 8 Center Drive, Rm 323
> Bethesda, MD 20892
>
> Submitted From:
>
> http://www.wormbase.org/about/Frequently_asked_questions#d1c294eb08a6735--10
> http://www.wormbase.org/about/Frequently_asked_questions#d1c294eb08a6735--10
> <http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#d1c294eb08a6735--10>
>
> This issue has been assigned ticket number: #4990. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4990>.
>
> Reported by: Tyler Hansen (tyler.hansen@nih.gov)
> 26 Jul 16 13:50
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

**Comment by kyook** [comment]
Hansen, Tyler (NIH/NIDDK) [F]
6:28 AM (4 hours ago)

to me 
Ah I see. That makes sense. Thanks. I didn’t check the reagent tab. Thanks for your help. 
Tyler

On Jul 26, 2016, at 5:05 PM, Karen Yook <karen@wormbase.org> wrote:

http://www.wormbase.org/species/c_elegans/gene/WBGene00002231#0d--10
