### ISSUE TITLE
  WormMine is so incredibly slow that i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4991]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormMine is so incredibly slow that it is timing out or failing to complete essentially all tasks. The Contact Help button on WormMine leads to a broken link, so I am writing to you in the hope that you can nudge someone to remedy the problem with the slowdown. Thanks.</p>

**Reported by:** Andr********* (agda***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

**Comment by nuin** [comment]
Checked PG load, system load and the website, all seem fine.

**Comment by tharris** [comment]
I also contacted the user for additional details on query.
