### ISSUE TITLE
  I have never worked with C. elegans b...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4992]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have never worked with C. elegans before, and was wondering whether you could recommend any practical course to learn basic techniques for working with C. elegans, possibly also to learn methods for genetic modification.  Would you know of any such courses?</p>

**Reported by:** Aarn***************** (spoe*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by kyook** [comment]
Karen Yook <karen@wormbase.org>
1:45 PM (21 hours ago)

to no-reply, help, spoela 
Dear Aarnoud, 

Are you a student or researcher?  I'm not aware of any general ongoing courses for introducing the basics of C. elegans as a laboratory model. There used to be one at Cold Spring Harbor, but that appears to have ended.  

Nonetheless, there are many online resources to learn about C. elegans and that discuss it's maintenance and manipulation. Two resources major are
1. WormBook http://www.wormbook.org/ and 
2. WormClassroom http://wormclassroom.org/

These sites contain a plethora of information to give you a solid background on C. elegans. The WormMethods section of WormBook http://www.wormbook.org/toc_wormmethods.html should be a good primer on C. elegans manipulation including genetic analysis tools.  

If you need hands on experience with C. elegans and are associated with a college or university the best thing would be to seek out a lab course there that uses C. elegans, or contact a C. elegans investigator to see if they would let you learn in their lab. 

Hope this information is helpful. Good luck. 

Karen
