### ISSUE TITLE
  Is there a guide anywhere for doing d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4996]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a guide anywhere for doing database-style queries with worm base? My task today was to find all genes with an RNAi phenotype of maternal effect lethal, but I don't know how to even begin to do this search. <br/>I often have related tasks, but without a schema and/or guide to how to use advanced search tools, I don't quite know the right way to go about this.<br/>Thanks for all the good work on wormbase, and thanks in advance for any pointers,<br/>Zach</p>

**Reported by:** Zach********** (zpin*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

**Comment by chris-grove** [comment]
Hi Zachary,

 The most straight-forward way to get your answer is to search "for a phenotype" in the search box (upper right corner of any WormBase page) for "maternal effect lethal" and select "maternal effect lethal emb" from the suggested options that pop up. That should direct you to the "maternal effect lethal emb" phenotype page:

http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000052#03--10

In the "Ontology Browser" widget, click on the "[174 gene products (174 direct)]" next to the phenotype name in the tree view. This will direct you to a page listing all genes that have been directly (or indirectly) annotated to this phenotype term via an RNAi experiment.

If you would still like to try your hand at querying the database, you can find "Queries" and "Schema" under the Tools menu at the top of any WormBase page. The Queries page will provide a query search box and links to examples of and documentation for the two query languages offered AQL and WQL. The Schema page will ask for a data class (e.g. "gene") and will return the database schema for that class. Please note that the web page query tool cannot handle very large or complex queries, so it's best to keep the queries simple for testing.

Hope that helps,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
User is happy :)
