### ISSUE TITLE
i need skn-1 gfp and skn-1 knockdown strains, ther...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4999]
*Help Desk query collected when no chat operators were online. Follow up required.*

i need skn-1 gfp and skn-1 knockdown strains, there are any whith dopaminergic neurons ? thanks

**Reported by:** mari* (mdud****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/strain/skn-1 gfp">http://www.wormbase.org/search/strain/skn-1 gfp</a>
**Browser:** Chrome 51.0.2704.103

**Comment by chris-grove** [comment]
Hello Maria,

You can find this information on the skn-1 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00004804#0d41--10

Look in the "Reagent", "Genetics" and "Expression" widgets (data boxes) for the relevant information. skn-1::GFP transgenes are listed in the "Reagents" widget, alleles are listed in the "Genetics" widget, and the "Expression" widget shows which expression assays revealed skn-1 expression in neurons (It looks like an antibody was used to detect dopaminergic neurons).

I hope that helps.

Best,

Chris Grove
WormBase
