### ISSUE TITLE
WormMine: Cannot retrieve chromosomal coordinates or query for genes in a chromosome interval

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5004]
Hello,

I'm trying to use WormMine to extract the list of genes that fall in a chromosomal interval. I found the template for doing so (Chromosome Interval --> Genes), which appears straightforward. However, the query returns "No Results". I figured the template would be functional. When I add my parameters it also returns no results; I have not been able to get it to return results. Is the tool working, or am I doing something wrong?

Thank you for your help,
Ryan

**Comment by chris-grove** [comment]
This may be related to issue #4960

**Comment by chris-grove** [comment]
Hello Ryan,

 No, you're not doing anything wrong; the chromosome location query is just not working properly at the moment. Thanks for reporting the issue. You can follow progress on this issue on our GitHub issue tracker here:

https://github.com/WormBase/website/issues/5004

Apologies for the inconvenience and thanks for your patience while we fix the problem.

Best,

Chris

**Comment by chris-grove** [comment]
I'll just add that I noticed that the query works when querying for chromosomal location from under the Transcript header, but not under the general Gene header

**Comment by nuin** [comment]
@chris-grove There is an error on the current build either on GFF3 parsing and/or transfer sequence post-process that is preventing from some coordinates to be searched properly. We are working on the new build and hopefully fix these errors.

**Comment by chris-grove** [comment]
@nuin  OK, thanks, sounds good!

**Comment by chris-grove** [comment]
@nuin 
I'm pretty sure this will be solved when the duplicate gene problem from #4842 is resolved.

**Comment by nuin** [comment]
@chris-grove You still see the same problem on 254?

**Comment by chris-grove** [comment]
@nuin 
The template query now runs and returns results, but the gene objects returned are not the real gene objects, i.e. they don't have the proper gene IDs, sequence names or gene names and are not properly connected to any other gene info. The genes returned are the duplicate gene objects that need to be resolved.

**Comment by nuin** [comment]
@chris-grove I fixed the web app, CSS is not working properly still, but the query seems to return better results ATM, can you check?

**Comment by chris-grove** [comment]
@nuin 
Yep, the chromsomal interval query is now returning results. The results highlight the fact that there are still duplicate copies of genes in the data. For example, looking at the results with the default parameters returns the following:

![screen shot 2016-12-09 at 11 07 19 am](https://cloud.githubusercontent.com/assets/611382/21061097/c0451cec-bdff-11e6-9147-546a9589b89f.png)

You can see that many genes return 6 or 9 rows for the same gene, with some of the copies having gene ID of the form "gmap:unc-1" and "landmark:unc-1", for example. These "gmap" and "landmark" gene objects need to be resolved/merged. Also I don't know why there are 3 identical rows for each gene or gene version.

If you'd like I can close this ticket and create two more tickets for the remaining issues: (1) resolving "gmap" and "landmark" copies of genes and (2) resolving the apparent triplicate copies of genes in the chromosomal interval search results.

Let me know what works best.

**Comment by nuin** [comment]
@chris-grove Thanks. I will close this, if you can open the other two tickets, I'd appreciate.
