### ISSUE TITLE
I am interested in requesting a gene name for F52A...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5009]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am interested in requesting a gene name for F52A8.6. KBRL-1 (kappaB-Ras-Like") reflects that this is the sole C. elegans ortholog of kappaB-Ras. "NKIRas" is also used in the mammalian literature, and is of approximately the same usage in the literature. The protein directly binds to I-kappaB, so both names are appropriate.  It is somewhat arbitrary as to which name to choose.  But, from our perspective a connection has been made in the literature between mammalian kappaB-Ras and RalGAP (HGAP-1 and 2 in worms). KappaB-Ras is thought to be part of the GAP complex, and mutants for the worm gene share phenotypes with hgap-1 and hgap-2 mutants.  Thus KappaB-Ras, KBRL-1, probably has the better association and provides more clarity wrt nomenclature. 

Thanks!

Dave R

**Reported by:** Dave******* (drei******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#096g41c8de--10-6418de">http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#096g41c8de--10-6418de</a>
**Browser:** Firefox 47.0

**Comment by tuli** [comment]
test

**Comment by tuli** [comment]
Dear Dave.

Thank you for writing to WormBase. I have forwarded your message to
Tim who will need to approve your proposed gene name. You will hear
from him directly.

Best wishes,

Mary Ann

On 2 August 2016 at 21:46,  <no-reply@wormbase.org> wrote:
> offline chat I am interested in requesting a gene name for F52A8.6. KBRL-1
> (kappaB-Ras-Like") reflects that this is the sole C. elegans ortholog of
> kappaB-Ras. "NKIRas" is also used in the mammalian literature, and is of
> approximately the same usage in the literature. The protein directly binds
> to I-kappaB, so both names are appropriate. It is somewhat arbitrary as to
> which name to choose. But, from our perspective a connection has been made
> in the literature between mammalian kappaB-Ras and RalGAP (HGAP-1 and 2 in
> worms). KappaB-Ras is thought to be part of the GAP complex, and mutants for
> the worm gene share phenotypes with hgap-1 and hgap-2 mutants. Thus
> KappaB-Ras, KBRL-1, probably has the better association and provides more
> clarity wrt nomenclature. Thanks! Dave R
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#096g41c8de--10-6418de
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#096g41c8de--10-6418de
>
> This issue has been assigned ticket number: #5009. Follow progress on our
> issue tracker.
>
> Reported by: Dave Reiner (dreiner@ibt.tamhsc.edu)
> 02 Aug 16 20:47
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by Paul-Davis** [comment]
Dear Dave.

Thank you for writing to WormBase. I have forwarded your message to
Tim who will need to approve your proposed gene name. You will hear
from him directly.

Best wishes,

Mary Ann

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Mary Ann Tuli <maryann.tuli@wormbase.org>
Date: 3 August 2016 at 09:22
Subject: Re: [wormbase-help] offline chat transcript: I am interested
in requesting a gene name for F52A... (Dave Reiner)
To: "Reiner, David" <dreiner@ibt.tamhsc.edu>
Cc: "help@wormbase.org" <help@wormbase.org>, WormBase/website
<reply@reply.github.com>,
Tim Schedl <ts@genetics.wustl.edu>


Dear Dave.

Thank you for writing to WormBase. I have forwarded your message to
Tim who will need to approve your proposed gene name. You will hear
from him directly.

Best wishes,

Mary Ann

On 2 August 2016 at 21:46,  <no-reply@wormbase.org> wrote:
> offline chat I am interested in requesting a gene name for F52A8.6. KBRL-1
> (kappaB-Ras-Like") reflects that this is the sole C. elegans ortholog of
> kappaB-Ras. "NKIRas" is also used in the mammalian literature, and is of
> approximately the same usage in the literature. The protein directly binds
> to I-kappaB, so both names are appropriate. It is somewhat arbitrary as to
> which name to choose. But, from our perspective a connection has been made
> in the literature between mammalian kappaB-Ras and RalGAP (HGAP-1 and 2 in
> worms). KappaB-Ras is thought to be part of the GAP complex, and mutants for
> the worm gene share phenotypes with hgap-1 and hgap-2 mutants. Thus
> KappaB-Ras, KBRL-1, probably has the better association and provides more
> clarity wrt nomenclature. Thanks! Dave R
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#096g41c8de--10-6418de
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#096g41c8de--10-6418de
>
> This issue has been assigned ticket number: #5009. Follow progress on our
> issue tracker.
>
> Reported by: Dave Reiner (dreiner@ibt.tamhsc.edu)
> 02 Aug 16 20:47
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



--
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by Paul-Davis** [comment]
I don't think you need to add this again Tuli.....I see your response 👍

**Comment by tuli** [comment]
Paul Test



On 03/08/2016 09:22, Mary Ann Tuli wrote:
> Dear Dave.
>
> Thank you for writing to WormBase. I have forwarded your message to
> Tim who will need to approve your proposed gene name. You will hear
> from him directly.
>
> Best wishes,
>
> Mary Ann


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
