### ISSUE TITLE
BLAST/BLAT page down

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5012]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Stefan, how can I help?</br>visitor_name (visitor_email): Hello, I just wanted to inform you that the blast tool is down</br>visitor_name (visitor_email): sorry, just got distracted for a second</br>Chris: Ah, OK, apologies. Thanks for letting us know!</br>Chris: No problem</br>Chris: I can email you once it's back up and running</br>visitor_name (visitor_email): great thanks</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): nope, that's it. thanks for the help</br>Chris: OK, take care

**Reported by:** stef** (szdr**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#_=_">http://www.wormbase.org/#_=_</a>
**Browser:** Chrome 51.0.2704.103

**Comment by chris-grove** [comment]
BLAST/BLAT page is throwing a 504 Gateway Time-out
