### ISSUE TITLE
Retrieving information for transposons

### ISSUE THREAD

**Issue by adomingues** [WormBase/website#5016]
Hi,

I am quantifying Transposon abundance using the gene coordinates provided in the gff [c_elegans.WS235.annotations.gff3.gz](ftp://ftp.wormbase.org/pub/wormbase/releases/WS235/species/c_elegans/c_elegans.WS235.annotations.gff3.gz). These contain little information about the gene other than the location and ID in the format BTransposon00000*, and I would like to add some extra information - at least the transposon family to which they belong, possibly also the sequence name. 

Initially I tried to accomplish this using R/Bioconductor `biomaRt` but it seems like WormBase is not longer one the databases it retrieves information from. 

I next noticed that there are tables in the WormBase with information for the Transposon families which contain a list of Transposon loci [here](http://www.wormbase.org/resources/transposon_family/MARINER2#01--10). My question is how/where to download those tables with the correspondence between BTransposon00000* and transposon family+sequence name.

Thanks.

**Comment by brucebolt** [comment]
Hello,

Unfortunately WormMart has been retired and the new WormMine is still in a beta, with some data types not yet available.

I do not believe we make available a file containing the mappings between transposon families and transposon loci.

However, it is possible to programatically access the data from any widget on the website.  This would enable you to retrieve this information on a case by case basis using a script.  Below each widget, there is a Download button.  Select JSON or XML then modify the URL to match the transposon family you would like to get information about.

Best wishes

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD

**Comment by chris-grove** [comment]
@adomingues 
I've put together a dump of all transposon data from our most recent build (WS255):

https://dl.dropboxusercontent.com/u/4290782/WormBase/WS255_transposon_info.xlsx

This includes parent sequence (cosmid/chromosome), family, and remark, among other data. Hopefully that gets you what you need. Unfortunately, we don't currently have an FTP file with this data.

**Comment by adomingues** [comment]
Hi Chris,

Sorry for the late reply but I have been away (still am) for personal reasons. 

Thank you for the data dump! It has been downloaded, and will be very useful. One concern: We are currently transitioning from WS235 (iGenomes WBCel235) - old project were started with this - to the latest version. Do you think this table is compatible with the old annotations? 

Cheers.

**Comment by chris-grove** [comment]
@adomingues 
I'm not sure how much the data may have changed since the WS235 release. 
@Paul-Davis 
Do you have any sense as to how much the transposon annotations have changed since WS235? Can we look at the WS235 release data? I just have access to querying WS255 locally (without specifically building WS235 locally)

**Comment by Paul-Davis** [comment]
I'll take a look and get back to you

**Comment by Paul-Davis** [comment]
To summaries:
WS235 -> WS255 
---------------------

* 33 Transposons manually curated

```
Transposon : "WBTransposon00000740"
Transposon : "WBTransposon00000741"
Transposon : "WBTransposon00000742"
Transposon : "WBTransposon00000743"
Transposon : "WBTransposon00000744"
Transposon : "WBTransposon00000745"
Transposon : "WBTransposon00000746"
Transposon : "WBTransposon00000747"
Transposon : "WBTransposon00000748"
Transposon : "WBTransposon00000749"
Transposon : "WBTransposon00000750"
Transposon : "WBTransposon00000751"
Transposon : "WBTransposon00000752"
Transposon : "WBTransposon00000753"
Transposon : "WBTransposon00000754"
Transposon : "WBTransposon00000755"
Transposon : "WBTransposon00000756"
Transposon : "WBTransposon00000757"
Transposon : "WBTransposon00000758"
Transposon : "WBTransposon00000759"
Transposon : "WBTransposon00000760"
Transposon : "WBTransposon00000761"
Transposon : "WBTransposon00000762"
Transposon : "WBTransposon00000763"
Transposon : "WBTransposon00000764"
Transposon : "WBTransposon00000765"
Transposon : "WBTransposon00000766"
Transposon : "WBTransposon00000767"
Transposon : "WBTransposon00000768"
Transposon : "WBTransposon00000769"
Transposon : "WBTransposon00000770"
Transposon : "WBTransposon00000771"
Transposon : "WBTransposon00000772"
```
* 10496 Predicted (Predicted_*)

* 2 merged.

Data added/changed - existing annotations
---------------------------------------------
* Copy status tags (Full/Partial)
* Corresponding_CDS	
* Gene	
* Member_of (populated for some objects)

* The CDSs that had been added as child objects of some Transposons were relinked to the genome to make mapping consistent.

* With the removal of the second layer of scaffolding in the genome (Chromosome/Superlinks/Clone vs Chromosome/Clone) Some Transposons were moved up a level in the genome.

gff changes not including the new annotations
---------

```
< CHROMOSOME_I.gff:CHROMOSOME_I	Transposon	transposable_element	186273	188077	.	+	.	Transposon "WBTransposon00000695"
> CHROMOSOME_I.gff:CHROMOSOME_I	history	transposable_element	186273	188077	.	+	.	Transposon "WBTransposon00000695"

< CHROMOSOME_I.gff:CHROMOSOME_I	Transposon	transposable_element	1998045	1998893	.	+	.	Transposon "WBTransposon00000348"
> CHROMOSOME_I.gff:CHROMOSOME_I	Transposon	transposable_element	1998047	1999637	.	+	.	Transposon "WBTransposon00000348"

< CHROMOSOME_I.gff:CHROMOSOME_I	Transposon	transposable_element	2054512	2059225	.	-	.	Transposon "WBTransposon00000714"
> CHROMOSOME_I.gff:CHROMOSOME_I	Transposon	transposable_element	2055129	2059225	.	-	.	Transposon "WBTransposon00000714"

< CHROMOSOME_II.gff:CHROMOSOME_II	Transposon	transposable_element	1935481	1937092	.	+	.	Transposon "WBTransposon00000045"
> CHROMOSOME_II.gff:CHROMOSOME_II	history	transposable_element	1935481	1937092	.	+	.	Transposon "WBTransposon00000045"

< CHROMOSOME_II.gff:CHROMOSOME_II	Transposon	transposable_element	3352501	3356303	.	-	.	Transposon "WBTransposon00000668"
> CHROMOSOME_II.gff:CHROMOSOME_II	Transposon	transposable_element	3351580	3356987	.	-	.	Transposon "WBTransposon00000668"

< CHROMOSOME_IV.gff:CHROMOSOME_IV	Transposon	transposable_element	2904732	2908521	.	-	.	Transposon "WBTransposon00000722"
> CHROMOSOME_IV.gff:CHROMOSOME_IV	Transposon	transposable_element	2902772	2909933	.	-	.	Transposon "WBTransposon00000722"

< CHROMOSOME_V.gff:CHROMOSOME_V	Transposon	transposable_element	7310500	7311342	.	+	.	Transposon "WBTransposon00000265"
> CHROMOSOME_V.gff:CHROMOSOME_V	history	transposable_element	7307389	7309556	.	+	.	Transposon "WBTransposon00000265"

> CHROMOSOME_V.gff:CHROMOSOME_V	Transposon	transposable_element	7309917	7311342	.	+	.	Transposon "WBTransposon00000264"
< CHROMOSOME_V.gff:CHROMOSOME_V	Transposon	transposable_element	7309917	7310494	.	-	.	Transposon "WBTransposon00000264"

< CHROMOSOME_V.gff:CHROMOSOME_V	Transposon	transposable_element	4304628	4308697	.	-	.	Transposon "WBTransposon00000732"
> CHROMOSOME_V.gff:CHROMOSOME_V	Transposon	transposable_element	4300957	4311008	.	-	.	Transposon "WBTransposon00000732"
```

**Comment by Paul-Davis** [comment]
@chris-grove as point of contact I will let you decide what info to pass on to the OP if that's ok with you.

P

**Comment by chris-grove** [comment]
@adomingues 
Let us know if the information @Paul-Davis provided was not sufficient to answer your question. I will close this ticket and reopen if necessary.

**Comment by adomingues** [comment]
I am using the data now, and it never thanked you for your quick and helpful replies. 
Thanks!
