### ISSUE TITLE
please what kind of information can retieved from ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5019]
*Help Desk query collected when no chat operators were online. Follow up required.*

please what kind of information can retieved from wormbase database?

**Reported by:** SANN******** (sann*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 48.0.2564.116

**Comment by brucebolt** [comment]
Dear Sanni

WormBase is a repository for data on the biology, genetics and genomics of C. elegans and other related nematodes.  The information available is diverse.  To get an idea of the current features and information stored, you may wish to read the most recent paper in Nucleic Acids Research: http://nar.oxfordjournals.org/content/early/2015/11/16/nar.gkv1217.full

Best wishes

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
