### ISSUE TITLE
Hello, when I go to wormmine, and click on templat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5025]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, when I go to wormmine, and click on templates, it doesn't seem to be bringing up the templates, the page just seems to be  loading, but nothing happening, is something broken?
Regards,
Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Firefox 38.0

**Comment by epaule** [comment]
I had a quick try and it seems to work for me. I also tries a private session/tab and it also returned the templates (and results for them).
Can you give it another try and maybe reset the WormMine cookie?
