### ISSUE TITLE
QC Datomic results on for external links on gene pages

### ISSUE THREAD

**Issue by a8wright** [WormBase/website#5027]
I have made sure as much as possible that the Clojure/ Datomic based API is producing the exact same results as the AcEDB based API. Sibyl and I have made several changes to the website to allow the website to use datomic data when an interface is available. She has also added the ability to know if the data is being received from Datomic or AcEDB, in the staging/development environments. 

Currently  external links part of the gene page on staging are being populated from Datomic. If / When this proves to be successful I will role out another URL (approx. one URL per widget). 

My hope is to be able to role out as many URLs for the gene page before we release WS255

Feel free to contact me if either of you find anything.

**Comment by epaule** [comment]
are you using https://github.com/WormBase/website/blob/staging/root/templates/config/external_urls for the URLs as a shared config?

**Comment by a8wright** [comment]
Hi Michael, 

Thanks for the link. It is actually didn't know about this file. The code isn't using a template for pulling any of the URL's. The logic tends to either be in the database or in the API code. 

For this URL the query for the XREF's is relatively simple - I am not too worried about the correctness of the query. 

That being said, I tested the API for the external_links by querying the URL for several genes with both the AcEDB based API and the Datomic based API. I would take the JSON returned from each and compare. Every time they proved to be identical. 

The reason I am releasing this URL is because I am very confident with it. 

Theoretically if the API's produce the exact same data the website should render identically as well. I did a little bit of looking at the pages to make sure they look reasonable. But this is harder to test. 

That being said, what I am concerned about with these URLs is there being some sort of edge cases that I am not aware of. The one reason for this is that when I am looking through the code for pulling the data from AcEDB vs. Datomic, they are quite different. In the end I know I will be very close with generating the JSON data for the website templates. I just want to have other eyes looking at the results, hoping that someone else will see something that I don't... if there is something to see. 

One last thing. The main config I am working with is the wormbase.conf https://github.com/WormBase/website/blob/staging/wormbase.conf

Let me know if you have any other questions.

**Comment by sibyl229** [comment]
Hi @epaule @a8wright ,  https://github.com/WormBase/website/blob/staging/root/templates/config/external_urls is still being used by the the External link widget. It's downstream of what Adam's code does. I think Adam's code pulls out the data source of the object, while the mapping of the data source to the actual link is still done at the template (.tt2) level based on the templates/config/external_urls.
