### ISSUE TITLE
What is the function of gene numr-1 and numr-2?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5028]
*Help Desk query collected when no chat operators were online. Follow up required.*

What is the function of gene numr-1 and numr-2?

**Reported by:** Yong***** (yong*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00017270#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00017270#0-9g-3</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
Hello Yong,


 I would recommend taking a look at the gene pages for each gene in WormBase:


numr-1

http://www.wormbase.org/species/c_elegans/gene/WBGene00017270#-03ce-10


and numr-2

http://www.wormbase.org/species/c_elegans/gene/WBGene00017267#-03ce-10


In particular, I would take a look at the Overview, Gene Ontology, Phenotypes, and References widgets to get a sense of each gene's function. These genes appear to be involved in response to metals, cadmium in particular.


Hope that helps!


Chris Grove

WormBase
