### ISSUE TITLE
Expression image thumbnails appearing as full size images

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5030]
It looks like the default display of images in the Expression widget on gene pages is showing the full size image, rather than thumbnails. For example, on the hlh-2 page:

![screen shot 2016-08-15 at 12 58 57 pm](https://cloud.githubusercontent.com/assets/611382/17672072/582c1e2a-62e8-11e6-9a87-e5b56437e39b.png)

This is making the widget really wide and cumbersome to view all the data.

**Comment by draciti** [comment]
hey Sibyl, regular pictures -not the renderings like the one in Chris' example- display just fine. 
e.g. http://www.wormbase.org/species/c_elegans/gene/WBGene00001170#-10edg3498cb-10

What I am thinking is that for the regular images you are fetching the pre-generated 200 pixel thumbnail, while for the renderings you are not. Is that right? Do you need us to generate the thumbnails also for the renderings or you can do that at your end?
thanks

**Comment by sibyl229** [comment]
Hi @chris-grove @draciti the problem with expression thumbnail is due to a caching issue. The old styles sheets instead of the new one is being served. This should resolve soon. Todd is looking into it. Sorry about this.

**Comment by draciti** [comment]
great, thanks Sibyl and Todd

**Comment by sibyl229** [comment]
Hi @chris-grove @draciti Todd has fixed the css caching issue, so the worm in expression widget is normal sized now :)

**Comment by draciti** [comment]
looks great, thanks guys!
