### ISSUE TITLE
  I am trying to dowload gff and gtf fi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5039]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to dowload gff and gtf files from the latest release. These files have a bug and couldn't be downloaded to my computer. Would you please check these files?<br/>c_elegans.PRJNA13758.WS255.annotations.gff3.gz<br/>c_elegans.PRJNA13758.WS255.canonical_geneset.gtf.gz<br/>c_elegans.PRJNA13758.WS255.annotations.gff2.gz</p><p>What were you doing? <br />&nbsp;&nbsp;RNA-seq. Trying to align Tophat accepted hits to gtf or gff3 files.</p>

**Reported by:** Hoky**** (hong*****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7

**Comment by rankishore** [comment]
Todd's replied: Do note that WS255 is the *development* release of WormBase. It is not due in production until the end of September.  WS254 is the current production 
That said, the files look okay to me (see below).  Can you let me know where you are running into trouble?
(Did not hear back from User, closing.)
