### ISSUE TITLE
Wikipedia says that Complex II is succinate dehydr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5040]
*Help Desk query collected when no chat operators were online. Follow up required.*

Wikipedia says that Complex II is succinate dehydrogenase or succinate-CoQ reductase, and Complex III is cytochrome bc1 complex or CoQH2-cytochrome c reductase. Than complex II is ubiquinol-cytochrome c reductase in the overview of mev-1 gene. 

Reference: Wikipedia: Electron transport chain

**Reported by:** Yong***** (yong*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003225#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00003225#0-9g-3</a>
**Browser:** Chrome 52.0.2743.116

**Comment by rankishore** [comment]
Changed description of mev-1 to indicate that Complex II is succinate-CoQ reductase and informed User.
