### ISSUE TITLE
Hello,
I'm wondering have you stored information o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5043]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I'm wondering have you stored information on the severeness of phenotypes in WormBase? Also, if a particular gene has a Sterile phenotype in a RNAi screen, do you store the % of animals that have the phenotype?
Regards,
Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Firefox 38.0

**Comment by chris-grove** [comment]
Hi Avril,


 If severity of the phenotype is reported, we usually capture this in a phenotype remark which should be visible wherever the phenotype is displayed for an allele or RNAi experiment, for example. Aside from the phenotype remark (which is just free text) we may also capture the penetrance (% animals that have the phenotype) in a Penetrance or Penetrance Remark field which should also be displayed with the phenotype annotation. The penetrance may be simply listed as "Low", "Incomplete", "High", or "Complete" and/or the actual % presented as an integer value from 0 to 100.


I hope that's clear.


Best,


Chris Grove

WormBase
