### ISSUE TITLE
QC Datomic results on For overview on gene pages

### ISSUE THREAD

**Issue by a8wright** [WormBase/website#5044]
I have released the overview page onto the staging website.

I have checked the json between the between the results from the Datomic REST API and the AceDB API on several URLs.

Once I put the URL on staging I noticed that there are some occurences where in the json there is an empty array or object "{}" when it should be null. This doesn't cause the content to be incorrect but it does cause titles to sections to appear when the shouldn't. This happens rarely and does not effect content. @sibyl229 and I have already discussed this and I will be fixing it on the API side.  

@tharris 

Please check to make sure there are no problems with the data itself and mention any other issues that arise.

**Comment by sibyl229** [comment]
Hi @rankishore, @a8wright has made the Gene overview widget pull data from Datomic. I seem to remember you work on concise descriptions that appear in the Gene Overview. Would you like to take a look at the widget? And do you know anyone else might be interested in checking this widget, to make sure it has everything?

**Comment by rankishore** [comment]
@sibyl and @a8wright: I've checked several genes on the staging site and the overview widget looks good to me with the right data.
@a8wright: A minor detail:  I think that when the 'Details' drop-down is empty, we don't even have to show it in the widget. eg. aat-3.  Also curious about the yellow 'Datomic' label on the right hand side, guessing it's just for the testing phase and will not move to the live site?

**Comment by sibyl229** [comment]
Hi @rankishore Datomic label currently only shows up on staging. I'm looking into having that feature available for users logged in as admins only on production. 

Hi @a8wright Details widget only shows up if the "structured_description" field has content. Is this field one that you are working on converting empty hash to null?

**Comment by rankishore** [comment]
@sibyl and @a8wright: Just to clarify this a bit more, 'Structured_description' has several tags, of these only the data under the 'Concise_description' and 'Automated_description' tags are displayed in the 'Overview widget' (we control at the data dumping level which one gets into the ace file).  The data under all the other tags--'Provisional_description', 'Detailed_description', 'Other_description', 'Sequence_features', 'Functional_pathway', 'Functional_physical_interaction', 'Biological_process', 'Molecular_function' and 'Expression' go into the 'Details' widget, if present.  (I suspect that most of these are not even present in the ace file for most genes).

**Comment by sibyl229** [comment]
Hi @rankishore Adam and I are checking if structured description from these tags are included. We see in the code, that it fetches data for all these tags except Detailed_description. But it appears that there are no gene entries in Acedb with Detailed_description populated in WS255. Do you know if Detailed_description is in use? Thanks!

**Comment by rankishore** [comment]
@sibyl229: Detailed_description seems to be a legacy tag, we don't dump that.  Not sure if we ever used it.

**Comment by sibyl229** [comment]
Thanks @rankishore 

@a8wright based on @rankishore 's comment. Seems that it's safe to ignore the Detailed_description
