### ISSUE TITLE
the link to http://www.wormbase.org/submissions/ph...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5045]
*Help Desk query collected when no chat operators were online. Follow up required.*

the link to http://www.wormbase.org/submissions/phenotype.cgi gives a 504 Gateway time out

**Reported by:** Dani*** (drac***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Safari 9.1

**Comment by draciti** [comment]
Juancarlos confirmed is on tazendra, which is having issues now. Closing
