### ISSUE TITLE
Hello,  Is there a feature in worm base that can g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5047]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,  Is there a feature in worm base that can give me information on the genetic map?  For example: to find out what genes with visual phenotypes (unc, bli, dpy etc)  map in the region of +8.0  on LG3? Or what are the genes at the center of LG5?    Thanks!

**Reported by:** Gaut** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002335#0f-9edcai-10-f">http://www.wormbase.org/species/c_elegans/gene/WBGene00002335#0f-9edcai-10-f</a>
**Browser:** Safari 9.1.2

**Comment by chris-grove** [comment]
Pointed user to Genetic Map tool and Genetic Limits track on GBrowse
