### ISSUE TITLE
  Try getting to the genetic map from a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5049]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Try getting to the genetic map from a specific gene... what you'll get is a "bad gateway" error.  Upshot appears to be that the genetic map is currently nonfunctional.<br/>Any fix to this would be welcome.</p>

**Reported by:** me@n***********
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by chris-grove** [comment]
Fixed
