### ISSUE TITLE
visitor_name (visitor_email): Can anyone recommend...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5053]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Can anyone recommend the best gfp strains of C. elegans and the best lights under which to view the gfp - for high school students?

**Reported by:** Jo-A*** (purd*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 51.0.2704.84

**Comment by rankishore** [comment]
Resolved through chat with @chris-grove, who also directed user to the WormBase forum.
