### ISSUE TITLE
visitor_name (visitor_email): Can you recommend th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5054]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Can you recommend the best instrument for moving worms from plate to plate?

**Reported by:** Jo-A*** (purd*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 51.0.2704.84

**Comment by chris-grove** [comment]
Hi Jo-Anne, most commonly people use a glass Pasteur pipet and platinum wire. You can place a small length (~1 inch or less) of platinum wire inside the narrow end of the Pasteur pipet and melt the glass pipet with a flame, embedding the platinum in the glass. Once cooled, the "worm pick" is ready to be used.

I hope that helps,

Chris Grove
WormBase
