### ISSUE TITLE
QC Datomic results on for history widget on gene pages

### ISSUE THREAD

**Issue by a8wright** [WormBase/website#5058]
I have released to staging the the history widget from Datomic. 

I have tested this widget by comparing the JSON output provided through the AceDB REST interface and the Datomic REST interface. With all the URLs I have checked the output is identical. Once I released the code for this widget to staging I checked several URL's and everything, once again, is identical. 

I have very little concern with this widget, as it is quite simple. 

@tharris 

If anybody sees any issues with this widget please let me know.

**Comment by tuli** [comment]
@a8wright 
I've looked at a few gene objects in staging as requested and can confirm that the History widget looks absolutely fine.
