### ISSUE TITLE
I would like to need some c.elegans about 200 for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5059]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to need some c.elegans about 200 for you, i sincerely hope i can get some c.elegans from you, and i look forward to your reply at your earliest convenience.

**Reported by:** xiao** (zhan**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans#014--10">http://www.wormbase.org/species/c_elegans#014--10</a>
**Browser:** MSEdge 13.10586

**Comment by chris-grove** [comment]
Hello Xiaoxi,


 WormBase does not store or provide strains to users. You may order C. elegans strains from the Caenorhabditis Genetics Center:


http://cbs.umn.edu/cgc/home


Best,

Chris Grove

WormBase
