### ISSUE TITLE
Hello,
This is about cnk-1: two deletion alleles e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5060]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
This is about cnk-1: two deletion alleles exist for this gene (ok836 and sv39). However only ok836 is mentioned in the cnk-1 gene page. I get information on sv39 in the "variations" page but not (as far as I can tell) on the gene page itself.
Thanks.

**Reported by:** Gaut****** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Firefox 31.0

**Comment by rankishore** [comment]
From Todd:
Hi Gautam -On the gene page, you need to check the table for alleles that have no demonstrated phenotype. I think what you are seeing is actually a pointer to a *strain* reagent carrying the ok allele.
