### ISSUE TITLE
visitor_name (visitor_email): Feedback: What a fab...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5066]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Feedback: What a fabulous website. I'm really happy to see information for parasitic nematodes being collected and collated. The format, information and images are amazing.

**Reported by:** Bron************ (ebro****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006754#01-9gh-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006754#01-9gh-3</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
Hello Bronwyn,


 Thanks for the positive feedback! It's much appreciated. We're glad you find the website useful.


Best,


Chris Grove

WormBase
