### ISSUE TITLE
Add 'feature' on gene expression page

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5067]
could you please add, on the expression pattern page, in the details widget a line called

Feature: <display Associated_feature>

See screenshot
<img width="559" alt="screen shot 2016-08-31 at 11 42 52 am" src="https://cloud.githubusercontent.com/assets/901243/18138074/9fea5ac6-6f70-11e6-872f-0f48fbacbcae.png">

thanks

**Comment by raymond91125** [comment]
Might the label be more informative, say "Sequence feature". Show public name in place of ID. And perhaps fetch out the Method tag, in this case "enhancer", and display them.

**Comment by draciti** [comment]
Good points. I have updated the mockup
<img width="750" alt="screen shot 2016-08-31 at 2 08 32 pm" src="https://cloud.githubusercontent.com/assets/901243/18142738/8d3f72a8-6f84-11e6-9241-b3a5eefdd649.png">

**Comment by sibyl229** [comment]
Hi @draciti @raymond91125 here is the field for sequence feature: http://staging.wormbase.org/species/all/expr_pattern/Expr11275#01--10
