### ISSUE TITLE
  To WormBase, greetings! My name is vi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5068]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;To WormBase,<br/>greetings!<br/>My name is visitor_name, I work as a client manager of Annoroad Gene Tech., a renowned technology service company in China. Your company on genetics, genomics, bioinformatics fields are very impressive, and we would like to look for the chance of collaboration, which could assist you to expand the market through our NGS(Next Generation Sequencing) services.<br/>Annoroad Gene Tech, focuses on R&D and services of Next Generation Sequencing, devoting to promote the development of biotechnology and provides excellent technical solutions for life science research. Our Next Generation Sequencing services (Genome, Transcriptome, Epigenome, Hi-C and Single-cell Sequencing) have assisted over 2000 clients in their researches in the past 4 years, and the results have been published on several high impact journals like Science, Nature, Cell Stem Cell, Immunity, etc.<br/>We have accumulated plenty of project experiences and built stable procedures for quality control, library preparation, sequencing and analysis. Our sequencing platform includes Illumina HiSeq X Ten, HiSeq 4000, HiSeq 2500, NextSeq 500 and MiSeq to fulfill different requirements on sequencing strategy and cost. More information can be viewed on our website: en.genome.cn.<br/>It will be great if we could collaborate with each other. Don't hesitate, trust us and  contact us if you want to seek cooperation.<br/>Thanks a lot for your time. Your feedback will be highly appreciated.<br/>Best regards.<br/>Xiaoying</p>

**Reported by:** Xiao********** (xiao*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by chris-grove** [comment]
SPAM, closing
