### ISSUE TITLE
Help Desk: RESTful API help request

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5069]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello!</br>visitor_name (visitor_email): I am having difficulties using the RESTful API</br>visitor_name (visitor_email): is the service functioning?</br>visitor_name (visitor_email): I am planning to create a web app using the RESTful service

**Reported by:** Laur**** (lene****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_developers#145320--10">http://www.wormbase.org/about/userguide/for_developers#145320--10</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
From @sibyl229 
"Hi Laurence,

Sorry about the problem with REST API documentation. The REST API service is running. Here is more documentation on what data types you can access and how to do that: http://www.wormbase.org/about/userguide/for_developers/API-REST#01--10 

Could you let me know what data you are trying to retrieve? Maybe I can help you better that way.

Thank you for writing to us!

Sibyl"

**Comment by chris-grove** [comment]
@sibyl229  Have you heard back? I'll close if you haven't (or its resolved). Thanks.

**Comment by sibyl229** [comment]
Hi @chris-grove I haven't heard back. I will close the issue for now. Will reopen if I hear anything.
