### ISSUE TITLE
New Expression table on the gene page

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5070]
Hi Sibyl,
at the group meeting we discussed about re-vamping the expression widget on the gene page. Instead of the current table displayed under Spatio-temporal expression Patterns, we would like to display a (hopefully) more compact table. don’t be overwhelmed by the description below, look at the mock up first :)

this is the summary view

<img width="462" alt="screen shot 2016-09-01 at 3 40 41 pm" src="https://cloud.githubusercontent.com/assets/901243/18183874/fa49455e-705b-11e6-9611-4bd1c37b70a4.png">

this is the full view

<img width="532" alt="screen shot 2016-09-01 at 3 40 31 pm" src="https://cloud.githubusercontent.com/assets/901243/18183902/1b483b20-705c-11e6-98ac-108701a33578.png">

and this is the boring part- visual cues in the screenshot at the bottom:

The table will have 5 columns, as in the mock-up

Anatomy|Life stage| Cellular component| Method| Experiment

In the Anatomy column we will display the Anatomy_term <name>, e.g. : PLMR for WBbt:0004103.

in the .ace file:
Anatomy_term    "WBbt:0004103"

In the Life_stage column we will display the Life_stage <name>, e.g. : Embryo Ce for WBls:0000003.

in the .ace file:
Life_stage  "WBls:0000003"

In the Cellular component column we will display the GO <name>, e.g. : Nucleus for GO:0005634.

in the .ace file:
GO_term "GO:0005634"

Whenever the .ace file has a life_stage associated to an anatomy_term, in this fashion:
Anatomy_term    "WBbt:0006899" Life_stage "WBls:0000024"

We will display Anatomy and life stage in the same row (the screenshot might be more informative)

We will display only one occurrence of the anatomy object, in case multiple experiments report the same anatomy for a single gene. For example if Expr_1, Expr_2, Expr_3 are all associated to PLMR, we will have ‘PLMR’ in the Anatomy  column and in the Method column we will have a ‘details’ drop down that will list all the papers associated to that evidence, in a similar way GO tables in the GO widget are constructed. 

Same thing for Life_stage or cellular component, we will display one instance per term and link multiple evidences in the Method column.

In the Method column we will list the ‘type’ i.e. reporter gene, Antibody, etc.. with a drop down ‘Details’ that, when opened, will list all the papers associated. 

In the Experiment column we will display 1 image if there are images, -with the same behavior as the images on the gene page, i.e.link to picture full display + gallery; OR Display ExprID(s), linking to the expression page.

<img width="668" alt="screen shot 2016-09-01 at 3 41 01 pm" src="https://cloud.githubusercontent.com/assets/901243/18183966/5ef58ea4-705c-11e6-8f5a-525f643c143e.png">

I know this is a lot to digest at once but I am available any time to Skype to get this started.
thanks :)
d

**Comment by draciti** [comment]
P.S.: there are expression objects that do not have annotations attached (anatomy/life_stage/GO). One example are the Chronograms -screenshot below. Those should be listed at the bottom of the table and will probably have only the Method and Experiment columns populated

<img width="914" alt="screen shot 2016-09-07 at 11 54 08 am" src="https://cloud.githubusercontent.com/assets/901243/18321201/96cd2d9c-74f2-11e6-8c11-87fb6edc88d6.png">

**Comment by draciti** [comment]
New mock-up below:
![screen shot 2017-01-10 at 10 25 55 am](https://cloud.githubusercontent.com/assets/901243/21855774/68969298-d7d4-11e6-8054-506dea643844.png)

**Comment by draciti** [comment]
more specs here:
[mock-up Sibyl_compact.docx](https://github.com/WormBase/website/files/699347/mock-up.Sibyl_compact.docx)

**Comment by sibyl229** [comment]
Hi @draciti I have a question about the Supporting evidence column in the expression pattern tables. Does the "expressed during" under details dropdown come from both the Life_stage tag attached through the Qualifier tag and those directly attached on Expr_pattern? If so, do we make any distinction between the two? Thanks!

**Comment by draciti** [comment]
Hi Sibyl, the 'expressed during' under details drop down in the supporting evidence column should list only the Life_stages attached through the Qualifier tag.
thanks!

**Comment by sibyl229** [comment]
Note for myself, example with qualifier: rest/widget/gene/WBGene00007433/expression

**Comment by sibyl229** [comment]
Hi @draciti here is my WIP on the expression widget tables. They are not staging site yet, please test it on http://dev.wormbase.org:9016. Here is an example: http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000904#1--3 It's a bit different from the mock up you gave me. But I think maybe it's better to show it first before I tune it. 

I ran into some performance issue with genes that are studied in the Expr10220 and Expr10221. http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00007433#1--3 I feel those hundreds of rows base on the two expression pattern are drowning other useful information in the table. Maybe we need to handle them as a special case. What do you think?

Another question, about the big 3D worm image, do you know if it's recorded in ACeDB whether a picture is made for a particular gene or not?

**Comment by draciti** [comment]
it looks great Sibyl, thank you!

one comment: in the Expressed during table, let's not show the image unless the WBPicture is annotated with the corresponding life_stage term. Does this make sense?

I agree the Murray study -WBPaper00040986- should be treated as a special case (this is the one we discussed from the beginning on as a potential PITA (pain in the 'neck') :)

I suggest to have a separate table below the Subcellular localization one called EPIC data that has the current display and behavior- See screenshot.

![screen shot 2017-03-03 at 10 24 16 am](https://cloud.githubusercontent.com/assets/901243/23563451/98aacd6a-fffb-11e6-99ea-808a303980d3.png)

one thing missing from your instance is the 'Expression Profiling Graphs' section, which should stay as is.
Happy to skype if need be
Many thanks

**Comment by draciti** [comment]
forgot to mention that I welcome suggestions on the EPIC dataset display :)

**Comment by sibyl229** [comment]
Hi @draciti I just added the Expression Profiling Graphs back. Please take a look. I seems to remember only the first 4 columns of that take is ever populated, and we agreed to removed the rest from display. Could you confirm that please?

About an earlier question about the 3D worms, like /img-static/virtualworm/Gene_Expr_Renders/WBGene00000904.jpg, is it possible for me to tell if such an image exists for a gene without checking the file on the disk? So is this information in the database somewhere?

Your EPIC table suggestion makes sense to me. I will implement what you have.

Yes. I will do something about the multiple entry of terms.

**Comment by draciti** [comment]
>Expression Profiling Graphs back. Please take a look. 
look good! 

> Could you confirm that please?
confirmed

>About an earlier question about the 3D worms, like /img-static/virtualworm/Gene_Expr_Renders/WBGene00000904.jpg, is it possible for me to tell if such an image exists for a gene without checking the file on the disk? So is this information in the database somewhere?

we need to ask Chris, will ping him via e-mail

thank you!

**Comment by chris-grove** [comment]
@sibyl229 @draciti 
I've never made any database entries for genes with virtual worm images. I believe I just asked Todd to pull from a source directory, although it's been a while now so I can't recall all the details.

**Comment by sibyl229** [comment]
Hi Thanks @chris-grove @draciti for looking into this for me. The reason I'm asking is that (as part of the database migration on the website end), the new API/web service that powers the widget data is running on a different instance, with no access to the file system that these images are served from. I wonder if it's possible to make a Picture object for these images, because aside from the current technical issue, it seems to make sense to track this information in the database. Please take your time to think about it (this doesn't block me from migrating the rest of the expression widget.).

**Comment by sibyl229** [comment]
Hi @draciti a couple of questions here:

* I'm working on the Microarray "topography map" data field. I'm not sure what would be a straight forward way of identifying the expr_profile of a gene. It seems that the name of the expr_profile is the same as the sequence name of the gene, like T13C5.1 for daf-9. But I'm not sure if this is a reliable way of identifying expr_profile. What do you suggest?
* I guess I can remove the "Anatomy terms" field, which is a list of anatomy terms (refer to production site)?

I also have a few more things ready for testing here. Since I'm converting everything in the expression widget to use Datomic instead of ACeDB, I might break things. Please let me know if anything is off. There are some fields missing. I'm working on adding them back.

So for testing: http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000905#1--3

* sites of action table
* expression cluster table

**Comment by draciti** [comment]
it looks great Sibyl, thanks!

- I guess I can remove the "Anatomy terms" field, which is a list of anatomy terms (refer to production site)?

yes you can

- Microarray "topography map"

Wen should be able to advise

Do you have a sense on when this will go to production? I am asking because we are writing chapters for the methods in molecular biology issue and I want to have a feel if I should include the new display (probably so). thanks

**Comment by sibyl229** [comment]
Thanks @draciti the changes will go in with WS258 website release. We have a development freeze at the end of this week. Things will go live about 1 or 2 weeks after that.

**Comment by draciti** [comment]
perfect, thank you Sibyl

**Comment by sibyl229** [comment]
Hi @WenChenWormBase  I'm rewriting all the fields in the expression widget on gene page to get data from Datomic, but got stuck on the Microarray "topography map" data field. Can I ask you some questions about it?

In particular, what would be a reliable way to identify the expr_profile of a gene. It seems that the name of the expr_profile is the same as the sequence name of the gene, like T13C5.1 for daf-9. But I'm not sure if this way is a reliable way. What do you suggest? 

Thank you!

**Comment by WenChenWormBase** [comment]
@sibyl229 @raymond91125  I do not handle topography map. It was originally imported by Raymond about 15 years ago. We no longer display them in WormBase, although the data are available in ACeDB and ftp site. I think we can ignore this field because the data are really outdated, but I will leave the decision to Raymond.

**Comment by sibyl229** [comment]
Thanks @WenChenWormBase for explaining the context! I will leave the topography map field as is for now, until we hear from @raymond91125 .

**Comment by draciti** [comment]
quick comment on that: I recalled that Anne Villeneuve -see issue #2324- strongly suggested to keep mountain data in.

**Comment by sibyl229** [comment]
@draciti right, I do remember that issue you mentioned.

Another question, do you think the expression widget should show up on the Transcript page as well? Even though all the data is based on the gene?

**Comment by draciti** [comment]
i see that in the current transcript page there is the expression widget, so we can keep it, unless someone has strong opinions against that

**Comment by sibyl229** [comment]
@draciti Sure. That works. Thanks! And what should the epic data table called? And how would describe the table in one sentence (this is for the tooltip when you mouseover the field title).

**Comment by draciti** [comment]
you can call it 'EPIC dataset' and this is the text for mouse over 'Large-scale cellular resolution compendium of gene expression dynamics'. let me know if it's too long.

the mouse over for expression profiling graphs on the live site currently is:
'Expression patterns associated with the gene: WBGenexxx'
please change it into
'Expression profiles associated with the gene: WBGenexxx'
 thanks!

**Comment by sibyl229** [comment]
@draciti yup, the typo in the tooltip of expression profiling graph is fixed. And the EPIC table is ready for testing (I split out all the expr_pattern with type EPIC): 
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00007433#1--3 
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00003002#1--3

I ran into a problem with the description. There are multiple descriptions for some expr_pattern objects under Pattern tag. In ACeDB, they seem to be ordered, but I don't think the order is preserved in Datomic. Previously the code simply grab the first description under Pattern tag, but now that approach gives me a different description (and sometimes a really long one). 

Do you think there is a way to tell which one is the right description based on the content? If not, I guess, my temporary solution would be merge all the descriptions and take the first 50 characters or so (to avoid super long description). What do you think?

**Comment by khowe** [comment]
@sibyl229 we're currently going through the models and trying to identify multi-value fields where order matters. The Datomic conversion pipeline has a workaround for these. 

This sounds like another one for @Paul-Davis @mgrbyte to add to the list.

**Comment by Paul-Davis** [comment]
I have added this to the list, but checking a few examples, I don't see an ordering issue, it seems random in acedb if there is a big or small block of text 1st......The size of the text block is only constrained by the size of the sentence or paragraph that was adapted/added by the curator. It might be that all of these text fields should be merged and limited to 50 characters as you proposed @sibyl229 with the option to expand to see all of the info anyway, If this can be done by the website code, curators can just load new text without having to worry about existing data.

**Comment by sibyl229** [comment]
Thanks @khowe @Paul-Davis I will look for a website code workaround for now. I think the curators @draciti might still have to decide which description to show first, in terms of which one is more important for users to see first. I wonder if the current order of these descriptions in ACeDB is sorted by importance.

**Comment by draciti** [comment]
thanks Sibyl.
EPIC Data: tested it and looks good. wrt the description, order is not preserved. In out ontology annotator tool, whenever the text is too long -or different blocks of text have to be put in, we pipe separate them. This results in different lines in the .ace file, e.g.

Pattern	"Inferred expression. EPIC dataset. http:\/\/epic.gs.washington.edu\/ Large-scale cellular resolution compendium of gene expression dynamics throughout development. This reporter was inferred to be expressing in this cell or one of its embryonic progenitor cells as described below."
Pattern	"To generate a compact description of which cells express a particular reporter irrespective of time, ..."

to allow the right sentence to be displayed first, I will modify the existing EPIC entries by removing the pipes, that will be a quick fix at my end. I'll keep you posted

Your suggestion to display the first 50~ characters or so is good. maybe we could make it so that only the sentence EPIC dataset. http://epic.gs.washington.edu/  will be displayed.
I know you have to wait for the next upload to be effective but it will be ok to display the first ~50 characters of the other sentence for now

**Comment by draciti** [comment]
Done- pipes removed for the 321 objects

**Comment by sibyl229** [comment]
Thanks @draciti and nice ACeDB hacking!

**Comment by draciti** [comment]
Hi Sibyl, I was checking your WIP for expression as I need to rewrite the MiMB paragraph with the new display screenshots but it seems to retrieve the older table
http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00001170#1--3

can you please let me know when it will contain the new look?
thx!

**Comment by sibyl229** [comment]
Hi @draciti sorry about that, I had my development server turned off. It should be working now. You will also see the change on staging shortly.

**Comment by sibyl229** [comment]
Hi @raymond91125 I think my question got buried in the thread. It has to do with the topography map, and Mountain tag in SK_map connected to Expr_profile. Can I reliably identify the expr_profile of a gene based on the Sequence_name of the gene? If not, what would be a good way to do that? Thanks!

**Comment by draciti** [comment]
Sibyl, in case the same image is displayed multiple times on the widget, e.g.: WBPicture0000007416 for Paper WBPaper00035485
http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00004876#1--3
could we try to display it only the first time is mentioned and just have a 'See images' text in following entries? see mock-up
let me know what you think
thx
<img width="892" alt="screen shot 2017-03-09 at 2 01 04 pm" src="https://cloud.githubusercontent.com/assets/901243/23768386/70a12f50-04d1-11e7-8cb5-0cb5bbda6ff6.png">

**Comment by draciti** [comment]
Also, in the gallery view, that pops up if you click on 'view images' in the current display, it seems that images are redundantly displayed

**Comment by sibyl229** [comment]
@draciti I think first occurrence vs later might not work, because once you use the sorting or filtering feature of the table, you might miss the row where images is shown. I agree the redundancy of images is problematic, in the sense that users have to mentally filter out these images that don't provide additional information. One thing I can try is to take all the images out and list them together above these tables, and then shrink these **images within these tables** to about 1cmx1cm (more like an icon than content), and lay them out horizontally. Hopefully these icon-like mini-images provide more of a visual cue to guide the user to the bigger image above. What do you think? And if I list the images above the table, would you like their corresponding expr_pattern listed too?

**Comment by draciti** [comment]
we can try that and see how it looks (and if it is not too much work at your end, in case we might like the first look better :))
No need to list the corresponding expr_pattern if by clicking on the image will show the picture pop-up (where there's a link to the expression pattern page)

**Comment by raymond91125** [comment]
@sibyl229 From Expr_profile, strictly speaking, the gene connection is through PCR_product. I can't say how reliable it would be if you rely on the name per se.

**Comment by sibyl229** [comment]
Thanks @raymond91125 ! But how is PCR_product associated with Gene? There doesn't seem to be a direct association.

**Comment by sibyl229** [comment]
@draciti that's fine. Reverting changes is easy.

**Comment by draciti** [comment]
cool, thank you sibyl

**Comment by sibyl229** [comment]
@raymond91125 after looking into the schema a bit more. It seems that I can get the PCR_products from Transcript and CDS through Corresponding_pcr_product. Do I need to check both the Transcript and CDS to obtain a complete set of expr_profiles of a given gene? Thank you!

**Comment by raymond91125** [comment]
@sibyl229 I would say yes, you may need to check both for there may be genes with transcripts that don't have CDS. But they may be rare.

**Comment by sibyl229** [comment]
Hi @draciti I made a few changes to the expression pattern tables, based on some of your earlier feedback. 
* rows are merged if they share the same ontology term 
* only display image if the Picture object is annotated with life-stage, subcellular-localization, or anatomy that matches the ontology term of the row. 
* avoid duplicate images in the gallery

I also made the expr_pattern and qualifier related info collapsed by default (mostly because it's easier for me to do at the moment). I'm still finishing up the work with displaying images. But it would be nice to hear what you think about the tables. Example for testing: http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000905#1--3


Hi @raymond91125 Thanks for confirming that. The topography map field and sites of action table has been migrated. Could you double check whether they look fine? Thank you!
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00007433#1--3
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000905#1--3

**Comment by raymond91125** [comment]
The topo graph examples look fine.

**Comment by sibyl229** [comment]
Thank you @raymond91125 !

**Comment by draciti** [comment]
Hi Sibyl, the links that you sent do not seem to point to the updated changes:
http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000905#1--3

can you pls resend? thx

**Comment by sibyl229** [comment]
Hi @draciti sorry about that. I turned off the server to test something. It should be back on now

**Comment by draciti** [comment]
ok, thanks. Checking it now

**Comment by draciti** [comment]
it looks great Sibyl, thank you!

Checked also the Qualifier for Expressed During, e.g. Expr12045 for bar-1 and looks fine!
http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000238#1--3

One thing related to the EPIC tables -you might still have to work on it, but I am just pointing this out- is that the text is still fully displayed

http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00015138#1--3
thanks

**Comment by chris-grove** [comment]
@draciti @sibyl229 
Looks good! Small thing: In the "Expressed In" table, it still says "Life Stage" as the first column header instead of "Anatomy Term" or whatever you intended

**Comment by draciti** [comment]
Chris, Sibyl, just following up on the virtual worm images. See Sibyl previous comment on this ticket:
'I wonder if it's possible to make a Picture object for these images, because aside from the current technical issue, it seems to make sense to track this information in the database. Please take your time to think about it (this doesn't block me from migrating the rest of the expression widget.).'

There are a couple of issues:
- to make picture objects for the images we will need to link to an ExprID, we cannot link directly to a gene.
- Chris, are the images a composite display of all the anatomy terms that are listed for an individual expression pattern or a combination of multiple expression patterns?
- are the images constantly re-generated whenever there are new expression patterns?

I find the cartoons useful when there are few anatomy terms associated, e.g.
http://www.wormbase.org/species/c_elegans/gene/WBGene00015146#-1-3
but can be overwhelming for gene expressed in multiple tissues
http://www.wormbase.org/species/c_elegans/gene/WBGene00004876#-1-3

Maybe the best place to display the virtual worm images are the anatomy pages -as we previously discussed. I am open to suggestions, thx

**Comment by draciti** [comment]
Good catch!! thanks Chris

Sibyl, the Expressed in table should have as header 'Anatomy Term'
the Subcellular Localization table should have as header 'Cellular Component'
thx

**Comment by sibyl229** [comment]
Thanks @chris-grove Good catch. Don't worry about the VirtualWorm picture issue. I will solve that from my end.

**Comment by draciti** [comment]
ok sounds good

**Comment by sibyl229** [comment]
Hi @draciti @chris-grove sorry I wasn't clear. It's okay either way whether virtual worm has corresponding database entity. Having discussed with @mgrbyte, Datomic cannot have binary format data (images) and images are probably best served from file system than database anyway. I will leave it up to you to decide if any metadata needs to be in the database.

@chris-grove do those existing virtual worm images change over time? 

Thank you both!

**Comment by chris-grove** [comment]
@sibyl229 
The virtual worm images haven't changed since I initially created them a few years ago, but ideally they would be updated for each release. Once I get a pipeline back up and running I will consult with you about how to manage the image files.

**Comment by sibyl229** [comment]
Hi @chris-grove sounds good! 

@chris-grove @draciti I put back the virtual worm to gene an transcripts for now. Table header bug is fixed.
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00015099#1-g-3
* http://dev.wormbase.org:9016/species/c_elegans/transcript/B0280.1b#016--10

**Comment by draciti** [comment]
ok looks good, thanks Sibyl

**Comment by sibyl229** [comment]
Hi @draciti Here are the changes related to expression pattern images, as we discussed earlier. Before I try to get the gallery working. Could you take a look please? Thanks!

http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000905#1-g-4

**Comment by draciti** [comment]
thanks Sibyl, is there a way we could see both the new implementation and the old look? I slightly prefer the older display but I'd like to get feedback from other WormBasers

**Comment by sibyl229** [comment]
Hi @draciti yeah, we can do that. Just to confirm, when you say the older look, do you mean bigger image in the table, rather than have them listed separately? In that case, the images associated with expr_pattern but not Depicting any ontology term would not be shown. Is that okay?

**Comment by draciti** [comment]
as per our Skype conversation:
- decreased size of thumbnails displayed in the 'Expression pattern images' section
- increased size of thumbnails in table
- changed text in tooltips
- change order of expression profiling graphs
- add the gallery for 'Expression pattern images' section

**Comment by sibyl229** [comment]
@draciti I think I fixed all the things you told me. If things look good, please do a final check of this widget to make sure I didn't break anything. Thanks!
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00000905#1-0-3
* http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00004876#1-g-4

**Comment by draciti** [comment]
it looks great Sibyl, thank you! you did not break anything :)

A couple of minor things:
tooltip for ‘Expressed in’: ‘The tissue in which the gene is expressed’
tooltip for ‘Expressed during’: ‘The developmental stage in which the gene is expressed’
tooltip for ‘Subcelluar localization’: ‘The cellular component in which the gene is expressed’

the text description for the EPIC dataset should be trimmed to ~50 words
http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00015138#1-g-4

I’ll let Gary W and Wen pipe in for this but maybe it will be worthwhile to separate small scale expression data and large scale expression data? i.e.: anything from Expression Cluster and below should be in a’ separate Large scale expression’ widget?

**Comment by sibyl229** [comment]
Hi @draciti I fixed the tooltips and trimmed the description text to 50 words. 
http://dev.wormbase.org:9016/species/c_elegans/gene/WBGene00015138#1-g-4

For the small scale expression data, could you create a separate ticket please?

**Comment by draciti** [comment]
perfect Sibyl, thank you! 
small scale expression data: I will see what Wen and Gary think (and anyone else interested in giving suggestions) and will eventually open a new ticket. Feel free to close this one if ready.
Thanks for all your work on the tables, they look great

**Comment by sibyl229** [comment]
Great, thanks @draciti ! Expression widget change should be on staging now.
