### ISSUE TITLE
visitor_name (visitor_email): How could I Know the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5075]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): How could I Know the sequence of pb of my gene daf-18 of C. elegans? I need exons and introns incluided. Thanks.

-- How could I Know the sequence of pb of a gene o C. elegans? I need exons and introns incluided. Thanks.

**Reported by:** Bego******** (bego**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
Hello Begoña,


 You can find gene sequences in the "Sequences" widget/data panel on a given gene page. For example, for daf-18:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000913#0g--10


If you click on the little gray double-helix icon under "Transcript" or "Coding Sequence (CDS)" you can retrieve the genomic sequence of that gene, including exons and introns (click on "view unspliced + UTR"). The exons will be highlighted alternately in yellow and orange, the introns are between the exons in non-highlighted lowercase font.


I hope that helps!


Best,


Chris Grove

WormBase
