### ISSUE TITLE
  Hello! I would like to have my person...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5076]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello!<br/>I would like to have my personal email removed from the "Person" search on wormbase. Is there a way I can do that?<br/>Thank you!</p>

**Reported by:** ayli*********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by ceciliaWBPerson1** [comment]
Dear Aylia:

I removed your email from the "Person" search on 2016-07-25.

Updates will be available in release WS256 of WormBase.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule
Thanks,
Have a great day!
cecilia
