### ISSUE TITLE
visitor_name (visitor_email): Hello!...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5077]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello!

**Reported by:** Matt (matt*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/go_term/GO:0000076#0--10">http://www.wormbase.org/species/all/go_term/GO:0000076#0--10</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
Hi Matt, sorry we missed you. Did you have a question or comment for us to address?


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
User resolved issue on his own
