### ISSUE TITLE
fixes to the WS255 assembly hub

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5078]
I just fixed some issues for the WS255 hub (the second C.remanei strain didn't appear as multiple alignment track and some gene tracks weren't built properly).

could someone from the web team sync
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS255/MULTI_SPECIES/hub/
to 
ftp://ftp.wormbase.org/pub/wormbase/releases/WS255/MULTI_SPECIES/hub/

so the load balancer can point to the same data at both sides of the atlantic.

thanks,

M

**Comment by scottcain** [comment]
My belief is that mirroring this to ftp.wormbse.org will happen automatically.  I keep an eye on it for the next few days to see if it does and if not I'll intervene.

**Comment by epaule** [comment]
Not sure it is happening automatically, I think it is more an "on-demand" syncing strategy.

**Comment by scottcain** [comment]
@epaule Here's what I think (hope) happens: there is on demand syncing between EBI and dev.wormbase.org, and when the ftp directory on the dev machine changes, it automatically updates the ftp server.  I started the on demand sync last night, and finished it up this morning.  Fingers crossed that it goes up to the ftp server now :-)

**Comment by scottcain** [comment]
So much for what I hoped would happen.  I updated the ftp directory on the dev server (/usr/local/ftp) which is what would mirror up to the ftp server, but obviously there is a tool that has to make that happen.  Unfortunately, neither @sibyl229 nor I have shell access to that machine, so we can't make it happen until @tharris gets back.

**Comment by epaule** [comment]
Is that the same update process which you would run when WS256 is on our
site? Because that might throw a spanner into your workflow.

**Comment by tharris** [comment]
The process can run in release dependent or independent manner. Syncing FTP happens twice a month, 1 and 15 to pick up periodic hinxton patches

**Comment by scottcain** [comment]
@epaule it looks like it did happen automatically yesterday; can you take a look a the ftp site to make sure files that should be updated are and then close this issue?
