### ISSUE TITLE
  Hi! How do I post an announcement of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5082]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi!<br/>How do I post an announcement of a worm meeting? to whom should i send the info and in which format.<br/>Thanks  a lot!!!</p><p>What were you doing? <br />&nbsp;&nbsp;wondering how do I...</p>

**Reported by:** Ines (carr******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/537.86.7

**Comment by chris-grove** [comment]
Hello Ines,


 You can send the meeting information to this email address (help@wormbase.org) and one of our curators will post the meeting and confirm with you.


Best,


Chris Grove

**Comment by chris-grove** [comment]
Resolved
