### ISSUE TITLE
Hello 
Yesterday I looked at the page of the prote...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5084]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello 
Yesterday I looked at the page of the protein Y6B3B.4, and today I noticed missing phenotypes. Is it a bug or an update to that page (and if so- can I ask what the reason is)?
Thank you

visitor_name

**Reported by:** Ohad (worm******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00012389#0cb43-9g65-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00012389#0cb43-9g65-3</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
Hello Ohad,

 There shouldn't have been any changes in reported phenotypes for Y6B3B.4 today compared to yesterday. Do you remember what you saw yesterday that you're not seeing today? Keep in mind that there are several phenotypes reported NOT to be observed for this gene if you expand that section of the Phenotypes widget/data-panel.

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Issue resolved
