### ISSUE TITLE
Finding variations and their effects for million mutation strains

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5088]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): how can I find the list of mutated genes in a million mutation strain, like VC20541, and also the sequence of that mutation? Thanks!

**Reported by:** Xinx********* (xinx**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 52.0.2743.116

**Comment by chris-grove** [comment]
Hi Xinxing,


 Unfortunately there's no way currently to return a list of all alleles in the strain WITH their sequence effects, but I can show you how to gather the list of all alleles and their associated genes for the strain. I've created a screen capture video to demonstrate:


https://dl.dropboxusercontent.com/u/4290782/WormBase/Movies/Getting_list_of_alleles_and_genes_for_a_Million_mutation_strain_9-8-2016.mov


This process involves looking up the strain, accessing the list of variations by looking at the "Tree Display" for the strain, copying and pasting that list of WBVar IDs into WormMine to generate a WormMine list, and then adding columns to the resulting list in WormMine to retrieve the allele public names and their associated genes.

The sequence effects of each allele will need to be assessed individually.


I hope that helps.


Best,


Chris Grove

**Comment by chris-grove** [comment]
This is a use case for being able to query WormMine for sequence effects of alleles/variations.

**Comment by chris-grove** [comment]
Hi Xingxing,


 I was actually wrong about there being no way to get the sequence consequence as well. If you go to our FTP site and download the GFF file from here:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/


You can download and unzip the file and perform a Unix command of 'grep' to pull out all lines containing the strain and collect them into a new file like so:


$ grep VC30541 c_elegans.PRJNA13758.WS254.annotations.gff3 > VC20541_gff_lines.txt


I've attached the results of this process.


Let me know if you have questions about that.


Best,


Chris
