### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5090]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): i have been getting an error message the past 2 days that says the connection was reset while loading the page and then I am unable to reconnect. any help would be greatly appreciated!

**Reported by:** mike******** (mich************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/">http://www.wormbase.org/</a>
**Browser:** Firefox 48.0

**Comment by chris-grove** [comment]
Hi Mike,

 Apologies for the error. Can you tell us exactly what happened? Were you trying to load the WormBase homepage (or are you able to now), or was this happening with a specific page? Have you tried multiple browsers?

Any details will help us identify the problem.

Thanks!

Chris Grove

**Comment by chris-grove** [comment]
Site working for user again; Closing.
