### ISSUE TITLE
visitor_name (visitor_email): Hi, I have recently ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5094]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I have recently been trying to use the WormBase REST API, and have been having some inconsistent success in getting  things to work. Some classes seem to behave as expected, and others do not. Right now I am trying to work with the "Interaction" class but it doesn't seem to return anything (just the HTML for an error page) even when running the example queries.</br>visitor_name (visitor_email): well, now it's working although I didn't do anything different</br>visitor_name (visitor_email): the example doesn't work, but my own IDs seem to...

**Reported by:** Adam********* (adam****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/interaction/WBInteraction000000671#0--10">http://www.wormbase.org/species/all/interaction/WBInteraction000000671#0--10</a>
**Browser:** Firefox 48.0

**Comment by chris-grove** [comment]
Hi Adam,

 

Thanks for the feedback and apologies for any problems you've been experiencing. Are you still having trouble?


Someone from our web team can assist you if you're still experiencing problems.


Best,


Chris Grove

**Comment by chris-grove** [comment]
Haven't heard back from user. Closing. Will reopen if necessary.
