### ISSUE TITLE
visitor_name (visitor_email): where can i find the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5096]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): where can i find the domains and their functions of UNC-62 in C. elegans?

**Reported by:** Joyc* (joyc**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006796#0-3-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006796#0-3-3</a>
**Browser:** Chrome 52.0.2743.116

**Comment by Paul-Davis** [comment]
Dear Joyce,

If you search WormBase for your gene unc-62 you will be presented with 
the gene summary page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00006796#013479bcg--10

On here there are various sections detailing the predicted and observed 
functions of this gene. I have limited the above url to list the main 
areas you need to be looking in.

The protein summary page linked from the Sequence section contains 
details on the domain architecture for each isoform of the gene.

Here is the summary for UNC-62, isoform b

http://www.wormbase.org/species/c_elegans/protein/WP:CE21220#05681--10

Thank you for contacting WormBase.

Paul

On 10/09/2016 12:37, no-reply@wormbase.org wrote:
> online chat Joyce (joyce_schuring@hotmail.com): where can i find the 
> domains and their functions of UNC-62 in C. elegans?
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00006796#0-3-3 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00006796#0-3-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006796#0-3-3> 
>
>
> This issue has been assigned ticket number: #5096. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5096>.
>
> Reported by: Joyce (joyce_schuring@hotmail.com)
> 10 Sep 16 11:39
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
