### ISSUE TITLE
visitor_name (visitor_email): Hi , visitor_name (v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5097]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi ,</br>visitor_name (visitor_email): I'm looking for a way to find all the genes with a specific phenotype. How can I do that?

**Reported by:** Nett********** (nett*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/ontology_browser">http://www.wormbase.org/tools/ontology_browser</a>
**Browser:** Firefox 46.0

**Comment by raymond91125** [comment]
Go to the phenotype page (e.g. top right of page search box, "lethal", 
choose "for a phenotype" -> 
http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000062#03--10), 
on the left, Page Content, choose Ontology Browser. In the Ontology 
Browser widget, look for the focus term in green color. To the right of 
the term, there are two numbers. Click on the numbers hypertext leads to 
a new page with lists of genes that have been annotated with the 
"lethal" phenotype.

Cheers,

Raymond

**Comment by raymond91125** [comment]
Thank you,

Netta
