### ISSUE TITLE
Dear WormBase administrators,

first of all, you h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5098]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear WormBase administrators,

first of all, you have done a great job with WormBase, so, thanks for that.

I have a question: from the GFF3 file of C. elegans PRJNA13758.WS253, is there any way to know which type of transposon each element corresponds?

I found the families here on the website, but I want to know if there's a file in which I can link the WormBase Transposon ID (or the sequence_name) to each family.

Thanks a lot!

Cheers,
Braulio.

**Reported by:** Brai************************ (bval*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transposon/WBTransposon00000746#012--10">http://www.wormbase.org/species/c_elegans/transposon/WBTransposon00000746#012--10</a>
**Browser:** Opera 39.0.2256.71

**Comment by chris-grove** [comment]
Hello Brailio,


There isn't a straightforward way to do this with current tools, but I recently generated a file of all transposons and their families from our latest build (WS255) for someone else (attached). Hopefully that has what you need.


Best,


Chris Grove

WormBase
