### ISSUE TITLE
functional description file from OICR

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5104]
I am not currently having issues with the API. However, I have noticed what seems to be an inconsistency with the molecular names for a file available through the FTP. I have found that the "functional descriptions" file (ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/functional_descriptions/c_elegans.PRJNA13758.WS254.functional_descriptions.txt.gz) has a bunch of molecular names with "a" appended to the end, which appears to be erroneous, as it's not that way in the "geneIDs" file, nor in the WormBase website. I am seeing this from both ws253 and ws254.
For example WBGene00008780 (hxk-1) should have molecular name F14B4.2, but in the "functional descriptions" file, it seems to be F14B4.2a. This has been an issue when I've been trying to merge together data from different sources based on those identifiers, so I wanted to check if this is something that should be this way or not.

**Comment by epaule** [comment]
I think that is being created for historical reasons by the OICR staging process.
But maybe that is something we could move into the HX build process, if we get access to the script that creates the file?

**Comment by sibyl229** [comment]
Hi @tharris, @epaule here is looking for the scripts that creates the functional description file, which was historically created by OICR staging process, but he should like to move it into Hinxton build process. I'm not familiar with OICR staging process, could you help him with this? Thanks!
