### ISSUE TITLE
blue header bar on top

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5108]
I think we can remove the blue bar on top with "Please sign this petition in support of Model Organism Databases" , as the petition is now closed.

**Comment by sibyl229** [comment]
Hi @epaule the petition banner is gone. The content of the banner is now about contacting help, as it was used to be. Could you check http://staging.wormbase.org/#012-34-5? Thanks!

**Comment by epaule** [comment]
looks fine to me

**Comment by sibyl229** [comment]
Thanks @epaule
