### ISSUE TITLE
full page button

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5113]
the "Full page" button on the mini-JBrowse doesn't do anything whatsoever:

http://www.wormbase.org/species/b_malayi/gene/WBGene00224555

**Comment by scottcain** [comment]
That's weird.  I don't know what's going on yet, as that used to work in that context.  In the error console, I can see the message that it is executing the function to open the new window, so I have to look into what's stopping it from happening.

**Comment by epaule** [comment]
I tried it on Chrome and Firefox and it seems to behave the same (as in: it doesn't open a full page). I also didn't see any notices from any ad blocker or the browser, so I would think it is genuinely broken.

**Comment by scottcain** [comment]
Fixed by https://github.com/WormBase/website-admin/commit/79a59488addd0885aa76890fcc1d1c33da5c835b
