### ISSUE TITLE
  Hi, I recently switched to a new comp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5117]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I recently switched to a new computer so needed to login to Wormbase again.  It says there is no record of my having an account, but there is no obvious way for me to start a new account.  I don't want to login through Google + or Facebook.  Please help!  <br/>Thanks,<br/>Nicki</p>

**Reported by:** Nick********* (nlia***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Nicki,

Sorry you are having trouble with your account, someone from our web 
team will be in contact to hopefully get you back up and running.

Paul
[HelpDesk]


On 23/09/2016 17:31, no-reply@wormbase.org wrote:
> My Account
>
>   Hi, I recently switched to a new computer so needed to login to 
> Wormbase again. It says there is no record of my having an account, 
> but there is no obvious way for me to start a new account. I don't 
> want to login through Google + or Facebook. Please help!
> Thanks,
> Nicki
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5117. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5117>.
>
> Reported by: Nicki Liachko (nliachko@uw.edu)
> 23 Sep 16 16:29
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/53.0.2785.116 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by khowe** [comment]
User given help with setting an up an account.
