### ISSUE TITLE
ftp  down...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5118]
*Help Desk query collected when no chat operators were online. Follow up required.*

ftp  down

**Reported by:** Dani*** (drac***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#01-23-6">https://www.wormbase.org/#01-23-6</a>
**Browser:** Firefox 48.0

**Comment by scottcain** [comment]
Up now.

**Comment by draciti** [comment]
thanks Scott!
