### ISSUE TITLE
  Hello, I am trying to find in the WS2...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5119]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am trying to find in the WS254 version a simple way to find the existing genetic markers within a chromosome interval, similar to what 'Markers' in the old version (legacy) used to allow by entering two genetic loci ~2cM apart.<br/>Thank you,<br/>Carlos</p>

**Reported by:** Carl*********** (carl********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by tuli** [comment]
It's been a while since we've had a request for this.

It used to be here: http://legacy.wormbase.org/db/searches/interval and earlier here: http://ws220.wormbase.org/db/searches/strains

Any chance

**Comment by Paul-Davis** [comment]
Dear Carlos,

Thanks you for your email, we are looking into how best to provide this 
data. You can track progress on the issue that has been raised here: 
https://github.com/WormBase/website/issues/5119

Paul
[HelpDesk]



On 24/09/2016 23:50, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> I am trying to find in the WS254 version a simple way to find the 
> existing genetic markers within a chromosome interval, similar to what 
> 'Markers' in the old version (legacy) used to allow by entering two 
> genetic loci ~2cM apart.
> Thank you,
> Carlos
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5119. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5119>.
>
> Reported by: Carlos Carvalho (carlos.carvalho@usask.ca)
> 24 Sep 16 22:52
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 
> Firefox/48.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Closing this ticket as @tuli suggested that the solution is only in the reimplementation of the tool in ticket #507
