### ISSUE TITLE
  WBVar02120219 is not a frameshift mut...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5125]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WBVar02120219 is not a frameshift mutation as annotated - it is a synonymous change as far as I can tell</p>

**Reported by:** Dani*********** (dani*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by epaule** [comment]
gah, I think the script uses Deletion_and_insertion_allele to identify deletion&insertions.

**Comment by tuli** [comment]
@epaule  you mean that the map_alleles looks at Method to identify they Type_of_mutation and not Type_of_mutation?

**Comment by epaule** [comment]
It uses the Method to decide which checks to do. Will see if we can't make it behave a bit smarter.

**Comment by tuli** [comment]
OK. Will you reply to the user then?

**Comment by epaule** [comment]
when i fixed it, yes

**Comment by khowe** [comment]
Fixed for WS256. Replied to user.
