### ISSUE TITLE
Can't call method "segment" on an undefined value.

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5126]
The brugia GBrowse location widge is broken again (JBrowse version works):

http://www.wormbase.org/species/b_malayi/gene/WBGene00229198
![image](https://cloud.githubusercontent.com/assets/20523/18868000/76c45ffa-849e-11e6-8a14-e7f0099d7bf6.png)

http://www.wormbase.org/tools/genome/gbrowse/b_malayi_PRJNA10729/?name=Bm_v4_Chr2_contig_001%3A13850656..13853927
![image](https://cloud.githubusercontent.com/assets/20523/18867978/5c4138c4-849e-11e6-9bfc-21e8e98d8689.png)

**Comment by scottcain** [comment]
Hi @epaule 

Given that this works on 255 and it will be live in a few weeks, we aren't going to fix this now.

**Comment by epaule** [comment]
I reopened it, because while it worked on 255/staging ... it doesn't on 255/live , so the automatic fix didn't work.

**Comment by scottcain** [comment]
Hi @epaule I hadn't updated the GBrowse configs for 255 on the live site until a few minutes ago, so even though the header said it was 255, it was really 254.  It works now.
