### ISSUE TITLE
  I'm having a hard time finding a .gtf...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5129]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm having a hard time finding a .gtf file for RNA seq using ws255 genome for c. elegans. Could you provide me with some advice on this?</p><p>What were you doing? <br />&nbsp;&nbsp;rna-seq</p>

**Reported by:** Adam****** (ajhe***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by khowe** [comment]
Helped.
