### ISSUE TITLE
  WBVar02101089 does not result in a fr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5133]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WBVar02101089 does not result in a frameshift - it is a synonymous mutation</p><p>What were you doing? <br />&nbsp;&nbsp;This seems to be a general problem with indel pages. My guess is that if the deletion takes out a number of nucleotides not divisible by 3, it gets called as a frameshift, even if the simultaneous insertion returns the frame back to normal. Or something like that</p>

**Reported by:** Dani*********** (dani*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by khowe** [comment]
Same as #5125
