### ISSUE TITLE
Hi ! i just need help regarding genotyping of tran...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5134]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi ! i just need help regarding genotyping of transgenic worms and what is the best way to learn that e.g. if the genotype is baln11 what does that mean

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#014-23-6">http://www.wormbase.org/#014-23-6</a>
**Browser:** Chrome 53.0.2785.116

**Comment by raymond91125** [comment]
HI Supi,

You can learn about transgene nomenclature here <http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10>.

I think you're referring to baIn11 <http://www.wormbase.org/species/all/transgene/WBTransgene00000129#01--10>.

Cheers,

Raymond
