### ISSUE TITLE
i also want to know about axenically culturing of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5135]
*Help Desk query collected when no chat operators were online. Follow up required.*

i also want to know about axenically culturing of c.elegans what are the components and if any limitations
please help

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#014-23-6">http://www.wormbase.org/#014-23-6</a>
**Browser:** Chrome 53.0.2785.116

**Comment by raymond91125** [comment]
Hi Supi,

You may start by reading some literature, e.g. 
<https://www.ncbi.nlm.nih.gov/pubmed/18375873>, or start a discussion 
here <http://forums.wormbase.org/>.

Cheers,

Raymond


On 09/28/2016 09:43 AM, no-reply@wormbase.org wrote:
> offline chat i also want to know about axenically culturing of 
> c.elegans what are the components and if any limitations please help
>
> Submitted From:
>   http://www.wormbase.org/#014-23-6 http://www.wormbase.org/#014-23-6 
> <http://www.wormbase.org/http://www.wormbase.org/#014-23-6>
>
> This issue has been assigned ticket number: #5135. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5135>.
>
> Reported by: supi (supinderkr@gmail.com)
> 28 Sep 16 16:45
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
