### ISSUE TITLE
Hi I AM TRYING TO OPEN THE PAPER ON DNA TRANSFORMA...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5136]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi I AM TRYING TO OPEN THE PAPER ON DNA TRANSFORMATION 1995 BY  Dr. Craig but I dont why there is not full paper

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10">http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10</a>
**Browser:** Chrome 53.0.2785.116

**Comment by raymond91125** [comment]
Sorry, we are not permitted to offer copy-right protected material. I 
assume that's the reason.

Raymond



On 09/28/2016 12:53 PM, no-reply@wormbase.org wrote:
> offline chat Hi I AM TRYING TO OPEN THE PAPER ON DNA TRANSFORMATION 
> 1995 BY Dr. Craig but I dont why there is not full paper
>
> Submitted From:
>   http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10 
> http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10 
> <http://www.wormbase.org/http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10> 
>
>
> This issue has been assigned ticket number: #5136. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5136>.
>
> Reported by: supi (supinderkr@gmail.com)
> 28 Sep 16 19:52
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
