### ISSUE TITLE
I wonder if I can ask a question about my favorite...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5138]
*Help Desk query collected when no chat operators were online. Follow up required.*

I wonder if I can ask a question about my favorite gene sequence ? thanks

**Reported by:** ni w*** (wang**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#b6372aec0d48915--10">http://www.wormbase.org/about/Frequently_asked_questions#b6372aec0d48915--10</a>
**Browser:** Firefox 49.0

**Comment by khowe** [comment]
User was asked for more information, never replied.
