### ISSUE TITLE
  Wormbase genes have a type field show...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5139]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Wormbase genes have a type field shown on the "overview" panel in the web page (e.g. "protein coding" or "ncRNA").<br/>I would like to get a list of the type of every gene in the database, so that I can filter some gene lists by type.<br/>I can't seem to find the "type" field listed as an output option in WormMine, nor am I sure what database table to try to grab from the wormbase ftp site. Any advice in this would be greatly appreciated!<br/>Thanks,<br/>Zach</p>

**Reported by:** Zach********** (zpin*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8

**Comment by khowe** [comment]
Replied:

You can use the WormBase ParaSite BioMart to get this information : http://parasite.wormbase.org/biomart/martview

1. Define the Query filter. You need to select "Caenorhabditis elegans [WS254]" from the "Species " panel. 
2. Define Output Attributes. You need to select "Gene Stable ID" and "Gene Biotype" in the "Gene" box. You might also find it useful to select other attributes for output (e.g. Gene name).
3. Click the "Results" button at the top left. Only the first 10 rows are shown by default, but it should be obvious how to get the full result set.
