### ISSUE TITLE
How can I see a graphical representation of the 14...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5140]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I see a graphical representation of the 143 cDNAs for the mig-6 gene? In older versions of wormbase they were easily displayed. How can I do it now?

**Reported by:** Andr************ (andr*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003242#0eb14-9dag-3-eb14a">http://www.wormbase.org/species/c_elegans/gene/WBGene00003242#0eb14-9dag-3-eb14a</a>
**Browser:** Chrome 53.0.2785.116

**Comment by raymond91125** [comment]
Hi Andrea,

In GBrowse, turn on track ESTs (best) -> click on "Configure this track" 
(wrench icon, left of track) -> change from Auto to "Expand and Label".

In JBrowse, search under "Available Tracks", "est" -> click on ESTs 
(best), under supporting evidence. A few more under Green Lab ESTs (all).

I don't know if that accounts for 143 but looks pretty close.

Cheers,

Raymond


On 09/29/2016 05:50 AM, no-reply@wormbase.org wrote:
> offline chat How can I see a graphical representation of the 143 cDNAs 
> for the mig-6 gene? In older versions of wormbase they were easily 
> displayed. How can I do it now?
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00003242#0eb14-9dag-3-eb14a 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00003242#0eb14-9dag-3-eb14a 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003242#0eb14-9dag-3-eb14a> 
>
>
> This issue has been assigned ticket number: #5140. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5140>.
>
> Reported by: Andrea Thackeray (andrea.thackeray@umassmed.edu)
> 29 Sep 16 12:52
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Fantastic!!!

thanks so much

Andrea Thackeray
