### ISSUE TITLE
Hi will you pkease tell me names of some transgeni...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5141]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi will you pkease tell me names of some transgenic strains where calcium is expressed in neurons. Thanks!

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#014-23-6">http://www.wormbase.org/#014-23-6</a>
**Browser:** Chrome 53.0.2785.116

**Comment by raymond91125** [comment]
No, nothing I know of.
