### ISSUE TITLE
Chris: Hello Supi, how can I help? visitor_name (v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5144]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Supi, how can I help?</br>visitor_name (visitor_namenderkr@gmail.com): Hi chris i want some help regading strains which express GCaMP in neurons</br>Chris: OK</br>visitor_name (visitor_namenderkr@gmail.com): I searched CGC but I dont know much about genotype so it was very difficult for me to find the right strains for me</br>Chris: OK</br>visitor_name (visitor_namenderkr@gmail.com): Thanks a lot for your help</br>Chris: Let me perform a query of the database for strains that carry transgenes that mention "GCaMP"</br>visitor_name (visitor_namenderkr@gmail.com): you are always a great help</br>Chris: Glad to help; almost done</br>Chris: OK, I'll email you the table of transgenes that reference GCaMP, along with associated strains</br>visitor_name (visitor_namenderkr@gmail.com): but how i will know whether they are expressing in neurons</br>Chris: The list I'm going to send is about 75 transgenes. You'll need to check which of the promoters express in neurons. You can check WormBase pages for each transgene to find references/papers that mention the transgenes. That will help you narrow down the list to those expressed in neurons</br>visitor_name (visitor_namenderkr@gmail.com): Thanks a lot so so nice of you. Have A great weekend</br>Chris: OK, thanks, you too!</br>Chris: OK, I'm closing the chat window now. I'll be in touch shortly via email</br>visitor_name (visitor_namenderkr@gmail.com): ok

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#014-23-6">http://www.wormbase.org/#014-23-6</a>
**Browser:** Chrome 53.0.2785.116

**Comment by chris-grove** [comment]
Sent data to user.
