### ISSUE TITLE
You misspelled previous affilitions  it should rea...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5146]
*Help Desk query collected when no chat operators were online. Follow up required.*

You misspelled previous affilitions  it should read MIT (Bob Horvitz)  not MT, that is reserved for the strain at his lab

**Reported by:** Erik********** (ehar*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/person/WBPerson245#01--10">http://www.wormbase.org/resources/person/WBPerson245#01--10</a>
**Browser:** Firefox 48.0

**Comment by tuli** [comment]
Dear Erika,

Thank you for writing to WormBase.

MT is the laboratory code for the Horvitz lab. Laboratory codes are
used in strain designations, thus we refer to MT as the
laboratory/strain code.

The widget is named "Lab Affiliation" and MT refers to the lab (code)
where you were previously affiliated, not the name of the institution
(MIT).

I hope this explains things for you.

Best wishes,

Mary Ann

On 1 October 2016 at 21:36,  <no-reply@wormbase.org> wrote:
> offline chat You misspelled previous affilitions it should read MIT (Bob
> Horvitz) not MT, that is reserved for the strain at his lab
>
> Submitted From:
>   http://www.wormbase.org/resources/person/WBPerson245#01--10
> http://www.wormbase.org/resources/person/WBPerson245#01--10
>
> This issue has been assigned ticket number: #5146. Follow progress on our
> issue tracker.
>
> Reported by: Erika Hartwieg (ehartwieg@mit.edu)
> 01 Oct 16 20:39
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
