### ISSUE TITLE
Hello! I'd like to submit some sequencing data to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5147]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello! I'd like to submit some sequencing data to update allele info that is not curated in the wormbase (i.e. gld-1 gene, q361 allele). The allele is described in multiple publications but the exact lesion or mutation is not updated in the worm base. Would you please direct me to a link where I could submit this? Thank you!

Best
visitor_name

**Reported by:** Heaj****** (hshi************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00241085#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00241085#02-45-3</a>
**Browser:** Safari 10.0

**Comment by khowe** [comment]
Hello Heaji,


 Thank you for submitting allele sequence data; it is much appreciated!


You can submit allele information via this online form:


http://www.wormbase.org/submissions/allele_sequence.cgi


Our sequence curator will be in touch if there are any questions.


Best,


Chris Grove

WormBase
