### ISSUE TITLE
WS256 GFF changes

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5148]
Here is a summary of the gff changes between WS255 and WS256

```
COMPARISON BETWEEN GFF CURRENT (c_elegans.PRJNA13758.WS256) AND GFF PREVIOUS (c_elegans.PRJNA13758.WS255)

There are source/type present now but not present previously (probably okay):
 KO_consortium insertion_site 1
 PCoF_KO_consortium insertion_site 1

COMPARISON BETWEEN GFF CURRENT (c_briggsae.PRJNA10731.WS256) AND GFF PREVIOUS (c_briggsae.PRJNA10731.WS255)

There are source/type present now but not present previously (probably okay):
 Allele complex_substitution 2
 PCoF_Allele complex_substitution 2

COMPARISON BETWEEN GFF CURRENT (c_remanei.PRJNA53967.WS256) AND GFF PREVIOUS (c_remanei.PRJNA53967.WS255)

There are source/type present now but not present previously (probably okay):
 BLAT_Caen_Trinity_BEST expressed_sequence_match 391838
 BLAT_Caen_Trinity_OTHER expressed_sequence_match 850928
 WormBase pseudogenic_tRNA 159
```
I don't believe any of these are 100% new and have existed for some species in the past so the g/jbrowse config should work out of the box, but it might be worth checking with @tuli about the Variation changes.

P

**Comment by scottcain** [comment]
@Paul-Davis: Some of these features are not configured to show up anywhere in genome browsers.  I guessing that insertion_site:KO_consortium should go in the track with other KO_consortium features, and similarly for PCoF_KO_consortium insertion_site features, yes?

Also the BLAT_Caen_Trinity features don't have a track that they call home, but some time ago I added a track for BLAT_Trinity_BEST:expressed_sequence_match for @gw3.  Should I create a similar track for BLAT_Caen_Trinity_BEST (and, as somewhat of an aside, that track only exists in JBrowse now--should it be back ported to GBrowse?)

**Comment by Paul-Davis** [comment]
Hi @scottcain 

@gw3 confirmed with me that there isn't much utility in the BLAT_Caen_Trinity features for the users so it is fine for these to be omitted from the g/jbrowse configs.

Just waiting for @tuli to confirm the Variation changes, but whay you propose sounds right.

**Comment by tuli** [comment]
KO_consortium goes in the High-throughput alleles track and PCoF goes in the Change-of-function alleles track. 

Allele complex_substitution goes in the Classical alleles track and PCoF_Allele complex_substitution goes in toe Change-of-function alleles track.

**Comment by Paul-Davis** [comment]
Thanks @tuli

**Comment by scottcain** [comment]
I'm going to leave this issue open so I remember to check when the build happens for 256, but I'm pretty sure these commits will add everything new.

**Comment by scottcain** [comment]
G and JBrowse are both built for 256, and they have these new features, so all went as planned.  Yay.

Closing...
