### ISSUE TITLE
Trying to find the phenotype of the worms we are w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5149]
*Help Desk query collected when no chat operators were online. Follow up required.*

Trying to find the phenotype of the worms we are working with in intro to genetics lab.
Thanks

**Reported by:** Vene*** (vmje**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 30.0.1599.103

**Comment by chris-grove** [comment]
Hello Venette,


 Do you have any identifying information about the strain of worms you are working with, like a strain name or a genotype?


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Sorry about the previous message. I was sending it to a classmate. For sure I don't know. All I know is the worm is "mutant dumpy A" I dont know what is its genotype or anything else.
Thanks
