### ISSUE TITLE
Hello, the page for F19G12.2 says that it's involv...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5150]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, the page for F19G12.2 says that it's involved in DNA damage response, and cites Pothof 2003 PMID:12600937, but I don't see that gene listed in the Pothof tables as being involved in response to damage,
so am wondering is that a mistake. Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00017610#0f-9e63bg1c5-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00017610#0f-9e63bg1c5-10</a>
**Browser:** Firefox 38.0

**Comment by Paul-Davis** [comment]
--adding text as didn't arrive via the email route.

Hi Avril,

The gene is referenced in Table 1 section V.

Pothof J et al. (2003) - Identification of genes that protect the C. elegans genome against mutations by genome-wide

Hope this helps.

Paul
