### ISSUE TITLE
Hi Chris
I need help regarding axenically culturin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5151]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi Chris
I need help regarding axenically culturing of c.elegans in both liquid and solid media. If THERE IS ANY ESTABLISHED PROTOCOL

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#014-23-6">http://www.wormbase.org/#014-23-6</a>
**Browser:** Chrome 53.0.2785.116

**Comment by chris-grove** [comment]
[wormbase-help] offline chat transcript: Hi Chris
Today, 10:34 AMsupinderkr@gmail.com;help@wormbase.org
Hi Supi,

 I would suggest looking at the WormBook chapter on maintaining cultures of C. elegans:

http://www.wormbook.org/chapters/www_strainmaintain/strainmaintain.html

They reference an article that reports how to prepare axenic cultures:

https://www.ncbi.nlm.nih.gov/pubmed/8462849?dopt=Abstract

You may also find this JOVE (Journal of Visualized Experiments) page helpful:

http://www.jove.com/video/51796/culturing-caenorhabditis-elegans-axenic-liquid-media-creation


I hope that helps.

Best,

Chris
