### ISSUE TITLE
pagi bos .., saya lupa sand dan user name saya ..,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5154]
*Help Desk query collected when no chat operators were online. Follow up required.*

pagi bos .., saya lupa sand dan user name saya .., gimana solusinya bos

**Reported by:** chak****** (cakr***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 53.0.2785.143

**Comment by khowe** [comment]
Spam
