### ISSUE TITLE
evalue sorting in the homology table

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5155]
as example: http://www.wormbase.org/species/c_elegans/protein/WP:CE51110

it sorts it alphanumerical and not by value ... but only in the "full blast list", the short one sorts by value

**Comment by sibyl229** [comment]
Hi @epaule I will fix that. I noticed that the full blastp matches table is structured differently from the best blastp matches one. Is it intended? 
![screen shot 2016-10-05 at 10 22 32 am](https://cloud.githubusercontent.com/assets/1753893/19117520/44217e6c-8ae7-11e6-9abd-e59f23120852.png)

**Comment by epaule** [comment]
i don't think it is intended

**Comment by epaule** [comment]
sorting works now as expected in the full table.
