### ISSUE TITLE
  Where is "transcript type" in WormMin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5156]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Where is "transcript type" in WormMine?  I can't find it.<br/>I tried the contact help button in WormMine and got a page does not exist error.<br/>THanks,<br/>Julie</p>

**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by epaule** [comment]
I think the "Method" field in the Transcripts section does roughly what you might be looking for.
