### ISSUE TITLE
  →Hello, when I look at the page for W...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5158]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;→Hello, when I look at the page for WBGene00228755 , the 'Sequence Features' box is empty, is it supposed to be? Regards, Avril</p>

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by epaule** [comment]
No, it shouldn't look like that. It seems more like the GBrowse that provides the graphics is currently broken, as also http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/ return an error.

**Comment by epaule** [comment]
is the same as #5126

**Comment by scottcain** [comment]
It seems fine now.  I think the mysql database that drives GBrowse was a little slow this morning for some reason so some requests were timing out.  The B.malayi problem should be fixed today when release 255 goes live.
