### ISSUE TITLE
visitor_name (visitor_email): Hello, when I look a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5159]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello, when I look at the page for WBGene00228755 , the 'Sequence Features' box is empty, is it supposed to be? Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/b_malayi/gene/WBGene00228755#0f-9e63bg1c5-10">http://www.wormbase.org/species/b_malayi/gene/WBGene00228755#0f-9e63bg1c5-10</a>
**Browser:** Firefox 38.0

**Comment by khowe** [comment]
Fixed.
