### ISSUE TITLE
visitor_name (visitor_email): Hello, I am trying t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5162]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello, I am trying to cite this page using the Name-year format. Could you tell me the publisher/sponsor and the date this was published? I cannot seem to find this.</br>visitor_name (visitor_email): Hello?

**Reported by:** Juli********* (juli**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003856?redirect=1#-95c1-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00003856?redirect=1#-95c1-3</a>
**Browser:** Chrome 53.0.2785.143

**Comment by draciti** [comment]
Hi Julia,

below the guidelines for citing WormBase content:

http://www.wormbase.org/about/citing_wormbase#012--10 <http://www.wormbase.org/about/citing_wormbase#012--10>

Best,
Daniela
