### ISSUE TITLE
Is the sequence of a gene  in 5´-3´?
Thanks very m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5163]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is the sequence of a gene  in 5´-3´?
Thanks very much

**Reported by:** Bego** (bego**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/Y53C10A.12#06--10">http://www.wormbase.org/species/c_elegans/transcript/Y53C10A.12#06--10</a>
**Browser:** Chrome 53.0.2785.143

**Comment by draciti** [comment]
Hi Begona,
yes the directionality is 5’-3’.
Best,
Daniela

**Comment by draciti** [comment]
Thanks you very much Daniela,
Best,
Begoña
