### ISSUE TITLE
GBrowse tracks not loading

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5164]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_email): Hi, I tried to change the browser size in the preferences from 800 to ~1400.</br>visitor_name (visitor_email): After changing, I have been getting this error in the browser</br>visitor_name (visitor_email): Track rendering error: can't call method "prepare_cached" on an unidentified value at /usr/local.wormbase/extlib/lib/perl15/Bio/DB/SeqFeature/Store/DBI/mysql.pm line 1805</br>Chris: OK, this is in the GBrowse genome browser?</br>visitor_name (visitor_email): yes</br>Chris: Thanks for reporting the problem. We are aware that this type of problem sometimes occurs. Can you tell me what coordinates you are looking at?</br>visitor_name (visitor_email): its the same for all the coordinates that I tried. for example: Y37f4.7</br>Chris: OK, which track or tracks are giving you the error?</br>visitor_name (visitor_email): Errors are being displayed in the landmarks and polymorphism tracks. but I can't even see the "curated genes"</br>Chris: I see. OK, I'll contact our GBrowse team and let them know. You're not the only one to be reporting such issues. I'll be in touch via email once I know more about progress on this issue</br>visitor_name (visitor_email): Ok, thanks.</br>Chris: Thanks for the report. Is there some specific data you are looking for that I may be able to retrieve for you in the meantime</br>Chris: ?</br>visitor_name (visitor_email): No, thank you.</br>Chris: OK, thanks again. I'll be in touch

**Reported by:** Kris*** (kris***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Firefox 48.0

**Comment by chris-grove** [comment]
@scottcain I've received a number of reports of GBrowse tracks not loading and I can confirm that they are still not loading properly in several instances. For example, the user in the chat above pointed out that loading GBrowse from the "Location" widget on the Y37F4.7 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00021388#-09-10

is consistently resulting in loading errors for several tracks including the "Landmarks", "High-throughput alleles", "Classical alleles" and "Change-of-function alleles" tracks; here's a screenshot:

![screen shot 2016-10-11 at 1 26 52 pm](https://cloud.githubusercontent.com/assets/611382/19281123/baf8fc4e-8fb6-11e6-932e-efc73ae602d4.png)

**Comment by scottcain** [comment]
I'm a little reluctant to put time into this today, since 255 is due out any minute (or so).  If the problem persists after 255 is out, please let me know (though I'll be checking too).

**Comment by Paul-Davis** [comment]
If the user wants to see the data for a single gene and they don't need to scroll around they can export the view as a PNG and see the tracks.......the problem is the local cahning of the tracks so you can re-order them I believe??

**Comment by epaule** [comment]
I think you got as part of the web team a way better estimate when 255 will
be coming out than us (or how much work it would be to fix the 254 GBrowse).
And to be fair, the JBrowse version works and I can direct people in its
direction. It is more that the embedded images on the web site are broken
with GBrowse being down.

M

**Comment by Paul-Davis** [comment]
jbrowse is live and running so the user should be advised to use that for WS254.

**Comment by Paul-Davis** [comment]
Actually....gbrowse seems to be behaving for me today.

**Comment by chris-grove** [comment]
My email to user:
"
 I would just like to point out that our newest genome browser, JBrowse, seems to be working well so you may want to use that instead of GBrowse for the time being. A link to JBrowse is available in the gene page Location widget, to the right of the GBrowse link (click on the coordinates to the right of "Try the new Genome Browser"). It is likely that GBrowse will remain as is until our WS255 release, in which a fix should be in place.


Best,


Chris"

**Comment by scottcain** [comment]
There were disk space issues on the mysql server that were causing these problems.  Those issues have been resolved.
