### ISSUE TITLE
Hello,
I am using proteome data from wormbase ftp ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5167]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I am using proteome data from wormbase ftp website, there is a file called species_tree.json 
ftp://ftp.wormbase.org/pub/wormbase/parasite/releases/WBPS6/species_tree.json, 
is this a phylogenetic tree ? and does it represent the species position in the tree ?  or it mean totally different thing ?
Regards
visitor_name

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-4-">http://www.wormbase.org/#01-23-4-</a>
**Browser:** Chrome 48.0.2564.82

**Comment by brucebolt** [comment]
Dear Nishant

Thank you for writing to WormBase.

The file you have linked to is a taxonomic tree, based on the taxonomy data from NCBI, for all the species in WormBase ParaSite release 6.

For more information about how NCBI have created this taxonomy, it is best to refer to their website: https://www.ncbi.nlm.nih.gov/taxonomy <https://www.ncbi.nlm.nih.gov/taxonomy>

Best regards

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
