### ISSUE TITLE
  Bad Gateway Timeout Report  What were...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5169]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Bad Gateway Timeout Report</p><p>What were you doing? <br />&nbsp;&nbsp;BLAST search</p>

**Reported by:** Davi********* (davi*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by draciti** [comment]
Hi David,
thanks for letting us know.

Webteam: confirmed on the live site, it works well on staging.
Thanks,
Daniela

**Comment by draciti** [comment]
merge with #5170

**Comment by chris-grove** [comment]
Hi David,
 
It seems BLAST services have been restored. Thanks for reporting the problem. Let us know if you have any more issues.

Best,

Chris
