### ISSUE TITLE
External URL question

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5171]
Hi Sybil/Webteam,
I committed on github the following external URL addition with the formatting below, i.e. enclosing  'Micropublication: Biology' because of the colons.
Please let me know if I should do differently or if it broke anything
thanks

 'Micropublication: Biology' = {
    description = 'Micropublication:Biology'
    base        = 'http://www.micropublicationbiology.org/'
    search      = 'http://www.micropublicationbiology.org/%s'
    }

**Comment by sibyl229** [comment]
Hi @draciti feel free to edit the external URLs, generally you won't break anything when following the format. The 'Micropublication: Biology' may not work as you intended here though, could you explain to me where this url will be used?

**Comment by draciti** [comment]
thanks Sibyl,
we have generated a paper object for a micropublication (WBPaper00050256- will upload for WS257). The micropublication will be published on the Micropublication:biology journal, we therefore need the Micropublication:biology URL to link out to it.
On my end, I have added Micropublication:biology in the pictures pipeline and have a Database object for it in the picture dump:

Database : "Micropublication:biology"
Name	"Micropublication: biology"
URL	"http:\/\/www.micropublicationbiology.org\/"
URL_constructor	"http:\/\/www.micropublicationbiology.org\/%s”


Let me know if this will work
thanks!

**Comment by sibyl229** [comment]
Hi @draciti the link to the micro publication site is working http://staging.wormbase.org/species/c_elegans/expr_pattern/Expr12292#0213--10 but it's not linking to the article because the citation template in acedb is missing the fragment about article URL. I think it should work once the citation template is fixed. http://staging.wormbase.org/tools/tree/run?name=WBPicture0000013205;class=Picture

**Comment by sibyl229** [comment]
@draciti Yeah, the Article_URL tag is fine, but I was referring to the Template tag: "Reprinted from <Journal_URL>". Is it supposed to include "<Article_URL>"?

**Comment by draciti** [comment]
got it Sibyl, thanks! I changed the template to include the <Article_URL>, will go in for WS265. I will keep this open until WS265 will be on staging.

**Comment by epaule** [comment]
didn't hear anything from @draciti , so will close that ticket
