### ISSUE TITLE
  Dear colleagues: In the repeatmasker ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5172]
_Submitted from the feedback form on the WormBase website._

<p>&nbsp;&nbsp;Dear colleagues:<br/>In the repeatmasker tract of Cbrowser for Cbriggsae appear many sequences<br/>of the type C_briggssae_sequence**, where ** is a number.<br/>I would like to have a list of all the reference sequences used to create these hits.<br/>I have found a list of all the  hits in the genome, but what I need are the reference sequences. <br/>They are not present in the Standard Repeatmasker file in the<br/>giri website.<br/>Thank you for your help<br/>visitor_name</p>

**Reported by:** Juan (juan******************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by kyook** [comment]
Hi Juan,

I'm wondering if anyone has gotten back to you. Please let me know if your
request has been addressed or if you are still waiting to hear from
someone.

Karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Mon, Oct 17, 2016 at 2:02 AM, <no-reply@wormbase.org> wrote:

> Feature Request
>
>   Dear colleagues:
> In the repeatmasker tract of Cbrowser for Cbriggsae appear many sequences
> of the type C_briggssae_sequence**, where ** is a number.
> I would like to have a list of all the reference sequences used to create
> these hits.
> I have found a list of all the hits in the genome, but what I need are the
> reference sequences.
> They are not present in the Standard Repeatmasker file in the
> giri website.
> Thank you for your help
> Juan
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5172. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5172>.
>
> Reported by: Juan (juan.a.subirana@upc.edu)
> 17 Oct 16 09:02
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

**Comment by kyook** [comment]
Michael Paulini
AttachmentsNov 3 (6 days ago)

to me, Kevin, help, Juan 
Dear Juan,

we have an repeat library from Jack Chen's lab that we use to mark up the sequences (attached).
But your request triggered some attempts to improve the annotation of the library (which is still going on).
We will give a shout when we finished with it.

From release WS257 onwards, the respective repeat libraries will be also included in the WormBase distributions on the FTP sites.

regards,

Michael

**Comment by kyook** [comment]
Juan Antonio Subirana <juan.a.subirana@upc.edu>
Nov 3 (6 days ago)

to me 
Hi Karen,
Thanks to your help I got the data from Michael Paulini.
Cheeers
