### ISSUE TITLE
New header looks weird on BLAST

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#5173]
Great to see the new website header on WS255, however it renders badly on the BLAST page (see screenshot attached).
![screen shot 2016-10-17 at 11 11 52](https://cloud.githubusercontent.com/assets/6329861/19433913/a6de58fa-945a-11e6-915c-8ca7f19b377c.png)

**Comment by scottcain** [comment]
The same thing happened in JBrowse--the jquery libraries need to be updated.  I'm teaching shortly, but if nobody gets to it by this evening, I'll fix it.

**Comment by scottcain** [comment]
Hi @brucebolt I can't reproduce this on either the live site or staging.  Can you do a hard reload to see if your browser is caching the old javascript?

**Comment by brucebolt** [comment]
Hi @scottcain, this appears to be fixed now.  We were all seeing this issue at Hinxton yesterday morning, so I assume the problem was transient.
