### ISSUE TITLE
How to search for genes specifically up-regulated in L1 and dauer

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5175]
_Help Desk chat transcript. Issue can be closed if question was resolved in chat._

visitor_name (visitor_email): how can I search for gene with similar developmental expression pattern? Specifically I'm looking for those similar to cab-1, which is high in L1 and in dauer</br>Chris: Hi visitor_name</br>Chris: I think you can use WormMine to get genes that fit this criteria</br>Chris: Let me take a look and get back to you with a query template</br>visitor_name (visitor_email): ok, thanks!</br>Chris: Hi visitor_name, this is something you can normally do in WormMine: Get all genes expressed in L1, get all genes expressed in dauer, and then get the list of overlapping genes; however the save list functionality seems to be buggy at the moment so I'll generate the list of genes expressed in both L1 and dauer and send it to your email address. Is that OK?</br>visitor_name (visitor_email): yes, that would be great.</br>visitor_name (visitor_email): yhanks you</br>Chris: OK great, sounds good</br>visitor_name (visitor_email): What is important is that their expression increases at those stages compared to other one</br>Chris: OK, getting quantitative comparisons like that is going to be much more difficult, unfortunately. The list of genes annotated as expressed in dauer and L1 is only 50 genes, so you may be able to narrow it down from there. I could narrow it further by only selecting (from those 50) genes that are also not expressed in other stages, but that will likely be too stringent</br>visitor_name (visitor_email): ok</br>visitor_name (visitor_email): i can start with that</br>Chris: OK I just sent you the list. I'll ask my colleagues about getting the list of genes that are specifically up-regulated during L1 and dauer and get back to you</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): no, i'm good with that for the moment</br>visitor_name (visitor_email): thanks a lot</br>Chris: OK, you're welcome. Take care

**Reported by:** Patr**\* (pata*******************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/analysis/RNASeq#0--10">http://www.wormbase.org/resources/analysis/RNASeq#0--10</a>
**Browser:** Chrome 53.0.2785.116

**Comment by chris-grove** [comment]
Hi Patrick,


 Here are the list of genes annotated as expressed in both the L1 larval stage as well as the dauer larval stage in C. elegans. You can use WormMine to get L1 expressed genes using the following XML query:


`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.expressionPatterns.lifeStages.primaryIdentifier Gene.expressionPatterns.lifeStages.publicName Gene.expressionPatterns.primaryIdentifier" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.lifeStages.publicName" op="=" value="L1 larva Ce"/>
</query>`



or dauer-expressed genes using this XML query:


`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.expressionPatterns.lifeStages.primaryIdentifier Gene.expressionPatterns.lifeStages.publicName Gene.expressionPatterns.primaryIdentifier" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.lifeStages.publicName" op="=" value="dauer larva Ce"/>
</query>`



Normally you can save each of these as a WormMine list and then perform intersection operator on them in WormMine, but the save list functionality seems to be buggy at the moment, so I did the comparison with a different tool and created the list (attached). As I mentioned before, it is currently difficult to get genes that are preferentially expressed in L1 and dauer compared to other stages based on quantitative expression. I'll ask my other WormBase colleagues if there's a straightforward way to do this and get back to you.



Best,


Chris

**Comment by raymond91125** [comment]
Oops. Guess there's still a bit not finished.

**Comment by draciti** [comment]
If we did not hear back from the user, I assume it's safe to close.
