### ISSUE TITLE
Bug in Gene history widget (Datomic)

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5176]
User reported tag change in History widget on the gene page.

Split-from vs Split_from
Split-into vs Split_into

I believe this is coming from the re-write of the widget to pull the data from the datomic instance.

Should not be an issue for a general user, but they use the rest API to pull a json dump of the widget and parse this into a database.

**Comment by a8wright** [comment]
This is change is live now (only 7 hours later) Matt and I worked together for this minor change and were able to do continuous deployment to fix the issue. I am quite happy with us being able to do this instead of wait for the next website / database release.

**Comment by Paul-Davis** [comment]
Yeah, this is Amazing +1
