### ISSUE TITLE
Chris: Hello Ann, how can I help? visitor_name (vi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5177]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Ann, how can I help?</br>visitor_name (visitor_email): I need help answering author queries about how to cite wormbase and I couldn't figure it out from the citation page.</br>Chris: OK</br>Chris: Are you trying to cite WormBase in general or a specific page?</br>visitor_name (visitor_email): Specific page it is probably best for me to post the text and tell you what they want.  This will take a second</br>Chris: OK</br>visitor_name (visitor_email): We said: "RNA-seq data compiled on WormBase provides strong support for expression of lin-42a and lin-42b, while support for lin-42c comes from 3'RACE  (Rapid amplification of cDNA ends) sequence tags (WormBase release WS252)."  They want the following:</br>visitor_name (visitor_email): 1. provide a reference citation fo rhte RNAseq data complied on wormBase....and 2. Provide a specfic reference for WormBase release WS252 or a direct URL.  THe gene page may have changes since we wrote the paper since it is now release WS255. I am not sure how to even access teh 252 data page.</br>Chris: OK, the RNAseq data was taken from the Expression data on the lin-42 gene page?</br>Chris: As for the WS252 release, maybe it would suffice to point to our FTP site which houses data from that release?</br>Chris: ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/</br>visitor_name (visitor_email): Yes from clicking the RNA seq expression track under expression.</br>Chris: OK</br>visitor_name (visitor_email): I can ask whether they will take the ftp for the URL</br>Chris: OK, if that won't suffice I'll have to consult with other members of WormBase</br>visitor_name (visitor_email): I will include it in our answers and see if they object. It may be a couple days to get a reply.</br>Chris: OK, sure, sounds good</br>Chris: For the RNA seq expression, were you finding evidence for specific transcripts/splice variants for RNA seq from GBrowse or the gene page? http://www.wormbase.org/species/c_elegans/gene/WBGene00018572#-1-10</br>Chris: There are references listed for some of the RNAseq data, but I'm not sure specifically about splice variants</br>Chris: This more specific FTP URL may be good for referencing transcript sequences: ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/species/c_elegans/PRJNA13758/</br>Chris: Although, I don't think it specifically references the 3'RACE data</br>visitor_name (visitor_email): I guess just the Gbrowse.  Simply looking at the complied seqs vs the gene structure.  Lots of reads for a and b, many fewer for c. And then there were a couple indications of 3'RACE ends  that support lin-42c (weaker evidence). Not sure how to cite other that WB252.</br>Chris: OK, let me look into this and consult with other WormBase staff and get back to you. I'll try to get back to you within a day.</br>visitor_name (visitor_email): OK, thanks!</br>Chris: No problem. Is there anything else I can help you with?</br>visitor_name (visitor_email): not at the moment!</br>Chris: OK, I'll get back to you with citation information by email</br>Chris: Have a nice day!

**Reported by:** Ann ******* (roug***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/citing_wormbase#012--10">http://www.wormbase.org/about/citing_wormbase#012--10</a>
**Browser:** Firefox 49.0

**Comment by chris-grove** [comment]
Could someone help Ann with her request to properly cite RNA-Seq and 3'RACE data as supporting evidence for particular transcripts of lin-42?

Ann, if you can recall the tracks in GBrowse that were used as evidence for the lin-42 transcripts, there may be links to the source documentation from those.

Thanks,

Chris

**Comment by chris-grove** [comment]
I am pretty certain I was just using the RNA-seq track to support lin-42 a/b expression based on general alignment with the exons.
For the 3'RACE, I am having trouble reproducing it today.  There was a 3'race track that when selected indicated a 3'end mapped to the end of lin-42c.

A

**Comment by chris-grove** [comment]
Hi Ann, yes I'm seeing that now with the tracks listed under the "modENODE Tracks" under "Piano Group" track listings, particularly the "L2" and "L3" tracks of the "3RACE polyA-capture 3-UTR 454 alignments". If you click on the "?" in the track header in GBrowse you can find some links to data sources, GEO submissions for example:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM446653

for the 3' RACE data.

Chris

**Comment by chris-grove** [comment]
I see the ones for lin-42a/b but not for lin-42c.....
A

**Comment by chris-grove** [comment]
OK, I just found a page capture shot of what I was looking at - it is listed as a C. elegans RST, a 3' RST, RST3_378173.  Does this help?  I attached a picture of the printout.
![img_1365](https://cloud.githubusercontent.com/assets/611382/19521222/dfb78318-95e0-11e6-8f94-d350e3bfdcbd.jpg)

**Comment by chris-grove** [comment]
Hi Ann, yes this helps.

I'll still need to hear from someone on our sequence curation team about the RNA-Seq track citation. As for the RST track, clicking on the "?" in the track header provides some information about the data:

The submitted RACE data come from cloning and sequencing of 5' and 3' C.elegans RACE PCR products. The experiments were done using RNA isolated from "mix stage" wild-type N2 worms. SL1 and SL2 were used as 5' universal primers for 5'RACE experiments. The "RST's" (i.e., RACE Sequence Tags), are 5' reads from cloned RACE products (sequenced as minipools). Sequences are vector trimmed then quality trimmed (SL sequences are not removed from 5' RST's). In quality trimming, the first sliding window of 20 nt long with an average quality score higher than 15 marks the start of good quality sequences. Likewise, the first sliding window of 20 nt with average quality score lower than 15 marks the end of good quality sequences. Each RST is identified as being 5' or 3'(indicated as 5-RST or 3-RST) followed by a unique trace ID (e.g., >CCSB_5-RST_373657). 1,355 5' and 1589 3' RSTs are included in this submission. Data provided by Kourosh Salehi-Ashtiani, Vidal Lab. For information on the project, please see the Race Project Page at WorfDB.

with a link to the RACE Project page:

http://worfdb.dfci.harvard.edu/index.php?page=race

I would contact the Vidal group from that page; they may be able to point you to a specific paper with this data.

Chris

**Comment by chris-grove** [comment]
From @Paul-Davis 
Dear Ann,

I am a sequence curator and can add the following to my colleagues comments.

For citing evidence for the individual Isoforms as they are at the moment I would use the following:

F47F6.1a - Analysis:RNASeq_splice which is  "RNASeq splice region. These are the regions spanned by the SRA RNASeq short reads aligned to the genome by tophat/bowtie." This confirms the novel 1st exon for this isoform.

F47F6.1b - SL1 feature data (WBsf011249) as defined by AU203222 and Race Sequence Tag RST5_372798 "[090511 pad] More information about this dataset is available at the following URL: http://worfdb.dfci.harvard.edu/index.php?page=race"

F47F6.1c - mRNA data AF183400 ( Science. 1999 Nov 5;286(5442):1141-6.
Similarity of the C. elegans developmental timing protein LIN-42 to circadian rhythm proteins. Jeon M, Gardner HF, Miller EA, Deshler J, Rougvie AE.

F47F6.1d - Analysis:RNASeq_splice which is  "RNASeq splice region. These are the regions spanned by the SRA RNASeq short reads aligned to the genome by tophat/bowtie." This confirms the 5' extension of the locus as well as SL1 feature data (WBsf951596)

F47F6.1e - SL1 feature data (WBsf951548) as defined by multiple RNASeq experiments

F47F6.1f - A 5' extended form of F47F6.1c to follow the same evidence as F47F6.1d.


I have updated the citing wormbase page http://www.wormbase.org/about/citing_wormbase to bring it in line with current release data availability.

You are correct that the individual gene/Transcript pages for WS252 are no longer provided, so from the citation page I would suggest using the following text in their publication:

WormBase web site, http://www.wormbase.org, release WS252, date 07-Mar-2016.

I will also make sure that the Analysis summary for the RNASeq_splice is updated with the information above which will be visible on here: http://www.wormbase.org/resources/analysis/RNASeq_splice so this could also be used as a static URL for the evidence.

Please feel free to email and discuss anything.

Paul
