### ISSUE TITLE
Regarding caching of rest API widgets w/regard to the datomic api

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/website#5178]
@a8wright and I recently deployed a fix for #5176, which seemed to have resolved the issue.
The user has subsequently reported they were still encountering a similar error (original message truncated for applicability):
> I see that the genome representation for these split genes has been fixed=
.
>
> But even after refreshing the pages
>
> http://www.wormbase.org/rest/widget/gene/WBGene00270290/
> history?content-type=3Dapplication/json
>
> and
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00270290#05--3
>
> still return =E2=80=9CSplit-from=E2=80=9D.
>
> I=E2=80=99ve actually gone into the history file and edited it on my end,=
 so
> there=E2=80=99s no urgent need for me. 

The new datomic api for the URL the user quotes is shown to be correct by:
```bash
curl -H "Content-type: application/json" http://datomic-to-catalyst.a26ahpitsj.us-east-1.elasticbeanstalk.com/rest/widget/gene/WBGene00270290/history
```
It is my understanding that datomic rest API results are not cached - can this be confirmed?
Assuming that no caching of the datomic API is done, then I only theorise that
the cache-building system has cached the result of the previously-incorrect version?

Furthermore, if caching of the datomic rest API results is _not_ done,
then  the logic of the the website [code](/WormBase/website/blob/acadb63e915df071a66aaff2aac5206dd1ec7385/lib/WormBase/Web/Controller/REST.pm#L875) that determines which back-end to source the data from  would seem incorrect?
(There may be other configuration or code which means my reading of this is incorrect).

**Comment by a8wright** [comment]
Hi Matt, 

The design at present is for the widgets to get cached once they have been visited. This was to reduce risk during initial deployment. The intention is to not cache at all with the next release when the URI is coming from datomic. Usually Todd pre-caches the widgets but was intending on not pre-caching the datomic URI's. I know that he was running into some issues with not caching Datomic URI's but am not sure if he was able to fully fix the issue. He did say that he had a way to delete cache for specific URI's

@tharris Would it be possible for you to clear the cache for the history widget?

**Comment by mgrbyte** [comment]
Hi Adam,
Thanks for the explanation - this confirms my best guess at what may of been the cause and makes sense!

**Comment by tharris** [comment]
a small fraction of the URIs that use datomic were inadvertently cached but you would be hard pressed to find them.  

While it is possible to expire items in bulk from the cache, the process isn't fast, ot it can be done on a case by case basis.

**Comment by mgrbyte** [comment]
The user did mention that they had no urgent need, so I think we can await the next cache purge/rebuild.
Thanks @tharris!
