### ISSUE TITLE
User requests better information about available downloads

### ISSUE THREAD

**Issue by kyook** [WormBase/website#5179]
I found we have a widget about our downloads on the user guide, but it hasn't been updated in 5 years. http://www.wormbase.org/about/userguide#03--10-0
Can we update this information?

**Comment by epaule** [comment]
have a look if it shows an edit button on the lower border of the widget. If yes, you should be able to edit it, else give a shout to the webteam.

**Comment by sibyl229** [comment]
Thanks @epaule . Hi @kyook you should be able to edit it yourself when you login your wormbase account. I edited the part that I think is out of date: http://www.wormbase.org/about/userguide#03--10-0
