### ISSUE TITLE
Links from gene pages to WormFlux database are directing back to WormBase

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5180]
In the External Links widget on gene pages, we now have apparent links to the WormFlux database, but they are linking right back to the WormBase gene page. See, for example, the gene page for the gpi-1 gene:

http://www.wormbase.org/species/c_elegans/gene/WBGene00013597#-2-10

The "WormFlux" and associated "WBGene00013587" links both link back to the same page rather than to the WormFlux database page for this gene:

http://wormflux.umassmed.edu/Genes/WBGene00013597.php

**Comment by sibyl229** [comment]
Hi @chris-grove The WormFlux link should be good now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00013597#-2-10

**Comment by chris-grove** [comment]
@sibyl229 
 Perfect! Thanks Sibyl!
