### ISSUE TITLE
visitor_name (visitor_email): hello there visitor_...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5191]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): hello there</br>visitor_name (visitor_email): do you know hot F43G9 affects toxicity?</br>visitor_name (visitor_email): hot=how

**Reported by:** Olga (olga*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00009664#-037c-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00009664#-037c-10</a>
**Browser:** Chrome 53.0.2785.143

**Comment by chris-grove** [comment]
Hi Olga,

 I don't know how it affects toxicity. You're best bet would be to use Google or Google Scholar. I was able to find this article which seems the most relevant of results:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3248563/

Good luck,

Chris
