### ISSUE TITLE
  Is it possible to get the "overview" ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5192]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is it possible to get the "overview" information from wormbase as an exported column in wormmine?  I have tried to use "description" and "brief description", but sometimes there is information that is available in the overview that doesn't show up.   If there is a way to do that, please let me know.  Thank you</p>

**Reported by:** Mega********* (mega*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by chris-grove** [comment]
Hi Megan,


 The WormMine data is a couple of releases behind the data on the live site, which may explain the discrepancy you're seeing with gene descriptions. Could you give us some specific examples of genes for which the descriptions are not the same in WormBase and WormMine?

You may also find it useful to use our SimpleMine tool, available under the WormBase Tools menu:


http://www.wormbase.org/tools/mine/simplemine.cgi


For this tool, you would need to enter a list of gene names or IDs to get the results. The results include several data types including description, and may be more up to date than WormMine.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Haven't heard back from user. Closing.
