### ISSUE TITLE
operons missing from the gene overview

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5193]
the overview widget of M01G5.1 on the live site did show in the past the operon from the Contained_in_operon tag, similar to the staging sites behaviour. Now it is gone.
On the positive side, the operons are indexed in the search, so I can search for all genes contained in operon CEOP3899

(it affects all operons, not only the C.elegans ones)

http://www.wormbase.org/species/c_elegans/gene/WBGene00019715
http://staging.wormbase.org/species/c_elegans/gene/WBGene00019715
http://www.wormbase.org/search/gene/CEOP3899

**Comment by sibyl229** [comment]
Hi @epaule The problem with Operon in gene overview should be fixed now. http://staging.wormbase.org/species/c_elegans/gene/WBGene00019715#0--3

**Comment by epaule** [comment]
thanks. Looking good :-)
