### ISSUE TITLE
  Dear WormBase, We published an articl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5195]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase,<br/>We published an article (see link below) earlier this year describing the interaction between MBK-2 and GEI-12 (renamed to MEG-3) with detailed characterisation. However, our paper is not listed under the MEG-3 entry as a reference. Could you please add our paper to the MEG-3 page?<br/>http://www.wormbase.org/resources/paper/WBPaper00049305#0--10<br/>Many thanks,<br/>visitor_name, PhD</p>

**Reported by:** Jiax******** (jiax**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by vanaukenk** [comment]
Dear Jia-Xuan,

Thanks for writing to WormBase.

I've made the additional gene-paper connections for WBPaper00049305 and they will appear in WormBase release WS258.

Best,
--Kimberly Van Auken
