### ISSUE TITLE
  Hi, how do i download a fasta file wi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5196]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, how do i download a fasta file with sequences including the 3'UTR region for a list of genes that i'm studying ?</p>

**Reported by:** Jose****** (carl********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by chris-grove** [comment]
Hello Carlos,


 You can get 3'UTRs for a list of genes using the BioMart tool at WormBase ParaSite. You can find a link to this tool under the WormBase Tools menu, under the subheading "Data Mining and Batch Queries" as "ParaSite Biomart":

http://parasite.wormbase.org/biomart/martview/f8eae6b82899729bc85bee7925e291e9


In the "Query Filters" section you can specify a list of genes. Then, in the "Output Attributes" section you can select the "Retrieve Sequences" radio button and select "cDNA sequences" from under the "SEQUENCES" section which should include 3'UTRs. Then click on "Results" to get the list of sequences.


Let us know if you need any help or have any questions.


Chris Grove

WormBase
