### ISSUE TITLE
visitor_name (visitor_email): can I download all C...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5202]
_Help Desk chat transcript. Issue can be closed if question was resolved in chat._

visitor_name (visitor_email): can I download all C. elegans  protein-coding gene on x chromosome from wormbase?

**Reported by:** Ren *****\* (ren-************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/gmap/run?name=V;class=Map&amp;click=310-8">http://www.wormbase.org/tools/gmap/run?name=V;class=Map&amp;click=310-8</a>
**Browser:** Firefox 49.0

**Comment by chris-grove** [comment]
Hello Ren,


 You can use WormBase ParaSite BioMart (you can find a link under the Tools menu) to get this information. If you open this URL:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.ensembl_gene_id|wbps_gene.default.feature_page.external_gene_id&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.chromosome_name."X"|wbps_gene.default.naive_filters.biotype."protein_coding"&VISIBLEPANEL=resultspanel

You can click on "Results" to get your list. I also attach the query results.


Best,


Chris Grove

WormBase
