### ISSUE TITLE
visitor_name (visitor_email): i need more informat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5203]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): i need more information about RPB 6

**Reported by:** thịn* (than*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/protein/WP:CE02117#06--10">http://www.wormbase.org/species/c_elegans/protein/WP:CE02117#06--10</a>
**Browser:** Chrome 54.0.2840.71

**Comment by tuli** [comment]
Good morning,

Thank you for writing to WormBase.

Please can you tell us more specifically what additional information
you need about protein RPB-6?

Have you tried looking at the information within the different widgets
on the page e.g. Motif Details or Homology?

Best wishes,

Mary Ann

On 31 October 2016 at 06:47,  <no-reply@wormbase.org> wrote:
> online chat thịnh (thanhthinhlee@gmail.com): i need more information about
> RPB 6
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/protein/WP:CE02117#06--10
> http://www.wormbase.org/species/c_elegans/protein/WP:CE02117#06--10
>
> This issue has been assigned ticket number: #5203. Follow progress on our
> issue tracker.
>
> Reported by: thịnh (thanhthinhlee@gmail.com)
> 31 Oct 16 06:47
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
