### ISSUE TITLE
Downloads linking to ParaSite 6

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#5205]
On the downloads page, the links to ParaSite download files are for WBPS6, but the latest version (since August) is WBPS7: http://www.wormbase.org/species/all

**Comment by sibyl229** [comment]
Hi @tharris it looks like WBPS7 hasn't been synced to the FTP site yet: ftp://ftp.wormbase.org/pub/wormbase/parasite/releases/ Could you take a look at please? Thank you!

**Comment by tharris** [comment]
Mirrored.

**Comment by brucebolt** [comment]
Re-opening as the links in the downloads table still go to WBPS6 (latest release is WBPS8).

**Comment by tharris** [comment]
It's syncing now and continues to do so. You can close the issue when its complete.

**Comment by brucebolt** [comment]
@tharris Thanks, I can see the data on the FTP site.  The issue is the link in the downloads table on WormBase needs updating to either the latest release number or the current symlink.

**Comment by tharris** [comment]
Ah, I see. Sorry, @brucebolt. @sibyl229, recommend updating the links to just use the "currnet" symlinks on the FTP site.

**Comment by brucebolt** [comment]
I see an issue here.  The filename also includes the ParaSite release number.

@sibyl229 we have a REST endpoint that will return the latest WBPS release number and the corresponding WormBase release - maybe this could be used to deduce the filename: http://parasite.wormbase.org/rest/info/version/?content-type=application/json

**Comment by sibyl229** [comment]
Hi @brucebolt Thanks for the info! Do you have an endpoint for all the Parasite species? Currently it relies on the species_tree.json on the ftp site, which isn't made for WBPS7 and 8.

**Comment by brucebolt** [comment]
Hi @sibyl229, we have a dynamic version of species_tree.json which is updated each release: http://parasite.wormbase.org/Multi/Ajax/species_tree

**Comment by sibyl229** [comment]
@brucebolt Great! Thank you

**Comment by sibyl229** [comment]
Done
