### ISSUE TITLE
  To whom it may concern, I'm intereste...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5206]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;To whom it may concern,<br/>I'm interested in studying gene expression in c. elegans using gfp fusion proteins as an indicators for gene expression. I am having a hard time using the data base and search directory to find certain gfp fusion genes of interest in c. elegans. Is there a way to view a comprehensive list of all c. elegans with a gfp fusion gene or of searching for a certain gfp-fusion gene in c. elegans? Any feedback would be helpful.<br/>Thank you in advanced,<br/>visitor_name</p>

**Reported by:** Cath******* (csol***************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; Tablet PC 2.0; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; McAfee; LCJB; rv:11.0) like Gecko

**Comment by draciti** [comment]
Hi Catherine,

thanks for contacting WormBase. Is there any particular gene you are interested in looking at?

as a general example, see this WormBase page for the gene smf-1
http://www.wormbase.org/species/c_elegans/gene/WBGene00004876#-1-10 <http://www.wormbase.org/species/c_elegans/gene/WBGene00004876#-1-10>


on the right hand side of the table you have a ‘Transgene’ column that lists the GFP-fusions used to monitor expression.

If you are interested instead in finding gfp fusions expressed in a specific cell/tissue you can go the the Anatomy page, see for example

http://www.wormbase.org/species/all/anatomy_term/WBbt:0003963#01--10 <http://www.wormbase.org/species/all/anatomy_term/WBbt:0003963#01--10>

In the Associations widget you will see a list of transgenes that have been used to monitor expression in that specific tissue/cell.

Please do not hesitate to contact us if you have any additional questions.

best,
Daniela

**Comment by raymond91125** [comment]
@draciti Could we close this if no more response coming from user?

**Comment by draciti** [comment]
yes raymond thanks, I have not heard back. Closing

**Comment by raymond91125** [comment]
cheers.
