### ISSUE TITLE
  i want list of housekeeping gene in c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5208]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;i want list of housekeeping gene in c.elegans  which are identical in meloidogyne incognita </p><p>What were you doing? <br />&nbsp;&nbsp;i am m.sc student division of nematology IARI new delhi 110012</p>

**Reported by:** shiv*** (shiv*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.28 Safari/537.36

**Comment by brucebolt** [comment]
Dear Shivaji

WormBase does not maintain a list of housekeeping genes for C. elegans.  I suggest you search the literature, where you may find some information.

Once you have a list of C. elegans genes, you can lookup the orthologues in M. incognita using the WormBase ParaSite BioMart.  Set Query Filters —> GENE —> ID list limit —> Gene Stable ID, then insert your list of C. elegans gene IDs.  Then set Output Attributes —> ORTHOLOGUES —> M. incognita gene stable ID & Human gene name.  Click Results (button at top of page) are you will see the orthologues.

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
