### ISSUE TITLE
Apparently bogus genes in WormMine (im-254)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5209]
@nuin 
This could very well be logged under issue #4842 , but they may be slightly different issues...

When I perform a very basic search for any and all genes in WormMine:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>`

I get results that look like this:

![screen shot 2016-11-02 at 11 56 44 am](https://cloud.githubusercontent.com/assets/611382/19936340/7f8c374a-a0f3-11e6-8971-8a92d22d46e4.png)

There are two red flags:

1) The "WormBase Gene IDs" are either a set of numbers (e.g. "100506422", "2565702") or have the form of a gene sequence name (e.g. "B0303.5", "C13B9.1"); these are not real WormBase gene identifiers and are likely the result of an import error, or a bad cross-reference

2) Several "genes" have no species attached. Every gene in the database should have a species

**Comment by nuin** [comment]
#4842

**Comment by chris-grove** [comment]
I'll just add:
There are several genes whose "Gene IDs" begin with "gmap:" or "landmark:"; these are also duplicates that should not be different from the genes whose names come after that prefix. So, for example, there are two gene objects "gmap:unc-3" and "landmark:unc-3" that should not be separate objects from each other or from the "real" unc-3 gene object with ID "WBGene00006743", sequence name "Y16B4A.1" and gene name "unc-3". Another duplicate unc-3 gene object is the one that has "Gene:WBGene00006743" as the ID and "WBGene00006743" as the gene name.

**Comment by nuin** [comment]
@chris-grove I was able to pinpoint the problem to Panther data added to the database. 

```
panther/RefGenomeOrthologs:HUMAN|Ensembl=ENSG00000005189|UniProtKB=H3BM72	HUMAN|Gene=44M2.3|UniProtKB=Q96IC2	P	Homo-Pan|HUMAN	PTHR12801
panther/RefGenomeOrthologs:HUMAN|Gene=44M2.3|UniProtKB=Q96IC2	MOUSE|MGI=MGI=1919402|UniProtKB=D3YW29	LDO	Euarchontoglires	PTHR12801
panther/RefGenomeOrthologs:HUMAN|Gene=44M2.3|UniProtKB=Q96IC2	RAT|RGD=1305412|UniProtKB=A1A5R7	LDO	Euarchontoglires	PTHR12801
panther/RefGenomeOrthologs:HUMAN|Gene=44M2.3|UniProtKB=Q96IC2	CHICK|Ensembl=ENSGALG00000002239|UniProtKB=F1P5D1	LDO	Amniota	PTHR12801
panther/RefGenomeOrthologs:HUMAN|Gene=44M2.3|UniProtKB=Q96IC2	HUMAN|HGNC=24660|UniProtKB=Q8IX06	P	Craniata-Cephalochordata|Osteichthyes	PTHR12801
panther/RefGenomeOrthologs:HUMAN|Gene=44M2.3|UniProtKB=Q96IC2	HUMAN|HGNC=24616|UniProtKB=Q8N1G1	P	Craniata-Cephalochordata|Osteichthyes	PTHR12801```

I grepped for `44M2.3`, now I need to find out why the merge is not working correctly, or why the results are being shown for something with no species attached to it. Maybe we need to improve the template, but I am checking.

**Comment by nuin** [comment]
Note to self, move Entrez step to the bottom.

**Comment by nuin** [comment]
Changing the Entrez step to the end of the build didn't work. The step stopped on an error and manually running it didn't work too. The error is still present and it's not known if it's because the Entrez step failed, or the solution itself failed.

**Comment by nuin** [comment]
This is definitely coming from Panther data. I will contact InterMine devs to check this.

**Comment by chris-grove** [comment]
OK, I think this issue is pretty much resolved. Closing

**Comment by nuin** [comment]
Yes, we are not adding Panther anymore due to this issue. I am investigating a better loading process for it.

**Comment by chris-grove** [comment]
@nuin 
OK, I'll let you re-open this ticket if you need to

**Comment by nuin** [comment]
I will open a new one, with more technical stuff.
