### ISSUE TITLE
Non-C.elegans transcripts associated with C. elegans in WormMine (im-254)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5210]
While checking over the template available on the WormMine homepage called "Species --> Transcript", I leave the default search for "Caenorhabditis elegans" and get some reasonable looking results. However, if I remove the transcript's "WormMine ID", and add the transcript's "Sequence Name", I begin to see many transcripts whose sequence name begins as "Pan_g" or "Cang"; here's a screenshot:

![screen shot 2016-11-02 at 3 18 12 pm](https://cloud.githubusercontent.com/assets/611382/19943927/f15423e4-a10f-11e6-8f13-716159652fea.png)

The query for this is:

`<query name="" model="genomic" view="Transcript.chromosomeLocation.start Transcript.chromosomeLocation.end Transcript.chromosomeLocation.strand Transcript.chromosomeLocation.locatedOn.primaryIdentifier Transcript.symbol" longDescription="">
  <constraint path="Transcript.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>`

It turns out there are 79,116 transcripts labeled as belonging to C. elegans but start with the "Pan_g" of Panagrellus redivivus and 101,802 transcripts labeled as belonging to C. elegans with the "Cang_" of Caenorhabditis angaria. I don't know if there are any other cross-species "contamination" of transcripts.

**Comment by nuin** [comment]
@chris-grove I have a new instance on im-257.wormbase.org (CSS is not perfect) and it seems that the error above was solved. The offending entries were on FASTA files coming from other species. We can either remove these files or work on parsing them correctly. As they were only added in the last build, I will remove the FASTA from other sequences from 257 and work on a better solution.

**Comment by nuin** [comment]
@chris-grove Instance is current down for another test build.

**Comment by chris-grove** [comment]
@nuin 
OK, can you give me a shout when the new im-257 site is back up and running?

**Comment by chris-grove** [comment]
@nuin 
Yes, looks good. Thanks! Closing.
