### ISSUE TITLE
visitor_name (visitor_email): Hi, I need to know a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5211]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I need to know all the strains available that present neuronal ablation. Is there an easier way to get this information, instead of searching the literature?

**Reported by:** Dani********** (dani*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 54.0.2840.71

**Comment by tuli** [comment]
@kyook I don't think there is a Phenotype object for neuronal ablation

Is there another way to get this info do you know?

**Comment by kyook** [comment]
Hi Mary Ann, 

None that I know of; however, Raymond does curate ablation data. I have already requested his help for getting back to the user. 

Raymond, if you can't address this user request, please let me know. 

Karen

**Comment by raymond91125** [comment]
Some strains used to remove or knock down cell function are annotated in anatomy function but it's far from complete or structured. If strain curation has no additional info, then I think the answer is a clear no. I for some reason stopped getting help desk user email addresses.

**Comment by kyook** [comment]
Ok, so unfortunately the only way to get this information is through the literature.

**Comment by chris-grove** [comment]
@kyook Have you (or anyone else) responded directly to the user by email?

**Comment by kyook** [comment]
I could not find the users e-mail address. 

-mobile-

**Comment by chris-grove** [comment]
@kyook I just sent it to you

**Comment by kyook** [comment]
I replied to the user: 
Hi Danielle,

I'm very sorry for the delay in getting back to you. Unfortunately, there is no easy way to get this information and the literature search is the best option for finding it. 

Apologies,
Karen


Haven't heard back so I will close this ticket for now.
