### ISSUE TITLE
Cannot specify species when uploading a list of alleles in WormMine (im-254)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5212]
When attempting to upload a list of alleles, specifying the species results in no hits. For example, if I enter the C. elegans alleles e1370, mu86, and sy1 and specify the species as C. elegans, as in the screenshot below:

![screen shot 2016-11-03 at 10 16 45 am](https://cloud.githubusercontent.com/assets/611382/19969456/005b1286-a1af-11e6-985c-2de13bd93348.png)

once I click "Create List", it returns no results. If I perform the same list upload without specifying the species, it properly recognizes them. I imagine this is an indication that the allele objects do not have species info populated in WormMine yet.

**Comment by nuin** [comment]
Hi @chris-grove 

I just did a similar list search using `unc-26` and `aap-1` as identifiers and selected C. elegans 
![wormmine__lists](https://cloud.githubusercontent.com/assets/6273/20688444/fd2a3dca-b57d-11e6-93d3-7c647501de1d.png)
 on the dropdown and I got results


![wormmine__list_confirmation](https://cloud.githubusercontent.com/assets/6273/20688342/aa917330-b57d-11e6-8f00-65f9e2196ee1.png)


Trying the same identifiers you used in the WS253 release also didn't give me any results. Can you double check, please?

**Comment by chris-grove** [comment]
@nuin 
My example was specifically of allele names, not gene names. If I specify the type as "Allele" and leave the "for Organism" field blank (or choose "Any"), I can get results using the alleles "e1370", "mu86" and "sy1". However, if I specify the species as C. elegans (which these alleles belong to) I get no results. I think the problem is that these allele objects are not indexed with a species (that's my guess). This is not a high priority item.

**Comment by nuin** [comment]
Sorry, I didn't notice the Allele on your search. I am checking now, but I don't think Alleles per se are indexed, as you mentioned.

**Comment by nuin** [comment]
@chris-grove With the failure of species retrieval, there's no way to select species anymore in the list, but the search with `Any` works fine for the IDs you provided above. Please, take a look and let me know.

**Comment by chris-grove** [comment]
@nuin 
OK, yes that's working now. So I guess that means we won't have a species selection option for list uploads? I'm not sure that we need it, so I think that's OK

**Comment by nuin** [comment]
The species will be back eventually, when I fix an error on Entrez species retrieval. There is some thoughts from @tharris to create a slim **C. elegans** only Mine.

**Comment by chris-grove** [comment]
@nuin 
OK, got it. Thanks!
