### ISSUE TITLE
WormMine (im-254): Reference tag name in RNAi should be "WBPaper ID" instead of "PubMed ID"

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5213]
In the RNAi class in WormMine, the reference tag is labeled as "PubMed ID" but the data is in WBPaper ID format and so should be relabeled as "WBPaper ID".

![screen shot 2016-11-03 at 10 50 03 am](https://cloud.githubusercontent.com/assets/611382/19970749/57d654f4-a1b3-11e6-8467-9a051d17cfc2.png)

**Comment by nuin** [comment]
Hi @chris-grove 

This seems the norm for most classes, labels are set as PubMed ID all around. I am investigating how to change it.

**Comment by nuin** [comment]
@chris-grove Changed in the whole system. I am closing the ticket.

**Comment by chris-grove** [comment]
@nuin 
Thanks!
