### ISSUE TITLE
WormMine (im-254): RNAi inhibited gene is populated with transcript names; should be gene IDs

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5214]
If I run the following query for all RNAi objects and their inhibited genes and transcripts:

`<query name="" model="genomic" view="RNAi.primaryIdentifier RNAi.inhibitsGene.primaryIdentifier RNAi.inhibitsGene.secondaryIdentifier RNAi.inhibitsGene.symbol RNAi.inhibitsTranscript.symbol" longDescription="" sortOrder="RNAi.primaryIdentifier asc">
</query>`

I get the following table of results:

![screen shot 2016-11-03 at 10 57 57 am](https://cloud.githubusercontent.com/assets/611382/19971090/69b8917c-a1b4-11e6-8370-8579ff83b261.png)

The names listed in the "Inhibits Gene, WormBase Gene ID" field are actually names of transcripts, for example "B0511.9a", "B0511.9b", and "B0511.9c", whereas the sequence name and gene name fields are blank as is the transcript field. This may be why some duplicate/bogus gene objects are being populated in WormMine with transcript names instead of gene IDs (e.g. WBGene00000001) as reported in issue #5209 

For the rows showing "B0511.9a", "B0511.9b", and "B0511.9c" as the gene IDs for the inhibited gene(s), these should rather be listed as the following:

RNAi WormBase ID-----WB Gene ID ----------Seq.Name----Gene Name---Transcript Seq.Name
WBRNAi00000002------WBGene00015235----B0511.9-------cdc-26---------B0511.9a
WBRNAi00000002------WBGene00015235----B0511.9-------cdc-26---------B0511.9b
WBRNAi00000002------WBGene00015235----B0511.9-------cdc-26---------B0511.9c

**Comment by nuin** [comment]
I think the easiest solution for this would be to link the `/RNAi/Inhibits/Predicted_gene//CDS` to the primary identifier of the CDS table (transcript name), then it should affect the other columns at the same time. I will work on this as soon as WS259 is in production.

**Comment by chris-grove** [comment]
@nuin 
FWIW, the ?RNAi class in ACEDB refers directly to the gene calculated to be inhibited by the RNAi experiment in the "Gene" tag:

?RNAi
     Inhibits  Gene   ?Gene

So maybe it's best to get the gene ID from that tag in ACEBD? That is, rather than determine which gene is associated with the CDS. A quick query of WS259 ACEDB shows that there are about 2000 more RNAi experiments that refer to "Gene" than refer to "Predicted_gene", so if we only go through the "Predicted_gene" tag we'll surely be missing some (~2000) RNAi-to-gene associations.

**Comment by nuin** [comment]
OK, thanks @chris-grove, I already have in my list revisit some of the RNAi mapping and that would be a addition to the changes.
