### ISSUE TITLE
  GBrowser is broken  What were you doi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5215]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;GBrowser is broken</p><p>What were you doing? <br />&nbsp;&nbsp;When I access the GBrowser and head to the mop-25.1 promoter, and try to get the promoter sequence via a FASTA dump after selecting the non-coding region, I either get no dump in the new window that opens, or I get the ~400bp of coding region, starting with an ATG.

GBrowser has been broken for a very long time now and this continues to happen at multiple genomic loci. Please help.</p>

**Reported by:** Davi********* (davi*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by scottcain** [comment]
Response sent to user:


There are two ways of getting sequence from GBrowse and both are currently working for me.  I'll describe each below, but I'm wondering if you have a javascript blocker that isn't allowing some WormBase javascript from executing, which would explain why it seems broken for you but continues to work for me, or if you are using a browser that is not compatible with GBrowse (I don't know of any off hand, but I haven't tested with every browser in existence, particularly newer Windows browsers).  If you think that might be the case, please try a different browser if possible.

The way it sounds like you are trying to get sequence is by highlighting a region that you want sequence for and then selecting "Dump selection as FASTA".  When I do that, GBrowse opens another window with the highlighted region's sequence in fasta format.  The other way to get fasta from GBrowse is to use zooming and panning to get the region you want sequence for displayed in the GBrowse details panel, and then click on the (admittedly tiny) floppy disk icon in the row of icons next to the track name.  Select the fasta radio button and then click the "Download track data across region X:4,001,234..4,002,345" (or whatever) and it will download a fasta file to your default download folder.

Finally, it is also possible to get fasta from our new genome browser, JBrowse.  For instance, if you go to this link:

http://www.wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758&loc=X%3A3998151..4039750&tracks=Curated%20Genes%20(protein%20coding)&highlight=

You'll see the mop-25.1 gene.  Right click or control click on a transcript and select "View Sequence" from the pop up menu and you'll see a sequence display that allows you to get up and downstream sequence as well as to hide other sections of sequence or highlight them.  Please note that this functionality in JBrowse is still in beta but works pretty well.  It's not currently available in the main "Curated Genes" track, but is available in the all of the Curated Genes subsets (non-coding, protein coding, etc).

Please let me know if you're still having difficulties with this functionality,
Scott

**Comment by raymond91125** [comment]
@scottcain Good to close this?

**Comment by scottcain** [comment]
Haven't heard back after a few weeks; closing.

**Comment by raymond91125** [comment]
Yah. That's what I assumed. :)
