### ISSUE TITLE
C. elegans: full neuron-gene dataset, annotations, qualifiers

### ISSUE THREAD

**Issue by AurinaBMH** [WormBase/website#5216]
Hello,

I am quite new to C. elegans gene data and would be very grateful if you could help me with some issues/questions that came up during the process of acquiring it. 

To start with, I downloaded a full gene expression dataset from this address:  ftp://ftp.wormbase.org/pub/wormbase/releases/WS254/ONTOLOGY/anatomy_association.WS254.wb result I am looking for is gene expression matrix for all available neurons and all available genes in a format where rows are neurons and each column represents a separate gene. Would you recommend to use this dataset for this purpose? Or there is another (more reliable/more up to date) version of it?

In regards to this current dataset, I also have a few questions about annotation types:

In this dataset, there are genes that are directly annotated to neurons (e.g. a gene is expressed in a certain neuron) as well as indirectly annotated gene (e.g. a gene is expressed in a hierarchical category of neurons, such as "head neurons"). I was wondering if directly and indirectly annotated genes should be interpreted differently of if they are equivalent in terms of reliability. The more specific question is whether we should use all genes (directly+indirectly annotated) or only directly annotated genes in the final analysis where we need a reliable neuron x gene expression matrix with all neurons and all available genes. 

Another question is about gene qualifiers (like certain/uncertain/partial/enriched/Life_stage ...). Could you please explain once again what some of them mean? I have found explanations for some of them (certain/uncertain/partial) in here: https://github.com/WormBase/website/issues/1001 , but I am still wondering what does it mean if a gene is qualified as "Enriched" or "Life_stage" and whether blank qualifiers mean only that the study is done before 2005 or it has some additional meaning? In relation to that, could you please advise me if it's the best choice to only use "certain" qualified genes in order to have the most reliable data and at the same time not to miss valuable information?

I would be very grateful if you could help me to clarify these issues. 
Thank you for your time!

Aurina

**Comment by draciti** [comment]
Hello Aurina,

we recently generated an output file for neuronal expression that might be useful to you. The file-attached- includes only expression that was observed via immunohistochemistry, in situ hybridization, reporter fusion. It does not include microarray, RNAseq and proteomic data (the enriched genes that you see in the anatomy association file). The file dates back to July 2016, it's pretty recent but we will work on a newer version of it and send it to you by next week.


to answer specifically to your questions:

>I am looking for is gene expression matrix for all available neurons and all available genes in a format where rows are neurons and each column represents a separate gene. Would you recommend to use this dataset for this purpose? Or there is another (more reliable/more up to date) version of it?


yes you can use this dataset (is the most reliable and up-to-date)


>there are genes that are directly annotated to neurons (e.g. a gene is expressed in a certain neuron) as well as indirectly annotated gene (e.g. a gene is expressed in a hierarchical category of neurons, such as "head neurons"). I was wondering if directly and indirectly annotated genes should be interpreted differently of if they are equivalent in terms of reliability.


for the direct and indirect, just look at this example

http://www.wormbase.org/species/all/anatomy_term/WBbt:0005413#031--10


78 genes have been found directly to be expressed in AIYL. Consequently those genes have been indirectly associated to be expressed to the higher node of the ontology, the neuron AIY, in turn they will be indirectly associated to interneuron.


>I am still wondering what does it mean if a gene is qualified as "Enriched" or "Life_stage" and whether blank qualifiers mean only that the study is done before 2005 or it has some additional meaning?


gene qualified as enriched have been found enriched in a certain dataset through microarray, RNAseq or proteomic analysis.

Life_Stage captures the developmental stage at which genes have been found to be expressed and yes, blank qualifiers mean that the study has been done before we introduced the qualifier tagging in 2005.


>In relation to that, could you please advise me if it's the best choice to only use "certain" qualified genes in order to have the most reliable data and at the same time not to miss valuable information?


I would advice to use the certain, partial, blank, enriched qualifiers for best results.

It’s up to you to run the analysis adding the ‘uncertain’ qualifier. An example of uncertain expression could be that the authors were not absolutely sure about the cell identity and classified the expression as possible. Other times the expression is seen infrequently and they report it again as potential.


I hope I have addressed your questions, do not hesitate to contact us should you have additional ones.


Good luck!

Daniela



________________________________

**Comment by AurinaBMH** [comment]
Hello Daniela, 

Thank you for a very informative response. 
I would like to clarify a few things just to ensure I understood them correctly. 

In terms of directly/indirectly annotated genes, is it true that if a gene is directly annotated to a few (not all) neurons from a certain higher order category, this gene will be indirectly associated to this particular higher order category despite the fact that not all neurons in this category express this particular gene?

Therefore, if this is true, we can not perform the reverse assignment by relating genes to specific neurons according to their indirect association to higher order categories. For example, if a gene is indirectly associated with interneuron category, it doesn't mean that all interneurons express this gene? 
Please correct me if I'm wrong here. 

Could you also help me accessing the attached file you mentioned in your response - I couldn't find the attachment. 

Thank you so much for your time!
Your answers were really helpful. 

Best, 
Aurina

**Comment by draciti** [comment]
Hi Arina,

> is it true that if a gene is directly annotated to a few (not all) neurons from a certain higher order category, this gene will be indirectly associated to this particular higher order category despite the fact that not all neurons in this category express this particular gene?

yes, that is correct. This happens when authors simply say that, for example, the gene was expressed in interneurons without specifying if 'all interneurons'. At the level of annotation, we do assign the higher order category, i.e. interneuron.

>Therefore, if this is true, we can not perform the reverse assignment by relating genes to specific neurons according to their indirect association to higher order categories. For example, if a gene is indirectly associated with interneuron category, it doesn't mean that all interneurons express this gene? 

that is correct.

I attach the file updated to today.
Best,
Daniela
[List_with_genes_20161105.txt](https://github.com/WormBase/website/files/573246/List_with_genes_20161105.txt)

**Comment by AurinaBMH** [comment]
Hi Daniela, 

Thank you very much for your help!

Best, 
Aurina

**Comment by draciti** [comment]
Glad to hear Aurina.
Best,
Daniela
