### ISSUE TITLE
I need a reference gene sequence of c.elegance brc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5223]
*Help Desk query collected when no chat operators were online. Follow up required.*

I need a reference gene sequence of c.elegance brca1  for analysis of mutation

**Reported by:** Mano* (biom****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006701?from=http://www.wormbase.org/db/gene/gene?name=ubc-1#0-9g-10-9">http://www.wormbase.org/species/c_elegans/gene/WBGene00006701?from=http://www.wormbase.org/db/gene/gene?name=ubc-1#0-9g-10-9</a>
**Browser:** Chrome 54.0.2840.71

**Comment by chris-grove** [comment]
Hello,


 The C. elegans orthologs of human BRCA1 are brc-1 and F42A6.5. You can find sequences for them in the "Sequences" widget on each gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000264#0-46g-10

http://www.wormbase.org/species/c_elegans/gene/WBGene00018327#0g-46-10

You can find mutation information in the "Genetics" widget.

Best,


Chris Grove

WormBase
