### ISSUE TITLE
Hi, good morning, i have a question, about if exis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5226]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, good morning, i have a question, about if exists, the strain with knock out of NMDAreceptors Thank you for yor attention

**Reported by:** fern**** (mafe****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/strain/knock out NMDAr">http://www.wormbase.org/search/strain/knock out NMDAr</a>
**Browser:** Chrome 54.0.2840.71

**Comment by chris-grove** [comment]
Hi,


 The C. elegans NMDA receptors are encoded by two genes, nmr-1 and nmr-2. You can view their respective gene pages here:


http://www.wormbase.org/species/c_elegans/gene/WBGene00003774#04--10

http://www.wormbase.org/species/c_elegans/gene/WBGene00003775#04--10


From the "Genetics" widget, you can find strains that carry variants of these genes. The knockout strain for nmr-1 is VM487:


http://www.wormbase.org/species/c_elegans/strain/VM487#0216--10


and for nmr-2 is VC2623:


http://www.wormbase.org/species/c_elegans/strain/VC2623#0216--10



Best,


Chris Grove

WormBase
