### ISSUE TITLE
  We discovered an entry or original su...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5227]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We discovered an entry or original submission error concerning the position of mat-1(ax161) mutation. The data available in wormbase is wrong based on the sequencing results of the mutant. I can provide with the correct information and send you the appropriate file that you correct the faulty entry.<br/>Regards<br/>Attila Stetak</p>

**Reported by:** a.st**************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7

**Comment by tuli** [comment]
Dear Attila,

Thank you for writing to WormBase and for bringing this mistake to our
attention.

Please can you submit the correct data via our allele submission form,
which can be found here:
http://www.wormbase.org/submissions/allele_sequence.cgi

Best wishes,

Mary Ann

On 9 November 2016 at 13:41,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   We discovered an entry or original submission error concerning the
> position of mat-1(ax161) mutation. The data available in wormbase is wrong
> based on the sequencing results of the mutant. I can provide with the
> correct information and send you the appropriate file that you correct the
> faulty entry.
> Regards
> Attila Stetak
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5227. Follow progress on our
> issue tracker.
>
> Reported by: a.stetak@unibas.ch
> 09 Nov 16 13:42
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML,
> like Gecko) Version/9.1.2 Safari/601.7.7
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
