### ISSUE TITLE
  I need to find the C.elegans with the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5228]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I need to find the C.elegans with the phenotype Long-1</p><p>What were you doing? <br />&nbsp;&nbsp;I need find out the impact of that  strain (Long-1) in C-elegans</p>

**Reported by:** wivi*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

**Comment by chris-grove** [comment]
Hello,

 It sounds like you're looking for the C. elegans gene lon-1. Here's the page for that gene:

http://www.wormbase.org/species/c_elegans/gene/WBGene00003055#0-c4-10

You can find information about strains carrying variants of this gene in the "Genetics" widget.

Best,

Chris Grove
WormBase
