### ISSUE TITLE
Full neuron-gene dataset: missing information

### ISSUE THREAD

**Issue by AurinaBMH** [WormBase/website#5230]
Hi, 

I would be very grateful if you could advise me on a few additional issues regarding full gene expression dataset. 

First, I'd like to clarify, if it's possible to distinguish between two cases of: "a gene is not expressed" and "there are no data" cases in the WS254 dataset 
(ftp://ftp.wormbase.org/pub/wormbase/releases/WS254/ONTOLOGY/anatomy_association.WS254.wb)

For example, a dataset of directly annotated genes (for certain, enriched, partial, blank qualifiers), consists of 932 genes in total with the number of genes expressed in each neuron varying from 3 to 135. What can be said about other genes: are they not expressed in neurons? or there is no information about it? Moreover, what information about some not neuron-specific genes (like genes regulating ATP synthesis) can be extracted from this dataset?

Finally, as the reverse gene expression assignment from higher-level annotations to specific neurons is not correct (https://github.com/WormBase/website/issues/5216), is the above-mentioned data set (with 932 directly annotated gene) is the one to use if we are looking for a gene expression matrix for all available neurons and all available genes in a format where rows are neurons and each column represents a separate gene?

Any help would be very appreciated. 
Thank you for your time. 

Aurina

**Comment by draciti** [comment]
Hi Aurina,
we started to annotate NOT expressed only recently, so it is not possible at the moment to distinguish between not annotated and not expressed. Authors seldom describe when a gene is not expressed.

>is the above-mentioned data set (with 932 directly annotated gene) is the one to use if we are looking for a gene expression matrix for all available neurons and all available genes in a format where rows are neurons and each column represents a separate gene?

that's the one I would use.

Best,
Daniela

**Comment by AurinaBMH** [comment]
Hi Daniela, 

Thank you very much for your help once again!

Best, 
Aurina

**Comment by kyook** [comment]
This seems closable.
