### ISSUE TITLE
  Hi, I am a new faculty looking for po...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5231]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am a new faculty looking for postdocs. I was wondering whether and how I could post a postdoc ad on the WormBase website.<br/>Looking forward to your reply. Thank you very much in advance!<br/>Best wishes,<br/>Paschalis<br/>visitor_name, Ph.D.<br/>Assistant Professor<br/>Biological Sciences Division<br/>Department of Neurobiology<br/>Grossman Institute for Neuroscience<br/>University of Chicago<br/>947 E. 58th St., AB412<br/>Chicago, IL 60637, USA<br/>Office: +1-773-702-7442<br/>Lab: +1-773-834-7605<br/>http://www.kratsioslab.org</p>

**Reported by:** Pasc************** (pkra******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14

**Comment by chris-grove** [comment]
Hello,

 You can post postdoc opportunities on our forums:

http://forums.wormbase.org/

Best,

Chris Grove
WormBase
