### ISSUE TITLE
I am looking for instructions to navigate wormbase...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5234]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking for instructions to navigate wormbase to find the gene sequence for c. elegans dpy-11 (e794). thank you.

**Reported by:** Pam (sesh*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0-9g-3</a>
**Browser:** MSEdge 14.14393

**Comment by tuli** [comment]
Dear Pam,

Thank you for writing to WormBase.

First, submit a query for the e794 variation using the general search
box in the top right.
This will take you to the e794 variation summary page:
http://www.wormbase.org/species/c_elegans/variation/WBVar00143490
If you look at the Molecular Details widget you can see the wild type
and mutated sequence around the region of the lesion.

The full dpy-11 gene sequence can be found on the gene summary page
for dpy-11 http://www.wormbase.org/species/c_elegans/gene/WBGene00001073
under the Sequences widget.

I hope this answers your query.

Best wishes,

Mary Ann

On 14 November 2016 at 09:51,  <no-reply@wormbase.org> wrote:
> offline chat I am looking for instructions to navigate wormbase to find the
> gene sequence for c. elegans dpy-11 (e794). thank you.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0-9g-3
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0-9g-3
>
> This issue has been assigned ticket number: #5234. Follow progress on our
> issue tracker.
>
> Reported by: Pam (seshadp@sunysuffolk.edu)
> 14 Nov 16 09:53
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
