### ISSUE TITLE
visitor_name (visitor_email): hello I have a follo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5235]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): hello I have a followup question</br>visitor_name (visitor_email): http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=lethal&amp;focusTermId=WBPhenotype:0000062</br>visitor_name (visitor_email): That is where I am at</br>visitor_name (visitor_email): The question is what form these gene names are listed in... My end goal is to find the human homologs of the yeast essential genes</br>visitor_name (visitor_email): Sorry i accidentally deleted my last chat</br>visitor_name (visitor_email): I am on this page http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=lethal&amp;focusTermId=WBPhenotype:0000062</br>visitor_name (visitor_email): I am wondering what form the genes are listed in because I need to compare/ convert them. The end goal is to get the human homologs of the about 4,700 c. elegans genes listed</br>visitor_name (visitor_email): Thank you

**Reported by:** sier** (bbyt************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/drosophila_melanogaster/gene/FBgn0024956#0-9g-3">http://www.wormbase.org/species/drosophila_melanogaster/gene/FBgn0024956#0-9g-3</a>
**Browser:** Chrome 54.0.2840.71

**Comment by chris-grove** [comment]
Hi,


 The gene names listed on that page are the "public names" of the genes. You can import this list into WormBase ParaSite BioMart to get human orthologs. Here's a URL to replicate that type of query with the first list of 558 genes:


http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.production_name_1010|wbps_gene.default.feature_page.ensembl_gene_id|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.hsapiens_gene|wbps_gene.default.feature_page.hsapiens_gene_name|wbps_gene.default.feature_page.hsapiens_homolog_perc_id|wbps_gene.default.feature_page.hsapiens_orthology_type|wbps_gene.default.feature_page.hsapiens_homolog_perc_id_r1&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."act-5,aha-1,alg-1,alg-2,ama-1,apc-11,apa-2,arf-3,arx-2,arx-5,arx-7,asp-1,asp-3,asp-4,atl-1,baf-1,bec-1,ben-1,cap-2,ccf-1,cco-1,cct-1,cct-2,cct-4,cct-5,cct-6,cdc-6,cdk-7,cdt-1,ced-10,ceh-24,ceh-27,ceh-32,ceh-34,cep-1,chk-1,chk-2,cit-1.1,cit-1.2,cki-1,clp-1,col-35,col-48,cpf-2,cpl-1,cpr-1,cpr-3,cpr-6,cpz-2,crn-3,crn-5,cars-1,crt-1,csn-1,csn-5,cul-1,cyk-1,cyk-3,cyk-4,sig-7,dcr-1,dhc-1,dhs-16,div-1,dnj-17,dnj-21,cks-1,dpy-9,dpy-22,dre-1,dars-1,duo-1,dyn-1,egl-18,egl-27,elp-1,elt-1,elt-2,elt-6,end-1,epi-1,etr-1,fos-1,fbf-2,fars-1,ftt-2,gei-4,lin-66,snpc-4,gei-13,gei-17,gfi-2,gld-1,gld-3,gna-2,gob-1,gpc-2,gpr-1,gpr-2,grl-17,gsp-2,hbl-1,hcp-3,hcp-6,hel-1,his-7,C50F4.6,his-41,his-65,hlh-4,hmg-4,hrp-1,hars-1,hsf-1,hsp-1,hsr-9,icp-1,ifg-1,ify-1,ima-2,ima-3,imb-1,imb-3,xpo-1,gon-14,iars-1,iars-2,isw-1,kin-20,kars-1,lag-1,ldb-1,let-19,let-49,let-60,let-70,let-92,let-526,let-607,let-765,let-767,lev-11,lin-26,lin-40,lin-48,lin-53,lir-1,lmn-1,lars-1,lsm-1,ccar-1,lsy-2,mat-3,mcm-7,mec-7,mec-8,mek-2,mel-26,mel-28,mep-1,mog-4,mog-5,mpk-1,mtm-1,mtm-3,mtm-5,mtm-6,mtm-9,mua-3,mup-4,nas-7,ndx-6,nhl-1,nhr-6,nhr-23,nhr-25,nhr-49,nhr-80,npp-9,asns-1,nsf-1,ntl-2,ntl-3,nxf-1,odd-2,osm-11,pak-1,par-2,par-5,par-6,pas-3,pas-4,pas-5,pas-6,pat-9,pax-3,pbs-1,pbs-3,pbs-4,pbs-6,pbs-7,pha-1,pha-4,plk-1,pmk-2,pod-2,mdt-30,pri-1,prpf-4,prp-21,pry-1,swsn-1,ptc-1,ptc-3,ptr-1,ptr-2,ptr-4,ptr-6,ptr-10,ptr-16,puf-9,rab-1,rab-5,rab-7,rab-10,ran-1,ran-2,ran-3,rbx-1,rgr-1,rnp-4,rnp-6,rnr-1,rpl-2,rpl-39,rpn-1,rpn-3,rpn-6.1,rpn-8,rpn-11,rps-8,rpt-3,rpt-4,rpt-5,rpt-6,rsp-3,rsp-8,san-1,sap-49,sbp-1,sdc-2,sec-8,sec-23,sec-24.1,sex-1,sft-4,skn-1,skr-1,skr-2,skr-17,smo-1,snx-1,sop-3,sox-2,spd-2,spl-1,sqv-5,src-1,src-2,srp-5,srp-6,stl-1,taf-1,taf-5,sams-5,tba-2,tba-4,tbb-1,tbb-2,tbg-1,tim-1,tir-1,tra-1,tra-3,try-6,tsr-1,uaf-1,uaf-2,uba-1,uba-2,ubc-1,ubc-9,ubq-1,ufd-1,ula-1,unc-15,unc-37,unc-52,unc-59,unc-62,unc-98,unc-120,vab-3,vab-19,vbh-1,vha-1,vha-2,vha-3,vha-4,vha-5,vha-11,vps-26,vps-35,glp-4,wve-1,zyg-9,zyg-11,rfp-1,mdt-8,mdt-10,mdt-18,mdt-19,mdt-22,mdt-31,ssl-1,mys-1,B0250.3,B0250.7,dhcr-7,cdk-12,gck-4,cdc-48.1,atp-5,C07A9.2,stip-1,C15A11.2,C18B12.4,C25A1.5,nola-3,ruvb-1,prp-4,C36E8.1,C53A5.6,cdc-5L,D2030.4,lex-1,F11A10.5,F12F6.7,F13E6.2,F21D9.4,ehbp-1,mrpl-54,ncbp-2,lsy-22,capg-1,fasn-1,F35G12.11,rbpl-1,tat-5,copb-2,piki-1,F40F12.7,mfap-1,F43G9.12,F45G2.8,acaa-2,srpa-68,F57F5.1,math-33,dcn-1,mrpl-10,rnf-113,K01G5.10,ant-1.3,sec-12,K05C4.2,K07C5.6,K09E4.1,somi-1,let-522,M28.5,M117.3,sao-1,R186.3,R186.8,mrps-14,T01H3.2,snpc-3.4,sdz-30,zim-1,zim-2,zim-3,T08D2.7,ostb-1,T11G6.8,set-16,sna-2,mrps-18B,cyp-29A2,T19B10.2,T23D8.3,jun-1,T28D6.5,T28D6.6,nuo-6,rpb-11,W02D9.10,cacn-1,mtr-4,W09C5.8,nduf-7,agef-1,ash-2,Y19D2B.1,pap-1,Y38E10A.24,Y38H6C.14,xrn-1,Y40B1A.1,sptf-3,Y47D3B.1,Y48A6C.2,mcd-1,sta-1,Y51H4A.18,Y51H4A.19,rsr-2,Y57G11C.31,prp-6,Y62E10A.14,cyp-42A1,Y95D11A.1,zoo-1,exoc-8,Y111B2A.10,tpst-1,hut-1,ZK262.8,rev-1,clpp-1,ain-2,B0261.1,abi-1,ykt-6,sco-1,C01F1.3,C03A7.2,mrps-17,copd-1,sptl-1,C25H3.7,ntl-9,swd-2.2,hecd-1,C48B6.2,arp-11,C50F2.3,tag-294,eaf-1,snap-1,D2096.6,pole-2,pcyt-1,srpa-72,hmgr-1,usp-39,F09F9.4,cpsf-2,F13C5.2,bcl-11,F14D2.11,clec-1,hpo-18,F33D11.10,chtl-1,F37A4.6,F37C12.1,F37C12.14,ncbp-1,F41C3.4,smk-1,ceh-86,acs-1,lin-42,F52C6.3,F52C6.12,mnat-1,cct-3,mrpl-40,pmt-2,cir-1,F56C9.10,ddx-15,H12I13.2,sacy-1,K03B4.1,sdz-24,K08D12.3,K09H9.7,fah-1,K12H4.5,riok-1,R02F2.7,R05D3.8,R05D3.12,npp-21,htz-1,kbp-1,larp-1,R144.11,T07F8.4,mrpl-23,cct-7,knl-3,gen-1,sld-2,clec-178,T20B5.2,T21E12.3,T22H9.1,tat-4,T26A8.4,sna-1,W03F9.10,pig-1,W05G11.4,arx-4,ell-1,Y39G10AL.1,Y39G10AR.9,pcaf-1,Y47G6A.19,xpd-1,Y54E10BL.1,nprt-1,tag-262,Y55F3AM.3,Y65B4A.6,eel-1,clec-171,prp-31,use-1,nstp-3,pmt-1,ZK686.3,dve-1,W09G12.3,sor-1,C09G4.4,syd-9,ham-3,tag-267,cpsf-4,ZK1225.12,C25A1.16,Y48A6C.6,T24H7.8,sqst-5"&VISIBLEPANEL=resultspanel


If you want a list of all identifiers for your list of gene names, you can also use our SimpleMine tool:


http://www.wormbase.org/tools/mine/simplemine.cgi


This is discoverable under the "Tools" menu on any WormBase page. This will return a table of gene information for your list of genes, including the WBGene ID, the sequence name (e.g. "W02C12.3") and gene name (e.g. "hlh-30") among other data.


I hope that helps.


Chris
