### ISSUE TITLE
  Dear Wormbase,  I've got an array des...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5236]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase,  I've got an array designed from C. elegans genome assembly ws231.<br/>I'd like to upgrade the features to the most current assembly.  Should I be using ws255 PRJNA13758 or PRJNA275000/?  I'm confused as to how they differ.<br/>Thanks, Sajeev</p>

**Reported by:** Saje******** (saje***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by raymond91125** [comment]
Hi Sajeev,

PRJNA275000 corresponds to genome of the Hawaiian isolate strain CB4856 
whereas PRJNA13758 Bristol N2, the more common wild type isolate.

Cheers,

Raymond



On 11/14/2016 01:59 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Dear Wormbase, I've got an array designed from C. elegans genome 
> assembly ws231.
> I'd like to upgrade the features to the most current assembly. Should 
> I be using ws255 PRJNA13758 or PRJNA275000/? I'm confused as to how 
> they differ.
> Thanks, Sajeev
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5236. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5236>.
>
> Reported by: Sajeev Batra (sajeev_batra@affymetrix.com)
> 14 Nov 16 22:00
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
See <http://www.wormbase.org/species/c_elegans#3--10>, PRJNA275000 did 
not appear until WS250.

Cheers,

Raymond


On 11/15/2016 12:35 PM, Batra, Sajeev wrote:
>
> Hi Raymond,  Thanks for the quick response!
>
> So presumably the assembly ws231 is for the more common WT
>
> PRJNA13758 Bristol N2
> Is that right?
> Thanks, Sajeev
> ------------------------------------------------------------------------
> *From:* Raymond Lee <raymond@caltech.edu>
> *Sent:* Monday, November 14, 2016 2:19 PM
> *To:* Batra, Sajeev
> *Cc:* 
> reply@reply.github.com; 
> help@wormbase.org
> *Subject:* Re: [wormbase-help] How Do I ...?: Dear Wormbase, I've got 
> an array des... (Sajeev Batra)
> Hi Sajeev,
>
> PRJNA275000 corresponds to genome of the Hawaiian isolate strain 
> CB4856 whereas PRJNA13758 Bristol N2, the more common wild type isolate.
>
> Cheers,
>
> Raymond
>
>
>
> On 11/14/2016 01:59 PM, no-reply@wormbase.org wrote:
>> How Do I ...?
>>
>>   Dear Wormbase, I've got an array designed from C. elegans genome 
>> assembly ws231.
>> I'd like to upgrade the features to the most current assembly. Should 
>> I be using ws255 PRJNA13758 or PRJNA275000/? I'm confused as to how 
>> they differ.
>> Thanks, Sajeev
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #5236. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/5236>.
>>
>> Reported by: Sajeev Batra (sajeev_batra@affymetrix.com)
>> 14 Nov 16 22:00
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 
>> (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> ---
>> You received this message because you are subscribed to the Google 
>> Groups "WormBase: help" group.
>> To unsubscribe from this group and stop receiving emails from it, 
>> send an email to help+unsubscribe@wormbase.org 
>> <mailto:help+unsubscribe@wormbase.org>.
>
>
> -- 
> __
> Raymond Lee
> raymond@caltech.edu
> http://www.WormBase.org/
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687
>
> ------------------------------------------------------------------------
> This message/attachment is intended solely for the individual/entity 
> to whom it is addressed. It may contain confidential or legally 
> privileged information. Any unauthorized disclosure or copying is 
> prohibited and may be unlawful. If you believe you have been sent this 
> message in error, please notify the sender immediately and delete it 
> from your system.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
