### ISSUE TITLE
Unable to create a list in WormMine

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#5238]
When I try to create a list (even with just one gene) in WormMine, I just get the loading page but it never completes.  The spinner keeps spinning.
![screen shot 2016-11-15 at 10 42 22](https://cloud.githubusercontent.com/assets/6329861/20302732/619863da-ab20-11e6-8bd8-22821259277a.png)

**Comment by chris-grove** [comment]
@brucebolt 
Could you specify what your search criteria were? What data class and what species (if any) that was specified?

@nuin 
I may have mentioned this in another ticket, but there seems to be a problem with list upload in that it is not robust to varying search parameters. For example, you can use the example list of genes to upload that list of genes on the list upload page, but if you don't specify a species, the upload hangs indefinitely, as Bruce points out. If you try to upload the same list but specify C. elegans as the species, it works almost immediately. Conversely, if I try to upload a list of alleles, for example "e1370" and "mu86" without specifying a species, the upload is successful, but if I specify the species as C. elegans, I get no results (even though both alleles are C. elegans alleles).

**Comment by chris-grove** [comment]
@nuin 
Sorry, this is now fixed in the im-254 version of WormMine for genes.

The allele problem, where specifying the species yields no results, is still there. That can be made into a separate ticket.

**Comment by chris-grove** [comment]
@brucebolt 
Would you mind checking the same functionality on the latest WormMine dev site:

http://im-254.wormbase.org/tools/wormmine/begin.do

**Comment by brucebolt** [comment]
This is working on the dev site.

I was adding a list of gene names to the "Analyse a list" section on the page WormMine landing page.  Data type gene, with no species specified as there is nowhere to choose this on that page.

**Comment by chris-grove** [comment]
Fixed in im-259

http://im-259.wormbase.org/tools/wormmine/begin.do

Closing
