### ISSUE TITLE
expression pattern images missing

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5240]
the images for the expression profiling graphs seem to be missing here:
http://www.wormbase.org/species/c_japonica/gene/WBGene00134207

**Comment by draciti** [comment]
they look fine on staging, though, in case it helps

**Comment by sibyl229** [comment]
Hi @epaule @draciti I think Todd fixed the missing expression images. Before it ran out of disk space. Can we close this? Thanks!

**Comment by draciti** [comment]
yep, closing. thx
