### ISSUE TITLE
visitor_name (visitor_email): Hi, I am looking to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5241]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I am looking to place a mutation of my gene on the sequence. The paper describe the position of the mutation accordingly to a previous version of wormbase. Is it possible that I acces the genome browser of that previous version somehow</br>visitor_name (visitor_email): ?

**Reported by:** Muri** (mdes****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/operator">http://www.wormbase.org/tools/operator</a>
**Browser:** Chrome 54.0.2840.71

**Comment by raymond91125** [comment]
Hi Murial,

For WS230 or earlier, you may try <http://http://legacy.wormbase.org>. 
It may take a long time to load, for them to come out of hibernation. We 
are not supporting these versions, though.

Cheers,

Raymond

On 11/16/2016 08:23 AM, no-reply@wormbase.org wrote:
> online chat Muriel (mdesbois@scripps.edu): Hi, I am looking to place a 
> mutation of my gene on the sequence. The paper describe the position 
> of the mutation accordingly to a previous version of wormbase. Is it 
> possible that I acces the genome browser of that previous version somehow
> Muriel (mdesbois@scripps.edu): ?
>
> Submitted From:
>   http://www.wormbase.org/tools/operator 
> http://www.wormbase.org/tools/operator 
> <http://www.wormbase.org/http://www.wormbase.org/tools/operator>
>
> This issue has been assigned ticket number: #5241. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5241>.
>
> Reported by: Muriel (mdesbois@scripps.edu)
> 16 Nov 16 16:22
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
