### ISSUE TITLE
504 Gateway Time-out for wormbase.org

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#5242]
The problem was first noticed for http://www.wormbase.org/tools/ontology_browser. Then it seems to have propagated more generally.

**Comment by tharris** [comment]
This has been a recurring issue since Nov 1, manifesting to a greater extent the past two days. I can normally intervene before users are impacted but, you know, well, sleep.

**Comment by raymond91125** [comment]
The ontology browser is still unavailable at this time. I checked the servers on Caltech end and they seem to work properly.

**Comment by tharris** [comment]
where is the ontology browser supposed to be found?

**Comment by raymond91125** [comment]
ontology browser needs to access wobr.caltech.edu on port 8081

**Comment by raymond91125** [comment]
OK. my (machine's) bad. Apparently the network was working just good enough on our solr server to fool me that it was working yet bad enough for ontology browser to choke. And the general issue yesterday made thorough testing difficult. Sorry for the troubles. Ontology browsers and SObA are all working now.

**Comment by tharris** [comment]
Whew! For a second I thought I had inadvertently deleted some proxy-fu.  Happy to hear it is working again. :)
