### ISSUE TITLE
I got approval for two gene names by Tim Schedl in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5245]
*Help Desk query collected when no chat operators were online. Follow up required.*

I got approval for two gene names by Tim Schedl in August. Since we are currently revising a manuscript on one of the genes, could you give me an estimate, when the new names will appear in Wormbase?

 
Von: Schedl, Tim [mailto:ts@wustl.edu] 
Gesendet: Freitag, 19. August 2016 20:50
An: visitor_name &lt;visitor_email&gt;; genenames@wormbase.org
Betreff: Re: New name for M60.2

Hi Ralf,

Thank you for contacting WormBase for new gene class and gen association proposals.  

The following has been approved.  

New Gene class:
“endu” for “ENDonuclease, poly(U) specific”
 
New gene associations
K02A11.3 = endu-1 
M60.2 = endu-2 
 
Overview pages should indicate that K02A11.3 has a single XendoU domain and M60.2 has two XendoU domains, respectively.  
Thanks,

Tim

**Reported by:** Ralf*********** (baum******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000426#0c-e61-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000426#0c-e61-10</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by tuli** [comment]
Dear Ralf,

Thank you for writing to WormBase.

The update was made at the end of September and will be available in
release WS257. This will be on our live site at the end of Jan 2017.
You can see the release schedule here:
http://juancarlos.wormbase.org/about/release_schedule.

Best wishes,

Mary Ann



On 18 November 2016 at 10:27,  <no-reply@wormbase.org> wrote:
> offline chat I got approval for two gene names by Tim Schedl in August.
> Since we are currently revising a manuscript on one of the genes, could you
> give me an estimate, when the new names will appear in Wormbase? Von:
> Schedl, Tim [mailto:ts@wustl.edu] Gesendet: Freitag, 19. August 2016 20:50
> An: Ralf Baumeister <baumeister@celegans.de>; genenames@wormbase.org
> Betreff: Re: New name for M60.2 Hi Ralf, Thank you for contacting WormBase
> for new gene class and gen association proposals. The following has been
> approved. New Gene class: “endu” for “ENDonuclease, poly(U) specific” New
> gene associations K02A11.3 = endu-1 M60.2 = endu-2 Overview pages should
> indicate that K02A11.3 has a single XendoU domain and M60.2 has two XendoU
> domains, respectively. Thanks, Tim
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00000426#0c-e61-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00000426#0c-e61-10
>
> This issue has been assigned ticket number: #5245. Follow progress on our
> issue tracker.
>
> Reported by: Ralf Baumeister (baumeister@celegans.de)
> 18 Nov 16 10:28
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
