### ISSUE TITLE
  Hello! I can´t get access to the gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5247]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello!<br/>I can´t get access to the genetic maps. I have students tomorrow that have mapped different mutations to a location and are supposed to look for candidate mutations with help of the genetic map search tool. When will it be fixed?</p>

**Reported by:** Cata********** (cata********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14

**Comment by raymond91125** [comment]
Hi Catarina,

Apologies for the trouble. It seems that the Genetic Map Viewer is 
restored now. Please write us back with a bit more detail if it's not 
the case for you.

Thanks.

Raymond


On 11/20/2016 01:37 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   Hello!
> I can´t get access to the genetic maps. I have students tomorrow that 
> have mapped different mutations to a location and are supposed to look 
> for candidate mutations with help of the genetic map search tool. When 
> will it be fixed?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5247. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5247>.
>
> Reported by: Catarina Mörck (catarina.morck@cmb.gu.se)
> 20 Nov 16 09:36
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.2.14 
> (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
