### ISSUE TITLE
  How to download a research paper from...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5248]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How to download a research paper from worm base?</p>

**Reported by:** Ashw********* (pati****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by epaule** [comment]
we do not have papers to download at WormBase, but if you follow the links from the references, they should end on a Paper page with more information and potentially in the external links section should be potentially links to the original sources.
