### ISSUE TITLE
please cite ckb-3 somatic gonad expression
Kroetz ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5250]
*Help Desk query collected when no chat operators were online. Follow up required.*

please cite ckb-3 somatic gonad expression
Kroetz and Zarkower 2015
doi: 10.1534/g3.115.022517

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000513#0-g91ec-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000513#0-g91ec-10</a>
**Browser:** Safari 6.2.8

**Comment by draciti** [comment]
Dear Alexandra,

the ckb-3 somatic gonad expression from the paper you mentioned is already curated and available on WormBase.
Please see: https://www.wormbase.org/species/all/expr_pattern/Expr12527#021--10 <https://www.wormbase.org/species/all/expr_pattern/Expr12527#021--10>

You can also go to the Paper page and check the ‘Referenced’ widget:
https://www.wormbase.org/resources/paper/WBPaper00048690#03--10 <https://www.wormbase.org/resources/paper/WBPaper00048690#03--10>

Best,
Daniela

**Comment by draciti** [comment]
thanks for this quick reply, I meant more specifically:

this paper should be annotated in ckb-3 references (I see only 3 and not this one) and in overview there could be 1 sentence about somatic gonad expression. 

Alexandra

**Comment by draciti** [comment]
Thanks for the clarification Alexandra. I reopened the github ticket which will automatically alert our Paper curator to add the Paper-gene connection and our Concise description curator to update the description in the Overview.
Let us know if you have additional questions.
Best,
Daniela

**Comment by draciti** [comment]
From Alexandra:
great!

**Comment by vanaukenk** [comment]
Dear Alexandra,

Thanks very much for writing to WormBase.
I've made the appropriate gene-paper connections in our curation database and the paper will be listed in the bibliography for these genes starting with the WS258 WormBase release which will be available in early April of next year.

Best,
--Kimberly Van Auken

**Comment by rankishore** [comment]
Had already e-mailed Alexandra on 11.21.2016:
Hi Alexandra
If you would like to edit the concise description that shows in the ‘Overview’ widget on WormBase, to add any new data about ckb-3, please use this form
http://www.wormbase.org/submissions/community_gene_description.cgi

It will be added to the WS258 upload for WormBase, that will appear in a couple of months on the live website.

Thanks very much!
Ranjana Kishore
