### ISSUE TITLE
  Hi, I am writing to you in regards to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5251]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am writing to you in regards to our recent updated list of 2016 who might be interested in the Genomics industry and check if you would be interested in acquiring.<br/>We can provide you with complete contact details and verified email addresses of CEO's , Owners , VP's , Area managers, Buyers, Merchandise managers ,Production managers, Sales managers, Genomic scientist, Research scientist, Protein scientist, Bioinformatics analyst, Clinical Genomics Variant Scientist, Bio analytical Scientist, Research Associate , Testing Associates and all other key decision makers from all the industries dealing in genomics and much more.<br/>We provide updated list of healthcare and agricultural research organizations, biotechnology companies, pharmaceutical and diagnostics companies, agricultural and seed companies, government agencies and all for genomics services.<br/>If this is not your target industry, Kindly let me know your target criteria:<br/>Target Industry :<br/>Target Geography :<br/>Target Job Title :<br/>Thanking you in anticipation.<br/>Regards,<br/>visitor_name<br/>Marketing Manager</p><p>What were you doing? <br />&nbsp;&nbsp;Genomics industry database
</p>

**Reported by:** Shar********** (shar*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by epaule** [comment]
spam
