### ISSUE TITLE
Hello. I was wondering where I could get a sequenc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5252]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello. I was wondering where I could get a sequence for the CFTR gene. I need it for a project at school

**Reported by:** Iasi* (iasi**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/homo_sapiens/gene/ENSG00000001626#0-9g13-10">http://www.wormbase.org/species/homo_sapiens/gene/ENSG00000001626#0-9g13-10</a>
**Browser:** Chrome 54.0.2840.99

**Comment by raymond91125** [comment]
Human gene sequences may be obtained from GenBank 
https://www.ncbi.nlm.nih.gov/genbank/.

Cheers,

Raymond


On 11/21/2016 10:27 AM, no-reply@wormbase.org wrote:
> offline chat Hello. I was wondering where I could get a sequence for 
> the CFTR gene. I need it for a project at school
>
> Submitted From:
>   http://www.wormbase.org/species/homo_sapiens/gene/ENSG00000001626#0-9g13-10 
> http://www.wormbase.org/species/homo_sapiens/gene/ENSG00000001626#0-9g13-10 
> <http://www.wormbase.org/http://www.wormbase.org/species/homo_sapiens/gene/ENSG00000001626#0-9g13-10> 
>
>
> This issue has been assigned ticket number: #5252. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5252>.
>
> Reported by: Iasia (iasiabeh@gmail.com)
> 21 Nov 16 18:27
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
