### ISSUE TITLE
visitor_name (visitor_email): im unsure what gene ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5253]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): im unsure what gene ZK1225.1 for C. elegans does</br>visitor_name (visitor_email): and i do not know how to find out

**Reported by:** Chri***** (cmba*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00014235#0-9g-10">https://www.wormbase.org/species/c_elegans/gene/WBGene00014235#0-9g-10</a>
**Browser:** Chrome 54.0.2840.99

**Comment by raymond91125** [comment]
Hi Christian,

It appears that our information on this gene is limited to large scale 
gene expression analysis, including what conditions affect ZK1225.1 
expression. You might use http://www.textpresso.org/celegans/ to survey 
the literature to see if there's more information. We would be very 
interested to learn if we missed anything.

Thanks.

Raymond


On 11/21/2016 05:21 PM, no-reply@wormbase.org wrote:
> online chat Christian (cmbadillo@cox.net): im unsure what gene 
> ZK1225.1 for C. elegans does
> Christian (cmbadillo@cox.net): and i do not know how to find out
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans/gene/WBGene00014235#0-9g-10 
> https://www.wormbase.org/species/c_elegans/gene/WBGene00014235#0-9g-10 
> <http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00014235#0-9g-10> 
>
>
> This issue has been assigned ticket number: #5253. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5253>.
>
> Reported by: Christian (cmbadillo@cox.net)
> 22 Nov 16 01:23
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
