### ISSUE TITLE
Hi,

how can i know what is the longest protein pr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5257]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,

how can i know what is the longest protein predicted to be encoded by the unc -22

thanks.

**Reported by:** mage******** (alde*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3</a>
**Browser:** Chrome 51.0.2704.103

**Comment by raymond91125** [comment]
Hi Maged Aldeeb,

Unless I've misunderstood your question, otherwise the last column in 
the Sequences widget should answer your question perfectly.

Cheers,

Raymond


On 11/22/2016 12:12 PM, no-reply@wormbase.org wrote:
> offline chat Hi, how can i know what is the longest protein predicted 
> to be encoded by the unc -22 thanks.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3> 
>
>
> This issue has been assigned ticket number: #5257. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5257>.
>
> Reported by: maged aldeeb (aldeebm20@uww.edu)
> 22 Nov 16 20:13
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
