### ISSUE TITLE
  How do I cite a page on wormbase in A...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5258]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I cite a page on wormbase in APA?</p>

**Reported by:** Alli****** (alli******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14

**Comment by raymond91125** [comment]
Hi Alli,

I'm sorry, WormBase does not have a general support for APA. We might be 
able to provide additional information if you have questions about 
specific parts.

Cheers,

Raymond
