### ISSUE TITLE
Dear WormBase team,
I would like to receive your s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5266]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear WormBase team,
I would like to receive your support in my research. I wonder if we can chat anytime soon because I saw this option at your website. What I basically need is all of the information about the neuroreceptors like the one in the Google Document in http://www.wormatlas.org/NTRmainframe.htm which typically links to your database. The information in this document is sometimes confusing and not so updated, so I trust more what I find in WormBase. For example, in the case of the specific gen ser-1, I found very useful what is detailed at the bottom of the page http://www.wormbase.org/species/all/expr_pattern/Expr7825#021--10 (In "Details", specifically "Expressed in:" and then "Anatomy Term:"), so it will be great to have a list for all of the different neuroreceptors and their associated genes and/or proteins, explicitely vinculated to all of the neurons where they are present. If everything works fine in the near future, I can even contribute to add this new feature to your wonderful database, if it is not already present and I just did not know how to look carefully for it.
Thank you very much,
Jorge (visitor_email)

**Reported by:** Jorg****** (jorg*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/expr_pattern/Expr2710#021--10">http://www.wormbase.org/species/all/expr_pattern/Expr2710#021--10</a>
**Browser:** Firefox 50.0

**Comment by chris-grove** [comment]
In contact with user. Have resolved for now; he will write back if needed
