### ISSUE TITLE
Genetics widget under testing

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#5267]
Hi @tuli @tharris the Genetics widget on Gene page has been migrated to get data from Datomic. It's ready for testing on staging. Could you please help me check whether there's any discrepancy between staging and production? Thank you!

**Comment by tuli** [comment]
Hi @sibyl229 

I'm adding your email (with my responses) here for tracking purposes.

"One thing I noticed is the “Spice_site” and “readthrough" value in Protein effect column. I’m not sure if they are protein effect. If it’s correct, I will fix the staging code to replicate this behaviour. Here are examples on production: 
gk328459  under “Other alleles” on http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-4-10
gk179518 under “Other alleles” on http://www.wormbase.org/species/c_elegans/gene/WBGene00019459#0-4-9

Yes, these are correct. 

Some tags present in the molecular-change model weren’t populated in Datomic Database. Do you think the lack of data there is correct? Here they are:
- promoter
- noncoding-exon
-regulatory-feature
-genomic-neighbourhood"

These tags have certainly been added to the Gene tag within Variation objects e.g. http://www.wormbase.org/species/c_elegans/variation/WBVar00090136 (genomic_neighbourhood) 
& 
http://www.wormbase.org/species/c_elegans/variation/WBVar00601075 (promoter).

I add these are part of my manual Variation curation when e.g. the paper says the lesion affects the promoter, but the precise location of the lesion is not provided. These will not be mapped, but they should be in the database.  

@mgrbyte Do you know why these have not made it to Datomic?

**Comment by tuli** [comment]
..and I've had a look around and don't spot any problems. It looks good.

**Comment by sibyl229** [comment]
@tuli Thanks a lot @tuli ! 

@mgrbyte it's not a data problem. I noticed in @tuli 's example, the molecular change are annotated to the affected gene, I was only querying for affected predicted_cds. So it was my fault, don't worry about this.

**Comment by tuli** [comment]
@sibyl229 Great. The Molecular_change hash can be hard to track so I can see where the confusion arose.

**Comment by sibyl229** [comment]
@tuli just to double check the variations under Affects->Gene, Predicted_CDS, Transcript, and Pseudogene all need to be fetched for the Genetics widget?

**Comment by tuli** [comment]
Yes, that's right.

**Comment by sibyl229** [comment]
Hi @tuli there's nothing urgent. Just letting you know that I think the missing info under "Protein effect" column has been fixed. These following tags are being fetched and displayed in the protein effect column:
```
:molecular-change/missense 
:molecular-change/nonsense 
:molecular-change/frameshift 
:molecular-change/silent 
:molecular-change/splice-site 
:molecular-change/promoter 
:molecular-change/genomic-neighbourhood 
:molecular-change/regulatory-feature 
:molecular-change/readthrough 
```

These following tags are displayed in locations column:
```
:molecular-change/intron
:molecular-change/coding-exon 
:molecular-change/utr-5 
:molecular-change/utr-3 
```

Do you know of any tag that I missed here? 

For the **location column**, is it sufficient to pull molecular change data from ONLY Affects->CDS and Affects->Transcript (ignore Affects->Gene and Affects->Pseudogene)?

For the **protein effects column**, is it sufficient to pull molecular change data from ONLY Affects->CDS and Affects->Gene (ignore Affects->Transcript and Affects->Pseudogene)?

**Comment by sibyl229** [comment]
Hi @tuli the Genetics widget (currently on staging) will go live with WS256 website release soon, probably this weekend if nothing goes wrong. If you notice any new problem, please let me know. 

I still have two more questions:

For the **location column**, is it sufficient to pull molecular change data from ONLY Affects->CDS and Affects->Transcript (ignore Affects->Gene and Affects->Pseudogene)?

For the **protein effects column**, is it sufficient to pull molecular change data from ONLY Affects->CDS and Affects->Gene (ignore Affects->Transcript and Affects->Pseudogene)?

Thank you @tuli

**Comment by tuli** [comment]
@sibyl229  I'll look at this first thing tomorrow.

**Comment by sibyl229** [comment]
@tuli Great, thanks!

**Comment by tuli** [comment]
@sibyl229 

There are Molecular_change curations associated with objects other than CDSs and Transcripts. 

For example I will manually curate the Molecular_change of a Gene when I know that I have not been able to curate the molecular details (flanking sequences and Type_of_mutation)

In CurrentDB there are 291 such Variation objects BUT only 126 of these DO NOT also have Predicted_CDS curation ie I believe only these 126 objects have novel information. 

e.g. http://www.wormbase.org/species/c_elegans/variation/WBVar00089587

For the Location column I would like you to pull out molecular change from Gene. nb there may be some redundancy due to historical changes in allele curation but the numbers of affected Varations is small so I think it will be OK. 

There are no Pseudogenes with associated Molecular_change curation. 

For the protein affects column I think you should pull molecular change data from Transcript (see e.g. http://www.wormbase.org/species/c_elegans/variation/WBVar00000007  which has Molecular_change info associated with the Transcript). 

I hope this answers your questions.

**Comment by sibyl229** [comment]
Hi @tuli Thank you very much. Just to clarify, say for location column, it's to pull molecular change from ONLY Gene, right? Not Gene in addition to CDS and transcript? 

The code removes redundancy in the Location column and Protein effect column. So you don't need to worry about that. Neither is data fetching speed much of a concern for this. It's more for making sure the code does what is supposed to do and nothing more.

**Comment by tuli** [comment]
@sibyl229 

Other way - please pull Gene AND CDS AND Transcript! 

Glad you checked. 

Great that redundancy is removed.

**Comment by sibyl229** [comment]
Hi @tuli makes sense! Thank you

**Comment by tuli** [comment]
:thumbsup:

**Comment by mgrbyte** [comment]
@sibyl229 wonder if this is done now?

**Comment by sibyl229** [comment]
Yup, this is done. Thanks @mgrbyte
