### ISSUE TITLE
  How can i submit the genome project d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5270]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can i submit the genome project data to wormbase</p>

**Reported by:** Bo L** (lb_b**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by raymond91125** [comment]
HI Bo Liu,

We suggest that you submit your data to public repositories and we have 
standard pipeline to pick them up there.

Thanks.

Raymond
