### ISSUE TITLE
53938466...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5271]
*Help Desk query collected when no chat operators were online. Follow up required.*

53938466

**Reported by:** reni************ (reni*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001570?from=http://www.wormbase.org/db/gene/gene?name=WBGene00001570;class=gene#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001570?from=http://www.wormbase.org/db/gene/gene?name=WBGene00001570;class=gene#0-9g-3</a>
**Browser:** Chrome 28.0.1500.94

**Comment by raymond91125** [comment]
nothing wrong reported.
