### ISSUE TITLE
I am looking for a strain with trimethyl Histone3 ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5272]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking for a strain with trimethyl Histone3 kysine 4 protein tagged to gfp

**Reported by:** Tani** (tani**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/strain/ABR7#023761--10">http://www.wormbase.org/species/c_elegans/strain/ABR7#023761--10</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by raymond91125** [comment]
If you search for the gene name under Strains, you could see if any 
carries GFP.

Raymond
