### ISSUE TITLE
  From one of my hits WBGene00044919 th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5273]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;From one of my hits WBGene00044919 there is no sequence known. The description is:  Remarks:<br/>[120315 mt3 pad] This gene was previously the uncloned version of mig-31<br/>Does that mean it now encodes mig-31(and should I use that sequence)? or should I look for the sequence on modENCODE?<br/>Kind regards,<br/>visitor_name </p>

**Reported by:** Anna********** (a.eb****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by raymond91125** [comment]
Hi Annabel,

It appears that WBGene00044919 was mig-31's other name and then mig-31 
merged into vab-10 (WBGene00006876).

Hope that solves the problem for you.

Cheers,

Raymond

**Comment by Paul-Davis** [comment]
For dead genes that have been merged into another gene, should we provide the merged into data in the overview to avoid user confusion as highlighted in this ticket?

![mig-31](https://cloud.githubusercontent.com/assets/717707/20631333/ce0fb9fe-b32d-11e6-8976-729710456b57.png)

**Comment by tuli** [comment]
:thumbsup:

**Comment by sibyl229** [comment]
Hi @Paul-Davis the problem with Merged into gene is now displayed for dead gene: http://staging.wormbase.org/species/c_elegans/gene/WBGene00044919#0--10 Could you doublecheck please? Thanks!

**Comment by Paul-Davis** [comment]
Great @sibyl229 no doubting that :) 

+1 from Gary as well.
