### ISSUE TITLE
Hi,


is it possible to get the 'Overview' text fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5281]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,

is it possible to get the 'Overview' text for a certain gene programmatically? E.g. for gene ZC308.4, I'd like to get the description : 'RNA sequencing and microarray studies indicate that ZC308.4 is regulated by Methylmercury hydroxide, Rotenone, Manganese chloride, Progesterone, Testosterone, Resveratrol, Deoxyglucose, Atrazine, Cadmium, Hydrolyzable Tannins, Humic substances, Paraquat, and Sirolimus; tiling array and RNA sequencing studies indicate that ZC308.4 is enriched in the hypodermis, gon_male_dtc posterior, gon_male_dtc anterior, Z1.p, Z4.a, Z4, and Z1 and in the BAG neurons.' which is shown for the manual seach for this gene.

**Reported by:** Chri***** (chri*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00022586#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00022586#0-9g-3</a>
**Browser:** Firefox 50.0

**Comment by raymond91125** [comment]
Hi Christian -

Briefly, use the developer tools of your browser to explore the underlying API. 

You can easily make REST requests to fetch the Overview widget in JSON. 

I can expand more if you need additional help, or I will add additional detail here when back at my desk on Monday.  

Todd
