### ISSUE TITLE
  Dear Sir/Madam, In my transcription s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5282]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam,<br/>In my transcription sequencing data (which we annotated using a data-set we got from Wormbase) a RIT gene popped up. From literature I assumed it encodes a long non-coding RNA. However, I can not find the RIT back on wormbase. I tried looking for it on modENCODE (but without a location on the genome, it is hard to pinpoint on a non-gene encoding sequence). Also, I have tried to contact modENCODE, but the email was somehow undeliverable (probably because the contact information on the site is outdated). I did find a list (gtf file) including the linc-RNA# and chromosome positions (which I can use to find back the genomic sequence of my RNA). However, I only have the RIT code (RIT2M.1898). Is there a conversion table telling me which RIT is which lincRNA? Or did I misinterpret something and is the RIT annotation used for another type of genomic fragment? <br/>Thanks in advance,<br/>Kind regards,<br/>visitor_name</p>

**Reported by:** Anna********** (a.eb****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by gw3** [comment]
Hi Annabel,

I did some work on the modENCODE predicted transcripts some years ago.
I will have a look at my records and see if I can find the corresponding 
WormBase data.

Gary Williams

**Comment by gw3** [comment]
Annabel,

'RIT2M.1898' appears to be from the original 2010 release of modENCODE data.
The ID appears to have become a bit abbreviated, it should be 
'Aggregate_1003_RIT2M.1898.T1'.
No other data in modENCODE has an ID that includes 'RIT2M.1898', so I am 
confident that this is the data that you found.

The modENCODE data for 'Aggregate_1003_RIT2M.1898.T1' is an exact match 
to the WormBAse coding gene F49C5.12.

You were expecting to find a linc-RNA gene, so if you could let me know 
the chromosome positions and the WormBase release I can see if there is 
a linc-RNA at your position.

Gary
