### ISSUE TITLE
I need help writing an essay on C.elegans please s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5283]
*Help Desk query collected when no chat operators were online. Follow up required.*

I need help writing an essay on C.elegans please send help

**Reported by:** Mega********* (Nspw********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide#3--10">http://www.wormbase.org/about/userguide#3--10</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by raymond91125** [comment]
Hi Megan,

Thank you for contacting WormBase. Unfortunately, we do not currently 
offer essay-writing help. If you have specific questions about accessing 
information on our site, we'd be happy to help.

Good luck.

Raymond


On 11/28/2016 07:41 AM, no-reply@wormbase.org wrote:
> offline chat I need help writing an essay on C.elegans please send help
>
> Submitted From:
>   http://www.wormbase.org/about/userguide#3--10 
> http://www.wormbase.org/about/userguide#3--10 
> <http://www.wormbase.org/http://www.wormbase.org/about/userguide#3--10>
>
> This issue has been assigned ticket number: #5283. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5283>.
>
> Reported by: Megan Burnley (Nspwhior@2015.ljmu.ac.uk)
> 28 Nov 16 15:43
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
email to user bounced.
