### ISSUE TITLE
  What's the current procedure to reque...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5284]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;What's the current procedure to request a gene name change?</p>

**Reported by:** Javi*********** (javi***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Comment by tuli** [comment]
Dear Javier,

Thank you for writing to WormBase.

Changes in gene name need to be approved by Tim Schedl.
Please submit your request using the form here:
http://www.wormbase.org/submissions/gene_name.cgi


Best wishes,

Mary Ann

On 28 November 2016 at 15:55,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   What's the current procedure to request a gene name change?
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5284. Follow progress on our
> issue tracker.
>
> Reported by: Javier Irazoqui (javierira@gmail.com)
> 28 Nov 16 15:55
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/54.0.2840.98 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by raymond91125** [comment]
@tuli Efficiency!

**Comment by tuli** [comment]
:muscle:
