### ISSUE TITLE
Correction to error in worm base: cdk-7(ax224)

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#5285]
To whom it may concern; 

Julie Arhinger informed me of a mistake in the reporting of one of our alleles: cdk-7(ax224) 

We erroneously referred to this mutation in Wallenfang et al., 2002 as C280T. The correct change is C280Y. 

The ax224 mutation is a change from TGT to TAT  (Cysteine to Tyrosine).  

Thank you 

Geraldine
2016/11/28 02:56 PM PST

**Comment by tuli** [comment]
Dear Geraldine,

Thank you for writing to WormBase. I have corrected the ax224 allele
as requested. The update will be available in release WS258 of
WormBase.

Best wishes,

Mary Ann

On 28 November 2016 at 22:56, Geraldine Seydoux <gseydoux@jhmi.edu> wrote:
> To whom it may concern;
>
> Julie Arhinger informed me of a mistake in the reporting of one of our
> alleles: cdk-7(ax224)
>
> We erroneously referred to this mutation in Wallenfang et al., 2002 as
> C280T. The correct change is C280Y.
>
> The ax224 mutation is a change from TGT to TAT  (Cysteine to Tyrosine).
>
> Thank you
>
> Geraldine
>
>
>
> —
> Geraldine Seydoux, Ph. D.
> Sheldon Professor in Medical Discovery
> Dept. of Molecular Biology and Genetics / PCTB 706
> Johns Hopkins University School of Medicine
> 725 N. Wolfe Street
> Baltimore MD 21205 USA
> Tel: 410-6144622
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
