### ISSUE TITLE
Anatomy attribute nested under Life Stage in Expression Pattern objects in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5289]
Whereas the Life Stage and Anatomy attributes of expression pattern objects are siblings in the ACEDB data model, the model browser of WormMine is showing the Anatomy attribute as a child of Life Stage, which I think may be contributing to problems with anatomy associations with Expr objects (see issue #4831 ).

When I open up the QueryBuilder for the expression pattern class, I see this:

![screen shot 2016-11-29 at 1 22 02 pm](https://cloud.githubusercontent.com/assets/611382/20729463/e554e6aa-b636-11e6-9ee2-3a6f430772fb.png)

with no anatomy attribute immediately visible. Only when I expand the Life Stages node do I see the Anatomy Terms attribute:

![screen shot 2016-11-29 at 1 22 09 pm](https://cloud.githubusercontent.com/assets/611382/20729485/060ba5fa-b637-11e6-866d-0b98643d60f3.png)

**Comment by nuin** [comment]
Hi Chris, sorry to come to this ticket so late. I will double check, but there are a number of problems with data loading in some of these classes. We had a problem before with protein information, that is coming from a different source than the one it was supposed to be.

**Comment by chris-grove** [comment]
@nuin 
OK, thanks!

**Comment by nuin** [comment]
Hi Chris, I am still checking with Todd and Scott how to extract the data. Sorry for the delay.

**Comment by chris-grove** [comment]
@nuin  OK, thanks for the update!

**Comment by nuin** [comment]
I have a new build with the data added, but it seems that the anatomy term is still buried under life stage. I will double check things.

**Comment by chris-grove** [comment]
@nuin 
OK thanks

**Comment by nuin** [comment]
Hi @chris-grove this is what I have now. I will keep the build on for the next day or two.

Let me know.

![screen shot 2017-05-17 at 1 43 32 pm](https://cloud.githubusercontent.com/assets/6273/26172840/f337dade-3b06-11e7-95bb-acd623bc7cbb.png)

**Comment by chris-grove** [comment]
@nuin 
Yes!! Now it's giving me correct results for the data that is available (this isn't a full build, right?).

**Comment by nuin** [comment]
This is a small build. I hope to get strains in the system before running a full build. I keep you posted, glad that it worked.

**Comment by draciti** [comment]
That is AWESOME! thanks Chris and Paulo for your efforts!!

**Comment by chris-grove** [comment]
OK this is fixed in im-259. The only remaining issue with regards to this is that the template query "Gene --> Expression Pattern" needs to be updated to point to the correct anatomy terms (to the terms nested directly under Expression Pattern, not the ones nested under Life Stage). I'll create a separate ticket for that.
