### ISSUE TITLE
  Hi there, I am looking to get ahold o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5293]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there,<br/>I am looking to get ahold of all the rRNA gene annotations for C. briggsae. They don't seem to be in the GFF. Does wormbase have them annotated elsewhere or in an older version of the genome?<br/>thanks!<br/>Asher</p>

**Reported by:** Ashe******** (ashe******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by scottcain** [comment]
I'm working on this--I'm going to send him a file with the rRNA GFF entries in it.

**Comment by scottcain** [comment]
I sent this email to the requester:

Hi Asher,

Attached is a small GFF file with the rRNA genes from C. briggsae release WS255.  Please let me know if you think anything is missing.  I found this in the released GFF with this command (if you wanted to know :-)

gzip -dc c_briggsae.PRJNA10731.WS255.annotations.gff3.gz |grep -A 1 rRNA > c_briggsae.WS255.rRNA.gff3 

Good luck,

Scott

[c_briggsae.WS255.rRNA.gff3.zip](https://github.com/WormBase/website/files/625628/c_briggsae.WS255.rRNA.gff3.zip)
