### ISSUE TITLE
  Hello! I found there is error related...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5297]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello! I found there is error related to describe qx304,an allele of cpl-1 gene. It is  point mutation, but not deletion mutant. In qx304 mutants, the start codon ATG of the cpl-1 gene was mutated to ATA, leading to a predicated translation initiation at methionine 52 relative to the wild-type protein; this results in a CPL-1 protein lacking the first 51 amino acids, according to my research (Xu M, Mol Biol Cell 2014;25(13):2071-2083). Please correct the error. Thanks!</p>

**Reported by:** Meng*** (xmen****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by tuli** [comment]
Dear Meng Xu,

Thank you for writing to WormBase and bringing this mistake to our attention.

I have corrected the molecular details of the qx304 allele as
requested. The update will be available in release WS258 of WormBase.

Best wishes,

Mary Ann

On 5 December 2016 at 08:34,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hello! I found there is error related to describe qx304,an allele of cpl-1
> gene. It is point mutation, but not deletion mutant. In qx304 mutants, the
> start codon ATG of the cpl-1 gene was mutated to ATA, leading to a
> predicated translation initiation at methionine 52 relative to the wild-type
> protein; this results in a CPL-1 protein lacking the first 51 amino acids,
> according to my research (Xu M, Mol Biol Cell 2014;25(13):2071-2083). Please
> correct the error. Thanks!
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5297. Follow progress on our
> issue tracker.
>
> Reported by: Meng Xu (xmeng@genetics.ac.cn)
> 05 Dec 16 08:32
>
> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/50.0.2661.102 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
