### ISSUE TITLE
  Hi wormbase people! I want to downloa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5298]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi wormbase people!<br/>I want to download some data from wormbase, but I'm not familiar with perl, so I'm not exactly crazy about using the API. <br/>Basically, I want to pull the expression pattern (list of genes reportedly expressed in that cell type) for a given anatomy term, then do some stuff with it in a script. I know I can do this manually for the anatomy terms I'm interested in, but that would be time consuming (and boring), and would only be a "freeze" of wormbase info. If I were to be able to call on the database and get information on the fly (i.e. for that script I'm thinking of writing), then it would be always updated. <br/>Anyways, I'm working on learning the wormbase perl API, but in the meantime I'm wondering if there's an easier way. I'd like not to have to write my script in a language I don't know (yet).<br/>Thanks in advance guys!<br/>-dylan</p>

**Reported by:** Dyla****** (dpr2****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Dylan,


Thanks for writing to WormBase.


Have you looked at the anatomy association file on the WB ftp site to see if that would be suitable for your needs?  The anatomy association file is a tab-delimited file of expression data produced with every WB release.  The file for the WS255 release is currently available here:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS255/ONTOLOGY/anatomy_association.WS255.wb

Let us know if you have any questions about the file or if you'd like any additional help.


Best,

--Kimberly Van Auken

**Comment by vanaukenk** [comment]
From Dylan:

Oh that’s great! I suppose I didn’t look hard enough around the ftp site. 

You’re the best! :)

-dylan
