### ISSUE TITLE
  How do i register a acount? I can't f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5299]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do i register a acount? I can't find where to register.</p>

**Reported by:** Wei ** (lang*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Wei Ma,

Thank you for writing to WormBase.

You can register an account by clicking on the 'Login' text in the upper right corner of the home page. 

You will then be prompted to sign in with either a Google or Facebook account, as WormBase currently only allows user authentication via Google or Facebook. 

Please let us know if you have any additional questions about, or problems with, registering at our site.

Best,
--Kimberly Van Auken
