### ISSUE TITLE
rewrite FPKM field with data from Datomic

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#5301]
Hi @draciti @gw3 ,

I'm in the process of rewriting Expression widget for genes and transcripts to use Datomic instead. I will need some help from you to answer some questions and test the widget (once it's done). Also, if you there's anything you want changed in the Expression widget, it's also a good time to let me know.  Thanks!

Currently the Expression widget on Transcript page has a lot of data coming from the associated gene (`Transcript->Gene`). I think several expression pattern tables and the rnaseq table are done this way. I believe this is a decision made earlier. I wonder if it still holds, because I now see rnaseq objects linked directly to the Transcript object.

**Comment by sibyl229** [comment]
Hi @gw3 a while back, you created a look up table for the name of a study, that weren't in ACeDB at that time. Can I get the info from the database now? Here is a part of the table:

> PRJNA75295	Hillier_modENCODE
> SRP016006	Thomas_Male_Female_comparison
> PRJNA75295	Hillier_modENCODE
> PRJNA104933	Uyar_Briggsae_transcriptome
> SRP016006	Thomas_Male_Female_comparison

**Comment by draciti** [comment]
Absolutely, thanks sibyl.
there is this ticket wrt changes to the widget: #5070. It's a full revamp of the top portion of the widget.
Once you start working on it we can communicate via skype if it makes things easier.
thanks
d

**Comment by sibyl229** [comment]
Hi @draciti sure, we can do that. For my question, do you think the Expression widget on Transcript should get all the info from its corresponding Gene?

**Comment by gw3** [comment]
Hi @sibyl229 

There is currently RNASeq expression data on both the Gene and Transcript objects.
We may stop making the Transcript expression data because we plan to change the way we run the RNAseq pipeline.

You should continue to use the Gene RNASeq expression data.

**Comment by gw3** [comment]
Hi @sibyl229

What was the look-up table for?

The data is in the database now:

SRP016006 (elegans)
PRJNA75295 now has the ID: SRP006033 (briggsae)
PRJNA104933 now has the ID SRP011366 (briggsae)

**Comment by sibyl229** [comment]
Hi @gw3 Thanks a lot!

The lookup table is to give the project label in this table:
![screen shot 2016-12-07 at 11 16 14 am](https://cloud.githubusercontent.com/assets/1753893/20976001/215391f4-bc6f-11e6-961d-8e30491db024.png) According to what you said, I guess I should fetch the Project Tag and get its title?

Is there any more PRJNA- prefixed projects in the database now? In the web code, these PRJNA prefixed projects link to BioProject external url instead of the NCBI trace. I wonder if this case is still necessary.

There is another piece of hard-coded dataset in the code. I think it's for experimental conditions used in the figure. It looks like this:
```
		 SRX092477 => ['0','polyA', 'N2_EE_50-0'],
		 SRX092478 => ['0','polyA', 'N2_EE_50-0'],
		 SRX099902 => ['0','polyA', 'N2_EE_50-0'],
		 SRX099901 => ['0','polyA', 'N2_EE_50-0'],
		 SRX103649 => ['0','polyA', 'N2_EE_50-0'],
```
Does this info exist in the database?

Thanks!

**Comment by gw3** [comment]
Hi @sibyl229

There should not be any Analysis of Condition objects using a PRJNA- prefixed Project name in the database now.

The hard-coded data for making the FPKM expression graphs doesn't exist in the database.
This data will not change. It is static.
There are not really any suitable tag fields in the Analysis object that could hold this data.
It could be squeezed into the Database tag, I guess, or we could have a model change.

Gary

**Comment by sibyl229** [comment]
Thank you @gw3 . One more thing, previously the "Project" column links to ncbi pages, now that RNASeq_Study.SRP***** exists as a WormBase page, do you think it makes sense to link to the WormBase page instead? 

For the static dataset, if you think there is no chance it will change, and its only use is to create the graph (not be looked up with query or displayed else where), I will leave it hard coded in the code that creates the graph.

**Comment by gw3** [comment]
Hi @sibyl229,

Yes, it makes sense to link the "Project" column to the WormBase page instead.

For the static dataset, there is no chance it will change. It is OK to leave it as hard-coded.

**Comment by sibyl229** [comment]
Hi @gw3 , sorry, this has been a long while. The fpkm related display on Gene page is getting data from Datomic now. Could you take a look for me please? Thank you!

**Comment by gw3** [comment]
Hi @sibyl229, Yes, this looks good, thanks.

**Comment by sibyl229** [comment]
Thanks @gw3 for checking! Closing
