### ISSUE TITLE
  I opened a new worm lab at Lancaster ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5302]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I opened a new worm lab at Lancaster University. I wrote to the email I found on wormbase to get my lab code, strain and allele codes, but received no answer. Do you have any alternate contacts or ways for registering a new lab?</p>

**Reported by:** Alex*************** (a.be***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; .NET CLR 1.1.4322; rv:11.0) like Gecko

**Comment by tuli** [comment]
Dear Alexandre,

Thank you for writing to WormBase. I have checked my email and do not
see a message from you, so maybe it got lost in our system somewhere.
Can you tell me which email address you used?

I have cc'ed this reply to Tim Schedl who is responsible for assigning
lab/strain and allele codes and you will hear from him very soon.

I apologise for any inconvenience.

Best wishes,

Mary Ann

On 7 December 2016 at 11:51,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   I opened a new worm lab at Lancaster University. I wrote to the email I
> found on wormbase to get my lab code, strain and allele codes, but received
> no answer. Do you have any alternate contacts or ways for registering a new
> lab?
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5302. Follow progress on our
> issue tracker.
>
> Reported by: Alexandre Benedetto (a.benedetto@lancaster.ac.uk)
> 07 Dec 16 11:54
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727;
> .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C;
> .NET4.0E; .NET CLR 1.1.4322; rv:11.0) like Gecko
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Tim addressing.
