### ISSUE TITLE
"gmap" and "landmark" duplicates of genes in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5306]
This issue came up while addressing issue #5004 

There are duplicate copies of genes in im-254 WormMine such that the only identifying information is a gene ID of the form "gmap:<gene name>" and "landmark:<gene name>". For example if you run the following query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A or B">
  <constraint path="Gene.primaryIdentifier" code="A" op="CONTAINS" value="gmap"/>
  <constraint path="Gene.primaryIdentifier" code="B" op="CONTAINS" value="landmark"/>
</query>`

this returns ~27,000 genes of this form. These are distinct from the corresponding genes with the <gene name> in the Gene Name field. This can be most clearly seen when running the Chromosomal Interval --> Genes template query with the default parameters, which returns a list of genes in the specified interval:

![screen shot 2016-12-09 at 11 07 19 am](https://cloud.githubusercontent.com/assets/611382/21062670/b40dfff0-be06-11e6-930c-e251fc13fc99.png)

I don't know where these "gmap" and "landmark" gene objects are coming from but they will need to either be removed or merged with their corresponding gene object with proper IDs, e.g. "WBGene00000001"

**Comment by scottcain** [comment]
@nuin I am pretty sure the gmap and landmark features are coming from the GFF files--they are there specifically to allow GBrowse to display some information in the browser, but are not needed by anybody else (I think--I know that's true for landmark, not so sure about gmap, but the gmap entries definitely represent redundancy).  They should probably be removed via preprocessing the GFF file.  You could filter on "\tlandmark\t" and "pmap_position\t" to catch items in the second column that aren't needed.

**Comment by nuin** [comment]
Thanks @scottcain and @chris-grove. I will check it soon.

**Comment by nuin** [comment]
Hi @chris-grove, please take a look at the newest build. This issue seems resolved.

**Comment by chris-grove** [comment]
@nuin 
Yes, the "gmap" and "landmark" entries are now gone. Thanks!
