### ISSUE TITLE
Genes showing up in triplicate when returning genes in a chromosomal interval in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5307]
When running the Chromosomal Interval --> Genes template query in WormMine, with the following query:

`<template name="genes_within_a_chromosomal_interval" title="Chromosome Interval --&gt; Genes" comment="">
  <query name="genes_within_a_chromosomal_interval" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.locations.locatedOn.primaryIdentifier Gene.locations.start Gene.locations.end Gene.organism.name" longDescription="Returns all genes within a specified chromosomal interval in a given species" sortOrder="Gene.locations.end asc" constraintLogic="A and B and C and D">
    <constraint path="Gene.locations.locatedOn.primaryIdentifier" code="A" editable="true" op="=" value="X"/>
    <constraint path="Gene.locations.start" code="B" editable="true" op="&gt;" value="1000000"/>
    <constraint path="Gene.locations.end" code="C" editable="true" op="&lt;" value="1500000"/>
    <constraint path="Gene.organism.name" code="D" editable="true" op="=" value="Caenorhabditis elegans"/>
  </query>
</template>`

it appears that each gene is showing up in three identical rows in the output, as such:

![screen shot 2016-12-09 at 11 06 36 am](https://cloud.githubusercontent.com/assets/611382/21062799/4f798b4e-be07-11e6-9486-9bbb47ff8ae1.png)

It isn't clear why 3 rows are showing up for each gene.

**Comment by nuin** [comment]
@chris-grove I have an updated build on im-257 and it seems that the triplicates are gone. Of course there are still some bogus entries, but the issue of this ticket seems resolved. 

Due to the fact that this is a limited dataset build, we might have consequences down the road on data merge and we will need to test more when time comes. Please let me know.

**Comment by chris-grove** [comment]
@nuin 
Yep, looks good. Thanks Paulo!

**Comment by nuin** [comment]
Thanks a lot @chris-grove
