### ISSUE TITLE
  Hi Wormbase, I use the wormbase API t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5309]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi Wormbase,<br/>I use the wormbase API to retrieve information from the interactions, overview, concise_description, provisional_description from a bunch of genes.<br/>Since a few days I get this error when retrieving interactions or overview. <br/>During retrieving I get or the overview or the interactions and sometimes none.<br/>I don't understand why it worked always fine. I hope you can help me.<br/>Server Error: 500 at rest/field/gene/WBGene00044322/interactions<br/>Error Message:<br/>Caught exception in WormBase::Web::Controller::REST->field "cannot locate template interactions.tt2 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 1646."</p><p>What were you doing? <br />&nbsp;&nbsp;Retrieving data with the wormbase API</p>

**Reported by:** diti*************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.1000 Chrome/30.0.1599.101 Safari/537.36

**Comment by vanaukenk** [comment]
Hi,


Thank you for writing to WormBase.


Our web development team will take a look at this issue and get back to you as soon as possible.


Best,

**Comment by sibyl229** [comment]
> Sorry to hear that your REST API query stopped working. I guess you expect JSON in the response? Based on the error message, looks like the request is treated as one for HTML instead. Could you try to pass in the content-type application/json into your request (either as header or a parameter in the URL) for now? Such as:
> curl http://api.wormbase.org/rest/field/gene/WBGene00044322/interactions -H "Content-Type:application/json"
> Or
> curl http://api.wormbase.org/rest/field/gene/WBGene00044322/interactions?content-type=application/json
> I’m a bit puzzled that it used to work. Let me check.
>Please let me know if you have more questions.

**Comment by Jehudith** [comment]
Hi sibyl229,

Thanks for answering me soon.
Yes I expect JSON and I made a Base class which checks the content type.  I always tested my code in Advanced REST client and I get there the same error while content-type: application/json.
Before it wasn't like that. I made this datafetcher in januari and up till now it worked great.

Hope you could me, sorry for the trouble

Here is the base class , its in python 3.3.5

(Other classes are responsible for getting the overview and interactions)
-------------------
import requests
from config import *


class BaseRequestHandler(object):
    """

    request client,get, request sturen naar een url
    """

    def __init__(self):
        super(BaseRequestHandler, self).__init__()

    def get(self, url):
        """
        make request, and get response r
        Get the url (from wormbaserequesthandler), try decode into json.
         """
        try:
            #retrieve data in json format
            headers = {"content-type": "application/json",
                       "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) "
                                     "Chrome/41.0.2228.0 Safari/537.36"}

            r = requests.get(url, headers=headers)
        except:
            if DEBUG_MODE:
                #request failed
                print("BaseRequestHandler: get(request) failed")
            return None
        if not self.status_code_ok(r):
            return None
        return self.get_json(r)

    def status_code_ok(self, r):
        """
        the GET Request will response with a status number (standard response for successful HTTP requests)
        (the number is an entity corresponding to the request resource)
        :param r: json response (format)
        :return: True
        """
        #successful HTTP request
        if not r.status_code == 200:
            if DEBUG_MODE:
                #gives status
                print("BaseRequestHandler: status_code not 200 but:", r.status_code)
                print("BaseRequestHandler: Request returned:", r.text)
            return False
        return True

    def get_json(self, r):
        """
        string decode to json format
        :param r: string which contains a dict format
        :return: decode dict
        """
        try:
            #from string to python; decode(string to object)
            decode_dict = r.json()

        except:
            if DEBUG_MODE:
                print("BaseRequestHandler: decode json fail")
            return None
        return decode_dict

-----------------------------------
config file contents:
---------------------
DEBUG_MODE = True

# API
WB_API_BASE_URL = "http://api.wormbase.org/rest"
WB_API_GENE_URL = WB_API_BASE_URL + "/field/gene"

**Comment by sibyl229** [comment]
Hi @Jehudith I haven't run your code yet. But I wonder if the header should be "Content-Type" instead of the lower case version.

 Does running directly `curl` the URLs work for you?

**Comment by sibyl229** [comment]
HI @Jehudith This is a bit weird. I tried part of your code, and it works for me. I wonder if the error you ran into could be transient or relates to the problem of a particular server). Here is what I tried:

```
>>> import requests
>>> headers = {"content-type": "application/json"}
>>> requests.get("http://api.wormbase.org/rest/field/gene/WBGene00044322/interactions", headers=headers).json();
{u'class': u'gene', u'uri': u'/species/gene/WBGene00044322', u'name': u'WBGene00044322', u'interactions': {u'name': {u'data': {u'taxonomy': u'c_elegans', u'class': u'gene', u'id': u'WBGene00044322', u'label': u'tag-280'}, u'description': u'The name and WormBase internal ID of WBGene00044322'}, u'interactions': {u'data': {u'phenotypes': None, u'edges_all': None, u'edges': None, u'showall': u'1', u'nodes': None, u'class': u'Gene', u'types': None, u'ntypes': None}, u'description': u'genetic and predicted interactions'}}}
```

If you continue to have problem, let's test with http://staging.wormbase.org subdomain to check possibility that a particular production server is causing problem.

**Comment by Jehudith** [comment]
Hi @sibyl229 
that's odd, it still doen't work for me. is it possible that if i did a lot of request in the past it reject me?

**Comment by sibyl229** [comment]
Hi Jehudith, do you get any error message? What's the status code? Staging doesn't work for you either?

**Comment by Jehudith** [comment]
Hi @sibyl229 
same error  status_code not 200 but: 500 and i get html code back,, i am not sure how to use the staging let me check again.
https://www.dropbox.com/s/l1ctktlj3lyxaa3/WormbaseFetcher.zip?dl=0 this is my whole program , i fetch here data of  genes I insert

**Comment by Jehudith** [comment]
Hi sibyl229,

For instance this genes crashes WBGene00022623

**Comment by sibyl229** [comment]
I don't know if you are blocked for making too many requests (will have to ask someone). Usually if you need to send a big list of rest api requests, you will have to make your code wait on requests. If you think your IP might be blocked, how about try it on another network first, so we can check if that is indeed the case? 

You may also find the data you need in downloadable formats on the ftp site: ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

I tried the interactions field on WBGene00022623:
![screen shot 2016-12-14 at 12 52 46 pm](https://cloud.githubusercontent.com/assets/1753893/21194045/7766dd34-c1fc-11e6-93d8-85b90c4a84ff.png)

**Comment by Jehudith** [comment]
thanks, interactions work for me , but not the overview does it work for you?

**Comment by sibyl229** [comment]
Overview doesn't work for me either. Thanks for letting me know. I will look into it.

**Comment by Jehudith** [comment]
@sibyl229  thank you so much. I didn't know that. sorry for troubling you so much!

**Comment by sibyl229** [comment]
No problem @Jehudith . Good luck working with the API.
