### ISSUE TITLE
  Dear sir/madam, I was looking on worm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5310]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear sir/madam,<br/>I was looking on wormbase to a gene of interest. And I found that this gene (dch-4) had two splice variants (cdh-4a and cdh-4b) a while ago. However, now, I cannot find this second splice variant back on Wormbase. <br/>Is that because new data has shown that the gene does in fact not contain two splice variants?<br/>Or is there a small bug?<br/>Thank you in advance and kind regards,<br/>visitor_name</p>

**Reported by:** Anna********** (a.eb****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by Paul-Davis** [comment]
Dear Annabel,

Thank you for emailing WormBase. I personally reviewed this gene back in 
June:

[160609 pad] Added 2 single bp micro introns to correct the frame and 
generate the correct peptide sequence for this gene. Removed the 
secondary isoform as the novel coding sequence has been absorbed by the 
annotation update.

My assessment of all the available data for this gene at the time was 
that there is either assembly issues in exon 13 (Possible genome 
sequence error found in RNASeq analysis of ten lab isolates of N2 by 
Kate Weber.), some kind of RNA editing/frame compensation in that region 
or this gene is damaged and therefore a Pseudogene. As I altered the 
annotation to allow for this exon abnormality the second Isoform was 
absorbed into the current structure. I also took the decision to keep it 
as a coding loci as it doesn't have any close paralogs and therefore 
would be a unitary pseudogene.

If you have data conflicting with the new annotation on WormBase, I 
would be more than happy to review/incorporate the data.

Paul

On 12/12/2016 10:56, no-reply@wormbase.org wrote:
> Feature Request
>
>   Dear sir/madam,
> I was looking on wormbase to a gene of interest. And I found that this 
> gene (dch-4) had two splice variants (cdh-4a and cdh-4b) a while ago. 
> However, now, I cannot find this second splice variant back on Wormbase.
> Is that because new data has shown that the gene does in fact not 
> contain two splice variants?
> Or is there a small bug?
> Thank you in advance and kind regards,
> Annabel Ebbing
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5310. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5310>.
>
> Reported by: Annabel Ebbing (a.ebbing@hubrecht.eu)
> 12 Dec 16 10:56
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 
> Firefox/50.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
