### ISSUE TITLE
  Could you please give me the referenc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5313]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Could you please give me the reference to the statement "microarray studies indicate that Y40H7A.9 is regulated by Progesterone .." in the overview session of gene page http://www.wormbase.org/species/c_elegans/gene/WBGene00012746?<br/>If it is automatically inferred by homology, could you please let me know which paper showed that the homolog of Y40H7A.9 is regulated by Progesterone?  Also if this is the case, may I suggest to reword the statement to reflect that it is about the homologs?<br/>Thanks!<br/>Weiwei</p><p>What were you doing? <br />&nbsp;&nbsp;I was trying to read more about the gene Y40H7A.9.</p>

**Reported by:** Weiw******** (weiw*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by raymond91125** [comment]
HI Weiwei,

This association is not based on homology. But it does appear that there 
may be some error in the database that Wen is investigating.

Thanks for bringing it to our attention.

Best regards,

Raymond

On 12/13/2016 09:12 AM, no-reply@wormbase.org wrote:
> Content Correction
>
>   Could you please give me the reference to the statement "microarray 
> studies indicate that Y40H7A.9 is regulated by Progesterone .." in the 
> overview session of gene page 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00012746?
> If it is automatically inferred by homology, could you please let me 
> know which paper showed that the homolog of Y40H7A.9 is regulated by 
> Progesterone? Also if this is the case, may I suggest to reword the 
> statement to reflect that it is about the homologs?
> Thanks!
> Weiwei
>
> What were you doing?
>   I was trying to read more about the gene Y40H7A.9.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5313. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5313>.
>
> Reported by: Weiwei Zhong (weiwei.zhong@rice.edu)
> 13 Dec 16 17:11
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Thanks for the quick reply, Raymond!

 

I thought it was a cool result that I can cite in my paper, and all I needed was a reference. Now you are telling me that it may not be real?  Darn it. I have to rewrite my whole paper now. <kidding>  ;-)

 

Thanks for the hard work!

 

 

Weiwei

**Comment by raymond91125** [comment]
Dear Weiwei,

Thank you for bringing this issue to our attention. The statement came from
expression cluster object WBPaper00005124:progesterone_10-9M_regulated,
that derived from microarray analysis.

The paper was published in 2001. At that time, any bit of information from
genomic study was precious, so authors probably submitted us several large
lists of genes that they saw difference in expression after treatment. It
has been 15 years after this paper was published, we have got a lot more
information from other studies, so what we thought important in 2005 may be
considered distracting now.

What I noticed is that this expression cluster object contained ~11000
genes. This is too broad. When I checked the fold change of this particular
gene, it was not that significant.

I re-annotated expression clusters from this paper applying a more
stringent threshold. Now this particular expression cluster only has 68
genes left, and Y40H7A.9 is not longer listed. The changes will appear in
WS258, if I hear no objection from WormBase users or other curators.

Please let us know what you think about this.






On Tue, Dec 13, 2016 at 10:24 AM, Weiwei Zhong <wz8@rice.edu> wrote:

> Thanks for the quick reply, Raymond!
>
>
>
> I thought it was a cool result that I can cite in my paper, and all I
> needed was a reference. Now you are telling me that it may not be real?
> Darn it. I have to rewrite my whole paper now. <kidding>  ;-)
>
>
>
> Thanks for the hard work!
>
>
>
>
>
> Weiwei
>
>
>
>
>
> *From:* Raymond Lee [mailto:raymond@caltech.edu]
> *Sent:* Tuesday, December 13, 2016 12:03 PM
> *To:* weiwei.zhong@rice.edu
> *Cc:* reply+000974000767a606bcafce85b53174edf701f885e8fc73f892cf00000001
> 1467edf892a169ce0ba43cd7@reply.github.com; help@wormbase.org
> *Subject:* Re: [wormbase-help] Content Correction: Could you please give
> me the referenc... (Weiwei Zhong)
>
>
>
> HI Weiwei,
>
> This association is not based on homology. But it does appear that there
> may be some error in the database that Wen is investigating.
>
> Thanks for bringing it to our attention.
>
> Best regards,
>
> Raymond
>
> On 12/13/2016 09:12 AM, no-reply@wormbase.org wrote:
>
> Content Correction
>
>   Could you please give me the reference to the statement "microarray
> studies indicate that Y40H7A.9 is regulated by Progesterone .." in the
> overview session of gene page http://www.wormbase.org/
> species/c_elegans/gene/WBGene00012746?
> If it is automatically inferred by homology, could you please let me know
> which paper showed that the homolog of Y40H7A.9 is regulated by
> Progesterone? Also if this is the case, may I suggest to reword the
> statement to reflect that it is about the homologs?
> Thanks!
> Weiwei
>
> What were you doing?
>   I was trying to read more about the gene Y40H7A.9.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org/tools/support>
>
> This issue has been assigned ticket number: #5313. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5313>.
>
> Reported by: Weiwei Zhong (weiwei.zhong@rice.edu)
> 13 Dec 16 17:11
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google Groups
> "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to help+unsubscribe@wormbase.org.
>
>
>
>
>
> --
>
> __
>
> Raymond Lee
>
> raymond@caltech.edu
>
> http://www.WormBase.org/
>
> California Institute of Technology
>
> Division of Biology and Biological Engineering
>
> Mail Code 156-29
>
> Pasadena, CA 91125
>
> USA
>
> tel: 626.395.2687 <(626)%20395-2687>
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by raymond91125** [comment]
Hi Wen,

Thanks for explaining it.  That makes sense!  

 

I look forward to the WS258 release. 

 

Weiwei

**Comment by vanaukenk** [comment]
Hi Weiwei
Nice to hear from you!  And now to clarify how the automated descriptions work….

Automated descriptions just reflect the data in WormBase, in  this case the data from the expression clusters.  If Wen has made a correction for WS258 upload, then  this will only get reflected in the WS259 descriptions, which use the WS258 build files.  We reflect data from one release ago.

Cheers
Ranjana

**Comment by vanaukenk** [comment]
Hi Ranjana,

Thanks for the info!  

So I will look forward to WS259 !


Weiwei
----------------------
Weiwei Zhong, Ph.D.
Assistant Professor
Department of BioSciences
Rice University
6100 Main St, MS140
Houston, TX 77005
(713) 348-2307
http://wormlab.rice.edu
