### ISSUE TITLE
  How can I get a file which have all d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5316]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I get a file which have all description of genes,include gene name,gene ID and it's functions.</p>

**Reported by:** Li J****** (7477************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36

**Comment by Paul-Davis** [comment]
Thank you for contacting WormBase.

You can get this data from WormMine our data mining tool.

http://intermine.wormbase.org/tools/wormmine/query.do

I have generated a query for C. elegans genes which will give you a base 
for refining the query to get the data you require.

xml:

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.briefDescription Gene.organism.name" longDescription="" sortOrder="Gene.briefDescription asc">
   <constraint path="Gene.organism.species" op="=" value="elegans"/>
</query>

This can be imported here:

http://intermine.wormbase.org/tools/wormmine/importQueries.do

I hope this helps.

Paul





On 14/12/2016 03:10, no-reply@wormbase.org wrote:
> Question:
>
>   How can I get a file which have all description of genes,include 
> gene name,gene ID and it's functions.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5316. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5316>.
>
> Reported by: Li Jingxin (747705074@qq.com)
> 14 Dec 16 03:10
>
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/53.0.2785.89 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
