### ISSUE TITLE
  Hi,  How do I get the dataset of the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5326]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>How do I get the dataset of the genomic coordinates of the c. elegans "operon" please?</p>

**Reported by:** anne (daul************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by chris-grove** [comment]
Hi Anne,


 You can get this information from the C. elegans GFF file on our FTP site:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/gff/


I downloaded the file "c_elegans.PRJNA13758.WS254.annotations.gff3.gz", unzipped it, and then ran this command in a terminal window:


grep operon elegans.PRJNA13758.WS254.annotations.gff3 > WS254_gff_operon_output.txt


This will generate a file (attached) with the chromosomal coordinates for each operon mentioned in the GFF file.


I hope that helps!


Best,


Chris Grove

WormBase
