### ISSUE TITLE
  I have a list of variations and want ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5327]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a list of variations and want to look up the corresponding gene. Is there a batch search, or what file from the ftp server can I download that would contain the information?<br/>For example:<br/>WBVar00000007<br/>WBVar00000046<br/>WBVar00000100<br/>WBVar00087837<br/>WBVar00087934<br/>WBVar00088252</p>

**Reported by:** niqq**************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14

**Comment by vanaukenk** [comment]
Hi,


Thanks for writing to WormBase.


You can use the WormMine tool to retrieve corresponding genes for a list of WBVariations.

From the following link:

http://im-254.wormbase.org/tools/wormmine/begin.do
WormMine: Home
im-254.wormbase.org
Integrated queryable database for nematode genomics


Click on the Lists tab at the top of the page, choose Allele from the Select Type menu, Select Any from Organism, and then paste your WBVariation list into the box.  Then click on Create List.


On the resulting page, click on the Green Save List box on the right side of the page, and then the Manage Columns link at the top left of the next page.  The pop-up menu will then allow you to add Columns, such as WBGene ID and Gene Name, under the Gene menu.


My colleague Chris Grove has created a movie that illustrates how to do this.  The WormMine-specific part of the example starts at about the 35 second mark:


https://dl.dropboxusercontent.com/u/4290782/WormBase/Movies/Getting_list_of_alleles_and_genes_for_a_Million_mutation_strain_9-8-2016.mov

Please let us know if you need any additional help.


Best,

--Kimberly Van Auken

**Comment by vanaukenk** [comment]
Thank you so much for your instructions, with your help I was able to download the data that I needed :)

Cheers,
Monique
