### ISSUE TITLE
  1) How do I access the data for genom...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5328]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;1) How do I access the data for genomic tracks (e.g., modeENCODE H3K36me3 peaks) that are displayed in the Genome Browser?<br/>2) In what format(s) (e.g., bigBed) are the data available?<br/>Thanks!<br/>Harold</p>

**Reported by:** Haro******** (smit******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by scottcain** [comment]
This was sent to the requestor:

Hi Harold,

Obtaining the modENCODE data can be a little opaque.  Generally, your best bet is to get it from the modENCODE website at http://intermine.modencode.org/.  For specific data sets, it might help to use Google to lead you to the right page.  For example, the data set you asked about for H3K36me3 peaks, I Googled "modencode H3K36me3_N2_L3" (see below for why I chose this query) which lead me to this page:

http://intermine.modencode.org/query/experiment.do?experiment=Chromatin+ChIP-seq

From which you can download various formats of the data for different experiments.

For data we have in our browsers, we have either BigWig, BAM or GFF data, though the GFF files we no longer have--we loaded them into MySQL databases for serving GBrowse and removed the originals.  For any of these data, I would be happy to send you want we have, or put on an ftp site if that would be helpful.


How I chose that string to help me find the data on the modENCODE site: I went to our newer genome browser, JBrowse:

http://www.wormbase.org/tools/genome/jbrowse/?data=data%2Fc_elegans_PRJNA13758

and clicked on the "Select tracks" tab.  In the search box, I entered "H3K36me3" to see what tracks we had related to that term and found 16 tracks.  I took the end of the title of the first track I found and used that in the Google search.


I realize this sounds a little Byzantine; if you'd like clarification or more help, please let us know.

Scott
