### ISSUE TITLE
when was this published?? and who published this p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5329]
*Help Desk query collected when no chat operators were online. Follow up required.*

when was this published?? and who published this piece??

**Reported by:** sam (game******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000039#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00000039#0-9g-3</a>
**Browser:** Chrome 54.0.2840.99

**Comment by chris-grove** [comment]
Hi Sam,


 What are you referring to exactly? The gene description for acn-1?


You can open up the "References" widget to see which papers have published information on this gene:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000039#0e-9g-3


Let us know if you need more information.


Best,


Chris Grove

WormBase
