### ISSUE TITLE
visitor_name (visitor_email): Hi, I would like to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5334]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I would like to know : how to save or download the results from the genome browser in wormbase. I am able to highlight motifs present in a protein sequence and not able to save the results.

**Reported by:** Jyot*** (jdin**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_users#2130--10">http://www.wormbase.org/about/userguide/for_users#2130--10</a>
**Browser:** Chrome 55.0.2883.87

**Comment by scottcain** [comment]
This response was emailed:

Hi Jyoti,

It depends on which genome browser you're using.  If you are using GBrowse, you don't need to highlight the region you want downloaded, just get the view you want saved in the browser window.  Then press the "download this track" button (the one that looks like a floppy disk in the track label (see the first attached picture)) and select the "Download track data across region" button, which will download a GFF3.

If you are using JBrowse (the new WormBase genome browser), again get the view of what you want saved in the browser and press the drop down menu triangle on the right end of the track label (see the second attached picture) and select "Save track data" and click Save in the resulting window.  This will download a similar GFF3 file.

Please let us know if you need any more assistance,
Scott

![screen shot 2016-12-28 at 10 47 57 am](https://cloud.githubusercontent.com/assets/274751/21525722/1a02042e-cced-11e6-8ae2-078c1c774f52.png)

![screen shot 2016-12-28 at 10 54 34 am](https://cloud.githubusercontent.com/assets/274751/21525724/1e6aec74-cced-11e6-8d24-000ff6d8e3d9.png)
