### ISSUE TITLE
Hi,
Thank you for your response. 
I am able to sav...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5335]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
Thank you for your response. 
I am able to save sequence information but would like to save graphical map view as I see on screen as output of marked motifs. 
for example, in below link could you tell me how can I save the view  of jbrowser :as it it, 
http://www.wormbase.org/tools/genome/jbrowse/?loc=X%3A7716518..7727487&amp;data=data%2Fc_elegans_PRJNA13758&amp;tracks=Curated%20Genes%20(protein%20coding)%2CTranscription%20end%20site%2CProtein%20motifs&amp;highlight=

**Reported by:** Jyot*** (jdin**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_users#2130--10">http://www.wormbase.org/about/userguide/for_users#2130--10</a>
**Browser:** Chrome 55.0.2883.87

**Comment by scottcain** [comment]
Continuation of #5334

**Comment by scottcain** [comment]
Emailed:

Hi Jyoti,

Unfortunately, this is one of the downsides of using JBrowse at the moment: there is no tool for taking high resolution screenshots built in to it like GBrowse has.  The available options are these:

1. Take a screenshot and edit it to you needs.

2. Use GBrowse and its builtin tools for getting high resolution images.

3. Use an external tool called phantomjs and have it create a "higher" resolution png than you can get from a simple screenshot.  I wrote a blog post describing how to do that earlier this year:

http://blog.wormbase.org/2016/02/10/creating-hi-res-screenshots-in-jbrowse/

Which ever one of these you'd like to do, please let us know if there is more we can do to help,
Scott
