### ISSUE TITLE
  I am interested in gene structure.  S...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5336]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am interested in gene structure.  Specifically, I wanted to look at genes with the 5' intron longer than 1000 nucleotides.  Is there a list or way to search for genes with this qualification?<br/>Thank you!</p>

**Reported by:** Sara********** (slro****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by mgrbyte** [comment]
Replied directly to the user - Hinxton will determine exactly what query is required.

**Comment by brucebolt** [comment]
Response from user:

> Hi Bruce,
> 
> I am looking for the 5' most intron that is longer than 1000 nt.  Since I'm sure some of these do fall within the 5' UTR, these might be included in the list.  
> 
> Does this help?
> 
> Sarah
> 

This isn't something we can do in BioMart.  Anyone have any suggestions?

**Comment by brucebolt** [comment]
Hi Sarah,

There is no direct way of answering your specific question using the
website tools. However, everything you need is included in our GFF3 files:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/c_elegans.canonical_bioproject.current.annotations.gff3.gz

The specific lines that you need are feature type (column 3) is "intron"
and source (column 2) is "WormBase". That snag is that the intron lines do
no encode any information about which intron they are within the transcript
(i.e. whether it is the first intron, second intron etc). For that, you
will need to write a little script (in Perl or Python) that collects
together the introns for each transcript, obtains the 5'-most one,
calculate its length, and output it is > 1000 nt.

If you don't have the knowledge to do that (and if there's no-one in your
lab that can help), then let us know and we can produce the list of genes
you are looking for as a one-off.

Best,

Kevin

**Comment by brucebolt** [comment]
Hi Kevin,


If you can make the list of genes, I would really appreciate the help.


Thank you!


Sarah

________________________________

**Comment by khowe** [comment]
Sent user what they needed in direct email.
