### ISSUE TITLE
  Hi, I am currently a postdoc in Monic...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5337]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am currently a postdoc in Monica Driscoll's lab of Rutgers. I would like get a wormbase ID, so I can submit data to wormbase.</p>

**Reported by:** Guoq********* (wang**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by raymond91125** [comment]
Please provide personal information via form 
<http://www.wormbase.org/submissions/person.cgi>.

Thanks.

Raymond
