### ISSUE TITLE
  can't seem to access Blast via site  ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5338]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;can't seem to access Blast via site</p><p>What were you doing? <br />&nbsp;&nbsp;Blast</p>

**Reported by:** John******* (jhw3**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by chris-grove** [comment]
Hello John,


 Thanks for the bug report, and apologies for the inconvenience.


Our web team is working on the issue now.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Getting a 504 Gateway Time-out

**Comment by chris-grove** [comment]
BLAST is still throwing the time out error

**Comment by chris-grove** [comment]
Fixed

**Comment by chris-grove** [comment]
Hello again John,

 The BLAST/BLAT service has been restored. Please let us know if you encounter any more issues.

Thanks,

Chris
