### ISSUE TITLE
how can I search for c elegans genes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5341]
*Help Desk query collected when no chat operators were online. Follow up required.*

how can I search for c elegans genes

**Reported by:** amee** (thus***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about#01--10">http://www.wormbase.org/about#01--10</a>
**Browser:** Chrome 55.0.2883.87

**Comment by chris-grove** [comment]
Hello Ameena,


 You can use the search box in the upper right corner of any WormBase page to search "for a gene". Just type in the name of the gene you are looking for (e.g. "unc-26") and click on the search button icon (looks like a magnifying glass). Let us know if you need any more help.


Best,


Chris Grove

WormBase
