### ISSUE TITLE
visitor_name (visitor_namemayda@yahoo.com): I need...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5343]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_namemayda@yahoo.com): I need to cited this cite for my thesis work. How can i cited this?

**Reported by:** umma (umma***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0-9g-3</a>
**Browser:** Chrome 55.0.2883.87

**Comment by WenChenWormBase** [comment]
Dear Umma,

Thank for you for writing to WormBase. There are a few ways to cite
WormBase, you can choose which way works for your publication from this
page:
http://www.wormbase.org/about/citing_wormbase#012--10

-- 
Wen Chen, Ph.D.
Curator, WormBase
