### ISSUE TITLE
  Appears to be a broken image in the l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5348]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Appears to be a broken image in the location widget (genes)<br/>http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#04i9--10</p>

**Reported by:** Matt******** (matt***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by mgrbyte** [comment]
![wborg-broken-img-location-widget](https://cloud.githubusercontent.com/assets/3185091/21805571/c066e9e4-d72c-11e6-88d0-0cdf943be8d7.png)

**Comment by scottcain** [comment]
Hi @mgrbyte Thanks for reporting this. I'm reasonably sure this was a transient problem--we were messing with MySQL earlier today and you may have just had some bad luck with the timing.
