### ISSUE TITLE
  To Whom it may concern: My name is vi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5349]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;To Whom it may concern:<br/>My name is visitor_name, a junior at Lynbrook High School, New York, and have been working with C. Elegans at school in my research class. I wanted to know is it possible to get the C. Elegan strain CL2006. If so, how?<br/>Thank you for your time.</p>

**Reported by:** Soph************ (soph*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by chris-grove** [comment]
Hello Sophia,


 You'll want to contact the Caenorhabditis Genetics Center (CGC); here's their website:


http://cbs.umn.edu/cgc/home


They have the strain CL2006. Once you (or your teacher) establish an account the strain should cost $7.


Good luck!


Chris Grove

WormBase
