### ISSUE TITLE
Rewrite of GO widget with data from Datomic 

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#5350]
Hi @vanaukenk @tharris the GO widget on Gene page has been rewritten to use data from Datomic. Could you take a look to see if anything is off? Thanks a lot!

**Comment by sibyl229** [comment]
Oh, I noticed that the "With" column is missing. I will fix it.

**Comment by mgrbyte** [comment]
Minor difference in display:
 When there are >= 2 items listed in the `With` column (full view): 
     On `www` the `list-style` seems to be disc/circle, where as staging the style is `none`.

I'm not sure which is "correct" or desired, just noting the difference.

**Comment by vanaukenk** [comment]
Thanks @sibyl229!  I'll take a careful look and let you know if I see anything that needs to be addressed.

**Comment by vanaukenk** [comment]
Hi @sibyl229 --

I've checked the display of about a dozen genes and can't find anything that is off.  There are a couple of small display issues that I'd like to address, but they aren't due to the difference in the source of the data and are relatively minor.  I'll make separate tickets for those.

@mgrbyte - wrt your comment about list-style, did you find an example of where the display was affected?  Thx.

**Comment by mgrbyte** [comment]
@vanaukenk I was comparing the gene ontology widget for the gene unc-22 between staging and live.

**Comment by vanaukenk** [comment]
Thx @mgrbyte I see what you mean now.
@sibyl229 - I think the disc/circle feature of the display on the live site is helpful and we should keep that.

**Comment by sibyl229** [comment]
Hi @vanaukenk sure, I will add the disc back.

**Comment by sibyl229** [comment]
Hi @vanaukenk the "With" column and disc for a list of items should be fixed now. Here is an example for testing: http://staging.wormbase.org/species/c_elegans/gene/WBGene00001173#3--10 Thanks!

**Comment by paulwsternberg** [comment]
Very nice!!!!
Paul


On Jan 16, 2017, at 9:20 AM, Sibyl G <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @vanaukenk<https://github.com/vanaukenk> the "With" column and disc for a list of items should be fixed now. Here is an example for testing: http://staging.wormbase.org/species/c_elegans/gene/WBGene00001173#3--10 Thanks!

**Comment by vanaukenk** [comment]
@sibyl229 - this looks good to me!  Thx.
