### ISSUE TITLE
BLAST page throwing 504 Gateway timeout error

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5351]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Zhiji, how can I help?</br>visitor_name (visitor_email): Hi, I noticed that the blast site is not working.</br>Chris: Oh, OK, apologies</br>visitor_name (visitor_email): I could not load the webpage</br>Chris: Our web team is working on it now</br>visitor_name (visitor_email): That's okay. just want to let you know</br>Chris: I can send you an email as soon as it is back up and running</br>Chris: OK thank you!</br>visitor_name (visitor_email): great. Thank you</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): That's it. Thanks</br>Chris: OK, take care</br>visitor_name (visitor_email): you too</br>Chris: Thanks!

**Reported by:** Zhij***** (zren****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/support?url=/">http://www.wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 55.0.2883.95

**Comment by chris-grove** [comment]
Confirmed 504 Gateway Time-out

**Comment by chris-grove** [comment]
Hello Zhiji,


 It appears that the BLAST service is back up and running. Please let us know if you experience any more problems.


Thanks for the report.


Best,


Chris Grove

WormBase
