### ISSUE TITLE
  can't access blast server  What were ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5352]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;can't access blast server</p><p>What were you doing? <br />&nbsp;&nbsp;blast</p>

**Reported by:** John******* (jhw3**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by chris-grove** [comment]
Hi John,


 It appears that BLAST service has been restored. Thanks for letting us know. Let us know if you experience any more problems.


Best,

Chris Grove

WormBase
