### ISSUE TITLE
I need to learn more about homozygosity and hetero...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5353]
*Help Desk query collected when no chat operators were online. Follow up required.*

I need to learn more about homozygosity and heterozygosity in C. elegans. Thanks.

**Reported by:** Sayr** (sayr*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001665#0--10">http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001665#0--10</a>
**Browser:** Chrome 55.0.2883.87

**Comment by raymond91125** [comment]
Hi Sayran,

Sorry if I mis-understood your question. But you may benefit from 
reviewing general and specific genetics about C. elegans. Here is an 
article that may be helpful 
<http://wormbook.org/chapters/www_complementation/complementation.html>.

Thanks.

Raymond



On 01/11/2017 11:20 AM, no-reply@wormbase.org wrote:
> offline chat I need to learn more about homozygosity and 
> heterozygosity in C. elegans. Thanks.
>
> Submitted From:
>   http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001665#0--10 
> http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001665#0--10 
> <http://www.wormbase.org/http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001665#0--10> 
>
>
> This issue has been assigned ticket number: #5353. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5353>.
>
> Reported by: Sayran (sayransalim77@gmail.com)
> 11 Jan 17 19:21
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
