### ISSUE TITLE
  This isn't necessarily a correction, ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5355]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;This isn't necessarily a correction, but I was looking into the BA1083 strain (F43G6.6(hc184) II) and trying to find where the deletion in the hc184 allele is. I can't find any information about the deletion in CGC or publications either. I noticed the curation on this allele is still pending, but I wonder whether curation has been completed and simply isn't up on wormbase yet? Any information about this deletion allele would be appreciated. Thanks!</p>

**Reported by:** Tina****** (trly*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by tuli** [comment]
Dear Tina,

Thank you for writing to WormBase.

I am afraid I can add nothing more to what you have already found. The
hc184 has not been curated.

I was going to suggest you contact the Ward lab (from which the strain
originated) to ask whether they had further information but see that
the link to the website is broken so maybe the lab is closed. I can do
some further digging around if the information is important to you.
Let me know.

Best wishes,

Mary Ann

On 11 January 2017 at 20:42,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   This isn't necessarily a correction, but I was looking into the BA1083
> strain (F43G6.6(hc184) II) and trying to find where the deletion in the
> hc184 allele is. I can't find any information about the deletion in CGC or
> publications either. I noticed the curation on this allele is still pending,
> but I wonder whether curation has been completed and simply isn't up on
> wormbase yet? Any information about this deletion allele would be
> appreciated. Thanks!
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5355. Follow progress on our
> issue tracker.
>
> Reported by: Tina Lynch (trlynch2@wisc.edu)
> 11 Jan 17 20:43
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
> Gecko) Chrome/55.0.2883.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
User to sequence strain herself.
