### ISSUE TITLE
  Hi there, I'm trying to figure out ho...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5357]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there, I'm trying to figure out how to download protein sequences for 65 genes (for which I have 'names' like R03D7.6), so that I can BLAST them against another nematode's genome.<br/>Is there a way to batch download these?  (I've played around with QueryBuilder on WormMine; I just can't find an option for generating protein sequence data).<br/>Of course if there is a way to do this even faster - i.e. blast the list of 65 genes (listed by name) against another genome, without even needing to download protein sequence - that would be even better!!!<br/>Thanks so much for your help,<br/>visitor_name</p>

**Reported by:** Aman** (acwo******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by brucebolt** [comment]
Dear Amanda

Thank you for writing to WormBase.

We do not currently have protein sequences available in WormMine.  However, you can retrieve the sequences from the WormBase ParaSite BioMart (http://parasite.wormbase.org/biomart/martview/).

Under ‘Query Filters’, set ‘SPECIES’ —> ‘Genome’ equal to C. elegans.  Under ‘GENE’ —> ‘ID list limit’, select ‘WormBase Sequence Name [e.g. F27C8.1]’.  Then enter your list of sequence names in the box below, with each one on a new line.

Under ‘Output Attributes’, select ‘Retrieve sequences’.  Then choose ‘SEQUENCES’ —> ‘Peptide’.

Click ‘Results’ and you will see the protein sequences.  These can also be downloaded as a FASTA file.

This link <http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.sequences.production_name_1010%7Cwbps_gene.default.sequences.wbps_gene_id%7Cwbps_gene.default.sequences.peptide&FILTERS=wbps_gene.default.naive_filters.species_id_1010.%22elegaprjna13758%22%7Cwbps_gene.default.naive_filters.wormbase_gseqname.%22R03D7.6%22&VISIBLEPANEL=resultspanel> will take you to an example query with the above filters and attributes already selected.

Let me know if you have any more BioMart questions.

Best regards

Bruce



-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD

**Comment by chris-grove** [comment]
@brucebolt 
For the record, WormMine does have protein sequences, just not DNA sequences.
