### ISSUE TITLE
  Hi, My name is visitor_name and I wor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5358]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>My name is visitor_name and I work as a post-doc in a C. elegans lab in University of Virginia. I would like to gain information about the gene expression conditions of a series of genes from wormbase. Please let me know if there is a tool for this in which importing a series of gene names will give the expression values and conditions as output rather than looking at the expression one gene at a time.<br/>Thank you,<br/>Vinod</p>

**Reported by:** Vino****** (vkm2**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by draciti** [comment]
Hi Vinod,
thanks for writing to WormBase. You can use our Simple Mine tool to query gene lists:
http://www.wormbase.org/tools/mine/simplemine.cgi

Just put your gene list in the box and Query.
Gene expression data are in the Expr_pattern Tissue and Expr_pattern Life_Stage columns.
Let us know if you have additional questions.
Thanks,
Daniela

**Comment by draciti** [comment]
From Vinod:
1) Hi Daniela,
Thanks for the quick response. I will try this and will request if need more help.
Vinod

2) This was useful. But is there a way to get the expression values like fold changes/FPKMs of RNA seq and the experimental conditions related to what's already known about the genes.

redirected user to RNAseq curators:
Hi Vinod,
I am cc'ing our RNAseq curators, they might be able to help.
Best,
Daniela

**Comment by gw3** [comment]
Hi @WenChenWormBase ,
I want to see what I can do with SPELL to help this user, but SPELL hangs when I go to it.
Is there a known problem with SPELL at present?
Gary
