### ISSUE TITLE
Files of new CGC genes

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5359]
A problem was discovered in the WS257 files of new and changed CGC names.
These files have been fixed on the EBI FTP site.
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS256/species/c_elegans/PRJNA13758/annotation/
the files are:

c_elegans.PRJNA13758.WS257.changed_CGC_names.txt
c_elegans.PRJNA13758.WS257.readable_changed_CGC_names.txt

This data is used to display the list of genes with changed CGC names on the website main page.

**Comment by tharris** [comment]
Synced!
