### ISSUE TITLE
  Dear all, I am contacting you because...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5363]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear all,<br/>I am contacting you because I am currently working with C. elegans but from my institution asked me if to work with this animals, we have to pass any bioethics commitee, and as far as I am not concerned. C. elegans does not need to pass this evaluation, am I wrong?<br/>If I am correct, do you have any document confirming it? <br/>It would be very helfpul if you can help.<br/>Thanks in advance,<br/>anna</p><p>What were you doing? <br />&nbsp;&nbsp;use c. elegans to evaluate nanoparticles</p>

**Reported by:** Anna********** (alar***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by raymond91125** [comment]
Hi Anna,

I don't know the answer to your question but I'd guess some PI's might 
have dealt with similar issues. I suggest that you post the question to 
Worm Community Forum <http://forums.wormbase.org/> to reach a larger 
audience.

Thanks.

Raymond


On 01/18/2017 08:29 AM, no-reply@wormbase.org wrote:
> Feature Request
>
>   Dear all,
> I am contacting you because I am currently working with C. elegans but 
> from my institution asked me if to work with this animals, we have to 
> pass any bioethics commitee, and as far as I am not concerned. C. 
> elegans does not need to pass this evaluation, am I wrong?
> If I am correct, do you have any document confirming it?
> It would be very helfpul if you can help.
> Thanks in advance,
> anna
>
> What were you doing?
>   use c. elegans to evaluate nanoparticles
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5363. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5363>.
>
> Reported by: Anna Laromaine (alaromaine@icmab.es)
> 18 Jan 17 16:27
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
