### ISSUE TITLE
  Hi all, I am writing with an update f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5365]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi all,<br/>I am writing with an update for the n484 allele of egl-15 (the reference allele). The sequence variation is not annotated on Wormbase, but a 2003 article in Development by Goodman et al. (http://dev.biologists.org/content/130/16/3757.short) mentions that it is a tryptophan to stop nonsense mutation in exon 5A. Based on this, I was able to identify the precise location and change by PCR amplification and sequencing of N2 and n484 strains. I wanted to report this to Wormbase. The flanking sequences are: <br/>GAGGAGAGTGAAAAGCCAATTGGGCGGATG<br/>and<br/>GAGAAGATGAATAATGAACAGAAAATTGTT<br/>with a G-->A change in between. Thus, the mutant sequence is <br/>GAGGAGAGTGAAAAGCCAATTGGGCGGATGAGAGAAGATGAATAATGAACAGAAAATTGTT<br/>Please let me know if you need any additional information - I'm only emailing because I don't want to take full credit for this annotation when much of the work was done by Goodman and colleagues!<br/>Thank you for all you do for the worm community,<br/>visitor_name<br/>Graduate Student<br/>Heiman Lab<br/>Boston Children's Hospital</p>

**Reported by:** Eliz************ (eliz**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by tuli** [comment]
Dear Elizabeth,

Thank you very much for bringing this to our attention. I have curated
the molecular details of the n484 allele as advised and you'll see the
update in release WS259 of WormBase.

Thank you for helping to keep WormBase up to date!

Best wishes,

Mary Ann

On 19 January 2017 at 15:32,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hi all,
> I am writing with an update for the n484 allele of egl-15 (the reference
> allele). The sequence variation is not annotated on Wormbase, but a 2003
> article in Development by Goodman et al.
> (http://dev.biologists.org/content/130/16/3757.short) mentions that it is a
> tryptophan to stop nonsense mutation in exon 5A. Based on this, I was able
> to identify the precise location and change by PCR amplification and
> sequencing of N2 and n484 strains. I wanted to report this to Wormbase. The
> flanking sequences are:
> GAGGAGAGTGAAAAGCCAATTGGGCGGATG
> and
> GAGAAGATGAATAATGAACAGAAAATTGTT
> with a G-->A change in between. Thus, the mutant sequence is
> GAGGAGAGTGAAAAGCCAATTGGGCGGATGAGAGAAGATGAATAATGAACAGAAAATTGTT
> Please let me know if you need any additional information - I'm only
> emailing because I don't want to take full credit for this annotation when
> much of the work was done by Goodman and colleagues!
> Thank you for all you do for the worm community,
> Elizabeth Lamkin
> Graduate Student
> Heiman Lab
> Boston Children's Hospital
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5365. Follow progress on our
> issue tracker.
>
> Reported by: Elizabeth Lamkin (elizabeth.lamkin@gmail.com)
> 19 Jan 17 15:33
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/55.0.2883.95 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
