### ISSUE TITLE
  it would be a really cool feature to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5372]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;it would be a really cool feature to have each gene linked to known balancers for that gene.</p>

**Reported by:** kbru****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by tuli** [comment]
Dear Katherine,

Thank you for writing to WormBase.

I agree, I think this would be a useful addition. I will look into
different ways to do this and discuss with my colleagues, and get back
to you shortly.

Meanwhile, there is a table of Balancers here:
http://wiki.wormbase.org/index.php/Balancers and they are also visible
on the Genome Browser.

Best wishes,

Mary Ann

Mary Ann


On 19 January 2017 at 23:45,  <no-reply@wormbase.org> wrote:
> Feature Request
>
>   it would be a really cool feature to have each gene linked to known
> balancers for that gene.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5372. Follow progress on our
> issue tracker.
>
> Reported by: kbrugman@caltech.edu
> 19 Jan 17 23:46
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/55.0.2883.95 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Katie,


 Just to add to Mary Ann's comments: You can also find balancers for a gene by looking in the "Genetics" widget on the gene page. For example:


http://www.wormbase.org/species/c_elegans/gene/WBGene00002280#0-4-10


If you scroll down to the Strains section of the Genetics widget, you can find strain genotypes that mention balancers, like "mnDp1 (X;V)/+ V" and "mnDp26(X;f)". If you click on the strain name, that will take you to the strain page, where you can then click on the name of the balancer to see details on the actual rearrangement page:


http://www.wormbase.org/species/all/rearrangement/mnDp1#0123--10



Hope that helps.

Chris Grove

________________________________
