### ISSUE TITLE
  Hello, Please connect these papers to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5373]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>Please connect these papers to my person. Thank you, RC<br/>Ribonuclease-Mediated Control of Body Fat. Habacher C, Guo Y, Venz R, Kumari P, Neagu A, Gaidatzis D, Harvald EB, Færgeman NJ, Gut H, Ciosk R.<br/>Dev Cell. 2016 Nov 7;39(3):359-369. doi: 10.1016/j.devcel.2016.09.018.<br/>Increasing Notch signaling antagonizes PRC2-mediated silencing to promote reprograming of germ cells into neurons. Seelk S, Adrian-Kalchhauser I, Hargitai B, Hajduskova M, Gutnik S, Tursun B, Ciosk R. Elife. 2016 Sep 7;5. pii: e15477. doi: 10.7554/eLife.15477.</p>

**Reported by:** Cios******** (rafa**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by vanaukenk** [comment]
The paper is in WB as WBPaper00050279.
It looks like the author-person connections, made in postgres on 2016-11-30, will not be in WB until WS258. @ceciliaWBPerson1 , do you want to reply to Rafal?

**Comment by vanaukenk** [comment]
Just double-checking before I responded to Rafal, and it looks like Cecilia answered him on the 20th of January, so I've pasted in her reply and will close this ticket.

Dear Dr. Rafal Ciosk:

Thank you very much for the updates.

I added:
-  paper identified as WBPaper00050279, pmid27746047,
doi10.1016/j.devcel.2016.09.018  to your Person page on 2016-11-30 14:46:10.084739-08.

Updates will be available in WS258 release of WormBase.
We are currently in version WS256.

- paper identified as WBPaper00050094, pmid27602485,
doi10.7554/eLife.15477 to your Person page on 2016-10-21
14:59:51.351246-07

Updates will be available in WS257 release of WormBase.
It is available in our staging site.

http://staging.wormbase.org/resources/person/WBPerson2117#0123--10

Please check your Lineage section, if you'd like to update it please fill
this form:
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person_lineage.cgi?action=Display&number=WBPerson2117

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule

Thanks again, have a great day!
Cecilia
