### ISSUE TITLE
Tree Display

### ISSUE THREAD

**Issue by tuli** [WormBase/website#5374]
The Tree Display on the Production site has been down for quite a while. OK on Staging.

**Comment by sibyl229** [comment]
Hi @tuli Todd probably has started ACeDB, and it looks like tree display is working now: http://www.wormbase.org/species/c_elegans/gene/WBGene00015146#h-g-3 Feel free to let us know if it's down again. Thanks!

**Comment by tuli** [comment]
Tree display giving a gateway time out error.http://www.wormbase.org/species/c_elegans/variation/WBVar02144131#0-54362719-10

**Comment by tuli** [comment]
http://www.wormbase.org/resources/paper/WBPaper00031462#05--10 Tree display timing out.

**Comment by tuli** [comment]
http://www.wormbase.org/resources/molecule/WBMol:00001845#01237--10 Tree display timing out

**Comment by epaule** [comment]
duplicate of #5436
