### ISSUE TITLE
  Could I ask to include a meeting abst...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5378]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Could I ask to include a meeting abstract to my site at wormbase: <br/>http://www.wormbase.org/resources/person/WBPerson439#013--10:<br/>It is:  <br/>2015<br/>289C. Comparative Analysis of Human Alzheimer’s Risk Factor Genes from GWAS and Linkage Analyses.. Behrad Vahdati Nia, Deborah Lee, Phong Ta, Steven Munassi, visitor_name.<br/>You can confirm it at: <br/>http://www.genetics-gsa.org/celegans/2015/pages/posterlisting.shtml</p>

**Reported by:** Shin********* (shin****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by gw3** [comment]
Dear Shin Murakami,

Your abstract is already in WormBase.
The ID of your abstract is: "WBPaper00047596"

Gary Williams
WormBase
