### ISSUE TITLE
Genetic Map timing out

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5381]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): In class my teacher showed us how to see all of the genes on chromosome III of C. elegans but I forgot how to do it and I can't figure it out. Are you able to help me?</br>Chris: Hello visitor_name</br>Chris: This was using the WormBase website?</br>Chris: That would be a list of thousands of genes</br>visitor_name (visitor_email): Yes it was. She was able to see the full chromosome and then move to different parts of the chromosome to see the different genes</br>Chris: OK, you may be referring to the genome browser GBrowse</br>Chris: You can get to it under the Tools menu</br>Chris: http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/</br>Chris: Is that what you were looking for?</br>Chris: You can specify chromosome III in the "Landmark or Region" field</br>visitor_name (visitor_email): Her's looked different,, it was a vertical chromosome and it had a bunch of genes on the right hand side and some where highlighted yellow</br>Chris: Ah, that's the genetic map viewer</br>Chris: http://www.wormbase.org/tools/gmap</br>Chris: which seems to be down at the moment</br>visitor_name (visitor_email): Ok thank you, I thought that was it but the page wouldn't load. I will try again later.</br>Chris: OK, sorry about that</br>Chris: I can send you an email once it's back up and running</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): That is all. Thank you!</br>Chris: OK, take care

**Reported by:** Brea*** (brea*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools#0--10">http://www.wormbase.org/tools#0--10</a>
**Browser:** Chrome 55.0.2883.87

**Comment by chris-grove** [comment]
I'm getting a 504 Gateway Time-out error

**Comment by chris-grove** [comment]
Hi Breanne,


 It looks like the genetic map viewer is back up and running:


http://www.wormbase.org/tools/gmap/


You can select the chromosome you want and click on "View".


Best,


Chris
