### ISSUE TITLE
  Hi - can you tell me how to a.  downl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5384]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi - can you tell me how to a.  download a batch of spliced transcripts from a list of WB numbers; and b.  how to do a GO analysis of a list of WB numbers?  thanks! pb</p>

**Reported by:** Perr************ (blac******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by vanaukenk** [comment]
Dear Perry,


Thanks for writing to WormBase.


To download spliced transcripts using a list of WB gene IDs, e.g. WBGene00000001, you can use the Mart tool available at WormBase Parasite:


http://parasite.wormbase.org/biomart/martview


and enter your list of WBGene in the ID list box under the Gene menu.  Then when you select the Output Attributes, you can click on the radio button for Retrieve Sequences and specify the sequence you'd like to return.


Alternatively, you can download sequence files from the WormBase ftp site, and parse the sequence you want from those files:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS256/species/c_elegans/PRJNA13758/


For Gene Ontology analysis, we recommend using the Panther enrichment tool that can be accessed from the left side of the GO's home page:


http://www.geneontology.org/
Gene Ontology Consortium | Gene Ontology Consortium
www.geneontology.org
Filter classes. Download ontology. Gene Ontology: the framework for the model of biology. The GO defines concepts/classes used to describe gene function, and ...
Please let us know if you have any additional questions or need further assistance with anything.


Best,

--Kimberly Van Auken
