### ISSUE TITLE
Gene IDs, names, and sequence names are misformatted in WormMine im-257

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5385]
@nuin 
I noticed that in the new im-257 WormMine build, the gene IDs, names, and sequence names are mostly not formatted correctly. For example, performing this query for C. elegans genes:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.organism.name" op="==" value="Caenorhabditis elegans"/>
</query>`

Results in the following results:

![screen shot 2017-01-27 at 11 04 32 am](https://cloud.githubusercontent.com/assets/611382/22383853/7d7bf546-e480-11e6-9c8a-a165e6a39c5e.png)

The problem is that the "WormBase Gene ID" is of the form "Gene:WBGene########" when it should simply be "WBGene########" and the "Gene Name" is of the format "WBGene########" when it should be something like "unc-26" or "dpy-3" and the "Sequence Name" field is mostly empty when it should have names like "W02C12.3" or "M05B5.5".

An example of a gene entry that is formatted properly can be seen with this query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.organism.name" code="A" op="==" value="Caenorhabditis elegans"/>
  <constraint path="Gene.symbol" code="B" op="CONTAINS" value="unc"/>
</query>`

This query should return more than a hundred genes but it only returns one (unc-26), so it seems that a few genes are formatted correctly, but most are not.

I hope that's clear.

**Comment by nuin** [comment]
The `Gene:` should be straightforward to fix, I will try to have a new build ready tonight. I will check the other things. Thanks for reporting.

**Comment by nuin** [comment]
`Gene:` is fixed, I am checking the other issues in this.

**Comment by nuin** [comment]
@chris-grove Please check the new build, as there were some changes to the load. There might be an error here-and-there but mostly the complete information is there.

**Comment by chris-grove** [comment]
@nuin 
OK, the "Gene:WBGene####" problem is now fixed, but most genes are still not formatted properly. If I do the query for C. elegans genes:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc"> <constraint path="Gene.organism.name" op="==" value="Caenorhabditis elegans"/> </query>`

I get this page of results:

![screen shot 2017-02-08 at 11 35 13 am](https://cloud.githubusercontent.com/assets/611382/22754009/ef6be76c-edf2-11e6-9102-771d423f2fc3.png)

Note that there are several genes with nonsensical Gene IDs (e.g. 176909, 2565696, etc.), some with sequence names in the Gene ID column (e.g. B0303.5, C13B9.1, F55A11.4, etc.) and for the genes with proper WB Gene IDs (e.g. WBGene00000001, WBGene00000002, etc.) the sequence name is in the "Gene Name" field when it should be in the "Sequence Name" field and each of the genes displayed (WBGene00000001 through WBGene00000010) all have gene names if you hover the cursor over the gene ID (e.g. "aap-1" for WBGene00000001) but those gene names are not displayed in the Gene Name column.

**Comment by nuin** [comment]
@chris-grove My main guess is the genes with IDs like 176909 are coming from Panther, I will build without it and see. The name and sequence name are indeed coming from GFF3 and I will double check. Thanks.

**Comment by chris-grove** [comment]
@nuin 
OK, thanks!

**Comment by nuin** [comment]
New build and the *strange* genes are gone. I am working on a GFF load to start the full build. Probably Panther won't be added this time.

**Comment by chris-grove** [comment]
@nuin 
Cool! Thanks!

**Comment by nuin** [comment]
Hi @chris-grove, did some adjustments and it seems that things changed in the loading data. Let me know how is it and I will start a full build, as for some of the other issues I need more data loaded in the db.

<img width="1666" alt="screen shot 2017-02-08 at 11 37 20 pm" src="https://cloud.githubusercontent.com/assets/6273/22772019/7c4f2f04-ee57-11e6-831b-2eae50815552.png">

**Comment by chris-grove** [comment]
@nuin 
Much better, thanks! Almost perfect; there's a few minor issues remaining; I can put these in another ticket if needed:

1) Uncloned genes, like the WBGene00000011 in your screenshot, don't have a sequence name (which is correct), but should have a gene name. In the case of WBGene00000011, the gene name should be "abc-1". You can see this when you click on the ID. The same is true for other uncloned genes I noticed (e.g. WBGene00000078/adp-1, WBGene00000091/age-2, WBGene00000278/cad-1)

2) There are genes for which the database has a sequence name, but no public gene name of the form "xyz-1"; for example WBGene00000263. This is normal, but this gene shows up in the WormMine table with the Gene ID and the sequence name correct, but lists the gene ID (WBGene00000263) as the "Gene Name". In these cases, the "Gene Name" should be the same as the sequence name; in the case of WBGene00000263 that would be F23H11.5. The same is true for WBGene00000308, WBGene00000310, and WBGene00000311. I hope that's clear.

**Comment by nuin** [comment]
hi @chris-grove 

Thanks again for the report. I checked both issues on the current GFF3 that we have, as most of this information is coming from this file, I have to find a way to get this data from some other source(s):

1. The only mention of WBGene00000011 in the unprocessed GFF3 are 

```
III     Oligo_set       reagent 1274    1333    .       -       .       Target=GPL8304_CE_WBGene00000011_A 1 60 +

III     Oligo_set       reagent 2888    2947    .       -       .       Target=GPL8304_CE_WBGene00000011_B 1 60 +
```
and we are currently not using `Oligo_set` lines in the load.

2. The same is partially true to WBGene00000263. The second line below is the one used to load the data into WormMine, and the gene name is set as `WBGene00000263`

```
III     operon  operon  900138  910589  .       -       .       Name=CEOP3048;genes=WBGene00000263,WBGene00017759,WBGene00017760,WBGene00017763
III     WormBase        gene    909957  910589  .       -       .       ID=Gene:WBGene00000263;Name=WBGene00000263;sequence_name=F23H11.5;biotype=protein_coding;Alias=F23H11.5
III     WormBase        mRNA    909957  910589  .       -       .       ID=Transcript:F23H11.5;Parent=Gene:WBGene00000263;Name=F23H11.5;wormpep=WP:CE09613
III     Oligo_set       reagent 910118  910177  .       -       .       Target=GPL13394_WBGene00000263 1 60 +
III     Oligo_set       reagent 910127  910186  .       -       .       Target=GPL8304_CE_WBGene00000263_C 1 60 +
```

Changing number 1 might be possible with code, but number 2 might require a change in the GFF3 generation.

Thanks again.

**Comment by chris-grove** [comment]
@nuin 
OK, thanks for checking. I would have assumed that much of the gene identity information would have been pulled in from ACEDB, not just GFF. Are we getting any gene info from ACEDB? Names, IDs, etc.? We would of course want to merge records when the WBGene ID from ACEDB and the ID from GFF match. This data import shouldn't rely solely on GFF.

**Comment by scottcain** [comment]
Uncloned genes are the problem with using GFF as the primary source of data, since uncloned genes don't have a location (duh), which is what you need to appear in a GFF file.  I imagine there is a way to get around this (some supplemental file that has uncloned genes in it that gets loaded at the same time as the GFF).  I imagine there is an xml format that is used for this purpose.

Problem 2 is a problem with how the GFF is constructed.  The Name attribute of WBGene00000263 is "WBGene00000263", which explains the Gene Name entry.  Is it possible that a preprocessing rule of removing Name attributes when the value of the ID == "Gene:" + the value of the Name would do the trick?  I imagine having the Name like that for genes without a public name is on purpose, and in fact was probably done for GBrowse, but it seems to me that it shouldn't be that way (but I wouldn't want to remove it since we and perhaps people outside of WormBase probably have code that depends on it being that way).

**Comment by scottcain** [comment]
I'm pretty sure there are no tools for pulling data from ACEDB, but there is a tool for using GFF.

**Comment by nuin** [comment]
@scottcain Solution for `1` would be to merge the data of gene after GFF3, is this data is available on the gene.xml file.

**Comment by scottcain** [comment]
@chris-grove Of course @nuin is right--and you'd think I know that, since I've created some of the xml dumps from acedb.  I would think the appropriate info for unmapped genes is in there but we'll double check and figure out why.  I'll also add on of the unmapped genes to our test data set.

**Comment by tharris** [comment]
Yes info on uncloned genes should be drawn from the xml dumps of the gene class. GFF only has features that have been placed on the physical map.

**Comment by tharris** [comment]
And instead of conditionally deciding if a gene is cloned or uncloned, you might just fetch the public name, the sequence name, the locus name and so on directly from the xml dumps for all genes. Then you don't have to worry about it.

**Comment by nuin** [comment]
GFF3 is coming before all AceDB loads, so this info might not be loading correctly from the AceDB files. The best course of action is to try each step separately and then check what is going where.

**Comment by nuin** [comment]
Both steps seem fine and adding data incrementally. Usually, InterMine overwrites data from one source after a step is completed, that's why the sequence of loads is important. One possibility is that some genes that are not in our small dataset have their data only sourced from GFF3 and thus incomplete. I will start the full build and see what happens.

**Comment by khowe** [comment]
@scottcain in constructing the GFF, we assume that the ID field has no meaning, and is there purely to be able to link parent/child features, split features etc. The fact that we use things like "Gene:WBGene0000XXX" is for convenience only. We could have used numerical ids. I therefore think it's wrong for apps consuming GFF3 to attempt to place any meaning on the ID attribute (although I appreciate many do). 

Given that then, we therefore use the Name attribute to store the primary identifier of the feature - which for genes, is always the WBGene id. We use other WB-specific attributes to capture the plethora of other names for genes.

**Comment by tharris** [comment]
@nuin can't you merge data later? I recall doing that with secondary data sources. Just had to make sure that the integration keys were specified correctly. Easier than creating big monolithic loaders

**Comment by scottcain** [comment]
@khowe You are absolutely right: assuming IDs have no meaning is definitely the right thing to do.  Unfortunately, both creators and consumers of GFF3 from many sources don't live by the same code (which is to say, they ignore the specification).  One would hope that turning this behavior off would be easy/possible.

**Comment by nuin** [comment]
@chris-grove I have a full build ready and it solves the error of a gene with no sequence name but with an actual gene name. Also the gene without a gene name but with a sequence name seems corrected in this one. Please check and let me know, same URL for testing.

**Comment by chris-grove** [comment]
@nuin 
OK, yes, those last issues I raised are now fixed. Thanks!
The last thing I still notice is that if I set the filter on both the Gene Name column and the Sequence Name column to "IS NULL", I get a list of 46 genes that have neither Gene Name or Sequence Name in WormMine, although they all seem to be uncloned genes that do have a gene name in WormBase:

![screen shot 2017-02-10 at 11 30 51 am](https://cloud.githubusercontent.com/assets/611382/22841012/ad04cd38-ef84-11e6-83d9-55df78002a5b.png)

**Comment by chris-grove** [comment]
@nuin 
Another thing (and let me know if you want this in a separate ticket): If I query for all genes regardless of species:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <join path="Gene.organism" style="OUTER"/>
</query>`

I get a large number of genes whose "Gene ID" is of the format of a transcript name (which is like a sequence name except sometimes has an 'a' or 'b' at the end to denote different transcript isoforms from the same gene):

![screen shot 2017-02-10 at 11 44 13 am](https://cloud.githubusercontent.com/assets/611382/22841405/5630e24c-ef86-11e6-9bd0-28ff4328b170.png)

I have a suspicion that these are coming from the RNAi objects and this is related to my earlier ticket #5214

**Comment by nuin** [comment]
@chris-grove Addressing the genes with no name and sequence name, I can see some of the on the AceDB XML only and not on GFF3. They do have a name in the XML and I would need to check why the name is not loaded. Can you open a ticket with this error? Thanks.

**Comment by nuin** [comment]
@chris-grove Regarding the error with genes with IDs like ` 2L52.1a`, it seems the error might be from other sources. I am checking where it is coming from, it should be straightforward to see its history in the DB, and if you can open another ticket, please do so. I am closing this one and will work on the subsequent tickets ASAP.

**Comment by chris-grove** [comment]
@nuin 
Sure thing.

**Comment by nuin** [comment]
Thanks, Chris, much appreciated.
