### ISSUE TITLE
I am doing a BLAST with one of my proteins of inte...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5386]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am doing a BLAST with one of my proteins of interest and many of the residues of may protein are marked a "X". What does that mean?

**Reported by:** Carl** (cvil**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run#hit_anchor_C25B8.1a_1">http://www.wormbase.org/tools/blast_blat/run#hit_anchor_C25B8.1a_1</a>
**Browser:** Chrome 55.0.2883.87

**Comment by chris-grove** [comment]
Hi Carlos,


 You probably have the "Filter" checkbox selected at the input screen which acts to mask out any regions deemed to be regions of low complexity (i.e. repeats). If you want to see the BLAST results without the "X"s, uncheck the "Filter" box and rerun the BLAST.


Best,


Chris Grove

WormBase
