### ISSUE TITLE
  Hi, We were trying to use CALTECH SPE...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5387]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>We were trying to use CALTECH SPELL server for some gene expression data mining. Looks like it's not working now. Please look into this matter at the earliest.<br/>Thanks,<br/>Vinod</p>

**Reported by:** Vino****** (vkm2**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by raymond91125** [comment]
Hi Vinod,

spell.caltech.edu appears to be be working now. Please give it another 
try. Let us know if you encounter more issues.

Thanks.

Raymond

On 01/30/2017 12:40 PM, no-reply@wormbase.org wrote:
> Everything's broken!
>
>   Hi,
> We were trying to use CALTECH SPELL server for some gene expression 
> data mining. Looks like it's not working now. Please look into this 
> matter at the earliest.
> Thanks,
> Vinod
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5387. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5387>.
>
> Reported by: Vinod Mony (vkm2e@virginia.edu)
> 30 Jan 17 20:41
>
> Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/49.0.2623.112 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
