### ISSUE TITLE
  I note that gene D2005.1 is described...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5388]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I note that gene D2005.1 is described as an ortholog of human TARBP2.  However, as far as I can tell it has no significant sequence homology to TARBP2 (or visa versa)</p><p>What were you doing? <br />&nbsp;&nbsp;I was reviewing a grant proposal that is proposing experiments with this gene, and I sort of have to know if it is really likely to be involved in the RISC complex.</p>

**Reported by:** Chri****** (link**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by epaule** [comment]
that orthology has been predicted by pantherdb.
While their gene page (http://www.pantherdb.org/genes/gene.do?acc=HUMAN|HGNC=11569|UniProtKB=Q15633) shows only a Chimpanzee ortholog, their flatfile (that we import) from ftp://ftp.pantherdb.org/ortholog/11.1/RefGenomeOrthologs.tar.gz contains that line:
HUMAN|HGNC=11569|UniProtKB=Q15633	CAEEL|WormBase=WBGene00008397|UniProtKB=Q93412	O	Bilateria	PTHR10910

**Comment by epaule** [comment]
sent the feedback to panther
