### ISSUE TITLE
Hello, I am developing an online tool that current...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5390]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I am developing an online tool that currently uses wormbase REST api, however I am planning on expanding it and making it a public tool. It produces multiple HTTP requests (hundreds per submisison) to the wormbase REST API. Would I need to download the wormbase database and query that instead for this kind of tool? if so, could I run the wormbase rest api server on that local instance of the database  so that I can keep my queries the same and not abuse wormbase online REST api?

Many thanks, please contact me if you would like to clarify anything I've said as well. 

Laurence

**Reported by:** Laur*********** (lene****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 55.0.2883.95

**Comment by tharris** [comment]
User contacted with details on acceptable use and provisioning of API services.
