### ISSUE TITLE
  Hi, Quick question, how do we grab se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5394]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>Quick question, how do we grab sequence from the new genome browser? In the old system we used to highlight a section and a window would pop up and give us download options.<br/>Thank you,<br/>visitor_name</p>

**Reported by:** Iash* (iash***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by chris-grove** [comment]
Hi Iasha,


 In JBrowse, if you turn on the track called "Reference Sequence", you can click on the drop down menu on the track title and choose "Save track data". Then you can view or save the sequence for the indicated region.


To specify (and zoom to) a specific region, you can click and drag along the top of the JBrowse view (where the bp position numbers are displayed).


Let us know if you have any more questions.


Best,


Chris Grove

WormBase
