### ISSUE TITLE
The C. brenneri gene Cbn-unc-2 appears to be wrong...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5397]
*Help Desk query collected when no chat operators were online. Follow up required.*

The C. brenneri gene Cbn-unc-2 appears to be wrongly annotated. Given its homology and location (upstream of srtx-1) I would suggest that this gene is in fact Cbn-egl-19

**Reported by:** Step*********** (nurr**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_brenneri/gene/WBGene00194574#0gfe-69cd41-3">http://www.wormbase.org/species/c_brenneri/gene/WBGene00194574#0gfe-69cd41-3</a>
**Browser:** Firefox 51.0

**Comment by gw3** [comment]
The C. brenneri gene Cbn-unc-2 now has now been extended by several exons.
This new gene structure should be available in release WS259.
The name change will be considered by our nomenclature experts shortly.

Gary Williams

**Comment by tuli** [comment]
@epaule 
Gary advised that you said I should look at this. 

Cbn-unc-2 was assigned by you in 2008 when it was first imported from NGASP. 

There is no elegans ortholog so the name unc-2 would not have been chosen by me. 

It is not connected by orthology to egl-19

Do you have any comments to add?

**Comment by epaule** [comment]
Not many:
Considering that in 2008 that gene appeared as ortholog, I would guess it
was "jigsawed" into the bit that you could see until WS258. And I am hoping
that Gary's work will make it appear again as unc-2 ortholog. If you want,
you can wait with the naming until C.brenneri went through a build to
confirm that, but it might take a while (I think WS259 will be a C.briggsae
/ S.ratti combo, so it will happen earliest for WS260).

M

**Comment by tuli** [comment]
@epaule would you mind replying to the user, you have more expertise in ortholog naming than I do.

**Comment by epaule** [comment]
I just borrowed the updated sequence from the curation database and it
looks way more similar to egl-19 than unc-2.
So I would propose to follow his proposal of changing the name to
Cbn-egl-19.

M

**Comment by gw3** [comment]
Hi Stephen,

I had a quick look at the updated gene sequence and you are right with the
Cbn-egl-19 homology.

best regards,

Michael
