### ISSUE TITLE
  Hi, mi name is visitor_nameGabriela A...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5400]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, mi name is visitor_nameGabriela Acosta, i want to know how did you get all the gene sequences of brugia malayi??? if its all genome is sequenced??? I study with UGGT (UDP-glycosyl transferase) and im searching the different species that have this enzime and also if they have the two isoforms or just one! that is why its important to know if the entire brugia malayi genome is known! thank you for the help! visitor_name</p>

**Reported by:** Ana  (gaby**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
we do have the new v4 genome assembly for Brugia malayis, that is available from WormBase (http://www.wormbase.org/species/b_malayi) that is 97.58% complete according to CEGMA (which is 0.9% more than the old v3). In addition we scaffolded the chromosomes based on optical mapping, so it has a lot less redundancy than the old one and more contiguous sequence.

So no, 100% of the genome is not know, but it is one of the more complete ones of the nematode genomes.
Have also a look at: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0027025 which describes the two uggt genes in C.elegans.

You can see predicted "completeness" in that table here: http://parasite.wormbase.org/species.html based on CEGMA as well as BUSCO.

I also just had a quick look at the Bma-uggt-1 gene and it looks like the 3'-end of the 24th exon was a bit off, so I just fixed it and it will go into one of the next WormBase releases.

You can also see a orthology tree here: http://parasite.wormbase.org/Brugia_malayi_prjna10729/Gene/Compara_Tree?g=WBGene00224465

One thing the tree shows is a potential loss of one uggt copy in the clade 3 nematodes, but you might want to further investigate that.
