### ISSUE TITLE
  Is it possible to get the list of all...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5402]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is it possible to get the list of all WormBase entities which have other names or synonyms? Mainly we're looking at neurotransmitters (including neuropeptides) and receptors.</p><p>What were you doing? <br />&nbsp;&nbsp;Contributing to OpenWorm.</p>

**Reported by:** Chri* (cbar*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
considering we store quite a lot of different classes (and their entities) in our database, could you be more specific?

As examples of data already preprocessed into flatfiles, we got: 
* per species identifiers (gene centric) ftp://ftp.wormbase.org/pub/wormbase/releases/WS257/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS257.xrefs.txt.gz
* a collection of alternative names for C.elegans genes ftp://ftp.wormbase.org/pub/wormbase/releases/WS257/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS257.geneOtherIDs.txt.gz

we also got various data mining tools (WormMine / ParaSiteMart / SimpleMine ) to cover some less common data types.

**Comment by epaule** [comment]
if you just want them for genes, you can easily get them from a.e. the files I sent the urls for.
As we release our database every two months, the data will be stable during that time. So you would get a lot of speed by using the flatfiles (plus they are quite small).

We do use an object storage system as our "database", so there is no table schema, only class definitions. The definitions reside here: https://github.com/WormBase/wormbase-pipeline/blob/master/wspec/models.wrm It might be a bit confusing, you can see that not only genes, but also other classes have secondary identifiers, etc.
