### ISSUE TITLE
Hello, the sequence for this transposon appears to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5405]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, the sequence for this transposon appears to be badly wrong, can you take a look please? Thanks

**Reported by:** Luke****** (lmn3********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/sequence/Y51H4A#04--10">http://www.wormbase.org/species/c_elegans/sequence/Y51H4A#04--10</a>
**Browser:** Chrome 55.0.2883.95

**Comment by Paul-Davis** [comment]
Dear Luke,

Thank you for contacting WormBase, could you clarify which Transposon 
sequence is incorrect? You submitted your ticket from a C. elegans 
genomic YAC clone used by the C. elegans Sequencing Consortium when 
generating the reference genome.

Thanks

Paul


On 08/02/2017 00:22, no-reply@wormbase.org wrote:
> offline chat Hello, the sequence for this transposon appears to be 
> badly wrong, can you take a look please? Thanks
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/sequence/Y51H4A#04--10 
> http://www.wormbase.org/species/c_elegans/sequence/Y51H4A#04--10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/sequence/Y51H4A#04--10> 
>
>
> This issue has been assigned ticket number: #5405. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5405>.
>
> Reported by: Luke Noble (lmn3@nyu.edu)
> 08 Feb 17 00:20
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
User made a mistake about the context of the parent sequence connected to the WBTransposon

**Comment by Paul-Davis** [comment]
User made a mistake about the context of the parent sequence connected to the WBTransposon
