### ISSUE TITLE
C.briggsae FPKM graphs

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5407]
It looks like the FPKM graphs for C.briggsae are not being rendered.

http://www.wormbase.org/species/c_briggsae/gene/WBGene00029008
![image](https://cloud.githubusercontent.com/assets/20523/22736661/2bf4cfc4-edf7-11e6-8b02-ae0ab9735b47.png)

**Comment by epaule** [comment]
seems tp affect more than just C.briggsae

**Comment by sibyl229** [comment]
Hi @epaule I tried the link you posted. The FPKM graphs is working for me at the moment. Does it work for you? If not, does it work on any gene page at all? Thanks!

**Comment by epaule** [comment]
yes, it works now.
