### ISSUE TITLE
Hello,
I am looking for an option to download all ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5408]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I am looking for an option to download all the search results that I receive, for example:
I am searching all the strains of C .elegans that the mutants are sterile at specific temperature- CF512 

Is there an option to download all the search results in tub delimited or excel file.

Thank you,
visitor_name

**Reported by:** Ayal* (ayal****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001037#0--5">http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001037#0--5</a>
**Browser:** Chrome 56.0.2924.87

**Comment by gw3** [comment]
Assuming that you are using WormMine for your searches, you can easily download a file suitable for use in Excel.

When your WormMine search is complete and you are looking at the page of columns of results, look at the top right of the screen and you will see a button labelled "Export".

Clicking on "Export" brings up a window which allows you to select the file-name and the format (TSV = tab separated values, CSV = comma separated values) either of which can be read by Excel.
