### ISSUE TITLE
  how do get protein sequence for C. el...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5410]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do get protein sequence for C. elegans? i need hsp70 induciable protein sequence</p>

**Reported by:** char*********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by chris-grove** [comment]
Hello Charles,


 Could you specify what protein sequences you are looking for? There are a number of Hsp70 proteins in C. elegans. What do you mean by hsp70-inducible protein sequence?


Best,


Chris Grove

WormBase
