### ISSUE TITLE
  I need to show my students the Pedigr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5411]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I need to show my students the Pedigree Cell Browser. In previous years, I showed something like this:<br/>http://www.its.caltech.edu/~wormbase/userguide/MoreSearches/Cell/<br/>But now I am not able to see where I can do it within your website.</p><p>What were you doing? <br />&nbsp;&nbsp;I visit your website to show the potential or C. elegans to my students.
I need to show the Pedigree Browser but I cannot find it any more.</p>

**Reported by:** Manu************ (Manu***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Manuel,

Thank you for contacting WormBase, the view has changed slightly since 
that user guide was written, but the data can be accessed via our 
Ontology browser.

http://www.wormbase.org/tools/ontology_browser

Anatomy Ontology -> Cell

Paul





On 09/02/2017 11:44, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I need to show my students the Pedigree Cell Browser. In previous 
> years, I showed something like this:
> http://www.its.caltech.edu/~wormbase/userguide/MoreSearches/Cell/
> But now I am not able to see where I can do it within your website.
>
> What were you doing?
>   I visit your website to show the potential or C. elegans to my 
> students. I need to show the Pedigree Browser but I cannot find it any 
> more.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5411. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5411>.
>
> Reported by: Manuel P. Alonso (Manuel.Alonso@uv.es)
> 09 Feb 17 11:44
>
> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) 
> Chrome/56.0.2924.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi,

You may want to browse the Lineage branch of the ontology. The 
relationship is built on nuclei.

Cheers,

Raymond
