### ISSUE TITLE
  How can I retrieve nematode specific ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5413]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I retrieve nematode specific genes with no homology to mammals?<br/>A similar question is posted in the WormMine FAQs but the answer reads:<br/>"/// out dated (Raymond 20080214) /// From the "advanced query" WormBase page, construct the following query:<br/>find predicted_gene NOT Pep_homol"<br/>Thanks!<br/>Patricia</p>

**Reported by:** Patr*************** (bern**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
the easiest way is to use the ParaSite BioMart (http://parasite.wormbase.org) and put a filter in with "Restrict results to genes without orthologues in..." with the species of choice.
While we do not have a comprehensive set of mammalian genomes, the usual model organisms are present (zebrafish, mouse,...).
