### ISSUE TITLE
Uncloned genes missing gene name in WormMine im-257

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5415]
A carry-over from #5385 

In WormMine, 48 C. elegans genes have a WBGene ID, but have no gene name nor sequence name. This can be seen with this query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B and C">
  <constraint path="Gene.organism.name" code="A" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.secondaryIdentifier" code="B" op="IS NULL"/>
  <constraint path="Gene.symbol" code="C" op="IS NULL"/>
</query>`

All of the genes I have checked from this list have a gene name on WormBase. These are uncloned and do not have a sequence name.

**Comment by nuin** [comment]
Hi @chris-grove 

I rechecked this issue and the "error" seems to be on the GFF file that has nothing assigned to these genes. Most of the information like names and chromosomes come from the GFF and not from the XML.

One example (this is the raw GFF file, not pre-processed
```
➜  raw git:(im-259) ✗ grep WBGene00000141 c_elegans.PRJNA13758.WS259.gff
➜  raw git:(im-259) ✗ grep WBGene00000140 c_elegans.PRJNA13758.WS259.gff
I       WormBase        gene    4321095 4359080 .       +       .       ID=Gene:WBGene00000140;Name=WBGene00000140;locus=anc-1;sequence_name=ZK973.6;biotype=protein_coding;Alias=anc-1,ZK973.6
I       WormBase        mRNA    4321095 4359080 .       +       .       ID=Transcript:ZK973.6;Parent=Gene:WBGene00000140;Name=ZK973.6;wormpep=WP:CE33588;locus=anc-1
I       deprecated_operon       operon  4321095 4362548 .       +       .       Name=CEOP1922;genes=WBGene00000045,WBGene00000140
I       Oligo_set       reagent 4358797 4358856 .       +       .       Target=GPL8304_CE_WBGene00000140_A 1 60 +
I       Oligo_set       reagent 4358806 4358865 .       +       .       Target=GPL13394_WBGene00000140 1 60 +
I       Oligo_set       reagent 4358891 4358950 .       +       .       Target=GPL8304_CE_WBGene00000140_B 1 60 +
```

What do you think is the best course of action to have these genes added to the GFF file? I can ask @tharris and @scottcain, but I don't know how the GFF is generated.

**Comment by chris-grove** [comment]
@nuin 
These genes will not (and cannot) come from the GFF file (as far as I'm aware), as they are uncloned genes and have no physical position in the genome; they're only identified and named by the fact that they cause a phenotype and the responsible locus still has not been identified on the genome. I'm pretty certain that they will need to come in from ACEDB.

**Comment by nuin** [comment]
Easier way, then,  would be to create a separate step to load this information for these genes. I think because the locus doesn't exist, when the Gene.xml is loaded at the merge the symbol in the table (locus or gene name, i.e. anc-1) is not updated or doesn't merge correctly. I can add "manually" the information after the build, as the list of genes is not that big.

**Comment by nuin** [comment]
Sorry, closed by mistake. Reopened.

**Comment by chris-grove** [comment]
@nuin 
I'm just checking old tickets to close those that no longer apply. This one still applies to WS262. Still a ~minor issue.

**Comment by chris-grove** [comment]
Resolved. Closing.
