### ISSUE TITLE
Many genes in WormMine have Gene ID field populated by transcript names

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5416]
Carry-over from issue #5385 

If I query for all genes regardless of species:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <join path="Gene.organism" style="OUTER"/>
</query>`

I get a large number of genes whose "Gene ID" is of the format of a transcript name (which is like a sequence name except sometimes has an 'a' or 'b' at the end to denote different transcript isoforms from the same gene):

![screen shot 2017-02-10 at 11 44 13 am](https://cloud.githubusercontent.com/assets/611382/22841405/5630e24c-ef86-11e6-9bd0-28ff4328b170.png)

I have a suspicion that these are coming from the RNAi objects and this is related to my earlier ticket #5214

**Comment by chris-grove** [comment]
@nuin 
Is there any update on this issue? I just had to do a lot of manual clicking to disambiguate when uploading a list to WormMine because of these genes with Gene IDs (primary identifiers) that are of the form of Sequence Names (secondary identifiers).

**Comment by nuin** [comment]
I started reverse engineering the template in order to isolate the problem and I am still not done after working on some other issues that showed up. I will restart this week.

**Comment by chris-grove** [comment]
@nuin 
OK thanks

**Comment by nuin** [comment]
Hi @chris-grove, I noticed that this error is being caused by RNAi data loading. I will work on a couple of other issues and get back to it soon.

**Comment by nuin** [comment]
Hi @chris-grove 

I recreated the mappings for RNAi and it seemed to work. Please take a look again at the query on im-259.wormbase.org. This is a limited dataset, so not all IDs and other info will be there.

**Comment by chris-grove** [comment]
@nuin 
OK, these gene objects are now gone on im-259. Thanks!

**Comment by nuin** [comment]
Thanks Chris!
