### ISSUE TITLE
FTP server behaviour

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5417]
![image](https://cloud.githubusercontent.com/assets/20523/22881320/d6dc71aa-f1dd-11e6-9930-219e489981e4.png)

it seems like the ftp server asks for authentication which breaks the UCSC hub

**Comment by epaule** [comment]
thanks for fixing it.

**Comment by epaule** [comment]
I thought it was solved, but it reappeared :-(

**Comment by tharris** [comment]
Nothing has changed with configuration of the FTP server in years. You can connect without authentication as a guest.

**Comment by epaule** [comment]
Currently yes, but yesterday neither me nor UCSC could (as the screenshot above shows). Luckily it only affected the American side of the UCSC users ;-)

**Comment by tharris** [comment]
So it's working now?  Because again, nothing has changed with the ftp server in a very long time. :)

**Comment by epaule** [comment]
yes, and it might be related to #4426  #1533 and #854

**Comment by tharris** [comment]
So then it's working now and the issue can be closed?

**Comment by epaule** [comment]
I think it would be good if you could have a look in the FTP logs if there
was something "special" yesterday (too many connections, etc), but if you
want you can close the ticket.
