### ISSUE TITLE
  find a 100,000 base pair region inclu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5418]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;find a 100,000 base pair region including a globin gene on C. briggsae chromosome I within position 200,000-300,000? </p><p>What were you doing? <br />&nbsp;&nbsp;This is for my Genomics Class & we're learning how to use your site. </p>

**Reported by:** Don (dlt2***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by chris-grove** [comment]
Email sent:

"You'll want to go to:

http://www.wormbase.org/tools/genome/gbrowse/c_briggsae_PRJNA10731/

and specify the location as:


I:200,000..300,000

making sure you have the "Genes" track turned on. Then you can look at the gene names in that region. You should find what you're looking for."
