### ISSUE TITLE
RNAi phenotypes missing from WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5419]
From user:

"Dear WormBase staff

I am trying to use Wormmine to mine RNAi results using the QueryBuilder function, however, in the "RN Ai Result" section I cannot find any phenotype information to show. Please see the attached image for details. Please advise how to extract the phenotype information of RNAi experiments. Thanks a lot! In addition, there is a small error in the name of the RNAi section, there is a space between N and A."

**Comment by nuin** [comment]
Hi @chris-grove 

Seems phenotype is showing on query builder, please check. Thanks

**Comment by chris-grove** [comment]
@nuin 
The problem is that phenotypes associated with RNAi experiments are not being populated. There should be phenotypes under the RNAi model, but they are not there. The RNAi model also seems to have shrunk considerably on im-259 compared to the current live WormMine.

**Comment by nuin** [comment]
As I mentioned in the other ticket, I changed the mapping and I removed some entries, that I might need to re-add. I will double check and update here. Thanks, Chris.

**Comment by nuin** [comment]
Hi @chris-grove 

Would you mind checking again? This is small dataset build so data is constrained.

Thanks

**Comment by chris-grove** [comment]
@nuin 
OK, there are phenotypes for RNAi objects now. I realize that it's a limited dataset so I shouldn't expect there to be all phenotypes for a gene, but so you know, when I check for RNAi phenotypes for the gene unc-26 (i.e. if I filter for the Gene ID of the inhibited gene to contain "JC8.10", which for the record should be "WBGene########" as mentioned in ticket #5214 ) I get several phenotypes that are actually NOT observed by RNAi (assayed for but not observed). We will need to distinguish between observed and NOT observed phenotypes as we currently do for alleles. Also, we will want to provide users with the primary name of the phenotype in addition to the WBPhenotype ID.

**Comment by nuin** [comment]
Thanks Chris, I am running a new build and should have a new class differentiating between phenotype and phenotype not observed. There still won't be a link back to an actual phenotype name, but I will be working on it. I will let you know when the build is done and I will need to revert to a full build to work on expression stuff that is pending.

**Comment by chris-grove** [comment]
@nuin 
OK, sounds good. Thanks!

**Comment by nuin** [comment]
The build is complete, the table has the column, but I don't see the data or the field in the query. I will discuss with in InterMine and get back to you next week.

**Comment by chris-grove** [comment]
@nuin 
OK. It looks like now only observed phenotypes are showing up in the "Phenotype" column for RNAi objects, whereas RNAi objects with not_observed phenotypes are showing a blank field, which is what we would expect once the Phenotype Not Observed column is being displayed. So, it's looking better.

**Comment by nuin** [comment]
One step at a time Chris, slowly but surely. I will anyway clear things with InterMine people. Thanks a lot for all the help.

**Comment by chris-grove** [comment]
Yep! Sure thing, sounds good

**Comment by chris-grove** [comment]
OK, I didn't realize this was addressed, but it appears to now be resolved in the live WormMine. Closing. Thanks!
