### ISSUE TITLE
  Person lineage graph is showing blank...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5420]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Person lineage graph is showing blank, e.g. http://www.wormbase.org/resources/person/WBPerson1562#2--10<br/>staging site works.</p>

**Reported by:** Raym*** (raym**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by azurebrd** [comment]
It works on juancarlos.wormbase also, I don't have access to see what's happening on the live site.

**Comment by ceciliaWBPerson1** [comment]
It works in stage site WS257
http://staging.wormbase.org/resources/person/WBPerson241#012--10

But it does not work in live site WS257
http://staging.wormbase.org/resources/person/WBPerson241#012--10

**Comment by tharris** [comment]
Possibly resolved by recent JS fix?  Please re-test -- it looks okay to me now.

**Comment by ceciliaWBPerson1** [comment]
Thanks! it works now.
c
