### ISSUE TITLE
  No tree displayed when asked.  What w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5421]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;No tree displayed when asked.</p><p>What were you doing? <br />&nbsp;&nbsp;Asking for tree display for ETS-5 gene, on a Ubuntu 16.10 system, through Firefox browser 51.0.1 64bit</p>

**Reported by:** pogn*************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by tharris** [comment]
sgifaceserver restarted.  Problem resolved and user contacted.
