### ISSUE TITLE
Malformed ID names

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5423]
The following Author class names appear to be malformed:

"Author", "HE/Baillie"
"Author", "RKH/LA"
"Author", "Zenteno-Savi;n T"

The following Clone class name appears to be malformed:

"Clone", "SG25/36!"

**Comment by chris-grove** [comment]
@gw3 
I'm looking into the malformed author names with @vanaukenk 

As for the "SG25/36!" clone name, I can see the name in our autocomplete options when entering a clone name in our curation tools, but I can't find any actual annotation that refers to it. Do you have any more information about where this clone name is coming from?

**Comment by gw3** [comment]
@chris-grove

We've found the "SG25/36!" clone name in our data.
It looks like it is a valid name that is a duplicate of Clone "SG25/36" 
from before 1998, so we will leave it in the database.

Gary

**Comment by gw3** [comment]
@chris-grove


'HE/Baillie' and 'RKH/LA' are from geneace - sorry for passing you those!
I'll inform the appropriate person :-)

'Zenteno-Savi\;n T' is from the CalTech Author and Paper data:

Author : "Zenteno-Savi\;n T" -O "2017-01-16_11:56:47_wormpub"
Paper    -O "2017-01-13_11:05:45_kimberly" "WBPaper00013182" -O 
"2017-01-13_11:05:45_kimberly"

Paper : "WBPaper00013182" -O "2017-01-13_11:05:45_kimberly"
Author   -O "2017-01-13_11:05:45_kimberly" "Zenteno-Savi\;n T" -O 
"2017-01-13_11:05:45_kimberly"

Gary

**Comment by chris-grove** [comment]
@gw3 
OK, thanks for clarifying  ;)

It looks like the Zenteno-Savin surname has a ´ accent on the "i"; I'm not sure if that was trying to be captured. I'll wait to hear from @vanaukenk
