### ISSUE TITLE
visitor_name (elvisitor_namemartinez@gmail.com): H...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5424]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (elvisitor_namemartinez@gmail.com): Hello, I was wondering if it was possible to see all the hits on a million mutation strain</br>visitor_name (elvisitor_namemartinez@gmail.com): or download it in table form with the protein effect</br>visitor_name (elvisitor_namemartinez@gmail.com): predicted protein effect might be more precise

**Reported by:** luis (ellu********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006830#0db463-9gf78c-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006830#0db463-9gf78c-3</a>
**Browser:** Safari 10.0.2

**Comment by chris-grove** [comment]
Hello Luis,


 If you go to the strain page, like this one:


http://www.wormbase.org/species/c_elegans/strain/VC20386#01--10


You can find this information in the "Contains" widget. To download the data, including the list of alleles, their effects, and which gene they are associated with, click on the "Save table" button at the upper right of the table and choose a download format option.


Let us know if you need anything else.


Best,


Chris Grove

WormBase
