### ISSUE TITLE
  How do I identify a worm homolog/orth...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5426]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I identify a worm homolog/ortholog for a human gene?</p>

**Reported by:** Lorr*********** (Lorr*********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by tuli** [comment]
Hi Lorraine

Put in the name of the human gene of interest in the upper right hand search box in WormBase and choose ‘All’ from the drop-down (the first choice) which reverts to an ‘anything’ search.  You will get a results page which will have lot of relevant data, including orthology relevant data.
I don’t think there is a more targeted search for this, from the website.  

You could also put in something like, for example ‘p53 ortholog’ in WormMine, http://im-254.wormbase.org/tools/wormmine/begin.do, in the ‘Search’ box and you will get a list of relevant data, which again may not pull up the exact ortholog right at the top, but a list, which should include orthology information, if this is curated in WormBase.

Hope this helps.  My colleagues will chip in if there is a more direct way to do this.

Best
Ranjana Kishore
WormBase
