### ISSUE TITLE
Hello,

Genetics Map is not working for me 
When I...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5428]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,

Genetics Map is not working for me 
When I go to it via a gene page I get: " Sorry! an error has occurred. Gateway Time-out"
When I get through it's page it says "504 gateway time out"

I tried Mac and PC with explorer, chrome and Safari browsers. I tried at home and at work network.

Is it going to be fixed?
Is there another way to get up-to-date genetics map?

Thanks,
Sarit

**Reported by:** Sari*********** (sari*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/issue/*">http://www.wormbase.org/search/issue/*</a>
**Browser:** Chrome 56.0.2924.87

**Comment by gw3** [comment]
This now appears to work.
