### ISSUE TITLE
Subcellular compartment --> Genes template problems

### ISSUE THREAD

**Issue by nuin** [WormBase/website#5432]
The column Expression Patterns Reporter Gene is empty. What ate the expected values for this column?

**Comment by chris-grove** [comment]
@nuin 
The field actually isn't empty across all objects. If you keep the default species C. elegans and compartment "nucleus", you can filter the "Expression Patterns Reporter Gene" for "IS NOT NULL" and find 9 rows that have text. These are just free text descriptions of the reporter gene. I'll close the ticket.
