### ISSUE TITLE
Gene --> Qualifier GO Term, Evidence Code, Reference

### ISSUE THREAD

**Issue by nuin** [WormBase/website#5433]
The column GO Annotation Qualifier is empty? What are the expected values for this column if any? Are there duplicates in the output?

**Comment by chris-grove** [comment]
@nuin 
The "GO Annotation Qualifier" field is empty for the default search gene bec-1; if you query for all non-null values for the field you'll find 224 rows with entries like "contributes_to", "colocalizes_with" and "NOT":

`<query name="" model="genomic" view="Gene.symbol Gene.goAnnotation.qualifier Gene.goAnnotation.ontologyTerm.name Gene.goAnnotation.evidence.code.code Gene.goAnnotation.evidence.publications.pubMedId" longDescription="This query shows how to retrieve all GO annotations for a given gene, the evidence code for the annotation and qualifier, and the PMID for the associated reference.  pad 2016--2-24" sortOrder="Gene.goAnnotation.ontologyTerm.name asc">
  <constraint path="Gene.goAnnotation.qualifier" op="IS NOT NULL"/>
</query>`

I can't find any duplicates; it looks good. I'll close the ticket.
