### ISSUE TITLE
Protein --> CDS template problems

### ISSUE THREAD

**Issue by nuin** [WormBase/website#5434]
Are the CDS and WP prefixes required in this output?

**Comment by epaule** [comment]
I don't think the prefixes are not needed.

In our ACeDB database, the CDS also don't have any prefixes, just the proteins (WP stands for WormPep).

**Comment by chris-grove** [comment]
@nuin 
Yes, just to second @epaule 's comment: We don't need the "CDS:" prefix, but we can keep the "WP:" prefix

**Comment by nuin** [comment]
Hi

I am just reviving this old ticket, but it seems that the `CDS:` prefix (and the WP) are not coming from the GFF or the XML. I will keep checking, but if it seems OK, please close the issue.

**Comment by chris-grove** [comment]
@nuin 
The prefixes on im-259 look good. I would change the existing "Protein --> CDS" template query from:

`<query name="" model="genomic" view="Protein.CDSs.primaryIdentifier Protein.organism.name Protein.primaryAccession" longDescription="shows a mapping of protein identifiers to CDS, restricted to one species.">
  <constraint path="Protein.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>`

to

`<query name="" model="genomic" view="Protein.organism.name Protein.primaryAccession Protein.CDSs.symbol" longDescription="shows a mapping of protein identifiers to CDS, restricted to one species.">
  <constraint path="Protein.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>`

As the WormMine ID I consider to be internal and hence OK to have the extra 'CDS' prefix, whereas the sequence name of the CDS (correctly) does not have the 'CDS' prefix. The 'WP' prefix is standard and should be there for the protein's primary accession identifier.

**Comment by nuin** [comment]
@chris-grove I don't why the CDS prefix is showing up, maybe it's a labelling thing to link it to CDS page on WormBase. I will work on the template, but we will find the same problem as the expression one. I am working some ideas to make it easier to change templates and such.

**Comment by nuin** [comment]
I have a new template on http://im-259.wormbase.org/tools/wormmine/template.do?name=protein_cds_new&scope=all, please check. I will ask @tharris to remove the old one when the new is tested.

**Comment by chris-grove** [comment]
@nuin 
That new template looks good. Thanks!

**Comment by epaule** [comment]
looking good, as far as I can see
