### ISSUE TITLE
  tree display not accessible ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5436]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;tree display not accessible</p>

**Reported by:** Kare****** (kare**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by azurebrd** [comment]
@kyook which object / webpage ?

**Comment by kyook** [comment]
I was looking at strain page AB1

**Comment by azurebrd** [comment]
http://www.wormbase.org/species/c_elegans/strain/AB1#5--10

**Comment by chris-grove** [comment]
Found another example:

https://wormbase.org/species/c_elegans/strain/JU263#5--10
