### ISSUE TITLE
Information not showing properly in phenotype evidence

### ISSUE THREAD

**Issue by kyook** [WormBase/website#5437]
In the evidence column of the phenotype table, the Phenotype assay tag shows other tags rather than the actual tag data. For example on AB1 strain page, the Phenotype assay tag shows "Strain" and "Treatment" rather than the data that is stored in those tags.  For the Treatment data in Phenotype assay for the carbon dioxide response variant, the information should read "Treatment: 10% CO2"

**Comment by sibyl229** [comment]
Adam fixed this awhile back: http://www.wormbase.org/species/c_elegans/strain/AB1#03--10
