### ISSUE TITLE
  Hi, we found that there is an error i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5440]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, we found that there is an error in the sequence for allele ju476. The correct sequence is pasted below (5bp insertion in upper case with flanking region in lower case):<br/>actcaaatgaaagctctgaattttccatgaaaattatgaattttccgaaaattaggatctttaagggtagtttaaagttactgtagaaaattttaaaaatttcgaaaaattccgaaaaattttttaatttttaaaattccgaaaatttttgaaaatccataactctgtcaatttttggtattttcagctcaatattgcctaaaaatgaagataaacttttaaactttttcggaaaaccaaatcgatctctagctacagtacccctttgtggtgggaactaactaaaataaagaagtcccatgcaaaaaaaaatattagaaaactcagaaaaaggaaagagcatgcacatacgagaggagcaactgatcacaccgtgtgggacacgtgacgggctgtcacgtgtaaagaagacgggctgtccggggactgcagttgacttgttgactgacgtggagaccctccgacgtgaagctatgcgcccgtccgaccagcgaccgtcacCGTTAcgttacggtacagagtttgggagtagcaaacctggaaaatttgaggaaaatcgataaactttgagtttaaaaaaatcgaaatttttcgaaatatttgtgccaaaaattaatttcctcctcacctgttgtcctccaccattaatagctgtgcagctaccggctccagcgctccacatcccggaatcctgagaaaatccggaatccctggccggtgatccacgggccccacccagcgtctcccagtaggaccctgaatgacgtatggcgtcgttgcgtaggatttctgaaatttttctattttttttaaattgaggggaccaagagcttttagaaatgtataatcatgtcgaggtttttggaaacttgatttttttgcaaaaaattgaggtctccccgcggaaatcccgtggataatgtagccaagtagttataagtgaatcaaatatttttgccaagttgttcattaactttgctatattttgtaatacattttttggaat</p>

**Reported by:** Lewi* (lewi***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by tuli** [comment]
Dear Lewie,

Thank you for writing to WormBase.

I am consulting with the original author of ju476 before making the
change you suggest and will write back to you soon.

Best wishes,

Mary Ann

On 3 March 2017 at 21:02,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hi, we found that there is an error in the sequence for allele ju476. The
> correct sequence is pasted below (5bp insertion in upper case with flanking
> region in lower case):
> actcaaatgaaagctctgaattttccatgaaaattatgaattttccgaaaattaggatctttaagggtagtttaaagttactgtagaaaattttaaaaatttcgaaaaattccgaaaaattttttaatttttaaaattccgaaaatttttgaaaatccataactctgtcaatttttggtattttcagctcaatattgcctaaaaatgaagataaacttttaaactttttcggaaaaccaaatcgatctctagctacagtacccctttgtggtgggaactaactaaaataaagaagtcccatgcaaaaaaaaatattagaaaactcagaaaaaggaaagagcatgcacatacgagaggagcaactgatcacaccgtgtgggacacgtgacgggctgtcacgtgtaaagaagacgggctgtccggggactgcagttgacttgttgactgacgtggagaccctccgacgtgaagctatgcgcccgtccgaccagcgaccgtcacCGTTAcgttacggtacagagtttgggagtagcaaacctggaaaatttgaggaaaatcgataaactttgagtttaaaaaaatcgaaatttttcgaaatatttgtgccaaaaattaatttcctcctcacctgttgtcctccaccattaatagctgtgcagctaccggctccagcgctccacatcccggaatcctgagaaaatccggaatccctggccggtgatccacgggccccacccagcgtctcccagtaggaccctgaatgacgtatggcgtcgttgcgtaggatttctgaaatttttctattttttttaaattgaggggaccaagagcttttagaaatgtataatcatgtcgaggtttttggaaacttgatttttttgcaaaaaattgaggtctccccgcggaaatcccgtggataatgtagccaagtagttataagtgaatcaaatatttttgccaagttgttcattaactttgctatattttgtaatacattttttggaat
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5440. Follow progress on our
> issue tracker.
>
> Reported by: Lewie (lewie.zeng@yale.edu)
> 03 Mar 17 21:00
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/55.0.2883.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Pending response from original authro

**Comment by Paul-Davis** [comment]
This is a simple strand issue. The original data was reported on one strand while the issue sequence is on the gene strand. It might be beneficial to report the variant in the same sense as the gene, but this technically isn't an error and represents what was originally supplied/reported.
