### ISSUE TITLE
what is the upstream and downstream limit( in base...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5441]
*Help Desk query collected when no chat operators were online. Follow up required.*

what is the upstream and downstream limit( in base pairs) of Sir-2.1

**Reported by:** Rich*********** (rich***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004800#0-9g-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00004800#0-9g-10</a>
**Browser:** Chrome 56.0.2924.87

**Comment by raymond91125** [comment]
Hi Richmond,

I'm not certain what you're asking but the answer can probably be found 
on the Genome Browser views of the gene. Links are on the gene page, 
Location widget.

Cheers,

Raymond
