### ISSUE TITLE
  Dear Sir/Madam I am currently enrolle...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5442]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam<br/>I am currently enrolled in a Master's degree at the University of Aarhus in Denmark. We are currently producing a project proposal that intends to deal the with African Armyworm (Spodoptera exempta) and intend to use the Neem tree to defend against it in West Africa. I was wondering if the WormBase can provide details of its expected migration patterns? Or if I can put in the data to find this information? We need to know where it is heading in order to create this preventive defense for agricultural workers in Liberia. <br/>I look forward to hearing back from you. <br/>Yours gratefully<br/>visitor_name</p>

**Reported by:** Josh******* (josh****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
I might be mistaken, but isn't that some kind of lepidoptera larvae? Because lepidopterans are covered by LepBase rather by WormBase. But I am not sure if they got migratory patterns.
