### ISSUE TITLE
I want to know the genomic location (cM) of ruls32...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5443]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to know the genomic location (cM) of ruls32, if that could be possible is not in the gene details

thank you,

**Reported by:** Juan********** (jdro****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/transgene/WBTransgene00001996#014--10">http://www.wormbase.org/species/all/transgene/WBTransgene00001996#014--10</a>
**Browser:** Chrome 56.0.2924.87

**Comment by chris-grove** [comment]
Hi Juan,


As far as I can tell, this is the original paper to publish the transgene:

https://www.ncbi.nlm.nih.gov/pubmed/11238406

It looks like they mapped the transgene to chromosome III, but got strange recombination frequency results (Table 3, construct pAZ132, strain AZ212) that might suggest that there is a chromosomal rearrangement. It looks like the integrated transgene is within one cM of both dpy-17 and dpy-18, which are themselves are about 10 cM apart on a normal chromosome III.


For future reference, you can find mapping information in the Tree Display on a WormBase transgene page:


http://www.wormbase.org/species/all/transgene/WBTransgene00001996#0125--10


Look under the "Genetic_information" tag.


I hope that helps.


Chris
