### ISSUE TITLE
Hi there,

How do I find out what amino acids my s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5446]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there,

How do I find out what amino acids my sequence and the C.elegans homolog have in common? Thanks

**Reported by:** Emil********** (emil**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/protein/WP:CE15998#068735a--10-6735">http://www.wormbase.org/species/c_elegans/protein/WP:CE15998#068735a--10-6735</a>
**Browser:** Chrome 56.0.2924.87

**Comment by chris-grove** [comment]
Hello Emily,


 If you have the amino acid sequence you can use the BLASTP tool:


http://www.wormbase.org/tools/blast_blat


Paste in your sequence, make sure the "Query Type" is set to "Protein" and the "BLAST" drop down is set to "blastp" and click on "Submit". You should then be directed to a results summary page with alignments to the closest protein matches in C. elegans. There will also be links to the gene summary page for each match, where you can download the protein sequence for the C. elegans protein from the "Sequences" widget and then perform an alignment with Clustal Omega or similar alignment program online.


Let us know if you have more questions.


Best,


Chris Grove

WormBase
