### ISSUE TITLE
Hello...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5448]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello

**Reported by:** Brun* (brun**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003914#036--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00003914#036--10</a>
**Browser:** Chrome 56.0.2924.87

**Comment by azurebrd** [comment]
Hello Bruno,

If you have any further questions, feel free to ask on the github
ticket, or reply-all to this email.

Juancarlos, Help Desk
