### ISSUE TITLE
What do the highlighted regions and the non-highli...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5449]
*Help Desk query collected when no chat operators were online. Follow up required.*

What do the highlighted regions and the non-highlighted ones in the genetic map mean? x

**Reported by:** Bubs (bube****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/gmap/run?name=V;class=Map;map_start=24.9511;map_stop=25.2511">http://www.wormbase.org/tools/gmap/run?name=V;class=Map;map_start=24.9511;map_stop=25.2511</a>
**Browser:** Chrome 56.0.2924.87

**Comment by tuli** [comment]
Dear Bubs,

Thank you for writing to WormBase.
I presume you mean the difference between the orange, yellow and
no-colour genes?

Orange genes are cloned. They have a map position, an approved gene
name, a sequence name, but NO real genetic map data.

Yellow genes are cloned AND have experimental genetic map data. They
have mutation data, and an experimental genetic map position.

A gene with no colour is a mapped gene. They have mutation data, an
experimental map position but have NOT been cloned.

I hope this answers your query.

Best wishes,

Mary Ann



On 9 March 2017 at 14:19,  <no-reply@wormbase.org> wrote:
> offline chat What do the highlighted regions and the non-highlighted ones in
> the genetic map mean? x
>
> Submitted From:
>
> http://www.wormbase.org/tools/gmap/run?name=V;class=Map;map_start=24.9511;map_stop=25.2511
> http://www.wormbase.org/tools/gmap/run?name=V;class=Map;map_start=24.9511;map_stop=25.2511
>
> This issue has been assigned ticket number: #5449. Follow progress on our
> issue tracker.
>
> Reported by: Bubs (bubegoseva@gmail.com)
> 09 Mar 17 14:18
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
