### ISSUE TITLE
  Hi!  I'd like a list of all worm prot...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5454]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi!  I'd like a list of all worm protein coding gene IDs.  Just the names would be great.  Is that available from the downloads page?<br/>Thanks!<br/>Tom</p>

**Reported by:** tom ***** (tom@***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8

**Comment by chris-grove** [comment]
Hi Tom,

 I've made a little screen capture video to demonstrate how to get this list from WormMine (you can link to WormMine from the "Tools" menu at the top of any WormBase page):


https://dl.dropboxusercontent.com/u/4290782/WormBase/How_to_get_list_of_protein_coding_genes_in_WormMine.mov

You'll first need to identify all protein coding transcripts using the WormMine template query "Transcript Type, Species --> Genes". Once you've specified your species and transcript type ("Coding_transcript"), click "Show Results" and you'll be directed to a table with all transcripts (33,217 for C. elegans). From there you can save a list of all genes represented in the table (20,249 for C. elegans) using the "Save as List" function, making sure "Create List" is selected and then clicking on "Gene (20,249 Genes)". You can then rename your list, and click on the name that pops up once you're done making the list; alternatively you can go to the "Lists" tab and click on "View" to see your list. Once you've loaded the list of protein coding genes as a table in WormMine you can use the "Export" function to download the list in a format of your choosing.


I hope that helps.


Best,


Chris Grove

**Comment by chris-grove** [comment]
User is happy
