### ISSUE TITLE
there should be a way to filter genes that have ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5455]
*Help Desk query collected when no chat operators were online. Follow up required.*

there should be a way to filter genes that have genetic interaction

**Reported by:** Me (ddsf*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00016217#08-9gc-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00016217#08-9gc-3</a>
**Browser:** Safari 10.0.3

**Comment by chris-grove** [comment]
[wormbase-help] offline chat transcript: there should be a way to filter genes that have ge... (Me)
Grove, Christian A. (Chris)
ddsfkjhsdjh@hotmail.comhelp@wormbase.org
Hello,

Thanks for the feedback. Could you clarify what you mean exactly? Do you want to find all genes that are involved in a genetic interaction?

Best,

Chris

**Comment by chris-grove** [comment]
Email bounced, closing
