### ISSUE TITLE
  Good afternoon, I am contacting you a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5456]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good afternoon,<br/>I am contacting you as Source BioScience have recently launched a new website, which means that the links to the Ahringer RNAi clones and library have now changed.  I would therefore like to ask who the best person is to contact regarding updating these links?<br/>I look forward to hearing from you.<br/>Kind regards<br/>Helen</p>

**Reported by:** Hele******** (hele*****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by chris-grove** [comment]
Hi Helen,

 I can take care of updating links to Source BioScience. Can you send us a URL constructor of some sort? For C. elegans RNAi clones we usually key off of the clone location, e.g. IV-2C11.

Thanks,

Chris

**Comment by epaule** [comment]
fixed
