### ISSUE TITLE
WormBase ParaSite BioMart download not working

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5457]
@brucebolt 
Not sure if you're the one I should address this issue to, but the ParaSite BioMart tool is throwing errors when trying to look at all results or when trying to download a file. For example, this query:

`http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.sequences.peptide|wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.external_gene_id&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."col-10,col-101,col-102,col-103,col-104,col-105,col-106,col-107,col-108,col-109,col-11,col-110,col-111,col-113,col-114,col-115,col-116,col-117,col-118,col-119,col-12,col-120,col-121,col-122,col-123,col-124,col-125,col-126,col-127,col-128,col-129,col-13,col-130,col-131,col-132,col-133,col-135,col-136,col-137,col-138,col-139,col-14,col-140,col-141,col-142,col-143,col-144,col-145,col-146,col-147,col-148,col-149,col-15,col-150,col-151,col-152,col-153,col-154,col-155,col-156,col-157,col-158,col-159,col-16,col-160,col-161,col-162,col-163,col-164,col-165,col-166,col-167,col-168,col-169,col-17,col-170,col-171,col-172,col-173,col-174,col-175,col-176,col-177,col-178,col-179,col-18,col-180,col-181,col-182,col-183,col-184,col-185,col-186,col-187,col-19,col-2,col-20,col-3,col-33,col-34,col-35,col-36,col-37,col-38,col-39,col-40,col-41,col-42,col-43,col-44,col-45,col-46,col-47,col-48,col-49,col-5,col-50,col-51,col-52,col-53,col-54,col-55,col-56,col-58,col-60,col-61,col-62,col-63,col-64,col-65,col-66,col-68,col-69,col-7,col-71,col-72,col-73,col-74,col-75,col-76,col-77,col-78,col-79,col-8,col-80,col-81,col-83,col-84,col-85,col-86,col-87,col-88,col-89,col-9,col-90,col-91,col-92,col-93,col-94,col-95,col-96,col-97,col-98,col-99"&VISIBLEPANEL=resultspanel`

doesn't let me look at all results or download the FASTA file.

**Comment by brucebolt** [comment]
The connection appears to be timing out.  I'll see what we can do to speed this up to avoid timeouts.

The 'notify by email' option is working, since this creates the FASTA file in the background.

**Comment by chris-grove** [comment]
@brucebolt 
OK, thanks!

**Comment by brucebolt** [comment]
EBI have increased the web timeout for ParaSite, up to 60 seconds, which means this query now returns all the requested sequence without error.  I'm told this can be increased further, should this be required for more complex queries.

I will be leaving this ticket opening for now, since I'd like to see if we can make the BioMart sequence code more efficient.

**Comment by chris-grove** [comment]
@brucebolt 
OK, thanks!

**Comment by brucebolt** [comment]
I've added a new index into the sequence mart database.  The above query returns fill results in less than 10 seconds on the WBPS9 BioMart.  Hopefully this, coupled with the longer timeout, should resolve the issue.
