### ISSUE TITLE
Chris: Hello Garif, how can I help? visitor_name (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5458]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Garif, how can I help?</br>visitor_name (visitor_email): Hi Chris</br>visitor_name (visitor_email): Can you help me with downloading all sequences of a protein family?</br>Chris: OK, sure</br>Chris: Which family?</br>visitor_name (visitor_email): I found all genes, but only need the sequences for now</br>Chris: OK</br>visitor_name (visitor_email): col- of E. elegance</br>visitor_name (visitor_email): got 181 hits</br>Chris: This might be best done using BioMart at the WormBase ParaSite website</br>visitor_name (visitor_email): ok</br>Chris: or possibly WormMine</br>Chris: First, lets</br>Chris: try BioMart</br>visitor_name (visitor_email): ok</br>Chris: You can find the link to WormBase ParaSite BioMart under the Tools menu at the top of any WormBase page</br>visitor_name (visitor_email): Got it</br>Chris: http://parasite.wormbase.org/biomart/martview/</br>Chris: OK great</br>Chris: Under query filters, paste your list of genes into the field under the "Genes" option</br>Chris: Actually it just says "GENE"</br>visitor_name (visitor_email): Got it</br>Chris: Check the "ID list limit" checkbox and paste in your list of gene names/IDs</br>visitor_name (visitor_email): OK</br>Chris: You will need to specify if the list is of IDs or names in the drop down menu above the list of genes</br>visitor_name (visitor_email): ok</br>Chris: OK. Next we want to go to "Output Attributes" at the left</br>visitor_name (visitor_email): ok</br>Chris: and click on the radio button for "Retrieve Sequences"</br>visitor_name (visitor_email): got it</br>Chris: Open the "SEQUENCES" section and specify Peptide</br>visitor_name (visitor_email): got it</br>Chris: Now you can click "Results" to get your list of peptide sequences</br>visitor_name (visitor_email): got it</br>Chris: You may want to go back and add or change the types of identifiers that are listed for each gene/protein</br>Chris: You can do this under the "Output Attributes"</br>Chris: Actually under the "HEADER INFORMATION" beneath the "SEQUENCES" section where you specified "Peptide"</br>visitor_name (visitor_email): ok</br>visitor_name (visitor_email): does not look like collagen sequences</br>Chris: OK, can you tell from the output that it doesn't look right</br>Chris: ?</br>visitor_name (visitor_email): meloidogyne_incognita_prjea28837|Minc04389</br>visitor_name (visitor_email): &gt;caenorhabditis_elegans_prjna13758|WBGene00000594</br>Chris: Maybe you can give me a few genes from your list to try troubleshooting?</br>visitor_name (visitor_email): there is no collagen infos</br>visitor_name (visitor_email): short cuts are col-1, col-2 col-3 ...</br>Chris: OK, we may need to also specify the species; are you looking for C. elegans genes only?</br>visitor_name (visitor_email): yes</br>Chris: OK, let's go back to "Query Filters" and specify species, just in case that is an issue</br>visitor_name (visitor_email): I already did this</br>Chris: OK, so what does your output look like?</br>visitor_name (visitor_email): the one I sent already</br>Chris: There's no sequence along with the gene header?</br>visitor_name (visitor_email): there is</br>visitor_name (visitor_email): &gt;meloidogyne_incognita_prjea28837|Minc04389
MDAKPIKMDYESRIKAYRFVAYSTVSFSVISLVSVCFTLPMLQSYVSNVASNMDRELNLC
QGTAKDIWSEVNQLKSIPASSNRTARQAGYGGGEAPVTGGSASSSGGGGQCSDCCSGGGP
GPAGPPGPPGRSGNPGAPGSPGQPGKSQQAPCQQVTTPPCKPCPGGQPGQPGPPGPPGQP
GGPGQPGQPGGQASPGEPGPAGPPGSPGAPGNIFLIFMRV*
&gt;brugia_pahangi_prjeb497|BPAG_0000298801
MVDSDDPKQLLIEAESMKKLAFCGVAVSTVATLVAIICVPMLCTYMQNVQSNLQDEISFC
RTRAIGLRGEFTKLESSRSALKKERQKRQAVFQCCSCGIGPVGPPGPPGQDGDDGRDGPP
GKPGMPGQDAQETQLPTERDWCFNCPAGPPGPRGKPGPKGQRGLPGDKGSSGQPGEPGPV
GPQGPRGPNGPRGNPGPAGEPGKPGVQTEVPGPPGPPGPPGPQGPPGEQGPAGRDGNPGR
PGPRGPPGQNGKDGPPGHDGPNGDQGEAGPDGPKGSCDHCPPPRTAPGY*</br>Chris: OK, did you want collagens from Meloidogyne incognita as well as Brugia pahangi? If not we'll need to specify that we only want C. elegans as the species in the "Query Filters" section</br>visitor_name (visitor_email): Just c. elegance</br>Chris: For simplicity, you can click on this URL to get the same query that I'm using:</br>Chris: http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&amp;ATTRIBUTES=wbps_gene.default.sequences.peptide|wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.external_gene_id&amp;FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."col-1,col-2,col-3"&amp;VISIBLEPANEL=resultspanel</br>visitor_name (visitor_email): ok this is the hits for 2 out of 181</br>Chris: Do the results look reasonable at that URL?</br>Chris: Right, I only put in "col-1, col-2, col-3" for the input</br>visitor_name (visitor_email): yours does, because it says col-1</br>Chris: col-1 is actually an other name for sqt-3</br>Chris: OK, if you now paste your entire gene list into the Query Filters section, you should get your results</br>visitor_name (visitor_email): than I will try this</br>visitor_name (visitor_email): Thank you for your help!</br>Chris: the only issue is that if you're not using the official gene name (like "sqt-3" for "col-1") then the results will be missing</br>Chris: You're welcome</br>Chris: Did that get you the sequences you were looking for?</br>visitor_name (visitor_email): I don`t have the full list yet. I searched with "col-" in the WormBase and got all hits. Need to do the list</br>Chris: OK</br>visitor_name (visitor_email): 181 Genes found (0.01 seconds)
col-178 [gbrowse (BioProject PRJNA13758)]
Caenorhabditis elegans
col-129 [gbrowse (BioProject PRJNA13758)]
Caenorhabditis elegans</br>Chris: OK, it sounds like it found all your genes</br>visitor_name (visitor_email): yes with "col-" it did, but this does not work in Biomart</br>Chris: Oh OK, you still need to get the list of gene names?</br>visitor_name (visitor_email): right</br>Chris: OK, here's the page for the "col"</br>Chris: gene class</br>Chris: http://www.wormbase.org/resources/gene_class/col#01--10</br>visitor_name (visitor_email): Beautiful 164 members</br>Chris: Yes</br>Chris: Then you can open the C. elegans section, click on "Save table"</br>Chris: then click on "Copy" and paste your list into Excel or other spreadsheet program</br>Chris: then copy and paste the gene name list into BioMart</br>visitor_name (visitor_email): Your`re a genius!</br>Chris: Haha, thanks</br>visitor_name (visitor_email): Saves my day</br>Chris: OK, great</br>visitor_name (visitor_email): I am trying the list</br>Chris: OK</br>Chris: Did that work for you? It worked for me</br>visitor_name (visitor_email): it is still searching</br>Chris: OK</br>visitor_name (visitor_email): it shows some hits, but  when I want to show all hits it does not work</br>Chris: OK, I'm having trouble downloading the file</br>Chris: It seems there's something wrong;</br>visitor_name (visitor_email): same here</br>Chris: I will make a ticket so this can be fixed</br>visitor_name (visitor_email): great</br>Chris: OK, let me get the list using WormMine and I'll send you an email with the list attached; is that OK?</br>visitor_name (visitor_email): That would be great Chris!</br>visitor_name (visitor_email): It actually gives an error now</br>Chris: OK, apologies for the error</br>visitor_name (visitor_email): No worries</br>Chris: I'll get it worked out in WormMine and send you the query and the results in a few minutes</br>visitor_name (visitor_email): excellent, thank you!</br>Chris: Sure, you're welcome

**Reported by:** Gari******** (gari********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/col-?species=c_elegans">http://www.wormbase.org/search/gene/col-?species=c_elegans</a>
**Browser:** Chrome 56.0.2924.87

**Comment by chris-grove** [comment]
Hello Garif,


Here's the list of collagen protein sequences. The first file (#1) is of all protein sequences for all genes named "col-*" as a primary public name. List #2 is a list of protein sequences for 10 collagen genes in which the "col-*" name is an alias. The first list I was able to generate in WormMine using the following XML query:


`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.CDSs.protein.sequence.residues Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.organism.name" code="A" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.symbol" code="B" op="CONTAINS" value="col-"/>
</query>`


The second list is more complicated to get, so I won't explain how I got it.


I've notified the person responsible about the bug in BioMart. It turns out that the email file option is working, so you can use that with your BioMart results if you want.


Cheers,


Chris
