### ISSUE TITLE
Hello, Excuse me. FLP-21 on is view sequence page ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5459]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, Excuse me. FLP-21 on is view sequence page it's : Pre-Pro_FLP-21?

http://www.wormbase.org/species/c_elegans/protein/WP:CE30733#0634591--10

**Reported by:** Brun* (brun**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/protein/WP:CE30733#0634591--10">http://www.wormbase.org/species/c_elegans/protein/WP:CE30733#0634591--10</a>
**Browser:** Chrome 56.0.2924.87

**Comment by gw3** [comment]
Yes it is the Pre-Pro FLP-21

The mature peptide is "GLGPRPLRFG" .

Gary Williams
WormBase
