### ISSUE TITLE
  Hi: I am new tonematodes.  I need a g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5462]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi: I am new tonematodes.  I need a good basic protociol for growing nematodes. <br/>Thank you<br/>Farida</p><p>What were you doing? <br />&nbsp;&nbsp;I teach genetics and would like my students to learn about thenematode</p>

**Reported by:** Fari************** (fsaf*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by raymond91125** [comment]
HI Farida,

You can find much useful information about methods here 
<http://www.wormbook.org/toc_wormmethods.html>.

Cheers,

Raymond


On 03/13/2017 12:29 PM, no-reply@wormbase.org wrote:
> Question:
>
>   Hi: I am new tonematodes. I need a good basic protociol for growing 
> nematodes.
> Thank you
> Farida
>
> What were you doing?
>   I teach genetics and would like my students to learn about thenematode
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5462. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5462>.
>
> Reported by: Farida Chamberlain (fsafadi@colostate.edu)
> 13 Mar 17 19:30
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
