### ISSUE TITLE
visitor_name (visitor_email): Dear People at WormB...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5465]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Dear People at WormBase. I'd appreciate if you could make the following changes to the list of publications on my WBPerson page: The two publications listed as Kulkarni et al. (2015) suffered from long delays between acceptance and print and appeared only in 2016. I'd also appreciate if you could add the following publications from 2016 and earlier: Streit, A. and Davis, R. E. (2016). Chromatin diminution version 2. In: eLS. John Wiley &amp; Sons Ltd, Chichester. http://www.els.net/,  DOI: 10.1002/9780470015902.a0001181.pub2 ; Streit, A., Wang, J., Kang, Y. and Davis, R. E. (2016). Gene Silencing and Sex Determination by Programmed DNA Elimination in Parasitic Nematodes. Current opinion in Microbiology 32 120-127 ; Hunt, V. L., Tsai, I. J., Coghlan, A., Reid, A. J., Holroyd, N., Foth, B. J., Tracey, A., Cotton, J. A., Stanley, E. J., Beasley, H., Bennett, H., Brooks, K., Harsha, B., Kajitani, R., Kulkarni, A., Harbecke, D., Nagayasu, E., Nichol, S., Ogura, Y., Quail, M., Randle, N., Ribeiro, D., Sanchez-Flores, A., Hayashi, T., Itoh, T., Denver, D. R., Grant, W., Stoltzfus, J. D., Lok, J. B., Murayama, H., Wastling, J., Streit, A., Kikuchi, T., Viney, M. E., Matthew Berriman, M. (2016). The Genomic Basis of Parasitism in the Strongyloides Clade of Nematodes. Nature Genetics  48, 299-307.  doi:10.1038/ng.3495 ; Guo, L., Chang, Z., Dieterich, C. and Streit, A. (2015). A protocol for chemical mutagenesis in Strongyloides ratti. Experimental Parasitology  158, 2-7 . Thank you very much.

**Reported by:** Adri********* (adri**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/person/WBPerson629#0123--10">http://www.wormbase.org/resources/person/WBPerson629#0123--10</a>
**Browser:** Safari 6.1.6

**Comment by ceciliaWBPerson1** [comment]
resolved
