### ISSUE TITLE
  Dear wormbase team (great job, by the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5466]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase team (great job, by the way, as always),<br/>in my lab entry (ZX, zx - Gottschalk lab), I notice there is no e-mail address (please use the one above), and the lab URL is out of date. Please use this one:<br/>http://www.biochem.uni-frankfurt.de/index.php?id=8<br/>Thank you and best,<br/>Alexander</p>

**Reported by:** Alex**************** (a.go****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by tuli** [comment]
Dear Alexander,

Thank you for writing to WormBase. I am writing to confirm that I have
added your email address and URL to your laboratory details.

You'll see the update in release WS260 of WormBase.

Best wishes,

Mary Ann


On 14 March 2017 at 22:36,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Dear wormbase team (great job, by the way, as always),
> in my lab entry (ZX, zx - Gottschalk lab), I notice there is no e-mail
> address (please use the one above), and the lab URL is out of date. Please
> use this one:
> http://www.biochem.uni-frankfurt.de/index.php?id=8
> Thank you and best,
> Alexander
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5466. Follow progress on our
> issue tracker.
>
> Reported by: Alexander Gottschalk (a.gottschalk@em.uni-frankfurt.de)
> 14 Mar 17 22:34
>
> Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
