### ISSUE TITLE
  Hi, when searching for gene T28D6.4 >...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5467]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, when searching for gene T28D6.4 > Genetics, I find the table "Alleles with phenotype": One entry, tm926, and as a reference: Antonacci et al. 2015. However, this paper does not contain any appearance of either T28D6.4 or tm926. Is this a bug?<br/>Best<br/>Ralf</p>

**Reported by:** Ralf*********** (baum******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

**Comment by tuli** [comment]
Dear Ralf,

Thank you for writing to WormBase.

I have checked the paper and see that tm926 and T28D6.4 are cited in
Table S1 in the Supporting Information.

Best wishes,

Mary Ann

On 15 March 2017 at 10:17,  <no-reply@wormbase.org> wrote:
> Bug Report
>
>   Hi, when searching for gene T28D6.4 > Genetics, I find the table "Alleles
> with phenotype": One entry, tm926, and as a reference: Antonacci et al.
> 2015. However, this paper does not contain any appearance of either T28D6.4
> or tm926. Is this a bug?
> Best
> Ralf
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5467. Follow progress on our
> issue tracker.
>
> Reported by: Ralf Baumeister (baumeister@celegans.de)
> 15 Mar 17 10:17
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727;
> .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C;
> .NET4.0E; InfoPath.3; rv:11.0) like Gecko
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
