### ISSUE TITLE
I'm trying to find a list of all the WormBase IDs ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5473]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'm trying to find a list of all the WormBase IDs along with the sequence ID.  Is there a way to download from wormbase?

**Reported by:** Bria******** (bria******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00007072#-09g1f-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00007072#-09g1f-10</a>
**Browser:** Chrome 56.0.2924.87

**Comment by chris-grove** [comment]
Hi Brian, if you're looking for all C. elegans gene IDs, you can get them from our FTP site here:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/geneIDs/


You can download and unzip the file:


c_elegans.PRJNA13758.current.geneIDs.txt.gz


from the directory.


Let us know if you need something else.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
User is happy
