### ISSUE TITLE
  Hi I am a scientist who is now in edu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5474]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>I am a scientist who is now in educational development.  I would like to develop a site similar to wormbase to meet our needs.  I was wondering if you could tell me anything about your architecture and if you have any of the code/platform that you could share.  This is for a non-profit website/database on a completely different topic. </p>

**Reported by:** Gene******** (gste****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

**Comment by sibyl229** [comment]
User has been contacted. Closing.

> WormBase website actually has a lot of moving parts that we expose as a unified website. In generally, what you see on the website falls into a few categories, the report pages (like gene page, phenotype page, etc), search result page, services that we build on top of other open source tools (JBrowse, BLAST), FTP site for downloading data. 
> 
> In terms of what code would be reusable. I think most of the code we write here deal specifically with our data, which is likely different from yours. So I don’t think a huge amount actual code is reusable, beyond what exists as open source tools (like JBrowse, BLAST). But I will link to our code below. 
> 
> On the other hand, what made WormBase website so complex is our data model. Outside of that, what we do is fairly generic, which means that there are a lot of tools out there that will help you build something similar. 
> 
> Here I will list out the building blocks for WormBase website, and you can find the alternatives in your programming language and existing technology stack. There are probably better ways to build a website than what we do now, so don’t be afraid of deviating from the approach we took:
> 
> - MVC Web framework: Catalyst in Perl (alternatives like Django in Python, Spring in Java would work just as well). We have a server side MVC architecture, you may not need a full MVC web framework, depending on your architecture.
> - Search engine: Xapian (Elasticsearch and Solr are popular choices today)
> - DataBase: Datomic (another graph DBMS or relational DBMS may work for you as well)
> - User authetication: we delegate to Login with Google
> - You may or may not need a caching layer
> - Some deployment option for the website and FTP: we deploy to Amazon AWS
> 
> Web site source code:
> https://github.com/WormBase/website
> 
> Some documentation about the various technology used at WormBase:
> http://wiki.wormbase.org/index.php/Co-op_Documentation#Tools.2FResources
