### ISSUE TITLE
Hello,
--1) What argument I used to demontrated th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5480]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
--1) What argument I used to demontrated that aminopepdidase B (Arg/Lys aminopeptidase) it is PAM-1 in C elegans?
--2) The same for Cathespsin L and CPL-1 in C elegans.

Thanks.

**Reported by:** Brun* (brun**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001189#036c--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001189#036c--10</a>
**Browser:** Chrome 56.0.2924.87

**Comment by chris-grove** [comment]
Hi Bruno,

 From our online chat conversation I told you that:

"The C. elegans gene pam-1 is the closest BLASTP match to a lysine aminopeptidase from Aspergillus luchuensis"

When I do a search at NCBI for "lysine aminopeptidase", the Aspergillus luchuensis was the first match I found:

https://www.ncbi.nlm.nih.gov/protein/GAT25807.1

so I performed a BLASTP search with that protein sequence to get pam-1 as the closest C. elegans match.

The gene cpl-1 comes up in WormBase when I do a search for genes with "cathepsin L".

Chris
