### ISSUE TITLE
Gene interactions widget (datomic)

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/website#5482]
Hi @chris-grove (and others familiar with the interactions widget/data!)

Could you take a look over the gene interactions widget I've developed with the data coming from Datomic?

Generally, the potential issues I can see are:

* Extra variants
  The clojure/datomic version seems to be finding more variants than that served via the existing perl/ACeDB, and the occasional interaction seems to be missing. I'm not sure which version is "correct",
and hoping you may be able to shed some light.
* Effector/Affected allocation when direction is "non-directional" (as discussed via email)
 
Simple cases appear to just be fine. (e.g WBGene00009192, WBGene00020398)

The genes I'm using as a test case are:

Datomic Dev server | Staging  server  |  Comments 
---------------------------| --------------------- | -----------------
[prx-19][prx-19_dev] | [prx-19][prx-19_stag] | Seems to be identical
[aap-1][aap-1_dev] | [aap-1][aap-1_stag] | Graph ledgend showing more variants, but seems to match table... is this correct? missing interaction between aap-1 and daf-1
[ced-7][ced-7_dev] | [ced-7][ced-7_stag] | Missing interaction (Supression, ced-7 : mig-2 : mtm-1, is contained in other composite interaction)

Perhaps you could suggest other genes which would make good test-cases for this widget.

Thanks!

[prx-19_dev]: http://dev.wormbase.org:9018/species/c_elegans/gene/WBGene00004201
[ced-7_dev]: http://dev.wormbase.org:9018/species/c_elegans/gene/WBGene00000421
[aap-1_dev]: http://dev.wormbase.org:9018/species/c_elegans/gene/WBGene00000001
[prx-19_stag]: http://staging.wormbase.org:9018/species/c_elegans/gene/WBGene00004201
[ced-7_stag]: http://staging.wormbase.org:9018/species/c_elegans/gene/WBGene00000421
[aap-1_stag]: http://staging.wormbase.org:9018/species/c_elegans/gene/WBGene00000001

**Comment by chris-grove** [comment]
@mgrbyte 
OK, I'm having a look now. As you point out, I think prx-19 is (essentially) the same on both the Datomic Dev and Staging servers, so that is all set.

As for aap-1, there appears to be 2 issues that explain the discrepancy:

1) There is a single interaction (WBInteraction000501051) that is between three genes (daf-2, daf-1, and aap-1) that is being displayed in the table as two separate interactions on staging but as one interaction (between aap-1 and daf-2) on Datomic Dev. This is a tricky situation (as are all interactions involving more than 2 interactors) as we want to implicate all three genes in the interaction. Ideally we would have one set of interactors in the "Effector" column and another set of interactors in the "Affected" column; in the case of WBInteraction000501051 both daf-2 and daf-1 are indicated as "Affected" and so both should appear together in the "Affected" column

2) The other discrepancy is that there are more phenotypes appearing in the legend. It seems that the phenotypes for "Nearby" interactions are showing up in the legend on the Datomic Dev but not on Staging, where "Nearby" means interactions not involving the focus gene (aap-1 in this case). Lately I've been leaning towards removing phenotypes from the legend altogether, as the legend becomes unusable when there are lots of genetic interactions (e.g. daf-2 gene page), so this would become a moot point.

I'll look at the ced-7 page and get back to you.

**Comment by chris-grove** [comment]
@mgrbyte 
Also for aap-1, there are additional interaction types displayed in the legend on Datomic Dev compared to Staging. On Datomic Dev there is the "Synthetic" interaction type between the nearby interactors daf-2 and pal-1. I don't know why that interaction is not showing up as a nearby interaction on Staging. Also, the "Change of expression level" interaction type (under the Regulatory types) is showing up between daf-2 and akt-1 on Datomic Dev but not Staging; this is also unclear to me. Both sites should be running off the same data (WS258) correct? I tried to look at the interactions on the akt-1 gene page on Datomic Dev and the Interactions widget won't load (throws error):

http://dev.wormbase.org:9018/species/c_elegans/gene/WBGene00000102#8--10

**Comment by chris-grove** [comment]
Also getting errors when looking up daf-2 and age-1 on Datomic Dev

**Comment by chris-grove** [comment]
As for the ced-7 gene page on Datomic Dev, there are two interactions (one between ced-7 and ced-1 and the other between ced-7 and ced-6) that are listed in the interaction table as "Regulatory" interactions, but it would be best if they were displayed to the more granular term "Does Not Regulate" as they are on Staging, highlighting the negative nature of the data.

As for the ced-7 : mig-2 : mtm-1 suppression interaction, that should be separated from the other ced-7 : mtm-1 interactions as it is distinct (includes mig-2) as it is on Staging, and, as I mention above, the interactions with three or more interactors should list all interactors collectively in the "Effector" and "Affected" columns. For this interaction (ced-7 : mig-2 : mtm-1) both mig-2 and mtm-1 are listed as the Effectors for the interaction.

Also, as for the Cytoscape network graph on Datomic Dev, the graph shows a "No interaction" edge between Caffeine and lin-1, a "Genetic interaction" and "Predicted" interaction between ced-12 and mec-4, a "Change of expression level" interaction between ced-10 and tbc-2 and several interactions between mig-2 and other entities, despite the fact that there are no interactions (at least on Datomic Dev) between ced-7 and lin-1, mec-4, tbc-2, or mig-2. In brief, there shouldn't be any nodes in the network that don't have at least one direct connection to the focus gene.

**Comment by chris-grove** [comment]
In general there seem to be more interactions displayed on the Datomic Dev site than the Staging site, which all seem legitimate; I don't know why they don't show on Staging, but it's good that they are displaying on Datomic Dev

**Comment by mgrbyte** [comment]
@chris-grove 

With regard to your feedback on app-1:
1) I'll see if I can make this happen. Currently the datomic-dev version is only handling single effector/affected pairs (triples aren't handled correctly as you've commented)

2) 
Could you clarify "Nearby?" and "focus gene"
I assume "focus gene" is the gene page currently loaded (i.e the one in the URL)
Nearby:
 - when I tick the checkbox in the legend (any version datomic-dev,staging,live), interactions are displayed that are _not_ directly connected to the focus gene (aap-1 in this case IIUC); when unticked the converse, no indirect associations with aap-1 are shown.

>On Datomic Dev there is the "Synthetic" interaction type between the nearby interactors daf-2 and pal-1. I don't know why that interaction is not showing up as a nearby interaction on Staging. Also, the "Change of expression level" interaction type (under the Regulatory types) is showing up between daf-2 and akt-1 on Datomic Dev but not Staging; this is also unclear to me. Both sites should be running off the same data (WS258) correct?

That's correct.
I've attempted to mimic the logic of the perl code as much as possible, but I can't see why they do not appear on staging/in the resulting JSON.

They seem to be legitimate connections from a data perspective.
This is also the reason for there being more phenotype listed in the legend, since those phenotype are associated with these additional interactions.

> I tried to look at the interactions on the akt-1 gene page on Datomic Dev and the Interactions widget won't load (throws error):
> http://dev.wormbase.org:9018/species/c_elegans/gene/WBGene00000102#8--10
There seems to be a bug (e.g: daf-2, atk-1 gene, I'm looking into that now.

Thanks Chris!

**Comment by chris-grove** [comment]
@mgrbyte 
"Nearby" interactions are those that are between two interactors of the focus gene (yes, the focus gene is the one whose page we are currently viewing). So nearby interactions don't involve the focus gene, but all nodes present should connect by at least one edge to the focus gene (if not the graph would quickly explode in size if we include all interactions of all interactors). I hope that's clear.

Yes, the data appearing on Datomic Dev that is not appearing on Staging all seem legit.

As for the interactions involving three or more interactors, I've thought at times about forcing all interactions to be binary, but it becomes difficult to handle certain situations, either in the display or the interpretation, or both.

**Comment by mgrbyte** [comment]
@chris-grove I think this is done now, can you confirm?

**Comment by chris-grove** [comment]
@mgrbyte 
I think so, but I'm not sure where I should be checking as the original Datomic Dev and Staging links are now broken.

**Comment by mgrbyte** [comment]
@chris-grove 
I believe this has been deployed to the live site, so will close now and if any problem a new issue can be opened. thanks!

**Comment by chris-grove** [comment]
OK, sounds good
