### ISSUE TITLE
  Could you please correct the paper ev...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5483]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Could you please correct the paper evidence for lax188 and lax120 to the original paper documenting these alleles?<br/>http://www.wormbase.org/species/c_elegans/variation/WBVar01474253#02-45-3<br/>http://www.wormbase.org/species/c_elegans/variation/WBVar01474254#02-45-3<br/>the correct paper is:<br/>http://www.wormbase.org/resources/paper/WBPaper00042117#0--10<br/>Thanks,<br/>Sean</p><p>What were you doing? <br />&nbsp;&nbsp;I've been contacting by several people in the community who were trying to get info on these alleles but had no reply since they are contacting a lab that used these alleles, but did not create them.</p>

**Reported by:** Sean******* (spcu************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by tuli** [comment]
Dear Sean,

Thank you for writing to WormBase.

I have updated the evidence for lax188 and lax120 to your paper as requested.

You'll see the update in release WS260

Best wishes,

Mary Ann

On 19 March 2017 at 21:46,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Could you please correct the paper evidence for lax188 and lax120 to the
> original paper documenting these alleles?
> http://www.wormbase.org/species/c_elegans/variation/WBVar01474253#02-45-3
> http://www.wormbase.org/species/c_elegans/variation/WBVar01474254#02-45-3
> the correct paper is:
> http://www.wormbase.org/resources/paper/WBPaper00042117#0--10
> Thanks,
> Sean
>
> What were you doing?
>   I've been contacting by several people in the community who were trying to
> get info on these alleles but had no reply since they are contacting a lab
> that used these alleles, but did not create them.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5483. Follow progress on our
> issue tracker.
>
> Reported by: Sean Curran (spcurran@usc.edu)
> 19 Mar 17 21:46
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/56.0.2924.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
