### ISSUE TITLE
Hi! 
I would like to convert a wig file using ce4 ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5492]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! 
I would like to convert a wig file using ce4 to the coordinates for ce10, is there a tool to do so? So far I have found only liftOver for bed files.

Thanks for your help!

**Reported by:** Ahil** (ahil***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/tools/coordinate_converter#0--10">http://www.wormbase.org/about/userguide/tools/coordinate_converter#0--10</a>
**Browser:** Chrome 57.0.2987.110

**Comment by epaule** [comment]
I think it would boil down to https://www.biostars.org/p/81185/ which is to convert the Wiggle file to BedGraph use liftover and convert it back.
We also have a tool to liftover GFF files, but I don't think you would gain too much by using that.
