### ISSUE TITLE
Add ?Gene_class to the XML dumps for intermine

### ISSUE THREAD

**Issue by tharris** [WormBase/website#5493]
We've added the Gene_class for WS258. @scottcain, can you add the Gene_class to the script that dumps XML for intermine loading for WS259 and beyond?

**Comment by scottcain** [comment]
Hi @tharris there is already a Gene_class.xml file that is created by the full database dump, which is presumably what you want.  I'm guessing you'd like something added to the test data set as well?  I added this:
```
query find Gene_name $GENE ; follow Public_name_for ; follow Gene_class
show -x -f "$DESTINATION/temp-Gene_class-$GENE.xml"
```
which does generate an xml file.  If you'd like to look at the result and verify that it looks like what you'd expect, you can find it at ```/usr/local/wormbase/intermine/builds/WS258/WS258-test-data/Gene_class.xml ```

If you're good with that, I'll commit the changes to the dump test script.

**Comment by tharris** [comment]
Thanks, Scott.  Ah, I guess I anticipated my future self and added the Gene_class already.  For the test, I would just dump the entire class. It's small and shouldn't really impact the build much.

**Comment by scottcain** [comment]
Should have closed this a long time ago
