### ISSUE TITLE
Hi Everyone,


I was wondering one could provide a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5497]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi Everyone,

I was wondering one could provide a  protocol to isolate pure diakinesis oocytes population(&gt;95% pure)...Wild type strain would be ideal but I could use also other strain that works better for this purpose.Thanks a lot.

**Reported by:** Tani** (tani**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#">http://www.wormbase.org/#</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by chris-grove** [comment]
the WormBase forum may be the best place to post your question:

http://forums.wormbase.org/

You could also peruse the methods at WormBook:

http://www.wormbook.org/toc_wormmethods.html

Best,

Chris
