### ISSUE TITLE
  I want to update my lab's website lin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5498]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to update my lab's website link and my email address (both are no longer functional because our institute's server died the other month).  Could my lab's website be updated to www.libudalab.org and my email updated to visitor_email<br/>Thank you so much for taking the time to do this!!!  I hope you're having a great week!<br/>Cheers!<br/>visitor_name</p>

**Reported by:** Dian******** (dlib***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8

**Comment by ceciliaWBPerson1** [comment]
Dear Diana E. Libuda:

Thanks for the updates.

I have updated your data in your WBPerson page.

Updates will be available in release WS260 of WormBase.
We are currently in version WS257.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule

Thanks again, have a great day!
cecilia

On Wed, Mar 22, 2017 at 4:23 PM, WormBase Helpdesk <notifications@github.com

**Comment by tuli** [comment]
Updated lab.
