### ISSUE TITLE
Dear colleagues at wormbase, 
I would like to ask ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5499]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear colleagues at wormbase, 
I would like to ask a favor. I have a list of gene. I wonder whether wormbase has a tool that will systermatically find the human homologs for all the genes in the list and identify those homologs that have been implicated in human diseases.
Thanks, 
visitor_name
Postdoc from the Sternberg lab at Caltech

**Reported by:** Han **** (han.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 57.0.2987.110

**Comment by epaule** [comment]
I don't think the human disease data has been added (yet) to WormMine, but we definitely have the data in our database.
But considering that Paul's WormBase group are the ones curating C.elegans models of human diseases, you might want to walk over and have a chat with them.
