### ISSUE TITLE
I have a question about re-annotating a gene. I ha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5500]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have a question about re-annotating a gene. I have a western blot that has pick up a very bright band that we think it is another isoform of that gene. Can anyone help me? Thank you.

**Reported by:** Ruby******** (ruby**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001340#0-9gefa84-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001340#0-9gefa84-10</a>
**Browser:** MSEdge 14.14393

**Comment by gw3** [comment]
Thank you for your information.
Could you submit any EST or mRNA evidence that you have for this isoform 
to INSDC (http://www.insdc.org/) and we will automatically update the 
database with this information.
It would be helpful if you could also indicate the exon structure of 
your isoform.

Gary Williams
WormBase
