### ISSUE TITLE
  BLAST/BLAT query search returns 504 B...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5502]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;BLAST/BLAT query search returns 504 Bad Gateway</p><p>What were you doing? <br />&nbsp;&nbsp;BLASTing C. elegans cki-1 protein against p.redivivus or c. elegans genome</p>

**Reported by:** Davi********* (davi*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by chris-grove** [comment]
Hi David,

 Sorry about that. It looks like BLAST is back up and running. Let us know if you have any more trouble.

Chris
