### ISSUE TITLE
  When I search for the P. redivivus ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5503]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;When I search for the P. redivivus gene g1968, no gene can be found, even though I got the transcript name via BLASTing C. elegans cki-1 against the P. redivivus genome.</p>

**Reported by:** Davi********* (davi*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
it looks like the blast indices haven't been updated to the new names.
Until we have done that, you can stick a Pan_ in front of the id and it will find them.

@webteam can you rebuild the Panagrellus blast indices from the respective fasta files?

**Comment by epaule** [comment]
looks like the blast index has been rebuilt

**Comment by chris-grove** [comment]
@epaule  Did you by chance email the user?

**Comment by epaule** [comment]
once on how to convert the ids. But not when the index was rebuilt (which was sometime between yesterday and 20 days ago).
