### ISSUE TITLE
  How do I find the complete descriptio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5509]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find the complete description of the allele e794 in C. elegans? Where is the place where I can look up the function of each allele? I cannot seem to find the allele e794 in the description at all. Please help!</p>

**Reported by:** Brit**** (bwis*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8

**Comment by kyook** [comment]
Hi Brittani,

You can find information about e794 on its variation page
http://www.wormbase.org/species/c_elegans/variation/WBVar00143490#0-6271345-10

You get to this page by searching for e794 and choosing Variation in the
drop down list in the search box.

You can see different information about the allele by opening the different
widgets listed in the left sidebar of the page.

Please let us know if there is some information in particular that you
can't find on the page, or that you think is missing.

Further, you can search our C. elegans literature corpus using Textpresso
at this link: http://www.textpresso.org/celegans/

Best,
Karen



~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Mon, Mar 27, 2017 at 7:13 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   How do I find the complete description of the allele e794 in C. elegans?
> Where is the place where I can look up the function of each allele? I
> cannot seem to find the allele e794 in the description at all. Please help!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5509. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5509>.
>
> Reported by: Brittani (bwiseman14@hastings.edu)
> 28 Mar 17 02:15
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8
> (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
