### ISSUE TITLE
  I would like to get the FPKM values (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5511]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to get the FPKM values (or other similar expression values) for all genes at L4 and young adult timepoints. I can see the data per gene e.g. for http://www.wormbase.org/species/c_elegans/gene/WBGene00009226 in the sections "FPKM expression data from selected modENCODE libraries" and "Aggregate expression estimates", but I can't work out how to get that data for all genes. Please advise. Thanks.</p>

**Reported by:** Alas********** (acri********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by gw3** [comment]
You can find the values for the table "Aggregate expression estimates" 
for all genes in the FTP file:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS258/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS258.RNASeq_controls_FPKM.dat

The L4 larvae life-stage is WBls:0000038
The adult life-stage is WBls:0000041

Gary Williams
WormBase
