### ISSUE TITLE
  par-5 expression data don't load ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5512]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;par-5 expression data don't load</p>

**Reported by:** Chlo* (chlo***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by chris-grove** [comment]
Hi Chloe,
can you give it another try?
the page loads fine for me (in Firefox).

http://www.wormbase.org/species/c_elegans/gene/WBGene00003920#10c3--10

thanks,
Daniela

**Comment by chris-grove** [comment]
yes it did after reloading, sorry I should have tried it before sending an email
thank you for your quick reply!!

Chloe
