### ISSUE TITLE
  Hi, I'm trying to find primers for th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5513]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm trying to find primers for the lmp-1 mutant strain PD4482, but there are none up here. I was told use the 'Contact Us' feature to see if you knew who I could get into contact with to try to find these.  Thanks!</p>

**Reported by:** Tom (thm4***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36

**Comment by chris-grove** [comment]
Hi Tom,

It looks like you're looking for sequence details of the nr2045 locus:


http://www.wormbase.org/species/c_elegans/variation/WBVar00091393#0-257-10

Unfortunately the sequence has not been curated yet, and the sequence details do not seem to be explicitly stated in the papers that reference the allele (see the "References" section on the link above). You may need to contact the authors of those papers to get specifics on the sequence. The strain page:


http://www.wormbase.org/species/c_elegans/strain/PD4482#014--10


says, in the "Curatorial remarks" that the deletion spans exons 1-3 (out of 4), so you're best bet may be to sequence the region yourself (if the other publication authors cannot help).


Chris Grove

WormBase
