### ISSUE TITLE
  I am getting internal errors on many ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5514]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am getting internal errors on many of my searches</p>

**Reported by:** sfor************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by tharris** [comment]
Hello sfore -

My apologies for the difficulties. I've identified the source of the problem, which is now resolved.

Thanks again for contacting us. 

Todd
