### ISSUE TITLE
  The aex-3(sa5) mutation is 'not curat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5515]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The aex-3(sa5) mutation is 'not curated'. Do you have information about this mutation but have not published it yet?</p>

**Reported by:** tita*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by tuli** [comment]
Dear Titas,

Thank you for writing to WormBase.

I have done some literature searching for the molecular details of sa5
(both within the References that are listed on the sa5 Variation
summary page, and via TextPresso) but unfortunately cannot find
further details.

This variation was generated at the James Thomas lab. His contact
details can be found
http://www.wormbase.org/resources/person/WBPerson655
He may be able to help you.

Best wishes,

Mary Ann

On 29 March 2017 at 20:50,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   The aex-3(sa5) mutation is 'not curated'. Do you have information about
> this mutation but have not published it yet?
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5515. Follow progress on our
> issue tracker.
>
> Reported by: titas.sengupta@yale.edu
> 29 Mar 17 19:50
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/56.0.2924.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
