### ISSUE TITLE
Hi, I come back one more time with my same questio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5520]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I come back one more time with my same question. Do I have an mammalian orthologue of C elegans ''Aminopeptidase B''. Some article associated with, is welcome.

Thanks

**Reported by:** Brun* (brun**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 56.0.2924.87

**Comment by chris-grove** [comment]
Hi Bruno,


 If you know the C. elegans gene, you can find the list of orthologs in other species within the "Homology" widget on that gene's WormBase gene page. To find references open the "References" widget. It appears that the human Aminopeptidase B gene is RNPEP:


http://www.uniprot.org/uniprot/Q9H4A4

You can find the WormBase page for the human RNPEP gene here:


http://www.wormbase.org/species/homo_sapiens/gene/ENSG00000176393#06--10


In the Homology widget it shows two C. elegans genes as orthologs: ZC416.6, C42C1.11


Here are their respective gene pages with Homology and References widgets open:


http://www.wormbase.org/species/c_elegans/gene/WBGene00022610#06e--10


http://www.wormbase.org/species/c_elegans/gene/WBGene00016589#06e--10


You can find orthologs for these genes in the homology widget on each page.


Best,


Chris Grove

WormBase
