### ISSUE TITLE
  Please correct the ref-1 gene page.  ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5521]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Please correct the ref-1 gene page.  The description mistakenly refers to "nfx-1" which instead should read "nxf-1" These are two different genes.</p>

**Reported by:** crai******* (crai********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by chris-grove** [comment]
Hi Craig,


 Thanks for the feedback. I couldn't seem to find mention of "nfx-1" on the ref-1 gene page, but I found the reference to nfx-1 in the ref-2 gene description. I've gone ahead and changed "nfx-1" to "nxf-1". This change will be visible in the WS260 release of WormBase which is expected to be available at the end of July.


Thanks again,


Chris Grove
