### ISSUE TITLE
I am dissapointed by Wormbase trying to find simpl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5525]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am dissapointed by Wormbase trying to find simple facts and/or upgrades on the structure and function of the Renette-cells or H-cells; nothing useful in this base! Or perhaps you can tell me what has to be typed in to find papers or articles on the worm excretion. I'd like to see review or proper articles to get into the systems...but how?

**Reported by:** Hein************* (dirc******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/paper/excretory">http://www.wormbase.org/search/paper/excretory</a>
**Browser:** Firefox 52.0

**Comment by raymond91125** [comment]
Hi Heinrich,

You can find information about excretory canal via anatomy term search. 
A direct link here 
<http://www.wormbase.org/species/all/anatomy_term/WBbt:0005775#0132--10>.

In the Overview, there is a specific link to the additional information 
about the excretory system at WormAtlas.org, which provides extensive 
textbook writings about C. elegans anatomy.

Hope you're less disappointed after reviewing the available information. 
We are indeed deficient on general and comparative nematode anatomy. We 
would appreciate any suggestions or collaborations.

Cheers,

Raymond


On 04/03/2017 02:12 AM, no-reply@wormbase.org wrote:
> offline chat I am dissapointed by Wormbase trying to find simple facts 
> and/or upgrades on the structure and function of the Renette-cells or 
> H-cells; nothing useful in this base! Or perhaps you can tell me what 
> has to be typed in to find papers or articles on the worm excretion. 
> I'd like to see review or proper articles to get into the 
> systems...but how?
>
> Submitted From:
>   http://www.wormbase.org/search/paper/excretory 
> http://www.wormbase.org/search/paper/excretory 
> <http://www.wormbase.org/http://www.wormbase.org/search/paper/excretory>
>
> This issue has been assigned ticket number: #5525. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5525>.
>
> Reported by: Heinrich Dircksen (dircksen@zoologi.su.se)
> 03 Apr 17 09:12
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi Heinrich,

Thanks for the feedback. Our web site does by default target molecular 
geneticist users more than others. But we should have more ramps to 
educators, students, and the public.

Comparative nematode anatomy is a large subject. If you run into any 
experts in the future, please send them our way for collaboration.

Best regards,

Raymond


On 04/03/2017 10:57 AM, Heinrich Dircksen wrote:
>
> Thanks a lot Raymond, it was really not easy to find.
>
> Maybe you should introduce on the first (or home) pages of Wormbase 
> some easy-to-reach categories or links so-to-say for the beginner to 
> enter the (fine) anatomy before getting familiar with the other much 
> more complex (molecular and genetic) details.
>
> I have started with the search function in Wormbase and got 
> nowhere...I did not know (or see any clearcut link) to the Wormatlas; 
> most likely my fault...
>
> Not easy to find general and comparative nematode anatomy on Pubmed or 
> Google, after more than 2 hours of searching I found 2 attached papers 
> (one recent one classic) which are relatively useful but still pretty 
> specific or special. Most of the nextbook knowledge is, however, often 
> simply useless... Unfortunately, I am not working in the nematode 
> field but have to teach basic and advanced aspects of nematodes which 
> I had not quite fully understood, and this is surely always 
> bad...well, I cannot contribute anything so easily.
>
> Therefore, thanks again and best regards
>
> Heinrich
>
>
>
> On 03/04/2017 17:37, Raymond Lee wrote:
>> Hi Heinrich,
>>
>> You can find information about excretory canal via anatomy term 
>> search. A direct link here 
>> <http://www.wormbase.org/species/all/anatomy_term/WBbt:0005775#0132--10>.
>>
>> In the Overview, there is a specific link to the additional 
>> information about the excretory system at WormAtlas.org, which 
>> provides extensive textbook writings about C. elegans anatomy.
>>
>> Hope you're less disappointed after reviewing the available 
>> information. We are indeed deficient on general and comparative 
>> nematode anatomy. We would appreciate any suggestions or collaborations.
>>
>> Cheers,
>>
>> Raymond
>>
>>
>> On 04/03/2017 02:12 AM, no-reply@wormbase.org wrote:
>>> offline chat I am dissapointed by Wormbase trying to find simple 
>>> facts and/or upgrades on the structure and function of the 
>>> Renette-cells or H-cells; nothing useful in this base! Or perhaps 
>>> you can tell me what has to be typed in to find papers or articles 
>>> on the worm excretion. I'd like to see review or proper articles to 
>>> get into the systems...but how?
>>>
>>> Submitted From:
>>> http://www.wormbase.org/search/paper/excretory 
>>> http://www.wormbase.org/search/paper/excretory 
>>> <http://www.wormbase.org/http://www.wormbase.org/search/paper/excretory> 
>>>
>>>
>>> This issue has been assigned ticket number: #5525. Follow progress 
>>> on our issue tracker <https://github.com/WormBase/website/issues/5525>.
>>>
>>> Reported by: Heinrich Dircksen (dircksen@zoologi.su.se)
>>> 03 Apr 17 09:12
>>>
>>> This question was reported via the web interface at wormbase.org. 
>>> You can also email us <mailto:help@wormbase.org> directly.
>>>
>>> -- 
>>> -- 
>>> You received this message because you are subscribed to the 
>>> "WormBase: help" group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>> ---
>>> You received this message because you are subscribed to the Google 
>>> Groups "WormBase: help" group.
>>> To unsubscribe from this group and stop receiving emails from it, 
>>> send an email to help+unsubscribe@wormbase.org 
>>> <mailto:help+unsubscribe@wormbase.org>.
>>
>>
>> -- 
>> __
>> Raymond Lee
>> raymond@caltech.edu
>> http://www.WormBase.org/
>> California Institute of Technology
>> Division of Biology and Biological Engineering
>> Mail Code 156-29
>> Pasadena, CA 91125
>> USA
>> tel: 626.395.2687
>
> -- 
> ================================================================
> Prof. Dr. Heinrich Dircksen
> professor of zoology
> Stockholm University
> Dept. Zoology FM
> Svante Arrhenius väg 18A
> S-10691 Stockholm, Sverige
> Tel.: 0046-8-164076
> Fax.: 0046-8-167715
> Email:dircksen@zoologi.su.se
> Web:http://www.zoologi.su.se/about/staff/person.php?suuid=hdirc
> http://www.zoologi.su.se/research/morphology/daphnia/index.php
> ================================================================


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
