### ISSUE TITLE
searching for Unc mutants with neuronal defects

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5526]
Hi Wormbase,

I am interested in searching Wormbase for all unc genes, whose loss of function phenotype results from a defect in neuronal function rather than muscular function.  That is, I want those uno genes whose products function in neurons rather than muscle.  Is there a fast way to do this or do I have to go through each gene entry one by one?  Thanks for any help you can provide.

Best Regards,

Kevin O’Connell
Senior Investigator
Laboratory of Biochemistry and Genetics
National Institute of Diabetes & Digestive and Kidney Diseases
8 Center Drive, Room 2A07
Bethesda, MD 20892-0830

Phone: 301-451-4557
Fax: 301-402-0240

**Comment by chris-grove** [comment]
Hello Kevin,


 I think the best query we can do to get what you're looking for is to look for all "unc" genes (with a "locomotion variant" or descendant phenotype annotation) that are expressed in neurons but not in muscle. I took advantage of the "Ontology Browser" widget on the phenotype page (to get all unc genes) and the anatomy pages (to get all genes expressed in neurons or muscle). The ontology browser widget gives you a link to a list of genes that are annotated to that ontology term or any of its is_a descendant terms (e.g. "pharyngeal neuron is a neuron"). Ideally you could import this list directly into WormMine, but at the moment this isn't working quite right, so I would paste the list of genes into our SimpleMine tool (available under the tools menu) and download the list of WB Gene IDs. We can then import these lists of genes into WormMine and then perform list comparison operations to get all "unc" genes that are expressed in neurons but not in muscle. I've attached the resulting list of 662 C. elegans genes in an Excel file.


I'd be happy to guide you through the process step-by-step if you'd like.


Best,


Chris Grove

WormBase
