### ISSUE TITLE
  Hi We are organizing the second C. el...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5530]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>We are organizing the second C. elegans course in Barcelona:<br/>http://www.crg.eu/en/event/coursescrg-celegans<br/>We wonder how  announce that at wormbase. Could you poste it as meeting/event, or should we write to the forum?<br/>Thanks for your help !</p>

**Reported by:** juli******** (jcer********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by epaule** [comment]
I added it to the C.elegans section of our "Meetings" section.
