### ISSUE TITLE
WormMine google login 400

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5531]
Hi,

I'm getting a 400 on the WM 257 instance.

![imgoogle404](https://cloud.githubusercontent.com/assets/717707/24653691/c49b0d44-192e-11e7-9183-0c5ff8baeee6.png)

Paul

**Comment by sibyl229** [comment]
Hi @Paul-Davis That should be fixed now. Though there is a different issue after you login. Looking into it right now. 

Hi @nuin the original issue is due to OAuth2 callback URL not added for the im-257 prefixed url. Just in case you need to fix it in the future, you can add it in the Google developer console (website), I should have given you permission before. (all the callback URLs have to be exact match, not regex allowed, probably to avoid accidental security breach).

**Comment by nuin** [comment]
Thanks @sibyl229, I will check with you about the Google developer console.

**Comment by sibyl229** [comment]
Hi @nuin actually, I think the im-257 URL probably should not have become exposed to public. I used to update those hardcoded "im-257" to be "intermine" instead, right before releasing it to production. (There might be a better approach, but I couldn't find it). Everything should be documented in the intermine google docs under pre-release checklist or something like that.

**Comment by Paul-Davis** [comment]
Thanks @sibyl229 and @nuin for looking at it so quickly :)

**Comment by nuin** [comment]
@Paul-Davis Most people at InterMine's support channel seem to be away, I will check with them as soon as I can.

**Comment by nuin** [comment]
@Paul-Davis I tried replicating the problem in our dev instance with my credentials and I got an error different than yours, but I was able to actually login. I contacted InterMine about the problems and they  get the same error on other mines and are unaware of of a possible solution at the moment. 

I will report back when I get something else.

**Comment by Paul-Davis** [comment]
@nuin thanks for the update

**Comment by nuin** [comment]
Just a heads-up from InterMine:

> Google changed their API again, and we've now updated our code to match (again). Please update as soon as you can so that your users can use their Google login with their mine:

	https://github.com/intermine/intermine/releases

>The change Google made doesn't prevent your users from being authenticated. That still works. However they'll get an error message on logging in regarding their alias, and might assume they were not able to log in.

>For the technical details, see the GitHub ticket:

	https://github.com/intermine/intermine/issues/1533

>If you have any problems upgrading, please let me know!

**Comment by nuin** [comment]
@Paul-Davis Please try again. We built WormMine with InterMine 1.7.2 and I tested my login and it worked.

**Comment by sibyl229** [comment]
Login works for me. Closing.
