### ISSUE TITLE
  I would like a nomenclature strains c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5536]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like a nomenclature strains created in my laboratory.<br/>What should I do?<br/>thank you<br/>visitor_name</p>

**Reported by:** Adel******* (adel*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25

**Comment by tuli** [comment]
Dear Adele,

Thank you for writing to WormBase.

The guidelines on how to register a new laboratory and receive strain
and allele designations can be found in the Overview section our
Nomenclature guidelines:
http://www.wormbase.org/about/userguide/nomenclature

Best wishes,

Mary Ann

On 6 April 2017 at 15:49,  <no-reply@wormbase.org> wrote:
> Question:
>
>   I would like a nomenclature strains created in my laboratory.
> What should I do?
> thank you
> Adele Adamo
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5536. Follow progress on our
> issue tracker.
>
> Reported by: Adele Adamo (adele.adamo@ibbr.cnr.it)
> 06 Apr 17 14:49
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML,
> like Gecko) Version/8.0 Safari/600.1.25
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by raymond91125** [comment]
Hi Adele,

You may start with this document 
<http://www.wormbase.org/about/userguide/nomenclature#l0bck1g4m--10>. 
Contact us if you need more information.

Thanks.

Raymond


On 04/06/2017 07:49 AM, no-reply@wormbase.org wrote:
> Question:
>
>   I would like a nomenclature strains created in my laboratory.
> What should I do?
> thank you
> Adele Adamo
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5536. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5536>.
>
> Reported by: Adele Adamo (adele.adamo@ibbr.cnr.it)
> 06 Apr 17 14:49
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 
> (KHTML, like Gecko) Version/8.0 Safari/600.1.25
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
