### ISSUE TITLE
Citing WormMine

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5537]
Hello.
Could you tell me the preferred reference citation for WormMine?

Best regards,
Michelle

**Comment by chris-grove** [comment]
Hello Michelle,


 My colleagues can correct me if I'm wrong, but I think the first place we have mentioned WormMine in a publication is in this paper:


https://www.ncbi.nlm.nih.gov/pubmed/24194605

You could also mention this WormBase paper:


https://www.ncbi.nlm.nih.gov/pubmed/26578572



Chris Grove

WormBase
