### ISSUE TITLE
  Hi, I lost my account and forget my p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5538]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I lost my account and forget my password.  I used this address before as my account ID.  </p>

**Reported by:** Qi H*** (hall***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by sibyl229** [comment]
User has been contacted. Closing.
