### ISSUE TITLE
  Is there a way to pull out all transm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5539]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a way to pull out all transmembrane proteins in the Ce genome and sequence for their transmembrane domains?<br/>Thanks a lot in advance!</p><p>What were you doing? <br />&nbsp;&nbsp;I wanted to see if there is a common feature for the transmembrane domains of all proteins that are localized to sensory cilia. Thanks a lot in advance!</p>

**Reported by:** Juan***** (juwa******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thanks for contacting WormBase, searching the database I could find 101 
Pfam domains that refer to transmembrane in their Title.

PF00001
PF00002
PF00003
PF00664
PF00939
PF01127
PF01389
PF01490
PF01794
PF01891
PF02683
PF02790
PF02921
PF02932
PF03409
PF03647
PF03821
PF04148
PF04505
PF04549
PF05602
PF05977
PF06472
PF06814
PF07114
PF07787
PF07857
PF08693
PF09049
PF09125
PF09163
PF09534
PF09608
PF09656
PF09721
PF09726
PF09771
PF09772
PF09773
PF09777
PF09788
PF10149
PF10190
PF10192
PF10267
PF10268
PF10269
PF10271
PF10272
PF10507
PF10639
PF10716
PF11044
PF12077
PF12089
PF12369
PF12371
PF13272
PF13386
PF13748
PF13755
PF14400
PF14402
PF14575
PF14640
PF14770
PF14812
PF14935
PF14940
PF14979
PF14995
PF15009
PF15029
PF15062
PF15071
PF15190
PF15330
PF15332
PF15345
PF15383
PF15431
PF15444
PF15471
PF15475
PF15664
PF15705
PF15706
PF15816
PF15817
PF15841
PF15844
PF15872
PF15877
PF15982
PF16054
PF16070
PF16214
PF16311
PF16913
PF16995
PF17028

Using this as a filter on the WormBase ParaSite Biomart

http://parasite.wormbase.org/biomart/martview/7fc5dbaddd12c2899a8a1835701e8535

and also filtering for species (C. elegans) 340 genes were identified. 
It is then possible to output the protein sequence.

I hope this helps.

Paul



On 07/04/2017 13:40, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Is there a way to pull out all transmembrane proteins in the Ce 
> genome and sequence for their transmembrane domains?
> Thanks a lot in advance!
>
> What were you doing?
>   I wanted to see if there is a common feature for the transmembrane 
> domains of all proteins that are localized to sensory cilia. Thanks a 
> lot in advance!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5539. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5539>.
>
> Reported by: Juan Wang (juwang@dls.rutgers.edu)
> 07 Apr 17 12:40
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/56.0.2924.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
