### ISSUE TITLE
  Dear staff, How can I add information...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5540]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear staff,<br/>How can I add information about my lab?<br/>Thanks</p>

**Reported by:** Daia************** (avil**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by tuli** [comment]
Dear Daiana,

Thank you for writing to WormBase.

It looks like you are not currently associated with a Laboratory in WormBase.
Please read the Overview section of the guidelines available here:
http://www.wormbase.org/about/userguide/nomenclature which will
explain the steps you need to do to register a new laboratory and
receive lab, strain and allele designations.

Thank you,

Mary Ann


On 7 April 2017 at 16:15,  <no-reply@wormbase.org> wrote:
> My Account
>
>   Dear staff,
> How can I add information about my lab?
> Thanks
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5540. Follow progress on our
> issue tracker.
>
> Reported by: Daiana Silva Avila (avilads1@gmail.com)
> 07 Apr 17 15:16
>
> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/57.0.2987.133 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
