### ISSUE TITLE
ftp from wormbase

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5541]
Hi,
I’m trying to login to the ftp site, but it is asking for username and password. I tried “anonymous” with my e-mail as password, but this did not work. Is there something else I should be doing?
thanks,
dave

**Comment by nuin** [comment]
It’s strange ATM. I am getting this

 ftp ftp.wormbase.org
Connected to ftp.wormbase.org (206.108.120.212).
421 There are too many connected users, please try later.
