### ISSUE TITLE
I am looking for information on the splice variant...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5543]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking for information on the splice variants and their expression for different mutant strains such as dyp-10 and bli-1.

**Reported by:** Ryan****** (clar****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000251#0-9g12345678abc-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000251#0-9g12345678abc-10</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by epaule** [comment]
you can got to the respective transcript pages: http://www.wormbase.org/species/c_elegans/transcript/C09G5.6.2 and http://www.wormbase.org/species/c_elegans/transcript/C09G5.6.1 and have a look in the expression widget for non N2 backgrounds.

I don't think we have fully integrated the background/expression in our WormMine, but then it is only two transcripts.
