### ISSUE TITLE
the blast service page is giving an error 502 bad ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5546]
*Help Desk query collected when no chat operators were online. Follow up required.*

the blast service page is giving an error 502 bad gateway

**Reported by:** M. w********** (wdav*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 49.0.2623.112

**Comment by chris-grove** [comment]
Hi Wayne -

Sorry for the difficulties. The blast service has been restored -- have at it!

Todd
