### ISSUE TITLE
  How do I convert the corresponding ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5547]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I convert the corresponding genomic coordinate from one version to another. For example, how do I convert the coordinate in WS220 to WS240?<br/>Thanks.</p>

**Reported by:** Liji******** (long*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by epaule** [comment]
we have a small per script that lets you map GFFs between the various releases: http://wiki.wormbase.org/index.php/Converting_Coordinates_between_releases

you can also try the UCSC liftover tool for BED/WIG, if the releases you want have been used by UCSC: http://www.wormbase.org/about/Frequently_asked_questions
