### ISSUE TITLE
  information about dumpy phenotype ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5548]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;information about dumpy phenotype</p>

**Reported by:** Fran******** (fmia*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by epaule** [comment]
the search box on the top right corner actually has a drop-down menu, that is not too obvious.
You can switch that to different datatypes, which will allow you to search for dumpy in the phenotype category.
