### ISSUE TITLE
Hello. I'm trying to find a database with the loca...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5549]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello. I'm trying to find a database with the location or spatial position of the neurons and synapses of the C. elegans. Looking at the "Virtual Worm Project" (http://caltech.wormbase.org/virtualworm/), I guess this information is probably included in their Virtual Worm Blend File, but they also refer to WormBase. I can not find a normal text file with this information, I looked at all the databases of http://www.wormatlas.org/neuronalwiring.html but in none of them the neurons and synapses locations are clear enough to construct something so precise such as the Virtual Worm, for example. Where else should I look? Many thanks!

**Reported by:** Jorg* (jorg*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Firefox 52.0

**Comment by chris-grove** [comment]
In communication with user. Closing ticket
