### ISSUE TITLE
  I wanted to find snip-snps to map a m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5552]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I wanted to find snip-snps to map a mutant using N2 vs hawaiian polymorphisms with a student.  Is this still possible?<br/>-Thanks,<br/>visitor_name</p>

**Reported by:** Bob (ohag**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
I didn't see a simple way to do that, but I dug up CB4856 SNPS with RFLPs (in the attached list).
Some actually have also the PCR products on their pages.
