### ISSUE TITLE
No updated (beyond WS254) gene functional description files on FTP site

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5553]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_email): hi, could you tell which file in the FTP contains functional description of genes?</br>visitor_name (visitor_email): it used to be in one of the annotation files, but it seems it's gone since WS255</br>Chris: Sure, one moment while I look up the correct file</br>Chris: It looks like this is the proper place for the functional description file:</br>Chris: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/functional_descriptions/</br>Chris: but it looks like our scripts stopped producing the file last August</br>Chris: Let me keep digging to see if I can find updated descriptions</br>visitor_name (visitor_email): thank you, that was my question</br>Chris: OK, it looks like I can't find description files for anything beyond the WS254 release, if that's good enough for you for now, but I'll be sure to look into where the updated descriptions are and get back to you</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): if you can let me know where to find the updated description, that would be great. thank you very much</br>Chris: OK, I will send you an email as soon as I find out</br>visitor_name (visitor_email): thanks a lot, happy easter, bye bye</br>Chris: Thank you, you too! Take care

**Reported by:** Jim (jiax***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Safari 10.1

**Comment by chris-grove** [comment]
@tharris @khowe 
It appears that the functional descriptions file on the FTP site has not been generated since August 2016 (about the WS254 release). The two locations that seem to be the place for this file are here:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/functional_descriptions/

and here

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/functional_descriptions/

Any ideas as to what might be going on or how to generate the updated files?

Thanks!

**Comment by khowe** [comment]
This is another one that used to be generated as part of the OICR staging process. 

For the interactions file, we have the script and it will be run as part of the Hinxton build from WS260. If someone points us to the script for functional descriptions, we can do that same for that.

**Comment by chris-grove** [comment]
@tharris 
Can you point @khowe to the script for this file?

**Comment by chris-grove** [comment]
@tharris 
Do you know where the script to generate the functional descriptions file is, or who would know?
Thanks!

**Comment by sibyl229** [comment]
Hi @chris-grove @tharris is on vacation until next Tuesday. I think he will know for sure. I never worked on the staging process, but a search among the code repositories that I know of, this file came up: https://github.com/WormBase/website-admin/blob/master/update/staging/annotation_dumpers/dump_species_functional_descriptions.pl I'm not sure if this is the right one.

**Comment by chris-grove** [comment]
@sibyl229 
Ok thanks! We can wait for Todd to get back. That file you found looks like the right one, but we'll wait for Todd to confirm.

**Comment by khowe** [comment]
@epaule another one to add to the set (see above)

**Comment by khowe** [comment]
@sibyl229 is website-admin a private repo to OICR members of WormBase? I don't see it under WormBase in github.

**Comment by sibyl229** [comment]
Hi @khowe it's a private repo, but I can't really tell who has access to it. I imagine it's kept private because it has sensitive system related information.

**Comment by khowe** [comment]
I can tell you who doesn't have access to it: me! 

Would you mind sending the script directly to @epaule ? He's working on wrapping these scripts into the main Hinxton build.

**Comment by sibyl229** [comment]
@khowe done. It was sent to both of you.

**Comment by epaule** [comment]
We will add it to our build over here. When @tharris is back we might want to check if we can move more of the file-dumping over.

**Comment by chris-grove** [comment]
@khowe @epaule @sibyl229 @tharris 
Just checking in: Any update on this?

**Comment by tharris** [comment]
The scripts are part of a generic harness that I wrote years and years ago. The intent was that anyone could contribute dumping scripts. There are both species specific scripts -- which are generated for each species found on the FTP site -- and for non-species related data, like laboratories.
[annotation_dumpers.zip](https://github.com/WormBase/website/files/968911/annotation_dumpers.zip)

**Comment by epaule** [comment]
Thanks. I will try to stuff as many of them as possible into Gary's build.

**Comment by epaule** [comment]
@tharris is the one that mails you and Thomas Burglin new publications actually in use?

**Comment by tharris** [comment]
obviously doesn't need to be part of the build

**Comment by chris-grove** [comment]
Any update on this? Are we waiting for the next build? Can we generate a file for the current release?

**Comment by khowe** [comment]
@epaule is working on getting these into the current build (WS260).

**Comment by epaule** [comment]
That is going into WS260. But if you just want a file to send to the user,
I can run it quickly outside of the build on the old release.

M

**Comment by chris-grove** [comment]
@epaule 
Yes, I'd like to get something to the user soon. That would be great if you could run the script on an earlier release so I can send him that file.

**Comment by epaule** [comment]
@chris-grove  [ws259_c_elegans_funtional_descriptions.txt.gz](https://github.com/WormBase/website/files/1007989/ws259_c_elegans_funtional_descriptions.txt.gz)

**Comment by chris-grove** [comment]
@epaule 
Perfect! Thanks!

**Comment by epaule** [comment]
@tharris can you resync the WS260 functional description files, as the non C.elegans ones were a but sparse on our FTP site.

**Comment by tharris** [comment]
Resynced. Hinxton FTP site has been really slow, BTW. Syncing WS260 took > 24 hours.

**Comment by khowe** [comment]
@tharris we'll look into this. What's a typical sync time?

**Comment by tharris** [comment]
At least ten times faster -- typically on order of two hours per release, or something like 1Mb/sec.  Perhaps it would be worthwhile to write new releases directly to canonical FTP site? Would not address congestion, but would be one less synchronization step.

**Comment by epaule** [comment]
I do use the EBI FTP site to load balance the UCSC hub, but I don't think
anything speaks against "releasing" it to both in a push fashion.

**Comment by gw3** [comment]
@tharris can you resync the FTP  WS260/ONTOLOGY/disease_ontology.WS260.obo file, as Ranjana provided us with an updated one which is now on our FTP site.
