### ISSUE TITLE
Please tell me the evidence for calling the 5' end...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5557]
*Help Desk query collected when no chat operators were online. Follow up required.*

Please tell me the evidence for calling the 5' end of the short transcripts B0496.3c.1 and B0496.3c.2, which begin so far downstream of the other 2 known promoter regions.

**Reported by:** Pame******** (pame******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/B0496.3c.2#06--10">http://www.wormbase.org/species/c_elegans/transcript/B0496.3c.2#06--10</a>
**Browser:** Chrome 57.0.2987.133

**Comment by gw3** [comment]
Pamela,

The isoform B0496.3c has been created based on the mRNA sequence 
FJ169450 which has four 5' UTR exons.
This number of UTR exons is very unusual and we would normally not 
create a coding isoform if we only had EST evidence for the transcript.
We generally tend to believe authors when they are confident enough to 
assert that their data is evidence of there being a mRNA producing a 
protein product.


Our coding transcript data is automatically produced by taking the 
manually curated CDS structures (in this case, 'B0496.3c') and finding 
mRNA, EST and Trinity transcripts which match them.

In the case of B0496.3c.1 this is EST: 'yk356a4.3', 'yk405f4.3', 
'yk159d1.3', 'yk286b1.3','yk315d2.3', 'yk360b4.3', 'yk1269h06.3', 
'yk1232g01.3', 'yk1646f05.3', 'yk1749g10.3', 'yk1121c09.3', 
'yk896c08.3', 'yk1305a10.3', 'RST3_378116', 'yk1662a06.3'; and Trinity: 
'elegans_PE_SS_GG8201|c2_g2_i13'.

In the case of B0496.3c.2 this is EST: 'yk1662a06.3', 'RST3_378116', 
'yk1305a10.3', 'yk896c08.3', 'yk1121c09.3', 'yk1749g10.3', 
'yk1646f05.3', 'yk1232g01.3', 'yk1269h06.3', 'yk360b4.3', 'yk1232g01.5', 
'yk315d2.3', 'yk286b1.3', 'yk159d1.3', 'yk405f4.3', 'yk356a4.3'; and 
mRNA:  'FJ169450'.

These matching transcripts are used to extend the CDS structures to 
produce the coding transcript structures (in this case B0496.3c.1 and 
B0496.3c.2).

If you have any evidence that will confirm or refute the existence of 
this isoform, we would be pleased to hear from you.

Gary Williams
WormBase
