### ISSUE TITLE
it is ok...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5558]
*Help Desk query collected when no chat operators were online. Follow up required.*

it is ok

**Reported by:** dan (dan_******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/H13N06.3a#06--10">http://www.wormbase.org/species/c_elegans/transcript/H13N06.3a#06--10</a>
**Browser:** Chrome 57.0.2987.133

**Comment by chris-grove** [comment]
I've replied to user to check if there's a question. I will close when appropriate.

**Comment by chris-grove** [comment]
Haven't heard back. I'll close now and reopen if necessary.
