### ISSUE TITLE
until recently, were the C. briggsae gene predictions taken from Uyar et al. (2012), PubMed ID 22772596?

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5560]
Hi all,

It's my recollection that, until quite recently, the WormBase gene prediction set for C. briggsae was taken from the work of Jack Chen's laboratory described by Uyar et al. (2012):

    https://www.ncbi.nlm.nih.gov/pubmed/22772596

Is that putative recollection correct?

(I'm aware that there has lately been an ongoing effort to correct gene models in briggsae, based on RNA-seq data, carried on by Gary Williams and others...)

--Erich

**Comment by epaule** [comment]
I vaguely remember that NGASP predictions were used as C.briggsae gene set. At least there are quite a few CDSes with "corrected based on jigsaw" in the database.

But we do have a GenBlastG track for C.briggsae (as described in the paper, just updated every release) which is probably closer to the JC geneset.

If you are coming to the IWM, you can also grab Gary for his newer C.briggsae work.
