### ISSUE TITLE
JBrowse "RNASeq introns" track missing

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5561]
The JBrowse track "RNASeq introns" is not being displayed as expected.
See:

http://www.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=II%3A12459632..12460723&tracks=Curated_Genes%2CRNASeq%20introns&highlight=

**Comment by scottcain** [comment]
Looking into it--it's available on staging; I'm not sure what happened with 258.

**Comment by scottcain** [comment]
Fixed.  I had to recreate the track data from the 258 GFF file but all is well now.
