### ISSUE TITLE
  I am trying to view EST evidence for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5562]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to view EST evidence for the gene model of noah-1 and cannot view the alignment in either Gbrowse or Jbrowse. I have tried multiple internet browsers including Safari, Chrome, and Firefox to no avail. I don't know if it's a compatibility issue with my computer or a problem with the genome browser software. I would appreciate any help greatly.</p>

**Reported by:** chlo******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by raymond91125** [comment]
Hi,

See attached screen capture for the GBrowse view of noah-1 region 
obtained just now. Is that the type of alignments you want to see? You 
may have to configure the track by clicking on the wrench icon and chose 
Spacing->Expand. If you still have trouble, let us know.

Cheers,

Raymond

**Comment by chris-grove** [comment]
@scottcain 
The ESTs(best) track is not displaying data on live JBrowse (it is displaying on staging)

**Comment by chris-grove** [comment]
Email to user:
"Hello Chloe,


 Unfortunately it looks like the live JBrowse is not showing the data for the ESTs (best) track, although you can view it on our staging site (staging.wormbase.org). Please keep in mind that our staging site is not stable and is not meant for regular use. Our genome browser expert is working on a solution. You can follow progress on GitHub here:


https://github.com/WormBase/website/issues/5562


Best,


Chris Grove"

**Comment by scottcain** [comment]
After @gw3 reported a problem yesterday with a different track, I looked today to check all of the tracks and found a few including this one that are missing data.  I was already working on it when I saw this bug report.  It should be fixed within the hour.

**Comment by chris-grove** [comment]
@scottcain  Thanks!

**Comment by scottcain** [comment]
@chris-grove OK, the ESTs (best) track is fixed.  I'll leave this open so you can inform the user.  There are still a few tracks I'm working on but those will be fixed before the end of the day.

**Comment by chris-grove** [comment]
Hi Chloe,


 JBrowse is now showing the EST data on the live site:

http://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CESTs%20(best)&loc=I%3A5872245..5880338&data=data%2Fc_elegans_PRJNA13758&highlight=

Best,

Chris

**Comment by chris-grove** [comment]
Thanks @scottcain

**Comment by chris-grove** [comment]
User is happy
