### ISSUE TITLE
are there genome informations about c. elegns in t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5563]
*Help Desk query collected when no chat operators were online. Follow up required.*

are there genome informations about c. elegns in this database

**Reported by:** huic********* (hcch*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide#2--10">http://www.wormbase.org/about/userguide#2--10</a>
**Browser:** Chrome 45.0.2454.101

**Comment by epaule** [comment]
as entry point, have a look at that page http://www.wormbase.org/species/c_elegans where you can get the genome of the Hawaiian strain.

In addition we annotated the SNPs between N2 and CB4856, which you can find in the N2 GFF3 file.

There are also Whole Genome Alignments, which you can see on the WormBase hub at UCSC (add the hub, pick C.elegans and turn on the Hawaii strain in the comparative tracks).

And we projected N2 gene models over and did some protein blast, which you can find here: ftp://ftp.wormbase.org/pub/wormbase/releases/WS258/species/c_elegans/PRJNA275000/c_elegans.PRJNA275000.WS258.annotations.gff3.gz
