### ISSUE TITLE
Change "Tissue Enrichment Analysis" to "Gene Set Enrichment Analysis" in Tools menu

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5565]
The tool that is linked to via the "Tissue Enrichment Analysis" link in the Tools menu now performs gene set enrichment analysis for phenotype and Gene Ontology as well, so I'd like to suggest that we change the name of the link to "Gene Set Enrichment Analysis", as it is more appropriate now.

**Comment by sibyl229** [comment]
Hi @chris-grove I update the name of the tool to "Gene Set Enrichment Analysis" on staging. The tools menu is the only place that needs changing right? Thanks

**Comment by raymond91125** [comment]
I believe so. Thanks.

**Comment by chris-grove** [comment]
@sibyl229 
Great! Looks good, thanks! Closing
