### ISSUE TITLE
Olark chats generating duplicate emails and GitHub tickets

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5568]
It seems that two emails and tickets are being generated for every Olark chat instance.

**Comment by tharris** [comment]
This no longer seems to be the case -- at least with issues that have come in the past few days. Am I missing something?

**Comment by chris-grove** [comment]
OK, yeah, it seems to have stopped. I'll reopen if necessary.

**Comment by tuli** [comment]
It's not right now.

There should be two emails for each help message, one with subject [wormbase-help] and another (from github) with subject [WormBase/website]. The latter has the long string which needs to be included in responses in order for the message to be included in git. 

See e.g. [wormbase-help] offline chat transcript: I wish to submit scaffolds, gene list and annotati... (Kaneez e Rabab) 
There is no message with subject [WormBase/website]

**Comment by chris-grove** [comment]
I did receive both emails for that inquiry

**Comment by chris-grove** [comment]
I haven't noticed this problem lately. Closing.
