### ISSUE TITLE
Genetic Map down

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5569]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have had problems when trying to load the genetic map webpage. This is the first time I write to you but is not the first time it happens. I have noticed that it varies with the time of the day but in general is a pretty annoying problem. <br/>It would be great if you can fix that.<br/>Regards<br/>visitor_name </p><p>What were you doing? <br />&nbsp;&nbsp;Browsing the genetic map and trying to identify useful deficiencies for my project.</p>

**Reported by:** Nels*** (nels******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by chris-grove** [comment]
Confirmed: getting 504 Gateway Time-out error

**Comment by chris-grove** [comment]
Hello Nelson,


 Apologies for the inconvenience. Our team is working on a fix now. You can follow progress on the issue on our GitHub issue tracker here:


https://github.com/WormBase/website/issues/5569


Best,

Chris Grove

WormBase

**Comment by chris-grove** [comment]
The map tool is still down today

**Comment by tharris** [comment]
Restored. Please contact user.

**Comment by tuli** [comment]
Dear Nelson,

I am writing to let you know that the Genetic Map has been restored.
We apologise for any inconvenience.

Best wishes,

Mary Ann

On 21 April 2017 at 07:15,  <no-reply@wormbase.org> wrote:
> Question:
>
>   I have had problems when trying to load the genetic map webpage. This is
> the first time I write to you but is not the first time it happens. I have
> noticed that it varies with the time of the day but in general is a pretty
> annoying problem.
> It would be great if you can fix that.
> Regards
> Nelson
>
> What were you doing?
>   Browsing the genetic map and trying to identify useful deficiencies for my
> project.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5569. Follow progress on our
> issue tracker.
>
> Reported by: Nelson (nelson.ramirez@phd.einstein.yu.edu)
> 21 Apr 17 06:13
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:52.0) Gecko/20100101
> Firefox/52.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
