### ISSUE TITLE
Gene Name mir-8199

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5571]
Hi Mary Ann.

miRNA name missing from the wormbase entry.

mir-8199 C40A11.10 WBGene00016553

http://www.mirbase.org/cgi-bin/query.pl?terms=mir-8199

Paul

**Comment by tuli** [comment]
Person evidence Victor Ambroz?
mirbase release v21?

**Comment by Paul-Davis** [comment]
MiRbase cite this publication.....23729632 but Jonathan Ewbank highlighted the discrepancy to me as we had a 2 exon coding gene.

**Comment by tuli** [comment]
Thanks. Done. Added paper.
