### ISSUE TITLE
  I would like to report that I found a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5572]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to report that I found a wrong dope regarding the overview information about dnj-14 gene (K02G10.8). According to WormBase, C. elegans mutants dnj-14(tm3223) and dnj-14(ok137) show an impairment in mechanosensation, but according to Kashyap et al., 2014 (paper evidence for this information) there is no such an impairment. They actually assayed mechanosensation in these strains but they couldn't find any differences between these and N2 worms performance. <br/>I hope this information is useful to you, <br/>Yours sincerely, <br/>visitor_name. </p>

**Reported by:** Marí************** (marr****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by rankishore** [comment]
@tuli, I've corrected this error in the description and hopefully Wen can use the corrected .ace file in the WS260 upload.  I will confirm this with her.  I've also written to User about this.
