### ISSUE TITLE
  HI, My name is visitor_name, building...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5573]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;HI, My name is visitor_name, building my own worm lab in Huazhong University of Science and Technology, China. I don;t know how do i register a new lab, or who should I contact with?<br/>Best, and Thanks!<br/>Shangbang</p>

**Reported by:** Shan********* (sgao************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by tuli** [comment]
Dear Shangbang,

Thank you for writing to WormBase. Instructions on registering a new
lab can be found in our nomenclature guidelines here:
http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10
(see the "How to Register a New Laboratory and Receive Lab, Strain and
Allele designations" section).

Please let me know if you have further questions.

Best wishes,

Mary Ann

On 24 April 2017 at 14:39,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   HI, My name is Shangbang Gao, building my own worm lab in Huazhong
> University of Science and Technology, China. I don;t know how do i register
> a new lab, or who should I contact with?
> Best, and Thanks!
> Shangbang
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5573. Follow progress on our
> issue tracker.
>
> Reported by: Shangbang Gao (sgao@hust.edu.cn)
> 24 Apr 17 13:38
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
