### ISSUE TITLE
URLs for Disease Ontology (DO) Terms need to be changed

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#5575]
@sibyl229 @Paul-Davis: The Disease Ontology site has proper URL's for their term pages now.  I remember @Paul-Davis, when we first imported the DO a while ago, their pages were sparse.  So we went with whatever they had.

Please update DO term URLs to the correct Disease Ontology web pages, for example, on the Alzheimer's page:
https://www.wormbase.org/resources/disease/DOID:10652#0--10
the DOID:10652 points to: http://disease-ontology.org/term/DOID%3A10652/
It should point to: http://www.disease-ontology.org/?id=DOID:10652

For the gene pages, looks like the DOID points to the WB disease report page, so this is fine:
for example, for aip-1, 
https://www.wormbase.org/species/c_elegans/gene/WBGene00000097#07-9g-3
'aip is an experimental model for Alzheimer's disease (DOID:10652)", ID goes to our disease page, so this is fine. 
Thanks!

**Comment by sibyl229** [comment]
Hi @rankishore the DO link on staging has been updated. Could you double check that? http://staging.wormbase.org/resources/disease/DOID:10652#01--10 Thank you!

**Comment by Paul-Davis** [comment]
Looks good to me :)

**Comment by rankishore** [comment]
@sibyl229.  I tested several different DO IDs and they lead to the right links on the DO site.  Will close issue. Thanks for fixing this.
