### ISSUE TITLE
I want to use blast to find the human homolog of d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5578]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to use blast to find the human homolog of dpy-11. How can I find that?

**Reported by:** Yola******* (yrav*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#04c6-9g531-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001073#04c6-9g531-3</a>
**Browser:** Safari 10.1

**Comment by chris-grove** [comment]
From Kevin:
"
Hi Yolanda, 

We have pre-calculated BLAST matches between each C. elegans protein and human proteins. If you open up the "Homology" widget on the dpy-11 gene page, you will see a table "Best BLASTP matches". That table contains a match to the H. sapiens protein "ENSEMBL:ENSP00000393316", which is an Ensembl protein. The e-value and percentage identity are shown in the table. 

Click through to Ensembl, and you will see that this protein from a transcript of the TMX1 gene. This gene is also classified as an ortholog of dpy-11, as shown on the "Orthologs" table underneath. 

Hope this helps,

Kevin Howe
WormBase Help Desk"
