### ISSUE TITLE
  References are not showing in the Ref...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5579]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;References are not showing in the Reference Widget on the Construct pages</p>

**Reported by:** Kare****** (kare**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by chris-grove** [comment]
Fixed on staging; see #6040
