### ISSUE TITLE
Dear Sir, I want to isolate RNA and DNA from soil....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5580]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear Sir, I want to isolate RNA and DNA from soil. what could be the usage of your website for my research. assist me. thanks

**Reported by:** Aqle** (aqlp*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00008566#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00008566#0-9g-3</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by chris-grove** [comment]
Hello Aqleem,


Unless you're specifically looking for information on nematodes, WormBase may not be of much help. You may want to look at more generic biological databases like NCBI:


https://www.ncbi.nlm.nih.gov/


Best,


Chris Grove

WormBase
