### ISSUE TITLE
Hi- On the genome browser for bca-2, it shows that...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5581]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi- On the genome browser for bca-2, it shows that there are MMP point mutations, but I cannot seem to access them, only the larger deletions-  also, the MMPs are not listed undergenetics on the main bca-2 page.  Can you help clarify these issues?
Thanks,
Peter

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00013805#0a9cdefjh-41g6-10-h">http://www.wormbase.org/species/c_elegans/gene/WBGene00013805#0a9cdefjh-41g6-10-h</a>
**Browser:** Chrome 58.0.3029.81

**Comment by raymond91125** [comment]
Hi Peter,

On the Gene page, Genetics widget, you can expand "Other alleles 
(currently no associated phenotype)" by clicking on the triangle to 
reveal MMP all alleles.

On GBrowse and JBrowse, the MMP track does include point mutations. You 
may have to zoom in enough to clearly see them and clicking on the 
feature should bring you to the corresponding Variation page.

Regards,

Raymond


On 04/28/2017 09:46 AM, no-reply@wormbase.org wrote:
> offline chat Hi- On the genome browser for bca-2, it shows that there 
> are MMP point mutations, but I cannot seem to access them, only the 
> larger deletions- also, the MMPs are not listed undergenetics on the 
> main bca-2 page. Can you help clarify these issues? Thanks, Peter
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00013805#0a9cdefjh-41g6-10-h 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00013805#0a9cdefjh-41g6-10-h 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00013805#0a9cdefjh-41g6-10-h> 
>
>
> This issue has been assigned ticket number: #5581. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5581>.
>
> Reported by: Peter Roy (peter.roy@utoronto.ca)
> 28 Apr 17 16:45
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
