### ISSUE TITLE
I found that three alleles of scd-2 (sa249, sa303,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5582]
*Help Desk query collected when no chat operators were online. Follow up required.*

I found that three alleles of scd-2 (sa249, sa303, sa935) are all currently misannotated on Wormbase and have the wrong sequence for the mutation, leading also to their incorrect annotation as type of mutation. I submitted new allele sequence information for all three with the correct information. Please fix these errors and let me know that you got this message.

**Reported by:** Mich********** (mail**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004740#0e6-9g481-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004740#0e6-9g481-3</a>
**Browser:** Firefox 48.0

**Comment by tuli** [comment]
Dear Michael,

Thank you for writing to WormBase and bringing these mistakes to our
attention. I would like to confirm that I have updated the 3 alleles
according to your submissions (alongside the publication). You'll see
these updates in release WS261 of WormBase.

Best wishes,

Mary Ann

On 30 April 2017 at 08:18,  <no-reply@wormbase.org> wrote:
> offline chat I found that three alleles of scd-2 (sa249, sa303, sa935) are
> all currently misannotated on Wormbase and have the wrong sequence for the
> mutation, leading also to their incorrect annotation as type of mutation. I
> submitted new allele sequence information for all three with the correct
> information. Please fix these errors and let me know that you got this
> message.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00004740#0e6-9g481-3
> http://www.wormbase.org/species/c_elegans/gene/WBGene00004740#0e6-9g481-3
>
> This issue has been assigned ticket number: #5582. Follow progress on our
> issue tracker.
>
> Reported by: Michael Ailion (mailion@uw.edu)
> 30 Apr 17 07:17
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
