### ISSUE TITLE
  How do I  to mark genomic DNA sequenc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5583]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I  to mark genomic DNA sequence in differnet colors?</p>

**Reported by:** weij*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by chris-grove** [comment]
Hello,


If you are referring to the genome browser, you may find this documentation helpful:


http://www.wormbase.org/gbrowse-static/annotation_help.html

Best,


Chris Grove

WormBase

**Comment by scottcain** [comment]
I added this:

Also, if you are using JBrowse:

https://www.wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758

some of the tracks like "Curated Genes (protein-coding)" (but not the plain "Curated Genes" track) have a sequence viewer available when you right click on a feature (giving "View Sequence" as an option).  You might get some warning messages, but after clicking through them you'll get a window where you can highlight sequence and even hide sequence (like introns to create a "in silico" processed transcript).  Some browsers will then let you copy and paste to MS Word with the highlighting intact (I know Firefox will let you do this, not sure about other browsers).  This is still somewhat of a beta feature, so if you have any problems or suggestions, please let me know.

Thanks,
Scott
