### ISSUE TITLE
I wish to submit scaffolds, gene list and annotati...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5584]
*Help Desk query collected when no chat operators were online. Follow up required.*

I wish to submit scaffolds, gene list and annotation data for a draft genome of a nematode worm. Can you give me details as how I can go about it?. For example, format of data, how much of detailing of experimental data needed, etc

Thank you

**Reported by:** Kane********** (kane**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#01--10">http://www.wormbase.org/about/userguide/submit_data#01--10</a>
**Browser:** Firefox 52.0

**Comment by tuli** [comment]
Hi Kaneez, 

WormBase is not a repository/archive for genome sequence data or assemblies. You therefore first need to submit your genome to the NCBI or EBI. I would start by sending them an email:

NCBI (US): genome@ncbi.nlm.mih.gov
EBI (Europe): datasubs@ebi.ac.uk

They will help you get started with the process. Once the genome is archived at NCBI/EBI, then we can make a genome browser for it in WormBase. 

Best,

Kevin
