### ISSUE TITLE
  Hello http://www.wormbase.org/species...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5586]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>http://www.wormbase.org/species/c_elegans/gene/WBGene00001910<br/>should appear as his-36, not C50F4.6.<br/>And a widespread typo: <br/>Photorhabdus luminescens is referred to in many places as P.lumniescens (e.g. http://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00038438:P.lumniescens_24hr_upregulated_RNAseq)<br/>Thanks</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by tuli** [comment]
Dear Jonathan,

The his-36 <->  C50F4.6 connection was removed in 2006 as the gene
does not encode a histone. This was on Jonathan Hodgkin's
recommendation. The curatorial remark explains this.

Do you have new evidence that indicates it is a histone? If not then I
will look into updating the misleading description in the Overview.

I am looking into the best way to correct the Photorhabdus luminescens
typo and will get back to you shortly.

Best wishes,

Mary Ann

On 2 May 2017 at 05:22,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hello
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001910
> should appear as his-36, not C50F4.6.
> And a widespread typo:
> Photorhabdus luminescens is referred to in many places as P.lumniescens
> (e.g.
> http://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00038438:P.lumniescens_24hr_upregulated_RNAseq)
> Thanks
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5586. Follow progress on our
> issue tracker.
>
> Reported by: Jonathan J Ewbank (ewbank@ciml.univ-mrs.fr)
> 02 May 17 04:20
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101
> Firefox/53.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
@rankishore please can you update the Description. This gene is NOT a histone. 
 
Webteam, why does a search for "gene" his-36 give this as a hit ie what do I need to remove from the curation?

**Comment by tuli** [comment]
Dear Jonathan,

Further to my earlier email, we have identified 7 database records
which cite the incorrect P.lumniescens
I have forwarded these to the appropriate curator who will let you
know when they've been updated.

Thanks for letting us know about this.

Mary Ann

On 3 May 2017 at 10:39, Mary Ann Tuli <maryann.tuli@wormbase.org> wrote:
> Dear Jonathan,
>
> The his-36 <->  C50F4.6 connection was removed in 2006 as the gene
> does not encode a histone. This was on Jonathan Hodgkin's
> recommendation. The curatorial remark explains this.
>
> Do you have new evidence that indicates it is a histone? If not then I
> will look into updating the misleading description in the Overview.
>
> I am looking into the best way to correct the Photorhabdus luminescens
> typo and will get back to you shortly.
>
> Best wishes,
>
> Mary Ann
>
> On 2 May 2017 at 05:22,  <no-reply@wormbase.org> wrote:
>> Content Correction
>>
>>   Hello
>> http://www.wormbase.org/species/c_elegans/gene/WBGene00001910
>> should appear as his-36, not C50F4.6.
>> And a widespread typo:
>> Photorhabdus luminescens is referred to in many places as P.lumniescens
>> (e.g.
>> http://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00038438:P.lumniescens_24hr_upregulated_RNAseq)
>> Thanks
>>
>> Submitted From:
>>   support /tools/support
>>
>> This issue has been assigned ticket number: #5586. Follow progress on our
>> issue tracker.
>>
>> Reported by: Jonathan J Ewbank (ewbank@ciml.univ-mrs.fr)
>> 02 May 17 04:20
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101
>> Firefox/53.0
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by sibyl229** [comment]
The reason C50F4.6 shows up when searching for his-36 is due to the text "his-36" being mentioned in the descriptions and remarks. I think it's useful for search to tell the user what we know about his-36 .
