### ISSUE TITLE
  Hi I want to know how to access the w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5587]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>I want to know how to access the wormbase homepage previous version.<br/>Because I can't fine the sequence highlighted in a defferent color both introns and exons.<br/>Even though I downloaded the sequence fasta file, it's not separated.<br/>thank you for your help.</p>

**Reported by:** MI R* (peac*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; APCPMS=^N20151209063658599759AC62B2E95531D93F_9249^) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

**Comment by tuli** [comment]
Dear Miri,

Thank you for writing to WormBase.

Within the Sequence widget of any Gene Summary page you can click on
the DNA button, which will expand the sequence and you will see
introns and exons coloured orange and yellow. I hope this answers your
query.

Best wishes,

Mary Ann
