### ISSUE TITLE
Molecular_name in primary gene data

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5590]
There are 39 WBGene objects coming from geneace that have Molecular_name data, this is auto-populated during the build and should not be in the primary database. Looks like this is contamination when genes are/were loaded back into the database.

P

**Comment by tuli** [comment]
It looks like they were all added in Sept 2016 as a one off event then. 
So, if I remove them all from Geneace now, the build won't add them again, right? 
Is that all I need to do?

**Comment by Paul-Davis** [comment]
Data seems to have been removed so should be resolved.
