### ISSUE TITLE
visitor_name (visitor_email): hey bitvh Chris: Hel...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5593]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): hey bitvh</br>Chris: Hello Charley</br>Chris: How can I help?</br>visitor_name (visitor_email): i have a question</br>Chris: OK, shoot</br>visitor_name (visitor_email): im taking elizabeth to prom , how should i ask her?</br>Chris: Haha, sorry I can't help you with that</br>visitor_name (visitor_email): come on, science is her favorite subject</br>Chris: Haha</br>visitor_name (visitor_email): so no ideas?</br>Chris: Hmmm, not off the top of my head</br>visitor_name (visitor_email): dang , thanks for the help anyways motherfucker</br>visitor_name (visitor_email): omg i just shit myself</br>visitor_name (visitor_email): brb</br>visitor_name (visitor_email): gotta go clean up

**Reported by:** char***** (char**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g-3</a>
**Browser:** Chrome 54.0.2840.59

**Comment by chris-grove** [comment]
Ah, the joys of live online chat

**Comment by khowe** [comment]
Does someone want to put Charlie and Alma in touch?

**Comment by chris-grove** [comment]
@khowe  Haha, yeah, a match made in heaven, I'm sure
