### ISSUE TITLE
My publication record in 2015 and 2016 are as foll...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5603]
*Help Desk query collected when no chat operators were online. Follow up required.*

My publication record in 2015 and 2016 are as follows.
Please correct them. Thank you very much!

1.	Oh S, Yoon S, Youn E, Kawasaki I, Shim YH. (2016). cdc-25.2, a Caenorhabditis elegans ortholog of cdc25, is required for male tail morphogenesis. Biochem. Biophys. Res. Comm. Epub ahead of print. PMID: 27923661

2.	Son M, Kawasaki I, Oh BK, Shim YH. (2016). LIN-23, an E3 ubiquitin ligase component, is required for the repression of CDC-25.2 activity during intestinal development in Caenorhabditis elegans. Molecules and Cells 39(11): 834-840. PMID: 27871172

3.	Oh S, Kawasaki I, Park JH, Shim YH. (2016). cdc-25.4, a Caenorhabditis elegans ortholog of cdc25, is required for male mating behavior. G3 (Bethesda, Md.) 6 (12): 4127-4138. PMID: 27770028

4.	Kim DK, Lim HS, Kawasaki I, Shim YH, Vaikath NN, El-Agnaf OM, Lee HJ, Lee SJ. (2016). Anti-aging treatments slow propagation of synucleinopathy by restoring lysosomal function. Autophagy 12(10): 1849-1863. PMID: 27485532, PMCID: PMC5079673

5.	Min H, Youn E, Kawasaki I, Shim YH. (2016). Caffeine-induced food-avoidance behavior is mediated by neuroendocrine signals in Caenorhabditis elegans. BMB Reports Epub ahead of print. PMID: 27697105

6.	Al-Amin M, Min H, Shim YH, Kawasaki I. (2016). Somatically expressed germ-granule components, PGL-1 and PGL-3, repress programmed cell death in C. elegans. Scientific Reports 6: 33884. PMID: 27650246, PMCID: PMC5030653

7.	Al-Amin M, Kawasaki I, Gong J, Shim YH. (2016). Caffeine induces the stress response and up-regulates heat shock proteins in Caenorhabditis elegans. Molecules and Cells 39(2): 163-168. PMID: 26743903, PMCID: PMC4757805

8.	Min H, Shim YH, Kawasaki I. (2016). Loss of PGL-1 and PGL-3, members of a family of constitutive germ-granule components, promotes germline apoptosis in C. elegans. Journal of Cell Science 129(2): 341-353. PMID: 26598553

9.	Lee YU, Son M, Kim J, Shim YH, Kawasaki I. (2016). CDC-25.2, a C. elegans ortholog of cdc25, is essential for the progression of intestinal divisions. Cell Cycle (Georgetown, Tex.) 15(5): 654-666. PMID: 27104746, PMCID: PMC4845952

10.	Min H, Kawasaki I, Gong J, Shim YH. (2015). Caffeine induces high expression of cyp-35A family genes and inhibits the early larval development in Caenorhabditis elegans. Molecules and Cells 38(3): 236-242. PMID: 25591395, PMCID: PMC4363723

**Reported by:** Ichi*********** (ikaw************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/person/WBPerson1148#013--10">http://www.wormbase.org/resources/person/WBPerson1148#013--10</a>
**Browser:** Chrome 49.0.2623.112

**Comment by vanaukenk** [comment]
Hi Ichiro,

Thanks very much for writing to WormBase.  I'll review your list of publications and make sure that what we have in WormBase for each of these is correct.

Best,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
I double-checked all of the references in Ichiro Kawasaki's list, made some updates to the publication dates, and @azurebrd and I fixed a bug that was padding an extra zero onto dates < 10.
Also created a separate ticket, #5612 to check on Publication display on staging.
