### ISSUE TITLE
Repeatedly getting error messages when trying to extract upstream flanking sequences for genes in ParaSite BioMart

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5608]
![screen shot 2017-05-12 at 1 16 34 pm](https://cloud.githubusercontent.com/assets/611382/26009130/753c3ac0-3715-11e7-9724-84a388a60cec.png)

I'm repeatedly, although not entirely consistently, getting the above error message when trying to query ParaSite BioMart for upstream flanking sequences. A user was asking about this type of query.

**Comment by brucebolt** [comment]
I was also able to reproduce the problem intermittently.  I have removed the cached sessions file and restarted the BioMart service.  This appears to have fixed the issue.
