### ISSUE TITLE
  Hi, we have a few strains to deposit....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5611]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, we have a few strains to deposit. How should I do it.</p>

**Reported by:** qi H*** (hall***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by Gschindelman** [comment]
Qi,
WormBase does not manage the strain collection. This is done by the Caenorhabditis Genetics Center (CGC) 
https://cbs.umn.edu/cgc/home

If you would like to submit strains to the CGC, you can find the information you need here:
Sending Strains to the CGC 
https://cbs.umn.edu/cgc/sending-strains
You can find the forms you need to fill out before sending the strains to the CGC.

Best,
Gary S 
WormBase Helpdesk
