### ISSUE TITLE
  Hi, I was searching the database for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5622]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I was searching the database for functions of certain peptide genes, an for nlp-11 in the summary it was stated that it is involved in fat storage, but when I looked in the paper evidence, I could not find a paper to support this. Am I looking over something?<br/>Kind regards,<br/>Bram</p>

**Reported by:** Bram****** (bram***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by epaule** [comment]
if you click on the evidence thing below the description, it shows that part of it comes from Gene Ontology, which if you look there in the detailed view points towards:
GO:0019915	lipid storage from WBRNAi00024268 (fat content increased)

if you click on the RNAi, you can see http://www.wormbase.org/resources/paper/WBPaper00005655 as reference paper.

I would assume, that the data to support it is in there.
