### ISSUE TITLE
how do I get intergenic sequence from the new brow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5624]
*Help Desk query collected when no chat operators were online. Follow up required.*

how do I get intergenic sequence from the new browser? thank you

**Reported by:** hsin******* (hsin******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00172541#0c-96fbgd8-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00172541#0c-96fbgd8-10</a>
**Browser:** Chrome 58.0.3029.110

**Comment by scottcain** [comment]
Here's what I wrote to the user (I'll have to break GBrowse more often to get JBrowse questions from users :-)

Hello,

First, let me apologies for GBrowse not being available yesterday; I was working on it to make it "more efficient" and broke it instead.  It's back now.

In the new genome browser, if you load the reference sequence track, you can click on the right side of the track lable where there is a menu triangle.  One of the options from that menu is "Save track data".  This will create a small window asking whether you want to download the region you're browsing or the whole chromosome (which is usually greyed out) as FASTA.  Clicking the save button will cause it to be downloaded to your computer.  

Please let me know if you have anymore questions,
Scott
