### ISSUE TITLE
  Hello, How do I find all the genes on...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5625]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>How do I find all the genes on chromosome X of C. elegans that have an uncoordinated phenotype?<br/>Thank you,<br/>Best regards.<br/>visitor_name</p>

**Reported by:** Méli*********** (meli*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

**Comment by chris-grove** [comment]
Hi Mélissa,

Unfortunately we don't have a (working) straight-forward way to do this at the moment. I've compiled a list of 31 genes on the C. elegans X chromosome that have an allele-based "locomotion variant"/Unc phenotype (attached). To get this list I first used the following query in WormMine:

`<query name="" model="genomic" view="Gene.primaryIdentifier" longDescription="" constraintLogic="A and B">   <constraint path="Gene.alleles.phenotypesObserved.name" code="A" op="=" value="locomotion variant"/>   <constraint path="Gene.organism.name" code="B" op="=" value="Caenorhabditis elegans"/> </query>`

to get a list of C. elegans genes (WBGene IDs) that exhibit an allele-based Unc phenotype. Then I used the following query:

`<query name="" model="genomic" view="Gene.primaryIdentifier" longDescription="" constraintLogic="B and A">   <constraint path="Gene.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>   <constraint path="Gene.chromosome.primaryIdentifier" code="A" op="=" value="X"/> </query>`

to get all C. elegans genes on chromosome X. Then, using this website:

http://jura.wi.mit.edu/bioc/tools/compare.php

I compared the two lists and took the overlapping set.

I hope that helps.

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Hi again Mélissa,


 Sorry, that second query should have been:


`<query name="" model="genomic" view="Gene.symbol" longDescription="" constraintLogic="B and A">   <constraint path="Gene.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>   <constraint path="Gene.chromosome.primaryIdentifier" code="A" op="=" value="X"/> </query>`


That will give you a comparable list.


Best,


Chris

**Comment by chris-grove** [comment]
User is happy
