### ISSUE TITLE
im-259 WormMine missing "Trail: Query" option to return to QueryBuilder from results

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5626]
On the live WormMine instance (and on all previous versions, as far as I'm aware) there is a "Trail: Query" link at the top of a WormMine results table that allows a user to link back to the QueryBuilder for the query that was just executed. On the im-259 instance, this link seems to have disappeared meaning that using the browser's "Back" button is the only way to return to the query. I think the link should stay there.

**Comment by nuin** [comment]
Hi Chris, I have checked all changes from one version to another and I didn't see anything related to this link. I am investigating why it disappeared.

**Comment by nuin** [comment]
It's a bug with InterMine, https://github.com/intermine/intermine/pull/1574, I will fix it today

**Comment by nuin** [comment]
It's back, Chris.

**Comment by chris-grove** [comment]
@nuin 
Perfect! Thanks!
