### ISSUE TITLE
im-259 WormMine: Gene names/IDs misformatted

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5627]
@nuin 
If I do a generic query for genes, like:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>`

 in im-259 WormMine, I get the following results:

![screen shot 2017-05-22 at 4 25 48 pm](https://cloud.githubusercontent.com/assets/611382/26326971/8bcf2c86-3f0b-11e7-87e9-aecfd2e29034.png)

In this case, the gene "WBGene00000001" for example should have the following:

WormBase Gene ID: WBGene00000001
Gene Name: aap-1
Sequence Name: Y110A7A.10

I know this isn't a complete build, but I want to make sure that when the complete build is generated that all genes have the correct IDs and all entities are merged properly.

**Comment by nuin** [comment]
In the full build this should be correct, one example is the gene `abc-1` on the image above. But I will double check anyway.

**Comment by chris-grove** [comment]
OK looks good in full build

**Comment by nuin** [comment]
Thanks Chris. The reason the small build shows a lot of "wrong" entries is because we still use the full GFF in it, and there's no merging when the Gene.XML is loaded. But it is good to keep an eye on this as multiple loads can lead to data problems.
