### ISSUE TITLE
Fix "Gene --> Expression Pattern" template query to point to correct anatomy terms

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5628]
@nuin 
Now that the correct anatomy data has been imported into im-259 WormMine under the Expression Pattern class, the template query "Gene --> Expression Pattern" needs to be updated to point to the correct anatomy terms. The current query is this:

`<query name="" model="genomic" view="Gene.symbol Gene.secondaryIdentifier Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.lifeStages.anatomyTerms.name Gene.expressionPatterns.lifeStages.anatomyTerms.synonym" longDescription="Returns a list of cells/tissues where a specific gene is expressed." sortOrder="Gene.expressionPatterns.primaryIdentifier asc">
  <constraint path="Gene" op="LOOKUP" value="lin-3" extraValue=""/>
</query>`

and it needs to be updated to this:

`<query name="" model="genomic" view="Gene.symbol Gene.secondaryIdentifier Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.anatomyTerms.name Gene.expressionPatterns.anatomyTerms.synonym" longDescription="Returns a list of cells/tissues where a specific gene is expressed." sortOrder="Gene.expressionPatterns.primaryIdentifier asc">
  <constraint path="Gene" op="LOOKUP" value="lin-3" extraValue=""/>
</query>`

**Comment by nuin** [comment]
I will work on it, thanks Chris.

**Comment by nuin** [comment]
Hi Chris, I have a new template for the query, but I cannot remove the old one (I guess). Check it and close the ticket if necessary. Thanks.

**Comment by chris-grove** [comment]
@nuin 
Where is the new template and what is it called? I don't see it on the im-259 instance. Also, I really want the old template removed entirely before I close the ticket, as the point is that I don't want any users to use the old (incorrect) template query. As I'm writing this I also realize that another expression template query needs to be fixed/replaced: The "Cell/Tissue --> Expression" template query is currently like this:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.expressionPatterns.lifeStages.anatomyTerms.primaryIdentifier Gene.expressionPatterns.lifeStages.anatomyTerms.name Gene.expressionPatterns.lifeStages.anatomyTerms.synonym" longDescription="Show all genes that are expressed in anchor cell, as an example - XW" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.lifeStages.anatomyTerms.name" op="=" value="anchor cell"/>
</query>`

and it needs to be changed to:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.expressionPatterns.anatomyTerms.name Gene.expressionPatterns.anatomyTerms.primaryIdentifier Gene.expressionPatterns.anatomyTerms.synonym" longDescription="" sortOrder="Gene.symbol asc">
  <constraint path="Gene.expressionPatterns.anatomyTerms.name" op="=" value="anchor cell"/>
</query>`

I can create a separate ticket for that if needed.

**Comment by nuin** [comment]
As soon as I updated the webapp with the fix for the trail the template disappear, even from my user page. I will investigate and add the new Cell/Tissue template. Sorry about that.

**Comment by chris-grove** [comment]
@nuin 
Ah, OK, no worries

**Comment by nuin** [comment]
Template is back on here http://im-259.wormbase.org/tools/wormmine/template.do?name=gene_expression_pattern&scope=all, let me know. I am working one the other one.

**Comment by chris-grove** [comment]
@nuin 
OK, the query for which you provided the link looks good, but the critical thing is that the template query "Gene --> Expression pattern" available on the home page or under the "Templates" tab needs updating to this new query.

**Comment by nuin** [comment]
Yes, I think it belongs to @tharris and I didn't find a way for my user to remove it. Whenever I am confident it will stay put between webapp builds I will coordinate with him to remove it.

**Comment by chris-grove** [comment]
@nuin 
OK

**Comment by tharris** [comment]
I've removed "Gene --> Expression pattern" template from the home page and the Expression category (but not deleted it)

**Comment by nuin** [comment]
Thanks @tharris

**Comment by chris-grove** [comment]
@tharris 
Would you mind doing the same for the "Cell/Tissue --> Expression" template?
Thanks!

**Comment by tharris** [comment]
Done.

**Comment by nuin** [comment]
@tharris and @chris-grove I am working on the replacement for "Cell/Tissue --> Expression"

**Comment by nuin** [comment]
@chris-grove Created, let me know. I have some small changes to interface and if they don't stay after rebuild I will re-add them

**Comment by chris-grove** [comment]
@tharris 
Thanks!

@nuin 
OK, the new templates look good. Thanks!

**Comment by chris-grove** [comment]
@nuin 
I think I spoke too soon...
The new "Cell/Tissue --> Expression" template needs to do the lookup on the anatomy term, not the gene (e.g. lin-3 as it is now). So the template on im-259 is now:

`<query name="" model="genomic" view="Gene.symbol Gene.secondaryIdentifier Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.anatomyTerms.name Gene.expressionPatterns.anatomyTerms.synonym" longDescription="Returns a list of cells/tissues where a specific gene is expressed." sortOrder="Gene.expressionPatterns.primaryIdentifier asc">
  <constraint path="Gene" op="LOOKUP" value="lin-3" extraValue=""/>
</query>`

but it needs to be:

`<query name="" model="genomic" view="Gene.symbol Gene.secondaryIdentifier Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.anatomyTerms.name Gene.expressionPatterns.anatomyTerms.synonym" longDescription="Returns a list of cells/tissues where a specific gene is expressed." sortOrder="Gene.expressionPatterns.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.anatomyTerms.name" op="=" value="anchor cell"/>
</query>`

**Comment by tharris** [comment]
Chris, maybe you should just create the template until it's working for you?

**Comment by nuin** [comment]
Will change

**Comment by chris-grove** [comment]
@tharris @nuin 
OK, I've just created the public template "Cell/Tissue --> Genes Expressed"

**Comment by chris-grove** [comment]
@tharris @nuin 
OK, I've just created the public template "Cell/Tissue --> Genes Expressed"

**Comment by nuin** [comment]
I removed the public tag from mine. I will keep an eye if it is kept between builds. Thanks @chris-grove

**Comment by tharris** [comment]
Great! That's the whole beauty of templates!

**Comment by chris-grove** [comment]
OK, great! All looks good now. At some point maybe we can change the title of "Gene --> Expression pattern 2" to simply "Gene --> Expression Pattern" or something similar (without the "2")

**Comment by chris-grove** [comment]
@tharris 
How do I add the template query to the "Expression" category (for display on the home page "EXPRESSION" tab and for filtering on the "Templates" tab)?

**Comment by nuin** [comment]
@chris-grove I think this is an extra tag that needs to be added to the template. I will check the documentation and connect with InterMine people if needed. But @tharris might know.

**Comment by tharris** [comment]
You may need to be a superuser to do so. Check My Mine > then select the Templates tab.  Find the template. There should be an option to add tags. Tags are what control what is displayed on the home page and in which categories.

**Comment by nuin** [comment]
@tharris Chris is superuser with his wormbase email address account

**Comment by chris-grove** [comment]
Yeah, I'm pretty sure I'm already a superuser and that's why I could make my new template public. I remembered the 'im:public' and 'im:frontpage' tags, but I don't remember what tag I need to add to add the template to a category and there weren't any pre-existing tags in the drop down menu for adding tags

**Comment by nuin** [comment]
You can import tags, mine are more or less like this

```<tags>

  <tag name="im:favourite" objectIdentifier="show_expression_of_a_given_gene" type="template">
  </tag>
  <tag name="im:public" objectIdentifier="gene_expression_pattern" type="template">
  </tag>
</tags>```

and according to the [documentatrion](http://intermine.readthedocs.io/en/latest/webapp/admin/), for categorization you need to use

`im:aspect:CategoryName`

**Comment by chris-grove** [comment]
@nuin 
OK, thanks. I've applied the tag 'im:aspect:Expression', but it doesn't appear to have changed anything

**Comment by nuin** [comment]
I will see what I can do.

**Comment by nuin** [comment]
According to the documentation your tag is correct and it has the correct name 

```
begin.tabs.3.id = Expression
begin.tabs.3.description =
```

This is the tab where it should be. I will redeploy the webapp and see what happens. Be aware that the template might disappear. I will probably, starting on the next build, separate the profile table from dev and production.

**Comment by nuin** [comment]
@chris-grove I don't see your template when I am logged out of my account. I made my template non-public too. I am redeploying the webapp now.

**Comment by nuin** [comment]
I don't see it there. I will try to dump and load a different copy of the profile DB. I will discuss with @tharris the best procedure, as it is not hosted on the same server as WormMine.

**Comment by tharris** [comment]
You also need the im:public and I think im:front page (or something like that)

**Comment by chris-grove** [comment]
@nuin 
My template query is still there: "Cell/Tissue --> Genes Expressed"

It's showing in the general templates list, but it still isn't showing up in the "Expression" category even though it has the tag "im:aspect:Expression"

**Comment by nuin** [comment]
I will double check in a bit, thanks Chris

**Comment by nuin** [comment]
I created a template based on yours add the correct tags (including the ones suggested by Todd) and got nothing. It's public but it does not show up on the Expression tab. I will redeploy the webapp and check. If it doesn't work I will try InterMine devs.

**Comment by nuin** [comment]
Hi @chris-grove 

I have replicated the user profile DB in order to check if sharing the DB between prod and dev is the problem. I tried to make a test template visible but it didn't work. I am investigating

**Comment by chris-grove** [comment]
@nuin 
OK, thanks

**Comment by nuin** [comment]
@chris-grove I am closing this, it seems corrected in the past 6-7 releases.
