### ISSUE TITLE
Question about best BLASTP matches on WormBase vs. ParaSite

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5630]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi visitor_name, how can I help?</br>visitor_name (visitor_email): Hi,

I'm wondering how the "Best BLASTP matches" in the homology section was determined. I was trying to do BLASTP and find sequence identity of a gene in different nematode species, but the results I got from WormBase ParaSite were very different from the ones shown on the WormBase gene page.

Thank you</br>Chris: Yeah, I think there are some discrepancies in the algorithms and cutoffs used to make calls on the two sites, but I can't tell you for sure myself. I'll write an email to Michael Paulini of Wormbase who can tell you more specifics about the algorithms used and why there may be a discrepancy</br>Chris: and I'll CC you</br>visitor_name (visitor_email): Great! Thank you very much Chris!</br>Chris: Sure thing! Is there anything else I can help you with?</br>visitor_name (visitor_email): No. That's it for now.</br>Chris: OK, have a nice weekend!</br>visitor_name (visitor_email): you too :)</br>Chris: Thanks!

**Reported by:** Pei (pshi*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#014-23-6">http://www.wormbase.org/#014-23-6</a>
**Browser:** Chrome 58.0.3029.110

**Comment by epaule** [comment]
until the release of WS260 the "best blastp matches" in the homology table are from WU-BLASTP and are scores from a single target database (like C.briggsae/B.malayi/etc.). These target databases also include historic proteins and are therefore slightly larger than the ParaSite ones, which are only live proteins.
From WS260 on we are using NCBI-BLAST+ similar to the ParaSite blast service, so the scores should be a tad closer. 

So far my impression is that especially for close homologies the difference between the two algorithms is not too large, so it would be great if you could share your example search and we can have a look at it.

**Comment by tharris** [comment]
User contacted; closing.
