### ISSUE TITLE
  what does this  mean that gene is dea...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5638]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;what does this  mean that gene is dead</p>

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by tuli** [comment]
Good morning,

Thank you for writing to WormBase.

A dead gene is not a valid gene and should be disregarded.

It may have been created in error or the gene has been merged into
another one, or new findings show that the object should not have been
curated as a gene.

The reason for a gene being killed should appear on the record for
that gene in WormBase.

Best wishes,

Mary Ann

On 27 May 2017 at 21:30,  <no-reply@wormbase.org> wrote:
> Question:
>
>   what does this mean that gene is dead
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5638. Follow progress on our
> issue tracker.
>
> Reported by: supi (supinderkr@gmail.com)
> 27 May 17 20:29
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
> Gecko) Chrome/58.0.3029.110 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
