### ISSUE TITLE
  Hi, I want to use the strain RW10312-...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5647]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I want to use the strain RW10312- stIs10312 [lim-7::TY1::EGFP::3xFLAG + unc-119(+)]. I would like to know more information about this strain such as the site of the tag (N or C-term or in the middle?). The wormbase page for this says "Made by: DKV/RJT/PW" Who is this and how can I contact them?  </p>

**Reported by:** Rema****** (rema******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Hello Rema,

This strain has the RW laboratory code for Robert (Bob) Waterston, so you can contact the Waterston lab for more information about the strain:

http://www.wormbase.org/resources/laboratory/RW#03--10

The strain can be ordered from the Caenorhabditis Genetics Center (CGC):

https://cgc.umn.edu/strain/RW10312

I hope that helps.

Chris Grove
WormBase
