### ISSUE TITLE
RNAi labels need fix on WormMine

### ISSUE THREAD

**Issue by nuin** [WormBase/website#5648]
RNAi labels are showing as RN Ai. This is known as InterMine's regex would some time split camelCase labels.

**Comment by nuin** [comment]
Changed `/bio/webapp/resources/webapp/WEB-INF/bioClassNames.properties`. Fixes RNAi main class label, but doesn't fix other locations.

**Comment by nuin** [comment]
Changed `/bio/webapp/resources/webapp/WEB-INF/bioFieldNames.properties` fixed other locations, still need some checking.

**Comment by nuin** [comment]
@chris-grove I checked most places where RNAi labels are shown, but I don't know if all of the are fixed, would mind doing a quick checking? If you don't find anything out of the ordinary, please close the ticket.

**Comment by chris-grove** [comment]
@nuin 
In the gene model browser it is still listed as "RN Ai"

I'll keep looking and let you know

**Comment by chris-grove** [comment]
Also in the Transcript model browser

**Comment by chris-grove** [comment]
![screen shot 2017-05-30 at 5 43 52 pm](https://cloud.githubusercontent.com/assets/611382/26606364/a2684324-455f-11e7-877b-032bc186789f.png)


![screen shot 2017-05-30 at 5 44 07 pm](https://cloud.githubusercontent.com/assets/611382/26606365/a5ff0d38-455f-11e7-8718-6e0170502344.png)

I think those two examples are all that are left with the gap in the name

**Comment by nuin** [comment]
Thanks, Chris, appreciated. I will go deeper in the configuration then. I though the two files I changed were enough to fix the error, but who said InterMine doesn't have enough surprises.

**Comment by nuin** [comment]
I am using the directions here http://intermine.readthedocs.io/en/latest/data-model/data-labels/, and my changes should have been global.

**Comment by nuin** [comment]
Fixed, the issue was that both in Gene and Transcript the RNAi was a different field. I checked and it seems fine, you can close the ticket if you are happy with it. Thanks for the help, again.

**Comment by chris-grove** [comment]
@nuin 
Yep! Looks good, thanks!
