### ISSUE TITLE
Chris: Hello William, how can I help? visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5649]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello William, how can I help?</br>visitor_name (visitor_email): Hi, I am wondering how I can download the 3'UTRs for a set of c. elegans genes?</br>visitor_name (visitor_email): the website listed on the FAQ does not work</br>Chris: The best tool for that would be WormBase ParaSite BioMart</br>Chris: You can find a link to it from the Tools menu at the top of any WormBase page</br>Chris: I'll generate the query and send you a URL</br>Chris: http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&amp;ATTRIBUTES=wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.3utr&amp;FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."hlh-1,myo-3"&amp;VISIBLEPANEL=resultspanel</br>Chris: Just go back to "Query Filters" and replace the genes that I put in with your list of genes</br>Chris: and then click "Results" at the top to get your list of sequences</br>visitor_name (visitor_email): Ok wow! Thanks you so much!</br>Chris: You're welcome!</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): I think that's it thank you</br>Chris: OK, no problem. Take care

**Reported by:** Will************* (wil.********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#1a893e5c604bd72--10">http://www.wormbase.org/about/Frequently_asked_questions#1a893e5c604bd72--10</a>
**Browser:** Chrome 58.0.3029.110

**Comment by chris-grove** [comment]
I've updated the FAQ section instructions on how to acquire 3'UTR sequences
