### ISSUE TITLE
  How do I find all genes retrieved fro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5650]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find all genes retrieved from the neuron cells(such as I5 or M4)?</p><p>What were you doing? <br />&nbsp;&nbsp;c elegan regulate network analysis</p>

**Reported by:** kevi* (hang***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by chris-grove** [comment]
Hello Kevin,

You can find genes reported to be expressed in the I5 neuron or M4 neuron on their respective anatomy pages:

http://www.wormbase.org/species/all/anatomy_term/WBbt:0004740#03--10

http://www.wormbase.org/species/all/anatomy_term/WBbt:0004467#03--10

If you look in the "Ontology Browser" widget, you will see the number of genes reported to be expressed in each cell (996 in I5, 27 in M4). If you click on the numbers you will be directed to a page listing out the genes. You can copy and paste that list for subsequent analysis.

Best,

Chris Grove
WormBase
