### ISSUE TITLE
Hi, just wondering how do I retrieve all genes fro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5651]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, just wondering how do I retrieve all genes fro the specific neuron(like I5)?

best 
Kevin

**Reported by:** kevi* (hang***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/anatomy_term/WBbt:0003953">http://www.wormbase.org/species/all/anatomy_term/WBbt:0003953</a>
**Browser:** Firefox 53.0

**Comment by chris-grove** [comment]
Duplicate of #5650
