### ISSUE TITLE
Hi~I am a researching master student. Because I am...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5652]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi~I am a researching master student. Because I am studying chil1 gene but I don't quite understand what the color bars in the genomic browser mean. Can you explain a bit on the meaning of those color bars and solid lines in between those bars?    Thanks a lot

**Reported by:** Patr*** (p.ti*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#59cb6473e081d2a--10">http://www.wormbase.org/about/Frequently_asked_questions#59cb6473e081d2a--10</a>
**Browser:** Chrome 58.0.3029.110

**Comment by chris-grove** [comment]
![chil-1_gbrowse_image](https://cloud.githubusercontent.com/assets/611382/26685820/298601a2-46b9-11e7-9d2a-a1952435e499.png)

Hello Patrice,


 The boxes (colored grey and blue) represent the exons of the genes, and the solid lines between the bars represent introns. The grey colored regions of the boxes represent untranslated regions (UTRs) and the blue colored regions of the boxes represent coding sequence that codes for protein.


I hope that helps.


Chris Grove

WormBase
