### ISSUE TITLE
  I'd like to search for all genes that...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5653]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'd like to search for all genes that when treated for RNAi yield Ric phenotype. I'm aware of a large-scale screen by Kaplan lab, but I don't want to miss smaller reports. Is the published data from multiple studies available in WORMBASE in the phenotype category? If so, how to do search for the list of genes and the studies they come from? Thanks!</p>

**Reported by:** jon ****** (pier*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

**Comment by chris-grove** [comment]
Hello Jon,

 You can quickly find the list of genes that exhibit a Ric phenotype by RNAi by going to the "aldicarb resistant" phenotype page:

http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000017#03--10

And looking in the "Ontology Browser" widget you can click on the "235 gene products" link next to the "aldicarb resistant" phenotype name. That will take you to a page that lists all genes that show the Ric phenotype by RNAi.

To get at the publications is a little trickier, so I've queried the ACEDB database for you and generated the attached Excel file. With that you can see the individual RNAi experiment IDs, the genes knocked down, the WormBase paper ID, and the brief citation for the paper. As you can see, the vast majority of these annotations come from the Kaplan paper, but there are a few others.

I hope that helps.

Best,

Chris Grove
WormBase
