### ISSUE TITLE
  automatically download all genes of a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5658]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;automatically download all genes of all c. elegans' neurons(I5, ALMR, ETC..) using python language?</p><p>What were you doing? <br />&nbsp;&nbsp;I used to retrieve all genes in wormmine web with python code.</p>

**Reported by:** kevi* (hang***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by draciti** [comment]
Todd/Paulo, is this something you can address? thx

**Comment by nuin** [comment]
@draciti The Python API is still working fine and available for any query. Just run on my computer fine. The user has to have the InterMine Python module installed in their machine.

One example is a template

```python
from intermine.webservice import Service
service = Service("http://intermine.wormbase.org/tools/wormmine/service")
query = service.new_query("Gene")
query.add_view(
    "symbol", "transcripts.symbol", "transcripts.CDSs.symbol",
    "transcripts.CDSs.protein.symbol",
    "transcripts.CDSs.protein.primaryAccession"
)
query.add_constraint("Gene", "LOOKUP", "unc-27", code = "A")

for row in query.rows():
    print row["symbol"], row["transcripts.symbol"], row["transcripts.CDSs.symbol"], \
        row["transcripts.CDSs.protein.symbol"], row["transcripts.CDSs.protein.primaryAccession"]
```

**Comment by draciti** [comment]
thanks Paulo- could you get back to the user directly? I am not sure how to automatically download ALL genes for ALL neurons using python. thx

**Comment by nuin** [comment]
Hi 

I can, I have to check the query, maybe @chris-grove can help me with it. How do I contact the user?

Thanks

**Comment by draciti** [comment]
thanks Paulo,

here is the user's contact

kevin (hang.xu05@gmail.com).



________________________________

**Comment by chris-grove** [comment]
@nuin 
I could help to build a query and send you the XML for it, but the data is not there on the live site and currently when I try to use im-259 site, I cannot access the QueryBuilder for im-259. As soon as I click on the "QueryBuilder" tab, I get directed to the QueryBuilder for WS258 (intermine.wormbase.org ...) instead of WS259 (im-259.wormbase.org ...)

**Comment by chris-grove** [comment]
OK, I managed to get this query constructed:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.anatomyTerms.name Gene.expressionPatterns.anatomyTerms.primaryIdentifier" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.anatomyTerms.name" op="=" value="I5 neuron"/>
</query>`

**Comment by chris-grove** [comment]
but that needs to be run on the im-259 instance, or it won't work

**Comment by nuin** [comment]
OK, I already set the webapp of im-259 for release, but I don't have access to the proxy to redirect access. I will check with @tharris when the release is coming, and depending revert the configuration.

Thanks @chris-grove

**Comment by tharris** [comment]
The WS259 build of intermine is now available in production.

**Comment by chris-grove** [comment]
Wrote to user:
"Hello Kevin,


 You should now be able to download genes expressed in a specified cell using the attached WormMine Python query. The attached query is an example using the "I5 neuron" anatomy term, which you can replace with your anatomy term/neuron of interest.


Let us know if you have any more questions.


Best,


Chris Grove

WormBase"

**Comment by chris-grove** [comment]
@tharris
@nuin 
Thanks Todd and Paulo!

**Comment by nuin** [comment]
Thanks Chris.
