### ISSUE TITLE
I would like to know if there is any sequence simi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5659]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to know if there is any sequence similarity of a particular mammalian gene with C. elegans genome

**Reported by:** Vidi************ (tvid****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat">http://www.wormbase.org/tools/blast_blat</a>
**Browser:** Chrome 58.0.3029.110

**Comment by chris-grove** [comment]
Hello Vidisha,

To find sequence similarity to a mammalian protein-coding gene in C. elegans, use the mammalian gene's protein sequence and perform BLASTP against the C. elegans proteome using the WormBase BLAST tool. If it is a non-coding gene, you can just perform a nucleotide BLAST using the mammalian gene's DNA sequence.


Let us know if you have questions about the process.


Best,


Chris Grove

WormBase
