### ISSUE TITLE
  What is the primer of lrk1 gene in c....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5662]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;What is the primer of lrk1 gene in c.elegans?</p>

**Reported by:** neha (neha********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by chris-grove** [comment]
Hello Neha,


Could you provide more details of what you are looking for? You may want to look at the sequence of the irk-1 gene:


http://www.wormbase.org/species/c_elegans/gene/WBGene00002149#0g--10


There are many primers that can be derived from the irk-1 gene sequence. You may want to use a primer/oligonucleotide calculator, like this one:


http://biotools.nubic.northwestern.edu/OligoCalc.html


Best,


Chris Grove

WormBase
