### ISSUE TITLE
  Searches are not loading, gateway tim...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5667]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Searches are not loading, gateway timeouts.</p><p>What were you doing? <br />&nbsp;&nbsp;Searching for strains.</p>

**Reported by:** NIDA***** (nida****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by tharris** [comment]
WS259 had some catastrophic problems; reverted to WS258. User contacted.
