### ISSUE TITLE
Certainty column not displaying values

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5673]
Hi web team,
the certainty column on the Association widget in the anatomy page:

http://www.wormbase.org/species/all/anatomy_term/WBbt:0004740#013--10

does not display the 'certain/uncertain/etc' qualifier.

could you please take a look?
thx

**Comment by a8wright** [comment]
@draciti This one is similar to the certainty in the markers table that we are creating. I have added code to make it so that it shows the string from the "qualifier" entity "certainty" field. I have not found an instance where it is filled in though. I will also make it have the same logic as the Marker widget table when we have that fully spec'ed out.

**Comment by draciti** [comment]
This object has 3 qualifier fields 

Expr_pattern : "Expr10052"
Anatomy_term	"WBbt:0003681" Certain
Anatomy_term	"WBbt:0004088" Certain
Anatomy_term	"WBbt:0004090" Certain
Anatomy_term	"WBbt:0004574" Certain
Anatomy_term	"WBbt:0004577" Certain
Anatomy_term	"WBbt:0005772" Certain
Anatomy_term	"WBbt:0006748" Uncertain "May be either uterine or vulval cells."
Anatomy_term	"WBbt:0006751" Partial "Expressed in at least eight pairs of neurons in the head."
..

hope it helps

**Comment by a8wright** [comment]
@draciti Same as the other ticket. this is now fixed on this endpoint on staging. Feel free to close if you agree. Also feel free to ask for more changes if you see anything off.

**Comment by draciti** [comment]
it seems the certainty column displays always 'partial', at least here:
staging.wormbase.org/species/all/anatomy_term/WBbt:0004740#013--10

Take Expr1072, .ace below, should have certain as qualifier.
thanks!

Expr_pattern : "Expr1072"
Anatomy_term	"WBbt:0004473" Certain
Anatomy_term	"WBbt:0004487" Certain
Anatomy_term	"WBbt:0004739" Certain
Anatomy_term	"WBbt:0004740" Certain
Anatomy_term	"WBbt:0004741" Certain
Anatomy_term	"WBbt:0004742" Certain
Anatomy_term	"WBbt:0004743" Certain
Anatomy_term	"WBbt:0004744" Certain
Anatomy_term	"WBbt:0004745" Certain
Anatomy_term	"WBbt:0004746" Certain
Anatomy_term	"WBbt:0005135" Certain
Anatomy_term	"WBbt:0005775" Certain
Anatomy_term	"WBbt:0005776" Certain
Anatomy_term	"WBbt:0005812" Certain
Anatomy_term	"WBbt:0005829" Certain
Anatomy_term	"WBbt:0006977" Certain

**Comment by a8wright** [comment]
The displaying of "partial" always was a bug. I was using a function that had an unexpected feature of using the last one if there was no match - partial is the last one in the list. I have fixed it on staging now. Unfortunately It is not showing certainty for Expr1072. @mgrbyte do you see anything in the conversion process that would cause this issue or see the information in Datomic?

**Comment by draciti** [comment]
thanks Adam, right now the only certainty tag I see is 'Uncertain' (Expr12337)
http://staging.wormbase.org/species/all/anatomy_term/WBbt:0004740#0132--10
I'll wait for Matt's reply to test some more.thx

**Comment by mgrbyte** [comment]
@Paul-Davis There's an issue with the change we made here; wormbase-pipelines commit ref: 689b86ae7c6c8ed1917e8000bd313be623e9b3c2
@a8wright @draciti 
This is another case of the general issue that "bare" leaf tags (those without a value set in data) will be treated as missing my the conversion process.

e.g ACe line that wouldn't get converted
`Antyhing That Looks Like This`
Where  `This` in the line above is meant to be treated in a boolean context.

**Comment by mgrbyte** [comment]
What I wrote above was wrong, so have redacted.
To correct mylsef; this data appears in ACeDB, but not on the site.
ATM there is no transactor runing for WS263, so I can't connect and run datomic queries against it.
I am downloading it now to run the test later on, and will be then be able to tell if this is data or query/d2c issue.

**Comment by a8wright** [comment]
This has been fixed
