### ISSUE TITLE
sbt-1 (http://www.wormbase.org/species/c_elegans/g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5676]
*Help Desk query collected when no chat operators were online. Follow up required.*

sbt-1 (http://www.wormbase.org/species/c_elegans/gene/WBGene00011392) isn't giving an interpolated genetic map position. Not a big problem - I could get it from the next gene over - but irritating if more widespread.

Thanks!

**Reported by:** Hill*********** (hill***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00011392#0a-9e1c6db4j5fg7-10-a">http://www.wormbase.org/species/c_elegans/gene/WBGene00011392#0a-9e1c6db4j5fg7-10-a</a>
**Browser:** Chrome 58.0.3029.110

**Comment by tuli** [comment]
Seems to be a general problem with Mapping_data not being displayed.

**Comment by sibyl229** [comment]
Hi @tuli interpolated-map-position has never been displayed before. Could you clarify what you'd like to be shown? 

By default I could show something like "Interpolated map position: V	25.3009". There are additional information that can be retrieved from the Map model, if you like. 

Could you also provide a one sentence description of what the field is about? 

Thanks!

**Comment by tharris** [comment]
The interpolated map position was displayed directly underneath the physical position (if known). It also displayed the confidence.

**Comment by tharris** [comment]
(See "Genetic position" in the locations widget)

**Comment by mgrbyte** [comment]
@sibyl229 wondering if this can be closed now?

**Comment by chris-grove** [comment]
@mgrbyte  The initial problem reported is fixed. I'll close.
