### ISSUE TITLE
  Hi, first of all, congratulations, th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5680]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, first of all, congratulations, this site is fantastic. I was looking for the original work of E. Maupas on the C. Elegans (http://www.wormbase.org/resources/paper/WBPaper00000239), but could not find the original text –nor a translation.<br/>Just in case you have a copy, it'd be nice to have it linked on the page:) <br/>Regards,<br/>visitor_name</p><p>What were you doing? <br />&nbsp;&nbsp;I'm a fan of the c. elegans, and decided to read the original paper by Maupas...</p>

**Reported by:** Mari******* (mari*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by HillelSchwartz** [comment]
I was intrigued and looked; it's available here: http://www.biodiversitylibrary.org/item/25956#page/537/mode/1up

It's not translated, so I hope your French is better than mine (which is in any case nonexistent).

**Comment by chris-grove** [comment]
Hello Mario,

Our colleague Hillel Schwartz found the paper online, although completely in French. Here's his note:

"I was intrigued and looked; it's available here: http://www.biodiversitylibrary.org/item/25956#page/537/mode/1up
It's not translated, so I hope your French is better than mine (which is in any case nonexistent)."

Best,

Chris Grove
WormBase

**Comment by kyook** [comment]
Hi, Marie Anne Felix wrote a translation: http://legacy.wormbase.org/papers/1900-maupas/Maupas_1900.pdf
