### ISSUE TITLE
WS260 patch for Expression_cluster

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5681]
@tharris, could you do a fresh sync of the FTP files from EBI - there are new/updated files for WS260:
acedb/PATCHES/WS260Patch.ace 
ONTOLOGY/anatomy_association.WS260.wb

@raymond91125, Your patched anatomy_association.WS260.wb file is available from 
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS260/ONTOLOGY/anatomy_association.WS260.wb

**Comment by raymond91125** [comment]
Thanks. Patched WS260 solr and Tissue Enrichment Analysis using your file.

**Comment by tharris** [comment]
Patched on staging.wormbase.org and the FTP site.
