### ISSUE TITLE
Configure display of genetic interactions to accommodate new data model

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5684]
The ?Interaction model was recently updated to reflect a change in the way we intend to categorize genetic interaction types. The previous model had a single flat list of genetic interaction types:

Genetic_interaction
Neutral_genetic
Synthetic
Enhancement
Unilateral_enhancement
Mutual_enhancement
Positive_genetic
Suppression
Complete_suppression
Partial_suppression
Unilateral_suppression
Complete_unilateral_suppression
Partial_unilateral_suppression
Mutual_suppression
Complete_mutual_suppression
Partial_mutual_suppression
Suppression_enhancement
Asynthetic
Negative_genetic
Oversuppression
Unilateral_oversuppression
Mutual_oversuppression
Oversuppression_enhancement
Phenotype_bias
No_interaction
Epistasis
Positive_epistasis
Maximal_epistasis
Minimal_epistasis
Neutral_epistasis
Qualitative_epistasis
Opposing_epistasis
Quantitative_epistasis

These types will now be superseded by three sets of terms that can be used in conjunction with one another, up to one term per set (or "module") per interaction:

GI_module_one
		A_phenotypic
		Mono_phenotypic
		Cis_phenotypic
		Iso_phenotypic
		Trans_phenotypic
GI_module_two
		Enhancing
		Suppressing
		All_suppressing
		Super_suppressing
		Sub_suppressing
		Inter_suppressing
		Semi_suppressing
		Co_suppressing
		Masking
GI_module_three
		Neutral
		Non_neutral
		Positive
		Negative
		Converging
		Diverging

Also, each genetic interaction (regardless of subtype) will get the tag "Genetic_interaction", plus zero to three additional classifiers, one from each set/module. Ideally, these types should appear in the Cytoscape network view legend under the "Genetic Interaction" section, nested as shown above. The same "AND" logic that's currently used in the Cytoscape network and legend for types and subtypes display can be used with these new subtypes. What I mean is, all relevant checkboxes need to be selected for an interaction to display in the network graph.

Then, in the interactions table, the "Interaction Type" can be listed as the concatenation of:

<module 1 term, if present> + <module 2 term, if present> + <module 3 term, if present> + "genetic interaction"

and preferably in user-friendly format, i.e. "All-suppressing" instead of "All_suppressing" (replace underscores with hyphens).

For now, the interaction data will be dumped from our curation database and uploaded to CITace with the old classifiers in place as well as the new ones, so integration of the new types does not need to happen immediately, except that the new tags would possibly need to be ignored by the web code.

**Comment by tharris** [comment]
And this arrives when? WS260?

**Comment by chris-grove** [comment]
@tharris  WS261 at the earliest. The data model has just been approved for WS261, but we are still going to be dumping out the old tags alongside the new ones so that there's some leeway in getting the new display working.
