### ISSUE TITLE
  Hi there, I am working with sma-6(wk7...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5686]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there,<br/>I am working with sma-6(wk7) strain and there is no allele information in wormbase. I realized there is a paper that states the variation is a stop codon at Y72 position. I thought it would be good to put this info to the wk7 variation page so people can access it easily. <br/>Reference paper: BMP signaling requires retromer-dependent recycling of the type I receptor<br/>Gleason et al, 2014, PNAS<br/>DOI: 10.1073/pnas.1319947111</p>

**Reported by:** Oguz*********** (oguz**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.2.5 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.5

**Comment by tuli** [comment]
Dear Oguzhan,

Thank you for writing to WormBase.

I am writing to confirm that I have updated allele wk7 with the
molecular details described in the Gleason et al paper. We appreciate
you bringing this to our attention.

The update will be available in release WS261 of WormBase.

Best wishes,

Mary Ann

On 14 June 2017 at 04:32,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   Hi there,
> I am working with sma-6(wk7) strain and there is no allele information in
> wormbase. I realized there is a paper that states the variation is a stop
> codon at Y72 position. I thought it would be good to put this info to the
> wk7 variation page so people can access it easily.
> Reference paper: BMP signaling requires retromer-dependent recycling of the
> type I receptor
> Gleason et al, 2014, PNAS
> DOI: 10.1073/pnas.1319947111
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5686. Follow progress on our
> issue tracker.
>
> Reported by: Oguzhan Baltaci (oguzhan.baltaci@monash.edu)
> 14 Jun 17 03:30
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.2.5 (KHTML,
> like Gecko) Version/10.1.1 Safari/603.2.5
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
