### ISSUE TITLE
  I have problems to get the correct se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5688]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have problems to get the correct sequence for some fosmids, e.g. for the fosmid WRM0636bH03 I get a sequence of 407054 bp. This is much to long for a fosmid and not possible. For another fosmid in the same region WRM0635dF04 I have got a sequence of 29729 and the list of genes on this fosmid.<br/>Would you please try to find the (my) problem.<br/>Best wishes,<br/>Henning</p>

**Reported by:** Henn*********** (Henn********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10

**Comment by tharris** [comment]
User contacted; requested additional help from a sequence curator.

**Comment by Paul-Davis** [comment]
@epaule is looking into it and has been in contact with the user.

**Comment by Paul-Davis** [comment]
Any update on this @epaule ?

**Comment by Paul-Davis** [comment]
@epaule has identified a problem with ~28 fosmids (insert size >60kb) where all have a flanking sequence that hits a repeat sequence. Seeing if mapping can be made to bring them close to the ~43kb average insert size.

**Comment by epaule** [comment]
"fixed" for WS261
