### ISSUE TITLE
blastx tracks on J/GBrowse

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5689]
two of the blastx tracks for C.elegans and B.malayi contained wrongly formatted protein ids. I fixed: 
b_malayi.PRJNA10729.WS260.annotations.gff2.gz
b_malayi.PRJNA10729.WS260.annotations.gff3.gz
c_elegans.PRJNA13758.WS260.annotations.gff2.gz
c_elegans.PRJNA13758.WS260.annotations.gff3.gz

and there is a acedb patch (which is probably not needed, as the website doesn't use acedb to show blastx alignments). acedb/PATCHES/blastx_patch_ws260.ace.gz

**Comment by scottcain** [comment]
Hi @epaule those files haven't made it to the WormBase ftp site yet (I think that mirroring happens automatically, right @tharris ?). When it does, I'll make sure that the GBrowse and JBrowse datasets get updated.

**Comment by tharris** [comment]
Mirrored and databases for WS260 rebuilt on rdbms host.

**Comment by epaule** [comment]
@scottcain it looks like the staging jbrowse/gbrowse still show the old data:
![image](https://user-images.githubusercontent.com/20523/27698303-9d5b6c66-5cee-11e7-8a9a-f86bd99b9d9d.png)

**Comment by scottcain** [comment]
Hi @epaule and @tharris --it looks to me like the elegans and malayi GFF files were touched on the WB ftp site a few weeks ago (the modification date changed), but when I download them and look for updated IDs.  For example, I looked for BM41074 in the 259 malayi release and found BLASTX results but nothing in 260 release.  Unfortunately, the same file on the EBI ftp site has the same problem (and same size and same md5 sum).  I think that means @epaule needs to check the EBI ftp site and update the GFF files with the corrected ones.

**Comment by epaule** [comment]
erm ....

zgrep protein_match b_malayi.PRJNA10729.WS260.annotations.gff3.gz |perl
-anE '$h{$F[1]}++;END{while(($k,$v)=each %h){say "$k => $v"}}'

dmelanogaster_proteins-BLASTX => 28353
cremanei_proteins-BLASTX => 48767
cbrenneri_proteins-BLASTX => 54801
ovolvulus_proteins-BLASTX => 87953
bmalayi_proteins-BLASTX => 42488
hsapiens_proteins-BLASTX => 61431
celegans_proteins-BLASTX => 65916
cbriggsae_proteins-BLASTX => 55761
sratti_proteins-BLASTX => 39839
ppacificus_proteins-BLASTX => 39313
cjaponica_proteins-BLASTX => 53999
UniProt-BLASTX => 53986
scerevisiae_proteins-BLASTX => 11383

I had to switch off our old WU-blast pipeline and replace it with a newer
NCBI-blast one. Meaning, it is a bit less sensitive in the middle range and
the filtering actually works nowadays. The raw results looked almost
identical, but we do strip self-hits, proteins below a certain coverage and
below an e-value cutoff when we import it into acedb.

Your example had less than 80 of its 477 aa aligned, which falls squarely
into the coverage filter even if the e-value is not too shabby (4e-33).
Below is a graph of the blastx hits between NCBI (hive / hive-2) and WU
(rulemanager), where you can see that the middle range is mostly affected.
In the low e-value range, NCBIB is even more sensitive than WUB.

[image: Inline images 1]
the bigger differences are also in blastx rather than blastp, where we
loose almost nothing (but observe a similar behaviour of more low-evalue
hits and less mid-range ones, just less pronounced):
[image: Inline images 2]

so I would propose, you load the current GFF3 files, as it will definitely
fix the id issues, which are my main complaint.

**Comment by khowe** [comment]
@epaule to summarise: was it the case the @scottcain unluckily choose the wrong protein to search for in the new GFF files (i.e. one which the new pipeline correctly does not report a hit for)?

**Comment by epaule** [comment]
in that example: yes.

**Comment by scottcain** [comment]
OK, @epaule then let me ask explicitly what is wrong with the data in the GBrowse image.  Is the "CBP" part supposed to be something else?  I'm guessing that the malayi proteins are supposed to look like "BM:BM####".  I just want to be able to check the file and resulting build with something I can verify.  Also, I build the elegans JBrowse instance on staging yesterday--you could take a look at it too (malayi is building right now).

**Comment by epaule** [comment]
exactly. the prefixes were wrong. Or rather: I blasted against C.briggsae
instead of B.malayi (and O.volvulus), which is why they had BM:CBPXXX and
OV:OVOPXXX ids (and also the alignments were of the C.briggsae proteins
rather than the respective worms).
I rerun the blasts with the correct protein sets and changed the GFF2/GFF3
files (so there should be BM:BMAXXX proteins in the B.malayi blastx track
on the C.elegans browser).

The whole thing was because I changed the blast pipeline, as our
rulemanager one is unsupported (and WU-BLAST was also on the todo list, as
it is massively outdated) . And I copy & pasted the fasta file name
templates across ... and mixed them up (or rather copied it three times for
two worms).

Btw. I can't properly check them on JBrowse, as JBrowse doesn't show the
ids for blastx features. And GBrowse shows still the dubious ids.

**Comment by scottcain** [comment]
Oh, right--I never turned on labels for JBrowse.  I can do that.  In the mean time, you can right click on those features and select "View details" which will have the ID in the popup window.  Also, the malayi build just finished, so you can check it too.

Now I'll look into what's going on with the GBrowse database--maybe @tharris built it "prematurely" and it will have to be done again.

**Comment by epaule** [comment]
looks good on JBrowse. (I had a js plugin running to prevent right-click
hijacking from various Atlassian tools and the left click in JBrowse didn't
do very much).

**Comment by scottcain** [comment]
@tharris I think the malayi and elegans database have to be rebuilt.  I know you did it a few weeks ago, but I think the pipeline must have used the old (incorrect) gff3 files.  These queries show that the malayi IDs are still wrong in the current database.

from b_malayi_PRJNA10729_WS260:
```
select * from name where name like 'BM:%' limit 2;
+---------+-------------+--------------+
| id      | name        | display_name |
+---------+-------------+--------------+
| 2886948 | BM:CBP00009 |            1 |
| 3042043 | BM:CBP00009 |            1 |
+---------+-------------+--------------+
```
and from c_elegans_PRJNA13758_WS260, same query:
```
+---------+-------------+--------------+
| id      | name        | display_name |
+---------+-------------+--------------+
| 7921114 | BM:CBP00009 |            1 |
| 7921255 | BM:CBP00009 |            1 |
+---------+-------------+--------------+
```

**Comment by scottcain** [comment]
@epaule This is an aside: I turned on feature labeling in the B. malayi similarity track and I think I remember why I turned it off: it makes what can be a very dense track quite tall.  Please take a look and let me know what you think.

I think rather than turning labeling on, I'd rather have a mouseover display the ID, plus fixing the left clicking to do something useful (Currently in GBrowse it isn't).  I don't want to drag this too much into this issue, so if this turns into a discussion, it should probably go into its own issue.

**Comment by epaule** [comment]
you could turn the left click into what the right click currently does ...
or open a  WB Protein object, like you do with the genes.

**Comment by tharris** [comment]
Both C. elegans and B. malayi have been rebuilt for WS260 (and I discovered the problem where the previous files had synced but weren't used the first time I kicked off the rebuild).

**Comment by epaule** [comment]
looking good on GBrowse
