### ISSUE TITLE
Please correct ATE-1 gene description, it has an e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5693]
*Help Desk query collected when no chat operators were online. Follow up required.*

Please correct ATE-1 gene description, it has an extra T in the name: "ArginyltTransferasE 1 homolog" should be "ArginylTransferasE 1 homolog"

**Reported by:** Benj*********** (benj************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00010615#0-9g68c7-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00010615#0-9g68c7-10</a>
**Browser:** Firefox 53.0

**Comment by epaule** [comment]
that is actually the ATE gene class

**Comment by tuli** [comment]
Dear Benjamin,

Thank you for bringing this typo to our attention. I have removed the
spurious t from the description. You'll see this update in release
W261 of WormBase.

Best wishes,

Mary Ann

On 18 June 2017 at 14:56,  <no-reply@wormbase.org> wrote:
> offline chat Please correct ATE-1 gene description, it has an extra T in the
> name: "ArginyltTransferasE 1 homolog" should be "ArginylTransferasE 1
> homolog"
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00010615#0-9g68c7-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00010615#0-9g68c7-10
>
> This issue has been assigned ticket number: #5693. Follow progress on our
> issue tracker.
>
> Reported by: Benjamin Weaver (benjamin.weaver@colorado.edu)
> 18 Jun 17 13:55
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
