### ISSUE TITLE
In the protein interaction category what is meant ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5695]
*Help Desk query collected when no chat operators were online. Follow up required.*

In the protein interaction category what is meant by "predicted" and "protein-protein" in the categories. Also what is meant by "directional" and "non directional"

**Reported by:** joe (beye****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_users#0132--10">http://www.wormbase.org/about/userguide/for_users#0132--10</a>
**Browser:** Chrome 58.0.3029.110

**Comment by chris-grove** [comment]
[MARKETING] [wormbase-help] offline chat transcript: In the protein interaction category what is meant ... (joe)
Grove, Christian A. (Chris)
beyene@g.harvard.edu;help@wormbase.org
Hi Joe,

The "Interactions" section of the gene page is intended to capture and display all gene interactions, which includes "predicted" genetic interactions, real genetic interactions, regulatory interactions, and physical (direct molecular) interactions. We capture three types of physical interactions, protein-protein, protein-DNA, and protein-RNA.

"Directional" refers to interactions that are inherently directional, for example a genetic suppression event, where a genetic perturbation of one gene suppresses the phenotype induced by another genetic perturbation (usually of a different gene). In such cases we want to be sure that it's clear which genetic perturbation is suppressing and which is suppressed. Other interactions are "non-directional" meaning there is no inherent directionality to the interaction, at least as indicated by the experiment. An example of a non-directional interaction is a synthetic genetic interaction, where two genetic perturbations individually cause no phenotype, but when combined produce a synthetic phenotype.

Let us know if you have any further questions.

Best,

Chris Grove
WormBase
