### ISSUE TITLE
Link to tissue enrichment tool broken

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#5699]
Hi,

Clicking on the tissue enrichment link from the Tools menu is currently giving a 404 error.

https://wormbase.org/tools/enrichment/tea/tea.cgi

**Comment by raymond91125** [comment]
This specific URL is using the https protocol which does not work, http 
does.

**Comment by chris-grove** [comment]
FWIW, I'm able to load the tool without any problem from the Tools menu

**Comment by sibyl229** [comment]
Thank you @raymond91125
