### ISSUE TITLE
I need to now how to search for a figure in the wo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5701]
*Help Desk query collected when no chat operators were online. Follow up required.*

I need to now how to search for a figure in the wormbase

**Reported by:** John******* (john****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/antibody/the als like ligand binding domain of candida albicans">http://www.wormbase.org/search/antibody/the als like ligand binding domain of candida albicans</a>
**Browser:** Firefox 53.0

**Comment by chris-grove** [comment]
Hello John,

 Could you provide more specifics of what you are looking for? WormBase has acquired permissions to display figures for some papers, and most of the figures we display are related to expression patterns of genes. You can find these figures in the "Expression" widget on gene pages, for example:


http://www.wormbase.org/species/c_elegans/gene/WBGene00001609#01--10


Best,


Chris Grove

WormBase
