### ISSUE TITLE
Hi , how can I find the promoter of Let-754?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5703]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi , how can I find the promoter of Let-754?

**Reported by:** Juan (cagj****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002879#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00002879#0-9g-3</a>
**Browser:** Chrome 58.0.3029.110

**Comment by chris-grove** [comment]
From Ranjana:
"Hello Juan

Thanks for writing to WormBase.  Have you taken a look at the BioMart query tool, available from WormBase—>Tools—>Parasite BioMart (Under datelining and Batch Queries).

Select your query filters, which is the information you are looking for and then your Output Attributes which are the results you would like to see, check ‘Retrieve sequences’ at the top of the Output Attributes section, and choose all your attributes.

Let us know if you need any further help.

Ranjana Kishore
WormBase Help-desk."

**Comment by chris-grove** [comment]
Hello Juan,

 Just to add to Ranjana's comments:

There are a few ways to get the promoter of a gene:

1) You can use GBrowse to acquire the promoter sequence by manually selecting the region of interest and downloading the sequence as shown here:

https://dl.dropboxusercontent.com/u/4290782/WormBase/Retrieving_let-754_promoter_sequence_from_GBrowse.mov

2) You can get 2000 bp upstream from the Sequences widget on the gene page as shown here:

https://dl.dropboxusercontent.com/u/4290782/WormBase/Retrieving_let-754_2000bp_upstream_sequence.mov

3) If you have a list of genes and want to get upstream sequences up to 2000bp, but not including upstream genes/coding regions, I would recommend the Regulatory Sequence Analysis Tool (RSAT):

http://rsat.sb-roscoff.fr/

as shown here:

https://dl.dropboxusercontent.com/u/4290782/WormBase/Using_RSAT_to_get_upstream_sequence_without_other_coding_regions.mov


Also, the ParaSite BioMart tool is currently having issues retrieving upstream sequences, but I can send you a sample query as a URL once it is fixed.

Best,

Chris Grove
WormBase
