### ISSUE TITLE
I need to get S.mansoni ova for my research. How d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5704]
*Help Desk query collected when no chat operators were online. Follow up required.*

I need to get S.mansoni ova for my research. How do I go about it

**Reported by:** Okek******************** (obru*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search">http://www.wormbase.org/search</a>
**Browser:** Firefox 52.0

**Comment by chris-grove** [comment]
From Ranjana:
"Hello—

Thanks for writing to WormBase.  Could you please clarify your question further, are you looking for protocols/methods related to S. mansoni?  Please take a look at this page:

http://parasite.wormbase.org/Schistosoma_mansoni_prjea36577/Info/Index

There are links to many resources and other information on the parasite portal.

Hope this helps.

Ranjana Kishore"
