### ISSUE TITLE
  in your FAQ you have a response to th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5705]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;in your FAQ you have a response to this question "How can I retrieve 1.5 kb promoter region upstream of a bunch of genes?"  but the response is written for use in worm mart.  would it be possible to guide me in how to do this on worm mine to download the promoter regions from the genome (either total or chromosome by chromosome) and from a set of genes i have in a list<br/>thanks</p>

**Reported by:** stev******** (stev********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.2.5 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.5

**Comment by rankishore** [comment]
Pointed user to the Parasite Biomart tool.
