### ISSUE TITLE
ParaSite BioMart not loading at all

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5711]
I'm running VPN on a coffee shop WIFI right now, so I don't know if that is the reason, but ParaSite BioMart is not loading at all and instead is throwing the following error:

<img width="1405" alt="screenshot 2017-06-25 13 19 17" src="https://user-images.githubusercontent.com/611382/27519458-2b25640a-59a9-11e7-9b81-000992ec0996.png">

**Comment by brucebolt** [comment]
Hi @chris-grove, I'm not seeing any issue myself.  Your previous session with the error may have been cached.  I have cleared all the sessions, so hopefully this will work for you now.

**Comment by chris-grove** [comment]
OK it's working for me now. Closing.

**Comment by chris-grove** [comment]
OK, I'm at my normal desk and now am again not able to open ParaSite BioMart at all, getting the following error:

![screen shot 2017-06-27 at 4 20 43 pm](https://user-images.githubusercontent.com/611382/27608224-9bb337cc-5b54-11e7-8d13-d8567f15b6e5.png)

**Comment by chris-grove** [comment]
The problem appears to be specific to Chrome

**Comment by khowe** [comment]
It's working for me on Chrome. 

@chris-grove can you try it from an Incognito window on Chrome (File -> New Incognito window). That will tell us if it's a session-specific issue.

**Comment by khowe** [comment]
Actually, I take that back. It just happened for me too. Same query on Firefox worked.

**Comment by brucebolt** [comment]
Duplicate on #5710.
