### ISSUE TITLE
Hi guys, just wondering when the GFP expression da...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5712]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi guys, just wondering when the GFP expression data (by McKay and Newbury) for srv-4 was added? Was this a recent addition for example with a newer version of Wormbase? Just wondering if it was available in 2015?

**Reported by:** Kayl****** (u501***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe">http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe</a>
**Browser:** Safari 10.0

**Comment by rankishore** [comment]
Replied to User:
Hi Kayla--Looks like we added this information in the overview for srv-4, for the WS252 WormBase release, which was made available in March 2016.
