### ISSUE TITLE
  How do I get my own letter code for m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5713]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get my own letter code for my lab? I will be starting my own lab, and I would like a strain code (e.g. Andy Fire's lab is PD####, and alleles are cc####).</p>

**Reported by:** Josh*********** (jaar****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by tuli** [comment]
Dear Joshua,

Thank you for writing to WormBase.

Guidelines on how to request a lab/strain and allele code can be see
here: http://www.wormbase.org/about/userguide/nomenclature#0123456789abcdefghijklmn--10
(see How to Register a New Laboratory and Receive Lab, Strain and
Allele designations).

Best wishes,

Mary Ann
