### ISSUE TITLE
Gene_class : Designating_laboratory not displayed

### ISSUE THREAD

**Issue by tuli** [WormBase/website#5715]
e.g. http://www.wormbase.org/resources/gene_class/nipi#014--10

Should have Designating_laboratory IG

Problem in staging as well.

**Comment by sibyl229** [comment]
Hi @tuli the designating lab for gene class should be fixed on staging now: http://staging.wormbase.org/resources/gene_class/nipi#014--10

**Comment by tuli** [comment]
Nice. Thanks @sibyl229 
Closing.
