### ISSUE TITLE
I'm surprised that exc-1 http://www.wormbase.org/s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5716]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'm surprised that exc-1 http://www.wormbase.org/species/c_elegans/gene/WBGene00001362#0-9g1e64c5d-10
doesn't have a sequence yet associated at it has seems to have been cloned last year Facilitation of Endosomal Recycling by an IRG Protein Homologue Maintains Apical Tubule Structure in Caenorhabditis elegans.
Grussendorf KA, Trezza CJ, Salem AT, Al-Hashimi H, Mattingly BC, Kampmeyer DE, Khan L, Hall DH, Gobel V, Ackley BD, Buechner M
[Genetics, 2016]
Thank you for your work!

**Reported by:** nath********** (pujo******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001362#0-9g1e64c5d-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001362#0-9g1e64c5d-10</a>
**Browser:** Safari 9.1.2

**Comment by Paul-Davis** [comment]
"we conclude that C46E1.3 encodes EXC-1" from the paper.....I'm checking the gene structure.

**Comment by Paul-Davis** [comment]
Ignore the reference to ticket 5710 above as github has a bug and you can't remove an incorrect reference once it's been deleted.

**Comment by tuli** [comment]
Dear Tim,

Paper attached.

Do you approve the merging of WBGene00001362 (exc-1) with WBGene00008116
(C46E1.3)
Paper evidence WBPaper00049851 (see pg 1796)

Thanks,

M.A.

---------- Forwarded message ----------

**Comment by tuli** [comment]
Hi Mary Ann,

New gene association:
C46E1.3 = exc-1, Paper evidence WBPaper00049851

Thanks,
Tim




________________________________
From: Mary Ann Tuli <maryann.tuli@wormbase.org>
Sent: Wednesday, July 5, 2017 8:09 AM
To: Tim Schedl
Cc: WormBase/website
Subject: Fwd: [WormBase/website] I'm surprised that exc-1 http://www.wormbase.org/s... (#5716)

Dear Tim,

Paper attached.

Do you approve the merging of WBGene00001362 (exc-1) with WBGene00008116 (C46E1.3)
Paper evidence WBPaper00049851 (see pg 1796)

Thanks,

M.A.

---------- Forwarded message ----------

**Comment by tuli** [comment]
Dear Nathalie,

Thank you for writing to WormBase and bringing this publication to our
attention.

This is to confirm that I have made the exc-1 <-> C46E1.3 connection.
You'll see the update in release WS262 of WormBase.

Best wishes,

Mary Ann

On 28 June 2017 at 00:57,  <no-reply@wormbase.org> wrote:
> offline chat I'm surprised that exc-1
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001362#0-9g1e64c5d-10
> doesn't have a sequence yet associated at it has seems to have been cloned
> last year Facilitation of Endosomal Recycling by an IRG Protein Homologue
> Maintains Apical Tubule Structure in Caenorhabditis elegans. Grussendorf KA,
> Trezza CJ, Salem AT, Al-Hashimi H, Mattingly BC, Kampmeyer DE, Khan L, Hall
> DH, Gobel V, Ackley BD, Buechner M [Genetics, 2016] Thank you for your work!
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001362#0-9g1e64c5d-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00001362#0-9g1e64c5d-10
>
> This issue has been assigned ticket number: #5716. Follow progress on our
> issue tracker.
>
> Reported by: nathalie pujol (pujol@ciml.univ-mrs.fr)
> 27 Jun 17 23:56
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
