### ISSUE TITLE
  How do I find out what genome version...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5717]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find out what genome version is being used in the current version of wormbase?  I can find that WS258 is the current annotation, but what genome coordinates are used?  ce11?<br/>Thanks,<br/>Julie</p>

**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by khowe** [comment]
Replied off-line, saying that we will look into adding a genome summary widget on the front page

#5718
