### ISSUE TITLE
 Server Error: 500 at  rest/widget/construct/WBCns...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5721]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/construct/WBCnstr00008811/overview">rest/widget/construct/WBCnstr00008811/overview</a></p><p></p><p>Error Message:<br> undef error - Can't locate auto/Ace/Object/size.al in @INC (@INC contains: /var/lib/jenkins/jobs/staging_build/workspace/lib /usr/local/wormbase/extlib/lib/perl5/x86_64-linux-gnu-thread-multi /usr/local/wormbase/extlib/lib/perl5 {APP_HOME}/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /var/lib/jenkins/jobs/staging_build/workspace/root/templates/shared/page_elements.tt2 line 286.<br> </p>

**Reported by:** rik.******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by Paul-Davis** [comment]
Thank you for contacting WormBase.

It seems that we have a problem with one of the machines that serves the 
website, a quick reload seems to return the data you require, but the 
web team are working on fixing this issue.

Paul
[HelpDesk]


On 03/07/2017 10:59, no-reply@wormbase.org wrote:
> Bug Report
>
> Server Error: 500 at rest/widget/construct/WBCnstr00008811/overview 
> <http://www.wormbase.org/rest/widget/construct/WBCnstr00008811/overview>
>
> Error Message:
> undef error - Can't locate auto/Ace/Object/size.al in @INC (@INC 
> contains: /var/lib/jenkins/jobs/staging_build/workspace/lib 
> /usr/local/wormbase/extlib/lib/perl5/x86_64-linux-gnu-thread-multi 
> /usr/local/wormbase/extlib/lib/perl5 {APP_HOME}/lib /etc/perl 
> /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 
> /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 
> /usr/local/lib/site_perl .) at 
> /var/lib/jenkins/jobs/staging_build/workspace/root/templates/shared/page_elements.tt2 
> line 286.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5721. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5721>.
>
> Reported by: rik.haagmans@gmail.com
> 03 Jul 17 09:56
>
> Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
#5720 probably same issue

**Comment by Paul-Davis** [comment]
#5709 probably same issue

**Comment by sibyl229** [comment]
Hi @Paul-Davis should be fixed as was #5709 on staging: http://staging.wormbase.org/species/all/construct/WBCnstr00008811#01--10
Thank you!
