### ISSUE TITLE
  Is there any tool or database to find...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5722]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there any tool or database to find out if a particular set of protein is translationally tagged?</p>

**Reported by:** Moha********************* (flak*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thank you for contacting WormBase. I am not aware of this data being 
available through WormBase but will ask my colleagues if they are aware 
of such a resource or if this is something that can be extracted from 
our data in some way.

Paul



On 03/07/2017 21:53, no-reply@wormbase.org wrote:
> Question:
>
>   Is there any tool or database to find out if a particular set of 
> protein is translationally tagged?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5722. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5722>.
>
> Reported by: Mohammed Farhan Lakdawala (flakdawala4@gmail.com)
> 03 Jul 17 20:52
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/59.0.3071.115 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
Hello Mohammed,


Attached is a list of all constructs annotated by WormBase that are apparent translational fusions. Each is included with it's ID, the gene that is expressed, the fusion reporter/marker/tag, and the construct summary. To verify any particular construct, I would recommend using its ID to look it up in WormBase and look in the "Tree Display" widget to find the paper in which the construct was reported, for example:


http://www.wormbase.org/species/all/construct/WBCnstr00011023#015--10


Let us know if you have any questions.


Best,


Chris Grove

WormBase
