### ISSUE TITLE
Hi WormBase team,
For each species, I'd like to kn...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5723]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi WormBase team,
For each species, I'd like to know how many genes have been manually reviewed by a curator. Is this information available on your website?
Kind regards,
Kim

**Reported by:** Kim ******** (kimc************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all#0123--10">http://www.wormbase.org/species/all#0123--10</a>
**Browser:** Firefox 54.0

**Comment by Paul-Davis** [comment]
Hi Kim,

Thanks for contacting WormBase.

As the project has been running for so long and procedures have changed 
and evolved over this time, it's not the easiest question to answer, but 
here is the limited information that we have that can be reliably traced.

C. elegans - 15855 coding genes have been reviewed at some point over 
the last ~13 years (some of which will have had multiple itterations and 
some curation will not have been recorded so the error bar would be 
quite large for this stat).
C. briggsae - 17870 coding genes have been reviewed/corrected, the 
majority of which in the last year with the major re-annotation project 
done by us.
B. malayi - 4652 coding genes
For the rest of the core species the numbers will be far lower and much 
more error prone.

I hope this helps

Paul


On 04/07/2017 09:56, no-reply@wormbase.org wrote:
> For each species, I'd like to kn... (Kim Strasser)
> Content-type: text/html; charset="utf-8"
> Date: Tue, 4 Jul 2017 08:55:49 +0000
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
>
>
>     
>                                                                                           <style type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat Hi WormBase team,
> For each species, I'd like to know how many genes have been manually reviewed by a curator. Is this information available on your website?
> Kind regards,
> Kim  <p>Submitted From:
> <br>&nbsp;&nbsp;http://www.wormbase.org/species/all#0123--10 <a href="http://www.wormbase.org/http://www.wormbase.org/species/all#0123--10">http://www.wormbase.org/species/all#0123--10</a>
> </p>
>
> <p>
> This issue has been assigned ticket number: #5723. Follow progress on our <a href="https://github.com/WormBase/website/issues/5723">issue tracker</a>.
> <p>
>
> <p>
> Reported by: Kim Strasser (kimchi.strasser@concordia.ca) <br />
> <span class="fade">04 Jul 17 08:55 </span><br /><br />
> <span class="fade"> </span>
> </p>
>
> <p class="fade">
> This question was reported via the web interface at wormbase.org. You can also <a href="mailto:help@wormbase.org">email us</a> directly.
> </p>
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
