### ISSUE TITLE
Extra TSS wiggle plot files in WS261

### ISSUE THREAD

**Issue by gw3** [WormBase/website#5725]
@scottcain - there will be an extra pair of wiggle files as of the WS261 release in the annotation file:
.../species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS261.TAR_gene_expression.tar.gz

The extra files: TSS_Gu.Forward.wig and TSS_Gu.Reverse.wig display Pol II transcription start sites as defined by the paper WBPaper00041861 (Gu et al. ￼ Cell (2012) 151; 7, pp 1488–1500)

Could these extra TSS files be added to the TSS section of G/JBrowse, please.

Gary Williams

**Comment by scottcain** [comment]
Sure.  Would it be OK if I convert the wiggle files to BigWigs?  JBrowse doesn't support wiggle natively, and the workaround is ugly.

**Comment by gw3** [comment]
@scottcain Yes, of course that's fine. :-)

**Comment by scottcain** [comment]
Hi @gw3 

Are you sure the files you mentioned above made it into the c_elegans.PRJNA13758.WS261.TAR_gene_expression.tar.gz file?  The only files I see in this tar are files whose names start with gene_ and transcripts_ and none contain the string tss or TSS.  These files are all time stamped July 21.  I got these from the OICR mirror of the ftp site.  Perhaps there was an update after the mirror was made?

**Comment by scottcain** [comment]
Oh, I think I have the right file now: it's not in the gene_expression tar file, it's in the (surprise!) c_elegans.PRJNA13758.WS261.TSS.wig.tar.gz file.

**Comment by gw3** [comment]
Hi @scottcain,

Yes, you have the correct file now.
:-)

Gary

**Comment by scottcain** [comment]
@gw3: I've converted these wiggle files to bigwig and put them on JBrowse:

http://staging.wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758&loc=I%3A7346025..7348462&tracks=Curated_Genes%2CTSS%20(Gu)%20Forward%2CTSS%20(Gu)%20Reverse&highlight=

Do you have a feeling for what value of max score should be?

**Comment by gw3** [comment]
I had a look at the values for the forward sense.
There is a long tail going up to very high values:

Bin_of_value Count
0 24724
1000 2897
2000 1363
3000 694
4000 411
5000 284
6000 208
7000 139
8000 110
9000 98
10000 77
11000 76
12000 41
13000 36
14000 40
15000 34
16000 26
17000 17
18000 32
19000 23
20000 26
21000 18
22000 18
23000 21
24000 16
25000 11
26000 20
27000 8
28000 10
29000 10
30000 6
31000 12
32000 11
33000 8
34000 6
35000 5
36000 8
37000 8
38000 9
# deletia
5772000 1
8908000 1
11196000 1
11719000 1
18926000 1
22671000 1

A value of 1000 for max score gives 24,724 below max score and 7208 
above max score.
This looks reasonable on the browser - gives a good sense of where the 
strong sites are without losing the weak sites.
Go with max score = 1000

Gary

**Comment by epaule** [comment]
seems working
