### ISSUE TITLE
WormBase wiki

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5726]
Login seems to be broken so if you are logged in.....all is good, but if you have been logged out you can no longer log back in :(

![wiki_login](https://user-images.githubusercontent.com/717707/27866224-69fa3458-618d-11e7-85a4-630efcc33e23.png)

Tested by Michael, Gary and Kev.

Paul

**Comment by tuli** [comment]
Same problem in the Steeple Bumpstead outstation.

**Comment by Paul-Davis** [comment]
Chris emailed Todd who fixed the issue
