### ISSUE TITLE
I have a question about identifying the rh411 alle...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5727]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have a question about identifying the rh411 allele. It says that the "Reference allele" is m20, so does it mean that rh411 and m20 contain the same mutation? I obtained the strain AA86 daf-12(rh61rh411)X from the CGC, and I'm trying to cross in this allele to another strain. I'm just not sure how I should design primers for sequencing the rh61rh411 allele. Thanks for your help!

**Reported by:** Io L******** (IoLo********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088536#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00088536#02-45-3</a>
**Browser:** Chrome 59.0.3071.115

**Comment by chris-grove** [comment]
Hello Io,


"Reference allele" is just to say that m20 is the reference allele for daf-12; it doesn't pertain to rh411 other than that they are both alleles of daf-12.


I couldn't find any sequence information/details about rh411, so you may want to sequence the whole daf-12 locus. You could also try to reach out to Edward Hedgecock, whose lab originally isolated the allele:


http://www.wormbase.org/resources/person/WBPerson1052#0134--10


Best,


Chris Grove

WormBase
