### ISSUE TITLE
Where can I find descriptive statistics of the dat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5728]
*Help Desk query collected when no chat operators were online. Follow up required.*

Where can I find descriptive statistics of the data included in WormBase?

**Reported by:** Amra*********** (amra***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_developers#03--10">http://www.wormbase.org/about/userguide/for_developers#03--10</a>
**Browser:** Chrome 59.0.3071.115

**Comment by chris-grove** [comment]
Hello Amrapali,


 You can find some descriptive statistics of WormBase data from our release letter, generated for each release of the database. You can find this by clicking on the "Release Schedule" link at the bottom of any WormBase page in the "About" section which will take you here:


http://www.wormbase.org/about/release_schedule#01--10


Once on that page, you can click on a release number to see the release letter. For example, to see the release letter for the current version of WormBase (WS258), click on the hyperlinked "WS258" in the Release column of the table:


http://www.wormbase.org/about/wormbase_release_WS258#0--10


For other stats, you may want to look at files on our FTP site, a link for which is at the bottom of every WormBase page:


ftp://ftp.wormbase.org/pub/wormbase/


If you have specific data stats requests not available in these locations, we may be able to query the database or write a script to get the numbers you're looking for.


Best,


Chris Grove

WormBase
