### ISSUE TITLE
  How would you use Gbrowse or any othe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5729]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How would you use Gbrowse or any other tool to find the FASTa or the genetic code of a specific non coding region? I hope that makes sense </p><p>What were you doing? <br />&nbsp;&nbsp;I've been using Gbrowse, Searching for a general segment of non coding DNA flanking cbr-unc-54 in order to get the FASTa or just the copy of the letter code. I haven't been able to find the actual code. I'm trying to use it to generate CRISPR targets so I could use any bit of code whether tandem repeats or low variation segments.
Thank you so much! </p>

**Reported by:** John********** (doug*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by chris-grove** [comment]
Hello John,

Here's a brief screen capture video demonstrating how to use GBrowse and JBrowse to get flanking, non-coding sequence adjacent to Cbr-unc-54:

https://www.dropbox.com/s/wrbxbm8vt0mn5fv/Retrieving_flanking_non_coding_sequence_of_Cbr-unc-54.mov?dl=0


Also, here's a URL for a WormBase ParaSite BioMart query for pulling out 2000 bp of upstream sequence from Cbr-unc-54:


http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.gene_flank|wbps_gene.default.sequences.upstream_flank."2000"&FILTERS=wbps_gene.default.naive_filters.species_id_1010."briggprjna10731"|wbps_gene.default.naive_filters.gene_name."Cbr-unc-54"&VISIBLEPANEL=resultspanel


Just click on "Results" at the top of the page to get the sequence; it may require a couple of attempts as there's an intermittent bug affecting this query, but it should work after a few attempts.


Please let us know if you have any questions.


Best,


Chris Grove
WormBase
