### ISSUE TITLE
WormMine 502 Proxy Error

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5730]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Lamia, how can I help?</br>visitor_name (visitor_name@stanford.edu): Hi! Wormmine seems to  not be working since yesterdat.</br>Chris: Oh, hmmm, sorry about that</br>Chris: let me take a look</br>visitor_name (visitor_name@stanford.edu): ok thanks!</br>Chris: Yep, it seems it's not loading</br>Chris: OK, I'll contact our WormMine developer and make sure he is aware of the problem. I can send you an email once we have it back up and running. Apologies for the inconvenience and thanks for letting us know!</br>visitor_name (visitor_name@stanford.edu): thanks so much!</br>Chris: Is there anything else I can help you with?</br>Chris: Take care!

**Reported by:** lami* (lami**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 60.0.3112.40

**Comment by chris-grove** [comment]
On Safari, Chrome, and Firefox I get a 502 Proxy Error when trying to load WormMine:

![wormmine_502_proxy_error_7-7-2017](https://user-images.githubusercontent.com/611382/27975840-0003cb30-6332-11e7-9c79-cb2140fc298d.png)

**Comment by nuin** [comment]
Investigating. I got the same error a couple of days ago, but it was fine yesterday.

**Comment by nuin** [comment]
It's back on. I will keep an eye on it just in case, you can close the ticket if it works for you.

Thanks, @chris-grove

**Comment by chris-grove** [comment]
Wrote to user:
"Hello Lamia,


 Thanks again for reporting the WormMine error, and apologies for the inconvenience. WormMine is now back up. Please let us know if you encounter any more issues.


Best,


Chris Grove

WormBase"
