### ISSUE TITLE
Chris: Hello Ichiro, how can I help? visitor_name ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5733]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Ichiro, how can I help?</br>visitor_name (visitor_email): I really appreciate WormBase's effort on Publication records on me. Nevertheless I feel unnatural that Al-Amin et al paper in Scientific Reports (Article number: 33884) was assigned as Year Not Available. If its doi (doi:10.1038/srep33884) is checked, it is clear that it has been published in 2016. Please reconsider the assignment. Thank you very much.

**Reported by:** Ichi*********** (ikaw************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/person/WBPerson1148#013--10">http://www.wormbase.org/resources/person/WBPerson1148#013--10</a>
**Browser:** Chrome 49.0.2623.112

**Comment by chris-grove** [comment]
User ended chat before I could respond.

@vanaukenk  
This looks fixed in the paper editor. Maybe it just hasn't made it to the website yet?

**Comment by chris-grove** [comment]
Also, the paper is WBPaper00050167

**Comment by vanaukenk** [comment]
@chris-grove  - Yes, this was updated in the editor, but was only included in the latest upload, so will definitely not be on the website yet.  I will email Ichiro tomorrow.

**Comment by chris-grove** [comment]
@vanaukenk 
OK, thanks!
