### ISSUE TITLE
  I am looking at the RNASeq track on t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5734]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am looking at the RNASeq track on the briggsae genome. It says it includes "sequences from all available RNASeq projects". Is there a way I can get a list of the RNASeq projects that were included? Thanks!</p>

**Reported by:** Ian (iwoo*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

**Comment by gw3** [comment]
Ian,

The C. briggsae SRA Experiments used in release WS258 are:

SRX392707	
SRX392711	
SRX089119	
SRX392709	
SRX103666	
SRX191954	
SRX311791	
SRX1500344	
SRX103656	
SRX191957	
SRX1500346	
SRX103655	
SRX103668	
SRX392713	
SRX052081	
SRX392718	
SRX1297656	
SRX1500345	
SRX311788	
SRX103667	
SRX100087	
SRX311790	
SRX1297657	
SRX127749	
SRX052079	
SRX089120	
SRX191958	
SRX392712	
SRX100086	
SRX089070	
SRX100088	
SRX392714	
SRX311789	
SRX392708	
SRX392717	
SRX1297659	
SRX392706	
SRX191953	
SRX311787	
SRX392715	
SRX053351	
SRX1297658	
SRX1297660	
SRX392716	
SRX311786	
SRX089069	
SRX1297661	
SRX127748	
SRX191955	
SRX100089	
SRX191956	
SRX392710	


These come from the following SRA Studies:

SRP006033
SRP011366
SRP016006
SRP026198
SRP034522
SRP056941
SRP067756

If there is any further information you require about how the data was processed, please get back to me.

Regards,
Gary Williams
