### ISSUE TITLE
Blast/Blat service is down

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5742]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;There is 504 Bad Gateway Time out error</p><p>What were you doing? <br />&nbsp;&nbsp;Using BLAST</p>

**Reported by:** xue ****** (hoxu**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Paul-Davis** [comment]
Thank you for reporting the issue, the web team are aware of the issue 
and are working to redeploy the service.

Paul
[HelpDesk]


On 13/07/2017 04:14, no-reply@wormbase.org wrote:
> Everything's broken!
>
>   There is 504 Bad Gateway Time out error
>
> What were you doing?
>   Using BLAST
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5742. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5742>.
>
> Reported by: xue yan ho (hoxueyan@gmail.com)
> 13 Jul 17 03:14
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
Paul Davis
Senior Technical Officer [WormBase Bioinformatician]
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
#5744 is a duplicate

**Comment by Paul-Davis** [comment]
Service seems to be working fine.....closing the ticket.
