### ISSUE TITLE
  Blast/Blat isn't working - it is timi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5744]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Blast/Blat isn't working - it is timing out.</p><p>What were you doing? <br />&nbsp;&nbsp;trying to reach the blast/blat tool</p>

**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi Julie,

We are aware of the issue, seems that the WS259 update last night still 
has some issues.

You can use the Parasite blast service while we are working to restore 
the service to the main site.

http://parasite.wormbase.org/Tools/Blast?db=core

Paul


On 13/07/2017 11:20, no-reply@wormbase.org wrote:
> Bug Report
>
>   Blast/Blat isn't working - it is timing out.
>
> What were you doing?
>   trying to reach the blast/blat tool
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5744. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5744>.
>
> Reported by: Julie Ahringer (ja219@cam.ac.uk)
> 13 Jul 17 10:21
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
