### ISSUE TITLE
  Is there a way to easily find out how...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5745]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a way to easily find out how many gene model changes occurred between different wormbase releases?  <br/>Thanks,<br/>Julie</p>

**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Paul-Davis** [comment]
Subject: | Re: [wormbase-help] How Do I ...?: Is there a way to easily find out how... (Julie Ahringer)
-- | --
Thu, 13 Jul 2017 15:09:22 +0100
Kevin Howe <kevin.howe@wormbase.org>
kevin.howe@wormbase.org
Julie Ahringer <ja219@cam.ac.uk>
help@wormbase.org <help@wormbase.org>, no-reply@wormbase.org
