### ISSUE TITLE
  Hello,  I am interested in preforming...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5746]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>I am interested in preforming a high throughput blast of a group of transcription factor binding sites against the c. elegans genome and I was wondering if there was an easy way to do this with worm base. <br/>Thank you,<br/>Rebecca</p>

**Reported by:** Rebe**** (rriv*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Paul-Davis** [comment]
Hello Rebecca,


Are you querying with specific sequences for exact matches, or are you looking to query with a position frequency (or weight) matrix? The BLAST tools won't really work for very short sequences; I was able to go as short as 14 nt before BLAST didn't return any results.


The JBrowse tool will allow you to search for exact matches in a region of the genome or will allow you to upload a position frequency matrix and a score cutoff to look for matches within a region.


If you really want to query against the whole genome for a small (<14 nt) TF binding sites, you may need to download the whole genome from our FTP site:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/sequence/genomic/


and probably write a script (or use some other tool) to get matches.


Best,


Chris Grove

WormBase
