### ISSUE TITLE
I have a doubt

When I search information for the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5747]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have a doubt

When I search information for the gene F41G3.20 in wormbase. I find the following information
Tiling array and microarray studies indicate that F41G3.20 is regulated byrsr-2, osm-7, osm-11, crh-1, tax-6, tdp-1, mir-35, isp-1, and nuo-6; microarray studies indicate that F41G3.20 is regulated by Resveratrol, Hydrolyzable Tannins, Humic substances, and Allantoin.
Date last updated: 2017-2-14 
Inferred automatically: This description was generated automatically by a Textpresso script based on homology/orthology data, Gene Ontology (GO) annotations and tissue expression data from the WS258 version of WormBase. 
Curator: James Done; Ranjana Kishore

http://www.wormbase.org/species/c_elegans/gene/WBGene00044315#03-9g-10

I do not find the paper evidence anyway. What is the meaning of “This description was generated automatically by a Textpresso script based on homology/orthology data, Gene Ontology (GO) annotations and tissue expression data from the WS258 version of WormBase”.

Thank you in advance

**Reported by:** Susa*********** (susa************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00044315#03-9g-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00044315#03-9g-10</a>
**Browser:** Chrome 59.0.3071.115

**Comment by Paul-Davis** [comment]
Hi Susana

Thanks for writing to WormBase. Most of our gene descriptions are generated automatically by scripts that look at the primary data already curated in WormBase such as orthology, gene ontology (GO), and expression data such as expression cluster data.  This is stated in the Evidence that reads ‘This description was generated automatically……’. 

The specific data that you are asking about related to regulation of the gene of interest by drugs and other genes belongs to what we call ‘expression cluster’ data.  Large scale data such as microarray, tiling array, and RNA seq data is summarized by the curator who curates this, from several papers, and is incorporated into the gene description. The details of the expression cluster data can be found on the F41G3.20 gene page, in the ‘Expression’ widget (make sure you have this widget open, from the vertical menu bar on the left side of the page), in the ‘Expression Cluster’ table.  The paper references can be found here as well.

I hope this helps, please don’t hesitate to write to me, if you have any further questions.

Best
Ranjana Kishore
WormBase.
