### ISSUE TITLE
Hello, please send me the step wise methods, that ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5750]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, please send me the step wise methods, that how we can analyse the microRNA in C. elegans for reproductive toxicity.

**Reported by:** Alam********* (dral*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Safari 9.1.2

**Comment by Paul-Davis** [comment]
Dear Alam,

Thank you for contacting WormBase. Unfortunately we do not have a list 
of protocols so you might be better off asking in the Worm Community 
Forum: http://forums.wormbase.org/

All the best for your research.

Paul
[HelpDesk]


On 16/07/2017 09:10, no-reply@wormbase.org wrote:
> offline chat Hello, please send me the step wise methods, that how we 
> can analyse the microRNA in C. elegans for reproductive toxicity.
>
> Submitted From:
>   http://www.wormbase.org/#012-34-5 http://www.wormbase.org/#012-34-5 
> <http://www.wormbase.org/http://www.wormbase.org/#012-34-5>
>
> This issue has been assigned ticket number: #5750. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5750>.
>
> Reported by: Alam Zeb Khan (dralamzebkhan2010@hotmail.com)
> 16 Jul 17 08:10
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
