### ISSUE TITLE
  Whether there is any commercially ava...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5752]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Whether there is any commercially available kit for Isolation of C. elegans mitochondria and its mitochondria protein.Please suggest me that bec we dont have ultracentrifuge in the department.<br/>Thanking you<br/>visitor_nameMir</p><p>What were you doing? <br />&nbsp;&nbsp;Ph.D student</p>

**Reported by:** Dila**** (dila***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thank you for contacting WormBase. It might be worth asking your 
question on the worm community forum: http://forums.wormbase.org/

The forum has many expert lab scientists who are more familiar with 
technologies and kits that are available for experimenting with C. elegans.

Paul
[HelpDesk]


On 17/07/2017 11:51, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Whether there is any commercially available kit for Isolation of C. 
> elegans mitochondria and its mitochondria protein.Please suggest me 
> that bec we dont have ultracentrifuge in the department.
> Thanking you
> Dilawer Mir
>
> What were you doing?
>   Ph.D student
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5752. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5752>.
>
> Reported by: Dilawer (dilawerjk@gmail.com)
> 17 Jul 17 10:51
>
> Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/59.0.3071.115 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
