### ISSUE TITLE
Ontology Browser giving 504 Gateway Time-out

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5753]
I cannot load the Ontology Browser tool from the main Tools menu. I'm getting the "504 Gateway Time-out" error message.

**Comment by raymond91125** [comment]
I'm not sure where the problem is. wormbase.org is still loading with difficulties and on caltech end, nothing seems to be out of the ordinary at the moment. will have to wait until wormbase stabilizes to test again.

**Comment by raymond91125** [comment]
It's back working for me.

**Comment by chris-grove** [comment]
Yep, me too. Thanks.
