### ISSUE TITLE
Can't find the gene info reported in any of the pa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5756]
*Help Desk query collected when no chat operators were online. Follow up required.*

Can't find the gene info reported in any of the papers listed as evidence. It's painful.

**Reported by:** Ales****** (alep************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006495#0-9gcd-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00006495#0-9gcd-10</a>
**Browser:** Chrome 59.0.3071.115

**Comment by vanaukenk** [comment]
Dear Alessandra,

Thank you for writing to WormBase.

The gene description for cpna-1, as well as many others in WormBase, are produced via an automated pipeline that uses existing primary data curated in WB as supporting evidence for the description.

In this particular case, if you look at the Expression and Gene Ontology widgets on the cpna-1 gene page, and click on the Details link (for Gene Ontology annotation this is accessed by selecting the Full View radio button) you will see the supporting paper evidence that is also cited in the gene description.

For papers that report on Expression Clusters, it may be easiest to click on the supporting paper evidence listed in the concise description and then access the list of genes in each associated expression cluster to find mention of cpna-1.

Please let us know if you need any other assistance.

Best,
--Kimberly Van Auken

**Comment by draciti** [comment]
Hello Alessandra, 
we're sorry for the inconvenience. We have fixed the underlying curated data. 
The update will be available online in the next WormBase release.

Thanks for spotting this!

Best,
Daniela
