### ISSUE TITLE
I would like to know if Haemonchus a parasitic nem...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5757]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to know if Haemonchus a parasitic nematode has information about its genome

**Reported by:** Mari******************* (mlop*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all#05--10">http://www.wormbase.org/species/all#05--10</a>
**Browser:** Safari 10.1.1

**Comment by raymond91125** [comment]
You might want to check parasite.wormbase.org for parasitic nematode 
information.

<http://parasite.wormbase.org/Haemonchus_contortus_prjeb506/Info/Index>

<http://parasite.wormbase.org/Haemonchus_contortus_prjna205202/Info/Index>

<http://parasite.wormbase.org/Haemonchus_placei_prjeb509/Info/Index>

Raymond
