### ISSUE TITLE
  I would like to have a list of Overvi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5758]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to have a list of Overview section in the Wormbase for the list of genes. How do I do that?? Thanks!</p>

**Reported by:** noma*****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

**Comment by Paul-Davis** [comment]
Hi,

Thank you for contacting wormbase.

If you want to get the full details of the overview widget you can use 
the rest API with the following end point:

http://www.wormbase.org/rest/widget/gene/WBGene00044736/overview

You can issue commands such as

curl -X GET --header 'Accept: application/json' 'http://rest.wormbase.org/rest/widget/gene/WBGene00000412/overview' > WBGene00000412.overview.json

to save the data to disk.

I hope this helps.

Paul

On 19/07/2017 06:57, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I would like to have a list of Overview section in the Wormbase for 
> the list of genes. How do I do that?? Thanks!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5758. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5758>.
>
> Reported by: nomawormlab@gmail.com
> 19 Jul 17 05:57
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
