### ISSUE TITLE
Need to get additional Phenotype association data into WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5759]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I used a WormMine to obtain the list of genes having locomotion variant as a phenotype. I used Phenotype -> Gene in the templates. However, some genes seem to be missing. For example, F59D12.1 is reported to have a locomotion variant phenotype in Wormbase but it was not retrieved in the list. Could you please let me know why it happens? Thank you!</p>

**Reported by:** noma*****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

**Comment by Paul-Davis** [comment]
Hi,

Unfortunately your example gene is not included in the list of results 
as it's association is made via RNAi which are not in the wormine 
database. The list of results you are getting are through variation 
mappings.

The best way of getting a list of genes with this phenotype is to 
download this file:
ftp://ftp.wormbase.org/pub/wormbase/releases/WS260/ONTOLOGY/phenotype_association.WS260.wb

and filter out all the WBPhenotype:0000643 (locomotion variant) lines

I hope this helps.

Paul



On 19/07/2017 07:06, no-reply@wormbase.org wrote:
> Bug Report
>
>   I used a WormMine to obtain the list of genes having locomotion 
> variant as a phenotype. I used Phenotype -> Gene in the templates. 
> However, some genes seem to be missing. For example, F59D12.1 is 
> reported to have a locomotion variant phenotype in Wormbase but it was 
> not retrieved in the list. Could you please let me know why it 
> happens? Thank you!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5759. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5759>.
>
> Reported by: nomawormlab@gmail.com
> 19 Jul 17 06:06
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Converting ticket into a WormMine data request.
