### ISSUE TITLE
Need wormbase@ebi.ac.uk added to staff@wormbase.org

### ISSUE THREAD

**Issue by khowe** [WormBase/website#5763]
Hi Todd, 

Could wormbase@ebi please be added to staff@wormbase.org, with permission to post but not receiving email? 

We need this in place by the end of next week (2017-07-29)

Thanks.

**Comment by tharris** [comment]
See discussion on Slack DM.

**Comment by tharris** [comment]
Seems to be working (as per recent post by MP). Closing.
