### ISSUE TITLE
Release notes 

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#5767]
For now I've posted a blog item about WormBase releases in general, with a link to the WS259 release notes.  I think we can  1. Make the release notes more user friendly and consumable (as discussed on today's conference call).  2.  Make the release notes/letter easier to find, personally I think it's hard to find them now.  Would it be possible to make the 'Version: WS259' on the home pag, a hyperlink to the release notes?  Also we could put the link to the current release notes directly under About-->What's New-->Release notes (together with Release Schedule).  The huge Release History table is a bit scary for Users to go through just to find the Release notes.

**Comment by rankishore** [comment]
Action item: Hinxton is working on making a JSON/HTML representation of the release notes that users can compute on, compare and contrast, etc.
Other ideas: Have a visual representation of the release notes in the form of graphs/pie charts on the WB home page which would also serve to convey the breadth and depth of the data we curate.

**Comment by sibyl229** [comment]
Hi @rankishore Sorry about the lateness. The release note has now been linked to from About-->What's New-->Release notes , as well as the version number in the header, http://staging.wormbase.org/ .

**Comment by rankishore** [comment]
@sibyl229: Cool, I tested both links and it works. Closing.
