### ISSUE TITLE
Hi there! Can I download for a gene the FPKM expre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5772]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there! Can I download for a gene the FPKM expression data from selected modENCODE libraries (i.e the polyA+ and ribozero RNAseq data across life-stages)? Thank you!

**Reported by:** Gust*********** (gsal************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001564#0c1-9g8b-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001564#0c1-9g8b-3</a>
**Browser:** Chrome 59.0.3071.115

**Comment by gw3** [comment]
Gustavo,

The data for the graph of FPKM across the life-stages is calculated from 
the values of several libraries.
We do not have a file prepared for you to download.
If you send me a list of the genes that you are interested in, I can 
create a csv file for you of the FPKM values.

Gary Williams
