### ISSUE TITLE
Sequences Widget issue on Gene page (Pseudogene and Transcript genes) 

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5773]
Hi,

It seems that somewhere down the line the contents of the Sequences widget got partially lost/new data types not included.

For Pseudogene:
http://www.wormbase.org/species/c_elegans/gene/WBGene00015078#0g9--10

![pseudogene_sequences_widget](https://user-images.githubusercontent.com/717707/28519535-e6ef4a22-7063-11e7-9cd6-47c6c8684e6e.png)

There is a lack of any linking to the Pseudogene object and summary page....I would have expected there to be this entry in the sequence widget table.

For non-coding genes:
http://www.wormbase.org/species/c_elegans/gene/WBGene00002285#0g9--10

We have a partial table:

![transcript_gene_sequence_widget](https://user-images.githubusercontent.com/717707/28519600-23098928-7064-11e7-80f3-59231bc02d1f.png)

But this isn't complete and should look more like the "sequence like" table on the corresponding Transcript summary Overview widget

![transcript_sequence_like_overview_table](https://user-images.githubusercontent.com/717707/28519642-50134e5e-7064-11e7-96ab-0c1ae047c857.png)

I remember there was a phase when generating this semi dynamic widget was causing the web team coding issues, but I thought that was all ironed out.

If someone could take a look that would be great as currently I don't think there is a Pseudogene summary page entry point on the website.

Thanks

Paul

**Comment by sibyl229** [comment]
Hi @a8wright , I recall you worked on converting sequence widgets lately. Could you take a look at this ticket when you are back?

**Comment by a8wright** [comment]
Thanks @Paul-Davis for finding this, I will work on fixing this issue, when I am back, next week. @sibyl229 yes I created this widget, I think it was recently but not too recently - I will have to dig into the code to remember how it works. :)

**Comment by a8wright** [comment]
Taking a look today.

**Comment by a8wright** [comment]
@Paul-Davis, I have been working on the code so that the table on the Gene (sequences) widget with CDS, Transcript, and Protein (Overview) widgets. I have this working on the Overview widgets will not be releasing them right away because other parts of those widgets require more work. That being said I believe that the code running on staging contains a fix for this ticket that I would like to release as soon as it is approved. That being said Let me know if there are any cases that are not working correctly with this widget.

**Comment by Paul-Davis** [comment]
@a8wright looks good. Fixes you have in place seem to resolve all the issues I identified.

**Comment by Paul-Davis** [comment]
I don't think the code was ever released for this as staging and live are still not showing sequence data for Pseudogenes

**Comment by a8wright** [comment]
@Paul-Davis Thanks for noticing this. I think I remember someone briefly mentioning something about this on one of the calls. For some reason I didn't clue in that this could have happened. I am not sure why it was over looked. I have just worked with sibyl to get it pulled into the develop branch. It will be running on staging shortly.

**Comment by sibyl229** [comment]
Hi @Paul-Davis do you mind checking again? I think the changes are deployed on staging now:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00002285#0-9g-3
Thanks!

**Comment by Paul-Davis** [comment]
Hi, thanks for actioning this......looks great, but do you think it's worth adding the (no CDS) to all rows in the table?

![issue5773](https://user-images.githubusercontent.com/717707/35619589-68c1c478-0676-11e8-97fd-35ea8fb81d5b.png)

**Comment by a8wright** [comment]
@Paul-Davis I think this one was finished. Please let me know if there is further work to be done. If not feel free to close the ticket
