### ISSUE TITLE
Just a short note about tag-342: In the paper (htt...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5774]
*Help Desk query collected when no chat operators were online. Follow up required.*

Just a short note about tag-342: In the paper (https://doi.org/10.1016/j.ceca.2007.07.008) the authors find a calcium binding motif in tag-342. This is mentioned in the supplementary data. Not sure whether this kind of information is useful for you.

**Reported by:** Gaut****** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/person/WBPerson324#01--10">http://www.wormbase.org/resources/person/WBPerson324#01--10</a>
**Browser:** Firefox 52.0

**Comment by vanaukenk** [comment]
Dear Gautam,

Thank you very much for bringing this paper to our attention.

We will review the paper as part of our functional annotation pipeline and add all information where appropriate to the respective genes, including tag-342.

Best,
--Kimberly Van Auken
