### ISSUE TITLE
Hello! I need help regarding control of RFP RNAi a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5775]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello! I need help regarding control of RFP RNAi as in my case its expressing in neurons and to check effect i need control. I tried to use GFP RNAi as control but it didn't worked. Please suggest what to do and help. 
Thanks

**Reported by:** SUPI**** (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 59.0.3071.115

**Comment by vanaukenk** [comment]
Dear Supinder,

Thanks for contacting WormBase.

Are you familiar with the Worm Community Forum?

http://forums.wormbase.org/

The Worm Community Forum is a great way to get advice and feedback from members of the C. elegans community on specific experimental techniques.  You can search the forum without registering, but if you want to post your question, you'll need to set up an account.

Good luck and please let us know if you need any additional assistance.

Best,
--Kimberly Van Auken
