### ISSUE TITLE
I was looking for the primers used in the construc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5776]
*Help Desk query collected when no chat operators were online. Follow up required.*

I was looking for the primers used in the construction of the strain VC387. I have been working with this strain, did some crosses and I want to have a molecular assay to verify the deletion. Could you be so kind to send me that information. Thank you.

**Reported by:** Céli********** (C.M.********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/strain/VC387#02--10">http://www.wormbase.org/species/c_elegans/strain/VC387#02--10</a>
**Browser:** Chrome 59.0.3071.115

**Comment by vanaukenk** [comment]
Dear Celia,

Thanks for writing to WormBase.

You can find the Molecular Details of the deletion, ok618, contained in the VC387 strain on the corresponding variation page in WB:

 http://www.wormbase.org/species/c_elegans/variation/WBVar00091902

In the list of widgets on the left-hand side of the page, click on the Molecular Details link.  The information in that widget shows the extent of the ok618 deletion, as well as 250bp of flanking sequence from which you can create primers to verify the presence of the deletion in your strain.

Please let us know if you need any additional assistance.

Best,
--Kimberly Van Auken
