### ISSUE TITLE
Need to fix links to CGC

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#5778]
Hi,

The CGC updated their website, but it looks like the link outs from WB weren't also updated.

Current WB links:

https://cbs.umn.edu/cgc/home

https://cgcdb.msi.umn.edu/search.php?st=EU40

Example replacements:

https://cgc.umn.edu/

https://cgc.umn.edu/strain/EU40

Let me know if there's a file on github that needs to be updated.  Thx.

**Comment by tuli** [comment]
Thank @vanaukenk 
I have updated the links within the Nomenclature guidelines

**Comment by epaule** [comment]
you can change that file for the website links: https://github.com/WormBase/website/blob/staging/root/templates/config/external_urls

**Comment by vanaukenk** [comment]
Thanks @epaule 

@sibyl229  - I've updated the cgc URLs in the external_urls and generated a pull request for my edited branch.

Thx.

**Comment by tuli** [comment]
The link in the bottom black list of links on the homepage needs to be updated to https://cgc.umn.edu/

**Comment by sibyl229** [comment]
CGC link in the footer is fixed.
