### ISSUE TITLE
Hi.

Can you tell me, please, which online form (f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5779]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi.

Can you tell me, please, which online form (from those at http://www.wormbase.org/about/userguide/submit_data#012--10) should be filled in order to submit a GTF file containing lincRNAs annotation for Schistosoma mansoni?

Thanks in advance.

--
visitor_name

**Reported by:** Davi**************** (davi***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#012--10">http://www.wormbase.org/about/userguide/submit_data#012--10</a>
**Browser:** Chrome 59.0.3071.109

**Comment by vanaukenk** [comment]
Hi David, 

WormBase is a nematode-centric resource, and although we display public genomic data from platyhelminth species in our sister site WormBase ParaSite, we don't generally accept submissions of non-nematode data sets. 

The custodians of the S. mansoni genome and reference annotation are the parasite genomics group at the Wellcome Trust Sanger Institute. I've been in contact with them, and they would be happy to discuss the possibility of taking your lincRNAs and including them in the new reference annotation for S. mansoni. The person to write to is Zhigang Lu (zl3@sanger.ac.uk). 

Best wishes, 

Kevin
