### ISSUE TITLE
(ParaSite) species tree json file checksum

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#5781]
Hi @khowe ,

Not sure if I should report this minor issue with the parasite species tree. The json has an array reference accidentally mixed into a string https://github.com/WormBase/website/blob/staging/conf/species/parasite_species_tree.json#L995. As the array reference gets updated, the JSON gets a different checksum (even though nothing else visible in the json is different). 

What makes this a problem is that the website routinely gets the file from http://parasite.wormbase.org/Multi/Ajax/species_tree and keep a copy in git (so the website can work independently from other resources). As the file checksum changes (which happens quite frequently, like every week or so), git requires a manual commit. Is this something that can be fixed on the ParaSite side?

Thanks,

Sibyl

**Comment by khowe** [comment]
Hi @sibyl229. Thanks for reporting. This is fixed now.

**Comment by sibyl229** [comment]
Thanks a lot @khowe !
