### ISSUE TITLE
  I want to know whether your instituti...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5789]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to know whether your institution can  send the transgene strains to me.<br/>I am in China. Thanks.</p><p>What were you doing? <br />&nbsp;&nbsp;I am a graduate student in East China university of science and technology .</p>

**Reported by:** Xue *** (1561*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by tuli** [comment]
Dear Xue Cao,

Thank you for your email. Strains should be ordered from the
Caenorhabditis Genetics Center (CGC), details of which can be found
here: https://cgc.umn.edu/

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
