### ISSUE TITLE
  Hi I would like to submit some data t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5790]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi I would like to submit some data to Wormbase, I just wanted to follow up how to go about it. I have some sequence data (of alternatively spliced transcripts) as well as some expression data (from a translational GFP construct). <br/>Cheers, <br/>visitor_name</p>

**Reported by:** Kayl* (kayl******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50

**Comment by vanaukenk** [comment]
Hello Kayla,

thanks for contacting WormBase. Are the data you are planning to submit unpublished?
If so you can submit them through Micropublication:biology (the Principal Investigator of the lab should give his/her consent). 
The data will be sent out for peer-review and, if accepted, will receive a DOI (your data can be cited), will be published on Micropublication:biology, and will be included in WormBase.

Expression data can be submitted via this form. 
Please contact us directly at micropublications@wormbase.org for sequence data or if you need assistance with the expression data submission.

If this is not what you are planning to do, do not hesitate to get back to us with your alternative request.

Best regards,

Daniela


~~~~~~~~~
www.micropublicationbiology.org

**Comment by Paul-Davis** [comment]
Hi Kayla,

If you have submitted you alternative transcript sequence data to 
Genbank https://www.ncbi.nlm.nih.gov/genbank/submit/ then WormBase will 
automatically receive the sequence data as we sync worm data every 
month. If you give us the accession numbers we can prioritise them. If 
you haven't submitted your data to an INSDC partner database then we do 
encourage it for proper attribution, but we can always take your data 
directly,  the method is entirely up to you, Email 
(hinxton@wormbase.org) or if you can deposit the data on a public 
institute FTP site. Even if you have submitted your data and are 
awaiting it to be accepted please feel free to send it over directly.

Thank you for contacting us and offering to share your data.

Paul
Sequence curation.



On 28/07/2017 08:33, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi I would like to submit some data to Wormbase, I just wanted to 
> follow up how to go about it. I have some sequence data (of 
> alternatively spliced transcripts) as well as some expression data 
> (from a translational GFP construct).
> Cheers,
> Kayla
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5790. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5790>.
>
> Reported by: Kayla (kayla.venn@hotmail.com)
> 28 Jul 17 07:34
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.1.50 
> (KHTML, like Gecko) Version/10.0 Safari/602.1.50
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
Paul Davis
Senior Technical Officer [WormBase Bioinformatician]
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
