### ISSUE TITLE
  How do I find about  male C.elegan's ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5792]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find about  male C.elegan's sperms number when they mature?</p>

**Reported by:** samm*****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Sammy,

Thanks for writing to WormBase.

Upon reaching adulthood, C. elegans males have been reported to have between ~160 sperm.  However, during adulthood, the number continues to increase, with almost 300 sperm reported two hours after the adult molt.  

For more information, please see the paper by LaMunyon and Ward, specifically the section on sperm production:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1689481/pdf/9821364.pdf

Best,
--Kimberly Van Auken
