### ISSUE TITLE
  How do I align the protein sequence o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5795]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I align the protein sequence of the Necator americanus aspartyl protease APR 1 with potential ASP homologues from C.elegans?</p>

**Reported by:** Davi************* (dand**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by chris-grove** [comment]
From Michael:
"Hi David,

N.americanus should be in parasite.wormbase.org

I would first try to find out which one of the many N.americanus aspartyl proteases you would like to use and then either look up their respective C.elegans ortholog in the orthology section or if there is none, blast it against the C.elegans proteome.
Depending on what you want to do, you might even use multiple N.americanus proteins in your alignments.

Mcihael"
