### ISSUE TITLE
  How do I download sequence data from ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5797]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I download sequence data from JBrowse?  In GBrowse, I use "download decorated FASTA file" option. Am I missing something in JBrowse?<br/>Thanks!</p>

**Reported by:** Ben (benj************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by chris-grove** [comment]
Hi Ben,


Yes, downloading sequence from JBrowse is much different than GBrowse. I've made a screen capture video showing how this can be done:


https://dl.dropboxusercontent.com/u/4290782/WormBase/Retrieving_sequence_from_JBrowse.mov


1) First, you can turn on the "Reference sequence" track, click on the track title and "Save track data" in the form of a FASTA download; you can zoom to your region of interest first, as the download will include sequence for the region you are currently viewing.


2) Second, if you're interested in sequences for a particular gene, turn on the "Curated genes (protein coding)" track, right-click on the gene model, and click on "View Sequence" to open a sequence display box for the gene. From there, you can specify if you want to highlight coding regions, exons or introns, etc. You can also hide sequence, e.g. introns, from view and just copy and paste your sequence of interest. You can also include upstream and downstream sequence if desired.


I hope that helps.


Best,


Chris Grove

WormBase Help Desk
