### ISSUE TITLE
  Please correct the reference for the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5798]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Please correct the reference for the aph-2 gene - the paper that characterizes this gene, first published its sequence, and the phenotype of the zu181 allele (and a few others):<br/>aph-2 encodes a novel extracellular protein required for GLP-1-mediated signaling.Goutte C, Hepler W, Mickey KM, Priess JR.<br/>Development. 2000 Jun;127(11):2481-92.  PMID: 10804188<br/>Strangely, this obvious reference is completely missing from the main page of the aph-2 gene (I'm almost certain it used to be there).<br/>The "Draper 1996" paper that is referenced has NOTHING to do with the aph-2 gene, so please remove that reference.<br/>There is also a second paper that further characterizes the aph-2 phenotype, that also should be added to the page:<br/>APH-2/nicastrin functions in LIN-12/Notch signaling in the Caenorhabditis elegans somatic gonad.<br/>Levitan D, Yu G, St George Hyslop P, Goutte C.<br/>Dev Biol. 2001 Dec 15;240(2):654-61.  PMID: 11784090<br/>Thank you for making these corrections,<br/>visitor_name<br/>Amherst College</p>

**Reported by:** Caro*********** (cego****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/537.86.7

**Comment by vanaukenk** [comment]
Dear Caroline,

Thanks for writing to WormBase.

I've reviewed the aph-2 gene page and the information contained on some of the widgets.

For the aph-2 concise description, I've switched this over to use our automated description, generated from various sources of primary data curation in WormBase.  This new description, which cites many more aph-2 references, will be available starting with the WS262 release.

Also, under the references widget, I did confirm that the 2000 Development paper is listed.

For the zu181 variation page, I will defer to my colleagues who curate variation data to make all necessary updates to the references on that page.

Please let us know if you'd like any additional updates.

Best,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
References have been updated for the zu181 variation.  Draper et al., 1996 was removed, and Goutte et al., 2000 and Levitan et al., 2001 added.
