### ISSUE TITLE
  Hi There, I would like to know how to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5811]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi There, I would like to know how to download the entire transgene dataset so that I can compare it to a list of ~ 500 genes that show ageing related changes in expression. Ideally, we want to work out which genes of interest already have transcriptional reporters available for them and which ones we would need to construct. </p>

**Reported by:** Dhav******** (dhav***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by chris-grove** [comment]
Hello Dhavel,


 We don't currently have a ready-made file to download this info, but I've dumped transgene, construct, and strain data from the WS261 release (latest) of WormBase and attaching it to this email. You'll likely want to look at the "WS261_constructs_and_info" spreadsheet first, as it is the construct class that refers to the gene (or more precisely the gene's promoter) that is driving expression in the transgene. The gene that is driving expression will be listed in the "Driven by gene" column of the constructs file. From there you can narrow down the list of constructs, and thus transgenes, that you are interested in. The strains file contains all strains that are available at the CGC that have a transgene, and the respective transgene(s) they contain. Here's the CGC website where you can order strains:


https://cgc.umn.edu/


Let us know if you have any further questions.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
From user:
"Hello Chris,

Thank you so much for the files you sent me, this will make our target selection pipeline a lot more efficient.

Cheers,

Dhaval"
