### ISSUE TITLE
  Hi 2 questions. 1) I haven't logged o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5812]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>2 questions.<br/>1) I haven't logged on for quite a while and now can't seem to do so even after changing my pwd several times. Can you help?<br/>2) I've closed my lab and have a couple of Leica stereo microscopes I'd like to sell to help fund a new lab I'm starting (yeast genetics). Would it be OK to post an ad for these on the forum?<br/>Colin</p>

**Reported by:** Coli********* (coli*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

**Comment by chris-grove** [comment]
Hi Colin,

 One of our web developers will get back to you about issues regarding logging in to WormBase. If you don't have much saved in your current account, you may want to consider logging in with Google or Facebook. If you have an account with either, it's a convenient way to login in and I believe that process is working robustly. The developers can give you more clarity on that issue though.

As for posting an ad to sell your microscopes, I don't see why not, but let me consult with the other team members and get back to you.

Best,

Chris Grove
WormBase Help Desk

**Comment by chris-grove** [comment]
Have communicated with user on both issues. Closing
