### ISSUE TITLE
  Hi, Is there a way to use BLAST for b...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5813]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>Is there a way to use BLAST for batch queries? So, I have ~100 peptide sequences and I want to search for each of them for homologous C.elegans genes. I do not want to manually enter each sequence to https://www.wormbase.org/tools/blast_blat. Is there a way to enter those sequences using a code and get the resulting C.elegans genes and e-values in a .csv file?</p>

**Reported by:** Safi******** (safi********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by epaule** [comment]
while you can put multiple fasta sequences into the query, I would recommend using the NCBI blast+ commandline tool (https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs&DOC_TYPE=Download) for large batch queries.
You can get the C.elegans protein sequences from the download section of http://www.wormbase.org/species/c_elegans , as BLAST  needs them locally. But make sure to have a look at the command line options to set p-value cutoffs, filtering and output format.
Also blast has actually a tabular output format, which makes parsing the output easier.
