### ISSUE TITLE
I'm not able to access the FTP server. Is it down?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5816]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'm not able to access the FTP server. Is it down?

**Reported by:** Eyal (ebd@********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all#1--10">http://www.wormbase.org/species/all#1--10</a>
**Browser:** Chrome 60.0.3112.90

**Comment by draciti** [comment]
Hi Eyal,


Thanks for contacting WormBase.

I can successfully access the FTP server. Would you give it another try? Try to connect as 'Guest' in case 'Registered User' give you problems.


Let us know.

Thanks,

Daniela


HelpDesk Officer

________________________________

**Comment by draciti** [comment]
From user:
Oh, just noticed that ensembl ftp isn't working either. Must be a problem on my end. Sorry!
