### ISSUE TITLE
Hi 
I would like to use modencode and look for the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5817]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi 
I would like to use modencode and look for the PQM-1 binding sites in genome in C elegans. I need some help in how to visualize modencode.

**Reported by:** mali** (mail******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 59.0.3071.115

**Comment by chris-grove** [comment]
Hello Malini,


 You can use either of our genome browsers, GBrowse or JBrowse, to view the ChIP-Seq data tracks for PQM-1 binding sites. You can also download the track data as Wiggle plot data/peak data or as GFF, if that's what you're looking for. We would be happy to help you with that.


Are you looking for something else?


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Hi Christian,

Many thanks for the response. I am not a bioinformatician so Is there
a simple way like list of regions that PQM-1 binds to in a table
format.
I am not sure how to track from the data sets

Thanks
Malini

**Comment by chris-grove** [comment]
Hi Malini,

OK, I've created a screen capture video demonstrating how you can get a list/table of PQM-1 binding sites:

https://dl.dropboxusercontent.com/u/4290782/WormBase/Getting_list_of_PQM-1_binding_sites.mov

I would recommend using the "PQM-1 Combined (GFP ChIP)" or "PQM-1 Combined (GFP ChIP) recalled peaks", the latter being a bit more stringent in terms of peak calling. Note that there's an issue with downloading all of the track data for the entire genome at once, so you'll need to download the data one chromosome at a time. The output file you should be able to import into Excel or some other spreadsheet program. The first column is the chromosome number/name, the second column is the genomic coordinate of the start of the peak, the third column is the genomic coordinate of the end of the peak, and the fourth column is, I believe, the q-value of the peak call. The q-value will often appear as zero in the output file, I think if the value is less than 0.0001.

I hope that helps.

Chris
