### ISSUE TITLE
  How can i get the numbers for "FPKM e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5822]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can i get the numbers for "FPKM expression data from selected modENCODE libraries" graphs shown on the worm base for a large gene set?  <br/>Thanks</p>

**Reported by:** Alpe****** (aa74***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by gw3** [comment]
Alper,

It's not easy for you to get this.
If you send me your list of Gene IDs, I'll give you a csv file of the 
values for the life-stages of each gene.

Gary Williams

**Comment by draciti** [comment]
Hi Gary, any update on this? Did the user reach out to you? Please close if resolved. thx

**Comment by gw3** [comment]
The user said they would get back to me with a list of genes.
They have not been in touch since.
This issue will be reopened if they ever reply.
