### ISSUE TITLE
  Dear Sir/Madam, I am a researcher fro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5824]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam, I am a researcher from Argentina working on c.elegans.<br/>We have made several strains here, and would like to have a strain name for each of them. As the lab is quite new, we still do not have a two or three letter code for the strains. Would like to know what is the process to obtain it.<br/>Best<br/>Diego.</p>

**Reported by:** Dieg******* (dray***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by Paul-Davis** [comment]
Dear Diego,

Thank you for contacting WormBase, I am CCing the Worm Gene Nomenclature 
Committee who will be able to help you get a code.

All the best.

Paul


On 23/08/2017 12:59, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Dear Sir/Madam, I am a researcher from Argentina working on c.elegans.
> We have made several strains here, and would like to have a strain 
> name for each of them. As the lab is quite new, we still do not have a 
> two or three letter code for the strains. Would like to know what is 
> the process to obtain it.
> Best
> Diego.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5824. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5824>.
>
> Reported by: Diego Rayes (drayes@criba.edu.ar)
> 23 Aug 17 12:00
>
> Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Diego,

Further to my colleague Paul's email, I am writing to inform you that
Tim Schedl who is responsible for assigning laboratory codes is away
at the moment.
It would be preferable if you could wait for his return, but if you
need the codes urgently (e.g. in order to submit a paper to a
journal), then please write back to me.

Best wishes,

Mary Ann

On 23 August 2017 at 13:02, Paul Davis <paul.davis@wormbase.org> wrote:
>
> Dear Diego,
>
> Thank you for contacting WormBase, I am CCing the Worm Gene Nomenclature
> Committee who will be able to help you get a code.
>
> All the best.
>
> Paul
>
>
>
> On 23/08/2017 12:59, no-reply@wormbase.org wrote:
>
> How Do I ...?
>
>   Dear Sir/Madam, I am a researcher from Argentina working on c.elegans.
> We have made several strains here, and would like to have a strain name for
> each of them. As the lab is quite new, we still do not have a two or three
> letter code for the strains. Would like to know what is the process to
> obtain it.
> Best
> Diego.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5824. Follow progress on our
> issue tracker.
>
> Reported by: Diego Rayes (drayes@criba.edu.ar)
> 23 Aug 17 12:00
>
> Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
> --
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by Paul-Davis** [comment]
Dear Mary Ann,
thank you for your reply.
We can wait as we are going to submit a paper but not before mid september.
Best,

Diego

**Comment by tuli** [comment]
Dear Diego,

Further to Tim's email I would like to confirm that I have added the OAR
and nba codes to WormBase. This update will be available in release WS262.

Best wishes,

Mary Ann

On 25 August 2017 at 18:46, Schedl, Tim <ts@wustl.edu> wrote:

> Hi Diego,
>
>
> The OAR Laboratory/strain and “nba” Allele designations are available and
> are now yours.
>
>
> This information will appear on your Laboratory and Person pages in an
> upcoming release of WormBase.
>
>
> Tim
>
>
> ------------------------------
> *From:* Diego Rayes <drayes@criba.edu.ar>
> *Sent:* Friday, August 25, 2017 12:22 PM
> *To:* Schedl, Tim
> *Cc:* genenames WormBase
> *Subject:* [wormbase-genenames] Re: Laboratory/strain and Allele
> designations
>
> Hi Tim,
> Thank you for the lab/strain list.
>
> Our designation willl be:
>
> -Strain: OAR
> -allele: nba
>
> Contact information:
> Diego Rayes
> INIBIBB-CONICET
> Bahía Blanca
> Argentina
>
> I also sent the request to join the Worm Board.
>
> Thank you!
>
> Diego.
>
> On 25/8/2017 2:08 p. m., Schedl, Tim wrote:
>
> Hi Diego,
>
>
> Thank you for contacting WormBase for Laboratory/strain and Allele
> designations
>
>
> Below is a list of Laboratory/strain designations (all CAPs) that are
> currently in use ----- please choose a designation that is not on the
> list.  (Designations ending in I or O are disallowed)
>
> If you are making mutations of any type, or transgenic lines, then you
> also need an Allele designation.
> Below that is a list of Allele designations (all lower case) that are
> currently in use ----- please choose a designation that is not on the
> list.  (Designations ending in i, l or o are disallowed, as is *single*
> letter c)
>
> For administrative reasons, the CGC wants the designations for
> Laboratory/strain and Allele to be different - so choose distinct
> designations.
>
> Please advise on your choices.
>
>
> Please also provide the contact information that you want on your
> Laboratory and Person pages.
>
> As a new Laboratory Head, you are invited to join a low-traffic,
> announcement only mailing list from the Worm Board. You can read more about
> the purpose of the Worm Board on the WormBase Blog (
> http://blog.wormbase.org/2015/12/18/call-for-nominations-for-a-worm-board/
> Call for nominations for a Worm Board - The Blog
> <http://blog.wormbase.org/2015/12/18/call-for-nominations-for-a-worm-board/>
> blog.wormbase.org
> Dear Worm Community, Following discussions at the 2015 International Worm
> Meeting it is apparent that there is a need for a group to support
> community resources and ...
>
> ). You can request to join the group here:
>
> https://groups.google.com/a/wormbase.org/forum/#!forum/labheads
>
>
> Thank you,
>
> Tim
> ------------------------------------------------------------
> ------------------------------------------------------------
> ----------------------
>
>
> ASSIGNED CAENORHABDITIS GENETICS CENTER STRAIN DESIGNATIONS
> (Designations ending in I or O are disallowed)
> 2-LETTER CODES:
> -----------------------------------------------------------------------
> AA AB AC AD AE AF AG AH AJ AK AL AM AN AP AQ AR AS AT AU AV AW AX AY AZ
> BA BB BC BD BE BF BG BH BJ BK BL BM BN BP BQ BR BS BT BU BV BW BX BY BZ
> CA CB CC CD CE CF CG CH CJ CK CL CM CN CP CQ CR CS CT CU CV CW CX CY CZ
> DA DB DC DD DE DF DG DH DJ DK DL DM DN DP DQ DR DS DT DU DV DW DX DY DZ
> EA EB EC ED EE EF EG EH EJ EK EL EM EN EP EQ ER ES ET EU EV EW EX EY EZ
> FA FB FC FD FE FF FG FH FJ FK FL FM FN FP FQ FR FS FT FU FV FW FX FY FZ
> GA GB GC GD GE GF GG GH GJ GK GL GM GN GP GQ GR GS GT GU GV GW GX GY GZ
> HA HB HC HD HE HF HG HH HJ HK HL HM HN HP HQ HR HS HT HU HV HW HX HY HZ
> IA IB IC ID IE IF IG IH IJ IK IL IM IN IP IQ IR IS IT IU IV IW IX IY IZ
> JA JB JC JD JE JF JG JH JJ JK JL JM JN JP JQ JR JS JT JU JV JW JX JY JZ
> KA KB KC KD KE KF KG KH KJ KK KL KM KN KP KQ KR KS KT KU KV KW KX KY KZ
> LA LB LC LD LE LF LG LH LJ LK LL LM LN LP LQ LR LS LT LU LV LW LX LY LZ
> MA MB MC MD ME MF MG MH MJ MK ML MM MN MP MQ MR MS MT MU MV MW MX MY MZ
> NA NB NC ND NE NF NG NH NJ NK NL NM NN NP NQ NR NS NT NU NV NW NX NY NZ
> OA OB OC OD OE OF OG OH OJ OK OL OM ON OP OQ OR OS OT OU OV OW OX OY OZ
> PA PB PC PD PE PF PG PH PJ PK PL PM PN PP PQ PR PS PT PU PV PW PX PY PZ
> QA QB QC QD QE QF QG QH QJ QK QL QM QN QP QQ QR QS QT QU QV QW QX QY QZ
> RA RB RC RD RE RF RG RH RJ RK RL RM RN RP RQ RR RS RT RU RV RW RX RY RZ
> SA SB SC SD SE SF SG SH SJ SK SL SM SN SP SQ SR SS ST SU SV SW SX SY SZ
> TA TB TC TD TE TF TG TH TJ TK TL TM TN TP TQ TR TS TT TU TV TW TX TY TZ
> UA UB UC UD UE UF UG UH UJ UK UL UM UN UP UQ UR US UT UU UV UW UX UY UZ
> VA VB VC VD VE VF VG VH VJ VK VL VM VN VP VQ VR VS VT VU VV VW VX VY VZ
> WA WB WC WD WE WF WG WH WJ WK WL WM WN WP WQ WR WS WT WU WV WW WX WY WZ
> XA XB XC XD XE XF XG XH XJ XK XL XM XN XP XQ XR XS XT XU XV XW XX XY XZ
> YA YB YC YD YE YF YG YH YJ YK YL YM YN YP YQ YR YS YT YU YV YW YX YY YZ
> ZA ZB ZC ZD ZE ZF ZG ZH ZJ ZK ZL ZM ZN ZP ZQ ZR ZS ZT ZU ZV ZW ZX ZY ZZ
>
>
>
> 3-LETTER CODES:
> ABA ABR ABY ABZ ACH ADS AEB AEK AFS AGC AGD AGF AGG AGK AGP AGR AHS AJP AKA
> AKK AKR ALF ALM ALS AMF AMG AMH AMJ AML AMM AMS ANA ANF ANM ANR AOK APD
> APP APR APS APW ARF ARM ARP ASM ATD ATG ATH ATL ATR AUM AUW AVB AVG AVS
> AWK AWR AYE
> BAB BAD BAN BAR BAT BAY BBB BCN BCW BEG BEL BER BFF BHL BIG BIJ BJD BJH
> BJS BLC BLW BOL BOP BOX BRF BRC BSS BTJ BTP BWU BXN BYU
> CAK CAL CAU CBC CDH CEC CER CEW CFB CFC CFJ CGC CHB CHC CHL CHN CHP CLA
> CLB CLD CLP CMD CMH CMJ CNQ COP CPB CPV CRB CRR CSM CSS CTD CUP CUU CVB
> DAG DAH DAM DCD DCL DCR DDH DDK DDP DET DIM DIV DJK DJN DJR DKT DLM DLW
> DMH DMR DMS DOM DPX DQM DRK DRW DUD DUP DVG DWF DWP DYG
> EAB EAG EAH EAK ECA ECD EDC EEG EEV EFS EGD EHC EJP EJR EKM EKN ELG EMM
> ENL EPH ERC ERL ERT ESZ EVG EVL EZE
> FAD FAM FAS FCS FED FDU FDX FGP FJH FJJ FUH
> GAL GBG GCP GCU GIN GJH GKC GLS GMC GMD GNE GOT GOU GRN GSH GSX GUN GWJ GMW
> GNW GXW
> HAH HAL HBC HBR HZB HCC HCL HCX HDW HFW HGA HIW HJZ HKK HML HMT HMZ HNC
> HRN HRT HRW HSD HST HTN HTU HUJ HUS
> IBP IBW ICF IFM IFP IMN INV IPE IRB IWM
> JAB JAC JAS JAZ JBC JBL JCB JCC JCM JCP JCW JDH JDK JDL JDU JDW JED JEK
> JEL JEP JES JFM JGG JHU JIM JIN JIP JJA JKA JKM JLF JLG JMT JNC JPC JPL
> JPM JPS JRK JRM JRP JRS JRW JSD JSR JUP JVR
> KAE KAG KAL KAM KAN KCG KDK KHA KHK KHR KIR KJP KLJ KLS KME KMW KPU KRA
> KRD KRN KRY KUH KWN KXK
> LBV LEN LHU LIB LIU LKC LKJ LKW LMN LMW LNP LRB LRL LSC LSD LSJ LTM LTY
> LUA LWA LWZ
> MAB MAC MBA MAE MAD MAH MAJ MAM MAS MAV MBK MBM MCJ MCP MCR MCW MDH MDX
> MED MEG MEV MGH MGL MHB MHE MHL MIA MIR MJS MJB MJF MJW MKC MKV MLC MLG
> MLM MLU MLY MMA MMH MNN MOC MOL MOT MQD MRM MRP MRS MSB MSC MSD MSH MSN
> MSU MTM MTS MTU MVG MWP MYP MZE
> NAA NAM NAV NBR NES NFB NKZ NIC NIK NIN NIS NKC NLL NOA NPR NTC NUJ NVK
> NWG NYL
> OCF OCY OEB OIC OIK OKA OLB OLS OMG ONA OTL
> PAB PAS PAZ PDL PFR PHX PIR PJK PJP PKL PKR PLD PLS PNG PMB PMD PMW POL
> POM PRB PRJ PSY PTM PTN PVH PVX
>
> QDZ ->
> RAB RAC RAF RBG RBW RCH RCT RDV REB RED RER RFK RGD RIE RJM RJP RLH RMR
> ROG RPF RPW RSL RSN RTD RUX RVM RWK RZB
> SAH SAL SAN SAR SAY SBG SBL SBP SBW SCB SCH SCL SCS SDW SEE SEH SFT SGA SGC
> SGP SGR SHG SHK SHX SJL SJZ SKC SKP SLP SLS SLR SMD SMS SMW SNK SNU SOU
> SOZ SPC SPN SPU SQC SRS SRU SSM SSP SSR STA STE STR SUN SVQ SWD SWF SWG SYD
> SYS
> TAM TBD TCB TEE TGF TKB TLG TMB TMD TMG TMR TOG TOL TRG TRZ TSK TTV TWL
> TWN TWP TXL
> UDE UGR UHN UMT UOT UQM USC UTA UTR UTK
> VAG VBS VDL VEP VER VIG VIL VPR VVR VWL
> WAL WAW WBF WBM WBX WCH WDC WDY WEH WEN WFK WHA WHE WJA WKB WLP WLZ WMM
> WON WRM WSR WUM WWZ WYY
> XHX XIL XMN XSW XWZ
> YAA YAN YAR ZAS YBT YEW YHS YQL YMW YOS YUW
> ZAM ZHU ZIB ZIM ZOU ZPL ZPW ZTH ZXW ZZY
>
>
>
>
>
> ASSIGNED CAENORHABDITIS GENETICS CENTER ALLELE DESIGNATIONS
> (Designations ending in i, l or o are disallowed, as is *single* letter c)
> 2-LETTER CODES:
> ------------------------------------------------------------------------
> a  aa ab ac ad ae af ag ah aj ak am an ap aq ar as at au av aw ax ay az
> b  ba bb bc bd be bf bg bh bj bk bm bn bp bq br bs bt bu bv bw bx by bz
> -  ca cb cc cd ce cf cg ch cj ck cm cn cp cq cr cs ct cu cv cw cx cy cz
> d  da db dc dd de df dg dh dj dk dm dn dp dq dr ds dt du dv dw dx dy dz
> e  ea eb ec ed ee ef eg eh ej ek em en ep eq er es et eu ev ew ex ey ez
> f  fa fb fc fd fe ff fg fh fj fk fm fn fp fq fr fs ft fu fv fw fx fy fz
> g  ga gb gc gd ge gf gg gh gj gk gm gn gp gq gr gs gt gu gv gw gx gy gz
> h  ha hb hc hd he hf hg hh hj hk hm hn hp hq hr hs ht hu hv hw hx hy hz
> -  ia ib ic id ie if ig ih ij ik im in ip iq ir is it iu iv iw ix iy iz
> j  ja jb jc jd je jf jg jh jj jk jm jn jp jq jr js jt ju jv jw jx jy jz
> k  ka kb kc kd ke kf kg kh kj kk km kn kp kq kr ks kt ku kv kw kx ky kz
> -  la lb lc ld le lf lg lh lj lk lm ln lp lq lr ls lt lu lv lw lx ly lz
> m  ma mb mc md me mf mg mh mj mk mm mn mp mq mr ms mt mu mv mw mx my mz
> n  na nb nc nd ne nf ng nh nj nk nm nn np nq nr ns nt nu nv nw nx ny nz
> -  oa ob oc od oe of og oh oj ok om on op oq or os ot ou ov ow ox oy oz
> p  pa pb pc pd pe pf pg ph pj pk pm pn pp pq pr ps pt pu pv pw px py pz
> q  qa qb qc qd qe qf qg qh qj qk qm qn qp qq qr qs qt qu qv qw qx qy qz
> r  ra rb rc rd re rf rg rh rj rk rm rn rp rq rr rs rt ru rv rw rx ry rz
> s  sa sb sc sd se sf sg sh sj sk sm sn sp sq sr ss st su sv sw sx sy sz
> t  ta tb tc td te tf tg th tj tk tm tn tp tq tr ts tt tu tv tw tx ty tz
> u  ua ub uc ud ue uf ug uh uj uk um un up uq ur us ut uu uv uw ux uy uz
> v  va vb vc vd ve vf vg vh vj vk vm vn vp vq vr vs vt vu vv vw vx vy vz
> w  wa wb wc wd we wf wg wh wj wk wm wn wp wq wr ws wt wu wv ww wx wy wz
> x  xa xb xc xd xe xf xg xh xj xk xm xn xp xq xr xs xt xu xv xw xx xy xz
> y  ya yb yc yd ye yf yg yh yj yk ym yn yp yq yr ys yt yu yv yw yx yy yz
> z  za zb zc zd ze zf zg zh zj zk zm zn zp zq zr zs zt zu zv zw zx zy zz
>
>
>
> 3-LETTER CODES:
> aaa aab aar aat abc aby ach ade aea aeb afa aij aka akr ala alp alx ant
> apd ana aot apr ard arm arp art asc asd asr ast atn atr aug aus avb axr,
> azr
> bab baf bar bas bch bcm bet bfy bgg bgu bic bid biu bkn blc blm bln blt bmn
> bon bop bos bru brz bst
> cam can cas cau caz cbc cbd cbg ccc ccy cdb cen cer cgb cgu chp chr chs chu
> cim cin cip ciu cjn cld cle cmp cnj cny crg crk crr crs cwr csb csf csh
> csn csu cue cur cws cuw cwu cyd
> dah dcr ddh dec del den dev dhb dhk djr dkt dma dom dot drc drg drj drp
> drx dud due duk dus
> ean eav ecu eee egx ehc ejd ele elf elg elu emc enj eor epa epf erb ers
> etc eth ety evm
> fau fda fer fgp fhc fin fjj fkt flv fox fra frm ftw fun
> gaa gab gcu gda gec gee ges gin glm gls gmc gnv goe gos gre gtg gva gxw
> han hat hav haw hbn hca hcf hdw heb hen his hjd hkd hku hmn hmr hop hrt hzt
> hua hub huj hus hut hzh
> iam ibb icb ibp ice icv ihk ijm ijp imp ind iow iub ivy iwf iwt lzq
> jaa jah jam jar jaz jbc jbm jcc jcp jdc jdk jep jer jgr jhu jin jlg jlb
> jlu jpn jrs jrw
> kag kah kam kap kar kas kaz kbs kea ken ker key kez kis kjr kku kln kmh
> knj knu kor kpd kry ksh kst ksu ktn kun kyt
> lab lac lad lan lax lcs ldr lea lfc lib liz los lot lpg lsk lst lsu ltm luc
> lyn
> maa mac mad mam mar mat mau maz mbd mcg mch mcj mcr mer mew mfd mgm mgw
> mhs mib mic mid mik mir miz mja mjy mkc mks mla mlg mmm mnh mnn mnt mon
> mop mor mpg mpt mrm mrs msk msn msu mud mut mvp mwu mxc myp myr mzm
> naa nap nar nat nct nds ndz nkz nib nna noa nor npb nth ntu nwr nyc nyg
> ocb ocf ocu ogr okz ola ole ons opy osa osk otn
> pas pav pcc pdr pdu pee pek pet pig pir pjp pmc pmn pok pra prt ptn
> qbc qef
> raj ram raw rax rdv red rem res rga ris rms rny roc rog rov rrr rux rzv
> sag saj sal sam san sar sas sbg sbj sbw scr scu sda sea ses sev sgp shc shr
> sht shy sic sks sky slc slv smb sml snx som sos spr sra srf srh ssd ssp ssr
> sta ste stj stn sun stx svq syb syd syn syr
> tag tak tau tcn tdc tem tex thm thu tmg ton tpe trc tur twn txu
> uab uae ubs ucc ucr uge uia ukc ula ulb ulv umn ums und unr uon uos uot
> upp ups ury usc ust utd uth utk utr uts uus uvw uwa
> var vas vba ver vie vir viz vlc vlt vpr vua
> wac wam war wbf wbm wec wen wig win wit wle wlz wor wow wrd wrm wsg wsh
> wtf wue wur wvs wzp
> xch xix xmu xoe xwh
> yad yak yan yas ycx yes yfh yhw ykp ylw yok yph yrk yth yuq
> zap zax zen zhs zju zpa zuc zum zye zzy
>
>
>
> ------------------------------
>
> The materials in this message are private and may contain Protected
> Healthcare Information or other information of a sensitive nature. If you
> are not the intended recipient, be advised that any unauthorized use,
> disclosure, copying or the taking of any action in reliance on the contents
> of this information is strictly prohibited. If you have received this email
> in error, please immediately notify the sender via telephone or return mail.
>
>
> --
> --
> You received this message because you are subscribed to the "Wormbase:
> genenames" group.
> To post to this group, send email to genenames@wormbase.org
> To unsubscribe from this group, send email to
> genenames+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/genenames
> Google Groups <http://groups.google.com/a/wormbase.org/group/genenames>
> groups.google.com
> Google Groups allows you to create and participate in online forums and
> email-based groups with a rich experience for community conversations.
>
>
>
> ---
> You received this message because you are subscribed to the Google Groups
> "WormBase: genenames" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to genenames+unsubscribe@wormbase.org.
>
>
> ------------------------------
>
> The materials in this message are private and may contain Protected
> Healthcare Information or other information of a sensitive nature. If you
> are not the intended recipient, be advised that any unauthorized use,
> disclosure, copying or the taking of any action in reliance on the contents
> of this information is strictly prohibited. If you have received this email
> in error, please immediately notify the sender via telephone or return mail.
>
> --
> --
> You received this message because you are subscribed to the "Wormbase:
> genenames" group.
> To post to this group, send email to genenames@wormbase.org
> To unsubscribe from this group, send email to
> genenames+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/genenames
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Thank you Mary Ann!
