### ISSUE TITLE
  How do I interpret tissue names as an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5825]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I interpret tissue names as annotated in SimpleMine? For e.g. Body wall muscle cells and Body wall musculature; should the gene list tagged with these tissues be combined to get the list of genes expressed in Body wall muscle. Another example: what is the difference between pharynx and pharyngeal muslce cell?<br/>Another question: what is the difference between the following columns Expr_pattern Tissue and Expr_pattern LifeStage? </p><p>What were you doing? <br />&nbsp;&nbsp;I would like a list of genes which are expressed in a given tissue.</p>

**Reported by:** Chin********* (cjjo************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by raymond91125** [comment]
Hi Joshi,

It may be easier for you to get a list of gene expressed in a specific 
tissue by using the anatomy term ontology browser. For example, say 
you're interested in genes expressed in the pharynx, go to wormbase 
front page, select "for an anatomy term" from the drop down in top right 
search box, type in pharynx and hit the magnifying glass icon. You 
should be redirected to the pharynx anatomy page. Turn on the widget 
"Ontology Browser" on the left menu bar. You should see a tree-like list 
where "pharynx" is colored in green with numbers to the right. "5093 
gene products (1769 direct)" label means that there are 1769 genes 
directly annotated to pharynx (by expression data) and 5093 directly or 
indirectly. Indirectly means annotation is to any part of subtype of the 
pharynx, e.g. pharyngeal muscle cell. If you click on that, you'd be 
shown a new page with lists of gene names.

Cheers,

Raymond
