### ISSUE TITLE
  Hi I would like to obtain the complet...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5826]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>I would like to obtain the complete proteome of the latest annotation of C. elegans. <br/>But I would like to have only the longest isoform for each gene, and not all possible isoforms.<br/>How can I do this?<br/>Thank you in advance!<br/>Regards<br/>visitor_name</p>

**Reported by:** Wann********** (wann*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by draciti** [comment]
Hello Hinxton, 
can someone get back to Wannes? thanks

**Comment by Paul-Davis** [comment]
I have generated the peptide file and added it here:

[C.elegans_longest_peptide_gene.txt](https://github.com/WormBase/website/files/1260647/C.elegans_longest_peptide_gene.txt)

Emailing the user the location of the file.

Paul

**Comment by Paul-Davis** [comment]
Dear Wannes,

I have generated the peptide file you were after and added it to the 
help ticket that was created for you.

Ticket: https://github.com/WormBase/website/issues/5826

File: 
https://github.com/WormBase/website/files/1260647/C.elegans_longest_peptide_gene.txt

Thanks

Paul



closes #5826


On 24/08/2017 12:47, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi
> I would like to obtain the complete proteome of the latest annotation 
> of C. elegans.
> But I would like to have only the longest isoform for each gene, and 
> not all possible isoforms.
> How can I do this?
> Thank you in advance!
> Regards
> Wannes Dermauw
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5826. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5826>.
>
> Reported by: Wannes Dermauw (wannes.dermauw@ugent.be)
> 24 Aug 17 11:49
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Paul

I have one more question.

At the wormbase website, it is mentioned in the beginning of the C. elegans WS260 summary that there are 20222 protein coding genes, while a bit later, for the wormpep dataset there are 20219 protein coding loci.

Why is there a 3 gene difference?

Thank you in advance!

Regards

Wannes


C. elegans gene data (48328 genes in total)
----------------------------------------------

Protein-coding (20222 genes):
  Curated description         5143    (25.4%)
  Automated description      14801    (73.2%)
  Human disease association   1514     (7.5%)
  Approved Gene name          9985    (49.4%)
  Reference                  10942    (54.1%)
  RNAi results               18765    (92.8%)
  Microarray results         20133    (99.6%)
  Expression patterns        19908    (98.4%)
  Variations                 20217   (100.0%)
  Interaction data           15822    (78.2%)

Non-coding RNA and pseudogene (26560 genes):
  Curated description          200     (0.8%)
  Automated description       4103    (15.4%)
  Human disease association     15     (0.1%)
  Approved Gene name         16443    (61.9%)
  Reference                   5786    (21.8%)
  RNAi results                1194     (4.5%)
  Microarray results          1695     (6.4%)
  Expression patterns          551     (2.1%)
  Variations                 26518    (99.8%)
  Interaction data             438     (1.6%)

Uncloned (1546 genes):
  Curated description          786    (50.8%)
  Automated description        171    (11.1%)
  Human disease association     10     (0.6%)
  Approved Gene name          1500    (97.0%)
  Reference                   1117    (72.3%)
  RNAi results                   0     (0.0%)
  Microarray results             0     (0.0%)
  Expression patterns           17     (1.1%)
  Variations                  1183    (76.5%)
  Interaction data             120     (7.8%)



Wormpep data set:
----------------------------

There are 28237 CDSs, from 20219 protein-coding loci

The 28237 sequences contain 39063627 base pairs in total.

Modified entries      20
Deleted entries       37
New entries           77
Reappeared entries    3


Wannes Dermauw <http://scholar.google.be/citations?user=YApJYSsAAAAJ&hl=nl>, PhD
Laboratory of Agrozoology <http://www.agrozoology.ugent.be/>
Department of Crop Protection
Faculty of Bioscience Engineering, Ghent University
Coupure Links 653, B-9000 Ghent, Belgium
tel: ++32(0)92646155

> Op 29-aug.-2017, om 16:44 heeft Paul Davis <paul.davis@wormbase.org> het volgende geschreven:
> 
> 
> Dear Wannes,
> 
> I have generated the peptide file you were after and added it to the help ticket that was created for you.
> 
> Ticket: https://github.com/WormBase/website/issues/5826 <https://github.com/WormBase/website/issues/5826>
> 
> File: https://github.com/WormBase/website/files/1260647/C.elegans_longest_peptide_gene.txt <https://github.com/WormBase/website/files/1260647/C.elegans_longest_peptide_gene.txt>
> 
> Thanks
> 
> Paul
> 
> 
> 
> closes #5826
> 
>
