### ISSUE TITLE
  How do I get the whole database of va...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5829]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get the whole database of variation description for C. elegans, such as variation id and description? In download, I only found genome related information.</p><p>What were you doing? <br />&nbsp;&nbsp;For strain selection for research</p>

**Reported by:** YUE ** (Yue.**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by tuli** [comment]
Dear Yue Wu,

Thank you for writing to WormBase.

Please can you clarify what you mean by "variation description".
Do you mean the genotype of the strain carrying the variation e.g. for
EU1510 this would be "zyg-9(or634) II."
Or do you mean the Description/Remark associated with the strain e.g.
for EU1510 this would be "Temperature sensitive. Maintain at 15C. At
26C, animals give rise to 100% dead embryos, with embryos exhibiting
lack of pronuclear migration at the one-cell stage. At 15C, animals
give rise to viable progeny."

Or maybe something else?

I look forward to helping you further.

Mary Ann


On 26 August 2017 at 19:36,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   How do I get the whole database of variation description for C. elegans,
> such as variation id and description? In download, I only found genome
> related information.
>
> What were you doing?
>   For strain selection for research
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5829. Follow progress on our
> issue tracker.
>
> Reported by: YUE WU (Yue.Wu@uga.edu)
> 26 Aug 17 18:36
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML,
> like Gecko) Version/10.1.2 Safari/603.3.8
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by raymond91125** [comment]
No reply from the user?

**Comment by tuli** [comment]
Still ongoing. Thanks for prompt.

**Comment by tuli** [comment]
User is happy he has the data he needs in the gff
