### ISSUE TITLE
  Please update year on the copyright: ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5830]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Please update year on the copyright:<br/>WormBase is copyright © 1999-2015 California Institute of <br/>Technology, European Bioinformatics Institute, Ontario Institute <br/>for Cancer Research, Washington University at St. Louis, and <br/>The Wellcome Trust Sanger Institute. <br/>Permission to use the information contained in this database <br/>was given by the researchers/institutes who contributed or <br/>published the information. Users of the database are solely <br/>responsible for compliance with any copyright restrictions, <br/>including those applying to the author abstracts. Documents <br/>from this server are provided "AS-IS" without any warranty, <br/>expressed or implied. <br/>WormBase is supported by a grant from the National Human <br/>Genome Research Institute at the US National Institutes <br/>of Health # U41 HG002223 and the British Medical Research Council.</p>

**Reported by:** paul********** (pws@***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by sibyl229** [comment]
Copyright year is now updated. Closing.
