### ISSUE TITLE
On this page "http://www.wormbase.org/species/o_vo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5831]
*Help Desk query collected when no chat operators were online. Follow up required.*

On this page "http://www.wormbase.org/species/o_volvulus/transcript/OVOC5284#06178--10" 
I am looking at the expression analyses for the gene and don't seem to understand why there is a mean and a median whenit comes to this data

**Reported by:** Robe******** (shey*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/o_volvulus/transcript/OVOC5284#06178--10">http://www.wormbase.org/species/o_volvulus/transcript/OVOC5284#06178--10</a>
**Browser:** Firefox 55.0

**Comment by epaule** [comment]
if you click on the details below the numbers, you can see that, as example, the "total over all stages" is based on 22 data points therefore you get meaningful differences between median and average. In cases where N=1 there is of course no difference, but most have more than one data point.

The box plots below also show the spread of the data, so it becomes more obvious.
