### ISSUE TITLE
  release dates ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5834]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;release dates</p>

**Reported by:** khod**********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by raymond91125** [comment]
Top menu About -> Release Schedule.

Raymond
