### ISSUE TITLE
Could you help me to undestand the description ind...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5835]
*Help Desk query collected when no chat operators were online. Follow up required.*

Could you help me to undestand the description indicated in this strain? above all the meaning of Unc. 
( This descrption was indicated by the CGC)
Thanks 

Name	EU1    View On Wormbase
Species	C. elegans
Genotype	skn-1(zu67) IV/nT1 [unc-?(n754) let-?] (IV;V).
Description	Heterozygotes are Unc and segregate Unc, WT which give only dead eggs, and dead eggs. Maintain by picking Unc.

**Reported by:** Luis (llop*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/nomenclature#0ifjkag8b9h47625dce13--10">http://www.wormbase.org/about/userguide/nomenclature#0ifjkag8b9h47625dce13--10</a>
**Browser:** Chrome 60.0.3112.113

**Comment by raymond91125** [comment]
Hi Luis,

Unc indicates the observed phenotype 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000643#03--10>. 
If you would like to know more about balancers, see 
<http://www.wormbook.org/chapters/www_geneticbalancers/geneticbalancers.html>.

Thanks.

Raymond


On 07/09/17 04:19, no-reply@wormbase.org wrote:
> offline chat Could you help me to undestand the description indicated 
> in this strain? above all the meaning of Unc. ( This descrption was 
> indicated by the CGC) Thanks Name EU1 View On Wormbase Species C. 
> elegans Genotype skn-1(zu67) IV/nT1 [unc-?(n754) let-?] (IV;V). 
> Description Heterozygotes are Unc and segregate Unc, WT which give 
> only dead eggs, and dead eggs. Maintain by picking Unc.
>
> Submitted From:
>   http://www.wormbase.org/about/userguide/nomenclature#0ifjkag8b9h47625dce13--10 
> http://www.wormbase.org/about/userguide/nomenclature#0ifjkag8b9h47625dce13--10 
> <http://www.wormbase.org/http://www.wormbase.org/about/userguide/nomenclature#0ifjkag8b9h47625dce13--10> 
>
>
> This issue has been assigned ticket number: #5835. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5835>.
>
> Reported by: Luis (llopg10@gmail.com)
> 07 Sep 17 11:19
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
