### ISSUE TITLE
  I'd like to use the data for homolog ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5839]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'd like to use the data for homolog between C. elegans and other species(homo sapiens). I try use biomart, but it didn't contains all homolog I see on wormbase page. Is there any way to download the table for homolog of C elegans and human in wormbase?</p>

**Reported by:** Yue ** (Yue.**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by WenChenWormBase** [comment]
Yue, you should be able to find human homologs using SimpleMine:
http://www.wormbase.org/tools/mine/simplemine.cgi

The source data for SimpleMine can be downloaded from here:
ftp://caltech.wormbase.org/pub/wormbase/simpleMine/souceFileWS260/
