### ISSUE TITLE
 Server Error: 500 at  rest/widget/rearrangement/s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5840]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/rearrangement/sDf26/overview">rest/widget/rearrangement/sDf26/overview</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "http://datomic-to-catalyst-ws260.us-east-1.elasticbeanstalk.com/rest/widget/rearrangement/sDf26/overview failed with 500 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 919." </p><p>What were you doing? <br />&nbsp;&nbsp;just clicked on sDf26 and got this error message</p>

**Reported by:** Andy******* (andy*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//rest/widget/rearrangement/sDf26/overview">/rest/widget/rearrangement/sDf26/overview</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by sibyl229** [comment]
Hi @a8wright could you take a look at this 500 error on rearrangement overview please?

**Comment by a8wright** [comment]
This has now been fixed in production as well
