### ISSUE TITLE
Hi, how can I view earlier Wormbase releases? I th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5841]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, how can I view earlier Wormbase releases? I think something has changed for a gene I am working on with the WS260 release but I would like to be able to check on my own. Thanks.

--Jim

**Reported by:** Jim ********* (jlis**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide#0123456--10">http://www.wormbase.org/about/userguide#0123456--10</a>
**Browser:** Chrome 60.0.3112.113

**Comment by raymond91125** [comment]
Hi Jim,

We have a limited number of prior versions you could check, linked at 
the lower right corner of the front page "Data Freezes".

Hope that helps.

Raymond
