### ISSUE TITLE
there are 10 groups of ganglia in the worm. where ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5845]
*Help Desk query collected when no chat operators were online. Follow up required.*

there are 10 groups of ganglia in the worm. where can I find the neuron list in each ganglion.

**Reported by:** Mei (shid**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&amp;query=CAN">http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&amp;query=CAN</a>
**Browser:** MSEdge 15.15063

**Comment by raymond91125** [comment]
If you follow down the hierarchy in the Ontology Browser widget for the 
anatomy term "ganglion", you can find all the neurons for each.

Thanks.

Raymond


On 10/09/17 05:46, no-reply@wormbase.org wrote:
> offline chat there are 10 groups of ganglia in the worm. where can I 
> find the neuron list in each ganglion.
>
> Submitted From:
>   http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&query=CAN 
> http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&query=CAN 
> <http://www.wormbase.org/http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&query=CAN> 
>
>
> This issue has been assigned ticket number: #5845. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5845>.
>
> Reported by: Mei (shidongmei211314@gmail.com)
> 10 Sep 17 12:47
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
