### ISSUE TITLE
Geneservice Links need updating

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5849]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Where do I order fosmids and cosmids? The links to Geneservice do not take me anywhere</p>

**Reported by:** Dan  (dsc3**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Dan,

Thank you for contacting WormBase.

Updated information about ordering reagents is available here: 
http://www.wormbase.org/about/Frequently_asked_questions#b--10

I am having difficulty location the out of date information, would it be 
possible for you to send me the url where you are seeing Geneservice as 
these links should have been removed several years ago.

Thanks

Paul
[Sequence Curation]

On 12/09/2017 17:20, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Where do I order fosmids and cosmids? The links to Geneservice do 
> not take me anywhere
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5849. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5849>.
>
> Reported by: Dan (dsc38@duke.edu)
> 12 Sep 17 16:20
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/60.0.3112.113 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hello Paul,


Thank you for the quick reply!


Here are the URLs that I visited that told me to go to Geneservice:

http://www.wormbase.org/species/c_elegans/sequence/WRM0631dA02#04--10

http://www.wormbase.org/species/c_elegans/sequence/WRM061cE11#04--10

http://www.wormbase.org/species/c_elegans/sequence/WRM0641bG05#04--10


Thanks,

Dan

________________________________

**Comment by Paul-Davis** [comment]
Hi Dan,

Thank you for providing the links, we will get this resolved asap.

Paul



On 12/09/2017 17:35, Paul Davis wrote:
>
> Dear Dan,
>
> Thank you for contacting WormBase.
>
> Updated information about ordering reagents is available here: 
> http://www.wormbase.org/about/Frequently_asked_questions#b--10
>
> I am having difficulty location the out of date information, would it 
> be possible for you to send me the url where you are seeing 
> Geneservice as these links should have been removed several years ago.
>
> Thanks
>
> Paul
> [Sequence Curation]
>
> On 12/09/2017 17:20, no-reply@wormbase.org wrote:
>> How Do I ...?
>>
>>   Where do I order fosmids and cosmids? The links to Geneservice do 
>> not take me anywhere
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #5849. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/5849>.
>>
>> Reported by: Dan (dsc38@duke.edu)
>> 12 Sep 17 16:20
>>
>> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
>> like Gecko) Chrome/60.0.3112.113 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Webteam

Would it be possible to update the following link on the Sequence overview of WRM Fosmid clone pages.

http://www.wormbase.org/species/c_elegans/sequence/WRM0631dA02#046--10

![geneservice_error](https://user-images.githubusercontent.com/717707/30369379-347e1fae-986c-11e7-996e-e2be66a8789d.png)

The links should be pointing at this style of url:

https://www.sourcebioscience.com/search?s=WRM0631dA02&search=WRM0631dA02&tb=1&pr=10&ar=10&cc=12514781#tab1

Not pretty, but it gets us to the right page as it seems they have moved away from Don's original naming schema for their catalog.

Thanks

Paul

**Comment by Paul-Davis** [comment]
Geneservice is still appearing on the live site after a very long time, can we get these updated for WS262??

**Comment by sibyl229** [comment]
Hi @Paul-Davis  The GeneService link from sequence overview should be fixed now: http://staging.wormbase.org/species/c_elegans/sequence/WRM0631dA02#0465--10 

One thing to note: it's linking to the search result page on Source Bioscience website for now (WS262), instead of the link you provided: `https://www.sourcebioscience.com/search?s=WRM0631dA02&search=WRM0631dA02&tb=1&pr=10&ar=10&cc=12514781#tab1`, because I'd like to confirm with you if the `&tb=1&pr=10&ar=10&cc=12514781#tab1` part remains the same for every sequence ID. Also, that URL doesn't look like one that's designed to be linked to, which I think you already know :)

**Comment by Paul-Davis** [comment]
Hi @sibyl229, I think without a decent end point, what you have done is the best option.

Thanks
