### ISSUE TITLE
  I was wondering if there is a way to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5850]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was wondering if there is a way to pull down amino acid sequence files for a large number of select proteins?</p><p>What were you doing? <br />&nbsp;&nbsp;I am looking through transcriptome data trying to identify secreted proteins. If I have the amino acid sequences I can identify if they are secreted or not.</p>

**Reported by:** Dan (dsc3**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by raymond91125** [comment]
Hi Dan,

You can bulk download protein sequences using Tools -> Parasite BioMart. 
A sample query <https://goo.gl/uL5QbX>.

Cheers,

Raymond


On 12/09/17 15:31, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I was wondering if there is a way to pull down amino acid sequence 
> files for a large number of select proteins?
>
> What were you doing?
>   I am looking through transcriptome data trying to identify secreted 
> proteins. If I have the amino acid sequences I can identify if they 
> are secreted or not.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5850. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5850>.
>
> Reported by: Dan (dsc38@duke.edu)
> 12 Sep 17 22:31
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/60.0.3112.113 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Thank you very much, Raymond, this is exactly what I needed!


Dan

________________________________
