### ISSUE TITLE
  How do I download the RNAi pathway pr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5851]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I download the RNAi pathway protein sequences of C.elegans from Wormbase?</p>

**Reported by:** Huli** (huli**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 UBrowser/5.2.2603.25 Safari/537.36

**Comment by chris-grove** [comment]
Hello Hulili,


Unfortunately WormBase does not currently have a list of all genes involved in the RNAi pathway, so you'll need to assemble that list yourself from reviews and such. Once you have your list of genes, you can use either WormMine with this example query:


<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.CDSs.symbol Gene.CDSs.protein.symbol Gene.CDSs.protein.sequence.residues" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="C. elegans genes with a cell cycle variant - or descendant - allele phenotype as of WS257"/>
</query>

or you can use WormBase ParaSite BioMart with this example query:


http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.sequences.peptide|wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.external_gene_id&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."hlh-26,hlh-2,unc-3,hlh-30"&VISIBLEPANEL=resultspanel


In each case you'll need to supply your list of genes as input, but then you should be able to get the protein sequences for your list of genes.


Let us know if you have any questions or encounter any problems.


Best,


Chris Grove

WormBase
