### ISSUE TITLE
?PCR_product page link to Source BioScience needs updating

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5857]
Related to issue #5856 

On PCR product pages for Ahringer RNAi clones, like sjj_W02C12.3:

http://www.wormbase.org/species/all/pcr_oligo/sjj_W02C12.3#0--10

The "Reagent" field has "Source BioScience: IV-2C11" with URL link:

http://www.sourcebioscience.com/search?search=IV-2C11

which is resolving to:

https://www.sourcebioscience.com/search?search=IV-2C11&search=IV-2C11

which is a nonsense URL leading to a search for "IV-2C11" twice resulting in no matches. The URL should be updated to:

https://www.sourcebioscience.com/search?search=IV-2C11

which has the "https" instead of "http" which appears to be the problem.

Thanks!

**Comment by chris-grove** [comment]
Same issue exists on RNAi pages as well:

http://www.wormbase.org/species/c_elegans/rnai/WBRNAi00092856#01--10

See the Details widget link to Source BioScience. Changing the hyperlink from "http://" to "https://" should fix the problem.

**Comment by sibyl229** [comment]
Hi @chris-grove I think the link to Souce BioScience has been fixed: http://www.wormbase.org/species/all/pcr_oligo/sjj_W02C12.3#0--10

**Comment by chris-grove** [comment]
@sibyl229 
OK, the links look good now. Thanks Sibyl!
