### ISSUE TITLE
I am going to do cosmid rescue of mutant phenotype...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5860]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am going to do cosmid rescue of mutant phenotype. Can I have protocol of that? Do I have to microinject or feed them?

**Reported by:** Youm** (YouM*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006914#0-9gced4a-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00006914#0-9gced4a-10</a>
**Browser:** Chrome 61.0.3163.79

**Comment by chris-grove** [comment]
Duplicate of #5859
