### ISSUE TITLE
Transcript objects haven't merged properly in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5861]
I don't know whether this issue has been resolved in one of the WormMine development instances already, but there is an apparent problem with duplicate Transcript objects in the live WormMine, where one "copy" of a transcript object has a transcript sequence name (identical to the transcript sequence name of the other "copy"), a transcript length, a transcript WormMine ID (identical to the transcript sequence name), and a species (but no transcript method, no gene ID, no gene sequence name, and no gene name), and the second "copy" has the same transcript sequence name, a transcript WormMine ID prefixed with "Transcript:", a transcript method, a species, as well as a gene ID, a gene sequence name, and a gene name. As an example, you can perform the following query:

`<query name="" model="genomic" view="Transcript.symbol Transcript.length Transcript.primaryIdentifier Transcript.method Transcript.gene.primaryIdentifier Transcript.gene.secondaryIdentifier Transcript.gene.symbol Transcript.organism.name" longDescription="" sortOrder="Transcript.symbol asc">
  <join path="Transcript.gene" style="OUTER"/>
  <join path="Transcript.organism" style="OUTER"/>
  <constraint path="Transcript.symbol" op="=" value="Y110A7A.10.1"/>
</query>`

and get the following table of results:

![screen shot 2017-09-15 at 10 42 01 am](https://user-images.githubusercontent.com/611382/30488228-bf2227f2-9a03-11e7-8e8a-152a5bd6fb5f.png)

So, there's one copy of the transcript object that has a length and a species, but essentially no connection to a gene, and the other has a connection to a species and a gene, but has no length. This is similar to the problem we had been having with gene objects not merging properly. Maybe this has to do with the discrepancy in WormMine ID, e.g. "Y110A7A.10.1" versus "Transcript:Y110A7A.10.1"?

**Comment by nuin** [comment]
Seems a problem in the GFF pre-processing. I will check and work on a patch build. Thanks @chris-grove

**Comment by nuin** [comment]
Hi Chris, digging deeper I went to find the culprit in the database:


```
 secondaryidentifier | intermine_method  |    symbol    |    primaryidentifier    | lastupdated | length |   id    | name | scoretype | score | chromosomeid | chromosomelocationid | organismid | proteinid | sequenceid | sequenceontologytermid | geneid  |               class
---------------------+-------------------+--------------+-------------------------+-------------+--------+---------+------+-----------+-------+--------------+----------------------+------------+-----------+------------+------------------------+---------+------------------------------------
                     | Coding_transcript | Y110A7A.10.1 | Transcript:Y110A7A.10.1 |             |        | 9312448 |      |           |       |              |                      |    1000009 |           |            |                8000015 | 4000004 | org.intermine.model.bio.Transcript
                     |                   | Y110A7A.10.1 | Y110A7A.10.1            |             |   2351 | 7024975 |      |           |       |      7000002 |              7024974 |    1000009 |           |            |                7000011 |         | org.intermine.model.bio.MRNA
```

The important information here is the id `9312448`. Checking tracker, I see:

```
objectid |      fieldname       |     sourcename      | version
----------+----------------------+---------------------+---------
  9312448 | length               | wb-acedb-cds        |     135
  9312448 | name                 | wb-acedb-cds        |     135
  9312448 | protein              | wb-acedb-cds        |     135
  9312448 | sequence             | wb-acedb-cds        |     135
  9312448 | primaryIdentifier    | wb-acedb-cds        |     135
  9312448 | scoreType            | wb-acedb-cds        |     135
  9312448 | secondaryIdentifier  | wb-acedb-cds        |     135
  9312448 | chromosome           | wb-acedb-cds        |     135
  9312448 | lastUpdated          | wb-acedb-cds        |     135
  9312448 | score                | wb-acedb-cds        |     135
  9312448 | chromosomeLocation   | wb-acedb-cds        |     135
  9312448 | method               | wb-acedb-transcript |     115
  9312448 | length               | wb-acedb-transcript |     115
  9312448 | name                 | wb-acedb-transcript |     115
  9312448 | protein              | wb-acedb-transcript |     115
  9312448 | sequence             | wb-acedb-transcript |     115
  9312448 | primaryIdentifier    | wb-acedb-transcript |     115
  9312448 | scoreType            | wb-acedb-transcript |     115
  9312448 | organism             | wb-acedb-transcript |     115
  9312448 | secondaryIdentifier  | wb-acedb-transcript |     115
  9312448 | chromosome           | wb-acedb-transcript |     115
  9312448 | lastUpdated          | wb-acedb-transcript |     115
  9312448 | score                | wb-acedb-transcript |     115
  9312448 | chromosomeLocation   | wb-acedb-transcript |     115
  9312448 | symbol               | wb-acedb-transcript |     115
  9312448 | method               | wb-acedb-gene       |      88
  9312448 | length               | wb-acedb-gene       |      88
  9312448 | name                 | wb-acedb-gene       |      88
  9312448 | protein              | wb-acedb-gene       |      88
  9312448 | sequence             | wb-acedb-gene       |      88
  9312448 | primaryIdentifier    | wb-acedb-gene       |      88
  9312448 | id                   | wb-acedb-gene       |      88
  9312448 | scoreType            | wb-acedb-gene       |      88
  9312448 | sequenceOntologyTerm | wb-acedb-gene       |      88
 9312448 | organism             | wb-acedb-gene       |      88
  9312448 | secondaryIdentifier  | wb-acedb-gene       |      88
  9312448 | chromosome           | wb-acedb-gene       |      88
  9312448 | lastUpdated          | wb-acedb-gene       |      88
  9312448 | score                | wb-acedb-gene       |      88
  9312448 | chromosomeLocation   | wb-acedb-gene       |      88
  9312448 | symbol               | wb-acedb-gene       |      88
  9312448 | gene                 | wb-acedb-gene       |      88
```

meaning that this transcript was created by the gene load step. Grepping things in the data directory, we see

```
im-dev1 :: ip-10-0-1-221 :: data2/intermine/datadir ‹im-260-dev*› % grep -r "Transcript:Y110A7A.10.1" *
wormbase-acedb/cds/XML/prepped_CDS.xml:      <Transcript>Transcript:Y110A7A.10.1</Transcript>
wormbase-acedb/gene/XML/prepped_gene.xml:      <Transcript>Transcript:Y110A7A.10.1</Transcript>
```

The only other place with `Transcript:Y110A7A.10.1` is the raw GFF file before pre-processing. I am checking the old releases to see if they have the same entry. The only quick solution for this would be to remove the `Transcript:` from gene and CDS.

**Comment by nuin** [comment]
@chris-grove Checking on WS258, the `Transcript:` was not in front to the Transcript ID in the Gene.xml source file. It seems that I don't have WS259 available to check, but it seems that this is new. I will try to prep WS260 Gene.xml for a patch build.

**Comment by nuin** [comment]
This `Transcript:` label in the element is no present in WS261, so I will patch WS260 without disabling the instance.

**Comment by chris-grove** [comment]
@nuin OK, thanks!

**Comment by nuin** [comment]
Working properly now, please check @chris-grove 
Thanks

**Comment by chris-grove** [comment]
@nuin 
Looks good! Thanks!!
