### ISSUE TITLE
sequence information about bp484 and related wide ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5862]
*Help Desk query collected when no chat operators were online. Follow up required.*

sequence information about bp484 and related wide type.

**Reported by:** guom******* (1185*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar02147268#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar02147268#02-45-3</a>
**Browser:** Chrome 45.0.2454.101

**Comment by tuli** [comment]
Dear Colleague,

Thank you for writing to WormBase. It is not clear to me what your
question is, however I note that we do not yet have the molecular
details of the bp484 allele. Looking at the literature I see that it
is defined in PMID 24185444 Zhang H et al. (2013) Autophagy "The two
C. elegans ATG-16 homologs have partially redundant functions in the
...."

"bp484 contains a G to A nucleotide substitution at the consensus " -1
" position of the splice acceptor site in the first intron of atg-5"

I will ensure this information is added to WormBase and you'll see it
in release WS262.

Please let me know if you have addition questions.

Best wishes,

Mary Ann

On 18 September 2017 at 08:50,  <no-reply@wormbase.org> wrote:
> offline chat sequence information about bp484 and related wide type.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar02147268#02-45-3
> http://www.wormbase.org/species/c_elegans/variation/WBVar02147268#02-45-3
>
> This issue has been assigned ticket number: #5862. Follow progress on our
> issue tracker.
>
> Reported by: guomiaomiao (1185847267@qq.com)
> 18 Sep 17 07:50
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
