### ISSUE TITLE
Chris: Hello Claudia, how can I help? visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5864]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Claudia, how can I help?</br>visitor_name (visitor_email): Hello, I downloaded full transcripts for an helminth and now I need to know the protein that corresponds to each transcript ID (i.e. &gt;T265_00001 transcript=T265_00001 gene=T265_00001)</br>visitor_name (visitor_email): is that possible to do here?</br>Chris: This should be possible</br>Chris: which species?</br>visitor_name (visitor_email): Opisthorchis viverrini and Fasciola hepatica</br>Chris: OK one moment please</br>visitor_name (visitor_email): sure</br>Chris: OK, would you like to get protein sequences in FASTA format?</br>visitor_name (visitor_email): yes but before that I would like to look at the protein name</br>Chris: OK, let me take a closer look</br>visitor_name (visitor_email): or FASTA is linked to a protein name?</br>Chris: well, not necessarily. I can use the BioMart tool to input transcript names like "T265_00001" and get the associated protein sequence, but I don't see a way in BioMart to get the protein name, so I'm going to see how to do that now</br>visitor_name (visitor_email): ok, thank you</br>Chris: You're welcome</br>Chris: I'm not seeing protein names anywhere I look. It's possible that the proteins are simply being referred to by their respective transcript name, but I'll have to check with our WormBase ParaSite colleagues to see if that's the case</br>visitor_name (visitor_email): wonderful</br>Chris: Do you have a list of transcript IDs for each species?</br>visitor_name (visitor_email): yes I do</br>visitor_name (visitor_email): it's long, more than 3000 for each organism</br>Chris: OK, then I recommend going to the WormBase ParaSite BioMart tool</br>Chris: http://parasite.wormbase.org/biomart/martview/181eb756c4f745c62f0515665471807c</br>visitor_name (visitor_email): ok</br>Chris: In Query Filters, select the species (one at a time)</br>visitor_name (visitor_email): ok</br>Chris: OK, once you've selected the species, you can open the "GENE" section, click on "ID list limit", select "Transcript stable ID(s)" from the drop down menu above the entry box, and paste in your list of transcript IDs</br>visitor_name (visitor_email): oh I see</br>visitor_name (visitor_email): any data in gene type?</br>Chris: No, I would leave that blank</br>Chris: Once you've selected the species pasted your list of transcript IDs in the box, go to (click on) Output Attributes</br>visitor_name (visitor_email): ok</br>Chris: OK, I actually did find protein stable ID, and it appears to be the same as the transcript ID</br>Chris: OK, under Output Attributes, click on the "Retrieve sequences" radio button</br>visitor_name (visitor_email): ok</br>Chris: Then under SEQUENCES click on the "Peptide" radio button</br>visitor_name (visitor_email): ok</br>Chris: OK, now under "HEADER INFORMATION" click the checkboxes for "Gene stable ID", "Transcript stable ID" and "Protein stable ID"</br>visitor_name (visitor_email): I found gene name in header information, probably I may find the information I need there</br>Chris: yes</br>visitor_name (visitor_email): done</br>Chris: I think so</br>Chris: OK, now click on "Results" at the top of the page</br>visitor_name (visitor_email): something is wrong, it creates a txt but it is empty</br>Chris: OK, as a positive control, try Opisthorchis viverrini as the species and just try the T265_00001 transcript ID</br>visitor_name (visitor_email): oh I did a mistake by entering &gt;</br>Chris: and try the Results again</br>visitor_name (visitor_email): sorry</br>Chris: Ah</br>Chris: no problem</br>visitor_name (visitor_email): now it is ok</br>Chris: OK, you're getting the protein IDs and peptide sequences back for your list?</br>visitor_name (visitor_email): yes, how many transcripts I can submit at once?</br>Chris: Hmmm, I'm not sure what the limit is, 10,000 maybe? I would test it out</br>Chris: It won't show you all the results at once if its a big list</br>Chris: you can then download a file</br>visitor_name (visitor_email): it's fine</br>visitor_name (visitor_email): but unfortunately the protein name is not there</br>visitor_name (visitor_email): please check with your team if it is possible to obtain it</br>Chris: OK, do you have an example of a known protein name for a particular transcript or gene ID?</br>visitor_name (visitor_email): in the meantime I will move forward with the protein sequences</br>Chris: OK</br>Chris: I will ask my colleagues if they have any additional information about protein names</br>visitor_name (visitor_email): I believe it can appear like "transcript 0001, protein name" (something like "endonuclease or cathepsine...)</br>Chris: I see, OK</br>visitor_name (visitor_email): the traditional way is to do Blast but that will take much time because we have thousends of transcripts</br>visitor_name (visitor_email): so if there is another more easy way that will be great</br>Chris: right</br>visitor_name (visitor_email): thank you Chris, you may send me an email if you prefer</br>Chris: OK I will check and get back to you</br>Chris: Yes, I'll do that, thanks</br>visitor_name (visitor_email): have a nice day</br>Chris: thanks! you too

**Reported by:** Clau************* (clau***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Firefox 55.0

**Comment by chris-grove** [comment]
Hi Hinxton,

Could someone help Claudia? She has lists of transcript IDs for Opisthorchis viverrini and Fasciola hepatica and would like to get the human readable protein names like "endonuclease" or "cathepsin E" for each transcript. BioMart only seems to generate protein IDs, which appear to be identical to the transcript IDs, like "T265_00001".

Thanks,

Chris

**Comment by khowe** [comment]
Hi, 
The field you need is "Description". In ParaSite, this is the human-readable protein-name, as annotated by UniProt. But bear in mind that most of the parasitic worms have sparse annotation from UniProt. For O. viverrini for example, only around 400 genes have such a description (it is null/empty for most genes).

**Comment by chris-grove** [comment]
Hi Claudia,

 This is the response from my colleague Kevin Howe who helps run the WormBase ParaSite database and website:

"Hi,
The field you need is "Description". In ParaSite, this is the human-readable protein-name, as annotated by UniProt. But bear in mind that most of the parasitic worms have sparse annotation from UniProt. For O. viverrini for example, only around 400 genes have such a description (it is null/empty for most genes)."

I found one example transcript from Opisthorchis viverrini that has a description: T265_12759

If you query ParaSite BioMart for that transcript and request the gene description you'll find that it is described as:

"OSM-5  [Source:UniProtKB/TrEMBL;Acc:G5ED37] (projected from Caenorhabditis elegans ortholog osm-5)"

so, mostly an orthology reference to the C. elegans protein. I suppose you could discuss with the folks at UniProt if you'd like to expedite and/or contribute to the descriptions for genes from Opisthorchis viverrini or Fasciola hepatica.

Best,

Chris
