### ISSUE TITLE
  Hi, We are trying to find interactors...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5865]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>We are trying to find interactors of genes. For example there are 10 genes and we wanted to find all the possible interactions among all combinations of these 10 interactors and the literature that cites this. Althoug with wormbase interactions we can download all possible interactions on an individual gene basis, it gives a lot of non specific (for our purposes) interactions. Is there a quick way to get at the interactors with wormbase tools or some related tools?<br/>Thanks<br/>visitor_name</p>

**Reported by:** Vino* (vkm2**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by chris-grove** [comment]
Hello Vinod,


I had written a Python script a little while back to extract interaction IDs involving at least two genes in an input list of genes. I'm attaching it here (as a zipped folder).


You should be able to paste in your list of genes as WBGene IDs into the "gene_input.txt" file and then open a terminal, navigate to that directory, and run the Python script like this:


$ python finding_interactions_between_genes_on_a_list.py


It will read all interactions from the file:


c_elegans.PRJNA13758.current_development.interactions.txt


which I was able to obtain from our WormBase FTP site here:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/interactions/


and then output a list of interactions in a file called "Interactions_with_multiple_hits.txt". That file will list the interaction IDs with multiple (2 or more) genes from your list along with the gene IDs for the genes involved.


If you want to run this script for future releases of the database, just navigate to that FTP directory above and re-download the file


c_elegans.PRJNA13758.current_development.interactions.txt


and run the script again.


Let me know if you have any trouble.


Best,


Chris Grove

WormBase
