### ISSUE TITLE
  Hello How can one tell which release ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5866]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>How can one tell which release is behind SimpleMine? WormMine shows the release (currently WS260), but SimpleMine doesn't and it apparently isn't WS260, since a new gene like WBGene00271694 comes back as "not found".<br/>Thanks</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by raymond91125** [comment]
(Wen)
Dear Jonathan,

I am so sorry. SimpleMine is supposed to be synchronized with WS releases but I forgot to update it to the new version after WormBase moved to WS260.

I just updated SimpleMine to WS260. Please give it a try and let us know if you see any problem.

Let me think about if there is any way to automate this step in the future or get a reminder for myself.
