### ISSUE TITLE
WormMine and human orthologs

### ISSUE THREAD

**Issue by khowe** [WormBase/website#5869]
Can WormMine provide a template to take a list of  C. elegans genes (or proteins) and return the best human ortholog for each entry?
Searches sort of like this are available at ZebrafishMine
I know the results would be variable in accuracy, but it would be really helpful

If it is available, I can’t find
Thanks for all of your help

**Comment by chris-grove** [comment]
Hi Anne,

 We JUST introduced Panther orthologs into WormMine. I've created a template query called "Genes --> Human Orthologs" (ignore the one titled "C. elegans Genes --> Human Orthologs"). Here's a video showing how you can perform the query on your list of genes:

https://www.dropbox.com/s/0euzd33s6fhv8mx/Getting_human_orthologs_for_a_list_of_C.elegans_genes.mov?dl=0

You can also perform the query using WormBase ParaSite BioMart, although this apparently uses a different ortholog-calling algorithm:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.production_name_1010|wbps_gene.default.feature_page.wbps_gene_id|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.hsapiens_gene|wbps_gene.default.feature_page.hsapiens_gene_name|wbps_gene.default.feature_page.hsapiens_homolog_ensembl_peptide|wbps_gene.default.feature_page.hsapiens_orthology_type|wbps_gene.default.feature_page.hsapiens_homolog_perc_id&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."abt-2"&VISIBLEPANEL=resultspanel

You'll need to specify your list of genes in the "Query Filters" section of the BioMart tool.

With both queries, the results will be a set of predicted best orthologs, not just a single best match, so you may need to narrow it down further if you're only interested in a single best hit.

Let us know if you have any questions or encounter any issues.

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Hi Anne,


 Just to add to my last email:


The WormBase ParaSite BioMart tool uses Ensembl Compara as the ortholog prediction tool.


Best,


Chris
Draft saved at 11:45 AM
Grove, Christian A. (Chris)
Today, 11:22 AManne_hart@brown.edu;help@wormbase.org
Hi Anne,

 We JUST introduced Panther orthologs into WormMine. I've created a template query called "Genes --> Human Orthologs" (ignore the one titled "C. elegans Genes --> Human Orthologs"). Here's a video showing how you can perform the query on your list of genes:

https://www.dropbox.com/s/0euzd33s6fhv8mx/Getting_human_orthologs_for_a_list_of_C.elegans_genes.mov?dl=0
