### ISSUE TITLE
  Geneservice link is dead. Are these Y...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5872]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Geneservice link is dead. Are these YACS and cosmids available from Sanger? <br/>WRM0639dF06<br/>WRM064dE11<br/>WRM0638cD09<br/>WRM0620cG07<br/>It looks like YACS/Cosmids/Fosmids links in this region may not have been updated from Geneservice links.</p>

**Reported by:** Dan (dsc3**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by scottcain** [comment]
I assume this is a question we can answer or at least give the asker guidance for whom to ask, but I don't know those answers.  Who does?

**Comment by chris-grove** [comment]
Related issue #5849

**Comment by chris-grove** [comment]
Hi Dan,


 Yeah, apologies about the dead "Geneservice" links. We are in the processing of updating them now.


These clones might be available at the Sanger; you can ask them via the ordering form:


http://www.sanger.ac.uk/form/Sanger_CloneRequests


Someone from Sanger should email you back soon to discuss details of what you're looking for. It also appears that the specific clones you're looking for are available at Source BioScience:


https://www.sourcebioscience.com/search?s=WRM0639dF06&search=WRM0639dF06&tb=1&pr=10&ar=10&cc=12545349#tab1

https://www.sourcebioscience.com/search?s=WRM064dE11&search=WRM064dE11&tb=1&pr=10&ar=10&cc=12518854#tab1

https://www.sourcebioscience.com/search?s=WRM0638cD09&search=WRM0638cD09&tb=1&pr=10&ar=10&cc=12543840#tab1

https://www.sourcebioscience.com/search?s=WRM0620cG07&search=WRM0620cG07&tb=1&pr=10&ar=10&cc=12532829#tab1

Best,


Chris Grove

WormBase
