### ISSUE TITLE
Community curator contributors on homepage

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5873]
Hi guys,
since we are trying to push community curation, how about replacing the 'Random Page' box on the WormBase homepage with 'Community curators of the week' or of the month followed by a table like the one below?

**'Community curators of the week'**

<img width="413" alt="screen shot 2017-09-26 at 3 57 28 pm" src="https://user-images.githubusercontent.com/901243/30884076-d9daff46-a2d3-11e7-9780-80dfb83ae34d.png">

**Comment by tuli** [comment]
That's a good idea @draciti

**Comment by chris-grove** [comment]
Related issue:  #4827

**Comment by chris-grove** [comment]
I've just updated the table of top contributors to include the top 20 over the last 3 months for phenotype data:

http://www.wormbase.org/about/userguide/submit_data#02--10

**Comment by chris-grove** [comment]
I'd like to shorten the list to the top 10 or so, but I need to work that out with @sibyl229

**Comment by sibyl229** [comment]
Hi @draciti I created a new spreadsheet for Community Curator of the week (similar to the Top community curator one). https://docs.google.com/a/wormbase.org/spreadsheets/d/171B7bZwiw60D94X_lCBp5Lic6qwQlzSPLKvDWaCkJ98/edit?usp=sharing 

You will be able to edit its content after you login to Google Drive through your WormBase account. There is a bit more info in the speadsheet itself on how to make changes. 

Please let me know if you run into any issue. I will add it to the Activity widget on the home page once the content is ready. Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Thanks! These are actually the top community curators of the past 3 months, and that content is correct and ready to go. I can update it again in the future.

**Comment by draciti** [comment]
Thanks Sibyl! I'll let Chris give the initial feedback as he is the 'community curator' person. I will test once on staging.

**Comment by sibyl229** [comment]
Hi @chris-grove Thanks! I see. For your previous question on only keeping the top 10. I think deleting the extra rows from both the Curator View and Public View will give you a shorter list. I might need to make some minor changes on my end to adjust the whitespace. Do you prefer to make the changes now or in the future?https://docs.google.com/spreadsheets/d/1u2EuEEeeo5pa7hLZ_mw08qhS1yJQKyRZxCNTYm90ULQ/edit

**Comment by chris-grove** [comment]
@sibyl229 
OK, I just deleted all but the top 10 on both the Curator View and the Public View sheets. It doesn't seem to automatically update on the live site (I still see 20 entries there).

**Comment by chris-grove** [comment]
@sibyl229 
OK, it looks all set now (I also adjusted the height of the window in the widget). Thanks!

**Comment by Paul-Davis** [comment]
Looks like the box on the widget isn't scaling correctly?
![top10](https://user-images.githubusercontent.com/717707/32234014-ac2a911a-be53-11e7-8083-ce4553437c73.png)

**Comment by chris-grove** [comment]
@sibyl229 
OK it was looking fine for me on Chrome and Safari, and only a little cutoff on Firefox. I've increased the panel height. See what you think now.

**Comment by Paul-Davis** [comment]
looking 99% ok on osX FF here.

**Comment by chris-grove** [comment]
@sibyl229 
Should I make it a little taller?

**Comment by chris-grove** [comment]
Sorry @Paul-Davis 
I wasn't looking closely

**Comment by Paul-Davis** [comment]
I can live with the slight cut off....only mentioned it for your information ;)

**Comment by chris-grove** [comment]
@Paul-Davis  OK sounds good.
@sibyl229  Yeah, I fixed it. I think it should be fine now.

**Comment by Paul-Davis** [comment]
![top102](https://user-images.githubusercontent.com/717707/32239185-c23e4dda-be61-11e7-950c-74efba65ba70.png)

Yup def better :)

**Comment by sibyl229** [comment]
Thanks @chris-grove !

@draciti @Paul-Davis @chris-grove The top curator list is now also in the Activity widget on the home page: http://staging.wormbase.org/#012-34-5

**Comment by chris-grove** [comment]
@sibyl229  Looks good! Thanks!!
