### ISSUE TITLE
  I named the F55B11.1 gene "xdh-1" . H...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5874]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I named the F55B11.1 gene "xdh-1" . However, we found a typo as x"hd"-1 in the web site. Could you please correct the spell in following web page? Correct spell is "xdh-1".<br/>Thank you for your time.<br/>http://www.wormbase.org/species/c_elegans/gene/WBGene00010083#0-9g1e6c-10</p>

**Reported by:** Atsu********** (atsu*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by tuli** [comment]
Dear Atsushi,

Thank you for bringing this typo to our attention. I apologise for the mistake.
It has been fixed and will be visible in release WS263 of WormBase.

Best wishes,

Mary Ann

On 27 September 2017 at 08:49,  <no-reply@wormbase.org> wrote:
> Bug Report
>
>   I named the F55B11.1 gene "xdh-1" . However, we found a typo as x"hd"-1 in
> the web site. Could you please correct the spell in following web page?
> Correct spell is "xdh-1".
> Thank you for your time.
> http://www.wormbase.org/species/c_elegans/gene/WBGene00010083#0-9g1e6c-10
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5874. Follow progress on our
> issue tracker.
>
> Reported by: Atsushi Kuhara (atsushi_kuhara@me.com)
> 27 Sep 17 07:50
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.3.8 (KHTML,
> like Gecko) Version/10.1.2 Safari/603.3.8
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
