### ISSUE TITLE
  How do I get the C. elegans genome bu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5877]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get the C. elegans genome build ce11? I wish to download the genome sequence ce11 for bioinformatic analyses.</p>

**Reported by:** Srav*************** (nsps***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by chris-grove** [comment]
Question addressed by email
