### ISSUE TITLE
  I'm interested in gaining information...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5880]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm interested in gaining information regarding the expression profiles for the 7 B. malayi Bma-JNK isoforms. Not quite sure how to gain this information. Appreciated if you can help.<br/>John</p>

**Reported by:** John********** (siek********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Hi John,


You can find expression data for the Bma-jnk-1 gene in the "Expression" widget on the Bma-jnk-1 gene page:


http://www.wormbase.org/species/b_malayi/gene/WBGene00222081#01g9--10


We don't currently (as far as I'm aware) annotate expression levels of each distinct isoform, but rather for the whole gene. You may find it useful to browse the genome in GBrowse or JBrowse with RNA-Seq tracks turned on:


http://www.wormbase.org/tools/genome/jbrowse-simple/?loc=Bm_v4_ChrX_scaffold_001%3A3557494..3578257&data=data%2Fb_malayi_PRJNA10729&tracks=Curated_Genes%2CESTs%20(best)%2CTrinity-assembled%20RNAseq%2CRNASeq&highlight=


My colleagues can provide additional information if I missed anything.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
I should add that you may find additional RNA-Seq tracks in the JBrowse instance at WormBase ParaSite:


http://parasite.wormbase.org/jbrowse/index.html?data=%2Fjbrowse-data%2Fbrugia_malayi_prjna10729%2Fdata&loc=Bm_v4_ChrX_scaffold_001%3A3560273..3576422&highlight=&tracks=DNA%2CGene_Models%2C027_SRS1051640%2C028_SRS1051639%2C029_SRS1051638%2C001_SRS1256343%2C002_SRS1256380%2C051_ERS067029%2C052_ERS067026


Best,


Chris
