### ISSUE TITLE
Yea nothing now...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5883]
*Help Desk query collected when no chat operators were online. Follow up required.*

Yea nothing now

**Reported by:** Alex (andu****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00011832#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00011832#0-9g-3</a>
**Browser:** Chrome 61.0.3163.100

**Comment by chris-grove** [comment]
Hi Alex, was there something you needed help with?


Best,


Chris Grove

WormBase
