### ISSUE TITLE
  Hello I guess "rrf-3(allele) or rrf-3...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5884]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>I guess "rrf-3(allele) or rrf-3(allele2)" is a bug, at<br/>http://www.wormbase.org/species/c_elegans/gene/WBGene00004510<br/>in the concise description<br/>"rrf-3(allele) or rrf-3(allele2) mutants are hypersensitive to somatic RNAi",</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by chris-grove** [comment]
Hello Jonathan

Thanks for reporting this.  We will correct this error, the corrected version of the rrf-3 description will be available in the WS261 version of WormBase.

Ranjana
