### ISSUE TITLE
  CF512  Hello, I am using the strain (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5886]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;CF512 <br/>Hello, I am using the strain (CF512) for my experiment and about to publish a paper on it. Based on the original paper from Cynthia Kenyon (Garigan et al. 2002, Genetics), CF512 is (fer-15(b26)II; fem-1(hc17)IV). However, when I search the worm base with CF512,  "rrf-3(b26) II; fem-1(hc17) IV" comes up. Is this a mistake? Can you please clarify this? Than you very much for your time. Best</p>

**Reported by:** Tomo********** (ttab*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by WenChenWormBase** [comment]
Dear Tomoko,

fer-15 is an "Other_name" for rrf-3. So you are reading the correct strain
description.


Wen Chen
Curator, WormBase

On Mon, Oct 2, 2017 at 10:07 AM, <no-reply@wormbase.org> wrote:

> Content Correction
>
>   CF512
> Hello, I am using the strain (CF512) for my experiment and about to
> publish a paper on it. Based on the original paper from Cynthia Kenyon
> (Garigan et al. 2002, Genetics), CF512 is (fer-15(b26)II; fem-1(hc17)IV).
> However, when I search the worm base with CF512, "rrf-3(b26) II;
> fem-1(hc17) IV" comes up. Is this a mistake? Can you please clarify this?
> Than you very much for your time. Best
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5886. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5886>.
>
> Reported by: Tomoko Tabuchi (ttabuch1@ucsc.edu)
> 02 Oct 17 17:09
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8
> (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase
