### ISSUE TITLE
  Hi! I was wondering how to reference ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5888]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi!<br/>I was wondering how to reference gene sequences I have obtained from worm base? is it sufficient to just reference the web page I got it from? Such as this one: http://www.wormbase.org/species/c_elegans/variation/WBVar00091947#02-45-3<br/>I was going to reference the original publication but can't find a reference on the page above to find it. It's only referring back to this paper "Large-Scale Screening for Targeted Knockouts in the Caenorhabditis elegans Genome". Is that the reference best used in my case as well?<br/>Any help would be greatly appreciated.<br/>Best wishes,<br/>Franzi</p><p>What were you doing? <br />&nbsp;&nbsp;looking for gene sequences and their references
</p>

**Reported by:** Fran********** (f.po************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by raymond91125** [comment]
Hi Franziska,

Yes, the "The C. elegans Deletion Mutant Consortium et al. (2012)" is 
the proper reference. The sequence information we display is provided by 
them.

Thanks.

Raymond

On 04/10/17 02:41, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi!
> I was wondering how to reference gene sequences I have obtained from 
> worm base? is it sufficient to just reference the web page I got it 
> from? Such as this one: 
> http://www.wormbase.org/species/c_elegans/variation/WBVar00091947#02-45-3
> I was going to reference the original publication but can't find a 
> reference on the page above to find it. It's only referring back to 
> this paper "Large-Scale Screening for Targeted Knockouts in the 
> Caenorhabditis elegans Genome". Is that the reference best used in my 
> case as well?
> Any help would be greatly appreciated.
> Best wishes,
> Franzi
>
> What were you doing?
>   looking for gene sequences and their references
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5888. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5888>.
>
> Reported by: Franziska Pohl (f.pohl@rgu.ac.uk)
> 04 Oct 17 09:43
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/61.0.3163.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
