### ISSUE TITLE
  Where can i find the name of the muta...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5889]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Where can i find the name of the mutated gene that causes the phenotype in my strain of interest.</p>

**Reported by:** kris*************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by chris-grove** [comment]
Hello Krishin,


 You'll need to go to the WormBase web page for that strain. From the WormBase homepage:

www.wormbase.org


using the search box at the upper right, select to search "for a strain" from the drop down menu, paste/type in your strain name and either hit enter or click on the autosuggest strain name that comes up (if it's a recognized strain). You should then arrive at a strain page like this one:


http://www.wormbase.org/species/c_elegans/strain/CB1370#012--10


You can look for the gene in the "Genotype" field of the "Overview" widget or in the "Gene" field of the "Contains" widget. You can turn widgets on and off from the left side control panel.


Let us know if you have any questions.


Best,


Chris Grove

WormBase
