### ISSUE TITLE
The tissue enrichment analysis (TEA) link under To...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5890]
*Help Desk query collected when no chat operators were online. Follow up required.*

The tissue enrichment analysis (TEA) link under Tools takes me to a '404-Page not found' error

**Reported by:** Ranj*********** (ranj***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/enrichment/tea/tea.cgi">https://www.wormbase.org/tools/enrichment/tea/tea.cgi</a>
**Browser:** Chrome 61.0.3163.100

**Comment by chris-grove** [comment]
@rankishore 
Is this still an issue for you?

**Comment by raymond91125** [comment]
This problem is due to http*S*. It may be rather involved to solve.

**Comment by chris-grove** [comment]
I think this issue has been resolved. @rankishore  please re-open if it is not.
