### ISSUE TITLE
Hi, I was wondering if you could let me know what ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5892]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I was wondering if you could let me know what is the source of this cDNA http://www.wormbase.org/species/c_elegans/sequence/elegans_PE_SS_GG460%7Cc1_g1_i6#04--10. I would need to order it but cannot figure out where it is coming from. Thanks so much for your help.  Best, visitor_name

**Reported by:** Ales****** (alep************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/sequence/elegans_PE_SS_GG460|c1_g1_i6#04--10">http://www.wormbase.org/species/c_elegans/sequence/elegans_PE_SS_GG460|c1_g1_i6#04--10</a>
**Browser:** Chrome 61.0.3163.100

**Comment by gw3** [comment]
Alessandra,

This is an artificial transcript created by using the software package 
'Trinity' (https://github.com/trinityrnaseq/trinityrnaseq/wiki) to align 
a set of RNA-seq short reads together into a contiguous sequence.

It has no physical existence, so you cannot order it.

If you are interested, I can give you detailed descriptions of which 
reads were joined by Trinity to create this sequence.


Gary Williams
WormBase
