### ISSUE TITLE
  Hi Wormbase.  I received a Lab (CFJ) ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5894]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi Wormbase. <br/>I received a Lab (CFJ) and Allele (kst) designation from Tim Schedl. At the time, I didn't have my contact information. Can you please update the record in Wormbase?<br/>Thanks,<br/>Christian<br/>visitor_name, Ph.D. <br/>Assistant Professor of Bioscience<br/>King Abdullah University of Science and Technology (KAUST)<br/>Biological & Environmental Sciences & Engineering Division (BESE)<br/>Office: Bldg.2, Level 4, 4237<br/>Thuwal 23955-6900<br/>Kingdom of Saudi Arabia<br/>E: cfjensen@kaust.edu.sa<br/>T: (+966) 128082968 </p>

**Reported by:** Chri********************** (chri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by fayerodgers** [comment]
Cecilia replied to the user: 
Dear Christian Froekjaer-Jensen:

Thanks for the updates.

I have updated your data in your WMPerson page.
It will be available in release WS263 of WormBase.
We are currently in version WS260.

The full release schedule is available here:
http://www.wormbase.org/about/release_schedule

Thanks again, have a great day!

Cecilia
