### ISSUE TITLE
  Hi Wormbase, I entered a new email ad...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5895]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi Wormbase, I entered a new email address (cfjensen@kaust.edu.sa). I got the verification email but when I clicked it (within an hour of registering), the web site told me the link was invalid and/or expired. Any chance you can verify my email manually - or send me a link to do it myself?<br/>Thanks<br/>Christian</p>

**Reported by:** Chri********************** (chri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by sibyl229** [comment]
Replied to user. Waiting to hear back.

The issues has to do with adding additional email to the profile and unable to resend verification email (after initial verification fails).
