### ISSUE TITLE
i am inetresting about nematode...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5898]
*Help Desk query collected when no chat operators were online. Follow up required.*

i am inetresting about nematode

**Reported by:** Raha************ (raha**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00017690#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00017690#0-9g-3</a>
**Browser:** Chrome 53.0.2785.104

**Comment by chris-grove** [comment]
Hello Rahat,


Is there something that we can help you with?


Best,


Chris Grove

WormBase
