### ISSUE TITLE
  I have an assignment due for bioinfor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5901]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have an assignment due for bioinformatics and it keeps saying my gene cant be found</p>

**Reported by:** ml04*************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by fayerodgers** [comment]
Chris replied 13/10/17.
No response from user, closing issue.
