### ISSUE TITLE
  tax-6 interaction graph has two big f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5902]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;tax-6 interaction graph has two big fat arrows that overlap, makes it difficult to see which genes interact with which.</p>

**Reported by:** Jae *** (bioc**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by raymond91125** [comment]
Yes, confirmed (just for illustration).

raymond


On 13/10/17 12:35, no-reply@wormbase.org wrote:
> Feature Request
>
>   tax-6 interaction graph has two big fat arrows that overlap, makes 
> it difficult to see which genes interact with which.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5902. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5902>.
>
> Reported by: Jae Cho (biocho@caltech.edu)
> 13 Oct 17 19:36
>
> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 
> Firefox/56.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
testing.

**Comment by chris-grove** [comment]
@raymond91125 
This issue may be resolved with the new interactions network display coming in the next release, worked on by @sibyl229 and currently visible on the staging site:

http://staging.wormbase.org/species/c_elegans/gene/WBGene00006527#8--10

Still needs a few tweaks, but I'm working with Sibyl on that.

**Comment by chris-grove** [comment]
I think this issue is resolved with the (very nice) new interaction display (I will discuss with Jae). Closing
