### ISSUE TITLE
The conceptual translation of mitochondrial genome...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5903]
*Help Desk query collected when no chat operators were online. Follow up required.*

The conceptual translation of mitochondrial genome encoded genes is wrong since the genetic code used by this genome is different than the canonical code. Is there any way to fix this? It would be extremely helpful for us. Thank you.

**Reported by:** Maul******** (maul*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/MTCE.3#06--10">http://www.wormbase.org/species/c_elegans/transcript/MTCE.3#06--10</a>
**Browser:** Firefox 55.0

**Comment by khowe** [comment]
@sibyl229 suggested fix for this would be to us the sequence of the attached protein object (which is correct).

**Comment by kyook** [comment]
from @fayerodgers 

Hi Maulik,
Apologies for the delayed response. 
Thanks for bringing this to our attention, we're looking into the issue and will get back to you.
Best wishes,
Faye

**Comment by Paul-Davis** [comment]
I also pointed the user to the protein summary page for the gene they were interested in.

**Comment by raymond91125** [comment]
@sibyl229 @khowe suggested to bypass the real-time translation and use ACeDB hard-coded protein sequences. Or I guess if you can sub in Mito translation script just for mito genes.

**Comment by sibyl229** [comment]
Hi @khowe @Paul-Davis @raymond91125 

The protein sequence is fixed on transcript and CDS pages.
http://staging.wormbase.org/species/c_elegans/transcript/MTCE.3#06--10
http://staging.wormbase.org/species/c_elegans/cds/MTCE.3#05--10

I couldn't tell if a gene is mitochondrial, so I used the stored protein sequence by default if one exists. Is there harm in doing that?

Thanks,

**Comment by Paul-Davis** [comment]
currently staging just errors on the widgets...need to test when staging back up.

**Comment by mgrbyte** [comment]
@Paul-Davis It's back now.

**Comment by Paul-Davis** [comment]
Thanks @mgrbyte 

Looks good to me @sibyl229

**Comment by sibyl229** [comment]
Thanks @Paul-Davis
