### ISSUE TITLE
WormBase is down for me right now

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5905]

**Comment by scottcain** [comment]
Staging is also inaccessible even though starman is running. Has anybody modified the security groups?

**Comment by nuin** [comment]
It works fine for me, but I might be accessing from cache.

**Comment by nuin** [comment]
![screen shot 2017-10-16 at 9 38 04 pm](https://user-images.githubusercontent.com/6273/31645636-61f1c3ce-b2ba-11e7-8711-9ad698771709.png)

**Comment by chris-grove** [comment]
OK, working now. closing
