### ISSUE TITLE
  How do I down load a list of all muta...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5907]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I down load a list of all mutant genes with the 'rubber band' phenotype for example?</p>

**Reported by:** Pete* (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by raymond91125** [comment]
Hi Peter,

If you go to the Phenotype report page for "rubber band" and open the 
Ontology Browser 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000514#03--10>, 
to the right of the focus term there is a hyperlink to 3 genes.

Cheers,

Raymond


On 17/10/17 15:16, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I down load a list of all mutant genes with the 'rubber band' 
> phenotype for example?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5907. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5907>.
>
> Reported by: Peter (peter.roy@utoronto.ca)
> 17 Oct 17 22:17
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 
> (KHTML, like Gecko) Version/11.0 Safari/604.1.38
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
