### ISSUE TITLE
  There use to be a tool to get multipl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5911]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;There use to be a tool to get multiple sequence alignments for a given protein vs other species- if its still on wormbase, can you direct me to it?</p>

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by chris-grove** [comment]
Hi Peter,


 Are you referring to the protein page "Protein Aligner"?


http://www.wormbase.org/species/c_elegans/protein/WP:CE15371#08--10


On WB protein pages, there's the Protein Aligner widget which displays multiple protein sequence alignments with other species.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Hi Peter,

We have this <http://www.wormbase.org/tools/protein_aligner>. And you could use on-line EBI tools <https://www.ebi.ac.uk/Tools/msa/> to align your choice of sequences.

Cheers,

Raymond

**Comment by raymond91125** [comment]
Basically it's on the protein page, Overview widget. From gene page -> 
Sequence widget -> Protein. As Chris pointed out, the multiple protein 
alignment is a widget on protein pages also.

Cheers,

Raymond


On 20/10/17 08:17, Peter Roy wrote:
> sorry, but where do I find the WB protein ID?
>
> Peter J. Roy, Ph.D.
> Professor, Vice Chair
> Canada Research Chair in Chemical Genetics
> Department of Molecular Genetics
> Department of Pharmacology & Toxicology
> The Donnelly Centre, Rm 1202
> 160 College St., Toronto, ON
> University of Toronto
>
> 416-946-8395
> roylab.ccbr.utoronto.ca <http://roylab.ccbr.utoronto.ca>
>
>> On Oct 20, 2017, at 11:12 AM, Raymond Lee <raymond@caltech.edu 
>> <mailto:raymond@caltech.edu>> wrote:
>>
>> Hi Peter,
>>
>> We have this <http://www.wormbase.org/tools/protein_aligner>. And you 
>> could use on-line EBI tools <https://www.ebi.ac.uk/Tools/msa/> to 
>> align your choice of sequences.
>>
>> Cheers,
>>
>> Raymond
>>
>>
>>
>> On 18/10/17 19:01, Peter Roy wrote:
>>> HI Raymond,
>>> Thanks for that.
>>> Another question- how can I get a multiple sequence alignment 
>>> (protein) from wormbase?
>>> Thanks,
>>> Peter
>>>
>>>
>>> Peter J. Roy, Ph.D.
>>> Professor, Vice Chair
>>> Canada Research Chair in Chemical Genetics
>>> Department of Molecular Genetics
>>> Department of Pharmacology & Toxicology
>>> The Donnelly Centre, Rm 1202
>>> 160 College St., Toronto, ON
>>> University of Toronto
>>>
>>> 416-946-8395
>>> roylab.ccbr.utoronto.ca <http://roylab.ccbr.utoronto.ca/>
>>>
>>>> On Oct 17, 2017, at 6:30 PM, Raymond Lee <raymond@caltech.edu 
>>>> <mailto:raymond@caltech.edu>> wrote:
>>>>
>>>> Hi Peter,
>>>>
>>>> If you go to the Phenotype report page for "rubber band" and open 
>>>> the Ontology 
>>>> Browser<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000514#03--10>, 
>>>> to the right of the focus term there is a hyperlink to 3 genes.
>>>>
>>>> Cheers,
>>>>
>>>> Raymond
>>>>
>>>>
>>>> On 17/10/17 15:16,no-reply@wormbase.orgwrote:
>>>>> How Do I ...?
>>>>>
>>>>>   How do I down load a list of all mutant genes with the 'rubber 
>>>>> band' phenotype for example?
>>>>>
>>>>> Submitted From:
>>>>>   support/tools/support <http://www.wormbase.org//tools/support>
>>>>>
>>>>> This issue has been assigned ticket number: #5907. Follow progress 
>>>>> on ourissue tracker <https://github.com/WormBase/website/issues/5907>.
>>>>>
>>>>>
>>>>> Reported by: Peter (peter.roy@utoronto.ca)
>>>>> 17 Oct 17 22:17
>>>>>
>>>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) 
>>>>> AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
>>>>>
>>>>> This question was reported via the web interface atwormbase.org 
>>>>> <http://wormbase.org/>. You can alsoemail us 
>>>>> <mailto:help@wormbase.org>directly.
>>>>>
>>>>> --
>>>>> --
>>>>> You received this message because you are subscribed to the 
>>>>> "WormBase: help" group.
>>>>> To post to this group, send email tohelp@wormbase.org
>>>>> To unsubscribe from this group, send email to
>>>>> help+unsubscribe@wormbase.org
>>>>> For more options, visit this group at
>>>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>>>
>>>>> ---
>>>>> You received this message because you are subscribed to the Google 
>>>>> Groups "WormBase: help" group.
>>>>> To unsubscribe from this group and stop receiving emails from it, 
>>>>> send an email tohelp+unsubscribe@wormbase.org 
>>>>> <mailto:help+unsubscribe@wormbase.org>.
>>>>
>>>>
>>>> -- 
>>>> __
>>>> Raymond Lee
>>>> raymond@caltech.edu
>>>> http://www.WormBase.org/
>>>> California Institute of Technology
>>>> Division of Biology and Biological Engineering
>>>> Mail Code 156-29
>>>> Pasadena, CA 91125
>>>> USA
>>>> tel: 626.395.2687
>>>
>>
>> -- 
>> __
>> Raymond Lee
>> raymond@caltech.edu
>> http://www.WormBase.org/
>> California Institute of Technology
>> Division of Biology and Biological Engineering
>> Mail Code 156-29
>> Pasadena, CA 91125
>> USA
>> tel: 626.395.2687
>

-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
