### ISSUE TITLE
I have been trying to search the ROL-6, N2, BLI-1,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5923]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have been trying to search the ROL-6, N2, BLI-1, and UNC-22 proteins, but I cannot seem to find all of the coded protein for the genes above. How can I find the page that will give me the information about the proteins in one page? Thank you for your time.

**Reported by:** Roci** (rher*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/N2 mutations">http://www.wormbase.org/search/gene/N2 mutations</a>
**Browser:** Safari 11.0

**Comment by raymond91125** [comment]
Hi Rocio,

N2 in your list is not a gene but likely referring to the standard 
wild-type strain. Perhaps your professor meant to trick you.

For others, if you search the names, while choosing "for a protein", in 
the top right on WormBase landing page, you should find one or more 
proteins that they encode.

Good luck.

Raymond


On 22/10/17 14:31, no-reply@wormbase.org wrote:
> offline chat I have been trying to search the ROL-6, N2, BLI-1, and 
> UNC-22 proteins, but I cannot seem to find all of the coded protein 
> for the genes above. How can I find the page that will give me the 
> information about the proteins in one page? Thank you for your time.
>
> Submitted From:
>   http://www.wormbase.org/search/gene/N2 mutations 
> http://www.wormbase.org/search/gene/N2 mutations 
> <http://www.wormbase.org/http://www.wormbase.org/search/gene/N2%20mutations> 
>
>
> This issue has been assigned ticket number: #5923. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5923>.
>
> Reported by: Rocio (rherrera3@csustan.edu)
> 22 Oct 17 21:33
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
