### ISSUE TITLE
  find the worm proteins coded for by t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5924]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;find the worm proteins coded for by the worm genes N2, dpy-10, unc-22, rol-6 and bli-1 for C. elegans.</p>

**Reported by:** sneh*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by kyook** [comment]
same as #5923, which Raymond addressed.

**Comment by chris-grove** [comment]
@kyook 
Has someone responded directly to this user? This is a different user than the one Raymond responded to.

**Comment by chris-grove** [comment]
Hello Sneha,


 From the WormBase homepage:


www.wormbase.org


select "for a protein" from the search box pull down menu and type in your gene/protein name. You can click on the suggested names that come up and you will be directed to the protein page for each gene.


Alternatively, you can look up each gene in the search box using the default ("for a gene") search option to reach each gene page. From there, look in the "Sequences" widget to see the proteins. For example:


http://www.wormbase.org/species/c_elegans/gene/WBGene00001072#0g--10


Note that "N2" is a commonly used wild type strain of C. elegans, not a gene.


Best,


Chris Grove

**Comment by kyook** [comment]
Thank you for catching this Chris. 

Karen
