### ISSUE TITLE
kr208, as described in 

Richard, M., Boulin, T., ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5926]
*Help Desk query collected when no chat operators were online. Follow up required.*

kr208, as described in 

Richard, M., Boulin, T., Robert, V. J. P., Richmond, J. E., &amp; Bessereau, J.-L. (2013). Biosynthesis of ionotropic acetylcholine receptors requires the evolutionarily conserved ER membrane complex. Proc Natl Acad Sci US A, 110(11), E1055–63. http://doi.org/10.1073/pnas.1216154110

is an allele of unc-29, specifically an in frame knock-in of tagRFP into the unc-29 genomic locus.

**Reported by:** Step*********** (nurr**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar02125731#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar02125731#02-45-3</a>
**Browser:** Firefox 56.0

**Comment by Paul-Davis** [comment]
Thank you for submitting your data. I will look at incorporating it into 
the WS263 release of WormBase.

Paul

On 24/10/2017 00:00, no-reply@wormbase.org wrote:
> offline chat kr208, as described in Richard, M., Boulin, T., Robert, 
> V. J. P., Richmond, J. E., & Bessereau, J.-L. (2013). Biosynthesis of 
> ionotropic acetylcholine receptors requires the evolutionarily 
> conserved ER membrane complex. Proc Natl Acad Sci US A, 110(11), 
> E1055–63. http://doi.org/10.1073/pnas.1216154110 is an allele of 
> unc-29, specifically an in frame knock-in of tagRFP into the unc-29 
> genomic locus.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar02125731#02-45-3 
> http://www.wormbase.org/species/c_elegans/variation/WBVar02125731#02-45-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar02125731#02-45-3> 
>
>
> This issue has been assigned ticket number: #5926. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5926>.
>
> Reported by: Stephen Nurrish (nurrish@molbio.mgh.harvard.edu)
> 23 Oct 17 23:01
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
@Paul-Davis  did this get resolved?

**Comment by Paul-Davis** [comment]
yup....closing @chris-grove
