### ISSUE TITLE
WormMine: on im-dev2: duplicate gene objects

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5927]
On im-dev2 WormMine:

http://im-dev2.wormbase.org/tools/wormmine/begin.do

If I query for genes in which the "WormBase Gene ID" is a particular gene ID (e.g. WBGene00001949) or the "Gene Name" is the same ID, I get two results, one in which the WormBase Gene ID, Sequence Name, and Gene Name are all correct, and another in which the Gene Name is erroneously the WBGene ID. So for example, if I do the following query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A or B">
  <constraint path="Gene.primaryIdentifier" code="A" op="=" value="WBGene00001949"/>
  <constraint path="Gene.symbol" code="B" op="=" value="WBGene00001949"/>
</query>`

I get the following result:

![screen shot 2017-10-24 at 2 31 01 pm](https://user-images.githubusercontent.com/611382/31961187-ff44c47e-b8c7-11e7-821f-526971fd28cf.png)

It appears that the gene that inappropriately has the WBGene ID as the Gene Name may be coming from the Ensembl Compara homology data.

**Comment by nuin** [comment]
Changed [Compara config file](https://github.com/intermine/intermine/blob/dev/bio/sources/ensembl/ensembl-compara/resources/ensembl-compara_keys.properties) adding primaryIdentifier on _C. elegant taxon ID_. Duplications seem to be removed.

**Comment by chris-grove** [comment]
@nuin 
There are still duplicates on im-dev2. I don't see duplicates on im-dev3. Should I close this?

**Comment by nuin** [comment]
im-dev2 is the new production, build should end tomorrow sometime. The current test will be wiped and the changes tested on I'm-dev3 were applied to this build. Let's wait until tomorrow or so.

Thanks @chris-grove

**Comment by chris-grove** [comment]
OK
