### ISSUE TITLE
Protein change not accurately reflected on Variation page Molecular Details widget

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5932]
At least for the case of daf-2(e1370):

http://www.wormbase.org/species/c_elegans/variation/WBVar00143949#05--10

the "Protein Change" field in the "Molecular Details" widget is indicating that all transcripts are "wildtype":

![screen shot 2017-10-25 at 3 37 09 pm](https://user-images.githubusercontent.com/611382/32019201-684bd34a-b99a-11e7-9803-8d016f10480b.png)

which I think is misleading and is not in agreement with what is in the Genetics widget on the daf-2 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#04--10

![screen shot 2017-10-25 at 3 38 22 pm](https://user-images.githubusercontent.com/611382/32019253-941372d0-b99a-11e7-9bee-47a5313b5952.png)

You can see the change in the conceptual translation and maybe the "wildtype" is supposed to indicate that the link to the indicated transcript and/or the sequence in the helix icon is wildtype, but I expected to see something like I see on the gene page, e.g. "Y55D5A.5a (P1465S)". Maybe with the conceptual translation we don't need the link to the transcript object or the helix icon?

**Comment by sibyl229** [comment]
@a8wright Don't worry about this. It's a template issue.

**Comment by sibyl229** [comment]
@chris-grove protein change bug in molecular details widget should be fixed now: http://staging.wormbase.org/species/c_elegans/variation/WBVar00143949#05--10

**Comment by chris-grove** [comment]
@sibyl229 
Looks great! Thank you!!
