### ISSUE TITLE
Links from JBrowse back to WormBase object pages break after editing config file max height

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5933]
In JBrowse, if I change the track height manually by editing the config file, none of the features link properly to their respective pages, even after changing the height back to the original:

https://www.dropbox.com/s/jh6p4q68l45wi24/JBrowse_bug_movie-links_to_cDNAs_break_after_resizing_track_height.mov?dl=0

This happens on the "ESTs (best)" track as well as the "Curated Genes" track

**Comment by scottcain** [comment]
I don't think this issue needs to stay open, as I added the larger maxHeight to the builtin config.  It's a fairly obscure bug :-)
