### ISSUE TITLE
WS262 patches

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5935]
we discovered some acedb data issues post-release for WS262.
The files are here: 
* [briggsae_patch](http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/acedb/PATCHES/briggsae_gene_confirmation_status.ace)
* [brugia_patch](http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/acedb/PATCHES/brugia_gene_confirmation_status.ace)
* [panther_patch](http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/acedb/PATCHES/pantherdb_analysis_fix.ace)

OICR: When you build the acedb database can you load the patches
HX: would be good to do the same for the datomic build

**Comment by mgrbyte** [comment]
Patches were applied to the ACeDB database before dumping files for migration (on the ec2 instance).
Patches applied with `tace`, here's the commands for reference (all executed on the `wb-db-migration` ec2-instance)

```bash
mkdir ~ec2-user/ws262-patches
cd $_
wget http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/acedb/PATCHES/briggsae_gene_confirmation_status.ace
wget  http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/acedb/PATCHES/brugia_gene_confirmation_status.ace
wget http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/acedb/PATCHES/pantherdb_analysis_fix.ace
cd /wormbase/acedb_database`
tace .
> Parse /home/ec2-user/brugia_gene_confirmation_status.ace
> Parse /home/ec2-user/brugia_gene_confirmation_status.ace
> Parse /home/ec2-user//pantherdb_analysis_fix.ace
> Save
<Crtl-d to quit>
```
@sibyl229 assigned to you in case the ACeDB db needs patching at your end.

**Comment by epaule** [comment]
not sure if @sibyl229 patched the acedb database. If yes, can you close it?
