### ISSUE TITLE
Strain Request - WBPaper00051023--Localized TWIST1 and TWIST2 basic domain.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5936]
Ranjana Kishore [10:02 PM] 
Please create the strains in WBPaper00051023--Localized TWIST1 and TWIST2 basic domain.......we are working on a workflow here so temporarily I'm not using the new_objects.cgi form, but will probably go back to using it at some point. either way I have to alert you anyway.

**Comment by Paul-Davis** [comment]
Stub strain objects created for WS263

```
Strain : AG278
Strain : AG240
Strain : AG237
Strain : AG233
Strain : AG245
Strain : AG266
Strain : AG255
Strain : AG290
Strain : AG285
Strain : AG279
Strain : AG315
Strain : AG316
Strain : AG317
Strain : AG318
Strain : AK55
Strain : AG250
Strain : AG253
Strain : AG241
Strain : AK176
Strain : AG249
Strain : AK177
Strain : AG255
Strain : AK167
Strain : AK170
Strain : AK171
Strain : AK169
Strain : AK172
Strain : AK173
Strain : AK168
Strain : AK174
```

**Comment by rankishore** [comment]
@Paul-Davis: All these strains have made their way into the OA, thanks.

**Comment by Paul-Davis** [comment]
NP @rankishore
