### ISSUE TITLE
ar131 sequence correction

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5945]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Elia, how can I help?</br>visitor_name (visitor_email): Hi we found an error in this allele sequence</br>Chris: Ah OK</br>visitor_name (visitor_email): By sequencing the correct sequence of ar131 is attached</br>Chris: Can you please send the allele details to help@wormbase.org and we will make sure the appropriate curator addresses the problem.</br>visitor_name (visitor_email): ok</br>Chris: Thank you!!</br>Chris: Is there anything else I can help you with, or do you have any additional feedback?</br>visitor_name (visitor_email): no thanks</br>Chris: OK, have a nice day

**Reported by:** elia*********** (elia**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10">http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10</a>
**Browser:** Chrome 61.0.3163.100

**Comment by chris-grove** [comment]
From Elia:
"Hi,
 we have found an error in sel-12(ar131) allele sequence in wormbase (http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10). Attached is the correct sequence, as found by direct Sanger sequencing of ar131 and by checking the original paper by Levitan and Greenwald Nature 1995 (attached is the relative figure).
Many thanks
Elia"

[ar131 seq.docx](https://github.com/WormBase/website/files/1427760/ar131.seq.docx)

![pastedgraphic-1](https://user-images.githubusercontent.com/611382/32179432-c47dd810-bd65-11e7-97bb-c85c121389b7.png)

**Comment by chris-grove** [comment]
Hello Elia,


 Thank you for the information. An allele curator will be in touch with you soon.


Best,

Chris Grove

WormBase

**Comment by Paul-Davis** [comment]
Thanks for the info Chris....I guess that's me for now :)

**Comment by Paul-Davis** [comment]
Dear Elia,

I have updated the annotation and this will appear in the WS263 release 
of wormbase.

Thanks again for pointing out the error.

Paul


On 30/10/2017 15:16, no-reply@wormbase.org wrote:
> online chat Chris: Hello Elia, how can I help?
> elia di schiavi (elia.dischiavi@ibbr.cnr.it): Hi we found an error in 
> this allele sequence
> Chris: Ah OK
> elia di schiavi (elia.dischiavi@ibbr.cnr.it): By sequencing the 
> correct sequence of ar131 is attached
> Chris: Can you please send the allele details to help@wormbase.org and 
> we will make sure the appropriate curator addresses the problem.
> elia di schiavi (elia.dischiavi@ibbr.cnr.it): ok
> Chris: Thank you!!
> Chris: Is there anything else I can help you with, or do you have any 
> additional feedback?
> elia di schiavi (elia.dischiavi@ibbr.cnr.it): no thanks
> Chris: OK, have a nice day
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10 
> http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10> 
>
>
> This issue has been assigned ticket number: #5946. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5946>.
>
> Reported by: elia di schiavi (elia.dischiavi@ibbr.cnr.it)
> 30 Oct 17 15:17
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
closes #5945

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
