### ISSUE TITLE
  for png-1, WormBase has no phenotypes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5948]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;for png-1, WormBase has no phenotypes cited, but in References does include the one paper in 2010 that shows png-1 mutants to have an axonal branching phenotype.</p><p>What were you doing? <br />&nbsp;&nbsp;just checking the png-1 page since we are studying this gene.</p>

**Reported by:** Andy******* (andy*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by chris-grove** [comment]
Hi Andy,


 Thanks for the information. We haven't curated this paper for mutant phenotypes yet. If you wouldn't mind, you could submit the phenotypes from the paper using our online phenotype form:


http://www.wormbase.org/submissions/phenotype.cgi


If you know the allele(s) and the phenotype, it should only take a minute or two. You don't need to be an author of the paper to submit these and it would really help us tackle our backlog of papers that need phenotype curation.

Let me know if you have any questions.


Thanks!


Chris Grove

WormBase
