### ISSUE TITLE
  How to find promoter of gene aex-3 ? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5954]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How to find promoter of gene aex-3 ?<br/>or promoter that express in all neuron expressing.</p>

**Reported by:** anan**********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by chris-grove** [comment]
Hi,

As the exact limits of functional gene promoters are rarely defined explicitly, upstream sequence of a given transcript is usually used as a proxy for the promoter sequence. To find the promoter sequence of gene aex-3, I would first recommend going to the aex-3 gene page:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000086#0g9--10


You can find this page by searching for "aex-3" in the search box which is set to search for genes by default. Once there, you can find a list of transcripts in the first column of the table in the "Sequences" widget. To the left of each transcript ID (e.g. "C02H7.3a") is a gray double helix icon. Clicking on any of these icons will bring up the sequence details for that transcript, including 2 kb upstream and 2 kb downstream sequences.


Another option is to use JBrowse (a link to which you can find in the "Sequences" widget; click on the genomic coordinates link to the right of the "Try the new Genome browser"). Find and turn on the "Curated genes (protein coding)" track under the "Curated Genes" section of the JBrowse track selector panel to the left. Once the track has loaded, right click on the transcript for which you'd like upstream sequences. Select "View Sequence", click on the OK of the warning message box that likely pops up (you can ignore those messages), and you'll be presented with a tool for viewing the transcript sequence and highlighting various features of it including upstream sequence. At the right end of the line labeled "Upstream" click on the "Select View" drop down menu and choose how much sequence upstream of the transcript you'd like to view, in increments of 500bp up to 4kb. Once you selected a length, click on "Highlight" and/or "Lowercase" to visually distinguish this sequence from the transcript. This is all demonstrated in this video:


https://www.dropbox.com/s/75ih8gqrgasqw7m/Finding_upstream_sequence_of_a_gene.mov?dl=0

Let us know if you have any questions.


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Also you may want to look at the promoters of rab-3 and unc-119, two other genes considered to be expressed pan-neuronally.


Best,


Chris

**Comment by raymond91125** [comment]
Just to add that on the Anatomy term page for neuron 
<http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#014--10> 
-> Association widget -> Expression patterns. If you search for 
"marker", you'd find entries that have the word marker in Descriptions.

Cheers,

Raymond

**Comment by raymond91125** [comment]
That is also a great resource Raymond.
Thank you so much. :)

Regards,
Anand

On Wed, Nov 1, 2017 at 10:16 PM, raymond <raymond@caltech.edu> wrote:

> Just to add that on the Anatomy term page for neuron
> <http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#014--10>
> <http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#014--10>
> -> Association widget -> Expression patterns. If you search for "marker",
> you'd find entries that have the word marker in Descriptions.
>
> Cheers,
>
> Raymond
>
>
>
> On 11/01/2017 05:40 PM, Anand Patwardhan wrote:
>
> Dear Chris,
>
> Thats a great explanation. I learnt  so much.
> Yes, I have sorted few promoters and looking forward to use unc-119.
>
> I am new to worm research & appreciate your help.
>
> Kind Regards,
> - Anand
>
> On Wed, Nov 1, 2017 at 5:21 PM, Grove, Christian A. (Chris) <
> cgrove@caltech.edu> wrote:
>
>> Also you may want to look at the promoters of rab-3 and unc-119, two
>> other genes considered to be expressed pan-neuronally.
>>
>>
>> Best,
>>
>>
>> Chris
>> ------------------------------
>> *From:* Grove, Christian A. (Chris)
>> *Sent:* Wednesday, November 1, 2017 5:15:42 PM
>> *To:* anandrpatwardhan@gmail.com
>> *Cc:* help@wormbase.org
>> *Subject:* Re: [wormbase-help] : How to find promoter of gene aex-3 ? ...
>>
>>
>> Hi,
>>
>>
>> As the exact limits of functional gene promoters are rarely defined
>> explicitly, upstream sequence of a given transcript is usually used as a
>> proxy for the promoter sequence. To find the promoter sequence of gene
>> aex-3, I would first recommend going to the aex-3 gene page:
>>
>>
>> http://www.wormbase.org/species/c_elegans/gene/WBGene00000086#0g9--10
>>
>>
>> You can find this page by searching for "aex-3" in the search box which
>> is set to search for genes by default. Once there, you can find a list of
>> transcripts in the first column of the table in the "Sequences" widget. To
>> the left of each transcript ID (e.g. "C02H7.3a") is a gray double helix
>> icon. Clicking on any of these icons will bring up the sequence details for
>> that transcript, including 2 kb upstream and 2 kb downstream sequences.
>>
>>
>> Another option is to use JBrowse (a link to which you can find in the
>> "Sequences" widget; click on the genomic coordinates link to the right of
>> the "Try the new Genome browser"). Find and turn on the "Curated genes
>> (protein coding)" track under the "Curated Genes" section of the JBrowse
>> track selector panel to the left. Once the track has loaded, right click on
>> the transcript for which you'd like upstream sequences. Select "View
>> Sequence", click on the OK of the warning message box that likely pops up
>> (you can ignore those messages), and you'll be presented with a tool for
>> viewing the transcript sequence and highlighting various features of it
>> including upstream sequence. At the right end of the line labeled
>> "Upstream" click on the "Select View" drop down menu and choose how much
>> sequence upstream of the transcript you'd like to view, in increments of
>> 500bp up to 4kb. Once you selected a length, click on "Highlight" and/or
>> "Lowercase" to visually distinguish this sequence from the transcript. This
>> is all demonstrated in this video:
>>
>>
>> https://www.dropbox.com/s/75ih8gqrgasqw7m/Finding_upstream_
>> sequence_of_a_gene.mov?dl=0
>>
>>
>> Let us know if you have any questions.
>>
>>
>> Chris Grove
>>
>> WormBase
>>
>>
>>
>>
>> ------------------------------
>> *From:* no-reply@wormbase.org <no-reply@wormbase.org>
>> *Sent:* Wednesday, November 1, 2017 3:58:51 PM
>> *To:* help@wormbase.org
>> *Cc:* anandrpatwardhan@gmail.com
>> *Subject:* [MARKETING] [wormbase-help] : How to find promoter of gene
>> aex-3 ? ...
>>
>> Question:
>>
>>   How to find promoter of gene aex-3 ?
>> or promoter that express in all neuron expressing.
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #5954. Follow progress on our issue
>> tracker <https://github.com/WormBase/website/issues/5954>.
>>
>> Reported by: anandrpatwardhan@gmail.com
>> 01 Nov 17 23:00
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101
>> Firefox/56.0
>>
>> This question was reported via the web interface at wormbase.org. You
>> can also email us <help@wormbase.org> directly.
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> ---
>> You received this message because you are subscribed to the Google Groups
>> "WormBase: help" group.
>> To unsubscribe from this group and stop receiving emails from it, send an
>> email to help+unsubscribe@wormbase.org.
>>
>
>
>
> --
> *Anand Patwardhan*
> 1482, 5th Avenue
> <https://maps.google.com/?q=1482,+5th+Avenue+%0D+San+Francisco,+California+%C2%A094122&entry=gmail&source=g>
> San Francisco, California  94122
> Contact  anandrpatwardhan@gmail.com
> Mobile   (+1) 510 516 87 82
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google Groups
> "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to help+unsubscribe@wormbase.org.
>
>
>


-- 
*Anand Patwardhan*
1482, 5th Avenue
San Francisco, California  94122
Contact  anandrpatwardhan@gmail.com
Mobile   (+1) 510 516 87 82

**Comment by raymond91125** [comment]
Dear All,

I am cloning my gene in front of RAB3 (neuronal promoter). Should I clone
my gene directly after end of promoter sequence OR leave a spacer or a gap
in promoter and gene ?
In some plasmids I have, there is 50-100bp gap. For example please check
attached snapshot below. Is that purple linker necessary ?

[image: Inline image 1]
Thank you !!! :)
GOOD DAY

*Anand Patwardhan* *Postdoctoral Researcher*
*Kao*
* Lab *
675 Nelson Rising Lane,
Sandler Neurosciences Building
UCSF, California, USA 94158
*📩anandrpatwardhan@gmail.com <anandrpatwardhan@gmail.com> *
*📞(+1) 510 516 87 82*
[image: Inline image 2]


On Wed, Nov 1, 2017 at 10:16 PM, raymond <raymond@caltech.edu> wrote:

> Just to add that on the Anatomy term page for neuron
> <http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#014--10>
> <http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#014--10>
> -> Association widget -> Expression patterns. If you search for "marker",
> you'd find entries that have the word marker in Descriptions.
>
> Cheers,
>
> Raymond
>
>
>
> On 11/01/2017 05:40 PM, Anand Patwardhan wrote:
>
> Dear Chris,
>
> Thats a great explanation. I learnt  so much.
> Yes, I have sorted few promoters and looking forward to use unc-119.
>
> I am new to worm research & appreciate your help.
>
> Kind Regards,
> - Anand
>
> On Wed, Nov 1, 2017 at 5:21 PM, Grove, Christian A. (Chris) <
> cgrove@caltech.edu> wrote:
>
>> Also you may want to look at the promoters of rab-3 and unc-119, two
>> other genes considered to be expressed pan-neuronally.
>>
>>
>> Best,
>>
>>
>> Chris
>> ------------------------------
>> *From:* Grove, Christian A. (Chris)
>> *Sent:* Wednesday, November 1, 2017 5:15:42 PM
>> *To:* anandrpatwardhan@gmail.com
>> *Cc:* help@wormbase.org
>> *Subject:* Re: [wormbase-help] : How to find promoter of gene aex-3 ? ...
>>
>>
>> Hi,
>>
>>
>> As the exact limits of functional gene promoters are rarely defined
>> explicitly, upstream sequence of a given transcript is usually used as a
>> proxy for the promoter sequence. To find the promoter sequence of gene
>> aex-3, I would first recommend going to the aex-3 gene page:
>>
>>
>> http://www.wormbase.org/species/c_elegans/gene/WBGene00000086#0g9--10
>>
>>
>> You can find this page by searching for "aex-3" in the search box which
>> is set to search for genes by default. Once there, you can find a list of
>> transcripts in the first column of the table in the "Sequences" widget. To
>> the left of each transcript ID (e.g. "C02H7.3a") is a gray double helix
>> icon. Clicking on any of these icons will bring up the sequence details for
>> that transcript, including 2 kb upstream and 2 kb downstream sequences.
>>
>>
>> Another option is to use JBrowse (a link to which you can find in the
>> "Sequences" widget; click on the genomic coordinates link to the right of
>> the "Try the new Genome browser"). Find and turn on the "Curated genes
>> (protein coding)" track under the "Curated Genes" section of the JBrowse
>> track selector panel to the left. Once the track has loaded, right click on
>> the transcript for which you'd like upstream sequences. Select "View
>> Sequence", click on the OK of the warning message box that likely pops up
>> (you can ignore those messages), and you'll be presented with a tool for
>> viewing the transcript sequence and highlighting various features of it
>> including upstream sequence. At the right end of the line labeled
>> "Upstream" click on the "Select View" drop down menu and choose how much
>> sequence upstream of the transcript you'd like to view, in increments of
>> 500bp up to 4kb. Once you selected a length, click on "Highlight" and/or
>> "Lowercase" to visually distinguish this sequence from the transcript. This
>> is all demonstrated in this video:
>>
>>
>> https://www.dropbox.com/s/75ih8gqrgasqw7m/Finding_upstream_
>> sequence_of_a_gene.mov?dl=0
>>
>>
>> Let us know if you have any questions.
>>
>>
>> Chris Grove
>>
>> WormBase
>>
>>
>>
>>
>> ------------------------------
>> *From:* no-reply@wormbase.org <no-reply@wormbase.org>
>> *Sent:* Wednesday, November 1, 2017 3:58:51 PM
>> *To:* help@wormbase.org
>> *Cc:* anandrpatwardhan@gmail.com
>> *Subject:* [MARKETING] [wormbase-help] : How to find promoter of gene
>> aex-3 ? ...
>>
>> Question:
>>
>>   How to find promoter of gene aex-3 ?
>> or promoter that express in all neuron expressing.
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #5954. Follow progress on our issue
>> tracker <https://github.com/WormBase/website/issues/5954>.
>>
>> Reported by: anandrpatwardhan@gmail.com
>> 01 Nov 17 23:00
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101
>> Firefox/56.0
>>
>> This question was reported via the web interface at wormbase.org. You
>> can also email us <help@wormbase.org> directly.
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> ---
>> You received this message because you are subscribed to the Google Groups
>> "WormBase: help" group.
>> To unsubscribe from this group and stop receiving emails from it, send an
>> email to help+unsubscribe@wormbase.org.
>>
>
>
>
> --
> *Anand Patwardhan*
> 1482, 5th Avenue
> <https://maps.google.com/?q=1482,+5th+Avenue+%0D+San+Francisco,+California+%C2%A094122&entry=gmail&source=g>
> San Francisco, California  94122
> Contact  anandrpatwardhan@gmail.com
> Mobile   (+1) 510 516 87 82
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google Groups
> "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to help+unsubscribe@wormbase.org.
>
>
>


-- 
*Anand Patwardhan*
1482, 5th Avenue
San Francisco, California  94122
Contact  anandrpatwardhan@gmail.com
Mobile   (+1) 510 516 87 82
