### ISSUE TITLE
how to buy C.elegens...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5956]
*Help Desk query collected when no chat operators were online. Follow up required.*

how to buy C.elegens

**Reported by:** meng*** (1884***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/support?url=/">http://www.wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 53.0.2785.104

**Comment by Paul-Davis** [comment]
Duplicate of #5957
