### ISSUE TITLE
reference widget broken for Analysis pages

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5958]
http://staging.wormbase.org/resources/analysis/Panther
http://wormbase.org/resources/analysis/Panther

![image](https://user-images.githubusercontent.com/20523/32339219-03e277e6-bfef-11e7-9c43-6f6d5ca1029b.png)

**Comment by chris-grove** [comment]
Same problem on Expression Pattern pages:

http://www.wormbase.org/species/all/expr_pattern/Expr10#021--10
http://www.wormbase.org/species/all/expr_pattern/Expr10000#021--10
http://www.wormbase.org/species/all/expr_pattern/Marker50#021--10

**Comment by chris-grove** [comment]
Fixed on staging; see #6040
