### ISSUE TITLE
Adding a new widget on the anatomy page

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5959]
Hello Webteam, 
we discussed at today's group meeting to add a new widget on the anatomy page

http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#310--10

The widget should be below the association widget. 
Name of the widget: "Expression markers"

The widget should display the same table that is shown in the Associations widget but filtering out the Expression objects, meaning that only the 'Markers' will be displayed.

The label Expression patterns should be changed into
'Markers for this cell/tissue'

Rudimental mock-up attached.
thx
<img width="1073" alt="screen shot 2017-11-02 at 11 59 04 am" src="https://user-images.githubusercontent.com/901243/32339360-9b57ed7e-bfc5-11e7-97fb-09e0f72049da.png">

**Comment by a8wright** [comment]
@draciti I have made the rest API for pulling the data out of Datomic. The logic currently pulls all the expr-pattern entities that are linked to the anatomy-term entity you are on and then the "gene" field is pulled directly off of that and the description is pulled from the "pattern" field. Does this sound correct. Does this sound correct? An alternative for the "gene" column would be to pull from the "reporter-gene" field. I am not sure which would be correct. Also I don't know of an alternative for getting the description. Is it correct to pull this from the "pattern" field? And for the "Certainty" column, do you know where this information should be pulled from?

**Comment by draciti** [comment]
thanks Adam-
the logic sounds correct. Please note: should pull all the expr-pattern entities that are linked to the anatomy term entity but display only the ones that have Marker in the object name. Good to pull gene from the 'Gene' Field associated to the expression object and to pull description from the 'pattern' field. for the certainty column, the info is in the 'Anatomy_term' field.  See example .ace below:

Expr_pattern : "Marker50"
Anatomy_term	"WBbt:0003679" Certain
Construct	"WBCnstr00001568"
Gene	"WBGene00006843"
Pattern	"Expressed in all neurons."
Reference	"WBPaper00004727"
Reflects_endogenous_expression_of	"WBGene00006843"
Remark	"Picture: Fig. 6A."
Remark	"Reporter gene fusion type not specified."
Reporter_gene
Transgene	"WBTransgene00001578"

What I was proposing when I opened the ticket was to use the same table that is in the association widget but displaying only Markers (not sure if it is doable):
_'The widget should display the same table that is shown in the Associations widget but filtering out the Expression objects, meaning that only the 'Markers' will be displayed.'_

thanks!
Daniela

**Comment by sibyl229** [comment]
Hi @draciti does the Marker widget look right http://staging.wormbase.org/species/all/anatomy_term/WBbt:0003679#310--10 ?

**Comment by sibyl229** [comment]
Hi @a8wright You can extract the certainty from the qualifier schema: https://github.com/WormBase/pseudoace/blob/master/generated-schemas/schema262.edn#L2224

**Comment by draciti** [comment]
Hi Sibyl, the widget displays all the expression objects as of now. It should display only the ones that have 'Marker' in the object name, e.g. 

Marker50 | unc-119 | Expressed in all neurons. |  
Marker39 | unc-119 | Expressed in all neurons. |  
Marker119 | unc-33 | Marker for all neurons. |  
Marker118 | rgef-1 | Marker for all neurons.

**Comment by a8wright** [comment]
@draciti I have updated it to show the string that is in the "certain" field on the "qualifier" entity. How do we know when to show information in the "uncertain" field? Could you give some context to what this means?

**Comment by draciti** [comment]
If you pull  the string from the "qualifier" entity it will show 'uncertain' in the "certainty" column.
Hope it makes sense.

**Comment by a8wright** [comment]
@draciti Thanks for explaining. I actually came across this in other endpoints that I was developing - it is updated everywhere we are using certainty, on staging!

Feel free to close the ticket if you are satisfied

**Comment by draciti** [comment]
also the marker widget display just partial, FYI
http://staging.wormbase.org/species/all/anatomy_term/WBbt:0003679#3102--10

**Comment by a8wright** [comment]
can you check again. I had the database set to WS262 still. I wasn't switching right away because I was pushing things to production to fix 500 errors, at first. Matt pointed this out to me. This morning I got WS263 setup and running on staging. I will get a chance to go through all the things we talked about in a few hours. Feel free to check earlier if you like - suspect that it will be much better!

**Comment by draciti** [comment]
thanks Adam, the certainty column displays fine on the expression markers table but now the 'Expression patterns' table on the 'Associations' widget is gone. It should stay, as on the live site

http://www.wormbase.org/species/all/anatomy_term/WBbt:0003679#3102--10

**Comment by a8wright** [comment]
should be good now

**Comment by draciti** [comment]
yep! looks good. Shall I wait to close until you do more testing? At my end everything looks good

**Comment by a8wright** [comment]
I will close it then - thanks. I don't anticipate anything more. I had tested on many URI's over the past couple of days. If there is an issue I expect it be from the changes to the database schema. I will be checking though the code for more of these later today. I think that could be counted as separate from this issue though. Nice working with you!

**Comment by draciti** [comment]
same here :) thanks @a8wright
