### ISSUE TITLE
visitor_name (visitor_email): The website is actin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5960]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): The website is acting glitchy again.  Searches are timing out.</br>Chris: Hi visitor_name, sorry to hear. Let me make sure our developers are aware of the issue</br>visitor_name (visitor_email): Thanks.</br>Chris: Yes, I'm experiencing the same issues</br>Chris: Our team is working on a fix now</br>Chris: I'll write you an email as soon as we are stable again. Is that OK?

**Reported by:** Dona** (ddwy*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 62.0.3202.75

**Comment by chris-grove** [comment]
Site is slow to load and often timing out

**Comment by chris-grove** [comment]
Hi Donard,


 I think we've identified the problem and implemented a fix, so the website should be more stable now.


Apologies for the inconvenience. Please let us know if you experience any more issues.


Thanks for the feedback and thanks for your patience.


Best,


Chris Grove

WormBase
