### ISSUE TITLE
Interactions file on FTP site missing second interactor for self-self interactions

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5961]
It seems that self-self interactions, where a gene regulates itself or physically interacts with itself, are not being properly populated in the interaction FTP file. Looking at this file:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS262/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS262.interactions.txt.gz

I see that, for example, WBInteraction000525240 is only displaying a single interactor, tbx-2, as a trans-regulator. This interaction is in fact a self regulation where tbx-2 plays the role of both the trans-regulator AND the trans-regulated. This fact is properly captured in the curation database, properly dumped in the .ACE file, is represented properly in ACEDB (WS262), and is displayed (mostly) properly on the website:

http://www.wormbase.org/species/all/interaction/WBInteraction000525240#06--10

but not properly in the FTP file. Another example is WBInteraction000523905, a physical protein-protein interaction between HLH-1 and itself. This self interaction is represented on the website:

http://www.wormbase.org/species/all/interaction/WBInteraction000523905#06--10

but in the FTP interactions file hlh-1 is only listed once as the bait interactor, not also as the target as it should be.

**Comment by epaule** [comment]
I fixed the scripts and push out an updated file for WS262, don't think @tharris would appreciate fixes for WS261 at the moment.

**Comment by epaule** [comment]
will fix it on Monday, as our FTP server is r./o. at the moment

**Comment by chris-grove** [comment]
Fixed
