### ISSUE TITLE
updated interaction file for WS262

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5966]
hia,

because of  #5961 and #5962 (from @chris-grove ) I updated the WS262 version of the interaction file (and the CHECKSUM).
It is here (and needs syncing to WormBase FTP central): ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS262/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS262.interactions.txt.gz

thanks,

M

**Comment by chris-grove** [comment]
@epaule 
Thanks for that. However, I don't see fixes implemented for either issue. Physical interactions subtypes are still not showing and those self-self interactions are still only showing one interactor. Am I missing something?

**Comment by epaule** [comment]
erm ... can you give the FTP server 60 minutes to sync (which would be another 20)?

**Comment by chris-grove** [comment]
@epaule 
OK, I waited about 4 hours and checked the file again, but it still has the same problems.

**Comment by epaule** [comment]
thanks @chris-grove for reporting. 
Our systems team has been informed about the broken FTP sync.

**Comment by epaule** [comment]
@chris-grove try again

**Comment by epaule** [comment]
maybe we could still do that in the WS262 release cleanup?

**Comment by sibyl229** [comment]
Hi @tharris , did the FTP sync happen? Can this issue be closed?

**Comment by tharris** [comment]
Synced. Closing...
