### ISSUE TITLE
Hi! Do you happen to know which part of the gene t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5967]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! Do you happen to know which part of the gene the dpy-10 mutation occurs? Thank you!

**Reported by:** Mega* (free*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 61.0.3163.100

**Comment by tuli** [comment]
Dear Megan,

Thank you for writing to WormBase.

WormBase lists a number of mutations within the dpy-10 gene.

If you go to the dpy-10 summary page and then the Genetics widget you
will see a table which gives the molecular details if they are
available. You can click on the allele of interest which
will take you to the allele summary page where you can see the precise
location of the lesion.

I hope this answers your query.

Best wishes,

Mary Ann
