### ISSUE TITLE
  Good afternoon We've a question about...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5969]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good afternoon<br/>We've a question about the genomic sequence of Fasciola hepatica (PRJEB6687)...why can we find that a same code has many entries? <br/>For example:<br/>>s10053B020.mRNA-4 transcript=s10053B020.mRNA-4 gene=s10053B020<br/>MASLMDIQVTDPNELIDVICKDCWRLCDF<br/>>s10053B020.mRNA-1 transcript=s10053B020.mRNA-1 gene=s10053B020<br/>MPPYGNIVMDVPYSLPKNPDTVVMLYTLITPRWCHQLRRYHSKRFKARRLHVYL<br/>>s10053B020.mRNA-2 transcript=s10053B020.mRNA-2 gene=s10053B020<br/>ESHEQQLRSCGIPEHFWKKLHEKLQNESYDAHQHVMLHRVEYLDNDDNVNNSLDLFDWQV<br/>TVCSEELSYSDPDCIFLVDHAWTFEPGSIRESLEKVPGLKDRMASLMDIQVTDPNELIDV<br/>ICKDCWR<br/>>s10055B020.mRNA-1 transcript=s10055B020.mRNA-1 gene=s10055B020<br/>MLTGDGLGPEFMGYVREVYQLLGAQVDFEEINVNQDCDETTFLDALLAMKRNGVGIKGNF<br/>ATEPGQSSRNLALRVQLNLYAFVQHCRNFPGIKTRHDNVDIVIIRENTEGEYSR<br/>It's the same code (s10055B020) but it has 4 differents transcripts. I was analyzing the whole genomic sequence and I found many times this situation. Is there any explanation?</p>

**Reported by:** Mari********** (mari**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by azurebrd** [comment]
Responded by Kevin Howe : 
Dear Maria, 

It's quite common for genes to have multiple transcripts (and resulting peptide sequences) due to alternative splicing. In this case, the gene has 4 alternatively spliced products. 

In our database, the ids for F. hepatica (PRJEB6687) look like this:

>BN1106_s9918B000014.mRNA-1 transcript=BN1106_s9918B000014.mRNA-1 gene=BN1106_s9918B000014

>BN1106_s9918B000014.mRNA-2 transcript=BN1106_s9918B000014.mRNA-2 gene=BN1106_s9918B000014

>BN1106_s9918B000014.mRNA-3 transcript=BN1106_s9918B000014.mRNA-3 gene=BN1106_s9918B000014

>BN1106_s9918B000015.mRNA-1 transcript=BN1106_s9918B000015.mRNA-1 gene=BN1106_s9918B000015

>BN1106_s992B000186.mRNA-1 transcript=BN1106_s992B000186.mRNA-1 gene=BN1106_s992B000186

>BN1106_s992B000187.mRNA-1 transcript=BN1106_s992B000187.mRNA-1 gene=BN1106_s992B000187


Where exactly did you get the file containing the 4 protein sequences below? The identifiers lack the "BN1106" prefix present in our entries. 
Best,
