### ISSUE TITLE
I'm looking for the sequences of all alcohol dehyd...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5972]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'm looking for the sequences of all alcohol dehydrogenase genes of the species on WormBase. Would be very grateful if you could indicate as to how I may procure same!

**Reported by:** Pól ************** (pol.**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00010790#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00010790#0-9g-3</a>
**Browser:** Firefox 56.0

**Comment by chris-grove** [comment]
Hello Pól,

There are a few ways to get the list of genes that have been annotated as alcohol dehydrogenase genes.

1) First, if you're looking for C. elegans genes only, you can use the following query in WormMine:


<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.goAnnotation.evidence.code.code Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">   <constraint path="Gene.goAnnotation.ontologyTerm.namespace" code="A" op="=" value="molecular_function"/>   <constraint path="Gene.goAnnotation.ontologyTerm.name" code="B" op="CONTAINS" value="alcohol dehydrogenase"/> </query>

Just go to WormMine (link available in the Tools menu), click on the "QueryBuilder" tab, click on "Import query from XML", paste the XML query above into the box, and click Submit. You should then be directed to a constructed query. Click on "Show results" and you will be shown a table of C. elegans genes that have been annotated to any Gene Ontology term from the Molecular Function branch that contains the text "alcohol dehydrogenase" in the name of the term.


If you'd like a list of all alcohol dehydrogenase genes in all WormBase nematode species (from our "core" genomes/species), you can use one or more of the following approaches:


2) In the WormBase search box, select to search "for a go term" from the dropdown menu of data types to search for. Type into the search box "alcohol dehydrogenase" in double quotes to search for the exact phrase. Press ENTER or click on the magnifying glass search icon to perform the search. You should then be shown a results page with 24 matching GO terms, the first 20 of which have the exact phrase "alcohol dehydrogenase" in the term name. Check each of those (20) pages for associations/annotations to WormBase genes. For example, on the page for the GO term "alcohol dehydrogenase (NAD) activity":


http://www.wormbase.org/species/all/go_term/GO:0004022#012--10


there is a list of 6 nematode genes (1 from Caenorhabditis remanei, 5 from Caenorhabditis elegans) in the "Associations" widget "Genes" table.


3) In the WormBase search box, select to search "for a gene" (default) from the dropdown menu of data types to search for. Type into the search box "alcohol dehydrogenase" in double quotes to search for the exact phrase. Press ENTER or click on the magnifying glass search icon to perform the search. You should see 4 genes that come back as results. Note that this type of search is usually limited as it only searches for the exact text somewhere in the gene's description.


4) In the WormBase search box, select to search "for anything" from the dropdown menu of data types to search for. Type into the search box "alcohol dehydrogenase" in double quotes to search for the exact phrase. Press ENTER or click on the magnifying glass search icon to perform the search. Once the search results appear, click on the "Classes" header in the left side panel on the results page. Click on "Motif: 29". This will show you a list of 29 protein motifs in WormBase (from InterPro and PFAM) that contain the exact phrase "alcohol dehydrogenase" in the name of the motif. You can check each of these pages for genes that are predicted to have any of these motifs. For example, on the motif page for "Alcohol dehydrogenase, iron-type":

http://www.wormbase.org/resources/motif/INTERPRO:IPR001670#01--10

You can see a list of all WormBase nematode proteins that are predicted to have that particular motif in the "Homologs" table of the "Overview" widget.

Unfortunately, these search methods won't be entirely comprehensive as it will miss GO terms, motifs, and genes that exclusively mention, for example, "methanol dehydrogenase", which could be considered a subtype of alcohol dehydrogenase.


I hope that helps. Please let us know if you have any additional questions or concerns.


Best,


Chris Grove

WormBase
