### ISSUE TITLE
  WBPerson13192 is me but I am unable t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5974]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WBPerson13192 is me but I am unable to actually see and access my account for any edits. Could you please help me sort that out?<br/>Kind regards,<br/>visitor_name </p>

**Reported by:** Soud************* (soud***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by chris-grove** [comment]
Hello Soudabeh,


You can view your WormBase person page here:


http://www.wormbase.org/resources/person/WBPerson13192#03124--10


To make edits to your personal information as it is stored in WormBase, please use this form:


http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person.cgi?action=Query&number=two13192\


Let us know if you have any other questions or concerns.


Best,


Chris Grove

WormBase
