### ISSUE TITLE
  Hello, I am looking to download an an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5979]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am looking to download an annotated reference genome for small RNAseq analysis.  I need it to be annotated for at least miRNAs, piRNAs, and if possible siRNAs.  Really one that had small non-coding RNAs in general would be ideal but I'm not sure how realistic that is.  Is that information accessible through this site?  Thanks for your time,<br/>-Nicole</p><p>What were you doing? <br />&nbsp;&nbsp;I have downloaded both the RNAseq track and annotated genes track via the genome browser, but not sure thats what I'm looking for</p>

**Reported by:** Nico************** (nkur****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by epaule** [comment]
did you have a look at the Download section?
Notably here: http://www.wormbase.org/species/c_elegans

There should be a link to the genomic sequence as well as the GFF3 file with the annotation.
Basically almost all the tracks you see in the Genome Browsers on WormBase should be in there. Notably the ncRNA genes (including miRNAs , piRNAs, etc.) should be there, identifiable by their SO-terms.
