### ISSUE TITLE
  How do I cite wormbase? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5982]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I cite wormbase?</p>

**Reported by:** jeco*********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by raymond91125** [comment]
http://www.wormbase.org/about/citing_wormbase#0132--10

On 15/11/17 08:32, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I cite wormbase?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5982. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5982>.
>
> Reported by: jecoleman1@eagles.usi.edu
> 15 Nov 17 16:32
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/61.0.3163.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
