### ISSUE TITLE
  I am cloning my gene in front of RAB3...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5985]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am cloning my gene in front of RAB3 (neuronal promoter). Should I clone my gene directly after end of promoter sequence OR leave a spacer or a gap in promoter and gene ?<br/>In some plasmids I have, there is 50-100bp gap</p><p>What were you doing? <br />&nbsp;&nbsp;Cloning in C elegans vector.</p>

**Reported by:** Anan* (anan*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by chris-grove** [comment]
Hello Anand,


 In my experience, it is not necessary to add any "gap"/"linker" between the promoter and the gene. You may reach a broader audience by posting your question on the WormBase Community Forum:


http://forums.wormbase.org/


If you don't have an account already, you'll need to register to post questions, but then you can ask your question to a larger audience of C. elegans/nematode biologists.


Best,


Chris Grove

WormBase
