### ISSUE TITLE
visitor_name (visitor_email): how can I find pheno...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5986]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): how can I find phenotype of this: smd-1 RNAi</br>visitor_name (visitor_email): Got it

**Reported by:** Grac* (grac*****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search?q=smd-1 RNAi">http://www.wormbase.org/search?q=smd-1 RNAi</a>
**Browser:** Chrome 62.0.3202.94

**Comment by chris-grove** [comment]
Hello Grace,


 It sounds like you found what you were looking for. Please let us know if you have any more questions.


Best,


Chris Grove

WormBase
