### ISSUE TITLE
visitor_name (visitor_email): Hi! I am blasting so...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5989]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi! I am blasting some of the plasmid sequences and I am new with wormbase.</br>visitor_name (visitor_email): Can you suggets me how to extract more info from here?

**Reported by:** Sham*********** (ssin*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run">http://www.wormbase.org/tools/blast_blat/run</a>
**Browser:** Safari 11.0.1

**Comment by chris-grove** [comment]
Hello Shambhavi,


 What information are you looking to extract? The results of a BLAST search in WormBase should give you a list of nematode genes or proteins with highest sequence similarity. Any sequences from your plasmid that are not of nematode origin will likely not return any meaningful results using WormBase BLAST.


Let us know what you're looking for.


Best,


Chris Grove

WormBase
