### ISSUE TITLE
Im having a hard time locating a few things for th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5991]
*Help Desk query collected when no chat operators were online. Follow up required.*

Im having a hard time locating a few things for the SLO-1, isoform j. If you could help me it would be very much appreciated. One would be -	What gene is this mutant defective in? the second is -	What does the protein encode? and the last is what is the mutation in the DNA and what is the consequence on the protein. 
Again, if you are able to aid me in finding this information I would greatly appreciate it.

**Reported by:** Dure********** (colv*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/protein/WP:CE47368#06842--10">http://www.wormbase.org/species/c_elegans/protein/WP:CE47368#06842--10</a>
**Browser:** Chrome 62.0.3202.94

**Comment by raymond91125** [comment]
Hi Dureese,

You're inquiry looks like an incompletely specified home work problem. 
In general, we prefer not to give students direct answers to their home 
work problems as that would be robbing them from their opportunity to 
learn. But we are happy to help if there are questions about how to use 
WormBase.

Thus, if you have any WormBase usage questions, please write us back.

Cheers,

Raymond


On 17/11/17 08:20, no-reply@wormbase.org wrote:
> offline chat Im having a hard time locating a few things for the 
> SLO-1, isoform j. If you could help me it would be very much 
> appreciated. One would be - What gene is this mutant defective in? the 
> second is - What does the protein encode? and the last is what is the 
> mutation in the DNA and what is the consequence on the protein. Again, 
> if you are able to aid me in finding this information I would greatly 
> appreciate it.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/protein/WP:CE47368#06842--10 
> http://www.wormbase.org/species/c_elegans/protein/WP:CE47368#06842--10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/protein/WP:CE47368#06842--10> 
>
>
> This issue has been assigned ticket number: #5991. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5991>.
>
> Reported by: Dureese Colvin (colvindureese@gmail.com)
> 17 Nov 17 16:20
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
