### ISSUE TITLE
  Starting the Genome Decoders project ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5994]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Starting the Genome Decoders project with my A Level Biologists.  My IT dept has set up an account for me iris@st-francis.herts.sch.uk and a password, but can't access the site with this.  Any advice would be appreciated.<br/>Thank you,<br/>Julia Glanville (Head of Biology at St. Francis' College)</p>

**Reported by:** jgla******************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by khowe** [comment]
Responded to user off-line.
