### ISSUE TITLE
Variations without species throwing error in "Location" widget on variation page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5995]
I'm labeling this as a web team issue, but it could be a data issue. I suppose even if it is a data issue, the web page could have a better way of handling it.

I was querying WS262 ACEDB to see how many variation objects are not affiliated with a species, and when I checked their respective pages on the live WormBase site I noticed that they were all throwing errors in the "Location" widget. For example on the page for WBVar02147713:

http://www.wormbase.org/species/all/variation/WBVar02147713#02-458-10

the Location widget looks like this:

![screen shot 2017-11-20 at 5 42 46 pm](https://user-images.githubusercontent.com/611382/33045271-45b8da82-ce1a-11e7-96a0-b9c878b2edc1.png)

Similarly, on the page for WBVar02125727:

http://www.wormbase.org/species/all/variation/WBVar02125727#02-458-10

I get the same error. In these two examples, the variations apparently have no species, even though they are both affiliated with C. elegans genes (cha-1 and ced-1, respectively). In another case, WBVar00145397:

http://www.wormbase.org/species/all/variation/WBVar00145397#02-458-10

the variation has been merged into another variation. Other examples of variations without a species that throw the error:

WBVar02125338
WBVar02125339
WBVar02125340
WBVar02141322
WBVar02146350
WBVar02141319

Strangely, WBVar02148530 exists in WS262 (affiliated with WBGene00000962 (dhc-1), but no species), but doesn't show up on live WS261 or staging WS262 WB website.

The solution may be to make sure that all variations have a species (they should in theory).

**Comment by khowe** [comment]
This is partly a data issue, but yes @chris-grove, probably the sensible behaviour to to default to C. elegans for any object that does not have the Species tag populated. 

There are nearly 200 "Live" vars that do not have Species populated. Will fix this for WS263. 

There are many Dead vars (killed, or merged into other vars) that also have no Species populated, but this is intentional - we strip much of the primary information out of these object, and just retain a forwarding reference to the object that it's been merged into.

**Comment by chris-grove** [comment]
@khowe  OK thanks for the explanation. I would guess that in the instances where we strip everything except the forwarding reference we'll want to have a mechanism to display an empty Location widget, or at least something without the glaring error message.

**Comment by Paul-Davis** [comment]
@khowe it doesn't seem that this was patched for WS263 but I have patched all Live variations ready for WS264. Should I get @epaule to patch for WS263? All were elegans based on the associated Strain or Gene information (28 were ancient from the WB Gazette so assumed elegans).

**Comment by Paul-Davis** [comment]
Actually WS263 has no Live Variations with no species so looks good for WS263 so must have been patched but not fed back into geneace.
