### ISSUE TITLE
Wrong gene shown in Location widget on protein page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5996]
I noticed that on the "UNC-13 isoform a" protein page:

http://www.wormbase.org/species/c_elegans/protein/WP:CE15371#04--10

only a portion of the mrck-1 gene is being displayed in the Location widget:

![screen shot 2017-11-21 at 5 13 23 pm](https://user-images.githubusercontent.com/611382/33099579-53cea848-cedf-11e7-940a-05d66a16e097.png)

mrck-1 is on chromosome V and unc-13 is on chromosome I. Not sure what's going on here.

**Comment by scottcain** [comment]
This is pretty clearly not a genome browser issue. Can someone check the database that it's getting served from (datomic or acedb) @a8wright or @sibyl229. I'm wondering if the data are correct before it gets to catalyst

**Comment by a8wright** [comment]
@scottcain Thanks for your help earlier today. I found the issue... or at least the main issue. 

@chris-grove I believe this is fixed. The exact issue you noticed has been fixed (on staging). If you notice anything else please let me know.

**Comment by chris-grove** [comment]
@a8wright 
Yep, looks good! Thanks!
