### ISSUE TITLE
Interactions widget not loading on daf-12 gene page

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5999]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;</p><p>What were you doing? <br />&nbsp;&nbsp;looking for interactors of daf-12 in gene page</p>

**Reported by:** elia**********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by chris-grove** [comment]
Confirmed problem loading the Interactions widget on the daf-12 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000908#08--10

![screen shot 2017-11-27 at 5 27 43 pm](https://user-images.githubusercontent.com/611382/33292741-4d750f24-d398-11e7-97e6-560cf3673ac1.png)

daf-12 does have a lot of interactions (417), but not more than some other genes like daf-2 (890) that don't have trouble loading the Interactions widget.

**Comment by chris-grove** [comment]
Also failing to load on staging

**Comment by chris-grove** [comment]
Hello Elia,


 Thank you for reporting the problem and apologies for the inconvenience. I can confirm that the interactions widget is not loading properly on the daf-12 gene page. We are working on a solution to the problem now.


In the meantime, please let us know if there are specific questions you have about daf-12 interactions and we may be able to get that information to you directly.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
daf-12 Interactions widget now loads on live WS262, but the Cytoscape network viewer is timing out

**Comment by chris-grove** [comment]
OK, loading now. Closing
