### ISSUE TITLE
I would like to programmatically download the fast...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6000]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to programmatically download the fasta sequences of some transcripts for which I have the identifiers (for instance K06C4.12). I have trouble navigating the documentation for developers (http://www.wormbase.org/about/userguide/for_developers). For instance,  http://rest.wormbase.org/ doesn't seem to exist.

Based on the example found at http://www.wormbase.org/about/userguide/for_developers/API-REST, I manged to form this URL: http://www.wormbase.org/rest/widget/transcript/K06C4.12/overview but then I don't know how to proceed to download the " &gt;K06C4.12 spliced + UTR" fasta sequence as proposed in http://www.wormbase.org/species/c_elegans/transcript/K06C4.12

Where is the detailed and up-to-date documentation?

Thank you in advance for your help.

**Reported by:** Blai***** (blai****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_developers#3--10">http://www.wormbase.org/about/userguide/for_developers#3--10</a>
**Browser:** Firefox 57.0

**Comment by sibyl229** [comment]
I answered the user here, but please feel free to add anything I missed: https://github.com/sibyl229/wb-graphql/issues/4#issuecomment-346859203

**Comment by mgrbyte** [comment]
rest.wormbase.org is now resolving again, we had a technical issue with the name resolving service.
