### ISSUE TITLE
Location column in Genetics widget (on gene and pseudogene pages) not specifying which transcript or gene that the location applies to

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6002]
As alluded to in #5837 by @khowe 

"""
There is actually a small bug (IMO) in the "Alleles with phenotypes" table in the Genetics widget on the gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00021561#0-4-10

In the "Locations" column, it states both "Coding exon" and "Intron". This is misleading, because the "Coding_exon" location is for a different gene. The fix for this would be to only state the locations for the transcripts associated with the gene you are looking it. It would then be clear(er) to the user that the association between the gene and allele is only intronic...
"""

This appears to be an issue on gene page and pseuodgene page Genetics widgets. Here's an example of a pseudogene page:

http://www.wormbase.org/species/c_elegans/pseudogene/M117.8#2--10

The problem is that the Location column in the Genetics widgets is displaying all transcript/gene regions that are affected by (or overlap with, I presume) the variation in question, for all transcripts/genes affected without specifying which transcript(s) or gene(s). So when multiple regions are listed it's impossible to know which transcript/gene it is referring to. 

The example that came up originally in the thread for #5837 was for allele gk849:

http://www.wormbase.org/species/c_elegans/gene/WBGene00003704#4--10

which affects the coding region of nhr-114 but only the intron of Y45G5AM.9. I think it would be good to include the transcript and/or gene in the Location column to indicate which region refers to which transcript/gene, or filter the regions to only show those that apply to the gene/pseudogene whose page you're on.

**Comment by sibyl229** [comment]
Hi @chris-grove  Does the location and protein effect columns look fixed? I kept only #Molecular_changes associated CDS, transcript, gene, pseudogene that correspond to the current gene or pseudogene.
http://staging.wormbase.org/species/c_elegans/gene/WBGene00021561#0-4-10
http://staging.wormbase.org/species/c_elegans/pseudogene/M117.8#2--10
http://staging.wormbase.org/species/c_elegans/gene/WBGene00003704#4--10

I wonder if #5132 is about the same issue?

Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
It looks great! Thanks!

As for #5132 it's a separate issue. That issue has to deal with how phenotypes are displayed and making it clear in the phenotype display all of the genes affected and how they are affected.

**Comment by chris-grove** [comment]
@sibyl229 
Yes, you're right about #5132 
That problem is also now fixed. Thanks again!!
