### ISSUE TITLE
Overview widget not loading on variation page for gk962765

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6003]
On the variation page for variation gk962765:

http://www.wormbase.org/species/c_elegans/variation/WBVar01498996#0--10

The Overview widget does not load, presumably because it is trying to list all 14,470 genes affected by the tandem duplication. It would be good if we had a mechanism to detect the number of genes and present a default message indicating that there are too many genes to show, as in the "Genetics" and "Molecular Details" widgets:

http://www.wormbase.org/species/c_elegans/variation/WBVar01498996#025--10

**Comment by khowe** [comment]
An data fix for this would be to not create associations to genes for "large" variations.

**Comment by sibyl229** [comment]
@chris-grove what would be a good cutoff for too many genes? Thanks

**Comment by chris-grove** [comment]
I queried WS263 to see how many variations have large numbers of genes associated. Here's an Excel spreadsheet with the ranked list:

https://www.dropbox.com/s/jbvdswiocdf4bax/WS263_variations_mapping_to_more_than_three_genes.xlsx?dl=0

It seems that the Overview widget can actually handle as many as 9,741 genes:

http://www.wormbase.org/species/c_elegans/variation/WBVar01499697#01234567--10

but times-out when we get up to 13,924:

http://www.wormbase.org/species/c_elegans/variation/WBVar01499925#01234567--10

so I guess an practical empirical limit would be 10,000. It does feel a bit silly to be copy/pasting a list of 10,000 gene names from the Overview widget. I think it would be a great feature on the site that whenever there is a large list of objects, there would be an option to download (or copy to the clipboard) the list of primary identifiers. I think telling users to go to WormMine (without any further instruction) is not exactly helpful, especially since I just found that WormMine isn't capturing all the genes for an allele (I will make a ticket).

**Comment by chris-grove** [comment]
Here's a Google spreadsheet of the same list:

https://docs.google.com/spreadsheets/d/18eymesE5jfMFphuYsr7gB4QaAjTtU9L7eM11sJx_Pzo/edit?usp=sharing

**Comment by sibyl229** [comment]
Hi @chris-grove you can now download a list of genes from variation overview when the number of genes is greater than 20: http://staging.wormbase.org/species/c_elegans/variation/WBVar01498996#0--10
Does that work?

Hi @khowe I think the data for corresponding genes is fine. It's the rendering of HTML that caused the timeout.

**Comment by chris-grove** [comment]
@sibyl229 
Yes! That's great! The file that I download doesn't appear to have any delimiters or newlines, though, making it impossible to parse. Can you make it tab-delimited with standard newlines?

**Comment by chris-grove** [comment]
Sorry, not impossible (one could parse on the text "WBGene", but it's a little sloppy)

**Comment by sibyl229** [comment]
@chris-grove I'm sorry. That wasn't the intended behaviour. Thanks for caching that. It should be working now: http://staging.wormbase.org/species/c_elegans/variation/WBVar01498996#0--10

**Comment by chris-grove** [comment]
@sibyl229 
Yes! Perfect! Thanks Sibyl!!
