### ISSUE TITLE
Orthology question pertaining to Gene avr-14

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/website#6004]
Question from a user (via email):

By digging through the references for avr-14, Daniel Shaye and Iva Greenwald’s PLoS One article in 2011 (doi: 10.1371/journal.pone.0020085) cited their work on OrthoList. I believe that the wormbase webpage for avr-14 has an error as introducing avr-14 to be homologous to human GLRA2. 

On the OrthoList database/website from the greenwald lab (http://www.greenwaldlab.org/ortholist/), avr-14 is actually listed as orthologous to the entire family of GLRA genes, of which GLRA1 was identified by 3 out of the 4 programs (Ensembl Compara, Homologene, OrthoMCL) in meta-analysis, the most out of the GLRA family.

Of note, GLRA1 is the only human ortholog of avr-14 identified by Homologene, sited by the authors as more “specific”, or had fewer false-positives in both phylogenetic and functional tests.

I believe that GLRA1, rather than GLRA2, was should be intended as a the gene avr-14 is more orthologous to.

**Comment by epaule** [comment]
the description was hand-written by Carol and has two papers attached.

**Comment by chris-grove** [comment]
Hello Joseph,


I assume you are referring to the text in the gene description:


"avr-14 encodes an alpha-type subunit of a glutamate-gated chloride channel homologous to human GLRA2..."


My colleagues that work on homology and orthology for WormBase may like to comment further, but I'd like to point out that although one could argue that GLRA2 may not be the best called human ortholog of avr-14, that doesn't mean that avr-14 is not in any way homologous to GLRA2. The statement made above does not say "most homologous to" or "orthologous to".


I believe this information was originally gleaned from WBPaper00004103:

Culetto E, Sattelle DB. A role for Caenorhabditis elegans in understanding the
function and interactions of human disease genes. Hum Mol Genet. 2000 Apr
12;9(6):869-77. Review. PubMed PMID: 10767309.

In Table 1 of this paper, in the line referring to "Hyperekplexia", the authors note homology between human GLRA2 and B0207.12 (avr-14):


https://academic.oup.com/hmg/article/9/6/869/618668


As orthology calling can involve many factors, WormBase has not explicitly called any particular human GLRA gene as the definitive ortholog. Of note, you may also want to look at the Alliance of Genome Resources (AGR; a new collaborative database project involving WormBase and other model organism databases) website for the avr-14 gene page:


http://www.alliancegenome.org/gene/WB:WBGene00000232


In the "Orthology" section, best matches are presented from 7 different ortholog calling methods. 5 out of these 7 methods find that GLRA3 and GLRA4 are likely the best candidates for orthologs to avr-14.


Both WormBase and AGR have yet to incorporate orthology criteria other than sequence similarity into their pipelines, but plan to do so in the future.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Will reopen if necessary...
