### ISSUE TITLE
  Just a comment that the references se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6005]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Just a comment that the references section of the gene cep-1 says there are no references for the gene.  </p>

**Reported by:** Lisa********* (lisa****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by chris-grove** [comment]
Hi Lisa,


Thanks for your feedback. When I check the cep-1 gene page:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000467#0e--10


I see a list of 182 papers, including 108 journal articles and 9 reviews. On which page are you seeing no references for cep-1?


Thanks!


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Hi Christian,

It must of been a weird bug on my end.  I was looking at the same page you sent and even when I used your link I still saw no references.  Although if I looked at another gene say lin-35 there were references.  I restarted my browser and now I can see them.  Sorry for the false lead.

Lisa
