### ISSUE TITLE
  Hi, I am trying to identify all genes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6008]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am trying to identify all genes, mutations in which have a specific phenotype (WB Phenotype:0001639, "roaming reduced"). I tried the few obvious things, but they did not seem to work. Would appreciate general as well as specific hep. <br/>Thanks! Ilya</p>

**Reported by:** Ilya********* (ilya**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

**Comment by mgrbyte** [comment]
Hi,
I believe to get the listing you want you can:
 * Enter `WBPhenotype:0001639` in the search box and select "phenotype" from the drop down list.
 * On the resulting phenotype page, there should be a "Variations" widget, listing all the genes in a table.
   (Select the variations widget from the left-hand pane if not)

In order to extract a listing, you can click "Save table", then export the data in CSV format.
_Please note you'll need to enable Flash player support in your web browser for the "save table" function to work_

**Comment by chris-grove** [comment]
Hi Ilya,


 Just to add to my colleague's advice, you may also find a list of genes that exhibit the phenotype (or any of the phenotype's ontological "is a" descendants (child terms)) by looking in the "Ontology Browser" widget:


http://www.wormbase.org/species/all/phenotype/WBPhenotype:0001639#0635--10


In the case of the "roaming reduced" phenotype, there are 75 gene products that have been annotated to the phenotype. You can get the list of genes by clicking on the "75 gene products" next to the"roaming reduced" phenotype in the "Ontology Browser" widget. If applicable, you may also find transgenes and RNAi experiments associated with the phenotype in the respective widgets.


Let us know if you have further questions.


Best,


Chris Grove

**Comment by raymond91125** [comment]
Hi Ilya,

On the phenotype page 
<http://www.wormbase.org/species/all/phenotype/WBPhenotype:0002315#03--10>, 
there is an Ontology Browser widget. In that, to the right of the 
green-colored focus term, there is a number (75, specifically) of gene 
products. If you click on that hyperlink, you will get lists of genes 
(75 by variation, 0 by RNAi).

Perhaps for your inquiry, you may also be interested in the parent term 
"roaming variant" of 205 genes that include additionally those that are 
"roaming increased".

Best regards,

Raymond




On 29/11/17 02:09, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> I am trying to identify all genes, mutations in which have a specific 
> phenotype (WB Phenotype:0001639, "roaming reduced"). I tried the few 
> obvious things, but they did not seem to work. Would appreciate 
> general as well as specific hep.
> Thanks! Ilya
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6008. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6008>.
>
> Reported by: Ilya Ruvinsky (ilya.ruvinsky@northwestern.edu)
> 29 Nov 17 10:09
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
