### ISSUE TITLE
Finding protein complexes for C. elegans

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6010]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Hyundoo, how can I help?</br>visitor_name (visitor_name@tamu.edu): Hello</br>visitor_name (visitor_name@tamu.edu): May I ask you a question for WormBase?</br>Chris: Sure!</br>visitor_name (visitor_name@tamu.edu): In fact, I am trying to find a protein functional complex for C. Elegans. However, I have a difficulty to find it in the database.</br>visitor_name (visitor_name@tamu.edu): Can you help me where can I find the functional complex for the Cel? Functional complex means the list of proteins (or genes) to play a particular function.</br>Chris: OK, WormBase does not currently curate protein complexes, but let me know what you're looking for specifically and maybe I can help you find it</br>visitor_name (visitor_name@tamu.edu): Okay Thanks.</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_name@tamu.edu): No thats all</br>Chris: OK</br>Chris: Have a nice day</br>visitor_name (visitor_name@tamu.edu): Oh.. I guess you may give come comments for finding database.</br>visitor_name (visitor_name@tamu.edu): can you give any suggestion or recommendation for protein complexes for Cel?</br>Chris: I'll have to look into it a bit, but I (and my colleagues) can send you an email soon to follow up</br>visitor_name (visitor_name@tamu.edu): Okay Thank you for helping me.</br>Chris: You're welcome. I'm sorry I couldn't be of more help, but we'll be in touch</br>visitor_name (visitor_name@tamu.edu): Okay I will close this chat room. Have a good day :)</br>Chris: OK, thanks. You too!

**Reported by:** hyun*** (hyun************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide#3--10">http://www.wormbase.org/about/userguide#3--10</a>
**Browser:** Safari 11.0.1

**Comment by chris-grove** [comment]
Hi Hyundoo,


Using the Gene Ontology annotations in WormBase you may be able to get at some of the protein complexes and their respective members. I would suggest first looking at the Gene Ontology term page for "macromolecular complex":


http://www.wormbase.org/species/all/go_term/GO:0032991#02--10


and use the Ontology Browser widget to view all complexes and complex child/descendant terms. You can click on the "# gene products" link next to any term to see the list of genes annotated to the term (or any of the term's child/descedant terms). You may also wish to browse the "Cellular Component" branch of the Gene Ontology using the WormBase Ontology Browser tool:


http://www.wormbase.org/tools/ontology_browser


which is always available under the Tools menu on any WormBase page.


I hope that helps.


Best,


Chris Grove

**Comment by chris-grove** [comment]
From user:
"Thank you for helping me to figure out. 
I looked over the webpage you suggested, and I think I can find a solution for protein complexes. 
I will try to use GO annotation in WormBase. 
Thanks again and have a good day."
