### ISSUE TITLE
e-value sorting in various homology tables not working properly

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6012]
Related to issues #5155 and #1588 and #1589 

Although the e-value sorting on "Best BLASTP matches" tables is working in the Homology widget on gene pages and protein pages (see tickets referenced above), there are still issues with sorting the "BLAST e-value" column on the "view full BLASTP List" tables. Here's a video demo:

https://www.dropbox.com/s/bcgwu0kj7eje1hu/View_full_BLASTP_List_table_evalue_sorting_problem.mov?dl=0

**Comment by sibyl229** [comment]
Hi @chris-grove Sorting by e-value should be fixed in the "view full blastp list". Here is an example: http://staging.wormbase.org/species/c_elegans/gene/WBGene00000232#6--3 Thank you!

**Comment by chris-grove** [comment]
@sibyl229 
Looks great! Thanks Sibyl!
