### ISSUE TITLE
visitor_name (visitor_email): Hello Chris: Hi Youm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6014]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello</br>Chris: Hi Youmie, how can I help?</br>visitor_name (visitor_email): Where can I know what antibiotics resistant gene cosmid have?</br>Chris: You have the sequence?</br>Chris: which cosmid?</br>visitor_name (visitor_email): I got the cosmid C26B2 from Sanger institute</br>Chris: OK, did the Sanger provide any instructions as to which antibiotic resistance gene the cosmid carries?</br>visitor_name (visitor_email): No</br>visitor_name (visitor_email): They just said streak on plates</br>visitor_name (visitor_email): I streaked them just on LB.</br>Chris: OK, I would contact the Sanger and ask. You could also ask on the forums, but I don't know off-hand what the AR gene would be</br>visitor_name (visitor_email): Okay. would contact the Sanger.</br>visitor_name (visitor_email): Anyway  they grew well. ^^</br>Chris: :) OK, sounds good</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): No Many thanks</br>Chris: OK, good luck</br>Chris: Have a nice day!</br>visitor_name (visitor_email): You too</br>Chris: Thanks!

**Reported by:** youm** (YouM*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/clone/C26B2#02--10">http://www.wormbase.org/species/c_elegans/clone/C26B2#02--10</a>
**Browser:** Chrome 60.0.3112.113

**Comment by raymond91125** [comment]
Cosmid vector information can be found here 
<http://wiki.wormbase.org/index.php/Cosmids/YACs>.

I think C clones are from pJB8 thus Amp-R but please double check for 
yourself. Once relaxed the selection, you may not recover the cosmids.

Cheers,

Raymond


On 30/11/17 13:57, no-reply@wormbase.org wrote:
> online chat youmie (YouMie.Kim@umassmed.edu): Hello
> Chris: Hi Youmie, how can I help?
> youmie (YouMie.Kim@umassmed.edu): Where can I know what antibiotics 
> resistant gene cosmid have?
> Chris: You have the sequence?
> Chris: which cosmid?
> youmie (YouMie.Kim@umassmed.edu): I got the cosmid C26B2 from Sanger 
> institute
> Chris: OK, did the Sanger provide any instructions as to which 
> antibiotic resistance gene the cosmid carries?
> youmie (YouMie.Kim@umassmed.edu): No
> youmie (YouMie.Kim@umassmed.edu): They just said streak on plates
> youmie (YouMie.Kim@umassmed.edu): I streaked them just on LB.
> Chris: OK, I would contact the Sanger and ask. You could also ask on 
> the forums, but I don't know off-hand what the AR gene would be
> youmie (YouMie.Kim@umassmed.edu): Okay. would contact the Sanger.
> youmie (YouMie.Kim@umassmed.edu): Anyway they grew well. ^^
> Chris: :) OK, sounds good
> Chris: Is there anything else I can help you with?
> youmie (YouMie.Kim@umassmed.edu): No Many thanks
> Chris: OK, good luck
> Chris: Have a nice day!
> youmie (YouMie.Kim@umassmed.edu): You too
> Chris: Thanks!
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/clone/C26B2#02--10 
> http://www.wormbase.org/species/c_elegans/clone/C26B2#02--10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/clone/C26B2#02--10> 
>
>
> This issue has been assigned ticket number: #6014. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6014>.
>
> Reported by: youmie (YouMie.Kim@umassmed.edu)
> 30 Nov 17 21:57
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by chris-grove** [comment]
@raymond91125 
Did you email the user?

**Comment by chris-grove** [comment]
@raymond91125 
Nevermind
