### ISSUE TITLE
Create/add genotype info for Strains from WBPaper00005722

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#6015]
@Paul-Davis: There are some  'UA' strains or their genotypes missing in WB, eg., UA5, refer WBPaper00005722, under 'Materials and Methods'-->'C. elegans Protocols'. For those UA strains (from this paper) already in WB, would be useful to add the genotype information.

**Comment by Paul-Davis** [comment]
I'll take a look @rankishore :)

**Comment by Paul-Davis** [comment]
UA3 - 8 have either been curated or updated to reflect the genotype, gene association and alternative name data contained in the publication.
