### ISSUE TITLE
  why I cannot look through fox-1 gene ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6016]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;why I cannot look through fox-1 gene sequence in C. briggsae?</p>

**Reported by:** Qian****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by Paul-Davis** [comment]
Kev replied to user
