### ISSUE TITLE
Overview widget not loading on staging gene class pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6020]
I don't know if this is being worked on or if it will fix itself once migrated to www, but the Overview widget is consistently failing to load on gene class pages on staging:

http://staging.wormbase.org/resources/gene_class/unc#0--10

![screen shot 2017-12-04 at 11 49 24 am](https://user-images.githubusercontent.com/611382/33564735-3cf6c100-d8e9-11e7-80fa-8a5677112626.png)

**Comment by sibyl229** [comment]
probably duplicated #6127
