### ISSUE TITLE
  Hello, I would like to download expre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6023]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I would like to download expression and alternative data for genes expressed in the C. elegans nerve ring. For the expression data, I found and managed to parse the 'anatomy_association' and 'anatomy_ontology' files, which gave me the expression data that I wanted. However, I am unable to find similar files that link the genes sequence (e.g.C29A12.4) to the alternative splices (e.g.  C29A12.4a,C29A12.4b, etc).  I am looking at over a hundred genes, so would ideally like to work with your wb and obo files rather than going through the database. Thanks. </p>

**Reported by:** Chri*************** (cabr***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

**Comment by draciti** [comment]
Hello Chris,

We do curate gene expression attaching the annotation to WBGene and not isoform, so it will be hard for you to retrieve the information.

One thing you could try for now is to parse the file located here 
ftp://caltech.wormbase.org/pub/wormbase/expr_dump/expr_pattern.ace.20171115
and look for the word 'isoform' in the 'Pattern' and 'Subcellular localization' fields. I know it's not ideal but might work..
The file also contains the anatomy annotations, in your case nerve ring ( WBbt:0006749 ) 
 
We are going to curate to isoforms in the immediate future, FYI.

Do not hesitate to contact us should you have additional questions.
Best,

Daniela

**Comment by draciti** [comment]
waiting to ping again the user after Chris' and Gary W's feedback

**Comment by chris-grove** [comment]
Hi Christopher,


 I'm not sure if this is what you were asking for, but if you want to get the list of transcript names for all genes in C. elegans, you can use WormMine to query these out. To do this, go to the WormMine QueryBuilder tool:


http://intermine.wormbase.org/tools/wormmine/customQuery.do


Click on the "Import query from XML" link and paste in the following XML query:

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.transcripts.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>


and click "Submit". Then click on "Show results" on the subsequent page. That will give you a list of all transcript names for all C. elegans genes. You can download a table from there. If you want this list just for a specific set of genes, this can be done as well. Let me know and I can guide you through this process as well.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
No response from user. Closing
