### ISSUE TITLE
  trying to register so we can order Ap...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6025]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;trying to register so we can order Apl-1 and Sod-1 and wild types.<br/>can you assist?</p>

**Reported by:** Jaeg** (jjae***************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko

**Comment by raymond91125** [comment]
Hi Jaeger,

We do not supply any reagents nor strains, thus registering with us does 
not help you. You may order strains from The Caenorhabditis Genetics 
Center (CGC) here <https://cgc.umn.edu/>.

Cheers,

Raymond


On 05/12/17 11:32, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   trying to register so we can order Apl-1 and Sod-1 and wild types.
> can you assist?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6025. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6025>.
>
> Reported by: Jaeger (jjaeger@northbabylonschools.net)
> 05 Dec 17 19:32
>
> Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; 
> .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
