### ISSUE TITLE
Build display for disease annotation data

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#6026]
**Display for Gene pages:**
@sibyl229: The Disease_model_annotation class (under ?Gene) was introduced to add details for disease data such as genetic entities (allele/variation, strain, transgene) implicated as disease models, experimental conditions and treatments. This also incorporates specifications by AGR Disease Working Group (DWG). Please start displaying this data in the 'Human diseases' widget on gene pages. 

A simple table called 'Annotation details' in the 'Human Diseases' widget would work with the following columns, in this order: Disease, Genetic entity, Association Type, Evidence code, Experimental condition, Modifier, Reference.  Below is Column name --->Acedb tag in Disease_model_annotation class where data comes from.

Look at 'Disease_relevant_gene' tag to determine which gene page these annotation details should be displayed on.
1. Disease-->Disease_term
2. Genetic entity-->Either Strain, Variation or Transgene whichever exists.
(We don't have to show the 'Disease_relevant_gene' since we are on the gene page).
3. Association Type-->Association_type
4. Evidence Code-->Evidence_code
5. Experimental condition-->Inducing_chemical and Inducing_agent (Display both if data exists)
6. Modifier-->Modifier_transgene, Modifier_variation, Modifier_strain, Modifier_gene, Modifier_molecule, Other_modifier (Display data for all tags that have them)
7. Reference-->Paper_evidence

**Comment by sibyl229** [comment]
Hi @rankishore disease model annotation display is on staging for testing:

Test cases:
* Modifier (variation) 
    * http://sibyl.wormbase.org/species/c_elegans/gene/WBGene00003892#07h--10
* Inducing chemical
    * http://sibyl.wormbase.org/species/c_elegans/gene/WBGene00003562#07h--10
* Inducing agent
    * http://sibyl.wormbase.org/species/c_elegans/gene/WBGene00001865#07h--10

Please let me know if there is anything that can be improved.

**Comment by sibyl229** [comment]
@rankishore sorry, I might mistakenly sent you testing links to my development instance. They should be staging instead. I corrected the links on the github ticket.

**Comment by rankishore** [comment]
@sibyl229: Detailing the things we talked about for the Disease widget on gene pages:
1.  Have two major sections:  Curated Disease Associations and Automatic Disease Associations
2. Remove current heading 'Curated Experimental Model'
3. For the table:
a. Change table header from 'Detailed Disease Model' to 'Annotation details'
b. Remove 'Association type' column for now
c. Keep identical Variations together (as adjacent rows), with the one with experimental and/or modifiers below the one without
c. Add 'Modifier Association Type' column to the right of the 'Modifier' column and show values
4. Change 'Curated Human Disease Relevance' to 'Disease Description' (comes from the acedb tags, either 'Disease_relevance' under ?Gene or from 'Disease_model_description' under 
 ?Disease_model_annotation

**Comment by rankishore** [comment]
@sibyl229:  We need to tweak the way data is being displayed in the 'Annotation details' table in the 'Human Diseases' widget on gene pages.  This data comes from the 'Disease_model_annotation' tag in the gene model.  

Example--for the gene nphp-4, there exist 4 disease_model_annotation objects-00000010, 00000039, 00000319 and 00000381.  This corresponds to 4 separate annotations that are showing up as 4 rows in the table, this is correct, but all of the data in each of those disease_model_annotation objects is not showing up.  For example, 00000039 has an Interacting_variation WBVar00091788 (ok500) which we should show in an 'Interacting Variation' column immediately to the right of the 'Genetic entity' column. Same for an 'Interacting_gene' tag value if it exists.  

I am wondering whether we can show only those columns for which data exist? All four of these annotations do not have data for 'Experimental condition', 'Modifier' or 'Modifier association type', and the table shows empty columns for these.  But I'm guessing this may be an overall table design issue.

**Comment by sibyl229** [comment]
Hi @rankishore the display for genotype in the disease model is ready for testing:

- http://sibyl.wormbase.org/species/c_elegans/gene/WBGene00001131#-7h-10
- http://sibyl.wormbase.org/species/c_elegans/gene/WBGene00011261#-7h-10

Please let me know if there is a problem. I think it's particularly important to check some edge cases, and make sure the genotype string produced is correct.
