### ISSUE TITLE
How do you find the splice products a gene encodes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6030]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do you find the splice products a gene encodes? and where can you find the major domains?

**Reported by:** Holl******** (adam**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g6f178ahc35d2b-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g6f178ahc35d2b-10</a>
**Browser:** Safari 10.1.1

**Comment by Paul-Davis** [comment]
Hi,

On the gene summary you can get information on splice products a gene 
encodes in the "Sequences" widget and you can get domain information by 
looking at the protein products summary pages available via the links in 
the "Protein" column in that table.

Example:

http://www.wormbase.org/species/c_elegans/gene/WBGene00005027#-g-10

All the best

Paul




On 07/12/2017 06:46, no-reply@wormbase.org wrote:
> offline chat How do you find the splice products a gene encodes? and 
> where can you find the major domains?
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g6f178ahc35d2b-10 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g6f178ahc35d2b-10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006759#0-9g6f178ahc35d2b-10> 
>
>
> This issue has been assigned ticket number: #6030. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6030>.
>
> Reported by: Hollie Adams (adamsh@oxy.edu)
> 07 Dec 17 06:46
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
