### ISSUE TITLE
  Hello,  This must exist in a hundred ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6031]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>This must exist in a hundred different places on or off the web, but I really cannot find it and will ask here before I start bugging individuals. I'm after the the complete cell lineage in graph/network format, is such a thing downloadable from WormBase? Thanks</p><p>What were you doing? <br />&nbsp;&nbsp;googling furiously</p>

**Reported by:** Luke****** (luke****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by raymond91125** [comment]
Is this what you're looking for?

<http://www.wormatlas.org/celllineages.html>.

raymond


On 07/12/17 17:48, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> This must exist in a hundred different places on or off the web, but I 
> really cannot find it and will ask here before I start bugging 
> individuals. I'm after the the complete cell lineage in graph/network 
> format, is such a thing downloadable from WormBase? Thanks
>
> What were you doing?
>   googling furiously
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6031. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6031>.
>
> Reported by: Luke Noble (luke.noble@gmail.com)
> 08 Dec 17 01:48
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi Raymond,
That's an image of the lineage (I've found plenty of those!) ... I'm
looking for the lineage in a parseable network format (e.g., xml, gml) for
some simulations.

Luke Noble

Postdoctoral Associate
Rockman laboratory
Center for Genomics and Systems Biology
Department of Biology
New York University

**Comment by chris-grove** [comment]
Hi Luke,

A few years ago I had generated this Excel file which can be uploaded to Cytoscape to visualize the embryonic cell lineage as a network. Maybe that could work for you.

Best,

Chris Grove
WormBase

**Comment by raymond91125** [comment]
Ya, I suspected not but ...

You might want to post your question to the forum 
<http://forums.wormbase.org/>.

We have the lineage relationship of nuclei coded in OBO and OWL 
<http://www.ontobee.org/ontology/WBbt?iri=http://purl.obolibrary.org/obo/WBbt_0000102>.

Cheers,

Raymond




On 08/12/17 09:24, Luke Noble wrote:
> Hi Raymond,
> That's an image of the lineage (I've found plenty of those!) ... I'm 
> looking for the lineage in a parseable network format (e.g., xml, gml) 
> for some simulations.
>
> Luke Noble
>
> Postdoctoral Associate
> Rockman laboratory
> Center for Genomics and Systems Biology
> Department of Biology
> New York University
>
>
> On 8 December 2017 at 12:10, Raymond Lee <raymond@caltech.edu 
> <mailto:raymond@caltech.edu>> wrote:
>
>     Is this what you're looking for?
>
>     <http://www.wormatlas.org/celllineages.html>
>     <http://www.wormatlas.org/celllineages.html>.
>
>     raymond
>
>
>
>     On 07/12/17 17:48, no-reply@wormbase.org
>     <mailto:no-reply@wormbase.org> wrote:
>>     How Do I ...?
>>
>>       Hello,
>>     This must exist in a hundred different places on or off the web,
>>     but I really cannot find it and will ask here before I start
>>     bugging individuals. I'm after the the complete cell lineage in
>>     graph/network format, is such a thing downloadable from WormBase?
>>     Thanks
>>
>>     What were you doing?
>>       googling furiously
>>
>>     Submitted From:
>>       support /tools/support <http://www.wormbase.org//tools/support>
>>
>>     This issue has been assigned ticket number: #6031. Follow
>>     progress on our issue tracker
>>     <https://github.com/WormBase/website/issues/6031>.
>>
>>     Reported by: Luke Noble (luke.noble@gmail.com
>>     <mailto:luke.noble@gmail.com>)
>>     08 Dec 17 01:48
>>
>>     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)
>>     AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94
>>     Safari/537.36
>>
>>     This question was reported via the web interface at wormbase.org
>>     <http://wormbase.org>. You can also email us
>>     <mailto:help@wormbase.org> directly.
>>
>>     -- 
>>     -- 
>>     You received this message because you are subscribed to the
>>     "WormBase: help" group.
>>     To post to this group, send email to help@wormbase.org
>>     <mailto:help@wormbase.org>
>>     To unsubscribe from this group, send email to
>>     help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>>     For more options, visit this group at
>>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>>     <http://groups.google.com/a/wormbase.org/group/help?hl=en>
>>
>>     ---
>>     You received this message because you are subscribed to the
>>     Google Groups "WormBase: help" group.
>>     To unsubscribe from this group and stop receiving emails from it,
>>     send an email to help+unsubscribe@wormbase.org
>>     <mailto:help+unsubscribe@wormbase.org>.
>
>
>     -- 
>     __
>     Raymond Lee
>     raymond@caltech.edu <mailto:raymond@caltech.edu>
>     http://www.WormBase.org/
>     California Institute of Technology
>     Division of Biology and Biological Engineering
>     Mail Code 156-29
>     Pasadena, CA 91125
>     USA
>     tel:626.395.2687 <tel:%28626%29%20395-2687>
>
>

-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Yeah, the forum was my next move (though the question has been asked, and
not answered, before), or this guy <http://wormweb.org/celllineage>.

But the embryonic lineage should do it, thanks Chris!



Luke Noble

Postdoctoral Associate
Rockman laboratory
Center for Genomics and Systems Biology
Department of Biology
New York University
