### ISSUE TITLE
Hi. I am confused by the annotation for lq20 here....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6032]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi. I am confused by the annotation for lq20 here. In the paper where this mutant was isolated, the mutation was mapped to a different amino-acid than what is mentioned here. In that paper, the mutation affects a CCC codon, changing it to CTC, and the amino-acid change is P29L. On this page it is listed as a CCG to CTG mutation 5 codons downstream, leading to a P34L mutation. How do I know which annotation is correct? Thanks! Dan

**Reported by:** Dan ***** (shay*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10">http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10</a>
**Browser:** Safari 11.0.2

**Comment by Paul-Davis** [comment]
Hi Dan,

This mutation was curated back in 2006 based on the published data in 
Shakir MA et al. (2006) Genetics, assuming this is the publication you 
are referring to it would seem that the information has either become 
out of date as the reference genome was changed or that the original 
nucleotide change was not recorded correctly. I will look into this and 
make the correction for the WS264 release of wormbase, but in the mean 
time please use the published data. If I have any further information I 
will get back to you. Thank you for bringing this to our attention.

Paul

On 08/12/2017 05:05, no-reply@wormbase.org wrote:
> offline chat Hi. I am confused by the annotation for lq20 here. In the 
> paper where this mutant was isolated, the mutation was mapped to a 
> different amino-acid than what is mentioned here. In that paper, the 
> mutation affects a CCC codon, changing it to CTC, and the amino-acid 
> change is P29L. On this page it is listed as a CCG to CTG mutation 5 
> codons downstream, leading to a P34L mutation. How do I know which 
> annotation is correct? Thanks! Dan
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10 
> http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10> 
>
>
> This issue has been assigned ticket number: #6032. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6032>.
>
> Reported by: Dan Shaye (shaye@uic.edu)
> 08 Dec 17 05:05
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Just to confirm, this variation has been corrected in WormBase and will 
be visible in the WS264 release of wormbase.

Paul

On 08/12/2017 14:28, Paul Davis wrote:
>
> Hi Dan,
>
> This mutation was curated back in 2006 based on the published data in 
> Shakir MA et al. (2006) Genetics, assuming this is the publication you 
> are referring to it would seem that the information has either become 
> out of date as the reference genome was changed or that the original 
> nucleotide change was not recorded correctly. I will look into this 
> and make the correction for the WS264 release of wormbase, but in the 
> mean time please use the published data. If I have any further 
> information I will get back to you. Thank you for bringing this to our 
> attention.
>
> Paul
>
> On 08/12/2017 05:05, no-reply@wormbase.org wrote:
>> offline chat Hi. I am confused by the annotation for lq20 here. In 
>> the paper where this mutant was isolated, the mutation was mapped to 
>> a different amino-acid than what is mentioned here. In that paper, 
>> the mutation affects a CCC codon, changing it to CTC, and the 
>> amino-acid change is P29L. On this page it is listed as a CCG to CTG 
>> mutation 5 codons downstream, leading to a P34L mutation. How do I 
>> know which annotation is correct? Thanks! Dan
>>
>> Submitted From:
>> http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10 
>> http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10 
>> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088505#02-457-10> 
>>
>>
>> This issue has been assigned ticket number: #6032. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/6032>.
>>
>> Reported by: Dan Shaye (shaye@uic.edu)
>> 08 Dec 17 05:05
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
