### ISSUE TITLE
Location widget for Strain pages

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#6034]
During a conversation with @kyook we hit upon the idea of having a location widget for Strain pages where there is a genome browser for the strain.  So for N2 or CB4856 would open a location widget like you would see on a gene page, where the view/link would be for one or more predefined locations (like plg-1 or him-5 for Hawaiian).

**Comment by khowe** [comment]
Many strains are associated with a single variation, and it makes perfect sense to have location widget for those strains (showing that variation). 

I'm not convinced though that is would be useful for WGS strains containing many (thousands) of variations distributed all over the genome.

**Comment by sibyl229** [comment]
I guess we probably won't implement this, but feel free to reopen if something needs to be done.
