### ISSUE TITLE
What is the proper antibody for ATP-2 protein...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6037]
*Help Desk query collected when no chat operators were online. Follow up required.*

What is the proper antibody for ATP-2 protein

**Reported by:** Dila*** (dila***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/antibody/[cgc4813]:atp-2#012--10">http://www.wormbase.org/species/all/antibody/[cgc4813]:atp-2#012--10</a>
**Browser:** Chrome 62.0.3202.94

**Comment by chris-grove** [comment]
Hello Dilawer,


 The only antibody we have curated at WormBase for the ATP-2 protein is the one whose page you were viewing:


http://www.wormbase.org/species/all/antibody/%5Bcgc4813%5D:atp-2#012--10


As my colleague Daniela pointed out, there is one paper connected to this antibody in the database, WBPaper00004813:


http://www.wormbase.org/resources/paper/WBPaper00004813?from=http://www.wormbase.org/db/misc/paper?name=WBPaper00004813;class=Paper#03--10


Tsang WY, Sayles LC, Grad LI, Pilgrim DB, Lemire BD. Mitochondrial respiratory
chain deficiency in Caenorhabditis elegans results in developmental arrest and
increased life span. J Biol Chem. 2001 Aug 24;276(34):32240-6. Epub 2001 Jun 15. 
PubMed PMID: 11410594.

Best,


Chris Grove
WormBase

**Comment by chris-grove** [comment]
From user:
"Thank you for your prompt reply,The search of atp-2 antibody is  a complicated story, mostly no one is having S. cerevisiae ATP2p antibody for C. elegans  atp-2 protein long before Dr J.Velours has gifted this antibody as a gift to people for research purpose , no one is supplying presently . if you have any source to get this antibody please inform."

**Comment by chris-grove** [comment]
Hello,

 I don't have any more information about where to acquire the antibody you're looking for. You may have luck by posting the question on the WormBase forums:

http://forums.wormbase.org/

You'll have to register, if you haven't already. There are quite a few C. elegans researchers on there that may know or may know where to point you.

Best,

Chris
