### ISSUE TITLE
Discrepancy on who isolated N2 between WB and CGC

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6039]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Paul</br>visitor_name (visitor_email): So I just spotted something trivial</br>Chris: OK, what's that?</br>visitor_name (visitor_email): But WormBase and the CGC disagree on who isolated Bristol N2</br>Chris: Hmmm</br>visitor_name (visitor_email): The CGC say is was isolated by Staniland and cultured by Nicholas; we say it was sampled and isolated by Nicholas.</br>Chris: Yes, I see it now</br>Chris: OK, I'm not sure at the moment where to get clarifying information. Do you happen to know off hand?</br>visitor_name (visitor_email): I suspect there is also a terminology thing here - when they say "isolated", we mean "sampled" and when they say "cultured" we mean "isolated"</br>Chris: Ah, right, that's certainly possible</br>visitor_name (visitor_email): No, I just found this by accident.  It's probably not worth fixing unless somebody knows what's right</br>Chris: OK, I'll look into it. Thanks for pointing it out.</br>Chris: Anything else to report?</br>United Kingdom (Cambridge) #1363: No</br>United Kingdom (Cambridge) #1363: thanks

**Reported by:** Paul******* (pker*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/strain/N2#02--10">http://www.wormbase.org/species/c_elegans/strain/N2#02--10</a>
**Browser:** Safari 11.0.2

**Comment by Paul-Davis** [comment]
I believe that this is just a terminology issue between the sampling point and the Isolation point.
WB treats the point that the worm was plucked from whatever medium in the wild as the isolation point where in the passage quoted on both the CGC and in the WB Overview widget Isolation is done in the lab when the worm is extracted and cultured. I'm going to leave it as it has been curated for now.
