### ISSUE TITLE
Overview widget not loading on PCR Product/Oligo pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6042]
On the following pages:

http://www.wormbase.org/species/all/pcr_oligo/sjj_M05B5.5_f#03--10
http://www.wormbase.org/species/all/pcr_oligo/sjj_M05B5.5_b#03--10
http://www.wormbase.org/species/all/pcr_oligo/sjj_F42D1.1_f#03--10
http://www.wormbase.org/species/all/pcr_oligo/sjj_F42D1.1_b#03--10
http://www.wormbase.org/species/c_elegans/pcr_oligo/193538_s_at#03--10

The Overview widget fails to load:

![screen shot 2017-12-11 at 11 49 19 am](https://user-images.githubusercontent.com/611382/33842721-5b4ac43c-de69-11e7-83bd-4900fd74b63e.png)

**Comment by a8wright** [comment]
I now understand that this one page shows information for three types of entities: oligo, oligo-set, and pcr-product. This is now handled by the code that is running on staging.

@chris-grove If there should be more information shown for any of these types of entities let me know and I will add it before pushing to production

**Comment by a8wright** [comment]
@sibyl229 for oligos I am producing a list of pcr products. Like the one in the JSON you sent me. I am pretty sure what my code is producing is an exact match. Unfortunately it is not showing up in the widget.

**Comment by chris-grove** [comment]
@a8wright 
No more info needed right now. Thanks. Closing.
