### ISSUE TITLE
Problems loading www.wormbase.org

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6046]
I'm getting 502 Bad Gateway errors and 504 Gateway Time-out errors trying to load www.wormbase.org. I can get it to load (slowly) sometimes, but autocomplete doesn't work in search boxes, and often gene pages don't load, or the widgets don't load (with 502 or 504 errors).

**Comment by draciti** [comment]
I am having the same problem - both safari and firefox (started only ~15 min ago, before then it was working fine)

**Comment by nuin** [comment]
I got 504. intermine.wormbase.org is fine.
