### ISSUE TITLE
User submission of gene sequence annotation

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6053]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello! I'd like to submit a new annotation of the existing gene (annotation is wrong in the wormbase) but I'm not sure which forms to fill out, under the "submit data" section.

**Reported by:** Heaj* (hshi************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#01--10">http://www.wormbase.org/about/userguide/submit_data#01--10</a>
**Browser:** Chrome 63.0.3239.84

**Comment by Paul-Davis** [comment]
Hi,

Thank you for offering to provide us with the updated information. I 
would be more than happy to take a look if you would like to forward the 
data.

Thanks again.

Paul
[Sequence Curation]


On 15/12/2017 02:34, no-reply@wormbase.org wrote:
> online chat Heaji (hshin38@wisc.edu): Hello! I'd like to submit a new 
> annotation of the existing gene (annotation is wrong in the wormbase) 
> but I'm not sure which forms to fill out, under the "submit data" 
> section.
>
> Submitted From:
>   http://www.wormbase.org/about/userguide/submit_data#01--10 
> http://www.wormbase.org/about/userguide/submit_data#01--10 
> <http://www.wormbase.org/http://www.wormbase.org/about/userguide/submit_data#01--10> 
>
>
> This issue has been assigned ticket number: #6053. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6053>.
>
> Reported by: Heaji (hshin38@wisc.edu)
> 15 Dec 17 02:34
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Heaji,

Thanks for the detailed information. I can confirm that this Isoform has 
been updated inline with your sequence data and will be visible in the 
WS264 release of WormBase.

Paul

On 15/12/2017 16:25, Heaji Shin wrote:
>
> Hi Paul,
>
> Thank you for getting back to me about this. I’m attaching a summary 
> of the updated annotation for the lst-1 gene. The main update is that 
> the current annotation of the lst-1 gene in the wormbase mis-annotates 
> the start codon of the long form, which accidently adds 70 amino acid 
> in the N-terminus. Please see the attached file for the detailed 
> information.
>
> Thank you for your help on this!
>
> Heaji
>
> Heaji Shin, PhD
>
> Judith Kimble Lab
>
> HHMI/University of Wisconsin-Madison
>
> hshin38@wisc.edu <mailto:hshin38@wisc.edu>
>
> 608-262-7970 ext. 3342
>
> *From: *Paul Davis <paul.davis@wormbase.org>
> *Date: *Friday, December 15, 2017 at 6:22 AM
> *To: *WormBase/website 
> <reply@reply.github.com>, 
> "help@wormbase.org" <help@wormbase.org>
> *Cc: *"hshin38@wisc.edu" <hshin38@wisc.edu>
> *Subject: *Re: [wormbase-help] online chat transcript: visitor_name 
> (visitor_email): Hello! I'd like to s... (Heaji)
> *Resent-From: *<hshin38@wisc.edu>
>
> Hi,
>
> Thank you for offering to provide us with the updated information. I 
> would be more than happy to take a look if you would like to forward 
> the data.
>
> Thanks again.
>
> Paul
> [Sequence Curation]
>
>
> On 15/12/2017 02:34, no-reply@wormbase.org 
> <mailto:no-reply@wormbase.org> wrote:
>
>     online chat Heaji (hshin38@wisc.edu <mailto:hshin38@wisc.edu>):
>     Hello! I'd like to submit a new annotation of the existing gene
>     (annotation is wrong in the wormbase) but I'm not sure which forms
>     to fill out, under the "submit data" section.
>
>     Submitted From:
>     http://www.wormbase.org/about/userguide/submit_data#01--10
>     http://www.wormbase.org/about/userguide/submit_data#01--10
>     <http://www.wormbase.org/http:/www.wormbase.org/about/userguide/submit_data#01--10>
>
>
>     This issue has been assigned ticket number: #6053. Follow progress
>     on our issue tracker
>     <https://github.com/WormBase/website/issues/6053>.
>
>     Reported by: Heaji (hshin38@wisc.edu <mailto:hshin38@wisc.edu>)
>     15 Dec 17 02:34
>
>     This question was reported via the web interface at wormbase.org.
>     You can also email us <mailto:help@wormbase.org> directly.
>
>     -- 
>     -- 
>     You received this message because you are subscribed to the
>     "WormBase: help" group.
>     To post to this group, send email to help@wormbase.org
>     <mailto:help@wormbase.org>
>     To unsubscribe from this group, send email to
>     help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>     For more options, visit this group at
>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
