### ISSUE TITLE
Correct linking of segmental duplication ?Feature objects in GBrowse to appropriate page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6054]
Branched off of #6049 

From @Paul-Davis 

"Hi Diana, There is actually a set of segmental duplications calculated by OrthoCluster that can be viewed in the both of our genome browsers for C. elegans. 

http://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CYACs_Fosmids_Cosmids%2CSegmental%20duplication&loc=III%3A9044186..9051990&data=data%2Fc_elegans_PRJNA13758&highlight= 

http://www.wormbase.org/species/c_elegans/feature/WBsf039960#012374--10 

Unfortunately you cannot currently click in the feature in gbrowse and get to the summary pages but the ID is searchable and can be cut and pasted from the popup window. 

These were taken directly from a 3rd party submitter so we do not have an accurate assessment of the accuracy or completeness but the details are published in this paper: 

http://www.wormbase.org/resources/paper/WBPaper00034747#05--10 

I hope this helps. 

Paul"

The segmental duplications track in GBrowse displays segmental duplication sequence feature (?Feature) objects, but clicking on them leads to a WormBase search results page for the ?Feature object ID (e.g. "WBsf041888") searched in the ?Sequence class, which results in the wrong hit:

http://www.wormbase.org/search/sequence/WBsf041888?redirect=1

Preferably these GBrowse glyphs would link directly to the correct ?Feature object page:

http://www.wormbase.org/species/c_elegans/feature/WBsf041888#012345--10

**Comment by scottcain** [comment]
Will do. Currently C. elegans is the only species with this feature; is that likely to stay that way (so I can hard code the “elegans”part of the path)?

**Comment by chris-grove** [comment]
@scottcain 
Hmmm, I'm not familiar with this feature type; I'd have to ask.

@Paul-Davis 
Do you happen to know if this is likely to remain a C.-elegans-only feature?

**Comment by khowe** [comment]
@scottcain @chris-grove not sure I understand the species thing. A feature on the C. elegans browser should always link to a C. elegans page. But if a feature track got added to the e.g. C. remanei Jbrowse, I would expect it to link to a C. remanei feature page.

**Comment by Paul-Davis** [comment]
It was taken from a publication a very long time ago......seems they have generated data for C. briggsae so we will have to discuss if we are going to rerun the analysis to generate the features on the current briggsae assembly.

This url style can be used to make any config species independent:
http://www.wormbase.org/db/feature/feature?name=WBsf039960;class=Feature

**Comment by scottcain** [comment]
@khowe it's a pragmatic question: it's really easy to write code that will has a literal "elegans" in the url like "http://www.wormbase.org/species/c_elegans/feature/" + ID/name/whatever, but if I have to first figure out what species I'm looking at, the code gets more complicated.

**Comment by scottcain** [comment]
Ah, @Paul-Davis thanks--it wasn't clear to me if something like that was an option.

**Comment by Paul-Davis** [comment]
I think the above URL syntax is a leftover from the old site as external databases also wanted a simple species independent url for linking.

**Comment by scottcain** [comment]
Fixed on staging; will go into production with 262
