### ISSUE TITLE
  I want to get a computer parsable tex...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6055]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to get a computer parsable text file of gene information that looks like<br/>this for WBGene00017280 (which I see when I enter the gene name in the<br/>search widget on the main WB page)<br/>usp-39 is an ortholog of human USP39 (ubiquitin specific peptidase 39); usp-39 is involved in embryo development, hermaphrodite genitalia development, locomotion and nematode larval development; usp-39 is predicted to have thiol-dependent ubiquitinyl hydrolase activity and zinc ion binding activity, based on protein domain information; usp-39 is expressed in the pharynx, nervous system, tail, and the intestine.<br/>Is there such a file available, and, if so, where can I find it?<br/>Thank you.<br/>Brent</p>

**Reported by:** bge@******
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by epaule** [comment]
have a look at that one: ftp://ftp.wormbase.org/pub/wormbase/releases/WS261/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS261.functional_descriptions.txt.gz

It is a collection of descriptions for each gene with each gene separated by a =
