### ISSUE TITLE
visitor_name (visitor_email): The example urls on ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6056]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): The example urls on this page all include a gene that is not accessible: WBGene000066763 and causes an error with all the api examples</br>visitor_name (visitor_email): The page is http://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10

**Reported by:** Davi****** (davi**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763">http://www.wormbase.org/search/gene/WBGene000066763</a>
**Browser:** Chrome 62.0.3202.94

**Comment by Paul-Davis** [comment]
Dear David,

Hmm seems we had a typo in our documentation as all our gene IDs are 
WBGene\d{8} and the example you quoted has 9.

http://www.wormbase.org/search/gene/WBGene00066763 
<http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763>

Returns the remanei gene CRE07764 where WBGene000066763 fails as you say.

I have updated the documentation, thank you for spotting this typo, it 
seems to have been in there for 5 years :(

Paul

On 15/12/2017 17:47, no-reply@wormbase.org wrote:
> online chat David King (davidcking.inbox@gmail.com): The example urls 
> on this page all include a gene that is not accessible: 
> WBGene000066763 and causes an error with all the api examples
> David King (davidcking.inbox@gmail.com): The page is 
> http://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10 
>
>
> Submitted From:
>   http://www.wormbase.org/search/gene/WBGene000066763 
> http://www.wormbase.org/search/gene/WBGene000066763 
> <http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763> 
>
>
> This issue has been assigned ticket number: #6056. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6056>.
>
> Reported by: David King (davidcking.inbox@gmail.com)
> 15 Dec 17 17:47
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
I fixed it

**Comment by Paul-Davis** [comment]
Does that mean that no one is using the REST API, or at least no one is
looking at the documentation for it? I was exploring some ideas for using
it.

Thanks,

David

On Tue, Dec 19, 2017 at 3:34 AM, Paul Davis <paul.davis@wormbase.org> wrote:

> Dear David,
>
> Hmm seems we had a typo in our documentation as all our gene IDs are
> WBGene\d{8} and the example you quoted has 9.
>
> http://www.wormbase.org/search/gene/WBGene00066763
> <http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763>
>
> Returns the remanei gene CRE07764 where WBGene000066763 fails as you say.
>
> I have updated the documentation, thank you for spotting this typo, it
> seems to have been in there for 5 years :(
>
> Paul
>
> On 15/12/2017 17:47, no-reply@wormbase.org wrote:
>
> online chat David King (davidcking.inbox@gmail.com): The example urls on
> this page all include a gene that is not accessible: WBGene000066763 and
> causes an error with all the api examples
> David King (davidcking.inbox@gmail.com): The page is
> http://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10
>
> Submitted From:
>   http://www.wormbase.org/search/gene/WBGene000066763
> http://www.wormbase.org/search/gene/WBGene000066763
> <http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763>
>
> This issue has been assigned ticket number: #6056. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6056>.
>
> Reported by: David King (davidcking.inbox@gmail.com)
> 15 Dec 17 17:47
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
> --
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================
>
>


-- 
David C. King, PhD.

Osborne Nishimura lab
Colorado State University
Biochemistry & Molecular Biology
1870 Campus Delivery
200 W. Lake St.
239 MRB Building
Fort Collins, CO 80523

**Comment by Paul-Davis** [comment]
Hi David,

We get quite a lot of rest queries so more likely you were unlucky as 
there were only 16 instances of the malformed WBGene ID out of 118 that 
appear on that page. Also people usually have their own test IDs that 
they know the data for?

This is a supported feature and isn't going to be disappearing any time 
soon so please continue your development.

Paul

On 20/12/2017 00:31, David King wrote:
> Does that mean that no one is using the REST API, or at least no one 
> is looking at the documentation for it? I was exploring some ideas for 
> using it.
>
> Thanks,
>
> David
>
> On Tue, Dec 19, 2017 at 3:34 AM, Paul Davis <paul.davis@wormbase.org 
> <mailto:paul.davis@wormbase.org>> wrote:
>
>     Dear David,
>
>     Hmm seems we had a typo in our documentation as all our gene IDs
>     are WBGene\d{8} and the example you quoted has 9.
>
>     http://www.wormbase.org/search/gene/WBGene00066763
>     <http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763>
>
>     Returns the remanei gene CRE07764 where WBGene000066763 fails as
>     you say.
>
>     I have updated the documentation, thank you for spotting this
>     typo, it seems to have been in there for 5 years :(
>
>     Paul
>
>     On 15/12/2017 17:47, no-reply@wormbase.org
>     <mailto:no-reply@wormbase.org> wrote:
>>     online chat David King (davidcking.inbox@gmail.com
>>     <mailto:davidcking.inbox@gmail.com>): The example urls on this
>>     page all include a gene that is not accessible: WBGene000066763
>>     and causes an error with all the api examples
>>     David King (davidcking.inbox@gmail.com
>>     <mailto:davidcking.inbox@gmail.com>): The page is
>>     http://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10
>>     <http://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10>
>>
>>
>>     Submitted From:
>>     http://www.wormbase.org/search/gene/WBGene000066763
>>     <http://www.wormbase.org/search/gene/WBGene000066763>
>>     http://www.wormbase.org/search/gene/WBGene000066763
>>     <http://www.wormbase.org/http://www.wormbase.org/search/gene/WBGene000066763>
>>
>>
>>     This issue has been assigned ticket number: #6056. Follow
>>     progress on our issue tracker
>>     <https://github.com/WormBase/website/issues/6056>.
>>
>>     Reported by: David King (davidcking.inbox@gmail.com
>>     <mailto:davidcking.inbox@gmail.com>)
>>     15 Dec 17 17:47
>>
>>     This question was reported via the web interface at wormbase.org
>>     <http://wormbase.org>. You can also email us
>>     <mailto:help@wormbase.org> directly.
>>
>>     -- 
>>     -- 
>>     You received this message because you are subscribed to the
>>     "WormBase: help" group.
>>     To post to this group, send email to help@wormbase.org
>>     <mailto:help@wormbase.org>
>>     To unsubscribe from this group, send email to
>>     help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>>     For more options, visit this group at
>>     http://groups.google.com/a/wormbase.org/group/help?hl=en
>>     <http://groups.google.com/a/wormbase.org/group/help?hl=en>
>>
>
>     -- 
>     ===========================================
>     WormBase
>     European Bioinformatics Institute (EMBL-EBI)
>     European Molecular Biology Laboratory
>     Wellcome Trust Genome Campus
>     Hinxton
>     Cambridge CB10 1SD
>     United Kingdom
>     ===========================================
>
>
>
>
> -- 
> David C. King, PhD.
>
> Osborne Nishimura lab
> Colorado State University
> Biochemistry & Molecular Biology
> 1870 Campus Delivery
> 200 W. Lake St.
> 239 MRB Building
> Fort Collins, CO 80523


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
