### ISSUE TITLE
Wrong chromosome in EU2917 strain annotation

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6057]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi!<br/>I'm a postdoc in the Bowerman Laboratory. A strain that my lab submitted a few years ago (EU2917) has the wrong chromosome listed for it. It is an endogenous CRISPR line linking GFP to the gene drp-1. drp-1 is located on Chromosome IV, but currently in wormbase, it is saying EU2917 is on chromosome V. I was wondering if this could be fixed please? Thank you for your time!<br/>-Molly-</p>

**Reported by:** Moll***** (mjud************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by Paul-Davis** [comment]
Hi Molly,

Thanks for bringing this to our attention. We regularly update our 
strain data from the CGC which includes the genotype information stating 
Chromosome V. I will feed this back to the CGC but in the mean time have 
updated the WormBase entry which will update in the WS264 release of 
WormBase.

Paul


On 20/12/2017 01:07, no-reply@wormbase.org wrote:
> Content Correction
>
>   Hi!
> I'm a postdoc in the Bowerman Laboratory. A strain that my lab 
> submitted a few years ago (EU2917) has the wrong chromosome listed for 
> it. It is an endogenous CRISPR line linking GFP to the gene drp-1. 
> drp-1 is located on Chromosome IV, but currently in wormbase, it is 
> saying EU2917 is on chromosome V. I was wondering if this could be 
> fixed please? Thank you for your time!
> -Molly-
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6057. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6057>.
>
> Reported by: Molly Jud (mjud@uoregon.edu)
> 20 Dec 17 01:07
>
> Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 
> Firefox/57.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
