### ISSUE TITLE
  Hi, How can I find out the gene disru...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6063]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, How can I find out the gene disruption technologies used to obtain the gene functions listed here.<br/>ftp://ftp.wormbase.org/pub/wormbase/releases/WS262/species/c_elegans/PRJNA275000/<br/>Thank you.</p>

**Reported by:** Nick (nid1************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by chris-grove** [comment]
Hi Nick,


 The FTP link you provided in your question points to GFF and FASTA files pertaining to the BioProject PRJNA275000, which refers specifically to the genome sequence of the C. elegans Hawaiian isolate strain CB4856. So, there aren't really any gene function annotations in these files. Did you mean to refer to a different FTP directory? Or, if not, can you specify which gene function information you are specifically referring to?


Thanks,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
From user:
"Thanks for getting back to me.
I really meant to ask about the file named: phenotype_association – This file contain a list of genes and then the phenotypes associated to those genes. I am interested in how those phenotypes were identified and linked to the genes. The knock out/down technologies etc."

**Comment by chris-grove** [comment]
Hi Nick,


OK, so you are looking at this file, for example?


ftp://ftp.wormbase.org/pub/wormbase/releases/WS262/ONTOLOGY/phenotype_association.WS262.wb


This file itself doesn't specify the exact technology used but does refer to the specific genetic variation (e.g. WBVar00250471) or RNAi experiment (e.g. WBRNAi00003960) that was annotated as the cause for the observed phenotype. You can look up the details of the variation object by going to the respective variation object page in WormBase, like this:


http://www.wormbase.org/species/c_elegans/variation/WBVar00250471#03267-5-3


You can find isolation details and molecular details for the variation on this page.


To search for additional variation objects, use the WormBase search box and make sure to search "for a variation" and paste in your WBVar ID and search.


To find RNAi experiment details, you'll want to take a look at the WormBase RNAi page, like this:


http://www.wormbase.org/species/c_elegans/rnai/WBRNAi00003960#0415--10


On that same page, you can search for more RNAi IDs using the search box with the "for a rnai" criteria set.


Let us know if you need something else.


Chris

**Comment by chris-grove** [comment]
From user:
"That’s great. Individually that is easy enough, but is there a quicker way to identify the different technologies used? Trying to be more clear, I am interested in a particular few genes which you have now explained how I get the information for. But I am also interested in the overall technology use. Is there a list of the different practises used for all the mutations in that file?"

**Comment by chris-grove** [comment]
Hi Nick,


 There isn't really a way to get at this info directly through the WormBase website, currently, but I can query it out of the database. So that you're aware, this is the WormBase/ACEDB ?Variation class data model, indicating what kind of information we curate for variations/alleles:


http://www.wormbase.org/tools/schema/run?class=Variation&view=expand


So, we capture attributes like "Variation_type" which can be "Engineered_allele" or "Transposon_insertion" for example; we also capture "Production_method" like "CRISPR_Cas9" or "TALENs" for example; we also capture details about "Isolation" such as "Mutagen" or "Reverse_genetics"; if there's anything else from that data model that I didn't mention that you'd like to see (or if you can narrow down the list to what you are interested in) let me know and I can construct an appropriate query.


Chris

**Comment by chris-grove** [comment]
Hi Nick,


 Here's a list of all WormBase variations that have been annotated to a phenotype, including ID, public name, variation type, production method, and mutagen. The data is quite sparsely populated as it may not have been curated completely and/or the authors did not report it in their papers.


Chris
