### ISSUE TITLE
  I was wondering if the allele db99 fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6066]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was wondering if the allele db99 for flp-18 (strain AX1410) has been curated yet.  <br/>Thank you for any help.</p><p>What were you doing? <br />&nbsp;&nbsp;I am setting up a cross, and want to be able to track the mutation.</p>

**Reported by:** Doug******* (dkre************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Doug,

Unfortunately the exact sequence change for this allele is not available 
so has not been curated. The source of this allele is cites as Choi S et 
al. (2013) Neuron "Analysis of NPR-1 reveals a circuit mechanism for 
behavioral quiescence in C. elegans"

https://www.ncbi.nlm.nih.gov/pubmed/23764289

The available data has been extracted into this Variation record: 
http://www.wormbase.org/species/c_elegans/variation/WBVar02125005#0213-459-3

Paul

On 29/12/2017 14:26, no-reply@wormbase.org wrote:
> Feature Request
>
>   I was wondering if the allele db99 for flp-18 (strain AX1410) has 
> been curated yet.
> Thank you for any help.
>
> What were you doing?
>   I am setting up a cross, and want to be able to track the mutation.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6066. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6066>.
>
> Reported by: Doug Reilly (dkreilly@wpi.edu)
> 29 Dec 17 14:26
>
> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/63.0.3239.84 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
