### ISSUE TITLE
  How do we get Gene ontology termss fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6069]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do we get Gene ontology termss for Genbank genome. how do we combine both</p><p>What were you doing? <br />&nbsp;&nbsp;metabolic reconstruction</p>

**Reported by:** vani***********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by vanaukenk** [comment]
Hello,

Thank you for writing to WormBase.

If you are interested in downloading all of the Gene Ontology annotations for the C. elegans genome, we recommend downloading the Gene Association file from: http://geneontology.org/page/download-annotations

The annotations in this file are associated with WormBase gene IDs, e.g. WBGene00015776.

Please let us know if you need any additional assistance.

Best,
--Kimberly Van Auken
