### ISSUE TITLE
Hi 
I need help regarding promoter of AWC neurons ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6071]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi 
I need help regarding promoter of AWC neurons to express gene in these neurons.

Thanks!

**Reported by:** supi (supi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Safari 11.0.2

**Comment by chris-grove** [comment]
Hello Supi,


If you navigate to the AWC anatomy page in WormBase:


http://www.wormbase.org/species/all/anatomy_term/WBbt:0005672#013--10


You can find "anatomy function" annotations in the "Associations" table. Look at the "AWC" entries in the "Body Parts Involved" column to find descriptions of the construct used to express in the AWC neurons. These descriptions will give you information about promoters that drive expression in AWC neurons, although it may not be entirely specific. These include the promoters of:


gcy-10

odr-3


In the "Ontology Browser" widget, at the bottom, you will find a short list of genes that may be specifically/exclusively expressed in the AWC neurons. The two genes listed currently are:


srd-17

nrde-3


I hope that helps.


Best,


Chris Grove

WormBase
