### ISSUE TITLE
WormMine GFF loading problems

### ISSUE THREAD

**Issue by nuin** [WormBase/website#6072]
:12] 
I created a new pre-processed GFF file where the exons have IDs like `ID=Exon1`, and the build fails with this error:
```-retrieve-from-gff3:
[integrate] Processing file: new_gff.gff

BUILD FAILED
/mnt/data2/intermine_newest2/imbuild/integrate.xml:54: The following error occurred while executing this line:
/mnt/data2/intermine_newest2/imbuild/source.xml:253: java.lang.RuntimeException: Failed setting setRefsAndCollections() in GFF3Converter - processing child before parent - Y74C9A.6
```

Grepping the new GFF file, I get
```
im-dev1 :: ip-10-0-1-221 :: datadir/wormbase-gff3/final ‹im-262*› % grep "Y74C9A.6" new_gff.gff
I       WormBase        gene    3747    3909    .       -       .       ID=WBGene00023193;Name=WBGene00023193;interpolated_map_position=-21.9001;sequence_name=Y74C9A.6;biotype=snoRNA;so_term_name=snoRNA_gene;curie=WB:WBGene00023193;Alias=Y74C9A.6
I       WormBase        exon    3747    3909    .       -       .       ID=Exon1;Parent=Y74C9A.6
```

and the ID is only on an exon and a `Alias` of a gene. I went back to the original file, non-pre-processed GFF, and grepping it

```
im-dev1 :: ip-10-0-1-221 :: datadir/wormbase-gff3/raw ‹im-262*› % grep "Y74C9A.6" c_elegans.PRJNA13758.WS262.gff
I       WormBase        gene    3747    3909    .       -       .       ID=Gene:WBGene00023193;Name=WBGene00023193;interpolated_map_position=-21.9001;sequence_name=Y74C9A.6;biotype=snoRNA;so_term_name=snoRNA_gene;curie=WB:WBGene00023193;Alias=Y74C9A.6
I       WormBase        snoRNA  3747    3909    .       -       .       ID=Transcript:Y74C9A.6;Parent=Gene:WBGene00023193;Name=Y74C9A.6
I       WormBase        exon    3747    3909    .       -       .       Parent=Transcript:Y74C9A.6
I       history nc_primary_transcript   3782    3904    .       -       .       ID=Transcript:Y74C9A.6:wp166;Name=Y74C9A.6:wp166
I       history exon    3782    3904    .       -       .       Parent=Transcript:Y74C9A.6:wp166
```

meaning the ID is present in some other structures, like the small RNA, that actually has a `Transcript` label and ID.

Conclusion: `Y74C9A.6` is present in an exon (as a parent of that exon) and only present in a secondary or tertiary ID from a gene, meaning the exon exists but there’s no parent Transcript/CDS to it, at least in the file we are loading. (edited)

Now, should I remove exons that have parents that are not represented in Transcripts/CDSs? Or should I include things like snoRNA and other structures in the pre-processed file to allow for InterMine to see the parents? What is the best strategy?

**Comment by nuin** [comment]
#1217
#1290
#4315

**Comment by chris-grove** [comment]
@nuin 
I don't know what the answer is, but I'd like to point out some observations:

1) The error message was: "processing child before parent - Y74C9A.6"

2) The original GFF file refers to the gene object, the transcript object (snoRNA), and the exon for this gene. The gene and transcript each have a class qualifier at the beginning of their IDs:

ID=Gene:WBGene00023193
ID=Transcript:Y74C9A.6

and the exon refers to the parent as:

Parent=Transcript:Y74C9A.6

3) The processed GFF file (new_gff.gff) has only the gene and exon (skips the transcript) and the gene ID is of the format:

ID=WBGene00023193

whereas the parent reference for the exon is:

Parent=Y74C9A.6

So, taken together, I would guess that the new_gff file needs to include the transcript line, probably with the transcript class prefix in the ID (ID=Transcript:Y74C9A.6) and the reference to the parent from the exon should refer to the transcript, also including the class prefix in the ID (Parent=Transcript:Y74C9A.6). Maybe that's already the conclusion you came to.

I would opt to include the snoRNA (and other types) transcripts in the GFF and not filter them out.

**Comment by nuin** [comment]
Hi Chris

I will work on that, but I am not sure if InterMine will be able to see lines that are not `mrna`, `gene`, `cds` and `exons` on the third column. If the `snoRNA` can be treated as a transcript, we might need to change the label to `mrna`, if the system is not able to see the `snoRNA`. I will keep testing .

Thanks

**Comment by nuin** [comment]
I cut an excerpt of the GFF file and organized a small list of exons that have no parent (orphans? at least in the pre-processed GFF file) and I will check this partial list for possible DNA structures apart of `snoRNA` that are parents to these exons at least.
With this smaller file, I was able to complete a build, after removing the offending exons (for testing), and it seems the results are an improvement.


In the transcripts table I see

```
 secondaryidentifier | intermine_method |    symbol    | primaryidentifier | lastupdated | length |   id    | name | scoretype | score | chromosomeid | chromosomelocationid | organismid | proteinid | sequenceid | sequenceontologytermid | geneid  |            class
---------------------+------------------+--------------+-------------------+-------------+--------+---------+------+-----------+-------+--------------+----------------------+------------+-----------+------------+------------------------+---------+------------------------------
                     |                  | Y74C9A.3     | Y74C9A.3          |             |   6115 | 1000010 |      |           |       |      1000005 |              1000009 |    1000000 |           |            |                1000011 | 1000007 | org.intermine.model.bio.MRNA
                     |                  | Y74C9A.2a.1  | Y74C9A.2a.1       |             |   5299 | 1000031 |      |           |       |      1000005 |              1000030 |    1000000 |           |            |                1000011 | 1000029 | org.intermine.model.bio.MRNA
                     |                  | Y74C9A.2a.2  | Y74C9A.2a.2
```

a gene ID in the `geneid` column

Nothing showsup on the `exon` table, but I see this in the `exonstranscript` table
```  
exons  | transcripts
---------+-------------
 1000013 |     1000010
 1000021 |     1000010
 1000023 |     1000010
 1000025 |     1000010
 1000027 |     1000010
 1000033 |     1000031
```


where we have many exons connected to a transcript (i.e. 1000010 with 5 exons)

**Comment by chris-grove** [comment]
@nuin 
Can you fill in the details pertaining to this ticket here? Thanks!

**Comment by nuin** [comment]
In the model browser we have this now: 


![screen_shot_2018-01-04_at_3 11 41_pm_480](https://user-images.githubusercontent.com/6273/34626155-d4e6f0f0-f218-11e7-9b1d-48d7af28f2b4.png)

and this

![screen_shot_2018-01-04_at_3 13 30_pm_480](https://user-images.githubusercontent.com/6273/34626170-e6394a56-f218-11e7-9735-ea39d61a9ce4.png)

This solves part of the problem.

There's still an issue with exons,  where exons children of structures not `gene`, `mrna` and `cds`  generate an error on load, as structures like `snoRNA`  that are parents to exons are not capture in our pre-processing step.

I am defining a list of new structures for capture in processing the full GFF and check if they are accepted by the InterMine loader.

**Comment by nuin** [comment]
The GFF scrape script has been modified to try to capture all possible categories represented in the GFF3 file as

```bash
egrep "^\S*\s(WormBase)\S*\s(gene|mRNA|CDS|exon|miRNA|mRNA|ncRNA|scRNA|snoRNA|snRNA)" $1 > $2
```

the script extracts all lines that have these labels in the third column, and all are accepted by InterMine.

But there are still some issues in loading the resulting file, mostly for _orphan_ exons. These axons have parents (in an initial check) that are `pseudogene_transcripts` and `piRNA`, which are not accepted by InterMine as a class that can be loaded in the module. I am cleaning the processed GFF file and testing a build for model and data checking.

**Comment by nuin** [comment]
Also, there are cases where the exon is linked to a gene, but the it has as a parent a transcript ID that is not represented in the processed GFF, indicating that the transcript/structure is labelled not in the classes mentioned above.

**Comment by nuin** [comment]
I got information from InterMine that any extra classes (more labels/astructures in the third column) require change on the core code. I don't know yet were this resides and I will update accordingly, as there are a number of exons that are orphans.

**Comment by nuin** [comment]
I have a new build with 6000 lines worth of GFF info on im-dev1 for testing. There are a number of new RNA types in the model now.

Can you check @chris-grove?

![screen shot 2018-01-08 at 1 12 42 pm](https://user-images.githubusercontent.com/6273/34690271-b3a4a874-f475-11e7-917c-95e3a6199ef4.png)

**Comment by chris-grove** [comment]
@nuin 
I really don't think we want new (or separate in general) classes for mRNA, mRNA region, snoRNA, ncRNA, etc. These are just different types of transcripts (each type should be captured in the SO Term attribute) and should generally share the same attributes as any transcript. We should be able to query for these in the transcript class by constraining the "Sequence Ontology Term (SO Term)" attribute of transcripts. I think creating separate classes in WormMine will create confusion.

**Comment by nuin** [comment]
OK.

There are possibly two solutions for this then:

- keep only mRNA (third column) and remove exons that are somewhat linked to `snoRNA`, `piRNA`, etc avoiding orphan exons loading errors. This would require some advanced pre-processing 

- change the third column of all the different RNAs to some catch-all class. This might be biologically incorrect, but if we are capturing the structures, we can try to "store" them in one class only (maybe try to link later to a page or some more information about it).

**Comment by chris-grove** [comment]
I've responded on Slack, somewhat. What kind of transcript types can Intermine (consistently) load besides mRNA?

**Comment by nuin** [comment]
ATM, the pre-processed GFF file contains (from the third column)

`gene|mRNA|CDS|exon|miRNA|mRNA|ncRNA|scRNA|snoRNA|snRNA`

all the other element types in the third column generate an error, but can be included in the loading.

**Comment by chris-grove** [comment]
OK, we should also include, if possible, tRNA, piRNA, lincRNA, rRNA

**Comment by nuin** [comment]
Will do, hopefully in the next couple of days. If we keep in separate classes they will be unique classes in the method, is that OK?

**Comment by chris-grove** [comment]
@nuin I don't know what you mean by: "If we keep in separate classes they will be unique classes in the method, is that OK?"

**Comment by nuin** [comment]
Sorry, I meant that if we want to keep all exons, we will need to have `ncRNA`, `snoRNA`, etc. classes in the model. Or we can change all these different RNAs into an umbrella class and have the tagged differently.

I will modify the model to add the missing classes for the orphan exons, should have a new build this PM

**Comment by nuin** [comment]
So, in order to capture all exons and their parents in the GFF the pre-processing of the GFF3 files ends up being
```
egrep "^\S*\s(WormBase)\S*\s(gene|mRNA|CDS|exon|miRNA|mRNA|ncRNA|scRNA|snoRNA|snRNA|piRNA|pseudogenic_transcript|nc_primary_transcript|pseudogenic_tRNA|tRNA|antisense_RNA|lincRNA|rRNA|pseudogenic_rRNA)"
```

These classes needed to be added to the `so_terms`

```
piRNA
pseudogenic_transcript
nc_primary_transcript
pseudogenic_tRNA
antisense_RNA
lincRNA
miRNA_primary_transcript
pseudogenic_rRNA
scRNA
```

These items create new classes and when captured a table is created. That won’t change anything on the backend, but some changes will be seen in the model/query on the webapp
