### ISSUE TITLE
  what happened to most of the referenc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6079]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;what happened to most of the references that used to be linked to wormbase? Over the last several weeks I have noticed that this section no longer has references listed where as it previously did?<br/>is this section no longer supported?  if so, where do we get this info???</p><p>What were you doing? <br />&nbsp;&nbsp;e.g. references under hsr-9 is blank.  but also many others.  </p>

**Reported by:** Judi*********** (jly@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by raymond91125** [comment]
Hi Judith,

It is not our intention to remove references. It appeared that there may 
be transient problems with fetching references on gene pages as I've 
heard another report just yesterday. Similar to that case, I couldn't 
reproduce the problem; the references are showing up for me 
<http://www.wormbase.org/species/c_elegans/gene/WBGene00002027#-e-10>.

Please do not hesitate to report problems to us anything time you 
suspect seeing them.

Cheers,

Raymond


On 05/01/18 15:46, no-reply@wormbase.org wrote:
> Feature Request
>
>   what happened to most of the references that used to be linked to 
> wormbase? Over the last several weeks I have noticed that this section 
> no longer has references listed where as it previously did?
> is this section no longer supported? if so, where do we get this info???
>
> What were you doing?
>   e.g. references under hsr-9 is blank. but also many others.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6079. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6079>.
>
> Reported by: Judith Yanowitz (jly@alum.mit.edu)
> 05 Jan 18 23:46
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Well, it is reproducible sometimes. If I search for "hsr-9" a few more times (not page reload), I can hit a snag and got no references. Race condition?

**Comment by raymond91125** [comment]
Hi Judith,

I'm actually beginning to see the same problem after hitting the search 
of hsr-9 gene a few more times. eat-4 behaves the same. I got variable 
results: most times I got references but occasionally not; reloading the 
page got the same page back, whether there is reference or not.

Given that this is 'reproducible', we can begin to troubleshoot.

Thanks for the report and sorry for the trouble.

Raymond


On 05/01/18 16:07, Yanowitz, Judith wrote:
> Thanks.
> I see it in the link, though I still have some troubles with it here. 
>  I will continue to see if using your link solves the problem.
>
> Judith
>
>
> From: Raymond Lee <raymond@caltech.edu <mailto:raymond@caltech.edu>>
> Date: Friday, January 5, 2018 at 7:02 PM
> To: 
> "reply@reply.github.com 
> <mailto:reply@reply.github.com>" 
> <reply@reply.github.com 
> <mailto:reply@reply.github.com>>, 
> Judith Yanowitz <jly@alum.mit.edu <mailto:jly@alum.mit.edu>>
> Cc: "help@wormbase.org <mailto:help@wormbase.org>" <help@wormbase.org 
> <mailto:help@wormbase.org>>
> Subject: Re: [MARKETING] [wormbase-help] Feature Request: what 
> happened to most of the referenc... (Judith Yanowitz)
>
> Hi Judith,
>
> It is not our intention to remove references. It appeared that there 
> may be transient problems with fetching references on gene pages as 
> I've heard another report just yesterday. Similar to that case, I 
> couldn't reproduce the problem; the references are showing up for me 
> <http://www.wormbase.org/species/c_elegans/gene/WBGene00002027#-e-10>.
>
> Please do not hesitate to report problems to us anything time you 
> suspect seeing them.
>
> Cheers,
>
> Raymond
>
>
> On 05/01/18 15:46, no-reply@wormbase.org wrote:
>> Feature Request
>>
>>   what happened to most of the references that used to be linked to 
>> wormbase? Over the last several weeks I have noticed that this 
>> section no longer has references listed where as it previously did?
>> is this section no longer supported? if so, where do we get this info???
>>
>> What were you doing?
>>   e.g. references under hsr-9 is blank. but also many others.
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #6079. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/6079>.
>>
>> Reported by: Judith Yanowitz (jly@alum.mit.edu)
>> 05 Jan 18 23:46
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
>> (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> ---
>> You received this message because you are subscribed to the Google 
>> Groups "WormBase: help" group.
>> To unsubscribe from this group and stop receiving emails from it, 
>> send an email to help+unsubscribe@wormbase.org 
>> <mailto:help+unsubscribe@wormbase.org>.
>
>
> -- 
> __
> Raymond Lee
> raymond@caltech.eduhttp://www.WormBase.org/
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687
>
> /Confidential UPMC, Magee//-Womens//Research Institute & Foundation 
> Information.//Any unauthorized or improper disclosure, copying, 
> distribution or use of the contents of this email or any attachments 
> is prohibited. The information contained in this email message is 
> intended only for the personal and confidential use of the 
> recipient(s) named above. If you have received this communication in 
> error, please notify the sender immediately by email and delete the 
> original message./
>

-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Yes, it may be helpful for our web team to know the timing. We would 
always like to hear from our users more often ...

cheers,

raymond

**Comment by sibyl229** [comment]
@raymond91125 the reference widgets have been fixed on staging now. Sorry about that.

**Comment by chris-grove** [comment]
Hi Judith,


 This is an issue that we've been working on and have just fixed on our staging website today:


http://staging.wormbase.org/species/c_elegans/gene/WBGene00002027#-e-10


This fix should go live with the next release of the website, WS262, which should go live very soon. In the meantime, you can check the staging site:


staging.wormbase.org


if you need to see references; please keep in mind that the staging site is not very stable and may not always be available.


You can see a GitHub ticket about this issue here:


https://github.com/WormBase/website/issues/6040


Best,


Chris Grove

WormBase

**Comment by raymond91125** [comment]
@sibyl229 thanks.
