### ISSUE TITLE
Gene_class Summary Page Overview addition

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6082]
Hi,

Would it be possible to get the Evidence for a gene class displayed in the Overview widget?

Example Object
http://www.wormbase.org/resources/gene_class/ecr#0--10

Either in the box on the RH side
![paper_evidence](https://user-images.githubusercontent.com/717707/34681830-f42e1f46-f494-11e7-917c-3074a70d2ec4.png)

Or up to you.

Thanks

Paul

**Comment by a8wright** [comment]
@sibyl229 I have made it so that there is an evidence field being supplied to the gene-class overview widgets endpoint. This uses obj/get-evidence. This will give you more than just paper evidence. If you want changes just let me know.

**Comment by sibyl229** [comment]
@a8wright Thanks! I made some changes so it returns only the paper evidence, if you don't mind.

**Comment by sibyl229** [comment]
Hi @Paul-Davis paper evidence for gene class is added on staging:  http://staging.wormbase.org/resources/gene_class/ecr#0--10
Does that work?

**Comment by epaule** [comment]
looking good
