### ISSUE TITLE
Hi, I want to ion channels of C. elegans. But I di...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6085]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I want to ion channels of C. elegans. But I didn't find like human. How can I find easily? Thanks

**Reported by:** seda************** (sess**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/ion channel">http://www.wormbase.org/search/gene/ion channel</a>
**Browser:** Chrome 63.0.3239.84

**Comment by vanaukenk** [comment]
Dear Seda,


Thank you for writing to WormBase.


You can get a list of candidate ion channels for C. elegans by querying for genes annotated to the Gene Ontology term, 'ion channel activity' (GO:0005216).


From this page:


http://amigo.geneontology.org/amigo/term/GO:0005216


select the Annotations tab, and use the filters on the left side of the page to filter on Organism (C. elegans) and also to exclude gene products that are annotated to terms such as regulation of ion channel activity, such as pde-2, by using the GO class (direct) filter.


The list of genes may be downloaded by clicking on the Downloads link at the top of the Annotation table.


Please let us know if you need any additional assistance.


Best,
--Kimberly Van Auken

**Comment by chris-grove** [comment]
Hello Seda,


 Just to add to Kimberly's comments:


You may also be interested in genes that have been annotated to "is_a" descendant terms of "ion channel activity", as often times many genes are annotated to a more specific term and not directly to the more general term of "ion channel activity". To get this list I would recommend using the WormMine tool, discoverable in the Tools menu on any WormBase page:


http://intermine.wormbase.org/tools/wormmine/begin.do


Under the "GENE ONTOLOGY" heading on the WormMine homepage, you can find a template query called "GO Term --> is_a Descendants". Click that to begin the template query, and in the field "GO Term > Name" replace the pre-populated "protein glycosylation" with the term "ion channel activity" and click on the green "Show Results" button. This will return a table of GO terms that includes the "ion channel activity" term itself, as well as all "is_a" descendants. You can then use the "Save as List" button at the top to save the list of 135 terms indicated with the "GO Term > Relations > Child Term (135 Ontology Terms)". I've gone ahead and created this list and made the list public, so if you click on the "Lists" tab and click on the "View" option you can already see the list titled "ion channel activity and descendant terms" with 135 Ontology Terms. Then you can use the following query to get all C. elegans genes annotated to any of these terms:


<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.goAnnotation.ontologyTerm.name Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.evidence.code.code Gene.goAnnotation.evidence.publications.pubMedId Gene.goAnnotation.dataSets.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <join path="Gene.goAnnotation.evidence.publications" style="OUTER"/>
  <constraint path="Gene.organism.name" code="A" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.goAnnotation.ontologyTerm" code="B" op="IN" value=" ion channel activity and descendant terms"/>
</query>

Copy the XML query above, navigate to the "QueryBuilder" tab in WormMine:


http://intermine.wormbase.org/tools/wormmine/customQuery.do


click on the "Import query from XML", and paste the XML query above into the provided search box. Then, click on the "Submit" button. This will load a query that I've constructed for you. Then click on "Show results" and you'll have a table of all genes annotated to any of these terms, the terms they are annotated to, as well as the evidence code and, if applicable, PubMed ID of the paper in which the association was reported. You can then use the "Export" button on the results page to download a tab-delimited (.tsv) file with your results. If you simply want the list of genes, use the "Save as List" button at the top of the results table and click on "Gene (315 Genes)" and export the resulting table of non-redundant gene names and IDs.


Let us know if you have further questions.


Best,


Chris Grove

WormBase
