### ISSUE TITLE
  Hi The website the next C. elegans me...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6086]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>The website the next C. elegans meeting in Barcelona is already online.<br/>http://meetings.embo.org/event/18-c-elegans<br/>Please could you activate the link in the wormbase section for meetings?<br/>Thanks!</p>

**Reported by:** Juli** (jcer**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by epaule** [comment]
thanks for the update, I added it to the entry.
