### ISSUE TITLE
Bad sorting of "Term" column in Gene Ontology tables in "Summary view" with annotation extensions on gene pages 

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6087]
I just noticed that when viewing the "Gene Ontology" widget on gene pages, in "Summary View" the "Term" column doesn't sort properly if there are any annotation extensions present (e.g. "occurs in", "has input", "happens during", etc.). For example, look at the "Biological process" table in summary view on the egl-4 gene page (expand to show 50 entries and sort on the "Term" column):

http://www.wormbase.org/species/c_elegans/gene/WBGene00001173#0-3-3

It seems that the terms with extensions sort independently of the terms without extensions. It would be good if they all sorted by term name only, regardless of extensions present or not.

**Comment by sibyl229** [comment]
Hi @chris-grove the ordering of gene ontology table in summery view should be fixed now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00001173#0-3-3 .  Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks good, thanks! Closing.
