### ISSUE TITLE
  I think there is a mistake with the "...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6089]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I think there is a mistake with the "Paper Evidence" for the mlst-8 gene. The paper listed (Mosesson et al 2009) does not discuss mLST8 or mlst-8 or C10H11.8 in C. elegans. Instead, it is about Lst2.<br/>I haven't found the correct "Paper Evidence" yet. If you have that, please let me know.</p>

**Reported by:** Aile********* (asew****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by raymond91125** [comment]
I believe the user is speaking about the reference for CGC_name. In WS262, this data has the time stamp 2016-11-29...mt3. @Paul-Davis 
Textpresso search shows the earliest paper WBPaper00032966 mentioned RNAi C10H11.8 (lst-8 homolog) and it also referred to mLST-8 (mouse gene).

**Comment by vanaukenk** [comment]
Just fyi - I'd already sent an email to @Paul-Davis and @timschedl to ask about the correct evidence for this as there was a genenames email thread about a year ago regarding the appropriate name for mlst-8.

**Comment by raymond91125** [comment]
good to know. should/could the previous thread be referenced here?

**Comment by vanaukenk** [comment]
Probably not necessary to paste the whole thread here, but the gist of it was whether or not we should consider renaming any of the existing lst- genes (the answer was no) and what was the most appropriate name for C10H11.8 which is orthologous to mammalian MLST8, Target of rapamycin complex subunit LST8.

I think the paper evidence added to mlst-8 is honestly just a clerical error as that paper describes similarity between C. elegans lst-2 and the human Lateral signaling target protein 2 homolog LST2 and was referenced in the genenames email thread solely wrt lst-2.

Hope that helps.

**Comment by Paul-Davis** [comment]
Dear Aileen,

Thank you for passing on this correction. It seems that this paper was 
associated with the gene naming in error back in 2016. There was a 
discussion on the genenames list about the possible naming of the gene 
based on confidential information and the human ortholog. mlst-8 was 
fixed upon standing for Mtor (MTOR) associated protein, LST8 homolog.

Unfortunately there is no reference for this naming but you can cite 
WormBase if you need to do so.

Paul

On 09/01/2018 20:56, no-reply@wormbase.org wrote:
> Content Correction
>
>   I think there is a mistake with the "Paper Evidence" for the mlst-8 
> gene. The paper listed (Mosesson et al 2009) does not discuss mLST8 or 
> mlst-8 or C10H11.8 in C. elegans. Instead, it is about Lst2.
> I haven't found the correct "Paper Evidence" yet. If you have that, 
> please let me know.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6089. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6089>.
>
> Reported by: Aileen Sewell (asewell@colorado.edu)
> 09 Jan 18 20:56
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 
> Firefox/57.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
