### ISSUE TITLE
how can i access the DNA sequences using matlab fu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6091]
*Help Desk query collected when no chat operators were online. Follow up required.*

how can i access the DNA sequences using matlab functions?

**Reported by:** himm*********** (himm*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/transcript/F56F11.4a.1#06--10">http://www.wormbase.org/species/c_elegans/transcript/F56F11.4a.1#06--10</a>
**Browser:** Chrome 63.0.3239.84

**Comment by Paul-Davis** [comment]
Subject: | Re: [wormbase-help] offline chat transcript: how can i access the DNA sequences using matlab fu... (himmath khatoon)
-- | --
Fri, 12 Jan 2018 12:02:33 +0000
Paul Davis <paul.davis@wormbase.org>
help@wormbase.org <help@wormbase.org>, himmath.khatoon@gmail.com


Hi, Thank you for the question, but we are a little unsure of what you are trying to do?

The DNA sequence is available for download from the sequence widget on each Transcript summary page.

http://www.wormbase.org/species/c_elegans/transcript/F56F11.4a.1#06--10

Maybe this can be used in your matlab tools?

Paul

**Comment by sibyl229** [comment]
I replied the user:

> Thanks for you question! We provide the sequence widget content in JSON format over REST API in URLs like this one:
> 
> http://www.wormbase.org/rest/widget/transcript/F56F11.4a.1/sequences?download=1&content-type=application/json
> 
> Maybe you could use a HTTP client in matlab to access the content in the URL above?
