### ISSUE TITLE
Location widget throwing error on dead variation pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6092]
On the page for WBVar00216854:

http://www.wormbase.org/species/all/variation/WBVar00216854#48--10

and on the page for WBVar00240938:

http://www.wormbase.org/species/all/variation/WBVar00240938#48--10

the Location widget is consistently throwing an error message:

![screen shot 2018-01-10 at 10 02 31 am](https://user-images.githubusercontent.com/611382/34779180-6a378890-f5ed-11e7-8873-618f29c2d670.png)

It seems both are dead variations that have merged into another variation object (see Tree Display). The problem also exists on staging.

**Comment by mgrbyte** [comment]
Could it be that all widgets should not be available on pages for which an entity is "Dead" ? (except perhaps the overview widget?)

**Comment by chris-grove** [comment]
Similarly, I found broken Location widgets on these pages:

http://www.wormbase.org/species/all/variation/WBVar02148620#02-458-10

http://www.wormbase.org/species/all/variation/WBVar02148621#02-458-10

**Comment by sibyl229** [comment]
Hi @a8wright could you take a look at this one?

**Comment by a8wright** [comment]
I have fixed this issue in production. The only thing that is still confusing is that I don't see where the user is supposed to know what the variation was merged-into. For this reason I have added a merged_into field in the overview endpoint. @sibyl229 could you display the information from this field in the overview widget?

**Comment by chris-grove** [comment]
@a8wright 
OK, thanks! I see the fix working on production for these two pages:

http://www.wormbase.org/species/all/variation/WBVar00216854#48--10
http://www.wormbase.org/species/all/variation/WBVar00240938#48--10

but not for these two:

http://www.wormbase.org/species/all/variation/WBVar02148620#-458-10
http://www.wormbase.org/species/all/variation/WBVar02148621#-458-10

Should there be a separate ticket for these last two?

**Comment by a8wright** [comment]
No need for a new ticket for now. I will investigate - it might be a similar issue

**Comment by a8wright** [comment]
@chris-grove I have fixes for these two on staging. I am guessing you know but these were not actually were linked to strain entities and nothing else. If you find any other issues please point them out. If not let me know and I will push this out to production.

**Comment by chris-grove** [comment]
@a8wright 
OK, looks good, thanks! Closing.
