### ISSUE TITLE
 Server Error: 500 at  rest/widget/expression_clus...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6093]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/expression_cluster/170WBPaper00032948:FedUp/overview">rest/widget/expression_cluster/170WBPaper00032948:FedUp/overview</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "http://datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com/rest/widget/expression_cluster/170WBPaper00032948:FedUp/overview failed with 404 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 919." </p><p>What were you doing? <br />&nbsp;&nbsp;Following a link in   Cui et al., 2017. Genetics
 https://doi.org/10.1534/genetics.116.194282 </p>

**Reported by:** Katj* (kdie**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by chris-grove** [comment]
Hello Katja, thanks for submitting the bug report. It seems to have been a temporary glitch as I can load the page from the paper now without issue:


http://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00032948:FedUp#0145--10


There is another link to a dataset from that paper that appears to have a malformed URL in the Genetics paper PDF. The correct URL for this other expression cluster dataset is:


http://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00032948:StarveUp1#5410--10


Let us know if you experience any more issues or if you have any questions.


Thanks!


Chris Grove

WormBase
