### ISSUE TITLE
  To whom it may concern: I was wonderi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6094]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;To whom it may concern:<br/>I was wondering if you provide also genome data from several C. elegans strains (ie population data) and/or from different related species? Or are you aware of such a resource? Please accept my apologies if I have missed something obvious. Many thanks for your help!<br/>With best wishes for a happy new year,<br/>Gabriel</p>

**Reported by:** Gabr************* (gabr************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by epaule** [comment]
Genomics wise:
for C.elegans we only provide full data sets for N2 (our reference strain) and CB4856 (the hawaiian strain), as you can see on http://www.wormbase.org/species/c_elegans
For the other strain we only got the data submitted to us as SNPs vs N2 and therefore are part of the variation set of N2.

Population-data wise:
I don't think we got population data integrated yet, but I vaguely remember that someone showed his natural population results at the Evolution meeting in Cambridge 2 years ago.
Also I think that Marie-Ann Felix and Asher Cutter would know of good sources if you ask them.
