### ISSUE TITLE
Hi! Please forgive me if this a naive question. I ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6096]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! Please forgive me if this a naive question. I want to obtain the exonic sequences (including utrs) for a large list of genes. I tried using wormbase parasite. However, when I query this I get multiple exon sequences for each gene. I just want to get the entire continuous coding sequence (including utrs). I have some python skills but I am not sure how to combine all of the exonic sequences for each gene. 

Thank you so much for your time! I really appreciate wormbase!

**Reported by:** Will********** (wsch*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 63.0.3239.132

**Comment by ceciliaWBPerson1** [comment]
Hi Will, 

You can do this using WormBase ParaSite BioMart. It sounds like you may have
selected the "Exon sequences" output attribute. You should rather select the
"cDNA sequences" attribute.

Please let us know if anything is unclear. 

Best,

Kevin Howe
