### ISSUE TITLE
  Hi, could you tell me how I could fin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6097]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, could you tell me how I could find out the different gene knockout technologies used for the identification of the phenotypes listed in this file: <br/>ftp://ftp.wormbase.org/pub/wormbase/releases/WS258/ONTOLOGY/phenotype_association.WS258.wb<br/>Thank you.</p>

**Reported by:** Nick (nid1************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by chris-grove** [comment]
Hello Nick,


I've gone ahead and generated a non-redundant list of 12,198 alleles/variations from the WS258 phenotype file and created the list in WormMine:


http://intermine.wormbase.org/tools/wormmine/begin.do


You can find the list under the "Lists" tab when you select the "View" option. The list is titled "WS258_FTP_phenotype_file_variations_list". With this list, we can then query out all of the relevant attributes (that are currently provided in WormMine) using the following query:


<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.otherName Allele.species Allele.status Allele.sequenceStatus Allele.sequenceDetails Allele.type Allele.typeOfMutation Allele.productionMethod Allele.mutagen Allele.missense Allele.missenseChange Allele.KOConsortiumAllele Allele.NBPAllele Allele.NemaGENETAGConsortiumAllele Allele.affects Allele.amber_UAG Allele.ochre_UAA Allele.opal_UGA" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele" op="IN" value="WS258_FTP_phenotype_file_variations_list"/>
</query>


Copy the XML query above, navigate to the "QueryBuilder" tab in WormMine, click on the "Import query from XML" link,  paste the query into the search box, and click "Submit". This will show you the query construction. Then click on "Show results" and you should have a table of all the alleles/variations and their corresponding data. From there, you can export in tab-delimited (.tsv) format.


Let us know if you have any questions.


Best,


Chris Grove

WormBase
