### ISSUE TITLE
Intermine query error, faulty reporting process

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6100]
I was testing the new WormMine (WS262) by loading all alleles' WormBase ID and Public Name (symbol) and tried to constrain the table to those alleles whose Public Name (symbol) started with an "e" (so queried for Public Name like "e*") and the query crashed showing me this screen:

![screen shot 2018-01-16 at 2 27 07 pm](https://user-images.githubusercontent.com/611382/35008078-68d2f63e-fac9-11e7-9d59-05f7b3047a87.png)

Then when I click on "Send a bug report", my Mail program opens with the following pre-constructed email:

![screen shot 2018-01-16 at 2 28 39 pm](https://user-images.githubusercontent.com/611382/35008183-9f005314-fac9-11e7-9612-9d1190654a1a.png)

with the "To:" field populated by "HELP REQUESTS ARE SENT HERE"; I assume that's supposed to be a valid email to which someone can email a bug report.

**Comment by nuin** [comment]
I will check, thanks @chris-grove

**Comment by nuin** [comment]
Added help@wormbase.org and re-deployed production. Would you mind checking it?

Thanks

**Comment by chris-grove** [comment]
I have to figure out how to get an error like that first. I cannot reproduce the same one from yesterday

**Comment by chris-grove** [comment]
OK, I somehow managed to get this error:

![screen shot 2018-01-17 at 9 58 03 am](https://user-images.githubusercontent.com/611382/35049101-fa01b5ca-fb6c-11e7-9cf4-5487eda93296.png)

and the "send us an email" link appropriately populated the "To:" address field with help@wormbase.org. I'll consider this fixed and close the issue.
