### ISSUE TITLE
Phenotype annotations missing from WS262 WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6101]
Querying for phenotypes of the e1368 allele in WormMine:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.phenotype" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.symbol" op="=" value="e1368"/>
</query>`

gives me only a single result:

![screen shot 2018-01-16 at 5 35 51 pm](https://user-images.githubusercontent.com/611382/35015753-c59dd7ca-fae3-11e7-8b5e-ebb171cba39f.png)

yet e1368 on staging (also WS262):

http://staging.wormbase.org/species/c_elegans/variation/WBVar00143947#06--10

shows 20 distinct phenotypes.

Likewise with the m41 allele: 1 phenotype on WormMine, 12 on staging:

http://staging.wormbase.org/species/c_elegans/variation/WBVar00088550#06--10

**Comment by chris-grove** [comment]
If I query for phenotypes of all alleles:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.phenotype" longDescription="" sortOrder="Allele.primaryIdentifier asc">
</query>`

it appears that WormMine only ever returns a single phenotype for each allele:

![screen shot 2018-01-17 at 10 49 02 am](https://user-images.githubusercontent.com/611382/35051821-16bbe760-fb74-11e7-9070-35b86505c4ef.png)

but in all cases where a phenotype is listed, that I checked, there are multiple phenotypes on WormBase.

**Comment by nuin** [comment]
Phenotype-Variation relationship with the current mapping (old) is a one-to-one relationship, this has to be modified to a one-to-many in the new mapping, if it's still not set as this.

**Comment by chris-grove** [comment]
@nuin Looks good! Closing.
