### ISSUE TITLE
the legend does not obviously say that C. elegans ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6102]
*Help Desk query collected when no chat operators were online. Follow up required.*

the legend does not obviously say that C. elegans in WP.  this could be added at the top.  it might be better to actualy say Celegans: CE....   thanks.

**Reported by:** paul********** (pws@***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/protein/WP:CE03840#068359--10">http://www.wormbase.org/species/c_elegans/protein/WP:CE03840#068359--10</a>
**Browser:** Chrome 63.0.3239.132

**Comment by khowe** [comment]
The different protein sets were historically treated as different resources by WormBase, each with their own resource prefix (WP = "wormpep" =  C. elegans proteins, BP = "brigpep" = C. briggsae proteins). But id after the prefix (i.e. the CE**) is unique across species (and also starts with a species code). 

So the prefixes are redundant. I've always wanted to get rid of them, but have been nervous about how this might affect connectivity with other resources, references to these proteins in papers etc etc.
