### ISSUE TITLE
I've been looking for a description of the color c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6107]
*Help Desk query collected when no chat operators were online. Follow up required.*

I've been looking for a description of the color coding for the anatomic expression pattern shown on specific gene pages, but have been unable to find it. I would be grateful to be pointed in the right direction. Many thanks. 
Jim

**Reported by:** Jim ********* (jlis**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#e7c1495062a8bf3d--9">http://www.wormbase.org/about/Frequently_asked_questions#e7c1495062a8bf3d--9</a>
**Browser:** Chrome 63.0.3239.132

**Comment by chris-grove** [comment]
Hi Jim,


If you're referring to the Virtual Worm renderings, the color code was adopted from WormAtlas:


http://www.wormatlas.org/picts/Colorcode.pdf


The codes are listed as hexadecimal for HTML display.


Cheers,


Chris Grove

WormBase
