### ISSUE TITLE
Retirement/standardisation of protein prefixes

### ISSUE THREAD

**Issue by khowe** [WormBase/website#6109]
Currently, all protein objects in the database have the form PREFIX:ID. For WormBase proteins, we have historically used species-specific PREFIXes, e.g. "WP:" for C. elegans, "BP:" for C. briggsae. However, the IDs themselves already contain a species prefix (e.g. "CE" for C. elegans, "CBP" for C. briggsae). 

We propose to remove this anomaly. We are currently undecided between two options: 

(1) remove the prefix altogether for WormBase proteins, and only use the prefix for proteins that we have imported from other resouces; or

(2) Standardize on a single on a single prefix "WP:" for all WormBase proteins.

Comments welcome on pros/cons of these two options. But whichever option is implemented, the following change will be needed in the web code: do no use the prefix to look up the species from a table, but rather look inside the object (Species property). This will work regardless of which of (1) or (2) above we implement. 

Plan is to implement the data change for WS265. The web code change could be done in advance of that.

**Comment by khowe** [comment]
FAO @tharris @sibyl229 @a8wright

**Comment by tharris** [comment]
I’ve always found these prefixes to be quaint, historical oddballs. Sorry to see them go :)

I’ll need to double check, but I don’t believe the prefixes are widely used to determine species (I can think of possibly one exception that is easily corrected). We will also need to check Intermine (@nuin). 

One question though. Does stripping the prefix result in an ID that is sufficiently distinct to describe it as a protein as well as enough flexibility to add species?  Right now, we have \w\w{2,3}\d* which is itself kind of wonky.

**Comment by nuin** [comment]
On my end, we programmatically add the `WP:` on the FASTA loader in order to merge with whatever is coming from AceDB's Protein.xml. The FASTA loader needs work anyway, due to changes in InterMine's core model/code, but by removing the prefix won't affect much on WormMine. Whenever we are able to load other species proteins we will need to devise a loader that reads the information from the ID itself.

**Comment by khowe** [comment]
@tharris that's a good point. I think we have enough flexibility to add species (we use 2 or 3 letter prefixes for the actual ID), but they may not easily be identifiable as proteins.  

If being able to identify the entity type from the ID is something we want to keep, maybe that's a case for keeping the "WP:" (but standardizing on WP for all worm)?

**Comment by tharris** [comment]
Yep, the blast table was the example I was thinking of, too!

I generally agree with you about treating IDs in an opaque fashion. However, we’ve often used public names as primary IDs. That coupled with the well-defined C. elegans nomenclature means that (some) IDs also carry meaning. It can be useful to use these to our advantage at times, although it tends to reduce portabilIty.

**Comment by sibyl229** [comment]
Yeah, I agree it's good that we **generate** meaningful. Meaningful ID is useful when external users consume our IDs in their system. On opacity, I only meant that the web code should try to **consume** an ID as if it is opaque, and obtain other info (like species) from the database.

**Comment by tharris** [comment]
Yes, totally agree. 

But treating IDs as an opaque entity has not always been sufficient. We haven’t always had species for all classes, for example. But I believe that’s now a moot point.

**Comment by sibyl229** [comment]
Hi @khowe it looks like the protein ID and transcript ID changes have made into the WS266 database, and staging is currently running on it. Is there anything we need to test?

**Comment by khowe** [comment]
Thanks @sibyl229 

I think it would be good to do some clicking around. @epaule @Paul-Davis @gw3 can you chip in?

**Comment by sibyl229** [comment]
I verified that the transcript and protein pages are loading. Search via the new identifier is working. 
- https://staging.wormbase.org/species/c_elegans/transcript/AC3.1a.1#0635--10
- https://staging.wormbase.org/species/c_elegans/protein/CE29545#0639--10

Search via the old identifier might not give helpful suggestions though. I'm not sure if that is a problem.

**Comment by sibyl229** [comment]
@epaule oh, let me talk with @tharris about the broken links on the live site. It looks like one of the production instance is not using the right rest api.

**Comment by sibyl229** [comment]
@epaule the broken production link should be fixed now
