### ISSUE TITLE
Change wording of Enrichment Analysis result redirect

### ISSUE THREAD

**Issue by kyook** [WormBase/website#6110]
Hiya, 
On this page http://www.wormbase.org/tools/enrichment/tea/tea.cgi
The instructions at top say 
"Click here for TEA results"
"Click here for PEA results" . etc. 

Only these links do not go to pages that list results, rather they go to pages where people can perform those analysis

Perhaps the instructions should say
"Click here to search for Tissue Enrichment"
"Click here to search for Phenotype Enrichment"
"Click here to search for GO term Enrichment"

Or something like that.

**Comment by raymond91125** [comment]
Not sure what you mean. It's working as intended by going to the proper location on the page.
<https://drive.google.com/file/d/1I3Egk9w6Y9s3kF2fd9st8tfawVnARF-w/view?usp=sharing>

**Comment by raymond91125** [comment]
The hyperlinks go to page anchors within the same page of sections labelled X Enrichment Analysis Results. I still don't understand what the concern is, I'm afraid.
