### ISSUE TITLE
Hi there WormBase team!

Lately it seems that the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6113]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there WormBase team!

Lately it seems that the redirect to yeastgenome.org for all the yeast homologs is not working anymore, or the redirect works and then the page on yeastgenome.org says "Page not found". Is that a problem of wormbase or yeastgenome.org?

Best! Simon

**Reported by:** Simo********* (haeu****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001811#036eg7-94cb-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001811#036eg7-94cb-10</a>
**Browser:** Firefox 57.0

**Comment by epaule** [comment]
thanks for reporting that. Good to see that SGD revamped their website.
I updated the links and they should percolate through to the live website over time.

@sibyl229 I committed the fix to staging only
