### ISSUE TITLE
Gene Ontology widget filtering issue

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6114]
I found some strange table filtering behavior in the Gene Ontology widget tables. For example, if I navigate to the mlk-1 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00003374#03--10

and I click on "Full View" to look at the entire annotations for "Biological process" terms annotated to mlk-1, if I enter "IGI" into the "Search" box to filter the table to only IGI evidence code annotations, the table returns 3 GO terms and their respective annotations (apparently):

GO:0008340 | determination of adult lifespan
GO:0031103 | axon regeneration
GO:0050829 | defense response to Gram-negative bacterium

If I then sort the table on the "Evidence code" column, and then immediately resort on the "Term ID" column (all while leaving "IGI" in the "Search" filter box), I now see 5 GO terms and their respective annotations:

GO:0008340 | determination of adult lifespan
GO:0031103 | axon regeneration
GO:0050829 | defense response to Gram-negative bacterium

as well as:

GO:0042594 | response to starvation
GO:0048680 | positive regulation of axon regeneration

So, on the first filtering event, apparently the last two terms are being hidden and it seems their annotations are being inappropriately displayed as associated to the "axon regeneration" term. On sorting the "Evidence code" column and then resorting the "Term ID" column, the last two terms appear with their respective annotations. Here's a screen recording of the behavior:

﻿https://www.dropbox.com/s/npxigqewxt3nkq0/GO_widget_filter_bug_on_mlk-1_gene_page_Jan_19_2018.mov?dl=0

**Comment by sibyl229** [comment]
Hi @chris-grove Nice catching the gene ontology table problem! It should be fixed now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00003374#03--10 Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks good, thanks! Closing.
