### ISSUE TITLE
UniProt links to specific protein pages are being redirected to UniProt homepage (URL constructor has changed)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6115]
On WormBase protein pages, in the External Links widget, links to UniProt entries are redirecting to the UniProt homepage when they should be leading directly to the specific protein page at UniProt. This appears to be a result of a change in URL constructor for the links. For example on the protein page for MLK-1, isoform a:

http://www.wormbase.org/species/c_elegans/protein/WP:CE30383#01--10

the External Links widget lists a UniProt entry with accession number "A0A0K3AV08" that is currently hyperlinked to the URL:

http://www.ebi.uniprot.org/entry/A0A0K3AV08

but this redirects to the UniProt homepage:

http://www.uniprot.org/

when it should lead to the specific protein page with the A0A0K3AV08 accession number:

http://www.uniprot.org/uniprot/A0A0K3AV08

This constructor should be changed for all protein UniProt external links across the site.

**Comment by epaule** [comment]
the constructor has been changed already last week with c99a119bb890f5159996218c823911d8c8375004 I should arrive shorty on staging for testing.
