### ISSUE TITLE
UniProt_GCRP external links lead right back to same WormBase protein page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6116]
It seems that on protein pages, in the External Links widget, the entries for database "UniProt_GCRP" simply link right back to the same protein page that you're on. For example, on the NSY-1, isoform a protein page:

http://www.wormbase.org/species/c_elegans/protein/WP:CE44901#01--10

If I click on either the "UniProt_GCRP" database name or the accession number "Q21029", I am directed right back to the same protein page:

http://www.wormbase.org/species/c_elegans/protein/WP:CE44901

I figure this must be a bug; it certainly isn't an external link.

**Comment by epaule** [comment]
resolved in e2511a17167f80967e21cd55f48bb8a6daf653cb should be available on staging soon
