### ISSUE TITLE
Chris: Hello Neba, how can I help? visitor_name (v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6120]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Neba, how can I help?</br>visitor_name (visitor_email): hello</br>visitor_name (visitor_email): i am trying to search some O.volvulus proteins but i dont get back a search sequence</br>Chris: OK, do you have some particular protein IDs or names you're looking for?</br>visitor_name (visitor_email): yes say this ID: http://www.cbs.dtu.dk/services/SignalP/</br>visitor_name (visitor_email): sorry, OVOC10819</br>Chris: OK thanks</br>Chris: OK, it you open up WormBase and type "OVOC10819" into the search box in the upper right corner of the screen, select to search "for a protein" from the search box drop down menu and press ENTER to perform the search</br>Chris: that should take you to the protein page for OVOC10819:</br>Chris: http://www.wormbase.org/species/o_volvulus/protein/OV:OVP02506#06--10</br>visitor_name (visitor_email): Ok thank you, let me try that</br>Chris: You can view the sequence of the transcript, coding sequence, and protein amino acid sequence by clicking on the gray double helix icons in the Transcript, CDS, or Protein columns of the table in the Overview widget</br>Chris: or you can look at the protein sequence in the "Sequences" widget</br>Chris: Did that get you what you were looking for?</br>visitor_name (visitor_email): i think there is a problem with my network</br>Chris: Hmmm, is the page not loading for you?</br>visitor_name (visitor_email): after following all the procedure you listed, i still dont get results</br>Chris: Do you see anything at the link I pasted in?</br>Chris: Which web browser are you using?</br>visitor_name (visitor_email): it loads and then stops without returning the sequence</br>Chris: OK</br>visitor_name (visitor_email): The link you pasted loads as well but i see no sequence, just a blank space</br>visitor_name (visitor_email): i am on FIREFOX</br>Chris: Here's a link to a screenshot that I just took of the page that I see with that link:</br>Chris: https://www.dropbox.com/s/em80qxbvgct7kc5/Screenshot%202018-01-21%2014.23.21.png?dl=0</br>Chris: Do you see anything resembling that?</br>Chris: Which version of Firefox are you running?</br>visitor_name (visitor_email): Firefox Setup 42.0b9</br>visitor_name (visitor_email): i have not yet received the link to the screenshot you just sent, i really think its connection issues</br>Chris: OK, that's possible. Do you see anything at all when you go to that link? Also, you're running an older version of Firefox. I would recommend updating your Firefox browser as soon as you can, for security reasons if nothing else. With the updated Firefox may work better</br>visitor_name (visitor_email): The link has not yet downloaded on my side here, its still loading. as for the Firefox, ill try to get an updated version as you've recommended soonest. i'll let you know what i see when i retrieve the link</br>Chris: OK, yes, it sounds like you have a very slow connection. You can try to run an internet speed test, by Googling "internet speed test" and running the test or using a dedicated website like ﻿﻿http://www.speedtest.net/</br>Chris: If you're getting much less than 1-5 Megabits per second you're internet speed is probably the limiting factor</br>Chris: your internet speed</br>Chris: Hello Neba? Is there anything else I can help you with?</br>visitor_name (visitor_email): Nothing for now, Thank you, you have been of great help</br>Chris: OK, best of luck. Have a nice day!

**Reported by:** Neba******** (neba*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/support">http://www.wormbase.org/tools/support</a>
**Browser:** Firefox 42.0

**Comment by chris-grove** [comment]
Hello again Neba,
If you'd like, you can send me your list of protein IDs/names for the sequences you want and I can send you a file with all of data.
Let me know.
Best,
Chris

**Comment by chris-grove** [comment]
Haven't heard from user; will close for now.
