### ISSUE TITLE
Making WormBase compatible with Internet Explorer?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6121]
*Help Desk query collected when no chat operators were online. Follow up required.*

I recently experience difficulties in reading the references of an entry. I see three abstract lines, the third one is fading. Unlike in previous versions, I cannot expand these three lines by clicking to see the entire abstract. Moreover, clicking on the title will result in a switch the the respective paper, but will not show the abstract, but only the references cited therein (obviously). Can you please show me a way to read (and copy-paste) the abstract of single references, as I was able to do it in previous Wbase versions? Thanks

**Reported by:** Ralf*********** (baum******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002133#0-ecd1-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00002133#0-ecd1-10</a>
**Browser:** Microsoft Internet Explorer 11.0

**Comment by hansduo** [comment]
This seems to happen due to an incompatibility between the Browser used  (IE11) and the scripts needed for that function. I can reproduce that missing functionality.

**Comment by chris-grove** [comment]
Hi Ralf,


 Apologies for the difficulty. Could you possibly try a different web browser? My understanding was that WormBase doesn't have active support for Internet Explorer, but Todd Harris (CC'ed) could clarify.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
From Ralf:
"hi Chris, yes, it works with Firefox. I am routinely, like most European labs, use Internet Explorer, and that one caused the problem. 
Best

Ralf"

**Comment by chris-grove** [comment]
OK, thanks for letting me know Ralf, we appreciate it. Apologies that IE doesn't work so well with WormBase. I can ask Todd if there should be a push to be compatible with IE in the future.


Chris

**Comment by sibyl229** [comment]
Hi @chris-grove I think we should be able to support IE11. I'm working on this.

**Comment by sibyl229** [comment]
Ready for testing on staging http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#e--3
(IE11 required for testing)

**Comment by hansduo** [comment]
Works fine here.

**Comment by sibyl229** [comment]
Great! Thanks a lot @hansduo for the testing!
