### ISSUE TITLE
URL links in Overview widgets on Analysis pages for TreeFam and Inparanoid_8 lead back to WormBase

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6122]
In the Overview widget on the "TreeFam" Analysis page:

http://www.wormbase.org/resources/analysis/TreeFam#0--10

the URL is listed as "www.treefam.org" but clicking on it appears to load the same WB page rather than link to the actual site. Command/control clicking (to open a new tab in Firefox) leads to a WB search for the text "www.treefam.org".

Similar issue on the "Inparanoid_8" Analysis page:

http://www.wormbase.org/resources/analysis/Inparanoid_8#0123--10

Clicking on the URL entry "inparanoid.sbc.su.se" links back to the WB page for "Inparanoid", not to the actual site.

**Comment by epaule** [comment]
there is also a data patch, you can load into the WS263 acedb database:
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS263/acedb/PATCHES/analysis_patch.ace

**Comment by sibyl229** [comment]
Thanks @epaule ! 

@tharris could you show me how to patch ACeDB?

**Comment by tharris** [comment]
Easy!
`
[tharris @ dev] [2176:~]> saceclient localhost -port 2005
Please enter userid: admin
Please enter passwd: [ITSASECRET]
acedb@localhost> Parse /path/to/your/file.ace
`

**Comment by sibyl229** [comment]
Thanks @tharris 

But it's not exactly working for me. I get:
>// Response: 53 bytes.
// Keyword Parse does not match
// 0 Active Objects

**Comment by tharris** [comment]
1. Do you know the password? It has been the same for years.

2. You also need to be listed in the `wspec/serverpasswd.wrm` file in order to have write access. I have added you there.

**Comment by sibyl229** [comment]
@tharris I think I got further this time with the right password. But it's still telling me that I don't have write access. 

>acedb@localhost> Parse /usr/local/wormbase/acedb/PATCHES/analysis_patch.ace
// Response: 60 bytes.
// Sorry, you cannot gain Write Access
// 0 Active Objects

**Comment by tharris** [comment]
Guessing this is a problem with the underlying database files and/or that sgifaceserver needs to be restated. I've made some changes to the first, and restarted the server.

**Comment by epaule** [comment]
we released WS264, so I will close that one
