### ISSUE TITLE
Dead URL link on OMA Analysis page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6123]
On the OMA Analysis page:

http://www.wormbase.org/resources/analysis/OMA#0--10

The URL link in the Overview widget:

http://www.cbrg.ethz.ch/research/orthologous/index

is leading to a dead page.

**Comment by sibyl229** [comment]
Thanks @chris-grove , the web code takes the URL in ACeDB and displays it. It seems that the URL over there is dead. Do you know who shall I ask?

**Comment by chris-grove** [comment]
@sibyl229 
It seems Christophe Dessimoz is the corresponding author on the communication:

http://www.wormbase.org/resources/person/WBPerson7052#01--10

We could ask him if he knows.

**Comment by chris-grove** [comment]
OK, his email address on WB is outdated (so my email to him bounced) but I believe I tracked down the appropriate site:

https://omabrowser.org/oma/home/

I'll email him at his new email address to confirm

**Comment by epaule** [comment]
I can update the link in geneace.
Should be https://omabrowser.org

M

**Comment by chris-grove** [comment]
@epaule 
OK, thanks. He just confirmed that 

http://omabrowser.org/

would probably be the most future proof (so, perhaps without the https)

**Comment by epaule** [comment]
it does actually redirect to the https:// site

**Comment by chris-grove** [comment]
@epaule 
OK, got it. Thanks!
