### ISSUE TITLE
Is the col-19 gene conserved in other nematodes or...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6125]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is the col-19 gene conserved in other nematodes or other organisms?

**Reported by:** Vick* (vkl1**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00000608">https://www.wormbase.org/species/c_elegans/gene/WBGene00000608</a>
**Browser:** Chrome 62.0.3202.94

**Comment by chris-grove** [comment]
Hello Vicki,


 Yes, col-19 encodes for a collagen and exhibits homology with genes in many other species. You can explore the homologies in the "Homology" widget on the col-19 gene page:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000608#0g-6-3


Best,


Chris Grove

WormBase
