### ISSUE TITLE
Gene class page Overview error

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6127]
On the page for the nhr gene class:

http://www.wormbase.org/resources/gene_class/nhr#01--10

I'm getting an error in the Overview widget:

![screen shot 2018-01-23 at 2 58 13 pm](https://user-images.githubusercontent.com/611382/35297704-dde924dc-004d-11e8-9114-1c7ca6e57a07.png)

Seems to apply to every gene class I've checked.

**Comment by a8wright** [comment]
This was fixed
