### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene_class/dpy/...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6128]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene_class/dpy/overview">rest/widget/gene_class/dpy/overview</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "http://datomic-to-catalyst-ws262.us-east-1.elasticbeanstalk.com/rest/widget/gene_class/dpy/overview failed with 500 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 919." </p>

**Reported by:** sana***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7

**Comment by a8wright** [comment]
This was a simple bug that is now fixed. It effected some gene_class overview widgets with laboratory information.
