### ISSUE TITLE
  Hello, I'm trying to find a S. haemot...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6129]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I'm trying to find a S. haemotobium gene in WormBase that has come up as a BLAST hit for my gene in S. mansoni.<br/>The NCBI page is here - https://www.ncbi.nlm.nih.gov/nucleotide/XM_012942477?report=genbank&log$=nuclalign&blast_rank=1&RID=6GU6WM5D015<br/>I can't find any gene annotated as "High affinity cAMP-specific 3',5'-cyclic phosphodiesterase 7A", and can't work out which "cyclic phosphodiesterase" it now is.  I assume the database annotations have been updated compared to the data in NCBI.<br/>Thank you so much for your assistance!!!</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to find a particular gene that I found from a BLAST search at NCBI.</p>

**Reported by:** Jane******* (jane*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by WenChenWormBase** [comment]
Dear Jane, 

This gene is annotated in a new version of the S. haemotobium genome that we do not yet have in WormBase ParaSite. We are looking to incorporate this new version in the next release (planned for March). 

Best,

Kevin
