### ISSUE TITLE
Link to author pages broken

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6130]
Hi, 
it seems the link to authors does not work for some papers. 
Example:

**Comment by draciti** [comment]
http://www.wormbase.org/resources/paper/WBPaper00052923#03--10

**Comment by draciti** [comment]
by clicking on 'Cao J' it directs me to the following page -see screenshot
<img width="626" alt="screen shot 2018-01-24 at 9 07 49 am" src="https://user-images.githubusercontent.com/901243/35339468-54ab07be-00e6-11e8-9005-8e1153bb2b7c.png">

This happened both on staging and the live site..until I opened the ticket :)
now happening only on staging
Thanks

**Comment by draciti** [comment]
on the live site it now points to a generic page with the list of authors rather than to the specific author page
<img width="988" alt="screen shot 2018-01-24 at 9 11 37 am" src="https://user-images.githubusercontent.com/901243/35339647-bea9667e-00e6-11e8-802a-fb42462ace82.png">

this does not happen for other papers. For example:
http://www.wormbase.org/resources/paper/WBPaper00051463#03--10

Clicking on author's names points to the correct person page

**Comment by sibyl229** [comment]
Hi @draciti it should be fixed on staging now http://staging.wormbase.org/search/person/Cao%20J . The inconsistent result for production is due to 30% of search traffic goes to Elasticsearch, and 70% goes to Xapian. In WS263, all the traffic will be going through Elasticsearch, as does staging site right now.

**Comment by draciti** [comment]
Awesome, thanks Sibyl. Tested and ok. Closing
