### ISSUE TITLE
Move "Gene --> Expression Pattern" template query to homepage "Expression" tab

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6131]
Apparently, at the time of writing the Methods in Molecular Biology chapter we had a template query called "Gene --> Expression Pattern" on the WormMine homepage under the "EXPRESSION" tab. This is referred to in the text of the chapter, but didn't exist in the live WormMine. I've gone ahead and created the template query on live WormMine, but cannot get it to sit under the "EXPRESSION" tab on the WormMine homepage (I tried to do this by adding the tags "im:aspect:Expression", "im:frontpage" and "im:public" to the saved template query, which I thought was sufficient, but apparently not).

This ticket is to request (or remind myself once I have access privileges) to add this template to the "EXPRESSION" tab on the WormMine homepage by the time the chapter is published (March 2018?).

**Comment by draciti** [comment]
thanks Chris! I noticed it was missing when we were at UCSF

**Comment by nuin** [comment]
@cgrove We have been having problems assigning templates to different tabs on the front page. This problem was raised with InterMine and there's no solution for it. I can try doing this from the superuser account, but I am not sure is going to work.

**Comment by chris-grove** [comment]
@nuin 
OK. I have to submit corrections for the chapter tomorrow. I have to decide whether it warrants changing the text in the chapter. I think I will leave it as is and hope that Intermine can fix the problem by publication time (probably unlikely). At the very least, the template exists and people can find it in the "Templates" tab, even if it isn't on the homepage. I'll keep this ticket open as a reminder to change it ASAP.

**Comment by chris-grove** [comment]
I've made an equivalent template query that is now available under the "EXPRESSION" tab on the WormMine front page. The section in the book chapter referring to a "Gene --> Expression Pattern" template query was removed before publication. Closing.
