### ISSUE TITLE
Interactions Cytoscape graph defaults to Physical interactions even if there are none

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6132]
@sibyl229 
First, the new interactions Cytoscape display is great!

Second: we had discussed a way of pruning the graph by default to only include physical interactions when there were possibly too many to display at once, but I found an instance of a gene that doesn't have any physical interactions, itr-1:

http://www.wormbase.org/species/c_elegans/gene/WBGene00002173#08--10

and what happens is that when the interaction network graph is expanded, nothing is rendered because the interaction type has been restricted to physical interaction types, even though there are none for this gene. Could we do a little calculation to only show physical interactions if there are any, and then if not default to regulatory interactions, and if not default to genetic interactions, and if not default to predicted interactions? Or something like that?

**Comment by sibyl229** [comment]
Hi @chris-grove I made some changes to the interaction graph: first, always show the regulatory interaction regardless of the totals, second, show a count for each type in the legend: http://staging.wormbase.org/species/c_elegans/gene/WBGene00002173#08--10 Does this solution work?

**Comment by chris-grove** [comment]
@sibyl229 
Yes, that will work, thanks. I like the counts for each type. I did notice that there are sometimes alignment issues with the counts in the legend, like on the dpy-5 gene page:

http://staging.wormbase.org/species/c_elegans/gene/WBGene00001067#08--10

![screen shot 2018-02-01 at 4 40 30 pm](https://user-images.githubusercontent.com/611382/35704861-c9bbfa02-076e-11e8-92f5-b08c301e7026.png)

This appears to happen most on Firefox, a little bit on Safari, and not at all on Chrome, from what I can tell. I'm using an iMac on OSX 10.10

**Comment by sibyl229** [comment]
Thanks @chris-grove The alignment issue in the legend should be fixed now.

**Comment by chris-grove** [comment]
@sibyl229 
Yep! Looks good, thanks!
