### ISSUE TITLE
  I'm wondering how the rtel1 mutants m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6133]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm wondering how the rtel1 mutants made by Simon Boulton's group were created? How do I know rtel1 is knocked out?</p>

**Reported by:** Mari*** (oram************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by chris-grove** [comment]
Hello Marissa,


 Could you be more specific as to which mutants you are referring to? Do you have a publication or a WormBase webpage to point to?


Thanks,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
From user: "Yes, the ones used in the attached publication." (attached PDF of paper PMID:29351848, for which we do not yet have a WBPaper ID)

**Comment by chris-grove** [comment]
I could not find a mutation of the C. elegans rtel-1 made by Simon Boulton's group. The only rtel-1 mutation I find mentioned in the paper is the tm1866 allele:


http://www.wormbase.org/species/c_elegans/variation/WBVar00250829#01234567--10


made by Shohei Mitani's group in Japan. You can find whatever information we have about the allele on that page (link above) or by following the links on that page to the National BioResource Project page for the allele:


http://shigen.nig.ac.jp/c.elegans/mutants/DetailsSearch?lang=english&seq=1866


It appears to be a 1346 bp deletion that removes four of the coding exons from rtel-1. This was apparently identified and confirmed by PCR of the genome using the primers indicated.


Chris

**Comment by chris-grove** [comment]
From user: "Great that is the same mutants they used, thank you very much!"
