### ISSUE TITLE
Restore Cytoscape interaction network viewer on Process pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6134]
I just noticed that, with WS262, the WormBase process pages are no longer displaying Cytoscape network graphs of affiliated interactions. Previously, one could view all interactions annotated as pertaining to the topic/process in Cytoscape in the "Interactions" widget. The Interactions widget is still there, as is the interactions table, but the Cytoscape graph is missing. Could we add that back?

Thanks!

**Comment by chris-grove** [comment]
Here's an example of a page where I used to be able to see many interactions in a Cytoscape viewer:

http://www.wormbase.org/resources/wbprocess/WBbiopr:00000014#015--10

**Comment by chris-grove** [comment]
Also, this is referenced in the Methods in Molecular Biology chapter coming out in March, so it would be nice to have the display available as referenced in the text of the chapter.

**Comment by sibyl229** [comment]
Hi @chris-grove interaction network for wbprocess should be fixed: http://staging.wormbase.org/resources/wbprocess/WBbiopr:00000014#015--10 Could you check if the content looks right? Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Yes! Looks good, thanks!
