### ISSUE TITLE
  On Firefox, the front page top menu (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6135]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;On Firefox, the front page top menu (About, Directory, etc) are non-responsive for mousing over and produces blank pages if clicked on.<br/>In fact, even the "Send" bottom for the help request page is defunct.<br/>On Chrome browser, they still work.</p>

**Reported by:** Raym*** (raym****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Comment by sibyl229** [comment]
Hi @raymond91125 I have trouble reproducing the problem on Firefox. Would you mind showing it to me on Slack?

**Comment by nuin** [comment]
@raymond91125 Which version of Firefox are you using? On 58.0 (64-bit) it seems fine.

**Comment by raymond91125** [comment]
Hum, that is what I'm using on Ubuntu.

**Comment by nuin** [comment]
I am on OS... er macOS.

**Comment by raymond91125** [comment]
i updated firefox on a windows 10 machine. i then saw the same problems. it could be me but not me on linux only.

**Comment by sibyl229** [comment]
Yeah, that was a genuine bug in the web code. Fixed on staging now.

**Comment by raymond91125** [comment]
More people are experiencing the problem. We need a hot fix.
