### ISSUE TITLE
WormBase not loading any widgets; non-responsive

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6139]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_email): Hi Chris, I am having problems getting the page to fully load. The side bar loads but not the main screen. When I click on an option it does not respond</br>Chris: Hmm, yes I see it too. Thanks for letting me know! There may be an update happening right now. Let me see if I can find out what's going on. Can I email you back once it's up and running again?</br>visitor_name (visitor_email): Yes! That would be great. Thank you for investigating</br>Chris: OK, I'll keep you posted. Thanks!

**Reported by:** Leah (leah**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/">https://www.wormbase.org/</a>
**Browser:** Safari 11.0.2

**Comment by chris-grove** [comment]
Hello Leah,


 I think I realized what happened. I think the site at https://www.wormbase.org (note the "https") is unresponsive. Make sure your web browser is pointing to http://www.wormbase.org (note the "http") instead. Let us know if you have any more trouble.


Best,


Chris Grove

WormBase
