### ISSUE TITLE
Expression widget display

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6140]
Hi Sibyl, 
We had some feedback from users on the expression widget display on the gene page. The suggestions we received were discussed at the caltech meeting. We would like to:

1) Remove the Images column in the table (this is because for some genes the image can be redundant (e.g. eat-4: http://www.wormbase.org/species/c_elegans/gene/WBGene00001135#10--10)

2) Pull the reagents and show them on the widget. This can be achieved in 2 ways:
a) In the supporting evidence column, replace ‘Type: Reporter gene’ with ‘Reagents:list of regents’ e.g.: ‘Reagents: WBPaper00003349Ex1 [eat-4::lacZ]; adIs1230 [eat-4::GFP]’ the list is the same of the one displayed on the Gene expression page in the Details widget, under the Experiment tag (see screenshot)

<img width="1115" alt="screen shot 2018-01-26 at 8 24 27 am" src="https://user-images.githubusercontent.com/901243/35446139-6c05b0a0-0279-11e8-8730-709978c3d2dc.png">

OR

b) Add an extra column (not sure how the relationship to the objects in the supporting evidence column can be maintained). Screenshot below.

<img width="869" alt="screen shot 2018-01-26 at 8 34 32 am" src="https://user-images.githubusercontent.com/901243/35446165-7c0ac26a-0279-11e8-90fa-b6068bc66211.png">

3) Users also thought the description of the pattern should be displayed directly on the expression widget on the gene page, same considerations for display options as for the reagents.

4) Still on the expression widget display on the gene page: Add a disclaimer next to ‘Expression pattern Images’: ‘We display only images for which we were granted permissions from the publisher’ 

Do not hesitate to contact me on Skype if you need more info or if you want to talk about it.

Many thanks

**Comment by sibyl229** [comment]
Hi @draciti could you clarify what counts as a reagent, other than transgene? Thanks

**Comment by draciti** [comment]
Hi Sibyl,  I wonder if you could port the functionality from the 'Experiment' section on the Expression pattern page -> 'Details' widget. Happy to talk if you need more info

**Comment by sibyl229** [comment]
@draciti here is what I have so far for expression widget. Is there anything else? http://staging.wormbase.org/species/c_elegans/gene/WBGene00001135#1--10

**Comment by sibyl229** [comment]
I'm working on porting the 'Experiment' section now. So please feel free to hold off testing until I'm done.

**Comment by draciti** [comment]
sounds good

**Comment by sibyl229** [comment]
Hi @draciti ready now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00001135#1--10

**Comment by draciti** [comment]
thanks Sibyl!
A couple of things:
1) the field Type: Reporter gene can be deleted
2) I cannot check if the antibody field is displayed correctly as probably you are working on staging, and it throws an error. the corresponding live page is
http://www.wormbase.org/species/c_elegans/gene/WBGene00002081#1--10
Expr1467

Same for the other types, e.g. Western, in_situ etc..
thx

**Comment by sibyl229** [comment]
@draciti should be fixed now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00002081#1--10

Does strain count as an reagent? If so, do you have an example?

**Comment by draciti** [comment]
it looks great! thanks Sibyl
While testing I have noticed that objects that have ‘genome editing’ as type do not have anything listed in the Experiment section in the ‘Details’ widget on the gene expression page.

http://staging.wormbase.org/species/all/expr_pattern/Expr12732#013--10

this is because we recently started to curate them.
Could you please list the associated variations. For the example above it will be:
Experiment: Genome editing: WBVar02145397
This should also be reflected on the Expression widget on the gene page.

Strains: yes, we can pull strain as well. here is an example
http://www.wormbase.org/species/all/expr_pattern/Expr143#013--10

Let me know if you have questions
thx

**Comment by sibyl229** [comment]
@draciti thanks! Should be working now:
- showing strain: http://staging.wormbase.org/species/all/expr_pattern/Expr12732#013--10
- adding variation: http://staging.wormbase.org/species/all/expr_pattern/Expr143#013--10

**Comment by draciti** [comment]
it looks great Sibyl, thank you!
I'll wait to close the ticket, I want to share the preview with the users that gave us feedback. Would it be ok for me to give them the staging url or you prefer me to take a screenshot and send it to them?
Thanks again

**Comment by sibyl229** [comment]
Sure @draciti . Sharing staging URL should be fine. Just remember to remind them that staging site is less reliable and less stable and is generally only intended for testing.

**Comment by draciti** [comment]
sounds good. Thanks Sibyl!

**Comment by draciti** [comment]
For the records, this is the message sent to the users that provided feedback:

Dear Jin and Sreekanth,

Thanks again for your valuable feedback on the gene expression display.
We have worked with our web development team to implement the changes we have discussed during our Skype call:

- We have added a disclaimer wrt the images displayed, stating that we display only images for which we were granted permission.

- We have removed images from the table to minimize redundancy.

- We have added reagents info and pattern description in the 'Details' drop down.

You can see the changes on our development site, please note that -since it is the development page- it can be unstable. 

http://staging.wormbase.org/species/c_elegans/gene/WBGene00001135#1--10

Do not hesitate to contact us should you have additional questions.

Many thanks,

Daniela
