### ISSUE TITLE
WormMine not capturing/displaying all genes for allele/variation objects

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6141]
Looking at variations that map to multiple genes for another ticket, I created a spreadsheet ranking each variation by the number of genes that map to it:

https://docs.google.com/spreadsheets/d/18eymesE5jfMFphuYsr7gB4QaAjTtU9L7eM11sJx_Pzo/edit?usp=sharing

I realized by querying for all genes for any given allele, that querying WormMine for any of these alleles only ever shows one gene associated. For example:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.gene.primaryIdentifier Allele.gene.secondaryIdentifier Allele.gene.symbol" longDescription="" sortOrder="Allele.gene.primaryIdentifier asc">
  <constraint path="Allele.primaryIdentifier" op="=" value="WBVar01500117"/>
</query>`

This query should return 4 genes:

Y54G2A.13 (WBGene00021878)
clec-80 (WBGene00043062)
21ur-13160 (WBGene00171446)
Y54G2A.37 (WBGene00023484)

as shown on the WB page for this variation:

http://www.wormbase.org/species/c_elegans/variation/WBVar01500117#01234567--10

but the query only returns one gene:

Y54G2A.13 (WBGene00021878)

Same is true for any other variation mapping to more than one gene that I've looked at. Can we get the total set of genes for an allele associated to the allele in WormMine?

**Comment by nuin** [comment]
@chris-grove How was this in previous versions?

**Comment by chris-grove** [comment]
@nuin 
I don't remember

**Comment by nuin** [comment]
The new mapping for Variation/Allele should have solved this (now reverted), if not we can make arrangements to transform the relationship into one-to-many or many-to-many. I will work on a build and give you plenty of time for testing.

**Comment by chris-grove** [comment]
@nuin 
This issue holds on the current im-dev1 instance. For example, if I look up the variation/allele gk962622:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.gene.primaryIdentifier Allele.gene.secondaryIdentifier Allele.gene.symbol" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.symbol" op="=" value="gk962622"/>
</query>`

I get one gene associated, but this allele has 75 genes associated on WB website:

http://www.wormbase.org/species/c_elegans/variation/WBVar01498288#0258--10

Could be a small build issue, I'm not sure.

**Comment by chris-grove** [comment]
@nuin 
Still an issue on WS263 production, FYI

**Comment by chris-grove** [comment]
@nuin 
This is related to today's help desk inquiry. This is also linked to testing query 7:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.gene.primaryIdentifier Allele.gene.secondaryIdentifier Allele.gene.symbol" longDescription="Query for Genes that are associated with allele gk962622" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.symbol" op="=" value="gk962622"/>
</query>`

**Comment by chris-grove** [comment]
Resolved. Closing.
