### ISSUE TITLE
Hi i could not find Gene ontology terms informatio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6144]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi i could not find Gene ontology terms information for Haemonchus contortus whole genome only one gene info is there can u please share the data of the same if you have.

**Reported by:** vani (vani***************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 63.0.3239.132

**Comment by gw3** [comment]
Go to the Parasite page.
https://parasite.wormbase.org/index.html

Select 'BioMart' (Third item across from the left in the top grey menu bar).

Click on the top left blue 'New' button
Click on '+ SPECIES' and select one of the H. contortus species you require.

On the left, click on the blue link '2. Output Attributes'
Click on '+ GENE' and ensure that the Gene ID is selected.
Click on '+ GENE ONTOLOGY (GO)' and select and select data you wish to 
be displayed like 'GO term accession', 'GO term name', 'GO term definition'

At the top left, click on the blue 'Results' button.

At the top of the page Select the output format you require from the 
'Export all results to' line e.g. 'File' in 'CSV'  format.
Click on 'Go'

A file will be downloaded to your computer.


Gary Williams
Helpdesk
