### ISSUE TITLE
  How do I access the parent sequence f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6145]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I access the parent sequence for UNC-13? When I go to access it, it reads, "CHROMOSOME_I" in grey letters. The letters being grey make it so that I cant click the link to navigate to the sequence.</p><p>What were you doing? <br />&nbsp;&nbsp;I was trying to access UNC-13s parent sequence so that way I could find a specific sequence of DNA to clone. (This is my first time using this site.)</p>

**Reported by:** bcl1*************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by gw3** [comment]
Go to the Gene page for unc-13 :
http://www.wormbase.org/species/c_elegans/gene/WBGene00006752#-09g-10

In the 'Page Content' menu on the left, click on the 'Location' option.

Scroll down to the second diagram of the gene structure - this is 
labelled 'GBrowse image:'
Click on the image.

A page displaying the GBrowse genome browser will appear.
There are two scales at the top showing the location on the genome.
Look at the second scale down.
For 'unc-13' this acale should be displaying values from about 7350k to 
7540k

Right mouse button click and drag along this scale to highlight a region 
that you wish to get the sequence for.
When you release the right mouse button a small menu of options will appear.
Select 'Dump selection as FASTA'
The sequence will appear on your screen and you can download it from there.

Gary Williams
Helpdesk
