### ISSUE TITLE
  I got your new species nemotode. Do I...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6146]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I got your new species nemotode. Do I get a reward for just curious?</p>

**Reported by:** Keit*********** (Keit***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1

**Comment by gw3** [comment]
Keith,

If you are referring to the reward for finding a new sister species of 
C. elegans, this prize was claimed several years ago.

Gary Williams
Helpdesk
