### ISSUE TITLE
Ontology browser 500 error

### ISSUE THREAD

**Issue by a8wright** [WormBase/website#6147]
This error I came across today. I checked to see if it was caused by d2c and it is getting produced correctly from that perspective.

http://www.wormbase.org/species/all/anatomy_term/WBbt0007833#310--10

**Comment by chris-grove** [comment]
@a8wright 
FWIW, this object "WBbt0007833" is a bogus anatomy_term object and should be deleted from ACEDB. I can't tell where it's coming from at the moment.

**Comment by gw3** [comment]
"WBbt0007833" is referenced in a few Condition objects coming from Hinxton.
This will be corrected.

**Comment by chris-grove** [comment]
Thanks @gw3 !
