### ISSUE TITLE
  Could you please teach me how to find...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6148]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Could you please teach me how to find a list of all collagens in C. elegans?Thanks a lot.</p>

**Reported by:** Ying***** (ying**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7

**Comment by gw3** [comment]
Go to WormBase:
http://www.wormbase.org

In the box at the top right,  click on 'for a gene' and select 'Gene Class'
then type in 'col' in the search field just in front of this and press 
the Return key.

This will display a list of species which have collagen genes 
identified, together with a count of the number of genes.

Click on 'Caenorhabditis elegans (164 members)' and the list of all the 
C.elegans 'col' genes will be displayed.


Gary Williams
Helpdesk

**Comment by gw3** [comment]
Hi,
But this list missed other collagens such as dpy-10, how do I capture all collagens including those not named as col’s?
Appreciate for your kind help.
Best
Ying

> 在 2018年1月30日，上午8:01，Gary Williams <gw3@ebi.ac.uk> 写道：
> 
> Go to WormBase:
> http://www.wormbase.org <http://www.wormbase.org/>
> 
> In the box at the top right,  click on 'for a gene' and select 'Gene Class'
> then type in 'col' in the search field just in front of this and press the Return key.
> 
> This will display a list of species which have collagen genes identified, together with a count of the number of genes.
> 
> Click on 'Caenorhabditis elegans (164 members)' and the list of all the C.elegans 'col' genes will be displayed.
> 
> 
> Gary Williams
> Helpdesk
> 
>

**Comment by gw3** [comment]
This query seems more complete (191 total, 172 Ce genes).

http://www.wormbase.org/species/all/go_term/GO:0005581#02--10

raymond
