### ISSUE TITLE
How can I convert gene name to Gene id in bulk...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6154]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I convert gene name to Gene id in bulk

**Reported by:** Mali******** (mail******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 63.0.3239.132

**Comment by chris-grove** [comment]
Hello Malini,


The easiest way to do this is using the SimpleMine tool, available under the Tools menu on any WormBase page:


http://www.wormbase.org/tools/mine/simplemine.cgi


You can paste in your list of gene names or IDs and get back a table of info, including names and IDs, for each gene in your list.


Let us know if you need anything else.


Best,


Chris Grove

WormBase
