### ISSUE TITLE
Help with WormMine and Custom Queries

### ISSUE THREAD

**Issue by gw3** [WormBase/website#6157]
Help requested on:
Worm Community Forum » General Forum » General Scientific Discussion Area 
http://forums.wormbase.org/index.php?topic=3043.msg7604;topicseen#msg7604

Help with WormMine and Custom Queries
« on: February 01, 2018, 10:21 PM »
Hello all - I am hoping to use Wormmine on a list of genes I have to quickly identify those that have any alleles or mutations (Classical or change of function). I read the user guide and cannot really understand how to constraint to the list (i.e. I am unable to find the list constraint for the lists I have created). 

Help is appreciated !

**Comment by chris-grove** [comment]
User:
"Hi - I actually figured out how to constrain to a list of genes. Need help trying to figure out how to locate all genes within the list that have either a classical allele or a reference allele."

**Comment by chris-grove** [comment]
My first reply:
"Hello,


 You can constrain your query to a list of genes in the gene constrain dialog box. Click on the checkbox underneath the main constraint entry box, to the right of "OR" and left of "Contained in list:" and then select you gene list from the available lists of genes provided in the drop down menu. WormMine doesn't have the allele attributes that distinguish alleles as "classical" or "change of function", but we can apply other filters such as omitting any Million Mutation Project alleles or those identified by whole genome sequencing (WGS). Here's a screen recording video showing how this can all be done:


https://www.dropbox.com/s/uqbmhr0trbml3vb/Querying_for_genes_from_a_list_with_alleles_in_WormMine_Feb_2_2018.mov?dl=0


Please let me know if you have any trouble or have any questions.


Chris"

**Comment by chris-grove** [comment]
My second reply:
"""You can import the following query to see how to constrain to genes that have a reference allele:


`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.referenceAllele.primaryIdentifier Gene.referenceAllele.symbol Gene.referenceAllele.otherName" longDescription="" sortOrder="Gene.primaryIdentifier asc"> <constraint path="Gene.referenceAllele" op="IS NOT NULL"/> </query>`


"Reference Allele" is actually a separate attribute of genes in WormMine and can be constrained to "have a value". As I mentioned in my earlier post, WormMine does not classify alleles as "classical" so you'll have to filter by one of the other attributes available."""
