### ISSUE TITLE
Variations with no public name, only paper references, not clear what they represent

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6160]
I came across several variations in WormMine that have no public name and apparently have no information in them other than paper references. Here are three examples:

WBVar00000072
http://www.wormbase.org/species/all/variation/WBVar00000072#012345678--10

WBVar00000050
http://www.wormbase.org/species/all/variation/WBVar00000050#801234567--10

WBVar00090448
http://www.wormbase.org/species/all/variation/WBVar00090448#801234567--10

As for Caltech: do we know what variations these are in the papers that are referenced? They have no public name, just a WBVar ID and no other information than papers, so it's impossible to know what they correspond to in the paper, if anything, as far as I can tell.

As for Hinxton: Do we have any history on these variations that suggest where they came from? Any information lingering somewhere about these?

As for the webteam: Each of these variation pages are throwing errors in the Locations widget:

<img width="607" alt="screenshot 2018-02-03 10 10 19" src="https://user-images.githubusercontent.com/611382/35768483-7ac11628-08ca-11e8-9c63-91651690aa36.png">

I don't know if the errors can be suppressed. Perhaps these variations need to be deleted from the database.

**Comment by WenChenWormBase** [comment]
Chris, all three variations were created before 2005 as XREF from meeting abstracts. They were probably alleles that were merged to other objects later, but the XREFs from paper class were not taken care of. I think we should go through the whole CitaceMinus to look for these objects, and link these Paper objects to the correct Variation. Is there a place storing the information on how the alleles objects were merged?

**Comment by chris-grove** [comment]
@WenChenWormBase 

OK, sounds good. I can't see any additional info associated with these variation objects in the Tree Display or on ACEDB. Here are the ACEDB images of the objects with timestamps:

<img width="521" alt="screenshot 2018-02-03 16 16 22" src="https://user-images.githubusercontent.com/611382/35771669-bfbdcc9c-08fe-11e8-845b-5df743e315cf.png">

<img width="522" alt="screenshot 2018-02-03 16 16 41" src="https://user-images.githubusercontent.com/611382/35771670-c2d5a30a-08fe-11e8-857b-34fd0074410a.png">

<img width="528" alt="screenshot 2018-02-03 16 17 05" src="https://user-images.githubusercontent.com/611382/35771671-c6585b62-08fe-11e8-8085-5df72cc6c335.png">

**Comment by sibyl229** [comment]
Hi @chris-grove , the errors in location widget on variation page should be fixed now:
http://staging.wormbase.org/species/all/variation/WBVar00000072#012345678--10
http://staging.wormbase.org/species/all/variation/WBVar00000050#012345678--10
http://staging.wormbase.org/species/all/variation/WBVar00090448#012345678--10

**Comment by chris-grove** [comment]
@sibyl229 
Great! Thanks! Looks good. I'll assign the ticket to myself to take care of the rest.

**Comment by Paul-Davis** [comment]
@chris-grove hmm it could be that we could trace a human readable name for them, but I guess it would be difficult to be 100% sure......I'll take a look.

**Comment by chris-grove** [comment]
@Paul-Davis 
OK, thanks. I'm going to look into it more as well.

**Comment by chris-grove** [comment]
I suspect that WBVar00000072 is an extraneous WBVar object for allele ad820 (WBVar00000071):

http://www.wormbase.org/species/c_elegans/variation/WBVar00000071#012345678--10

I would suggest adding papers:

WBPaper00018319
WBPaper00022005

to ad820 and deleting WBVar00000072 from the database.

**Comment by chris-grove** [comment]
I suspect WBVar00000050 is an extraneous WBVar object for allele ad695 (WBVar00000049):

http://www.wormbase.org/species/c_elegans/variation/WBVar00000049#01234567a--10

I would suggest adding paper:

WBPaper00020978

to ad695 and deleting WBVar00000049 from the database.

**Comment by chris-grove** [comment]
I suspect WBVar00090448 is an extraneous WBVar object for allele n2368 (WBVar00090446):

http://www.wormbase.org/species/c_elegans/variation/WBVar00090446#01234567a--10

I would suggest adding paper:

WBPaper00025822

to n2368 and deleting WBVar00090448 from the database.

**Comment by Paul-Davis** [comment]
Seems you are right @chris-grove going back through the database it seems that all name data was transferred to the WBVars you suggested but the WBVBars were not killed by the curator who resolved the name issues <Allele_name>sd

I have moved the References and killed them in the DB.

**Comment by chris-grove** [comment]
Great! Thanks @Paul-Davis
