### ISSUE TITLE
Laboratory strain widget thowing d2c error in log

### ISSUE THREAD

**Issue by a8wright** [WormBase/website#6162]
ERROR (from log): "Reflection warning, NO_SOURCE_PATH:12:27 - call to method startsWith can't be resolved (target class is unknown)."

see src/rest_api/classes/laboratory/widgets/strains.clj line 12

I think you might want to use the Clojure function str/starts-with? or include the Java dependency. If possible you should probably use the Clojure function.

**Comment by azurebrd** [comment]
Thanks @a8wright for catching this, and the fix recommendation
