### ISSUE TITLE
 Server Error: 500 at  rest/widget/rearrangement/n...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6163]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/rearrangement/nT1[unc-%3F(n754dm)%20let-%3F]/overview">rest/widget/rearrangement/nT1[unc-%3F(n754dm)%20let-%3F]/overview</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "http://datomic-to-catalyst-ws262.us-east-1.elasticbeanstalk.com/rest/widget/rearrangement/nT1[unc-?(n754dm) let-?]/overview failed with 400 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 919." </p><p>What were you doing? <br />&nbsp;&nbsp;Clicking on the link nT1[unc-?(n754dm) let-?] under rearrangements from the strain page for GC463</p>

**Reported by:** Jaro********* (jaro*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by chris-grove** [comment]
Confirmed:

![screen shot 2018-02-05 at 9 11 01 am](https://user-images.githubusercontent.com/611382/35808666-8aa04254-0a54-11e8-8902-a28691e25a1f.png)

**Comment by sibyl229** [comment]
Hi @chris-grove the error on rearrangement page should be fixed now: http://staging.wormbase.org/species/all/rearrangement/nT1[unc-%3F(n754dm)%20let-%3F]#0--10

**Comment by chris-grove** [comment]
@sibyl229 
Looks great! Thanks!
