### ISSUE TITLE
WormMine: im-dev1 testing Feb 5, 2018: Most genes not connected to a CDS

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6165]
There are 47,253 C. elegans genes and 28,167 C. elegans CDS's, but only 47 C. elegans genes have a CDS:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.organism.name" code="A" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.CDSs" code="B" op="IS NOT NULL"/>
</query>`

They are not getting connected but should be.

**Comment by nuin** [comment]
CDS `XPATH` in the gene mapping file needs to have the `CDS:` prepended to the element being extracted from the XML. It was something that was lost in the code reversion from 262 production to 262/263 development. I added the change and I am running a new build.

**Comment by nuin** [comment]
I need to do some more digging on this one as the `Gene-CDS` relationship is a one-to-many relationship and by just concatenating the `CDS:` label to the item coming from the XML generates an error. This might require some manipulation of the Gene.xml itself. I am checking the legacy code.

**Comment by nuin** [comment]
It seems that this is related to the small build. We can close the issue and re-open if it appears in the full build.

**Comment by chris-grove** [comment]
@nuin I'd rather just leave it open until we know the full build does not have the problem

**Comment by chris-grove** [comment]
Fixed on production. Closing.
