### ISSUE TITLE
WormMine: im-dev1 testing Feb 5, 2018: CDS sequences are incomplete

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6166]
It appears that all of the CDS sequences only represent the sequence of the single exon with the highest chromosomal coordinate number (3' most exon for genes on the +1 strand, 5' most exon for genes on the -1 strand), not the entire CDS. Each CDS sequence should start with "ATG..." and end with either "...TAG", "...TGA", or "...TAA". It seems like the sequence of the CDS is being (attempted to be) calculated from the CDS coordinates, but these should all be accessible from the CDS_transcripts FASTA file:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS262/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS262.CDS_transcripts.fa.gz

**Comment by chris-grove** [comment]
Presumably as a result of this, the CDS lengths reported are not correct (only correspond to the length of the sequence stored, i.e. the single exon)

**Comment by nuin** [comment]
`CDS` loading in WormMine is not ideal, due to the fact that we don't have a proper loader. I will wait for the new InterMine's model to do any code changes, including loading information from `CDS` FASTA.

**Comment by chris-grove** [comment]
@nuin can we remove length and sequence from CDS objects until this gets sorted out?

**Comment by nuin** [comment]
AS lons as it is in the `CDS` line in the GFF it will be loaded. Only possible immediate change would be to create one line per `CDS` with the main start and end position.

**Comment by chris-grove** [comment]
We can't remove length and sequence from the CDS object model in WormMine?

**Comment by nuin** [comment]
The lines in the GFF are consumed by the loader. If we don't change the loader it will consume whatever is in the line. A new loader will solve this, any other loader that I see in the InterMine consumes the entire line, the CDS in the GFF have a different structure.

**Comment by chris-grove** [comment]
This seems to be resolved as of WS273. Closing.
