### ISSUE TITLE
  note the two periods at the end of th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6169]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;note the two periods at the end of these references, so likely a bug:<br/>(thanks, PWS)<br/>Lehner, B., Crombie, C., Tischler, J., Fortunato, A., & Fraser, A. G. (2006). Systematic mapping of genetic interactions in Caenorhabditis elegans identifies common modifiers of diverse signaling pathways.. <br/>Zhong, W., & Sternberg, P. W. (2006). Genome-wide prediction of C. elegans genetic interactions.. Science, 311, 1481-4. doi:10.1126/science.1123287</p>

**Reported by:** Paul********** (worm****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by sibyl229** [comment]
Hi Paul, the extra period in the paper title is removed now:
http://staging.wormbase.org/resources/paper/WBPaper00027756#0--10
