### ISSUE TITLE
WormMine: im-dev1 testing Feb 7, 2018: Unmerged Transcript objects

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6170]
Several Transcript objects do not have WormMine IDs of the form "Transcript:*". Querying for all transcripts that contain one of these transcript names, e.g. "B0207.4" in either the WormMine ID or the Sequence Name:

`<query name="" model="genomic" view="Transcript.primaryIdentifier Transcript.symbol" longDescription="" sortOrder="Transcript.primaryIdentifier asc" constraintLogic="A or B">
  <constraint path="Transcript.primaryIdentifier" code="A" op="CONTAINS" value="B0207.4"/>
  <constraint path="Transcript.symbol" code="B" op="CONTAINS" value="B0207.4"/>
</query>`

Shows that there are 3 unmerged transcript objects with this identifier:

![screen shot 2018-02-07 at 9 37 23 am](https://user-images.githubusercontent.com/611382/35922155-d61eae2c-0bea-11e8-95db-04ea4eda928f.png)

**Comment by chris-grove** [comment]
...one of which has WormMine ID of the form "Transcript:Transcript:*"

**Comment by chris-grove** [comment]
490 transcript objects don't have WormMine ID like "Transcript:*":

`<query name="" model="genomic" view="Transcript.primaryIdentifier Transcript.symbol" longDescription="" sortOrder="Transcript.primaryIdentifier asc">
  <constraint path="Transcript.primaryIdentifier" op="NOT LIKE" value="Transcript:*"/>
</query>`

333 of these have WormMine ID of the form "CDS:*". These appear to be coming from transposon genes:

`<query name="" model="genomic" view="Transcript.primaryIdentifier Transcript.symbol" longDescription="" sortOrder="Transcript.primaryIdentifier asc">
  <constraint path="Transcript.primaryIdentifier" op="LIKE" value="CDS:*"/>
</query>`

The 157 remaining transcript objects appear to all be unmerged transcript objects:

`<query name="" model="genomic" view="Transcript.primaryIdentifier Transcript.symbol" longDescription="" sortOrder="Transcript.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Transcript.primaryIdentifier" code="A" op="NOT LIKE" value="CDS:*"/>
  <constraint path="Transcript.primaryIdentifier" code="B" op="NOT LIKE" value="Transcript:*"/>
</query>`

If I try to upload the IDs for these as a list, I get a disambiguation page that asks me to indicate which of two unmerged transcript objects I am referring to:

![screen shot 2018-02-07 at 9 48 52 am](https://user-images.githubusercontent.com/611382/35922667-22895f40-0bec-11e8-8c09-031b675178df.png)

**Comment by nuin** [comment]
The IDs lacking transcript are due to CDS loading, pre-processing failed. I rechecked the XML and should be fine on the next test.

The ones with duplicate labels are from Gene.xml. It seems that the pre-processing script was run twice on the same file. I remove the duplicates and start a new test.

**Comment by nuin** [comment]
<img width="1645" alt="screen shot 2018-02-07 at 1 53 00 pm" src="https://user-images.githubusercontent.com/6273/35941032-3e0b495a-0c0e-11e8-87d4-3fad68e91bc6.png">


Seems fine with the recent changes.
