### ISSUE TITLE
WormMine: im-dev1 testing Feb 7, 2018: Many C. elegans proteins with heterogeneous IDs

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6171]
There are 114 C. elegans proteins with IDs and a name that I would consider correct, for example:

Protein Primary Accession: WP:CE01059
Protein WormBase ID: WP:CE01059
Protein Name: PELO-1

`<query name="" model="genomic" view="Protein.primaryAccession Protein.primaryIdentifier Protein.symbol" longDescription="" sortOrder="Protein.primaryAccession asc" constraintLogic="A and B and C">
  <constraint path="Protein.primaryAccession" code="A" op="LIKE" value="WP:CE*"/>
  <constraint path="Protein.primaryIdentifier" code="B" op="LIKE" value="WP:CE*"/>
  <constraint path="Protein.organism.name" code="C" op="=" value="Caenorhabditis elegans"/>
</query>`

The remaining 27,942 proteins have what I would consider incorrect ID formatting, for example:

Protein Primary Accession: Null
Protein WormBase ID: 2L52.1a
Protein Name: Null

`<query name="" model="genomic" view="Protein.primaryAccession Protein.primaryIdentifier Protein.symbol" longDescription="" sortOrder="Protein.primaryAccession asc" constraintLogic="A and C">
  <constraint path="Protein.organism.name" code="C" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Protein.primaryAccession" code="A" op="IS NULL"/>
</query>`

And, in fact, this really represents a merging problem as the first protein listed above, "WP:CE01059"/"PELO-1" actually has the CDS name "R74.6":

http://www.wormbase.org/species/c_elegans/protein/WP:CE01059#09--10

and is then represented twice in the WormMine data set:

`<query name="" model="genomic" view="Protein.primaryAccession Protein.primaryIdentifier Protein.symbol" longDescription="" sortOrder="Protein.primaryAccession asc" constraintLogic="C and (A or B)">
  <constraint path="Protein.organism.name" code="C" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Protein.primaryIdentifier" code="A" op="=" value="R74.6"/>
  <constraint path="Protein.primaryAccession" code="B" op="=" value="WP:CE01059"/>
</query>`

![screen shot 2018-02-07 at 10 08 25 am](https://user-images.githubusercontent.com/611382/35923665-e0fd3f9e-0bee-11e8-8f23-5d94515f75e9.png)

**Comment by chris-grove** [comment]
The line for this example protein in the protein FASTA file is:

`>R74.6 wormpep=CE01059 gene=WBGene00011280 locus=pelo-1 status=Confirmed uniprot=P50444 insdc=CAA85277.1 product="Protein pelota homolog"`

It should be possible to use this information to properly merge the objects.

"R74.6" is the name of the CDS that generates the protein

"wormpep=CE01059" indicates that the protein ID is "WP:CE01059"

"gene=WBGene00011280" indicates that the associated gene ID is "WBGene00011280"

"locus=pelo-1" indicates that the associated gene name is "pelo-1"

Looking up the CDS and gene for each of the proteins in the query above yields:

`<query name="" model="genomic" view="Protein.primaryAccession Protein.primaryIdentifier Protein.symbol Protein.CDSs.primaryIdentifier Protein.CDSs.symbol Protein.CDSs.gene.primaryIdentifier Protein.CDSs.gene.secondaryIdentifier Protein.CDSs.gene.symbol" longDescription="" sortOrder="Protein.primaryAccession asc" constraintLogic="C and (A or B)">
  <constraint path="Protein.organism.name" code="C" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Protein.primaryIdentifier" code="A" op="=" value="R74.6"/>
  <constraint path="Protein.primaryAccession" code="B" op="=" value="WP:CE01059"/>
</query>`

With the resulting table looking like:

![screen shot 2018-02-07 at 10 14 58 am](https://user-images.githubusercontent.com/611382/35924007-d26ec816-0bef-11e8-8907-883f3fd07ea5.png)

which I think highlights the nature of the problem.

**Comment by chris-grove** [comment]
Sorry, I should restate: Those last results show that the protein object in WormMine that has Primary Accession and WormMine ID as "WP:CE01059", has two unmerged CDS objects that it is pointing to.

If I open up the query to outer joins to include protein objects that do not have an associated CDS or gene:

`<query name="" model="genomic" view="Protein.primaryAccession Protein.primaryIdentifier Protein.symbol Protein.CDSs.primaryIdentifier Protein.CDSs.symbol Protein.CDSs.gene.primaryIdentifier Protein.CDSs.gene.secondaryIdentifier Protein.CDSs.gene.symbol" longDescription="" sortOrder="Protein.primaryAccession asc" constraintLogic="C and (A or B)">
  <join path="Protein.CDSs" style="OUTER"/>
  <join path="Protein.CDSs.gene" style="OUTER"/>
  <constraint path="Protein.organism.name" code="C" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Protein.primaryIdentifier" code="A" op="=" value="R74.6"/>
  <constraint path="Protein.primaryAccession" code="B" op="=" value="WP:CE01059"/>
</query>`

we can see that the protein that only has WormMine ID of "R74.6" has no corresponding CDS, and hence no associated gene:

![screen shot 2018-02-07 at 10 19 23 am](https://user-images.githubusercontent.com/611382/35924208-683148ba-0bf0-11e8-95fb-b4f2eb8cbb85.png)

**Comment by nuin** [comment]
Hi

A couple of things first @chris-grove:

- I don't know if these are one issue or multiple. I appreciate the thoroughness, but I don't know if I should try the top query, the middle one or the bottom, or if they are related or not.

- The initial post `There are 114 C. elegans proteins with IDs and a name that I would consider correct, for example:`, have you considered that this is because `im-dev1` is a small build? Have you tried the same query on production? On production I get 27000+ proteins with `WP` names

- The FASTA file is loaded as the GFF files and ATM we do a pre-processing removing most things but the protein ID from the header. We will need a new FASTA loader that would take in account the items in the header, and I currently am trying to focus on the GFF loader

**Comment by chris-grove** [comment]
@nuin 

1) I don't know if these are one issue or multiple either. I suspect it may all have one root cause but I can't be sure. I don't understand the question about which query to try; why can't you try all of them? I'm trying to describe a broader phenomenon that probably cannot be adequately described with a single example query.

2) "... have you considered that this is because im-dev1 is a small build?" Yes, of course I've considered that this may be due to the small build. However, I cannot be sure if it is or not and that's why I'm bringing it to your attention. Sure, on production you get all the C. elegans proteins with WP names, but I'm testing im-dev1, not production, so I don't know if any changes I'm seeing on im-dev1 are due to changes that were made for testing, because of the small build, or something else.

3) OK, maybe we need the new FASTA loader, or maybe the problem won't exist in the full build. I guess my point with mentioning the FASTA header is that taking advantage of the full header info may help us avoid merging errors in the future.

**Comment by chris-grove** [comment]
Fixed on production (I think with the recent fix to the "CDS -> Gene and Protein" and "Species -> Protein Sequences" template queries (protein merging issue) Issue #6252 ). Closing.
