### ISSUE TITLE
My preferred page format seems to have mysteriousl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6173]
*Help Desk query collected when no chat operators were online. Follow up required.*

My preferred page format seems to have mysteriously vanished. What's the easiest way to restore that?

**Reported by:** Curt******* (cloe**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#017-3-6">http://www.wormbase.org/#017-3-6</a>
**Browser:** Chrome 49.0.2623.112

**Comment by sibyl229** [comment]
I answered the user. Here is a copy of the email.
>Sorry about the problem. I think the easier way might be to save a new layout. First, you can turn on and off individual widgets from the left sidebar. Once you are happy with how the page looks, click on the “gear” icon above the left sidebar, which will show a panel with the option to save a new layout (please refer to the screenshot attached). You can also switch between different layouts from the same panel.
Please feel free to let me know if there is any other issue. 
Thank you for writing to us,
![screen shot 2018-02-07 at 3 36 56 pm](https://user-images.githubusercontent.com/1753893/36106517-981f87fa-0fe5-11e8-90dc-25fce678c766.png)
