### ISSUE TITLE
WormMine: im-dev1 testing Feb 8, 2018: 4 Genes with ID without prefix "WBGene"

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6175]
I had brought this up before on Slack, but hadn't made a GitHub ticket for it.

This can be seen with this query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.organism.name" code="A" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.primaryIdentifier" code="B" op="NOT LIKE" value="WBGene*"/>
</query>`

This results in 4 gene objects with the following IDs:

T01D1.2l
Y111B2A.14c
Y49C4A.7
Y53G8AL.4b

which are all CDS identifiers.

**Comment by nuin** [comment]
These are all from Panther and will be removed on a full build, either on the Panther file or on the database.
