### ISSUE TITLE
WormMine: im-dev1 testing Feb 8, 2018: Many transcript classes missing Gene attribute

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6177]
I found that several transcript classes lack a Gene attribute:

lincRNA
piRNA
rRNA
scRNA
snRNA
snoRNA
tRNA
Antisense RNA
Pseudogenic rRNA
Pseudogenic tRNA
Pseudogenic Transcript

I would suspect that most users that want to use these classes would want to be able to pull out the genes that they are associated with. For comparison, the following classes do have a Gene attribute:

mRNA
miRNA
ncRNA

**Comment by nuin** [comment]
Is there an example on a query or model browsing?

**Comment by chris-grove** [comment]
Yes, if you open QueryBuilder for any of those classes you will see there is no Gene attribute

**Comment by chris-grove** [comment]
![screen shot 2018-02-08 at 11 58 59 am](https://user-images.githubusercontent.com/611382/35986627-8e9ccd1c-0cc7-11e8-9de9-8c484f13e137.png)
 
![screen shot 2018-02-08 at 11 59 29 am](https://user-images.githubusercontent.com/611382/35986634-91c9a294-0cc7-11e8-90c9-ea8ce877f741.png)

... but maybe I misunderstood your question.

**Comment by nuin** [comment]
I think this would only be solved with with a proper GFF loader, as there's not enough information to link both. But to give a fair assessment I need to investigate further.

**Comment by chris-grove** [comment]
OK, this has been mostly fixed. The only classes (of transcript types) that do not now have a "Gene" attribute are the Pseudogenic transcripts. These are lower priority, IMO, and can be overlooked for now. Closing
