### ISSUE TITLE
  Hi Wormbase,  Can you tell me what yo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6178]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi Wormbase, <br/>Can you tell me what you use (data, analysis) to generate the "hmmpanther" diagrams you display on the Protein pages, and how to decode them (define green diamonds)? I've tried searching for hmmpanther and other PANTHER tools, but haven't found that readout.<br/>Thanks!</p>

**Reported by:** Aile** (asew****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by epaule** [comment]
I do not know exactly how the diagrams are being drawn from the data, but they are not limited to panther data, but rather show all domains from the protein as identified by interpro. If I would have a guess, I would think that the sticks are PFAM active sites.
But someone from our web team might know more and contact you.

**Comment by epaule** [comment]
If you look in the Motif Details widget, you can see that these are Phosphorylation sites from PhosphoPep

**Comment by sibyl229** [comment]
>Thanks for writing to us. The domain diagram contains exactly the same information as the table in Motif Details widget. To answer your question about how the diagram is dawn: the colour is to visually differentiate between motifs based on their identifiers, and the lollipop shape is to indicate motifs of length 1. For example, on the CNP-2 page, PhosphoPep:Y46G5A.10 is assigned the colour green, and it has a length of 1, hence the lollipop symbol. One thing to note is that, due to the limited number of colours, it’s possible for different motif identifiers to sometimes have the same colour, and that the same motif identifier might get a different colour on a different protein page. 

>The domain diagram was made a long time ago, and it really could be better. If you have any suggestions about what you’d like to see in these diagrams, please feel free to let me know.
