### ISSUE TITLE
WormMine: im-dev1 testing Feb 12, 2018: Should remove "Affects" attribute from Allele class in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6180]
There are a couple of issues with the "Affects" attribute in the Allele class which suggest to me it should be removed or replaced:

1) The "Affects" tag in the ACEDB data model is actually a supertag that refers to multiple subtags:

http://www.wormbase.org/tools/schema/run?class=Variation&view=expand

The subtags include "Gene", "Predicted_CDS", "Transcript", "Pseudogene", "Feature" and "Interactor". If I query for all alleles and their "Affects" attribute in im-dev1 WormMine, I apparently (and as I might expect from the ACEDB data model) get a mix of object types, including genes:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.affects" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.affects" op="LIKE" value="WBGene*"/>
</query>`

and non-gene objects, presumably CDS objects:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.affects" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.affects" op="NOT LIKE" value="WBGene*"/>
</query>`

Ideally this tag would refer to one type of object.

2) (Probably related to #6141) The "Affects" tag is only ever populated by one entity. If I query for all "Affects" entries for the allele gk962622:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.affects" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.symbol" op="=" value="gk962622"/>
</query>`

I only get one result "F55D12.3", but this variation affects 75 genes, 71 CDS's and 101 transcripts.

3) The "Affects" entry is almost always redundant with the "Gene" entry:

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.affects Allele.gene.primaryIdentifier" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.affects" op="LIKE" value="WBGene*"/>
</query>`

Some of the data population issues may be due to a small build, but regardless I think the "Affects" attribute as it is will lead to more confusion than clarity because of the complex nature of the attribute and its entries. I would recommend removing the "Affects" attribute and possibly make CDS and Transcript object/class connections in the future.

**Comment by nuin** [comment]
`Affects` removed

**Comment by chris-grove** [comment]
Thanks!
