### ISSUE TITLE
WormMine: im-dev1 testing Feb 12, 2018: Should remove "Sequence Details" attribute from Allele class

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6181]
The "Sequence Details" attribute of the Allele class is too loaded and likely difficult for users to interpret. The Sequence_details tag in the ACEDB model is a supertag with several subtags (some with their own subtags) carrying lots of heterogeneous data. Here are some examples of data in WormMine:

Pending_curation

Y55F3AM              Substitution              Pending_curation

F31E8                            tttctatttttctctcaactttttcatatc        ttttatcaagaattttacaaaaaaaaattc                    F31E8                      cctttttacgagaatttcagtgcctgaatgggcgttcgtatttcttggattcgtatttattctgctggttctcgcgtgtgcattctgtctcattcggaagttatttggaaaaaagcggcatggtgagaagaacaaaaagggtggattgaaaggattctttggtaaaggacaggatgtcgttgatggaaaaaatattcaaggggtatgtttttgaaatgaaaaataatgatgaaaaacaaggaaggaaatataataagttacggaataccgtattcgagcgactttgcgaaaccaaacatgtaaacttggttatgataatctagagctcccatgtatgcatggaggtgcaagagtataataggcacgtaggtaggcaggcaattttttgcaagtgactccaggcatgcaaatgtcttatttctggatttcttccttggatttcttggtattgttctaatttttagtttttgattcttaggaaaaactttgctgaa                    Sequenced

Y51H1A                            tcaatttttttttttttttttcaat        aattttttgaaaaaagtgcaaaatt                    Y51H1A                      A          G                            Sequenced

If we include data from this branch of the object we should use specific subtags of Sequence_details and show those data specifically.

**Comment by nuin** [comment]
`Sequence Details` removed.

**Comment by chris-grove** [comment]
@nuin 
Great! Thanks!
