### ISSUE TITLE
WormMine: im-dev1 testing Feb 12, 2018: Request change of Allele attribute listing order

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6182]
Currently the Allele attributes listed in the Model Browser of the QueryBuilder shows the attributes in the following order:

Affects
Amber _ UAG
KO Consortium Allele
Linked To
Missense
Missense Change
Mutagen
NBP Allele
Nema GENETAG Consortium Allele
Ochre _ UAA
Opal _ UGA
Other Name
WormBase ID
Production Method
Sequence Details
Sequence Status
Species
Status
Public Name
Type
Type Of Mutation 

I think this order is not intuitive and makes it challenging to find what you're looking for. As already expressed in other tickets (#6180 and #6181) I think the "Affects" and "Sequence Details" attributes should be removed until we find a better way of handling the associated data. As for the remaining attributes, I think they should be displayed in the following order:

WormBase ID
Public Name
Other Name
Linked To
Status
Sequence Status
Species
Production Method
Mutagen
Type
Type Of Mutation
Missense
Missense Change
Amber_UAG
Ochre_UAA
Opal_UGA
KO Consortium Allele
NBP Allele
Nema GENETAG Consortium Allele

**Comment by nuin** [comment]
I don’t think there’s a way to change the order of items in the browser. It’s usually alphabetical.

**Comment by chris-grove** [comment]
@nuin 
Usually alphabetical, except when it isn't. The gene, protein, CDS, Transcript and Sequence Feature classes have the following attribute order:

Gene:
Brief Description
Description
Last Updated
Length (nt)
Operon
WormBase Gene ID
Sequence Name
Gene Name


Protein:
Length
MD5 Checksum
Molecular Weight (kDa)
Primary Accession
WormBase ID
Name


CDS:
Length (nt)
WormMine ID
Sequence Name


Transcript:
Length (nt)
Method
WormMine ID
Sequence Name


Sequence Feature:
Last Updated
Length (nt) 
WormBase ID
Sequence Name
Name


Also, the current Allele attribute list is not in alphabetical order. If these were all consistently in alphabetical order that may make it easier to find attributes. Sometimes it seems that the name and ID attributes are clustered together, but not always. It seems that there must be some parameter that sets the attribute order somewhere.

**Comment by nuin** [comment]
This is the `Allele` class "creator"

```
        <class name="Allele" is-interface="true">
          <attribute name="naturalVariant" type="java.lang.String" />
          <attribute name="method" type="java.lang.String" />
          <attribute name="type" type="java.lang.String" />
          <attribute name="publicName" type="java.lang.String" />
          <attribute name="otherName" type="java.lang.String" />
          <attribute name="KOAllele" type="java.lang.String" />
          <attribute name="NBPAllele" type="java.lang.String" />
          <attribute name="nemaAllele" type="java.lang.String" />
          <attribute name="amber_UAG" type="java.lang.String" />
          <attribute name="ochre_UAA" type="java.lang.String" />
          <attribute name="opal_UGA" type="java.lang.String" />
          <attribute name="donorSpliceSite" type="java.lang.String" />
          <attribute name="acceptorSpliceSite" type="java.lang.String" />
          <attribute name="productionMethod" type="java.lang.String" />
          <attribute name="sequenceDetails" type="java.lang.String" />
          <attribute name="status" type="java.lang.String" />
          <attribute name="affects" type="java.lang.String" />
          <attribute name="NemaGENETAGConsortiumAllele" type="java.lang.String" />
<!--      <attribute name="missense" type="java.lang.String" /> -->
          <attribute name="detectionMethod" type="java.lang.String" />
          <attribute name="positiveClone" type="java.lang.String" />
          <attribute name="typeOfMutation" type="java.lang.String" />
          <attribute name="sequenceStatus" type="java.lang.String" />
          <attribute name="KOConsortiumAllele" type="java.lang.String" />
          <attribute name="missenseChange" type="java.lang.String" />
          <attribute name="mutagen" type="java.lang.String" />
          <attribute name="natureOfVariation" type="java.lang.String" />
          <attribute name="interpolatedMapPosition" type="java.lang.String" />
          <attribute name="species" type="java.lang.String" />
          <attribute name="rearrangement" type="java.lang.String" />
          <attribute name="linkedTo" type="java.lang.String" />
          <collection name="phenotype" referenced-type="Phenotype" reverse-reference="phenotypeAllele" />
          <collection name="phenotypeNotObserved" referenced-type="Phenotype" reverse-reference="phenotypeAlleleNotObserved" />
          <collection name="affectsGenes" referenced-type="Gene" reverse-reference="affectedByAlleles" />
          <collection name="affectsCDSs" referenced-type="CDS" reverse-reference="affectedByAlleles" />
          <collection name="affectsTranscripts" referenced-type="Transcript" reverse-reference="affectedByAlleles" />
          <!--<collection name="strains" referenced-type="Strain" reverse-reference="variations" /> -->
          <collection name="fromLabs" referenced-type="Laboratory" reverse-reference="variations" />
          <collection name="geneClass" referenced-type="GeneClass" reverse-reference="variations" />
        </class>```

Notice that the order is different from anything else. Also, above in your examples, we have classes that are coming from XMLs and classes that are coming from GFF.

There's nothing in the documentation related to this issue, the only possibility is asking them if there's a way to force a certain order. The build model XML file also has a completely different element order than some other configuration files.

**Comment by chris-grove** [comment]
OK. I think it would be worth asking Intermine folks.

**Comment by nuin** [comment]
Not possible according to InterMine devs.
