### ISSUE TITLE
WormMine: im-dev1 testing Feb 12, 2018: Allele "Missense" and "Missense Change" attributes point to a specific CDS but isn't clear

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6183]
The "Missense" and "Missense Change" attributes of alleles are referring to one specific CDS object that is affected in the indicated manner, but WormMine currently has no way to indicate which CDS it is. For example, the allele "m41":

http://www.wormbase.org/species/c_elegans/variation/WBVar00088550#08--10

![screen shot 2018-02-12 at 11 19 00 am](https://user-images.githubusercontent.com/611382/36106929-9d07fbac-0fe6-11e8-8ba9-deb5fc7c9f36.png)

is an allele of the gene daf-2 that affects four different CDS's of the gene in a similar manner (G to E change) but at different locations in the different CDSs. The data populated in WormMine is just that of the first one listed in the .ACE object, in this case amino acid 307 (for CDS "Y55D5A.5e", seen in Tree Display on WB page, but not available in WormMine):

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.missense Allele.missenseChange Allele.affects" longDescription="" sortOrder="Allele.primaryIdentifier asc">
  <constraint path="Allele.symbol" op="=" value="m41"/>
</query>`

I would suggest removing the "Missense" attribute, possibly only keeping the "Missense Change" attribute, as that effect is usually (always?) the same for all CDS's affected. Otherwise, we keep the "Missense" attribute, but then we'd need a way to show all of the missense changes and indicate which CDS's are affected in each respective manner, which I think would be quite tricky to implement at this point.

**Comment by nuin** [comment]
`I would suggest removing the "Missense" attribute, possibly only keeping the "Missense Change" attribute` 

`Missense` removed.
