### ISSUE TITLE
WormMine: im-dev1 testing Feb 12, 2018: Allele "Amber", "Ochre" and "Opal" attributes point to a specific CDS but isn't clear

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6184]
Similar to #6183 

The Allele class attributes "Amber_UAG", "Ochre_UAA", "Opal_UGA" each refer to specific CDS's affected at the location indicated, but no CDS is specified. For example, the allele "m65" is an Amber W to stop mutation:

http://www.wormbase.org/species/c_elegans/variation/WBVar00088561#0a5--10

![screen shot 2018-02-12 at 11 30 51 am](https://user-images.githubusercontent.com/611382/36107509-50b856e6-0fe8-11e8-93cb-a046feaf8733.png)

but the location at which this effect takes place depends on the specific CDS referred to, which isn't provided in WormMine. In WormMine, the entry for the "Amber_UAG" attribute is:

W to amber stop (1449)

The "W to amber stop" applies equally to all affected CDS's, but the position 1449 only applies to the first CDS listed in the .ACE file or Tree Display "Y55D5A.5a", which isn't available information in WormMine. I would suggest stripping out the position in these entries if possible to only display:

W to amber stop

without specifying the CDS. Otherwise we would need to indicate all the positions and their respective CDS's, which I think would be tricky to implement at this time.

**Comment by nuin** [comment]
So, solution is either to remove these `W to amber stop` entries or to strip `(149)` from 

```xml
<Txt><![CDATA[W to amber stop (149)
              ]]><Inferred_automatically>
                <Txt><![CDATA[map_Alleles.pl]]></Txt>
              </Inferred_automatically>
            </Txt>
          </Amber_UAG>
```

right?

**Comment by chris-grove** [comment]
Yes, ideally we would just strip the position `(149)` from the entry leaving the entire entry simply as `W to amber stop`; of course we want it generalized to strip the `(int)` from the end of any of these entries as well as from the "Ochre_UAA" and "Opal_UGA" entries, maintaining the amino acid letter code in the entry ("W" in this case).

**Comment by nuin** [comment]
`of course we want it generalized to strip the (int)` I don't think that it is possible when using XML. I would have to check the code to see how to implement this, but the main issue would be connect/merge to something else, as it will be a position in a `CDS` range.

**Comment by chris-grove** [comment]
OK, this isn't really high priority right now, but it would be good to deal with at some point.

**Comment by chris-grove** [comment]
@nuin Looks good! Thanks!
