### ISSUE TITLE
paper curation

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6186]
Dear WormBase,

We recently received an email from you, calling to flag our paper for detailed curation:
"WorMachine: machine learning-based phenotypic analysis tool for worms." BMC Biol, 2018.

While updating information and before pressing the "Flag" button, we accidentally pressed the following link:

-- If this is not a primary research article (e.g., this is a review, book chapter, etc.), please click here. You may ignore the fields below. Thank you. 

Afterwards, we resubmitted the information via the "Flag" button.
We would just like to clarify that our paper is indeed the primary research article, and not a review or book chapter.

Thanks and Best Regards,

**Comment by epaule** [comment]
our paper curator are currently on the road, but should come back beginning next week.
And should contact you then on how to proceed.

**Comment by vanaukenk** [comment]
Dear Yael,

Thanks for contacting WormBase about curating your paper.

I've double-checked all of the information in our paper curation tool and everything is fine; your paper is listed there as a primary research article.

Best,
--Kimberly
