### ISSUE TITLE
  Hi, Is there an easy way to upload a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6189]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>Is there an easy way to upload a list of genes (e.g., Y49E10.14, etc) and get a list of their "common names" (e.g., pie-1, etc) if any?<br/>Thank you<br/>Bill K</p>

**Reported by:** bill****** (bkel************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by chris-grove** [comment]
Hello Bill,


Yes, the easiest way to do this is using our SimpleMine tool:


http://www.wormbase.org/tools/mine/simplemine.cgi



A link to SimpleMine can be found in the "Tools" menu available at the top of any WormBase page. Paste in your list of identifiers into the search field, select "download" or "html" to download a tab-delimited file or view the results on a webpage, and select which attributes you want to see in the output. "Public Name" is the common name you're looking for. The output table will list your input list along with your output.


Let us know if you have any questions.


Best,


Chris Grove
WormBase
