### ISSUE TITLE
Request: revise display of gene lists from WormBase Ontology Browser (WOBr)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6190]
Currently, retrieving the list of genes annotated to an ontology term (or any of its ontological descendant terms) from the Ontology Browser (WOBr) tool leads to an often lengthy page where the genes are distributed among one or more lists according to come category or criteria. These results pages can often times be thousands of genes long, and it isn't always clear how many partitions or lists there are. Acquiring the list of genes usually (always?) means that a user has to manually copy and paste the list of gene names (public names, not WBGene IDs or sequence names) into another file and then process the list from there. There are several issues with this:

1) The page is too long to read and a user cannot quickly get a sense as to how many distinct lists of genes there are, or what the criteria for each list is, without scrolling all the way up and down the page which is tedious and can be error prone, especially for large (>1000) lists.

2) Because there are multiple lists, a user cannot just select all gene names on the page (Cmd+A or Ctrl+A or Shift+click select from top to bottom) to get a single list

3) The only name or identifier provided is the public name, which can become an ambiguous identifier if then processing the list of names in SimpleMine where, for example, the C. elegans gene name "nas-36" will be recognized as the C. elegans gene nas-36 (WBGene00003552) but will also be picked up as the other name of the B. malayi gene Bma-nas-36 (WBGene00222655). Additionally, many any gene names that come up that represent dead genes that have merged, will come up in SimpleMine as both the original dead gene as well as the live gene. The point is, the public name is not always unambiguous or sufficient to specify exactly which gene the list is referring to. Yes, there are hyperlinks, but that only helps if you have a sufficiently small list to click on each one individually.

For example, if I look up the GO root term "biological process" and look at all 54,508 gene products (WS262) I get an enormous page with the following categories/lists:

List of 67 C. elegans genes that were annotated with GO:0008150 biological_process

List of 9573 C. elegans genes that were annotated with GO:0008150 biological_process or any of its transitive descendant terms

List of 0 non C. elegans genes that were annotated with GO:0008150 biological_process

List of 44935 non C. elegans genes that were annotated with GO:0008150 biological_process or any of its transitive descendant terms

Or, if I look up the "Variant" phenotype term and all of its 9,898 gene products (WS262), I get a large page with the following categories/lists:

List of 4 genes that were annotated with WBPhenotype:0000886 Variant via RNAi

List of 2 genes that were annotated with WBPhenotype:0000886 Variant via Variation

List of 7700 genes that were annotated with WBPhenotype:0000886 Variant or any of its transitive descendant terms via RNAi

List of 4531 genes that were annotated with WBPhenotype:0000886 Variant or any of its transitive descendant terms via Variation

and it isn't entirely clear which species these genes are from.

I would like to request the following changes to the WOBr gene lists:

1) Condense all of the gene lists to a table of download links, one link/file for each category/list, perhaps even separated by species. The table should fit entirely within a reasonably sized web page.

2) The downloadable files should contain the list of (plain text) WBGene identifiers, at least, and possibly be a tab-delimited table of WBGene IDs, sequence names, and public names of the genes, perhaps also with species indicated

**Comment by azurebrd** [comment]
Hi @chris-grove 
Is there an example of what you'd like a table to work like on WormBase (to keep things similar) or elsewhere (to get an idea of what you'd like) ?

**Comment by chris-grove** [comment]
@azurebrd 

Well, sort of. I've drawn up some mockups as to how I'd like to see the gene lists for each ontology (based on how they are displayed currently):

https://docs.google.com/presentation/d/1pBlrphQaHrBwo-x9gntIb0a_JFv00zWe-KPHFAjXZKc/edit?usp=sharing

That includes a description of the download file format that I would like (tab-delimited .txt file with gene ID, public name, sequence name, and species [slide 6]).

I would like file download links as has been implemented on staging for variations with multiple genes, like:

https://staging.wormbase.org/species/c_elegans/variation/WBVar01499697#0--10

See the "Download genes (9741)" link in the Overview widget gray box to the right.

**Comment by azurebrd** [comment]
Thanks @chris-grove 
Sibyl's helped me work out something about the development server not working, and I've started looking into how the file generation works.  I've talked to @raymond91125  and I think we understand/agree with you on what we're trying to do.

**Comment by azurebrd** [comment]
This should do it. https://github.com/WormBase/website/pull/6292
