### ISSUE TITLE
WOBr missing 331 genes that have RNAi phenotype (compared to WormMine and website)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6191]
It seems there are 331 (C. elegans) genes that come up as having an RNAi phenotype in WormMine (and the website (gene pages) from what I can tell):

https://www.dropbox.com/s/o1pae2bf7vz036y/331_genes_with_RNAi_phenotype_in_WS262_WormMine_not_under_Variant_in_WOBr.xlsx?dl=0

that are not coming up on the Variant phenotype ontology browser (WOBr) gene product list:

http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=Variant&focusTermId=WBPhenotype:0000886

Some of these are pseudogenes, which can probably be ignored, but there are many protein coding genes in the list as well. It seems the WOBr calculation has missed them somehow.

**Comment by raymond91125** [comment]
It looks like the issue is upstream in the phenotype association file:

ftp://caltech.wormbase.org/pub/wormbase/releases/last-development-release/ONTOLOGY/phenotype_association.WS262.wb

I spot checked a couple of genes (abu-2, myo-2). There are no positive 
(not NOT) phenotype associations.

I think the reason is that we don't include phenotypes caused by RNAi 
when the gene is not the primary target.

I personally think this is a feature but I guess we should be consistent 
through out.

Raymond

**Comment by chris-grove** [comment]
@raymond91125 
OK, yes that seems to be the case (these genes are secondary targets). OK, yes, ideally we would have a way to indicate in all cases if the gene is a primary or secondary target in these experiments, but I do think it would be good to maintain consistency across the data outlets. Who maintains/develops the script/code for the phenotype association file?

**Comment by raymond91125** [comment]
@khowe is the DQM, if you will. We can decide on what to include from the perspective of users. I personally believe it's better to seek higher precision for these bulk qualitative data tools thus I am in favour of not including 2ndary targets for WOBr or SObA.

**Comment by khowe** [comment]
Yes, I am the author/maintainer of the script that generates the phenotype_association.wb file. And yes, it intentionally only reports Primary associations for RNAi phenotypes:

https://github.com/WormBase/wormbase-pipeline/blob/master/scripts/ONTOLOGY/make_phenotype_GAF.pl#L192

Although this was decided 4 years ago, I'm fairly confident that it wasn't my unilateral decision, but the outcome of a group discussion. It's easily changed, of course .

**Comment by chris-grove** [comment]
@khowe 
Thanks. Yes, I'm sure it was a group decision. I'm trying to decide now whether to include 2ndary targets in or exclude 2ndary targets from both data sets.

**Comment by chris-grove** [comment]
Closing. Will be resolved with #7138
