### ISSUE TITLE
trying to determine the name of the plasmid used t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6192]
*Help Desk query collected when no chat operators were online. Follow up required.*

trying to determine the name of the plasmid used to generate the kyEx2865 transgene.

**Reported by:** cory (kunk********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/transgene/WBTransgene00019139#01--10">http://www.wormbase.org/species/all/transgene/WBTransgene00019139#01--10</a>
**Browser:** Chrome 64.0.3282.167

**Comment by chris-grove** [comment]
Hello Cory,


If we stored the plasmid name for this transgene, it would most likely be stored as the name of the construct. You can find the construct name on the construct page, the hyperlink for which can be found on the transgene page in the Construction Details widget:


http://www.wormbase.org/species/all/transgene/WBTransgene00019139#014--10



The construct in this case is WBCnstr00018486:



http://www.wormbase.org/species/all/construct/WBCnstr00018486#01--10



It doesn't seem we have annotated a name for the plasmid, as it may not have been reported in the original publication. I would recommend reaching out to the authors of the paper in which the transgene was first described:


https://www.ncbi.nlm.nih.gov/pubmed/21849976



Best,


Chris Grove
WormBase
