### ISSUE TITLE
  Have the SNPs between the Hawaiian an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6193]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Have the SNPs between the Hawaiian and Bristol strains be identified? If so how do I access that information?</p>

**Reported by:** John******* (jlaw*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by epaule** [comment]
Several studies have independently sequenced the Hawaiian strain (CB4856), aligned the reads back to N2 and called variants. We've aggregated the data from all the studies we know about, and you can pull out the union of all the variant calls from our GFF file:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/c_elegans.canonical_bioproject.current.annotations.gff3.gz

The following "grep" will give you the CB4856 polymorphisms (note that the last "grep -v PCoF" part is necessary to remove some redundancy from the list). 

cat c_elegans.canonical_bioproject.current.annotations.gff3 | grep WBVar | grep CB4856 | grep -v PCoF
