### ISSUE TITLE
CDS length display off on C. briggsae protein page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6197]
I just noticed that on the protein page for C. briggsae protein BP:CBP06050, which has multiple distinct CDSs associated, that one of the CDSs, CBG19306,  is listed as having a different length than all of the others (375 nt instead of 312nt like the rest):

http://www.wormbase.org/species/c_briggsae/protein/BP:CBP06050#06--10

Looking at the sequence it is clear that the CDS length is actually 312, and this is accurately reflected on the gene and CDS pages for this CDS, but for some reason is displaying 375nt on the protein page. I thought I'd point it out in case it is indicative of a bug somewhere.

**Comment by sibyl229** [comment]
Hi @chris-grove the CDS length in protein overview should be fixed now: https://staging.wormbase.org/species/c_briggsae/protein/BP:CBP06050#06--10 Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks good! Thanks!
