### ISSUE TITLE
I have a list of differentially expressed M. incog...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6198]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have a list of differentially expressed M. incognita genes obtained from RNAseq, I want to perform GO analysis to see which processes are enriched in different samples. 
I dont see an interface where I can insert the gene IDs. 
Here is the list of genes and I need your help.
Minc16383 Minc03219 Minc09563 Minc02900 Minc01267 Minc04354 Minc16523 Minc01743 Minc04729 Minc04528 Minc14216 Minc09368 Minc05489 Minc00272 Minc10138 Minc00898 Minc05226 Minc06560 Minc16578 Minc16023 Minc13501 Minc16591 Minc04310 Minc00395 Minc02802 Minc17167 Minc04321 Minc04689 Minc02736 Minc10704 Minc17103 Minc06254 Minc01677 Minc06898 Minc10268 Minc01681 Minc08743 Minc00009 Minc14612 Minc03471 Minc15657 Minc16188 Minc18981 Minc07837 Minc16393 Minc09531 Minc11943 Minc18946 Minc09380 Minc18242 Minc03681 Minc17222 Minc14267 Minc03904 Minc07555 Minc13788 Minc16891 Minc05444 Minc11494 Minc17845 Minc19018 Minc13534 Minc16699 Minc04119 Minc16067 Minc17047 Minc18672 Minc10385 Minc15562 Minc16883 Minc07067 Minc17190 Minc18763 Minc08809 Minc17261 Minc12680 Minc09553 Minc16021 Minc18124 Minc01763 Minc00078 Minc11323 Minc07154 Minc18685 Minc08997 Minc00444 Minc10855 Minc00811 Minc00677 Minc12325 Minc02916 Minc12453 Minc04786 Minc17106 Minc00144 Minc05789 Minc11128 Minc06139 Minc08960 Minc03100 Minc18086 Minc16612 Minc17448 Minc03182 Minc09860 Minc00154 Minc09766 Minc14936 Minc13369 Minc08476 Minc03160 Minc03024 Minc03273 Minc10116 Minc14328 Minc15498 Minc18007 Minc01399 Minc17567 Minc17685 Minc05210 Minc14276 Minc00309 Minc02980 Minc03000 Minc02975 Minc01707 Minc15601 Minc04995 Minc04590 Minc13396 Minc03008 Minc06992 Minc18176 Minc13676 Minc04128 Minc13889 Minc04244 Minc08240 Minc07810 Minc14931 Minc18253 Minc10203 Minc06780 Minc15393 Minc03461 Minc11100 Minc08038 Minc01201 Minc12108 Minc08940 Minc04118 Minc15711 Minc06949 Minc01099 Minc08332 Minc07489 Minc19088 Minc18100 Minc03341 Minc02164 Minc11998 Minc18846 Minc06051 Minc03320 Minc19118 Minc17859 Minc18633 Minc01607 Minc08930 Minc08891 Minc01639 Minc04393 Minc02185 Minc17305 Minc09069 Minc16719 Minc08055 Minc07911 Minc06777 Minc05074 Minc13581 Minc12993 Minc02823 Minc03664 Minc07211 Minc12266 Minc14855 Minc09610 Minc10979 Minc13905 Minc08859 Minc17599 Minc12529 Minc07210 Minc02534 Minc16896 Minc01271 Minc02696 Minc12938 Minc15954 Minc15040 Minc13045 Minc13636 Minc06247 Minc01422 Minc01543 Minc04325 Minc03769 Minc02063 Minc09452 Minc06914 Minc06724 Minc10437 Minc17627 Minc06860 Minc06889 Minc13795 Minc15974 Minc00498 Minc12759 Minc11253 Minc18673 Minc18522 Minc17282 Minc16893 Minc03969 Minc18861 Minc06602 Minc05544 Minc08756 Minc17857 Minc18425 Minc02052 Minc11480 Minc13347 Minc18966 Minc09016 Minc08527 Minc07049 Minc01332 Minc06026

**Reported by:** Muha********** (mfah*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/ontology_browser">http://www.wormbase.org/tools/ontology_browser</a>
**Browser:** Firefox 58.0

**Comment by epaule** [comment]
We don't support enrichment analysis for species outside a small "core" set at the moment. We hope to add an enrichment tool to cover all the species in WormBase ParaSite at some point in the future.
