### ISSUE TITLE
  Dear wormbase, I was wondering if col...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6210]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase,<br/>I was wondering if col-126 and col-127 are truly two genes or just one gene?<br/>In Uniprot col-126 and col-127 are listed as synonymes:<br/>http://www.uniprot.org/uniprot/G5EFU8<br/>And you have it as 2 genes<br/>http://www.wormbase.org/species/c_elegans/gene/WBGene00000700#0123456789abcdefg--10<br/>http://www.wormbase.org/species/c_elegans/gene/WBGene00000701#0123456789abcdefg--10<br/>The DNA sequence of col-126 and col-127 are exactly the same<br/>https://www.ebi.ac.uk/Tools/services/web/toolresult.ebi?jobId=clustalo-I20180222-122914-0836-55559860-p1m<br/>By the genome assembly, was there unique flanking sequence of either gene to call them two genes? <br/>We are currently writing a paper about collagens col- genes and this would be important to know. <br/>Thank you in advance. <br/>Best<br/>Collin</p>

**Reported by:** Coll******** (coll****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5

**Comment by gw3** [comment]
Hi Colin,

col-126 and col-127 are two genes.

They are next to each other, but on opposite strands, forming an 
inverted repeat.

We (including one person who used to work on the original assembly team) 
have had a look at the original assembly data.
There is nothing to indicate that the assembly is incorrect.
There are some regions between these two genes which do not have a lot 
of supporting reads.

If you think that it is important for your project, it might be a good 
idea to PCR up the region containing these two genes to confirm that the 
current assembly is correct.

Gary Williams
