### ISSUE TITLE
  Hi, Could you please tell me how can ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6213]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>Could you please tell me how can I search for SNPs in specific genomic regions in Hawaiian C. elegans?<br/>Thank you.<br/>Vlad</p>

**Reported by:** tigi**************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by raymond91125** [comment]
In JBrowse, you can turn on "Alleles, Variations, RNAi"->"Polymorphisms" 
in the genome of BioProject PRJNA13758 (Bristol) to see CB4856 
(Hawaiian) SNPs but not the other way around.

Raymond


On 23/02/18 15:48, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> Could you please tell me how can I search for SNPs in specific genomic 
> regions in Hawaiian C. elegans?
> Thank you.
> Vlad
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6213. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6213>.
>
> Reported by: tigister@gmail.com
> 23 Feb 18 23:48
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 
> Firefox/58.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
