### ISSUE TITLE
hello! I 'm looking for information about odr-4 ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6214]
*Help Desk query collected when no chat operators were online. Follow up required.*

hello! I 'm looking for information about odr-4 gene. But i don't found. Can you help me please?

**Reported by:** Mari***************** (nour************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 64.0.3282.167

**Comment by epaule** [comment]
Here is a link to the odr-4 gene:

http://www.wormbase.org/species/c_elegans/gene/WBGene00003851#0--10

You can find genes by using the search box in the top right. The search box by default searches for genes. You can also select other types of entities to search by. 

I hope this helps.
