### ISSUE TITLE
How would I cite wormbase for a paper use? We've s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6215]
*Help Desk query collected when no chat operators were online. Follow up required.*

How would I cite wormbase for a paper use? We've specifically looked at the genes eya-1, lsd-1, and pax-6.

**Reported by:** Morg*************** (morg*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001377#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001377#0-9g-3</a>
**Browser:** Chrome 64.0.3282.167

**Comment by vanaukenk** [comment]
Dear Morgan,

Thanks for writing to WormBase.

Information on how to cite WormBase is available on our website here:

http://www.wormbase.org/about/citing_wormbase#012--10

Please feel free to contact us if you have any additional questions.

Best,
--Kimberly Van Auken
