### ISSUE TITLE
Chris: Hello Orna, how can I help? visitor_name (v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6216]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Orna, how can I help?</br>visitor_name (visitor_email): Hi, I just noticed that the genes thta appear in a paper from my lab, Joseph-Strauss et al 2012 May 15;365(2):445-57. doi: 10.1016/j.ydbio.2012.02.036. are not curated in wormbase (I didn't check each one but the frist one I checked weren't there). It might be useful for readers interested in these proteins. Thanks, Orna</br>Chris: OK, thanks for the heads up. We'll take a look. Did you have specific curation requests, or just wanted to make sure that the paper was listed on those gene pages?</br>visitor_name (visitor_email): The latter. Thanks!

**Reported by:** Orna********** (orna***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004914#036-9ge-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004914#036-9ge-3</a>
**Browser:** Firefox 52.0

**Comment by chris-grove** [comment]
Duplicate #6217
