### ISSUE TITLE
  Is it possible to search for genes by...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6219]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is it possible to search for genes by inputting multiple phenotypes? And maybe narrow it down to only certain chromosomes? I just completed a forward genetic screen and got several mutants with multiple secondary phenotypes but I'm not sure how to generate a list that has those specific combination of phenotypes. Thanks for any help here!</p>

**Reported by:** Jess* (jcoh************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by chris-grove** [comment]
We don't have a tool that does exactly that (takes in multiple phenotypes and looks for genes annotated to all of them), but there are some multi-step queries that could answer your question.

Probably you're best bet would be to use the WormBase Ontology Browser on phenotype term pages to collect the list of all genes annotated to each particular phenotype and then do list comparison to see which genes exist in both (all) sets. For example, if you are interested in genes annotated to the lethal (or a descendant term) phenotype, you can look at the lethal phenotype page:

http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000062#03--10

In the "Ontology Browser" widget, you will see a link to a list of all genes annotated to the term "lethal" or any of its ontological descendant terms (e.g. "embryonic lethal"); there are currently 4,970 genes annotated. Click on the link to the gene product list, copy all gene names and store that list as "lethal" genes. Then go to the other phenotype(s) page(s) and collect the gene lists for the other phenotypes and compare the lists using a list comparison tool, like this one:

http://jura.wi.mit.edu/bioc/tools/compare.php

Each time you do a comparison you can collect all genes belonging to both input lists, each time.

Alternatively, you can use WormMine to perform the following query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="(A and B) or (C and D) or (A and D) or (B and C)">
  <constraint path="Gene.alleles.phenotypesObserved.name" code="A" op="=" value="lethal"/>
  <constraint path="Gene.alleles.phenotypesObserved.name" code="B" op="=" value="dumpy"/>
  <constraint path="Gene.RNAiResult.phenotype.name" code="C" op="=" value="lethal"/>
  <constraint path="Gene.RNAiResult.phenotype.name" code="D" op="=" value="dumpy"/>
</query>`

Once you've loaded the above XML query into the WormMine QueryBuilder (via the import XML option), you would need to use the QueryBuilder tool to replace the constraints to the "lethal" and "dumpy" phenotypes (that I randomly chose) to those phenotype terms you are interested in. Note that the above query really only works for two phenotypes. If you have more, you would need to add the additional constraints for both allele- and RNAi-based phenotypes and adjust the constraint logic to accommodate all possible scenarios (which gets complicated for many more phenotypes).

I hope that helps.

Let us know if you have questions about those processes.

Best,

Chris Grove
WormBase
