### ISSUE TITLE
  I would like to create a table that h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6220]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to create a table that has all gene names, sequence names, and description (for example: "xbp-1 encodes a bZIP transcription factor orthologous to yeast Hac1 and mammalian X box-binding protein 1...")<br/>Where can I download this information (preferably as a table)?<br/>Thanks</p>

**Reported by:** Raz (razb*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

**Comment by epaule** [comment]
we got  ftp://ftp.wormbase.org/pub/wormbase/releases/WS262/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS262.functional_descriptions.txt.gz
which contains the collected ids and descriptions, with each entry separated by '='
Is that what you are looking for?

**Comment by chris-grove** [comment]
There are a couple of options to get this table:

1) SimpleMine: The SimpleMine tool (available under the Tools menu on any WormBase page) will let you download a table of all C. elegans genes and their descriptions:

http://www.wormbase.org/tools/mine/simplemine.cgi

Uncheck the "Set All Checkboxes" box, and then specifically select the "WormBase Gene ID", "Public Name", "Sequence Name" and "Concise Description" boxes. Make sure the "download" option is selected (not the "html" option) and click on the "query all C elegans" button. You will then download a tab-delimited file with all of the data.

2) WormMine: The WormMine tool (available under the Tools menu on any WormBase page) will also let you download a table of all C. elegans genes and their descriptions:

http://intermine.wormbase.org/tools/wormmine/begin.do

Use the following query in WormMine:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.description Gene.briefDescription" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>`

You can import the above XML query into WormMine from the "Import query from XML" option on the WormMine QueryBuilder page. Once you run the query you can export the results in tab-delimited (.tsv) format.

Note that the WormMine query will not include automated descriptions, which are more recently generated, automatic descriptions written by a script (these are available in SimpleMine).

Let us know if you need something else or have any questions.
