### ISSUE TITLE
Could you please let me know the name of this gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6222]
*Help Desk query collected when no chat operators were online. Follow up required.*

Could you please let me know the name of this gene in wormbase? https://www.ncbi.nlm.nih.gov/nuccore/Z81568
Thanks!

**Reported by:** Zhao***** (zhao**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 64.0.3282.186

**Comment by chris-grove** [comment]
The link you've provided is for a cosmid clone, representing a portion of chromosome III from C. elegans that contains several genes:

http://www.wormbase.org/species/c_elegans/clone/K08E3#042--10

You can see the list of genes encompassed by this cosmid on the page linked above.

Let us know if you have more questions.
