### ISSUE TITLE
New Species for WS264 - T. muris (Core) C.nigoni (Non-core)

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6223]
Dear Web Team,

**## WS264 sees the introduction of T. muris as a core species**
Requirements:
- g/jbrowse instances
- Species pages
- Incorporation into the navigation menus 
- BLAST/BLAT
- Full integration into other tools etc.

 
**## C.nigoni to your build as Tier III**
Requirements:
- g/jbrowse
- Species page
- mapping the gene+species to the respective browser endpoint

**Comment by scottcain** [comment]
Oooh, a new species.  Now we get to see what pipeline stuff I've written breaks.

**Comment by scottcain** [comment]
GBrowse pages are up for the new species:

https://staging.wormbase.org/tools/genome/gbrowse/c_nigoni_PRJNA384657/
https://staging.wormbase.org/tools/genome/gbrowse/t_muris_PRJEB126/

JBrowse will be along in a few days.

**Comment by tharris** [comment]
## WS264 sees the introduction of T. muris as a core species
Requirements:

g/jbrowse instances -- _gbrowse mysql database in place, configuration pending; jbrowse pending_
Species pages -- _ @sibyl229, can you add?_
Incorporation into the navigation menus -- _ @sibyl229, can you add?_
BLAST/BLAT -- _complete_
Full integration into other tools etc.

## C.nigoni to your build as Tier III
Requirements:

g/jbrowse -- _gbrowse mysql DB in place, configuration pending; jbrowse pending_
Species page -- _ @sibyl229 can you add? _
mapping the gene+species to the respective browser endpoint

**Comment by sibyl229** [comment]
Hi @Paul-Davis there's a species table on the All species page that might need updating: https://staging.wormbase.org/species/all#0123--10 But unfortunately I don't know all the info (like clade, original provider) to fill it in, could you do that please? Thanks!

**Comment by sibyl229** [comment]
Hi @tharris T muris has been added to staging as tier 2 and C nigoni as tier 3. Objects (such as genes) from both species need to be built into search index before this ticket is done and tested. I will start on that when the WS264 Datomic DB/transactor is ready. Adam says he will be working on the DB/transactor this week.

- [x] T muris can be accessed from the dropdown menu
- [x] All species page lists both: https://staging.wormbase.org/species/all#0123--10
- [x] T muris species index page: https://staging.wormbase.org/species/t_muris
- [x] C nigoni species index page: https://staging.wormbase.org/species/c_nigoni
- [ ] (after indexing) Test genes from T muris
- [ ] (after indexing) Test genes from C nigoni
- [ ] Check speices in overview widget on All species page

**Comment by scottcain** [comment]
I forgot to mention that JBrowse is done for both species too.

**Comment by epaule** [comment]
@sibyl229 could you put an overview widget into https://staging.wormbase.org/species/t_muris , so we can fill it with fluff?

**Comment by epaule** [comment]
@scottcain I only get the list of "available datasets" if I go to https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data/c_nigoni_PRJNA384657 ot T.muris throught hte dropdown

**Comment by sibyl229** [comment]
Hi @epaule Overview widget added: https://staging.wormbase.org/species/t_muris#34-2-5 You should be able to login and modify it. And maybe the overview widget on the "all species" page needs some update: https://staging.wormbase.org/species/all#0123--10

**Comment by epaule** [comment]
@sibyl229 done :-)

**Comment by scottcain** [comment]
@epaule Oops, they're back now on JBrowse staging.  While Sibyl and I were working on something else I inadvertently reverted to WS263.

**Comment by epaule** [comment]
did https://wormbase.org/species/c_nigoni not pick up the assembly for C.nigoni?

**Comment by epaule** [comment]
related to #6416

**Comment by epaule** [comment]
I think the only differences in the json files between 264 and 265 are the rebranding of Sanger and a fix in the brugia release version. Do you know from where the dropdown populates its data?

**Comment by sibyl229** [comment]
@epaule the assembly problem is probably due to ACeDB:
https://www.wormbase.org/tools/tree/run?name=Caenorhabditis%20nigoni;class=Species
https://staging.wormbase.org/tools/tree/run?name=Caenorhabditis%20nigoni;class=Species

The dropdown on the website (not sure about jbrowse) is based on both the ASSEMBLIES JSON and the wormbase.conf (which determines whether it should be listed in the menu).

**Comment by epaule** [comment]
@sibyl229 the #6228 would be the one with the acedb patches

**Comment by epaule** [comment]
maybe the JBrowse pages use a different wormbase.conf or weren't recached when we fixed the json a few months ago?

**Comment by scottcain** [comment]
The dropdown in JBrowse is populated with config file that I manually curate.

**Comment by epaule** [comment]
@scottcain could you add to Directory -> Browse -> By Species the missing T.muris ?

**Comment by scottcain** [comment]
Hi @epaule On both the main and staging sites, I see T. muris in the directory browse by species section (like this, right?)

<img width="351" alt="screen shot 2018-05-16 at 12 28 19 pm" src="https://user-images.githubusercontent.com/274751/40133712-84d47e9a-590e-11e8-876f-f935e38c02ca.png">

If that's not what you're referring to, can you help enlighten me?

**Comment by epaule** [comment]
yes, but no.
It shows up on the dropdowns on staging and live ... except the ones on the jbrowse pages
![image](https://user-images.githubusercontent.com/20523/40166558-b8235ee4-59b6-11e8-8fec-9d45cb9042a2.png)

**Comment by scottcain** [comment]
OH! Right.  Those are hard coded into the the index.html of JBrowse.  I'll fix shortly.
