### ISSUE TITLE
  Dear doctors, my question is whether ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6226]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear doctors, my question is whether there is the possibility of publishing a bibliographic document on C.elegans with the name: functions of the Ubiquitin E3 ligases and of the heat shock response proteins (HSP) in spermatogenesis of Caenorhabditis elegans, which covers a study of the last 10 years related to these contents. waiting for a good reception I say goodbye Henry Guzmán Amaro Mg in medical sciences mention cellular and molecular biology </p>

**Reported by:** henr*************** (henr*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by Gschindelman** [comment]
Dr Guzmán Amaro,
WormBase does not publish research/reviews.  You may want to look into WormBook (http://www.wormbook.org/)  or Micropublication:biology (https://www.micropublication.org/)
Sincerely
Gary Schindelman
WormBase Helpdesk
On Mar 3, 2018, at 5:44 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:

enry Guzmán Amaro

**Comment by Gschindelman** [comment]
Thank you for your response.
