### ISSUE TITLE
my wormbase page is not working, I use sometimes V...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6227]
*Help Desk query collected when no chat operators were online. Follow up required.*

my wormbase page is not working, I use sometimes VPN on my computer to use google and others

**Reported by:** fare*************** (muft********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/">http://www.wormbase.org/</a>
**Browser:** Chrome 64.0.3282.186

**Comment by Gschindelman** [comment]
Farees,
I was able to access WormBase on Chrome, Firefox and Safari.  Are you still having trouble?
Gary Schindelman
WormBase Helpdesk


On Mar 4, 2018, at 8:42 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:

 farees ud din muft
