### ISSUE TITLE
assemblies manifest

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6228]
in relation to #6223 

I patched the ASSEMBLIES.json file here, so C.nigoni appears: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS264/species/ASSEMBLIES.WS264.json

I also put up a patch for acedb if wanted, so Matt can load it into Datomic: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS264/acedb/PATCHES/nigoni_assembly.ace

**Comment by mgrbyte** [comment]
@a8wright Think you'll need change the d2c copy of the ASSEMBLIES file accordingly

**Comment by mgrbyte** [comment]
@epaule For the datomic migration, the .ace file needs to be in the "dumped-with-timestamps" format... could you make it so? I'm not sure how to (correctly) coherce this patch file into the right format.

**Comment by mgrbyte** [comment]
@epaule actually, will just patch using `tace` and re-dump; sorry for the noise.

**Comment by epaule** [comment]
np, had only started to fake the timestamps ;-)

**Comment by mgrbyte** [comment]
oops, sorry. I've successfully patched WS264 and re-dumped, migration stage 1 continues :+1:

**Comment by tharris** [comment]
Patched (and in production)
