### ISSUE TITLE
Hi, I'm trying to figure out if there is a way eit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6229]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I'm trying to figure out if there is a way either through the annotation files in the FTP or the REST API to get a list of all the C elegans operons, and then retrieve the associated genes for them? I see that there's an operon method for the API, but it only takes individual operon IDs so I would need a list of those first. I haven't come across any operon annotation in the files that are available in the FTP yet. I could probably export a list through the WormBase site (or perhaps WormMart) but I'm trying to do this in a way that would be scriptable for updating when WormBase updates. Thanks!

**Reported by:** Adam********* (adam****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide/for_developers/API-REST/Operon#0--10">http://www.wormbase.org/about/userguide/for_developers/API-REST/Operon#0--10</a>
**Browser:** Firefox 58.0

**Comment by chris-grove** [comment]
Hello Adam,


You can use WormMine (discoverable under the Tools menu) to get the list of operons:


http://intermine.wormbase.org/tools/wormmine/begin.do


Navigate to the "QueryBuilder" tab, click on the "Import query from XML" link on the page, and paste in the following XML query:

<query name="" model="genomic" view="Gene.operon Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.organism.name" longDescription="" sortOrder="Gene.operon asc">
  <constraint path="Gene.operon" op="IS NOT NULL"/>
</query>

and click "Submit". On the resulting page, click on "Show results" and you'll be directed to a table of operons, the genes contained within them, and the species of these genes/operons. You can export the table in tab-delimited format if you wish. Note that there is a WormMine API that you can access on the WormMine homepage (or on the QueryBuilder page); web service clients are available for Perl, Python, Ruby, and Java. You can acquire the corresponding code for the query at the bottom of the QueryBuilder page for the query (see "Perl", "Python", "Ruby" and "Java" links).


Let us know if you have any questions.


Chris Grove

WormBase
