### ISSUE TITLE
Is there a MSDS for the E. coli OP50?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6230]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is there a MSDS for the E. coli OP50?

**Reported by:** Jack**************** (jvan**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/escherichia_coli/strain/OP50#02--10">http://www.wormbase.org/species/escherichia_coli/strain/OP50#02--10</a>
**Browser:** Chrome 64.0.3282.140

**Comment by Gschindelman** [comment]
Jack
We do not have Safety Data Sheets for reagents, but OP50 is distributed through the Caenorhabditis Genetics Center (CGC), so perhaps they have one:
https://cgc.umn.edu/strain/OP50

It is a Biosafety Level-1 organism.  You may also be able to find this information online, or post to our forum:
http://forums.wormbase.org/

Gary Schindelman
Helpdesk


On Mar 5, 2018, at 3:24 PM, WormBase Helpdesk <notifications@github.com<mailto:notifications@github.com>> wrote:


Help Desk query collected when no chat operators were online. Follow up required.

Is there a MSDS for the E. coli OP50?

Reported by: Jack**************** (jvan**************)
Submitted from: <http://www.wormbase.org/http://www.wormbase.org/species/escherichia_coli/strain/OP50#02--10> http://www.wormbase.org/species/escherichia_coli/strain/OP50#02--10
Browser: Chrome 64.0.3282.140
