### ISSUE TITLE
  There are a lot of missing data on th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6234]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;There are a lot of missing data on this zcIs4 transgene page. Not sure what is going on here.</p>

**Reported by:** Kare****** (kare**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by kyook** [comment]
In a .ace from Jan 2018 the data attached to zcIs4 are : 
Transgene : "WBTransgene00005180"
Public_name	"zcIs4"
Summary	"[hsp-4::GFP; lin-15(n765)]"
Construct	"WBCnstr00005157"
Coinjection_other	"lin-15(n765)"
Integration_method	"UV"
Integrated
Strain	"SJ17"
Strain	"SJ30"
Strain	"SJ4005"
Strain	"SJ4005 "
Strain	"SJ6"
Strain	"CF2260"
Map	"V"
Marker_for	"ER stress"
Marker_for	"UPR-ER"
Reference	"WBPaper00005036"
Reference	"WBPaper00005432"
Reference	"WBPaper00013244"
Reference	"WBPaper00024269"
Reference	"WBPaper00025192"
Reference	"WBPaper00025202"
Reference	"WBPaper00026844"
Reference	"WBPaper00027357"
Reference	"WBPaper00027660"
Reference	"WBPaper00027723"
Reference	"WBPaper00027743"
Reference	"WBPaper00028479"
Reference	"WBPaper00028987"
Reference	"WBPaper00029359"
Reference	"WBPaper00030999"
Reference	"WBPaper00031042"
Reference	"WBPaper00031084"
Reference	"WBPaper00031296"
Reference	"WBPaper00031456"
Reference	"WBPaper00031468"
Reference	"WBPaper00031942"
Reference	"WBPaper00032135"
Reference	"WBPaper00032177"
Reference	"WBPaper00032192"
Reference	"WBPaper00032255"
Reference	"WBPaper00032521"
Reference	"WBPaper00032977"
Reference	"WBPaper00033458"
Reference	"WBPaper00035265"
Reference	"WBPaper00035302"
Reference	"WBPaper00035985"
Reference	"WBPaper00036008"
Reference	"WBPaper00036049"
Reference	"WBPaper00036076"
Reference	"WBPaper00036256"
Reference	"WBPaper00036413"
Reference	"WBPaper00037063"
Reference	"WBPaper00037973"
Reference	"WBPaper00038064"
Reference	"WBPaper00038075"
Reference	"WBPaper00038133"
Reference	"WBPaper00039783"
Reference	"WBPaper00039837"
Reference	"WBPaper00040082"
Reference	"WBPaper00040102"
Reference	"WBPaper00040114"
Reference	"WBPaper00040382"
Reference	"WBPaper00040397"
Reference	"WBPaper00040526"
Reference	"WBPaper00040582"
Reference	"WBPaper00040692"
Reference	"WBPaper00040883"
Reference	"WBPaper00041065"
Reference	"WBPaper00041150"
Reference	"WBPaper00041212"
Reference	"WBPaper00041295"
Reference	"WBPaper00041676"
Reference	"WBPaper00042060"
Reference	"WBPaper00042074"
Reference	"WBPaper00042171"
Reference	"WBPaper00042237"
Reference	"WBPaper00042360"
Reference	"WBPaper00042432"
Reference	"WBPaper00042524"
Reference	"WBPaper00042571"
Reference	"WBPaper00043885"
Reference	"WBPaper00043917"
Reference	"WBPaper00043918"
Reference	"WBPaper00043942"
Reference	"WBPaper00044035"
Reference	"WBPaper00044189"
Reference	"WBPaper00044206"
Reference	"WBPaper00044246"
Reference	"WBPaper00044555"
Reference	"WBPaper00044570"
Reference	"WBPaper00044603"
Reference	"WBPaper00044826"
Reference	"WBPaper00045007"
Reference	"WBPaper00045028"
Reference	"WBPaper00045060"
Reference	"WBPaper00045076"
Reference	"WBPaper00045096"
Reference	"WBPaper00045184"
Reference	"WBPaper00045290"
Reference	"WBPaper00045363"
Reference	"WBPaper00045369"
Reference	"WBPaper00045520"
Reference	"WBPaper00045553"
Reference	"WBPaper00045573"
Reference	"WBPaper00045631"
Reference	"WBPaper00045670"
Reference	"WBPaper00045675"
Reference	"WBPaper00045813"
Reference	"WBPaper00045849"
Reference	"WBPaper00045857"
Reference	"WBPaper00045919"
Reference	"WBPaper00045960"
Reference	"WBPaper00045971"
Reference	"WBPaper00046123"
Reference	"WBPaper00046127"
Reference	"WBPaper00046170"
Reference	"WBPaper00046622"
Reference	"WBPaper00046643"
Reference	"WBPaper00046863"
Reference	"WBPaper00046883"
Reference	"WBPaper00047001"
Reference	"WBPaper00048574"
Reference	"WBPaper00048593"
Reference	"WBPaper00048623"
Reference	"WBPaper00049072"
Reference	"WBPaper00049073"
Reference	"WBPaper00049085"
Reference	"WBPaper00049197"
Reference	"WBPaper00049206"
Reference	"WBPaper00049237"
Reference	"WBPaper00049307"
Reference	"WBPaper00049416"
Reference	"WBPaper00049483"
Reference	"WBPaper00049541"
Reference	"WBPaper00049545"
Reference	"WBPaper00049562"
Reference	"WBPaper00049584"
Reference	"WBPaper00049705"
Reference	"WBPaper00049792"
Reference	"WBPaper00049877"
Reference	"WBPaper00050006"
Reference	"WBPaper00050015"
Reference	"WBPaper00050057"
Reference	"WBPaper00050142"
Reference	"WBPaper00050225"
Reference	"WBPaper00050363"
Reference	"WBPaper00050406"
Reference	"WBPaper00050407"
Reference	"WBPaper00050412"
Reference	"WBPaper00050442"
Reference	"WBPaper00050499"
Reference	"WBPaper00050531"
Reference	"WBPaper00050539"
Reference	"WBPaper00050627"
Reference	"WBPaper00050747"
Reference	"WBPaper00050776"
Reference	"WBPaper00050787"
Reference	"WBPaper00050917"
Reference	"WBPaper00050972"
Reference	"WBPaper00051119"
Reference	"WBPaper00051521"
Reference	"WBPaper00051565"
Reference	"WBPaper00052970"
Reference	"WBPaper00052972"
Reference	"WBPaper00053105"
Reference	"WBPaper00053202"
Reference	"WBPaper00053292"
Reference	"WBPaper00053314"
Reference	"WBPaper00053387"
Reference	"WBPaper00053414"
Reference	"WBPaper00053491"
Synonym	"Expr11091_Ex"
Synonym	"[Phsp-4::GFP]"

**Comment by WenChenWormBase** [comment]
@kyook what you uploaded in Jan. were for WS264. WormBase is currently running WS262 and WS263. zcIs4 looks fine in AceDB for WS263 and WS264.

**Comment by chris-grove** [comment]
@WenChenWormBase 
When I look at WS263 on Spica, zcIs4 appears to be completely empty, as it does on the current live WS263 site (staging right now is also on WS263 and zcIs4 is empty there too)

**Comment by chris-grove** [comment]
@WenChenWormBase @kyook 
I had uploaded the transgene.ace file for the WS263 upload in November. This was the entry for zcIs4:

Transgene : "WBTransgene00005180"
Public_name	"zcIs4"
Summary	"[hsp-4::GFP; lin-15(n765)]"
Construct	"WBCnstr00005157"
Coinjection_other	"lin-15(n765)"
Integration_method	"UV"
Integrated
Strain	"SJ17"
Strain	"SJ30"
Strain	"SJ4005"
Strain	"SJ4005 "
Strain	"SJ6"
Strain	"CF2260"
Map	"V"
Marker_for	"ER stress"
Marker_for	"UPR-ER"
Reference	"WBPaper00005036"
Reference	"WBPaper00005432"
Reference	"WBPaper00013244"
Reference	"WBPaper00024269"
Reference	"WBPaper00025192"
Reference	"WBPaper00025202"
Reference	"WBPaper00026844"
Reference	"WBPaper00027357"
Reference	"WBPaper00027660"
Reference	"WBPaper00027723"
Reference	"WBPaper00027743"
Reference	"WBPaper00028479"
Reference	"WBPaper00028987"
Reference	"WBPaper00029359"
Reference	"WBPaper00030999"
Reference	"WBPaper00031042"
Reference	"WBPaper00031084"
Reference	"WBPaper00031296"
Reference	"WBPaper00031456"
Reference	"WBPaper00031468"
Reference	"WBPaper00031942"
Reference	"WBPaper00032135"
Reference	"WBPaper00032177"
Reference	"WBPaper00032192"
Reference	"WBPaper00032255"
Reference	"WBPaper00032521"
Reference	"WBPaper00032977"
Reference	"WBPaper00033458"
Reference	"WBPaper00035265"
Reference	"WBPaper00035302"
Reference	"WBPaper00035985"
Reference	"WBPaper00036008"
Reference	"WBPaper00036049"
Reference	"WBPaper00036076"
Reference	"WBPaper00036256"
Reference	"WBPaper00036413"
Reference	"WBPaper00037063"
Reference	"WBPaper00037973"
Reference	"WBPaper00038064"
Reference	"WBPaper00038075"
Reference	"WBPaper00038133"
Reference	"WBPaper00039783"
Reference	"WBPaper00039837"
Reference	"WBPaper00040082"
Reference	"WBPaper00040102"
Reference	"WBPaper00040114"
Reference	"WBPaper00040382"
Reference	"WBPaper00040397"
Reference	"WBPaper00040526"
Reference	"WBPaper00040582"
Reference	"WBPaper00040692"
Reference	"WBPaper00040883"
Reference	"WBPaper00041065"
Reference	"WBPaper00041150"
Reference	"WBPaper00041212"
Reference	"WBPaper00041295"
Reference	"WBPaper00041676"
Reference	"WBPaper00042060"
Reference	"WBPaper00042074"
Reference	"WBPaper00042171"
Reference	"WBPaper00042237"
Reference	"WBPaper00042360"
Reference	"WBPaper00042432"
Reference	"WBPaper00042524"
Reference	"WBPaper00042571"
Reference	"WBPaper00043885"
Reference	"WBPaper00043917"
Reference	"WBPaper00043918"
Reference	"WBPaper00043942"
Reference	"WBPaper00044035"
Reference	"WBPaper00044189"
Reference	"WBPaper00044206"
Reference	"WBPaper00044246"
Reference	"WBPaper00044555"
Reference	"WBPaper00044570"
Reference	"WBPaper00044603"
Reference	"WBPaper00044826"
Reference	"WBPaper00045007"
Reference	"WBPaper00045028"
Reference	"WBPaper00045060"
Reference	"WBPaper00045076"
Reference	"WBPaper00045096"
Reference	"WBPaper00045184"
Reference	"WBPaper00045290"
Reference	"WBPaper00045363"
Reference	"WBPaper00045369"
Reference	"WBPaper00045520"
Reference	"WBPaper00045553"
Reference	"WBPaper00045573"
Reference	"WBPaper00045631"
Reference	"WBPaper00045670"
Reference	"WBPaper00045675"
Reference	"WBPaper00045813"
Reference	"WBPaper00045849"
Reference	"WBPaper00045857"
Reference	"WBPaper00045919"
Reference	"WBPaper00045960"
Reference	"WBPaper00045971"
Reference	"WBPaper00046123"
Reference	"WBPaper00046127"
Reference	"WBPaper00046170"
Reference	"WBPaper00046622"
Reference	"WBPaper00046643"
Reference	"WBPaper00046863"
Reference	"WBPaper00046883"
Reference	"WBPaper00047001"
Reference	"WBPaper00048574"
Reference	"WBPaper00048593"
Reference	"WBPaper00048623"
Reference	"WBPaper00049072"
Reference	"WBPaper00049073"
Reference	"WBPaper00049085"
Reference	"WBPaper00049197"
Reference	"WBPaper00049206"
Reference	"WBPaper00049237"
Reference	"WBPaper00049307"
Reference	"WBPaper00049416"
Reference	"WBPaper00049483"
Reference	"WBPaper00049541"
Reference	"WBPaper00049545"
Reference	"WBPaper00049562"
Reference	"WBPaper00049584"
Reference	"WBPaper00049705"
Reference	"WBPaper00049792"
Reference	"WBPaper00049877"
Reference	"WBPaper00050006"
Reference	"WBPaper00050015"
Reference	"WBPaper00050057"
Reference	"WBPaper00050142"
Reference	"WBPaper00050225"
Reference	"WBPaper00050363"
Reference	"WBPaper00050406"
Reference	"WBPaper00050407"
Reference	"WBPaper00050412"
Reference	"WBPaper00050442"
Reference	"WBPaper00050499"
Reference	"WBPaper00050531"
Reference	"WBPaper00050539"
Reference	"WBPaper00050627"
Reference	"WBPaper00050747"
Reference	"WBPaper00050776"
Reference	"WBPaper00050787"
Reference	"WBPaper00050917"
Reference	"WBPaper00050972"
Reference	"WBPaper00051119"
Reference	"WBPaper00051521"
Reference	"WBPaper00051565"
Reference	"WBPaper00052970"
Reference	"WBPaper00052972"
Reference	"WBPaper00053105"
Reference	"WBPaper00053202"
Synonym	"Expr11091_Ex"
Synonym	"[Phsp-4::GFP]"

According to the Tree Display on production, the object appears to be completely empty

**Comment by chris-grove** [comment]
![screen shot 2018-03-07 at 9 49 19 am](https://user-images.githubusercontent.com/611382/37098864-f92106dc-21ec-11e8-83b5-322c6f67874c.png)

**Comment by epaule** [comment]
have a look at that one: WBTransgene00005180

**Comment by chris-grove** [comment]
OK, I take back that zcIs4 is empty in WS263 ACEDB; it just appears that way if I only search the Transgene class by the public name "zcIs4" instead of the full ID "WBTransgene00005180"

**Comment by epaule** [comment]
in your upload was not only WBTransgene00005180, but also another Transgene
object with a primary_id of zcIs4

**Comment by chris-grove** [comment]
@epaule @WenChenWormBase @kyook 
OK, really odd. So there are two "zcIs4" transgenes according to WS263:

http://www.wormbase.org/species/all/transgene/WBTransgene00005180#012437--10

http://www.wormbase.org/species/all/transgene/zcIs4#012437--10

**Comment by chris-grove** [comment]
@epaule 
I can only find mention of the string "zcIs4" in one place in the file I uploaded for WS263, and it's in the entry I pasted above. Here's the .ace file for reference:

﻿https://www.dropbox.com/s/og1mtrmflz8pa6q/transgene.ace?dl=0

**Comment by Paul-Davis** [comment]
There are 3 other bad Transgene objects coming from citace, it might be that another object references then on a non-xref link so you get these ghost objects.......I will go on the hunt for them.

![citace_bad_transgenes](https://user-images.githubusercontent.com/717707/37099731-ff5915b8-2218-11e8-9467-335be36918cb.png)

**Comment by chris-grove** [comment]
@Paul-Davis 
Yes, I just noticed these as well. I'm looking into it too.

**Comment by Paul-Davis** [comment]
Check "WBInteraction000537213" @chris-grove

**Comment by chris-grove** [comment]
@Paul-Davis 
Yep, that looks like at least one culprit. Very strange as that's an autocomplete/controlled-vocabulary field in our Ontology Annotator and yet somehow managed to get in. Thanks, I'll fix that and look for any other instances (and the other transgenes).

**Comment by WenChenWormBase** [comment]
Chris, they all came from you. Possible from interaction objects. 

Transgene : "dvIs70" -O "2018-01-19_17:38:44_Chris"

Transgene : "zcIs4" -O "2018-01-19_17:38:44_Chris"

Transgene : "zcIs9" -O "2018-01-19_17:38:44_Chris"

Transgene : "zcIs13" -O "2018-01-19_17:38:44_Chris"

**Comment by chris-grove** [comment]
@WenChenWormBase 
OK, thanks. I'll keep looking into where they are coming from

**Comment by Paul-Davis** [comment]
I think they are all coming from the WBInteraction data @chris-grove as the TS corresponds to the data load.

**Comment by Paul-Davis** [comment]
Do you want a list @chris-grove

**Comment by WenChenWormBase** [comment]
Yes, the time stamp indicates that they all came from the same ace file.

**Comment by chris-grove** [comment]
@Paul-Davis @WenChenWormBase 
OK, I think I've figured out the problem and I'm fixing it now. Paul, yes if you could send me a list that would be great.
Thanks!

**Comment by Paul-Davis** [comment]
```
Offender: dvIs70
WBInteraction000501468
WBInteraction000537246
WBInteraction000537247
WBInteraction000537248
WBInteraction000537249
WBInteraction000537250
WBInteraction000537251
WBInteraction000537252
WBInteraction000537253
WBInteraction000537254
WBInteraction000537255
WBInteraction000537256
WBInteraction000537257
WBInteraction000537258
WBInteraction000537259
WBInteraction000537260
WBInteraction000537261
WBInteraction000537262
WBInteraction000537263
WBInteraction000537264
WBInteraction000537265
WBInteraction000537266
WBInteraction000537267
WBInteraction000537268
WBInteraction000537269
WBInteraction000537270
WBInteraction000537271
WBInteraction000537272
WBInteraction000537273
WBInteraction000537274
WBInteraction000537275
WBInteraction000537276
WBInteraction000537277
WBInteraction000537278
Offender: zcIs4
WBInteraction000520400
WBInteraction000536747
WBInteraction000536748
WBInteraction000536749
WBInteraction000536750
WBInteraction000536751
WBInteraction000536752
WBInteraction000536753
WBInteraction000536754
WBInteraction000536755
WBInteraction000536756
WBInteraction000536768
WBInteraction000536769
WBInteraction000536770
WBInteraction000536771
WBInteraction000536772
WBInteraction000536822
WBInteraction000537213
WBInteraction000537214
WBInteraction000537215
WBInteraction000537216
WBInteraction000537217
WBInteraction000537218
WBInteraction000537219
WBInteraction000537220
WBInteraction000537221
WBInteraction000537222
WBInteraction000537223
WBInteraction000537224
WBInteraction000537225
WBInteraction000537226
WBInteraction000537227
WBInteraction000537228
WBInteraction000537229
WBInteraction000537230
WBInteraction000537231
WBInteraction000537232
WBInteraction000537233
WBInteraction000537234
WBInteraction000537235
WBInteraction000537236
WBInteraction000537237
WBInteraction000537238
WBInteraction000537239
WBInteraction000537240
WBInteraction000537241
WBInteraction000537242
WBInteraction000537243
WBInteraction000537244
WBInteraction000537245
Offender: zcIs9
WBInteraction000535551
WBInteraction000536932
WBInteraction000536933
WBInteraction000536934
WBInteraction000536935
WBInteraction000536936
WBInteraction000536937
WBInteraction000536938
WBInteraction000536939
WBInteraction000536940
WBInteraction000536941
WBInteraction000536942
WBInteraction000536943
WBInteraction000536944
WBInteraction000536945
WBInteraction000536946
WBInteraction000536947
WBInteraction000536948
WBInteraction000536949
WBInteraction000536950
WBInteraction000536951
WBInteraction000536952
WBInteraction000536953
WBInteraction000536954
WBInteraction000536955
WBInteraction000536956
WBInteraction000536957
WBInteraction000536958
WBInteraction000536959
WBInteraction000536960
WBInteraction000537037
WBInteraction000537038
WBInteraction000537039
WBInteraction000537040
WBInteraction000537041
WBInteraction000537042
WBInteraction000537043
WBInteraction000537044
WBInteraction000537045
WBInteraction000537046
WBInteraction000537047
WBInteraction000537048
WBInteraction000537049
WBInteraction000537050
WBInteraction000537051
WBInteraction000537052
WBInteraction000537053
WBInteraction000537054
WBInteraction000537055
WBInteraction000537056
WBInteraction000537057
WBInteraction000537058
WBInteraction000537059
WBInteraction000537060
WBInteraction000537061
WBInteraction000537062
WBInteraction000537063
WBInteraction000537064
WBInteraction000537065
WBInteraction000537180
WBInteraction000537181
WBInteraction000537182
WBInteraction000537183
WBInteraction000537184
WBInteraction000537185
WBInteraction000537186
WBInteraction000537187
WBInteraction000537188
WBInteraction000537189
WBInteraction000537190
WBInteraction000537191
WBInteraction000537192
WBInteraction000537193
WBInteraction000537194
WBInteraction000537195
WBInteraction000537196
WBInteraction000537197
WBInteraction000537198
WBInteraction000537199
WBInteraction000537200
WBInteraction000537201
WBInteraction000537202
WBInteraction000537203
WBInteraction000537204
WBInteraction000537205
WBInteraction000537206
WBInteraction000537207
WBInteraction000537208
WBInteraction000537209
WBInteraction000537210
WBInteraction000537211
WBInteraction000537212
WBInteraction000537488
WBInteraction000537489
Offender: zcIs13
WBInteraction000536877
WBInteraction000536878
WBInteraction000536879
WBInteraction000536880
WBInteraction000536881
WBInteraction000536882
WBInteraction000536883
WBInteraction000536884
WBInteraction000536885
WBInteraction000536886
WBInteraction000536887
WBInteraction000536888
WBInteraction000536889
WBInteraction000536890
WBInteraction000536891
WBInteraction000536892
WBInteraction000536893
WBInteraction000536894
WBInteraction000536895
WBInteraction000536896
WBInteraction000536897
WBInteraction000536898
WBInteraction000536899
WBInteraction000536900
WBInteraction000536901
WBInteraction000536902
WBInteraction000536903
WBInteraction000536904
WBInteraction000536905
WBInteraction000536906
WBInteraction000536907
WBInteraction000536908
WBInteraction000536909
WBInteraction000536910
WBInteraction000536911
WBInteraction000536912
WBInteraction000536913
WBInteraction000536914
WBInteraction000536915
WBInteraction000536916
WBInteraction000536917
WBInteraction000536918
WBInteraction000536919
WBInteraction000536920
WBInteraction000536921
WBInteraction000536922
WBInteraction000536923
WBInteraction000536924
WBInteraction000536925
WBInteraction000536926
WBInteraction000536927
WBInteraction000536928
WBInteraction000536929
WBInteraction000536930
WBInteraction000536931
WBInteraction000536982
WBInteraction000536983
WBInteraction000536984
WBInteraction000536985
WBInteraction000536986
WBInteraction000536987
WBInteraction000536988
WBInteraction000536989
WBInteraction000536990
WBInteraction000536991
WBInteraction000536992
WBInteraction000536993
WBInteraction000536994
WBInteraction000536995
WBInteraction000536996
WBInteraction000536997
WBInteraction000536998
WBInteraction000536999
WBInteraction000537000
WBInteraction000537001
WBInteraction000537002
WBInteraction000537003
WBInteraction000537004
WBInteraction000537005
WBInteraction000537006
WBInteraction000537007
WBInteraction000537008
WBInteraction000537009
WBInteraction000537010
WBInteraction000537011
WBInteraction000537012
WBInteraction000537013
WBInteraction000537014
WBInteraction000537015
WBInteraction000537016
WBInteraction000537017
WBInteraction000537018
WBInteraction000537019
WBInteraction000537020
WBInteraction000537021
WBInteraction000537022
WBInteraction000537023
WBInteraction000537024
WBInteraction000537025
WBInteraction000537026
WBInteraction000537027
WBInteraction000537028
WBInteraction000537029
WBInteraction000537030
WBInteraction000537031
WBInteraction000537032
WBInteraction000537033
WBInteraction000537034
WBInteraction000537035
WBInteraction000537036
WBInteraction000537086
WBInteraction000537087
WBInteraction000537088
WBInteraction000537089
WBInteraction000537090
WBInteraction000537091
WBInteraction000537092
WBInteraction000537093
WBInteraction000537094
WBInteraction000537095
WBInteraction000537096
WBInteraction000537097
WBInteraction000537098
WBInteraction000537099
WBInteraction000537100
WBInteraction000537101
WBInteraction000537102
WBInteraction000537103
WBInteraction000537104
WBInteraction000537105
WBInteraction000537106
WBInteraction000537107
WBInteraction000537108
WBInteraction000537109
WBInteraction000537110
WBInteraction000537111
WBInteraction000537112
WBInteraction000537113
WBInteraction000537114
WBInteraction000537115
WBInteraction000537116
WBInteraction000537117
WBInteraction000537118
WBInteraction000537119
WBInteraction000537120
WBInteraction000537121
WBInteraction000537122
WBInteraction000537123
WBInteraction000537124
WBInteraction000537125
WBInteraction000537126
WBInteraction000537127
WBInteraction000537128
WBInteraction000537129
WBInteraction000537130
WBInteraction000537131
WBInteraction000537132
WBInteraction000537133
WBInteraction000537134
WBInteraction000537135
WBInteraction000537136
WBInteraction000537137
WBInteraction000537138
WBInteraction000537139
WBInteraction000537140
WBInteraction000537141
WBInteraction000537142
WBInteraction000537143
WBInteraction000537144
WBInteraction000537145
WBInteraction000537146
WBInteraction000537147
WBInteraction000537148
WBInteraction000537149
WBInteraction000537150
WBInteraction000537151
WBInteraction000537152
WBInteraction000537153
WBInteraction000537154
WBInteraction000537155
WBInteraction000537156
WBInteraction000537157
WBInteraction000537158
WBInteraction000537159
WBInteraction000537160
WBInteraction000537161
WBInteraction000537162
WBInteraction000537163
WBInteraction000537164
WBInteraction000537165
WBInteraction000537166
WBInteraction000537167
WBInteraction000537168
WBInteraction000537169
WBInteraction000537170
WBInteraction000537171
WBInteraction000537172
WBInteraction000537173
WBInteraction000537174
WBInteraction000537175
WBInteraction000537176
WBInteraction000537177
WBInteraction000537178
WBInteraction000537179
WBInteraction000537488
WBInteraction000537489
```

**Comment by chris-grove** [comment]
@kyook @WenChenWormBase @Paul-Davis @epaule 
OK, I figured out what had happened and I've fixed all of the underlying data problems.

Is there anyway to push through a patch? If not, we'll just have to deal with these 4 empty transgenes (along with their real counterparts) for a few releases.

Apologies.
