### ISSUE TITLE
WormBase pages timing out

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6237]
The release schedule page:

http://www.wormbase.org/about/release_schedule#01--10

and the release notes page for WS263:

http://www.wormbase.org/about/wormbase_release_WS263

and for WS262:

http://www.wormbase.org/about/wormbase_release_WS262#10--10

are all timing out (504 Gateway time-out) currently.

**Comment by chris-grove** [comment]
Sorry, it isn't specific to release pages. The site is timing out for me in general.

**Comment by chris-grove** [comment]
Apparently, it's just me:

https://downforeveryoneorjustme.com/wormbase.org

**Comment by nuin** [comment]
It's timing out for me too.

**Comment by raymond91125** [comment]
#MeToo

**Comment by chris-grove** [comment]
@nuin @raymond91125 
OK, thanks for the confirmation

**Comment by chris-grove** [comment]
OK, back up for me. Others, re-open if WB is not back up for you.

**Comment by chris-grove** [comment]
Having problems again. Widgets are timing out everywhere

**Comment by sibyl229** [comment]
I'm taking a look

**Comment by nuin** [comment]
Problems spill on WormMine too, cannot load footer and queries don't show any results.

**Comment by chris-grove** [comment]
@sibyl229 
OK, seems back up now. Closing.

**Comment by sibyl229** [comment]
@chris-grove I restarted it. But I don't know what is causing the problem. And it happened twice today already. I will just leave the issue open for now.

**Comment by chris-grove** [comment]
@sibyl229 
OK, sounds good. Thanks!

**Comment by tharris** [comment]
Resolved. Closing.
