### ISSUE TITLE
Create alleles for the Undiagnosed Disease Network (UDN) data 

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#6241]
@Paul-Davis: We have begun working with Andy Golden to import UDN data for worms. Trying to get a small test set into WS265.  Please create the alleles for the genes he's sent us, as they will be put into disease model curation.  I've already e-mailed you the spreadsheet. It would be great if you could also put in the AA change for the alleles. Thanks!

**Comment by Paul-Davis** [comment]
Hi Ranjana,

I have created WBVariations for the 9 that were missing from your list:

![added_vars_ranjana](https://user-images.githubusercontent.com/717707/37288791-10ff3bfe-2600-11e8-80d8-44937d45dbf6.png)

Complete List:
```
"WBVar02147681" "av39"
"WBVar02147682" "av42"
"WBVar02147685" "av47"
"WBVar02147690" "av58"
"WBVar02147691" "av65"
"WBVar02147692" "av66"
"WBVar02147693" "av69"
"WBVar02147694" "av70"
"WBVar02148865" "av85"
"WBVar02148866" "av96"
"WBVar02148867" "av97"
"WBVar02148868" "av54"
"WBVar02148869" "av55"
"WBVar02148870" "av105"
"WBVar02148871" "av106"
"WBVar02148872" "av111"
"WBVar02148873" "av113"
```

I haven't stored the elegans AA change as yet, but will look at curating this information once I have resolved the genomic positions etc.
