### ISSUE TITLE
WormMine WS263: Update Transcript Type --> Gene template query to reflect species available

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6243]
On the WormMine homepage, the Template query "Transcript Type, Species --> Gene":

<img width="354" alt="screenshot 2018-03-09 19 58 50" src="https://user-images.githubusercontent.com/611382/37236389-ed8fac1c-23d4-11e8-8ec3-65697f418846.png">

leads to a constraint options page:

<img width="1053" alt="screenshot 2018-03-09 20 00 46" src="https://user-images.githubusercontent.com/611382/37236397-0885d3e8-23d5-11e8-9382-100ce48c9df1.png">

in which 20 species are offered as options, only 7 of which actually have transcripts:

Brugia malayi
Caenorhabditis brenneri
Caenorhabditis briggsae
Caenorhabditis elegans
Caenorhabditis japonica
Caenorhabditis remanei
Onchocerca volvulus

Can we remove the species for which we have no data from the list of options? That is, remove the following species:

Ascaris suum
Brugia pahangi
Bursaphelenchus xylophilus
Caenorhabditis angaria
Caenorhabditis sinica
Caenorhabditis tropicalis
Danio rerio
Haemonchus conrortus
Heterohabditis bacteriophora
Homo sapiens
Meloidogyne hapla
Meloidogyne incognita
Mus musculus

Also these species do have transcripts and so could be added:

Pristionchus pacificus
Strongyloides ratti

**Comment by nuin** [comment]
I think we already discussed this before and there's no straightforward way to actually modify the dropdown list as it gets the contents from the `organism` table. I will double check, but I am quite sure about it.
