### ISSUE TITLE
  I am trying to generate gene lists fr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6246]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to generate gene lists from wormmart - specifically, I am looking for any neuronal expressed gene (not necessarily neuronal specific), or any gene that would be ubiquitously expressed (and thus would also be expressed in the neurons).  If I use the  the expression cluster (WBPaper00048988:neuron_expressed) and using the template for expression cluster --> gene) work for this purpose?   How do I find other expression clusters (ie neuron specific, ubiquitous, etc).   Thank you so much!<br/>Megan</p>

**Reported by:** Mega********* (mega*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by WenChenWormBase** [comment]
Dear Megan,

Did you mean WormMart or WormMine?

To get gene expressed genes, the best tool is Ontology Browser. It is under
the Tools menu of WormBase.

 http://www.wormbase.org/tools/ontology_browser

Look for "neuron" under Anatomy Ontology, then you will see all the genes
associated with it.

Let us know if you need something else,

Wen.

On Mon, Mar 12, 2018 at 2:04 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I am trying to generate gene lists from wormmart - specifically, I am
> looking for any neuronal expressed gene (not necessarily neuronal
> specific), or any gene that would be ubiquitously expressed (and thus would
> also be expressed in the neurons). If I use the the expression cluster
> (WBPaper00048988:neuron_expressed) and using the template for expression
> cluster --> gene) work for this purpose? How do I find other expression
> clusters (ie neuron specific, ubiquitous, etc). Thank you so much!
> Megan
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6246. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6246>.
>
> Reported by: Megan SenchuK (megan.senchuk@vai.org)
> 12 Mar 18 18:04
>
> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like
> Gecko) Chrome/64.0.3282.186 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
User was happy.
