### ISSUE TITLE
Why do you not have Toxoplasma Gondii listed?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6248]
*Help Desk query collected when no chat operators were online. Follow up required.*

Why do you not have Toxoplasma Gondii listed?

**Reported by:** Fran******* (fran*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/userguide#0123456--10">http://www.wormbase.org/about/userguide#0123456--10</a>
**Browser:** Chrome 64.0.3282.186

**Comment by epaule** [comment]
we only deal with worms, and Toxoplasma is a not one (https://en.wikipedia.org/wiki/Toxoplasma_gondii)
But you will be happy to know that there is a dedicated resource just for Toxoplasma, called ToxoDB (http://toxodb.org) run by our colleagues at EuPathDB.
