### ISSUE TITLE
Inconsistent genomic position listed in Location widget on CDS pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6250]
I noticed that on the page for the CDS Y74C9A.2a:

http://www.wormbase.org/species/c_elegans/cds/Y74C9A.2a#03--10

the "Genomic position" listed in the Location widget is given as:

I:11641..16585

which correctly reflects the start and end of the CDS (not a transcript), as can be seen for the start position in this JBrowse snapshot (note the coordinates of the transcript/UTR start versus the CDS start):

![y74c9a 2a_cdss](https://user-images.githubusercontent.com/611382/37344321-725c81f4-26a0-11e8-89cc-add0a6c30c77.jpeg)

However, on the sister CDS page for Y74C9A.2b:

http://www.wormbase.org/species/c_elegans/cds/Y74C9A.2b#03--10

The Genomic position in the Location widget is listed as:

I:11623..16837

(which reflects the start and end of the entire transcript including UTRs) despite the fact that the CDS actually has start and end coordinates of:

I:15103..16585

as can be seen by this JBrowse snapshot of the locus:

![y74c9a 2_locus](https://user-images.githubusercontent.com/611382/37344668-60cc026a-26a1-11e8-8398-cc1f509d9c28.jpeg)

So, it seems that the correct genomic position is being listed for one CDS of a gene (excludes UTRs and only shows start and end of CDS) while a sister CDS from the same gene shows the genomic position, not for the CDS but for the entire encompassing transcript. Although the GFF indicates the actual start and end of the CDS, the Location widget on the CDS page is not necessarily reflective of that, and getting the actual start and end coordinates is otherwise quite difficult.

**Comment by scottcain** [comment]
Hmm, I don't know how to fix this.  I'm guessing an endpoint is reporting the wrong coordinates.  @a8wright and @sibyl229 do you know?

**Comment by a8wright** [comment]
@chris-grove This ended up being a quick easy fix. Unfortunately this bug was making it so that we were showing the location plus padding. I now have it so the link goes to the location with padding and shows the correct number to the user. It is currently on staging. If correct I will send it out once the current set of Widgets are looked over and approved for release.  Please check it over and let me know what you think.

**Comment by a8wright** [comment]
Also thank you for noticing this.

**Comment by chris-grove** [comment]
@a8wright 
Thanks for looking into it. I still see a problem on staging. For example, the CDS I mentioned above, Y74C9A.2b, is now showing genome coordinates of:

 I:10581..19444

instead of the correct coordinates:

I:15103..16585

https://staging.wormbase.org/species/c_elegans/cds/Y74C9A.2b#03--10

**Comment by a8wright** [comment]
@chris-grove 
I had to check the type of CDS. I believe it is now working. Let me know if you see anything else

**Comment by chris-grove** [comment]
@a8wright 
OK, looks good, thanks. Closing.
