### ISSUE TITLE
Phenotype Graph is not loading on gene pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6251]
It appears that the Phenotype Graph is not loading on gene pages right now:

http://www.wormbase.org/species/c_elegans/gene/WBGene00000898#0b--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00006763#0b--10
http://www.wormbase.org/species/c_elegans/gene/WBGene00003912#0b--10

**Comment by azurebrd** [comment]
Pretty sure it's solr again not working.

**Comment by raymond91125** [comment]
fixed.
