### ISSUE TITLE
  Hello, I am trying to analyze transpo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6253]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am trying to analyze transposon RNA expression from an RNA-seq experiment I did. I'm looking for the best way to download all of the transposon sequences in the C. elegans genome. Ideally, I would also like to be able to match each sequence to its transposon family. Can you please advice me on the best way to do this?<br/>Thank you!</p>

**Reported by:** Adit* (ashu***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by adomingues** [comment]
Sorry for intruding, but maybe this [thread/answer](https://github.com/WormBase/website/issues/5016) is relevant for this issue.

**Comment by chris-grove** [comment]
Hello Aditi,


Apologies for the late reply. The best place to download all transposon transcript sequences is our FTP site:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/sequence/transcripts/c_elegans.PRJNA13758.current.transposon_transcripts.fa.gz


To get the corresponding families, I would recommend using the WormBase advanced query tool:


http://www.wormbase.org/tools/queries


Select the "AQL" option, paste in the following query:


select l, l->gene, l->corresponding_pseudogene, l->corresponding_CDS, l->member_of from l in class transposon


Choose "Plain Text output", and click the "Submit" button. This will return a table of transposon IDs, corresponding genes, other IDs, and family name (see attached Excel file).


You should be able to do any necessary mapping from that data.


Let us know if you have more questions.


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Thanks @adomingues for the assist

**Comment by chris-grove** [comment]
From user:
"""
Thanks for your reply! That list from the advanced query tool was actually really helpful and exactly what I was looking for. I then went ahead and downloaded the “Transposons” track from the wormbase genome browser to find the coordinates/locations corresponding to all of the transposons on that list. Do you think that was the best way to do this?

Thanks again!
"""

**Comment by chris-grove** [comment]
Downloading the "Transposons" track from the genome browser is one way to get the data, but probably the best way is to extract the coordinates from the most recent GFF file(s). Here's the link to the most current GFF3 file on the WormBase FTP site:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/gff/c_elegans.PRJNA13758.current.annotations.gff3.gz

Once you've downloaded the file and unzipped it, you can run the following Unix command to extract the lines referring to transposons:

grep transposon c_elegans.PRJNA13758.current.annotations.gff3 > Transposons_from_elegans_GFF3.txt

I've attached the text file resulting from that grep operation. It will give the genomic coordinates for each transposon gene, CDS, and exon, along with the transposon ID/name.

Let us know if you need something else.

Chris
