### ISSUE TITLE
  Can I get the Bay Area Worm Meeting a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6255]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Can I get the Bay Area Worm Meeting added to the meetings page? It's May 5th, 2018 in Santa Cruz, CA.  Here's a link to the meeting site:<br/>https://sites.google.com/ucsc.edu/bawm2018/<br/>Thanks!  visitor_name</p>

**Reported by:** Jord******* (jwar***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

**Comment by rankishore** [comment]
Posted.
