### ISSUE TITLE
  I also getting a 500 error at: http:/...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6256]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I also getting a 500 error at: http://api.wormbase.org/rest/field/paper/WBPaper00000031/journal<br/>Error Message:<br/>Caught exception in WormBase::Web::Controller::REST->field "cannot locate template journal.tt2 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 1738."</p>

**Reported by:** watt*******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by sibyl229** [comment]
>Sorry about the difficulty. For some legacy reasons, JSON isn’t the default response for the REST APIs. By default it tries to render the content into HTML. To get the desirable behaviour, you have to specifying “content-type=application%2Fjson” as query parameter in the URL.

>For example,
http://api.wormbase.org/rest/field/paper/WBPaper00000031/journal?content-type=application%2Fjson

>Again, sorry about that. Hope this helps,

**Comment by mwatts15** [comment]
It's a paper that doesn't exist (anymore), but that should give a 404 rather than 500.

**Comment by mwatts15** [comment]
OK, that wasn't working 5 min ago...but now it is.
