### ISSUE TITLE
I want some articles on nematode genomics and prot...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6259]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want some articles on nematode genomics and proteomics. Thanks you very much.

**Reported by:** chen****** (7052************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 53.0.2785.104

**Comment by chris-grove** [comment]
Hello Chen,


You may want to try searching PubMed:


https://www.ncbi.nlm.nih.gov/pubmed/


using the following queries:


("Nematoda"[Mesh]) AND "Genomics"[Mesh]


and


("Nematoda"[Mesh]) AND "Proteomics"[Mesh]



Best,


Chris Grove

WormBase

**Comment by sibyl229** [comment]
>Thank you for writing to us. You might also be able to search for papers on the WormBase website using the search box on the top right corner. You will need to update the dropdown menu (next to the search box, which defaults to “Gene”), to either “All” or “Paper”. I attached a screenshot below to show this. This should search through paper titles and abstracts. 

>If you are not able to find what you look for, please feel free to let me know.
![screen shot 2018-03-19 at 12 40 49 pm](https://user-images.githubusercontent.com/1753893/37610419-eb999816-2b75-11e8-8d84-987354f354b9.png)
