### ISSUE TITLE
Tree Display widget broken on Construct pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6262]
Tree Display widget is throwing an error on all construct pages I've checked:

![screen shot 2018-03-19 at 3 13 22 pm](https://user-images.githubusercontent.com/611382/37617003-1e9113f4-2b88-11e8-8c2b-797d8c3a3dfe.png)

https://www.wormbase.org/species/all/construct/WBCnstr00000088#047--10
https://www.wormbase.org/species/all/construct/WBCnstr00000089#047--10
https://www.wormbase.org/species/all/construct/WBCnstr00000023#047--10
https://www.wormbase.org/species/all/construct/WBCnstr00031506#047--10

**Comment by chris-grove** [comment]
Just realized this is an HTTP vs. HTTPS issue. The Tree Display loads fine on HTTP, but not on HTTPS.

**Comment by sibyl229** [comment]
Hi @tharris Trying to access tree view on staging produces an nginx 404 error, instead of a Catalyst 404. https://staging.wormbase.org/tools/tree Is there something needed fixing on the proxy side, probably related to the HTTPS?

**Comment by chris-grove** [comment]
I don't know if it's related but I'm getting Tree Display time-outs on Construct pages:

http://www.wormbase.org/species/all/construct/WBCnstr00010953#25--10

<img width="847" alt="screenshot 2018-03-24 15 52 54" src="https://user-images.githubusercontent.com/611382/37868382-af98e268-2f7b-11e8-9ff8-2236f80d76d8.png">

**Comment by tharris** [comment]
@sibyl229 This is now resolved.

@chris-grove Somewhat related but also somewhat distinct :)  This should be fixed now too, but there seems to be a persistent problem that is killing the service. I will keep on eye on it.

**Comment by tharris** [comment]
I believe this is now resolved.

**Comment by chris-grove** [comment]
@tharris 
Yep! Thanks!
