### ISSUE TITLE
Analysis URL for OMA object

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#6263]
Hi @gw3 

Some test scripts here picked up a change in the URL of the OMA analysis object. It seems that the new URL is added without deleting the old one. This might be minor thing. I'm just letting you know that the values in Datomic may not have a fixed order/precedence, so either one of the values could end up being shown on the website.

![screen shot 2018-03-19 at 5 02 52 pm](https://user-images.githubusercontent.com/1753893/37622504-33ee7812-2b98-11e8-9640-82c37cdea3c4.png)

**Comment by epaule** [comment]
Hi @sibyl229 ,

good catch. We fixed it for WS265 and I have an ACeDB patch file here:
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS264/acedb/PATCHES/oma_url_patch.ace

**Comment by sibyl229** [comment]
Thanks @epaule for the quick fix !
