### ISSUE TITLE
I am looking for a comprehensive list of C. elegan...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6264]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking for a comprehensive list of C. elegans genes with their corresonding genetic positions. I have looked through wormmine and the wormbase FTP to no avail. Can you help with this?  Thank you!!

**Reported by:** Stev******** (sbla************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3</a>
**Browser:** Safari 11.0.3

**Comment by WenChenWormBase** [comment]
Hi Steve,

Have you tried SimpleMine? It is located under the "Tools" menu. We
recently included Genetic Map Position to this tool. If you do not have a
particular list of genes, there is an option to query all *C. elegans*
genes.

https://www.wormbase.org/tools/mine/simplemine.cgi

Wen.


On Mon, Mar 19, 2018 at 5:31 PM, <no-reply@wormbase.org> wrote:

> offline chat I am looking for a comprehensive list of C. elegans genes
> with their corresonding genetic positions. I have looked through wormmine
> and the wormbase FTP to no avail. Can you help with this? Thank you!!
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3
> http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3>
>
> This issue has been assigned ticket number: #6264. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6264>.
>
> Reported by: Steve Blazie (sblazie@ucsd.edu)
> 19 Mar 18 21:31
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Sorry Steve, the link from WormBase to SimpleMine is broken. You may use
this URL to access SimpleMine.

 http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

On Mon, Mar 19, 2018 at 6:14 PM, Wen Chen <wen@wormbase.org> wrote:

>
> Hi Steve,
>
> Have you tried SimpleMine? It is located under the "Tools" menu. We
> recently included Genetic Map Position to this tool. If you do not have a
> particular list of genes, there is an option to query all *C. elegans*
> genes.
>
> https://www.wormbase.org/tools/mine/simplemine.cgi
>
> Wen.
>
>
> On Mon, Mar 19, 2018 at 5:31 PM, <no-reply@wormbase.org> wrote:
>
>> offline chat I am looking for a comprehensive list of C. elegans genes
>> with their corresonding genetic positions. I have looked through wormmine
>> and the wormbase FTP to no avail. Can you help with this? Thank you!!
>>
>> Submitted From:
>>   http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3
>> http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3
>> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000147#0-9g-3>
>>
>> This issue has been assigned ticket number: #6264. Follow progress on our issue
>> tracker <https://github.com/WormBase/website/issues/6264>.
>>
>> Reported by: Steve Blazie (sblazie@ucsd.edu)
>> 19 Mar 18 21:31
>>
>> This question was reported via the web interface at wormbase.org. You
>> can also email us <help@wormbase.org> directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>
>
>
> --
> Wen Chen, Ph.D.
> Curator, WormBase
>



-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Thank you! It seems to be what I’m looking for and I’ll give it a try..
Steve
