### ISSUE TITLE
SimpleMine link broken

### ISSUE THREAD

**Issue by WenChenWormBase** [WormBase/website#6265]
The link from WormBase Tools menu to SimpleMine is broken: 
https://www.wormbase.org/tools/mine/simplemine.cgi

It gives a 404 Pages Not Found error. Possible due to the change to https.

**Comment by sibyl229** [comment]
Hi @WenChenWormBase the production site doesn't support HTTPS on every page yet. Please try visiting any production URL via the HTTP version, like http://www.wormbase.org Does that work for you?

**Comment by WenChenWormBase** [comment]
@sibyl, the actual URL for SimpleMine  http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi works fine. I think the link from WormBase Tools menu: https://www.wormbase.org/tools/mine/simplemine.cgi does not point to the actual SimpleMine URL. Can you check?

**Comment by sibyl** [comment]
Wrong sibyl.

**Comment by sibyl229** [comment]
Sorry Sibyl. You might have to Unsubscribe from the notification using the button in the right sidebar. We can't unsubscribe you once you are mentioned. Sorry!

@WenChenWormBase the URL for SimpleMine used by the site is `/tools/mine/simplemine.cgi`. This is a relative URL, meaning that depends where it is place and the protocol you use to access it (http vs https), it will concatenate with the base URL and become `http://www.wormbase.org/tools/mine/simplemine.cgi` or `https://www.wormbase.org/tools/mine/simplemine.cgi` or `https://staging.wormbase.org/tools/mine/simplemine.cgi`.  

I believe if you visit http://www.wormbase.org and then use the SimpleMine link from there, it should work correctly. Please make sure the address bar shows http://www.wormbase.org **(http without "s")**.  

There is probably a proxy that forwards http://www.wormbase.org/tools/mine/simplemine.cgi to http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

**Comment by WenChenWormBase** [comment]
Thank you for explaining this. Yes when I went to http://www.wormbase.org, the SImpleMine link works.
