### ISSUE TITLE
How do I get the sequence of a worm gene. Is the s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6266]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I get the sequence of a worm gene. Is the sequence an entire one with introns and exons?

**Reported by:** Osak* (osak******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001533#0f9--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001533#0f9--10</a>
**Browser:** Chrome 65.0.3325.162

**Comment by chris-grove** [comment]
Hello Osaka,


From the worm gene's web page, for example:


http://www.wormbase.org/species/c_elegans/gene/WBGene00006763#0g--10


Open up the "Sequences" widget (data box; select from the menu at the left side of the page) and in the "Transcript" column of the resulting table, click on the gray double-helix icon to the left of a transcript name, e.g. "JC8.10a" and you should see a pop-up window with the sequence information available. You will have the option to view unspliced sequence (including exons AND introns), or spliced sequence (including exons, excluding introns). If you're specifically looking for the sequence of the gene (all sequence encompassing all transcripts) you can use the following query in the WormMine data mining tool:


`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.sequence.length Gene.sequence.residues" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.symbol" op="=" value="unc-26"/>
</query>`

To perform this query, go to WormMine (discoverable in the Tools menu on any WormBase page):


http://intermine.wormbase.org/tools/wormmine/begin.do


click on the "QueryBuilder" tab, click on the "Import query from XML" link, and paste the above XML query into the search box. Click "Submit" and on the resulting page, click on the blue edit icon to the right of "unc-26" in the "Query Overview" panel. Replace "unc-26" with the name of your gene of interest, and then click on the green "Show results" button. Download the resulting table in FASTA format and you will have your gene sequence.


I hope that helps.


Chris Grove

WormBase
