### ISSUE TITLE
  I want to use N2 genome as the refere...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6267]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to use N2 genome as the reference genome in the analysis of a mutant by GALAXY. And i do not know how to get it by WormBase. And i can not identify the N2 genome from the CB4856 genome.</p><p>What were you doing? <br />&nbsp;&nbsp;using GALAXY analyse the WGS of a c.elegans mutant .</p>

**Reported by:** 1731***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by Paul-Davis** [comment]
Hi,

Thank you for your email.

The reference genome sequence can be downloaded from our FTP site:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS264/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS264.genomic.fa.gz

I am not entirely sure what input Galaxy requires, but the above file 
contains the current N2 reference that WormBase uses for the C. elegans 
gene set and analysis.

Paul





On 20/03/2018 12:14, no-reply@wormbase.org wrote:
> Question:
>
>   I want to use N2 genome as the reference genome in the analysis of a 
> mutant by GALAXY. And i do not know how to get it by WormBase. And i 
> can not identify the N2 genome from the CB4856 genome.
>
> What were you doing?
>   using GALAXY analyse the WGS of a c.elegans mutant .
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6267. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6267>.
>
> Reported by: 17317822349@163.com
> 20 Mar 18 12:14
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hopefully the user is ok with the genome fa file.
