### ISSUE TITLE
  How can I query the number of gene na...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6268]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I query the number of gene names used for multiple genes?<br/>I'm curious the situation of gene name re-assigning like below.<br/>1. Gene_Name_A was originally used for Gene_A.<br/>2. Gene_A was renamed with Gene_Name_B, <br/>however, Gene_Name_A is still alive as 'other_name' of Gene_A.<br/>3. Gene_Name_A is now used for another Gene_X.</p>

**Reported by:** Jae (jae.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by chris-grove** [comment]
Hi Jae,


Although it isn't a perfect approach, one way to do this is to use SimpleMine to download, for all C. elegans genes, the Public Name and the Other Name. Load the downloaded tab-delimited file into Excel, copy paste all "Other Name" entries to a text file, globally replace all ", " with "<newline>", and then enter the Public Names and the "linearized" Other Names list into a list comparison tool like this one:


http://jura.wi.mit.edu/bioc/tools/compare.php


which yields a list of 188 gene names (attached). Many of these (e.g. "ISK02E2") exist as both the Public Name and Other Name for the same gene, so don't really apply. However, you can find many genes for which the problem exists; for example, see all of the twk-* genes, which gets really messy.


Chris
