### ISSUE TITLE
Sequence widget throwing error on C. briggsae gene page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6270]
![screen shot 2018-03-21 at 3 06 54 pm](https://user-images.githubusercontent.com/611382/37731796-8827502a-2d19-11e8-8c48-26a9f22171f1.png)

http://www.wormbase.org/species/c_briggsae/gene/WBGene00042573#0g--10

**Comment by sibyl229** [comment]
Hi @chris-grove Adam probably already fixed this on staging: https://staging.wormbase.org/species/c_briggsae/gene/WBGene00042573#0g--10

**Comment by chris-grove** [comment]
@sibyl229 
OK, thanks! This should then propagate to the live site soon?
