### ISSUE TITLE
Tree Display widget timing out on C. briggsae CDS page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6271]
On page:

http://www.wormbase.org/species/c_briggsae/cds/CBG24470#09--10

![screen shot 2018-03-21 at 3 21 18 pm](https://user-images.githubusercontent.com/611382/37732492-8e7ee29c-2d1b-11e8-8da5-0336937de20c.png)

**Comment by tharris** [comment]
Resolved (and part of a batch of related issues). Closing.
