### ISSUE TITLE
WB Wiki having login troubles again

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6272]
I'm getting the Cookies notice again when trying to login to the WB Wiki:

![screen shot 2018-03-22 at 12 43 51 pm](https://user-images.githubusercontent.com/611382/37784738-e2241670-2dce-11e8-8955-cbe3c2e3e7a1.png)

@tharris  can you fix this please?

Thanks!

**Comment by tharris** [comment]
Fixed.  Thanks for notice, @chris-grove

**Comment by chris-grove** [comment]
Great! Thanks Todd!
