### ISSUE TITLE
Tree Display error on clone page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6274]
The Tree Display widget is throwing an error on the pDONR P4-P1R clone page:

https://www.wormbase.org/species/c_elegans/clone/pDONR%20P4-P1R#07--10

![screen shot 2018-03-22 at 4 57 47 pm](https://user-images.githubusercontent.com/611382/37798151-443e8c5a-2df2-11e8-91a3-bc8b417c9038.png)

**Comment by tharris** [comment]
Thanks for reporting this @chris-grove. This is now resolved. Please close if satisfactory.

**Comment by chris-grove** [comment]
Yes! Thanks @tharris
