### ISSUE TITLE
  Hi, is there a key somewhere for the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6280]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, is there a key somewhere for the genome browser that tells me what all the different colors mean etc?<br/>Thanks!</p>

**Reported by:** rlan**************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by scottcain** [comment]
Emailed the user:

Yes, both of the genome browsers have “about” sections that describe what colors mean. If you are using JBrowse, mouse over the name of the track and a “dropdown triangle” will appear. Select “about this track” to see the legend. 

If you are using GBrowse, there is a small question mark icon in the track label right next to the name of the track (it’s pretty tiny) that opens a similar window with legend information.
