### ISSUE TITLE
  how do i find an organism phenotype? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6282]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do i find an organism phenotype?</p><p>What were you doing? <br />&nbsp;&nbsp;trying to find out gene names and phenotype and genotype</p>

**Reported by:** soni****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by chris-grove** [comment]
Hello,


You can find gene phenotypes on the gene page. In the WormBase search bar (at the upper right corner of any WormBase page), the default search should be set to search "for a gene". Type or paste in the name of your gene and hit ENTER or select it from the autocomplete options that appear below the search bar. Once you've arrived at a gene page, like this one:


http://www.wormbase.org/species/c_elegans/gene/WBGene00000254#0c-9gb-3


make sure the "Phenotypes" and/or "Phenotype Graph" widgets are open on the page by selecting them from the list of "Page Content" options in the left side panel of the page. If you're looking for genetic information such as alleles and strains, look at the "Genetics" widget.


Let us know if you have any more questions.


Best,


Chris Grove
WormBase
