### ISSUE TITLE
  underastand g-browse,j-browse and bla...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6286]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;underastand g-browse,j-browse and blast/blat of wormbase</p><p>What were you doing? <br />&nbsp;&nbsp;bioinformatics</p>

**Reported by:** shub*** (sshi***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by tharris** [comment]
User contacted:

> GBrowse and JBrowse are graphical tools for exploring genomes.
> 
> BLAST/BLAT are very common tools for searching for sequence similarities.
