### ISSUE TITLE
Can you note if the mutation is a null mutation in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6287]
*Help Desk query collected when no chat operators were online. Follow up required.*

Can you note if the mutation is a null mutation in the description? That will help a lot.

**Reported by:** MM (6465************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/strain/MT534#0234--10">http://www.wormbase.org/species/c_elegans/strain/MT534#0234--10</a>
**Browser:** Chrome 63.0.3239.132

**Comment by chris-grove** [comment]
Hello MM,


WormBase annotates, when available, information about the nature of an allele (e.g. whether it is null or not) on the allele/variation pages. On the strain page for MT534:


http://www.wormbase.org/species/c_elegans/strain/MT534#02--10


To find out if there is information about the nature of any allele in the genotype of the strain, click on the individual allele names in the genotype (in this case "e1500" and/or "e164"). If you navigate to the allele page for e1500:


http://www.wormbase.org/species/c_elegans/variation/WBVar00144047#06--10


You can see in the Phenotypes widget several annotations that report e1500 as a type of gain-of-function allele. If the allele were a null, you would find this information here, in the Phenotypes widget on the allele page. For example, see the page for allele ok709:


http://www.wormbase.org/species/c_elegans/variation/WBVar00091993#06--10


I hope that helps.


Best,


Chris Grove

WormBase
