### ISSUE TITLE
Error attempting to retrieve flanking sequences from ParaSite BioMart

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6291]
ParaSite BioMart is throwing errors when trying to retrieve flanking sequences for genes. Here's a screen recording:

https://www.dropbox.com/s/q15m6gm93tuzwzv/BioMart_flanking_sequence_retrieval_error.mov?dl=0

**Comment by khowe** [comment]
@chris-grove This should now be fixed. Can you confirm at your end and close?

**Comment by chris-grove** [comment]
@khowe 
Yes! Working now. Thanks Kevin!

**Comment by chris-grove** [comment]
This issue has cropped up again:

https://www.dropbox.com/s/9hnpirhvlipx7fc/BioMart_flanking_sequence_retrieval_error2_March_31_2018.mov?dl=0

Sometimes it works, many times it doesn't (throws error).

**Comment by chris-grove** [comment]
Seems to have resolved itself
