### ISSUE TITLE
  I was looking at http://www.wormbase....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6294]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was looking at http://www.wormbase.org/species/c_elegans/gene/WBGene00004114#0g91c6--10<br/>This is the gene page for pqn-25, but it seems like homology section might be from nekl-4.  They are right next to each other in the genome and I wondered if a typo might have caused this (D1044.3 to D1044.8, maybe even some D1044.7 homology is included).  This is just FYI to improve content of wormbase.</p>

**Reported by:** Bob (ohag**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by gw3** [comment]
Some poor gene structures on C. japonica in WormBase appear to have caused some confusion when producing the orthologs of pqn-25. This has now been fixed.

In particular the C. japonica ortholog WBGene00137029 had a structure that has now been split into WBGene00137029 (the Cjp-nekl4 ortholog) and WBGene00303125 (the Cjp-pqn-25 ortholog). This new split structure will appear in release WS266 and should resolve the problems of naming the orthologs.

Many thanks for pointing out this problem.

Gary Williams
WormBase
