### ISSUE TITLE
ParaSite BioMart: GO term autocomplete entry not responding

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6302]
The Gene Ontology term entry portion of the ParaSite BioMart "Query Filters" section is not behaving. The prompt suggests typing in a GO term name to select from the autocomplete to populate the input list of GO terms, but once I start typing I get a spinning wheel with no terms showing up:

https://www.dropbox.com/s/wczo2voit6g0r5o/BioMart_GO_term_entry_bug.mov?dl=0

If I manually enter (or paste) in a GO Term ID (e.g. "GO:0007127"), I can get results, but not using the lookup.

**Comment by khowe** [comment]
We rely on the EBI ontology lookup service for this, and sometimes it gets flaky, even if ParaSite itself is okay. Seems okay at the moment. Closing. Please re-open if it consistently reoccurs.
