### ISSUE TITLE
Sequences widget throwing error on C. remanei pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6303]
For example:

http://www.wormbase.org/species/c_remanei_PRJNA248909/gene/PRJNA248909:FL81_00003#0g--10
http://www.wormbase.org/species/c_remanei_PRJNA248909/gene/PRJNA248909:FL81_00002#0g--10
http://www.wormbase.org/species/c_remanei_PRJNA248909/gene/PRJNA248909:FL81_00001#0g--10

![screen shot 2018-03-30 at 2 32 51 pm](https://user-images.githubusercontent.com/611382/38149126-4cb93192-3427-11e8-92d1-f968fe354519.png)

**Comment by sibyl229** [comment]
Hi @chris-grove this appears to be working on staging. Maybe Adam has fixed this? https://staging.wormbase.org/species/c_remanei_PRJNA248909/gene/PRJNA248909:FL81_00003#0g--10

**Comment by chris-grove** [comment]
@sibyl229 
Yes, it is working on staging. Should I close the ticket then?

**Comment by sibyl229** [comment]
@chris-grove Thanks for doublechecking. I'm closing this one
