### ISSUE TITLE
  If I want to find promoter sequences ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6304]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;If I want to find promoter sequences for homologs of elegans genes in other Caenorabditis species, how do I dump the sequence from the genome view after BLASTing against the other species? I would then refind the homologous gene and take the 5' sequence as the promoter. I'm using a MacBook Pro with Safari as the browser. My PI indicated this was possible, but I can't figure out how to highlight the region of interest and dump it as FASTA. (He uses a Linux OS). </p><p>What were you doing? <br />&nbsp;&nbsp;After BLASTing, I click Genome View and then tried to scroll to highlight the ROI, but instead it simply moves the genome view 5' or 3'. </p>

**Reported by:** Step*************** (svon*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

**Comment by chris-grove** [comment]
Hello Stephen,

You can manually try to extract upstream sequence from genes using the genome browsers, GBrowse or JBrowse, but you can also use WormBase ParaSite BioMart to query for upstream sequences for a list of genes. Here's a screen recording of how to get upstream sequences for the C. elegans gene lin-1 and its C. briggsae ortholog Cbr-elk-2 using those three methods (on a MacBook Pro using Safari):

https://www.dropbox.com/s/3kpgo5ki5izzdmf/Retrieve_upstream_sequence_GBrowse_JBrowse_and_ParaSite_BioMart_March_31_2018.mov?dl=0

Let us know if you have any questions about the procedure.

Best,

Chris Grove
WormBase
