### ISSUE TITLE
  I am looking for genome assemblies fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6308]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am looking for genome assemblies for both N2 and CB4856 strains. Where can I find and download those?</p>

**Reported by:** Davi******** (davi********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by chris-grove** [comment]
Hello Davis,


You can find these two assemblies on our FTP site in this directory:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/


The BioProject number "PRJNA13758" corresponds to the Bristol N2 assembly and "PRJNA275000" corresponds to the Hawaiian CB4856 assembly.


Best,


Chris Grove

WormBase
