### ISSUE TITLE
what is the use of wormbase...?
why wormbase is cr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6311]
*Help Desk query collected when no chat operators were online. Follow up required.*

what is the use of wormbase...?
why wormbase is created...?

**Reported by:** SARA***** (thro********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/analysis/modENCODE_3224_Snyder_TF_FOS-1#0--10">http://www.wormbase.org/resources/analysis/modENCODE_3224_Snyder_TF_FOS-1#0--10</a>
**Browser:** Chrome 49.0.2623.112

**Comment by chris-grove** [comment]
Replied to other related email (same user):
"Hello Saravanan,


WormBase is a genome database for the model organism nematode Caenorhabditis elegans and related nematode species. We catalog nematode genome sequences, the genes that exist within these genomes, and how these genes function in the context of nematode biology. There are thousands of laboratories across the world that study C. elegans and related nematodes to better understand basic biology as well as how our understanding of nematode biology can help us understand human health and medicine.


I hope that helps.


Best,


Chris Grove

WormBase"
