### ISSUE TITLE
  How do i find why a gene causes a cer...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6313]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do i find why a gene causes a certain phenotype.</p>

**Reported by:** Nath******************
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by chris-grove** [comment]
Hello Nathanto,

There are many factors that go into deciphering why a perturbation of a gene might cause a certain phenotype. Do you have a particular gene and phenotype in mind?

Chris Grove
WormBase

**Comment by tharris** [comment]
User contacted; can re-open if necessary.
