### ISSUE TITLE
login on live

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6316]
the google login on the live site throws currently an 400 error 
Error: redirect_uri_mismatch

staging.wormbase.org works

**Comment by tharris** [comment]
I don't have access to the API credentials. @sibyl229, do you?

**Comment by sibyl229** [comment]
Hi @tharris @epaule I added `https://wormbase.org/auth/code/google` to the whitelist for now. But just double checking that we want this url in addition to `https://www.wormbase.org/auth/code/google` (note the `www`)?

@tharris did you receive any email a moment ago from Google cloud platform or something like that?

**Comment by tharris** [comment]
Thanks, @sibyl229 I did receive the invite. I'm only rewriting requests to http, so yes, I do think we want to allow https://www as well.

**Comment by sibyl229** [comment]
Thanks @tharris ! Done.

**Comment by epaule** [comment]
thanks, works now +1
