### ISSUE TITLE
hi, i cat seem to find the phenotype data for dpy-...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6320]
*Help Desk query collected when no chat operators were online. Follow up required.*

hi, i cat seem to find the phenotype data for dpy-5

**Reported by:** Soni* (soni****************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00219918#0-c-3">https://wormbase.org/species/c_elegans/gene/WBGene00219918#0-c-3</a>
**Browser:** Chrome 65.0.3325.181

**Comment by chris-grove** [comment]
Hi Sonia,


As with the bli-4 example we discussed, you can find the phenotypes for the dpy-5 gene on the dpy-5 gene page. You can get there by searching "for a gene" in the search box with the name "dpy-5", going to the gene page, and then turning on the "Phenotypes" widget to see the list of available phenotypes:


https://wormbase.org/species/c_elegans/gene/WBGene00001067#0-c-3


Let us know if you have any trouble.


Chris
