### ISSUE TITLE
phenotype understanding...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6321]
*Help Desk query collected when no chat operators were online. Follow up required.*

phenotype understanding

**Reported by:** tahm**** (tahm*******************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001067#0c-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001067#0c-9g-3</a>
**Browser:** Chrome 65.0.3325.181

**Comment by chris-grove** [comment]
Hello Tahminul,


Can you elaborate on what you're looking for?


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
From user:
"I am looking for the phenotype of silencing the gene bli-4 in C.elegans. There's a number of phenotype there but i'm not sure how the phenotype arises, is it due to mutation, silencing etc?"

**Comment by chris-grove** [comment]
If you look in the "Supporting Evidence" column of the "Phenotypes" table, you will see either "Allele" or "RNAi" above each set of supporting evidence details. Under "Allele" will be listed the names of alleles (usually mutations) such as "s90" which are reported to exhibit the phenotype. Alleles tend to be mutations and tend to be loss-of-function, but some are gain-of-function (equivalent to an overactive gene product). Wherever it says "RNAi", that means gene knockdown or silencing by RNA-interference.

I hope that helps.
