### ISSUE TITLE
Embedded WikiPathways diagram not showing on Process page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6325]
I noticed that a couple of Process pages for which there are WikiPathways diagrams are not displaying the embedded WikiPathway diagram in the "Pathways" widget:

https://wormbase.org/resources/wbprocess/WBbiopr:00000077#07--10

https://wormbase.org/resources/wbprocess/WBbiopr:00000046#07--10

![screen shot 2018-04-05 at 2 54 10 pm](https://user-images.githubusercontent.com/611382/38385970-4f779cde-38e1-11e8-9311-1d721ba89b1b.png)

![screen shot 2018-04-05 at 2 54 16 pm](https://user-images.githubusercontent.com/611382/38385976-545da838-38e1-11e8-9731-691efbf99f68.png)

Seems maybe the image embedding has been disrupted.

**Comment by tharris** [comment]
@sibyl229 Wikipathways links should be updated to https.

https://www.wikipathways.org/index.php/Pathway:WP2578

**Comment by sibyl229** [comment]
Hi @chris-grove the wikipathway view should be working now.

**Comment by chris-grove** [comment]
@sibyl229 
OK, they're now working on staging. Closing.
