### ISSUE TITLE
  Dear Sir/Madam, we are currently need...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6330]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam,<br/>we are currently need few worm stamms for the research.<br/>Would it be possible possible to receive them from you, we are located in Germany (Magdeburg University). And if yes, under which conditions, how  long it would take, and how long we can store them before starting to use? <br/>We would need the following stamms:<br/>1).CX10979 kyEx2865[Psra-6:GCaMP3.0 Pofm-1:GFP] <br/>2) CX11935 kyEx3252[Pstr-2:GCaMP3.0 Pofm-1:GFP].<br/>3) CF512 (fer-15(b26) II; fem-1(hc17) IV)<br/>4) N2<br/>Thank yo in advance,<br/>Sincerely yours,<br/>M.Sokolov</p>

**Reported by:** Maxi********* (soko***************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 OPR/52.0.2871.40

**Comment by Paul-Davis** [comment]
Hi,

Thank you for contacting WormBase. Unfortunately we do not stock or 
distribute samples, but you might like to try the Caenorhabditis 
Genetics Center (CGC) and possibly the labs who created the original 
strains where they are not available from the CGC.

CF512
https://cgc.umn.edu/strain/CF512

N2
https://cgc.umn.edu/strain/N2

CX11935
https://www.sciencedirect.com/science/article/pii/S0092867415001841
cori@rockefeller.edu <mailto:cori@rockefeller.edu>

CX10979
http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1003619
dmferkey@buffalo.edu <mailto:dmferkey@buffalo.edu>

All the best.

Paul

On 06/04/2018 08:48, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Dear Sir/Madam,
> we are currently need few worm stamms for the research.
> Would it be possible possible to receive them from you, we are located 
> in Germany (Magdeburg University). And if yes, under which conditions, 
> how long it would take, and how long we can store them before starting 
> to use?
> We would need the following stamms:
> 1).CX10979 kyEx2865[Psra-6:GCaMP3.0 Pofm-1:GFP]
> 2) CX11935 kyEx3252[Pstr-2:GCaMP3.0 Pofm-1:GFP].
> 3) CF512 (fer-15(b26) II; fem-1(hc17) IV)
> 4) N2
> Thank yo in advance,
> Sincerely yours,
> M.Sokolov
>
> Submitted From:
>   support /tools/support <https://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6330. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6330>.
>
> Reported by: Maxim Sokolov (sokol5555@gmail.com)
> 06 Apr 18 07:48
>
> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/65.0.3325.181 Safari/537.36 OPR/52.0.2871.40
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
