### ISSUE TITLE
I can not open second page of website...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6333]
*Help Desk query collected when no chat operators were online. Follow up required.*

I can not open second page of website

**Reported by:** qizh*** (qizh***********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001402#--3">https://wormbase.org/species/c_elegans/gene/WBGene00001402#--3</a>
**Browser:** Safari 10.1.2

**Comment by tharris** [comment]
User contacted; no response yet.

**Comment by Paul-Davis** [comment]
closing after 2 weeks of inactivity
