### ISSUE TITLE
Journal linking into WormBase not finding correct paper URL?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#6334]
Hi,

We received this feedback about journal linking into WB from Jonathan Ewbank last week.  

Greer et al (https://www.sciencedirect.com/science/article/pii/S0092867415004225) includes "Research data for this article” which has the link
http://www.wormbase.org/get?doi=10.1016/j.cell.2015.04.005

this goes to http://www.wormbase.org/search/paper/j.cell.2015.04.005?redirect=1, ("Sorry, 0 results found for the search j.cell.2015.04.005”)

and not to http://www.wormbase.org/resources/paper/WBPaper00046746

I imagine that this reflects a more general problem.

**Comment by sibyl229** [comment]
Hi @vanaukenk thanks for letting me know about the DOI problem. Indeed it was a general issue, but should be fixed on staging now: http://staging.wormbase.org/get?doi=10.1016/j.cell.2015.04.005 Could you take a look again? Thanks!

**Comment by sibyl229** [comment]
Fixed for WS264.

**Comment by sibyl229** [comment]
Fixed for WS264
