### ISSUE TITLE
  How do I search a Gene Of Interest in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6335]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I search a Gene Of Interest in both N2 and CB4856 (Hawaiian) for location of polymorphisms.  Or how to download the Hawaiian sequence for GOI.<br/>Thanks, Susan</p><p>What were you doing? <br />&nbsp;&nbsp;We want to CRISPR both N2 and Hawaiian -- and want to know will the repair template change the Hawaiian sequence in that site. </p>

**Reported by:** Susa********* (stas****************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by epaule** [comment]
a.) you can just go to your gene of interest and look in the Genetics-> natural variants -> CB4856 section for variations.
which will give you the description and changes

or

b.) you can go to UCSC, connect the WormBase trackhub (My Data -> Public Hubs -> WormBase), pick WBcel235 as genome and put in the gene of interest in the search box
then turn on the Comparative Hub -> Caenorhabditis elegans CB4856 (Hawaii) track
this should give you a graphical display of the N2 - CB4856 alignment from a cactus run

**Comment by epaule** [comment]
if you wan tot download the whole CB4856 genome, it is linked from the C.elegans page: https://wormbase.org/species/c_elegans (Current Assemblies)
