### ISSUE TITLE
I am a new PI at Kindai university in Japan since ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6338]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am a new PI at Kindai university in Japan since April 2018. I was a research associate in Monica Colaiacovo's lab at Harvard Medical School until March 2018. I would like to register my own codes for lab, strain and allele to WormBase. Please help to setup them. Thank you.

**Reported by:** Taka********** (tsai********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/resources/person/WBPerson5686#01--10">https://wormbase.org/resources/person/WBPerson5686#01--10</a>
**Browser:** Safari 11.0.3

**Comment by rankishore** [comment]
From Cecilia: - For lab registration, please see:
How to Register a New Laboratory and Receive Lab, Strain and Allele designations
http://www.wormbase.org/about/userguide/nomenclature#ejd72460ifh385c9agb1lk--10
- Please use the following form:
https://cgc.umn.edu/laboratory/request
- I have updated your contact data to Kindai university in you Person page.
Updates will be available in release WS266 of WormBase. We are currently in version WS263.
