### ISSUE TITLE
  Hi, I used to use the API to access t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6339]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I used to use the API to access the per gene homology data under the structure http://www.wormbase.org/rest/widget/gene/gene_name/homology<br/>but this now returns "301 Moved Permanently". I've found where the nematode orthologs are now, but the blastp table isn't listed. I tried calling it using http://api.wormbase.org/rest/field/gene/gene_name/best_blastp_matches and it is there but it's not in your documentation. You might want to update it.<br/>Best</p>

**Reported by:** Alas********** (acri********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by Paul-Davis** [comment]
closing after 2 weeks of inactivity
