### ISSUE TITLE
I am trying to locate information about the e794 a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6354]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am trying to locate information about the e794 allele in C. elegans.  I have accessed the C. elegans summary, clicked on the "phenotypes section", but have no matches when I enter e794 in the search field.

**Reported by:** Mark******* (harr*****************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001073#0c-9g-10-">https://wormbase.org/species/c_elegans/gene/WBGene00001073#0c-9g-10-</a>
**Browser:** Chrome 65.0.3325.181

**Comment by chris-grove** [comment]
From me to user:
"The most straightforward way to look up information about specific alleles in WormBase is to use the search box to search "for a variation" searching on the name of the allele. This search should direct you right to the allele/variation page for e794:

https://wormbase.org/species/c_elegans/variation/WBVar00143490#0234567--10

The reason for the confusion, I think, is that the allele e794 has not yet been annotated to its corresponding phenotype. I've found the phenotypes in this paper:

Ko FC, Chow KL. A novel thioredoxin-like protein encoded by the C. elegans dpy-11 gene is required for body and sensory organ morphogenesis. Development. 2002 Mar;129(5):1185-94. PubMed PMID: 11874914.

and have curated them to the database, the data for which should become live in our WS266 release, due out on the website in late August 2018.

In the future, if you notice a missing phenotype, please feel free to let us know via email (help@wormbase.org) or go ahead and use our phenotype data submission system:

https://wormbase.org/submissions/phenotype.cgi

We'd greatly appreciate any help in getting our phenotype data up to date."
