### ISSUE TITLE
The C.Briggsae egl-19 gene model appears to be mis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6358]
*Help Desk query collected when no chat operators were online. Follow up required.*

The C.Briggsae egl-19 gene model appears to be missing the last few exons. For example it lacks the very C terminal GGSQEDLLLVTTL sequence. Using the elegans EGL-19 to TBlastN the briggsae sequence it's clear that the GGSQEDLLLVTTL sequence is present in the Briggsae genome.

**Reported by:** Step*********** (nurr**************************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/tools/blast_blat/run">https://wormbase.org/tools/blast_blat/run</a>
**Browser:** Firefox 59.0

**Comment by gw3** [comment]
Hi Stephen,

You are correct.
I've made the change and this will be available in release WS266 of 
WormBase.

The old C. briggsae structure had an expression, measured from RNASeq 
reads, that was a bit less than 10% of your proposed new structure.

I've checked over all of the Caenorhabditids that we curate, comparing 
the egl-19 orthologs, and they all *could* have a minor isoform with the 
final exon coding for a sequence similar to "KVADC", like the C. 
briggsae gene had.
They all express this minor isoform at a level that is less than 10% of 
the major structure ending with GGSQEDLLLVTTL. As we tend not to curate 
minor isoforms that are expressed below 10% of the level of the major 
isoforms in a locus, we will not be curating these minor isoforms.

Thanks
Gary Williams
WormBase
