### ISSUE TITLE
assembly/sequence_collection patch

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6361]
I put a patch to straighten out the assembly data for https://staging.wormbase.org/species/c_briggsae
here: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS264/acedb/PATCHES/brugia_assembly.ace

I would need loading into the website ACeDB database and then the 4 brugia assemblies should nicely show up on the widget in the correct order.

**Comment by tharris** [comment]
Patched (and in production).
