### ISSUE TITLE
There is an error in gbIs4 transgene overview and ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6366]
*Help Desk query collected when no chat operators were online. Follow up required.*

There is an error in gbIs4 transgene overview and contruction details.It is unc-25 promoter and not unc-5.Thanks

**Reported by:** elia*********** (elia**********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/all/transgene/WBTransgene00023182#01342--10">https://wormbase.org/species/all/transgene/WBTransgene00023182#01342--10</a>
**Browser:** Chrome 65.0.3325.181

**Comment by chris-grove** [comment]
Thank you for the correction notice. I've corrected the annotation in our curation database. The change should be visible in the WS266 release of WormBase due in August.
