### ISSUE TITLE
link to image overview

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6368]
Hello Webteam, during the AGR gene expression call it was asked if we do have a landing page for images. Specifically, would it be possible to have a landing page for the image gallery located in the expression widget on the gene page?
Expression pattern images:
https://wormbase.org/species/c_elegans/gene/WBGene00006744#0-g1-3-g
thanks!

**Comment by draciti** [comment]
Hi guys, sorry for pressing but we have the expression call in a couple of hours. Is there a possibility to have a landing page for images? thanks!

**Comment by sibyl229** [comment]
Hi @draciti , I just saw this. It's definitely possible. But we currently don't have a **stable** URL for picture. If you urgently need a URL that works, there is https://wormbase.org/rest/widget/picture/WBPicture0000011096/lightbox . But I think a better solution is to create a page with WormBase header and footer that contains a single widget.

**Comment by draciti** [comment]
Thanks Sibyl,
the interim solution with the URL you proposed should suffice for the time being.
There's no hard deadline yet for the permanent image URL. I'll keep you posted on that but this is something to keep in mind as we'll need it in the future. Keeping this ticket open

**Comment by sibyl229** [comment]
Hi @draciti linking to pictures is up on staging for testing: https://staging.wormbase.org/get?name=WBPicture0000007800&widget=lightbox Please let me know if that's what you are looking for.

**Comment by draciti** [comment]
Hi Sibyl, 
the Gene expression WG revived the picture discussion. Having a landing page to the individual picture is good but would it be possible to have a landing page for the image gallery located in the expression widget on the gene page? i.e. a page that will list all the images for a particular gene

**Comment by draciti** [comment]
<img width="938" alt="screen shot 2019-03-04 at 2 31 13 pm" src="https://user-images.githubusercontent.com/901243/53761155-7ae8d900-3e8a-11e9-8074-099a6567c158.png">

**Comment by sibyl229** [comment]
Hi @draciti we already link to expression widgets, here is an example:
https://wormbase.org/species/c_elegans/gene/WBGene00006744/widget/expression
 
The images are the very top thing in the expression widget. They should be easy to find, when people follows the link to expression widget.

**Comment by draciti** [comment]
ok thanks Sybil! I'll still leave this open and will close once we will finalize the issue at the Alliance

**Comment by draciti** [comment]
DQMs will update the JSON with these specs:
- Update the Add a name/url target in resourceDescriptors.yaml

- Add “gene/expression_images” to BGI crossReferences to indicate which genes get the link
         "crossReferences" : [
            {"id":"NCBI_Gene:184126"},
            {"id":"UniProtKB:Q19151"},
            {"id":"ENSEMBL:WBGene00000003"},
	    {"id":"WB:WBGene00000003","pages":["gene","gene/expression","gene/references", "gene/expression_images"]}
]

**Comment by draciti** [comment]
Living this open until the code is in the JSON

**Comment by draciti** [comment]
great, thanks Michael, closing this
