### ISSUE TITLE
I am unable to download "References" for a the eat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6369]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am unable to download "References" for a the eat-2 gene either as html or csv.  If I download as a csv, the file contains the error message:  ***ERROR***
Couldn't render template "rest/widget.tt2: file error - rest/widget.tt2: not found". 

Thanks.

**Reported by:** Pete******* (okke**********)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001133#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00001133#0-9g-3</a>
**Browser:** Safari 11.1

**Comment by rankishore** [comment]
Confirming that the 'download' function is not working for csv and html.  Selecting CSV, gives a 'This site can't be reached' page, and selecting html leads to a blank page.

**Comment by sibyl229** [comment]
Hi @rankishore Thanks for testing it. I added a new Download button on the references widget and remove the old broken one. https://staging.wormbase.org/species/c_elegans/gene/WBGene00001133#0-9ge-3 Does that work?

I also removed the download html button from the reference widget, since HTML is no longer being produced for that widget. I don't think there is a particular use case for downloading html, when other downloadable formats are generally more suitable.

**Comment by rankishore** [comment]
@sibyl229:  The 'Download all References' button is working now on the link you sent on staging, but do you plan to keep the 'Download' button on the left as well.  I would just keep one or the other.

**Comment by Paul-Davis** [comment]
@sibyl229 just checking out the new download CSV format and it seems some of the abstracts have newline characters which breaks the import process on most sheet applications.

WBPaper00043081 from your example.

Is this a data issue or an export issue? If you could remove any newline when exporting that would fix it.

I will report back to the user that this is being developed and is under testing.

Paul

**Comment by Paul-Davis** [comment]
Reply to user:


Dear Pete,

Just following up on this topic, the web team have been working on fixing the download issues you were having. Formats that are not available have been removed and they have added a new download button to get a CSV file...there is still one issue with newlines in the abstracts but looks like it's almost there

https://staging.wormbase.org/species/c_elegans/gene/WBGene00001133#e--3

Paul

**Comment by sibyl229** [comment]
This fix is live now. But feel free to re-open.
