### ISSUE TITLE
  Hi there How do I cite and reference ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6376]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there<br/>How do I cite and reference (Harvard Style) this website for a report (University level assignment)?<br/>Many thanks!</p>

**Reported by:** Yash*** (yh59***********)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by chris-grove** [comment]
I would suggest you take a look at the "How to Cite" page on WormBase, a link to which is provided in the WormBase footer at the bottom of any WormBase page:


https://wormbase.org/about/citing_wormbase#0123--10


You may wish to cite a particular web page or the database in general; instructions for both are available on the page.


As for referencing in Harvard Style, I would consult the Harvard Style manual for instructions on how to deal with web page and database references.
