### ISSUE TITLE
  How Can I cite the latest release of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6377]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How Can I cite the latest release of wormbase?</p>

**Reported by:** mohi****************
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by chris-grove** [comment]
Please refer to the WormBase "How to Cite" page:


https://wormbase.org/about/citing_wormbase#0312--10-12


to which there is a link in the WormBase footer at the bottom of every WormBase page. See the "Citing a specific release" widget for details. Note that the current release is WS263.
