### ISSUE TITLE
Hi! I'm doing several trials with Mitosox and C.el...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6378]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! I'm doing several trials with Mitosox and C.elegans in flow cytometry. I need some positive control to know mitosox works properly. I read about xanthine and antimycin a, but I don't know what of them are better. Thanks a lot!

**Reported by:** EVa (evas*************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 49.0.2623.112

**Comment by Paul-Davis** [comment]
Dear Eva,

Thanks for contacting WormBase. You question sounds quite technical so 
you might be better asking on the Worm Community Forum 
http://forums.wormbase.org/

Best

Paul


On 25/04/2018 11:49, no-reply@wormbase.org wrote:
> offline chat Hi! I'm doing several trials with Mitosox and C.elegans 
> in flow cytometry. I need some positive control to know mitosox works 
> properly. I read about xanthine and antimycin a, but I don't know what 
> of them are better. Thanks a lot!
>
> Submitted From:
>   https://wormbase.org/#012-34-5 https://wormbase.org/#012-34-5 
> <https://wormbase.org/https://wormbase.org/#012-34-5>
>
> This issue has been assigned ticket number: #6378. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6378>.
>
> Reported by: EVa (evasanher@usal.es)
> 25 Apr 18 10:49
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
