### ISSUE TITLE
ID resolution service

### ISSUE THREAD

**Issue by khowe** [WormBase/website#6382]
Gentle pressure is being applied by GO and the Data Commons to provide an ID resolution service for WormBase ids; e.g.

www.wormbase.org/id_resolve/WBGene000000001
www.wormbase.org/id_resolve/WBRNAi00000001
www.wormbase.org/id_resolve/WBls:00000001

etc. It is currently not possible to solve generically because we re-use identifiers between certain specific classes. e.g. there are two objects in WormBase called "JC8.10a": one is a CDS, the other is a Transcript.

However, can we provide a "best efforts" solution? For example, we could resolve all of our WBxxxxx\d+ ids (straightforward, because the class is trivially inferable from the id itself); and any id that does not fit this pattern could resolve to a search. 

For "problem" classes (e.g. CDS, Transcript, Strain), we could create a separate "resources" in the GO/Commons ecosystem, each with its own prefix (e.g. WB_cds:, WB_trans, WB_strain). This would be an interim solution. A more permanent/long-term solution might be to create WBxxx name-spaces for these classes (using the current ids as Public_names).

**Comment by sibyl229** [comment]
Hi @khowe Yes, this can be done relatively easily by having the existing `/get` endpoint resolve the ID through exact search. I believe this is what the `/get` endpoint is supposed to be doing. I'm taking a look at it today as there is a separate issue related to that endpoint.

**Comment by sibyl229** [comment]
Hi @khowe the ID resolution without class is ready for testing now using the "best effort" approach you described:
- When there is no ambiguity (the query matches the WB ID or public name exactly and unambiguously): https://staging.wormbase.org/get?name=WBGene00015146
- When there is ambiguity: https://staging.wormbase.org/get?name=B0336.6 (same ID used by CDS and expression profile)

I'm not sure what kind of edge case we need to test for? What do you think?

**Comment by khowe** [comment]
Looking really good @sibyl229. I'm not sure there are any edge-cases I can think of.  

Are we looking at WS265 to live with this?

**Comment by sibyl229** [comment]
Thanks @khowe ! Most likely WS264 if nothing goes wrong, but for sure no later than WS265.

**Comment by khowe** [comment]
Hi @sibyl229 . I've been playing around with this, specifically trying to resolve an example of every object type that has its own page. To get that list, I'm looking here:

https://wormbase.org/search

Is this list up-to-date? For example, when I search Picture for "*", I get no hits back.

**Comment by sibyl229** [comment]
Hi Kevin,

We don't have pages for pictures yet, only a Picture widget that contains
information related to the expression.

Are you asking because AGR wants to link to the expression pictures? I plan
to add a new type of page that makes linking to widget easier, instead of
overloading multi-widget page that we currently have.

If you are looking for a different use case, could you tell me what it is?

Thanks,

Sibyl

**Comment by draciti** [comment]
Hi Kevin,
see also #6368

**Comment by khowe** [comment]
Hi @sibyl229 . The IDs for some classes are not resolving to the correct place on staging. e.g. 

https://staging.wormbase.org/get?name=WBbt:0000102

resolves to:

https://staging.wormbase.org/species/anatomy_term/WBbt:0000102

I think that should be:

https://staging.wormbase.org/species/**all**/anatomy_term/WBbt:0000102

**Comment by sibyl229** [comment]
Hi @khowe good catch! The ID resolution for anatomy term is fixed now. https://staging.wormbase.org/get?name=WBbt:0000102

**Comment by sibyl229** [comment]
The ID resolution is live now (WS264). But feel free to re-open if there is any issue.

**Comment by sibyl229** [comment]
Hi @khowe I forgot to mention that the Pictures are searchable now.
