### ISSUE TITLE
Registration of WormBase API(s) with SmartAPI

### ISSUE THREAD

**Issue by khowe** [WormBase/website#6384]
FAO @a8wright 

We are required to register our APIs with SmartAPI, as per this DCPPC ticket:

https://github.com/dcppc/data-stewards/issues/5

Originally, we thought that this was being done at the level of AGR. However, it seems that each individual MOD is also required to register their APIs.

**Comment by a8wright** [comment]
I will have to build this into the build process. I will work on this for the next release

**Comment by khowe** [comment]
The ticket talks about a deadline of 7th May. I don't know how hard this deadline is (I've only just been onboarded with these DC tasks). 

More information here: https://docs.google.com/document/d/1TnuaCkEPOfzhRCS1FHH0E3QS4O5gPV6NwH-W-kscIeQ/edit

**Comment by a8wright** [comment]
Thanks for pointing out the deadline. As far as I know, it is relatively simple to register an API. I will try will add this to my list of things to do next week.
