### ISSUE TITLE
modENCODE JBrowse tracks throwing errors

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6386]
I just noticed that all of the tracks in the "modENCODE > Lieb Group > Transcription and Chromatin" branch of the JBrowse track tree are throwing error messages:

![screen shot 2018-04-27 at 10 28 32 am](https://user-images.githubusercontent.com/611382/39367911-22da4632-4a06-11e8-92d1-fa44fffe39ca.png)

**Comment by chris-grove** [comment]
@scottcain 
It actually looks like ALL modENCODE tracks are throwing errors

**Comment by chris-grove** [comment]
...and all transcription start site (TSS) tracks

**Comment by scottcain** [comment]
Hi @chris-grove this is a problem with AWS S3 and https access.  I fixed it on staging for 264 a few weeks ago and figured it could just update when 264 goes into production, but I should be able to do a hot fix on the production JBrowse if you want.

**Comment by chris-grove** [comment]
@scottcain 
OK, since it looks like WS264 is scheduled to be released to production today, we can wait until that goes live. Thanks!
