### ISSUE TITLE
  How do I check if C.elegans has a gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6388]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I check if C.elegans has a gene found in humans?</p>

**Reported by:** Beck********** (bdie*************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; MDDC; .NET4.0C; InfoPath.3; .NET4.0E; rv:11.0) like Gecko

**Comment by Paul-Davis** [comment]
Dear Becky,

Thank you for contacting wormbase. There are various ways of trying to 
identify the worm Ortholog of a human gene, but it depends what what you 
are starting with.

* If you have the human gene name you could try searching

     Example: ABI1

https://wormbase.org/search/all/ABI1

Then you can see if there is a worm Ortholog

https://wormbase.org/species/h_sapiens/gene/ENSG00000136754#0-6-3

Here you can see that there is a C. elegans gene abi-1

https://wormbase.org/species/c_elegans/gene/WBGene00015146#0-6-3

* If  the above does not work then you could take the Human Protein 
sequence:

Example: ABI1 from UniProt: http://www.uniprot.org/uniprot/Q8IZP0.fasta

This can then be blasted against the C. elegans proteome to find the 
best match.

https://wormbase.org/tools/blast_blat

Blasting against the C. elegans protein set you get the following result 
at the top:

B0336.6 
<https://wormbase.org/species/c_elegans/cds/B0336.6> wormpep=CE29545 gene=WBGene00015146 locus=abi-1 status=C...   163   2e-40
[Alignment] 
<https://wormbase.org/tools/blast_blat/run#hit_anchor_B0336.6_1> [Genome 
View (GBrowse) 
<https://wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758?name=B0336.6:-2995..3235;add=B0336.6+Hits+Hits+5-235,403-466> 
or (JBrowse)] 
<https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CHits%2CClassical_alleles%2CPolymorphisms&loc=B0336.6%3A-2995..3235&addFeatures=%5B%7B%22seq_id%22%3A%22B0336.6%22%2C%22start%22%3A5%2C%22end%22%3A466%2C%22name%22%3A%22Hits%22%2C%22type%22%3A%22match%22%2C%22subfeatures%22%3A%5B%7B%22seq_id%22%3A%22B0336.6%22%2C%22start%22%3A5%2C%22end%22%3A235%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22B0336.6%22%2C%22start%22%3A403%2C%22end%22%3A466%2C%22type%22%3A%22match_part%22%7D%5D%7D%5D&data=data%2Fc_elegans_PRJNA13758&addTracks=%5B%7B%22label%22%3A%22Hits%22%2C%22type%22%3A%22JBrowse%2FView%2FTrack%2FCanvasFeatures%22%2C%22store%22%3A%22url%22%2C%22subParts%22%3A%22match_part%22%2C%22glyph%22%3A%22JBrowse%2FView%2FFeatureGlyph%2FSegments%22%7D%5D> 
[Gene Summary] 
<https://wormbase.org/species/c_elegans/gene/WBGene00015146> 
<https://wormbase.org/rest/widget/protein/WP:CE29545/sequences?colorbox=1>[Protein 
Summary] <https://wormbase.org/species/c_elegans/protein/WP:CE29545>


I hope this helps.

Good luck

Paul








On 28/04/2018 19:17, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I check if C.elegans has a gene found in humans?
>
> Submitted From:
>   support /tools/support <https://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6388. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6388>.
>
> Reported by: Becky Diebold (bdiebol@emory.edu)
> 28 Apr 18 18:17
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 
> 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 
> 6.0; MDDC; .NET4.0C; InfoPath.3; .NET4.0E; rv:11.0) like Gecko
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
