### ISSUE TITLE
  what dose " building UTRs onto the cu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6394]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;what dose " building UTRs onto the curated CDS structure utilising sequence data from a variety of sources“ mean ？</p>

**Reported by:** 1731***************
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by Paul-Davis** [comment]
Thank you for your question.

This really means taking the curated CDS as a template and then 
extending the Transcript (CDS+UTR) following available 
EST/mRNA/RNASeq_Trinity data as well as taking 5' features (SL1/2) and 
3' features (PolyA) to build a better representation of the likely 
transcripts coming from that locus.

I hope that answers your question.

Paul



On 03/05/2018 10:14, no-reply@wormbase.org wrote:
> Question:
>
>   what dose " building UTRs onto the curated CDS structure utilising 
> sequence data from a variety of sources“ mean ？
>
> Submitted From:
>   support /tools/support <https://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6394. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6394>.
>
> Reported by: 17317822349@163.com
> 03 May 18 09:14
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
