### ISSUE TITLE
As the act-2 (beta actin) is my target gene, I wou...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6395]
*Help Desk query collected when no chat operators were online. Follow up required.*

As the act-2 (beta actin) is my target gene, I would like to know the name of other house keeping genes in  C. elegans for qPCR studies..??

**Reported by:** Poor************ (poor********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00000536#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00000536#0-9g-3</a>
**Browser:** Chrome 66.0.3359.139

**Comment by chris-grove** [comment]
My message to user:
"I've compiled a list of papers for which we have annotated qPCR experiments (attached). Here are a few examples of excerpts explaining what housekeeping (or other) genes were used for normalization:

(1)
https://www.ncbi.nlm.nih.gov/pubmed/20855423

In the "qPCR measurements" section of the methods:

"Glyceraldehyde-3-dehydrogenase (GAPDH) was selected as the housekeeping gene as its expression does not change as a result of MeHg treatment."

There are four GAPDH genes in C. elegans you may want to consider:

https://wormbase.org/resources/gene_class/gpd#01--10

(2)
https://www.ncbi.nlm.nih.gov/pubmed/26027928

In the "qRT-PCR" section of the methods:

"We used act-1 (actin) as an internal reference for normalization, and <delta><delta>Ct method was used to analyze qPCR data."

You may also find it useful to post your question on the WormBase Community Forums:

http://forums.wormbase.org/

I hope that helps."
