### ISSUE TITLE
As I would like to use clk-1 gene as reference gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6397]
*Help Desk query collected when no chat operators were online. Follow up required.*

As I would like to use clk-1 gene as reference gene for qPCR studies, I would like to know whether is there any research articles published by using clk-1 as reference gene...?

kindly let me know the answer...

**Reported by:** Poor************ (poor********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00000536#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00000536#0-9g-3</a>
**Browser:** Chrome 66.0.3359.139

**Comment by chris-grove** [comment]
We don't explicitly curate the normalization reference in qPCR experiments that we've annotated, so we cannot query for that specifically. Your best bet is probably to ask your question on the WormBase Community Forums:


http://forums.wormbase.org/

and see if anyone knows the answer to your question.
