### ISSUE TITLE
  Are there microarray scan files (raw ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6398]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Are there microarray scan files (raw data) for this expression cluster:<br/>https://wormbase.org/species/c_elegans/expression_cluster/WBPaper00031662:spaceflight_upregulated#015423--10<br/>I can't find any, but maybe I am not using the interface right...<br/>thanks</p>

**Reported by:** Dan (dani*********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by WenChenWormBase** [comment]
Dear Daniel,

You can download the processed microarray data from WormBase SPELL:
http://spell.caltech.edu:3000/search/dataset_details/54
These are processed data mapped to gene objects.

If you want the dataset in its probe names, you can also download them from
SPELL:
http://spell.caltech.edu/download_index.html
Download this file MrDataProbeCentric.tgz, unzip it and select the dataset
for WBPaper00031662
<ftp://caltech.wormbase.org/pub/wormbase/spell_download/datasets/WBPaper00031662.ce.mr.csv>

WormBase do not keep scan files for Microarray Data. You may contact the
authors of this paper for them.


Wen.


On Fri, May 4, 2018 at 2:21 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Are there microarray scan files (raw data) for this expression cluster:
> https://wormbase.org/species/c_elegans/expression_cluster/WB
> Paper00031662:spaceflight_upregulated#015423--10
> I can't find any, but maybe I am not using the interface right...
> thanks
>
> Submitted From:
>   support /tools/support <https://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6398. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6398>.
>
> Reported by: Dan (daniel.c.berrios@nasa.gov)
> 04 May 18 18:21
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase
