### ISSUE TITLE
Hi! I like to remove E.coli because I am working w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6400]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! I like to remove E.coli because I am working with other bacterias. I made a synchronized, but it did not work. 
I wanted to know which way is more effective to remove the E.coli.
Thanks!

**Reported by:** EVa (evas*************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 49.0.2623.112

**Comment by vanaukenk** [comment]
Dear Eva,

Thanks for writing to WormBase.

There are two methods for cleaning C. elegans of bacterial contaminants cited in the WormBook chapter on Maintenance of C. elegans:

http://www.wormbook.org/chapters/www_strainmaintain/strainmaintain.html#d0e671

Protocols 4 and 5 in Section 6 describe each of these.

If you've tried these methods and are still having trouble, I'd recommend searching the Worm Community Forum for entries on cleaning C. elegans stocks or posting your question if you still need help.

Best,
--Kimberly Van Auken
