### ISSUE TITLE
  Hello Wormbase, Which is the easiest ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6401]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello Wormbase,<br/>Which is the easiest way to download the promoter region (i.e. ~2kb upstream of ATG) for any given gene?<br/>If possible, how to do this in bulk?<br/>Thank you</p>

**Reported by:** Eyle** (ejor******************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by raymond91125** [comment]
You can do single/multiple gene flanking sequence query in Parasite 
BioMart (linked under Tools).

Raymond

On 07/05/18 10:32, no-reply@wormbase.org wrote:
> Question:
>
>   Hello Wormbase,
> Which is the easiest way to download the promoter region (i.e. ~2kb 
> upstream of ATG) for any given gene?
> If possible, how to do this in bulk?
> Thank you
>
> Submitted From:
>   support /tools/support <https://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6401. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6401>.
>
> Reported by: Eyleen (ejorourke@virginia.edu)
> 07 May 18 17:32
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
