### ISSUE TITLE
  download genomic sequences  ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6402]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;download genomic sequences </p>

**Reported by:** rcho***********************
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by vanaukenk** [comment]
Hello,

Thanks for writing to WormBase.

From the Downloads section on WormBase, there are links to download genomic sequences for the different species that we have:

https://wormbase.org/species/all#1--10

Please let us know if you need any additional assistance.

Best,
--Kimberly Van Auken
