### ISSUE TITLE
great job...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6403]
*Help Desk query collected when no chat operators were online. Follow up required.*

great job

**Reported by:** Alva** (alva******************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00003174#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00003174#0-9g-3</a>
**Browser:** Chrome 66.0.3359.139

**Comment by Paul-Davis** [comment]
Thank you for the feedback.


On 08/05/2018 06:05, no-reply@wormbase.org wrote:
> offline chat great job
>
> Submitted From:
>   https://wormbase.org/species/c_elegans/gene/WBGene00003174#0-9g-3 
> https://wormbase.org/species/c_elegans/gene/WBGene00003174#0-9g-3 
> <https://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00003174#0-9g-3> 
>
>
> This issue has been assigned ticket number: #6403. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6403>.
>
> Reported by: Alvaro (alvaroazcfue@gmail.com)
> 08 May 18 05:05
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
