### ISSUE TITLE
Anybody know if there is other pathway different t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6404]
*Help Desk query collected when no chat operators were online. Follow up required.*

Anybody know if there is other pathway different the  insulin/IGF-1 signaling (IIS) pathway and the transcription factors HSF-1 and DAF-16 that activates the hsp-16.2?
And could  HSP-16.2 and HSP-70 act by different pathways?
thank you very much

**Reported by:** Bego** (bego**************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 66.0.3359.139

**Comment by vanaukenk** [comment]
Dear Begona,

Thanks for writing to WormBase.  

To answer your question, I would recommend looking at the Interactions section on the hsp-16.2 ad hsp-70 gene pages to see if there are additional interactions that might indicate these genes are targets of additional signaling pathways.

You might also want to perform queries using Textpresso Central to find C. elegans papers that describe the pathways in which hsp-16.2 and hsp-70 are involved.  

https://textpressocentral.org/tpc/search

To search just the C. elegans literature, on the Textpresso Central page, click on Select Literature, uncheck all of the literatures and then check C. elegans.  If you'd like to also search Supplemental Information, you can click on C. elegans supplementals, as well. 

Please let us know if we can provide any further assistance.

Best,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
thanks very much about the information
It is very useful for me
Best,
Begoña Ayuda
