### ISSUE TITLE
How much tm7355(ogdh-1) C.elegans ?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6407]
*Help Desk query collected when no chat operators were online. Follow up required.*

How much tm7355(ogdh-1) C.elegans ?

**Reported by:** JY L** (a098*****************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/about/userguide#0123456--10">https://wormbase.org/about/userguide#0123456--10</a>
**Browser:** Chrome 66.0.3359.139

**Comment by vanaukenk** [comment]
Hello,

Thank you for writing to WormBase.

Information about ordering the strain containing the ogdh-1(tm7355) is available on this page at the National Bioresource Project:

http://shigen.nig.ac.jp/c.elegans/index.jsp

Please let us know if you need any additional assistance.

Best,
--Kimberly Van Auken
