### ISSUE TITLE
  How do I find sequence of vha-6 promo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6415]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find sequence of vha-6 promoter ?<br/>I am getting wrong sequence from a lab compared to what I find here http://worfdb.dfci.harvard.edu/promoteromedb/</p><p>What were you doing? <br />&nbsp;&nbsp;cloning my gene in front of vha-6 promoter </p>

**Reported by:** Anan* (frie************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by chris-grove** [comment]
There are several ways to retrieve the promoter (upstream sequence) of a gene:


1) In the "Sequences" widget on a gene page, click on the gray double-helix icon next to the transcript for which you'd like to retrieve upstream sequence. One of the sequence viewing options is "view unspliced + UTR + 2000 upstream"; expand that section and you will see 2000 bp of sequence upstream of the start codon (or 5'UTR if it is available). You can copy the sequence from there.


2) Open JBrowse from the vha-6 gene page "Location" widget to view the vha-6 locus. Open the "Reference sequence (DNA)" track, zoom into the promoter region by clicking and dragging along the coordinates listed at the top of the JBrowse view, and click on the "Reference sequence (DNA)" track label. Click on "Save track data" and save the file in FASTA format.


3) Also in JBrowse, turn on the "Curated Genes (protein coding)" track. Right-click (or Cntrl-click) on the transcript for which you would like upstream sequence, click on "View Sequence", click "OK" on the pop-up window, and you should see the "FeatureSequence Viewer" appear. This allows you to view and highlight various sequences with respect to the transcript you clicked on. Specify the amount of upstream sequence to view (in increments of 500bp) and highlight the sequence to view it. You can copy the sequence from within this window.


4) You can use the WormBase ParaSite BioMart tool to retrieve upstream sequence of a gene (or transcript)


All of these steps are demonstrated in the following screen capture video:


https://www.dropbox.com/s/nv46vmc01lqm99j/Finding_the_vha-6_promoter_sequence_May_15_2018.mov?dl=0


At the end of the video, I visit the PromoteromeDB website to retrieve the sequence of the cloned promoter for vha-6, copy the indicated sequence and BLAT it to the C. elegans genome. It appears that the promoter sequence provided at the PromoteromeDB website matches the promoter of vha-6 according to WormBase and the BLAT algorithm.


Let us know if you have any further questions.
