### ISSUE TITLE
  The sequence of the smy-7 gene corres...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6418]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The sequence of the smy-7 gene corresponds to the reverse complement of the actual transcript. The correct sequence should be:<br/>CAGCACGAUUUAACACUCUCAGGGCCUUACAAAAGACCCAGUGAACAAUUUUUGCAAACCCUGUCCUUUCAAGGUCAGGGUA<br/>The evidence for this is based on the fact that the above sequence contains clear features expected for an SmY RNA, whereas the "reverse complement" sequence in Wormbase does not.</p>

**Reported by:** Jona************ (jope**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by vanaukenk** [comment]
Hi Jonathan,

Thanks for reporting this issue with the smy-7 sequence.

Our sequence curators in Hinxton will take a look and let you know if they have any questions.

Best,
--Kimberly

**Comment by gw3** [comment]
Hi Jonathan,

Thanks for pointing this out.
You are quite correct, of course.
The changed structure will be visible in WS266.

Gary Williams
WormBase
