### ISSUE TITLE
cbp-3 as gene name for F40F12.7?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6427]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Daphne, how can I help?</br>visitor_name (visitor_name.cabianca@fmi.ch): Hello,I am working</br>visitor_name (visitor_name.cabianca@fmi.ch): on a gene named F40F12.7. However in a paper from Munkàcsy et al., 2016. They renamed it cbp-3. What name should I use?</br>Chris: OK, thanks for letting us know</br>Chris: It's possible that this name has been approved by WormBase but that it hasn't been made public yet. I will take a look.</br>visitor_name (visitor_name.cabianca@fmi.ch): Ok thanks, I would just like to know what is more correct to use.</br>Chris: Right, I'll have to check</br>visitor_name (visitor_name.cabianca@fmi.ch): if it doesn't appear as changed in the wormbase site should I stick to the longer code?</br>visitor_name (visitor_name.cabianca@fmi.ch): ok</br>visitor_name (visitor_name.cabianca@fmi.ch): should I wait or will you email me?</br>Chris: I just need one minute, so if you can stay on the chat I can get back to you shortly. Otherwise I can email you</br>visitor_name (visitor_name.cabianca@fmi.ch): ok, one minute I can. thanks a lot :)</br>Chris: Sure, you're welcome</br>Chris: OK, I can't find "cbp-3" as a name for F40F12.7 so far, but I don't have access to the primary (updated) gene name database. Once we end this chat, we'll both receive a transcript of this chat. I will then CC you on an email to genenames@wormbase.org so we can get an official word of whether or not "cbp-3" has been approved for F40F12.7. If not, we'll need to have some internal discussions and discuss the name with the authors</br>visitor_name (visitor_name.cabianca@fmi.ch): ok. So basically I wait to hear back from you via email, correct?</br>Chris: Yes</br>Chris: So, I'll end the chat now and email you in a bit, OK?</br>visitor_name (visitor_name.cabianca@fmi.ch): yes. thanks</br>Chris: OK, you're welcome. Talk to you soon

**Reported by:** daph** (daph******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00009595#0d-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00009595#0d-9g-3</a>
**Browser:** Chrome 66.0.3359.139

**Comment by chris-grove** [comment]
The conclusion was that F40F12.7 will indeed acquire the public name "cbp-3"
