### ISSUE TITLE
jbrowse not happy on staging

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6429]
Hi @scottcain,

Just getting the jbrowse is on the web congratulations boiler plate on pages like:

https://staging.wormbase.org/species/c_elegans/clone/WRM061dC06#2--10

Clicking on the failed to load url, does launch a working jbrowe though

P

**Comment by scottcain** [comment]
Hi @Paul-Davis,
I know--it's been unhappy for a little over a week now.  I'm trying to get a new version of JBrowse installed  whose initial load time is MUCH faster, but it is causing problems.  I'm giving myself another week or so before a throw in the towel for 265 and go back to the older JBrowse release.  I've leave this open until I make a decision one way or the other.

**Comment by Paul-Davis** [comment]
Thanks for the update @scottcain
