### ISSUE TITLE
  Dear Wormbase, I have ordered VC40088...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6430]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase,<br/>I have ordered VC40088 (REV1)  from CGC and <br/>It would be a great help if you can provide me the information regarding the mutation (G/A) the location in the gene and in which domain the mutation is located.<br/>Can I use as a control  N2 strain or I should order Wild-type Rev1 stain?<br/>Thanking you,<br/>Regards,<br/>Sharath <br/>PhD student</p>

**Reported by:** shar*** (shar**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by chris-grove** [comment]
By going to the WormBase strain page for VC40088:


https://wormbase.org/species/c_elegans/strain/VC40088#01--10


You can look at the "Variations" table in the "Contains" widget (info box) and search the table for "rev-1". That will pull up the gk455794 allele. Clicking on that allele name will take you to the respective Variation (allele) page:


https://wormbase.org/species/c_elegans/variation/WBVar00746942#052--10


You can see the sequence change details in the "Molecular Details" widget. You can BLAST or BLAT the sequence up to the change to look for where the mutation occurs in relation to the gene structure in one or both genome browsers. If I BLAT the sequence up to and including the G that is mutated, and look at the BLAT hit in GBrowse, I can see that the substitution occurs immediately before the 7th exon (last nucleotide of the 6th intron) and so likely affects splicing (see attached screenshot). You can also visit the rev-1 gene page:


https://wormbase.org/species/c_elegans/gene/WBGene00014066#04--10


and see in the "Genetics" widget, by searching for gk455794 in the "Other alleles" table that the location of the mutation is intronic and that the likely effect in the "Protein effects" column is "Splice site", also confirming the BLAT result. By looking at the BLAT hit in GBrowse with the "Protein motifs" track on, we can see that, although the mutation doesn't likely directly affect the protein sequence, the likely affected splice junction sits inside a domain with identifiers:


SUPERFAMILY:SSF56672

PFSCAN:PS50173

PFAM:PF00817


Searching for these motifs at their respective databases appears to indicate that this domain is likely involved in DNA or RNA polymerase activity and/or DNA repair.


Let us know if you have further questions.

**Comment by chris-grove** [comment]
Also,
As for control strain, I suppose you could use N2 but you would likely need to perform considerable amounts of backcrossing to get rid of all the other mutations in the background. It's unclear to me what you mean by "Wild-type Rev1 strain".
