### ISSUE TITLE
How do I remove the grid at the back?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6431]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I remove the grid at the back?

**Reported by:** Dars**** (dars********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=III:6223491..6230100&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=III:6223491..6230100&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Chrome 66.0.3359.181

**Comment by chris-grove** [comment]
@scottcain 
Do you happen to know if it is possible to remove the background grid in JBrowse?

**Comment by scottcain** [comment]
@chris-grove I am pretty sure it is not possible for a user to directly remove the grid lines, but JBrowse can be "themed" and there are a few that remove the grid lines, like:

* https://github.com/erasche/jbrowse-dark-theme/
* https://github.com/erasche/jbrowse-minimalist-theme/

but I don't think there is a user-facing tool for changing themes (if they were installed, which they currently are not).

It would be at least theoretically possible for me to write a plugin that adds an option to the "View" menu that would toggle the grid lines, and I don't think it would be hard, but obviously that doesn't exist yet either.  I asked in the JBrowse "slack equivalent" if there are any user tools for doing this that I'm not aware of.

**Comment by chris-grove** [comment]
@scottcain 
OK, thanks. Could you reply to the original user email and let them know? Thanks!!

**Comment by scottcain** [comment]
I wrote this to the original user:

Unfortunately, at the moment, there isn't a way to remove the grid for a user.  I'm checking into what it would take to add a menu option to toggle the grid lines.  I'm pretty sure that's possible but need to spend a little time making sure.  If it's easy, it will likely go into the WS265 release.  If it's not easy, well, I guess we'll see how long it takes :-/

**Comment by scottcain** [comment]
It was actually not terribly hard.  I implemented a menu item under the "View" menu that toggles the gridlines on and off.  Barring any wierdness, this should go live with 265.  I'm going to leave this open for at least a few more days to see if anything comes up that I haven't thought of.

**Comment by chris-grove** [comment]
@scottcain 
Great! Thanks! Once you think it's all set, can you email the user? Thanks again!

**Comment by scottcain** [comment]
I spoke to soon: it temporarily removes the grid lines, but as soon as you pan or zoom, they come back.

**Comment by scottcain** [comment]
Emailed this to the user:

It turns out that temporarily removing the grid lines was not terribly difficult.  I implemented a "View" menu item that removes the gridlines until the next reload or opening in another JBrowse window.  Please take a look at https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758 to try it out.  This is the WormBase development site.  Assuming you find this new functionality useful, it should go to the live WormBase site around the end of June or beginning of July.

Out of curiosity, why did you want to get rid of the grid lines, and is this temporary solution sufficient?

**Comment by chris-grove** [comment]
@scottcain 
I had to clear my cache to see the "View" option you've implemented. May be worth pointing out to the user

**Comment by chris-grove** [comment]
Issue resolved. Closing.
