### ISSUE TITLE
I am using the tissue enrichment analysis tool, I ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6433]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am using the tissue enrichment analysis tool, I would like to know how to obtain which genes belong to which tissue, given my analysis. It just tells me 42 expected, I would like to know which ones are those 42 and so on for the whole analysis.
Thank you for your time.
Best regards,
visitor_name

**Reported by:** Fran***** (fran***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide/for_users#1230--10">https://www.wormbase.org/about/userguide/for_users#1230--10</a>
**Browser:** Chrome 66.0.3359.181

**Comment by raymond91125** [comment]
Hi Francesca,

Yes, you can now get the gene-term table by clicking on "Download 
observed gene table here." on the result page.

Thanks.

Raymond
