### ISSUE TITLE
Hi everyone!
I have done a bleaching synchronized ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6438]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi everyone!
I have done a bleaching synchronized and the worm have been arrest at stage L1. Worms have food and they still at L1.

**Reported by:** Eva (evas*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#01-42-6">https://www.wormbase.org/#01-42-6</a>
**Browser:** Chrome 49.0.2623.112

**Comment by epaule** [comment]
we are mostly bioinformaticians here, but you could try to ask on the forum (http://forums.wormbase.org/) which people in the past used to exchange lab protocols and get advise on them.

There is also a WormMethods article on synching worms: https://www.jove.com/video/4019/basic-caenorhabditis-elegans-methods-synchronization-and-observation
But I don't know if it has a FAQ.
