### ISSUE TITLE
modENCODE GFP ChIP tracks in JBrowse need min and max scores adjusted

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6446]
Text taken from email discussion with @scottcain 

"""
Hi Scott,

I was responding to a user's question about UNC-62 protein binding the rho-1 locus when I noticed that GBrowse and JBrowse show substantially different views of the UNC-62 GFP ChIP modENCODE tracks (see attached screenshots). The GBrowse tracks look like what I'd expect, with specific highlighted peaks at particular locations. The JBrowse tracks appear to indicate that UNC-62 just coats the chromosome with an almost completely continuous peak all across the entire locus.

I thought about creating a GitHub ticket, but thought I'd email you first.

Can you fix this or explain what's going on?

Thanks,

Chris
"""

**Comment by scottcain** [comment]
Looking again at that JBrowse screenshot, I notice a lot of red bars, indicating that the max value has been hit for the track.  I have the max and min scores set at 4 and -4, but I have no idea why I picked that.  I suspect if that were changed, the resulting image might be more useful even without the vista plot magic.

**Comment by chris-grove** [comment]
@scottcain 
Yes, it starts to look better if I edit the track configuration such that instead of having:

  "max_score": 4,
  "min_score": -4,

it has:

  "max_score": 30,
  "min_score": 0,

it looks much better. I don't think negative values mean anything (or exist) for these tracks so I think min_score can always be 0.

**Comment by chris-grove** [comment]
Actually, setting max_score to 100 might be better. It would be good if there was a way to make the max_score a set percentage of the maximum value/score for the track.

**Comment by chris-grove** [comment]
<img width="1075" alt="screenshot 2018-05-31 21 44 02" src="https://user-images.githubusercontent.com/611382/40816589-c372745e-651b-11e8-967b-890198be4998.png">

Here's the rho-1 locus with all min_scores set to 0 and max_scores set to 100

**Comment by scottcain** [comment]
I changed the bounds from 0 to 100 for these tracks.  I'm guessing that vista plot glyph is doing some sort of normalization that is changing the values to range from -4 to 4 (maybe using log values?).  I'll ask Peter.

**Comment by chris-grove** [comment]
@scottcain 
Could you adjust the settings similarly for these tracks as well:

<img width="331" alt="screenshot 2018-11-26 15 32 28" src="https://user-images.githubusercontent.com/611382/49040448-96a85900-f190-11e8-8927-ea6dbad8da64.png">

They are also not displaying effectively due to the min/max default display values (-4 and 4).

**Comment by scottcain** [comment]
@chris-grove Done on staging; goes live with 268

**Comment by chris-grove** [comment]
@scottcain 
OK, thanks, those tracks look good on staging.
