### ISSUE TITLE
 Strain request: from WBPaper00032397

### ISSUE THREAD

**Issue by shaydamaher** [WormBase/website#6447]
@Paul-Davis 

Hi Paul, 
I am working with Ranjana to help curate disease models. Can you please create the strains in this paper that are not in Wormbase - these can be found by looking under "Strains" in "Materials and methods" Thank you!
Best,
Shayda Maher

**Comment by Paul-Davis** [comment]
apologies, I have been away on vacation, I will create them asap and detail the strains in this ticket once made.

**Comment by Paul-Davis** [comment]
Created:
```
Strain : KP742 
Strain : VM1268
Strain : ZB1096 
Strain : ZB1102
Strain : ZB1103 
Strain : ZB1104
Strain : ZB1105
Strain : ZB1334 
Strain : ZB1335 
Strain : ZB1336
Strain : ZB1337
```

Unfortunately there were multiple un-named strains and as there was push back about WBStrain IDs I had no way of adding these to the database. We need to come back to the WBStrain discussion at some point.
