### ISSUE TITLE
The previous Gbrowse allows user to select a regio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6448]
*Help Desk query collected when no chat operators were online. Follow up required.*

The previous Gbrowse allows user to select a region and dump the sequence as Fasta file. What is the best way to extract sequence information using Jbrowse especially for intergenic regions? Thanks a lot!

**Reported by:** Tita****** (tita*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/transcript/T08B1.6#06--10">https://www.wormbase.org/species/c_elegans/transcript/T08B1.6#06--10</a>
**Browser:** Chrome 66.0.3359.181

**Comment by scottcain** [comment]
Replied to the user:

Turn on the "Reference sequence (DNA)" track.  Pan or zoom to the region you want to save.  Click on the down pointing arrow in the resulting track's label (mouse over the track label to see the triangle) and select "Save track data" from the dropdown menu.  In the resulting dialog box, "Visible region" should be selected in the "Region to save" section.  Click the "Save" button at the bottom of the dialog box.

Please let us know if you have any other issues or questions about JBrowse.
