### ISSUE TITLE
I would like to have the list of genes annotated a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6449]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to have the list of genes annotated as fertilization downregulated RNA seq (WBPaper45420) in expression. How can I get it through wormbase? Best to click on the expression cluster (similar as for phenotype) and get all the genes. It is not in the supplemental of the paper.

**Reported by:** Alex************ (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00045420:fertilization_downregulated_RNAseq#0154--10">https://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00045420:fertilization_downregulated_RNAseq#0154--10</a>
**Browser:** Safari 11.1

**Comment by chris-grove** [comment]
My email to user:
"""
The genes for this expression cluster can be found in the "Genes" widget on the expression cluster page:

https://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00045420:fertilization_downregulated_RNAseq#03--10

You can find, and turn on, the Genes widget in the left hand side "Page content" panel. This expression cluster has 5,494 genes associated with it. You can copy the list of gene names from the Genes widget. In cases like these, we would like to have a simpler way to retrieve the list of genes, such as providing a link to download a file with all gene IDs and names and/or a link to copy the list of gene IDs to the clipboard. I will create a GitHub ticket to request this feature.

Let us know if you have any further questions.
"""
