### ISSUE TITLE
Is there a way to determine if a gene is embryonic...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6451]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is there a way to determine if a gene is embryonically lethal or the effects on an embryo? genes such as DGK-1, TAG-257, SNT-4, GBA-1? 
Thanks

**Reported by:** Kuna* (kuna****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00000958#0-1c-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00000958#0-1c-3</a>
**Browser:** Chrome 66.0.3359.139

**Comment by chris-grove** [comment]
My email to user:
"""
For a relatively small list of genes like yours, you can visit each respective gene page at WormBase and check the "Phenotypes" and "Phenotype Graph" widget to see if any of the genes exhibit an embryonic lethal or related phenotype:

dgk-1:
https://www.wormbase.org/species/c_elegans/gene/WBGene00000958#0-cb-10

tag-257/gakh-1:
https://www.wormbase.org/species/c_elegans/gene/WBGene00018516#0-cb-10

snt-4:
https://www.wormbase.org/species/c_elegans/gene/WBGene00004924#0-cb-10

gba-1:
https://www.wormbase.org/species/c_elegans/gene/WBGene00016335#0-cb-10

A faster and simpler way to check the allele and RNAi phenotypes for a list of genes is to use our SimpleMine tool:

https://www.wormbase.org/tools/mine/simplemine.cgi

Paste in your list of genes into the search box, select the download or html option for your output, and select the following attributes to show as columns in your output table:

WormBase Gene ID
Public Name
WormBase Status
Sequence Name
Other Name
RNAi Phenotype Observed
Allele Phenotype Observed

Then, click on "query list" and you will get your table showing this data for each gene in your input list.

It looks like none of these genes have an annotated embryonic phenotype.

Let us know if you have any other questions.
"""
