### ISSUE TITLE
2 mutant validation

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6452]
Dear sir/madam, 
    I am a graduate student in China, and our lab bought some mutant from CGC. 
    We wanted to validate these worms, so I searched the Wormbase and found the external and internal Oligo of gk448 and ok195 variation. Your website said they are for sequence-only assay. I dont undersatand what does that mean. Anyway, I run a nested PCR using these Oligo. The electrophoretic result is in the attachment. 
(F1=internal left Oligo; R1=external right Olige; R2=internal right Oligo; 100bp DNA marker is used. )
    Could you please tell me if the electrophretic result shows the right variation, and how to use these Oligos correctly? I would really appreciated your kindness. 
    I am looking forward to your reply.

**Comment by draciti** [comment]
Hello.
 gk448 seems to be a 50,000 basepair deletion according to the CGH paper.  I suggest reading the paper for details and then writing to
Mark Edgley, Lab Manager
edgley@mail.ubc.ca
best,
Paul

**Comment by chris-grove** [comment]
@draciti 
I'd like to leave this open for now, as there are a number of things to be addressed here:

1) WormBase says gk448 is a 355bp deletion; I cannot find info about it being a 50,000 bp deletion. If that is correct we need to update the gk448 molecule details annotated. If it is a 50,000 bp deletion, that could explain why the PCR didn't work, but then why do we have these primers listed at all as they wouldn't be relevant to detection of the deletion as the WB page suggests.

2) I'd like to let the user know what "sequence-only assay" means or let him know that we don't know (I don't know what it means; does anyone know what it means?)

3) I still wanted to look at ok195 to see what might be the problem, if anything

**Comment by draciti** [comment]
ok sounds good, thanks Chris

**Comment by Paul-Davis** [comment]
My reply to the user:

Dear Zhifan,

I think you have interpreted the oligo and PCRs correctly.

I am not sure what "Sequence-only assay" means, but looking in the web code the options are this by default or RFLP so I think it suggests that the details are for a sequencing reaction or PCR.

Looking at the PCR primers for the 2 pairs of PCRs that were conducted to confirm these two deletions I would expect the following sizes should be observed in N2.

gk448:
gk448_external ~2028bp
gk448_internal ~1913bp
gk448 - Curated variant size 355bp (Unfortunately the detail about the source of the confirmed sequence is not in the database).

ok195:
OK195_external ~3208bp
OK195_internal ~2992bp
ok195 - Not sequenced and has not been placed on the reference by WormBase

The difference between the N2 pcr sizes and those you observed in the mutant should give the actual size of the deletion. Unfortunately we do not have this data for the ok195 allele.

I hope this helps

Paul

**Comment by draciti** [comment]
Is this good to close?

**Comment by chris-grove** [comment]
I think so. Closing
