### ISSUE TITLE
  I have a list of 85+ gene names and w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6454]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a list of 85+ gene names and want to get the protein sequences for all of them without clicking on them all individually. I was able to query WormMine to get a spreadsheet with all of the WP protein names, but I'm stuck trying to use the list to get the sequences. FASTA format with all of the sequences as one file would be best if that is possible.<br/>Please let me know what function I should use to get this done.<br/>Thanks for your help!<br/>-Tim</p>

**Reported by:** Tim ***** (tkro************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by chris-grove** [comment]
You can query WormMine to get the protein sequences using a query like this one:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.CDSs.symbol Gene.CDSs.protein.primaryIdentifier Gene.CDSs.protein.symbol Gene.CDSs.protein.sequence.residues" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="C. elegans genes with a cell cycle variant - or descendant - allele phenotype as of WS257"/>
</query>`

On the WormMine "QueryBuilder" tab, click on "Import query from XML", paste in the query above, click "Submit" and then click on "Show results" and you should get your table. To use your own list of genes, upload your gene list via the "Lists" tab "Upload" function, and then when performing the query, change the example list I included in the query above with your own list. Unfortunately, the FASTA download option in WormMine appears to be broken (I will submit a ticket), but you can still download in tab separated values (TSV) format with the sequences.

Alternatively, you can use WormBase ParaSite BioMart. Click on this URL:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart_10&ATTRIBUTES=wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.external_gene_id|wbps_gene.default.sequences.peptide&FILTERS=wbps_gene.default.naive_filters.wbps_gene_id."WBGene00000537,WBGene00000870,WBGene00000871,WBGene00001281,WBGene00001284,WBGene00001413,WBGene00001511,WBGene00001513,WBGene00001998,WBGene00002042,WBGene00003401,WBGene00003594,WBGene00003791,WBGene00003916,WBGene00003917,WBGene00003918,WBGene00003919,WBGene00003920,WBGene00006379,WBGene00006699,WBGene00006974,WBGene00006996,WBGene00010406,WBGene00012004,WBGene00012767,WBGene00013443,WBGene00017132,WBGene00019630"&VISIBLEPANEL=resultspanel

and a BioMart query should load with the same example list of genes used in the WormMine query above. Just go to

"Query Filters" > GENE > ID list limit

and replace the existing list of genes with your own gene list (making sure to adjust the gene name format in the drop down menu). Then click on "Results" and you can download the results in FASTA format.

Let me know if you have any trouble or any questions.
