### ISSUE TITLE
WormMine: FASTA download is buggy

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6455]
This is a bit of an offshoot from help desk ticket #6454 

The FASTA export option in WormMine appears to be quite particular at the moment. For example, if perform the following query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.CDSs.symbol Gene.CDSs.protein.primaryIdentifier Gene.CDSs.protein.symbol Gene.CDSs.protein.sequence.residues" longDescription="" sortOrder="Gene.primaryIdentifier asc"> <constraint path="Gene" op="IN" value="C. elegans genes with a cell cycle variant - or descendant - allele phenotype as of WS257"/> </query>`

and try to export in FASTA format, I get a file "results.fa" that only reads:

"Nothing was found for export"

Strangely, if I simply rearrange the order of the output columns such that only "Protein" class attributes come before the sequence:

`<query name="" model="genomic" view="Gene.CDSs.protein.symbol Gene.CDSs.protein.primaryIdentifier Gene.CDSs.protein.sequence.residues Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.CDSs.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="C. elegans genes with a cell cycle variant - or descendant - allele phenotype as of WS257"/>
</query>`

I get a FASTA output file, with WP:CE IDs in each header (and no other info).

Could we adjust the FASTA download to work under more circumstances? Preferably with a rich header (not just WP CE ID), if those attributes are available?

**Comment by nuin** [comment]
I got the file fine on the first try with "default" parameters.  What browser are you using? I tried with Safari. AFAIK, the download uses mostly JAvaScript, but I might be wrong.


[results.txt](https://github.com/WormBase/website/files/2077921/results.txt)

**Comment by chris-grove** [comment]
I just tried Firefox, Chrome, and Safari on my (admittedly a bit old (late 2009)) iMac and got the "Nothing was found for export" in the file. I'll try on my 2016 MacBook Pro.

**Comment by chris-grove** [comment]
Just tried on my MacBook and got the same result.

**Comment by chris-grove** [comment]
Here's a screen recording:

https://www.dropbox.com/s/v63knynf5zsobdq/WormMine_FASTA_download_bug_June_6_2018.mov?dl=0

Note that I CAN download the *.tsv format and load it into Excel without problem, but when I specifically ask for the FASTA format, I get the file with the error message.

**Comment by nuin** [comment]
I see. The issue is on the column selected for FASTA, I get three options

```
Gene
Gene -> CDS
Gene -> CDS -> Protein
```

As we don't load genomic DNA separated in genes (we load chromosomes only), I guess there are no FASTA to be exported from genes, only from proteins. If you go to columns and select the bottom one, you should get a well-formatted FASTA file.

I guess it's more of a InterMine UI problem than our source.

**Comment by chris-grove** [comment]
Yes, currently there are no sequences for genes, CDSs, or transcripts, so no FASTA would apply.

Right, I figured this was probably an InterMine UI problem.

**Comment by nuin** [comment]
There are sequence for all of these elements (CDS might be a different case) but they are not in FASTA format per-se, as they are extracted from the chromosomes.

**Comment by nuin** [comment]
Just tested and it seems to be working OK.
