### ISSUE TITLE
How can I get genomic sequences?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6456]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I get genomic sequences?

**Reported by:** Mi C************ (jeon**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=V:14948267..14953701&amp;data=data/c_elegans_PRJNA13758">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=V:14948267..14953701&amp;data=data/c_elegans_PRJNA13758</a>
**Browser:** Chrome 66.0.3359.181

**Comment by raymond91125** [comment]
cf. <https://github.com/WormBase/website/issues/6448>

"Turn on the "Reference sequence (DNA)" track. Pan or zoom to the region 
you want to save. Click on the down pointing arrow in the resulting 
track's label (mouse over the track label to see the triangle) and 
select "Save track data" from the dropdown menu. In the resulting dialog 
box, "Visible region" should be selected in the "Region to save" 
section. Click the "Save" button at the bottom of the dialog box."

cheers,

raymond


On 06/06/18 15:13, no-reply@wormbase.org wrote:
> offline chat How can I get genomic sequences?
>
> Submitted From:
>   https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&loc=V:14948267..14953701&data=data/c_elegans_PRJNA13758 
> https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&loc=V:14948267..14953701&data=data/c_elegans_PRJNA13758 
> <http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CClassical_alleles%2CYACs_Fosmids_Cosmids&loc=V%3A14948267..14953701&data=data%2Fc_elegans_PRJNA13758> 
>
>
> This issue has been assigned ticket number: #6456. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6456>.
>
> Reported by: Mi Cheong Cheong (jeongmij@gmail.com)
> 06 Jun 18 22:13
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
