### ISSUE TITLE
ORFeome Project ID link leads to broken page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6460]
On the PCR Product/Oligo page:

https://www.wormbase.org/species/all/pcr_oligo/mv_CAA79269#021--10

The upper right gray box in the Overview widget displays an "ORFeome Project" ID that is hyperlinked. Clicking on the link directs me to:

https://www.wormbase.org/species/all/pcr_oligo/..CAA79269#021--10

which just displays a page (PCR Product/Oligo page???) with broken Overview, Sequence, and Location widgets:

https://www.wormbase.org/species/all/pcr_oligo/..CAA79269#021--10

![screen shot 2018-06-08 at 9 50 54 am](https://user-images.githubusercontent.com/611382/41161621-789e00c4-6b01-11e8-93ed-0bc63c3f2372.png)

I partly expected the link to go to the ORFeome project page for the clone:

http://worfdb.dfci.harvard.edu/searchallwormorfs.pl?by=name&sid=CAA79269

In any case, I think we should link to the ORFeome site, fix the WB page that you are directed to, or remove the hyperlink.

**Comment by sibyl229** [comment]
@chris-grove ORFeome Project ID link should be fixed now.

**Comment by chris-grove** [comment]
@sibyl229 
Looks great! Thanks!!
