### ISSUE TITLE
Gene class page Overview widget only showing first letter of description

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6465]
As pointed out by @timschedl 

Gene class pages are not showing the full description of the gene class, just the first letter. For example:

https://wormbase.org/resources/gene_class/ecr#0--10

<img width="819" alt="screenshot 2018-06-13 22 11 46" src="https://user-images.githubusercontent.com/611382/41392647-ca6bcc98-6f56-11e8-973e-93ff761cc9e7.png">

https://wormbase.org/resources/gene_class/dpy#03--10

<img width="817" alt="screenshot 2018-06-13 22 12 41" src="https://user-images.githubusercontent.com/611382/41392672-f40711a2-6f56-11e8-8446-3f8ed897f71d.png">

**Comment by tharris** [comment]
Can whoever converted this please fix? Originally it marked up the name of the gene in boldface in the description.

**Comment by sibyl229** [comment]
@chris-grove the gene class description is fixed now: https://staging.wormbase.org/resources/gene_class/ecr#0--10

(I didn't convert this widget, but it's an easy fix.)

**Comment by chris-grove** [comment]
@sibyl229 
OK, looks good. Thanks! Closing.
