### ISSUE TITLE
  Dear Wormbase support,  first of all,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6468]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase support, <br/>first of all, thank you for running this great website! <br/>I am trying to get a list of all genes and the assigned operon for each (CEOP#). <br/>How could I get such a list?<br/>I could not find this in SimpleMine, although one can "query all c elegans" which is already very nice to get a gene list with all phenotypes (allele and RNAi). <br/>Maybe it would be possible to add an operon column here containing either the CEOP identifier or "none"? <br/>Another cool thing would be to add three more columns with GO terms (biological process, cellular component and molecular function). <br/>Best regards, <br/>Jonathan <br/>graduate student Rajewsky lab, Berlin. </p>

**Reported by:** Jona************** (jona****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by raymond91125** [comment]
Hi Jonathan,

In WormMine (linked under Tools), there is a template query of Gene->Operon.

<http://intermine.wormbase.org/tools/wormmine/templates.do>

Cheers,

Raymond

**Comment by chris-grove** [comment]
User is satisfied with WormMine solution. Closing.
