### ISSUE TITLE
How to I download the fasta sequencing from a sele...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6471]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to I download the fasta sequencing from a selection in jbrowse?  I could select and write click in old version, but now don't know how to do it.  Thanks!

**Reported by:** Ashl********* (afra****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:16254009..16256727&amp;data=data/c_elegans_PRJNA13758">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:16254009..16256727&amp;data=data/c_elegans_PRJNA13758</a>
**Browser:** Safari 11.1.1

**Comment by scottcain** [comment]
Replied via email:

Hi Ashley,

Turn on the "Reference sequence (DNA)" track.  Pan or zoom to the region you want to save.  Click on the down pointing arrow in the resulting track's label (mouse over the track label to see the triangle) and select "Save track data" from the dropdown menu.  In the resulting dialog box, "Visible region" should be selected in the "Region to save" section.  Click the "Save" button at the bottom of the dialog box.

Please let us know if you have any other issues or questions about JBrowse.
