### ISSUE TITLE
daf-12 and daf-3 gene page Interactions widget not loading

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6473]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;About five minutes ago (at 8:50 PM MT), the Interactions tabs for all genes have stopped loading and have been showing an error message:<br/>"Sorry! An error has occured.<br/>Let us know<br/>Gateway Time-out"<br/>Why is that?</p><p>What were you doing? <br />&nbsp;&nbsp;I was looking through various genes in WormBase to determine whether they interact with elt-2.</p>

**Reported by:** Yaw ************* (yaw.***************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by chris-grove** [comment]
Apologies for the error. At this point I cannot replicate the error, so it may have been a temporary glitch. Are you still experiencing the issue? If so, could you let us know which web browser (and version) and operating system (and version) you are using?


Thanks

**Comment by chris-grove** [comment]
Will reopen if necessary

**Comment by chris-grove** [comment]
From user:
"Thanks so much for the response. It's actually the Interactions section for specific genes - daf-12 and daf-3 - that's not working. I loaded the Interactions section for elt-7 and it's working. I attempted the same tasks with Firefox and had the same outcomes.

I am using the newest and most updated versions of Windows 10 and Google Chrome (most updated as of today, Thursday 6/21/18) on my Asus laptop.

Thanks again! Much appreciated!"

**Comment by chris-grove** [comment]
My response:
"Ah, OK, I can replicate the problem now that I try those genes specifically. Thanks for reporting the problem. We will look into it and try to get a fix ASAP.

In the meantime, you can check these gene pages on our staging site, although be aware that our staging site is not stable and may be prone to sudden changes:

https://staging.wormbase.org/species/c_elegans/gene/WBGene00000908#08--10
https://staging.wormbase.org/species/c_elegans/gene/WBGene00000899#08--10

For some reason the Cytoscape network view won't load on the staging site, but the interactions table does load, so hopefully that helps."

**Comment by chris-grove** [comment]
@sibyl229 @a8wright 
This issue may be related to #6445 
For what it's worth, for daf-3, daf-12 the Interactions widget won't load on production, but will load the interactions table in the widget on staging (but not the Cytoscape viewer).

For sem-5, the entire widget loads on staging.

**Comment by chris-grove** [comment]
Actually, I take back the "the entire widget loads on staging" for sem-5; Now I cannot get the Cytoscape view to load for sem-5 on staging either

**Comment by sibyl229** [comment]
Hi @chris-grove , I made some fixes on the staging site that could explain the difference between staging and production. The timeout setting was what's preventing the graph view of sem-5 to load. I just asked Todd to extend that. It should load now. https://staging.wormbase.org/species/c_elegans/gene/WBGene00004774#0-8-10

**Comment by chris-grove** [comment]
@sibyl229 
OK, great! Looks good on staging for all three genes. I will close both tickets.

Thanks!!

**Comment by chris-grove** [comment]
My follow up:
"Our web team has made some adjustments and now all of the interaction data should display for daf-3 and daf-12 on our staging site. The website will update to this fixed version by the end of next week or the week after."
