### ISSUE TITLE
Gene_class Summary Page Overview display issue.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6476]
On the gene class summary pages

https://wormbase.org/resources/gene_class/unc#03--10

It seems that the description is being truncated to the 1st letter rather than displaying what's in the database.

![gene_class issue](https://user-images.githubusercontent.com/717707/41773427-f80ca2a8-7613-11e8-8409-bcbead7b3a53.png)

Paul

**Comment by chris-grove** [comment]
Duplicate of #6465
