### ISSUE TITLE
  Hello, I found one of my previous ema...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6477]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I found one of my previous email addresses (dorishs@yahoo.com) on the following page, under the "Previous Addresses" section:<br/>https://www.wormbase.org/resources/person/WBPerson11829#0--10<br/>Please is it possible to remove this email address (dorishs@yahoo.com) from your database?<br/>Thank you.<br/>Best regards,<br/>visitor_name</p>

**Reported by:** Hsia*********** (hsie********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by chris-grove** [comment]
I've removed the old email address from your profile. Note that you may update your information from your WBPerson page:

https://www.wormbase.org/resources/person/WBPerson11829#0123--10

Just click on the "Add or update your contact information" and adjust the information.

There's a bit of a time delay between submitting data and the changes being reflected on the website, so the change will be visible in the WS267 release of WormBase, due out on the website in late October.
