### ISSUE TITLE
visitor_name (visitor_email): Hi! Chris: Hello vis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6484]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi!</br>Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_email): I'm trying to build a primer for my gsy-1 mutant C. elegans</br>Chris: OK</br>visitor_name (visitor_email): I'm looking at the tm6196 allele page for the gsy-1 gene, and it's giving me the sequence and highlighting the mutation in red</br>visitor_name (visitor_email): But I downloaded the UTR unspliced sequence word document, and couldn't find that deleted sequence in that document</br>Chris: OK, where did you download the sequence from? The allele page or the gene page?</br>visitor_name (visitor_email): The gene page</br>Chris: OK, one thing to keep in mind here is that the deleted sequence as reported on the allele page may be in the reverse complement orientation to that of the gene's orientation</br>Chris: so you may want to search for the reverse complement of the red-highlighted sequence</br>visitor_name (visitor_email): Okay can I try that real quick and get back to you?</br>Chris: Yes, sure thing</br>Chris: no hurry

**Reported by:** Lizz** (eafl********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar01474080#02-45-3">https://www.wormbase.org/species/c_elegans/variation/WBVar01474080#02-45-3</a>
**Browser:** Chrome 67.0.3396.87

**Comment by chris-grove** [comment]
Olark chat service crashed (second time today).

My follow up email to user:
"Apologies, it looks like the Olark chat service we use is having connection issues, so I'm emailing you instead. I was able to get a match of the deleted sequence to the gsy-1 transcript once I converted the deleted sequence on the allele page to its reverse complement.


Let me know if you have any other questions or concerns."
