### ISSUE TITLE
  Might there be an error on the sequen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6490]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Might there be an error on the sequence for variant gk939307? I ordered strain VC40211, amplified the gene and sent for sequencing. WormBase lists the variant as atTgtccctc... but when I sequenced it I saw instead atgTtccctc... (insertion 1-2 base over).</p>

**Reported by:** joon***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by Paul-Davis** [comment]
Thank you for sending the error report, I will investigate and get back 
to you.

Paul
[Sequence Curation]



On 30/06/2018 22:43, no-reply@wormbase.org wrote:
> Content Correction
>
>   Might there be an error on the sequence for variant gk939307? I 
> ordered strain VC40211, amplified the gene and sent for sequencing. 
> WormBase lists the variant as atTgtccctc... but when I sequenced it I 
> saw instead atgTtccctc... (insertion 1-2 base over).
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6490. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6490>.
>
> Reported by: joonha.lee@yale.edu
> 30 Jun 18 21:43
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 
> Firefox/60.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
After looking at the data we have stored in the database and how the 
variation is being mapped it seems that there is a display error in the 
website code for the molecular details widget with the inserted base 
being put to the left of the correct position as you say. I will 
escalate this with the web team so that we can get this fixed asap.

Paul


On 02/07/2018 10:44, Paul Davis wrote:
>
> Thank you for sending the error report, I will investigate and get 
> back to you.
>
> Paul
> [Sequence Curation]
>
>
>
> On 30/06/2018 22:43, no-reply@wormbase.org wrote:
>> Content Correction
>>
>>   Might there be an error on the sequence for variant gk939307? I 
>> ordered strain VC40211, amplified the gene and sent for sequencing. 
>> WormBase lists the variant as atTgtccctc... but when I sequenced it I 
>> saw instead atgTtccctc... (insertion 1-2 base over).
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #6490. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/6490>.
>>
>> Reported by: joonha.lee@yale.edu
>> 30 Jun 18 21:43
>>
>> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 
>> Firefox/60.0
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Web team,

After tracking the details through from the flanking sequences we have stored in the database, mapping and the gff3 that is produced, it seems that the data is correct, but maybe the webcode isn't displaying the molecular details correctly. This might be because it is an insertion where the gff3 spec requires the same co-ordinate to be reported and the feature would be to the right of this co-ordinate. As this is a +ve strand feature it was easy to see that the code must be displaying to the left, possibly to try and deal with -ve strand example?

```
Geneace      gaccaacaacccaagctgcaacatgTtccctcactgccgatccaccagcc
WT display   gaccaacaacccaagctgcaacat-gtccctcactgccgatccaccagcc
+  display   gaccaacaacccaagctgcaacatTgtccctcactgccgatccaccagcc
```

gff3

```
I	Million_mutation	insertion_site	2562670	2562670	.	+	.	variation=WBVar01475053;public_name=gk939307;strain=VC40211;insertion=T;consequence=Frameshift
```

Graphical representation

![6490_support](https://user-images.githubusercontent.com/717707/42165786-fa54962a-7e00-11e8-97c8-d3496125bed7.png)

**Comment by scottcain** [comment]
I just spent several minutes trying to figure out what JBrowse was doing wrong, but I'm pretty sure it's right (especially since you wrote that the molecular details widget is getting it wrong :-)  @sibyl229 when you get back from today's Canadian holiday, please take a look at this.

**Comment by khowe** [comment]
@scottcain @sibyl229 yes, JBrowse is correct. My guess is that the widget code (which I believe is using the Bio::SeqFeature::Store DB populated from the GFF3)  is not interpreting the GFF3 semantics for insertion sites correctly. I always have to look it up to remind myself:

"For zero-length features, such as insertion sites, start equals end and the implied site is to the right of the indicated base in the direction of the landmark."

**Comment by Paul-Davis** [comment]
Ah, sorry @scottcain I was merely using Jbrowse to highlight the problem :~

**Comment by tharris** [comment]
I believe this is an off-by-one problem constrained to the -ve strand. @a8wright  can you take a look at this when working the molecular details widget?

**Comment by a8wright** [comment]
Yes -  I will make sure this gets corrected while I continue to work on the molecular details widget

**Comment by tharris** [comment]
IIRC there are also some unit tests. Perhaps these need to be fixed.

**Comment by raymond91125** [comment]
@a8wright bump

**Comment by a8wright** [comment]
@scottcain and @Paul-Davis I have added a fix for this bug on staging. I have checked through other insertions by comparing to JBrowse. I believe the insertion sites are correct with the change that I made. I am going to check through a few more this morning but every insertion I have checked so far was wrong and is correct with the fix. I would like to release this asap. If one or both of you could confirm the fix I will roll it out right away.

**Comment by a8wright** [comment]
The fix for this is currently on production.
