### ISSUE TITLE
Hello,  Would it be possible to access a database ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6491]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,  Would it be possible to access a database with all temperature sensitive mutants described so far?  Many thanks!

**Reported by:** blan*************** (blan*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00000875#0l-9gc-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00000875#0l-9gc-3</a>
**Browser:** Chrome 67.0.3396.99

**Comment by chris-grove** [comment]
I am now querying the database to get you a list of all alleles/mutations that have been annotated as temperature sensitive by WormBase, along with the genes they are known/predicted to affect.

I will send it to you shortly.

**Comment by chris-grove** [comment]
Here it the list. Note that some alleles affect multiple genes and so exist in multiple rows in the table. Also, these are mostly C. elegans alleles, but there are some non-elegans alleles as well.

Let is know if you have any questions.
