### ISSUE TITLE
  Hello WormBase, In the Sequencing Fea...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6492]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello WormBase,<br/>In the Sequencing Features of gene nceh-1, WormBase indicates a predicted binding site for mir-239. However, I couldn't confirm this on the website of miRbase (miranda). But if I compare the sequences of mature mir-239 and nceh-1 3'UTR, there does exist 8nt-complementary sequences between the two. Thus, would you please let me know where did you cite the original work of the binding site prediction? If possible, could you please send me a copy of that work?<br/>Thanks a lot!!!!<br/>Alice</p>

**Reported by:** Alic******* (szha*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Alice,

Thank you for your email. It appears that this data was provided to 
WormBase by Anton Enright's group using the miRanda program a long time 
ago. This information is in the gbrowse track information, but pretty 
tricky to find.

miRanda predictions -- indicated in red -- are the predicted target 
sequences for microRNA genes, provided by Anton Enright's group using 
the miRanda program.

Why this prediction is not being reported by miRbase I am not sure. It 
could be that this was low scoring and has been removed from the set 
they choose to display? I would be cautious of the data point and 
validate before doing anything costly.

I hope this helps

Paul

On 02/07/2018 23:51, no-reply@wormbase.org wrote:
> Feature Request
>
>   Hello WormBase,
> In the Sequencing Features of gene nceh-1, WormBase indicates a 
> predicted binding site for mir-239. However, I couldn't confirm this 
> on the website of miRbase (miranda). But if I compare the sequences of 
> mature mir-239 and nceh-1 3'UTR, there does exist 8nt-complementary 
> sequences between the two. Thus, would you please let me know where 
> did you cite the original work of the binding site prediction? If 
> possible, could you please send me a copy of that work?
> Thanks a lot!!!!
> Alice
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6492. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6492>.
>
> Reported by: Alic******* (szha*******************)
> 02 Jul 18 22:51
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
