### ISSUE TITLE
Is it possible to programmaticaly (e.g. using the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6493]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is it possible to programmaticaly (e.g. using the restAPI) fetch gene sequences with the case preserved for exons (upper) and introns (lower) as per the sequence pop-up widget? If not is there somewhere I can download all the C. elegans genes with the preserved case?

**Reported by:** Dami************* (dami************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/for_developers#423015--10">https://wormbase.org/about/userguide/for_developers#423015--10</a>
**Browser:** Firefox 60.0

**Comment by raymond91125** [comment]
To be considered as helped?
