### ISSUE TITLE
JBrowse embedded image not loading; link to Jbrowse not loading

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6494]
This may be part of what's being discussed on the Slack "Genome Browser" channel, but I'm not sure.

1) The embedded JBrowse image in the gene page Location widget is not loading

2) The link to JBrowse from the Location widget on the gene page is opening a new tab and resulting (after some time) in a 404 Not Found error

**Comment by scottcain** [comment]
Hi @chris-grove Actually, I was unaware of the problem on production, so thanks for pointing it out.  There has been a lot of monkeying with the proxy configuration, so I suspect that there might be a problem associated with it.  @tharris can you please take a look?

**Comment by scottcain** [comment]
Fixed with a minor proxy tweak.  Thanks @tharris !
