### ISSUE TITLE
What are  the Mutant strain of myo-2 and col-19 ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6497]
*Help Desk query collected when no chat operators were online. Follow up required.*

What are  the Mutant strain of myo-2 and col-19 genes ?

**Reported by:** Dila*** (dila***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 67.0.3396.99

**Comment by chris-grove** [comment]
The best place to look for strains for a gene is in the "Genetics" widget on the respective gene page. For example, for myo-2:


https://www.wormbase.org/species/c_elegans/gene/WBGene00003514#04--10


In the "Alleles" tables you can find alleles and polymorphisms affecting myo-2 and the strains that contain them. Note that most (all?) of the strains listed in the "Strains" section contain the myo-2 gene (or a portion of it) in a transgene, for example myo-2-promoter::GFP fusions.


Similarly for col-19:


https://www.wormbase.org/species/c_elegans/gene/WBGene00000608#04--10


You can check the Caenorhabditis Genetics Center (CGC):


https://cgc.umn.edu/


to see if the strains are available to order.
