### ISSUE TITLE
  Hello, I am looking to find informati...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6498]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am looking to find information about mRNA expression levels during aging in c. elegans. Specifically for the ulp-2 gene, <br/>but would also love to know if there is access/information about whole genome expression screens during aging.<br/>Thank you,<br/>visitor_name,<br/>PhD graduate, Tel-Aviv University, Israel.</p><p>What were you doing? <br />&nbsp;&nbsp;trying to look at ulp-2 expression levels during development but couldn't find it in aged worms.</p>

**Reported by:** Liri********** (liri***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by raymond91125** [comment]
Hi Lirin,

If you go to the gene page of ulp-2 
<https://wormbase.org/species/c_elegans/gene/WBGene00006737#-1-3> in the 
Expression widget, under Expression Clusters, you'd find some 
age-related expression studies in which ulp-2 was affected.

Hope that is helpful to you.

Cheers,

Raymond
