### ISSUE TITLE
  get the pmid from the WBPaper in a fi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6500]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;get the pmid from the WBPaper in a file (as in for all papers in the database)?</p>

**Reported by:** zach********* (zach*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by vanaukenk** [comment]
Dear Zach,


Thanks for writing to WormBase.


We maintain a paper xrefs file at this URL:


http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/generic.cgi?action=WpaXref



Each WBPaper that we have in WormBase is mapped in this file to any other external ids we have in our curation database, e.g. pmid, doi, etc.


Let me know if you have any questions about the xrefs or need any additional help.


Best,
--Kimberly Van Auken
