### ISSUE TITLE
Dear all, the DOI link given in 
https://www.wormb...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6503]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear all, the DOI link given in 
https://www.wormbase.org/resources/paper/WBPaper00027709#0--10 seem to point to a wrong publication. The correct DOI link is: 
https://www.molbiolcell.org/doi/10.1091/mbc.e05-12-1120

**Reported by:** Ralf*********** (baum******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/resources/paper/WBPaper00027709#0--10">https://www.wormbase.org/resources/paper/WBPaper00027709#0--10</a>
**Browser:** Firefox 61.0

**Comment by vanaukenk** [comment]
Dear Ralf,

Thanks very much for your email.

I've updated the doi in our curation database and the corrected version will appear in the WS267 WormBase release.

Best,
--Kimberly Van Auken
