### ISSUE TITLE
  I would to download a file of dead ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6505]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would to download a file of dead genes associated with the gene they have merged into.  I would like to be able to do this periodically to get the most up to date list of dead genes.</p>

**Reported by:** Loui************ (gevi*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by epaule** [comment]
Wen:
You can try SimpleMine under the Tools menu.
Choose to query for all C.elegans genes, and choose WormBase Status.

MP:
there is also a file on the FTP site containing all live and dead gene ids for a species of a release:
as example http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS264/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS264.geneIDs.txt.gz
