### ISSUE TITLE
 Server Error: 500 at  tools/epcr/run   
  Error M...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6509]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/epcr/run">tools/epcr/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "Could not connect to database acedb _WS264, host: ip-10-0-0-22" </p>

**Reported by:** norr******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/epcr/run">/tools/epcr/run</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14

**Comment by tharris** [comment]
Fixed.
