### ISSUE TITLE
Question about Jbrowse: is there a glossary/legend...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6512]
*Help Desk query collected when no chat operators were online. Follow up required.*

Question about Jbrowse: is there a glossary/legend that explains the color codes? i.e. when look at the "curated genes" track what's the difference between purple, green and gray? Thanks

**Reported by:** Alex************* (dele*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=V:9343121..9344400&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=V:9343121..9344400&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Firefox 61.0

**Comment by scottcain** [comment]
This reply was sent via email:

Hi Alex,

All tracks have a description, though looking that the Curated Genes track description, I noted that it's a little out of date, so I'll update straight away.  You can find find description by hovering your mouse over the track name, clicking on the down arrow that appears to the right of the name, and selecting "About this track" from the menu.

The purple and blue-green transcripts are protein coding and on the forward and reverse strands respectively.  Grey transcripts are either non-coding transcripts of a protein coding gene or transcripts of a noncoding gene.
