### ISSUE TITLE
Hello! I'm wondering how to determine the last tim...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6513]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello! I'm wondering how to determine the last time a gene page was edited. Specifically the sequence information for CDK-2 is different than much of my records and i'm wondering when this information was changed. Want to make sure it's not a data entry mistake on my part! Thanks so much!

**Reported by:** Joce*** (jhav***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 67.0.3396.99

**Comment by epaule** [comment]
In the Sequences section you can click on the curator comments and see any comments that were added during curation. It usually includes comments from the last curation.
From the timestamps it looks like the a and b isoforms were last changed on the 27th of February 2017.
