### ISSUE TITLE
Hello - I am trying to load a .gff file as a track...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6514]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello - I am trying to load a .gff file as a track but nothing seems to show up. Is there a "template" gff file that I could use to see if I have formatted mine incorrectly?

Thank you
Mehul

**Reported by:** Mehu****** (mehu****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse-simple/?data=data/c_elegans_PRJNA13758&amp;loc=V:10461259..10473216&amp;tracks=Curated_Genes,Classical_alleles,Polymorphisms&amp;highlight=">https://wormbase.org/tools/genome/jbrowse-simple/?data=data/c_elegans_PRJNA13758&amp;loc=V:10461259..10473216&amp;tracks=Curated_Genes,Classical_alleles,Polymorphisms&amp;highlight=</a>
**Browser:** Chrome 67.0.3396.99

**Comment by scottcain** [comment]
Emailed the user; closing until/unless they email back:

I don't really have a template, though I created a (very) simple GFF (attached) and it worked fine.  The most important things I can think of are to make sure that the chromosome names in the first column exactly match what WormBase uses (so "I" and not "chrI") and that you use tabs to separate the nine columns.  If these two items don't do the trick, please feel free to send me a sample of what you've got and I'll make further suggestions.

Good luck,
Scott
