### ISSUE TITLE
  Is it possible to access an earlier v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6515]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is it possible to access an earlier version of the tissue enrichment tool? <br/>I had analyzed a few sets of genes on the tool sometime around September of 2017. Those results drove my research into a new direction the findings of which I am preparing for publication. I had taken snapshots of the charts but didn't download high quality images. I have re-run the analysis on the current tool and the terms are slightly different and the chart format is also slightly different. It would be ideal if I could re-run the analysis on the early version and cite the appropriate WormBase release.<br/>Thank you for your help.</p><p>What were you doing? <br />&nbsp;&nbsp;tissue enrichment tool</p>

**Reported by:** Kiyo************ (kray*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by raymond91125** [comment]
Hi,

We've installed a one-off enrichment tool for you based on WS261 data 
here <http://caprica.caltech.edu/~raymond/cgi-bin/tea.cgi>. WS261 fits 
your time frame the best.

Please note that it may be not be maintained for too long and let us 
know if you have any questions.

Cheers,

Raymond


On 13/07/18 16:31, no-reply@wormbase.org wrote:
> Feature Request
>
>   Is it possible to access an earlier version of the tissue enrichment 
> tool?
> I had analyzed a few sets of genes on the tool sometime around 
> September of 2017. Those results drove my research into a new 
> direction the findings of which I am preparing for publication. I had 
> taken snapshots of the charts but didn't download high quality images. 
> I have re-run the analysis on the current tool and the terms are 
> slightly different and the chart format is also slightly different. It 
> would be ideal if I could re-run the analysis on the early version and 
> cite the appropriate WormBase release.
> Thank you for your help.
>
> What were you doing?
>   tissue enrichment tool
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6515. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6515>.
>
> Reported by: Kiyomi Kaneshiro (kraye02@gmail.com)
> 13 Jul 18 23:31
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
