### ISSUE TITLE
  Good afternoon, I am working with pep...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6516]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good afternoon,<br/>I am working with peptide sequences of Spirocerca lupi, a nematode whose genome has not been sequenced. I have all proteins that this worm excreted/secreted and were sequenced by LC-MS/MS. We have many peptides, however, only a small fraction of them have a hit using Max-Quant. Does Worm Base have a database for proteins to which I can "blast" my peptides? <br/>Many thanks for your help,<br/>visitor_name<br/>PhD Student<br/>Prof. Gad Baneth's Lab<br/>Hebrew University of Jerusalem</p>

**Reported by:** Alic******** (alic************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by chris-grove** [comment]
You may have better luck with our WormBase ParaSite Blast tool:

http://parasite.wormbase.org/Tools/Blast

You have the option to perform peptide/protein BLAST search against all genomes (100+) in the WormBase ParaSite database. Alternatively, if you just want to BLAST against WormBase "core" genomes, you can use the standard WormBase BLAST tool:

https://wormbase.org/tools/blast_blat

My other colleagues may have more specific suggestions.
