### ISSUE TITLE
hello,
What do the relative positions of genes rep...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6518]
*Help Desk query collected when no chat operators were online. Follow up required.*

hello,
What do the relative positions of genes represent?

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:2387955..2388819&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:2387955..2388819&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Chrome 67.0.3396.99

**Comment by chris-grove** [comment]
Could you clarify what it is you're asking? Are you referring to the genome browser view? The horizontal positions of the genes in any of the gene tracks indicates the position of the gene physically on the respective chromosome. Vertical positioning of gene glyphs is not biologically meaningful, but is rather a result of trying to fit several genome features (with labels) into the same visual span on the screen.


Let us know if you have further questions.
