### ISSUE TITLE
  Good morning,  My name is Bairon Hern...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6519]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good morning, <br/>My name is Bairon Hernández, i'm bioinformatician and i'm looking RNAi datas from C.elegans. Do you have a file with RNAi from C.elegans? Can you help me?<br/>Greetings!</p>

**Reported by:** Bair************ (bair************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by raymond91125** [comment]
Hi,

You might take a look at our phenotype association file in this ftp 
folder <ftp://ftp.wormbase.org/pub/wormbase/releases/WS265/ONTOLOGY/>.

Cheers,

Raymond
