### ISSUE TITLE
unmap gff between releases

### ISSUE THREAD

**Issue by cyaguesa** [WormBase/website#6520]
Hi ! According to the [wormbase wiki](http://wiki.wormbase.org/index.php/Converting_Coordinates_between_releases), Gary Williams developped for wormbase a tool to liftover coordinates backward called _unmap_gff_between_releases.pl_. It would be very useful for me, but this tool is not available on [the provided link](ftp://ftp.sanger.ac.uk/pub2/wormbase/software/Remap-between-versions/), only its forward counterpart, _remap_gff_between_releases.pl_, is. I tried it, thinking that you may have changed the script so that it can do both backward and forward liftover, but it doesn't. Is there a reason why the script is no longer available ? Can you put it back ? Thank you !

**Comment by cyaguesa** [comment]
After a bit of searching, I found a copy of the script on [github](https://github.com/SchwarzEM/ems_perl/blob/master/wormbase/unmap_gff_between_releases.pl). I'm still worried that there is a good reason why the script is no longer officialy provided by wormbase and that it is somehow buggy. Any info on that ?

**Comment by gw3** [comment]
Hi,

We no longer provide this 'unmap_gff_between_releases.pl' script because 
we try to encourage users to map their data onto the latest assembly of 
the reference genome.

I am not aware of any bugs in the 'unmap' script.
I am also not aware that it has ever been used since I wrote it.

The latest assembly (WBcel235) has not changed since the WormBase 
release WS235 in January 2013, so any data using a release since then 
does not require a change to their coordinates.

Gary Williams

**Comment by cyaguesa** [comment]
Thanks for your answer. 

> I am not aware of any bugs in the 'unmap' script.

It totally worked for me after a bit of tweaking on the chromosome naming convention, thanks !

> I am also not aware that it has ever been used since I wrote it.

While searching for the script, I found that it was used at least in [this publication](https://genome.cshlp.org/content/21/2/255).

> we try to encourage users to map their data onto the latest assembly of the reference genome.

I understand your point. In my case, I mapped RNA-seq reads on the ce10 (WS220) assembly because I wanted to upload my data on an online genome browser that only supported WS220. Then the project evolved and I had to use the WS262 gene annotation for compatibility with other data... I ended up keeping my reads aligned to the WS220 genome, with the WS262 gtf annotation mapped back to WS220 thanks to your script. It is perhaps suboptimal, but it allows me to keep my online genome browser while using the more recent annotation. Do you think it is ok to do that ?
