### ISSUE TITLE
hello, can i know the promoter in the gene locatio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6522]
*Help Desk query collected when no chat operators were online. Follow up required.*

hello, can i know the promoter in the gene location image?

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00021427#04-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00021427#04-9g-3</a>
**Browser:** Chrome 67.0.3396.99

**Comment by raymond91125** [comment]
Hi,

It may be a communication's issue but it appears that you're trying to 
learn about molecular biology in general. Our help desk is not the best 
place for that purpose as we are focused in providing information about 
nematode genomics. You may benefit greatly by consulting with a textbook 
or online courses.

When you have more specific questions about C elegans genes, please do 
not hesitate to make that clear.

Sincerely,

Raymond
