### ISSUE TITLE
  How do I download a list (e.g. .csv f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6524]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I download a list (e.g. .csv file) of all the WILD strains of all species?</p>

**Reported by:** Dave****** (davi***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by chris-grove** [comment]
I think at the moment the only way to get this list is by querying our underlying database. Could you tell me what information you'd like to include in your table for each wild strain? Here's our strain class schema for reference:


https://www.wormbase.org/tools/schema/run?class=Strain&view=expand


Once you let me know which attributes you're interested in (e.g. name, species, etc.) I'll query out the table for you.

**Comment by raymond91125** [comment]
Dave is probably interested in Strain and Species.

On this page <https://wormbase.org/tools/queries/run>, tick AQL and 
paste in the box

"select strain, species from strain in class Strain where exists_tag 
strain->wild_isolate, species in strain->species"

and Submit.

As of WS265, there are 1477 strains. The Plain Text output is tab 
delimited, I believe.

raymond


On 19/07/18 13:00, Grove, Christian A. (Chris) wrote:
>
> Hi Dave,
>
>
> I think at the moment the only way to get this list is by querying our 
> underlying database. Could you tell me what information you'd like to 
> include in your table for each wild strain? Here's our strain class 
> schema for reference:
>
>
> https://www.wormbase.org/tools/schema/run?class=Strain&view=expand
>
>
> Once you let me know which attributes you're interested in (e.g. name, 
> species, etc.) I'll query out the table for you.
>
>
> Best,
>
>
> Chris Grove
>
> WormBase
>
> ------------------------------------------------------------------------
> *From:* no-reply@wormbase.org <no-reply@wormbase.org>
> *Sent:* Thursday, July 19, 2018 11:51:11 AM
> *To:* help@wormbase.org
> *Cc:* david.fitch@nyu.edu
> *Subject:* [wormbase-help] How Do I ...?: How do I download a list 
> (e.g. .csv f... (Dave Fitch)
> How Do I ...?
>
>   How do I download a list (e.g. .csv file) of all the WILD strains of 
> all species?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6524. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6524>.
>
> Reported by: Dave Fitch (david.fitch@nyu.edu)
> 19 Jul 18 18:51
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
