### ISSUE TITLE
Human proteins missing from the Homology widget for C. elegans and C. briggsae

### ISSUE THREAD

**Issue by khowe** [WormBase/website#6527]
As reported by @sibyl229 on Slack, in WS266 (currently on staging), human proteins are missing from the Homology widget. 

This is due to a *data bug* in the WS266 Acedb database (also in Datomic) whereby the ":" is missing from the human protein names. e.g.

Protein : "CE32785"
Pep_homol "ENSEMBLENSP00000431399" wublastp_human 13.301029995663981 28 185 327 482 Target_species "Homo sapiens"

Should be:

Protein : "CE32785"
Pep_homol "ENSEMBL:ENSP00000431399" wublastp_human 13.301029995663981 28 185 327 482 Target_species "Homo sapiens"

 It is straightforward for us to issue an AceDB patch to fix this bug. And luckily the Homology widget is not yet being served from Datomic!

@sibyl229 @tharris if the patch is applied to the website copy of the WS266 Acedb, can the cache be flushed for these widgets before the release goes live in about 4 weeks?

**Comment by tharris** [comment]
Simply applying the patch should be sufficient — there is no cache yet for WS266.

**Comment by khowe** [comment]
Patch now included in the release folder on the EBI FTP site:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS266/acedb/PATCHES/fix_missing_colon_from_ensembl_ids.ace.gz

**Comment by sibyl229** [comment]
Thank you @khowe !

**Comment by tharris** [comment]
@sibyl229 to fix this, I had to adjust the user of the block.wrm files to user acedb and restart the acedb docker container (`docker restart CONTAINER`). After that I could `saceclient localhost 2005` and `Parse /path/to/file`. Do note that the path is uses the symbolic acedb path established when starting the docker container (`/acedb/wormbase` mapped to `/u/l/w/acedb/wormbase`). Thus: 

`acedb> Parse /acedb/wormbase/patch.ace`

**Comment by sibyl229** [comment]
@tharris thanks! I will try those step next time.

I'm closing the ticket as the original problem is fixed: https://staging.wormbase.org/species/c_elegans/protein/CE32785#0394--10
