### ISSUE TITLE
  I'm trying to use the chIP data in se...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6529]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm trying to use the chIP data in sequence features, and it's all coming up as a track-rendering error. This was also happening earlier in the day today. </p>

**Reported by:** Cole********* (ctmu******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

**Comment by scottcain** [comment]
Reply sent, leaving it open until fixed:

Hi Coleen,

There is a problem with GBrowse's modENCODE data that I'm aware of and working on.  I anticipate it will be fixed some time tomorrow.  In the meantime, you can I suggest you take a look at the modENCODE tracks on JBrowse?

Scott

**Comment by scottcain** [comment]
Another email sent to the user, now that GBrowse modencode data are fixed:

Hi again Coleen,

I believe I fixed the ChIP tracks in GBrowse if you would prefer to use it instead.
