### ISSUE TITLE
I am doing some simple annotation on some C. elega...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6531]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am doing some simple annotation on some C. elegans RNASeq data.  Is there a file I can download that has both the WB...... and corresponding gene names?

**Reported by:** Larr***** (larr******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 67.0.3396.99

**Comment by nuin** [comment]
User contacted, I am closing it now, might re-open if needed.
