### ISSUE TITLE
  I will like to know the homologue of ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6533]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I will like to know the homologue of protein kinase C gene in C. elegans. <br/>Also, what mutant strains have loss of function of protein kinase C gene</p>

**Reported by:** ayod****************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by raymond91125** [comment]
If you search "for All" "protein kinase c" at WormBase, you will find a 
gene class:PKC <https://wormbase.org/resources/gene_class/pkc#01--10>. 
Follow the genes and you will find more information that may interest 
you. Let us know if you get lost.

Thanks.

Raymond

**Comment by raymond91125** [comment]
FYI, tpa-1 gene encodes two isoforms homologous to PKC.
This is 'tpa' gene class.

Thanks,
Jae
