### ISSUE TITLE
  Dear Wormbase, I am trying to identif...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6534]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase,<br/>I am trying to identify some small RNA genes. There is a paper from 2002 that places them on chromosome 3 with 5′ start positions 3172520, 3162782, 3822816 and 4011623, respectively. There are no gene names. However, if I search for those location in gbrowser now, they can't be found. Is there a way to locate them?<br/>All the best<br/>Jenny</p>

**Reported by:** Jenn*********** (j.m.*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by gw3** [comment]
Hi Jenny,

Unfortunately, the elegans assembly was in constant turmoil in the early 
years, including 2002.

Our remapping data starts with release WS74 (February 2002).

I've picked a trio of dates to illustrate the problem with remapping 
from this early period.
The first column is your "2002" coordinate from your paper.
The next three columns are the 2002 location mapped to current (post 
WS235)  coordinates assuming the "2002" locations were from either WS74 
(Feb 2002), WS82 (July 2002), or WS90 (Nov 2003).

Paper        WS74        WS82            WS90
3172520    3100701    3176992    3172531
3162782    3090963    3167254    3162793
3822816    3751009    3827299    3822838
4011623    3939819    4016110    4011648

So, unless your paper can identify the release that was used to produce 
the coordinates that they report, there will be a large uncertainty in 
the position.

Sorry I can't help more at this stage.
Gary Williams
