### ISSUE TITLE
References widget empty on cep-1 gene page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6535]
On the cep-1 gene page:

https://www.wormbase.org/species/c_elegans/gene/WBGene00000467#0ej--10

The References widget is not displaying anything despite there being 189 references in the Tree Display:

![screen shot 2018-07-26 at 4 27 14 pm](https://user-images.githubusercontent.com/611382/43286675-cdda85fc-90f0-11e8-9130-ad8d76575318.png)

**Comment by chris-grove** [comment]
Just a note: I discovered this because linking to the "Literature" for cep-1 from the Alliance website:

https://test.alliancegenome.org/gene/WB:WBGene00000467#summary

Leads to this URL with no info:

https://www.wormbase.org/species/c_elegans/gene/WBGene00000467/widget/references

**Comment by sibyl229** [comment]
Hi @chris-grove The reference display issue is fixed both live and on staging:
https://www.wormbase.org/species/c_elegans/gene/WBGene00000467#0ej--10
https://www.wormbase.org/species/c_elegans/gene/WBGene00000467/widget/references
Thanks for writing about the issue.

**Comment by chris-grove** [comment]
@sibyl229 
OK, great thanks! I see the fix on staging, but cannot see the fix on www/production, even after clearing my cache and doing a hard refresh of the page

**Comment by sibyl229** [comment]
Hi @chris-grove sorry, my mistakes. I double checked the code deployed on production. These changes has made it there yet. It will be released when WS266 in around two weeks.

**Comment by chris-grove** [comment]
@sibyl229 
OK, sounds good. I'll close the ticket then. Thanks!
