### ISSUE TITLE
published recently an article with
PMID: 29912629 ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6536]
*Help Desk query collected when no chat operators were online. Follow up required.*

published recently an article with
PMID: 29912629 DOI: 10.1080/15548627.2018.1474312
Not getting the link to add it to publications.
Thanks

**Reported by:** Meen***** (drdw***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/person/WBPerson5584#013--10">https://wormbase.org/resources/person/WBPerson5584#013--10</a>
**Browser:** Chrome 67.0.3396.99

**Comment by vanaukenk** [comment]
Dear Meenakshi,


Thank you for writing to WormBase.


Your paper was included in our curation database last month and will be visible in WormBase with the WS267 release, available on our production site in mid-October.


Best,
--Kimberly Van Auken
