### ISSUE TITLE
JBrowse track filter not working

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6537]
It seems that the JBrowse track filter is not working. Here's a screen recording:

https://www.dropbox.com/s/jwvla7j5y129arn/JBrowse_track_filter_bug_July_30_2018.mov?dl=0

**Comment by scottcain** [comment]
Hi @chris-grove Thanks for this report.  It seems that the minor fanciness that adds the wormbase logo and the "looking for old modencode data" link broke the filter functionality.  I'll remove it from production while I sort out what's going on.

**Comment by scottcain** [comment]
@chris-grove pretty sure this is fixed now on staging and production, though you'll probably going to need to clear your cache to see the fix.  I'm so confident I'm closing--you can reopen if you run into an issue.

**Comment by chris-grove** [comment]
@scottcain  OK looks good. Thanks!
