### ISSUE TITLE
Question about promotion of annotation files to 'current' on ftp site

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#6538]
Hi,

I was looking at some GO annotation reports generated by the GO Consortium and this led me to checking which annotation files on our ftp site are 'current' vs 'development'.

Looking here:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/go_annotations/

it seems that the annotations on the gene pages for WS265 reflect what is in the 'development' files on the ftp site, while the files labeled 'current' still reflect WS264 annotations.

This looks to be similar for other data types, e.g. interactions.

Am I looking in the right place for the new files, and if I am, what is the procedure for updating annotations files on the ftp site to reflect what is 'current' vs 'development' wrt the release dates for production and staging?

https://wormbase.org/about/release_schedule

Thanks.

**Comment by vanaukenk** [comment]
@tharris - can we close this ticket or is there anything else you need/want to do?  Thx.

**Comment by tharris** [comment]
I don't believe there is anything that remains to be done, and the issue can be closed.
