### ISSUE TITLE
  How can I see upstream sequence of ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6540]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I see upstream sequence of gene more than 4000 bp?</p><p>What were you doing? <br />&nbsp;&nbsp;I was looking for promoter sequence of gene. I need upstream sequence more than 4000bp.</p>

**Reported by:** saeb****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36

**Comment by chris-grove** [comment]
There are several options within WormBase to get 4kb upstream sequence of a gene:

Crude method 1) You can open GBrowse for your gene, click and drag your cursor along the region you'd like to retrieve sequence for, and select "Dump selection as FASTA":

https://www.dropbox.com/s/s0vinmal11ex7t0/GBrowse_upstream_sequence.mov?dl=0

Crude method 2) You can open JBrowse for your gene, select the region of interest (and zoom in), and download the sequence from the "Reference sequence" track:

https://www.dropbox.com/s/pnieyj3bd6jmml5/JBrowse_upstream_sequence1.mov?dl=0

More precise method 1) Use the JBrowse track "Curated genes (Protein coding)" to select upstream sequence in increments of 500bp (make sure to right-click on the gene in the track and select "View sequence"):

https://www.dropbox.com/s/1uepj0746ql0e0t/JBrowse_upstream_sequence2.mov?dl=0

More precise method 2) Use WormBase ParaSite BioMart to retrieve upstream sequence of a specified length:

https://www.dropbox.com/s/3qpaji7nl399pul/WormBaseParaSiteBioMart_upstream_sequence.mov?dl=0

Please let us know if you have any questions.
