### ISSUE TITLE
Hello,
Im looking to access sequence info based on...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6544]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
Im looking to access sequence info based on Gene ids. 
I have tried this with nDi.2.2.2.t00004 on your search engine before and it returned all the info on this gene and I was able to collect it. but now it says no reults found for the same. Could you please help!

**Reported by:** Shab*** (sjaw*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/search/gene/nDi.2.2.2.t10521">https://wormbase.org/search/gene/nDi.2.2.2.t10521</a>
**Browser:** Chrome 67.0.3396.99

**Comment by epaule** [comment]
we have moved Dirofilaria over to parasite.wormbase.org
there the search will get you to the respective gene.
