### ISSUE TITLE
Schema display throwing error

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6547]
I can load the class entry page for the Schema Display page, but as soon as I enter a class and click on "Change" I get the following (or similar) error message:

![screen shot 2018-08-03 at 4 35 21 pm](https://user-images.githubusercontent.com/611382/43664582-62f90154-973b-11e8-8897-4dce4ea07a44.png)

**Comment by tharris** [comment]
Fixed. Problem related to new production instances.
