### ISSUE TITLE
  How do I select a region in JBrowse a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6550]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I select a region in JBrowse and export it as a FASTA sequence? I used to be able to do this by highlighting a region within a specific track in GBrowse but I'm not able to figure out where I need to make the selection in JBrowse (without simply zooming in to that region). <br/>Thanks!!</p>

**Reported by:** Beck* (andr*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by scottcain** [comment]
Replied to the user:

Hi Becky,

At the moment, the way to get fasta from JBrowse is this:

1. Zoom to the region for which you want sequence.
2. Turn on the "reference sequence (DNA)" track.
3. Mouse over the label of the track (in the upper left corner of the track)
4. Click on the down arrow on the right end of the track to expose a menu
5. Select "Save track data" from the menu.
6. Click "save" in the dialog box that opens up.

Look for the fasta file in your browser's default download location.

Sorry that it's currently 6 steps--I'm working on a way to make a "shift-mouse drag" give you a menu that would have "download sequence" as an option when you highlight a region in JBrowse.
