### ISSUE TITLE
B.malayi JBrowse

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6551]
RequestError: Unable to load https://www.wormbase.org/tools/genome/jbrowse-simple/data/b_malayi_PRJNA10729/includes/DNA.json status: 403.

linked through https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CClassical_alleles%2CYACs_Fosmids_Cosmids&loc=Bm_v4_Chr4_scaffold_001%3A4237952..4240611&data=data%2Fb_malayi_PRJNA10729

from the location widget of: https://www.wormbase.org/species/b_malayi/gene/WBGene00230858

**Comment by scottcain** [comment]
I’m pretty sure I fixed this but I’m on my phone so I’ll leave this open until I have a chance to check on a real computer
