### ISSUE TITLE
 Server Error: 500 at  rest/field/protein/ENSEMBL:...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6552]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="https://wormbase.org/rest/field/protein/ENSEMBL:ENSP00000247026/blast_details">rest/field/protein/ENSEMBL:ENSP00000247026/blast_details</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->field "mkdir /tmp/wormbase/: Permission denied at /usr/local/wormbase/jenkins/workspace/staging_build/lib/WormBase/API/Role/Service.pm line 248." </p><p>What were you doing? <br />&nbsp;&nbsp;looking for larger lists of homologous proteins
</p>

**Reported by:** Andy (andr*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by WenChenWormBase** [comment]
Dear Andy,

The link seems to work fine at this moment. Please try again and let us
know if you still experience problems.

Wen Chen
Help Desk

On Tue, Aug 7, 2018 at 8:10 AM, <no-reply@wormbase.org> wrote:

> Bug Report
>
> Server Error: 500 at rest/field/protein/ENSEMBL:ENS
> P00000247026/blast_details
> <https://wormbase.org/rest/field/protein/ENSEMBL:ENSP00000247026/blast_details>
>
> Error Message:
> Caught exception in WormBase::Web::Controller::REST->field "mkdir
> /tmp/wormbase/: Permission denied at /usr/local/wormbase/jenkins/wo
> rkspace/staging_build/lib/WormBase/API/Role/Service.pm line 248."
>
> What were you doing?
>   looking for larger lists of homologous proteins
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6552. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6552>.
>
> Reported by: Andy (andrew_samuelson@urmc.rochester.edu)
> 07 Aug 18 15:10
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101
> Firefox/61.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase
