### ISSUE TITLE
 Server Error: 500 at  db/ontology/anatomy   
  Er...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6555]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="https://wormbase.org/db/ontology/anatomy?name=bagl">db/ontology/anatomy</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::ClassicCompatibility-&gt;misc "mkdir /tmp/wormbase/: Permission denied at /usr/local/wormbase/jenkins/workspace/staging_build/lib/WormBase/API/Role/Service.pm line 248." </p><p>What were you doing? <br />&nbsp;&nbsp;accessing a page on BAG neurons</p>

**Reported by:** Mark (m.hi*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//db/ontology/anatomy">anatomy</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by WenChenWormBase** [comment]
The anatomy ontology page appears to work fine <https://wormbase.org/species/all/anatomy_term/WBbt:0003824?from=https://staging.wormbase.org/db/ontology/anatomy?name=bagl#01423--10>.

I don't know where leads to the broken URL.

Raymond
