### ISSUE TITLE
tm1547 and tm3162 mutants (nhr31 deletion) are not...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6557]
*Help Desk query collected when no chat operators were online. Follow up required.*

tm1547 and tm3162 mutants (nhr31 deletion) are not available at the cgc then is there any other way to get the mutants?

**Reported by:** youm** (youm*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00003625#04-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00003625#04-9g-3</a>
**Browser:** Chrome 64.0.3282.186

**Comment by epaule** [comment]
they should be available from the National Bioresource Project of Japan (http://shigen.nig.ac.jp/c.elegans/index.jsp).
If you turn on the external links on the Variation pages (a.e. https://www.wormbase.org/species/c_elegans/variation/WBVar00250536), you should see the links to them.
