### ISSUE TITLE
  Simple Mine isn't working. I get the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6558]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Simple Mine isn't working. I get the following message when trying to use it:<br/>Internal Server Error<br/>The server encountered an internal error or misconfiguration and was unable to complete your request.<br/>Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.<br/>More information about this error may be available in the server error log.</p>

**Reported by:** Amy ******* (amy.********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by WenChenWormBase** [comment]
Hi Amy,

The server issue is solved, so SimpleMine should work normally.

Thanks,
Jae
