### ISSUE TITLE
Hello, In the old GBrowse there is a way you can c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6559]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, In the old GBrowse there is a way you can click and drag the cursor over a segment of chromosome and have the sequence dumped into a fasta. Is there a way to do the same on the new JBrowse? Thanks!

**Reported by:** Gabr***** (gabr************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar00091808#02-4567-10">https://www.wormbase.org/species/c_elegans/variation/WBVar00091808#02-4567-10</a>
**Browser:** Chrome 67.0.3396.87

**Comment by scottcain** [comment]
Sent to the user:

Hi Gabrielle,

You can get sequence for regions in JBrowse, though the process is a little different:

1. Zoom to the region for which you want sequence.
2. Turn on the "reference sequence (DNA)" track.
3. Mouse over the label of the track (in the upper left corner of the track)
4. Click on the down arrow on the right end of the track to expose a menu
5. Select "Save track data" from the menu.
6. Click "save" in the dialog box that opens up.

Look for the fasta file in your browser's default download location.

Sorry that it's currently 6 steps--I'm working on a way to make a "shift-mouse drag" give you a menu that would have "download sequence" as an option when you highlight a region in JBrowse.
