### ISSUE TITLE
Hi
I want to cite wormbase in my thesis as have us...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6560]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi
I want to cite wormbase in my thesis as have used it for information on genes and genetic maps.
Would you please let me know how should I cite? I have used url links at few places. Do I need url at every place or shall I acknowledge wormbase for its enormous information.

Thanks

**Reported by:** Jyot******* (jdin**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/citing_wormbase#0123--10">https://wormbase.org/about/citing_wormbase#0123--10</a>
**Browser:** Chrome 67.0.3396.87

**Comment by chris-grove** [comment]
It seems you've already found our "Citing WormBase" page:

https://wormbase.org/about/citing_wormbase#0123--10

To cite WormBase in general you can cite our most recent (2017) Nucleic Acids Research paper:

https://www.ncbi.nlm.nih.gov/pubmed/29069413

It's up to you how many specific URLs you would like to cite, but you can use the "Citing A Specific Page" instructions on the "Citing WormBase" page linked above for each of those.

Thank you for citing WormBase in your thesis.
