### ISSUE TITLE
I have two questions. First, is there anywhere on ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6561]
*Help Desk query collected when no chat operators were online. Follow up required.*

I have two questions. First, is there anywhere on Wormbase to find published primer sets that have been used to measure gene expression by qRT-PCR? Second, are the "sjj" primers in the Reagents section of gene descriptions for amplifying the cDNA sequence of a gene or the entire locus, including introns?  Thank you!

**Reported by:** Matt********* (matt**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/all/pcr_oligo/sjj_M04G12.4#02--10">https://www.wormbase.org/species/all/pcr_oligo/sjj_M04G12.4#02--10</a>
**Browser:** Chrome 67.0.3396.99

**Comment by chris-grove** [comment]
For your first question, WormBase does not curate qRT-PCR primers from papers.


As for your second question, the "sjj" primers are from Julie Ahringer's laboratory:


https://wormbase.org/resources/person/WBPerson8#013--10

https://wormbase.org/resources/laboratory/JA#03--10


The resulting "sjj" PCR_product object were generated by amplifying genomic DNA and so includes all genomic DNA between the primers, including introns if applicable.


Let us know if you have further questions.
