### ISSUE TITLE
WS267 - Go Annotations connected to dead genes

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6564]
Minor issue, but 7 dead genes have connected go annotations. some of which were merged into other genes or retired 3 years ago.

```
Skipping annotation for WBGene00001421 because could not find a live gene with that id in db
Skipping annotation for WBGene00006834 because could not find a live gene with that id in db
Skipping annotation for WBGene00077738 because could not find a live gene with that id in db
Skipping annotation for WBGene00001611 because could not find a live gene with that id in db
Skipping annotation for WBGene00003200 because could not find a live gene with that id in db
Skipping annotation for WBGene00077741 because could not find a live gene with that id in db
Skipping annotation for WBGene00004934 because could not find a live gene with that id in db
```

**Comment by vanaukenk** [comment]
Thanks @Paul-Davis 
I'll take a look and see what the source for these annotations is.

**Comment by vanaukenk** [comment]
These annotations are all cleaned up now; some were deleted and some were re-annotated in Noctua.  Still need to confer with @azurebrd to make sure the dumper for GO annotations remaining in the OA catches dead genes, though, so I will leave the ticket open until that part is addressed.

**Comment by azurebrd** [comment]
@vanaukenk The script is populating a list of dead Gene objects, but it's not filtering the output based on it.  I've changed it and emailed you about it.

**Comment by Paul-Davis** [comment]
Can we close this ticket?
