### ISSUE TITLE
wiki.wormbase.org login failure due to cookie policy?

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6565]
Hey Web Team,

Looks like there is an issue with login to the wiki:

Mac OSx FF

![wiki_login](https://user-images.githubusercontent.com/717707/44149113-c3ba8804-a092-11e8-9be3-f29d3266d8d0.png)

**Comment by Paul-Davis** [comment]
I have all cookie preferences set to allow and @epaule confirms same behaviour.

**Comment by chris-grove** [comment]
@Paul-Davis 
This is a recurring error. I think Todd just needs to adjust something to fix it.

**Comment by tharris** [comment]
This should now be resolved. Apologies for the difficulties.

**Comment by Paul-Davis** [comment]
Someone fixed it?
