### ISSUE TITLE
  how to get text material about c eleg...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6570]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how to get text material about c elegans?</p>

**Reported by:** PRIY********* (priy**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by chris-grove** [comment]
You can find a number of (free) online resources for learning about C. elegans such as:


- WormBook

http://www.wormbook.org/


- WormAtlas

http://www.wormatlas.org/


- C. elegans II book (1998) at NCBI bookshelf

https://www.ncbi.nlm.nih.gov/books/NBK19997/


... and a number of hard copy books to purchase, for example:


- The Nematode Caenorhabditis elegans (1988)

https://www.amazon.com/Nematode-Caenorhabditis-elegans-Spring-Monograph/dp/0879694335/ref=mt_paperback?_encoding=UTF8&me=&qid=1534425832


- C. elegans II book (1998) hardcopy

https://www.amazon.com/C-Elegans-II-Donald-Riddle/dp/0879695323/ref=sr_1_9?ie=UTF8&qid=1534425516&sr=8-9&keywords=C.+elegans


- C. elegans: A Practical Approach (1999)

https://www.amazon.com/C-elegans-Practical-Ian-Hope/dp/0199637385/ref=sr_1_1?ie=UTF8&qid=1534425516&sr=8-1&keywords=C.+elegans


- C. elegans: Methods and Applications (Methods in Molecular Biology) (2006)

https://www.amazon.com/C-elegans-Methods-Applications-Molecular/dp/1588295974/ref=sr_1_7?ie=UTF8&qid=1534425516&sr=8-7&keywords=C.+elegans


- C. elegans Atlas (Hardcopy book of WormAtlas content) (2008)
https://www.amazon.com/C-elegans-Atlas-David-Hall/dp/0879697156/ref=sr_1_12?ie=UTF8&qid=1534425516&sr=8-12&keywords=C.+elegans


- C. elegans: Methods and Applications (Methods in Molecular Biology) (2015)

https://www.amazon.com/C-elegans-Methods-Applications-Molecular/dp/1493928414/ref=sr_1_4?ie=UTF8&qid=1534425516&sr=8-4&keywords=C.+elegans&dpID=41mgMnK8z5L&preST=_SY344_BO1,204,203,200_QL70_&dpSrc=srch


I hope that helps.
