### ISSUE TITLE
hello , I would like to know what does downstream ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6576]
*Help Desk query collected when no chat operators were online. Follow up required.*

hello , I would like to know what does downstream target gene means?

**Reported by:** Enic********** (enic*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001371#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00001371#0-9g-3</a>
**Browser:** MSEdge 17.17134

**Comment by chris-grove** [comment]
It may depend on the context, but often times "downstream target gene" means a gene that a transcription factor (protein, usually) regulates by promoting or repressing transcription of that gene. This can also mean more generally a gene whose function or activity is regulated (positively or negatively) by some factor (usually another gene or gene product). "Downstream" is simply a reference to an event that takes place further along a temporal chain of cause-effect events.


I hope that helps.
