### ISSUE TITLE
  how do I find insulin receptor sequen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6577]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do I find insulin receptor sequence in C. elegans?</p>

**Reported by:** sura*** (sura**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by chris-grove** [comment]
You can search for the Gene Ontology term "insulin-activated receptor activity":


https://wormbase.org/species/all/go_term/GO:0005009#02--10


and look in the "Ontology Browser" widget to find gene associations. There is one gene product annotated to this term, the well studied insulin receptor in C. elegans called "daf-2":


https://wormbase.org/species/c_elegans/gene/WBGene00000898#0g--10


In the "Sequences" widget of the daf-2 page, you can find the gene sequence, transcript sequences and protein isoform sequences.


Let us know if you have any further questions.
