### ISSUE TITLE
How can I find gene corresponding to the chromosom...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6579]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I find gene corresponding to the chromosome position

**Reported by:** Mali** (mail******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 67.0.3396.87

**Comment by scottcain** [comment]
Sent to the user:

Hi Malini,

If I understand your question correctly, I think you're asking about having a chromosomal position (like I:10,000..11,000 for example) and you'd like to know what genes are there are nearby.  The most obvious way I can think of to answer that question is to use a genome browser.  Try our JBrowse instance:

  https://wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758&loc=III%3A9055716..9076015&tracks=Curated_Genes

and enter the location in a similar format as what I used above ("chromosome_name:start..end") in the box to the left of the "Go" button, and then press Go.  I turned on the on Curated Genes track, so genes that are in the area you're interested in will be visible.  If there aren't any, you can use your mouse to slide to the left or right to look in the nearby area, or use the zoom out icon (the magnifying glass with a minus) to zoom out a little.

Please let me know if that wasn't what you were asking, or if you'd like clarification or other help,
