### ISSUE TITLE
Help Desk: Looking for genes located in set of genomic coordinates

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6580]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): I would like to know how to convert chromosome position with numbers be converted to the corresponding genes</br>Chris: Hello visitor_name</br>Chris: Would you like to convert a range of chromosomal coordinates to a list of genes in that interval?</br>visitor_name (visitor_email): ya</br>Chris: OK, I would recommend using our WormMine tool, which you can find a link to under the WormBase "Tools" menu</br>Chris: http://intermine.wormbase.org/tools/wormmine/begin.do</br>visitor_name (visitor_email): ok</br>Chris: On the WormMine homepage, there is a template query under the "GENOMICS" tab called a"Chromosome Interval --&gt; Genes"</br>Chris: Click on that, specify your chromosome and coordinates and you should get a list of genes in that interval</br>visitor_name (visitor_email): how can I do for bunch of co-ordinates all at the same time</br>visitor_name (visitor_email): ?</br>Chris: For that you can try the WormMine "Regions" tool</br>Chris: Go to the "Regions" tab, select your species, select the feature types you'd like to find in your region(s) and then enter your genomic regions/coordinates in the search box and click "Search"</br>Chris: You can click on "click to see an example" to see the format</br>visitor_name (visitor_email): ok got it..but I have the coordinates in excel format</br>visitor_name (visitor_email): its 2800 coordinates not sure how to convert to that format</br>visitor_name (visitor_email): I:1000-2000 something like this</br>Chris: You can export/save your Excel file into .txt format and upload the file, as long as the format is as indicated</br>Chris: what format is your current file in?</br>visitor_name (visitor_email): excel</br>Chris: I mean are the coordinates listed in the Excel file like "I:1000-2000</br>Chris: "?</br>visitor_name (visitor_email): no</br>visitor_name (visitor_email): first column chromosome</br>visitor_name (visitor_email): 2nd start of co-ordinate</br>visitor_name (visitor_email): 3rd end of coordinate</br>visitor_name (visitor_email): however wormmine asks to paste it in I:1000-2000 this format</br>Chris: right</br>visitor_name (visitor_email): or txt format</br>Chris: There are a number of different tricks you can use to convert it to the proper format from there; I'm trying to think of the fastest</br>visitor_name (visitor_email): Ok</br>Chris: OK, I just checked and your format will still work, but you need to export the Excel table as a .txt file</br>visitor_name (visitor_email): ok</br>Chris: Use the "File &gt; Save as... &gt; Tab delimited text (.txt)" option</br>Chris: Save the file (to your desktop for example), and then on the Regions tab of WormMine, select "Choose File" under the "Upload genomic regions from a .txt file..." under the search box</br>Chris: Let me know if that does or doesn't work for you</br>Chris: Also, keep in mind that this tool will return genome features that overlap with your windows/regions at all, not just those features entirely contained within the region</br>visitor_name (visitor_email): I am trying and Let me see what it shows</br>Chris: OK</br>Chris: Any luck?</br>visitor_name (visitor_email): I got the results</br>Chris: OK, are they what you were looking for?</br>visitor_name (visitor_email): Some of the results do not match with what I am looking for. But I will look deeply and get back to you probably by tomorrow. Thanks for now</br>Chris: OK. I'll close this chat window then. We will both receive a transcript of this chat afterwards. You can reply all to that email if you want to follow up</br>visitor_name (visitor_email): sure thanks a lot for your time</br>Chris: OK, you're welcome. Have a nice day!</br>visitor_name (visitor_email): thanks, you too</br>Chris: Thanks!

**Reported by:** Mali** (mail******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 67.0.3396.87

**Comment by chris-grove** [comment]
Will leave open for now

**Comment by chris-grove** [comment]
Emailed user to follow up. Closing. Will reopen if necessary.
