### ISSUE TITLE
WormMine Regions bug: trying to leave extended region field blank results in error message that takes over the page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6581]
Here's a screen recording:

https://www.dropbox.com/s/mhlsvj8422dhszq/Regions_bug_Aug_20_2018.mov?dl=0

The issue is that if you accidentally erase the entry for field 4 (the "Extend your regions at both sides" field) and try to move away from the field, there is the error message:

![screen shot 2018-08-20 at 3 40 10 pm](https://user-images.githubusercontent.com/611382/44365191-17233380-a497-11e8-87cf-e1dd9055b7c3.png)

which will not go away once clicking on "OK" and will not allow entering a number in field 4, or any field for that matter. You basically need to close the window and start over because nothing is allowed while that error message is showing, and you can't get rid of it.

**Comment by nuin** [comment]
@chris-grove Thanks for reporting this. Just checked other mines and they have the same behaviour, so I would assume this is on their code. I will report the error there.

**Comment by nuin** [comment]
I reported again to Intermine, on the dev list.
