### ISSUE TITLE
  Greetings, I need to search for devel...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6582]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Greetings,<br/>I need to search for developmental patterning phenotypes (any defects in embryonic or adult anatomy) associated with any genes that have the name channel, pump, transporter, antiporter, gap junction. I am wondering what the best way to go about that using your site might be? I appreciate any suggestions you are willing to suggest.<br/>Thanks,<br/>visitor_name</p>

**Reported by:** Tia (chri************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by chris-grove** [comment]
We'd be happy to help. First, could you help us narrow down which phenotype terms you're looking for exactly? We have a phenotype ontology, which you can browse here:

https://wormbase.org/tools/ontology_browser

Are you looking only for defects in embryos and adults, and not in any larval stages? Are you looking only for morphological phenotypes (i.e. changes in physical structure and appearance)?

I've generated some public lists and a query in WormMine which I think should get you started, but doesn't distinguish between embryo, larval and adult phenotypes; it just looks for genes (transporters (including channels, pumps, anti-porters) and/or gap junction genes) with morphological phenotypes. Copy the following XML query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and (B or C)">
  <constraint path="Gene.alleles.phenotype" code="A" op="IN" value="Organism and organ system morphology phenotype terms WS265"/>
  <constraint path="Gene.goAnnotation.ontologyTerm" code="B" op="IN" value="transporter activity and descendant terms WS265"/>
  <constraint path="Gene.goAnnotation.ontologyTerm.name" code="C" op="=" value="gap junction"/>
</query>`

Then go to the WormMine page (discoverable under the WormBase Tools menu):

http://intermine.wormbase.org/tools/wormmine/begin.do

Click on the "QueryBuilder" tab, click on "Import query from XML", paste in the query above into the search box, click "Submit" and then click on "Show results". This should return a table of 201 rows, representing 97 transporter and/or gap junction genes with some morphological phenotype (indicated in the last two columns). You can then export this table in .tsv format for further analysis.

Let us know if you need something else.
