### ISSUE TITLE
  Hello there. The CGC link (https://cg...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6583]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello there. The CGC link (https://cgc.umn.edu/strain/FX30123) from the FX30123 strain to wormbase appears to be broken... not sure what end that is on. Thanks for all your work! Christian</p>

**Reported by:** Chri********************** (chri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by chris-grove** [comment]
Thanks for the heads up. It appears that FX30123 is in our curation database but has not yet made it to any of our releases up to WS267. I suspect that the WormBase page for FX30123 will be available in the WS268 release due out on the website in mid-December.


Our strain curator may be able to provide additional information.
