### ISSUE TITLE
  I was confirming the presence of the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6584]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was confirming the presence of the daf-18(e1375) allele in some strains we made.  Our sequence confirms that reported in Ogg and Ruvkun 1998 Cell and found that the Wormbase sequence for this allele has two errors.<br/>1) The sequence for the 30 bp insertion is in the wrong orientation.<br/>2) Although not mentioned in the original paper, e1375 is a 30 bp insertion/ 2 bp deletion.<br/>The details are in figure 2A of the paper.  Here are the sequences for reference.<br/>WT: CAA GCG TTG ACT CAA ATG AAT CCA AAA<br/>e1375: CAA GCG TTG ACT CAA TGC GTT GAC TCA ATG CGT TGA CTC GTT GAC GAA TCC AAA A</p>

**Reported by:** Chri*************** (chri*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by Paul-Davis** [comment]
Dear Christian,

Thanks for taking the time to feed this back to us.

I will correct the orientation and add additional details about the 
nature of the mutation.

Paul



On 22/08/2018 20:59, no-reply@wormbase.org wrote:
> Content Correction
>
>   I was confirming the presence of the daf-18(e1375) allele in some 
> strains we made. Our sequence confirms that reported in Ogg and Ruvkun 
> 1998 Cell and found that the Wormbase sequence for this allele has two 
> errors.
> 1) The sequence for the 30 bp insertion is in the wrong orientation.
> 2) Although not mentioned in the original paper, e1375 is a 30 bp 
> insertion/ 2 bp deletion.
> The details are in figure 2A of the paper. Here are the sequences for 
> reference.
> WT: CAA GCG TTG ACT CAA ATG AAT CCA AAA
> e1375: CAA GCG TTG ACT CAA TGC GTT GAC TCA ATG CGT TGA CTC GTT GAC GAA 
> TCC AAA A
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6584. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6584>.
>
> Reported by: Christian Rocheleau (christian.rocheleau@mcgill.ca)
> 22 Aug 18 19:59
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 
> (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
@tharris so this seems to be another of the issues where the variation was published on the -ve strand as it's a -ve strand gene. The web code tries to enforce a + strand only view as we have discussed in the past. If there is inserted sequence then to context and the actual data provided to the user is nonsensical. Do you still think +ve strand only is the way we should be doing this or do you think it's time to rework the widget? The flanks are stored correctly in the database, the variation is mapped correctly and dumped in the gff  as is the insert sequence so theoretically should be doable if not a reasonable chunk of work for a developer.

**Comment by epaule** [comment]
@Paul-Davis do you want to keep that ticket?
