### ISSUE TITLE
  Hello can you help me fine the sequen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6589]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello can you help me fine the sequence for the following genes from Dirofilaria immitis:<br/>Ftsz (wolbachia)<br/>Tbuling and <br/>GST<br/>I do not have the gene ids for these. </p>

**Reported by:** shab**** (sjaw*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Zoom 3.6.0; rv:11.0) like Gecko

**Comment by epaule** [comment]
http://parasite.wormbase.org/Dirofilaria_immitis_prjeb1797/Info/Index/
would be the current entry point for Dirofilaria immitis

But I don't think the Wolbachia is in the current assembly, so you might have to trawl NCBI for the sequence of its genes.

I would guess that "Tbuling" should be "Tubulin" Gamma or maybe you mistook a greek delta (δ) for a g ? In any case, you would put the name (a.e. tubulin) into the search box to find a gene with the description and then see if there are any orthologs in D.immitis. For Tubulin Gamma, a good hit is the Trichurus trichiura gene TTRE_0000816401 and the I went to the ortholog section to find http://parasite.wormbase.org/Dirofilaria_immitis_prjeb1797/Gene/Summary?g=nDi.2.2.2.g05408

You could do a similar approach for GST. With the difference that the Glutathione S-transferase family is actually quite big and there are no obvious orthologs outside of the clade V.
So plan b. would be to search for any D.immitis proteins with a glutathione S-transferase domain (PF02798) in biomart, which comes up with 3 potential candidate genes for GST.
