### ISSUE TITLE
  Our lab name is PHX in wormbase. Sinc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6590]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Our lab name is PHX in wormbase. Since the PI of our lab was changed, I'm writing to see whether you can help change the corresponding information in the wormbase? <br/>We want to change the name of our PI from " YI XUE" to "XIULAN HU". </p>

**Reported by:** Lanc* (Suny**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by Paul-Davis** [comment]
Likely contact details sunybiotechchina@gmail.com

**Comment by chris-grove** [comment]
Issue has been resolved. User contacted. Closing.
