### ISSUE TITLE
  Hi, I am searching for C. elegans non...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6593]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am searching for C. elegans noncoding RNA genes list. Could you please tell me how to find?<br/>Thanks and regards,<br/>visitor_name</p>

**Reported by:** Amar*** (ac26**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by chris-grove** [comment]
You can use WormMine to get this list (the link to WormMine is discoverable under the WormBase "Tools" menu):

http://intermine.wormbase.org/tools/wormmine/begin.do

Navigate to the "QueryBuilder" tab, click on "Import query from XML", paste in the following query XML:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.transcripts.method" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.transcripts.method" code="A" op="ONE OF">
    <value>7kncRNA
    </value>
    <value>asRNA
    </value>
    <value>lincRNA
    </value>
    <value>miRNA
    </value>
    <value>miRNA_primary_transcript
    </value>
    <value>ncRNA
    </value>
    <value>piRNA
    </value>
    <value>pre_miRNA
    </value>
    <value>rRNA
    </value>
    <value>scRNA
    </value>
    <value>snRNA
    </value>
    <value>snlRNA
    </value>
    <value>snoRNA
    </value>
    <value>tRNA
    </value>
  </constraint>
  <constraint path="Gene.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>
</query>`

click "Submit", click on "Show results", and you should have your table. You can then export in tab-delimited format if you wish.

Let us know if you have any questions.
