### ISSUE TITLE
  I'm trying to find the reference geno...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6594]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm trying to find the reference genome used in mapping the RNA-seq reads in the following paper:<br/>Mutational and Transcriptional Landscape of Spontaneous Gene<br/>Duplications and Deletions in Caenorhabditis elegans<br/>Konrad et al. 2018<br/>In the supplementary material, the authors say that they used "the protein-coding transcriptome of C. elegans (Wormbase reference N2 genome version WS247)".<br/>I tried to find the corresponding reference transcriptome on Wormbase, but couldn't find it.</p>

**Reported by:** Shad******* (shad************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by chris-grove** [comment]
I think you should find what you need on our FTP site here:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS247/species/c_elegans/PRJNA13758/


in particular this file:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS247/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS247.mRNA_transcripts.fa.gz


or if you're only interested in protein-coding sequence:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS247/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS247.CDS_transcripts.fa.gz


or you may want to parse the GFF files available in the same directory.


Let us know if you need something else.
