### ISSUE TITLE
Hello. I have a list of 636 transcripts codes (obt...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6597]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello. I have a list of 636 transcripts codes (obtained from Opisthorchis viverrini genome) that I want to assign the corresponding accession number for each one. For instance: T265_03855 (transcript code) - A0A074ZQ61. How I can do that automatically?

**Reported by:** Clau************* (clau***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/support?url=/">https://wormbase.org/tools/support?url=/</a>
**Browser:** Firefox 61.0

**Comment by Paul-Davis** [comment]
No user contact details as the help email wasn't generated.

**Comment by Paul-Davis** [comment]
User data found......ask @chris-grove  if you want to respond to the user.

**Comment by epaule** [comment]
Hi Claudia,

can you try the Parasite Biomart (https://parasite.wormbase.org/biomart)
Just pick the species, restrict it to the transcript ids (which you can
copy in or upload as a file) and pick the attributes you want to see (like
ENA accession number)

best regards,

Michael
