### ISSUE TITLE
It used to be easy to download genomic sequence fr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6598]
*Help Desk query collected when no chat operators were online. Follow up required.*

It used to be easy to download genomic sequence from the genome browser, but I can't figure out how to do it from Jbrowse - what is the secret?

**Reported by:** Erin (e.cr**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=III:5045664..5047448&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=III:5045664..5047448&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Chrome 66.0.3359.117

**Comment by chris-grove** [comment]
The secret in JBrowse is to turn on the "Reference sequence (DNA)" track, and then use the track's "Save track data" option to download a FASTA file of the sequence whose region you are currently zoomed to.


https://www.dropbox.com/s/mr1v7zvf3ur280k/Retrieving_sequence_from_JBrowse.mov?dl=0


You can also get more annotated sequence from the "Curated genes (protein coding)" track by right-clicking on a particular transcript, selecting "View Sequence" and playing with the options to get different bits of sequence associated with the transcript, including upstream sequence:


https://www.dropbox.com/s/enuje3whq2ehaxq/Transcript_sequence_viewer_JBrowse.mov?dl=0


Let us know if you have any questions.
