### ISSUE TITLE
  I asked updating my lineage of C. ele...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6599]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I asked updating my lineage of C. elegans biologist by mistake. How do I cancel it?</p>

**Reported by:** Chis********** (cush********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by chris-grove** [comment]
@tharris 
This is the second help desk ticket to come in this week (the first being #6598) that I received a GitHub ticket alert for, but no Help Desk email from the help@wormbase.org mailing list. The issue is that the full name and contact information is censored in the GitHub ticket email and is only fully available from the Help Desk email. For #6598 I had to guess who the person was. Can we look into that?

**Comment by tharris** [comment]
I’ll take a look at the failing emails and see if there is something in common. As for unmasking user names and emails in Github, would you prefer that? 

I masked them because people might not suspect that posting to the help desk would actually be a public comment.

**Comment by chris-grove** [comment]
Well, I appreciate why the names and emails were masked in GitHub and am fine with (and would prefer) keeping it that way. My preference would be that the help desk emails come through faithfully with the required information

**Comment by sibyl229** [comment]
It seems that both the feedback form and the Olark chat (#6598) are affected. I wonder what's the common denominator. The last help email of a github issue I received was on Aug 30th.

**Comment by kyook** [comment]
@tharris was there a fix put in place?  It seems we are still missing some user e-mails...

**Comment by tharris** [comment]
Yes, but it just went inthis afternoon.

**Comment by ceciliaWBPerson1** [comment]
I replied to the user from the person lineage form i received.
