### ISSUE TITLE
  Hi- I'm looking to post a postdoc pos...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6606]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi- I'm looking to post a postdoc position in my lab to do worm work. I don't see a 'careers' section on your site, but maybe I'm missing it. If you have a job board of some type could you let me know how to find it?<br/>Cheers<br/>-Jason</p>

**Reported by:** Jaso****** (jhel***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.64

**Comment by chris-grove** [comment]
These types of job postings are most often made on the WormBase Community Forums:


http://forums.wormbase.org/


If you haven't already, you'll need to register to make a post, but then you can post in the "Job Postings" announcements and look through the "Positions Wanted" list.


Let us know if you have any questions.
