### ISSUE TITLE
  Hi WormBase, Wanted to touch base wit...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6607]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi WormBase,<br/>Wanted to touch base with you about Bm3263.<br/>When one conducts a search on Wormbase for UGT (aka UDP glucuronosyltransferase) one gets two hits:  Bm3263 and Bm17378.  Bm17378 is definitely a predicted UDP glucoronsylt transferase.  However, I'm not sure that Bm3263 is.  When we put the sequence into Interpro it comes up as a member of the PDZ superfamily, which suggests it is involved in cellular signaling and doesn't necessarily function as an enzyme.  Also, the text under Bm3263 states that proteomic studies have found that it localizes to the intestinal tract of Brugia.  To our knowledge, our group is the only one that has published a study on the proteome of the Brugia malayi intestinal tract and we did not find Bm3263 there. <br/>Thanks for all the terrific work you guys do!!  Great site...super helpful!!!<br/>-Ed</p>

**Reported by:** Ed M**** (edwa******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by epaule** [comment]
Dear Edward Mitre,

sorry for the late reply, we had some issue tracking issues here.

According to the gene history It looks like in 2012 (WS236) it was assigned
Bma-ugt-21 thorough orthology with the C.elegans ugt-21 gene. Later that
name was removed when we cleaned up orthology based naming after the last
gene set/assembly update.
I guess that our then synteny based orthology pipeline must have picked it
up as it included the then not yet existing upstream Bm17378 locus (which
came with the next geneset/assembly in 2015). Similar an xref to Bm1_13480
was added during that time (which was also described as UDP glycosil
transferase).
When the gene models were later changed the historic xref were inherited
down the line.

Also you don't have to put the proteins through InterPro, as you can see
the interpro (and other domains) in the protein page (Sequence -> Protein).

In addition I don't see any mass-spec data attached to that gene, and no
homologs with locations. So I don't know where the description pipeline
pulled that from (but I copied Ranjana into the email, who was involved in
designing it).

In my opinion the current description of Bm3263 looks quite outdated and
should be either updated or removed.

sorry for the inconvenience,

Michael
