### ISSUE TITLE
we provided the first evidence that f35e12.5 is an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6608]
*Help Desk query collected when no chat operators were online. Follow up required.*

we provided the first evidence that f35e12.5 is an immune response gene. please include this in wormbase: J Biol Chem. 2010 Apr 2;285(14):10832-40. doi: 10.1074/jbc.M109.091629. Epub 2010 Feb 4.

**Reported by:** alej************* (abal************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00009429#041-79gc6db-10">https://www.wormbase.org/species/c_elegans/gene/WBGene00009429#041-79gc6db-10</a>
**Browser:** MSEdge 17.17134

**Comment by chris-grove** [comment]
The gene F35E12.5/irg-5 has been added to this paper in the Paper Editor. Will follow up with user. Closing.
