### ISSUE TITLE
  I was surprised to find that the prim...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6610]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was surprised to find that the primary reference for the C. elegans genome does not exist in this database (C. elegans Sequencing Consortium, 1998). Also the links to the author list of that reference have been broken. Is there any way to restore such links or at least retrieve the original author list?</p><p>What were you doing? <br />&nbsp;&nbsp;Searching for a WormBase literature number for the original C. elegans genome sequence report in Science (Dec. 11, 1998)</p>

**Reported by:** Davi******* (davi***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

**Comment by Paul-Davis** [comment]
Do we have contact details for this user?

The information he was after is in WormBase, but I can't contact to let him know??

**Comment by Paul-Davis** [comment]
Not being able to find the publications might be linked to my ticket from yesterday: #6618

**Comment by kyook** [comment]
@chris-grove do you have a contact e-mail for this user by anychance?

**Comment by chris-grove** [comment]
@kyook 
No, this came in through the feedback form, not Olark, so I can't access the email address. I think you'll have to ask @tharris

**Comment by Paul-Davis** [comment]
Help me, @tharris. You're my only hope.
