### ISSUE TITLE
  WormBase Help, My lab has generated a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6611]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormBase Help,<br/>My lab has generated a list of proteins that co-immunoprecipitate with one of our favorite tagged proteins. Is there a computational way to compare our data to other similar published datasets?<br/>I’m happy to discuss this, if needed.<br/>Thank you!<br/>Best,<br/>Tina</p>

**Reported by:** Tina************ (Tgum*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (iPad; CPU OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1

**Comment by mgrbyte** [comment]
Is anyone able to help answer this please?

**Comment by WenChenWormBase** [comment]
I can write to her to find out more details. But I cannot find her email. Can you send it to me?

**Comment by draciti** [comment]
TGumienny@twu.edu
________________________________
