### ISSUE TITLE
I want to know if there is a mutant of the wirewor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6619]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to know if there is a mutant of the wireworm taste defect in your research~Thank you!

**Reported by:** Myvn (9299************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00050876#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00050876#0-9g-3</a>
**Browser:** Chrome 39.0.2171.95

**Comment by kyook** [comment]
Dear Myrn,

I am not familiar with "wireworm taste" defect.

We create and curate phenotypes based on what has been reported in
peer-reviewed published research that we can access through PubMed.
If you have a particular article in mind that reports this phenotype
that we missed, we would be happy to take a look and see if it is
something we would add to our database.

Best wishes,
Karen
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren



On Mon, Sep 10, 2018 at 6:07 PM,  <no-reply@wormbase.org> wrote:
> offline chat I want to know if there is a mutant of the wireworm taste
> defect in your research~Thank you!
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans/gene/WBGene00050876#0-9g-3
> https://www.wormbase.org/species/c_elegans/gene/WBGene00050876#0-9g-3
>
> This issue has been assigned ticket number: #6619. Follow progress on our
> issue tracker.
>
> Reported by: Myvn (929953023@qq.com)
> 11 Sep 18 01:07
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
