### ISSUE TITLE
please add reference 
Heppert JK, et al. 2017 Gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6628]
*Help Desk query collected when no chat operators were online. Follow up required.*

please add reference 
Heppert JK, et al. 2017 Genetics

**Reported by:** alex************ (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00002994#01d-g4ce9-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00002994#01d-g4ce9-3</a>
**Browser:** Safari 11.1.2

**Comment by kyook** [comment]
Hi Alexandra,

Thank you for bringing this to our attention.  We will look into this
and make sure this paper is properly connected to lin-5.

Best wishes,

**Comment by kyook** [comment]
Hi Kimberly,

Can you remind me again how genes are associated with papers?  I
thought this was an automatic process.  This paper does have a number
of genes, but looking at the record in the paper editor, I'm not
seeing any genes associated with it.

Looking at a few more past articles, these genetics papers also do
not, but should, have genes associated are:
http://tazendra.caltech.edu/~postgres/cgi-bin/paper_editor.cgi?action=Search&data_number=00053551&curator_id=two1760
http://tazendra.caltech.edu/~postgres/cgi-bin/paper_editor.cgi?action=Search&data_number=00053467&curator_id=two1760
http://tazendra.caltech.edu/~postgres/cgi-bin/paper_editor.cgi?action=Search&data_number=00053403&curator_id=two1760
(this is a wormbook article)

Also at least in this paper, only one gene is associated with the
article, other genes are mentioned for which there are results
reported,
http://tazendra.caltech.edu/~postgres/cgi-bin/paper_editor.cgi?action=Search&data_number=00053382&curator_id=two1760
Only oef-1 is associated with this paper, but there are reported
results for pdc-2, hus-1, him-3, etc.
