### ISSUE TITLE
  life cylce of C.elegans and how to id...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6632]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;life cylce of C.elegans and how to identify different larval stages?</p>

**Reported by:** SMRI*********** (bhar***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

**Comment by kyook** [comment]
no return address, so can't reply to user

**Comment by chris-grove** [comment]
@tharris 
Do you have the user's contact info?

**Comment by kyook** [comment]
No.

**Comment by tharris** [comment]
I pushed some messages through that had been marked as spam. For issues like this where the duplicate email that is posted to the list went missing, those messages should now have posted. If they *haven't* it's because they can't be recovered.
