### ISSUE TITLE
i want to download the intergenic regions of C ele...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6633]
*Help Desk query collected when no chat operators were online. Follow up required.*

i want to download the intergenic regions of C elegans

**Reported by:** Niki** (niki**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Classical_alleles,Polymorphisms,Curated_Genes&amp;loc=III:9055725..9076024&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Classical_alleles,Polymorphisms,Curated_Genes&amp;loc=III:9055725..9076024&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Chrome 69.0.3497.92

**Comment by epaule** [comment]
please have a look at ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/ there should be a file with all intergenic regions in C.elegans
