### ISSUE TITLE
movies on canopus

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6634]
Hi @sibyl229 ,

I have added a folder with 2 movies on Canopus. Located here
/home/daniela/OICR/Movies/WBPaper00055066
these will go in for WS268.
Let me know if you need re-encoding or if they are fine as is.

thanks
Daniela

**Comment by sibyl229** [comment]
Hi @draciti I checked those two movies. They don't need to be re-encoded. 

OICR sync the movies from ftp://caltech.wormbase.org/pub/OICR/Pictures Could you check with @azurebrd to see where to put the file so it makes to ftp://caltech.wormbase.org/pub/OICR/Pictures ?

**Comment by sibyl229** [comment]
If the movie is present in ftp://caltech.wormbase.org/pub/OICR/Pictures but doesn't show up when WS268 is deployed to staging, please let me know. Thanks!

**Comment by draciti** [comment]
Thanks Sibyl,
movies should be in this directory:
ftp://caltech.wormbase.org/pub/OICR/Movies

The folder --WBPaper00055066-- is already there. Let me know if there's anything I should do.
I'll check the movie files once WS268 will be on staging
thanks!

**Comment by sibyl229** [comment]
@draciti Thanks! Nothing in particular that you need to do.

**Comment by kyook** [comment]
@draciti can this be closed?

**Comment by draciti** [comment]
no, needs testing once WS268 will be up

**Comment by sibyl229** [comment]
Hi @draciti just letting you know that the two video has made 268. Here it is on the paper page: https://staging.wormbase.org/resources/paper/WBPaper00055066#03--10

**Comment by draciti** [comment]
thank you Sibyl!
they work well.
Closing
