### ISSUE TITLE
  Hello I am working on RNAseq analyses...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6636]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>I am working on RNAseq analyses from B malayi. So I am using the current version of B malayi genome and its corresponding current annotation (b_malayi.PRJNA10729.current.genomic.fa and .gff) as reference for reads alignment and reads count. I found from this annotation that the rRNA prediction was weird and not OK. Indeed after alignment I found big genomic region with a huge amount of aligned reads, so I suspected that could probably be a failure in rRNA depletion during libraries construction. To confirm that I did a rRNA prediction with Infernal against the Rfam database and I found that those region corresponded to rRNA that were not predicted in the wormBase annotation. Would you like to have this RNA prediction output for B malayi ?<br/>Thanks for your help !<br/>Germain</p>

**Reported by:** Germ************* (g.ch*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

**Comment by epaule** [comment]
we lifted over most of the RNA predictions from the previous assembly.
If you send your predictions our way, we will try to use them to improve the annotation.
