### ISSUE TITLE
GO-ribbon table in WormBase

### ISSUE THREAD

**Issue by WBjae** [WormBase/website#6640]
I found the sliding bar is overlapped with the radio buttons for the table below.
I tested chrome and firefox on pc, firefox on ubuntu. All of them have a same issue.
Can we solve it?
Thanks,

**Comment by vanaukenk** [comment]
@WBjae @sibyl229 

It looks like this issue may be fixed?  If so, shall we close the ticket?

Thx.

**Comment by WBjae** [comment]
Yes. I think the issue was solved already.

Thanks,
Jae
