### ISSUE TITLE
BLAST hits not getting rendered in GBrowse correctly on IE 11

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#6641]
This is from an email to the help list from Ekkehard Schulze:
```
Dear Sir,

I like to report a serious malfunction in Wombase BlastN Gbrowse when using IE11-
I send you attached two C. elegans blast runs performed for the C. elegans genome.
One was run and visualized using Firefox 62, the other using IE11.
It turns out, that Firefox visualization is correct, IE11 is showing something different.
In other word: the IE11 visualization is wrong.
I send you the respective query so that you can test this on you installations.
This error had consequences for our experimental work and caused
a considerable loss of time.
```
I suspect that, for whatever reason, the url that has the add "Hits" data isn't getting generated correctly.

**Comment by scottcain** [comment]
Sample sequence provided by the user, but I suspect it doesn't matter what sequence is used:

GAAGGTCGTGAGCGCGCGTATACGACTCACTATAGGGCGAATTGGGTACCGGGCCCCCCCTCGAGGTCGACGGTATCGATAAGCTTGATATCACAAGTTTGTACAAAAAAGCAGGCTTGCAGTCCTCGACTGATTTTCACGATGATGTTCATCTTGTCGATCCAACCTTTTTCGCTAATGAAGACAATAAGTGTCGGAGTGGATACACAATGTGCCATAGCGGAGACGTCTGCATACCTGACAGTTTTCTTTGTGACGGCGATCTAGATTGTGATGATGCTTCGGACGAGAAAAACTGCCAAACTAATGCCCCAAGCGAAGAAGAATATCTTTCTGGGCAAGCCGATCACATGCATTCGTGCTCAGCAGCAGGAATGTATTCTTGTGGAACAAAAGGATCCGAAATTGGCGTTTGTATTCCGATGAATGCCACGTGTAATGGGATCAAGGAGTGTCCACTAGGAGATGACGAGTCAAAACATTGCTCCGAATGTGCCAGAAAGCGATGTGACCACACATGTATGAACACTCCACACGGGGCTCGCTGCATTTGTCAAGAAGGATATAAGCTTGCCGATGACGGACTCACTTGCGAGGATGAAGATGAGTGTGCAACTCATGGGCACTTGTGCCAGCATTTCTGTGAAGATCGTTTGGGTTCCTTTGCATGCAAATGTGCCAACGGTTATGAGCTTGAAACGGATGGGCATTCTTGTAAATACGAGACAACCACTACGCCAGAAGGATATTTGTTCATCAGTCTTGGTGGAGAAGTTCGACAGATGCCATTGGCAGATTTCACCGATGGTTCAAATTACTCGCCGATTCAAAAGTTTGCTGGCCACGGAACCATCAGATCGATCGACTTCATGCATCGCAACAACAAAATGTTCATGTCAATTTCTGATGAGCACGGTGATCCAACTGGCGAATTGTCAGTGTCCGACAATGGATTGATGAGAGTTCTTCGAGAAAATGTCATTGGAGTGAGCAACGTGGCAGTCGACTGGATTGGTGGAAACGTTTTCTTCACACAAAAATCTCCATCTCCAAGCGCTGGGATTTCCATCTGCACAATGAGCGGAATGTTCTGTCGCCGAGTTATCGAAGGCAAAGAACAAGGACAATCCTATCGTGGTCTTGTTGTTCACCCGATGCGCGGTCTCATCATCTGGATCGATTCTTATCAAAAATTCCTCGCATCCGGATGGCTAATATGGATGGGTCCCAGGTCAAAATCCTTCCCGAAAAAAAATTGGAAGTTCCATCCGCCTTTGCCATGAAAAAATCCGCCCCAAAGTCTATTTGGAAAATTTGA

**Comment by sibyl229** [comment]
Example: https://wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758?name=IV:5467731..5474582;add=IV+Hits+Hits+5470731-5471582,5471628-5471820,5470612-5470685

**Comment by scottcain** [comment]
Darn it, IE.  Rewriting URLs is not nice.  I'll look at the code that parses this part of the URL to see if I can generalize it to split on space/%20.

**Comment by scottcain** [comment]
So URI encoding the pluses is not the problem.  Following the rewritten URL from a non-broken browser results in the expected behavior (adding a new "Hits" track with one feature that has three subparts).

@sibyl229 Can you confirm that following the second link you pasted with the %20 encoding fails to add a feature to the Hits track when using IE 11?  If it fails to do so, it's even weirder than I thought.

**Comment by scottcain** [comment]
I created a test instance of GBrowse where I could modify the perl modules without fear of breaking the production instance and sent the user some URLs to see if I could replicate the problem.  I could not.  I believe what was happening was the IE 11 was caching images that it should have been so that the tracks didn't match up with the reference sequence "ruler" (in fact if you look at the "wrong" image that the user sent, you can see that the grid lines don't match up between those parts of the browser).  Given that, I don't think there is anything we can do to fix the problem.  Here is what I sent the user:

------------------
That leaves me with the thought that it IE is caching images from a previous browsing session, even though the GBrowse code tells browsers not to cache those images (thanks Microsoft).  My suggestion is this: if you get an empty hits track when clicking on a BLAST result, try reloading the page (I'm not positive that will work, but it should).  Clearly when clicking on a link from the BLAST results page, you should get a result :-) My other suggestion is to use JBrowse, as it doesn't cache images (though I've honestly never tested it on IE 11 either, but it should work).

Please let me know if you have any further thoughts or data to add.  Thanks,
-----------------

Closing unless I hear more.
