### ISSUE TITLE
  I'm wondering how to view the synteny...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6643]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm wondering how to view the synteny in a particular region of the C. elegans genome in comparison with other Caenorhabditis species.<br/>Thanks!<br/>Emily</p>

**Reported by:** Emil********* (etro*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by scottcain** [comment]
Sent to the user:

To get to the synteny browser, mouse over the "Tools" link and a drop down menu will appear.  In that menu is Synteny Viewer.  Selecting that will take you to the synteny browser, where you can click on examples to get started or search for a landmark like a chromosomal region (note that you'll have to select which species to search in).  You can also turn on and off different species. 

Please let us know if you have any questions about how to use it,
