### ISSUE TITLE
  I was looking on worm base to locate ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6644]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was looking on worm base to locate the chromosome for which a certain gene is located (in this instance, mec-10). I was able to find the page on wormbase that has information about the gene, but I do not know how to find the chromosome. I would appreciate it if someone would tell me where to find the chromosome location on the page of a gene. Thank you in advance.</p>

**Reported by:** Mega* (megl************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Megan,

You were going in the right direction, If you check the gene page 
"Location" widget you can see the Chromosome and co-ordinates:

https://www.wormbase.org/species/c_elegans/gene/WBGene00003174#0-9g-10

X:8465832..8470256

Hope this helps.

Paul


On 21/09/2018 07:58, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I was looking on worm base to locate the chromosome for which a 
> certain gene is located (in this instance, mec-10). I was able to find 
> the page on wormbase that has information about the gene, but I do not 
> know how to find the chromosome. I would appreciate it if someone 
> would tell me where to find the chromosome location on the page of a 
> gene. Thank you in advance.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6644. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6644>.
>
> Reported by: Megan (meglen19@umd.edu)
> 21 Sep 18 06:58
>
> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/69.0.3497.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
