### ISSUE TITLE
  I have a list of C. briggsae genes (R...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6647]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a list of C. briggsae genes (RNA Seq), how can I find C. elegans homolog for them? (Bulk input)<br/>Thank you.</p><p>What were you doing? <br />&nbsp;&nbsp;I am a Ph. D. student at Department of Biology, McMaster University</p>

**Reported by:** Ish **** (jain*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by epaule** [comment]
try https://parasite.wormbase.org/biomart/martview/ 
You should be able to restrict the query by C.briggsae gene ids and get a table with the C.elegans orthologs.
