### ISSUE TITLE
  Dear Sir/Madam, We are submitting a C...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6649]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam,<br/>We are submitting a C. elegans research paper to eLife and they ask us to input the Research Resource Identifiers (RRIDs). We will need to upload the RRIDs for the strains we made in our lab. We see all the strain's RRIDs information are from WormBase. We were wondering how to upload our strain's information to WormBase and generate the new RRIDs?<br/>Thank you so much for the kind help and we look forward to your reply.<br/>Sincerely,<br/>visitor_name<br/>School of Biological Sciences<br/>Georgia Institute of Technology</p>

**Reported by:** Yueh******* (yzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi, thanks for contacting WormBase.

I should be able to help you get your data into WormBase and get RRIDs.

Paul

On 24/09/2018 21:20, no-reply@wormbase.org wrote:
> Question:
>
>   Dear Sir/Madam,
> We are submitting a C. elegans research paper to eLife and they ask us 
> to input the Research Resource Identifiers (RRIDs). We will need to 
> upload the RRIDs for the strains we made in our lab. We see all the 
> strain's RRIDs information are from WormBase. We were wondering how to 
> upload our strain's information to WormBase and generate the new RRIDs?
> Thank you so much for the kind help and we look forward to your reply.
> Sincerely,
> Yuehui Zhao
> School of Biological Sciences
> Georgia Institute of Technology
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6649. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6649>.
>
> Reported by: Yuehui Zhao (yzhao349@gatech.edu)
> 24 Sep 18 20:20
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Supplied RRIDs for their strain data
