### ISSUE TITLE
Dear Professor :
  I am a teacher in Southwest Uni...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6650]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear Professor :
  I am a teacher in Southwest University for Nationalities in Sichuan province in China. Recently, I isolated a nematoda in thymus of a Macaca fascicularis. Molecular identification of partial sequence of COI , 18S rRNA and 12S rRNA indicates maybe it is a filarial nematode with low identity in COI and 12S rRNA with other worms. However, I can’t confirm if it is a known species or new one.
   So, I am truly grateful to you and look forward to your good suggestion.
  If necessary, I would send the sequence to you.

Thanks!

**Reported by:** LiLi**** (leel**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/support?url=/">https://www.wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 49.0.2623.221

**Comment by khowe** [comment]
Responded to user:

Although WormBase collects and curates data on a wide variety of nematode species, we are not experts on nematode systematics and phylogenetics, so are not really in a position to give a good answer to your question.   There are a number of experts in the field that might be able to help; but to start with, I would recommend posting your question on the worm community forum:

http://forums.wormbase.org/

The "General scientific discussion" board would probably be the most appropriate place to post.
