### ISSUE TITLE
  An assembled genome of C. inopinata h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6652]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;An assembled genome of C. inopinata has recently been published (PMID: 30097582). I am wondering: what is the timeline for adding these data to wormbase? I am specifically interested in the Synteny viewer.</p>

**Reported by:** Ryan********** (rund***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by epaule** [comment]
It will be in our WS268 release, together with C.latens and some C.remanei and C.elegans strains.
I am not sure if I can update the synteny viewer in time, but will make Cactus alignments available as HAL files (so they can be at least visualised).
