### ISSUE TITLE
I am doing a lab report over c. elegans and I was ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6653]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am doing a lab report over c. elegans and I was wondering if you could help point me in the right direction towards articles about c. elegans background and research done with c. elegans. Thanks

**Reported by:** Anni* (anro***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans#4016--10">https://www.wormbase.org/species/c_elegans#4016--10</a>
**Browser:** Chrome 69.0.3497.100

**Comment by Paul-Davis** [comment]
Dear Annie,

Thank you for contacting wormbase.

WormBook might be a good source to start with.

http://www.wormbook.org/

Paul



On 28/09/2018 02:23, no-reply@wormbase.org wrote:
> offline chat I am doing a lab report over c. elegans and I was 
> wondering if you could help point me in the right direction towards 
> articles about c. elegans background and research done with c. 
> elegans. Thanks
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans#4016--10 
> https://www.wormbase.org/species/c_elegans#4016--10 
> <http://www.wormbase.org/https://www.wormbase.org/species/c_elegans#4016--10> 
>
>
> This issue has been assigned ticket number: #6653. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6653>.
>
> Reported by: Annie (anrose@siue.edu)
> 28 Sep 18 01:23
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
