### ISSUE TITLE
  Good Morning, I was wondering what th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6655]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good Morning,<br/>I was wondering what these two abbreviations mean. I sometimes see something that says NA>10 or NA 2. What is NA and what is the scale? Other times I will see OA 7 or OA>10. What is OA and what is the scale?<br/>Thank you for your help.<br/>Best,<br/>Jennell</p><p>What were you doing? <br />&nbsp;&nbsp;Searching different alleles.</p>

**Reported by:** Jenn********** (jtal***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by kyook** [comment]
Hi Jennell,

NA refers to 'Number of Alleles"
OA refers to 'Other Alleles"
These are legacy abbreviations used during pre-digital curation of
genes and alleles written by Jonathan Hodgkin and the community. They
can be found in the seminal C. elegans references books: C. elegans
and C. elegans II. NA was initially reserved to indicate there was
only one allele and was used mainly as 'NA1'.

Let me know if you need more information.

Kind regards,
Karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Fri, Sep 28, 2018 at 6:36 AM <no-reply@wormbase.org> wrote:
>
> How Do I ...?
>
>   Good Morning,
> I was wondering what these two abbreviations mean. I sometimes see something that says NA>10 or NA 2. What is NA and what is the scale? Other times I will see OA 7 or OA>10. What is OA and what is the scale?
> Thank you for your help.
> Best,
> Jennell
>
> What were you doing?
>   Searching different alleles.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #6655. Follow progress on our issue tracker.
>
> Reported by: Jennell Talley (jtalley@ggc.edu)
> 28 Sep 18 13:36
>
> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
