### ISSUE TITLE
  I am editing an article for the Onlin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6656]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am editing an article for the Online Updates column for Medical Reference Services Quarterly on WormBase. I would like to obtain permission to use screenshots to support the column. Who would be the best person to contact regarding image permissions?<br/>Please let me know if you have any questions. Thank you for your time,<br/>visitor_name</p>

**Reported by:** Emil* (evar****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by khowe** [comment]
Replied to the user:

You are free to use WormBase screenshots in your article, but we would please ask that you cite the project:

https://wormbase.org/about/citing_wormbase#0123--10
