### ISSUE TITLE
  Dear Wormbase Team, My name is visito...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6657]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase Team,<br/>My name is visitor_name and I am an PhD student, working with C. elegans.<br/>I had a question about the gene F21G4.6<br/>The gene is listed as a orthologue of the human HTT gene and I wanted to ask why it isn't called htt-1? I saw that there has been some confusion about if this is the real orthologue of the human HTT, but other teams and compagnies are using this as the human orthologue. Of what I saw they seem to have some evidence that these two proteins are orthologues. <br/>Therefore I wanted to ask you if the F21G4.6 is considered a real orthologue and why it isn't called htt-1.<br/>thank you very much.</p>

**Reported by:** Gill********** (gill***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Gilles,

Thank you for raising this issue.

This gene name was actually proposed as far back as 2013 and at the time 
the descision was taken not to accept the name association. The homology 
of F21G4.6 with huntingtin is marginal at best.  Only 1 of 10 orthology 
programs indicates a relationship between F21G4.6 and human huntingtin, 
and certainly not with reciprocal best BLAST.  Thus sequence analysis 
does not support the relationship.

This is nicely visualised on the Alliance of Genome Resources website:

C.elegans F21G4.6
https://www.alliancegenome.org/gene/WB:WBGene00009027#orthology

Switching the display to have no filtering you can see that only Panther 
predicts orthology between the other Model organism htt genes and no 
match to human.

Human HTT
https://www.alliancegenome.org/gene/HGNC:4851#orthology

Here you can see that the orthology between human HTT and the other 
model species is well observed while C. elegans is only predicted by 
Panther.

As was said back in 2013. If you have some other data that would 
strongly support the relationship we can revisit this decision, if not 
then the association of F21G4.6 and human huntingtin probably shouldn't 
be made?

I hope this explains things adequately.

Paul


On 02/10/2018 14:32, no-reply@wormbase.org wrote:
> Question:
>
>   Dear Wormbase Team,
> My name is Gilles Tossing and I am an PhD student, working with C. 
> elegans.
> I had a question about the gene F21G4.6
> The gene is listed as a orthologue of the human HTT gene and I wanted 
> to ask why it isn't called htt-1? I saw that there has been some 
> confusion about if this is the real orthologue of the human HTT, but 
> other teams and compagnies are using this as the human orthologue. Of 
> what I saw they seem to have some evidence that these two proteins are 
> orthologues.
> Therefore I wanted to ask you if the F21G4.6 is considered a real 
> orthologue and why it isn't called htt-1.
> thank you very much.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6657. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6657>.
>
> Reported by: Gilles Tossing (gilles.tossing@umontreal.ca)
> 02 Oct 18 13:32
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/69.0.3497.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
