### ISSUE TITLE
  Hi there,  1) I am annotating some RN...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6658]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there, <br/>1) I am annotating some RNAseq results using R and I am using the celegans.db package. However it seems that this is relatively old and I wanted to know if there is a newer annotator or a way to use wormbase to get the annotations? Obviously i don't expect a step by step instruction but more a general pointer. So far I have been using Wormmine, which brings me to question 2<br/>2) using the Wormmine "brief description" I noted that this does not include the automated descriptions that are associated with many genes like:<br/>"RNA sequencing and microarray studies indicate that C34F11.8 is affected by Rotenone, 4-bromodiphenyl ether, Ag nanoparticles, Resveratrol, Quercetin, Humic substances, single-walled carbon nanotubes, and Selenium; microarray and RNA sequencing studies indicate that C34F11.8 is enriched in the hypodermis and in the FLP neurons."<br/>how do I get those? <br/>thanks</p><p>What were you doing? <br />&nbsp;&nbsp;RNA seq analysis</p>

**Reported by:** mich*** (psch***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by WenChenWormBase** [comment]
Hi Michael,

for #2, you can use SimpleMine to get the automated description.
https://www.wormbase.org/tools/mine/simplemine.cgi
At this moment, automated description is provided only when Concise
Description is not available.

The sample description that you provided are summaries from expression
clusters generated from high throughput data. Starting from WS267 or WS268,
they will be removed from automated descriptions.  If expression cluster
summary is all you want, I can provide you a file listing summary for all
genes.

Wen Chen
Curator, WormBase

On Tue, Oct 2, 2018 at 8:28 AM <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Hi there,
> 1) I am annotating some RNAseq results using R and I am using the
> celegans.db package. However it seems that this is relatively old and I
> wanted to know if there is a newer annotator or a way to use wormbase to
> get the annotations? Obviously i don't expect a step by step instruction
> but more a general pointer. So far I have been using Wormmine, which brings
> me to question 2
> 2) using the Wormmine "brief description" I noted that this does not
> include the automated descriptions that are associated with many genes like:
> "RNA sequencing and microarray studies indicate that C34F11.8 is affected
> by Rotenone, 4-bromodiphenyl ether, Ag nanoparticles, Resveratrol,
> Quercetin, Humic substances, single-walled carbon nanotubes, and Selenium;
> microarray and RNA sequencing studies indic! ate that C34F11.8 is enriched
> in the hypodermis and in the FLP neurons."
> how do I get those?
> thanks
>
> What were you doing?
>   RNA seq analysis
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6658. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6658>.
>
> Reported by: michael (pscheck@scripps.edu)
> 02 Oct 18 15:28
>
> Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:59.0) Gecko/20100101
> Firefox/59.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
From User: 

Beautiful, the simplemine seems to do most of the job I need.

 

1) yes please provide me with an expression cluster listing. That would be swell.

2) Is there a way in R to automatically go to the simplemine and get the info on the fly, or alternatively a way to download it for all genes so that I can do that locally

 

You guys are great,

 

michael
