### ISSUE TITLE
  Hi, I have found myself looking up kn...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6660]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I have found myself looking up known phenotypes (mutants and RNAi) for several genes on the wormbase website. Thank you for providing such a cool and well-organized tool!<br/>I was wondering if I could make this process more efficient and whether you could point me to a download option for the phenotype information you have on the website or if there is a programmatic access that I have missed. Basically, there is so much useful information on the website that I would like to access either via download or R - does this exist? I was not able to find anything on the biomaRt man page or elsewhere.<br/>Thank you very much for your help!<br/>Best,<br/>Cyril</p>

**Reported by:** Cyri********* (cyri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

**Comment by WenChenWormBase** [comment]
Dear Cyril,

Have you tried WormMine or SimpleMine? Both have phenotype information and
a lot more. Please let us know if you have any problem getting what you
want.

They can be accessed via the WormBase Tools menu.

https://wormbase.org/tools/mine/simplemine.cgi
http://intermine.wormbase.org/tools/wormmine/begin.do

Wen.

On Tue, Oct 2, 2018 at 1:23 PM <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Hi,
> I have found myself looking up known phenotypes (mutants and RNAi) for
> several genes on the wormbase website. Thank you for providing such a cool
> and well-organized tool!
> I was wondering if I could make this process more efficient and whether
> you could point me to a download option for the phenotype information you
> have on the website or if there is a programmatic access that I have
> missed. Basically, there is so much useful information on the website that
> I would like to access either via download or R - does this exist? I was
> not able to find anything on the biomaRt man page or elsewhere.
> Thank you very much for your help!
> Best,
> Cyril
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6660. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6660>.
>
> Reported by: Cyril Statzer (cyril-statzer@ethz.ch)
> 02 Oct 18 20:23
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15
> (KHTML, like Gecko) Version/11.1 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by chris-grove** [comment]
My email to user:
"""
First, you can have a look at our FTP site, in this directory in particular:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/

The file called "phenotype_association.WS266.wb" (general name "phenotype_association.WSXXX.wb" where WSXXX is the version release) will have a summary of all allele and RNAi based phenotypes. The file format is similar to the Gene Ontology gene association file (GAF) format:

http://www.geneontology.org/page/go-annotation-file-format-20

This file is the most readily parse-able file immediately available. Note that phenotypes are listed as WBPhenotype IDs, so you'll need to map back to the human readable phenotype term names, either using the phenotype .OBO file (from the same FTP directory above):

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/phenotype_ontology.WS266.obo

or using a WormMine query (import the following XML into the WormMine QueryBuilder):

`<query name="" model="genomic" view="Phenotype.identifier Phenotype.name" longDescription="" sortOrder="Phenotype.identifier asc">
</query>`
 
Here's the WormMine page:

http://intermine.wormbase.org/tools/wormmine/begin.do

You can also get the allele phenotypes for each gene in WormMine using this query: 

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>`

and all RNAi phenotypes using this query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.RNAiResult.phenotype.identifier Gene.RNAiResult.phenotype.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>`

There are a couple of RNAi-specific phenotype files in the FTP directory as well you can take a look at:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/rnai_phenotypes.WS266.wb

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/rnai_phenotypes_quick.WS266.wb

Note that the "current-production-release" FTP directory will always have the data that is in sync with our live website, so you can bookmark that for future reference.

Let us know if you have any questions.
"""

**Comment by WenChenWormBase** [comment]
From user: 

The problem could be solved by downloading the phenotype files from the FTP server. In this way, I have the entire phenotype table available in my R session and can easily work with it:)

Thank you,
Cyril
