### ISSUE TITLE
  please where is the link to the best ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6666]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;please where is the link to the best guide on how to use wormbase effectively and efficiently? thanks. i am waiting and its urgent</p><p>What were you doing? <br />&nbsp;&nbsp;studying about C. elegans</p>

**Reported by:** solo*** (aszy***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by fayerodgers** [comment]
Hi Solomon,

Your best bet would be to refer to this chapter, which was published this year and contains the most up to date information:

https://www.ncbi.nlm.nih.gov/pubmed/29761466

We also have support pages on the website: https://wormbase.org/about/userguide/for_users#0231--10

Best,
Faye

**Comment by chris-grove** [comment]
In addition to Faye's suggestion, you may also want to look at our Wiki:

http://wiki.wormbase.org/index.php/Main_Page

If you have specific questions, please let us know.
