### ISSUE TITLE
  I really want to appreciate Faye Rodg...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6670]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I really want to appreciate Faye Rodgers and Chris Grove for their prompt response to my request. It was really helpful.<br/>I have one more request. There are some very important pages I really wish to print and read. However, the challenge is that the site page is not in a printable format. I wish I could download a page as a pdf and really study. An example of such a page https://wormbase.org/about/userguide/nomenclature#9g725c16hm4jba80iekfd3l--10<br/>How can I print such effectively and well formatted? Also urgent please sir. I am billed for a conference and need these information. Waiting…</p><p>What were you doing? <br />&nbsp;&nbsp;sourcing information</p>

**Reported by:** solo*** (aszy***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by chris-grove** [comment]
I was able to save your example page as a PDF using my web browser's Print function (using the Save as PDF option). I've attached the PDF to this email. I used Chrome to download the PDF, but I believe most web browsers should give you a Print -> Save as PDF option.
