### ISSUE TITLE
  Why am i not able to browse Wormbase ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6671]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Why am i not able to browse Wormbase . it is very slow</p>

**Reported by:** Jaga************ (jsri***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by chris-grove** [comment]
I replied to user. Have not heard back. Will reopen if necessary.
