### ISSUE TITLE
WormBase wiki issues

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6672]
hi I am having problems logging in the WormBase wiki page (reproduced by @vanaukenk).
Attached a screenshot. 
Tried with multiple browsers (with cookies enabled)
Can someone please help?
<img width="370" alt="screen shot 2018-10-10 at 12 09 34 pm" src="https://user-images.githubusercontent.com/901243/46753552-ca352f80-cc85-11e8-876a-c09b14d66e9b.png">

**Comment by chris-grove** [comment]
Confirmed on my end as well

**Comment by chris-grove** [comment]
Login is working for me now on the Wiki. I'm closing the ticket.

@draciti @vanaukenk 
If it still isn't working for you, please reopen this ticket.
