### ISSUE TITLE
The protein FL81_01584 on wormbase is truncated co...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6677]
*Help Desk query collected when no chat operators were online. Follow up required.*

The protein FL81_01584 on wormbase is truncated compared to the one on ParaSite - the C terminus is missing.

**Reported by:** scot******** (sari*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_remanei/gene/PRJNA248909_FL81_01584#0m-9g-3">https://www.wormbase.org/species/c_remanei/gene/PRJNA248909_FL81_01584#0m-9g-3</a>
**Browser:** Firefox 62.0

**Comment by chris-grove** [comment]
Thanks for the heads up! One of our sequence curators will get back to you soon (probably early next week).

**Comment by khowe** [comment]
User wrote to ParaSite helpdesk, and problem has been resolved (FTP site was pointing to the wrong file, and we informed the user that ParaSite and WormBase are serving different versions of the annotation for this genome, which will re-align in due course).
