### ISSUE TITLE
  Hello WB team, I have been working on...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6678]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello WB team,<br/>I have been working on some synteny analysis and I have noticed that in  regions that contain non-conserved genes we get three different answers from the three prediction programs (Mercator, PECAN, and OrthoCluster). In my specific case Mercator mapped a synteny block to one region in briggsae, OrthoCluster mapped the same block to a different region in briggsae, and PECAN did not predict a synteny region at all. Conversely, when looking at the well-conserved region around let-60, all three programs predict generally the same thing (as one would expect/hope). <br/>I am interested in the underlying data, eg the orthology predictions generated by Mercator or OrthoCluster. Is there a way I can access this data through WB? I would be interested in knowing the significance values attached to different synteny blocks by the different programs.<br/>Thank you,<br/>Ryan</p>

**Reported by:** Ryan********** (rund***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by epaule** [comment]
our multple-genome alignments were done with an EnsEMBL Compara pipeline that used Blast + Mercator + Pecan.
I am not sure if the MSA data that drives the GBrowse-Syn can be extracted from it and I know that we shifted to pair-wise methods in the last decade using Progressive Cactus.
Similar we changed from using synteny as orthology source and used external providers (like OMA, PantherDB, inParanoid and also the protein based EnsEMBL-Compara).

If you are interested in the parwise orthologs, you can either download them from the homology section of Wormbase, or grab the meta-analysis from DIOPT at the AGR site (https://www.alliancegenome.org/).
For synteny, you could also grab the PastCons and PhyloP wiggle data from our UCSC track hub (search for WormBase in their track list), as well as see the pairwise alignments.
