### ISSUE TITLE
Dear Friend, I want have a construct appearing in ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6684]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear Friend, I want have a construct appearing in wormbase (WormBase ID:
WBCnstr00038408 [ins-31p::ins-31::sfGFP; -2,035 ~750]). I am wondering how and where can I get it? 

Thanks you lots.

Best,

Haijun

**Reported by:** Haij***** (haij***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/all/construct/WBCnstr00038408#01--10">https://wormbase.org/species/all/construct/WBCnstr00038408#01--10</a>
**Browser:** Chrome 62.0.3202.89

**Comment by chris-grove** [comment]
My email to user:
"If you turn on the "References" widget (from the panel on the left side of the screen) on the construct page:


https://wormbase.org/species/all/construct/WBCnstr00038408#013--10


You will see the paper that the construct and corresponding transgene (bxEx200) were originally reported in. I would suggest contacting the authors of that paper to see if they can provide you with the construct."
