### ISSUE TITLE
  Biofunction role table is not display...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6690]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Biofunction role table is not displaying properly, full table can only be seen if you scroll horizontally.  Also values in Detection method and Extraction method columns should follow capitalization as shown in the tree display.</p>

**Reported by:** Kare****** (kare**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by sibyl229** [comment]
Hi @kyook the biofunction table problem should be fixed on staging now: https://staging.wormbase.org/resources/molecule/WBMol:00006312#021534--10 Thanks!
