### ISSUE TITLE
  How do I use the nlg-1(ok259) WT and ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6691]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I use the nlg-1(ok259) WT and mutant sequences proved to get the spliced sequence, in order to transcribe into an amino acid and later protein sequence?</p>

**Reported by:** Lucy (lucy*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by chris-grove** [comment]
Could you clarify your question? Are you asking about how to use the WormBase website?
