### ISSUE TITLE
Where is the Sequences Box?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6693]
*Help Desk query collected when no chat operators were online. Follow up required.*

Where is the Sequences Box?

**Reported by:** Ana ********* (20ro*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00004212#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00004212#0-9g-3</a>
**Browser:** Chrome 70.0.3538.67

**Comment by Paul-Davis** [comment]
Dear Ana,

I am not 100% sure which sequence box you are after as the page you 
submitted your question from had the Sequence widget open already.

If you are after the DNA or protein sequence from one of the gene 
products, these can be downloaded by clicking on one of the helix icons 
next to the product you want the sequence for in the sequence widget.

https://www.wormbase.org/species/c_elegans/gene/WBGene00004212#-g-10

CDS: F42G9.9a or Protein: PTL-1, isoform a

I hope this helps.

Paul






On 28/10/2018 03:12, no-reply@wormbase.org wrote:
> offline chat Where is the Sequences Box?
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans/gene/WBGene00004212#0-9g-3 
> https://www.wormbase.org/species/c_elegans/gene/WBGene00004212#0-9g-3 
> <http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00004212#0-9g-3> 
>
>
> This issue has been assigned ticket number: #6693. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6693>.
>
> Reported by: Ana ********* (20ro*******************)
> 28 Oct 18 03:12
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
