### ISSUE TITLE
Hi, just a question. When in the description of a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6694]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, just a question. When in the description of a mutant there is an "X". That means that it has been backcrossed ten times or none? For example here...
https://wormbase.org/species/c_elegans/strain/DH235#02--10

**Reported by:** Paol* (paol**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/strain/DH235#02--10">https://wormbase.org/species/c_elegans/strain/DH235#02--10</a>
**Browser:** Chrome 70.0.3538.77

**Comment by Paul-Davis** [comment]
Hi Paola,

It seems that there is a bug in the display for the strain you linked to as your example.

This should read "x2"

I will get the web team to take a look at fixing this.

Thanks for pointing it out.

Paul

**Comment by Paul-Davis** [comment]
![6694_ticket](https://user-images.githubusercontent.com/717707/47643543-ab7ad800-db63-11e8-8df8-44576ce7cc00.png)
It seems that the web code isn't picking up all of the data stored under the strain:outcrossed field.

**Comment by a8wright** [comment]
Hi Paul,

This turned out to be a small bug in the API endpoint. It is now fixed on staging and will be fixed on production as we roll out the next release!

**Comment by a8wright** [comment]
Hi Paul,

This turned out to be a small bug in the API endpoint. It is now fixed on staging and will be fixed on production as we roll out the next release!

**Comment by Paul-Davis** [comment]
Looks fixed on both staging and live

**Comment by Paul-Davis** [comment]
Reported the fix to the user.
