### ISSUE TITLE
  We would like to give a 3 letter gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6696]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We would like to give a 3 letter gene name to a number of genes based on the sequence information we find when treating mutants with specific genotoxins, thus revealing a function of a gene product in a specific DNA repair pathway. Should this be done via the gene name form? How is this usually coordinated with data publication? </p><p>What were you doing? <br />&nbsp;&nbsp;We treated a large set of likely DNA repair mutants (by homology search) with a range of genotoxins and identified mutation types and profiles</p>

**Reported by:** Bett********* (b.me****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Bettina,

Gene naming and 3 letter gene classes can be requested via the 
genenames@wormbase.org email list (cc'd). Prof. Tim Schedl presides over 
the naming and co-ordination of C. elegans gene names. Once a gene 
designation is decided upon, then these can be used in publications with 
the option to keep the confidential until a time of your choosing.

I hope this gives you enough detail.

Paul



On 29/10/2018 16:16, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   We would like to give a 3 letter gene name to a number of genes 
> based on the sequence information we find when treating mutants with 
> specific genotoxins, thus revealing a function of a gene product in a 
> specific DNA repair pathway. Should this be done via the gene name 
> form? How is this usually coordinated with data publication?
>
> What were you doing?
>   We treated a large set of likely DNA repair mutants (by homology 
> search) with a range of genotoxins and identified mutation types and 
> profiles
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6696. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6696>.
>
> Reported by: Bettina Meier (b.meier@dundee.ac.uk)
> 29 Oct 18 16:16
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
