### ISSUE TITLE
Hello,
The RNAi Database is not currently working....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6697]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
The RNAi Database is not currently working. There is a note that says Database connection failed, please report to database administrator.

**Reported by:** MiKa*** (mika*****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans#410--10">https://wormbase.org/species/c_elegans#410--10</a>
**Browser:** Safari 12.0

**Comment by chris-grove** [comment]
It seems you are referring to the link out to the RNAi-DB website:

http://www.rnai.org/

This site is external to WormBase, but if you'd like, you can email the administrators via the following email address:

admin@rnai.org

We will contact them to let them know as well.

Thank you for the heads up.

**Comment by chris-grove** [comment]
I've contacted the admins at rnai.org

**Comment by chris-grove** [comment]
Site is back up
