### ISSUE TITLE
  Dear support team, I ran the followin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6699]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear support team,<br/>I ran the following query on WormMine to get protein location data. The location data in the output seem to be wrong.<br/>query<br/><query name="" model="genomic" view="Protein.CDSs.symbol Protein.CDSs.chromosome.primaryIdentifier Protein.CDSs.chromosomeLocation.strand Protein.CDSs.chromosomeLocation.start Protein.CDSs.chromosomeLocation.end" longDescription="returns the protein sequences of all current proteins of a species" constraintLogic="B and A"><br/><constraint path="Protein.organism.name" code="B" op="=" value="Caenorhabditis elegans"></constraint><br/><constraint path="Protein.CDSs.primaryIdentifier" code="A" op="IS NOT NULL"></constraint><br/></query><br/>first line of output<br/>2L52.1a	II	1	1867	1911<br/>should be approximately 1900 - 4700<br/>Any help is appreciated. Thank you.<br/>Harald Hutter<br/>_________________________________<br/>Harald Hutter, Department of Biological Sciences<br/>Simon Fraser University, Burnaby, BC, Canada<br/>phone 778-782-4803, email: visitor_email</p>

**Reported by:** hutt*********
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4

**Comment by raymond91125** [comment]
Query that generates both correct and 'incorrect' answers:

<query model="genomic" view="CDS.chromosome.primaryIdentifier 
CDS.chromosome.organism.name CDS.symbol CDS.locations.start 
CDS.locations.end CDS.locations.strand 
CDS.chromosomeLocation.feature.primaryIdentifier 
CDS.chromosomeLocation.start CDS.chromosomeLocation.end 
CDS.chromosomeLocation.strand" 
sortOrder="CDS.chromosome.primaryIdentifier ASC" >
   <constraint path="CDS.symbol" op="=" value="2L52.1a" code="A" />
</query>

Column 9 "CDS Chromosome Location. End" should perhaps be "4663".


Raymond


On 30/10/2018 10:37 AM, Paulo Nuin wrote:
> Hi Harald
>
> I didn’t get the query you run. Can you paste it in a message so I can help you further?
>
> Cheers
> Paulo
>
>
>
>> On Oct 30, 2018, at 11:03 AM, no-reply@wormbase.org wrote:
>>
>> Bug Report
>>    Dear support team,
>> I ran the following query on WormMine to get protein location data. The location data in the output seem to be wrong.
>> query
>>
>>
>>
>>
>> first line of output
>> 2L52.1a	II	1	1867	1911
>> should be approximately 1900 - 4700
>> Any help is appreci! ated. Thank you.
>> Harald Hutter
>> _________________________________
>> Harald Hutter, Department of Biological Sciences
>> Simon Fraser University, Burnaby, BC, Canada
>> phone 778-782-4803, email: hutter@sfu.ca
>>
>> Submitted From:
>>    support /tools/support
>>
>> This issue has been assigned ticket number: #6699. Follow progress on our issue tracker.
>>
>>
>> Reported by: hutter@sfu.ca
>> 30 Oct 18 17:03
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4
>>
>> This question was reported via the web interface at wormbase.org. You can also email us directly.
>>
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>> ---
>> You received this message because you are subscribed to the Google Groups "WormBase: help" group.
>> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi,

this is the query I ran (I want the location of all the proteins). 

<query name="" model="genomic" view="Protein.CDSs.symbol Protein.CDSs.chromosome.primaryIdentifier Protein.CDSs.chromosomeLocation.strand Protein.CDSs.chromosomeLocation.start Protein.CDSs.chromosomeLocation.end" longDescription="returns the protein sequences of all current proteins of a species" constraintLogic="B and A">
  <constraint path="Protein.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Protein.CDSs.primaryIdentifier" code="A" op="IS NOT NULL"/>
</query>


I think my query gives me the location of the first exon for each protein.
Raymond’s query seems to give the location of all the exons separately. Is there a way to just get the beginning of the first exon and the end of the last exon?

Thanks,
Harald

**Comment by raymond91125** [comment]
Hi Harald and Raymond


> I think my query gives me the location of the first exon for each protein.


Raymon’s query displays the “problem” quite clearly. There’s an issue on how InterMine (now WormMine) deals with the ingestion of exons. Our GFF3 file has the exons linked to transcript entity, i.e.

Transcript:Y74C9A.3.1 has 5 exons and is set on the GFF3:

I       WormBase        mRNA    4116    10230   .       -       .       ID=Transcript:Y74C9A.3.1;Parent=WBGene00022277;Name=Y74C9A.3.1;wormpep=WP:CE28146;locus=homt-1
I       WormBase        exon    4116    4358    .       -       .       ID=Exon2;Parent=Transcript:Y74C9A.3.1
I       WormBase        exon    5195    5296    .       -       .       ID=Exon3;Parent=Transcript:Y74C9A.3.1
I       WormBase        exon    6037    6327    .       -       .       ID=Exon4;Parent=Transcript:Y74C9A.3.1
I       WormBase        exon    9727    9846    .       -       .       ID=Exon5;Parent=Transcript:Y74C9A.3.1
I       WormBase        exon    10095   10230   .       -       .       ID=Exon6;Parent=Transcript:Y74C9A.3.1

With a first line with a full mRNA/transcript information (notice the start and end 4116, 10230)  and each exon in a separate line connected by the Parent key.

At the same time CDSs in our GFF3 for the same transcript are like this in the GFF3

I       WormBase        CDS     4221    4358    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1;Name=Y74C9A.3;prediction_status=Confirmed;wormpep=WP:CE28146;locus=homt-1
I       WormBase        CDS     5195    5296    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
I       WormBase        CDS     6037    6327    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
I       WormBase        CDS     9727    9846    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
I       WormBase        CDS     10095   10148   .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1

Where there’s no “master” line with a start and end for the whole CDS, and where CDS exons are not linked to a CDS parent, but to a Transcript parent.

InterMine doesn’t have anything in its code that allows that these CDS exons to be loaded separately, as their code just see the ID=CDS:Y74C9A.3 in the last column and every time a line with the same ID is read, information is being overwritten. We have tried in the past to create a “master” CDS line, but we run into some problems. There are some InterMine code changes that were tried to, but failed with our GFF3 file. The only change that worked was to mark each assigned exon on the third column with an unique ID 

I       WormBase        exon    4116    4358    .       -       .       ID=Exon2;Parent=Transcript:Y74C9A.3.1
											     ^^^^^^^^^^
in order to InterMine to separate them. We also had problems in the past with exon, transcript and CDS lengths due to this, but they were solved with the introduction of respective FASTA files a couple of builds ago.


> Raymond’s query seems to give the location of all the exons separately. Is there a way to just get the beginning of the first exon and the end of the last exon?


I copied the email to Chris Grove that might be able to help you more on the query. As the exons are separate entities, I don’t know if InterMine allows you to constrain all related items into one.

Cheers
Paulo

**Comment by raymond91125** [comment]
Hi Paulo,

in this case it might be easier if just extract the information from the gff file. I saw in your sample that the gff file has ‘mRNA’ entries. It seems that these lines have the information I want. So can I just extract all lines containing ‘mRNA’ from the gff file to get the location data?

Cheers,
Harald

**Comment by raymond91125** [comment]
Hi Harald

I would check with a curator, I am not completely sure about differences between mRNA and CDS in C. elegans, 

With this caveat in mind, would this query work for you?

<query model="genomic" view="MRNA.primaryIdentifier MRNA.symbol MRNA.CDSs.primaryIdentifier MRNA.CDSs.symbol MRNA.chromosomeLocation.start MRNA.chromosomeLocation.end" sortOrder="MRNA.primaryIdentifier ASC" >
</query>

Cheers
Paulo

**Comment by raymond91125** [comment]
Hi Paulo,

that is exactly what I want. Thank you very much.

Harald

**Comment by raymond91125** [comment]
Hi Harald

Glad that it worked. If you somewhat constrain on the mRNA, the correct exon loading would give you the start and end. Just be sure if CDS/mRNA biological differences are not an issue here.

Cheers
Paulo

**Comment by raymond91125** [comment]
Hi Paulo,

FYI, the mRNA span should be greater than (or equal to) that of the 
corresponding CDS. The span is greater when there are untranslated 
5-prime and 3-prime sequences in terminal exons.

Thanks.

Raymond


On 30/10/2018 11:44 AM, Paulo Nuin wrote:
> Hi Harald
>
> I would check with a curator, I am not completely sure about differences between mRNA and CDS in C. elegans,
>
> With this caveat in mind, would this query work for you?
>
> <query model="genomic" view="MRNA.primaryIdentifier MRNA.symbol MRNA.CDSs.primaryIdentifier MRNA.CDSs.symbol MRNA.chromosomeLocation.start MRNA.chromosomeLocation.end" sortOrder="MRNA.primaryIdentifier ASC" >
> </query>
>
> Cheers
> Paulo
>
>
>
>> On Oct 30, 2018, at 12:34 PM, Harald Hutter <harald_hutter@sfu.ca> wrote:
>>
>> Hi Paulo,
>>
>> in this case it might be easier if just extract the information from the gff file. I saw in your sample that the gff file has ‘mRNA’ entries. It seems that these lines have the information I want. So can I just extract all lines containing ‘mRNA’ from the gff file to get the location data?
>>
>> Cheers,
>> Harald
>>
>>> On Oct 30, 2018, at 11:22 AM, Paulo Nuin <paulo.nuin@gmail.com> wrote:
>>>
>>> Hi Harald and Raymond
>>>
>>>
>>>> I think my query gives me the location of the first exon for each protein.
>>>
>>> Raymon’s query displays the “problem” quite clearly. There’s an issue on how InterMine (now WormMine) deals with the ingestion of exons. Our GFF3 file has the exons linked to transcript entity, i.e.
>>>
>>> Transcript:Y74C9A.3.1 has 5 exons and is set on the GFF3:
>>>
>>> I       WormBase        mRNA    4116    10230   .       -       .       ID=Transcript:Y74C9A.3.1;Parent=WBGene00022277;Name=Y74C9A.3.1;wormpep=WP:CE28146;locus=homt-1
>>> I       WormBase        exon    4116    4358    .       -       .       ID=Exon2;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        exon    5195    5296    .       -       .       ID=Exon3;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        exon    6037    6327    .       -       .       ID=Exon4;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        exon    9727    9846    .       -       .       ID=Exon5;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        exon    10095   10230   .       -       .       ID=Exon6;Parent=Transcript:Y74C9A.3.1
>>>
>>> With a first line with a full mRNA/transcript information (notice the start and end 4116, 10230)  and each exon in a separate line connected by the Parent key.
>>>
>>> At the same time CDSs in our GFF3 for the same transcript are like this in the GFF3
>>>
>>> I       WormBase        CDS     4221    4358    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1;Name=Y74C9A.3;prediction_status=Confirmed;wormpep=WP:CE28146;locus=homt-1
>>> I       WormBase        CDS     5195    5296    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        CDS     6037    6327    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        CDS     9727    9846    .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
>>> I       WormBase        CDS     10095   10148   .       -       0       ID=CDS:Y74C9A.3;Parent=Transcript:Y74C9A.3.1
>>>
>>> Where there’s no “master” line with a start and end for the whole CDS, and where CDS exons are not linked to a CDS parent, but to a Transcript parent.
>>>
>>> InterMine doesn’t have anything in its code that allows that these CDS exons to be loaded separately, as their code just see the ID=CDS:Y74C9A.3 in the last column and every time a line with the same ID is read, information is being overwritten. We have tried in the past to create a “master” CDS line, but we run into some problems. There are some InterMine code changes that were tried to, but failed with our GFF3 file. The only change that worked was to mark each assigned exon on the third column with an unique ID
>>>
>>> I       WormBase        exon    4116    4358    .       -       .       ID=Exon2;Parent=Transcript:Y74C9A.3.1
>>> 											     ^^^^^^^^^^
>>> in order to InterMine to separate them. We also had problems in the past with exon, transcript and CDS lengths due to this, but they were solved with the introduction of respective FASTA files a couple of builds ago.
>>>
>>>
>>>> Raymond’s query seems to give the location of all the exons separately. Is there a way to just get the beginning of the first exon and the end of the last exon?
>>>
>>> I copied the email to Chris Grove that might be able to help you more on the query. As the exons are separate entities, I don’t know if InterMine allows you to constrain all related items into one.
>>>
>>> Cheers
>>> Paulo
>>>
>>>
>>>
>>>
>>>
>>>> On Oct 30, 2018, at 11:55 AM, Harald Hutter <harald_hutter@sfu.ca> wrote:
>>>>
>>>> Hi,
>>>>
>>>> this is the query I ran (I want the location of all the proteins).
>>>>
>>>> <query name="" model="genomic" view="Protein.CDSs.symbol Protein.CDSs.chromosome.primaryIdentifier Protein.CDSs.chromosomeLocation.strand Protein.CDSs.chromosomeLocation.start Protein.CDSs.chromosomeLocation.end" longDescription="returns the protein sequences of all current proteins of a species" constraintLogic="B and A">
>>>> <constraint path="Protein.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>
>>>> <constraint path="Protein.CDSs.primaryIdentifier" code="A" op="IS NOT NULL"/>
>>>> </query>
>>>>
>>>>
>>>> I think my query gives me the location of the first exon for each protein.
>>>> Raymond’s query seems to give the location of all the exons separately. Is there a way to just get the beginning of the first exon and the end of the last exon?
>>>>
>>>> Thanks,
>>>> Harald
>>>>
>>>>
>>>>
>>>>> On Oct 30, 2018, at 10:46 AM, Lee, Raymond <raymond@caltech.edu> wrote:
>>>>>
>>>>> Query that generates both correct and 'incorrect' answers:
>>>>>
>>>>> <query model="genomic" view="CDS.chromosome.primaryIdentifier
>>>>> CDS.chromosome.organism.name CDS.symbol CDS.locations.start
>>>>> CDS.locations.end CDS.locations.strand
>>>>> CDS.chromosomeLocation.feature.primaryIdentifier
>>>>> CDS.chromosomeLocation.start CDS.chromosomeLocation.end
>>>>> CDS.chromosomeLocation.strand"
>>>>> sortOrder="CDS.chromosome.primaryIdentifier ASC" >
>>>>> <constraint path="CDS.symbol" op="=" value="2L52.1a" code="A" />
>>>>> </query>
>>>>>
>>>>> Column 9 "CDS Chromosome Location. End" should perhaps be "4663".
>>>>>
>>>>>
>>>>> Raymond
>>>>>
>>>>>
>>>>> On 30/10/2018 10:37 AM, Paulo Nuin wrote:
>>>>>> Hi Harald
>>>>>>
>>>>>> I didn’t get the query you run. Can you paste it in a message so I can help you further?
>>>>>>
>>>>>> Cheers
>>>>>> Paulo
>>>>>>
>>>>>>
>>>>>>
>>>>>>> On Oct 30, 2018, at 11:03 AM, no-reply@wormbase.org wrote:
>>>>>>>
>>>>>>> Bug Report
>>>>>>> Dear support team,
>>>>>>> I ran the following query on WormMine to get protein location data. The location data in the output seem to be wrong.
>>>>>>> query
>>>>>>>
>>>>>>>
>>>>>>>
>>>>>>>
>>>>>>> first line of output
>>>>>>> 2L52.1a	II	1	1867	1911
>>>>>>> should be approximately 1900 - 4700
>>>>>>> Any help is appreci! ated. Thank you.
>>>>>>> Harald Hutter
>>>>>>> _________________________________
>>>>>>> Harald Hutter, Department of Biological Sciences
>>>>>>> Simon Fraser University, Burnaby, BC, Canada
>>>>>>> phone 778-782-4803, email: hutter@sfu.ca
>>>>>>>
>>>>>>> Submitted From:
>>>>>>> support /tools/support
>>>>>>>
>>>>>>> This issue has been assigned ticket number: #6699. Follow progress on our issue tracker.
>>>>>>>
>>>>>>>
>>>>>>> Reported by: hutter@sfu.ca
>>>>>>> 30 Oct 18 17:03
>>>>>>>
>>>>>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4
>>>>>>>
>>>>>>> This question was reported via the web interface at wormbase.org. You can also email us directly.
>>>>>>>
>>>>>>>
>>>>>>> -- 
>>>>>>> -- 
>>>>>>> You received this message because you are subscribed to the "WormBase: help" group.
>>>>>>> To post to this group, send email to help@wormbase.org
>>>>>>> To unsubscribe from this group, send email to
>>>>>>> help+unsubscribe@wormbase.org
>>>>>>> For more options, visit this group at
>>>>>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>>>>>
>>>>>>> ---
>>>>>>> You received this message because you are subscribed to the Google Groups "WormBase: help" group.
>>>>>>> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org.
>>>>>
>>>>> -- 
>>>>> __
>>>>> Raymond Lee
>>>>> raymond@caltech.edu
>>>>> http://www.WormBase.org/
>>>>> California Institute of Technology
>>>>> Division of Biology and Biological Engineering
>>>>> Mail Code 156-29
>>>>> Pasadena, CA 91125
>>>>> USA
>>>>> tel: 626.395.2687
>>>>>

-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by khowe** [comment]
Hi Harald, 

The "mRNA" lines in the GFF3 represent the extent of the full-length transcript that encodes the protein. The region can (and often does) contain UTRs and introns. But if you are interested in the general location of the protein, this will be good enough. 

If you are rather interested in the specific regions of the genome that are translated to give a protein (i.e. the coding portions of exons), the CDS features contain this info. As per the GFF3 spec, a single CDS feature can be split across several lines, each line containing a "segment" of the CDS. Segments sharing the same ID are part of the same CDS, and therefore can be glued together to give the ATG->STOP that is translated to peptide sequence. 

Kevin

**Comment by raymond91125** [comment]
Hi Raymond

Thanks, I am more used to human transcripts, etc, just wasn’t sure for C. elegans. Chris already explained to me, but old age memory is a problem.

Cheers
Paulo
