### ISSUE TITLE
  Hi there, I could not download the Sp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6702]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there,<br/>I could not download the Spirometra protein in fasta format from the website. Could you please provide me for the information. Thank you very much in advance.</p><p>What were you doing? <br />&nbsp;&nbsp;Blood parasite</p>

**Reported by:** Siva*************** (siva********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

The/Spirometra erinaceieuropaei /protein data is available from WormBase 
Parasite

https://parasite.wormbase.org/Spirometra_erinaceieuropaei_prjeb1202/Info/Index/

The fasta file option is available in the Downloads section on the front 
page.

Paul


On 31/10/2018 02:58, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi there,
> I could not download the Spirometra protein in fasta format from the 
> website. Could you please provide me for the information. Thank you 
> very much in advance.
>
> What were you doing?
>   Blood parasite
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6702. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6702>.
>
> Reported by: Sivapong Sungpradit (sivapong.sun@mahidol.edu)
> 31 Oct 18 02:58
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/70.0.3538.77 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
