### ISSUE TITLE
g/jbrowse feature request.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6703]
Hey Scott,

Would it be possible to get an additional set of attributes from the gff3 displayed in the info boxes on both/jbrowse for Variations?

![snp_info_gbrowse2](https://user-images.githubusercontent.com/717707/47802540-62c04c00-dd28-11e8-9b2a-6cf8807875f8.png)
![snp_info_jbrowse](https://user-images.githubusercontent.com/717707/47802718-d2ced200-dd28-11e8-9821-4055e8277342.png)

Specifically the other_name data?

```
V	Variation_project_Polymorphism	SNP	6837758	6837758	.	+	.	variation=WBVar00210873;public_name=WBVar00210873;other_name=uCE5-1500,haw78149,haw167170,cewivar00235639;strain=CB4856;polymorphism=1;substitution=T/G;consequence=Intron
```

This probably should be for all species, but specifically for C. briggsae but wouldn't hurt for C. elegans as well.

Paul

**Comment by scottcain** [comment]
@Paul-Davis I implemented it on staging's jbrowse:

https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=I%3A3954..4004&tracks=Curated_Genes%2CPolymorphisms%2CDNA%2CProtein-coding%20genes%20(frame%20usage)&highlight=

(it might take a hard reload or incognito mode to see the change.)  GBrowse will take a little longer.

**Comment by scottcain** [comment]
Hi @Paul-Davis I implemented it for just the Polymorphisms track for C. elegans in GBrowse: 

https://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?start=3954;stop=4004;ref=I;width=800;version=100;flip=0;grid=1;id=565ac76e635f87a66400d6221d6dacd1;l=VARIATIONS_POLYMORPHISMS%1ELOCI%3Aoverview

So, let me make sure I know what you want: you'd like this change for every variation-type track that has this style of mouse-over balloon, right?  Of course, if a given feature doesn't have an other_name attribute, that line won't show up at all.  I can make that available for 267 for JBrowse for sure--getting it in for GBrowse might be a little harder, depending on when it goes to production.  If it's this weekend, it might not make it; next weekend I should be able to do.

**Comment by Paul-Davis** [comment]
Hi @scottcain that looks great!!!

**Comment by scottcain** [comment]
This addition is live in production (267) for JBrowse and fully implemented on staging (268) for GBrowse and seems to work well, so I'm closing.
