### ISSUE TITLE
ncRNA genes tagged with biotype for "ncRNA" instead of "ncRNA gene"

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6704]
Steven Marygold (FlyBase) noticed 

https://agr-jira.atlassian.net/projects/AGR/issues/AGR-1292

an issue at the Alliance website:

https://www.alliancegenome.org

That there are 100 _C. elegans_ genes labeled with the biotype "ncRNA" (SO:0000655) instead of "ncRNA gene" (SO:0001263). As these are gene objects, not transcript objects, they should probably all get the biotype "ncRNA gene" (SO:0001263) for consistency.

@Paul-Davis I'm assigning to you, but please reassign if it should be someone else.

Here are the 100 genes affected:

WBGene00219557
WBGene00219550
WBGene00219558
WBGene00220252
WBGene00206369
WBGene00194668
WBGene00219647
WBGene00195234
WBGene00206494
WBGene00219656
WBGene00219658
WBGene00219659
WBGene00194841
WBGene00219568
WBGene00219663
WBGene00219573
WBGene00219575
WBGene00219668
WBGene00219669
WBGene00219670
WBGene00219671
WBGene00219576
WBGene00219672
WBGene00235323
WBGene00219581
WBGene00219582
WBGene00219583
WBGene00195064
WBGene00194847
WBGene00219677
WBGene00195065
WBGene00219679
WBGene00219681
WBGene00219587
WBGene00219683
WBGene00235334
WBGene00194771
WBGene00194792
WBGene00219589
WBGene00219696
WBGene00236798
WBGene00194865
WBGene00206489
WBGene00219552
WBGene00236799
WBGene00219701
WBGene00219703
WBGene00219705
WBGene00219593
WBGene00194834
WBGene00219597
WBGene00219710
WBGene00219711
WBGene00235331
WBGene00235166
WBGene00195172
WBGene00235255
WBGene00194856
WBGene00219448
WBGene00219715
WBGene00219717
WBGene00219603
WBGene00194984
WBGene00235157
WBGene00219553
WBGene00219729
WBGene00195117
WBGene00219607
WBGene00219738
WBGene00219610
WBGene00219744
WBGene00194842
WBGene00235357
WBGene00219751
WBGene00219752
WBGene00219555
WBGene00194884
WBGene00194686
WBGene00219759
WBGene00219760
WBGene00219621
WBGene00219622
WBGene00219623
WBGene00194666
WBGene00219764
WBGene00255549
WBGene00219766
WBGene00236797
WBGene00219627
WBGene00194853
WBGene00194854
WBGene00219631
WBGene00219633
WBGene00219772
WBGene00219638
WBGene00194673
WBGene00219640
WBGene00194665
WBGene00219642
WBGene00194669

Thanks!

**Comment by khowe** [comment]
Concur. @Paul-Davis need to change Biotype of these genes in Geneace.

**Comment by scottcain** [comment]
I assigned myself to this, since it is probably going to require config changes for both GBrowse and JBrowse when this change goes through.

**Comment by khowe** [comment]
@scottcain I don't think this will require any G/JBrowse action. Only a small subset of the ncRNA genes had been mislabelled as "ncRNA". The majority were correctly labelled as "ncRNA_gene".

**Comment by scottcain** [comment]
Oh, I was under the impression there would be something "new" :-) I'll take myself off then.

**Comment by Paul-Davis** [comment]
script changed and the term for antisense long non coding RNA has been used with permission from the founder of the asRNA gene class.
