### ISSUE TITLE
Update lineage information link broken

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6705]
When I just clicked on the WBPerson page link "Add or update your lineage information" it led me to:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person_lineage.cgi?action=Display&number=

which loads a 500 internal server error message.

**Comment by ceciliaWBPerson1** [comment]
Apologies, it is working now. Please re-send your data.

cecilia

**Comment by chris-grove** [comment]
@azurebrd  working on now...

**Comment by azurebrd** [comment]
This should work now, e.g.
https://juancarlos.wormbase.org/resources/person/WBPerson1#2--10

**Comment by chris-grove** [comment]
@azurebrd 
Yep, looks good now. Thanks!
