### ISSUE TITLE
visitor_name (visitor_email): Where do we download...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6707]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Where do we download the most recent annotated genome for C. elegans?</br>Chris: Hello visitor_name, how can I help?</br>Chris: By annotated, you mean you're looking for the GFF file?</br>visitor_name (visitor_email): Yes</br>Chris: Under the "Directory" menu at the top of any WormBase page, under the "Browse by species" section, click on "C. elegans" and you will be directed to the C. elegans species page</br>Chris: https://wormbase.org/species/c_elegans#02--10</br>Chris: Make sure the "Downloads" widget is open and you can find a link to download the latest GFF</br>Chris: You can also go to the "Downloads" menu at the top of any WormBase page, click on "Listed by species" and you will be directed to a page that has all the GFF files for all species that we have GFFs for</br>Chris: https://wormbase.org/species/all#1--10</br>visitor_name (visitor_email): I see now. Thank-you!</br>Chris: You're welcome! Is there anything else I can help you with?</br>visitor_name (visitor_email): No, that's it.</br>Chris: OK, have a nice day!

**Reported by:** Lean** (lhke************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/wormbase_release_WS266#0--10">https://wormbase.org/about/wormbase_release_WS266#0--10</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
@tharris 
This Olark chat transcript did not get sent to help@wormbase.org again (at least not yet, as of 36 minutes ago when the chat happened).
