### ISSUE TITLE
Chris: Hi Scott, how can I help? visitor_name (vis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6708]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Scott, how can I help?</br>visitor_name (visitor_email): On this current version of worm base's genome browser (the new one) how can you download the sequence of a selected region?</br>visitor_name (visitor_email): This was a simple as selecting drop in FASTA in the old genome browser. Has this function been eliminated and if so why?</br>Chris: The trick in JBrowse is to turn on the "Reference sequence (DNA)" track</br>Chris: You can zoom into a region of interest and then use the track's "Save track data" option to save the sequence.</br>Chris: You can also use the hilighter tool to highlight a region of interest, and then use the "Reference sequence (DNA)" track's "Save track data" option to save the highlighted sequence specifically (so you don't have to zoom all the way in). This is how you can manually select a region and get the sequence</br>Chris: If you open the "Curated genes (protein coding)" track, you can specifically download sequences that pertain to a particular transcript</br>Chris: With the "Curated Genes (protein coding)" track open, right click on a transcript of interest, click on "View Sequence" and then you can view and select that transcript's corresponding full sequence, exons only, with or without UTRs, upstream (or downstream) flanking sequence, etc.</br>visitor_name (visitor_email): Thank you. I was clearly missing the reference sequence aspect of it. It seems a bit unintuitive as compared to the old version of genome browser.</br>Chris: I understand. I can forward your message to our JBrowse developer to make sure he (and other JBrowse developers) receive your feedback. Thanks for your input!</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): No, that's all. Thanks!</br>Chris: OK, have a nice day!

**Reported by:** Scot****** (sdou***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/clone/WRM0637dC03#02--10">https://www.wormbase.org/species/c_elegans/clone/WRM0637dC03#02--10</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
@scottcain  Some user feedback on sequence download issue (echoes many other user comments as well)

**Comment by scottcain** [comment]
I agree that it is difficult to "get the word out" about changes in how to do things, and I'm expecting the highlight to get a menu functionality to come back in JBrowse 2.  That said, "nonintuitive" with regard to most software usually means "not what I'm used to for the last 15 years" because I'm not sure it's any less intuitive (you get the data you want from the track with that data type, after all--that feels intuitive). I just wish there was a way to make it more discoverable, which is the real problem.
