### ISSUE TITLE
  How do I find out the Trancription fa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6709]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find out the Trancription factors binding to few chaperons in C elegans? </p>

**Reported by:** Khai*** (khai********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by chris-grove** [comment]
I've sent emails to the user to clarify the request. Awaiting response

**Comment by chris-grove** [comment]
Haven't heard back. Closing. Will reopen if necessary.
