### ISSUE TITLE
Hi, 

I'm finding the dataset of Hawaiian CB SNP ,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6710]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, 

I'm finding the dataset of Hawaiian CB SNP , however, the page; http://www.wormbase.org/db/searches/wb_query; isn't found.
So, where can I get the CB SNP dataset ?
I'm looking for your answer.

Sincerely,

visitor_name

**Reported by:** Yuto (yuto******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/Frequently_asked_questions#2105abf894e3d6c7--10">https://wormbase.org/about/Frequently_asked_questions#2105abf894e3d6c7--10</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
@tharris 
Here's another example of an Olark chat transcript that didn't get a corresponding email to help@wormbase.org. Issue #6711 is a duplicate as the user specifically submitted another request to the help desk, so I will close this as a duplicate.

**Comment by sibyl229** [comment]
@chris-grove I did something to fix email sending in WS267. Let's see if the problem continues after WS267 goes out. If it still happens, please let me know.

**Comment by chris-grove** [comment]
OK, thanks @sibyl229
