### ISSUE TITLE
  Hi, I'm doing SNP mapping using the H...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6711]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm doing SNP mapping using the Hawaiian CB strain. <br/>However, I can't find any SNP databases.<br/>I went to the page, http://www.wormbase.org/db/searches/wb_query, but the page said "NOT FOUND". <br/>So, Where can I get the CB SNP dataset ? <br/>I'm looking for your answer.<br/>Sincerely,<br/>visitor_name</p>

**Reported by:** Yuto (yuto******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by chris-grove** [comment]
You can get the Hawaiian (strain CB4856) SNPs from this GFF file:


ftp://ftp.wormbase.org/pub/wormbase/releases/WS266/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS266.annotations.gff3.gz


You can run the following commands on the command line to extract the Hawaiian SNPs from this file:


zcat c_elegans.PRJNA13758.WS266.annotations.gff3.gz | grep CB4856 | awk '$2 == "Variation_project_Polymorphism"' 

Please let us know if you have any questions.
