### ISSUE TITLE
Hi, 
I am looking at the Gene » R31.2. The phenoty...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6712]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, 
I am looking at the Gene » R31.2. The phenotype indicated is "amphid phasmid morphology variant" based on PMID: 17459615. But I do not find this gene in the paper.

https://wormbase.org/species/c_elegans/rnai/WBRNAi00065898#041--10

Thanks
Paula

**Reported by:** Paul****** (paul****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/paper/WBPaper00029323#0--10">https://wormbase.org/resources/paper/WBPaper00029323#0--10</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
In this paper:


https://www.ncbi.nlm.nih.gov/pubmed/?term=17459615


The authors report in their methods section about RNAi constructs:


"The target genes were osm-10, osm-6, gpb-1 and gfp. For the C. elegans genes we amplified, from genomic DNA, the same exon rich regions that were used as inserts for the E. coli plasmid library prepared to obtain RNAi by feeding (Kamath et al., 2003)."


Thus, we annotated the RNAi knockdown reagent as the Ahringer RNAi clone for osm-6, in this case, which corresponds to the clone "sjj_R31.3":


https://www.wormbase.org/species/all/pcr_oligo/sjj_R31.3#10--10


which mostly overlaps the osm-6 gene, but actually has 50+ bp overlap with the 3'UTR of R31.2, and so our RNAi target mapping pipeline predicts R31.2 to be a potential knockdown target of these RNAi experiments. That is why you're seeing these phenotypes attribtued to the R31.2 gene. If we can get confirmation that the RNAi reagent used to knockdown osm-6 did not also overlap R31.2, we can modify the annotation to be more specific to osm-6.
