### ISSUE TITLE
Hi,
I am checking the RNAi phenotype cytoplasmic p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6713]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
I am checking the RNAi phenotype cytoplasmic processing body variant, sterile, transgene subcellular localization variant -&gt; Remark: RNAi resulted in enhanced formation of P bodies throughout the whole animal, with pronounced formation in the germline according to

**Reported by:** Paul****** (paul****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00016741#0c681-9gebhf-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00016741#0c681-9gebhf-3</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
Duplicate #6714
