### ISSUE TITLE
Hi 
I am checking the phenotype cytoplasmic proces...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6714]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi 
I am checking the phenotype cytoplasmic processing body variant, sterile, transgene subcellular localization variant -&gt; Remark: RNAi resulted in enhanced formation of P bodies throughout the whole animal, with pronounced formation in the germline according to PMID: 22180091. But I do not find the gene C48B6.3. I also checked in the Supp Table 1.
Thanks for your help
Paula

**Reported by:** Paul****** (paul****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00016741#0c681-9gebhf-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00016741#0c681-9gebhf-3</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
Email to user:

Similarly to my last explanation, in the corresponding paper:


https://www.ncbi.nlm.nih.gov/pubmed/22180091


The authors report in the methods section of the paper:


"Preparation and induction of RNAi bacterial clones


The RNAi feeding library is commercially available from Geneservice. The library contains bacterial clones expressing dsRNA designed to individually inactivate 16,644 genes (targeting about 87% of the genome)"


which is referring to the Ahringer RNAi clone library:


https://www.ncbi.nlm.nih.gov/pubmed/12529635


(originally made available through the clone service company Geneservice, now no longer in operation).


In Table S1 (of paper 22180091), the authors report knocking down gene C48B6.2 (line 122), which has an Ahringer RNAi clone of "sjj_C48B6.2" which mostly overlaps the gene C48B6.2, but also overlaps the 3'UTR of C48B6.3 by more than 50 bp, resulting in our RNAi mapping pipeline identifying this gene as a potential knockdown target of the experiment, as indicated on the corresponding RNAi experiment page:


https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00094104#0415--10


I hope that clarifies the issue.
