### ISSUE TITLE
   Error del servidor: 500 en      reposo / campo ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6718]
*Submitted from the feedback form on the WormBase website.*

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Error del servidor: 500 en </font></font><a href="https://wormbase.org/rest/field/gene/WBGene00000912/interaction_details"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">reposo / campo / gen / WBGene00000912 / interaction_details</font></font></a></p><p>
</p><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mensaje de error: se </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">detectó una excepción en WormBase :: Web :: Controller :: REST-&gt; field "http://datomic-to-catalyst-ws266.us-east-1.elasticbeanstalk.com/rest/field/gene/WBGene00000912/ "interaccion_detalles falló con 504 en /usr/local/wormbase/jenkins/workspace/staging_build/lib/WormBase/Web/Controller/REST.pm line 1857."</font></font></p>

**Reported by:** Mari** (mari****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//rest/field/gene/WBGene00000912/interaction_details">/rest/field/gene/WBGene00000912/interaction_details</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by sibyl229** [comment]
Replied

> Thanks for contacting us! You might have experienced a transient issue with loading the interaction widget. I think it’s working now: > https://www.wormbase.org/species/c_elegans/gene/WBGene00000912#0-8-3
