### ISSUE TITLE
Is there an error in the Overview paragraph for ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6719]
*Help Desk query collected when no chat operators were online. Follow up required.*

Is there an error in the Overview paragraph for gene C27B7.7?  This says C27B7.7 is a leucine rich repeat protein (LRR).  But the homology listing says it has similarity to Drosophila DSCAM2, an IG-FN domain protein.

**Reported by:** Scot******** (scot************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00007764#04-9gf6-10">https://www.wormbase.org/species/c_elegans/gene/WBGene00007764#04-9gf6-10</a>
**Browser:** Chrome 69.0.3497.100

**Comment by chris-grove** [comment]
@rankishore  resolved with user
