### ISSUE TITLE
  I'm visitor_name (WBPerson24354), a p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6724]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm visitor_name (WBPerson24354), a postdoc in Ikue Mori's lab (IK).<br/>I'm writing on behalf of Ikue.<br/>A gene class "cdkl" is registered to our IK lab.<br/>However, our lab has nothing to do with this gene class except that a previous postdoc, Paola Jurado, is a source for the gene name of cdkl-1, a sole member of this gene class.<br/>We would like this "cdkl" gene class to be removed from our lab and, if appropriate, to be transferred to PJP lab.<br/>Best regards,<br/>visitor_name</p>

**Reported by:** Ichi******* (ichi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thanks for contacting WormBase, I will run this past Tim Schedl cc'd but 
I'm sure that this can be done for the WS269 release of the database.

Paul



On 07/11/2018 07:14, no-reply@wormbase.org wrote:
> Content Correction
>
>   I'm Ichiro Aoki (WBPerson24354), a postdoc in Ikue Mori's lab (IK).
> I'm writing on behalf of Ikue.
> A gene class "cdkl" is registered to our IK lab.
> However, our lab has nothing to do with this gene class except that a 
> previous postdoc, Paola Jurado, is a source for the gene name of 
> cdkl-1, a sole member of this gene class.
> We would like this "cdkl" gene class to be removed from our lab and, 
> if appropriate, to be transferred to PJP lab.
> Best regards,
> Ichiro Aoki
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6724. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6724>.
>
> Reported by: Ichiro Aoki (ichiro8848@gmail.com)
> 07 Nov 18 07:14
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/70.0.3538.77 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
