### ISSUE TITLE
Hello WormBase friends! I was wondering if you cou...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6726]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello WormBase friends! I was wondering if you could tell me how the WormBase data is licensed. (apologies if it's on your website, I did look!) Thank you!!

**Reported by:** Juli********** (juli***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/citing_wormbase#0312--10">https://wormbase.org/about/citing_wormbase#0312--10</a>
**Browser:** Firefox 63.0

**Comment by chris-grove** [comment]
@tharris @sibyl229 
Here's another Olark chat transcript that got sent to GitHub (and sent a GitHub email) but sent no email (as of 6 hours since the help request) was sent to help@wormbase.org

**Comment by chris-grove** [comment]
Sent to user:
"We have these two pages of information regarding copyright and citing procedures:

https://wormbase.org/about/policies#201--10
https://wormbase.org/about/citing_wormbase#0123--10

Please let us know if you need anything else."
