### ISSUE TITLE
visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6729]
*Help Desk query collected when no chat operators were online. Follow up required.*

visitor_name

**Reported by:** Yoge******* (yoge*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/search/gene/178393">https://www.wormbase.org/search/gene/178393</a>
**Browser:** Chrome 70.0.3538.64

**Comment by chris-grove** [comment]
My email to user:
"If you happened to be looking for a worm gene with an Entrez/NCBI Gene ID of '178393', you may have been looking for Y57G11C.32:

https://wormbase.org/species/c_elegans/gene/WBGene00013322#-02-10

Let us know if you need help with anything."
