### ISSUE TITLE
  Hello,  Is there any available tool i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6730]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>Is there any available tool in wormbase to rank genes based on intron length if I provide a gene list? I have seen in Parasite that it is possible to retrieve exonic sequences but not intronic.  I would like to design FISH pprobes against introns from sperm related genes, which are already very short in number of bp... do I would like to find the sperm related gene(s) with longer intron(s).<br/>Thank you for your time and help</p><p>What were you doing? <br />&nbsp;&nbsp;using parasite wormmart</p>

**Reported by:** Eric (eric******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

**Comment by chris-grove** [comment]
My email to user:
"""
We don't have a specific tool available for this. Using a couple tricks I was able to get more or less what you're looking for:

1) If you download the C. elegans GFF file from here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS267.annotations.gff3.gz

unzip the file, and run the following on the command line:

`​awk 'BEGIN {FS="\t";OFS="\t"} {if(($2 == "WormBase") && ($3 == "intron")) print $9,$4,$5}' c_elegans.PRJNA13758.WS267.annotations.gff3 > WB_elegans_introns_from_GFF3.txt`

This will return a tab-delimited table of all C. elegans introns (transcript ID in first column) with start (column 2) and end (column 3) genomic coordinates. If you use Excel to calculate the difference between columns 2 and 3 (column 3 value minus column 2 value) for the whole list, you will get the length of each intron. Then you can revserse sort (sort in descending order) the list of introns by size. Trimming the list of introns down to those that are 500 nt or longer brings the list down to about 42,000 introns.

2) Using WormMine, I can perform the following query for "spe-*" genes and list the gene length and the transcript lengths for each gene (import the following XML query into the "Import query from XML" option on the WormMine QueryBuilder tab):

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.transcripts.symbol Gene.sequence.length Gene.transcripts.sequence.length" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.symbol" op="=" value="spe-*"/>
</query>`

Exporting this list and opening in Excel, you can do a similar difference calculation on gene size and transcript size; presumably the genes with bigger discrepancies between the gene size and transcript size will have larger introns.

3) On the first GFF-derived file I started searching for lines that match the spe-* gene sequence names or transcript names from the WormMine-derived list, starting with genes with the largest discrepancy between gene size and transcript size (spe-15).

Using this approach I could find 9 spe-* genes with introns larger than 500bp (see attached Excel file).

I hope that helps. Let us know if you need something else.
"""

**Comment by ecornesm** [comment]
Hello Chris, thanks a lot for your reply, the explanations and the excel table.. this is exactly what I was looking for. Thanks a lot again!!!

**Comment by chris-grove** [comment]
@ecornesm  OK, great! Let us know if you have any other questions.

**Comment by ecornesm** [comment]
Hello again Chris, 

actually the approach worked well for sperm genes and I was wondering if you could help me to get a similar list for all the genes in the C elegans genome. It will be the one you already mentioned in your previous messages: "Trimming the list of introns down to those that are 500 nt or longer brings the list down to about 42,000 introns".
Thank you again for your help

Eric

**Comment by chris-grove** [comment]
@ecornesm 
Hi Eric,
If you want the list already trimmed to introns of length 500nt or more, you can run this on the command line:

`​awk 'BEGIN {FS="\t";OFS="\t"} {if(($2 == "WormBase") && ($3 == "intron") && (($5 - $4) >= 500)) print $9,$4,$5}' c_elegans.PRJNA13758.WS267.annotations.gff3 > WB_elegans_introns_from_GFF3.txt`

Let me know if you need something else.

**Comment by ecornesm** [comment]
Hi Chris, 
thanks for sharing the command line, we are downloading the file now. We will let you know 👍  thanks again

**Comment by ecornesm** [comment]
Actually, Im quite excited about the potential of using wormbase data so I contact you again for another question.
I would like to obtain another list regarding "expression" categories. This expression categories are listed for any gene in wormbase. 
I'm working with a gene named csr-1, which is expressed in P granules in the germline. Accordingly this info appears in the category: Expression/Subcellular localization/Pgranule for csr-1 gene. 
How can I obtain the list of all the genes that have "P granule"as a Subcellular localization based on all the info contained in Wormbase ?

**Comment by ecornesm** [comment]
Well, sorry, I just found out, clicking on the P granule category it appears another page, and if you click "associations" you get the complete list of genes...
Sorry for the spam, I contacted you before actually checking properly.

**Comment by chris-grove** [comment]
@ecornesm 
No problem at all. Let me know if you have any other questions.

**Comment by PierQ** [comment]
> @ecornesm
> Hi Eric,
> If you want the list already trimmed to introns of length 500nt or more, you can run this on the command line:
> 
> `​awk 'BEGIN {FS="\t";OFS="\t"} {if(($2 == "WormBase") && ($3 == "intron") && (($5 - $4) >= 500)) print $9,$4,$5}' c_elegans.PRJNA13758.WS267.annotations.gff3 > WB_elegans_introns_from_GFF3.txt`
> 
> Let me know if you need something else.

Hi, 
I used the command you described to get the list of genes with intron size higher than 500. 
The gene name output that I get is in the following format: F59D12.2.1
I tried to use the WormBase Parasite to have the correspondent gene name but it seems that the website doesn't fully accept this format. I explain with an example: F59D12.2 is accepted while F59D12.2.1 is not. Same with letters, C03H12.1a is not accepted but C03H12.1 is accepted. It seems that it doesn't accept isoforms, so the input name is fine until the first number after the first dot.

Is there any way (even on the Parasite) to convert the name in the format "C03H12.1a.1" in "gene name (like "pgl-1")? 

Sorry for the confusion but it is very hard to explain, I hope you got my question. 

Thank you in advance,
Pier

**Comment by chris-grove** [comment]
@PierQ 

OK, first, I've come up with a more direct way to get the list of transcripts reverse-sorted by intron length directly from the GFF:

`awk 'BEGIN {FS="\t";OFS="\t"} {if(($2 == "WormBase") && ($3 == "intron") && (($5 - $4) >= 500)) print $9,($5 - $4)}' c_elegans.PRJNA13758.WS267.annotations.gff3 | sort -r -t $'\t' -n -k2 > WB_elegans_introns_from_GFF3_reverse_sorted.txt`

Then, to get the list of transcripts you can do the following:

`cut -f1 WB_elegans_introns_from_GFF3_reverse_sorted.txt | cut -f1 -d";" | cut -f2 -d":" | sort | uniq > Transcript_IDs_long_introns.txt`

This should produce a list of 16,757 unique transcript IDs. These IDs can be uploaded to WormMine using the WormMine List Upload tool:

http://intermine.wormbase.org/tools/wormmine/bag.do

Make sure to select the data type as "Transcript" and paste in the list of 16,757 transcript IDs and click on "Create List". On the confirmation page, confirm that WormMine recognized all of the transcript IDs, name your list and save it. Then you can use WormMine's "Manage Columns" option to add the corresponding genes to the table, save those genes as a list, and export that gene list. Here's a screen capture video to demonstrate:

https://www.dropbox.com/s/pzay1nm887mz0d6/Convert_transcript_IDs_to_Gene_IDs_Nov-26-2018.mov?dl=0

WormBase ParaSite BioMart currently will not properly recognize transcript IDs, but that is getting fixed, so you can use WormMine in the meantime.

Another solution, if you want to use regular expressions, is to note that each transcript ID is a sequence name of a gene, e.g. "W02C12.3", (single dot) followed by either a lowercase letter, a dot and a number (usually 1, 2, or 3) or just a dot and a number. If you use regular expression (I haven't worked out the exact method), you can strip out the lowercase-letter-dot-number or dot-number suffix and you will have a gene sequence name which will be recognized by WormBase ParaSite BioMart, WormMine, or our SimpleMine tool.
