### ISSUE TITLE
  scroll function does not seem to be w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6731]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;scroll function does not seem to be working</p>

**Reported by:** Anon***** (larr******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Email to user:
"Thanks for the feedback. Could you clarify the issue you encountered? Were you trying to use a scroll function on a WormBase web page? We'd like to take care of the issue if there is one."

**Comment by chris-grove** [comment]
I haven't heard back. Closing.
