### ISSUE TITLE
DO term links from Ontology Browser widget not linking to respective DO term page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6734]
On any WormBase disease page, for example the ontology root term "disease":

https://www.wormbase.org/resources/disease/DOID:4#02--10

clicking on any DO terms (names or IDs) in the Ontology Browser widget results in being directed to a blank search results page. For example, clicking on the term "disease of anatomical entity" or its DOID "DOID:7" links to:

https://www.wormbase.org/species/all/do_term/DOID:7

which redirects to:

https://www.wormbase.org/search/all/do_term%20DOID:7?redirect=1

which is a blank search results page (0 results).

**Comment by azurebrd** [comment]
Fixed by https://github.com/WormBase/website/pull/6737

**Comment by chris-grove** [comment]
@azurebrd 
On juancarlos.wormbase.org, the links are now leading to a 404 Not Found page, but the links seem generally OK, as if I swap out "juancarlos" with "www" I get the page I would expect.

**Comment by chris-grove** [comment]
OK, fixed on staging. Closing.
