### ISSUE TITLE
  Are there annotation (in .gff or .bed...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6735]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Are there annotation (in .gff or .bed formats) of transposable and repetitive elements in C. elegans? Thank you.</p>

**Reported by:** Chen**** (cl73*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

**Comment by Paul-Davis** [comment]
Hi,

Thanks for contacting WormBase, yes we provide Transposon data in the 
form of .fasta for the sequence data and .gff in the main annotation file.

ftp://ftp.wormbase.org/pub/wormbase/releases/WS268/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS268.transposon_transcripts.fa.gz
ftp://ftp.wormbase.org/pub/wormbase/releases/WS268/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS268.annotations.gff3.gz

In the GFF file the Transposon annotations are in 2 forms,

ID=Transposon:Predicted_CELE2_5267 - These are filtered transposon 
repeat alignments that meet length cutoffs
ID=Transposon:WBTransposon00000416 - These are curated Transposon 
families that have been refined and classified into families.

If you require additional information please feel free to drop me an email.

Paul


On 14/11/2018 20:29, no-reply@wormbase.org wrote:
> Question:
>
>   Are there annotation (in .gff or .bed formats) of transposable and 
> repetitive elements in C. elegans? Thank you.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6735. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6735>.
>
> Reported by: Chenglin (cl737@cornell.edu)
> 14 Nov 18 20:29
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 
> (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
