### ISSUE TITLE
  Hello, I have a list of genes and wou...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6740]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I have a list of genes and would like to bulk download a list of the known interactions for these genes. I have been able to go in and see the interactions for each gene on the gene page, but have not been able to find a place where I can give a list and download the known interactions in bulk. How could I do this? If it is not available through wormbase is there an option in R? In the end I would like to visualize the interactions for this gene list using cytoscape. <br/>Best regards,<br/>Alyssa</p>

**Reported by:** Alys********** (wa23********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by WenChenWormBase** [comment]
Dear Alyssa,

You may try SimpleMine: https://wormbase.org/tools/mine/simplemine.cgi

Enter your gene list, then select "Interacting Gene" from the checklist as
output.

Please let us know if you have any questions,

Wen Chen
Curator, WormBase.

On Thu, Nov 15, 2018 at 1:12 PM <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Hello,
> I have a list of genes and would like to bulk download a list of the known
> interactions for these genes. I have been able to go in and see the
> interactions for each gene on the gene page, but have not been able to find
> a place where I can give a list and download the known interactions in
> bulk. How could I do this? If it is not available through wormbase is there
> an option in R? In the end I would like to visualize the interactions for
> this gene list using cytoscape.
> Best regards,
> Alyssa
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6740. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/6740>.
>
> Reported by: Alyssa Woronik (wa23@nyu.edu)
> 15 Nov 18 21:12
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/70.0.3538.77 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Thank you!
