### ISSUE TITLE
gene name widget broken link

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6741]
the genome name change widget has a broken link in:
the WS252 are archived [here].
it is:
http://ftp//ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/changed_CGC_names/
should be:
ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/changed_CGC_names/

**Comment by sibyl229** [comment]
@epaule the ftp linkout is fixed on staging now. Thanks for letting me know. I didn't realize that I broke this when fixing something else.

**Comment by epaule** [comment]
no problem, looking good :+1:
