### ISSUE TITLE
visitor_name (visitor_name.m_dvm@yahoo.com): Follo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6742]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_name.m_dvm@yahoo.com): Follow any of the links to get more information about the gene. Other details about the gene?</br>Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_name.m_dvm@yahoo.com): Actually I wanna have a idea how to answer some questions about your website</br>Chris: I'm sorry I don't understand your question.</br>Chris: OK</br>Chris: what questions?</br>Chris: You're trying to get details about a particular gene in WormBase?</br>visitor_name (visitor_name.m_dvm@yahoo.com): Yes I do</br>Chris: OK, which gene?</br>Chris: and what kind of details are you looking for?</br>visitor_name: uploaded file: https://olark-file-uploads.s3.us-west-1.amazonaws.com/processed/5c14c4f5-3436-4622-adf9-40e378911d80.jpg</br>visitor_name (visitor_name.m_dvm@yahoo.com): I look something like that information</br>Chris: OK, I can't do your homework assignment for you, but if you have specific questions about how to use WormBase, or if you'd like to report any issues with using WormBase (if it isn't working as expected) I can help you with that

**Reported by:** Moha**** (moha********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/search/gene/What is other details about the gene?">https://www.wormbase.org/search/gene/What is other details about the gene?</a>
**Browser:** Safari 12.0

**Comment by chris-grove** [comment]
The user actually uploaded an image of the homework assignment. That's new.
