### ISSUE TITLE
  do i have all those types an should  ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6743]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;do i have all those types an should  ask family dr for medicine</p>

**Reported by:** ruth************* (Terr******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by chris-grove** [comment]
WormBase does not provide any medical advice. If you have a medical question, please consult your family physician.
