### ISSUE TITLE
aipr-1 (C56C10.10) is a gene in Operon CEOP2256. H...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6744]
*Help Desk query collected when no chat operators were online. Follow up required.*

aipr-1 (C56C10.10) is a gene in Operon CEOP2256. However the sequence for CEOP2256 has an insertion of 49bp within aipr-1 compared to the sequence for the unspliced aipr-1.

**Reported by:** Step*********** (nurr**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Operons,DNA&amp;loc=II:6591021..6595715&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Operons,DNA&amp;loc=II:6591021..6595715&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Firefox 63.0

**Comment by Paul-Davis** [comment]
Dear Stephen,

Thank you for contacting WormBase. Could you elaborate on where you are 
getting the sequences for comparison as operons are just alignments on 
the reference genome so don't contain any DNA of their own to differ 
from that seen in jbrowse or any coding sequence that it overlaps with.

Taking the sequence from the jbrowse link you provided:
https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Operons,DNA&loc=II:6591021..6595715&data=data/c_elegans_PRJNA13758&highlight= 
<http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes%2COperons%2CDNA&loc=II%3A6591021..6595715&data=data%2Fc_elegans_PRJNA13758&highlight=>

Reverse complementing it and aligning it to the unspliced + UTR (1812 
bp) of transcript C56C10.10.1
https://wormbase.org/species/c_elegans/transcript/C56C10.10.1#6--10

I get the attached alignment using muscle in msf format which seems to 
align perfectly?

Paul





On 19/11/2018 18:45, no-reply@wormbase.org wrote:
> offline chat aipr-1 (C56C10.10) is a gene in Operon CEOP2256. However 
> the sequence for CEOP2256 has an insertion of 49bp within aipr-1 
> compared to the sequence for the unspliced aipr-1.
>
> Submitted From:
>   https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Operons,DNA&loc=II:6591021..6595715&data=data/c_elegans_PRJNA13758&highlight= 
> https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes,Operons,DNA&loc=II:6591021..6595715&data=data/c_elegans_PRJNA13758&highlight= 
> <http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse/?tracks=Curated_Genes%2COperons%2CDNA&loc=II%3A6591021..6595715&data=data%2Fc_elegans_PRJNA13758&highlight=> 
>
>
> This issue has been assigned ticket number: #6744. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6744>.
>
> Reported by: Stephen Nurrish (nurrish@molbio.mgh.harvard.edu)
> 19 Nov 18 18:45
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
