### ISSUE TITLE
  Dear Sir/Madam, Could you please add ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6745]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam,<br/>Could you please add the worm meeting 2015 abstract # 913C: Title:<br/>"Identifying a role of N-glycosylation in C. elegans epithelial polarity by an RNAi-based biosynthetic-pathway-screen approach. Hongjie Zhang, Nessy Abraham, visitor_name, Nan Zhang, Verena Gobel." available at:<br/>www.genetics-gsa.org/celegans/2015/pages/posterlisting.shtml<br/>under personal publication list. <br/>This abstract is not visible in WormBase.<br/>Thanks for your kind help.</p><p>What were you doing? <br />&nbsp;&nbsp;I was searching my meeting abstracts in wormBase, and the above abstract was missing.  </p>

**Reported by:** Liak******* (liak****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by vanaukenk** [comment]
@ceciliaWBPerson1  - can you associate Liakot's WBPerson ID with WBPaper00048289?

Thanks.

**Comment by ceciliaWBPerson1** [comment]
Done, Updates will be available in release WS270 of WormBase.
We are currently in version WS267.

**Comment by ceciliaWBPerson1** [comment]
Done.

Updates will be available in release WS270 of WormBase.
We are currently in version WS267.

cecilia

**Comment by azurebrd** [comment]
Email to user : 

Hello Liakot,

I see that the issue you generated has been closed, but didn't see
whether anyone sent you a response.  Has anyone gotten back to you ?

Thanks,
Juancarlos, Help Desk

**Comment by azurebrd** [comment]
Liakot writes : 

Thanks. No, no one. If possible, please take care of the issue.

Best regards.
Liakot

**Comment by ceciliaWBPerson1** [comment]
Hi. Sorry I thought I did.
Liakot I added the abstract to your bibliography/person page.

Updates will be available in release WS270 of WormBase.
We are currently in version WS267.

Happy Thanksgiving !
cecilia
