### ISSUE TITLE
Transcript identifier issues in ParaSite BioMart

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6748]
In ParaSite BioMart:

https://parasite.wormbase.org/biomart/martview/

If I query just for all C. elegans gene stable IDs and their corresponding transcript stable IDs:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.production_name_1010|wbps_gene.default.feature_page.wbps_gene_id|wbps_gene.default.feature_page.wbps_transcript_id&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"&VISIBLEPANEL=resultspanel

I find several issues:

1) There are 458 "gene stable ID" results of the form "Transcript:" instead of "WBGene"

2) For WBGene00000005 (aat-4), I get two results:

WBGene00000005 | T13A10.10a
WBGene00000005 | T13A10.10b

According to the respective WormBase gene page:

https://wormbase.org/species/c_elegans/gene/WBGene00000005#0g--10

T13A10.10a is the name of the CDS and T13A10.10a.1 is the name of the transcript. There is apparently no CDS or transcript T13A10.10b. So, if I wanted to search for the gene that corresponds to transcript "T13A10.10a.1" by querying for a stable transcript ID, I get no results because "T13A10.10a.1" is not recognized as a valid transcript ID.

Similarly, WBGene00000024 (abu-1) has the BioMart output:

WBGene00000024 | AC3.3

whereas the WB gene page:

https://wormbase.org/species/c_elegans/gene/WBGene00000024#0g--10

shows AC3.3 as the gene's sequence name and as the single CDS name, but the transcript ID is actually "AC3.3.1".

This isn't to say that they're all wrong, as WBGene00000001 (aap-1) has the correct results:

WBGene00000001 | Y110A7A.10.1
WBGene00000001 | Y110A7A.10.2

So, it seems that there are several issues:

A) Some genes have a gene stable ID of the incorrect form "Transcript:"

B) Some genes have a CDS name/ID instead of a transcript name/ID as a "stable transcript ID"

C) Some data might be outdated in BioMart as "T13A10.10b" (for example) is showing up when it shouldn't be (it's a retired CDS name/ID)

A user was just asking me how to translate transcript IDs into gene IDs/names, and I thought this should be possible in ParaSite BioMart, but this issue prevents that type of mapping output.

**Comment by khowe** [comment]
@chris-grove the second issue is due to the fact that the current live ParaSite BioMart is based on WS265. In a release subsequent to WS265 (I think it was WS267), we changed our transcript builder to ensure that all transcripts get a .N suffix, even if they are the only transcript for a CDS. This ensures that transcript and CDS ids are distinct. We're currently preparing ParaSite release 12, which is based on WS267, where this problem will go away. 

The first issue (Transcript:XXX gene ids) is a bug, plain and simple. @wbazant can you please look into this one for WBPS12?

**Comment by chris-grove** [comment]
@khowe 
OK, sounds good. Thanks!

**Comment by wbazant** [comment]
The spurious genes for mature miRNAs will go away from BioMart in WBPS12. You will still be able to access them on the site if you know where to look, but "give me the list of all the miRNAs" won't bring them up.

**Comment by epaule** [comment]
WBPS12 was released a while ago
