### ISSUE TITLE
  how do I search for the function of a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6749]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do I search for the function of a gene?</p>

**Reported by:** Anon***** (soph**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

**Comment by chris-grove** [comment]
Email to user:
"""
You may want to look at a WormBase gene page, like this one:

https://www.wormbase.org/species/c_elegans/gene/WBGene00000898#03c--10

and in particular look at the information provided in the "Gene Ontology" widget and the "Phenotypes" widget.

Let us know if you have additional questions.
"""
