### ISSUE TITLE
Hello,
I'm writing regarding strain gene mrpl-32 (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6750]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I'm writing regarding strain gene mrpl-32 (gk944287). On this website (https://www.wormbase.org/species/c_elegans/gene/WBGene00016249#0fab-9gedc4-3) is described as deletion mutant but on this webpage (https://www.wormbase.org/species/c_elegans/variation/WBVar01480028#02-45-3) it's described as a point mutant. This is true for other mutations in the mrpl-32 that have now be re-analyzed by million mutation project. Would it be possible to correct this?
Thank you for your help.
Best regards,
visitor_name Raj

**Reported by:** Doro** (doro************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar01480028#02-45-3">https://www.wormbase.org/species/c_elegans/variation/WBVar01480028#02-45-3</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
@tharris @sibyl229 
This is another case where the GitHub email (with masked name and email address) was sent but the help desk email (with exposed contact info) was not.

**Comment by chris-grove** [comment]
Email to user (email acquired from Olark):
"This mutation (gk944287) happens to be both a deletion AND a point mutation (single base pair deletion)."
