### ISSUE TITLE
Cannot log in to WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6752]
I can't log in to WormMine on Firefox or Chrome. On Firefox, when I attempt to log in, I just get a blank page. On Chrome, I get an error message:

<img width="552" alt="screenshot 2018-11-26 10 09 57" src="https://user-images.githubusercontent.com/611382/49022681-71512600-f163-11e8-9c36-dfa784f83a53.png">

**Comment by nuin** [comment]
There was an error connecting to PostgreSQL. Tomcat restarted, login capabilities restored.
