### ISSUE TITLE
Cannot upload and save lists in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6753]
I cannot currently upload a list into WormMine. I first upload the list and arrive successfully at the confirmation and list-naming page, but then when I go to save the list I get a strange double-screen error message that looks like this:

<img width="2197" alt="screenshot 2018-11-26 10 07 53" src="https://user-images.githubusercontent.com/611382/49022843-db69cb00-f163-11e8-881a-43ff86c6acc2.png">

It appears to be happening with any lists I try to upload.

**Comment by chris-grove** [comment]
I get the same results on Firefox and Chrome

**Comment by nuin** [comment]
Problem with Postgres connection was probably the issue, @chris-grove

**Comment by nuin** [comment]
List was created successfully on my end.
