### ISSUE TITLE
blast organisms for WS268

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6759]
that is something for the to-do list for the WS268 release, and might resolve itself as soon as the blast on staging gets updated to WS268 data:

the new strains for C.elegans, C.remanei and also the new species should show up on the dropdown menu

**Comment by sibyl229** [comment]
Hi @epaule the BLAST species should be up to date with the new species: https://staging.wormbase.org/tools/blast_blat Could you doublecheck? Thanks!

**Comment by epaule** [comment]
Hi @sibyl229 I think the protein set for VC2010 / C.elegans is missing. The rest looks fine

**Comment by sibyl229** [comment]
Hi @epaule thanks for checking! Let's include @tharris in the discussion. It looks like that BLAST database is missing proteins for VC2010. 

I'm not sure how to trace the source of the problem. Do you know whether the input for building the BLAST database is available for VC2010 proteins?

VC2010:
```
$ ls /usr/local/wormbase/databases/WS268/blast/c_elegans/PRJEB28388
ests.fa  ests.fa.nin  formatdb.log  genomic.fa  genomic.fa.nhr  genomic.fa.nin  genomic.fa.nsq
```

N2:
```
$ ls /usr/local/wormbase/databases/WS268/blast/c_elegans/PRJNA13758
ests.fa      ests.fa.nin  formatdb.log  genomic.fa.nhr  genomic.fa.nsq  peptide.fa.phr  peptide.fa.psq
ests.fa.nhr  ests.fa.nsq  genomic.fa    genomic.fa.nin  peptide.fa      peptide.fa.pin
```

**Comment by epaule** [comment]
I think it might be because we just added the VC2010 proteins to the FTP
site, so they probably weren't around when the blast databases have been
built.

**Comment by tharris** [comment]
Correct. I will need to rebuild them.

**Comment by sibyl229** [comment]
Great! Thanks @epaule @tharris

**Comment by sibyl229** [comment]
I think we fixed this. If not, please feel free to re-open.
