### ISSUE TITLE
  Identify the number of exons for a ce...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6764]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Identify the number of exons for a certain gene sequence?<br/>Specifically vab-7(e1562), found in CB1562 strain.</p>

**Reported by:** Nick (notv****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by chris-grove** [comment]
From @raymond91125 
"It doesn't seem like we have the information on that variation

Thanks."

**Comment by chris-grove** [comment]
My reply to user:
"vab-7 has 5 exons as seen on the vab-7 gene page here:

https://www.wormbase.org/species/c_elegans/gene/WBGene00006873#09--10

Are you looking for something else?"

Closing. Will reopen if necessary.
