### ISSUE TITLE
  register to get an account. I'm start...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6765]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;register to get an account. I'm starting a project using C. elegans as an host model, until now my lab was not a worm lab, but from 2002-2005 I worked in Jonathan Ewbank's lab in Marseille, France. How do I set up an account on wormbase please?</p>

**Reported by:** Eliz************ (eliz**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by ceciliaWBPerson1** [comment]
contacted user
