### ISSUE TITLE
  How should I go about petitioning to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6767]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How should I go about petitioning to changing Y53G8AL.2 to nduf-9 and wanted to check with you all first. We have shown that RNAi of the gene Y53G8AL.2 dramatically reduces respiration. It's the reciprocal best BLAST hit with human mitochondrial gene NDUFA9. Thanks!</p>

**Reported by:** Josh************ (jcr3********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by chris-grove** [comment]
Had to guess user's email address. My email:
"We're having some issues with our help submission form which omits most of the contact information, so I'm guessing that this question was submitted by you. If not, please let us know.

If you'd like to request a new gene name, you can email genenames@wormbase.org (CC'ed). Tim Schedl (WormBase nomenclature tsar) should get back to you soon about your request."

**Comment by epaule** [comment]
I assume he did propose the change to Tim
