### ISSUE TITLE
missing files from the FTP site

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6770]
Erich pointed out that some of the files for VC2010 were missing from the WormBase FTP site. I added them to the EBI site, it just need syncing again.

**Comment by sibyl229** [comment]
Hi @tharris just letting you know about this issue that requires a re-syncing of the FTP site from the EBI site.

**Comment by sibyl229** [comment]
Hi @epaule the VC2010 files should be on the FTP site now: ftp://ftp.wormbase.org/pub/wormbase/releases/WS268/species/c_elegans/PRJEB28388/

**Comment by epaule** [comment]
thanks @sibyl229
