### ISSUE TITLE
"Smart" database linkouts broken on motif page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6771]
On the motif page:

https://www.wormbase.org/resources/motif/SMART:SM00353#01--10

The "External Links" widget has two (apparent) links, one to the "Name" column entry "smart" and another to the "Entry" column entry "SM00353", both of which open a blank page when opened with the URL address listed as "about:blank"

**Comment by chris-grove** [comment]
The "smart" link should probably link to:

http://smart.embl-heidelberg.de/

and the ID link "SM000353" should link to:

http://smart.embl-heidelberg.de/smart/do_annotation.pl?BLAST=DUMMY&DOMAIN=SM000353

or something like it.

**Comment by epaule** [comment]
fixed in c2d2b43ff44666970382f4dd9558c310c9b51412
