### ISSUE TITLE
what is the gene size and base pair of lrk-1 gene ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6776]
*Help Desk query collected when no chat operators were online. Follow up required.*

what is the gene size and base pair of lrk-1 gene in c.elegans

**Reported by:** neha****** (neha********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00003068#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00003068#0-9g-3</a>
**Browser:** Firefox 63.0

**Comment by chris-grove** [comment]
You can find gene size information in the "Sequences" and "Location" widgets on a gene page. Here is the gene page for lrk-1:


https://www.wormbase.org/species/c_elegans/gene/WBGene00003068#09g--10


For gene size, you can take the difference in genomic coordinates (n2 - n1 + 1) taken from the Location widget, or you can simply click on the double-helix icon for the transcript in the Sequences widget and look at the length of the unspliced transcript (both approaches will give you the length 14,471bp). You can find whichever relevant sequence you're looking for in the Sequences widget as well.


Let us know if you have further questions.
