### ISSUE TITLE
  Hi, I want to BLAST the protein seque...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6777]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I want to BLAST the protein sequence of HTAS-1 (CE03848) to all the nematode species. Is it possible to BLAST it with all the nematode species at once? Like how we can do in NCBI blast?<br/>visitor_name</p><p>What were you doing? <br />&nbsp;&nbsp;I am trying to BLAST this HTAS-1 protein sequence to all the Nematode species available in this database:

>HTAS-1
MARLKQRPNRILNTSTKTSSAKKKKKRISRSTRSGLTFPVGRIHRKLRETTRGKQRISAGASVFMAATLEYLTTELMEMS
AIAANESKKSRVTPRHLHLAIYGDQETAQLLDKVTLPQGGVTPMPIHPSLLPKKKAKEDDKENNS

</p>

**Reported by:** Swad** (ssin******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by epaule** [comment]
we can do that even better than that, as we have way more worms genomes ;-)
Try https://parasite.wormbase.org/Multi/Tools/Blast and pick either all, some clades or whatever nematodes you might be interested in.

If you only want the orthologs, you could actually just look them up in WormBase by going to the homologs section of the respective gene.
