### ISSUE TITLE
  Re: Request for allele and strain des...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6782]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Re: Request for allele and strain designation<br/>Dear Wormbase,<br/>my name is visitor_name, and I have just started my own worm lab at the Institute Curie in Paris, France. I am not sure whether this is the right forum for this, but I'd like to request an allele designation and strain name designation. <br/>If still available, I'd like the following designations:<br/>Strain: WKE<br/>Allele: wkl<br/>My lab's website is:<br/>https://science.institut-curie.org/research/multiscale-physics-biology-chemistry/umr168-physical-chemistry/quantitative-developmental-biology/<br/>If this is not the right forum to ask for this, do you happen to know where I should send my request? <br/>Thanks and kind regards<br/>visitor_name<br/>Also, </p>

**Reported by:** Wolf********* (wolf******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by ceciliaWBPerson1** [comment]
I contacted him
