### ISSUE TITLE
C.inopinata

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6785]
The C.inopinata genes don't show up properly on staging (i put below a working C.anagaria for comparison):

https://staging.wormbase.org/species/c_inopinata/gene/PRJDB5687_Sp34_30261000
https://staging.wormbase.org/species/c_angaria/gene/PRJNA51225_Cang_2012_03_13_06428.g20263

TreeView:
https://staging.wormbase.org/tools/tree/run?name=PRJDB5687_Sp34_30261000;class=Gene
https://staging.wormbase.org/tools/tree/run?name=PRJNA51225_Cang_2012_03_13_06428.g20263;class=Gene

at first I thought it might be the dots, but then C.nigoni works (and it has additional dots in the ids)

**Comment by sibyl229** [comment]
Hi @epaule I just included C.inopinata and C. latens in the web display. The gene pages you linked to should be working now: https://staging.wormbase.org/species/c_inopinata/gene/PRJDB5687_Sp34_30261000

Thanks for letting me know.

**Comment by epaule** [comment]
looking good :+1:
