### ISSUE TITLE
Errors on anatomy page: Ontology Browser timing out

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6788]
@tharris @sibyl229 

I'm currently getting an error on the Tree Display widget on the "intestine" anatomy page:

https://www.wormbase.org/species/all/anatomy_term/WBbt:0005772#045--10

Also, @raymond91125 @azurebrd , the Ontology Browser widget on the same page is timing out.

**Comment by tharris** [comment]
The Tree Display issue is resolved. I'm not very familiar with the Ontology Browser but I'm guessing in may be falling over on a broad term like Intestine?

**Comment by chris-grove** [comment]
Thanks @tharris 
OK, it seems the Ontology Browser widget is failing to load across the board. I will assign @raymond91125 and @azurebrd

**Comment by nuin** [comment]
@chris-grove I got an error first time accessing the page, and after reloading it works fine. There was an error initially but I didn't catch it.

**Comment by chris-grove** [comment]
OK, it was consistently timing out on every page I checked a few minutes ago. Now it seems resolved. Thanks.

**Comment by tharris** [comment]
The little elves behind the scenes must have fixed something.

**Comment by chris-grove** [comment]
Yeah, I figured as much

**Comment by raymond91125** [comment]
Caltech was playing with power earlier and some how the server went out despite UPS. I restarted it. thanks for the alert.
