### ISSUE TITLE
Hello, WBRNAi00080874 seems to map only to let-413...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6789]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, WBRNAi00080874 seems to map only to let-413 gene. However when retrieving data using WormMine, the field "Uniquely mapped" is FALSE. I did not find additional curation remarks such as that the entire sequence of the clone used for RNAi is not known. Why "uniquely mapped" is FALSE? Many thanks, Paula

**Reported by:** Paul****** (paul****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00080874#041--10">https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00080874#041--10</a>
**Browser:** Chrome 70.0.3538.110

**Comment by chris-grove** [comment]
Email to user:
"""
Thanks for your inquiry. It seems you've found something odd with our "uniquely mapped" tagging.

@khowe , I can't see a reason why this RNAi experiment would not be considered "uniquely mapped" although it seems to have passed through the mapping pipeline without getting this tag:

https://wormbase.org/species/c_elegans/rnai/WBRNAi00080874#016--10

Also, I found several instances in which there are clearly two primary RNAi target genes predicted but they still have the "uniquely mapped" tag:

https://wormbase.org/species/c_elegans/rnai/WBRNAi00053497#016--10
https://wormbase.org/species/c_elegans/rnai/WBRNAi00048151#016--10

Maybe there's something up with our "uniquely mapped" tagging?
"""

**Comment by chris-grove** [comment]
I will modify Citace Minus to remove the "uniquely_mapped" tag as it is legacy and no longer maintained. Will be fixed for WS270 release.

**Comment by chris-grove** [comment]
Modification .ACE file uploaded for midbuild on Caltech Spica machine. @WenChenWormBase will read in for midbuild. 

Also, @nuin is in process of removing attribute from WormMine model and load

Closing ticket. Will reopen if necessary.

**Comment by chris-grove** [comment]
From @khowe 
"""
Hi Chris, 

We don't populate the "Uniquely_mapped" tag during the build. Looking at one of your examples, the tag has a timestamp of 2005, and comes from citace. 

I believe this a legacy concept that has been superseded by our Primary/Secondary treatment. I think you should remove the population of the tag from the next citace upload. 

Kevin
"""

**Comment by chris-grove** [comment]
My email reply to @khowe:
"""
Hi Kevin,

OK, thanks. These are probably all coming from Citace Minus then (earlier large scale studies mapped a long time ago) and not our active curation database (OA/Postgres). I'll have them removed for the next upload. I think tagging these RNAi experiments as uniquely mapped is useful to users, so maybe we can reinstate that in the current pipeline at some point.

Thanks,

Chris
"""

My follow up with user:
"""
OK, it seems that the "uniquely mapped" attribute is a legacy tag that no longer applies, so you should ignore that value. We will eliminate the field from WormMine and remove it from our database.
"""

**Comment by chris-grove** [comment]
Response from user:
"""
Many thanks for your replay.

What about the "Inhibits predicted gene" in the "RNAi Results" field?

For example, when requesting the RNAi data for WBGene00001496 (frm-10/F25H9.5), WormMine retrieves WBRNAi00027302 and the field "Inhibits predicted gene" shows F25H9.6. The viewer in WormBase shows that WBRNAi00027302 maps to both genes. Should I interpret that when the "Inhibits predicted gene" is a different gene from the one requested I am in cases in which the RNAi construct map to contiguous genes or gene family members/closed paralogs? Could I use this field as a "uniquely mapped" indicator?

Many thanks for your help!
"""

**Comment by chris-grove** [comment]
My response to user:
"""
The "Inhibits predicted gene" field is a little bit misleading, I think, as it is only going to show the coding sequence (CDS) that overlaps the dsRNA sequence captured in the RNAi experiment object. In the case you point out, WBRNAi00027302, you can see more details on the WormBase page:

https://wormbase.org/species/c_elegans/rnai/WBRNAi00027302#016--10

We can see that both "frm-10" and "F25H9.6" are indicated as primary (predicted) gene targets for this experiment. If you look down in the "Tree Display" widget, you can see how the data is stored in the database. There are two genes listed under the "Inhibits" > "Gene" field:

WBGene00009138
WBGene00001496

but only one CDS listed in the "Inhibits" > "Predicted_gene" field:

F25H9.6

This seems strange, but the reason becomes evident if you look at the page for the reagent listed in the "Details" widget. Click on the hyperlinked "sjj_F25H9.6" in the "Reagent" field of the "Details" widget, and you will be directed to the page for that reagent (PCR product):

https://wormbase.org/species/all/pcr_oligo/sjj_F25H9.6#01--10

Make sure the "Location" widget is turned on, and you can see that the sjj_F25H9.6 PCR product overlaps most of the F25H9.6 transcript, but also substantially overlaps the 3' untranslated region (3' UTR) of frm-10 (F25H9.5) (but NOT any of the frm-10 coding sequence (CDS)). As a result, the RNAi sequence gets mapped to both genes, but only one CDS.

If you're interested in the genes that are predicted to be inhibited by the RNAi experiment, to avoid confusion just look into the "Inhibits Gene" field and not the "Inhibits Predicted Gene" (it should probably be called "Overlapping CDS").

As it seems you're interested in the RNAi experiments that are uniquely mapped, I've queried our latest database build (WS268) for all RNAi experiments that map to a single gene and provide the list of RNAi objects and their respective genes (attached).

If you're interested in something else, or would like additional information for each uniquely mapped RNAi experiment, let me know and I can send it to you.
"""
