### ISSUE TITLE
  Hi, I'm trying to find a gene that is...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6791]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm trying to find a gene that is expressed across a long list of neurons but not in neurons outside of the list, in C. elegans. I have the list of neurons, but I'm not sure how to use the provided tools or API to achieve this purpose.</p>

**Reported by:** Kara (kara*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by 003084-K** [comment]
so really what I would like is a way to overlap of all the expression patterns of the various neurons in c elegans

**Comment by chris-grove** [comment]
@003084-K 
This could be a bit tricky to do efficiently. Can you send us the list of neurons? I'm assuming you're referring to a list of N named neurons, each from the 302 total count of neurons (in hermaphrodites at least), where the NOT list is the (302 - N) neurons? As opposed to genes expressed in all neurons within a neuron group like cholinergic neurons but not in dopaminergic neurons?

**Comment by chris-grove** [comment]
@003084-K 
I meant to add: can you provide your list(s)?

**Comment by 003084-K** [comment]
Hi Chris,

I am indeed interested in the hermaphrodite worm. Yes, I'd like a gene
that's expressed by all (or as many as possible) of the neurons in the
following list length N but not in any of the 302-N remaining neurons. I
may want to add more neurons to this list later
'ADEL', 'ADER', 'ADFL', 'ADFR', 'ADLL', 'ADLR', 'AFDL', 'AFDR', 'ALML',
'ALMR', 'ALNL', 'ALNR', 'AQR', 'ASEL', 'ASER', 'ASGL', 'ASGR', 'ASHL',
'ASHR', 'ASIL', 'ASIR', 'ASJL', 'ASJR', 'ASKL', 'ASKR', 'AUAL', 'AUAR',
'AVM', 'AWAL', 'AWAR', 'AWBL', 'AWBR', 'AWCL', 'AWCR', 'BAGL', 'BAGR',
'CEPDL', 'CEPDR', 'CEPVL', 'CEPVR', 'FLPL', 'FLPR', 'IL2DL', 'IL2DR',
'IL2VL', 'IL2VR', 'IL2L', 'IL2R', 'OLLL', 'OLLR', 'OLQDL', 'OLQDR',
'OLQVL', 'OLQVR', 'PDEL', 'PDER', 'PHAL', 'PHAR', 'PHBL', 'PHBR', 'PHCL',
'PHCR', 'PLML', 'PLMR', 'PLNL', 'PLNR', 'PQR', 'URYDL', 'URYDR', 'URYVL',
'URYVR', 'IL1DL', 'IL1DR', 'IL1VL', 'IL1VR', 'IL1L', 'IL1R', 'URADL',
'URADR', 'URAVL', 'URAVR', 'AVG', 'PVM', 'PVR', 'URBL', 'URBR', 'URXL',
'URXR'

**Comment by chris-grove** [comment]
Closing. Will reopen if necessary

**Comment by 003084-K** [comment]
Hi @chris-grove ! Happy New Year. Sorry for my delayed response. I was on a long holiday. My goal is to use as few genes as possible to to target all primary sensory neurons (neurons with direct roles in sensing stimuli) in a hermaphrodite C. elegans, without targeting, for example, a motor neuron that has no sensory role.

**Comment by chris-grove** [comment]
@003084-K 
Ah, OK, thanks for the explanation. In that case, you might find this page useful:

https://www.wormbase.org/species/all/anatomy_term/WBbt:0005759#04--10

Note that at the bottom of the "Ontology Browser" widget is a list of genes that "may be specifically expressed" in sensory neurons. There are 80 candidate genes there to looks at. You will probably need to assess the individual expression patterns of each of those to try to come up with complete coverage of all sensory neurons, but at least that's a start.

**Comment by 003084-K** [comment]
@chris-grove 
Thanks for your help with this. So I have my list of sensory neurons, and I have a list of genes specific to sensory neurons. What I need then is to extract the list of neurons in which a gene is expressed, for each gene in the sensory-specific list. I can then try to use an optimization algorithm to determine the fewest genes necessary. What do you think the fastest way to extract this data is? I see API tools for developers and Ace Queries. I'm extremely new to WormBase and to any programming related to the internet, so the  method that requires the smallest time investment would be greatly preferred. Thanks!

**Comment by chris-grove** [comment]
@003084-K 
Yes, you can do this quite easily in WormMine. Here's a screen recording of the process:

https://www.dropbox.com/s/cms0aa97ppcfy8n/Extracting_anatomy_terms_for_sensory_neuron_genes_Jan_8_2019.mov?dl=0

Steps are:

1) Get list of (possibly) sensory neuron-specific genes from "sensory neuron" page at WormBase
2) Import list of genes into WormMine via list upload
3) Query WormMine for anatomy terms in which the list of genes is expressed
4) Save list of anatomy terms from the query results
5) Download list

Let me know if you have any questions about that process.

**Comment by 003084-K** [comment]
Hi @chris-grove 
Thanks for your demo video! It was really helpful in learning how to use WormMine. I'm actually fine with some of the genes being expressed in cells other than sensory neurons, as long as they aren't expressed in a list of motor neurons I have or in a list of interneurons I have. This will give me more genes to choose from. So I've been playing around with wormmine and wanted to see genes expressed in anatomy terms in List A but NOT expressed in anatomy terms in List B or List C or List D. I tried implementing this on WormWire, but some of the genes that come up with my query (e.g., eat-4) actually are expressed in neurons in List B or C (e.g., eat-4 is expressed in AIZR, which is in List A). I'm not sure if I did something incorrectly or if there is a bug. I've attached a screenshot of how I queried.

I would also like to search for specific life stage expression, but I think I typed in the wrong thing, so I just deleted that filter.

![screenshot 97](https://user-images.githubusercontent.com/41455075/51345998-560ee280-1a51-11e9-9b16-a7281ddba575.png)

**Comment by 003084-K** [comment]
Hi @chris-grove  
Okay, it is working! I just need to filter by life stage, but every way that I've tried to do this has given zero query results. This is the most recent way I tried.
![screenshot 98](https://user-images.githubusercontent.com/41455075/51353229-db4fc280-1a64-11e9-9e66-64790d6be463.png)

**Comment by chris-grove** [comment]
@003084-K 
OK, almost there. There are a few reasons this query will be more restrictive than you are intending, the reasons for which admittedly require a bit of knowledge about how WormMine works and how WormBase curates expression patterns:

You've constrained on your list of genes (which is good) but constrained the "Expression Patterns > Anatomy Terms > Life Stages > Contained In" by performing a LOOKUP on "L4 larva nematode". There are a few reasons this last constraint will be much more restrictive than you are intending: First, while wanting to restrict your query to genes that have an expression pattern that has been annotated to the L4 larval stage, what you've actually requested here is that the genes have an expression pattern with at least one anatomy term that is itself annotated to/affiliated with a life stage (meaning the anatomy term exists during the life stage), that is itself (the life stage) contained within another life stage that has a match to the text "L4 larva nematode". Note that every time you indent (more to the right) in the Query Overview you are now querying within the class under which you are indented. What you want, more simply is to constrain "Expression Patterns > Life Stages" to L4 larva. Second, there are many life stages in our life stage ontology, and unfortunately WormMine doesn't currently automatically account for ontology closure (in other words, it doesn't automatically account for a major life stage AND all of its subtypes simultaneously). Of all the L4 related life stages, the one used by far the most for C. elegans genes is actually "L4 larva Ce".

So, the query I would recommend is this:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.expressionPatterns.lifeStages.publicName" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.expressionPatterns.lifeStages.publicName" op="=" value="L4 larva Ce"/>
</query>`

where you can import this via the QueryBuilder tab "Import query from XML" link. Let me know if you have questions on that part. The query should then look like this:

<img width="1017" alt="screenshot 2019-01-18 10 08 22" src="https://user-images.githubusercontent.com/611382/51394712-0a1f7480-1b09-11e9-96a4-494342c58b76.png">

Then, constrain the genes (use the "CONSTRAIN" option for any of the selected gene fields) to your list of genes. There are 1,720 genes annotated to the "L4 larva Ce" life stage, so I think you should get some genes out of the query. 

Let me know how that goes.

**Comment by chris-grove** [comment]
@003084-K 
OK, great! I'm glad I could help. Good luck and let us know if you have more questions in the future.
