### ISSUE TITLE
I try to find gene name BN1106_s4099B000076 but i ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6794]
*Help Desk query collected when no chat operators were online. Follow up required.*

I try to find gene name BN1106_s4099B000076 but i did not find it on this website, can you help me? and could you please let me know how to do?

**Reported by:** thin********* (thin*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/search/phenotype/BN1106_s4099B000076">https://wormbase.org/search/phenotype/BN1106_s4099B000076</a>
**Browser:** Chrome 70.0.3538.110

**Comment by chris-grove** [comment]
You'll want to search our sister website/database WormBase ParaSite:


https://parasite.wormbase.org/


If you search there you can find the gene you're looking for:


https://parasite.wormbase.org/Fasciola_hepatica_prjeb25283/Gene/Idhistory?db=core;g=BN1106_s4099B000076


Let us know if you have other questions.
