### ISSUE TITLE
WormMine: Expr_pattern objects only being associated to a single gene

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6796]
I just realized that Expr_pattern objects in WS267 WormMine are only getting associated with a single gene, although there are 231 Expr_pattern objects in WS267 ACEDB that have associations to multiple genes. A more extreme example is Expr3417 which has 47 genes associated in ACEDB/WS267:

https://www.wormbase.org/species/all/expr_pattern/Expr3417#1023--10

but only one gene in WormMine:

`<query name="" model="genomic" view="ExpressionPattern.primaryIdentifier ExpressionPattern.gene.primaryIdentifier ExpressionPattern.gene.secondaryIdentifier ExpressionPattern.gene.symbol" longDescription="" sortOrder="ExpressionPattern.primaryIdentifier asc">
  <constraint path="ExpressionPattern.primaryIdentifier" op="=" value="Expr3417"/>
</query>`

We should make sure that Expr_pattern objects in WormMine get a one-to-many relationship with genes.

**Comment by chris-grove** [comment]
Updated query XML:

```
<query name="""" model=""genomic"" view=""ExpressionPattern.primaryIdentifier ExpressionPattern.genes.primaryIdentifier ExpressionPattern.genes.secondaryIdentifier ExpressionPattern.genes.symbol"" longDescription=""Return a list of all genes associated with expression pattern Expr3417"" sortOrder=""ExpressionPattern.primaryIdentifier asc"">
  <constraint path=""ExpressionPattern.primaryIdentifier"" op=""="" value=""Expr3417""/>
</query>
```

**Comment by nuin** [comment]
Seems fixed.
