### ISSUE TITLE
I can't open anything on the wormbase page, why is...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6799]
*Help Desk query collected when no chat operators were online. Follow up required.*

I can't open anything on the wormbase page, why is that?

**Reported by:** Beat******** (chen*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide#0123456--10">https://wormbase.org/about/userguide#0123456--10</a>
**Browser:** Chrome 63.0.3239.132

**Comment by WenChenWormBase** [comment]
Cannot reproduce the error.
