### ISSUE TITLE
Authors, people and meetings

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#6802]
Hello

I had always assumed that all authors on WBpapers were also WBpersons

https://wormbase.org/resources/paper/WBPaper00010598

only O'Connor, G is an active link.

This is not an isolated case:

https://wormbase.org/resources/paper/WBPaper00016617

Here, additionally in the page header, "Anthony A Ferrante" but in overview, the surname is omitted.

A problem from when abstracts were lifted over from Leon Avery’s site?

Looking at this also makes me wonder whether having the meetings as a class would not be useful (e.g. allowing one to search for all abstracts from a particular meeting that talked about a particular gene).

Thanks

Jonathan

**Comment by vanaukenk** [comment]
Hi Jonathan,

Thanks for your feedback.

We'll discuss your suggestions at our meeting today and see what is feasible wrt cleaning up some of the older abstracts.

Ideally, I think we'd want to have any literature searches handled by Textpresso, but right now I don't see meeting abstracts in the corpus.  I'll check with Michael Mueller about that, as well.

Best,
--Kimberly

**Comment by tharris** [comment]
I think the missing surnames on some of the paper pages is actually a display issue. @sibyl229 or whoever converted the person pages can you have a look?

**Comment by vanaukenk** [comment]
Thanks @tharris 
For some of these older abstracts, some authors don't have an associated WBPerson id, but if we could still fix the author display in those cases where the person page doesn't exist, that'd be great.

**Comment by vanaukenk** [comment]
Great; thank you @tharris

**Comment by ceciliaWBPerson1** [comment]
Hi, We decided not to created Persons when there is not enough data, for
example just Last names and initials.
I will look further into this paper after my dental surgery.
cecilia

**Comment by sibyl229** [comment]
ToDo for @sibyl229 
- [ ] correct problem in author name display (refer to example above)
- [ ] make sure author name isn't linked at the display

**Comment by sibyl229** [comment]
Hi @vanaukenk and @ceciliaWBPerson1 I have a question related to the display of Author and Person names in Paper Overview. I wonder if you could help me with it.

It has to do with how the name should be shown for a Person or an Author. 

What the web code currently does seems flawed. It attempts to truncate the Person and Author name into [Last_name], [First_initial][Middle_initial]. (e.g. "Sternberg, PW).

There are two problems with that approach:
- With an Author entity (which could appear as "Paul Sternberg" or "Sternberg Paul"), the web code won't be able to tell first name from last name to format it correctly
- If I simply display Author name in full, it seems odd and inconsistent to display the truncated Person name

I wonder if we could display Author name in full, and display the Person name using the Standard_name ACeDB tag or something else. What do you think?

Thanks!

**Comment by sibyl229** [comment]
It’s trying to enforce standard reference styling.
> Yeah, I understand. But I wonder if Author is shown as a full name while Person is shown a partial name, would that seem unfair?

> How many cases are there now where we people are only represented by Author objects? 
I will do a count on that and let you know tomorrow.

> Second, how consistent are the standard name entries of the person class? 
I can also concat first, middle and last name if that's better.

**Comment by raymond91125** [comment]
How about just show each author's name string verbatim and not to worry about what their person name string is, should they be a WBperson. The hyperlink should be preserved and reserved for when an author is a WBperson.

**Comment by sibyl229** [comment]
I like Raymond's idea. I didn't realize that the Author tag also included
the author that we recognize as a WBPerson.

**Comment by vanaukenk** [comment]
I concur with @raymond91125 and think this is the most straightforward approach.

We will in some cases have differences in how Author names are presented in articles coming from PubMed vs meeting abstracts, but I think that is okay.

**Comment by sibyl229** [comment]
The authors in Paper Overview should now work as @raymond91125 and @vanaukenk suggested. 

It would be displayed as the Author ID and linked to appropriate WBPerson page if applicable. 

If the WBPerson is unknown, the link will go to search and the search result will include potential WBPerson and Paper that **might** be associated with Author. Because the un-associated author link works differently, and has an uncertain aspect to in, I included a small question mark on the link. 

A question here: if someone is on the Paper page and find themselves to an Author un-associated with a WBPerson, what should they do?

**Comment by sibyl229** [comment]
Hi @vanaukenk just a reminder that the author wbperson confusion issue is on staging for testing: 
- https://staging.wormbase.org/resources/paper/WBPaper00010598#0--9 
- https://staging.wormbase.org/resources/paper/WBPaper00016617#0--9
Would you like to take a look to make sure its working as you intended? Thanks!

**Comment by vanaukenk** [comment]
@sibyl229 - Taking a look right now!

**Comment by vanaukenk** [comment]
@sibyl229 

I like the idea of differentiating an author who is also a WBPerson from one who is not, but what do you think of actually changing it so that the authors who *are* WB people have a superscript WB next to their name so that they are most clearly distinguished?  

The authors who are not WB people would still be linked to the 'Anything' search results when someone clicks on their name, but there wouldn't be a question mark next to their name. 

It might also be nice to link out from each WBPaper page to the Person cgi form (https://wormbase.org/submissions/person.cgi) to encourage authors who are not WB people to submit their information and link their papers.  @ceciliaWBPerson1 - what do you think of that idea?

**Comment by sibyl229** [comment]
Hi @vanaukenk Thanks for the comment! I like your ideas. 

I agree with you that question mark might not be a good choice here. It might appear that we are uncertain about the author names we list, when the message is that we can't identify the person based on the name. Do you think a 🔍 icon would be more clear, with the intent here?

It's a good idea to encouraging authors to contact us by providing ways to do so on paper page. This can be done. Maybe we can have "

**Comment by sibyl229** [comment]
![screen shot 2019-02-20 at 3 58 45 pm](https://user-images.githubusercontent.com/1753893/53124037-6d496000-3528-11e9-960b-af9ee48cd893.png)

**Comment by vanaukenk** [comment]
Hi @sibyl229 
I was actually thinking that we wouldn't have anything next to the authors that are not also a WBPerson, but put a 'WB' next to the ones that are.
Clicking on the author names that are not a WBPerson would still take a user to the Anything search page.

**Comment by sibyl229** [comment]
@vanaukenk Yes, I understand. Let me clarify the goals and considerations, also to organize my own thoughts. I don't have a good solution that satisfy all of them, and I think they are all pretty important. Maybe you can help me.

Here are some of the considerations:

**We might want to visually differentiate what a link does.** 

A link that goes to another wormbase report page is the default behaviour. The reason I put a **?** or a 🔍 by the author is that the behaviour of those links _deviates_ from the default behaviour.

Unfortunately, 🔍 also calls attention to things that we have less info about, that we might not want to draw attention to (except the original author).

**We want users to contact us to provide authorship information that we missed.** 

This might be another reason to flag those ones, so we can do something like:

> **Tip:**
> See a 🔍 by your name? Please help us [identify you](https://wormbase.org/submissions/person.cgi).

On the other hand, missing a [WB] or 👤 next to their name, while seeing others having them might encourage people to contact us. 

**We want to make the message of clear**.  A WormBase recognized person vs someone we have problem identifying. And we want to avoid misunderstanding, would [WB] be interpreted as associated with wormbase.

**We want to minimize visual noise.** We want the visual cues we put there to add information without causing too much distraction. The number of times we place such visual cue also need to be taken into account, as well as the size and color, and word. I will attach some screenshots later.

**We likely want to have a consistent look of for the same kind of link across wormbase site**

**Comment by vanaukenk** [comment]
@sibyl229  Great points and I completely agree with you.

I really like the idea of having a Tip to help guide people to filling out their person information.

Maybe another simple option is to only link those authors that are WB people and then use the Tip to guide people whose name is not linked to the person form.

Perhaps we could say something like:

Tip: 
If your name is not linked, please help us identify you.

I'll look for your screenshots, though, when you've had a chance to attach them.  

Thx.

**Comment by sibyl229** [comment]
Hi @vanaukenk thanks a lot for going through the design process with me! I like this approach, might seem that we came back full circle 😄 , but I think we learned something! 

The lack of link communicates the message most clearly (that we can't identify those authors). 

Maybe we want to avoid disappointment (of clicking on an author link and didn't find anything they look for). It's difficult to balance between providing service and avoid disappointment.

Maybe I will implement this approach you said above. And if we come up something more effective, we can change it.

Here are some screenshots from my previous experimentation:

Wikipedia approach to highlight non-existent links:
![screen shot 2019-02-21 at 10 48 46 am](https://user-images.githubusercontent.com/1753893/53182507-9b31b180-35c7-11e9-852d-5e8e194d7f0c.png)

No links for author
![screen shot 2019-02-21 at 10 49 11 am](https://user-images.githubusercontent.com/1753893/53182508-9b31b180-35c7-11e9-8b0c-e613ed66798f.png)

Mark identified author
![screen shot 2019-02-21 at 10 49 52 am](https://user-images.githubusercontent.com/1753893/53182509-9bca4800-35c7-11e9-8820-b90ced0d38da.png)
![screen shot 2019-02-21 at 10 50 26 am](https://user-images.githubusercontent.com/1753893/53182510-9bca4800-35c7-11e9-868f-1d91c1ba86de.png)

Assess level of visual cue noise on other pages:
![screen shot 2019-02-21 at 10 37 28 am](https://user-images.githubusercontent.com/1753893/53182497-9a991b00-35c7-11e9-86ba-9b4eac660fad.png)
![screen shot 2019-02-21 at 10 42 52 am](https://user-images.githubusercontent.com/1753893/53182499-9b31b180-35c7-11e9-8a28-2b8011353372.png)
![screen shot 2019-02-21 at 10 44 59 am](https://user-images.githubusercontent.com/1753893/53182505-9b31b180-35c7-11e9-942c-fa84db1e3752.png)
![screen shot 2019-02-21 at 10 45 18 am](https://user-images.githubusercontent.com/1753893/53182506-9b31b180-35c7-11e9-8c1e-d1a07aa444cb.png)

**Comment by vanaukenk** [comment]
Thanks for the screenshots @sibyl229 
It's really helpful to be able to look at these for comparison.
I also like the Wikipedia approach to highlighting non-existent links.  Visually it's less crowded, but still conveys that we are missing information.
I leave it to you to decide if no color or red color for authors with no person information is best.
Either way, it'd still be great to link out to the Person from from the Paper pages.

**Comment by sibyl229** [comment]
Thanks @vanaukenk for your feedback! 

I also like the the wikipedia non-existent link approach. I will implement that one. If people find the colour distracting, we can try the no link approach. 

I will let you know when it's done. Thanks again!

**Comment by sibyl229** [comment]
Hi @vanaukenk the wikipedia style author link is ready for testing on staging now:
https://staging.wormbase.org/resources/paper/WBPaper00010598#0--10
https://staging.wormbase.org/resources/paper/WBPaper00016617

I made the red a shade darker, so the difference is noticeable without drawing too much attention.
![screen shot 2019-02-26 at 2 47 19 pm](https://user-images.githubusercontent.com/1753893/53443040-bd1ca100-39d8-11e9-9519-17c916a5ae0a.png)

**Comment by sibyl229** [comment]
Fix was deployed to production in WS270. Closing. Please feel free to repo if there is a problem.
