### ISSUE TITLE
  EPG-5 should be fused to C56C10.11 to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6804]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;EPG-5 should be fused to C56C10.11 to make complete EPG-5 homologous to all other variants including C remanei and C latens.</p>

**Reported by:** Erik********** (jorg**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by gw3** [comment]
Erik,

Thank you for spotting this and informing us.
We completely agree that these two genes should be merged.
This will be done for release WS270.

Gary Williams
