### ISSUE TITLE
  Hello, Is there a way to download a l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6808]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>Is there a way to download a list of all the Operons in the C. Elegans genome and their loci in the form of an excel file? The same way i would use Biomart to download a list of genes with their relevant information?</p>

**Reported by:** Anon***** (hasa**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Hasan,

You can pull the location information directly from our gff files on the 
ftp:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS269/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS269.annotations.gff3.gz

If you pull out all the lines containing operon this will give you the 
raw data you require. This can easily be turned into a cvs file which 
can be imported into excel.

I have created a .csv file containing

Operon Name,Chromosome,strand,start,stop,type,genes+

Available here: ftp://ftp.sanger.ac.uk/pub/wormbase/STAFF/pad/Hasan6808.csv

I hop[e this is what you are after.

Paul
[HelpDesk]



On 01/01/2019 13:36, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> Is there a way to download a list of all the Operons in the C. Elegans 
> genome and their loci in the form of an excel file? The same way i 
> would use Biomart to download a list of genes with their relevant 
> information?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6808. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6808>.
>
> Reported by: hasan.ishtayeh@mail.huji.ac.il
> 01 Jan 19 13:36
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/71.0.3578.98 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
