### ISSUE TITLE
  Dear team from WormBase, I am interes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6810]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear team from WormBase,<br/>I am interested in chondroitin sulfotransferases in C. elegans and when I was looking at the sequences that are predicted to have such activity I noticed a few problems:<br/>1) Some of them are identical to other genes (e.g. T24A6.16 and F40C5.1 or ZK1025.2 and ZK1025.8) <br/>2) Some are partially identical but assigned to different chromosomes (B0273.115 on Chr IV is identical to the last 2-3 exons of Y48G1BL.7 on Chr I) 3) At least one is connected with wrong "Other names" (C18B2.2 is said to be called seb-3/secr-2 but the sequence of seb-3 matches with C18B2.12). <br/>I don't know how to report or change these things and I assume that you'd like to check them before anything is done so I thought I'd let you know this way. <br/>Please let me know what I can/ should do! <br/>Thanks for your help (and happy New Year),<br/>Tabea</p>

**Reported by:** Tabe********* (tabe*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by Paul-Davis** [comment]
Hi Tabea,

Reporting via this route is exactly the right thing to do.

Happy New Year to you.

I will go through each of your reports/questions in turn.

> 1) Some of them are identical to other genes (e.g. T24A6.16 and 
> F40C5.1 or ZK1025.2 and ZK1025.8)
>
In many gene families there are natural gene duplication/expansion 
events. Taking your 1st example (T24A6.16 and F40C5.1) and running it 
through an alignment programme, there are 2 G->A bp changes which would 
point to a recent duplication event that has only accumulated 2 mutation.
>
> 2) Some are partially identical but assigned to different chromosomes 
> (B0273.115 on Chr IV is identical to the last 2-3 exons of Y48G1BL.7 
> on Chr I) 3)
>
This appears to be a partial duplication event where there appears to be 
an intact ORF made up of 3 exons.

Doing a protein alignment of this duplication shows 4 amino acid 
differences between the predicted protein products of       these 2 loci.

As this is a recent duplication we cannot say for sure if this intact 3 
exon ORF is functional, but the altered regions do appear to have RNASeq 
and EST support suggesting Transcription at least.

> At least one is connected with wrong "Other names" (C18B2.2 is said to 
> be called seb-3/secr-2 but the sequence of seb-3 matches with C18B2.12).
>
I agree the Other names make this confusing. It appears that in 2012 
Public_name seb-3 was assigned to the incorrect gene (C18B2.2) and 
Other_name secr-2

In 2013 this discrepancy was identified and seb-3 was assigned to the 
correct gene (C18B2.12) as Main/Public_name and Other_name secr-2

Unfortunately the curator left both as Other_names on C18B2.2 leading to 
this confusion, I will document and remove these for the WS270 release..

>
> I don't know how to report or change these things and I assume that 
> you'd like to check them before anything is done so I thought I'd let 
> you know this way.
> Please let me know what I can/ should do!
> Thanks for your help (and happy New Year),
> Tabea
>
Thanks again for reporting this, please feel free to email me if you 
have additional questions.

Paul

[HelpDesk/Sequence curation]


> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6810. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6810>.
>
> Reported by: Tabea Dierker (tabea.dierker@imbim.uu.se)
> 02 Jan 19 17:41
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 
> Firefox/64.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
