### ISSUE TITLE
  How do I find a list of mapping SNPs ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6815]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find a list of mapping SNPs between Hawaiian and N2. The old link "http://genome.wustl.edu/genome/celegans/celegans_snp.cgi" seems to be dead.</p><p>What were you doing? <br />&nbsp;&nbsp;Mapping</p>

**Reported by:** Shai******* (shah*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
I'm not sure if this is exactly what you're looking for, but I've used the current (WS267 release) N2 GFF3 annotations file to pull out all SNPs present in the Hawaiian strain CB4856, in GFF3 format (zipped file attached).

To do this yourself (for a future release, for example), you can download the current GFF3 annotations file from this FTP directory:


ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/


Note that the current file is:


ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS267.annotations.gff3.gz


but the "WS267" release version will increment with each new release so the exact file name will change. Once I've downloaded that file, in the same directory I can run the Unix command on the command line/terminal:


`awk 'BEGIN {FS="\t";OFS="\t"} {if(($3 == "SNP") && ($9 ~ "CB4856")) print}' c_elegans.PRJNA13758.WS267.annotations.gff3 > WS267_Hawaiian_SNPs.txt`


to generate the file.


Please let us know if you're looking for something else.

**Comment by chris-grove** [comment]
Just tried resending the email again and it failed. I have now emailed the Rockefeller help desk a second time (first time last Friday Jan 4) as I have not heard back from them.

**Comment by chris-grove** [comment]
OK, resent the email now. It seems the file attachment was too large. Closing.
