### ISSUE TITLE
I would like to know more about the sepetitions wi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6821]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to know more about the sepetitions within the sequence of htp-3 gene. Thanks

**Reported by:** Cris**** (clop**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/transcript/F57C9.5.1#06--10">https://wormbase.org/species/c_elegans/transcript/F57C9.5.1#06--10</a>
**Browser:** Safari 12.0.1

**Comment by Paul-Davis** [comment]
Dear Cristina,

Thanks for your email.

Could you give me a little more detail about what you would like help with.

Thank you

Paul
[HelpDesk]


On 07/01/2019 11:01, no-reply@wormbase.org wrote:
> offline chat I would like to know more about the sepetitions within 
> the sequence of htp-3 gene. Thanks
>
> Submitted From:
>   https://wormbase.org/species/c_elegans/transcript/F57C9.5.1#06--10 
> https://wormbase.org/species/c_elegans/transcript/F57C9.5.1#06--10 
> <http://www.wormbase.org/https://wormbase.org/species/c_elegans/transcript/F57C9.5.1#06--10> 
>
>
> This issue has been assigned ticket number: #6821. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6821>.
>
> Reported by: Cristina (clopez@embl.de)
> 07 Jan 19 11:01
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by tharris** [comment]
Closing. No response from user.
