### ISSUE TITLE
  Hello, I've found on this web page ht...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6825]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I've found on this web page<br/>https://www.wormbase.org/species/all/construct/WBCnstr00020816#01--10<br/>a reference about a construct for transgene [oazp::oaz(177)::gfp] but there is no indication wre to find a corresponding transgenic strain or a plasmid source as well?<br/>Do you know perhaps where it is possible to retrieve such tools?<br/>Thank's a lot for help.<br/>Best.<br/>simon</p><p>What were you doing? <br />&nbsp;&nbsp;University Professor working with C. elegans.
</p>

**Reported by:** simo******* (simo***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by Paul-Davis** [comment]
Dear Simon,

Thank you for your email.

If you open the Transgene widget you can access the data on the 
Transgene objects that contain this construct.

https://www.wormbase.org/species/all/construct/WBCnstr00020816#4013--10

On the corresponding transgene summary pages the attached reference 
should give you the details of the source of the reagents.

https://www.wormbase.org/species/all/transgene/WBTransgene00021196#014--10

Paul





On 08/01/2019 15:24, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> I've found on this web page
> https://www.wormbase.org/species/all/construct/WBCnstr00020816#01--10
> a reference about a construct for transgene [oazp::oaz(177)::gfp] but 
> there is no indication wre to find a corresponding transgenic strain 
> or a plasmid source as well?
> Do you know perhaps where it is possible to retrieve such tools?
> Thank's a lot for help.
> Best.
> simon
>
> What were you doing?
>   University Professor working with C. elegans.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6825. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6825>.
>
> Reported by: simon Galas (simon.galas@umontpellier.fr)
> 08 Jan 19 15:24
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:48.0) Gecko/20100101 
> Firefox/48.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
