### ISSUE TITLE
Change Overview widget content

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#6829]
@sibyl229: At this point, our manually written gene descriptions are really old.  From WS268 we debuted our new automatic gene description pipeline which is a great improvement over the old pipeline.  Please change the website code to always show the automatically written 'Automated_description' as the description displayed in the Overview and put the manually written description (acedb tag--Concise_description) under a collapsible arrow titled 'Legacy manual gene description' similar to the current 'Details' and 'From C. elegans I and II'.  So it's there if anyone still wants to look at it.

**Comment by rankishore** [comment]
@sibyl229 These could be the rules for the Overview widget
1. If a gene has both Automated_description and Concise_description, show the Automated_description and hide/collapse the Concise_description under the title 'Legacy manual annotation'
2.  If a gene has only Concise_description (and no Automated_description) do the same as above to hide/collapse it, and if Users want they can click to open but at least they know it's old and has not been updated and will not be manually updated!
3.  If a gene has only Automated_description, of course, just show this in the Overview widget

**Comment by rankishore** [comment]
Note that we from Caltech, no longer upload any other 'Structured_description' other than 'Automated_description' and 'Concise_description'.  So gone are all the legacy, really old, 'Provisional_description', 'Other_description' etc.  So this is a good opportunity to clean up the 'Overview' widget for WS268.

**Comment by rankishore** [comment]
After talking with @sibyl229, when a gene has no 'Automated_description' decided to leave the 'Legacy manual gene description' open (and not collapsed).

**Comment by sibyl229** [comment]
Changes have been live on production. Closing
