### ISSUE TITLE
Gene Page for mrpl-44 has wrong descriptions.

### ISSUE THREAD

**Issue by WBjae** [WormBase/website#6830]
https://wormbase.org/species/c_elegans/gene/WBGene00008514#03-9g816-10

I found that mrpl-44 gene (F02A9.4) page has incorrect information at gene description, GO and homology widgets.  Some descriptions in the page are actually for the different sequence (F02A9.10). We need to correct this by reassigning information to the right gene.

In my guess, this may be caused by the gene structure itself, since both gene products (F02A9.4 and F02A9.10) may be coming from alternative splicing and polyadenylation.

I don't know if this issue is only for this gene or other genes with similar structure.
Please let me know the best way how to investigate it systematically.

Thanks,
Jae

**Comment by WBjae** [comment]
With Raymond's help, I found this issue may be caused by "Splitting a gene into two".
I noticed the 'split_into' event from history of annotation (acedb) but no proper updates for the descriptions.

**Comment by gw3** [comment]
@WBjae this raises an interesting issue.
When we change a gene structure to split it into two genes, the structure curators are careful to assign tags that we are responsible for (like CGC_name) to the correct new genes, however there isn't a formal mechanism in place to alert other curators about the split. This results in situations like this where gene descriptions, GO and other data are attached to the wrong gene.

The F02A9.4, F02A9.10 split was part of a number of genes that were split in March 2018 because they have a structure where there are two or more alternate translations of a single transcript where there are substantial differences in the gene product. These have been grouped into operons with the Method = 'dicistronic_mRNA'.

There are 44 such operons in elegans and 1 in brugia.

We should probably establish a protocol of informing relevant curators when splits and merges of genes are made.

**Comment by vanaukenk** [comment]
I've checked the GO annotations for WS269 (and WS270) and the annotations that are sourced from UniProt (e.g. the KW mappings and UniPathway pipelines) are now correct for each gene.

I still need to double-check the one manual annotation and confirm some changes in the PAINT-derived annotations, but overall, the GO annotations for each gene should be okay starting with WS269.

+1 for establishing a more formal protocol for alerting curators to data types that may need to be examined as a result of gene splits.  I think that most of us have checks in place to catch data associated with dead genes, but I'm not sure about splits.

**Comment by WBjae** [comment]
@vanaukenk Thanks, that's perfect!
@gw3 Yes, I completely agree to the point we need to have a formal way for a notice to curators about such events, which potentially cause a wrong data assignment. In my thought, this issue also can be caused by renaming of genes. 

I'm now checking all the 44 cases you informed me. I found another case from them, I didn't finish all of them yet, though. I report the detail of another case below.

WBGene00016062 (cox-16) was splitted to WBGene00016062 and  WBGene00302991.

https://wormbase.org/species/c_elegans/gene/WBGene00016062#03-9g816-10
https://wormbase.org/species/c_elegans/gene/WBGene00302991#03-9g816-10

Based on AA sequence similarity, WBGene00302991 should have a gene name, cox-16.
However, now cox-16 gene name is assigned to WBGene00016062, but this gene is not homologous to cox-16.

**Comment by gw3** [comment]
@vanaukenk good spot on cox-16
This name was assigned a few days before I made the gene-split so it hadn't got into my curation database for me to be aware that the CGC_name needed to be moved.
It will be corrected for WS170.

**Comment by WBjae** [comment]
@gw3 Another situation I found regarding renaming of gene, is the case of syx-16 and cutl-19.
cutl-19 has been named as syx-16 before and now, the cutl-19 gene page has some data for syx-16.

**Comment by WBjae** [comment]
@gw3 
@vanaukenk 

 I checked the cutl-19 gene page from the 'staging' site.
Two widgets in the page probably need to be checked again.

1. Homology widget: 
    In the nematode orthologs table, Cbr-syx-16 and Cre-syx-16 are listed as orthologs.

2. Gene ontology widget:
   The information in the table seems to be for syx-16.

**Comment by vanaukenk** [comment]
@WBjae - I will relay this information to the UniProtKB GO curators (the original source of the GO annotations) so they can update the annotations to the correct UniProtKB accession.

Once they do that, the annotations imported into WB will go to the correct gene.

**Comment by WBjae** [comment]
@vanaukenk 
Thanks a lot!

**Comment by WBjae** [comment]
@gw3 
The gene description and homology infomation about mrpl-44 is not yet corrected.
MRPL-44 doesn't share homology with MCCC2.
The current gene description and part of homology data should be for F02A9.10.

**Comment by gw3** [comment]
@WBjae I don't curate the gene descriptions.
Is this something @rankishore could help with?

**Comment by WBjae** [comment]
@gw3 
Seems to me, this is not gene description issue.
mrpl-44 and F02A9.10 was split from one gene. And then some information between them were mixed.

**Comment by epaule** [comment]
hi Jae,

do you have an example of the mistake in the homology widget? Because it
should be all automated calculations based on the respective protein
sequences.

Michael

**Comment by WBjae** [comment]
@epaule 
Please see the attached image. All checked part is actually for F02A9.10.
I think this is caused by their gene structure sharing the first two exons.
If I want to find similar gene structures, how can I do that?


![InkedScreenshot_2019-11-12 mrpl-44 (gene) - WormBase Nematode Information Resource_LI](https://user-images.githubusercontent.com/32857185/68700649-1b26ef80-053a-11ea-9220-16ab9c7bb048.jpg)
![InkedScreenshot_2019-11-12 mrpl-44 (gene) - WormBase Nematode Information Resource(1)_LI](https://user-images.githubusercontent.com/32857185/68700656-1e21e000-053a-11ea-96fb-94ee4f51612a.jpg)

**Comment by gw3** [comment]
@WBjae good question. 
I made a one-liner to find shared identical exons between different genes.

zcat ~wormpub/DATABASES/current_DB/SEQUENCES/elegans.processed.gff2.gz | perl -ne '{@f=split /\t/, $_; if ($f[1] eq "curated" && $f[2] eq "exon") {$exon="$f[0]:$f[3]:$f[4]";($id)=($f[8] =~ /CDS\s\"(\w+\.\d+).*?\"/);if (exists $e{$exon} && $e{$exon} ne $id) {print "$e{$exon}\t$id\t$exon\n"}; $e{$exon} = $id}}'

This gives:

C53D5.2	C53D5.3	CHROMOSOME_I:280120:280206 (This is an error - these two genes should be merged)

F02A9.10	F02A9.4	CHROMOSOME_III:9089162:9089270 (This is the mrpl-44 and F02A9.10 pair)
F02A9.10	F02A9.4	CHROMOSOME_III:9089319:9089373

C38C3.5	F53E2.2	CHROMOSOME_V:1475139:1475141 (These share a small 5' exon)

**Comment by WBjae** [comment]
@gw3 
Thanks a lot! Interestingly, just a few cases there. 
For C38C3.5 F53E2.2 CHROMOSOME_V:1475139:1475141 (These share a small 5' exon),
this have been called unc-60A and unc-60B. Will F53E2.2 be renamed soon?

**Comment by gw3** [comment]
@WBjae These two genes have similar, but not identical protein products:
>F53E2.2 Actin-depolymerizing factor 1, isoforms a/b
>C38C3.5 Actin-depolymerizing factor 2, isoform c (unc-60)

I am not responsible for gene nomenclature, but feel free to suggest your names to Tim Schedl.

**Comment by WBjae** [comment]
@gw3 
Will the issue about mrpl-44 and F02A9.10 be fixed soon, at WS274 or WS275?

**Comment by WBjae** [comment]
@gw3 
Any plan for this issue?

**Comment by gw3** [comment]
@WBjae The gene structures conform to our standards: where there are two transcripts which only share a small fraction of their structure, then they are split into separate genes so that each gene product can be annotated independently.

@vanaukenk has contacted UniProtKB GO curators (the original source of the GO annotations) so they can update the annotations to the correct UniProtKB accession.

Once they do that, the annotations imported into WB will go to the correct gene.
