### ISSUE TITLE
  Dear Ladies and Gentlemen, the WormBa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6831]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Ladies and Gentlemen,<br/>the WormBase is a fanatastic homepage with a lot of helpful information!<br/>I have a question: Do you also sell isolates/genomic DNA of parasites, specifically of Syphacis muris and Aspiculuris tetraptera or dou you have any idea where this might be bought?<br/>Thank you in advance!<br/>Best regards,<br/>Felix</p>

**Reported by:** Feli******** (ff@g*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by chris-grove** [comment]
My email to user:
"""
Thanks for your kind words. WormBase is strictly a bioinformatics resource and does not sell clones or any other products. You may want to reach out to authors of publications that reported the genome sequences for these species, as they are likely the best resource for clone availability information.
"""
