### ISSUE TITLE
  I'm curious to know if there's a way ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6832]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm curious to know if there's a way to draw interaction networks between a list of genes using the same data that are used to produce the interaction diagrams for an individual gene on wormbase. I've noticed that there's not a perfect correlation between the interaction diagram on wormbase and the output from Genemania. It seems that part of the reason for that is that Genemania is not using the same source data as is used to construct the network in wormbase. For example, wormbase will use data from an immunoprecipitation experiment from a single publication as the basis for a physical interaction between proteins, but Genemania seems to rely mostly (or maybe even exclusively?) on data from high throughput studies.Therefore, physical interactions that come up on wormbase's interaction network are missing when I try to reproduce that diagram on Genemania's website. <br/>I'd like to be able enter a list of genes (as you would do on Genmania's website) and then use the same data that wormbase does to draw an interaction network between those genes. Is there any way to do that? I've reached out to the folks at Genemania, but so far there's been no response. Many thanks for your help!</p>

**Reported by:** Matt********* (matt**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

**Comment by chris-grove** [comment]
Email to user:
"""
We don't have a web-based tool to do what you're trying to do, but I've written a relatively simple Python script that can take the interactions file from our FTP site:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS267.interactions.txt.gz

and a list of genes (as WBGene IDs), and output a list of the interactions between genes in the list. Here's the compressed directory containing the current interactions file, the script, a sample input list of genes, and a sample output:

https://www.dropbox.com/s/ih5tp1gi54n5ks5/Interactions_between_genes_in_a_list_script.zip?dl=0

With the output you could then generate your own custom Cytoscape file and visualize the network directly from within Cytoscape. To only view certain interaction types, I would need to modify the output of the script to include interaction types for each interaction. If your gene list is short, you can check the details of each interaction on the WormBase website, like on this interaction page:

https://www.wormbase.org/species/all/interaction/WBInteraction000546208#0132--10

Just search using the interaction IDs in the script output. If your list is quite long, then I can modify the script to output interaction types and you can filter the output in Excel or something similar.

I hope that helps. Let me know if you have any questions.
"""
