### ISSUE TITLE
  How do I go about ordering of strains...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6838]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I go about ordering of strains?</p>

**Reported by:** Anas** (kayz*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by Paul-Davis** [comment]
Hi,

Strains can be ordered through the Caenorhabditis Genetics Center (CGC)

https://cgc.umn.edu/strain/search

If they do not have the Strain you are interested in then it might be 
available from the lab that generated it.

Thanks

Paul




On 11/01/2019 07:54, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   How do I go about ordering of strains?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6838. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6838>.
>
> Reported by: Anasha (kayzika@gmail.com)
> 11 Jan 19 07:54
>
> Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; 
> rv:11.0) like Gecko
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
