### ISSUE TITLE
  Hi everyone, I'm writing an introduct...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6839]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi everyone,<br/>I'm writing an introduction to transgenesis in C. elegans, and would like to know about the total # of unique Ex, Is, Ti and Si alleles WormBase currently has documented. If I could also find out how that number has evolved throughout WormBase's history, that would be superb.<br/>Paul sent me to the query tool:<br/>https://wormbase.org/tools/queries<br/>But I have little experience with WQL/AQL and the documentation and examples page leads to a 'Server not available' error page.<br/>Can anyone help?</p>

**Reported by:** Jona******** (jona*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by kyook** [comment]
Hi Jonathan,

Despite a working or nonworking query tool,  I'm not sure you would be
able to get the stats you need from WormBase.
Historically, Ex transgenes were not curated when transgene curation
started.  There was a brief period when they were more systematically
curated but that didn't last.  In addition, systematic curation of any
transgene including integrated ones has been on hold for the last
couple of years.

In good news, while curation of the transgenes has been on hold, we
have still been scanning the literature and capturing integrated
transgenes based on the Is and Si name.  Although the majority of
these have not been fully validated, and so have never made it to WB
proper, they should be useful to you.  In addition, we do have scripts
that identify Ex transgenes.  I will look up the files and scripts and
get back to you and we can take it from there.

Karen


~~~~
Karen Yook

Curator / Editor
WormBase Caltech / microPublication
email: kyook@caltech.edu
email: karen@wormbase.org
email: karen.yook@micropublication.org
skype name: wbkaren
tel: +1(415)306-4150

On Fri, Jan 11, 2019 at 9:14 AM <no-reply@wormbase.org> wrote:
>
> How Do I ...?
>
>   Hi everyone,
> I'm writing an introduction to transgenesis in C. elegans, and would like to know about the total # of unique Ex, Is, Ti and Si alleles WormBase currently has documented. If I could also find out how that number has evolved throughout WormBase's history, that would be superb.
> Paul sent me to the query tool:
> https://wormbase.org/tools/queries
> But I have little experience with WQL/AQL and the documentation and examples page leads to a 'Server not available' error page.
> Can anyone help?
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #6839. Follow progress on our issue tracker.
>
> Reported by: Jonathan Liu (jonathanliu@caltech.edu)
> 11 Jan 19 17:14
>
> Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

**Comment by kyook** [comment]
Jonathan Liu jonathanliu@caltech.edu via gmail.com
to me, Hans-Michael, Jonathan, Juancarlos, Valerio | to me, Hans-Michael, Jonathan, Juancarlos, Valerio
to me, Hans-Michael, Jonathan, Juancarlos, Valerio

Hi all,

Thanks so very much! I can work with transgenes_summary_nf.out in python to parse out just dates and transgene alleles. I think this is exactly what I need for the introduction.

Many thanks to everyone for all their hard work! When it's done I will be sure to credit all of you for helping me with this.

Happy Friday,
Jonathan
