### ISSUE TITLE
  I would like to suggest a content upd...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6842]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to suggest a content update for<br/>Otpl1 (and all Otpl genes) - related to vertebrate Otopetrin1. We recently showed in a paper published in Science that the gene family encodes proton-selection ion channels (Tu et al, 2018) http://science.sciencemag.org/content/359/6379/1047</p>

**Reported by:** emil******* (lima*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Emily,

Official C. elegans gene names can be requested from the 
genenames@wormbase.org email list CC'd.

Thank you for sending us your manuscript and hopefully a suitable gene 
name/set of gene names can be assigned to this gene class.

Paul
[HelpDesk]


On 12/01/2019 06:01, no-reply@wormbase.org wrote:
> Content Correction
>
>   I would like to suggest a content update for
> Otpl1 (and all Otpl genes) - related to vertebrate Otopetrin1. We 
> recently showed in a paper published in Science that the gene family 
> encodes proton-selection ion channels (Tu et al, 2018) 
> http://science.sciencemag.org/content/359/6379/1047
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6842. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6842>.
>
> Reported by: emily liman (liman@usc.edu)
> 12 Jan 19 06:01
>
> Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/71.0.3578.98 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
@Paul-Davis 
I think the gene names have already been sorted out:

https://www.wormbase.org/resources/gene_class/otpl#01--10

I think the user is looking for them to be annotated as proton channels (via a GO annotation I suppose). Will assign to @vanaukenk

**Comment by Paul-Davis** [comment]
Thanks @chris-grove I did actually realise this as I was looking at the paper.....I emailed them again the other day but haven't had any response :(

**Comment by vanaukenk** [comment]
I'll take a look at the publication and add any functional GO annotations I can.

**Comment by vanaukenk** [comment]
I've added this paper to the WB bibliography and added functional GO annotations, based on sequence similarity to a mouse protein, for C. elegans otpl-1 - otpl-8.
All C. elegans genes are also associated with this Science paper as well as two additional references that report on sequence analysis of this family of proteins.
All new annotation will be included in WormBase release WS271.
