### ISSUE TITLE
  Hi, I'm currently in Andy Golden's la...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6849]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm currently in Andy Golden's lab and we are trying to make a database of human rare disease genes along with their known worm orthologs. I was wondering: when I am looking at a worm gene, under the homology tab I find a table of the best BLASTP matches. The last column shows "% length". I was wondering how this is calculated or what program is used to obtain these values? Thanks!</p>

**Reported by:** Isab********** (isab**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by epaule** [comment]
that is the percent of the query protein covered by the alignment.
But I would highly recommend actual orthology predictions over raw sequence alignment results, as conserved elements like functional domains or repetitive elements easily throw off tools like BLAST.

We are currently in the process to integrate orthologs from the Alliance of Genome Resources (https://www.alliancegenome.org/) for C.elegans.
So unless you want to work with our non C.elegans nematodes, I would recommend their orthology tool (DIOPT) for queries. Plus we are member of the Alliance, and it specifically targets scientists researching model organism orthologs of human genes.
The main DIOPT query tool can be found here: https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl

We do also have our own Compara Orthology pipeline's result at parasite.wormbase.org (which shows up in the WormBase orthology section as ParaSite-Compara). And they are also in the respective BioMart query tool.

there are also a lot more alternatives:
EnsEMBL Compara https://ensembl.org
InParanoid http://inparanoid.sbc.su.se/cgi-bin/index.cgi
PantherDB http://www.pantherdb.org/
OMA https://omabrowser.or
OrthoList2 http://ortholist.shaye-lab.org/
