### ISSUE TITLE
Wormbase isn't loading...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6855]
*Help Desk query collected when no chat operators were online. Follow up required.*

Wormbase isn't loading

**Reported by:** Tari** (tari****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00000301#--3">https://wormbase.org/species/c_elegans/gene/WBGene00000301#--3</a>
**Browser:** Safari 11.0.3

**Comment by nuin** [comment]
Seems fine for me (30 minutes after report).

**Comment by tharris** [comment]
I’ve been looking at it shortly after report. Currently in communication with user; having general page loading problem after co ducting a search. Seems to be specific to their environment.

**Comment by tharris** [comment]
(Resolved: caching problem on client side)
