### ISSUE TITLE
Hello, I could not see the whole view of wormbase ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6858]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I could not see the whole view of wormbase as it always only squeeze to the left side of my PC. Is it because of my PC or wormbase setting? Thank you

**Reported by:** Song*** (song**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00022516#01--3">https://wormbase.org/species/c_elegans/gene/WBGene00022516#01--3</a>
**Browser:** Chrome 71.0.3578.98

**Comment by chris-grove** [comment]
My email to user:
"""
There is a WormBase setting that can adjust this. On a gene page, at the left hand side of the screen above "Page Content" is a settings button. Clicking that will show a menu of page layout options. You will need to select the full screen icon to fill the page horizontally. Here's a screen recording to show how to do it:

https://www.dropbox.com/s/r3ehotlpuy30x6n/Changing_WormBase_page_layout_Jan_23_2019.mov?dl=0

Let us know if you have any other questions.
"""
