### ISSUE TITLE
BLAST/BLAT defaulting to VC2010 bioproject instead of N2 bioproject

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6861]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>we noticed after blast that gene are named "chr III-pilon.g1234" (for example) on GBrowse.<br/>Thus, the name of the gene disappears... and disable the access to the Worm Base page dedicated to the gene.</p>

**Reported by:** Cami***** (cami************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

**Comment by epaule** [comment]
that might be related to the search not resolving the public name of the VC2010 genes: as example chrI_pilon.g1234 (Public_name ) / PRJEB28388_chrI_pilon.g1234 (GeneID)

**Comment by chris-grove** [comment]
My email to user:
"""
WormBase recently incorporated a new C. elegans genome assembly for the strain WC2010, in which all of the chromosomes and gene names have this peculiar naming scheme. The intention is to have BLAST/BLAT for nucleotide sequences default to the N2 assembly (bioproject PRJNA13758), but currently it is defaulting to this new VC2010 assembly (bioproject PRJEB28388). Make sure that when you run the BLAST/BLAT you have selected the N2 assembly (bioproject PRJNA13758) in the "Bioproject" field of the BLAST/BLAT form before performing you search.

Then you should get the expected gene names and chromosome names.

I hope that helps.
"""

**Comment by tharris** [comment]
I don’t think that is the problem per se. I believe that the VC2010 assembly is now set as the default, whereas most people are blasting against N2.

**Comment by chris-grove** [comment]
Fixed. Closing.
