### ISSUE TITLE
I am looking for journal articles dealing with und...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6862]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking for journal articles dealing with understanding the acs-2 gene in C. elegans.

**Reported by:** Jenn* (jenn**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00009221#01-9g5e-3">https://wormbase.org/species/c_elegans/gene/WBGene00009221#01-9g5e-3</a>
**Browser:** Chrome 71.0.3578.98

**Comment by chris-grove** [comment]
Email to user:
"""
You can find a list of associated references/papers for this paper on the acs-2 gene page in the "References" widget. We have 28 associated articles, 20 of which are journal articles:

https://wormbase.org/species/c_elegans/gene/WBGene00009221#0e--10
"""
