### ISSUE TITLE
Handling display of tandem-duplication with variation molecular-details widget.

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/website#6863]
I noticed that the tandem duplication was not showing up correctly in the variation molecular details widget. I have since corrected it on staging: https://staging.wormbase.org/species/c_elegans/variation/WBVar02120713#-53-10

One thing I noticed and fixed is the positions of the pseudogenes in the table at the bottom of the widget. I was not accounting for pseudogenes that are on the reverse strand. This now matches with what the legacy Acedb code produces. 

One thing to note is that the Ace code didn't hight the full tandem repeat sequence. I am currently highlighting it (red). Let me know if this is correct

Please let me know if there is anything I am missing

**Comment by tharris** [comment]
Looks good for this particular instance. @Paul-Davis please close if you concur.
