### ISSUE TITLE
References for efl-2 is not opening...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6865]
*Help Desk query collected when no chat operators were online. Follow up required.*

References for efl-2 is not opening

**Reported by:** Card******** (card*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001162/widget/references">https://wormbase.org/species/c_elegans/gene/WBGene00001162/widget/references</a>
**Browser:** Chrome 71.0.3578.98

**Comment by chris-grove** [comment]
Email to user:
"""
I'm not having trouble opening the References widget for the efl-2 gene page:

https://wormbase.org/species/c_elegans/gene/WBGene00001162#0e--10

Are you still having issues? If so, can you tell us which operating system and web browser (and versions of each) that you are using?
"""

**Comment by chris-grove** [comment]
Will reopen if necessary
