### ISSUE TITLE
C. elegans CRISPR biosafety level question

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6866]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
My name is visitor_name. I was a postdoc at Dr. Kevin O'Connell's lab at the NIH. I am currently an Assistant Professor at the University of Tulsa. The Biosafety Committee here is giving me a very hard time with performing CRISPR in C. elegans. I have been here for 6 months and I have been unable to start any CRISPR experiments in my lab. I was wondering if someone here could help clarify under what biosafety level does research involving CRISPR in C. elegans fall under? Kindly let me know. Thank you very much for your help!
Best Regards,
Jyoti

**Reported by:** Jyot****** (iyer****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 71.0.3578.98

**Comment by Paul-Davis** [comment]
Closing as it doesn't look like any staff are going to chip in anything and hopefully the user has luck with the forum.
