### ISSUE TITLE
  Are CRISPR modified alleles for examp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6868]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Are CRISPR modified alleles for example GFP-tagged via CRISPR indicated somehow? Is there a short hand designation for a CRISPR edited allele? Is there an effort afoot to tag all genes with GFP and Auxin Inducible Degrons?</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to gather data on the accessibility of different sequences to sg and find genes that have been tagged via CRISPR so I am not reinventing the wheel when I make my own edits.</p>

**Reported by:** Noel** (noel*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

**Comment by Paul-Davis** [comment]
Dear Noelle,

Thank you for contacting WormBase. We do have a mechanism for flagging 
CRISPR generated alleles within our resource.
Alleles generated by this method are annotated as Engineered_alleles 
with a Production method of CRISPR_Cas9.

I have entered a ticket to get this attribute displayed in the Overview 
widget on the Allele summary pages. Unfortunately we only have 343 
CRISPR variations in the database and of those only 116 are mapped to 
the genome with a further 60 attached to the gene that they are reported 
to interrupt.

There are various labs producing CRISPR knockouts for numbers of genes, 
but it might be worth asking on the Worm Community Forum about specific 
large scale projects etc.

http://forums.wormbase.org/

If you require additional information please feel free to email me.

Paul




On 25/01/2019 02:12, no-reply@wormbase.org wrote:
> Question:
>
>   Are CRISPR modified alleles for example GFP-tagged via CRISPR 
> indicated somehow? Is there a short hand designation for a CRISPR 
> edited allele? Is there an effort afoot to tag all genes with GFP and 
> Auxin Inducible Degrons?
>
> What were you doing?
>   Trying to gather data on the accessibility of different sequences to 
> sg and find genes that have been tagged via CRISPR so I am not 
> reinventing the wheel when I make my own edits.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6868. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6868>.
>
> Reported by: Noelle (noelle.letoile@ucsf.edu)
> 25 Jan 19 02:12
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 
> (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Noelle,


Just to add to Paul's points, I'm attaching lists of


1) All (82) alleles affiliated with an expression pattern (these are generally knock-in alleles)

2) All (23) CRISPR alleles affiliated with an expression pattern (subset of #1)

3) All (105) Expression_pattern objects in the database of the type "Genome_editing"


Note that you may want to open all widgets, including the "Tree Display" widget, to see all the info curated for a given allele or expression pattern object, for example:


https://wormbase.org/species/c_elegans/variation/WBVar02148941#012345678--10


or


https://wormbase.org/species/all/expr_pattern/Expr13712#0123--10


On variation pages for CRISPR alleles, you should be able to see the "Production_method" tag with the "CRISPR_Cas9" entry, for example:


https://wormbase.org/species/c_elegans/variation/WBVar02148633#012345678--10


I hope that helps.


Best,

Chris Grove

WormBase

________________________________
