### ISSUE TITLE
Interaction external link outs to BioGRID not working on interaction pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6869]
I just noticed that links out to BioGRID from interaction page "External Links" widgets are leading to a blank page with "about:blank" in the URL address bar. For example:

https://wormbase.org/species/all/interaction/WBInteraction000523777#01--10
https://wormbase.org/species/all/interaction/WBInteraction000554741#01--10

The "BioGRID" link in each case (in the "Name" column) should link to the BioGRID homepage:

https://thebiogrid.org/

and the annotation link in the "Entry" column should link to the BioGRID annotation page like:

https://thebiogrid.org/interaction/876627

and

https://thebiogrid.org/interaction/869100

respectively.

**Comment by sibyl229** [comment]
Hi @chris-grove the BIoGRID link should be fixed now: https://staging.wormbase.org/species/all/interaction/WBInteraction000523777#014--10 Could you take a look? Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks good thanks!
