### ISSUE TITLE
  Hi,  I am a new assistant professor a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6870]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I am a new assistant professor at Department of Molecular Biosciences at University of Texas at Austin. I was wondering if you could add our lab to the lab directories ? <br/>Here is more information: <br/>visitor_name, PhD<br/>Assistant Professor<br/>Molecular Biosciences, University of Texas at Austin<br/>Lab page: www.sarinayceniklab.org<br/>Address:<br/>University of Texas at Austin<br/>Patterson Bldg, Rm 241<br/>2415 Speedway,  Austin TX 78712<br/>Phone: <br/>+1-617-3197910</p>

**Reported by:** Elif************** (esar***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
@ceciliaWBPerson1  email response to user:
"""
Congratulations on your new lab.

The guidelines on how to register a new laboratory and receive strain
and allele designations can be found in the Overview section our
Nomenclature guidelines:
http://www.wormbase.org/about/userguide/nomenclature

I am updating your WBPerson contact data.
Updates will be available in release WS271 of WormBase.
We are currently in version WS268.
"""
