### ISSUE TITLE
Migrating sequence display on molecular details widget for feature page

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#6871]
For @sibyl229 
- [ ] Is strand relevant here?
- [ ] Ensure correct default strand is shown by default (if applicable)
- [ ] Watch out for different data structure returned by API depending of if sequence is available, and decide on which structure to go forward with.

Examples:
- of a feature on the negative strand: https://www.wormbase.org/species/c_elegans/feature/WBsf670036#5--10

**Comment by a8wright** [comment]
@Paul-Davis @sibyl229 and I are wondering about features (e.g. https://wormbase.org/species/c_elegans/feature/WBsf080918#0512--10) where we have up and downstream flanking sequences and single related flanking sequence (https://wormbase.org/species/c_elegans/sequence/W06E11#04--10) but we do not know the sequence itself. Not for the related flanking sequence link, it is in the sequence database. 

Few questions:
Is there a reason we can't find the location of the feature on the reference sequence?
Is there a way to figure out the strand of the flanking sequences for features that are not in the sequence database?
@sibyl229 is also wondering if there is value to providing both positive an negative strand for the sequences when the sequence is known for the features? (like the new variation molecular_details widgets)

**Comment by sibyl229** [comment]
Actionable items from a meeting with @Paul-Davis and @a8wright :

**Un-mapped sequence**:

- [ ] We reached consensus that we will not display sequence or flanking seqeunce for un-mapped sequence feature. Instead will display a message to indicate that it's un-mapped. 

Context: 
- un-mapped sequence feature are either historical/retired or otherwise has some problem. 
- The effort required to handling this scenario in the web code outweighs the benefit.

**Preferred strand:**

- [ ] We will use the flanking sequence to inferred the preferred strand to display the sequence. This should also match the strand inferred from `start` and `stop` in the sequence database.

- [ ] The display will also make it clear which strand is shown, and allow user to switch to the other strand.

Context:
- User would probably prefer to read the sequence on the same strand as it's associated gene, CDS, etc
- Curation generally puts the flanking sequence on the strand that users prefer to read.

**Comment by sibyl229** [comment]
Closing. The work for molecular details widget of sequence feature page has been done, and it has been tested by @Paul-Davis
