### ISSUE TITLE
Help finding polymorphism data

### ISSUE THREAD

**Issue by Gschindelman** [WormBase/website#6872]
The following was sent to Wormbase help 4 days ago

I am trying to obtain a bed, vcf or gff of polymorphism data for C. 
elegans from Wormbase. I have tried with the JBrowser and have been able 
to download the Polymorphism track for PRJNA13758, but the files only 
contain the positions and not the nucleotide change for each variant. I 
am presuming this data must be in your ftp site somewhere, but I have 
been unable to find. Could you point me in the right direction?

cheers

Ash

-- 
Ashley D Sawle
Senior Bioinformatics Analyst
Bioinformatics Core
Cancer Research UK Cambridge Institute

**Comment by Paul-Davis** [comment]
Dear Ash,

Thank you for contacting us, apologies for the slow reply.

You can access the Polymorphism data by parsing the elegans gff3 files 
we deposit on our ftp site.

ftp://ftp.wormbase.org/pub/wormbase/releases/WS269/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS269.annotations.gff3.gz

Here is an example snp
I       Variation_project_Polymorphism SNP     79846   79846   .       
+       . 
variation=WBVar00146885;public_name=WBVar00146885;other_name=snp_Y48G1C[2],haw135,cewivar00160223;strain=CB4856;polymorphism=1;substitution=T/A;consequence=Intron

Paul


On 22/01/2019 17:18, Ashley Sawle wrote:
> Hi
>
> I am trying to obtain a bed, vcf or gff of polymorphism data for C.
> elegans from Wormbase. I have tried with the JBrowser and have been able
> to download the Polymorphism track for PRJNA13758, but the files only
> contain the positions and not the nucleotide change for each variant. I
> am presuming this data must be in your ftp site somewhere, but I have
> been unable to find. Could you point me in the right direction?
>
> cheers
>
> Ash
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Ash,

Paul's answer is perfectly good--that's what I would do too if I wanted to
get the WormBase polymorphism data.  But I wanted to ask about your
experience with JBrowse: when I select "Save track data" from the menu by
the label I get the option to save as GFF, and when I do that I see lines
that look like this:

I    Variation_project_Polymorphism    SNP    7110119    7110119    .    +
   .
 _Variation=WBVar01432033;_Polymorphism=1;Name=WBVar01432033;_Substitution=A/T;_Strain=function
values() { [native code] };_Public_name=WBVar01432033

(now that I'm reading that sentence I realize I may have blown past what
you did, that's sometimes a hazard of tech help, tell me to back up if you
don't know what I mean :-)

While this is perhaps not ideal GFF (I love the very useful "native code"
in there; hopefully you don't need strain), it does at least indicate what
the substitution is.  Does this align with your experience?

Thanks,
Scott


On Mon, Jan 28, 2019 at 5:21 AM Paul Davis <paul.davis@wormbase.org> wrote:
>
>
> Dear Ash,
>
> Thank you for contacting us, apologies for the slow reply.
>
> You can access the Polymorphism data by parsing the elegans gff3 files
> we deposit on our ftp site.
>
>
ftp://ftp.wormbase.org/pub/wormbase/releases/WS269/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS269.annotations.gff3.gz
>
> Here is an example snp
> I       Variation_project_Polymorphism SNP     79846   79846   .
> +       .
>
variation=WBVar00146885;public_name=WBVar00146885;other_name=snp_Y48G1C[2],haw135,cewivar00160223;strain=CB4856;polymorphism=1;substitution=T/A;consequence=Intron
>
> Paul
>
>
> On 22/01/2019 17:18, Ashley Sawle wrote:
> > Hi
> >
> > I am trying to obtain a bed, vcf or gff of polymorphism data for C.
> > elegans from Wormbase. I have tried with the JBrowser and have been able
> > to download the Polymorphism track for PRJNA13758, but the files only
> > contain the positions and not the nucleotide change for each variant. I
> > am presuming this data must be in your ftp site somewhere, but I have
> > been unable to find. Could you point me in the right direction?
> >
> > cheers
> >
> > Ash
> >
>
> --
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google Groups
"WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send an
email to help+unsubscribe@wormbase.org.
>


--
------------------------------------------------------------------------
Scott Cain, Ph. D.                                   scott at scottcain dot
net
GMOD Coordinator (http://gmod.org/)                     216-392-3087
Ontario Institute for Cancer Research

**Comment by Paul-Davis** [comment]
Hi Scott and Paul

Thanks for the help. I only tried the bed file, I don't know why I didn't think to try the gff instead. Knowing the strain would have been helpful, but this should suit our purposes.

Thanks again.

Ash

On 28/01/2019 18:38, Scott Cain wrote:
Hi Ash,

Paul's answer is perfectly good--that's what I would do too if I wanted to get the WormBase polymorphism data.  But I wanted to ask about your experience with JBrowse: when I select "Save track data" from the menu by the label I get the option to save as GFF, and when I do that I see lines that look like this:

I    Variation_project_Polymorphism    SNP    7110119    7110119    .    +    .    _Variation=WBVar01432033;_Polymorphism=1;Name=WBVar01432033;_Substitution=A/T;_Strain=function values() { [native code] };_Public_name=WBVar01432033

(now that I'm reading that sentence I realize I may have blown past what you did, that's sometimes a hazard of tech help, tell me to back up if you don't know what I mean :-)

While this is perhaps not ideal GFF (I love the very useful "native code" in there; hopefully you don't need strain), it does at least indicate what the substitution is.  Does this align with your experience?

Thanks,
Scott


On Mon, Jan 28, 2019 at 5:21 AM Paul Davis <paul.davis@wormbase.org<mailto:paul.davis@wormbase.org>> wrote:
>
>
> Dear Ash,
>
> Thank you for contacting us, apologies for the slow reply.
>
> You can access the Polymorphism data by parsing the elegans gff3 files
> we deposit on our ftp site.
>
> ftp://ftp.wormbase.org/pub/wormbase/releases/WS269/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS269.annotations.gff3.gz
>
> Here is an example snp
> I       Variation_project_Polymorphism SNP     79846   79846   .
> +       .
> variation=WBVar00146885;public_name=WBVar00146885;other_name=snp_Y48G1C[2],haw135,cewivar00160223;strain=CB4856;polymorphism=1;substitution=T/A;consequence=Intron
>
> Paul
>
>
> On 22/01/2019 17:18, Ashley Sawle wrote:
> > Hi
> >
> > I am trying to obtain a bed, vcf or gff of polymorphism data for C.
> > elegans from Wormbase. I have tried with the JBrowser and have been able
> > to download the Polymorphism track for PRJNA13758, but the files only
> > contain the positions and not the nucleotide change for each variant. I
> > am presuming this data must be in your ftp site somewhere, but I have
> > been unable to find. Could you point me in the right direction?
> >
> > cheers
> >
> > Ash
> >
>
> --
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org<mailto:help%2Bunsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help%2Bunsubscribe@wormbase.org>.
>


--
------------------------------------------------------------------------
Scott Cain, Ph. D.                                   scott at scottcain dot net
GMOD Coordinator (http://gmod.org/)                     216-392-3087
Ontario Institute for Cancer Research

--
Ashley D Sawle
Senior Bioinformatics Analyst
Bioinformatics Core
Cancer Research UK Cambridge Institute
