### ISSUE TITLE
 Server Error: 500 at  tools/schema/run   
  Error...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6876]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/tools/schema/run">tools/schema/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "Could not connect to database acedb _WS268, host: staging.localdomain" </p><p>What were you doing? <br />&nbsp;&nbsp;Using the Schema display tool to look at ?Variation model</p>

**Reported by:** Chri******* (cgro**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/schema/run">/tools/schema/run</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
I currently cannot look at any data models via the Schema Display tool

**Comment by chris-grove** [comment]
Seems to be fixed now. Closing.
