### ISSUE TITLE
  Do you know of a SNP database for C. ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6879]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Do you know of a SNP database for C. elegans that I can use?</p><p>What were you doing? <br />&nbsp;&nbsp;Map the position of an unknown gene.</p>

**Reported by:** Sult********** (sjen*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Sultan,

Thanks for getting in touch with us. WormBase contains a large number of 
annotated SNPs for C. elegans.
Could you provide additions information on what you are trying to do so 
that we can help you further.

There is a jbrowse track specifically for SNP data.

https://staging.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CPolymorphisms&loc=X%3A10531994..10538141&data=data%2Fc_elegans_PRJNA13758&highlight=

Paul



On 28/01/2019 22:01, no-reply@wormbase.org wrote:
> Question:
>
>   Do you know of a SNP database for C. elegans that I can use?
>
> What were you doing?
>   Map the position of an unknown gene.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6879. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6879>.
>
> Reported by: Sultan Jenkins (sjenkins@lagcc.cuny.edu)
> 28 Jan 19 22:01
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/71.0.3578.98 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
