### ISSUE TITLE
Hi there. I'm wondering what a "ncRNA" is in the c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6880]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there. I'm wondering what a "ncRNA" is in the c.elegans annotation files. How do these differ from other non coding RNAs e.g. miRNAs, piRNA, lncRNAs?

**Reported by:** Lina (lina*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide#3--10">https://wormbase.org/about/userguide#3--10</a>
**Browser:** Chrome 71.0.3578.98

**Comment by Paul-Davis** [comment]
Dear Lina,

Thank you for contacting WormBase.

Generally if the small non-coding RNA is annotated as a generic ncRNA 
then either we do not have the relevant category in our schema to allow 
for that subtype of ncRNA to be captured or more frequently it's where 
the exact nature of the ncRNA is not known. These usually come from 
large scale RNASeq based projects where detailed study about the type of 
ncRNA was not part of the project so remains unknown.

If you have specific example I would be more than happy to take a look 
at them in detail.

Paul



On 29/01/2019 14:58, no-reply@wormbase.org wrote:
> offline chat Hi there. I'm wondering what a "ncRNA" is in the 
> c.elegans annotation files. How do these differ from other non coding 
> RNAs e.g. miRNAs, piRNA, lncRNAs?
>
> Submitted From:
>   https://wormbase.org/about/userguide#3--10 
> https://wormbase.org/about/userguide#3--10 
> <http://www.wormbase.org/https://wormbase.org/about/userguide#3--10>
>
> This issue has been assigned ticket number: #6880. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6880>.
>
> Reported by: Lina (linawadi862@gmail.com)
> 29 Jan 19 14:58
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
