### ISSUE TITLE
  Hi, I was wondering if there was a wa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6881]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I was wondering if there was a way to obtain a table of gene names based on the "Type" classification (e.g. protein coding, rRNA, etc.), thanks!</p>

**Reported by:** Anon***** (dark******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
You can do this in WormMine using the template query called "Transcript Type, Species --> Genes" under the "GENOMICS" tab on the WormMine homepage. Note that the results of this query are genes and all associated transcripts, so you can use the "Save as List" button to save the gene list specifically. Here's a screen recording to demonstrate:

https://www.dropbox.com/s/pmuzzbuo6pp22r2/Getting_list_of_genes_of_a_particular_type_Jan_29_2019.mov?dl=0

Let us know if you have any questions.
"""
