### ISSUE TITLE
WormMine Gene attribute addition

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6882]
Would it be possible to get Biotype added for Gene in WormMine?

I'm not sure what sources are used for the WormMine build so if you have questions about where to get the data feel free to ping me.

Thanks

Paul

**Comment by nuin** [comment]
Yes, that should be fine. Most of the data is loaded from the AceDB dump and Biotype is present there. I will check the type of the element and other requirements and get back to you.

**Comment by nuin** [comment]
@Paul-Davis I did some checking on Biotype, sorry for the delay, I just wanted to be sure to capture everything correctly. So far we don't have any other class with `<Biotype>` in WormMine but Gene.xml. Most items are 

`SO_term`

with a structure 

```
<Biotype>
    <SO_term>SO:00000</SO_term>
</Biotype>
```

It seems that `SO_terms` are found in Feature.xml too. We still don't have this in WormMine but it is in the pipeline. Would it be OK to have BioType by itself for now, not related to any other class? I can do a quick test for the mapping and see if the data is being loaded correctly. Do we need the terms connected to anything else that I am not capturing?

Thanks

**Comment by nuin** [comment]
@Paul-Davis I added a mapping to extract the Biotype entries from the XML.

```
biotype         = /Gene/Gene_info/Biotype/SO_term/text()[1]
```

Whatever gene that has `SO_term`, it will be added to the DB, like below.

```briefdescription             | unc-26 encodes synaptojanin, a polyphosphoinositide phosphatase orthologous to human synaptojanin 1 (OMIM:604297, 309000, which when mutated leads to Lowe oculocerebrorenal syndrome); UNC-26 is required for normal locomotion, pharyngeal pumping, and defecation, and specifically, appears to function in multiple steps of synaptic vesicle recycling; UNC-26 may also play a role in cytoskeletal organization.
description                  | *
scoretype                    | *
id                           | 1000005
length                       | *
name                         | unc-26
lastupdated                  | *
primaryidentifier            | WBGene00006763
score                        | *
biotype                      | SO:0001217
symbol                       | unc-26
operon                       | CEOP4539
secondaryidentifier          | JC8.10
referencealleleid            | 1000141
upstreamintergenicregionid   | *
downstreamintergenicregionid | *
sequenceontologytermid       | 1000140
organismid                   | 1000153
chromosomelocationid         | *
sequenceid                   | *
chromosomeid                 | *
class                        | org.intermine.model.bio.Gene
```

Currently this is not linked to any other `So_term` related tag/class, but this can be added anytime.

We can close the ticket after the next release. Let me know if there any issues or something else to be done.

**Comment by chris-grove** [comment]
@nuin Is there a place to test this? One thing I'm not clear on, from what you said, is whether these SO term IDs are going to be tied to a human readable name or not. I think that would be a requirement of including the biotype. I actually just noticed that we have the "SO Term" class that only has the "Name" attribute. We should really have the IDs and the names and then make the connection between the SO Term IDs in the Gene Biotype attribute to the SO Term names already loaded.

**Comment by nuin** [comment]
@chris-grove I built a small dataset with a handful of genes. 

The `SO Term` class is a core InterMine and at the moment this would be the only term of this type in the DB. 

https://intermine.readthedocs.io/en/latest/data-model/overview/#so-terms

I have checked our current sources and there are no other `SO_term` in other files but Gene.XML.

**Comment by nuin** [comment]
@chris-grove There's a deployment on im-dev1 with a test for Biotype. No Variation/Allele added to the  build.

**Comment by chris-grove** [comment]
@nuin 
OK thanks. It's good that we now have biotype loaded, but each gene is now only listing its respective SO Term ID, with no option to display the human readable name. Users should really be able to view the human readable name in addition to the SO ID. I see that we do have an "SO Term" class loaded into WormMine, but it has the opposite problem, only names and no SO IDs. Also, "CDS" as a type is repeated 6 times and "transcript" is repeated three times. Can we do a formal import of the SO ontology and merge these SO Term objects so that each has an ID and an affiliated human readable name?

**Comment by nuin** [comment]
@chris-grove 

Can you open a new ticket with SO issue and close this if the original request was fulfilled? I am working on the SO terms.

**Comment by chris-grove** [comment]
@nuin 
OK, new ticket here
https://github.com/WormBase/website/issues/7038
