### ISSUE TITLE
  I have a gene sequence for c. elegans...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6883]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a gene sequence for c. elegans, how do I find out what gene it is?</p>

**Reported by:** Sam (dant*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
Resolving via chat now. Closing.
