### ISSUE TITLE
  Hello, i would like to know the chrom...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6888]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, i would like to know the chromosome myo-3 is located on, and how many exons and introns are present in this gene. How might i go about doing this?</p><p>What were you doing? <br />&nbsp;&nbsp;Looked at sequences, location, etc.</p>

**Reported by:** Anon***** (arau***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
You can find all of this information in the Location widget on the myo-3 gene page:

https://wormbase.org/species/c_elegans/gene/WBGene00003515#09--10

The "Genomic position" shows you the chromosome and position on that chromosome and the Genome Browser Preview shows you the gene model(s) for the gene indicating the exons and introns in the cartoon.
"""
