### ISSUE TITLE
  What have you done to blast searches?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6891]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;What have you done to blast searches?  Now I cannot see what the gene is that is a hit on Gbrowse or Jbrowse.  Now all I see is chrIII_pilon_coordinates.<br/>Once upon a time when you did a blast search you could click on nearby genes in gbrowse and it linked to the acutal gene.</p><p>What were you doing? <br />&nbsp;&nbsp;Blast searching</p>

**Reported by:** Bria*********** (krae***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
@tharris 's email to user:
"""
Under “Bioproject”, make sure you have selected the “C. elegans Sequencing Consortium genome project”. Otherwise, currently, you’ll be blasting against VC2010 and not N2. 

This is a known issue on our docket. 
"""
