### ISSUE TITLE
  I just recognized that the current BL...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6893]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I just recognized that the current BLASTN default<br/>nucleotide database is not the standard C. elegans genome, but instead<br/>VC2020. This will trap very many users, who will wonder while the<br/>annotation in gbrowse looks so pour.<br/>I strongly suggest to set the default to the standard C. elegans genome.<br/>This would make life easier for most users.</p><p>What were you doing? <br />&nbsp;&nbsp;research&teaching</p>

**Reported by:** Ekke************ (Ekke*************************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by chris-grove** [comment]
My email to user:
"""
Thanks for the heads up. We are aware of the issue and plan to have a fix for this on the website soon.
"""
