### ISSUE TITLE
the browser of new wormbase is too sensitive...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6896]
*Help Desk query collected when no chat operators were online. Follow up required.*

the browser of new wormbase is too sensitive

**Reported by:** Yish***** (yiji**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=X:5716329..5731121&amp;data=data/c_elegans_PRJNA13758">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=X:5716329..5731121&amp;data=data/c_elegans_PRJNA13758</a>
**Browser:** Firefox 64.0

**Comment by scottcain** [comment]
Replied to user:

Hi Jin,

I'm assuming you are referring to JBrowse, the new(-ish) genome browser.  I have seen instances of "jittery" behavior when using a touch sensitive mouse like Apple's magic mouse.  Is that what you are referring to? If so, I don't have much to offer in terms of help, other than trying another mouse.  For what it's worth, I use a magic mouse when I'm using JBrowse and like it's behavior, but perhaps it trained me :-)

If that's not what you're referring to, please feel free to let me know what's going on and hopefully it can be addressed.  Also, if it helps, I can stop by and take a look--I recently moved to the San Diego area and live not very far from UCSD.
