### ISSUE TITLE
  I can't figure out how to find a prom...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6897]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I can't figure out how to find a promoter region for srh-220 in c elegans. I've found the gene, I can find the sequence of exons/introns, and I can look at the position, but I don't know how to identify the promoter region and copy the sequence. Also can't find any existing plasmids that contain it, which would also be helpful if you have advice on that in general... Thanks</p>

**Reported by:** Dani***************** (dcos**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""  
There are several different ways to find the promoter sequence of a gene. Using srh-220 as an example:

https://www.wormbase.org/species/c_elegans/gene/WBGene00005430#0dg9--10

First, in the "Sequences" widget in the "Transcript" column, click on the double-helix icon to the left of the transcript name "F47C12.5.1". You should then see a pop-up with sequence information. Towards the bottom of the pop-up is an option to:

"view unspliced + UTR + 2000 upstream + 2000 downstream"

Expand that section and you can find the sequence immediately upstream of that transcript in lowercase, beige-highlighted text. Note that this may or may not include sequences of upstream genes.

Second, in the "Location" widget, click on the "Genomic position" coordinates link, which will take you to JBrowse. Once in JBrowse, open the "Curated genes (protein coding)" track, right click on the transcript in question (only one for srh-220), click on "View Sequence", click "OK" on the pop-up, and you will then be presented with the gene sequence. You can highlight portions of the gene's sequence like CDS (coding sequence) or exons. Then, in the row titled "Upstream" click on the drop down menu "Select View" and select the desired amount of upstream sequence up to 4,000 bp in increments of 500 bp. Again, note that this may or may not include sequences of upstream genes.

Third, on our FTP site (link available at the bottom of every WormBase page), we have a file for intergenic sequences:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS268.intergenic_sequences.fa.gz

Note that this link is stable except for the "WS268" part which will update incrementally with each WormBase release. The directory will always be:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

The intergenic sequences are in FASTA format, with each header looking like (for example):

>WBGene00005430_WBGene00005432 IV 3978016, len:1809

where srh-220 (WBGene00005430) is the upstream gene on the positive strand and srh-222 (WBGene00005432) is the downstream gene on the positive strand. This entry has the sequence upstream of srh-220 up until the next upstream gene srh-222:

ACTTGAGTTTGGACCGAAAAGCCAGCTCATTGTTGGTAAGGTGGTGTAACTAGAGGCTGA
GGTAGAAGGGATGTCAAAAAAAATACGCAGCAGGTGAAAATGTAAATTTTCCTTACTAGG
GAGTCTTGTTTGGCGTCCAGAGAATCATAGATCGAACGATATATATCCTGAAAGCTTATG
CAATAGAAATTCTGAATATGAAATGAAATCTTGCCCGATTTGCCAATTTTTCAATTTTTT
GCGCCGCACTGTGAGCAGCGAAGTGCGAAAGGTGGTTATTTGGAAGCGGCCGACACGCAC
GTGGTTCCGCAGATTAGCGTGAAATCAGTAGTGAGTAGGCACTGGCCGGCGAACCTGCAC
CCACATGGAAGCCCCACTTCACGTGGGGTTTTGGTTTGATCTTCGAAAAATGCGGGAGAA
GAGACGCAGACTTTTCAACTGAATTCGCATGGTTAGGAGTGTTCTGACGTCACGTTTTCC
TGTGGGAAAAATTCCCGCATTTTTTGTAGGACCAAGCGCAATGAGACAGACTGAGACCAC
GTGCGACTTTAAAGCAACGTCATGGCAAATTTAATCAATTGTATCTCCTGTTAATCTCCG
TAAAATCAACAGATAGATGATAATGTGAACTCACAAATTTGGACAAACTTTACTGGACAA
ATTTTGTTCATTTGTAATATTGTTTCAATATGAAATTTTTAAAATGAAGTTATTTTATTA
CCAGGCAAATTGTGAGAATATAATACATACACATGATGGGAAAATTCTAAAAATTTCCAA
AAACCAAGCTAAAACTTGCCTGGGGCAACTGTTACCGATTTTTTGATTTTGTATGCATTA
TACGTACCAGATGTGATTTTTTTCGCAAATCGGCAAAAAAATTTCCATCGAAATGTGGCT
TTGCACTTTTTTTTTGAAATTTCAGAGTTTCAATTTTAATCGGCAAAATTGATCCAACAT
CTATTTTGAAATGAAAGCAAATTCTATGAAGTTATCTAAAGAAAACAGGAAAAAATTCCA
AAAAGGCACAGTTTTAAGTTTTTTATTAAAAAATTCCCCTAAACACTTTCGGCAAACGGC
AAATTGGCAATTCGCCAAAATTGAAAGTTCCCGGCAAATCTAAAAACCGGTAATTTGTCG
ATTTGCCAAACGGCAATTGCCGCCCACCCCTGATACGTACGCATGTCAGTAGTGGCGCTA
CAAACTACAAATATGTACTACATACTACAAGTTCTCCAAACTATAACAATCTGAACAAAA
ACTTTTGCAGACTCGGTGATTGAATTCTTTTTCATATCGGCAGGTGAAACTAATATTCAA
AAACTGGCTAGTTGCAACAGAAATGTAAGGTTTTTGAAACATGTGTAACGTATGAAAACC
TAATGGGATTATTTATGAAAAATGCAAAAATGTATTTTTATACAGTTCTCCCCTATTCAT
GTGTGCAGAAAGAGTTTTTAAAAACGCATTCATTTTTTCATTTTTTTAAACATTTTTCTG
CACACATGAATAGGGGAAAAGTTTATAAAAATAAATTTCTGCATTTTTCGTCATCACATG
AATCACCTAAAAACCAAAAAAACAAAATTTTCAACAGTAAAGTTAGCTTCCCACAACTGA
AAATATCACATTAACTTGACACTTTTTGAATTTTGACCCGGAACCAGCACTCTCTAATAT
TATTAGGATAATGGTGTCAATGAATATAATTAAATCAGTGATCAAAAAGTTGAAATCACC
GGGAATTGGCAGGTGGTAATATAGAGAGAAAGAAATTTTGTGATTTTCTCCCTCCATTCC
ACTCTAAAA

Note that this sequence starts at the 5' end of srh-220 and goes until the 5' end of srh-222, so you would want the reverses complement to get the promoter sequence in the direction of srh-220. Note that this will be exactly the intergenic sequence from one gene to the next.

Fourth, you can use WormBase ParaSite BioMart:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.transcript_flank|wbps_gene.default.sequences.upstream_flank."2000"&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."srh-220"&VISIBLEPANEL=resultspanel

This will return any number of nucleotides upstream that you specify (for a gene or all transcripts for a gene). Note that this may or may not include sequences of upstream genes.

Fifth, there are also ways to manually extract the sequence from JBrowse using the "Reference sequence (DNA)" track (use the track's "Save track data" option), but those are a little bit less precise. I'd be happy to show you those as well if you'd like.

As for plasmids, take a look in the gene page "Reagents" widget which lists constructs and transgenes using that gene's promoter.

Let us know if you have any questions.
"""
