### ISSUE TITLE
  When I tried to login to wormbase usi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6898]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;When I tried to login to wormbase using my email, I got a message saying that wormbase does not have such email.  <br/>visitor_name</p>

**Reported by:** Yish***** (yiji**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by chris-grove** [comment]
@WenChenWormBase 
Has the issue been addressed? Has anyone responded to the user?

**Comment by sibyl229** [comment]
I just did. Waiting to hear back from them.

**Comment by chris-grove** [comment]
OK, thanks @sibyl229

**Comment by vanaukenk** [comment]
@sibyl229 - okay to close this ticket?  Thx.

**Comment by sibyl229** [comment]
@vanaukenk thanks for the reminder. Closing
