### ISSUE TITLE
Please help me see the actual sequence of the regi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6900]
*Help Desk query collected when no chat operators were online. Follow up required.*

Please help me see the actual sequence of the regions I'm looking at. I need to copy  ~4kb before the str-1 gene. Thank you

**Reported by:** Dani***************** (dcos**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Hits,Classical_alleles,Promoter regions&amp;loc=IV:7167751..7178360&amp;addFeatures=[{"seq_id":"IV","start":3685491,"end":13446632,"name":"Hits","type":"match","subfeatures":[{"seq_id":"IV","start":7171789,"end":7173043,"type":"match_part"},{"seq_id":"IV","start":7173107,"end":7174230,"type":"match_part"},{"seq_id":"IV","start":7171135,"end":7171226,"type":"match_part"},{"seq_id":"IV","start":13446607,"end":13446632,"type":"match_part"},{"seq_id":"IV","start":6390292,"end":6390311,"type":"match_part"},{"seq_id":"IV","start":9858936,"end":9858955,"type":"match_part"},{"seq_id":"IV","start":11266259,"end":11266282,"type":"match_part"},{"seq_id":"IV","start":3685491,"end":3685513,"type":"match_part"},{"seq_id":"IV","start":4301005,"end":4301023,"type":"match_part"},{"seq_id":"IV","start":6444584,"end":6444606,"type":"match_part"}]}]&amp;data=data/c_elegans_PRJNA13758&amp;addTracks=[{"label":"Hits","type":"JBrowse/View/Track/CanvasFeatures","store":"url","subParts":"match_part","glyph":"JBrowse/View/FeatureGlyph/Segments"}]&amp;highlight=IV:7169569..7173788">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Hits,Classical_alleles,Promoter regions&amp;loc=IV:7167751..7178360&amp;addFeatures=[{"seq_id":"IV","start":3685491,"end":13446632,"name":"Hits","type":"match","subfeatures":[{"seq_id":"IV","start":7171789,"end":7173043,"type":"match_part"},{"seq_id":"IV","start":7173107,"end":7174230,"type":"match_part"},{"seq_id":"IV","start":7171135,"end":7171226,"type":"match_part"},{"seq_id":"IV","start":13446607,"end":13446632,"type":"match_part"},{"seq_id":"IV","start":6390292,"end":6390311,"type":"match_part"},{"seq_id":"IV","start":9858936,"end":9858955,"type":"match_part"},{"seq_id":"IV","start":11266259,"end":11266282,"type":"match_part"},{"seq_id":"IV","start":3685491,"end":3685513,"type":"match_part"},{"seq_id":"IV","start":4301005,"end":4301023,"type":"match_part"},{"seq_id":"IV","start":6444584,"end":6444606,"type":"match_part"}]}]&amp;data=data/c_elegans_PRJNA13758&amp;addTracks=[{"label":"Hits","type":"JBrowse/View/Track/CanvasFeatures","store":"url","subParts":"match_part","glyph":"JBrowse/View/FeatureGlyph/Segments"}]&amp;highlight=IV:7169569..7173788</a>
**Browser:** Chrome 71.0.3578.98

**Comment by scottcain** [comment]
Emailed the user:

Hi Danielle,

It’s pretty easy once you know the secret. Please open the “Curated genes (protein coding)” track and right/control click on the str-1 transcript. Select “view sequence” from the drop down menu and after clicking away a warning, you’ll get a dialog box with the sequence of str-1 in it. One of the options is to show upstream sequence and you can select 4kb from the menu. Select it all, copy and paste into whatever you want. Please let me know if you have any questions. 

She replied:

Fumbled around with the regular curated genes track (not protein coding), but finally got it! Thanks a lot, this is perfect

**Comment by scottcain** [comment]
Feature request that will help (slightly) with this: add the "view sequence" functionality to the main curated genes track.  When this functionality was initially implemented it wouldn't work with gene features (only individual transcripts) but it has been expanded to allow users to view the sequence of a gene and then select which transcript to view the subfeatures of.

**Comment by scottcain** [comment]
It's nice to close feature requests a mere 6 hours after opening them :-)

**Comment by chris-grove** [comment]
@scottcain  Very nice!!
