### ISSUE TITLE
  Lon regarding  ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6901]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Lon regarding </p>

**Reported by:** Anki*********************** (Anki*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Linux; Android 8.0.0; SM-A600G Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

**Comment by chris-grove** [comment]
Responded to user. Closing. Will reopen if necessary.
