### ISSUE TITLE
Hi, I'm trying to get info on C. elegans operons, ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6902]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I'm trying to get info on C. elegans operons, and I thought I just was able to retrieve the member genes for each of them from the API but I just noticed that there are a number of discrepancies between the genes that overlap the genomic position of some operons, and the genes that are listed in the "structure" field. For example, for CEOPX166 and CEOP1997 there appear to be at least two active protein-coding genes that overlap each of those operons, but the "structure" field is empty. Does that indicate these operons are effectively deprecated, but haven't been labeled as "deprecated" yet? I found 122 explicitly "deprecated" operons, and 14 cases among non-deprecated operons where no genes are defined. This is in the current production version of Wormbase. Any insight would be appreciated. Thank you.

**Reported by:** Adam (adam****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/operon/CEOP1997#012--10">https://www.wormbase.org/species/c_elegans/operon/CEOP1997#012--10</a>
**Browser:** Firefox 64.0

**Comment by Paul-Davis** [comment]
Dear Adam,

Thank you for contacting WormBase,

Could you clarify where you are seeing empty "structure" fields?

Checking the Operon summary pages for the 2 you have mentioned I do see 
fully populated Structure widgets:

https://www.wormbase.org/species/c_elegans/operon/CEOP1997#2--10
https://www.wormbase.org/species/c_elegans/operon/CEOPX166#2--10

These 2 would appear to be fully populated 2 gene operons.

Our annotations file also contains the correct data:
I    operon    operon    347469 357193    .    +    . 
Name=CEOP1997;genes=WBGene00021657,WBGene00021658
X    operon    operon    5279497    5289726    .    +    . 
Name=CEOPX166;genes=WBGene00017974,WBGene00021319

The Deprecated operons are operons that fall below the SL2 thresholds 
defined by Tom Blumental but WormBase chose to keep mapping and 
displaying them as they had been in existence for a long time with some 
EST/RNASeq evidence for low level SL2 usage.

Paul

On 06/02/2019 22:51, no-reply@wormbase.org wrote:
> offline chat Hi, I'm trying to get info on C. elegans operons, and I 
> thought I just was able to retrieve the member genes for each of them 
> from the API but I just noticed that there are a number of 
> discrepancies between the genes that overlap the genomic position of 
> some operons, and the genes that are listed in the "structure" field. 
> For example, for CEOPX166 and CEOP1997 there appear to be at least two 
> active protein-coding genes that overlap each of those operons, but 
> the "structure" field is empty. Does that indicate these operons are 
> effectively deprecated, but haven't been labeled as "deprecated" yet? 
> I found 122 explicitly "deprecated" operons, and 14 cases among 
> non-deprecated operons where no genes are defined. This is in the 
> current production version of Wormbase. Any insight would be 
> appreciated. Thank you.
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans/operon/CEOP1997#012--10 
> https://www.wormbase.org/species/c_elegans/operon/CEOP1997#012--10 
> <http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/operon/CEOP1997#012--10> 
>
>
> This issue has been assigned ticket number: #6902. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6902>.
>
> Reported by: Adam (adam_cornwell@urmc.rochester.edu)
> 06 Feb 19 22:51
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
User response:Thank you for the response- I was referring to the API results in particular, but it did line up with the web results at the time, and indeed I do see the two genes in the field for those two operons on the web results right now. I wish I had taken a screenshot a few days ago. I’ll have to re-check my API results. That’s odd.

Which file in the FTP has the operon information? I’ve tried to find it before, but didn’t see it in there, so I resorted to pulling the list of operon IDs from the website and then retrieving the associated information from the API.

I bet it’s in the GFF3 and I’m going to feel silly that I hadn’t checked there previously- I’ve been using the ENSEMBL GTFs primarily so I didn’t do a full survey of the feature types annotated in the WormBase GFFs…

 

Adam

**Comment by Paul-Davis** [comment]
Rest url's appear to be providing the data now:

**Comment by Paul-Davis** [comment]
Transient error maybe @sibyl229

**Comment by sibyl229** [comment]
This is quite odd. The code hasn't changed between now and then. And It doesn't look like the database has either. The Clojure code is producing the same result as the perl code based on ACeDB. 

I can' think of other potential causes at the moment. Would be good to troubleshoot when this problem is happening.
