### ISSUE TITLE
  The format for wormbase has change re...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6911]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The format for wormbase has change recently so I am not able to get back to my allele information page. How do I, for example, click on allele ok988 and go to page that use to belong in wormbase (that lists the EXACT sequence of the mutation).<br/>Thank you.</p>

**Reported by:** Anon***** (Mica********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50

**Comment by chris-grove** [comment]
My email to user:
"""
We recently implemented some upgrades to allele sequence display in the "Molecular Details" widget on variation pages, but I don't think that should have interfered with any links you are using. On which page are you clicking on the allele name "ok988" and where is that taking you?

The variation page for this allele is here:

https://www.wormbase.org/species/c_elegans/variation/WBVar00092259#05--10

The "Molecular Details" widget should have all the sequence information you are looking for. Let us know if not.
"""
