### ISSUE TITLE
Dear WormBase community,
I'd like to report a typo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6913]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear WormBase community,
I'd like to report a typo in the table of contents at
https://www.wormbase.org/about/userguide/for_developers/API-REST/Gene, though it seems to be a minor problem.
"concise_desciption" should be written as "concise_description".

**Reported by:** Yusu************ (taka****************************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10">https://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10</a>
**Browser:** Chrome 71.0.3578.98

**Comment by nuin** [comment]
@sibyl229 I fixed the only typo I could find, hope it's the right place

**Comment by tharris** [comment]
Issue resolved; user contacted.
