### ISSUE TITLE
  I am looking for relationships betwee...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6916]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am looking for relationships between ion channel gene mutations and structural defects including any developmental patterning phenotypes (any defects in embryonic or adult anatomy). I wanted to know what the most efficient way to do that is -- I want to find genes and see the effect a mutation in them has on the structure / phenotype of the organism (it can be any species). </p><p>What were you doing? <br />&nbsp;&nbsp;I was searching up terms like "ion channel" and trying to go gene by gene to see which one caused any structural defects but I only saw links to diseases they might cause, not actual relationships between mutations and the structural defects. I was wondering how I could find genes that lead to clear-cut structural defects. </p>

**Reported by:** Anon***** (1pra*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
Yes, this can be done in WormMine (discoverable under the WormBase Tools menu):

http://intermine.wormbase.org/tools/wormmine/customQuery.do

This particular query involves a few steps:

1) Save a list of Gene Ontology (GO) molecular function terms that are the term "ion channel activity" or any of its descendant terms: to do this, go to the WormMine homepage (link above), click on the heading "GENE ONTOLOGY" in the middle of the page, and then below that click on the template query "GO Term --> is_a Descendants". On the next page, in the "GO Term > Name" field, replace the default entry of "protein glycosylation" with "ion channel activity", and click on "Show Results". On the resulting page, click on the "Save as List" button, then click on "GO Term > Relations > Child Term (131 Ontology Terms)" and in the resulting dialog box, replace the default "List Name" with "ion channel activity and descendants" and click on "Create List"

2) Save a list of phenotype terms that are "morphology variant" and descendant terms: back on the WormMine homepage, click on the heading "PHENOTYPES" in the middle of the page, and then below that click on the template query "Phenotype --> Phenotype & All Subtypes". On the next page, in the "Phenotype > Name" field, replace the default entry "embryonic lethal" with the phenotype term name "morphology variant", and click on "Show Results". On the resulting page, click on the "Save as List" button, then click on "Phenotype > Relations > Child Term (494 Ontology Terms)" and in the resulting dialog box, replace the default "List Name" with "morphology variant and descendants" and click on "Create List"

3) Get your list of ion channel genes and associated alleles with a morphology phenotype: from within WormMine, click on the "QueryBuilder" tab at the top, then click on "Import query from XML" at the left and paste the following XML query into the search box:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.alleles.primaryIdentifier Gene.alleles.symbol Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B and C">
  <constraint path="Gene.goAnnotation.qualifier" code="A" op="IS NULL"/>
  <constraint path="Gene.goAnnotation.ontologyTerm" code="B" op="IN" value="ion channel activity and descendants"/>
  <constraint path="Gene.alleles.phenotype" code="C" op="IN" value="morphology variant and descendants"/>
</query>`

and click "Submit" and on the next page click "Show results". You should get a table of 187 rows listing all ion channel genes for which there exists at least one allele with a morphology variant phenotype. You can use the "Export" option to export the table in TSV format.

If you also want to check RNAi phenotypes for these genes, run the following query (using the same method as above):

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.RNAiResult.primaryIdentifier Gene.RNAiResult.phenotype.identifier Gene.RNAiResult.phenotype.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B and C">
  <constraint path="Gene.goAnnotation.qualifier" code="A" op="IS NULL"/>
  <constraint path="Gene.goAnnotation.ontologyTerm" code="B" op="IN" value="ion channel activity and descendants"/>
  <constraint path="Gene.RNAiResult.phenotype" code="C" op="IN" value="morphology variant and descendants"/>
</query>`

This should return a table of 55 RNAi-based morphology phenotypes for ion channel genes.

Let me know if you have any questions.
