### ISSUE TITLE
  Hello, I'm hoping to get a list of th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6918]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I'm hoping to get a list of the genes & isoforms that have full-length cDNAs supporting their structure. Is there any way to do this? I tried looking in the GFF annotation file, and found the Confirmed_cDNA tag in some introns, however there were only 2660 isoforms across 1511 genes with each of their introns labeled with Confirmed_cDNA. That number seemed really low to me, so I wanted to reach out and see if I am looking at the right thing, or if there is a better way to get a list of genes with full-length support.<br/>I see that there's a 'confirmed_genes.fa' in the annotation folder, but I'm trying to identify genes and isoforms whose structure was determined with full length cDNAs specifically, and exclude isoforms whose structure was determined by stitching ESTs together computationally. Any help you can provide would be greatly appreciated, thank you.</p>

**Reported by:** Nath******** (natp***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Nathan,

Just looking at the number of reported mRNAs for elegans I'm also coming 
up with similar numbers to you.
There are currently 1696 mRNAs attached to CDS isoforms that we align to 
the genome, these map to 1705 CDS Isoforms from 1251 genes.

I have deposited the list of CDS Isoforms and mRNA list here:
ftp://ftp.sanger.ac.uk/pub/wormbase/STAFF/pad/Roach/

I think the discrepancy in numbers are where some introns are confirmed 
by mRNA but there is a misalignment in the mRNA sequence so does not get 
attached.

I hope this helps.

Paul





On 13/02/2019 02:54, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> I'm hoping to get a list of the genes & isoforms that have full-length 
> cDNAs supporting their structure. Is there any way to do this? I tried 
> looking in the GFF annotation file, and found the Confirmed_cDNA tag 
> in some introns, however there were only 2660 isoforms across 1511 
> genes with each of their introns labeled with Confirmed_cDNA. That 
> number seemed really low to me, so I wanted to reach out and see if I 
> am looking at the right thing, or if there is a better way to get a 
> list of genes with full-length support.
> I see that there's a 'confirmed_genes.fa' in the annotation folder, 
> but I'm trying to identify genes and isoforms whose structure was 
> determined with full length cDNAs specifically, and exclude isoforms 
> whose structure was determined by stitching ESTs together 
> computationally. Any help you can provide would be greatly 
> appreciated, thank you.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6918. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6918>.
>
> Reported by: Nathan Roach (natproach@gmail.com)
> 13 Feb 19 02:54
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
