### ISSUE TITLE
In Jbrowse, how do you get FASTA genomic sequence?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6919]
*Help Desk query collected when no chat operators were online. Follow up required.*

In Jbrowse, how do you get FASTA genomic sequence?  Thanks

**Reported by:** Eliz************ (eliz***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00001460#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00001460#0-9g-3</a>
**Browser:** Firefox 60.0

**Comment by scottcain** [comment]
Replied to the user:
Hello Elizabeth,

As it happens, I was just working on a document that will become a blog post that answers this exact question.  If you like, you can take a look at what I have here:

[google doc url removed]

If it doesn't answer your question, please let me know so I can improve it.  Feel free to either email me back or comment in the google doc.
