### ISSUE TITLE
I am truly interested....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6923]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am truly interested.

**Reported by:** Anth************** (akmc***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00002235#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00002235#0-9g-3</a>
**Browser:** Chrome 72.0.3626.105

**Comment by tharris** [comment]
User contacted for clarification. 

Thank you for reaching out. Do you have a specific question for us?

Todd on behalf of The WormBase Help Desk
