### ISSUE TITLE
new features for WS271 VC2010 JBrowse

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6924]
there will me new features in the VC2010 GFF3, which need tracks on JBrowse:

minimap cDNA_match - minimap liftover of WS264 N2 gene models
infernal-1.1.2/Rfam-13.0 nucleotide_motif - RFam/Infernal ncRNA predictions
not_lifted_over region - VC2010 specific genome regions

I resorted the GFF3 file, so hopefully it just loads.

**Comment by epaule** [comment]
for testing: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/mh6/elegans_vc2010.gff3.xz

**Comment by epaule** [comment]
ok, I replaced the minimap/cDNA_match with filtered_minimap/* which hopefully should show as proper CDSes

the file on the FTP is also updated

**Comment by scottcain** [comment]
@epaule,

Can you please give me an update on these features?  When I look I look in the GFF for VC2010 for WS271 and WS272 (c_elegans.PRJEB28388.WS271.annotations.gff3 and c_elegans.PRJEB28388.WS272.annotations.gff3), I don't see any features that look like what you describe.  Should I be getting them from somewhere else?

**Comment by epaule** [comment]
no, they should have been appended to the VC2010 gff file. Will investigate our build scripts.

**Comment by scottcain** [comment]
Closing this, since the minimap features made it into the 273 GFF.
