### ISSUE TITLE
 Server Error: visitor_name at  tools/blast_blat/r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6926]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: visitor_name at <a href="http://wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_ivBJC.out.err' - sysopen: No such file or directory at /usr/local/wormbase/jenkins/workspace/staging_build/lib/WormBase/API/Service/blast_blat.pm line 319." </p>

**Reported by:** 500 (zhuh************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by tharris** [comment]
Issue resolved; user contacted.
