### ISSUE TITLE
  Dear Sir/Ma'am, Recently I wanted to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6927]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Ma'am,<br/>Recently I wanted to change my affiliation as well as linage in Wormbase, but my login was not successful. I get a message back saying that "no WormBase account is associated with this email". However, I'm sure that I used the same email address in 2015 to create my account and I even still have confirmation emails sent to the same address. Would you help me access my account again?<br/>Thank you very much in advance.<br/>visitor_name</p>

**Reported by:** Ghol************* (ghol******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by tharris** [comment]
Issue partially addressed. Still checking on problems with account.

```
We’ll take a look into the problem with your account.
In the meantime, it’s not actually possible to update your information directly from your account.
Instead, you can update your personal information via this form:
http://www.wormbase.org/submissions/person.cgi

And you can update your lineage information via this form:
http://www.wormbase.org/submissions/person_lineage.cgi
```

**Comment by tharris** [comment]
User had no acccount prior.
