### ISSUE TITLE
  Dear Wormbase team, How do I access t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6938]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase team,<br/>How do I access the most recent version of the genome assembly and annotation for all polymorphisms (SNPs, indels) for CB4856 (Hawaiian strain) vs. the N2 strain? <br/>On the FAQ page, there seems to be some typos or bug where it attempts to give that information:<br/>(https://wormbase.org/about/Frequently_asked_questions#a2cde3605184f7b9--10)<br/>"...I'm interested in the CB4858 pas* snp data can I get a bulk download?? <br/>A complete dataset of pas snp data is available from Here"<br/>There's no hyperlink where "Here" appears, and around that paragraph I don't see any info about answer that question.<br/>Please let me know what I need to do. Thanks for your help!<br/>Sincerely,<br/>Welles</p>

**Reported by:** Well******* (IoLo********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
Currently, the best (and quickest) way to get these is by parsing our C. elegans GFF file(s). The current version of these files can always be found on our FTP site here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

Currently, the GFF3 file is called:

c_elegans.PRJNA13758.WS268.annotations.gff3.gz

but will change with each WormBase release, such that the WS number will increase incrementally (the current release is WS268). Once you download and unzip that file, you can run the following command on the command line to extract the lines pertaining to the Hawaiian strain CB4856:

`awk 'BEGIN {FS="\t";OFS="\t"} {if($9 ~ "CB4856") print}' c_elegans.PRJNA13758.WS268.annotations.gff3 > WS268_Hawaiian_GFF3_lines.txt`

That should give you a file with the following features of CB4856 with respect to N2:

SNP
complex_substitution
deletion
insertion_site
substitution
tandem_duplication

You can also download the resulting file from my DropBox account here:

https://www.dropbox.com/s/rhgum37i52l0ub9/WS268_Hawaiian_GFF3_lines.txt?dl=0

Let us know if you have any questions.
"""
