### ISSUE TITLE
 Server Error: 500 at  tools/queries/run   
  Erro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6940]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/tools/queries/run">tools/queries/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools::Queries-&gt;run "Could not connect to database acedb _WS268, host: staging.localdomain"<br>Couldn't render template "tools/queries/run.tt2: file error - tools/queries/run.tt2: not found" </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to run a simple AQL query:
select l from l in class condition
via the WormBase Advanced Query page</p>

**Reported by:** Chri******* (cgro**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/queries/run">/tools/queries/run</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by tharris** [comment]
Transient issue?  Timeout?  Now working, user contacted.
