### ISSUE TITLE
  Dear Worm Base support team, We have ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6944]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Worm Base support team, We have been preparing a gene-expression micropublication for submission. We have used a wrmScarlet reporter, which is not listed in the 'reporter' field of the submission form. It seems impossible to select a reporter which is not on the list. Would it be possible to add wrmScarlet to the list of reporters?<br/>Regards,<br/>Vlad</p>

**Reported by:** Anon***** (vlad***************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by draciti** [comment]
Dear Vladislav, 

Thank you for contacting us. We will add wrmScarlet to the list of reporters. 
In the meanwhile, feel free to submit your microPublication using the attached template at contact@micropublication.org.

Do not hesitate to get in touch should you have additional questions.

We look forward to receiving your submission. 

Best wishes,

Daniela

**Comment by draciti** [comment]
wrmScarlet added to the list. Waiting for user's submission before closing

**Comment by draciti** [comment]
submission received, closing
