### ISSUE TITLE
Flickr images

### ISSUE THREAD

**Issue by draciti** [WormBase/website#6945]
Hello, 

does anyone know anything about the flickr images that WormBase was hosting a long time ago?
I got the email below from Ian Hope. If the images are mixed up on flickr we should just delete the account

Hello Daniella,
 
I hope all is well with you.
 
I received the two e-mails below about a mix up of my expression pattern data from wormbase, as presented in flickr. I am afraid that I know nothing about flickr but it looks as if the information and images have been communicated to flickr by wormbase. I also don’t know how extensive this problem is or who I ought to contact about it. Can you help?
 
Best wishes, Ian.
 
From: Kagias, Konstantinos 
Sent: Friday, February 22, 2019 7:37 PM
To: 'Ian Hope' <I.A.Hope@leeds.ac.uk>
Subject: RE: Plasmid map request
 
Dear Professor Hope,
 
Thank you for your prompt reply.
 
I don’t mean to take more of your time but I’ve noticed some discrepancies between the expression patterns presented in the following two data sources
 
https://www.flickr.com/photos/wormbase/2736080271/in/photostream/
 
https://www.wormbase.org/species/all/expr_pattern/Expr7542#021--10
 
This gene is just an example.
 
Thank you for your time again. Any input would be highly appreciated.
 
Best regards,
 
K

From: "Kagias, Konstantinos" <kkagias@fas.harvard.edu>
Date: Saturday, 23 February 2019 at 00:55
To: Ian Hope <I.A.Hope@leeds.ac.uk>
Subject: RE: Plasmid map request

I think the pictures are mixed somehow in the flickr.com source. For example the same picture is used for two different genes
 
https://www.flickr.com/photos/wormbase/2737018734/in/photostream/
https://www.wormbase.org/species/c_elegans/gene/WBGene00004078#01-9g743acfb-10
 
Because I happened to have looked into pos-1 expression myself (you kindly sent me the strain) I confirm that the Wormbase is the correct pattern. So I think the flickr.com is somehow mixed.
 
Best regards,
 
K

**Comment by draciti** [comment]
my reply to Ian: Hello Ian, 

thanks for reaching out and apologies for the trouble. The flickr images were set up at WormBase before my time. I will ask the group if anyone knows about this and will keep you posted.

Best wishes,

Daniela

**Comment by tharris** [comment]
I know about them:

http://toddharris.net/blog/2008/09/17/the-24-poor-mans-social-media-expression-pattern-database-pomasomeexppada/

I'll delete the images as this is absolutely ancient at this point.

**Comment by draciti** [comment]
ok, thanks Todd

**Comment by draciti** [comment]
Hello Ian,

The images on flickr will be deleted to avoid any confusion in the future. 
Let me know if you want me to reach out to Kostantinos.

Best wishes and apologies for the trouble.

Daniela

**Comment by draciti** [comment]
@tharris I'll let you close this issue when the images will be deleted. thanks

**Comment by vanaukenk** [comment]
@tharris - okay to close this ticket?  Thx.

**Comment by tharris** [comment]
I'm going to keep the images up on Flickr as I'd like to do something else with them.  Given that we've only gotten one query about them in over a decade, I don't think data drift is too much of a worry.  But to be sure, I placed a caveat under the account.
