### ISSUE TITLE
Expression Picture Lightbox widget data alignment

### ISSUE THREAD

**Issue by a8wright** [WormBase/website#6952]
I have a couple of examples where data isn't currently lining up between the AceDB and Datomic version of the Picture Lightbox widget. 

## Expression Pattern
https://staging.wormbase.org/rest/widget/picture/WBPicture0000003822/lightbox?content-type=application/json
On the left is production and right is what we are returning.
![expression-pattern](https://user-images.githubusercontent.com/668955/53443521-e427a280-39d9-11e9-8768-670d2416f450.png)

## External Sources
https://staging.wormbase.org/rest/widget/picture/WBPicture0000008392/lightbox?content-type=application/json
leff production right staging
*I actually cant find the information in the database that is in the production Article url

Also the generic code is returning "template-items" instead of "template_items". I added a little logic to change the dash to an underscore. Should probably look to see if we can change it to underscore in the generic function. 

![external_sources](https://user-images.githubusercontent.com/668955/53443918-c870cc00-39da-11e9-83dd-c2fab918dd1f.png)

Let me know if you need any help or notice anything that I should be changing. 

There are a few difference hre

**Comment by sibyl229** [comment]
Hi @a8wright 

For the **expression pattern** portion of the discrepancy. They are fine. Those data (the genes and reference attributes) aren't being used by the template here, because they are associated to the expr_pattern entity not the picture entity.

For the **External sources**, it should be:`template_items`

I will need to look into the other issue further.

**Comment by a8wright** [comment]
I have updated the rest endpoint to be "template_items" on develop/staging.

**Comment by sibyl229** [comment]
Hi @a8wright , I fixed the last issue you mentioned where you couldn't find the data in the database. I have a PR https://github.com/WormBase/datomic-to-catalyst/pull/196 in the d2c repo. No change in the template is necessary.

I didn't test it too thoroughly. You might need to check for regression.
