### ISSUE TITLE
  hi i want to use from this site data ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6955]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;hi<br/>i want to use from this site data to blast my data locally.<br/>but i need their taxonomy ID for use in blastn comment.<br/>could you please help me?</p>

**Reported by:** Anon***** (zein*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by chris-grove** [comment]
My email to user:
"""
The C. elegans taxon ID is 6239:

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=6239

Are you looking for something else?
"""
