### ISSUE TITLE
  Please update funding info on front p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6956]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Please update funding info on front page to:<br/>NIH NHGRI U24HG002223 <br/>we are a U24 rather than a U41 ..<br/>thanks</p><p>What were you doing? <br />&nbsp;&nbsp;wasting time</p>

**Reported by:** paul********** (pws@***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

**Comment by sibyl229** [comment]
Hi @paulwsternberg thanks for pointing out the error! The funding info is updated on staging site to "grant #U24 HG002223": https://staging.wormbase.org . The fix to production site will go out with WS269 website release.
