### ISSUE TITLE
I can see how many aa TMUE_3000012139 (397) has bu...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6957]
*Help Desk query collected when no chat operators were online. Follow up required.*

I can see how many aa TMUE_3000012139 (397) has but has that changed from when it was TMUE_s0083002300 as the original; sequence we had before the genome was published was 394

**Reported by:** Alli************ (alli*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/t_muris/gene/WBGene00291656#0-9g-3">https://wormbase.org/species/t_muris/gene/WBGene00291656#0-9g-3</a>
**Browser:** Safari 12.0.3

**Comment by epaule** [comment]
The version of T muris that we have in WormBase is an update to the one described in the 2014 genome paper (https://www.ncbi.nlm.nih.gov/pubmed/24929830). 
Where possible, the annotation was transferred from the published version to this current version (though new gene IDs were assigned). A number of gene models were updated, which will account for the change in your protein sequence. Let me know if you're having trouble with the correspondence between any other old and new gene models, I'd be happy to try to dig into any issues you have (and fix gene models if necessary). The previous assembly and annotation is still available from the WormBase ParaSite FTP site (where data from previous releases are maintained), if you need it: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/WBPS9/species/trichuris_muris/PRJEB126/
