### ISSUE TITLE
T muris location widget not showing genomic position or browser preview

### ISSUE THREAD

**Issue by fayerodgers** [WormBase/website#6958]
The location widget is not displaying the genomic position or genome browser preview for T muris genes, eg: https://wormbase.org/species/t_muris/gene/WBGene00295959#0-9g-3

**Comment by scottcain** [comment]
I don’t know why this is happening; @sibyl229 any ideas?

**Comment by sibyl229** [comment]
Hi @a8wright it appears that the API is not returning genomic position for T muris gene. Here is an example, https://staging.wormbase.org/rest/widget/gene/WBGene00295959/location?&content-type=application/json Would you mind taking a look?

**Comment by a8wright** [comment]
This one is now appearing on staging: https://staging.wormbase.org/species/t_muris/gene/WBGene00295959#9--10

**Comment by a8wright** [comment]
This one is now appearing on staging: https://staging.wormbase.org/species/t_muris/gene/WBGene00295959#9--10

And should be fixed on production once the 1day cache clears

**Comment by sibyl229** [comment]
Hi @fayerodgers , I believe @a8wright has fixed the genomic location and jbrowse issue for T muris. It's ready for testing on staging right now. Production should be automatically updated within 24 hours when the old cache expires.

Please feel free to close the issue if you think the problem fixed.

**Comment by fayerodgers** [comment]
Looks good to me, thanks guys.
