### ISSUE TITLE
Hi,
I am trying to edit my profile so that I can f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6960]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
I am trying to edit my profile so that I can fill out that I work in the lab of Hannes Lans (wormbase HAL), but I can't find how to do so.
Best, Karen

**Reported by:** Kare********** (k.th*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/me#2-0-10">https://www.wormbase.org/me#2-0-10</a>
**Browser:** Firefox 65.0

**Comment by chris-grove** [comment]
My email to user:
"""
You can use one or both of the following web forms to submit this information, both discoverable on our "Submit Data" page (linkable from the WormBase homepage):

https://wormbase.org/about/userguide/submit_data#01--10

The first form is for updating personal contact information:

https://wormbase.org/submissions/person.cgi

Note that you can query for your name as "Karen Thijssen" and you will be directed to your personal form:

https://wormbase.org/submissions/person.cgi?action=Query&number=two1519

There, you can add Hannes Lans in the field "Approved cgc lab code" (typing "Lans" will bring up his entry in the drop down). Click "Submit" when you're done making edits. We can also make the changes ourselves at WormBase if you'd prefer.

The second form is for updating information about your intellectual lineage:

https://wormbase.org/submissions/person_lineage.cgi

if you're interested.

Let us know if you have any other questions.
"""
