### ISSUE TITLE
Please create strains in WBPaper00056079

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#6961]
@Paul-Davis: Please create the strains in this paper, can be found under the heading 'C. elegans strains' in 'Materials and Methods'.

**Comment by Paul-Davis** [comment]
Strain UA198
Strain UA311
Strain UA350
Strain UA351
Strain UA352
Strain UA353
Strain UA354
Strain UA355
Strain UA356
Strain UA357
Strain UA358
Strain UA359
Strain UA360
Strain UA364
Strain UA365
Strain UA366

Created for WS271
