### ISSUE TITLE
How do you find the number in introns and exons wh...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6963]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do you find the number in introns and exons when looking at genomic position?

**Reported by:** Trac* (pj70*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00004397#0-9g-3-0">https://wormbase.org/species/c_elegans/gene/WBGene00004397#0-9g-3-0</a>
**Browser:** Safari 12.0.3

**Comment by rankishore** [comment]
My reply to User: 'I am not sure what exactly you are looking for, but if you click on a region of interest it takes you to a view that has a lot of information, in this detailed view, if you hover your mouse over the bar with the numbers right above the gene model, it gives you the exact position of where you are in that genomic region.'

Closing for now unless User writes back with further questions/clarifications
