### ISSUE TITLE
acedb patch for WS270 - DOTerms

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6964]
could you load: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS270/acedb/PATCHES/do_term_patch.ace

into the WS270 acedb database?

thanks,
M

**Comment by sibyl229** [comment]
Hi @tharris Hinxton asked for an ACeDB patch for WS270. Could you help me with that?

**Comment by tharris** [comment]
Loaded.

**Comment by vanaukenk** [comment]
@epaule @tharris 
Okay to close this ticket?
Thx.
