### ISSUE TITLE
  I have a doubt about genome engineeri...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6965]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a doubt about genome engineering nomenclature. I have generated different missense mutations in the same gene (sftb-1) by CRISPR/Cas9, so that I have 2 different strains with the following genotypes:<br/>1) sftb-1(cer1[K718E] III<br/>2) sftb-1(cer2[R643C] III<br/>I then injected the R643C mutation on the cer7[K718E] background to generate a double mutant strain. In that case, I wonder if the new allele nomenclature would be<br/>a) sftb-1(cer1[K718E];cer3[R643C]) III<br/>or b) sftb-1(cer3[K718E;R643C]) III <br/>I believe that because the new modification is within the same gene, the option B would be the correct one, but I want to make sure that the nomenclature is appropriate.<br/>Thanks for your help.</p>

**Reported by:** Xèni* (xser***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by rankishore** [comment]
Replied to User: 'Thanks for your e-mail.  I believe you are on the right track with option b.  However please do consult the ’Nomenclature’ page in WB at https://wormbase.org/about/userguide/nomenclature#mb30c71e5lk6gaj8dh29fi4--10, where there is a special section on ‘Genome Engineering’, also listed in the left-hand vertical bar. I would consult this section.  

I’m also cc-ing Dr. Tim Schedl on this e-mail, in case he has some advice for you.
