### ISSUE TITLE
How to retrieve list of genes with highest ChIP peaks for a transcription factor?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6968]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_email): Is there a way to retreat all genes with the highest GFP ChIP score in hypothetical promotor region for a particular Trafscription factor (modEncode data)</br>Chris: We don't have a ready-to-use tool that can extract this, but it may be possible to download the GFP-ChIP track data from JBrowse and parse it for peaks above a threshold which could then be cross referenced to a GFF file</br>Chris: Let me take a look at the data and check feasibility</br>Chris: Do you have a particular transcription factor in mind?</br>visitor_name (visitor_email): zip-2 Thanks!</br>Chris: OK</br>Chris: OK, I'm sure this is something we can extract but I need to discuss with our genome browser developer about how best to get the ZIP-2 GFP-ChIP track data and then make peak calls. This is a common use case, so we should come up with a general solution</br>Chris: Once we finish this chat, we will both get an email of the transcript of this chat. Then I can reply to you and forward to the appropriate people to figure out how we can get this to you</br>visitor_name (visitor_email): It would be great! Thank you!</br>Chris: Is that OK?</br>Chris: OK great</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): No, thanks!</br>Chris: OK, sounds good. I'll be in touch.</br>visitor_name (visitor_email): See you

**Reported by:** Mari** (knia***************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,ZIP-2 Combined (GFP ChIP)&amp;loc=X:11518086..11525025&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,ZIP-2 Combined (GFP ChIP)&amp;loc=X:11518086..11525025&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Firefox 65.0

**Comment by chris-grove** [comment]
My follow up email to user after input from @gw3 
"""
To get what you need we'll use the command line. It looks like you are (or at least were during our chat) using a Mac operating system. In that case you can download the file, unzip it, and place it on your Desktop. Then, open a Terminal window and type/paste in the following three commands (one at a time):

`cd Desktop`

`grep ZIP-2 c_elegans.PRJNA13758.WS268.annotations.gff3 > ZIP-2_WS268_GFF3_lines.txt`

`awk 'BEGIN {FS="\t";OFS="\t"} {if($3 == "gene") print}' c_elegans.PRJNA13758.WS268.annotations.gff3 > WS268_GFF3_gene_lines.txt`

You should then have two files on your Desktop:

1) ZIP-2_WS268_GFF3_lines.txt

This file will list the locations (chromosome in column 1, start position in column 4, end position in column 5) of all ZIP-2 binding sites. I see 763 binding site lines in my file.

2) WS268_GFF3_gene_lines.txt

This will list the locations (as above) of all genes (cloned and uncloned but mapped). This file should have 74,674 lines.

Both of those files you should be able to open in Excel. Then you can cross check the ZIP-2 binding sites with the gene locations to match them up. Alternatively, you can create single file listing the binding sites in line with the respective genes (and you can perform a search within the file for lines containing "ZIP-2" and see which gene lines they are adjacent to. To do this run the following on the command line:

`awk 'BEGIN {FS="\t";OFS="\t"} {if(($3 == "gene") || ($9 ~ "ZIP-2")) print}' c_elegans.PRJNA13758.WS268.annotations.gff3 > WS268_GFF3_ZIP-2_and_gene_lines.txt`

Then you'll have the file "WS268_GFF3_ZIP-2_and_gene_lines.txt" and you can open that in Excel.

Let us know if you have any questions.
"""
