### ISSUE TITLE
  I would like to perform GO annotation...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6971]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to perform GO annotation on a set of proteins. I am interested in biological functions. Is there a method to do this with a batch or local?</p><p>What were you doing? <br />&nbsp;&nbsp;I am responding to a reviewer comment to add functional annotations to our new Wb genome assembly. Specifically testing for enrichment of biological functions in comparison to our selection scans.</p>

**Reported by:** scot* (ssma**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by vanaukenk** [comment]
Hi Scott,



Thanks for writing to WormBase.



It would be great to get more information on exactly what types of GO annotations you'd like to submit.


I can work with you on how to do this and what file format would be best.


Please feel free to email me directly and we can start working out the details.


Best,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
Closing for now.  User was put in touch with the PANTHER team to perform enrichment analysis using the reference Wuchereria bancrofti proteome.
