### ISSUE TITLE
I'd like tp compare promoter regions of genes from...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6977]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'd like tp compare promoter regions of genes from WS228 with the current version, to see if there have been changes to sequence features from a previous publication. Any pointers would be greatly appreciated.
Thanks!

**Reported by:** Bria******** (bria******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=II:7496408..7500308&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=II:7496408..7500308&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Chrome 72.0.3626.119

**Comment by epaule** [comment]
if you have a look here: ftp://ftp.wormbase.org/pub/wormbase/releases/ you can find an archive of WormBase releases, including their genomic sequence and annotation.
The WS228 assembly was WBCel215, so some coordinates will have changed in WS235 and there are probably a lot more genomic features annotated since then.

**Comment by chris-grove** [comment]
My reply:
"""
In addition to what Michael said, you may be specifically interested in the intergenic sequence files for each release. For WS228, there is this file:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS228/species/c_elegans/c_elegans.WS228.intergenic_sequences.fa.gz

and for the current release there is:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS268.intergenic_sequences.fa.gz

assuming you're looking for C. elegans sequence.
"""
