### ISSUE TITLE
I want to know the difference between these 2 file...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6978]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to know the difference between these 2 files available on ftp server: c_elegans.PRJNA13758.WS264.geneIDs and c_elegans.PRJNA13758.WS264.geneOtherIDs

**Reported by:** sana**** (sana*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Firefox 65.0

**Comment by epaule** [comment]
the geneid file contains only the primary identifiers of the gene: WBGeneID , CGC names and the clone based sequence name.
the other_id file in addition contains the collected other ids connected to the respective gene (historical ids, non-approved names, protein identifiers, etc)
