### ISSUE TITLE
  ...create a new login/account, withou...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6979]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;...create a new login/account, without using Google or Facebook to sign in? When I click “login” from the main page, my options are to enter my email and password, or “sign-in with Google or Facebook”. I do not want to sign-in with Google or FB. </p>

**Reported by:** Tiff*** (Tiff*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/72.0.3626.101 Mobile/15E148 Safari/605.1

**Comment by epaule** [comment]
we did have a while a go a google/fb less account system. But I don't think it still works. But maybe someone from the webteam will chime in, as they know more about it.

**Comment by chris-grove** [comment]
From @sibyl229 to user:
"""
Sorry about the late reply. If you prefer email/password based login to Sign-in with Google, I can create an account for you. What email address would you like to use?
"""
