### ISSUE TITLE
  Hi,  I notice magu-2 gene structure i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6980]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I notice magu-2 gene structure is updated to merge with a gene that was used to be a separate gene 5' to magu-2.  what is the basis of this merge?  as the merged gene seems to be not consistent with the ortholog family. <br/>Yishi Jin</p>

**Reported by:** Anon***** (yiji**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by Paul-Davis** [comment]
Hi, Thank you for contacting WormBase,

This gene was merged with the upstream gene based on the RNASeq splice 
data suggesting that this is a single locus.

"[180913 gw3] The set of genes: WBGene00006467 WBGene00015276 has been 
merged and this structure is based on the RNASeq data."

The annotation has also been updated in C. briggsae so it is likely that 
the previous C. elegans annotation was used to inform the gene 
prediction in the other Caenorhabditis species.

Hope this helps.

Paul



On 12/03/2019 16:52, no-reply@wormbase.org wrote:
> Question:
>
>   Hi,
> I notice magu-2 gene structure is updated to merge with a gene that 
> was used to be a separate gene 5' to magu-2. what is the basis of this 
> merge? as the merged gene seems to be not consistent with the ortholog 
> family.
> Yishi Jin
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6980. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6980>.
>
> Reported by: yijin@ucsd.edu
> 12 Mar 19 16:52
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 
> Firefox/65.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
