### ISSUE TITLE
  I cannot open blast tool. If I click ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6981]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I cannot open blast tool. If I click the blast icon, it will automatically lead to Tools page. </p><p>What were you doing? <br />&nbsp;&nbsp;Blast</p>

**Reported by:** Hann****** (hshi*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; LCTE; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Confirmed. BLAST/BLAT page is throwing a "404 Not Found" error message

**Comment by tharris** [comment]
Fixed.  User contacted.
