### ISSUE TITLE
Variation Other_name in the website search

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6982]
Hi,

Would it be possible to check that Other_name for Variation is being indexed by the website search pls

Possibly Gene Other_name as well.

If they aren't indexed then this might be unintended as we store names from publications so that Genes and Variations can be found using the synonym used in the 3rd party resource/Publication.

Thanks

Paul

**Comment by sibyl229** [comment]
Hi @Paul-Davis , search currently indexes the Other_name and the Sequence_name. I can also index the Molecular_name too, is that what are trying to look up a gene by? 

For Variation, I will index the Other_name as you asked.

**Comment by sibyl229** [comment]
Hi @Paul-Davis Variation is now searchable on staging site by Other_name in addition to Public_name: https://staging.wormbase.org/search/all/cb19669

And Gene is searchable by Public_name, Sequence_name, Molecular_name, and Other_name. Could you take a look please?

**Comment by sibyl229** [comment]
Fix was deployed to production in WS270. Closing. Please feel free to repo if there is a problem.
