### ISSUE TITLE
  Hi! I'm having lots of trouble loadin...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6984]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi! I'm having lots of trouble loading the BLAST/BLAT function on your website. It seems as though most of the other tool will work and load but not this particular one (the only one I currently need). Is there a flash I need to have installed or some tips as to which browser to use?<br/>Thank you!<br/>visitor_name</p>

**Reported by:** Jeri*** (jeri**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by tharris** [comment]
Problem addressed; user contacted.
