### ISSUE TITLE
  Tree view is not working. ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6985]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Tree view is not working.</p>

**Reported by:** Anon***** (jae.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by tharris** [comment]
Fixed and anonymous wormbase staffer contacted.
