### ISSUE TITLE
  can not find sequence of varivation. ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6990]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;can not find sequence of varivation.</p>

**Reported by:** zl H* (2751************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by Paul-Davis** [comment]
Dear zl Hu,

I would be happy to help with your request if you could provide 
additional information about which Variation you are interested in.

Kind regards

Paul


On 15/03/2019 05:50, no-reply@wormbase.org wrote:
> Feature Request
>
>   can not find sequence of varivation.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6990. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6990>.
>
> Reported by: zl Hu (275180876@qq.com)
> 15 Mar 19 05:50
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
