### ISSUE TITLE
  Please make it easier to select a par...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6995]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Please make it easier to select a particular region on the displayed genomic map on JBrowse and then dump as FASTA/see the raw DNA sequence.  It is much too difficult/circuitous compared to GBrowse, which allows the user to simply highlight and have the option to dump as FASTA.  This is why I infinitely prefer GBrowse despite it being "legacy."</p>

**Reported by:** Kath********* (kl27***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by scottcain** [comment]
My reply to the user:

Making it easier to download sequence is on my list of development activities, believe me!  In the meantime, would you mind taking a look at this document I wrote and plan on making into a blog post at WormBase.  In some circumstances, I find getting sequence for some ranges to be easier/better in JBrowse versus GBrowse.  Please let me know what you think:

(google doc url removed)

Thanks,
Scott
