### ISSUE TITLE
I am writing to you in regard to some information ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6996]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am writing to you in regard to some information on the unc-54  gene ontology page which attributes pharyngeal pumping as a function that unc-54 affects. This paper: WBPaper00005299 is listed as the source for this attribution. From reading the paper it seems to me that a mistake was made in attributing any role of unc-54 in the pharynx.  A yeast two hybrid expt showed that UNC-54 and ITR-1 interact as do MYO-1 and ITR-1. Further expts confirmed both these interactions. The authors then went on to do further expts between MYO-1 and ITR-1 proteins to show that if you disrupt their interaction in vivo you can affect the worm's ability to do pharyngeal pumping. But UNC-54 is not involved in this expt. When one looks at where unc-54 is expressed in the worm, it's not in the pharynx and one or two of the figure legends of the figures you put up  in the expression tab specifically say, "note the absence of expression in the pharynx". I have been trusting information on WormBase for many years but this seems to be an attribution error. If I can help add to the trustworthiness of the site, well I am glad to help. If I am in error, please let me know.

**Reported by:** Jenn********** (jkle**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/paper/WBPaper00005299#0--10">https://wormbase.org/resources/paper/WBPaper00005299#0--10</a>
**Browser:** Safari 12.0.2

**Comment by vanaukenk** [comment]
Dear Jennifer,

Thank you very much for your feedback on the unc-54 annotations.  We'll definitely review the paper and make any necessary updates.

The revised information will then be included in the WS272 WormBase release.

Best,
--Kimberly Van Auken
