### ISSUE TITLE
  Hi, I was wondering if there was an e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6998]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I was wondering if there was an easy way (that does not require any code) to identify genes that are highly enriched in males.  For example, I would like to see all the genes that have a similar pattern of FPKM expression data from modENCODE as sdz-6.  Thanks for any suggestions!</p>

**Reported by:** Anon***** (dark******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
I would recommend taking a look at our expression cluster data, for example:

https://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00050928:male-mating_upregulated#034512--10

Here's a list of expression clusters that may be of interest to you:

WBPaper00048690:male-Z1-Z4_enriched
WBPaper00048690:male-Z1-Z4-daughter_enriched
WBPaper00026629:L2_male_enriched
WBPaper00026629:L3_male_enriched
WBPaper00026629:L4_male_enriched
WBPaper00048690:gonad-male-biased
WBPaper00041323:male-associated
WBPaper00050231:male_enriched
cgc4489_male_enriched_neuronal_genes
cgc4489_male_enriched_transcription_factors
WBPaper00044535:male_upregulated
[cgc6390]:male_germline-enriched
[cgc6390]:male_sex-enriched
[cgc6390]:male_soma-enriched

Each expression cluster page (like the one linked above), will have an explanation of the experiment, a list of genes, and a reference.

In addition you may want to try querying for sdz-6 in our SPELL tool:

https://spell.wormbase.org

which will return sets of genes most similar in expression profile to your query gene.

I hope that helps.
"""

**Comment by chris-grove** [comment]
My follow up:
"""
Apologies, I meant instead to suggest this expression cluster page:

https://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00050231:male_enriched#034512--10

The previous link is not quite relevant.
"""
