### ISSUE TITLE
Dear CGC,

I would like to know N2 strain which I ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6999]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear CGC,

I would like to know N2 strain which I have ordered previously can I get  reference  paper or if you have any data regarding normal life span in different temperature (  such as 20 or 25 degree Celsius in Lab )  .

Thank you .

**Reported by:** shar*** (shar**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Safari 12.0.1

**Comment by chris-grove** [comment]
My email to user:
"""
You have reached the WormBase help desk via the email address help@wormbase.org. The Caenorhabditis Genetics Center (CGC) is a separate organization, although we do work closely with them. Here is their website:

https://cgc.umn.edu/

Their contact email address is cgc@umn.edu

As for a reference for the N2 strain, I'm not sure which paper would be the best. One of the earliest mentions of that strain was the 1974 Genetics paper by Sydney Brenner:

https://www.ncbi.nlm.nih.gov/pubmed/4366476

As for normal life span, there are hundreds (if not thousands) of papers referring to C. elegans and aging; try searching pubmed with the following:

("Caenorhabditis elegans"[Mesh]) AND "Aging"[Mesh] 

and look for reviews. You may also be interested in this WormBook chapter:

http://www.wormbook.org/chapters/www_measurementanalysisCelegans/measurementanalysisCelegans.html

as well as our WormBase "Aging" process page:

https://wormbase.org/resources/wbprocess/WBbiopr:00000001#079--10

In my experience (I used to study aging in C. elegans), the typical N2 (wild type) life span at 20 degrees Celsius is about 16-18 days post-L4 larval stage (adult life span) or about 19-21 days post fertilization (entire life span), but I would recommend checking the literature yourself to confirm.

I hope that helps.
"""
