### ISSUE TITLE
Hello! I would like to register as a new user (to ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7001]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello! I would like to register as a new user (to run queries), but I can't seem to find the "Register" or "New user" button, only the login (which tells me that I don't have an account...)

Thanks for your help

**Reported by:** Chlo* (chlo***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools#0--10">https://wormbase.org/tools#0--10</a>
**Browser:** Firefox 65.0

**Comment by vanaukenk** [comment]
Dear Chloe,

Thanks for writing to WormBase, and our apologies for the delayed response.

WormBase uses Google or Facebook to authenticate users, so if you have an account with either of those two sites, you may use that to login.

At this time, WormBase is not supporting its own login or account creation system.

Please feel free to get in touch if you have any questions about using Google or Facebook to login to WormBase.

Best,
--Kimberly Van Auken
