### ISSUE TITLE
  Hi,  I found transcript/exons which e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7004]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I found transcript/exons which extend outside their parent gene. <br/>Fasta:       c_elegans.PRJNA13758.WS269.genomic.fa.gz <br/>GFF3 file: c_elegans.PRJNA13758.WS269.annotations.gff3.gz<br/>Gene: I	WormBase	gene	969089	976503	.	-	.	ID=Gene:WBGene00018788;Name=WBGene00018788;locus=shc-1;sequence_name=F54A5.3;biotype=protein_coding;so_term_name=protein_coding_gene;curie=WB:WBGene00018788;Alias=shc-1,F54A5.3<br/>transcript: I	WormBase	nc_primary_transcript	969680	976550	.	-	.	ID=Transcript:F54A5.3e;Parent=Gene:WBGene00018788;Name=F54A5.3e<br/>exon: I	WormBase	exon	972987	976550	.	-	.	Parent=Transcript:F54A5.3g<br/>I am wondering if this is the expected annotation?! <br/>thanks :) <br/>visitor_name<br/>Novocraft Technologies</p><p>What were you doing? <br />&nbsp;&nbsp;I was running our new rna-seq aligner novoSplice, 
@zingo:novoSplice$ bin/novoSplice --fasta /home/zingo/Data/cElegans/ref/wormBase/c_elegans.PRJNA13758.WS269.genomic.fa.gz --gff /home/zingo/Data/cElegans/ref/wormBase/c_elegans.PRJNA13758.WS269.annotations.gff3.gz  -1 /home/zingo/Data/read1.fastq -2 /home/zingo/Data/read2.fastq -o ./ > genes3.txt
[22/03/2019 16:41:22] [Info]     Parsing FASTA file 
[22/03/2019 16:41:22] [Info]     Parsing GFF3 file
[22/03/2019 16:41:22] [Error]    Exon with ParentID=Transcript:F54A5.3g , has end=976550 bigger than its gene's end, gene_id=Gene:WBGene00018788. Exit</p>

**Reported by:** Fade********** (fade***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by epaule** [comment]
fixed in https://github.com/WormBase/wormbase-pipeline/commit/4b3eef8b1a6e224be4bed82d1a401aa2a2d67b0c

**Comment by gw3** [comment]
Fadel,

Thank you for finding this problem in our GFF file.

It is an error.

The 'gene' region should be slightly longer so that it includes the 
'nc_primary_transcript'.

We will fix this in future releases of WormBase.


Gary Williams
WormBase

**Comment by Paul-Davis** [comment]
Fix confirmed for WS271
