### ISSUE TITLE
  Im looking for C. Elegans, variant E5...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7005]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Im looking for C. Elegans, variant E53. Im specifically looking for the mutation is dominant or recessive. Can you tell me where I can find this informatio. Thanks!</p>

**Reported by:** Anon***** (twil*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Linux; Android 7.0; LGMP260) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Mobile Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thanks for contacting WormBase.

E53 or e53 as we have it in WormBase (you need to confirm this is the 
correct variant) is WBVar00142936 and can be found here:

https://wormbase.org/species/c_elegans/variation/WBVar00142936#02-4516-10

This page contains all of the available details we have on this variant. 
There are a number of linked papers that might give you the additional 
information you require.

I hope this helps.

Paul







On 22/03/2019 14:09, no-reply@wormbase.org wrote:
> Question:
>
>   Im looking for C. Elegans, variant E53. Im specifically looking for 
> the mutation is dominant or recessive. Can you tell me where I can 
> find this informatio. Thanks!
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7005. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7005>.
>
> Reported by: twilliams0935@yahoo.com
> 22 Mar 19 14:09
>
> Mozilla/5.0 (Linux; Android 7.0; LGMP260) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/73.0.3683.75 Mobile Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
Just to add to Paul's comments, if you're looking for whether an allele or mutation is dominant or recessive, you will want to look at the phenotype annotations, for example in the Phenotypes widget on the allele page:

https://wormbase.org/species/c_elegans/variation/WBVar00142936#0-7-10

I don't see annotations to dominant or recessive, but I do see e53 annotated as a null mutant which would argue that it is likely a recessive mutation.

I hope that helps.
