### ISSUE TITLE
  the following paper should be referen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7006]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;the following paper should be referenced for C44C10.4:<br/>PLoS Genet. 2017 Mar 16;13(3):e1006614. doi: 10.1371/journal.pgen.1006614. eCollection 2017 Mar.<br/>An SMC-like protein binds and regulates Caenorhabditis elegans condensins.<br/>Chao LF1, Singh M2, Thompson J2, Yates JR 3rd2, Hagstrom KA1,3.</p>

**Reported by:** Judi*********** (jly@************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Judith,

Thanks very much for the feedback.

I've updated the gene-paper associations in our curation database, and the new information will be included in WormBase release, WS272.  The full WormBase release schedule is available here:

https://www.wormbase.org/about/release_schedule

Best,
--Kimberly Van Auken
