### ISSUE TITLE
  WormMine is not working now. (pacific...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7007]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormMine is not working now. (pacific time 10:47 AM)</p>

**Reported by:** Jae (jae.****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by nuin** [comment]
System is back up.
