### ISSUE TITLE
  May I ask how I send the strains to C...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7008]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;May I ask how I send the strains to CGC? Can you send me an address and things I should do to make it happen? </p>

**Reported by:** Anon***** (sisi**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thanks for contacting WormBase.

The CGC handles the submission process, but one thing you can do before 
contacting them is to get your lab registered with WormBase where we can 
assign a 2/3 letter code to your lab. I have CC'd Tim Schedl who can 
provide you with the most up to date information on code availability.

Once you have a lab code you can register with the CGC here
https://cgc.umn.edu/register

and then start the Donation process:
https://cgc.umn.edu/login?continue=https%3A%2F%2Fcgc.umn.edu%2Fstrain%2Fdonate

The lad code is important as this is used to name the trains you donate.

I hope this helps

Paul



On 23/03/2019 19:47, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   May I ask how I send the strains to CGC? Can you send me an address 
> and things I should do to make it happen?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7008. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7008>.
>
> Reported by: sisi.yang@yale.edu
> 23 Mar 19 19:47
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
