### ISSUE TITLE
  Hi WormBase devs, It appears that the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7009]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi WormBase devs,<br/>It appears that the WS269 release files available on the FTP server are malformed. For reference, the WS268 files look good though. Here are some example links:<br/>Valid:<br/>ftp://ftp.wormbase.org//pub/wormbase/releases/WS268/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS268.geneIDs.txt.gz<br/>Malformed:<br/>ftp://ftp.wormbase.org//pub/wormbase/releases/WS269/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS269.geneIDs.txt.gz<br/>Would it be possible to regenerate the WS269 flat files?<br/>Thanks!<br/>Mike</p>

**Reported by:** Mich************** (mike***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by mjsteinbaugh** [comment]
I came across this issue when using my wormbase R package:
https://github.com/acidgenomics/wormbase

**Comment by epaule** [comment]
Hi Michael,

I don't see any malformed entries in that file.
But it looks like some non N2 strain genes went into the version for WS269
(the ones with xxx_pilion_xxx are from teh VC2010 strain).
The following WS270 version has a cleaner file.
Technically each of the VC2010 genes should have the full allotment of REST
endpoints, so I would be interested in what error the R package throws.

best regards,

Michael Paulini

**Comment by epaule** [comment]
that would be great.

Implementation-wise, I would rather only include lines with WBGeneXXX than
exclude the pilion ones, as the next mistake will probably have different
ids.

**Comment by mjsteinbaugh** [comment]
@epaule I added additional checks to look for `WBGene` annotations before returning data frames to the user in R. This should be fixed in v0.2.7 of my R package: https://github.com/acidgenomics/wormbase
