### ISSUE TITLE
Hi there,

I am having trouble using the biomart f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7010]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there,

I am having trouble using the biomart feature as it does not have any option available for uploading a gene list wit WB ID's. Strangley enough the wormbase ID format is not even one of the options in the bioMART. I suspect there is something very simple I am missing here so I figured I reach out for some help.

With best regards

**Reported by:** Moha**** (pata***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 72.0.3626.121

**Comment by WenChenWormBase** [comment]
Dear Mohammad,

What are you trying to find by uploading a list of genes? You may try
WormBase SimpleMine to see if it can provide what you need.
https://wormbase.org/tools/mine/simplemine.cgi


Wen Chen
Curator, WormBase

On Mon, Mar 25, 2019 at 11:19 AM <no-reply@wormbase.org> wrote:

> offline chat Hi there, I am having trouble using the biomart feature as it
> does not have any option available for uploading a gene list wit WB ID's.
> Strangley enough the wormbase ID format is not even one of the options in
> the bioMART. I suspect there is something very simple I am missing here so
> I figured I reach out for some help. With best regards
>
> Submitted From:
>   https://www.wormbase.org/#012-34-5 https://www.wormbase.org/#012-34-5
> <http://www.wormbase.org/https://www.wormbase.org/#012-34-5>
>
> This issue has been assigned ticket number: #7010. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/7010>.
>
> Reported by: Mohammad (patashnak@gmail.com)
> 25 Mar 19 18:19
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen
Curator, WormBase

**Comment by chris-grove** [comment]
My email to suer:
"""
Are you using the WormBase ParaSite BioMart?

http://parasite.wormbase.org/biomart/martview

To enter WBGene IDs in the Query Filter you would need to specify the ID type as "Gene stable ID(s)", as in this query:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.production_name_1010|wbps_gene.default.feature_page.wbps_gene_id|wbps_gene.default.feature_page.wbps_transcript_id|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.gene_biotype&FILTERS=wbps_gene.default.naive_filters.wbps_gene_id."WBGene00000001,WBGene00000002,WBGene00000003,WBGene00000004,WBGene00000005,WBGene00000006,WBGene00000007"&VISIBLEPANEL=resultspanel

Let us know if that doesn't work for you or if it still isn't clear.
"""
