### ISSUE TITLE
Hi, after selecting a particular gene region on JB...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7011]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, after selecting a particular gene region on JBrowse, how can I perform "dump selection as FASTA" or "download decorated FASTA file" like in the legacy genome browser (which I am really used to)? Thank you!

**Reported by:** Kian***** (kian****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse-simple/?data=data/c_elegans_PRJNA13758&amp;loc=V:16233438..16235187&amp;tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;highlight=">https://wormbase.org/tools/genome/jbrowse-simple/?data=data/c_elegans_PRJNA13758&amp;loc=V:16233438..16235187&amp;tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;highlight=</a>
**Browser:** Safari 12.0.3

**Comment by scottcain** [comment]
Reply via email:

Questions of this type come up fairly often.  While I'm working on making it better, I wrote a WormBase blog post about it:

http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

Please let me know if this helps and if you have any questions or feedback,
Scott
