### ISSUE TITLE
  How do I download the gened ids of la...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7012]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I download the gened ids of latest release i.e. WS270 of c.elegans?</p>

**Reported by:** Troy****** (troy****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by vanaukenk** [comment]
Dear Troyee,


Thanks for writing to WormBase.


You can download the gene ids for WormBase release WS270 from our ftp site:


ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/geneIDs/

Please let us know if you need any additional assistance.


Best,

--Kimberly Van Auken
