### ISSUE TITLE
Allele ev763 should connect to gene pvf-1

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7013]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Gautam, how can I help?</br>visitor_name (visitor_email): Just wanted to say that for the pvf-1 gene atleast one allele does exist (ev763) which is discussed in 
PMID:24004945.  I don't know to whom I should send such information.</br>visitor_name (visitor_email): Thanks!</br>Chris: OK, thanks for the info. It looks like the sequence details of allele ev763 are still pending curation, although we have mapped the allele to bar-1 for some reason. Our variation/sequence curator will take a look and get back to you once that is updated.</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): I was wondering whether on the main gene page alleles for a gene are mentioned only after their molecular breakpoints or single base changes are known. Is that the reason that the ev763 allele is not listed but tm6000 is listed?</br>visitor_name (visitor_email): or maybe I missed it?</br>Chris: The alleles for a gene should show up as soon as the allele is connected to that gene</br>Chris: For some reason it seems that ev763 was erroneously connected to bar-1 instead of pvf-1, and so that is something we'll need to fix. The connection of an allele to a gene could be sequence based or mapping based</br>visitor_name (visitor_email): OK.Thanks again!

**Reported by:** Gaut****** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/paper/WBPaper00044133#0--10">https://wormbase.org/resources/paper/WBPaper00044133#0--10</a>
**Browser:** Firefox 60.0

**Comment by chris-grove** [comment]
My email response:
"""
Hi @Paul-Davis ,

It seems that the allele ev763 was erroneously connected to the gene bar-1:

https://wormbase.org/species/c_elegans/variation/WBVar00145285#0569--10

despite the declared association to the gene pvf-1, as per PMID:24004945 (WBPaper00044133):

https://wormbase.org/resources/paper/WBPaper00044133#034--10

Could you take a look and get back to Gautam (CC'ed) once updated?

Thanks!
"""

**Comment by chris-grove** [comment]
From @Paul-Davis 
"""
This allele seems to have been deposited with WormBase as far back as 2003/2004 and the bar-1 gene connected, I can only presume that this was not the intended connection. As the allele is still "Pending Curation" this is purely a manual connection based on the information that was given at the time. The depositing lab and the authors or the publication match up, so I will update the gene connection for WS271 which I am building at the moment.

I will curate this variant as there seems to be enough in the paper to get the correct deleted sequence.

Thanks for pointing this out.
"""
