### ISSUE TITLE
I found an error on the pax-1 gene page - it is li...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7014]
*Help Desk query collected when no chat operators were online. Follow up required.*

I found an error on the pax-1 gene page - it is listed as expressed in V1L and V2L based on description from Rasmussen et al 2013, but they were using "v1" to refer to vpi1, not the V1 seam cell

**Reported by:** John******* (jmur************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00003937#0-936g1c4edfb57-10">https://www.wormbase.org/species/c_elegans/gene/WBGene00003937#0-936g1c4edfb57-10</a>
**Browser:** Chrome 72.0.3626.121

**Comment by draciti** [comment]
Dear John,

Thanks for reporting this.
We have now corrected the annotation, which will appear in the next WormBase release.

You can find the release schedule here: https://wormbase.org/about/release_schedule#01--10

Best wishes,

Daniela
