### ISSUE TITLE
gk794 Molecular Details oddity

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7015]
Hi webteam,

It looks like the molecular deatils widget is doing something funny for complex insertion/deletion variations.

![gk794](https://user-images.githubusercontent.com/717707/55251263-036b5700-5248-11e9-8aed-4e16a444bc1b.png)

At the top we can see a consensus taken from a users reads compared to the flanking sequences we have in the database for mapping the variant onto the genome......complete agreement.

The middle section shows the +ve  and -ve display in the "mutant gk794, with 500bp flanks, shown on (+/-) strand" section of the Molecular details widget. Here you can see the correct insert sequence with the reverse flanks in yellow and the reverse complement insert with the correct flanking sequences. It looks like the web code is reverse complementing the stored insert sequence  
Finally at the bottom you can see the stored flanks for mapping with the correct insert as the user reported.

I'm not 100% sure what it's doing as the data looks correct but flipping it either way gives correct flanks but incorrect insert or correct insert with bad flanks.

Paul

**Comment by a8wright** [comment]
Interesting. Thank you for finding this and adding all the details. There must be a part of the logic in the code that is slightly off for this circumstance. I will fix this as soon as possible.

**Comment by a8wright** [comment]
@Paul-Davis This is now fixed on staging. It wasn't an error in my logic it was just a check in the code that wasn't working. 

Please let me know if it looks correct to you. If it does look good let me know if you think there is a reason for pushing this to production before the next release. Right now the repo is a little in flux making it a harder to deploy right away. If there is minimal need to get this out right away I will just wait for it to be in production with the next release.

**Comment by Paul-Davis** [comment]
Looks good to me @a8wright 👍
