### ISSUE TITLE
Hi there, just trying to access some of the downlo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7016]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there, just trying to access some of the downloads on the public FTP. Is the public FTP site down at the moment? I have tried different browsers and now computers. Thanks a lot for your help.  Kind Regards, visitor_name

**Reported by:** Emma (emma**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide#3--10">https://www.wormbase.org/about/userguide#3--10</a>
**Browser:** Safari 12.0.3

**Comment by tharris** [comment]
Confirmed that the FTP site is working.  Tried to contact the user but they entered their email incorrectly.

--

Hi Emma - 

I’m not noticing anything amiss and have been able to connect to the FTP site from multiple locations across the globe, via both the command line and a browser.

I do see someone from your location logging in successfully so it looks like perhaps it’s a browser issue?  Maybe try the command line?

**Comment by chris-grove** [comment]
@tharris 
I'm assuming this issue is resolved. Please reopen if necessary
