### ISSUE TITLE
  Dear WormBase Team, since you launche...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7017]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase Team,<br/>since you launched the new version of the GenomeBrowser (which I really like!) I am wondering how you can download fasta files of the displayed sequence. With the old version there was this drop-down list where you could choose "Download Decorated FASTA File". With the new JBrowse version I cannot find this feature anywhere. <br/>I really appreciate your effort on WormBase - keep up the good work!<br/>Cheers<br/>visitor_name</p>

**Reported by:** Barb*** (bpee**********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by vanaukenk** [comment]
Dear Barbara,


Thanks for contacting WormBase.


I am passing along a reply by our JBrowse developer, Scott Cain, to a similar request from another user.  Please feel free to get in touch again if you have any additional questions.


Best,
--Kimberly Van Auken


In the new genome browser (JBrowse) there isn't currently a button for downloading fasta; I plan on adding one soon.

In the meantime, it's not hard, just involves a few steps, depending on what you want to do. If you want the sequence around a particular gene or transcript, you can turn on the "Curated Genes" track and right or control click on gene. From the resulting popup menu, select "View Sequence". You will get a dialog asking you to pick a transcript and after picking one, the resulting window will let you do a variety of useful operations like highlighting, upper/lower casing, and hiding features, as well as letting you display up to a few kb of up or downstream sequence. You can copy from this dialog box and frequently preserve highlighting (in my experience it varies by browser--last I tried, Firefox worked, Chrome didn't and I don't remember for Safari or Edge).

Alternatively, if you want the sequence of a "random" region, you can turn on the "reference sequence" track, zoom the view to the region you want fasta for, then mouse over the label for that track, which makes it more "solid" and displays a down triangle indicating a menu. Clicking on that gives a menu with the option "Save track data". Selecting that will give you a dialog box that will give you the option to view or save the visible region's data as fasta. I don't think it gives you an option for where to save it, so it will end up in your Downloads folder or where ever your default location is.
