### ISSUE TITLE
  Hi, I've inherited a Ruby script whic...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7018]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I've inherited a Ruby script which queries WormBase.  I'm guessing that since it was last run, the schema may have changed and was hoping you might be able to check whether I have generated the right query:<br/>Old:<br/>service = Service.new("http://im-254.wormbase.org/tools/wormmine")<br/>genes = "WBGene00000003,WBGene00008571,WBGene00002176,WBGene00004063,WBGene00000089,WBGene00022358"<br/>genes = genes.chomp.split(",")<br/>fields1 = ["primaryIdentifier", "symbol", "secondaryIdentifier", "briefDescription", "alleles.symbol",<br/>"alleles.primaryIdentifier", "alleles.phenotypesObserved.identifier", "alleles.phenotypesObserved.name",<br/>"alleles.phenotypesObserved.description"]<br/>res1 = service.new_query("Gene").<br/>select(fields1).<br/>where("Gene.primaryIdentifier" => genes).<br/>where("Gene.alleles.phenotypesObserved.name" => {:contains => "lethal"}).<br/>order_by("primaryIdentifier", "ASC")<br/>res1.each_row { |r| puts r.to_csv + "\t\"allele_phenotypesObserved\""}<br/>New: <br/>service = Service.new("http://intermine.wormbase.org/tools/wormmine")<br/>genes = "WBGene00000003,WBGene00008571,WBGene00002176,WBGene00004063,WBGene00000089,WBGene00022358"<br/>genes = genes.chomp.split(",")<br/>fields1 = ["primaryIdentifier", "symbol", "secondaryIdentifier", "briefDescription", "allele.symbol",<br/>"allele.primaryIdentifier", "allele.phenotype.identifier", "allele.phenotype.name", "allele.phenotype.description"]<br/>res1 = service.new_query("Gene").<br/>select(fields1).<br/>where("Gene.primaryIdentifier" => genes).<br/>where("Gene.allele.phenotype.name" => {:contains => "lethal"}).<br/>order_by("primaryIdentifier", "ASC")<br/>Also, there were a couple of queries for the referenceAllele (e.g. referenceAllele.primaryIdentifier). What would this be under the newer schema?<br/>Many thanks in advance!!<br/>visitor_name</p>

**Reported by:** Vict**** (vo1@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by vanaukenk** [comment]
Dear Victoria,

Thank you for contacting WormBase.

I've assigned your ticket to Paolo Nuin, our WormMine developer, who should be able to help get the correct WormMine query for you.

Best,
--Kimberly Van Auken

**Comment by nuin** [comment]
User contacted, will follow up with her.

**Comment by chris-grove** [comment]
My email to user:
"""
I think Paulo may have already helped you, but I think this is the Ruby code you need to make the equivalent query (generated from the Ruby export feature of WormMine):

#!/usr/bin/env ruby

# This is an automatically generated script to run your query
# to use it you will require the intermine ruby client.
# To install the client, run the following command from a terminal:
#
#     sudo gem install intermine
#
# For further documentation you can visit:
#          http://intermine.org/docs/ruby-docs/
#     and: http://intermine.org/docs/ruby-bio-docs/
#
# The following two lines will be needed in every script:
require "rubygems"
require "intermine/service"
service = Service.new("http://intermine.wormbase.org/tools/wormmine")

# Get a new query from the service you will be querying:
service.new_query("Gene").
    select(["primaryIdentifier", "symbol", "secondaryIdentifier", "briefDescription", "allele.symbol", "allele.primaryIdentifier", "allele.phenotype.identifier", "allele.phenotype.name", "allele.phenotype.description"]).
    # You can edit the constraint values below
    where("Gene.primaryIdentifier" => "WBGene00000003").
    where("Gene.primaryIdentifier" => "WBGene00008571").
    where("Gene.primaryIdentifier" => "WBGene00002176").
    where("Gene.primaryIdentifier" => "WBGene00004063").
    where("Gene.primaryIdentifier" => "WBGene00000089").
    where("Gene.primaryIdentifier" => "WBGene00022358").
    where("Gene.allele.phenotype.name" => {:contains => "lethal"}).
    set_logic("(A or B or C or D or E or F) and G").
    order_by("primaryIdentifier", "ASC").
    limit(10).
    each_row { |r| puts r}


As for the reference allele, I think it has been removed from the model, but I don't know why. I'll have to discuss with Paolo; hopefully we can bring that back.
"""
