### ISSUE TITLE
  Nothing is loading when I search for ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7019]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Nothing is loading when I search for a gene.</p><p>What were you doing? <br />&nbsp;&nbsp;Searching for a gene.</p>

**Reported by:** Anon***** (123@*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by chris-grove** [comment]
Page is loading fine for me and according to 

https://downforeveryoneorjustme.com/wormbase.org

the site is up in general. Anonymous submission. Closing.
