### ISSUE TITLE
Chris: Hello German, how can I help? visitor_name ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7020]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello German, how can I help?</br>visitor_name (visitor_email): Hi, i am having issues loading the webpage. Unfortunately, it is taking several minutes to load and then the widgets do not load.</br>Chris: I'm sorry you're having trouble. I am able to load pages without issue. It may be a local issue you're having. One place to check if it is a general issue or a local issue is here:</br>Chris: https://downforeveryoneorjustme.com/wormbase.org

**Reported by:** Germ******** (rger**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/nomenclature#ik04g59j1ea6bcdhl2738fm--10">https://wormbase.org/about/userguide/nomenclature#ik04g59j1ea6bcdhl2738fm--10</a>
**Browser:** Chrome 73.0.3683.86

**Comment by chris-grove** [comment]
User ended chat. I'm not having any issues loading pages. Closing.
