### ISSUE TITLE
  Hi,  I need to conduct an enrichement...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7021]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I need to conduct an enrichement analysis in a set of transcripts (genes) of a couple of worms (Fasciola and Opisthorchis). I realized that you have a tool for C. elegans only. <br/>Is that possible to do that through WormBase?<br/>Thanks,</p><p>What were you doing? <br />&nbsp;&nbsp;Recognition of nuclear targeting proteins</p>

**Reported by:** Clau************* (clau***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by vanaukenk** [comment]
Hi Claudia, 

You can't do this directly in WormBase, but WormBase ParaSite has a collaboration with the gProfiler project which enables GSEA for lots of worm genomes:

https://biit.cs.ut.ee/gprofiler/gost

If you go to the species drop-down and scroll down to WormBase ParaSite, you will see both Fasciola and Opisthorchis listed. 

Best,
Kevin
