### ISSUE TITLE
Tree Display throwing error on Analysis pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7022]
On Analysis pages like:

https://wormbase.org/resources/analysis/RNASeq.elegans#03--10
https://wormbase.org/resources/analysis/RNASeq_Study.SRP000401#03--10
https://wormbase.org/resources/analysis/RNASeq.elegans.N2.WBls:0000004.Hermaphrodite.WBbt:0007833.SRP000401.SRX004866#03--10
https://wormbase.org/resources/analysis/RNASeq.elegans.N2.WBls:0000020.Hermaphrodite.WBbt:0007833.SRP000401.SRX099992#03--10

The Tree Display widget is throwing an error:

<img width="677" alt="Screenshot 2019-04-03 17 12 42" src="https://user-images.githubusercontent.com/611382/55513456-b74b5880-5633-11e9-9543-918834f713e8.png">

**Comment by tharris** [comment]
This is an intermittent acedb capacity issue. Recent improvements should have resolved this for good. Maybe :)
