### ISSUE TITLE
What is the function of dpy-11? We need help for r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7023]
*Help Desk query collected when no chat operators were online. Follow up required.*

What is the function of dpy-11? We need help for realz. Thanks babe. LUH YOU

**Reported by:** Tana******** (cran******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00001073#0-9g-3</a>
**Browser:** Chrome 72.0.3626.122

**Comment by chris-grove** [comment]
My email to user:
"""
It seems you found our dpy-11 gene page. You should find all the relevant information on that page. If you have more specific questions about how to find certain information, please let us know.
"""
