### ISSUE TITLE
Reagents widget throwing error on Ppa-lsy-12 gene page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7026]
On the Ppa-lsy-12 gene page:

https://wormbase.org/species/p_pacificus/gene/WBGene00091073#d--10

The Reagents widget is consistently throwing an error:

<img width="791" alt="Screenshot 2019-04-04 16 01 28" src="https://user-images.githubusercontent.com/611382/55584734-f5f41800-56f2-11e9-880f-981f7f049f75.png">

**Comment by sibyl229** [comment]
@a8wright would you mind taking a look at this?

**Comment by a8wright** [comment]
This is now fixed on staging and production
