### ISSUE TITLE
  download a gene file with selected tr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7027]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;download a gene file with selected tracks?</p>

**Reported by:** Jaqu***** (lope*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

**Comment by vanaukenk** [comment]
Dear Jaqueline,


Thanks for writing to WormBase.


You can download a gene file with selected features from the JBrowse tool. 


The JBrowse tool can be accessed from the general tool menu or from the Location widget on a gene page.  From the Location widget on the gene page, click on the graph view to enter the tool.


To download gene features, right click on your gene of interest, select View Sequence at the bottom of the list of options, select 'OK' from the next window to confirm which transcript you want, and then 'OK' on the next box (warnings about overlapping features).  


In the resulting pop-up window, you can select specific features for highlighting or add upstream and downstream sequences.  You can then copy from the dialog box and paste the highlighted sequence into a file on your computer.


You can also download information from specific tracks by mousing over the track name on the left side of the browser, clicking on the down arrow and selecting 'Save track data' from the menu.


I hope that helps.  Please let us know if you need any additional assistance.


Best,
--Kimberly Van Auken
