### ISSUE TITLE
  How do I cite this website? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7030]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I cite this website?</p>

**Reported by:** Anon***** (jose****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by chris-grove** [comment]
From @raymond91125 to user:
"On WormBase front page, down the bottom, there is a link to "How to Cite" <https://wormbase.org/about/citing_wormbase#0123--10>."
