### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/undefined/...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7032]
*Submitted from the feedback form on the WormBase website.*

<p style="text-shadow: none;">Server Error: 500 at <a href="https://wormbase.org/rest/widget/gene/undefined/overview" style="text-shadow: none;">rest/widget/gene/undefined/overview</a></p><p style="text-shadow: none;">
</p><p style="text-shadow: none;">Error Message:<br style="text-shadow: none;"> Caught exception in WormBase::Web::Controller::REST-&gt;widget "http://datomic-to-catalyst-ws269.us-east-1.elasticbeanstalk.com/rest/widget/gene/undefined/overview failed with 404 at /usr/local/wormbase/jenkins/workspace/staging_build/lib/WormBase/Web/Controller/REST.pm line 970." </p><p>What were you doing? <br />&nbsp;&nbsp;homework</p>

**Reported by:** jeff** (dezn*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//rest/widget/gene/undefined/overview">overview</a>
**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11647.104.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36

**Comment by chris-grove** [comment]
Email response to user by @a8wright 
"""
I believe the reason this link is responding with a 404 error message
is that there is no gene "undefined".

Do you happen to know where you got the link to this gene page?
"""
