### ISSUE TITLE
  How can I get all the RNAi data and i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7035]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I get all the RNAi data and its phenotype information?</p>

**Reported by:** Jack*********** (wang***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by chris-grove** [comment]
Resolved with user on chat
