### ISSUE TITLE
Chris: Hello Jackie, how can I help? China (Shenzh...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7037]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Jackie, how can I help?</br>China (Shenzhen) #5954: How can I get all the RNAi data and its phenotype information?</br>Chris: You can find a high-level summary of RNAi results on our FTP site here:</br>Chris: ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/</br>Chris: There are two files: "rnai_phenotypes" and "rnai_phenotypes_quick"</br>China (Shenzhen) #6452: SO great, Thanks.</br>Chris: The "rnai_phenotypes" file lists each RNAi experiment, with the affected gene, the phenotypes observed, and the RNAi experiment ID, and the paper that reported the evidence</br>Chris: the "rnai_phenotypes_quick" just lists each gene and all of its observed RNAi phenotypes</br>Chris: Does that get you what you need?

**Reported by:** Jack*********** (wang***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/rnai#124-03-5">https://wormbase.org/species/c_elegans/rnai#124-03-5</a>
**Browser:** Chrome 73.0.3683.86

**Comment by chris-grove** [comment]
Related to #7035   (same user)
