### ISSUE TITLE
Upastream sequence unavailable for transcript sequence display on nmy-2 gene page

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7045]
For some reason the upstream sequence of nmy-2 is unavailable from the Sequence widget Transcript column sequence icon:

https://www.wormbase.org/species/c_elegans/gene/WBGene00003777#0-9g-10

<img width="803" alt="Screenshot 2019-04-11 16 07 11" src="https://user-images.githubusercontent.com/611382/55989812-349a4d00-5c74-11e9-9729-adcbd58bd96c.png">

although the downstream sequence is available. I don't know if this hints at a larger issue.

**Comment by tharris** [comment]
Resolved. Closing.
