### ISSUE TITLE
API migration: (existing issue) CDS sequence widget display only one Transcript sequence when multiple exists

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#7046]
For example, JC8.10c (one of the CDSs of unc-26) has two transcripts: JC8.10c.1 and JC8.10c.2. 

The two transcripts differ in sequences, but the sequences widget of JC8.10c (CDS) arbitrarily chooses one of the transcript and displays its sequence. Maybe it's more accurate to display the sequences of both?

**Comment by raymond91125** [comment]
CDS should actually be just the coding part (from ATG to STOP) and thus one and the same between JC8.10C.1 and JC8.10C.2 transcripts, which differ in parts flanking the CDS. It is kind of funny that we choose an arbitrary transcript to represent the CDS. But that's probably for the sake of convenience. Showing both would be redundant, if you will. The best solution certainly would be showing just the CDS sequence on CDS page.

**Comment by tharris** [comment]
Aren’t both parent transcripts annotated to the CDS? By parent here, I mean in the GFF? It’s not — or does not need to be — arbitrary. The more important thing might be simply to note that a single CDS could possibly be generated by multiple transcripts, however biologically spurious that might be.

**Comment by khowe** [comment]
The CDS is the sequence from ATG to STOP. So the sequences widget on the *CDS* pages should just show the *CDS* sequence, not the sequence from one (or both) associated transcripts - we have Transcript pages for that:

https://wormbase.org/species/c_elegans/transcript/JC8.10a.1#06--10

My guess is that the CDS pages don't get visited much on the site (Todd?), so there might be only marginal value in trying to maximise the utility of the Sequences widget on those pages. However, I do think it should be technically correct, and just show the CDS sequence.

**Comment by sibyl229** [comment]
@raymond91125 @tharris @khowe thanks a lot for your suggestions! There is another more fundamental question that I should have asked earlier. Do we really need the webpage for CDS? 

The CDS in the database model is definitely useful, but we don't necessarily have to have webpages for all the model types.

The CDS page essentially repeat the same information we have already included on the Transcript page. The same information is included on the transcript page to make transcript page useful. Given this situation, I'm not sure what value CDS pages add. But there is a drawback of having redundant pages, where people would look for and expect to find additional information but find nothing. It's disappointing and a waste of time.

One reason to have CDS pages might be to aggregate information across different transcripts that share the same CDS. If this were the case, that might be an argument for showing all the transcript sequences. If not, maybe we need to evaluate the reason for having CDS pages.
