### ISSUE TITLE
API migration: CDS spliced sequence is missing UTR features

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#7047]
/rest/widget/cds/B0336.6/sequences

The UTR features are present in the un-spliced sequence, but missing from the spliced one.

**Comment by a8wright** [comment]
I have uncommented the widget on develop and have added the UTR. This change will also add the UTR regions for the spliced for the transcript sequence on the transcript page.

**Comment by a8wright** [comment]
Actually, I added the UTR regions to the spliced sequence for transcript and am not adding it for CDS now. We should discuss this.

**Comment by sibyl229** [comment]
@a8wright there is a new issue with the CDS sequence. The CDS sequence should not include introns. Could you take a look at this sometime next week?

**Comment by a8wright** [comment]
@sibyl229 I just noticed that in the description for the sequence of the cds I had it saying unspliced. I have changed the wording to say "spliced without UTR".

I just printed out the CDS that is being created by my endpoint and cut and pasted the spliced sequence from the staging website for CDS B0336.6 and then did a "git --not index <from-ace> <from-datomic>" command and they were identical.

Please double check what you were seeing. If you have an example I will definitely take a look

**Comment by sibyl229** [comment]
@a8wright here is the response I'm getting based on the latest commit on `feature/transcript-cds-fixes` branch. It has introns in the CDS sequence, which is not what's expected:

![Screen Shot 2019-04-18 at 9 06 15 PM](https://user-images.githubusercontent.com/1753893/56399769-1efdc800-621e-11e9-811d-7f0e5206a296.png)
