### ISSUE TITLE
Some miRNA sequences failing to load on miRNA gene pages and miRNA transcript pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7050]
I noticed on the mir-72 gene page:

https://wormbase.org/species/c_elegans/gene/WBGene00003300#0g--10

that clicking on the gray double helix icon in the Transcript column of the Sequences widget table for the transcript F53G2.9 results in an error reporting "This content failed to load."

<img width="1195" alt="Screenshot 2019-04-12 16 45 37" src="https://user-images.githubusercontent.com/611382/56065402-bb1d6000-5d42-11e9-8be0-f599e7ecb105.png">

Likewise, when I click on the transcript name I'm directed to the transcript page:

https://wormbase.org/species/c_elegans/transcript/F53G2.9#06--10

which throws an error in the "Sequences" widget:

<img width="1175" alt="Screenshot 2019-04-12 16 48 54" src="https://user-images.githubusercontent.com/611382/56065468-eacc6800-5d42-11e9-8f29-aa3848270187.png">

The sequence icon in the Overview widget of the transcript page also throws the same "This content failed to load." error as on the gene page.

**Comment by chris-grove** [comment]
Same issue for mir-2:

https://wormbase.org/species/c_elegans/gene/WBGene00003261#0g--10

and all of its transcripts:

https://wormbase.org/species/c_elegans/transcript/M04C9.7#06--10
https://wormbase.org/species/c_elegans/transcript/M04C9.7a#06--10
https://wormbase.org/species/c_elegans/transcript/M04C9.7b#06--10

**Comment by chris-grove** [comment]
Same for mir-1819:

https://wormbase.org/species/c_elegans/gene/WBGene00077716#0g--10

mir-1, on the other hand, appears to not have this problem:

https://wormbase.org/species/c_elegans/gene/WBGene00003260#0g--10

**Comment by sibyl229** [comment]
Hi @chris-grove the failure to load sequence seems to be a transient issue, seems to have recovered now. I don't know why it was having trouble connecting to the database that stores the GFF and sequence. If this happens again, I will take a look.

**Comment by chris-grove** [comment]
@sibyl229 
OK, yes, it seems to have been transient. Closing.
