### ISSUE TITLE
  Hi, I've been working on a project wh...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7055]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I've been working on a project which involves different peroxisomal proteins in C. elegans. I'm trying to find a good list of all (most of) the peroxisomal proteins present in C. elegans. Do you know if there's a tool available that I can blast with peroxisomal tag to find proteins or may be a curated list available that I can use for my project.<br/>Thanks</p>

**Reported by:** Subh****** (sbmy*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
The best place to find this information on WormBase is on our Gene Ontology page for the Cellular Component term "peroxisome":

https://www.wormbase.org/species/all/go_term/GO:0005777#021--10

In the "Ontology Browser" widget, you can find the number (and a link to the list) of genes that have been annotated to exist and/or be functional within the peroxisome. Right now, the widget reports that there are 212 gene products annotated to peroxisome. Clicking on that link "212 gene products (144 direct)" will bring you to the page listing (and providing download files for) these genes:

https://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=peroxisome&focusTermId=GO:0005777

You will see that there are 64 genes from C. elegans annotated as associated with the peroxisome and you can download that list here. You can also browse the "Associations" widget on the "peroxisome" page, and type "elegans" into the search box to filter the results to just C. elegans genes/proteins. By clicking on the "Full view" option, you can see which evidence codes with which these genes have been associated to the peroxisome as well as the source of the annotation, many times including a reference (publication).

Let us know if you have any further questions about this data.
"""
