### ISSUE TITLE
  WormMine, Hello, I'm having trouble c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7056]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormMine,<br/>Hello, I'm having trouble creating or logging into my WormMine account.  I get errors when attempting to login with Google and with trying to recover my password.  I also get errors with attempting to create an account.  I've tried with Chrome and Firefox.<br/>Thank you</p>

**Reported by:** Keit****** (kcho*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
Apologies for the difficulties. Our WormMine developer, Paulo Nuin (CC'ed), will get in touch with you shortly to sort out your login issues.
"""

**Comment by nuin** [comment]
All good, tested and it's working. Emailed the user.
