### ISSUE TITLE
  Hi, how an I get an alphabetic code f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7057]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>how an I get an alphabetic code for my lab?<br/>thanks,<br/>Matthias</p>

**Reported by:** matt************** (mtru******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by chris-grove** [comment]
Response to user from @ceciliaWBPerson1 
"""
Please see: https://wormbase.org/about/userguide/nomenclature#ejd72460ifh385c9agb1lk--10

How to Register a New Laboratory and Receive Lab, Strain and Allele designations

- I am updating your contact information in your WBPerson page.
Updates will be available in release WS272 of WormBase.
"""
