### ISSUE TITLE
How to download all of the EST sequences  of Praty...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7058]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to download all of the EST sequences  of Pratylenchus vulnus? Thank you!

**Reported by:** Lili*** (huli**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/search/all/Pratylenchus">https://wormbase.org/search/all/Pratylenchus</a>
**Browser:** Chrome 63.0.3239.132

**Comment by chris-grove** [comment]
My email to user:
"""
It appears that WormBase and WormBase ParaSite do not currently have any data on Pratylenchus vulnus, neither the genome nor any EST data. You may be able to get all of the EST data from NCBI:

https://www.ncbi.nlm.nih.gov/nuccore/?term=Pratylenchus+vulnus

My colleagues at WormBase ParaSite may be able to offer more specific advice.
"""

**Comment by chris-grove** [comment]
@epaule @khowe 
Any additional suggestions?

**Comment by khowe** [comment]
We don't have the genome in WBPS, and it's not on our "coming soon" list either. But as you've notices @chris-grove , GenBank has a healthy collection of ESTs.

**Comment by chris-grove** [comment]
OK thanks @khowe
