### ISSUE TITLE
New Tracks for WS271

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7059]
There are source/type present now but not present previously (probably okay):

C. elegans
-----------
Alper lincRNA submission track.....these should be in a predicted lincRNA track modeled closely on the "Curated Genes (noncoding)" g/jbrowse 
 WBPaper00056245 exon 5331
 WBPaper00056245 lincRNA 5048

B. Malayi
---------

deprecated_operon operon 1
This can be copied from the C. elegans config

P. pacificus
------------

All of these are probably already in other species configs
 BLAT_Caen_IsoSeq_BEST expressed_sequence_match 107675
 BLAT_Caen_IsoSeq_OTHER expressed_sequence_match 140975
 RepeatMasker repeat_region 97941
 history exon         4954
 history protein_coding_primary_transcript 240
 tmuris_proteins-BLASTX protein_match 49595

**Comment by scottcain** [comment]
Alper lincRNAs are here:
https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=I%3A4776701..4875400&tracks=Alper%20lincRNA%20(predicted)

B. malayi deprecated operons and T. muris proteins:
https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fb_malayi_PRJNA10729&loc=Bm_v4_Chr2_contig_001%3A10917645..10933608&tracks=T.%20muris%20proteins%2CDeprecated%20operons&highlight=

And the P. pacificus tracks:
https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fp_pacificus_PRJNA12644&loc=PPA_ChrIII%3A10740299..10742770&tracks=Non-C.%20elegans%20Isoseq%20collection%20(best)%2CNon-C.%20elegans%20Isoseq%20collection%20(other)%2CRepeat%20Region%20(RepeatMasker)%2CGene%20Models%20(historical)&highlight=

So all the JBrowse stuff is in place.  Please check the "about" for the Alper lincRNAs.  I plan on adding these configs to GBrowse too but I haven't gotten it done yet.

**Comment by Paul-Davis** [comment]
Hey @scottcain Just checked the Alper lincRNAs  and they look good, thanks for adding them......I think I found a bug in thr "About this track" > Predicted lincRNAs. See this paper for more. The paper link djust seems to cause a refresh of the jbrowse instance?

P

**Comment by scottcain** [comment]
@Paul-Davis 

Oh, right! I put that there anticipating that I'd put a link to the paper, but I didn't know what to link to.  What should I link to?

**Comment by Paul-Davis** [comment]
:) yup that's the paper....I think staging is still on the WS270 datomic instance but various bits of the release are being updated. WBPaper00056245  should be a valid paper in the WS271 Datomic database.

**Comment by tharris** [comment]
Ghost links now resolve. Issue resolved. Closing.
