### ISSUE TITLE
  The BLAST/BLAT tool is not working on...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7060]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The BLAST/BLAT tool is not working on Wormbase.  The link gives a 404 error.  Thanks.</p><p>What were you doing? <br />&nbsp;&nbsp;Accessing the BLAST/BLAT link form the Tools menu</p>

**Reported by:** Pete******* (okke**********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
Confirmed.
My response to user:
"""
Thanks for reporting the problem and apologies for the inconvenience. Our web team is currently working on a fix. I'll let you know as soon as it is sorted out.
"""

**Comment by chris-grove** [comment]
@tharris response to user:
"""
Thanks for letting us know of the issue.  I’ve restored service to the BLAST/BLAT tool.

My apologies for the difficulties.
"""
