### ISSUE TITLE
  On ontology Browser   the disease ont...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7061]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;On ontology Browser <https://wormbase.org/tools/ontology_browser> the disease ontology term link URL constructor is incorrect, should read <https://wormbase.org/resources/disease/%>.</p>

**Reported by:** Raym***** (raym***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by raymond91125** [comment]
[Ontology browser page](https://wormbase.org/tools/ontology_browser)

Good URL should read "https://wormbase.org/resources/disease/%"

**Comment by azurebrd** [comment]
Pull request : https://github.com/WormBase/website/pull/7078

**Comment by raymond91125** [comment]
another malformed URL <https://juancarlos.wormbase.org/resources/disease/DOID:2742#02--10>, in the ontology browser.
