### ISSUE TITLE
  Hello,  A couple of weeks ago, Scott ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7063]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>A couple of weeks ago, Scott Cain came to give an overview on how to use Jbrowse. One tool he mentioned was loading external data  (i.e. a BAM or VCF file) as a track. I attempted to do this and the track didn't load. I may have forgotten a step? I loaded the file (from the file menu), it was identified as a BAM file, and then I clicked open, but no track appeared either in the browser or as a track. Any help would be great, thanks!</p>

**Reported by:** Kath*************** (mccu************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by scottcain** [comment]
Replied to user:

It certainly should work :-) My first guess is that you and WormBase don't agree on what chromosomes are called.  At WB, chromosomes are I, II, etc but at UCSC they are called chrI, chrII, etc.  What are you using?

If that's not the problem, would it be possible to send me the file that doesn't work so I can poke it a little?

**Comment by scottcain** [comment]
Followed up with the user via email (quite a while ago).  The issue boiled down to having to tabix index the vcf file.
