### ISSUE TITLE
  Hello. I am currently interested in t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7066]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello. I am currently interested in tm2426 mutation of snt-3 gene. I typed "tm2426" in wormbase and found that this was a complex substitution. When I click on the details of the mutation on the gene map (BIOProject PRJNA13758), I get to see the 'region sequence'. The system shows that this is a complex substitution with a length of 600bp. My question is, does this mean that 600bp of this sequence was inserted somewhere in snt-3 sequence? or does this mean than 600bp of the specified region was deleted from snt-3 sequence to knockout the gene from transcription? or does this mean that only the specified sequence of snt-3 remains in those worms? Thank you for your time. </p><p>What were you doing? <br />&nbsp;&nbsp;I am trying to design primers for snt-3 (tm2426) worms for genotyping. </p>

**Reported by:** Sohe****** (sjeo***********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by chris-grove** [comment]
From @WBjae to user:
"""
Please see the page for molecular details of tm2426, which is a 600bp deletion.
https://wormbase.org/species/c_elegans/variation/WBVar00251313#-6-10
"""
