### ISSUE TITLE
ok3634 doesn't seem to be shown on the genome brow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7067]
*Help Desk query collected when no chat operators were online. Follow up required.*

ok3634 doesn't seem to be shown on the genome browser.  Is there are reason?  Or have I missed it?

**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/strain/RB2608#03--10">https://wormbase.org/species/c_elegans/strain/RB2608#03--10</a>
**Browser:** Chrome 73.0.3683.103

**Comment by Paul-Davis** [comment]
Hi Julie,

ok3634 is still classified as "Pending Curation" so WormBase doesn't 
have the exact sequence details in the database to map the variant.

If you have a reference detailing the information I can add this to the 
list of variants that we will curate prior to the next release cycle.

Paul



On 18/04/2019 10:55, no-reply@wormbase.org wrote:
> offline chat ok3634 doesn't seem to be shown on the genome browser. Is 
> there are reason? Or have I missed it?
>
> Submitted From:
>   https://wormbase.org/species/c_elegans/strain/RB2608#03--10 
> https://wormbase.org/species/c_elegans/strain/RB2608#03--10 
> <http://www.wormbase.org/https://wormbase.org/species/c_elegans/strain/RB2608#03--10> 
>
>
> This issue has been assigned ticket number: #7067. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7067>.
>
> Reported by: Julie Ahringer (ja219@cam.ac.uk)
> 18 Apr 19 09:54
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Chasing this up with the data providers in a batch of other things, closing
