### ISSUE TITLE
  Hi: Do you know where I could find a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7068]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi:<br/>Do you know where I could find a list that containing worm gene ID name, like WBGene00007063 and commonly used gene name? I checked gff3 file, but I couldn't find it<br/>many many thanks</p><p>What were you doing? <br />&nbsp;&nbsp;I get a excel list that with name written in worm gene ID, but I need to know their corresponding common gene name. </p>

**Reported by:** HSIN********* (tsai**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

If you are ok with doing a bit of unix command extracting you can get 
the data you require from the gff files

zcat elegans.processed.gff2.gz | grep gene | grep WBGene | less

CHROMOSOME_I    gene    gene    3798566 3805737 .       -       .       
Gene "WBGene00006751" ; Locus "unc-11" ; Sequence_name "C32E8.10" ; 
Biotype "protein_coding"
CHROMOSOME_I    gene    gene    3807458 3816809 .       - .       Gene 
"WBGene00016326" ; Locus "ubr-1" ; Sequence_name "C32E8.11" ; Biotype 
"protein_coding"
CHROMOSOME_I    gene    gene    3817996 3821505 .       + .       Gene 
"WBGene00003797" ; Locus "npp-11" ; Sequence_name "F53F10.5" ; Biotype 
"protein_coding"
CHROMOSOME_I    gene    gene    3821656 3821990 .       - .       Gene 
"WBGene00023066" ; Interpolated_map_position "-2.15051" ; Sequence_name 
"F53F10.7" ; Biotype "ncRNA"

If you have a list of WBGene IDs you are interested in, then there is 
the SimpleMine tool which will allow you to extract this data.

https://wormbase.org/tools/mine/simplemine.cgi

I hope this helps.

Paul



On 18/04/2019 11:26, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi:
> Do you know where I could find a list that containing worm gene ID 
> name, like WBGene00007063 and commonly used gene name? I checked gff3 
> file, but I couldn't find it
> many many thanks
>
> What were you doing?
>   I get a excel list that with name written in worm gene ID, but I 
> need to know their corresponding common gene name.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7068. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7068>.
>
> Reported by: HSIN-YUE TSAI (tsai.141@gmail.com)
> 18 Apr 19 10:26
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hello,

Just to add to Paul's suggestions, you can always get the entire mapping of gene IDs to names from our FTP site here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/

You would want the files with titles like:

c_elegans.PRJNA13758.WS269.geneIDs.txt.gz
c_elegans.PRJNA13758.WS269.geneOtherIDs.txt.gz

where the "WS269" will correspond to whichever WormBase release we are currently providing on the main website.

Let us know if you have additional questions.

Best,

Chris Grove
WormBase
________________________________

**Comment by Paul-Davis** [comment]
Dear all:

These are all wonderful suggestions, thank you for the guides to find the
information

HsinYue Tsai

Grove, Christian A. (Chris) <cgrove@caltech.edu>於 2019年4月18日 週四，下午9:31寫道：

> Hello,
>
> Just to add to Paul's suggestions, you can always get the entire mapping
> of gene IDs to names from our FTP site here:
>
>
> ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/
>
> You would want the files with titles like:
>
> c_elegans.PRJNA13758.WS269.geneIDs.txt.gz
> c_elegans.PRJNA13758.WS269.geneOtherIDs.txt.gz
>
> where the "WS269" will correspond to whichever WormBase release we are
> currently providing on the main website.
>
> Let us know if you have additional questions.
>
> Best,
>
> Chris Grove
> WormBase
> ------------------------------
> *From:* Paul Davis <paul.davis@wormbase.org>
> *Sent:* Thursday, April 18, 2019 6:16 AM
> *To:* reply@reply.github.com;
> help@wormbase.org
> *Cc:* tsai.141@gmail.com
> *Subject:* Re: [wormbase-help] How Do I ...?: Hi: Do you know where I
> could find a ... (HSIN-YUE TSAI)
>
>
> Hi,
>
> If you are ok with doing a bit of unix command extracting you can get the
> data you require from the gff files
>
> zcat elegans.processed.gff2.gz | grep gene | grep WBGene | less
>
> CHROMOSOME_I    gene    gene    3798566 3805737 .       -       .
> Gene "WBGene00006751" ; Locus "unc-11" ; Sequence_name "C32E8.10" ; Biotype
> "protein_coding"
> CHROMOSOME_I    gene    gene    3807458 3816809 .       -       .
> Gene "WBGene00016326" ; Locus "ubr-1" ; Sequence_name "C32E8.11" ; Biotype
> "protein_coding"
> CHROMOSOME_I    gene    gene    3817996 3821505 .       +       .
> Gene "WBGene00003797" ; Locus "npp-11" ; Sequence_name "F53F10.5" ; Biotype
> "protein_coding"
> CHROMOSOME_I    gene    gene    3821656 3821990 .       -       .
> Gene "WBGene00023066" ; Interpolated_map_position "-2.15051" ;
> Sequence_name "F53F10.7" ; Biotype "ncRNA"
>
> If you have a list of WBGene IDs you are interested in, then there is the
> SimpleMine tool which will allow you to extract this data.
>
> https://wormbase.org/tools/mine/simplemine.cgi
>
> I hope this helps.
>
> Paul
>
>
>
