### ISSUE TITLE
  have you (or anyone else) collated li...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7069]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;have you (or anyone else) collated list of worm genes that have been tested for rescue by human cDNAs?</p>

**Reported by:** Jane******** (jane********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
My email to user:
"""
I don't believe we have such a list currently, although we would certainly be interested in curating it if it were made available (or we were made aware of it).
"""
