### ISSUE TITLE
  is it possible to change the nomencla...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7070]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;is it possible to change the nomenclature of the isoforms for one gene? ie. mctp-1 has two variants. the longest one is mctp-1b and the short one is mctp-1a. instead of this. could it be possible to report in the paper mctp-1a the longest one and as a b the short one? </p>

**Reported by:** jose***** (sirj****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
My email to user:
"""
Our transcript sequence curators may correct me if I'm wrong, but I believe that our transcripts are named at the initial moment of curation according to a standard naming scheme and we would be quite reluctant to change the names once we have published these names to the WormBase website and database as it is bound to cause confusion in the future. So, it would be best to publish the transcript names in your paper that are consistent with those of WormBase, unless there is a strong case not to do so (precedence elsewhere for example.) The best thing to do in these circumstances is to clearly indicate the mapping of your transcript names to those of the current version of WormBase (and cite the WormBase release, e.g. WS269 is the current release number) and provide complete sequences for each named transcript. Having the sequences explicitly reported is really the best thing to do as it will avoid ambiguity.
"""
