### ISSUE TITLE
API migration: inconsistent json structure for sequences

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#7074]
Currently CDS and Transcript has:

```
{
  negative-strand: ...,
  positive-strand: ...,
  sequence_strand: ...,
}
```

While pseudogene has:
```
{
  negative_strand: ...,  # note the underscore instead of dash
  positive_strand: ..., # note the underscore instead of dash
  strand: ..., # note strand instead of sequence strand
}
```

Can we make them consistent? **What pseudogene has seems preferable.**

**Comment by a8wright** [comment]
Should be fixed in feature branch

**Comment by sibyl229** [comment]
@a8wright don't forget the un-spliced and unspliced with up/downstream. You should be able to test it on http://sibyl.wormbase.org/species/c_elegans/transcript/B0336.6.2#06--10 .
