### ISSUE TITLE
Include evidence type in Disease ontology browser show_genes table

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#7076]
Presently the show_genes page for disease ontology lacks useful information like evidence type, and sometimes, human readable gene names.
In cgi ontology_browser.pm, there should be a special case added for disease ontology. In SOLR queries, &fl should add evidence_type.
Also, no all genes (bioentity) in disease SOLR has bioentity_label filled. Thus, for consistency, the current column for the label should be removed. The three columns are Bioentity, Evidence_type, and Taxon_label.

**Comment by azurebrd** [comment]
Fixed by https://github.com/WormBase/website/pull/7078
