### ISSUE TITLE
disease ontology fix for WS271

### ISSUE THREAD

**Issue by epaule** [WormBase/website#7077]
I did fix the disease_association.WS271.daf.txt file on the EBI ftp site for WS271.
Could you resync it, so it is also updated at ftp.wormbase.org?

thanks,

M

**Comment by sibyl229** [comment]
Hi @epaule let me let @tharris know about this fix, as I don't know where the FTP site is served.

@tharris, @epaule asked disease_association.WS271.daf.txt to be updated on FTP site. Could you do that please?

**Comment by epaule** [comment]
thanks @sibyl229

**Comment by sibyl229** [comment]
Hi @epaule the disease associate daf should be up to date ftp://ftp.wormbase.org/pub/wormbase/releases/WS271/ONTOLOGY/. Also @tharris has a daily cron job setup that automatically sync the WB ftp from the EBI ftp. The cron job should happen at 1am UTC.

**Comment by epaule** [comment]
thanks @sibyl229
