### ISSUE TITLE
  Hi, we have been trying to reconstruc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7079]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, we have been trying to reconstruct a multi-layer network of C.elegans considering gene-gene interactions, protein-protein interactions and enzyme catalysis of metabolic reactions.<br/>We have collected gene-gene interactions and we find that there are different types  of gene-gene interactions. We have not been able to find what a glossary of what the different terms mean. Could you help us by providing the glossary or pointing at where the information is?<br/>Thank you very much for your time. <br/>visitor_name</p>

**Reported by:** Mart* (mart***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
My email to user:
"""
I can help you with this. Apologies that the nomenclature does not have clear documentation currently. Can you first tell me which data set or interactions list you are looking at? Then I can gather the definitions for the terms you are looking for.
"""

**Comment by chris-grove** [comment]
User response Apr 29, 2019:
"""
 Thanks for getting back to me.
The 'dataset' I am looking at is the result of parsing several files within wormbase that contain information about gene-gene regulations within wormbase.
I will have to look for the file names exactly (right now I cannot access them, so I'll try later today). After parsing the data I get entries of the type:

Genetic/Genetic_interaction;gap-1;lin-2;1;0;0
Where columns two & three are gene names and the first column is the type of interaction between these two genes.
['Genetic/Genetic_interaction', 'Genetic/Enhancement', 'Genetic/Suppression', 'Physical/N/A', 'Genetic/Epistasis', 'Genetic/Unilateral_enhancement', 'Genetic/Oversuppression', 'Genetic/Partial_unilateral_suppression', 'Genetic/Synthetic', 'Genetic/Opposing_epistasis', 'Genetic/Mutual_enhancement', 'Genetic/Partial_suppression', 'Genetic/Complete_unilateral_suppression', 'Genetic/Asynthetic', 'Regulatory/', 'Regulatory/Change_of_expression_level', 'Genetic/Mutual_suppression', 'Regulatory/Change_of_localization', 'Genetic/Oversuppression_enhancement', 'Genetic/Maximal_epistasis', 'Genetic/Phenotype_bias', 'Genetic/Unilateral_suppression', 'Genetic/Negative_genetic', 'Genetic/Minimal_epistasis', 'Genetic/Complete_suppression', 'Genetic/Positive_genetic', 'Genetic/Complete_mutual_suppression']

I am not sure if this is enough for you to get an idea of what I am talking about or if you need the names of the files.
"""

**Comment by chris-grove** [comment]
My response Apr 29, 2019:
"""
 The genetic interaction nomenclature has been undergoing an evolution for a number of years now. Those genetic interaction terms I think are mostly defined in this document:

https://docs.google.com/document/d/1guiMueCSuuSaXB_DqEglvEM5TGUV6jZNQUntOgOmMY8/edit?usp=sharing

We have a newer nomenclature which is quite different from these terms, so I wanted to make sure I sent you the appropriate definitions. Please don't hesitate to ask if you have any specific questions about these terms or how to interpret the definitions.

As for the 'physical' and 'regulatory' types, I think they are self explanatory, but please let me know if you have questions about those also.
"""

**Comment by chris-grove** [comment]
User response Apr 29, 2019:
"""
 Thank you so much.
I think I should have enough with this information. Should I need anything else I'll get back to you.
"""
