### ISSUE TITLE
Protein "genomic location" coordinates are off

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7082]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello visitor_name, how can I help?</br>visitor_name (visitor_email): Hello, I was hoping you could help me understand the difference between the "CDS" genomic location, the "gene" genomic location and the "protein" genomic location</br>visitor_name (visitor_email): I'm looking at rpoa-2 of C. elegans</br>Chris: Sure</br>visitor_name (visitor_email): All 3 locations are different, so I'm a bit confused haha</br>visitor_name (visitor_email): Thank you!</br>Chris: The gene location is delimited by the 5' most and 3' most ends of transcripts for that gene</br>Chris: The "CDS" stands for CoDingSequence, and so is equivalent to the open reading frame (ORF). That starts with the nucleotide sequence "ATG" for the starting methionine</br>Chris: That location is specific to each CDS for a gene, and there may be several CDSs per gene</br>Chris: so basically the CDS starts where the first "ATG" is</br>Chris: and ends where the stop codon is like "TAG", "TAA", or "TGA"</br>visitor_name (visitor_email): okay</br>visitor_name (visitor_email): And the protein?</br>Chris: and proteins don't technically have a genomic location, but would essentially be the CDS location of whichever CDS produced the protein</br>visitor_name (visitor_email): Let me send you the link</br>visitor_name (visitor_email): https://wormbase.org/species/c_elegans/protein/CE05629#064--9</br>visitor_name (visitor_email): If you go to "location" on this page,  you will find the genomic location</br>visitor_name (visitor_email): I:9279841..9289384</br>Chris: Right, that will just be the location of the corresponding CDS</br>visitor_name (visitor_email): The CDS, however is different</br>visitor_name (visitor_email): https://wormbase.org/species/c_elegans/cds/F14B4.3#06--9</br>visitor_name (visitor_email): I:9281309..9286562</br>Chris: Hmm, you're right, let me investigate</br>visitor_name (visitor_email): Thank you! It's confusing eh haha</br>Chris: Yes, you're right. There appears to be a problem with the reported location of the protein</br>Chris: The CDS location is correct, but the protein location is taking more than the whole gene</br>Chris: thanks for reporting the issue</br>visitor_name (visitor_email): The gene also has different coordinates, though</br>visitor_name (visitor_email): I:9280963..9286577</br>visitor_name (visitor_email): https://wormbase.org/species/c_elegans/gene/WBGene00008781#0-9g-3</br>visitor_name (visitor_email): And this is the case for all 7 genes I looked up</br>Chris: Hmmm, yeah that's a problem. Thank you very much for pointing this out. I will make sure the appropriate people are notified so we can sort this out.</br>visitor_name (visitor_email): Cool, thank you.</br>visitor_name (visitor_email): Any idea which one I should use if I'm planning a CRISPR experiment?</br>Chris: In the meantime, if you need coordinates for a gene or a list of genes, let me know and I can try to help you get them more quickly than just checking one by one</br>visitor_name (visitor_email): Here's the list of genes I used:
RPOA-2
C36E8.1
FIB-1
K01G5.5
DAO-5
LPD-7
NOL-6</br>visitor_name (visitor_email): (sorry they're all capitalized)</br>Chris: Hmmm, no I couldn't tell you about CRISPR strategy</br>Chris: OK one minute while I try to pull these up. So you're interested in the gene locations? or CDS locations? both?</br>visitor_name (visitor_email): One second, let me review what you wrote so I can understand the difference</br>visitor_name (visitor_email): Gene location</br>visitor_name (visitor_email): please</br>Chris: You will get a transcript of this entire conversation once we're done chatting</br>visitor_name (visitor_email): Great, thank you</br>Chris: OK, I have reliable gene locations for each of the 7 genes you listed</br>Chris: I'll send them to you in a file in a reply to this chat conversation confirmation</br>visitor_name (visitor_email): Perfect, thank you very much</br>Chris: If you have a much larger list I can show you how to do this yourself in WormMine</br>visitor_name (visitor_email): For now those are all the ones I need, but if I want to use WormMine in the future, is there a reference page that I can look at?</br>Chris: We don't have a specific documentation page to show you how to do this particular query, but I'll guide you through it</br>visitor_name (visitor_email): Okay!</br>Chris: Basically, you first want to upload and save your list of genes</br>Chris: You can import your list on the "Lists" tab:</br>Chris: http://intermine.wormbase.org/tools/wormmine/begin.do</br>visitor_name (visitor_email): One per line?</br>Chris: Sure, space separated also woroks</br>Chris: works</br>Chris: or comma separated</br>visitor_name (visitor_email): okay</br>Chris: OK, then click "Create List"</br>Chris: it should automatically recognize your gene names</br>visitor_name (visitor_email): it did</br>Chris: OK, now save your list either with the default name or with your own label</br>visitor_name (visitor_email): okay, done</br>Chris: OK great</br>Chris: Now click on the "QueryBuilder" tab</br>visitor_name (visitor_email): okay</br>Chris: Then click on "Import query from XML"</br>visitor_name (visitor_email): okay</br>Chris: paste the following into the space provided</br>Chris: &lt;query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name Gene.chromosomeLocation.locatedOn.primaryIdentifier Gene.chromosomeLocation.start Gene.chromosomeLocation.end Gene.chromosomeLocation.strand" longDescription="" sortOrder="Gene.primaryIdentifier asc"&gt;
  &lt;constraint path="Gene" op="IN" value="Gene list for all organisms 29 Apr 2019 17.41"/&gt;
&lt;/query&gt;</br>visitor_name (visitor_email): and submit?</br>Chris: yes</br>visitor_name (visitor_email): okay, great</br>Chris: Now you should see a QueryBuilder page, with a section called "Query Overview"</br>Chris: It should say "Gene" at the top and then the next line should read:</br>Chris: IN Gene list for all organisms 29 Apr 2019 17.41</br>visitor_name (visitor_email): yup</br>Chris: to the right of that line is a little blue pencil/edit icon</br>Chris: click on that</br>visitor_name (visitor_email): okay</br>Chris: and you should then see a dialog box with a "Contained in list" checkbox selected with a dropdown list of gene lists available</br>Chris: find your list, select it, and then click the button "Add to query"</br>visitor_name (visitor_email): done</br>Chris: OK, now click on "Show results"</br>visitor_name (visitor_email): great!</br>Chris: OK, great! Now you can click on the "Export" button in the upper right corner to save your list to a file</br>Chris: You can then open that file in Excel, for example; just be aware that gene names can sometimes be automatically converted into dates in Excel, so it's good to make sure you import everything as simple text, not as a "general" format</br>visitor_name (visitor_email): sounds good</br>visitor_name (visitor_email): how do i add the column headers?</br>Chris: When you click "Export" there is a web dialog box that appears. There is a section called "No Column Headers" which is set to that by default. You can click on a checkbox that says "Add column headers" and the downloaded file should then have column headers</br>visitor_name (visitor_email): great! thank you!</br>Chris: You're welcome</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): is there a list of the sql codes you sent me?</br>visitor_name (visitor_email): as in, if i want to generate another query, where can i find a list of fields?</br>Chris: There are template queries, although there isn't one right now for your specific query. You can create a WormMine account and save your queries and lists for future reference</br>Chris: If you want to keep your own file of the XML query, you can always export your own XML from the QueryBuilder page</br>visitor_name (visitor_email): makes sense</br>Chris: At the bottom of the page is an "Export XML" option</br>visitor_name (visitor_email): i see it</br>Chris: You're queries and lists will be saved for you automatically anyway for your given active session</br>Chris: but may not be saved next time you use the service, especially if you're on a public computer</br>Chris: unless you login and save, that is</br>visitor_name (visitor_email): so if i would like to add things like orthologs in humans, i wouldnt be able to do it via sql, then, right?</br>Chris: WormMine doesn't support an SQL, as far as I am aware, but you can certainly use the QueryBuilder to build your own custom queries</br>Chris: We do have a template query for human orthologs of a given gene</br>visitor_name (visitor_email): sorry, i meant xml</br>Chris: You can then edit that template query to constrain on a list of genes like we just did</br>Chris: Right, XML, no problem</br>visitor_name (visitor_email): but i would need to know the possible search fields</br>Chris: I wouldn't want to write out the XML by hand, but you could if you felt inspired ;)</br>Chris: Right, that's where the QueryBuilder is helpful because it shows you the available fields</br>visitor_name (visitor_email): okay, so if im in the query builder and i want to find the field for human homologue</br>visitor_name (visitor_email): what would i do?</br>Chris: OK, you can query from the perspective of different data types, so first make sure you're querying from the Gene class</br>Chris: You can select that on the main QueryBuilder page</br>visitor_name (visitor_email): yup</br>Chris: Then you can select basic identifying attributes like "WormBase Gene ID" and "Gene Name"</br>Chris: by clicking on the "SHOW" to the right of those attributes</br>Chris: to find human orthologs, expand the "Homologues" attribute in the "Model browser"</br>visitor_name (visitor_email): okay</br>Chris: then expand the "Homologue" under that and select "WormBase Gene ID" and "Gene Name" by clicking on each SHOW button</br>visitor_name (visitor_email): okay</br>Chris: Then expand the "Organism" attribute for that Homologue section</br>Chris: and next to "Name" click on the red "CONSTRAIN" button</br>Chris: that should pop up a dialog box with the option to select the species you want orthologs from, including Homo sapiens</br>visitor_name (visitor_email): done</br>Chris: then click "Add to query"</br>Chris: OK, as is, the query will return all human homologues for all genes in the database</br>Chris: So you can constrain the list of input genes; click on "CONSTRAIN" to the right of the original "Gene Name" tag/attribute</br>visitor_name (visitor_email): and restrict to my list</br>Chris: yes</br>Chris: you'll need to check the checkbox to the left of "Contained in list:"</br>Chris: to see the drop down options</br>visitor_name (visitor_email): do i want an A and B constraint?</br>visitor_name (visitor_email): or B and A?</br>Chris: the order doens't matter, but yes A and B (or B and A, it doesn't matter)</br>visitor_name (visitor_email): okay</br>Chris: One more thing that is helpful</br>Chris: Under the initial "Homologues" attribute, click on SHOW to the right of "Type"</br>Chris: this will show what type of homologue it is, "orthologue" vs. "least diverged orthologue" or simple "homologue"</br>visitor_name (visitor_email): that is indeed helpful :)</br>Chris: Unfortunately, we only have HGNC IDs for human genes, no gene names right now (but we're working on that)</br>Chris: So you can download the list of human genes as HGNC IDs and process them as a list</br>visitor_name (visitor_email): whats hgnc?</br>Chris: Human Gene Nomenclature Committee</br>visitor_name (visitor_email): kind of like an ensemble id?</br>Chris: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:15608</br>Chris: They exist at www.genenames.org</br>Chris: Yes, it's another type of ID</br>visitor_name (visitor_email): oh i see</br>visitor_name (visitor_email): okay</br>Chris: HGNC has become the authority on gene names</br>Chris: human gene names, that is</br>visitor_name (visitor_email): okay, i think thats all for now</br>Chris: OK, sounds good</br>visitor_name (visitor_email): thank you very much for your help</br>Chris: Feel free to write to help@wormbase.org if you have any follow up questions</br>Chris: You're very welcome</br>visitor_name (visitor_email): have a lovely evening!</br>Chris: Have a great night!</br>Chris: Thanks!

**Reported by:** Bian** (bian*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/for_users#2310--10">https://wormbase.org/about/userguide/for_users#2310--10</a>
**Browser:** Chrome 73.0.3683.103

**Comment by chris-grove** [comment]
@a8wright @sibyl229 
There appears to be a problem (noticed by this user), in which the protein page "genomic position" coordinates don't exactly map to the gene coordinates or the corresponding CDS coordinates, usually (as far as I can tell) including much more sequence than the gene itself. For example, on the protein page for RPOA-2:

https://wormbase.org/species/c_elegans/protein/CE05629#047--9

The genomic position is listed as:

I:9279841..9289384

which you can tell just from the embedded JBrowse image is too wide a span for this gene:

<img width="882" alt="Screenshot 2019-04-30 09 57 56" src="https://user-images.githubusercontent.com/611382/56967066-7826ff00-6b2e-11e9-9890-0970f8c5d6a1.png">

Same goes for every protein page I've checked so far:

https://wormbase.org/species/c_elegans/protein/CE24905#047--10
https://wormbase.org/species/c_elegans/protein/CE15371#047--10
https://wormbase.org/species/c_elegans/protein/CE46852#04--10

**Comment by a8wright** [comment]
@chris-grove This part of the code gets a little confusing. With the change I just made I simplified it slightly. I think the issue was due to the browser using the label to determine the position to show before. Scott changed this a while ago. I thought that @sibyl added change on the templating/UI side but it appears those changes being made were for something else or at least got lost in the shuffle. I have now made it so that the label on the location widgets shows the start and stop positions without padding (on staging). Please let me know if you see any issues.

**Comment by chris-grove** [comment]
@a8wright 
OK, it's better now as it is using the genomic coordinates of a transcript for the protein (albeit an arbitrary transcript when there are multiple transcripts for the protein), but ideally it should be using the coordinates of the single corresponding CDS for that protein. So for the RPOA-2 protein page:

https://staging.wormbase.org/species/c_elegans/protein/CE05629#04--8

It is reporting the coordinates as

I:9280963..9286577

but should be the coordinates of the CDS:

https://staging.wormbase.org/species/c_elegans/cds/F14B4.3#03--10

I:9281309..9286562

and for the EGL-2 (isoform a) protein page:

https://staging.wormbase.org/species/c_elegans/protein/CE24905#04--10

the coordinates are:

V:1288841..1299332

but should correspond to those of the CDS:

https://staging.wormbase.org/species/c_elegans/cds/F16B3.1a#03--10

V:1289696..1299208

Does that make sense?

**Comment by sibyl229** [comment]
@a8wright a bit background on what's expected and what the UI code does. 

The label text of the link (and the corresponding `label` attribute in the JSON) is supposed to be the **actual genomic coordinates** of the gene or feature. By actual genomic coordinates, I mean **no padding** to adjust the window size for the preview. My understanding of the problem here is that the API isn't returning the correct value for this, correct?

A related but different concept is the padded coordinates that depict the region of the preview window, as captured in `pos_string` of the JSON. This is only used by GBrowse, not JBrowse. For JBrowse, the UI code creates the padded region based on the actual genomic coordinates. If there's a problem with padded region given the correct actual genomic coordinates, please feel free to let me know.

**Comment by a8wright** [comment]
@chris-grove I have made the change on staging and it is currently using the location of the CDS to determine the genomic location of the protein from the sequence database. For the genetic location of the protein, it is using the location mapped to the gene object in Datomic/AceDB.

@sibyl229 I think the reason I didn't change the label to be without padding was that GBrowse was using it. I got Scott to change this a long time ago but never got the label updated... till now. I could be wrong but that is how I remember it.

**Comment by sibyl229** [comment]
@a8wright if it's fixed now, that's good. To my knowledge, the label is always expected to be the actual genomic coordinate. The same thing is used for both GBrowse and JBrowse as the text label for the link. It's the `id` and `pos_string` that's used only by GBrowse.

**Comment by chris-grove** [comment]
@a8wright 
OK, great! Looks good, thanks! Closing.
