### ISSUE TITLE
caenorhabditis elegans，L1,L2,L3,L4,picture and  fe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7084]
*Help Desk query collected when no chat operators were online. Follow up required.*

caenorhabditis elegans，L1,L2,L3,L4,picture and  feature

**Reported by:** 周筱 (1987*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/">https://www.wormbase.org/</a>
**Browser:** Chrome 63.0.3239.132

**Comment by chris-grove** [comment]
From @draciti to user:
"""
Hello, 

thank you for contacting WormBase.

Could you please be more specific in telling us what problem did you encounter?

Many thanks,
"""

**Comment by chris-grove** [comment]
Will reopen if necessary.
