### ISSUE TITLE
Update results of a gene class search on WB to return automated descriptions

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#7086]
Jae noticed that for a gene class search on the WB website, eg. 'cyn-' only the legacy manual descriptions show in the results; perhaps these results should match what we do in the Overview widget, so by default the automated description shows and then when a User clicks on them they are taken to the specific gene page where they can see both or include both in the search results .  

<img width="1001" alt="Screen Shot 2019-04-30 at 3 05 49 PM" src="https://user-images.githubusercontent.com/1414623/56996546-bd145b00-6b59-11e9-8fab-2c91d0582d86.png">

**Comment by sibyl229** [comment]
Hi @rankishore and @WBjae The problem should be fixed now. Both the automated and manual description are now searchable on the staging site (staging.wormbase.org). The description shown on the search result page is the automated description. 

This is a little different from what you asked for regarding the search result display. It's a temporary measure, as the search display is getting an overhaul in WS271. We will have plenty of time discussing this. So I'm gonna delay those change until then, especially the code freeze for WS270 has long passed.

I'm also somewhat unsure about showing the manual description collapsed in search result and gene overview. If the query match occurs in the collapsed manual description, user would have a hard time figuring out _why and where the query matches_. I'd like to propose showing only the matched description in the search result, and leave the manual description expanded in the gene overview. What do you think?

**Comment by WBjae** [comment]
Hi Sibyl,

I'm now testing the current updates at the staging pages. The automatic
description in the search result page looks working greatly.

Thanks,
Jae

**Comment by sibyl229** [comment]
@WBjae Thanks for checking!
