### ISSUE TITLE
WBGene ID as an "other name" for tln-1?

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7087]
@WormBase/wormbase-hinxton 
I just noticed while running a SimpleMine query on all C. elegans genes that there are two genes that are turning up as a match to the gene ID WBGene00022151. As it turns out, "WBGene00022151" is an other-name for the gene tln-1:

https://wormbase.org/species/c_elegans/gene/WBGene00006771#0g--10
https://wormbase.org/species/c_elegans/gene/WBGene00022151#0g--10

This seems unusual (unique, actually) and I'm wondering if it was intentional. It is clear that WBGene00022151 has merged into WBGene00006771, but I don't recall this type of ID inheritance for a gene merger. Is this intentional and should we leave it alone? Or should we strip this gene ID as an other name from tln-1?

NB: I'm labeling as Hinxton and Curation, but please correct me if it should be something else.

**Comment by gw3** [comment]
Chris,
I can only think that this was done to transfer the evidence for the 
OrthoList reference from the old gene to the gene acquiring the merge, 
but it was done halfway through last year, not in 2013 when the merge 
was originally made.
This is not our standard practice.
I have removed the Other_name WBGene00022151 from WBGene00006771, so the 
next Build (WS272) will not contain this link between these genes.
Gary

**Comment by chris-grove** [comment]
OK, great! Thanks @gw3 !
