### ISSUE TITLE
  Hi, I am trying to get a list of all ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7088]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am trying to get a list of all strains with X chromosome rearrangements, mainly translocation and chromosome breakage. <br/>Is there a way to get al least the rearrangement name or strain it is present on?<br/>Thank you,<br/>Yonatan</p><p>What were you doing? <br />&nbsp;&nbsp;Tried to type X on the arrangement search box.</p>

**Reported by:** Yona******** (yona**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
My response to user:
"""
We don't have a convenient user-facing tool to get at this information, but I've queried our most recent build (release WS271) for this information and provided it in an Excel spreadsheet (attached). The file lists all rearrangement objects on the X chromosome and lists their type (second column), their unique reference strain (third column), and a list of all associated strains (fourth column).

I hope that helps.
"""

**Comment by chris-grove** [comment]
User response:
"Thanks a million Chris.
This is exactly what I needed."
