### ISSUE TITLE
  Is there any way to retrieve all of t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7095]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there any way to retrieve all of the interaction-based phenotypes for all genes?<br/>I am interested in exploring phenotype data. I have retrieved phenotypes associated with all genes from SimpleMine and from these files:<br/>phenotype_association.WS271.wb<br/>rnai_phenotypes.WS271.wb<br/>However, it is unclear to me if they include interaction phenotypes. I suspect that they do, in which case I would like to remove them. <br/>On the website, there is a section called "interaction-based phenotypes" related to phenotype information for a given gene. So I know the data exist; do you happen to know where I can find them? They may also be in these files that I have retrieved; I may have overlooked some important column.<br/>I'm continuing to explore the FTP for just the right file that can help me, but in the meantime I thought I might ask.<br/>Thanks so much for you help!<br/>--visitor_name</p>

**Reported by:** Gavi* (gavi***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
My email response to user:
"""
 Those FTP files:

phenotype_association.WS271.wb
rnai_phenotypes.WS271.wb

do not include interaction phenotypes, as far as I'm aware. If you find a discrepancy, could you please let me know?

If you're still interested in interaction phenotypes, we don't have a ready-made file with this information, but I can query the database and generate one for you if you let me know exactly what information you would like.
"""
