### ISSUE TITLE
Chris: Hello Jack, how can I help? visitor_name (l...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7102]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Jack, how can I help?</br>visitor_name (ladisvisitor_name03@gmail.com): Ok man i talked to you once before i am not going to say it again</br>visitor_name (ladisvisitor_name03@gmail.com): you are the worst person ever</br>visitor_name (ladisvisitor_name03@gmail.com): but can you help me out</br>visitor_name (ladisvisitor_name03@gmail.com): hello</br>visitor_name (ladisvisitor_name03@gmail.com): hi</br>visitor_name (ladisvisitor_name03@gmail.com): talk to me</br>visitor_name (ladisvisitor_name03@gmail.com): i need help</br>visitor_name (ladisvisitor_name03@gmail.com): heyyyyyyyyyyyy

**Reported by:** jack (ladi*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 74.0.3729.131

**Comment by chris-grove** [comment]
homework trolls
