### ISSUE TITLE
Chris: Hello Michael, how can I help? visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7103]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Michael, how can I help?</br>visitor_name (visitor_email): hey can i ask some questions</br>Chris: If they are about how to use WormBase, sure!</br>visitor_name (visitor_email): can you show me</br>visitor_name (visitor_email): how to touch my toes</br>visitor_name (visitor_email): I like toes</br>visitor_name (visitor_email): toesssss

**Reported by:** mich******** (pool******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 73.0.3683.103

**Comment by chris-grove** [comment]
homework trolls
