### ISSUE TITLE
  Hello, I noticed that I can no longer...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7104]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I noticed that I can no longer extract genomic DNA sequences by selecting certain region of the genome. I remember there being a "dump in FASTA format" option once I select a certain region of the genome. Now it just zooms into the selected sequence. Could you please let me know how this function has been replaced? Thank you!</p>

**Reported by:** Saba (saba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by scottcain** [comment]
My reply to the user:

Since we've been getting this question a lot, I wrote a blog post about it:

http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

Please let me know if you have any questions about this functionality,
Scott
