### ISSUE TITLE
SPELL "Download Expression Data" link is broken

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7113]
On the SPELL homepage:

https://spell.wormbase.org/

The "Download Expression Data" link on the left is not working. On Chrome the error reads:

```
This site can’t be reached The webpage at ftp://caltech.wormbase.org/pub/wormbase/spell_download/datasets/ might be temporarily down or it may have moved permanently to a new web address.
ERR_FTP_FAILED
```

On Firefox, the link doesn't do anything or just leads to a blank page with the FTP address:

ftp://caltech.wormbase.org/pub/wormbase/spell_download/datasets/

The Caltech FTP appears to be up:

ftp://caltech.wormbase.org/pub/wormbase/spell_download/

but the "datasets" directory that the link points to appears to be missing or broken.

**Comment by WenChenWormBase** [comment]
Ah, the symbolic link does not work in this case. Just fixed it. Thank you for spotting this!

**Comment by chris-grove** [comment]
@WenChenWormBase 
OK, thanks, works now! Closing.
