### ISSUE TITLE
  It would appear that rest.wormbase.or...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7115]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;It would appear that rest.wormbase.org has no host. Is this a permanent change?</p><p>What were you doing? <br />&nbsp;&nbsp;$ ping rest.wormbase.org                                                                                           
ping: rest.wormbase.org: Name or service not known
</p>

**Reported by:** Mark****** (watt*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by chris-grove** [comment]
@a8wright 's email to user:
"""
Thanks for reporting the issue. We just rolled our latest release
(WS270) and have made a few back end changes. This resulted in the
route not being created. I have added the route you should now be able
to access rest.wormbase.org.

Let me know if you have any further questions or if any other issues arise.
"""
