### ISSUE TITLE
Hi. I've been trying to extract a gene's sequence ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7117]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi. I've been trying to extract a gene's sequence through an http request to your website. is that possible? I haven't been able to find clear instructions in your api page.

**Reported by:** Lira* (lira***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide/for_developers/API-REST/Sequence#0--10">https://www.wormbase.org/about/userguide/for_developers/API-REST/Sequence#0--10</a>
**Browser:** Chrome 73.0.3683.103

**Comment by chris-grove** [comment]
User answered in #7120
