### ISSUE TITLE
"Aldicarb resistance" is reported as a possible ph...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7119]
*Help Desk query collected when no chat operators were online. Follow up required.*

"Aldicarb resistance" is reported as a possible phenotype for daf-7 RNAi, but the source cited does not report those findings, as that study never investigated this particular gene (daf-7) at all.

**Reported by:** Tyle********* (tyle*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00000903#0-c-3">https://wormbase.org/species/c_elegans/gene/WBGene00000903#0-c-3</a>
**Browser:** Chrome 74.0.3729.131

**Comment by chris-grove** [comment]
Email to user:
"""
Thanks for writing to WormBase. daf-7 has a reported aldicarb resistance phenotype (suppression of dgk-1 mutation-induced aldicarb hypersensitivity) listed in Supplementary Table S2 of the paper.
"""
