### ISSUE TITLE
is there any way to extract a gene's sequence thro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7120]
*Help Desk query collected when no chat operators were online. Follow up required.*

is there any way to extract a gene's sequence through your api?

**Reported by:** Lira* (lira***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10">https://www.wormbase.org/about/userguide/for_developers/API-REST/Gene#0--10</a>
**Browser:** Chrome 73.0.3683.103

**Comment by chris-grove** [comment]
Email response to user by @a8wright 

"""
Thank you for writing. Luckily, we just upgraded our sequence widgets.
I am not sure exactly what sequence you are looking for but I am
guessing either transcript of CDS will provide you with the
information you are looking for.

To get to this you will need to go to the sequences widget on the gene
page that you are interested in. This widget should list the
transcripts and CDS sequences related to the gene of interest. This
information is also in the rest endpoint for the widget (e.g. REST
endpoint: rest/widget/gene/WBGene00015146/sequences). For the
transcript page you would like to look at the "sequences" widget (e.g.
REST endpoint: rest/widget/transcript/B0336.6.1/sequences) and for the
CDS you will want the sequences widget as well (e.g. REST endpoint:
rest/widget/cds/B0336.6/sequences).

For both the CDS and transcript "sequences" endpoints the REST
endpoint returns the sequence and feature locations in both the
positive and negative direction.

*Almost all endpoints can be accessed through our new REST interface
at rest.wormbase.org.

Please let me know if you have any questions,
"""
