### ISSUE TITLE
Chris: Hello Stephen, how can I help? visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7121]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Stephen, how can I help?</br>visitor_name (visitor_email): BLAST isn't working properly. It's very slow at the moment.. been waiting for 5min for a page to load to show the alignments and links to the genome</br>Chris: Hmmm, apologies, that shouldn't happen</br>Chris: I'll let the webteam know so they can work on it</br>visitor_name (visitor_email): Ok great. Thanks Chris.</br>visitor_name (visitor_email): First time using the Chat function.. I haven't had the need to indicate a problem in a while (kudos to the team for that) but I recall when it was a message that got sent to the team and then an email was sent back. This is much nicer</br>Chris: Haha, nice. Glad you like it. We also have the help desk email address help@wormbase.org which we try to reply to regularly</br>Chris: I just tried BLAST and it worked. Could you tell me what it is you're trying to BLAST? Sometimes</br>visitor_name (visitor_email): FYI Safari stopped trying to load the page.</br>Chris: Sometimes very large sequences (~10,000+ nt) are slow to BLAST</br>visitor_name (visitor_email): simply trying to BLAST this sequence against the genome, to see where the hit is.</br>visitor_name (visitor_email): caaattacggaaaatgaaaatttccggcaaatcggcaaattacggaaaatgaaaatttccggcaaatcggcaaattgtcggaattgaaggcggaagtcggcgcggctgccgttttggcgcctgcatggaagccccacagcctcaatcaaaaatcgctactcccttttctttaacctccggctctttttttgtgctaaaacttgctctctgaatagaaaatcaaatcttttcagaagtttcttgaagggggccctgacctcttgaaacttttccacaaccctccgccgctttcttcttcttattcccttttgctctctccgcatttttatgaatttctgaatagagggaaactgcggctccgtgagcacaaaggtacttttttgatggtgcctgagagcctgctgaaacgggaagggaatcgtaggagttttcgtccaaattccacaattttctcttactttacactctgggggctccatcaccaagtgacacttacccacaatgccctggaaatgcactttactctgtcaggatttttttgttgttgaaaaatctggattttctaggtgaaactctcttgaaaatgtggaatttttgacggttctttttttttgctcttttctgaaatttttcagctgtcaaaattgacaattttcagttttcacttaagtttgactggaaatttcgcctgaaaattaaagattgcggtgtgaagcaggttcggcaaattggaaaattgccggtttgctgatttgccggaaattttcgattctggcactttgccaatttgccggaaattgtcgattttggcagtttgccggtttaccggaaattttcaattccggcaattgatcgttttgccggaaattttcaattccggcaatttgccgttttaccggaaatttcaaactccggcaattttccgatttgccggaaatttcaagttccgccaatttgccggaaatttctaattccggcactttgccgatttgccggaagtttcaattcctgcaattcgccgatttgccgaaatctttcaattctggcaatttgtcggtttgcctgaaattttcaattccggcaattgaccgttttgccggaaattttcaattccggcaatttgccgatttaccggaaatttcaaactccggcaattttccgatttgccggaaatttcaagttccgccaatttgccggaaattttcaattccggcaatctgccgatttgccagaaattttcaattccgccaatttgccaatttgccgatttgccgaaatctttcaattctggcaatttgtcggtttgcctgaaattttcaattccggcaatttgccgataagctgaaaattttgaattccggcagtttgccgataaacttaaaattttgaattctggcagtttgccggtttgccggaaattttcaattccgacaatttgccggaaatttcaaattccggcaattcgccgattcgccgaaaattttcaattctggcaatttg</br>visitor_name (visitor_email): it's only 1.5kb</br>Chris: OK, right, that shouldn't be a problem</br>visitor_name (visitor_email): did you do a nucleotide BLAST when you tried it?</br>Chris: Yes</br>Chris: I'm trying your sequence now</br>visitor_name (visitor_email): ok. I'm trying again as well</br>visitor_name (visitor_email): still very slow at exiting from the input page to the output page.</br>Chris: yeah slow for me too</br>Chris: It looks like there may be quite a few repeats in this sequence</br>visitor_name (visitor_email): I have a blank screen and the safari progress bar is inching every so slowly</br>visitor_name (visitor_email): Yes, that's correct.</br>visitor_name (visitor_email): I just realized that there were repeats</br>Chris: That could be slowing things down</br>Chris: Also, if the "Filter" option is turned on, it tries to mask repeats</br>visitor_name (visitor_email): and wanted to see where things were in relation to the tandem repeats, to see if I should choose another site</br>Chris: OK, I'll troubleshoot a bit and see if I can get something to work</br>visitor_name (visitor_email): Ok. You'll send an email?</br>Chris: Once we end this chat, we'll both receive a transcript of this conversation. We can continue the conversation there</br>Chris: If that's OK</br>visitor_name (visitor_email): sounds good

**Reported by:** Step*************** (svon*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Safari 12.1

**Comment by chris-grove** [comment]
Follow up:
"""
OK, so I'm consistently getting slow service when trying to BLAST your sequence with the default settings. However, I'm consistently getting pretty fast results by changing the default "E-value Threshold" from "1E+0" to "1E-32". I think by having such a low threshold of "1E+0" BLAST is trying to find all possible matches and it's taking a long time. Applying the more stringent threshold of "1E-32" limits the number of relevant hits and I think speeds up the process.

Let me know if that still doesn't work for you. Also, here's a URL for a JBrowse view of your hit aligned to the genome:

https://wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes%2CHits&loc=I%3A11175781..11201120&addTracks=%5B%7B%22label%22%3A%22Hits%22%2C%22type%22%3A%22JBrowse%2FView%2FTrack%2FCanvasFeatures%22%2C%22store%22%3A%22url%22%2C%22subParts%22%3A%22match_part%22%2C%22glyph%22%3A%22JBrowse%2FView%2FFeatureGlyph%2FSegments%22%7D%5D&data=data%2Fc_elegans_PRJNA13758&addFeatures=%5B%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012577%2C%22end%22%3A14481982%2C%22name%22%3A%22Hits%22%2C%22type%22%3A%22match%22%2C%22subfeatures%22%3A%5B%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A11190806%2C%22end%22%3A11192230%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012692%2C%22end%22%3A1013466%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012658%2C%22end%22%3A1013431%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012629%2C%22end%22%3A1013396%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012762%2C%22end%22%3A1013469%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012594%2C%22end%22%3A1013361%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A14481354%2C%22end%22%3A14481982%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012577%2C%22end%22%3A1013115%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A1012590%2C%22end%22%3A1013151%2C%22type%22%3A%22match_part%22%7D%2C%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A14481353%2C%22end%22%3A14481807%2C%22type%22%3A%22match_part%22%7D%5D%7D%5D&highlight=
"""
