### ISSUE TITLE
Hi,
Do you know if C. elegans have a homologue gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7122]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
Do you know if C. elegans have a homologue gene of occludin?
Thanks very much

**Reported by:** Bego (bego**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00000526#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00000526#0-9g-3</a>
**Browser:** Chrome 74.0.3729.131

**Comment by epaule** [comment]
if you copy the human gene name (OCLN) into the search box on WormBase, it will show you the homologs and orthologs in WormBase.
But you probably want to cast your net a bit wiser and have a look at https://www.alliancegenome.org too.
