### ISSUE TITLE
  I recently found a paper, "Identifica...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7123]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I recently found a paper, "Identification of 1088 New Transposon Insertions of Caenorhabditis elegans: A Pilot Study Toward Large-Scale Screens" by Martin et al, Genetics 2002 Sep;162(1):521-4., which stated that a list of transposon insertions they identified could be found on wormbase.  There is no other information and I can't seem to find this data on here linked to the paper. <br/>Any thoughts on how I might access this information here are welcome.<br/>Thank you for your time and help.</p>

**Reported by:** Nico************** (nkur****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Nicole,

I believe that this publication is referring to what was to become the 
NemaGENETAG_consortium. This data can be found in various places, but I 
would suggest the annotation gff files on the ftp site:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS270.annotations.gff3.gz

NemaGENETAG_consortium transposable_element_insertion_site

I will look into increasing the visibility of Consortia data as we have 
a number of large scale projects that could do with an overview entry point.

Paul

On 16/05/2019 18:32, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I recently found a paper, "Identification of 1088 New Transposon 
> Insertions of Caenorhabditis elegans: A Pilot Study Toward Large-Scale 
> Screens" by Martin et al, Genetics 2002 Sep;162(1):521-4., which 
> stated that a list of transposon insertions they identified could be 
> found on wormbase. There is no other information and I can't seem to 
> find this data on here linked to the paper.
> Any thoughts on how I might access this information here are welcome.
> Thank you for your time and help.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7123. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7123>.
>
> Reported by: Nicole Kurhanewicz (nkurhane@uoregon.edu)
> 16 May 19 17:32
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
