### ISSUE TITLE
Change definition for life stage term 'larva nematode'

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#7124]
On the WB webpage, https://wormbase.org/species/all/life_stage/WBls:0000105#04--10
I noticed that the definition/description for the life stage term 'larva nematode' WBls:0000105, shows as: 'From the time after hatch till becomes adult.'

This should probably be changed to something like 'From the time after hatching till the adult stage' or some such wording.

**Comment by tharris** [comment]
Closed. Description changed to "The stage that begins after hatching and ends when the nematode becomes adult."
