### ISSUE TITLE
Syntax error for motif display on protein pages

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#7125]
Hi,

It looks like there's a syntax error where some of the motif displays are supposed to be on protein pages.

Here are two examples:

![image](https://user-images.githubusercontent.com/1730534/57933418-44b4d600-788b-11e9-8c69-65cc22ef61a0.png)

![image](https://user-images.githubusercontent.com/1730534/57933501-775ece80-788b-11e9-9871-637976cbce23.png)

**Comment by sibyl229** [comment]
Hi @vanaukenk and @chris-grove the domain graphics problem should be fixed now: https://staging.wormbase.org/species/c_elegans/protein/CE27837#0--10
https://staging.wormbase.org/species/c_elegans/protein/CE31525#0--10
Could you take a look? Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks good on all reported pages! Thanks Sibyl!
Closing.
