### ISSUE TITLE
I want to know OSM-6's signal transduction of the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7127]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to know OSM-6's signal transduction of the AWC neuron. Additionally what kind of protein does it encode and what does that protein do in the cell(about OSM-6)?

**Reported by:** IN Y********** (xvcc************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00003886#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00003886#0-9g-3</a>
**Browser:** Chrome 74.0.3729.131

**Comment by chris-grove** [comment]
My email to user:
"""
I would recommend checking the osm-6 gene page:

https://wormbase.org/species/c_elegans/gene/WBGene00003886#0c38bge--10

In particular, you may be interested in the information provided in the Overview (gene description), Gene Ontology, Interactions, Phenotypes, and Phenotype Graph widgets. Papers mentioning osm-6 are listed in the "References" widget. If you click on the protein name "OSM-6" in the Sequences widget, you will be directed to the OSM-6 protein page:

https://wormbase.org/species/c_elegans/protein/CE27774#035--10

There you can view details on protein homology and motifs.

I hope that helps.
"""
