### ISSUE TITLE
  Hello, I am currently trying to analy...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7135]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I am currently trying to analyze all potential ORFs in the C. elegans genome and I was wondering if there was any downloadable annotated versions of genome wide ORFs or files which contained all potential ORFs</p>

**Reported by:** Will************ (wmm2**********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36

**Comment by chris-grove** [comment]
My email response to user:
"""
At WormBase, we refer to ORFs as "CDS" for "CoDing Sequence". You can download a file of all ORF/CDS sequences in FASTA format from our FTP site. The current file for C. elegans (canonical genome/bioproject for the N2 strain) will always be at this location:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

The file you are looking for is the one titled as "c_elegans.PRJNA13758.WSXXX.CDS_transcripts.fa.gz" where WSXXX refers to the current release of WormBase (currently WS270). The current file is:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS270.CDS_transcripts.fa.gz

Let us know if you need something else.
"""
