### ISSUE TITLE
Variation Display

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7136]
Hi Web team, 

Would it be possible to display Remarks for Variations in the overview widget on the Variation summary page?

Test data point WBVar00142337

Thanks

Paul

**Comment by sibyl229** [comment]
@Paul-Davis of course! I will let you know when it's done.

**Comment by a8wright** [comment]
@sibyl229 It looks like this one is done. Is that correct?

**Comment by Paul-Davis** [comment]
Yes, looks good on live site to me
