### ISSUE TITLE
On the latest version of Wormbase the sequence for...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7137]
*Help Desk query collected when no chat operators were online. Follow up required.*

On the latest version of Wormbase the sequence for unspliced cDNA is no longer there. Also in variations there is no longer the sequence given for mutations where it is known. In the case of variations the only link to find what the mutation is is to JBrowse, however, once there is is totally unclear how you can find the sequence changes associated with the mutation. Both of these features are very useful and I use them regularly. Will these be restored in future updates?

**Reported by:** Step*********** (nurr**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/variation/WBVar00249531#02-45-3">https://wormbase.org/species/c_elegans/variation/WBVar00249531#02-45-3</a>
**Browser:** Firefox 66.0

**Comment by chris-grove** [comment]
My email response:
"""
Could you provide examples of where you cannot find the unspliced cDNA or cannot find the sequence change details? We certainly intend to keep displaying those, and from what I can see they are all still available (although there was a display update recently which changes how some sequences are displayed).

For example, the tm488 allele:

https://wormbase.org/species/c_elegans/variation/WBVar00249531#06--10

and the cDNA unspliced sequence for the gene shn-1:

https://wormbase.org/species/c_elegans/gene/WBGene00006444#0g--10

Note that the unspliced sequence is no longer available under the "Coding Sequence (CDS)" heading, but is still available under the "Transcript" heading.
"""
