### ISSUE TITLE
  Hello, I have a question about the la...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7139]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I have a question about the labeling of transcript sequences. The different sequences have the word 'UTR' in their titles. For instance, 'Spliced + UTR', 'Unspliced + UTR', etc..<br/>In this context, what does UTR mean? Is this the 5' and/or 3' UTR of the transcript? If I just wanted the coding sequence for a gene, would I copy the 'Spliced + UTR' sequence? And if I wanted the genomic sequence of a gene, including introns, would I copy the 'Unspliced + UTR' sequence? <br/>I just want to make sure the sequences I am using are what I believe them to be. Thanks for all your hard work in making this website!</p><p>What were you doing? <br />&nbsp;&nbsp;I was copying sequences from:
https://www.wormbase.org/species/c_remanei/transcript/CRE05609.1#06--10</p>

**Reported by:** Step*** (taha***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.158 Safari/537.36 Vivaldi/2.5.1525.43

**Comment by chris-grove** [comment]
My email response:
"""
"UTR" refers to "UnTranslated Region" and refers to the untranslated ends (5' or 3') of coding transcripts.

If you just want the coding sequence, you can open "Spliced + UTR" and just copy the capital letters highlighted in yellow and orange, or conversely you can just click on the sequence icon in the "Coding sequence (CDS)" column of the table (in the "Overview" widget) and get just the coding sequence (ATG -> stop codon).

Yes, if you want the genomic sequence of a gene (for a particular transcript) you would copy the entire sequence displayed under "Unspliced + UTR".

Let us know if you need further clarification.
"""
