### ISSUE TITLE
  Hi, it's been a while. How does one g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7143]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, it's been a while. How does one go about naming a gene that will be in publication soon?</p>

**Reported by:** Anon***** (aele***********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by chris-grove** [comment]
My email response:
"""
You should email genenames@wormbase.org (CC'ed) to discuss gene names, preferably prior to publication so we can be sure there are no name conflicts with existing names (or those being held in confidence until the respective publication is published).
"""
