### ISSUE TITLE
Hi there, 

I am interested in using the WS260.tra...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7144]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there, 

I am interested in using the WS260.transposon_transcripts file from the worm base FTP to compare to some RNA-Seq data and I was just wondering if you had any further information on how these files were generated - are these the filtered/ masked transposon transcripts from  the associated reference genome? 
Thanks very much for your help. 
Kind Regards, 

visitor_name

**Reported by:** Emma (emma********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Safari 12.1

**Comment by Paul-Davis** [comment]
Dear Emma,

Apologies I was on vacation when your help email came in.

The c_elegans.PRJNA13758.WS260.transposon_transcripts.fa.gz file 
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS260/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS260.transposon_transcripts.fa.gz> 
is a dump file of all the annotated CDSs that have manually been 
classified as being of transposon origin. These usually correspond to 
transposases or other gene products associated with transpositions etc.

The c_elegans.PRJNA13758.WS260.transposons.fa.gz 
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS260/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS260.transposons.fa.gz> 
file contains both manually and predicted transposon dna sequences. 
These are reference genome consensus sequences that have been either 
manually marked up of match aligned repeat sequences. The predicted 
transposons come mainly from the repeat masker library alignments with 
some classification and filtering to remove the matches that are too 
fragmented.

If you have further questions, please feel free to email me back.

Paul

On 27/05/2019 00:19, no-reply@wormbase.org wrote:
> offline chat Hi there, I am interested in using the 
> WS260.transposon_transcripts file from the worm base FTP to compare to 
> some RNA-Seq data and I was just wondering if you had any further 
> information on how these files were generated - are these the 
> filtered/ masked transposon transcripts from the associated reference 
> genome? Thanks very much for your help. Kind Regards, Emma
>
> Submitted From:
>   https://www.wormbase.org/#012-34-5 
> https://www.wormbase.org/#012-34-5 
> <http://www.wormbase.org/https://www.wormbase.org/#012-34-5>
>
> This issue has been assigned ticket number: #7144. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7144>.
>
> Reported by: Emma (emma.fbarriere@gmail.com)
> 26 May 19 23:19
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Leave open for a week and then if there is no user response then close.
