### ISSUE TITLE
Hello. I want to download all orthologues of a C. ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7145]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello. I want to download all orthologues of a C. elegans gene in nematodes, including in the sequence title the name of the species and the gene stable ID.
When I look for orthologues and download the FASTA file of CDS there are some stable IDs, but other sequences titles do not coincide with any of the IDs in the list, and I cannot identify which species and gene does it belong to.

**Reported by:** Dieg*********** (exce*********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00018604#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00018604#0-9g-3</a>
**Browser:** Chrome 74.0.3729.169

**Comment by chris-grove** [comment]
My email response:
"""
Your best bet is probably to use Wormbase ParaSite BioMart:

https://parasite.wormbase.org/biomart/martview/

There are many worm genomes to select from as orthologue output for your query of an input C. elegans gene. Here's a sample query using C. elegans let-60 as the input gene, and several worm species' orthologues as output:

https://bit.ly/2HHbTYN

You can go in and manually select which worm genomes you'd like to see orthologues for.

Let us know if you have any questions.
"""
