### ISSUE TITLE
RNA-Seq Related Tools

### ISSUE THREAD

**Issue by WenChenWormBase** [WormBase/website#7146]
Todd and Sibyl, 

We created two RNA-Seq related tools at Caltech. They function in ways similar to SimpleMine. I wonder if you can add them to the WormBase Tools menu.

Expression Dataset Locator
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/expression_dataset_locator.cgi

RNA-Seq FPKM Gene Search
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/fpkmmine.cgi

I wonder if you can create a new category called "RNA-Seq Related" under the Tools Menu, and list these three tools under it:

WormBase SPELL
Expression Dataset Locator
RNA-Seq FPKM Gene Search

You can create virtual URLs for these two RNA-Seq related tools, like how you handled SimpleMine.

**Comment by sibyl229** [comment]
Done! Closing. Please feel free to reopen, if there is any problem.
