### ISSUE TITLE
9588754525...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7147]
*Help Desk query collected when no chat operators were online. Follow up required.*

9588754525

**Reported by:** Shad******* (mrna********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/transcript/B0001.1b.1#06--9">https://www.wormbase.org/species/c_elegans/transcript/B0001.1b.1#06--9</a>
**Browser:** Chrome 52.0.2743.98

**Comment by chris-grove** [comment]
bogus return email address (bounced); ignore
