### ISSUE TITLE
AG laboratory info needs update

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7148]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We recently noticed that for the gene kqt-3 my association is with NCI, Frederick MD. That is 20 years old. Can you please erase any record of Frederick and have all my associations be NIDDK at NIH? Thanks. I appreciate the change.</p>

**Reported by:** Andy******* (andy*********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by chris-grove** [comment]
My email response:
"""
Apologies for any misinformation we are displaying. Can you specify where exactly you see this association with NCI? It seems that all of your contact information is up-to-date in our database, and I can't find any such association displayed on the kqt-3 gene page.
"""

**Comment by chris-grove** [comment]
Communicated with user. The ?Laboratory object needs to be updated:

https://wormbase.org/resources/laboratory/AG#03451--10

<img width="632" alt="Screenshot 2019-05-30 11 29 15" src="https://user-images.githubusercontent.com/611382/58643933-47bdb680-82ce-11e9-9f98-1a0966a1c417.png">

**Comment by ceciliaWBPerson1** [comment]
Lab data was supposed to be pulled from Person data. Anyway I updated it .

**Comment by chris-grove** [comment]
@ceciliaWBPerson1 
Is this an indication that some pipeline is broken?
