### ISSUE TITLE
  i am retired and am unsure of what is...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7149]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;i am retired and am unsure of what is requested with regard to the 90 papers listed</p><p>What were you doing? <br />&nbsp;&nbsp;looking over the online forms</p>

**Reported by:** Tom ******* (john*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by chris-grove** [comment]
My email response to user:
"""
 There are 46 papers of yours that our paper analysis pipelines have predicted have phenotype data, 33 of which are predicted to have allele phenotypes that are still in need of curation at WormBase and 8 of which are predicted to have RNAi phenotypes that are still in need of curation. We are just asking, if you feel so inclined, if you could use the phenotype form (or the provided worksheet) to submit any important or novel phenotypes to WormBase for these papers.

We would like to manually curate these papers ourselves, but the rate at which papers are published preclude us from keeping up to date with all phenotype curation ourselves, hence the request to authors (like yourself) to help us get up-to-date.

If you would prefer not to be contacted about this, we can certainly stop any future emails from being sent to you in this regard.
"""
