### ISSUE TITLE
(ParaSite) species_tree JSON SpeciesLanding page URL problem

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#7152]
Hi @khowe there seems to be a problem with the ParaSite species tree json: https://parasite.wormbase.org/Multi/Ajax/species_tree . The SpeciesLanding page url is **different between requests** for species that has multiple bioprojects. 

My development server regularly fetches the species_tree and saves a local copy, so I can see when this file changes and commit it. The problem is that the file is now constantly shown as changed due to this problem, requiring extra effort to exclude them when committing changes or switching branches.

Is it possible to have the SpeciesLanding url return the same value?

Thanks!

![Screen Shot 2019-05-31 at 4 24 14 PM](https://user-images.githubusercontent.com/1753893/58732782-8d5aac00-83c0-11e9-90a9-fe3460fac04b.png)
![Screen Shot 2019-05-31 at 4 20 04 PM](https://user-images.githubusercontent.com/1753893/58732784-8d5aac00-83c0-11e9-976d-3d3ec16fabef.png)

![Screen Shot 2019-05-31 at 4 37 13 PM](https://user-images.githubusercontent.com/1753893/58733426-8339ad00-83c2-11e9-8d57-62cabed02753.png)

**Comment by sibyl229** [comment]
@khowe Actually, don't worry about this. I worked around the problem, since the website doesn't use the species landing page URL. I will close the issue.

**Comment by wbazant** [comment]
@sibyl229 I think the endpoint replies with unsorted keys. It's just to feed the species page, and there's no reason to keep it stable, actually I'm pretty sure it will go away in sometime in early 2021.

Would you instead use `https://parasite.wormbase.org/rest/documentation/info/species` ? If you need a tree, there's also a "taxonomy" endpoint `https://parasite.wormbase.org/rest-13/documentation/info/info_genomes_taxonomy ` which you can ask for Nematoda and Platyhelminthes.

**Comment by sibyl229** [comment]
Thanks Wojtek for the info and speedy reply! Looks like I should be using
the rest/info endpoint. I will migrate to that at some point. Right now I
have been sorting the child nodes in the species tree and remove the
species landing page URL, which takes different but equally valid values
between refreshes.
