### ISSUE TITLE
  download the sequence.   What were yo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7154]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;download the sequence. </p><p>What were you doing? <br />&nbsp;&nbsp;I don't know how to download the actual sequence in the current genome browser. I know there was a button for it in the previous one. Say I would like to copy the sequence of the Chr I: 1000-5000 base. Thanks!</p>

**Reported by:** Ken **** (noma******************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by scottcain** [comment]
Replied to the user:

Hello Ken,

Since we've been getting this question a lot, I wrote a blog post about it:

http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

Please let me know if you have any questions about this functionality,
