### ISSUE TITLE
I just set up a worm lab in Nanchang University, C...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7155]
*Help Desk query collected when no chat operators were online. Follow up required.*

I just set up a worm lab in Nanchang University, China. How should I name the alleles generated in my lab?

**Reported by:** Fei **** (feic**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/laboratory#012--10">https://wormbase.org/resources/laboratory#012--10</a>
**Browser:** Chrome 74.0.3729.157

**Comment by Paul-Davis** [comment]
Congratulations on your new lab.

I an CC'ing the genenames list where you can request a new Lab and 
allele designation.

Paul


On 02/06/2019 16:04, no-reply@wormbase.org wrote:
> offline chat I just set up a worm lab in Nanchang University, China. 
> How should I name the alleles generated in my lab?
>
> Submitted From:
>   https://wormbase.org/resources/laboratory#012--10 
> https://wormbase.org/resources/laboratory#012--10 
> <http://www.wormbase.org/https://wormbase.org/resources/laboratory#012--10> 
>
>
> This issue has been assigned ticket number: #7155. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7155>.
>
> Reported by: Fei Chen (feichen@ncu.edu.cn)
> 02 Jun 19 15:04
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
