### ISSUE TITLE
  C. elegans strain (BR5706) 1) Where i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7163]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;C. elegans strain (BR5706)<br/>1) Where is the F3 expressed?<br/>2) What exactly is this F3 fragment of the human Tau protein that is deleted?<br/>3) Where is the marker expressed?<br/>4) Why was mutation of the human Tau  choosen to occur at F3 ?</p>

**Reported by:** Rebe********** (rebe*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by raymond91125** [comment]
Likely homework/exam related questions. Not pertinent to WormBase.
