### ISSUE TITLE
  Good Afternoon, I'm an exchange stude...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7167]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good Afternoon,<br/>I'm an exchange student form the University of Strasbourg (France) doing research for my master's degree at the University of Florida.<br/>I’m currently focusing on characterizing genes located specifically in Lysosome Related Organelles (LROs) in C. elegans. I’ve been searching literature and gathering information about genes that express in the LROs but I was wondering if there is any other good source available where I can get a list of genes that are found in the Lysosome. I know Wormbase has various tools to look for genes and their expression profiles in various tissues. It would be really helpful, if you can suggest me any list of genes which are annotated for lysosomal expression or may be some databases where I can search for specific LRO genes?<br/>Thank you for your time and I highly appreciate it,<br/>with kind regards, <br/>visitor_name</p><p>What were you doing? <br />&nbsp;&nbsp;LROs are essential for aging, metabolism and pheromone productions in C. elegans. There are a lot of genes in LROS which are uncharacteristic and might play crucial role in pheromone productions. This in term can affect the growth and behavior of the animal. I’m trying to characterize individual genes that expresses in LROs using RNAi based screening method.</p>

**Reported by:** Cand********* (cand************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Comment by chris-grove** [comment]
My email response:
"""
The quickest way to get this list is to go to the WormBase page for the Gene Ontology term "lysosome":

https://wormbase.org/species/all/go_term/GO:0005764#02--10

In the "Ontology Browser" widget you will see a link to the right of the term "lysosome" that reads "136 gene products (123 direct)". Click on that and you will be directed to a page summarizing the lists of these genes, including a specific one for C. elegans.

You can also use WormMine to query for these same genes (100 C. elegans genes):

http://intermine.wormbase.org/tools/wormmine/begin.do

Go to the "QueryBuilder" tab, click on "Import query from XML" and paste in the following XML:

`<query name="" model="genomic" view="GOTerm.relations.childTerm.ontologyAnnotations.subject.primaryIdentifier GOTerm.relations.childTerm.ontologyAnnotations.subject.secondaryIdentifier GOTerm.relations.childTerm.ontologyAnnotations.subject.symbol GOTerm.relations.childTerm.identifier GOTerm.relations.childTerm.name" longDescription="Return all is_a descendants of a GO term" constraintLogic="(B or C) and D and A">
  <constraint path="GOTerm.relations.relationship" code="B" op="=" value="is_a"/>
  <constraint path="GOTerm.relations.relationship" code="C" op="=" value="part of"/>
  <constraint path="GOTerm.relations.childTerm.ontologyAnnotations.subject.organism.name" code="D" op="=" value="Caenorhabditis elegans"/>
  <constraint path="GOTerm.name" code="A" op="=" value="lysosome"/>
</query>`

This will return the list of all C. elegans genes annotated to the GO term "lysosome" or any of its parts or subclasses.

Also, you might find this section of WormBook helpful:

http://www.wormbook.org/chapters/www_intestine/intestine.html#sec4_4

Let us know if you have any questions.
"""
