### ISSUE TITLE
  Search for  transmembrane proteins th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7169]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Search for  transmembrane proteins that express in the intestine and the excretory canal? or intestinal apical and basolateral membrane proteins.</p><p>What were you doing? <br />&nbsp;&nbsp;searching transmembrane proteins that express in the intestine and the excretory canal</p>

**Reported by:** Liak******* (mlkh******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
 WormBase does not have an easy way to search for transmembrane proteins at the moment, but you could query the UniProt database to get the list of known and predicted transmembrane proteins in C. elegans:

https://www.uniprot.org/uniprot/?query=annotation%3A%28type%3Atransmem%29+AND+organism%3A%22Caenorhabditis+elegans+%5B6239%5D%22&sort=score

You can import the UniProt IDs from that list into WormBase ParaSite BioMart:

https://parasite.wormbase.org/biomart/martview

to get the WormBase gene IDs (note that BioMart recognizes UniProtKB SwissProt and TrEMBL IDs independently, so you will need to run two queries). I've attached the resulting non-redundant list of 5,486 genes in the file called "C_elegans_transmembrane_protein_genes_June_14_2019.txt".

Next, to get the list of genes annotated to be expressed in the intestine (or any part of the intestine) you should visit the WormBase page for the anatomy term "intestine":

https://wormbase.org/species/all/anatomy_term/WBbt:0005772#04--10

In the "Ontology Browser" widget, you can click on the link next to the "intestine" term "[6906 gene products (6772 direct)]" and on the subsequent page download the gene list for "Directly annotated" annotations (file attached). Then next to "intestinal cell" click on the link "[175 gene products (153 direct)]" and on the subsequent page download the "Directly annotated + Inferred" file (attached).

Next, go to the WormBase page for the "excretory canal":

https://wormbase.org/species/all/anatomy_term/WBbt:0005775#04--10

and follow the same steps above to get the list of 91 genes annotated to be expressed in the excretory canal (file attached).

Now, if you're looking for genes that encode transmembrane proteins AND are expressed in the intestine AND are expressed in the excretory canal, you can use WormMine:

http://intermine.wormbase.org/tools/wormmine/begin.do

or some other list processing tool to get the list:

(transmembrane) AND (intestine(direct) OR intestinal_cell) AND (excretory_canal)

Further, if you want genes that have been annotated as localized to the apical and/or basolateral membranes of the intestine you can acquire the list of apical and basolateral protein genes from the respective Gene Ontology pages at WormBase:

apical plasma membrane:
https://wormbase.org/species/all/go_term/GO:0016324#02--10

basolateral plasma membrane:
https://wormbase.org/species/all/go_term/GO:0016323#02--10

and acquire the respective gene lists using the Ontology Browser widget as described above and then perform the union and intersection analysis of the appropriate lists to get your resulting gene list.

I hope that helps. Let us know if you need further assistance.
"""
