### ISSUE TITLE
Remove strain OH?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#7170]
The new Author First Pass pipeline extracted 'OH' as a valid WB strain name, but it looks like we don't have any associated data, other than species, for that object in WB.

https://wormbase.org/species/c_elegans/strain/OH

![image](https://user-images.githubusercontent.com/1730534/59529548-55b72e00-8eaf-11e9-8342-f3fcdee13a41.png)

Does anyone know more about this strain object?  OH is the laboratory designation for Oliver Hobert, so perhaps this was meant to be a strain object from his lab that lost the corresponding numbers.

Would it be okay to remove it?

**Comment by paulwsternberg** [comment]
Ohio??

Paul

On Jun 14, 2019, at 11:24 AM, vanaukenk <notifications@github.com<mailto:notifications@github.com>> wrote:


The new Author First Pass pipeline extracted 'OH' as a valid WB strain name, but it looks like we don't have any associated data, other than species, for that object in WB.

https://wormbase.org/species/c_elegans/strain/OH

[image]<https://user-images.githubusercontent.com/1730534/59529548-55b72e00-8eaf-11e9-8342-f3fcdee13a41.png>

Does anyone know more about this strain object? OH is the laboratory designation for Oliver Hobert, so perhaps this was meant to be a strain object from his lab that lost the corresponding numbers.

Would it be okay to remove it?

**Comment by Paul-Davis** [comment]
Removed the OH Strain, had a look for the origin, but other than :cough: my timestamp there is nothing associated with it.
