### ISSUE TITLE
visitor_name (visitor_email): Hi! I am retrieving ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7173]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi! I am retrieving duplicated genes (uggt-1 WBGene00018604 and uggt-2 WBGene00009178) from different Caenorhabditis species and I have a question.
In C. sinica I find two proximal sequences with identical coding sequences:  Csp5_scaffold_00456.g11627  y Csp5_scaffold_00456.g11618
It seems to be an artifact, but I wanted to rule out if it is the product of a local duplication</br>Chris: Hmm, I'm not sure. Let me ask our sequence curators if they have any indication if this is an artifact or not</br>Chris: When we're done chatting and we both get the transcript emailed to us, I will forward the message to our sequence curators to see what they say</br>Chris: Is that OK?</br>visitor_name (visitor_email): Yes!</br>visitor_name (visitor_email): Thanks in advance!</br>Chris: OK sounds good. I'll end the chat now, and then email you along with the sequence curators</br>visitor_name (visitor_email): Ok. Thank you!

**Reported by:** Dieg* (exce*********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/support?url=/">https://wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 74.0.3729.169

**Comment by raymond91125** [comment]
Hi Chris, Diego,

Michael is off sick at the moment.

I've not been involved in setting up the C. sinica data, so I don't know the quality of the assembly.

I've taken a look at the scaffold 'Csp5_scaffold_00456' and it is an exact inverted repeat totalling 47.3 Kb (two halves of 23.6 Kb) - this looks like an assembly artefact to me.

They are artefactual duplicates.

Gary
