### ISSUE TITLE
How do I get a list of all genes of Haemonchus con...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7176]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I get a list of all genes of Haemonchus contortus with no human homologs? If there is no possible, how it is possible to do it using C. elegans instead, pease?

**Reported by:** Alex************ (alex************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00001564#0643-g5hi-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00001564#0643-g5hi-3</a>
**Browser:** Chrome 74.0.3729.169

**Comment by chris-grove** [comment]
My email to user:
"""
You can perform this query using WormBase ParaSite BioMart:

https://parasite.wormbase.org/biomart/martview

In the "Query Filters" options, in the "HOMOLOGY (ORTHOLOGUES AND PARALOGUES)" section, make sure to check the checkbox for "Restrict results to genes without orthologues in..." and then select "Human" as your species. Here's the query result:

https://bit.ly/2FnASyS

Let us know if you have any questions.
"""
