### ISSUE TITLE
  Why do I couldn't found both gene seq...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7178]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Why do I couldn't found both gene sequence and mRNA sequence in the sequences search results of certain gene?</p><p>What were you doing? <br />&nbsp;&nbsp;designing primer for RT-qPCR</p>

**Reported by:** Fari**************** (fsni***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
You can acquire mRNA and gene sequences from the "Sequences" widget on gene pages. For example:

https://wormbase.org/species/c_elegans/gene/WBGene00003912#0g--10

Click on the double-helix icon next to the transcript names and you can get access to the gene sequence (unspliced + UTR) and the transcript (mRNA) sequence (spliced + UTR).

Let us know if you have any questions.
"""
