### ISSUE TITLE
  Hello, I am looking for a way to iden...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7179]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I am looking for a way to identify a list of proteins that are localized to the nucleus. Is there a way to do that through this platform?</p>

**Reported by:** Will*** (wmm2**********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
There are two ways to get this information.

1) First, and my recommendation, is to visit the Gene Ontology term WormBase page for the term "nucleus":

https://wormbase.org/species/all/go_term/GO:0005634#02--10

In the "Ontology Browser" widget, click on the link next to the term "nucleus" with text:

[7717 gene products (5716 direct)]

This will direct you to a page providing gene lists including C. elegans genes and non-elegans genes. For completeness, select the list(s) marked as "Directly annotated + Inferred".

2) Second, and not as thorough or accurate, is to use a WormMine template query for genes with a particular subcellular location:

http://intermine.wormbase.org/tools/wormmine/begin.do

Click on the tab called "EXPRESSION" (mid-way down the page), then click on the template query titled "Subcellular compartment --> Genes". The default constraint is to "nucleus" so you can just click on "Show results". This will return a table of genes which you can export in your preferred format.

Let us know if you have any additional questions.
"""
