### ISSUE TITLE
  Hello, I have newly established my la...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7185]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I have newly established my laboratory at the University of Tulsa. Could you kindly let me know what the procedure is to apply for a new alphabetical lab code and an allele designation for strains made in my lab? If possible, I would like to propose an alphabetical lab code IYR and an allele designation ji. Thank you very much for your help.<br/>Best Regards,<br/>Jyoti.</p>

**Reported by:** Jyot****** (jgi2**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by chris-grove** [comment]
Response to user by @ceciliaWBPerson1 
"""
Congratulations on your new lab!

The link to users guide is not working at the moment, please see below and write to genenames@wormbase.org.
https://wormbase.org/about/userguide/nomenclature

How to Register a New Laboratory and Receive Lab, Strain and Allele designations
WormBase assigns specific identifying codes to each laboratory engaged in dedicated long-term genetic research on C. elegans. Each laboratory is assigned a laboratory/strain code for naming strains, and an allele code for naming genetic variation (e.g., mutations) and transgenes. These designations are assigned to the laboratory head/PI who is charged with supervising their organization in laboratory databases and their associated biological reagents that are described on WormBase, in publications, and distributed to the scientific community on request. The laboratory/strain code is used (a) to identify the originator of community-supplied information on WormBase, which in addition to attribution facilitates communications between the community/curators and the originator if an issue related to the information should arise at a later date, and (b) provide a tracking code for activities at the CGC. The laboratory/strain designation consists of 2-3 uppercase letters while the allele designation has 1-3 lowercase letters. The final letter of a laboratory code should not be an “O” or an “I” so as not to be mistaken for the numbers “0” or “1” respectively. Additionally, allele designations should also not end with the letter “l” which could also be mistaken for the number “1.” These codes are listed at the CGC and in WormBase.
Investigators generating strains, alleles, transgenes, and/or defining genes require these designations and should apply for them at genenames@wormbase.org.

Thanks 
"""
