### ISSUE TITLE
Make anatomy term synonyms searchable from WB search box

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7190]
Currently, users cannot find an anatomy term page by searching for that anatomy term's synonyms. For example, searching for "RnB", a synonym of "ray neuron type B", does not return any results when searching "for an anatomy term". Here is the page for "ray neuron type B":

https://wormbase.org/species/all/anatomy_term/WBbt:0006973#041--10

Another example, "intestine" will find the page for intestine:

https://wormbase.org/species/all/anatomy_term/WBbt:0005772#041--10

but searching by its synonyms "gut" or "mesenteron" will not.

**Comment by paulwsternberg** [comment]
Great point!!

Paul

On Jun 26, 2019, at 12:14 PM, Chris Grove <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, users cannot find an anatomy term page by searching for that anatomy term's synonyms. For example, searching for "RnB", a synonym of "ray neuron type B", does not return any results when searching "for an anatomy term". Here is the page for "ray neuron type B":

https://wormbase.org/species/all/anatomy_term/WBbt:0006973#041--10

Another example, "intestine" will find the page for intestine:

https://wormbase.org/species/all/anatomy_term/WBbt:0005772#041--10

but searching by its synonyms "gut" or "mesenteron" will not.

**Comment by sibyl229** [comment]
Hi @chris-grove searching for `rnb` and `gut` should find the right anatomy term on staging now. Could you take a look please? Thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks great! Thanks!
