### ISSUE TITLE
c_elegans functional descriptions file does not have any descriptions

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#7200]
The file c_elegans.PRJNA13758.WS272.functional_descriptions.txt at
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS272/species/c_elegans/PRJNA13758/annotation/
does not have any descriptions, I'm guessing because of the PRJEB28388 genes and the lack of the WBGenes.  I'm guessing this was not meant to be created this way?  Shouldn't this file have had all the concise and automated descriptions for c_elegans WBGenes?

**Comment by epaule** [comment]
Hi Ranjana,

that looks like it is broken since WS269. I fixed the script and will
redump the files.
We might have to resync the ftp site for 272 afterwards.

Michael

**Comment by epaule** [comment]
Ok, all done.
Can the webteam resync 272 ? @tharris 

thanks,
M

**Comment by scottcain** [comment]
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS272/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS272.functional_descriptions.txt.gz is now on the ftp site.
