### ISSUE TITLE
hellow, i want know why ftp.wormbase.org/pub/wormb...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7202]
*Help Desk query collected when no chat operators were online. Follow up required.*

hellow, i want know why ftp.wormbase.org/pub/wormbase/genomes/
c_elegans/annotations/WS201_elegans_SNP_changes.txt.gz is not found? i needs this file to WGS-sequencing results analysis. Thank you!

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/pub/wormbase/genomes/c_elegans/annotations/WS201_elegans_SNP_changes.txt.gz">https://wormbase.org/pub/wormbase/genomes/c_elegans/annotations/WS201_elegans_SNP_changes.txt.gz</a>
**Browser:** Chrome 75.0.3770.100

**Comment by chris-grove** [comment]
Duplicate tickets:
#7202
#7203 
#7205 
#7206 
#7207 
#7209 
#7210 
Issue addressed closing.
