### ISSUE TITLE
oh,thank you. But I opened this link to display: T...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7203]
*Help Desk query collected when no chat operators were online. Follow up required.*

oh,thank you. But I opened this link to display: The page at ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz may be temporarily unavailable, or it has been permanently moved to the new URL.

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Chrome 75.0.3770.100

**Comment by scottcain** [comment]
Based on later issues submitted by this users, this got sorted out.

**Comment by chris-grove** [comment]
Duplicate tickets:
#7202
#7203 
#7205 
#7206 
#7207 
#7209 
#7210 
Issue addressed closing.
