### ISSUE TITLE
hello,  i want know why ftp.wormbase.org/pub/wormb...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7205]
*Help Desk query collected when no chat operators were online. Follow up required.*

hello,  i want know why ftp.wormbase.org/pub/wormbase/genomes/ c_elegans/annotations/WS201_elegans_SNP_changes.txt.gz and ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz is not found? i needs this file to WGS-sequencing results analysis. Can I open such a link withｇｏｏｇｌｅ　ｃｈｒｏｍｅ ?

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00022275#04ce-9g16-3">https://wormbase.org/species/c_elegans/gene/WBGene00022275#04ce-9g16-3</a>
**Browser:** Chrome 75.0.3770.100

**Comment by scottcain** [comment]
Based on later issues submitted by this users, this got sorted out.

**Comment by chris-grove** [comment]
Duplicate tickets:
#7202
#7203 
#7205 
#7206 
#7207 
#7209 
#7210
