### ISSUE TITLE
  Hello, excuse me i want know why ftp....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7206]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, excuse me<br/>i want know why ftp.wormbase.org/pub/wormbase/genomes/ c_elegans/annotations/WS201_elegans_SNP_changes.txt.gz or ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz is not found? I opened this link to display: The page at ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz may be temporarily unavailable, or it has been permanently moved to the new URL. i needs this file to WGS-sequencing results analysis. Can I open such a link with google chrome? Or have a file of N2 and CB4856 SNP differences at each locus is ok. Thank you very much!</p><p>What were you doing? <br />&nbsp;&nbsp;I am using WGS-SNP strategy(Doitsidou et al. 2010) to identify mutants.</p>

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by chris-grove** [comment]
Duplicate tickets:
#7202
#7203 
#7205 
#7206 
#7207 
#7209 
#7210 
Issue addressed closing.
