### ISSUE TITLE
  Hi, excuse me. Happy National day Tha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7207]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, excuse me. Happy National day<br/>Thank you for providing me with this file(<br/>ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz). But I also want to know the location of each SNP to analysis the WGS data.So I want to know if there are files with SNP differences between N2 and CB4856 like the above file and contain the location of each SNP</p><p>What were you doing? <br />&nbsp;&nbsp;I'm using WGS-SNP Strategy(Doitsidou et al. 2010) to identify mutant.</p>

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by scottcain** [comment]
@Paul-Davis does such a file exist or can it be created?

**Comment by Paul-Davis** [comment]
Tickets #7209 and #7210 are duplicates of this ticket, looking into answering this one so will close the others

**Comment by Paul-Davis** [comment]
Dear Yang,

Thank you for your email, The CB4856 snp location data can be extracted 
directly from the annotations gff file.

ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz

If you extract all the lines with CB4856 this should give you the data 
you require.

Paul



On 05/07/2019 07:54, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi, excuse me. Happy National day
> Thank you for providing me with this file(
> ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz). 
> But I also want to know the location of each SNP to analysis the WGS 
> data.So I want to know if there are files with SNP differences between 
> N2 and CB4856 like the above file and contain the location of each SNP
>
> What were you doing?
>   I'm using WGS-SNP Strategy(Doitsidou et al. 2010) to identify mutant.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7207. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7207>.
>
> Reported by: Yang yang (15751005343@163.com)
> 05 Jul 19 06:54
>
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/75.0.3770.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
Duplicate tickets:
#7202
#7203 
#7205 
#7206 
#7207 
#7209 
#7210

**Comment by Paul-Davis** [comment]
Response from the user:

Thank you very much!
