### ISSUE TITLE
  Hi, excuse me.  Thank you for providi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7209]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, excuse me. <br/>Thank you for providing me with this file(<br/>ftp://wormbase.org/pub/wormbase/species/c_elegans/annotation/WS201_elegans_SNP_changes.txt.gz). But I also want to know the location of each SNP to analysis the WGS data.So I want to know if there are files with SNP differences between N2 and CB4856 like the above file and contain the location of each SNP</p><p>What were you doing? <br />&nbsp;&nbsp;I am using WGS-SNP Strategy(Doitsidou et al. 2010) to identify mutant.</p>

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by chris-grove** [comment]
Duplicate tickets:
#7202
#7203 
#7205 
#7206 
#7207 
#7209 
#7210
