### ISSUE TITLE
  How do I get all RNAi ids for a given...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7211]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get all RNAi ids for a given target gene (ex apl-1)?</p><p>What were you doing? <br />&nbsp;&nbsp;Couldnt find any rest call to give me the list of RNAi IDS for a given gene target so I tried to parse the reponses from https://www.wormbase.org/search/rnai/apl-1 by hitting
https://www.wormbase.org/search/rnai/apl-1/1?&inline=1,
https://www.wormbase.org/search/rnai/apl-1/2?&inline=1,
https://www.wormbase.org/search/rnai/apl-1/3?&inline=1.
This allows me to regex out what I need but it is an issue programmatically due to the pagination. To handle pages I used https://www.wormbase.org/search/count//rnai/apl-1 to give me total count (to then divide by 10 and obtain number of pages) which doesnt work consistently due to some inconsistent format in responses like 2K, 600+, etc. Any suggestions?</p>

**Reported by:** Dhru******* (dhru********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by nuin** [comment]
Answer to the user

Hi Dhruv

One way to conduct larger queries would be through WormMine (http://intermine.wormbase.org). There are many ways to search the model and most of the structure/items you see on WormBase are linked in WormMine. 

The simplest query you can run checks for the association between genes and RNAi that inhibits each gene, and this can be achieved by using the below XML code in the QueryBuilder of WormMine (click on Import XML Query)

```
<query model="genomic" view="Gene.name Gene.primaryIdentifier Gene.RNAiResult.primaryIdentifier" sortOrder="Gene.name ASC" >
  <join path="Gene.RNAiResult" style="OUTER"/>
  <constraint path="Gene.organism.species" op="=" value="elegans" code="A" />
</query>
```

This will result in a table with three columns 

Gene Name
WormBase Gene ID 
RNAi result (each row is a collection of RNAi that interfere with the corresponding gene)

It will display empty results (as no RNAi inhibit the genes) and you can modify the query or manipulate the table to export/download only the data you want. There’s an API available too, and you can generate code for this query (modified or not) in different languages.

I don’t know if I captured the results you want or need, but we can work on tailoring the query to your desired results.

Let me know how further we can help you.

Cheers
Paulo

**Comment by nuin** [comment]
User response

```
Hey,
 
Thanks Paulo, thanks for the quick response. That does give me what I need. I believe the way I was trying before gave me some irrelevant results.
 
As just an aside suggestion – it might be more consistent to respond with actual number of results rather than 600+, 2K, etc. on the search field of the home page.
 
Many thanks,
Dhruv
```
