### ISSUE TITLE
?...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7213]
*Help Desk query collected when no chat operators were online. Follow up required.*

?

**Reported by:** RuiS**** (gris****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Firefox 67.0

**Comment by chris-grove** [comment]
My email response:
"""
Did you have a question for WormBase staff?
"""
