### ISSUE TITLE
  Hello, thank you very much for your r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7216]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, thank you very much for your reply！<br/>I want to know the reference genome in this file(ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz)  is Bristal(N2) or hawaiial(CB4856)?</p><p>What were you doing? <br />&nbsp;&nbsp;I'm using WGS-SNP Strategy(Doitsidou et al. 2010) to identify mutant.</p>

**Reported by:** yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Yang,

The reference genome in the annotation file is the Bristol N2 (PRJNA13758).

Paul


On 10/07/2019 03:37, no-reply@wormbase.org wrote:
> Question:
>
>   Hello, thank you very much for your replyï¼
> I want to know the reference genome in this 
> file(ftp://ftp.wormbase.org/pub/wormbase/releases/WS250/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS250.annotations.gff3.gz) 
> is Bristal(N2) or hawaiial(CB4856)?
>
> What were you doing?
>   I'm using WGS-SNP Strategy(Doitsidou et al. 2010) to identify mutant.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7216. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7216>.
>
> Reported by: yang yang (15751005343@163.com)
> 10 Jul 19 02:37
>
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/75.0.3770.100 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
