### ISSUE TITLE
  At the workshop you showed how to dis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7217]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;At the workshop you showed how to display a gene sequence in a separate window and then give the 5' us and 3' ds sequences attached to it.  </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to get lim-7 sequence "easily"</p>

**Reported by:** Laur************ (biol**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Comment by chris-grove** [comment]
My email response:
"""
Here's a screen recording of how to do it:

https://www.dropbox.com/s/e599otl7u5vgg9t/Getting_lim-7_gene_sequence_upstream_and_downstream_July_15_2019.mov?dl=0

Briefly, you want to right-click on the gene model in the "Curated Genes" track in JBrowse, then select "View Sequence" and then you can visualize and manipulate the sequence of the gene from there.

Also, we will soon upload video from the IWM workshop to our WormBase YouTube channel:

https://www.youtube.com/user/WormBaseHD

So keep an eye out for the new video(s).

Please let us know if you have any more questions about that.
"""
