### ISSUE TITLE
Firefox: copying colored transcript sequences does not work

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7219]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase Team,<br/>in the new version (WS271) of WormBase it seems to be impossible to copy the sequences of the transcripts including the colour-formats to word. By using the old version, I could always copy the yellow and orange appearance of the different exons to word which was very helpful and which seems not to work anymore. Could you please change that back? Thanks a lot!<br/>Nadine</p>

**Reported by:** Nadi******* (nadi********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by chris-grove** [comment]
Email response from @a8wright 
"""
Thank you for writing. I am one of the software developers on the UI team.

I just tested this issue locally and have found that copying from
chrome preserves the color formatting but firefox does not.

We will continue to look into this issue to see if there is a solution
we can implement to make it work in Firefox as well.

In the meantime, hopefully, you are able to use chrome to get your
formatted sequences.
"""

**Comment by tharris** [comment]
This is a very browser specific use case, expecting a copy-paste operation to preserve styling via CSS. Closing, as I believe this to be un-resolveable as stated, but with (for now) a reasonable work around.
