### ISSUE TITLE
  Why was the name fig-4 removed from C...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7221]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Why was the name fig-4 removed from C34B7.2 ?<br/>It's clearly an ortholog of human FIG4 and studies ongoing in my lab suggest interactions with other ALS genes.<br/>Thanks for clarifying/correcting<br/>Anne</p>

**Reported by:** Anne***** (anne***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by epaule** [comment]
I couldn't find anything about C34B7.2 being named fig-4 in the past (as it should be in the gene history widget).
But I am reasonably sure it couldn't be named like that, as the fig gene class in C.elegans stands for "dye-Filling abnormal, expressed In Glia" which is notably different to "phosphoinositide 5-phosphatase" used by HGNC.
The fig gene class was based on the Bacaj et al. Science paper from 2008 https://wormbase.org/resources/paper/WBPaper00032317 so it would be very confusing for people to mix the classes more than a decade after it has been published.
