### ISSUE TITLE
  OOPS! Please ignore the last question...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7222]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;OOPS! Please ignore the last question about C34B7.2<br/>I'll contact Tim S about naming it</p>

**Reported by:** Anne***** (anne***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by epaule** [comment]
duplicate
