### ISSUE TITLE
  How do I get a WBperson name   for a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7223]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get a WBperson name   for a new member of the lab?  Thank you</p><p>What were you doing? <br />&nbsp;&nbsp;submitting a micropublication</p>

**Reported by:** Alej***** (alec*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by kyook** [comment]
same person who submitted #7224
