### ISSUE TITLE
how do i get a WBperson name for a new student in ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7224]
*Help Desk query collected when no chat operators were online. Follow up required.*

how do i get a WBperson name for a new student in the lab

**Reported by:** olga******* (alec*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/support">https://www.wormbase.org/tools/support</a>
**Browser:** Chrome 75.0.3770.142

**Comment by Paul-Davis** [comment]
Dear Olga,

If you send the details of the Student to the genenames@wormbase.org list (cc'd) the person responsible for assigning names will get back to you with their WBPerson number.

Thank you for contacting WormBase

Paul

**Comment by Paul-Davis** [comment]
I'll let @ceciliaWBPerson1 close the ticket when the ID has been created.

**Comment by ceciliaWBPerson1** [comment]
done
