### ISSUE TITLE
  Is it possible to identify transgenes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7226]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is it possible to identify transgenes that express any fluorophore that are integrated in a certain chromosomal region (around V:8640700..10279800)? I'm trying to map an EMS-generated allele and this would be great for fine-mapping it. <br/>Thanks!<br/>Best, <br/>Tina</p><p>What were you doing? <br />&nbsp;&nbsp;Going one by one through the genes in the region and trying to find reagents with CRISPR'd fluorescent transgenes is time-consuming. </p>

**Reported by:** Tina************ (tgum*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15

**Comment by kyook** [comment]
Hi Tina,

Sorry for the late reply.  Unfortunately, integrated transgenes have
not be mapped to the genome so cannot be easily searched. I am hoping
my colleague, Paul Davis, might be able to help you pull out CRISPR
alleles for the region you are looking if they do exist.

Best wishes,
Karen

~~~~
Karen Yook

Curator / Editor
WormBase Caltech / microPublication
email: kyook@caltech.edu
email: karen@wormbase.org
email: karen.yook@micropublication.org
skype name: wbkaren
tel: +1(415)306-4150


On Fri, Jul 19, 2019 at 12:48 PM <no-reply@wormbase.org> wrote:
>
> How Do I ...?
>
>   Is it possible to identify transgenes that express any fluorophore that are integrated in a certain chromosomal region (around V:8640700..10279800)? I'm trying to map an EMS-generated allele and this would be great for fine-mapping it.
> Thanks!
> Best,
> Tina
>
> What were you doing?
>   Going one by one through the genes in the region and trying to find reagents with CRISPR'd fluorescent transgenes is time-consuming.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #7226. Follow progress on our issue tracker.
>
> Reported by: Tina L. Gumienny (tgumienny@twu.edu)
> 19 Jul 19 19:48
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

**Comment by kyook** [comment]
Karen, Paul,

Thanks! If you can pull out CRISPR’d alleles with some fluorescent protein coding region insertion in that region, that’d be fantastic!

Tina

**Comment by tharris** [comment]
@Paul-Davis Pending \ resolved \ unresolvable?

**Comment by kyook** [comment]
resolved
