### ISSUE TITLE
I want to find "Expressed in",but not every gene h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7228]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to find "Expressed in",but not every gene have it,why?

**Reported by:** Sure***** (1569*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00019081#10fg--10">https://www.wormbase.org/species/c_elegans/gene/WBGene00019081#10fg--10</a>
**Browser:** Chrome 63.0.3239.132

**Comment by kyook** [comment]
Hi Surenjing,

Would you clarify what you are looking for?  Are you trying to find
expression reports for a particular gene?  We only report data that
are generated by worm researchers and that we know about, if you see
that we are missing expression data it would be very helpful if you
could send us the paper that discusses them. I hope that helps.

Best,
Karen
~~~~
Karen Yook

Curator / Editor
WormBase Caltech / microPublication
email: kyook@caltech.edu
email: karen@wormbase.org
email: karen.yook@micropublication.org
skype name: wbkaren
tel: +1(415)306-4150

On Sat, Jul 20, 2019 at 7:15 PM <no-reply@wormbase.org> wrote:
>
> offline chat I want to find "Expressed in",but not every gene have it,why?
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans/gene/WBGene00019081#10fg--10 https://www.wormbase.org/species/c_elegans/gene/WBGene00019081#10fg--10
>
> This issue has been assigned ticket number: #7228. Follow progress on our issue tracker.
>
> Reported by: Surenjing (1569815520@qq.com)
> 21 Jul 19 02:15
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
