### ISSUE TITLE
Since the webpage changed, I no longer know how to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7229]
*Help Desk query collected when no chat operators were online. Follow up required.*

Since the webpage changed, I no longer know how to download the sequence flanking a mutation. It was very useful.

**Reported by:** Carl* (c.ll**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar00090602#02-45-3">https://www.wormbase.org/species/c_elegans/variation/WBVar00090602#02-45-3</a>
**Browser:** Chrome 75.0.3770.142

**Comment by Paul-Davis** [comment]
Dear Carla,

Thank you for getting in touch with us.

If you open the Molecular details widget from the left hand menu you are 
presented with the wildtype sequence and the mutant sequence, if you 
click on the download icon to the right of the header to the sequence 
you require this will give you a fasta file containing the mutant 
sequence with 500bp flanks.

I hope this answers your question.

Paul



On 22/07/2019 11:33, no-reply@wormbase.org wrote:
> offline chat Since the webpage changed, I no longer know how to 
> download the sequence flanking a mutation. It was very useful.
>
> Submitted From:
>   https://www.wormbase.org/species/c_elegans/variation/WBVar00090602#02-45-3 
> https://www.wormbase.org/species/c_elegans/variation/WBVar00090602#02-45-3 
> <http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar00090602#02-45-3> 
>
>
> This issue has been assigned ticket number: #7229. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7229>.
>
> Reported by: Carla (c.lloret@ucl.ac.uk)
> 22 Jul 19 10:33
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
