### ISSUE TITLE
How do I find all the genes with WBPhenotype 00012...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7230]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I find all the genes with WBPhenotype 0001259

**Reported by:** Step*************** (svon*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/all/phenotype/WBPhenotype:0001259#0--10">https://wormbase.org/species/all/phenotype/WBPhenotype:0001259#0--10</a>
**Browser:** Safari 12.1.1

**Comment by nuin** [comment]
My answer to the user

Hi Stephen

You can try using WormMine for such queries (http://intermine.wormbase.org). I set up a small query that just displays the genes linked to the WBPhenotype you were asking for

```
<query model="genomic" view="Gene.primaryIdentifier" sortOrder="Gene.primaryIdentifier ASC" constraintLogic="A and B" >
  <constraint path="Gene.organism.name" op="=" value="Caenorhabditis elegans" code="A" />
  <constraint path="Gene.alleles.phenotype.identifier" op="=" value="WBPhenotype:0001259" code="B" />
</query>
```

You can run the above XML on WormMine by clicking Query Builder and the importing the query from XML link. After the query is loaded you can modify it and add more classes/items as you wish to enhance the final result. 

Gene IDs in the final table link directly to the WormBase page for that gene.

Let me know if you need more help

**Comment by chris-grove** [comment]
Email response by @WBjae 
"""
Alternatively, you can use the ontology browser tab at left side.
Please see the linked page showing 4 direct and 1015 indirect annotations related to the phenotype.
(https://wormbase.org/tools/ontology_browser/show_genes?focusTermName=hermaphrodite%20fertility%20reduced&focusTermId=WBPhenotype:0001259)
"""
