### ISSUE TITLE
  Hi folks - looking at C elegans  PQN-...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7231]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi folks<br/>- looking at C elegans  PQN-84 protein, the protein domain sections have red json error boxes in them rather than any data</p><p>What were you doing? <br />&nbsp;&nbsp;just viewing the page; got there from C. briggsae PQN-84</p>

**Reported by:** Mark******** (mbla**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by epaule** [comment]
https://wormbase.org/species/c_elegans/protein/CE52838

**Comment by chris-grove** [comment]
Duplicate #7125 
Closing.

**Comment by chris-grove** [comment]
My email reply to user:
"""
Apologies for the error. This is a known issue that we are working on. You can follow progress on the issue here:

https://github.com/WormBase/website/issues/7125
"""
