### ISSUE TITLE
Remove "Uniquely mapped" attribute of RNAi objects in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7232]
@nuin 
The "Uniquely mapped" attribute of RNAi objects was actually only applied to a limited set of early RNAi experiments and not appropriately assessed after that, meaning that the entry for this field/attribute is mostly incorrect/inaccurate. We should remove this attribute from RNAi objects in WormMine as soon as possible.

**Comment by nuin** [comment]
@chris-grove That should be simple enough as it is just a XPATH in the loading map for the class. I will check if it is connected to anything else just to be safe.

I have a patch build in the works, I might be able to remove it before loading for RNAi starts

**Comment by nuin** [comment]
BTW, even if I remove from the mapping file for this build, you might still see it in the model as it has already been set prior to building start. It might show up as empty.

**Comment by nuin** [comment]
@chris-grove I deployed a test build on `im-dev1` without the `Uniquely mapped` attribute. Can you take a look and close the ticket if appropriate?

Thanks

**Comment by chris-grove** [comment]
Yes, looks good on im-dev1
Thanks! Closing
