### ISSUE TITLE
Hi, I'd appreciate your help with guiding me how t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7233]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I'd appreciate your help with guiding me how to download the list of genes that are encoded from the mtDNA. I just need the list of the 12 genes (such as ctb-1) that are translated

**Reported by:** chen (chen*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00000829#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00000829#0-9g-3</a>
**Browser:** Chrome 75.0.3770.142

**Comment by chris-grove** [comment]
My email response to user:
"""
You can get this list using WormMine:

http://intermine.wormbase.org/tools/wormmine/begin.do

Go to the QueryBuilder tab, click on "Import query from XML", paste the following query into the box:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.chromosome.primaryIdentifier" code="A" op="=" value="MtDNA"/>
  <constraint path="Gene.CDSs" code="B" op="IS NOT NULL"/>
</query>`


and click "Submit" and then "Show results". That will get you the 12 protein coding genes on the mitochondrial genome.
