### ISSUE TITLE
  I am trying to get the sequence of a ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7236]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to get the sequence of a particular variant.  Ideally, I would like the 20 bp upstream and downstream of that sequence, and ideally the particular variant would be highlighted so I could tell in context exactly which allele has changed and how. In particular I am interested in allele gk765180 from dnc-3. I have found that I can highlight the desired region on jBrowse but I cannot pull up a window that give me the opportunity to download the sequence (as the FAQ answers suggests I should be able to do. (But even if I could, it's not clear that the specific sequence variant I want would be highlighted within that region, which is important._ Is there a way for me to get to that?  Thank you.</p>

**Reported by:** Anit*********** (AFer********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by chris-grove** [comment]
My email to user:
"""
Yes, you can get this information in the "Molecular Details" widget on the respective variation/allele page:

https://wormbase.org/species/c_elegans/variation/WBVar00719853#06--10

This is the easiest way to get the sequence with the variant highlighted and the flanking sequences (25bp on each side) highlighted.

Let us know if you need something else.
"""
