### ISSUE TITLE
  Good afternoon, I'd appreciate your h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7237]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good afternoon,<br/>I'd appreciate your help-<br/>How can I download the sequences of the mitochondrial 12S and 16S genes, and search for optional ORFs within these sequences (based on the mitochondrial codon usage)? <br/>Thanks!</p>

**Reported by:** chen******* (cles*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by chris-grove** [comment]
My email response to user:
"""
I would recommend using the following WormMine query:

From the WormMine homepage (discoverable under the WormBase Tools menu):

http://intermine.wormbase.org/tools/wormmine/begin.do

Click on the "QueryBuilder" tab, then click on "Import query from XML", paste in the following XML query:

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene.transcripts.method" code="A" op="=" value="rRNA"/>
  <constraint path="Gene.chromosome.primaryIdentifier" code="B" op="=" value="MtDNA"/>
</query>

click "Submit" and then click "Show results". This should return two C. elegans rRNA genes on the mitochondrial genome. I'm not sure if they are 12S or 16S, but at least that should help you narrow it down.

Let us know if you have any questions or need something else.
"""
