### ISSUE TITLE
WormMine: phenotype names are missing

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7241]
@nuin 
WS271 WormMine phenotypes are completely lacking a public name; they only have identifiers. Can this get fixed before the next release?

**Comment by nuin** [comment]
Phenotype names are back, on the expense of not having Phenotype Ontology, will work on a solution. @chris-grove You can close this if you want, we can open another to track Ontology

**Comment by chris-grove** [comment]
OK thanks!
