### ISSUE TITLE
The HT115 strain page says it is C. elegans and do...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7242]
*Help Desk query collected when no chat operators were online. Follow up required.*

The HT115 strain page says it is C. elegans and doesn't list the genotype. It is E. coli, the genotype is at https://cgc.umn.edu/strain/HT115(DE3) albeit with a typo (should be lac, not lav). See also https://www.ncbi.nlm.nih.gov/pmc/articles/PMC17598/

**Reported by:** Hill*********** (hill***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/all/strain/HT115#02--10">https://wormbase.org/species/all/strain/HT115#02--10</a>
**Browser:** Chrome 75.0.3770.142

**Comment by chris-grove** [comment]
@Paul-Davis 
I'm assigning you as you curate strains now. Please re-assign if necessary.

**Comment by Paul-Davis** [comment]
Thanks @chris-grove will need to look into this as the current strain object in the primary Strain database has no species liasted and it is only created by XREF from Paper.

**Comment by Paul-Davis** [comment]
Hi Hillel,

We don't generally curate information on non-nematode strains and this 
looks like the case where papers reference the strain and the web code 
defaults to display elegans where no species is stored in the object. I 
will add the information you have provided but also reassign the ticket 
to the web team to disable the auto species population.

Thanks

Paul



On 02/08/2019 20:22, Grove, Christian A. (Chris) wrote:
> Thanks for the heads up Hillel. We'll look into changing ASAP. As you 
> know, you can follow the issue on GitHub:
>
> https://github.com/WormBase/website/issues/7242
>
>
> Chris
> ------------------------------------------------------------------------
> *From:* no-reply@wormbase.org <no-reply@wormbase.org>
> *Sent:* Thursday, August 1, 2019 5:49 PM
> *To:* help@wormbase.org <help@wormbase.org>
> *Cc:* Schwartz, Hillel T. <hillels@caltech.edu>
> *Subject:* [wormbase-help] offline chat transcript: The HT115 strain 
> page says it is C. elegans and do... (Hillel Schwartz)
> offline chat The HT115 strain page says it is C. elegans and doesn't 
> list the genotype. It is E. coli, the genotype is at 
> https://cgc.umn.edu/strain/HT115(DE3) albeit with a typo (should be 
> lac, not lav). See also 
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC17598/
>
> Submitted From:
>   https://wormbase.org/species/all/strain/HT115#02--10 
> https://wormbase.org/species/all/strain/HT115#02--10 
> <http://www.wormbase.org/https://wormbase.org/species/all/strain/HT115#02--10> 
>
>
> This issue has been assigned ticket number: #7242. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7242>.
>
> Reported by: Hillel Schwartz (hillels@caltech.edu)
> 02 Aug 19 00:49
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Web team, could we check my assumption about the auto species population is true?

**Comment by sibyl229** [comment]
@Paul-Davis You are right. Website defaulted to C elegans for strains without a species. It's fixed now, as you suggested to stop auto assigning species: https://staging.wormbase.org/species/all/strain/HT115#02--10

Thanks!

**Comment by Paul-Davis** [comment]
Thanks @sibyl229
