### ISSUE TITLE
  In the ceh-12 gene page.  The fourth ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7243]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;In the ceh-12 gene page.  The fourth expression image panel is showing expression for CHE-12 not CEH-12, this is also referenced in the panel of the figure. Expr12476; Das A, Dickinson DJ, Wood CC, Goldstein B & Slep KC, 2015. I hope this was helpful.  Keep up the very valuable and helpful work.  </p><p>What were you doing? <br />&nbsp;&nbsp;Analyzing CEH-12 expression patterns.</p>

**Reported by:** Jaco*********** (jrm8**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by draciti** [comment]
Hello Jacob,


Thanks for reporting the issue. This is now fixed and will be updated in Release WS274. You can see the release schedule here: https://wormbase.org/about/release_schedule#01--10

Release schedule - WormBase : Nematode Information Resource<https://wormbase.org/about/release_schedule#01--10>
wormbase.org
WormBase is supported by grant #U24 HG002223 from the National Human Genome Research Institute at the US National Institutes of Health, the UK Medical Research Council and the UK Biotechnology and Biological Sciences Research Council.



Cheers,


Daniela

________________________________
