### ISSUE TITLE
  Hello, I have a quick question about ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7245]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I have a quick question about TE annotations in older WS assemblies (specifically WS230). The GFF3 file here (WS263): <br/>ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/WBPS10/species/caenorhabditis_elegans/PRJNA13758/caenorhabditis_elegans.PRJNA13758.WBPS10.annotations.gff3.gz. <br/>has 11256 annotated TEs (3rd field == "transposable_element"). But the WS230 annotations from wormbase here:<br/>ftp://ftp.wormbase.org/pub/wormbase/releases/WS230/species/c_elegans/c_elegans.WS230.annotations.gff3.gz<br/>have only 890 entries annotated as TEs, which seems really low, even if it's a different version.<br/>Do you know why there's this discrepancy? Is there a separate TE list we could use that matches up to ce10 instead of ce11 but has all those WS263 TEs?<br/>Thanks for your help!</p>

**Reported by:** Cole********** (cole*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Colette,

Thank you for contacting WormBase.

There are few things going on here. You are comparing WormBase-Parasite 
with WormBase-Central gffs and comparing releases that differ in age by 
several years. WS230 (March 2012) and WS263 (End 2017). We only used to 
output manually curated transposon data in the gff, this was changed 
more recently to include more of the computationally predicted 
transposons where filtering was imposed to eliminate the smaller 
fragments. If you take the current WS272 gff there are 11256 
transposable_element in the file which matches with what you found for 
the WBPS10 gff as the data is coming directly from WormBase.

10496 Predicted
760 curated
336 genes

I hope that clears things up.

If you would like any additional info on this, please feel free to drop 
me an email.

Paul



On 06/08/2019 20:14, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> I have a quick question about TE annotations in older WS assemblies 
> (specifically WS230). The GFF3 file here (WS263):
> ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/WBPS10/species/caenorhabditis_elegans/PRJNA13758/caenorhabditis_elegans.PRJNA13758.WBPS10.annotations.gff3.gz. 
>
> has 11256 annotated TEs (3rd field == "transposable_element"). But the 
> WS230 annotations from wormbase here:
> ftp://ftp.wormbase.org/pub/wormbase/releases/WS230/species/c_elegans/c_elegans.WS230.annotations.gff3.gz
> have only 890 entries annotated as TEs, which seems really low, even 
> if it's a different version.
> Do you know why there's this discrepancy? Is there a separate TE list 
> we could use that matches up to ce10 instead of ce11 but has all those 
> WS263 TEs?
> Thanks for your help!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7245. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7245>.
>
> Reported by: Colette Picard (colettepicard@gmail.com)
> 06 Aug 19 19:14
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
