### ISSUE TITLE
  Dear Wormbase, I downloaded the WB235...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7246]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase,<br/>I downloaded the WB235 genome from ensembl and I am interested in looking at introns. <br/>I found a gff3 file named c_elegans.WS235.annotations 2.gff3 that lists introns (downloaded from this page ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/gff/)<br/>I wanted to confirm this annotation is correct for the WB235 genome. If so what is the difference between WS235 and WB235?<br/>If this annotation is not the correct to use can you point me to another gff file that lists intronic regions?<br/>Best Regards,<br/>Alyssa</p>

**Reported by:** Alys********** (wa23********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by epaule** [comment]
I do believe the genome assembly is called WBcel235 on EnsEMBL (https://www.ensembl.org/Caenorhabditis_elegans/Info/Index)
This means that it has been last changed in the WormBase release WS235.
But while the genome sequence is stable, the annotation (like genes, expression patterns, etc.) get updated every 2 months on WormBase.
We skip some updates for ensembl, but as you can see the version there is based on WS269 (https://www.ensembl.org/Caenorhabditis_elegans/Info/Annotation)
If you would like newer annotations, I would like to point you to: https://wormbase.org/about/userguide (which is also linked from the Downloads tab on top of the page)
