### ISSUE TITLE
Error in Protein Overview

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#7254]
![Screen Shot 2019-08-12 at 10 59 03 AM](https://user-images.githubusercontent.com/1753893/62875386-f16aec00-bcf0-11e9-9485-35e6b820bd5d.png)

**Comment by sibyl229** [comment]
The problem seems to be a result of upgrading perl and the code mistakenly relying on key order of hashes. 

The Perl version in our docker container is v5.26.2, while we had a much earlier version (v5.16.3) on the dev machine. The key order of hash can no longer be relied on since v5.18 https://www.perlmonks.org/?node_id=1005122

I will modify the code, so it will no longer rely on hash key order.

**Comment by chris-grove** [comment]
@sibyl229 
This a duplicate of #7125 
Thanks for taking a look at it

**Comment by sibyl229** [comment]
Good find @chris-grove! I was looking for that issue, but didn't find it. Thanks!
