### ISSUE TITLE
Hello,   How can I find out the name of the transg...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7255]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,   How can I find out the name of the transgene that was used to reveal the expression pattern in Expr842_Ex (ida-1:gfp)?  
Thanks / Gautam

**Reported by:** Gaut****** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/all/construct/WBCnstr00013299#01--10">https://wormbase.org/species/all/construct/WBCnstr00013299#01--10</a>
**Browser:** Firefox 60.0

**Comment by chris-grove** [comment]
My email to user:
"""
This transgene was reported in the following paper:

https://wormbase.org/resources/paper/WBPaper00004433#031--10

https://www.ncbi.nlm.nih.gov/pubmed/?term=11086294

The authors apparently did not name the transgene. You could email the corresponding author to ask if the transgene was named. The only reference we currently have to this transgene is via the WormBase construct "Expr842_Ex" which corresponds to the expression pattern "Expr842":

https://wormbase.org/species/all/expr_pattern/Expr842#0123--10
"""
