### ISSUE TITLE
Hi there! The flp-18 allele db99 was first describ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7256]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi there! The flp-18 allele db99 was first described in this paper: https://www.cell.com/cellmetabolism/supplemental/S1550-4131(09)00041-2#fig1 You might want to add this info to the wormbase. Thanks

**Reported by:** Irin* (it21*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00001461#0a-9g1c4-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00001461#0a-9g1c4-3</a>
**Browser:** Chrome 67.0.3396.87

**Comment by chris-grove** [comment]
Thanks for the heads up. The information has been added to the database and should appear on the WormBase site for the WS274 release due out at the end of the year:

https://wormbase.org/about/release_schedule#0--10
