### ISSUE TITLE
  On the SER-5 gene page it is stated t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7257]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;On the SER-5 gene page it is stated that it is similar to TAAR1. I blasted the protein and while it does have similarity to TAAR1. It also similar to many other genes/proteins. They are almost all catecholamines (dopamine, norepinephrine, etc) and Tryptamines (Serotonine, Melatonin, etc.) receptors/transporters. Might be better to say that the gene is an ortholog of many catecholamines and Tryptamines receptors and proteins instead of just TAAR1 and adrenergic <br/>orthol,https://www.wormbase.org/species/c_elegans/gene/WBGene00008890#0-9g-3</p><p>What were you doing? <br />&nbsp;&nbsp;I blasted the genes and the proteins of SER-5 against humans and also protein-protein blast of SER-5 and TAAR1</p>

**Reported by:** Anon***** (bonn*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

**Comment by chris-grove** [comment]
My response to user:
"""
 Thanks for bringing this to our attention. This is gene description written by our automated pipeline based on data in the database. The orthology calls mentioned in this description are from a standard set of orthology calls made by one or more particular algorithms. The people involved in developing this automated description are currently on vacation until the end of the month, but they can reply to you once they are back in the office.

My current guess is that the orthology mentioned in the description is coming from WormBase ParaSite-Compara algorithm calls. If you look at the Homology widget of the ser-5 gene page:

https://www.wormbase.org/species/c_elegans/gene/WBGene00008890#0-6-10

in the "Other Orthologs" table:

<img width="1209" alt="Screenshot 2019-08-16 09 24 03" src="https://user-images.githubusercontent.com/611382/63171117-e2de4680-c008-11e9-83a0-8f5070b9a747.png">

For human (you can filter by typing "sapiens" in the search box), I see exclusively the human TAAR genes, and the method used to make the call was "ParaSite-Compara", leading me to the conclusion I just mentioned. If you look at the "View full BLASTP List" table further up in the widget:

<img width="1283" alt="Screenshot 2019-08-16 09 23 57" src="https://user-images.githubusercontent.com/611382/63171135-ebcf1800-c008-11e9-8990-0524fdb2cdd1.png">

 again filtering for "sapiens", you can see the many BLASTP matches to the human adrenergic and hydroxytryptamine receptors I think you were referring to. Looking into this gene/protein sequence a bit more, it seems that this protein is particularly difficult to find an unambiguous match to as it matches relatively weakly to a large number of genes including the trace amine associated receptors (TAARs) and these other receptors shown above.

My colleagues may have additional input into this issue.
"""

**Comment by rankishore** [comment]
Wrote to User as well: 'Apologies for the delay in my reply, but just to add to what Chris already explained, our automated pipleline does not itself calculate/compute any orthologies to genes, it just reflects the data already in WormBase. Nor do we look at what WormBase has called and group orthologs as ‘catecholamines/Tryptamines etc.  However when the orthology calls in WormBase improve (and they do change as the methods improve) our automated descriptions will reflect the new data'.

Closing for now, unless user has further comments/questions.
