### ISSUE TITLE
  Dear Wormbase,  I am interested in do...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7262]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase, <br/>I am interested in downloading interactions for a list of genes. You guys have before directed me to the tool SimpleMine, however I cannot download predicted interactions using this tool. <br/>Is there a way that I can batch download (for about 500 genes) the interaction tables that I can access by clicking the "Save Table" button in the interactions section for a gene? <br/>To illustrate what I am interested in downloading I will use suro-1 as an example. <br/>Currently, when I use SimpleMine to download interacting genes for suro-1 I get two interactions back... rol-6 and col-19. However, what I would like to get is the 20 interactions listed in the interactions table (i.e. all interactions that can be seen in the interactions widget). <br/>Thanks in advance for the help, it is much appreciated. <br/>visitor_name</p>

**Reported by:** Alys** (wa23********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by WenChenWormBase** [comment]
@chris-grove can this be done via WormMine?

**Comment by chris-grove** [comment]
@WenChenWormBase 
No, interactions are not yet in WormMine. I will respond to the user

**Comment by WenChenWormBase** [comment]
@chris-grove  Shall I add an additional column to SimpleMine for "PredictedInteraction"?

**Comment by WenChenWormBase** [comment]
Dear Alyssa,

We are still discussing the best solution for your case.

Will it be helpful if we add a separate column in SimpleMine for all
predicted but not confirmed interactions?

Wen Chen


On Mon, Aug 19, 2019 at 12:41 PM <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Dear Wormbase,
> I am interested in downloading interactions for a list of genes. You guys
> have before directed me to the tool SimpleMine, however I cannot download
> predicted interactions using this tool.
> Is there a way that I can batch download (for about 500 genes) the
> interaction tables that I can access by clicking the "Save Table" button in
> the interactions section for a gene?
> To illustrate what I am interested in downloading I will use suro-1 as an
> example.
> Currently, when I use SimpleMine to download interacting genes for suro-1
> I get two interactions back... rol-6 and col-19. However, what I would like
> to get is the 20 interactions listed in the interactions table (i.e. all
> interactions that can be seen in the interactions widget).
> Thanks in advance for the help, it is much appreciated.
> Alyssa
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7262. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/7262>.
>
> Reported by: Alyssa (wa23@nyu.edu)
> 19 Aug 19 19:41
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/75.0.3770.142 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Dear Alyssa,

I just added a column called "Predicted Interaction" on our SimpleMine
development site. Please give it a try and tell me if it gives the
information that you need.
http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

Here is the result for suro-1, on the SimpleMine dev site, based on data
from WS272:

Your Input Interacting Gene Predicted Interaction
suro-1 rol-6(Regulatory), col-19(Regulatory) F46C8.8, ZK662.2, ptr-16,
C30H6.5, F26G1.5, mab-7, F10D11.6, F53B1.4, R74.2, grd-14, ZK180.6, lpr-7,
abu-12, ZC434.9, T06A4.1, T06A4.3, Y18H1A.9, Y47G6A.19, col-111, F30A10.2,
grl-7, F15B9.8, col-131, ora-1, tag-297, Y38F1A.4, F01D5.6, C02F4.4,
R12E2.15, Y38A10A.2, col-113, wrt-4, C50D2.1, ZC434.3, col-104, lgc-22,
nas-36, M03F8.1, F39D8.3, T19A5.3, fbxa-130, col-54, D2092.8, nas-14,
F07H5.8, C06G1.1, F46C8.1, wrt-8, C32H11.5, R12E2.7, abu-13, grl-15,
F18C5.5, col-182, col-75, col-173, C38C6.3, F40E10.5, acdh-6, Y52B11B.1,
col-97, ZK829.3, nas-29, F01G10.10, pqn-54, col-41, C52G5.2, ptr-2, col-90,
C15C6.1, sups-1, F09F9.2, col-79, T07G12.3, D1014.5, ZC449.1, glf-1,
H23N18.5, D2024.4, R11G11.6, F53F1.4, col-73, F32D8.7, Y45F3A.8, grd-2,
T01D1.3, rol-6, nas-15, R12E2.14, C26B9.2, cyn-17, qua-1, C32H11.8,
D1054.9, cht-2, T17H7.7, pqn-32, col-172, lgc-21, ptr-6, rol-8, agmo-1,
nas-38, ptr-18, col-17, col-156, M02G9.2, grd-6, T06E4.9, abu-14, dpy-4,
ZK1025.2, C06G1.2, B0280.7, C27C7.2, col-45, col-14, C46H11.7, C28H8.5,
H42K12.3, F38B6.7, cutl-28, osr-1, wrt-1, C02E7.7, T06E4.8, M153.1,
str-183, dpy-5, phat-2, F35D2.1, col-91, sqt-2, col-161, ZK180.5, dpy-13,
grd-5, K01D12.9, bgnt-1.8, Y11D7A.9, pqn-13, ZK154.1, col-65, W08A12.3,
col-38, Y47D3B.6, T26C5.2, ZK1025.8, R04B3.3, K08B12.1, C02E7.6, T06E4.7,
T06E4.10, skpo-2, srb-1, col-138, H03E18.1, wrt-9, F13B6.1, col-68,
F41F3.3, bus-19, T16G1.2, clx-1, R06B10.1, E01G6.1, F48G7.5, sqt-3,
T23F6.1, col-13, R02F11.1, mlt-9, lips-9


Wen Chen

On Wed, Aug 21, 2019 at 9:55 AM Wen Chen <wen@wormbase.org> wrote:

>
> Dear Alyssa,
>
> We are still discussing the best solution for your case.
>
> Will it be helpful if we add a separate column in SimpleMine for all
> predicted but not confirmed interactions?
>
> Wen Chen
>
>
> On Mon, Aug 19, 2019 at 12:41 PM <no-reply@wormbase.org> wrote:
>
>> How Do I ...?
>>
>>   Dear Wormbase,
>> I am interested in downloading interactions for a list of genes. You guys
>> have before directed me to the tool SimpleMine, however I cannot download
>> predicted interactions using this tool.
>> Is there a way that I can batch download (for about 500 genes) the
>> interaction tables that I can access by clicking the "Save Table" button in
>> the interactions section for a gene?
>> To illustrate what I am interested in downloading I will use suro-1 as an
>> example.
>> Currently, when I use SimpleMine to download interacting genes for suro-1
>> I get two interactions back... rol-6 and col-19. However, what I would like
>> to get is the 20 interactions listed in the interactions table (i.e. all
>> interactions that can be seen in the interactions widget).
>> Thanks in advance for the help, it is much appreciated.
>> Alyssa
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #7262. Follow progress on our issue
>> tracker <https://github.com/WormBase/website/issues/7262>.
>>
>> Reported by: Alyssa (wa23@nyu.edu)
>> 19 Aug 19 19:41
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36
>> (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You
>> can also email us <help@wormbase.org> directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>
>
> --
> Wen Chen
> Curator, WormBase
>


-- 
Wen Chen
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Hi Wen

Thanks so much! I was just writing you an email back. With a little text
manipulation I can make this work, wonderful thanks again.

I gave the new predicted interactions box a try (still using suro-1 as the
example) and it gave me 173 predicted interactions. However on the suro-1
website in the interactions widget there are only 18 predicted
interactions. Where are these extra interactions coming from?
Cheers
Alyssa

**Comment by chris-grove** [comment]
@WenChenWormBase 
When querying ACEDB for predicted interactions (I had forgotten about this), to get the interactions that agree with the website, we need to filter out only those that have a "Log_likelihood_score" of 1.5 or greater. If you apply that score cutoff, you will get the same results as the website. This was a cutoff suggested by the authors of the paper.

**Comment by WenChenWormBase** [comment]
Dear Alyssa,

I just learned from my colleague Chris Grove, the interaction curator, that
the website applies a threshold of log_likelyhood_score > 1.5 to the
predicted interactions. So I applied the same threshold to SimpleMine to
make the display consistent with the website. You can take a look at the
dev site now.
http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi

Your Input Interacting Gene Predicted Interaction
suro-1 rol-6(Regulatory), col-19(Regulatory) F46C8.8, ZK662.2, ptr-16,
C30H6.5, F26G1.5, mab-7, F10D11.6, F53B1.4, R74.2, grd-14, ZK180.6, lpr-7,
abu-12, ZC434.9, T06A4.1, T06A4.3, Y18H1A.9, Y47G6A.19


Wen.




On Wed, Aug 21, 2019 at 11:42 AM Alyssa Woronik <wa23@nyu.edu> wrote:

> Hi Wen
>
> Thanks so much! I was just writing you an email back. With a little text
> manipulation I can make this work, wonderful thanks again.
>
> I gave the new predicted interactions box a try (still using suro-1 as the
> example) and it gave me 173 predicted interactions. However on the suro-1
> website in the interactions widget there are only 18 predicted
> interactions. Where are these extra interactions coming from?
> Cheers
> Alyssa
>
> On Wed, Aug 21, 2019 at 2:35 PM Wen Chen <wen@wormbase.org> wrote:
>
>>
>> Dear Alyssa,
>>
>> I just added a column called "Predicted Interaction" on our SimpleMine
>> development site. Please give it a try and tell me if it gives the
>> information that you need.
>> http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/simplemine.cgi
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__mangolassi.caltech.edu_-7Eazurebrd_cgi-2Dbin_forms_simplemine.cgi&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=n_BvZMUjGIORfh03Qa6MuQ&m=Ja9LYzu86IOEHaQnlFVFy6C9Zwcq8KiJJTR9s-Myg5c&s=G7qGIRxL-oe41QFKAFvV79uuSCKTBQmalAbp9zij38Q&e=>
>>
>> Here is the result for suro-1, on the SimpleMine dev site, based on data
>> from WS272:
>>
>> Your Input Interacting Gene Predicted Interaction
>> suro-1 rol-6(Regulatory), col-19(Regulatory) F46C8.8, ZK662.2, ptr-16,
>> C30H6.5, F26G1.5, mab-7, F10D11.6, F53B1.4, R74.2, grd-14, ZK180.6, lpr-7,
>> abu-12, ZC434.9, T06A4.1, T06A4.3, Y18H1A.9, Y47G6A.19, col-111, F30A10.2,
>> grl-7, F15B9.8, col-131, ora-1, tag-297, Y38F1A.4, F01D5.6, C02F4.4,
>> R12E2.15, Y38A10A.2, col-113, wrt-4, C50D2.1, ZC434.3, col-104, lgc-22,
>> nas-36, M03F8.1, F39D8.3, T19A5.3, fbxa-130, col-54, D2092.8, nas-14,
>> F07H5.8, C06G1.1, F46C8.1, wrt-8, C32H11.5, R12E2.7, abu-13, grl-15,
>> F18C5.5, col-182, col-75, col-173, C38C6.3, F40E10.5, acdh-6, Y52B11B.1,
>> col-97, ZK829.3, nas-29, F01G10.10, pqn-54, col-41, C52G5.2, ptr-2, col-90,
>> C15C6.1, sups-1, F09F9.2, col-79, T07G12.3, D1014.5, ZC449.1, glf-1,
>> H23N18.5, D2024.4, R11G11.6, F53F1.4, col-73, F32D8.7, Y45F3A.8, grd-2,
>> T01D1.3, rol-6, nas-15, R12E2.14, C26B9.2, cyn-17, qua-1, C32H11.8,
>> D1054.9, cht-2, T17H7.7, pqn-32, col-172, lgc-21, ptr-6, rol-8, agmo-1,
>> nas-38, ptr-18, col-17, col-156, M02G9.2, grd-6, T06E4.9, abu-14, dpy-4,
>> ZK1025.2, C06G1.2, B0280.7, C27C7.2, col-45, col-14, C46H11.7, C28H8.5,
>> H42K12.3, F38B6.7, cutl-28, osr-1, wrt-1, C02E7.7, T06E4.8, M153.1,
>> str-183, dpy-5, phat-2, F35D2.1, col-91, sqt-2, col-161, ZK180.5, dpy-13,
>> grd-5, K01D12.9, bgnt-1.8, Y11D7A.9, pqn-13, ZK154.1, col-65, W08A12.3,
>> col-38, Y47D3B.6, T26C5.2, ZK1025.8, R04B3.3, K08B12.1, C02E7.6, T06E4.7,
>> T06E4.10, skpo-2, srb-1, col-138, H03E18.1, wrt-9, F13B6.1, col-68,
>> F41F3.3, bus-19, T16G1.2, clx-1, R06B10.1, E01G6.1, F48G7.5, sqt-3,
>> T23F6.1, col-13, R02F11.1, mlt-9, lips-9
>>
>>
>> Wen Chen
>>
>> On Wed, Aug 21, 2019 at 9:55 AM Wen Chen <wen@wormbase.org> wrote:
>>
>>>
>>> Dear Alyssa,
>>>
>>> We are still discussing the best solution for your case.
>>>
>>> Will it be helpful if we add a separate column in SimpleMine for all
>>> predicted but not confirmed interactions?
>>>
>>> Wen Chen
>>>
>>>
>>> On Mon, Aug 19, 2019 at 12:41 PM <no-reply@wormbase.org> wrote:
>>>
>>>> How Do I ...?
>>>>
>>>>   Dear Wormbase,
>>>> I am interested in downloading interactions for a list of genes. You
>>>> guys have before directed me to the tool SimpleMine, however I cannot
>>>> download predicted interactions using this tool.
>>>> Is there a way that I can batch download (for about 500 genes) the
>>>> interaction tables that I can access by clicking the "Save Table" button in
>>>> the interactions section for a gene?
>>>> To illustrate what I am interested in downloading I will use suro-1 as
>>>> an example.
>>>> Currently, when I use SimpleMine to download interacting genes for
>>>> suro-1 I get two interactions back... rol-6 and col-19. However, what I
>>>> would like to get is the 20 interactions listed in the interactions table
>>>> (i.e. all interactions that can be seen in the interactions widget).
>>>> Thanks in advance for the help, it is much appreciated.
>>>> Alyssa
>>>>
>>>> Submitted From:
>>>>   support /tools/support
>>>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org__tools_support&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=n_BvZMUjGIORfh03Qa6MuQ&m=Ja9LYzu86IOEHaQnlFVFy6C9Zwcq8KiJJTR9s-Myg5c&s=204NA51jQnRIycljCkISB7pcaAxej_lH0Gqh_h2-5ko&e=>
>>>>
>>>> This issue has been assigned ticket number: #7262. Follow progress on
>>>> our issue tracker
>>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WormBase_website_issues_7262&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=n_BvZMUjGIORfh03Qa6MuQ&m=Ja9LYzu86IOEHaQnlFVFy6C9Zwcq8KiJJTR9s-Myg5c&s=rNgnQOUrytssGxCuI2pEhUbwlr51OKGxFBoJusIP2ac&e=>
>>>> .
>>>>
>>>> Reported by: Alyssa (wa23@nyu.edu)
>>>> 19 Aug 19 19:41
>>>>
>>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36
>>>> (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
>>>>
>>>> This question was reported via the web interface at wormbase.org
>>>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__wormbase.org&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=n_BvZMUjGIORfh03Qa6MuQ&m=Ja9LYzu86IOEHaQnlFVFy6C9Zwcq8KiJJTR9s-Myg5c&s=nUqDxyFQ0X47zOPCZR1LoUCAUz7-nZuIZHC06dh1F0c&e=>.
>>>> You can also email us <help@wormbase.org> directly.
>>>>
>>>> --
>>>> --
>>>> You received this message because you are subscribed to the "WormBase:
>>>> help" group.
>>>> To post to this group, send email to help@wormbase.org
>>>> To unsubscribe from this group, send email to
>>>> help+unsubscribe@wormbase.org
>>>> For more options, visit this group at
>>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__groups.google.com_a_wormbase.org_group_help-3Fhl-3Den&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=n_BvZMUjGIORfh03Qa6MuQ&m=Ja9LYzu86IOEHaQnlFVFy6C9Zwcq8KiJJTR9s-Myg5c&s=ON-QISpELyXmj-rTdDnOU8MCA93N2CTGVP9u3f3J2WA&e=>
>>>>
>>>>
>>>
>>> --
>>> Wen Chen
>>> Curator, WormBase
>>>
>>
>>
>> --
>> Wen Chen
>> Curator, WormBase
>>
>

-- 
Wen Chen
Curator, WormBase

**Comment by chris-grove** [comment]
Sibyl put together this table of interactions for the WS272 release of WormBase:

https://www.dropbox.com/s/kaxvpjp7rb2efqy/all-interactions-ws272-filter-predicted.csv?dl=0

You'll want to create your list of gene names in a text file like "GeneList.txt", place it in the same directory as the above CSV file and then run a grep command like:

grep -f GeneList.txt all-interactions-ws272-filter-predicted.csv > Filtered_interactions.txt

Note that the grep command will not return the header row, so you may want to copy that over from the original CSV file to your filtered list file. Note that some interactions are repeated on multiple lines as they have multiple (non-mutually exclusive) interaction subtypes associated with them. Also, in order for grep -f to work on your gene list file, there must be regular newline characters at the end of each line, not just carriage returns as you might get copy-pasting from Excel, for example.

Also, just so you're aware, the curl command Sibyl sent didn't work for me with a direct copy-paste. The last single-quote character was actually malformatted (at least from what I copied) as it needs to be a simple single quote character, like this:

curl -X GET --header 'Accept: application/json' 'http://rest.wormbase.org/rest/widget/gene/WBGene00011235/interactions'

That will return JSON format which would then need to be parsed in order to generate a table. You may find this jq tool helpful:

https://stedolan.github.io/jq/

Let us know if/how that works out for you.
