### ISSUE TITLE
I want to know about genes list menstioned against...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7264]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to know about genes list menstioned against each life stage in gene ontology section. What does those number of genes mentioned in the brackets imply ? is that those genes are like specifically expressed in that life stage ?  Thank you

**Reported by:** Mose* (mose****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/resources/paper/WBPaper00041190#0--10">https://www.wormbase.org/resources/paper/WBPaper00041190#0--10</a>
**Browser:** Chrome 76.0.3809.100

**Comment by chris-grove** [comment]
My email response to user:
"""
What WormBase page are you referring to? A life stage page like this one:

https://www.wormbase.org/species/all/life_stage/WBls:0000003#02--10

?

In the "Ontology Browser" widget, the indicated list of gene products have some evidence of being expressed during that life stage. It does not imply that the genes are specifically expressed during that life stage.

Does that answer your question?
"""
