### ISSUE TITLE
  I have noticed that mig-13(mu225) mut...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7273]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have noticed that mig-13(mu225) mutation doesn't have a fully described location. To address this, I have identified the location of this single base deletion using a simple PCR+sequencing approach. <br/>I would like to know how can I provide this information to the worm base in order for it to be updated (I've looked into the forms but I wasn't sure which one to use). <br/>Al the best,<br/>Euclides</p>

**Reported by:** Eucl************************ (eucl*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

**Comment by kyook** [comment]
Dear Euclides,

If you would like to submit sequence information for an allele you can use
the form here <https://wormbase.org/submissions/allele_sequence.cgi>.
If you would like to get a citable article for your work, in addition to
submitting these data through the form, you can submit a write up of your
experiment to microPublication Biology <http://www.micropublication.org>.
I've attached a word template to follow for the microPublication.

Hope this helps.
Best,
Karen

On Wed, Aug 28, 2019 at 6:57 AM <no-reply@wormbase.org> wrote:
>
> How Do I ...?
>
>   I have noticed that mig-13(mu225) mutation doesn't have a fully
described location. To address this, I have identified the location of this
single base deletion using a simple PCR+sequencing approach.
> I would like to know how can I provide this information to the worm base
in order for it to be updated (I've looked into the forms but I wasn't sure
which one to use).
> Al the best,
> Euclides
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #7273. Follow progress on our
issue tracker.
>
> Reported by: Euclides E. Fernandes PÃƒÂ³voa (euclidespovoa@gmail.com)
> 28 Aug 19 13:57
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15
(KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You can
also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

**Comment by Paul-Davis** [comment]
Dear Euclides,

In addition to what my colleague suggested you can also send me the 
sequence data and I will integrate it into the record for you.

Paul


On 28/08/2019 14:57, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I have noticed that mig-13(mu225) mutation doesn't have a fully 
> described location. To address this, I have identified the location of 
> this single base deletion using a simple PCR+sequencing approach.
> I would like to know how can I provide this information to the worm 
> base in order for it to be updated (I've looked into the forms but I 
> wasn't sure which one to use).
> Al the best,
> Euclides
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7273. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7273>.
>
> Reported by: Euclides E. Fernandes PÃƒÂ³voa (euclidespovoa@gmail.com)
> 28 Aug 19 13:57
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 
> (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
