### ISSUE TITLE
  Hello, I am not a C. Elegans research...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7274]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I am not a C. Elegans researcher but my institution is searching for a new Assistant Professor in Molecular Genetics and I was wondering if you could post our position in your job listings?  The link for the posting is: https://jobs.nku.edu/postings/8641 </p>

**Reported by:** Emil********* (shif*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by chris-grove** [comment]
@epaule 
You marked this as "Helped". Should we close the ticket?
