### ISSUE TITLE
new GFF features for J/GBrowse

### ISSUE THREAD

**Issue by epaule** [WormBase/website#7275]
for C.elegans/B.malayi/P.pacificus/O.volvulus (which are Gary's nanopore alignments for N2)

BLAT_Caen_Nanopore_BEST expressed_sequence_match
BLAT_Caen_Nanopore_OTHER expressed_sequence_match

and for elegans_vc2010 (which are Erich's filtered liftover from N2)
minimap-filtered *

**Comment by epaule** [comment]
there are also still the cDNA liftovers for VC2010 in the GFF with minimap / cDNA_match which have very similar IDs. If they cause problems, give a shout then I will remove one or the other.

**Comment by scottcain** [comment]
@epaule ,

What identifiers and/or sources (GFF column 2) identify the minimap data, because I just grepped (case insensitive) through all of the 273 GFF files and didn't not find "minimap" in any of them.  This problem was mentioned in https://github.com/WormBase/website/issues/6924 but appears to not have been addressed yet.

**Comment by epaule** [comment]
I think I found the issue in our deployment.
Can you have a look at our EBI FTP site if it looks fine and then I will have to drop a note with the webteam to resync their FTP site.

**Comment by scottcain** [comment]
I believe that sync happens automatically so by tomorrow it will probably be updated.  VC2010 GFF looks OK; I'll try rebuilding it manually to see how it goes.

**Comment by gw3** [comment]
Hi Scott,

"About" descriptions of the Nanopore data: (I've put in detail of the current data set that all comes from the paper by Roach et al. If other Nanopore data sets ever appear and are added to this track, then we will have to make the description more generic.)

Nanopore (best)
This Nanopore transcript data is from the paper "The full-length transcriptome of ​C. elegans ​using direct RNA sequencing"  Roach et al. https://doi.org/10.1101/598763 Where several transcripts are nearly identical, they are represented by a single transcript and the number of transcripts is recorded in the read coverage. Sequencing is from 3' to 5' and randomly terminates, so the 5' end of transcripts is often incomplete. This data represents the best alignment of Nanopore transcripts to the reference genome.


Nanopore (other)
This Nanopore transcript data is from the paper "The full-length transcriptome of ​C. elegans ​using direct RNA sequencing"  Roach et al. https://doi.org/10.1101/598763 Where several transcripts are nearly identical, they are represented by a single transcript and the number of transcripts is recorded in the read coverage. Sequencing is from 3' to 5' and randomly terminates, so the 5' end of transcripts is often incomplete. This data represents secondary alignments of Nanopore transcripts to the reference genome and so can indicate duplicate genes and pseudogenic regions.
