### ISSUE TITLE
  https://www.wormbase.org/resources/pa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7277]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;https://www.wormbase.org/resources/paper/WBPaper00049531#0--10<br/>the publication is from 2016<br/>see https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-016-0256-3</p>

**Reported by:** pujo********** (pujo******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

**Comment by vanaukenk** [comment]
Dear Nathalie,

Thanks for reporting this.

The publication date information for this paper was updated earlier this year and is now included in the upcoming WormBase release:

https://staging.wormbase.org/resources/paper/WBPaper00049531

Best,
--Kimberly
