### ISSUE TITLE
Can you add this comment to slo-1 gene page under ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7278]
*Help Desk query collected when no chat operators were online. Follow up required.*

Can you add this comment to slo-1 gene page under human diseases. Check out Diagnosis on Netflix by the New York Times (episode 4). There is a very rare disease caused by mutations in the human KCNMA1 gene. If you study slo-1, perhaps you can help these patients.

**Reported by:** Andy******* (andy*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00004830#04-9gmn-3">https://wormbase.org/species/c_elegans/gene/WBGene00004830#04-9gmn-3</a>
**Browser:** Chrome 76.0.3809.100

**Comment by rankishore** [comment]
Reply to Andy: Thanks for this information.  Currently we don’t have a ‘comment’ section in the human diseases section of the gene page, but I’ll look into how I can do this and where this type of information would fit best.

09/04 reply: I realized that I could blog this type of quick news while we figure out how to get comments like this on gene pages.  So it’s out on the ’News’ section, let me know if you want any change.

**Comment by rankishore** [comment]
Also thinking that these type of comments/suggestions/alerts from the community might also be suitable for the worm forum

**Comment by chris-grove** [comment]
Added a comment to the slo-1 gene page on behalf of Andy
