### ISSUE TITLE
  how do i post to the worm community? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7279]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do i post to the worm community? i ddid not see any buttons that allow me to add a new post. Sorry, i thought it would be obvious.<br/>thanks!</p><p>What were you doing? <br />&nbsp;&nbsp;trying to post to the worm community forum</p>

**Reported by:** Andy******* (andy*********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by rankishore** [comment]
User helped by @sibyl229 with detailed screen shots and instructions.
