### ISSUE TITLE
  I can no longer log into WormBase. I ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7280]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I can no longer log into WormBase. I have had 3 different email addresses at nih. Can you change it to just visitor_email and tell me how i can reset my password.<br/>thank you.</p><p>What were you doing? <br />&nbsp;&nbsp;logging into wormbase</p>

**Reported by:** Andy******* (andy*********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by chris-grove** [comment]
Email response to user by @sibyl229 
"""
Sorry about the problem. I looked in our database just now and verified that you already have an account associated with this particular email address. You should be able to reset your password here: https://wormbase.org/password/index

If there is any problem, please let us know.
"""
