### ISSUE TITLE
  Hi, is there an easy way to get a lis...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7283]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, is there an easy way to get a list of genes based on % length homology relative to humans or any other species?  OrthoList is very useful but does not give % homology like your homology tables.  Thanks!</p>

**Reported by:** Anon***** (dark******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by chris-grove** [comment]
Emailed user:
"""
You can use WormBase ParaSite BioMart to get this information. Here's an example query:

https://bit.ly/2male32

Let us know if you have additional questions.
"""
