### ISSUE TITLE
Hi, I noticed the links for examples and documenta...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7285]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I noticed the links for examples and documentation on the AQL and WQL are not working (found on this page: https://wormbase.org/tools/queries/run). This should probably be fixed.
Thanks

**Reported by:** Bram****** (bram******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/queries/run">https://wormbase.org/tools/queries/run</a>
**Browser:** Firefox 60.0

**Comment by chris-grove** [comment]
My reply to user:
"""
Thanks for the heads up; our web team will remove those links soon. Unfortunately, the acedb.org server that had hosted those pages is no longer being maintained:

http://www.acedb.org/

so there currently is no online documentation available (that I'm aware of) for these query languages. That said, AQL and WQL will work on the WormBase website advanced query page really only for relatively simple queries. The best options to use for data mining would be our data mining tools available under our "Tools" menu on any WormBase page header. These include SimpleMine, WormMine, and WormBase ParaSite BioMart.

If you have a particular query in mind, we can show you how to perform it in one of our data mining tools, or (if it is a simple enough query and cannot be performed with our other tools) we can instruct you on how to do it in AQL or WQL via the advanced query page.

Please let us know if we can help.
"""
