### ISSUE TITLE
Hi. I'm looking to download the spatial transcript...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7287]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi. I'm looking to download the spatial transcriptomic data that is used in the expression tab in wormbase (the bar plot, I think it's from modEncode data). Is there an easily accessible table of FPKM values I can download?

**Reported by:** Eyal (ebd@********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans#410--10">https://www.wormbase.org/species/c_elegans#410--10</a>
**Browser:** Chrome 76.0.3809.132

**Comment by gw3** [comment]
Eyal,

I've created a .csv file for you with the data for these graphs in.
The data is taken from the latest release: WS273.
If anything isn't clear, please get back to me.

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/gw3/WS273_FPKM.csv

Gary
