### ISSUE TITLE
  I am trying to get the cDNA sequences...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7289]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to get the cDNA sequences (CDS) associated with the protein sequences for the C. elegens genome. Where can I get this data? </p><p>What were you doing? <br />&nbsp;&nbsp;I went to the Downloads section and I could not find the file which contained them. All I could find was whole chromosomal genomes and the protein amino acid sequences. </p>

**Reported by:** Will************ (wmm2**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by chris-grove** [comment]
Emailed user:
"""
 You can always find the current CDS FASTA file on our FTP site here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

You'll want the "CDS_transcripts.fa" file.

You can also query out these sequences using WormMine:

http://intermine.wormbase.org/tools/wormmine/begin.do

Go to the "QueryBuilder" tab, click on "Import query from XML", paste in the following XML query:

<query name="" model="genomic" view="CDS.symbol CDS.sequence.residues" longDescription="">
  <constraint path="CDS.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>

click on "Submit" and then click on "Show results". You can export the results in TSV or FASTA format if you want.

You can also use WormBase ParaSite BioMart to get the CDS sequences:

https://bit.ly/2kfmam8

You can then download the results in FASTA format. Note that for a large file like this you should use the "Export all results to" option of "Compressed web file (notify by email)".

I hope that helps.
"""
