### ISSUE TITLE
  I was just wondering what the relatio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7290]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was just wondering what the relationship was between the functional descriptions file in the FTP server and the gene descriptions on the website? I have noticed they are not always the same, and I don't know if one is better than the other. Thanks! <br/>Example: sqst-5 mentions it is predicted to bind zinc in the FTP server but not online.</p>

**Reported by:** Kati******* (kath*******************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by chris-grove** [comment]
Email from @rankishore to user:
"""
Thanks for writing to WormBase.  Could you please tell me which release you are looking at and what FTP server file?

 I checked the sqst-5 description on current release of WormBase which is WS272 and on our FTP server (WS273 descriptions, (ftp://ftp.wormbase.org/pub/wormbase/releases/WS273/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS273.functional_descriptions.txt.gz) and I see that they are the exact same.

(The WS272 file on our FTP server has a bug and has no descriptions).

Again, please let me know which two files you are comparing and I can look into it.
"""

**Comment by tharris** [comment]
Seems to be resolved. No follow up from user. Closing.
