### ISSUE TITLE
Modify the functional descriptions file produced for the WB FTP site

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#7291]
Please modify this file (if possible for WS273):
ftp://ftp.wormbase.org/pub/wormbase/releases/WS273/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS273.functional_descriptions.txt.gz
in order to remove the tags 'Provisional description' and 'Detailed description', we don't upload these tags/data anymore (from Caltech), they bloat the file and possibly confuse Users.

**Comment by epaule** [comment]
ok, I removed them for WS274

https://github.com/WormBase/wormbase-
pipeline/commit/c3fcd7c0a814a1d0c5e73d9c5739be22d21bf3d0
