### ISSUE TITLE
worm base doesn't have by250 strain detail...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7296]
*Help Desk query collected when no chat operators were online. Follow up required.*

worm base doesn't have by250 strain detail

**Reported by:** NEHA****** (neha********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/strain/BZ555#0241--10">https://www.wormbase.org/species/c_elegans/strain/BZ555#0241--10</a>
**Browser:** Firefox 69.0

**Comment by chris-grove** [comment]
My email to user:
"""
We have a strain page for BY250 here:

https://wormbase.org/species/c_elegans/strain/BY250#0138--10

Is there something in particular you are looking for that we are not displaying?
"""

Closing. Will reopen if necessary.
