### ISSUE TITLE
WormBase site throwing security warning messages 

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7298]
On Firefox, Chrome, and Safari, attempting to load www.wormbase.org results in security/privacy warning messages:

Chrome:
<img width="933" alt="Screenshot 2019-09-13 09 30 07" src="https://user-images.githubusercontent.com/611382/64866441-70fa1c80-d609-11e9-8776-923b99cda5bf.png">

Firefox:
<img width="1022" alt="Screenshot 2019-09-13 09 30 33" src="https://user-images.githubusercontent.com/611382/64866448-73f50d00-d609-11e9-9ddb-6b78a0433aeb.png">

Safari:
<img width="714" alt="Screenshot 2019-09-13 09 30 53" src="https://user-images.githubusercontent.com/611382/64866478-7f483880-d609-11e9-855c-cc6f1a7292e3.png">

**Comment by chris-grove** [comment]
Also, the site is essentially unusable if I accept the risk and continue loading the site

**Comment by chris-grove** [comment]
... and staging is throwing the same messages.

**Comment by epaule** [comment]
The SSL certificate expired yesterday

**Comment by tharris** [comment]
Expired today.  But all is set right with the world now. Please close if you feel the same.
