### ISSUE TITLE
  I just tried to access wormbase from ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7299]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I just tried to access wormbase from my computer at UCL in London using FireFox and I got the message that accessing wormbase represents a security risk. </p>

**Reported by:** Anon***** (b.co***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by raymond91125** [comment]
Hi Barbara,

Apologies for the problem. For a day, you may have to turn off the 
security checking feature of your browser to use WormBase.

Instructions:

https://pearsonnacommunity.force.com/support/s/article/How-to-display-mixed-content-with-Google-Chrome-Internet-Explorer-or-Firefox-1408394589290

Here's an excerpt explaining what happened:

###
Our security certificate expired today. I am in the process of renewing 
it which should be in place later today. You can proceed without concern.

Todd
###

Cheers,

Raymond


On 13/09/2019 7:01 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   I just tried to access wormbase from my computer at UCL in London 
> using FireFox and I got the message that accessing wormbase represents 
> a security risk.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7299. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7299>.
>
> Reported by: b.conradt@ucl.ac.uk
> 13 Sep 19 14:01
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 
> Firefox/69.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
Thank you for reporting the issue.  The problem is now resolved.  I can assure you that at no time was your security at risk.

My apologies for the interruption.
