### ISSUE TITLE
 Server Error: 500 at  tools/gmap/run   
  Error M...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7300]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/gmap/run?name=I;class=Map;map_start=29.3657;map_stop=30.0327">tools/gmap/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "Could not connect to database acedb _WS272, host: 46400cd85c73" </p><p>What were you doing? <br />&nbsp;&nbsp;I clicked the 'zoom out' button on the genetic map for the mIS13 marker</p>

**Reported by:** Ashl******* (anro***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/gmap/run">/tools/gmap/run</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by tharris** [comment]
Fixed, user contacted.

Thank you for reporting this issue.  I wasn’t able to find the cause of the problem, but service to the genetic map has been restored.  Please try your query again and let me know if you have problems.
