### ISSUE TITLE
  wormmine does not open from the tools...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7301]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;wormmine does not open<br/>from the tools menu...</p><p>What were you doing? <br />&nbsp;&nbsp;clicking on wormine link from home page tools menu</p>

**Reported by:** Paul********** (pws@***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by nuin** [comment]
Tomcat restarted, site back up.

**Comment by chris-grove** [comment]
@nuin 
It seems it is still down/not loading (I get a blank page when I try to connect).

**Comment by nuin** [comment]
Nothing I can do now Chris. The SSL change caused this, as it seems Wormmine’s is blocked on loading CDS and JS from Wormbase. I contacted Todd.

**Comment by tharris** [comment]
@nuin you need to update the java trust store on the Intermine instances. Details on slack.

**Comment by nuin** [comment]
All cleared, production and development are working. It was a certificate issue on the connection between WormMine instances and Wormbase main site. CSS wouldn't load and the page would never complete loading itself.
