### ISSUE TITLE
Tree Display appears to be broken

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7303]
Tree Display appears to be broken on all pages I've tested. For example, strain pages:

https://wormbase.org/species/c_elegans/strain/BY250#0136--10

transgene pages:

https://wormbase.org/species/all/transgene/WBTransgene00004908#015--10

gene pages:

https://wormbase.org/species/c_elegans/gene/WBGene00000934#-g-10

construct pages:

https://wormbase.org/species/all/construct/WBCnstr00004889#05--10

They all display the same error message:

<img width="930" alt="Screenshot 2019-09-17 09 22 56" src="https://user-images.githubusercontent.com/611382/65045451-cba6b780-d92c-11e9-8469-fef58b6f645b.png">

**Comment by chris-grove** [comment]
Maybe a duplicate of #7300 and #7302 
?

**Comment by tharris** [comment]
Back up.  Some issues with the container restarting.
