### ISSUE TITLE
  Just letting you know there are issue...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7304]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Just letting you know there are issues with the BLASTP application.  You might want to check it out.  It won't let me search after entering my sequence.</p>

**Reported by:** Dona** (ddwy*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by chris-grove** [comment]
Email to user from @tharris 
"Thank you for reporting the issue.  This problem is now resolved. Please have at your query again!"
