### ISSUE TITLE
  Hello, I would like to submit a conte...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7307]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I would like to submit a content correction in regards to the ire-1(zc14) allele of the gene ire-1. The mutation is annotated as a c/g mutation resulting in G723R missense mutation in the long isoform (G381R in the short). However, by sequencing the line containing this mutation, SJ30, I discovered that it is a c/t mutation at the same residue. This mutation is synonymous with the annotated mutation, i.e., it results in the same glycine codon being mutated to an arginine coding one. I am happy to provide sequencing data to demonstrate this if necessary.<br/>Kind Regards,<br/>visitor_name, PhD<br/>Dillin Lab -- UC Berkeley/HHMI</p>

**Reported by:** Andr********* (andr**********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Andrew,

Thanks for the update, I have made this change for the WS274 release of 
WormBase.

Paul

On 18/09/2019 23:33, no-reply@wormbase.org wrote:
> Content Correction
>
>   Hello,
> I would like to submit a content correction in regards to the 
> ire-1(zc14) allele of the gene ire-1. The mutation is annotated as a 
> c/g mutation resulting in G723R missense mutation in the long isoform 
> (G381R in the short). However, by sequencing the line containing this 
> mutation, SJ30, I discovered that it is a c/t mutation at the same 
> residue. This mutation is synonymous with the annotated mutation, 
> i.e., it results in the same glycine codon being mutated to an 
> arginine coding one. I am happy to provide sequencing data to 
> demonstrate this if necessary.
> Kind Regards,
> Andrew Murley, PhD
> Dillin Lab -- UC Berkeley/HHMI
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7307. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7307>.
>
> Reported by: Andrew Murley (andrew.murley@berkeley.edu)
> 18 Sep 19 22:33
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
