### ISSUE TITLE
  POT-2 exibits G-rich strand telomeric...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7308]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;POT-2 exibits G-rich strand telomeric DNA binding activity and not C rich as stated in the gene overview</p>

**Reported by:** Held*********** (held******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by vanaukenk** [comment]
Hi,
This looks to be coming from a GO MF annotations, so I'll double-check the annotation and fix as needed.

**Comment by vanaukenk** [comment]
Dear Helder,

Thank you again for reporting this information to WormBase.

I've updated the GO annotations for pot-1 and pot-2 and the revised annotations and gene descriptions will be available in WormBase release WS275.

Best,
--Kimberly Van Auken

**Comment by vanaukenk** [comment]
Note: also emailed genenames mailing list to add synonyms to pot-1 and pot-2 based on the paper used as evidence:  https://www.ncbi.nlm.nih.gov/pubmed/18329362
