### ISSUE TITLE
  Could you please provide me with info...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7309]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Could you please provide me with information about how to look for Hom-C genes? Thanks. </p><p>What were you doing? <br />&nbsp;&nbsp;I have an assignment. And I am supposed to look up for genes in C. elegans that are part of the Homeotic gene clusters. My prof told us that we should look for search for Hom-C. And I am getting 2000 genes. But I am not supposed to get that many genes. Could you please provide me with information about how to look for Hom-C genes? Thanks. </p>

**Reported by:** Anon***** (majo**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

**Comment by chris-grove** [comment]
There is no simple way to find HOM-C genes in C. elegans via WormBase by just searching for "HOM-C", unfortunately. I would recommend doing a literature search to find this information. This paper lists four known C. elegans HOM-C genes:

https://www.ncbi.nlm.nih.gov/pubmed/9584132

According to the paper the genes are: lin-39, ceh-13, mab-5 and egl-5
