### ISSUE TITLE
  plg-1 is listed as a pseudogene? with...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7312]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;plg-1 is listed as a pseudogene? with no transcript information? why? <br/>cheers,<br/>gillian</p>

**Reported by:** Gill************* (worm***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

**Comment by a8wright** [comment]
@rankishore I am not sure if you are the one to look at this. I found a bug in the code that resulted in this gene being labeled as a pseudogene. I have corrected this and pushed the fix to staging: https://staging.wormbase.org/species/c_elegans/gene/WBGene00004041#0--10

I don't understand the second part of this about the lac of transcript. Is the widget currently correct or is there more to be done?

**Comment by Paul-Davis** [comment]
Dear Gillian,

Thank you for contacting WormBase, this gene was last assessed by me 
back in 2015 at that time it appeared that a CER1 transposable element 
had integrated into the final coding exon of the gene. RNASeq read 
evidence was used to create a false intron that jumps the transposon 
creating the 3' extended Pseudogene you see in WS249 to present. Now 
that we have ONP sequences it could be argued that the transposon 
integration event was not catastrophic to the locus and the pre-249 
version should be reinstated assuming that the end of the transposon 
that makes up the final part of the ORF allows a valid protein product 
to be made.

If you have additional information that we could use to make this 
decision it would be great if you could share.

Paul


On 21/09/2019 22:41, no-reply@wormbase.org wrote:
> Question:
>
>   plg-1 is listed as a pseudogene? with no transcript information? why?
> cheers,
> gillian
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7312. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7312>.
>
> Reported by: Gillian Stanfield (wormgilly@gmail.com)
> 21 Sep 19 21:41
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 
> (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
@a8wright I'm not sure of what you spotted, but this looks like a curation question rather that the Website doing anything wrong??

**Comment by Paul-Davis** [comment]
I'm sure at one point the Biotype was displayed in the Overview widget but can't see this on live or staging now hmmmmm.

**Comment by a8wright** [comment]
Hi Paul,

What I found in the code is logic that says that if a gene has the field corresponding-pseudogene, which points to a gene, then it is marked as a pseudogene. I think this logic is backward. I think it should be if another gene has a corresponding-pseudogene field that points to the gene then it is itself a pseudogene. 

do you mind checking a few other genes/pseudogenes to see if the logic on staging is correct? If it is not I will reverse the change back to the original logic.

**Comment by Paul-Davis** [comment]
Comment via slack: The way the organisation of objects goes in WB is that a ?Gene has children that can be Transcript/CDS/Pseudogene so if there is a gene:corresponding_pseudogene tag then the web code was probably marking it up as a pseudogene which it should do......however I though that the code was modified a long time ago to look for gene:biotype which is a SO term and this should be used on the overview widget to decide on the overall biotype of the gene. I think you are talking about the Sequences widget which probably has it's own logic for building the table and populating column ?3 etc.
