### ISSUE TITLE
  May I ask what the light purple box i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7315]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;May I ask what the light purple box in the JBrowse represent? I am curious about that it represent CDS or exon?</p>

**Reported by:** Chun* (chli*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

**Comment by scottcain** [comment]
My reply: 

The light purple and light turquoise rectangles are CDS regions, and the skinnier brownish rectangles are UTR regions.  The purple CDSes are forward strand transcripts and the light turquoise are reverse strand.

I hope that helps and please let me know if you have any other questions,Scott
