### ISSUE TITLE
  Dear Sir/Madam, I am trying to find t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7317]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam,<br/>I am trying to find the transcription factor binding motif in rcan-1 promoter region. May I ask if you know any tools can find the binding sites?<br/>Thank you so much for your kind help.<br/>Warm regards,<br/>Yuehui Zhao</p><p>What were you doing? <br />&nbsp;&nbsp;We are working on a paper revision. Thank you for your kind help.</p>

**Reported by:** YH Z (zhao********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by chris-grove** [comment]
My email reply to user:
"""
WormBase has a few tools that may help you find what you're looking for.

1) JBrowse, our newest genome browser, has a set of motif search tracks that can be added based on existing annotated motifs from published papers. To find this tool, open JBrowse (for example from the genomic coordinates link in the Location widget on the rcan-1 gene page), click on "File" in the JBrowse header menu, click on "Add motif search track". This will open up a pop-up menu that allows you to select motif tracks for the indicated sequence-specific DNA binding factor or complex from the indicated publications.

Here's a screen recording demo:

﻿https://www.dropbox.com/s/ngbx97tllud0cyd/Finding_Binding_Motifs_in_rcan-1_promoter_Sep_26_2019.mov?dl=0

2) If you just want to find all transcription factors that have been reported to bind the region of the rcan-1 promoter according to chromatin immunoprecipitation studies, I would recommend opening JBrowse, viewing and/or highlighting the rcan-1 promoter region, turning on the track called "Transcription factor binding regions" found under the heading "Sequence Features" and subheading "Binding Sites & Regions", clicking on the track label drop down menu, and selecting "Save track data". This will give you the option to download a GFF3 formatted file which will indicate the different transcription factors known to bind this region, including the genomic coordinates of their ChIP binding peaks.

Here's a screen recording demo:

https://www.dropbox.com/s/296ztktovvidwhx/Finding_TF_binding_sites_for_rcan-1_promoter_Sep_26_2019.mov?dl=0


Additional online tools for finding transcription factor binding sites in a genomic region of interest (DNA sequence) include:

JASPAR:
http://jaspar.genereg.net/

UniProbe:
http://thebrain.bwh.harvard.edu/uniprobe/

ConTra:
http://bioit2.irc.ugent.be/contra/v3/#/step/1

MotifMap:
http://motifmap.ics.uci.edu/

Bioconductor packages:
https://bioconductor.org/packages/devel/workflows/vignettes/generegulation/inst/doc/generegulation.html

PROMO:
http://alggen.lsi.upc.es/cgi-bin/promo_v3/promo/promoinit.cgi?dirDB=TF_8.3


Let us know if you have any questions about the WormBase tools.
"""
