### ISSUE TITLE
I do not understand the difference between AU78, A...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7319]
*Help Desk query collected when no chat operators were online. Follow up required.*

I do not understand the difference between AU78, AU102, ZD39, ZD326. Please help

**Reported by:** Nadi* (njua**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/search/gene/AY102">https://www.wormbase.org/search/gene/AY102</a>
**Browser:** Safari 13.0

**Comment by chris-grove** [comment]
Duplicate #7320
