### ISSUE TITLE
I need help understanding AU78, Au102, ZD39, ZD326...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7320]
*Help Desk query collected when no chat operators were online. Follow up required.*

I need help understanding AU78, Au102, ZD39, ZD326. Please I am not very well informed of how to read strains so I want some clarifications.

**Reported by:** Nadi* (njua******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/strain/N2#03--10">https://wormbase.org/species/c_elegans/strain/N2#03--10</a>
**Browser:** Safari 13.0

**Comment by chris-grove** [comment]
My reply to user via email:
"""
Strain AU78:
https://wormbase.org/species/c_elegans/strain/AU78#013542--10

The genotype is listed as "agIs219 III" which means that the strain contains a transgene integrated on chromosome III. If you open the "Curatorial remarks" int he "Overview" widget you can find the text:

"agIs219 [T24B8.5p::GFP::unc-54-3' UTR + ttx-3p::GFP::unc-54-3' UTR] III. References: Shivers RP, et al. PLoS Genet. 2010 Apr 1;6(4):e1000892. Shivers RP, et al. Cell Host Microbe. 2009 Oct 22;6(4):321-30."

which explains the contents of the agIs219 transgene. You can also click on the hyperlinked "agIs219" in the "Contains" widget to go to the WormBase webpage for that transgene to see more details.

Strain ZD39:
https://wormbase.org/species/c_elegans/strain/ZD39#013542--10

The genotype here is listed as "agIs219 III; pmk-1(km25) IV." which means this strain also has the agIs219 transgene but also carries the km25 mutation of the gene pmk-1 on chromosome IV. Again, you can find detailed information about the transgene in the Curatorial remarks and links to the transgene page, km25 allele page, and the pmk-1 gene page in the "Contains" widget.

Strain ZD326:
https://wormbase.org/species/c_elegans/strain/ZD326#013542--10

The genotype is listed as "agIs219 atf-7(qd22qd130) III; pmk-1(km25) IV.", so this strain again has the agIs219 transgene and the pmk-1(km25) mutation as well as the mutation/allele "qd22qd130" of the gene atf-7 on chromosome III. Again, details can be found in the Curatorial remarks and in the Contains widget.

Strain AU102:
We don't have a record of a strain called AU102, but based on the page you posted your query from (on your prior email from your GMail address), I would guess you are referring to strain AY102:
https://wormbase.org/species/c_elegans/strain/AY102#013542--10

The genotype here is "pmk-1(km25) IV; acEx102.", so the strain has the allele/mutation pmk-1(km25) as well as the extrachromosomal array transgene acEx102. Again details can be found in Curatorial remarks and in the Contains widget on the page.

I hope that helps.
"""
