### ISSUE TITLE
  I find that when I click on the blast...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7321]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I find that when I click on the blast tool, the page never loads ... something seems broken.</p>

**Reported by:** Andr******** (ahin***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

**Comment by chris-grove** [comment]
@tharris  response to user:
"""
My apologies for the difficulties.  I’ve identified and fixed the issue. Can you please try your query again?

For convenience, here’s a link to the blast query page:

https://wormbase.org/tools/blast_blat
"""
