### ISSUE TITLE
Hello, A faculty member in my department suggested...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7326]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, A faculty member in my department suggested your platform for a faculty  position we want to advertise.  Can you please let me know if this would be possible?  Thank you!
Assistant to the Chair
University of Toronto Scarborough
Toronto, Ontario

**Reported by:** Joan*********** (chai************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/support?url=/">https://www.wormbase.org/tools/support?url=/</a>
**Browser:** Safari 11.1.2

**Comment by epaule** [comment]
I would guess you mean our job board on the WormBase forum: https://forums.wormbase.org/index.php?board=1.0Feel free to put the faculty position up there and give a shout if you have any problems with it.
