### ISSUE TITLE
  How do I found the video? ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7327]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I found the video?</p>

**Reported by:** Liu (x199*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by chris-grove** [comment]
email response by @draciti 
" Can you please be more specific on which video you are trying to find?
Thanks"
Closing. Will reopen if necessary.
