### ISSUE TITLE
  I'm looking at the unc-54(r274) allel...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7328]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm looking at the unc-54(r274) allele. It sequence in wormbase seems to be a C>T transition in unc-54, which is at odds with the initial description of the allele in (Pulak and Anderson 1993): "We sequenced unc-54(r274) as part of this study, r274 is a G > T transversion at nucleotide 4401, resulting in a UGA stop codon (Gly-761 > UGA)." I am wondering the evidence for the allele being a transition v transversion? The transition seems logical given the molecular bias of EMS (G>A and C>T), but given the textual/paper evidence for it being a transversion, am wondering which is right.</p>

**Reported by:** Josh*********** (jaar****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Joshua,

I will investigate and get back to you.
Thanks for reporting it.

Paul


On 30/09/2019 01:30, no-reply@wormbase.org wrote:
> Content Correction
>
>   I'm looking at the unc-54(r274) allele. It sequence in wormbase 
> seems to be a C>T transition in unc-54, which is at odds with the 
> initial description of the allele in (Pulak and Anderson 1993): "We 
> sequenced unc-54(r274) as part of this study, r274 is a G > T 
> transversion at nucleotide 4401, resulting in a UGA stop codon 
> (Gly-761 > UGA)." I am wondering the evidence for the allele being a 
> transition v transversion? The transition seems logical given the 
> molecular bias of EMS (G>A and C>T), but given the textual/paper 
> evidence for it being a transversion, am wondering which is right.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7328. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7328>.
>
> Reported by: Joshua Arribere (jaarribere@gmail.com)
> 30 Sep 19 00:30
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Joshua,

It seems that this 2009 annotation takes the closest Glycine at position 
758 but then incorrectly states G-A rather than the published G-T. The 
G-A fails to produce a stop codon so I have updated this as you 
suggested to match the 1993 paper, but I would be cautious of this 
annotation as the coordinates do not match those published. If you are 
designing experiments around this information I would suggest sequencing 
the mutation to confirm what we have annotated. I will put a statement 
in the variation record to that effect.

I hope that makes sense.

Paul







On 02/10/2019 14:43, Paul Davis wrote:
>
> Dear Joshua,
>
> I will investigate and get back to you.
> Thanks for reporting it.
>
> Paul
>
>
> On 30/09/2019 01:30, no-reply@wormbase.org wrote:
>> Content Correction
>>
>>   I'm looking at the unc-54(r274) allele. It sequence in wormbase 
>> seems to be a C>T transition in unc-54, which is at odds with the 
>> initial description of the allele in (Pulak and Anderson 1993): "We 
>> sequenced unc-54(r274) as part of this study, r274 is a G > T 
>> transversion at nucleotide 4401, resulting in a UGA stop codon 
>> (Gly-761 > UGA)." I am wondering the evidence for the allele being a 
>> transition v transversion? The transition seems logical given the 
>> molecular bias of EMS (G>A and C>T), but given the textual/paper 
>> evidence for it being a transversion, am wondering which is right.
>>
>> Submitted From:
>>   support /tools/support <http://wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #7328. Follow progress on 
>> our issue tracker <https://github.com/WormBase/website/issues/7328>.
>>
>> Reported by: Joshua Arribere (jaarribere@gmail.com)
>> 30 Sep 19 00:30
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 
>> (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can also email us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
> -- 
> ===========================================
> WormBase
> European Bioinformatics Institute (EMBL-EBI)
> European Molecular Biology Laboratory
> Wellcome Trust Genome Campus
> Hinxton
> Cambridge CB10 1SD
> United Kingdom
> ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Have had additional emails and we are pretty confident the annotation is now correct however the user is going to do crispr to confirm as no strain appears to be available anyway.
