### ISSUE TITLE
Chris: Hello Carolyn, how can I help? visitor_name...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7329]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Carolyn, how can I help?</br>visitor_name (visitor_email): I keep clicking on the little se</br>visitor_name (visitor_email): oops sorry. I keep clicking on the sedquence icon to the left of cdk-1 and Rather than getting the sequence back with all the usual option (spliced unspliced, with and without UTRs etc, I am getting a spinning wheel and a window showing exon structure but no sequence.  Am I having a moment of total forgetfulness? Is there something different I'm suppoed to click on?  T05G5.3</br>Chris: Hmmm, sounds like a bug, let me try to replicate the problem

**Reported by:** Caro********** (crn@*******)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00000405#0-9g-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00000405#0-9g-3</a>
**Browser:** Chrome 77.0.3865.90

**Comment by chris-grove** [comment]
User left the chat
