### ISSUE TITLE
  Hi, I have a question (not a correcti...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7330]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I have a question (not a correction) about Y41C4A.11.  Its annotation says COPB2 divergent ortholog.  It is also refered to that way in the papers where it is mentioned.  however, when I BLAST or do the NCBI domain search, I get a different human ortholog (which UNIprot does put in the Golgi, the site COP proteins would be).  The papers don't show any data about the orthology assignment or alignments to COPB proteins.  Would you have any additional information on that orthology assignment?</p>

**Reported by:** Amy ****** (amy.*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by epaule** [comment]
if you look to the OtherOrtholog section in the Homology widget, you can see that ParaSite Compara picked it up as ortholog.But the latest release of the compara code doesn't predict it anymore, and if you look at the Alliance and remove all DIOPT filters, you can see that only Panther still predicts the orthology.
