### ISSUE TITLE
I am looking for the raw RNAseq data files represe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7331]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking for the raw RNAseq data files represented on Wormbase under Expression--&gt; FPKM expression from selected modENCODE libraries, to reanalyze. We are specifically interested in the Dauer and L3 life stages. Where can we find the link to the source files represented in the barplots? Thank you very much.

**Reported by:** Coli********* (coli****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00019883#0418-9d3ecfb-3">https://wormbase.org/species/c_elegans/gene/WBGene00019883#0418-9d3ecfb-3</a>
**Browser:** Chrome 77.0.3865.90

**Comment by gw3** [comment]
Colin,

Take a look at:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/gw3/WS273_FPKM.csv

Get back to me if anything is not clear.

Gary Williams
