### ISSUE TITLE
  I am writing about pink-1(ok3538). Th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7333]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am writing about pink-1(ok3538). The CGC says that this is a 500bp deletion. I have also talked with someone who has worked with this mutation and they confirmed that it seems to be a deletion. However, on wormbase it is marked as an insertion. Do you have any information as to where the deletion is located? I would like to use this information to design primers for genotyping. Thank you very much for your help.</p>

**Reported by:** Chri******* (quin**********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by Paul-Davis** [comment]
Dear Chris,

Thank you for getting in touch.

Indeed this looks like an error on our part. Digging through the email 
archive I have found that the curator at the time added the insertion 
information but not the necessary tags to indicate that it is also a 
deletion.

Df/Dp_Rearrangement_2 "deletion + insertion"
Df/Dp_Gene_1 "pink-1"
Df/Dp_Results "ok3538 deletes part of the penultime and last exons"
Df/Dp_Genotype "pink-1(ok3538)"
Df/Dp_Date "2016-07"
Df/Dp_Comment "We have mapped the pink-1(ok3538) deletion which is a 
deletion + 5bp insertion.

Here you have the boundaries + the 5 bp insertion

TTCATAAGCATAAAGTTGCTCAGCGAGACATGAAAAGTGATAATATTCTTxxxxxxxxxx gtgat 
xxxxxxxxxxGACAAAGTGATGAATCTGATTACTGCTGAAACTATCATGGCCAACCTAGC
I will correct this for the WS275 release of WormBase.

Thanks

Paul



On 04/10/2019 19:34, no-reply@wormbase.org wrote:
> Content Correction
>
>   I am writing about pink-1(ok3538). The CGC says that this is a 500bp 
> deletion. I have also talked with someone who has worked with this 
> mutation and they confirmed that it seems to be a deletion. However, 
> on wormbase it is marked as an insertion. Do you have any information 
> as to where the deletion is located? I would like to use this 
> information to design primers for genotyping. Thank you very much for 
> your help.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7333. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7333>.
>
> Reported by: Chris Quinn (quinnc@uwm.edu)
> 04 Oct 19 18:34
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 
> Firefox/60.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Even though the deletion data was not in the variation record the molecular details widget was doing the correct thing which is great.....added the deleted sequence so that this info displays on the page.
