### ISSUE TITLE
trying to figure out where would i go to see what ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7334]
*Help Desk query collected when no chat operators were online. Follow up required.*

trying to figure out where would i go to see what chromosomes the genes are located on for the the caenorhabditis elegans

**Reported by:** Nya (nyaw***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-345-5">https://wormbase.org/#012-345-5</a>
**Browser:** Chrome 76.0.3809.132

**Comment by chris-grove** [comment]
My email to user:
"""
You can find the chromosome a gene is on from a gene page "Location" widget like here:

https://wormbase.org/species/c_elegans/gene/WBGene00001851#-09-10

In this case, the gene is on chromosome V (five).
"""
