### ISSUE TITLE
Good evening, may I know how will find whether a g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7335]
*Help Desk query collected when no chat operators were online. Follow up required.*

Good evening, may I know how will find whether a genes on lem-3 for C.elegans are encoded in the 5' to 3' direction or vice versa?

**Reported by:** Saha*** (hann*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00010609#0-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00010609#0-9g-3</a>
**Browser:** Chrome 77.0.3865.90

**Comment by chris-grove** [comment]
My email to user:
"""
This sounds like a basic molecular biology question. Maybe this book excerpt will help:

https://www.ncbi.nlm.nih.gov/books/NBK26887/#_A981_
"""
