### ISSUE TITLE
How do I find the names of the genes encoded on th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7336]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I find the names of the genes encoded on the 5’ and the 3’ end of lem-3?

**Reported by:** Saha*** (hann*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00002276#4h-ga9-3">https://wormbase.org/species/c_elegans/gene/WBGene00002276#4h-ga9-3</a>
**Browser:** Chrome 77.0.3865.90

**Comment by chris-grove** [comment]
My email to user:
"""
You can find this information by viewing the genome browser JBrowse for this particular gene. On the gene page, in the Location widget, click on the hyperlinked genomic position:

https://wormbase.org/species/c_elegans/gene/WBGene00002276#-9-10

Then you can scroll your view left and right to see the genes that are adjacent to lem-3.
"""
