### ISSUE TITLE
Hey there, I am unable to view the required genome...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7337]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hey there, I am unable to view the required genome sequence. Should I download other external app for this? or what might be the solution?

**Reported by:** Akri****** (giri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/analysis/RNASeq.ovolvulus.O_volvulus_Cameroon_isolate.WBls:0000104.Female.WBbt:0007833.SRP056861.SRX978159#0--10">https://wormbase.org/resources/analysis/RNASeq.ovolvulus.O_volvulus_Cameroon_isolate.WBls:0000104.Female.WBbt:0007833.SRP056861.SRX978159#0--10</a>
**Browser:** Chrome 77.0.3865.90

**Comment by raymond91125** [comment]
For the genome project, you can find it here 
<https://parasite.wormbase.org/Onchocerca_volvulus_prjeb513/Info/Index>.

Cheers,

Raymond

**Comment by Paul-Davis** [comment]
Dear Akrit,

The information on the genome project is available here:
https://wormbase.org/species/o_volvulus/strain/O_volvulus_Cameroon_isolate#0231645--10

The jbrowse tool for viewing the genomic sequence is here:
https://wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fo_volvulus_PRJEB513&loc=OVOC_MITOCHONDRIAL%3A1..13744&tracks=Curated_Genes&highlight=

If you need additional information, please feel free to contact us again.

Paul

On 07/10/2019 02:38, no-reply@wormbase.org wrote:
> offline chat Hey there, I am unable to view the required genome 
> sequence. Should I download other external app for this? or what might 
> be the solution?
>
> Submitted From:
>   https://wormbase.org/resources/analysis/RNASeq.ovolvulus.O_volvulus_Cameroon_isolate.WBls:0000104.Female.WBbt:0007833.SRP056861.SRX978159#0--10 
> https://wormbase.org/resources/analysis/RNASeq.ovolvulus.O_volvulus_Cameroon_isolate.WBls:0000104.Female.WBbt:0007833.SRP056861.SRX978159#0--10 
> <http://www.wormbase.org/https://wormbase.org/resources/analysis/RNASeq.ovolvulus.O_volvulus_Cameroon_isolate.WBls:0000104.Female.WBbt:0007833.SRP056861.SRX978159#0--10> 
>
>
> This issue has been assigned ticket number: #7337. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7337>.
>
> Reported by: Akrit Giri (giriakrit04@gmail.com)
> 07 Oct 19 01:38
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
