### ISSUE TITLE
  Good morning, I have an account with ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7345]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Good morning,<br/>I have an account with wormbase (opened account on 8/23/19).  However, when I tried to log in I receive an error message of "no email address associated with wormbase"<br/>Can you please tell me why my account is not working?<br/>Thank you</p>

**Reported by:** jobs (jobs**********)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by azurebrd** [comment]
Sibyl replied :
