### ISSUE TITLE
  We are trying to create primers that ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7346]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We are trying to create primers that flank the d-loop non-coding region of C. elegans mtDNA. We know that a NCR (including the d-loop/displacement loop) is placed between ND5 and ND6, but we so far can't find the sequences for this region. Does WormBase have any way to help us? </p><p>What were you doing? <br />&nbsp;&nbsp;We're using the NCR to look at mutigenicity. </p>

**Reported by:** Noel******** (noel*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by scottcain** [comment]
My response to the user:

Hi Noelle,

You can certainly do this in JBrowse.  The only small hiccup is that this region spans the origin in JBrowse, so it's two segments.  In the following two views, you can hover your mouse over the "Reference sequence" label and click on the down triangle to get the menu.  Select "save track data" from the menu, and then make sure "highlighted region" is selected and then click "Save."

  https://wormbase.org/tools/genome/jbrowse-simple/?loc=MtDNA%3A1..589&tracks=Curated_Genes%2CDNA&data=data%2Fc_elegans_PRJNA13758&highlight=MtDNA%3A1..112

and

https://wormbase.org/tools/genome/jbrowse-simple/?loc=MtDNA%3A11785..13794&tracks=Curated_Genes%2CDNA&data=data%2Fc_elegans_PRJNA13758&highlight=MtDNA%3A13272..13794

**Comment by scottcain** [comment]
@WBjae 's emails:
---------------------------
Just for your quick reference, please see also the site below.

Jae

Caenorhabditis elegans mitochondrial reference genome (https://www.ncbi.nlm.nih.gov/nucleotide/NC_001328.1)

Caenorhabditis elegans

Included in the Caenorhabditis elegans reference assembly (WBcel235)

    RefSeq: NC_001328.1 Length: 13,794 bp circular
---------------------------

and 

---------------------------
And also these.

nduo-5 (ND5)
https://wormbase.org/species/c_elegans/gene/WBGene00010967#0-9f-3 

nduo-6 (ND6)
https://wormbase.org/species/c_elegans/gene/WBGene00010957#0-9f-3
---------------------------

and Noelle's reply:
---------------------------
Thank you so much for these links — they’ve been a HUGE help to us!!! My partner and I have done a pretty exhaustive search of the literature and haven’t been able to find published primer sequences that flank the displacement loop region. Would you know of any literature that has the designs for primers flanking the d-loop that we might look at? In the case that no such designs exist, my partner and I investigated the links you sent us and noticed that two tRNA sequences flank the d-loop. Are these two tRNA sequences conserved in worms? If so, we are thinking that we could use them to design our primers. 
---------------------------

and finally, my reply to that:
---------------------------
There is a UCSC conservation track in JBrowse too, and it looks like much of the tRNAs around the region you're interested in are conserved across 26 nematode species.  The list of species UCSC used for this analysis is here:

  https://hgdownload.cse.ucsc.edu/goldenPath/ce11/multiz26way/
---------------------------

**Comment by scottcain** [comment]
@WBjae 's followups:

--------------------

Please see this paper. Even though they used PCR primer set for the broad region with D-loop, it may be helpful, or you can contact the authors for more information.

Cell Metab. 2016 Jul 12;24(1):91-103. doi: 10.1016/j.cmet.2016.06.008.
Homeostatic Responses Regulate Selfish Mitochondrial Genome Dynamics in C. elegans.
Gitschlag BL1, Kirby CS2, Samuels DC3, Gangula RD4, Mallal SA5, Patel MR6.

https://www.ncbi.nlm.nih.gov/pubmed/27411011

------------------------

and 

------------------------

For the comparison between species, this paper could be helpful.

Comparative mitochondrial genomics reveals a possible role of a recent duplication of NADH dehydrogenase subunit 5 in gene regulation
Runsheng Li, Xiaoliang Ren, Yu Bi, Qiutao Ding, Vincy Wing Sze Ho, Zhongying Zhao
DNA Research, Volume 25, Issue 6, December 2018, Pages 577–586, 
https://doi.org/10.1093/dnares/dsy026

https://academic.oup.com/dnaresearch/article/25/6/577/5066955
