### ISSUE TITLE
  Hello I am new to worm data base and ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7348]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>I am new to worm data base and would like to know from where I can download the celegans10 genome fasta file, chromosome size file as well as the refgene file<br/>Thanks,<br/>Sumy</p>

**Reported by:** sumy (sumy*****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by epaule** [comment]
if you have a look at the FAQ: https://wormbase.org/about/Frequently_asked_questions under UCSC versions, you can see that UCSC ce10 was based on the WormBase WS220 release.Amd as we do keep an archive of historical WormBase releases, you can find the collected WS220 data here: ftp://ftp.wormbase.org/pub/wormbase/releases/ It should be quite easy to come up with a perl one-liner to generate the chromosome sizes based on the fasta file, and as reference gene set, the ones from the GFF file would be recommended.
