### ISSUE TITLE
  Hello, My name is visitor_name and I ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7351]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>My name is visitor_name and I am a junior faculty at the University of Chicago.<br/>I am writing regarding the Lin-39 ChIP-seq data deposited at WormBase.<br/>The first paper of my lab is under revision and the reviewers asked for LIN-39 ChIP-seq data.<br/>I am only interested at the L3 stage. <br/>Is there any way to get the BAM or bigwig files for "Combined LIN-39 ChIP GFP” that are shown in Wormbase? Also, were any Input files (control for LIN-39 ChIP-Seq) submitted for the L3 experiment?<br/>Any help with this would be greatly appreciated as my lab is working towards meeting a fast approaching revision deadline.<br/>If you do not know the answer, can you refer me to someone?<br/>Thank you very much in advance.<br/>Best wishes,<br/>Paschalis<br/>visitor_name, Ph.D.<br/>Assistant Professor<br/>Biological Sciences Division<br/>Department of Neurobiology<br/>Grossman Institute for Neuroscience<br/>University of Chicago<br/>947 E. 58th St., AB412<br/>Chicago, IL 60637, USA<br/>Office: +1-773-702-7442<br/>Lab: +1-773-834-7605<br/>http://www.kratsioslab.org</p>

**Reported by:** Pasc************** (pkra******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by scottcain** [comment]
My reply:

All of the data that are displayed in JBrowse is publicly accessible via http.  For something like a BAM or BigWig file, perhaps the easiest way to get it is to read the track configuration to find the url for the source file.  Here's what I mean: when you're looking at a track in JBrowse, when you mouse over the label of the track, you'll notice that it gets more "solid" and a triangle appears indicating that there is a drop down menu.  When you click to get that menu, you select "Edit config".  In the resulting popup window, you can look for the urlTemplate entry, and the value that comes after it is the url for the file.  In this case, I think you're looking for

  https://s3.amazonaws.com/wormbase-modencode/wiggle_binaries/snyder/Snyder_LIN-39-GFP_L3_combined_WS220.bw

**Comment by scottcain** [comment]
Another happy customer:

Dear Scott,

This is incredibly helpful. Thank you so much!

Best wishes,

Paschalis
