### ISSUE TITLE
Supplementary jbrowse tracks for C. briggsae SNP data

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7353]
Hi @scottcain,

This user query has identified something that got lost back in 2015

 #7350 

We think the issue back then was getting the existing c. briggsae data in order to merge in these 3mil snps...but for some reason this data wasn't revisited.

Would it be possible to add this vcf file as a supplementary g/jbrowse track like we do for the C. elegans CeNDR variation data?

ftp://ftp.sanger.ac.uk/pub/wormbase/STAFF/pad/c.briggsae_snps.vcf 

Ideally the pop-up would display all of the strains that the snp has been observed in.

This is the paper: WBPaper00046558

If the VCF isn't jbrowse compatible give us a shout.

Does gbrowse allow for attaching vcf?

Thanks

Paul

**Comment by scottcain** [comment]
Unfortunately, GBrowse doesn't (and presumably, never will) do VCF, so the only way to get it into GBrowse would be to convert the variant data to GFF.

I'll grab the vcf file and see how it goes in JBrowse.

**Comment by scottcain** [comment]
The vcf displays fine.  I'll have to spend a little time writing code that will parse the genotype section to populate a pop up with the strain info.  The default dialog box you get when you click on the feature does have that information, though in an ugly format:
<img width="622" alt="Screen Shot 2019-10-16 at 10 51 38 AM" src="https://user-images.githubusercontent.com/274751/66944930-015dbf80-f003-11e9-8138-4a6db0c89d53.png">

https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_briggsae_PRJNA10731&loc=III%3A6896180..6905477&tracks=Curated_Genes%2Cbriggsae%20variation&highlight=

**Comment by Paul-Davis** [comment]
Hey @scottcain that looks like a great start...thanks

**Comment by scottcain** [comment]
@Paul-Davis WS273 is coming out shortly--I didn't get a chance to add a popup to this track, so I'll keep this issue open so that it happens for WS274.  At least the data are available for this release :-)

**Comment by Paul-Davis** [comment]
Great, Thanks for the update @scottcain

**Comment by tharris** [comment]
Pop up looks good. In production with WS274. Closing.
