### ISSUE TITLE
Variation-to-gene mapping error in WS273?

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7357]
@khowe @Paul-Davis 
While reviewing genetic interactions for the Alliance, I stumbled across an odd variation-to-gene mapping that doesn't appear to make sense and seems to have only sprung up in WS273 as it doesn't exist in WS272. The allele is e1386 and maps to only daf-5 (which makes sense) in WS272 but then in WS273 appears to have been mapped to both daf-5 AND W01G7.4, the latter of which doesn't make any sense as it doesn't come close to overlapping that gene. Compare:

https://wormbase.org/species/c_elegans/variation/WBVar00143963#025b--10

with

https://staging.wormbase.org/species/c_elegans/variation/WBVar00143963#0259--10

Could there have been a bug introduced into the variation-to-gene mapping pipeline in WS273? Or maybe I'm just missing something?

**Comment by chris-grove** [comment]
OK, nevermind, I figured out the reason. There's been added an extra long extended 5'UTR of W01G7.4 that now makes its intron overlap the variation. Looks odd but I assume there's enough experimental evidence to support it. Closing.

**Comment by epaule** [comment]
that comes from an Oxford nanopore read. Will check with @gw3
