### ISSUE TITLE
Alleles missing on WS273 staging site (but present in WS273 ACEDB)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7359]
I'm not sure if this is a bug or if some part of stage just still needs to be built, but I noticed that the allele tm5268 exists in WS273 ACEDB, but there is no page (or any search results) for tm5268 on staging.wormbase.org.

I don't know how widespread the issue might be. Could someone take a look?

**Comment by chris-grove** [comment]
For the record this corresponds to variation ID WBVar02143902. Here's the ACEDB image:

<img width="1046" alt="Screenshot 2019-10-22 11 55 36" src="https://user-images.githubusercontent.com/611382/67305133-e25ba380-f4c2-11e9-95ea-507be54025e0.png">

**Comment by chris-grove** [comment]
I should have checked this yesterday: the allele is present in WS272 production:

https://wormbase.org/species/c_elegans/variation/WBVar02143902#025b86--10

Also, I found another missing allele: n3196 (WBVar02125725)

Available on production WS272:
https://wormbase.org/species/c_elegans/variation/WBVar02125725#025b86--10

but missing on WS273 staging (although present in WS273 ACEDB).

**Comment by chris-grove** [comment]
Another: n3213 (WBVar02125726)
https://www.wormbase.org/species/c_elegans/variation/WBVar02125726#025869--10

**Comment by Paul-Davis** [comment]
Hi @chris-grove I can confirm they are in the WS273 acedb release and @mgrbyte has just queried the WS273 datomic instance for the Variations you have questioned above:

**Comment by Paul-Davis** [comment]
Hi @chris-grove I can confirm they are in the WS273 acedb release and @mgrbyte has just queried the WS273 datomic instance for the Variations you have questioned above.

```
user> (d/pull db '[:variation/public-name] [:variation/id "WBVar02125726"])
#:variation{:public-name "n3213"}
user> (d/pull db '[:variation/public-name] [:variation/id "WBVar02125702"])
#:variation{:public-name "ot743"}
user> (d/pull db '[:variation/public-name] [:variation/id "WBVar02143902"])
#:variation{:public-name "tm5268"}
```

**Comment by sibyl229** [comment]
@Paul-Davis Thanks for looking into this. @chris-grove I think this is a website / search indexing issue. I'm looking into this right now.

**Comment by sibyl229** [comment]
Hi @chris-grove the missing alleles issue should be fixed now, both on staging and when WS273 goes live. The problem was due to snapshot/backup of the search database being taken too early that some records hadn't being indexed. 

https://staging.wormbase.org/species/c_elegans/variation/WBVar02143902
https://staging.wormbase.org/species/c_elegans/variation/WBVar02125725

Please take a look, thanks!

**Comment by chris-grove** [comment]
@sibyl229 
Looks great! Thanks!
