### ISSUE TITLE
  Hi, I'm trying to treat my worms with...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7363]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm trying to treat my worms with a drug dissolved in M9 buffer. Are C. elegans able to survive in M9 buffer for some time? That is to say if we leave them suspended in buffer in microcentrifuge tubes for up to 24 hours, that alone will not kill the worms? </p>

**Reported by:** Noel******** (noel*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by raymond91125** [comment]
Hi Noelle,

I'd suggest you go to https://forums.wormbase.org/ for questions and 
discussions like this. You tend to get a lot more and detailed suggestions.

Personally, I wouldn't leave worms in a sealed tube as they do need 
oxygen like most living beings. But the practical specifics may have to 
be experimented upon.

Good luck.

Raymond

On 23/10/2019 10:28 AM, no-reply@wormbase.org wrote:
> Question:
>
>   Hi, I'm trying to treat my worms with a drug dissolved in M9 buffer. 
> Are C. elegans able to survive in M9 buffer for some time? That is to 
> say if we leave them suspended in buffer in microcentrifuge tubes for 
> up to 24 hours, that alone will not kill the worms?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7363. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7363>.
>
> Reported by: Noelle Chung (noelle.chung20@trinityschoolnyc.org)
> 23 Oct 19 17:28
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
