### ISSUE TITLE
I want to know if there's a method which I can get...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7364]
*Help Desk query collected when no chat operators were online. Follow up required.*

I want to know if there's a method which I can get the eggs in the dead worms,so as to have more ones.
Than you for receiving this email

**Reported by:** Mari********** (mari**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/Frequently_asked_questions#5f30b267e48a9c1d--10">https://wormbase.org/about/Frequently_asked_questions#5f30b267e48a9c1d--10</a>
**Browser:** Chrome 76.0.3809.132

**Comment by chris-grove** [comment]
A couple of methods come to mind:

1) Use a fine gauge syringe with a sharp endpoint and you should be able to slice individual worms open at the midbody and (hopefully) release the eggs
2) Perform a standard bleaching/hypochlorite treatment:

http://www.wormbook.org/chapters/www_strainmaintain/strainmaintain.html#d0e671

Other than that I would refer you to the WormBase Community Forums here:

https://forums.wormbase.org/

Once you register you can post questions to the community for feedback.

Good luck!
