### ISSUE TITLE
  From the website/database, How do you...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7365]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;From the website/database, How do you determine which proteins are encoded by bli-1 and dpy-11 in C. elegans and how many amino acids are in the proteins?</p><p>What were you doing? <br />&nbsp;&nbsp;Lab report</p>

**Reported by:** john******** (john******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi John,

If you search for your chosen genes in the main search box you will get 
to the gene summary page, if you look on the "Sequences section" you 
will see a column called Protein....follow that link and you will get 
the information you require.

https://wormbase.org/species/c_elegans/gene/WBGene00000251#0f--10

Paul

On 23/10/2019 21:53, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   From the website/database, How do you determine which proteins are 
> encoded by bli-1 and dpy-11 in C. elegans and how many amino acids are 
> in the proteins?
>
> What were you doing?
>   Lab report
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7365. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7365>.
>
> Reported by: johncuddihee (johncuddihee@gmail.com)
> 23 Oct 19 20:53
>
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/77.0.3865.120 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
