### ISSUE TITLE
  I have been reading about MTT assays ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7367]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have been reading about MTT assays adapted to C. elegans and have found that they all read at 575 nm. Are there any other wavelengths it can be read at? I don't have access to a lot of different materials, one of which is a 575 nm filter. I have other wavelengths, ideally 490/495, but sadly not this one in particular. If not, do you know of any XTT assays adapted to C. elegans that do not require cell lysates? </p><p>What were you doing? <br />&nbsp;&nbsp;We want to use the MTT/XTT assay to titer a chemical</p>

**Reported by:** Noel** (noel*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by chris-grove** [comment]
Email response from @WBjae 
"""
Please see this for an example.
https://www.ncbi.nlm.nih.gov/pubmed/11718805
Mech Ageing Dev. 2002 Jan;123(2-3):105-19.


And for further technical discussion, you can visit WormBase forum site to post your question and getting any feedback after registration and log-in.

https://forums.wormbase.org/
"""
