### ISSUE TITLE
Hi, I am looking at several motifs contained in th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7372]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I am looking at several motifs contained in the Ovo-ZIG-8 protein. I see "Score" on the far right of the Motif Details Column. What is this Score based on and what is considered high, moderate, or low? Thank you for your assistance.

**Reported by:** Seik******* (st@c*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/o_volvulus/protein/OVP07046#0534--10">https://www.wormbase.org/species/o_volvulus/protein/OVP07046#0534--10</a>
**Browser:** Chrome 78.0.3904.70

**Comment by chris-grove** [comment]
@epaule  Can you answer this one?

**Comment by epaule** [comment]
these scores are from the respective member databases analysis that contribute to interpro. Dependent on which tools the respective analysis used it will be different (from HMM to pattern matching to entropy).As Interpro is a meta-analysis, it is using analysis specific thresholds and combines them into InterPro motifs (which, as you can see have no score, as the scores don't combine).The in-depth details can be found in the various publications from the InterPro team.
