### ISSUE TITLE
Could you please let us know that where from we ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7374]
*Help Desk query collected when no chat operators were online. Follow up required.*

Could you please let us know that where from we get the antibodies against the reactivity with C.elegans of these protein pink-1, pdr-1, lrk-1 and djr-1. thank you

**Reported by:** neha (neha********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/protein/CE28904#064--10">https://wormbase.org/species/c_elegans/protein/CE28904#064--10</a>
**Browser:** MSEdge 17.17134

**Comment by chris-grove** [comment]
You can find antibody information on gene page "Reagents" widgets:

pink-1
https://wormbase.org/species/c_elegans/gene/WBGene00017137#c--10

pdr-1
https://wormbase.org/species/c_elegans/gene/WBGene00003967#c--10

lrk-1
https://wormbase.org/species/c_elegans/gene/WBGene00003068#c--10

djr-1.1
https://wormbase.org/species/c_elegans/gene/WBGene00015184#c--10

djr-1.2
https://wormbase.org/species/c_elegans/gene/WBGene00016789#c--10

It looks like we only have annotated one antibody for the LRK-1 protein:

https://wormbase.org/species/all/antibody/[WBPaper00049192]:anti-LRK-1#012--10

I would recommend reaching out the authors of the paper listed on that antibody page for access to the anitbody, in particular I would contact the creator of the antibody:

Kunihiro Matsumoto
https://wormbase.org/resources/person/WBPerson1315#01--10

I hope that helps.
