### ISSUE TITLE
  hi guys, how can I download the C. el...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7375]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;hi guys,<br/>how can I download the C. elegans proteome from this website? I assume the aa seq of all proteins is saved somewhere within a wormbase database. <br/>thanks,<br/>Matthias</p>

**Reported by:** matt************** (mtru******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

**Comment by epaule** [comment]
the easiest way is going tot Downloads -> "Listed by Species" and  then pick the Caenorhabditis elegans without strain identification.Or as variant: go to Directory -> C.elegans -> Downloads

**Comment by chris-grove** [comment]
Just to add to what Michael said: you can access a protein FASTA file for N2 C. elegans (reference genome) on our FTP site here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758

Look for and download the file with label ending in "protein.fa.gz"
