### ISSUE TITLE
  Hi, I'm wondering if there are any ma...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7376]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I'm wondering if there are any manufacturers that sell K complete medium for liquid culture of C. elegans. I plan on diluting BPS in this medium to treat my worms. </p>

**Reported by:** Noel******** (noel*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by chris-grove** [comment]
Email to user:
"""
You might get some helpful feedback on such questions from members of our WormBase Community Forum:

https://forums.wormbase.org/

Once you register, you can post questions to the forum and the community can respond and (hopefully) provide useful advice.
"""
