### ISSUE TITLE
Please check the correctness of F47F2.1 as a prima...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7377]
*Help Desk query collected when no chat operators were online. Follow up required.*

Please check the correctness of F47F2.1 as a primary target for kin-1 (ZK909.2). I believe this is an error and may relate all the way back to Manning Wormbook 2005 that incorrectly lists kin-1 as F47F2.1

**Reported by:** Shan***** (shan***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/rnai/WBRNAi00108308#041--10">https://wormbase.org/species/c_elegans/rnai/WBRNAi00108308#041--10</a>
**Browser:** Firefox 70.0

**Comment by raymond91125** [comment]
Hi Shane,

I'm not sure what you meant by (WormBase states) "F47F2.1 as a primary 
target for kin-1 (ZK909.2)".

The RNAi page you visited was about a double RNAi experiment 
<https://wormbase.org/species/c_elegans/rnai/WBRNAi00108308#6--5> (see 
Remark and attached) that resulted in a WT phenotype. The "Primary 
target" refers to that for the RNAi. It does not speak to any other 
relationship between F47F2.1 and ZK909.2.

If you think our presentation is confusing some how, please let us know 
specifically why.

Thanks.

Raymond

On 01/11/2019 11:03 AM, no-reply@wormbase.org wrote:
> offline chat Please check the correctness of F47F2.1 as a primary 
> target for kin-1 (ZK909.2). I believe this is an error and may relate 
> all the way back to Manning Wormbook 2005 that incorrectly lists kin-1 
> as F47F2.1
>
> Submitted From:
>   https://wormbase.org/species/c_elegans/rnai/WBRNAi00108308#041--10 
> https://wormbase.org/species/c_elegans/rnai/WBRNAi00108308#041--10 
> <http://www.wormbase.org/https://wormbase.org/species/c_elegans/rnai/WBRNAi00108308#041--10> 
>
>
> This issue has been assigned ticket number: #7377. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7377>.
>
> Reported by: Shane Rea (shanerea@uw.edu)
> 01 Nov 19 18:03
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by chris-grove** [comment]
My email to user:
"""
You can see that the authors performed RNAi against both genes (double RNAi) in Table S4 of the paper:

https://dev.biologists.org/content/suppl/2008/10/24/135.22.3665.DC1/DEV027060TableS4.pdf

Please let me know if you have any questions or if something still seems wrong.
"""
