### ISSUE TITLE
  502 Bad Gateway in Enrichment Analysi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7378]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;502 Bad Gateway in Enrichment Analysis<br/>https://www.wormbase.org/tools/enrichment/tea/tea.cgi</p>

**Reported by:** Anon***** (liyo*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by chris-grove** [comment]
My email response:
"""
Thank you for bringing this issue to our attention! We will get this fixed as soon as possible.
"""

**Comment by chris-grove** [comment]
@raymond91125  @azurebrd 
None of the SObA graphs are loading on the WormBase production site.

**Comment by chris-grove** [comment]
Email to user:
"""
The Gene Set Enrichment Analysis tool should be back up and running again.

Please let us know if you experience any other issues.

Thanks for letting us know about the problem.
"""
