### ISSUE TITLE
  How do I get list of all gene familie...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7379]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get list of all gene families and list of genes present in each of these families in C. elegans.</p>

**Reported by:** ayus* (ayus*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.85 Safari/537.36

**Comment by chris-grove** [comment]
My email response to user:
"""
This depends a bit on what you mean by a gene family. In WormBase, we have "Gene classes" which share a common public name prefix, like "unc-" for the uncoordinated gene class (genes whose perturbation results in an uncoordinated phenotype) which represent genes that share a common phenotype, but we also have gene classes that represent more molecular classification, like C. elegans homeobox genes with the "ceh" gene class. You can browse available gene classes and gene members for each available species from the gene class browsing page, discoverable under the "Directory" menu (look for "BROWSE > By Resource > Gene Class") at the top of any WormBase page:

https://wormbase.org/resources/gene_class#1-0-5

Note that some genes of the family may not have that gene class designation. So to see the "helix loop helix" family with class designation "hlh", type "hlh" into the Basic Search widget search box, click "Search" and then click on the resulting "hlh" class result to go to the class page:

https://wormbase.org/resources/gene_class/hlh#01--10

The Current Genes widget will include the gene members from each species.

If you're interested in gene families classified by encoded protein domains, you can go to the Directory menu, click on "Basic Search", click on the "Motif" class, and search for your protein motif or domain name of interest. You can also search by PFAM or INTERPRO domain IDs by prefixing, respectively, each ID with "PFAM:" or "INTERPRO:". So to search for the "Helix-loop-helix DNA-binding domain" PFAM domain with ID "PF00010", search for a motif in WormBase with the text "PFAM:PF00010":

https://wormbase.org/resources/motif/PFAM:PF00010#014--10

The Overview widget on each motif page should give you information about gene members from each species. Note that there are a lot of inter-related domains/motifs, so to be inclusive search for the most generic terms first.
"""
