### ISSUE TITLE
  Dear Sir/Madam, for the last few days...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7380]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir/Madam,<br/>for the last few days, I have a problem (502 Bad Gateway) with the Gene Set Enrichment Tool (https://wormbase.org/tools/enrichment/tea/tea.cgi). Do you have any information when the tool will be available again? Thank you. <br/>Best regards, <br/>Vladyslava</p>

**Reported by:** Vlad***************** (v.li***********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

**Comment by chris-grove** [comment]
My email response to user:
"""
Thank you for bringing this issue to our attention! We will get this fixed as soon as possible.
"""

Duplicate #7378 
Closing

**Comment by raymond91125** [comment]
Hi Vladyslava,

We have restored the tool. Thanks for the report.

It appears that the server fell on Nov 02 for unknown reasons. Please 
let us know if you experience any issues again.

Cheers,

Raymond


On 04/11/2019 5:51 AM, no-reply@wormbase.org wrote:
> Everything's broken!
>
>   Dear Sir/Madam,
> for the last few days, I have a problem (502 Bad Gateway) with the 
> Gene Set Enrichment Tool 
> (https://wormbase.org/tools/enrichment/tea/tea.cgi). Do you have any 
> information when the tool will be available again? Thank you.
> Best regards,
> Vladyslava
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7380. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7380>.
>
> Reported by: Vladyslava Liudkovska (v.liudkovska@biol.uw.edu.pl)
> 04 Nov 19 13:51
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
