### ISSUE TITLE
Gene page interaction widget Cytoscape network viewer bugs

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7383]
Hi @sibyl229 
This is the placeholder ticket for the bugs we just discussed. I'll make a screen capture video to demonstrate the various issues I'm seeing.

**Comment by chris-grove** [comment]
Here's a screen capture video:

https://www.dropbox.com/s/lk17ul05242vcw2/genepageinteractionswidgetcytoscapenetworkbugs_nov_4_2019.mov?dl=0

Issues include:

1) The graph defaulting to center at the upper left of the view

2) The whole network disappearing when zooming or panning

3) Nodes disappearing and only edges are visible

4) The "Re-position" button doesn't appear to recenter the graph

**Comment by sibyl229** [comment]
Hi @chris-grove I think the issue is fixed on staging. But as a result, I had to turn on the graph on all the gene pages. For test: https://staging.wormbase.org/species/c_elegans/gene/WBGene00003912#-8-10

**Comment by chris-grove** [comment]
@sibyl229 
Yes, looks a lot better thanks!
I'll close the ticket.

**Comment by sibyl229** [comment]
@chris-grove Thanks for checking! The same change for the network viewer is also on production now.

**Comment by chris-grove** [comment]
@sibyl229 
Looks good thanks!
