### ISSUE TITLE
  I'm trying to track down the source o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7384]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm trying to track down the source of data that underlies the "Mass spec peptides" track in the genome browser, but am not having any success, so I'm hoping you can help me out.<br/>Specifically I'm interested in the mass spec data for this F46G11.6 but if there are multiple data sources that contribute to the MS track overall, then I'd be happy to learn about that as well.<br/>Many thanks in advance!<br/>Best,<br/>Cameron</p>

**Reported by:** Came*********** (c.we******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15

**Comment by scottcain** [comment]
Another indication that should should be good "About this track" information.

**Comment by gw3** [comment]
Cameron,

We will try to change the way that the mass spec data is displayed on 
the JBrowse tracks, but here are details of the data you are interested 
in matching F46G11.6. These three all come from the same project.


MSP:NVQYPNHFEAGIFNPFPIR

Reference WBPaper00032058 (PubMed 18653799)
Remark Data from the modENCODE experiment modENCODE_2557
Strain N2
Life_stage WBls:0000002 (All C. elegans development stages, including 
embryo, larva and adult stage.)



MSP:HFEAGIFNPFPIR

Reference WBPaper00032058 (PubMed 18653799)
Remark Data from the modENCODE experiment modENCODE_2557
Strain N2
Life_stage WBls:0000002 (All C. elegans development stages, including 
embryo, larva and adult stage.)



MSP:ASSAAVVLFCVTTVVPIEHGQCTR

Reference WBPaper00032058 (PubMed 18653799)
Remark Data from the modENCODE experiment modENCODE_2557
Strain N2
Life_stage WBls:0000002 (All C. elegans development stages, including 
embryo, larva and adult stage.)


Gary Williams
