### ISSUE TITLE
Cannot watch video in Wormbook

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7392]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I cannot watch video in Wormbook as it shows "Unsupported Plug-ins".  I tried to find how to solve (Safari Plug-ins setting, Java, search through net...) and I just cannot make it work. Could you please navigate me how to have correct Plug-Ins?  This may not be the right place to ask but I hope you can help me out. Thank you.  </p>

**Reported by:** Masa** (masa*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Comment by chris-grove** [comment]
My email response to user:
"""
WormBook is not directly managed by WormBase but we can get you in touch with the right people. WormBook has its own feedback form where you can send in comments and questions:

http://www.wormbook.org/db/misc/feedback

Could you clarify exactly which movie(s) (on which page or in which chapter) you are experiencing issues with? That may help us identify the problem and a solution.
"""

**Comment by raymond91125** [comment]
Hi Masako,

Just an update: we ran into some issues with WormBook legacy site host with regard to adding files or file directories, and before that's resolved we cannot fix the video display.

But GOOD NEWS is, our PI Paul Sternberg just suggested you read those articles on NCBI Bookshelf (https://www.ncbi.nlm.nih.gov/books/NBK19662/), where we have an archive of everything, and their video displays are all up to date.

Thanks to Paul for the nice suggestion!

Best wishes,

Daniel

**Comment by tharris** [comment]
Semi-resolved, at least from WB perspective.
