### ISSUE TITLE
Turn off "Nearby interactions" by default on gene page Cytoscape network graph

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7394]
@sibyl229 
Based on our discussions: I know we may eventually decide to turn on nearby interactions by default on some genes for which there are very few interactions, but for now can we just turn off nearby interactions by default on all gene pages as requested by @WBjae ?

**Comment by WBjae** [comment]
@chris-grove 
Appreciate putting this ticket.
@sibyl229 
Can we do this for the next update, WS274?

**Comment by chris-grove** [comment]
This feature has already been implemented. Closing.
