### ISSUE TITLE
This site was so helpful!...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7396]
*Help Desk query collected when no chat operators were online. Follow up required.*

This site was so helpful!

**Reported by:** Eve (em14**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/transcript/T14B4.7.1#306--10">https://www.wormbase.org/species/c_elegans/transcript/T14B4.7.1#306--10</a>
**Browser:** Chrome 78.0.3904.87

**Comment by chris-grove** [comment]
Thanks for the positive feedback! Let us know if we can help you with anything.
