### ISSUE TITLE
Do you ship worms? I need them form my project...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7397]
*Help Desk query collected when no chat operators were online. Follow up required.*

Do you ship worms? I need them form my project

**Reported by:** Ira (im11**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001072#06-4f-3">https://wormbase.org/species/c_elegans/gene/WBGene00001072#06-4f-3</a>
**Browser:** Safari 13.0.2

**Comment by chris-grove** [comment]
You can order worm strains from the Caenorhabditis Genetics Center (CGC):

https://cgc.umn.edu/

Good luck!
