### ISSUE TITLE
Hello, I'm interested in purchasing a C. elegan mo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7398]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I'm interested in purchasing a C. elegan model to facilitate my studying, I was thinking the larger the better. Do you have anything of this sort?

**Reported by:** Chri***** (cm15**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Safari 13.0.2

**Comment by chris-grove** [comment]
My email response to user:

"""
I'm not aware of any physical models of C. elegans available for purchase, but you can explore a virtual model of the adult hermaphrodite using a model that I built in Blender, available here:

http://caltech.wormbase.org/virtualworm/

Please let me know if you have any questions.
"""
