### ISSUE TITLE
I had a question regarding C. elegans genetic nome...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7400]
*Help Desk query collected when no chat operators were online. Follow up required.*

I had a question regarding C. elegans genetic nomenclature upon CRISPR. If I make one modification using CRISPR (e.g. bus-50(e5000), and in a separate experiment modify bus-50(e5000) to create another lesion elsewhere in the gene, would it be bus-50(e5000e5001) or would it be bus-50(e5002). In the million mutation project, different alleles in one gene are labelled as a list of alleles. Furthermore, revertants are labelled as shown- lin-12(n676n930)-n930 is an intragenic revertant of the n676 lin-12 gain of function allele. I was wondering if there was a standard in the field? Thank you!

**Reported by:** Snus************ (snus*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10">https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10</a>
**Browser:** Chrome 77.0.3865.120

**Comment by Paul-Davis** [comment]
I need to check on this as I'm not 100% sure, will seek guidance and respond to the user.

**Comment by Paul-Davis** [comment]
Dear Snusha,

Thank you for contacting wormbase. Just so I understand, are we talking 
about the Strain genotype or describing a compound variation. Our 
current data model does not allow us to store multiple mutated loci in a 
single object. There have been a number of questions regarding 
additional modifications with CRISPR. I will raise this at our call 
today and get back to you.

Paul



On 06/11/2019 18:13, no-reply@wormbase.org wrote:
> offline chat I had a question regarding C. elegans genetic 
> nomenclature upon CRISPR. If I make one modification using CRISPR 
> (e.g. bus-50(e5000), and in a separate experiment modify bus-50(e5000) 
> to create another lesion elsewhere in the gene, would it be 
> bus-50(e5000e5001) or would it be bus-50(e5002). In the million 
> mutation project, different alleles in one gene are labelled as a list 
> of alleles. Furthermore, revertants are labelled as shown- 
> lin-12(n676n930)-n930 is an intragenic revertant of the n676 lin-12 
> gain of function allele. I was wondering if there was a standard in 
> the field? Thank you!
>
> Submitted From:
> https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10 
> https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10 
> <http://www.wormbase.org/https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10> 
>
>
> This issue has been assigned ticket number: #7400. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7400>.
>
> Reported by: Snusha Ravikumar (snusha.ravikumar@yale.edu)
> 06 Nov 19 18:13
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Paul

Thanks for getting back to me. I’m talking about Strain genotype nomenclature and multiple edits to one gene by CRISPR. Look forward to hearing from you. I’m writing a nomenclature protocol for new lab members and just wanted to clarify a debate on-going in our lab :)

Thank you!
Snusha
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Paul-Davis** [comment]
Hi,

Sorry for the delay in getting back to you.

This is the outcome of our discussions for your specific question from 
the variation side of things:

The second lesion would be e5001; putting it in the order e5000e5001 
helps the reader know that this change was added to the e5000 allele. 
Once the author explains what bus-50(e5000e5001) is, then they can use 
bus-50(e5001) for short

WB data storage:Would we do something similar to the Cis double mutants 
(curate e5000 and e5001 but then link them via (e5000e5001) Allele object).

Intragenic revertants would get an new allele name, e500

The genotype would use the relevant variant details at the time of 
submission/publication. If things progress or change then the genotype 
would be updated to reflect the changes....but I think what you proposed 
fits the nomenclature guide.

Hope this helps.

Paul




On 21/11/2019 14:03, Ravikumar, Snusha wrote:
> Hi Paul
>
> Thanks for getting back to me. I’m talking about Strain genotype 
> nomenclature and multiple edits to one gene by CRISPR. Look forward to 
> hearing from you. I’m writing a nomenclature protocol for new lab 
> members and just wanted to clarify a debate on-going in our lab :)
>
> Thank you!
> Snusha
> Get Outlook for iOS <https://aka.ms/o0ukef>
> ------------------------------------------------------------------------
> *From:* Paul Davis <paul.davis@wormbase.org>
> *Sent:* Thursday, November 21, 2019 7:17:24 AM
> *To:* 
> reply@reply.github.com 
> <reply@reply.github.com>; 
> help@wormbase.org <help@wormbase.org>
> *Cc:* Ravikumar, Snusha <snusha.ravikumar@yale.edu>
> *Subject:* Re: [wormbase-help] offline chat transcript: I had a 
> question regarding C. elegans genetic nome... (Snusha Ravikumar)
>
> Dear Snusha,
>
> Thank you for contacting wormbase. Just so I understand, are we 
> talking about the Strain genotype or describing a compound variation. 
> Our current data model does not allow us to store multiple mutated 
> loci in a single object. There have been a number of questions 
> regarding additional modifications with CRISPR. I will raise this at 
> our call today and get back to you.
>
> Paul
>
>
>
> On 06/11/2019 18:13, no-reply@wormbase.org 
> <mailto:no-reply@wormbase.org> wrote:
>> offline chat I had a question regarding C. elegans genetic 
>> nomenclature upon CRISPR. If I make one modification using CRISPR 
>> (e.g. bus-50(e5000), and in a separate experiment modify 
>> bus-50(e5000) to create another lesion elsewhere in the gene, would 
>> it be bus-50(e5000e5001) or would it be bus-50(e5002). In the million 
>> mutation project, different alleles in one gene are labelled as a 
>> list of alleles. Furthermore, revertants are labelled as shown- 
>> lin-12(n676n930)-n930 is an intragenic revertant of the n676 lin-12 
>> gain of function allele. I was wondering if there was a standard in 
>> the field? Thank you!
>>
>> Submitted From:
>> https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10 
>> <https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwormbase.org%2Fabout%2Fuserguide%2Fnomenclature%235d34cmjf82eak7hlb6g910i--10&data=02%7C01%7Csnusha.ravikumar%40yale.edu%7Caf33c022951b4b163b5a08d76e7cc7a4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C1%7C637099354515965136&sdata=hX%2F6Z15N7BNAS32hQHf6f4wWl%2F%2BsPsONEJAMoWhtRjs%3D&reserved=0>https://wormbase.org/about/userguide/nomenclature#5d34cmjf82eak7hlb6g910i--10 
>> <https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wormbase.org%2Fhttps%3A%2F%2Fwormbase.org%2Fabout%2Fuserguide%2Fnomenclature%235d34cmjf82eak7hlb6g910i--10&data=02%7C01%7Csnusha.ravikumar%40yale.edu%7Caf33c022951b4b163b5a08d76e7cc7a4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C1%7C637099354515965136&sdata=uI1gQACAfpvofkLJ%2BlYh%2ByicKOXGWRnXw0tb%2FPLQQB4%3D&reserved=0>
>>
>> This issue has been assigned ticket number: #7400. Follow progress on 
>> our issue tracker 
>> <https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWormBase%2Fwebsite%2Fissues%2F7400&data=02%7C01%7Csnusha.ravikumar%40yale.edu%7Caf33c022951b4b163b5a08d76e7cc7a4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C1%7C637099354515975129&sdata=kdKuNkxCJc15TUManjmdnZEmSI1vR8Ju58%2BeTTpAHwk%3D&reserved=0>. 
>>
>>
>> Reported by: Snusha Ravikumar (snusha.ravikumar@yale.edu 
>> <mailto:snusha.ravikumar@yale.edu>)
>> 06 Nov 19 18:13
>>
>> This question was reported via the web interface at wormbase.org. You 
>> can alsoemail us <mailto:help@wormbase.org> directly.
>>
>> -- 
>> -- 
>> You received this message because you are subscribed to the 
>> "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org 
>> <mailto:help@wormbase.org>
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en 
>> <https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgroups.google.com%2Fa%2Fwormbase.org%2Fgroup%2Fhelp%3Fhl%3Den&data=02%7C01%7Csnusha.ravikumar%40yale.edu%7Caf33c022951b4b163b5a08d76e7cc7a4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C1%7C637099354515975129&sdata=xwv6Cnj6vLU%2ByHwOxs3ocugh4tajYj5yMC63UN4n%2F8c%3D&reserved=0>
>>
>
> -- ===========================================WormBaseEuropean Bioinformatics Institute (EMBL-EBI)European Molecular Biology LaboratoryWellcome Trust Genome CampusHinxtonCambridge CB10 1SDUnited Kingdom ===========================================


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
