### ISSUE TITLE
could you fix the genome browser preview, it shows...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7401]
*Help Desk query collected when no chat operators were online. Follow up required.*

could you fix the genome browser preview, it shows Loading only, no data for a few days. thanks.

**Reported by:** ziyu**** (wuzi*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00000898#09fb3e6714a-cdkg-10-b3e714acg">https://wormbase.org/species/c_elegans/gene/WBGene00000898#09fb3e6714a-cdkg-10-b3e714acg</a>
**Browser:** Safari 13.0.1

**Comment by scottcain** [comment]
I'm not sure what's going on here, as it works fine for me.  I'll follow up with the user to see if we can figure it out.

**Comment by scottcain** [comment]
after some back and forth with the user on unrelated issues, we figured out it was just a caching issue and has been resolved.
