### ISSUE TITLE
RNAi objects not loaded properly into ACEDB?

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7403]
I just noticed a couple of RNAi objects that were uploaded via Citace that ended up, for some reason, only getting partially read in to WS273 ACEDB:

WBRNAi00112569
WBRNAi00112570

The RNAi ACE file that I uploaded for WS273 looks like this for these entries:

<img width="667" alt="Screenshot 2019-11-06 15 44 55" src="https://user-images.githubusercontent.com/611382/68341336-3fa44700-00b6-11ea-8457-46c0758d6619.png">

and they load into CitaceMinus just fine when I read them in from that same file:

<img width="635" alt="Screenshot 2019-11-06 16 22 39" src="https://user-images.githubusercontent.com/611382/68341387-58146180-00b6-11ea-8920-412ca55a745d.png">

<img width="632" alt="Screenshot 2019-11-06 16 23 14" src="https://user-images.githubusercontent.com/611382/68341393-5cd91580-00b6-11ea-8945-6126d6ac6626.png">

but in WS273 ACEDB they are missing most of the important data (including sequence which implicates the gene):

<img width="525" alt="Screenshot 2019-11-06 16 24 38" src="https://user-images.githubusercontent.com/611382/68341440-737f6c80-00b6-11ea-86f6-e1b8f1d8a86c.png">

<img width="529" alt="Screenshot 2019-11-06 15 46 38" src="https://user-images.githubusercontent.com/611382/68341453-78442080-00b6-11ea-9164-b5cf80e37376.png">

I don't know why this might have happened.

**Comment by khowe** [comment]
This has the hallmark of these object being deleted (at some point in the process), but recreated by cross-reference from other objects.
@epaule was the build manager for WS273

**Comment by epaule** [comment]
Hi Chris and Kevin,

if you look at the citace screenshot above, you can see that the Species
tag is not populated. Since we dump RNAi in a species specific way, all
without any species whatsoever will not appear with all data in the final
database.
I would assume that the data you can see, is from back references of other
objects.

best regards,

Michael Paulini

P.S.: it is also missing from WS274 for the above reason

**Comment by chris-grove** [comment]
@epaule 
Ah, that explains it. Thanks! I'll try to correct any cases missing a species annotation. Maybe, going forward, we can assume it is C. elegans unless otherwise specified?

**Comment by epaule** [comment]
Hi Chris,

I do believe we curated RNAi for other nematodes, so i would rather have
the species fixed upstream than default to C.elegans.

M

**Comment by epaule** [comment]
Paul said that Wen has a set of checks she runs before uploading citace,
maybe she could add it to them?

**Comment by chris-grove** [comment]
@epaule 
OK, all annotations fixed in the curation database
