### ISSUE TITLE
  I wanna submit new gene name in the "...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7404]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I wanna submit new gene name in the "gene description" website.<br/>Every time I type in my name"visitor_name", it dispay one selection drop-down-WBPerson42098. I am not sure this is my WBID, because I have never registered in wormbase, but how can i submit data without using wrong person ID?</p>

**Reported by:** Qi Y** (elle*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

**Comment by chris-grove** [comment]
My email response to user:
"""
We assign WBPerson IDs for any authors of C. elegans papers or meeting abstracts. To check if this person ID is yours, please check the corresponding WormBase Person page:

https://wormbase.org/resources/person/WBPerson42098#031--10

If all of that information is correct and you are the author "Yan Q" on the publication:

https://wormbase.org/resources/paper/WBPaper00054570#036--10

Xu F, Feng X, Chen X, Weng C, Yan Q, Xu T, Hong M, Guang S. A Cytoplasmic
Argonaute Protein Promotes the Inheritance of RNAi. Cell Rep. 2018 May
22;23(8):2482-2494. doi: 10.1016/j.celrep.2018.04.072. PubMed PMID: 29791857.


Then this is your person ID and you can go ahead with your submission.

Also, to request new gene names for genes, please email genenames@wormbase.org (CC'ed).
"""
