### ISSUE TITLE
Transposon Summary Page - Location Widget issue

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7407]
Hi,

I was going to ask to get the Transposon and Transposon_genes tracks added as the default tracks for the location widget view as the current view of the jbrowse image has zero features.

Then I noticed that the url and the resulting display when clicked on gives the correct data so this seems like a bug in the image cache??

Paul

**Comment by scottcain** [comment]
Hi @Paul-Davis 

That image is generated dynamically, no cache is used.  I'm looking into what networking issues might be causing the problem.

**Comment by scottcain** [comment]
I believe I fixed it; can you please double check that's the case (using incognito mode might be needed to get it to reload the config and not use a local cache)

**Comment by tharris** [comment]
Apparently resolved. Closing.
