### ISSUE TITLE
  i am trying to research the effects o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7424]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;i am trying to research the effects of propylene glycol on c elegens. I am having trouble finding a type of c elegen that is more susceptible to react to propylene glycol.</p><p>What were you doing? <br />&nbsp;&nbsp;SIRS Research</p>

**Reported by:** m sy** (mohs****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12499.51.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.92 Safari/537.36

**Comment by chris-grove** [comment]
Email to user:
"""
It doesn't look like we have any data in WormBase regarding the response of C. elegans to propylene glycol or any info on hypersensitive mutants. You can search PubMed like this:

https://www.ncbi.nlm.nih.gov/pubmed?term=(%22Propylene+Glycol%22%5BMesh%5D)+AND+%22Caenorhabditis+elegans%22%5BMesh%5D

This returns one paper that seems relevant to your research:

https://www.ncbi.nlm.nih.gov/pubmed/?term=26637209

Panitz D, Swamy H, Nehrke K. A C. elegans model of electronic cigarette use:
Physiological effects of e-liquids in nematodes. BMC Pharmacol Toxicol. 2015 Dec 
4;16:32. doi: 10.1186/s40360-015-0030-0. PubMed PMID: 26637209; PubMed Central
PMCID: PMC4669627.

Best of luck!
"""
