### ISSUE TITLE
WormBase staging site is down?

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7426]
I keep getting 502 Bad Gateway errors.

Maybe it's intended to be down for maintenance/upgrades?

I'd like to do some testing for issue #7347

**Comment by sibyl229** [comment]
Hi @chris-grove the staging server is restored now. I'm not sure what happened to it, but restarting the server fixed the issue. Thanks for letting me know.

**Comment by chris-grove** [comment]
@sibyl229 
Yep! Up and running now, thanks!
