### ISSUE TITLE
  We have generated and published new t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7427]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We have generated and published new transgenic strains of C. elegans, with novel mutations in the wah-1 gene (Troulinaki et. al., 2018, Cell Death and Discovery) as well as novel overexpressing lines generated by CRISPR/Cas9 (Piazzesi et al 2016, Cell Reports). How can we properly annotate this gene/transgene so that the information about these new alleles is available on WormBase?<br/>Thank you for your help<br/>Regards,<br/>visitor_name Piazzesi</p>

**Reported by:** Anto*** (Anto********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by gw3** [comment]
Can anyone help Piazzesi with this query. (adding allele information to WormBase)?

**Comment by chris-grove** [comment]
Email to user:
"""
You can submit new alleles, and their associated data, via our allele submission form:

https://wormbase.org/submissions/allele_sequence.cgi

This form is discoverable from any WormBase page by clicking on "Submit Data" under the search bar at the upper right corner of the page, then in the "Community Curation" widget, click on the "Fill out online form" to the right of "Allele Sequence Data Submission":

https://www.wormbase.org/about/userguide/submit_data#01--10

This form will capture general allele information, but not so much the details of transgenes. If you send me a list of the transgene information (how it was constructed, what promoter drives expression and what gene(s) is/are expressed, etc.) I can annotate that in our curation database.

Let me know if you have any questions.
"""
