### ISSUE TITLE
visitor_name (visitor_email): Hi, my name is Xiaof...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7429]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, my name is Xiaofei Bai from Andy Golden's lab at NIH. I was wondering is it possible to use wormbase isoform graphic for a publication, if so, should we cite the wormbase in the reference or in the acknowledgment section? Thank you</br>Chris: Hi Xiaofei, sure sounds good! It would be great if you could cite our most recent NAR paper: https://www.ncbi.nlm.nih.gov/pubmed/31642470</br>Chris: Also, at the bottom of every WormBase page (in the footer) we have a link called "How to Cite"</br>Chris: https://wormbase.org/about/citing_wormbase#012--10</br>Chris: So if you want to cite a particular page you can also do that</br>visitor_name (visitor_email): Okay, thank you. We are submitting a paper to elife, they request copyrighted materials. Is there any official evidence of permission from wormbase that we can use for submission?</br>Chris: Hmm, other than citing WormBase as described in the linked documentation, I don't think so, but I can double check if there is something special you should do for isoform graphics. Out of curiosity, how are you obtaining the isoform graphic? We have a couple of tools that may help you obtain a high quality image</br>visitor_name (visitor_email): Thank you Chris. I did the screenshot and image was not perfect. Is there any suggestion for a high resolution for the isoform figures?</br>Chris: There are two options: 1) Using the older GBrowse tool and 2) Using the newer JBrowse tool</br>Chris: So for JBrowse for example</br>Chris: https://wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&amp;loc=V%3A20779194..20785989&amp;tracks=Curated_Genes&amp;highlight=</br>Chris: here's the hif-1 locus</br>Chris: At the top right of the screen is a "Screen Shot" button</br>Chris: Click on that and you should get a pop-up dialog box to enter in specifications for your image</br>Chris: You can choose to output as PNG, JPG, or PDF</br>visitor_name (visitor_email): Okay thank you very much Chris, I will give a try</br>Chris: You can also try the older GBrowse "Save Snapshot" tool, but you might want to play with each to see what works best for you</br>Chris: OK sounds good</br>Chris: Once we're done chatting, we will both receive an email transcript of this chat. I will forward that to the rest of the WormBase group to see if anyone has additional suggestions about citing WormBase graphics</br>visitor_name (visitor_email): Okay, sounds great.</br>Chris: It would probably be a good idea to include the date and WS release version when you cite the image</br>Chris: currently we are on the WS273 release</br>visitor_name (visitor_email): Its my first time to try the online chat, it works great. I will recommend my coworker to try this</br>Chris: OK, great, glad you like it! :)</br>visitor_name (visitor_email): Yes, I just told Isabella in our lab, she loves it too ;)</br>Chris: Nice!</br>visitor_name (visitor_email): Have a great day Chris, thank you very much again for the help.</br>Chris: OK, thanks! You're welcome! You too!

**Reported by:** xiao******* (baix*********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide#2--10">https://www.wormbase.org/about/userguide#2--10</a>
**Browser:** Chrome 78.0.3904.97

**Comment by chris-grove** [comment]
Duplicate #7428
