### ISSUE TITLE
2nd Italian C.elegans Meeting

### ISSUE THREAD

**Issue by gw3** [WormBase/website#7430]
Hi,
we are pleased to announce the organization of the "2nd Meeting of the Italian C. elegans Research Community" (MICeRCo) to be held at the IBBR, CNR, Naples, Italy 5- 6 March 2020. The organizers are: Elia Di Schiavi (IBBR, Naples) and Simone Martinelli (ISS, Rome).
Website: www.micerco.it
Registration deadline: 15th December 2019.
The official language of the congress will be English.
Thanks,
Elia

Dr. Elia Di Schiavi, PhD
Institute of Biosciences and BioResources, IBBR
Department of Biology, Agriculture and Food Science - CNR
Via Pietro Castellino 111,  
80131 Naples
Italy
Ph  office +390816132365
Ph Lab	 +390816132418/468
skype name: elilulis 
email addresses: 
elia.dischiavi@ibbr.cnr.it
eliadischiavi@gmail.com
http://www.ibbr.cnr.it/ibbr/info/people/elia-di-schiavi

-- 
-- 
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

**Comment by epaule** [comment]
Hi Elia,

i put it onto our front page in the meetings section.

best regards,

Michael
