### ISSUE TITLE
  I am wondering where the endpoint is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7433]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am wondering where the endpoint is of a cosmid: F56B12.  This does not seem to be in wormbase anywhere.  Do you know where I can find this out, even approximately?<br/>It seems like this would have been in the old acedb (as we old-timers remember it) so presumably old physical map data must exist somewhere....</p>

**Reported by:** Will*********** (wsch**********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by Paul-Davis** [comment]
Dear Prof. Schafer

You are right....most of the original sequencing clones were available 
on the Pmap in the old acedb database.

I have attached the image that can be generated in an xace session.

The clone you are after only has minimal information and the ends were 
never correctly placed on the reference sequence so we do not have a way 
to add them to our gff files:

https://wormbase.org/species/c_elegans/clone/F56B12#20431--10

On the physical map you can see that R07D5, C11G10 and F09B12 were all 
golden path clones that overlap F56B12.

If I can be of further help, please feel free to get back in touch.

Paul







On 16/11/2019 09:06, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I am wondering where the endpoint is of a cosmid: F56B12. This does 
> not seem to be in wormbase anywhere. Do you know where I can find this 
> out, even approximately?
> It seems like this would have been in the old acedb (as we old-timers 
> remember it) so presumably old physical map data must exist somewhere....
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7433. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7433>.
>
> Reported by: William Schafer (wschafer@mrc-lmb.cam.ac.uk)
> 16 Nov 19 09:06
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:68.0) Gecko/20100101 
> Firefox/68.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
