### ISSUE TITLE
where can I find the molecular details of dpy-11
T...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7434]
*Help Desk query collected when no chat operators were online. Follow up required.*

where can I find the molecular details of dpy-11
Thanks

**Reported by:** jimm* (jimi******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00001073?species=c_elegans#b0-9f-3">https://wormbase.org/species/c_elegans/gene/WBGene00001073?species=c_elegans#b0-9f-3</a>
**Browser:** Chrome 78.0.3904.97

**Comment by epaule** [comment]
it depends a bit on which molecular detail you need. The page you were at when you sent the chat message should contain quite a few, but if you follow the links in the Sequences widget you can find more information (especially on the transcripts and proteins).
