### ISSUE TITLE
WS275 citace issues Expression_cluster::Gene connections and '((' in IDs that look wrong?

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7440]
Few errors for the start of the build:

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/citace/caltech_Expresion_cluster.ace
Expression_cluster : "WBPaper00057068:ints-4((RNAi)_downregulated"
Regulated_by_gene ints-4

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/citace/caltech_Expresion_cluster.ace
Expression_cluster : "WBPaper00057068:ints-4((RNAi)_downregulated_Cadmium"
Regulated_by_gene ints-4

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/citace/caltech_Expresion_cluster.ace
Expression_cluster : "WBPaper00057068:ints-4((RNAi)_upregulated"
Regulated_by_gene ints-4

Invalid object name format: /nfs/wormpub/BUILD/autoace/acefiles/primaries/citace/caltech_Expresion_cluster.ace
Expression_cluster : "WBPaper00057068:ints-4((RNAi)_upregulated_Cadmium"
Regulated_by_gene ints-4

Also noticed that there were some IDs with unbalanced '('s

Expression_cluster : "WBPaper00057068:ints-4((RNAi)_downregulated"

**Comment by Paul-Davis** [comment]
I have patched the correct WBGene ID for the above, but left the IDs as they are.

**Comment by WenChenWormBase** [comment]
Fixed the gene ID and the typos on the expression cluster names.
