### ISSUE TITLE
  how to understand the Genotype ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7442]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how to understand the Genotype</p>

**Reported by:** luya* (luya****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

**Comment by raymond91125** [comment]
This may get you started 
<https://wormbase.org/about/userguide/nomenclature#c--5>.

Cheers,

Raymond
