### ISSUE TITLE
  Dear Wormbase, Would you please clari...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7443]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Wormbase,<br/>Would you please clarify for me (or direct me to the page where it is explained) how to interpret results of the gene set enrichment analysis: specifically I want to figure out:<br/>- What is the difference in calculation/assignment behind Inferred Term and Enriched Term?<br/>- What does "Alliance Slim" mean?<br/>- What do "with or without direct annotation" terms mean?<br/>Thank you for building tools to support the research.<br/>Kind regards,<br/>Inna</p><p>What were you doing? <br />&nbsp;&nbsp;Was looking for my answers in Google and Wormbase, was not able to figure out.</p>

**Reported by:** Inna*********** (inna***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by raymond91125** [comment]
Hi Inna,

See answers below:

On 02/12/2019 6:27 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Dear Wormbase,
> Would you please clarify for me (or direct me to the page where it is 
> explained) how to interpret results of the gene set enrichment 
> analysis: specifically I want to figure out:
> - What is the difference in calculation/assignment behind Inferred 
> Term and Enriched Term?
>
The enriched terms are from your enrichment analysis result, whereas the 
inferred terms are from the respective ontology hierarchy included to 
help you see how the enriched terms are connected related to one another 
in the ontology graph.
>
> - What does "Alliance Slim" mean?
>
Alliance Slim terms are a subset of GO terms that are designated by 
Alliance Genome Resources (AGR). They are used in the GO ribbon plot, 
e.g. <https://wormbase.org/species/c_elegans/gene/WBGene00001135#3--10>. 
We indicate them in the graph for reference.
>
> - What do "with or without direct annotation" terms mean?
>
Alliance Slim With/Without Direct Annotation is a misnomer. It should be 
about with/without enrichment designations.

Cheers,

Raymond


> Thank you for building tools to support the research.
> Kind regards,
> Inna
>
> What were you doing?
>   Was looking for my answers in Google and Wormbase, was not able to 
> figure out.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7443. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7443>.
>
> Reported by: Inna Nikonorova (inna.nikonorova@rutgers.edu)
> 02 Dec 19 14:27
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/78.0.3904.108 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
