### ISSUE TITLE
  Hi! My name is visitor_name. I'm a po...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7445]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi! My name is visitor_name. I'm a postdoc at Columbia Univ. I'm interested in genes that are enriched in males, and I wonder if there's any way to get a list of all the male-enriched/specific genes from the FPKM expression data on worm base. Where would you suggest I start? Thanks! </p>

**Reported by:** Chen (cw29***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by chris-grove** [comment]
We annotate enriched gene lists in our "Expression cluster" objects in WormBase. If you click on the magnifying glass icon to the right of the WormBase search box (or, alternatively, under the "Directory" menu, under the "Search" heading, click on "Basic Search"), you will come to the WormBase basic search page. Click on "Expression cluster" under the "Classes" heading and then in the search box above type in "male enriched" and click on the magnifying glass icon (or hit ENTER/RETURN). When I perform this search the 5th hit is called

"WBPaper00050231:male_enriched"

Click on that link to see the Expression cluster page:

https://wormbase.org/species/c_elegans/expression_cluster/WBPaper00050231:male_enriched#0143--10

In the "Genes" widget you can get the list of 1,738 gene names. It is helpful at this point to copy and paste that list into our SimpleMine tool (discoverable under our Tools menu under the "DATA MINING AND BATCH QUERIES" section):

https://wormbase.org/tools/mine/simplemine.cgi

Select which attributes for each gene you would like to retrieve with the check boxes at the bottom of the form and click "query list". You can then download a TSV file table of the gene list. Careful when importing TSVs with gene names into Excel (or other spreadsheet programs) as some gene names get automatically converted to dates (e.g. apr-1, dec-1, etc.). I'm attaching an Excel file with the gene list and some basic information about each gene.

I hope that helps.

Please let us know if you have additional questions.
