### ISSUE TITLE
  Is there a way to report mis-annotate...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7448]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a way to report mis-annotated genes? For some reason fbf-2, https://wormbase.org/species/c_elegans/gene/WBGene00001402#0db-9f1g-4 suddenly has a ~13kb intron annotated. We're guessing it is due to homology to fbf-1, but it hasn't been annotated like this in the past, so we are confused as to why it has suddenly appeared. The only transcript that is known to exist is the one labeled as F21H12.5.4. Any advice would be much appreciated! Thank you!</p><p>What were you doing? <br />&nbsp;&nbsp;BLAST, Primer Design, looking up sequence information.</p>

**Reported by:** Bria********* (bcar*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by epaule** [comment]
it looks suspiciously like coming from some new nanopore reads.

But we will investigate more, as we currently trying new things to improve our UTR building procedure and it might be a unintended side-effect from that.

**Comment by gw3** [comment]
Brian,

The fbf-2 long erroneous transcripts were could be using new nanopore 
transcripts to automatically extend the 3' UTR.
This should be corrected in release WS275.
Thanks for pointing this out.

Gary Williams
WormBase
