### ISSUE TITLE
User report of slow gene searches

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#7454]
Hi,

I was just corresponding with Gary R (MGH) about the Author First Pass pipeline and he related his experience with the gene search:

"when i put in a gene name, it takes about 3 min for all kinds of useless junk to load and during that 3 min, chrome is completely frozen"

I don't know if other users have this experience (gene search typically works fine for me on Chrome), but is there anything we can do to help troubleshoot and improve his UX?

Thx.

**Comment by tharris** [comment]
Wow.  That's bad. I haven't heard any other reports like this. It definitely shouldn't be locking out his browser.  I suspect there's something wrong with his browser config?

**Comment by nuin** [comment]
I would say the same. Took me about 10 seconds to load a page (Jbrowse preview was the slowest) on  Safari behind a firewall. High probability of being machine specific.

**Comment by sibyl229** [comment]
@vanaukenk thanks for relaying the feedback. I wonder if we can contact him about the issue. Even though the symptom is in search, I suspect the cause lies somewhere else. It's going to be hard to try to guess what the cause might be without observing first hand what his is doing.

**Comment by vanaukenk** [comment]
Thanks @sibyl229 
I'll reply to Gary's original email and cc you.

**Comment by sibyl229** [comment]
@vanaukenk great, thanks!

**Comment by vanaukenk** [comment]
Problem solved on user's end; all working fine now.

**Comment by sibyl229** [comment]
@vanaukenk Thanks for coordinating the resolution of the issue!
