### ISSUE TITLE
John: Hi there. Need any help? Bob: Yes, please he...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7456]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

John: Hi there. Need any help?</br>Bob: Yes, please help me with billing.

**Reported by:** Bob *** (bob@***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.example.com/path">http://www.example.com/path</a>
**Browser:** Chrome 12.1

**Comment by tharris** [comment]
(Testing - direagard)
