### ISSUE TITLE
is there a way to download all protein sequences f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7460]
*Help Desk query collected when no chat operators were online. Follow up required.*

is there a way to download all protein sequences for a list of worm genes?

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00022505#04-9gfc6e17db-10">https://wormbase.org/species/c_elegans/gene/WBGene00022505#04-9gfc6e17db-10</a>
**Browser:** Safari 13.0.3

**Comment by nuin** [comment]
My answer to the email

```Hi Peter

Thanks for your message. Most of WormBase is attending a meeting at the moment, so I will try to help you to the best of my ability, there might be easier ways to achieve what you want.

One way is to use WormMine

http://intermine.wormbase.org

And try a query similar to the one below

<query model="genomic" view="Protein.organism.name Protein.CDSs.gene.name Protein.length Protein.sequence.residues" sortOrder="Protein.organism.name ASC" constraintLogic="A and B" >
  <constraint path="Protein.organism.name" op="=" value="Caenorhabditis elegans" code="A" />
  <constraint path="Protein.CDSs.gene" op="IN" value="C. elegans genes with a lethal - or descendant - allele phenotype as of WS257" code="B" />
</query>


In fact it would be a two step process:

- you will need to go to WormMine and create a list for your genes of interest. Click on the Lists tab and parse or upload a list of IDs. This will search the DB for matching IDs and will allow to finally select the items that should compose your list.

- with the list created and query above, you just need to to parse it on the QueryBuilder. Click on it in the tabs and then click on Import Query from XML and paste the query above. Where you see the 

 IN C. elegans genes with a lethal - or descendant - allele phenotype as of WS257 

Click on the edit button on its right side (blue) and in the dialog you should select your list. Click Add to query and then Show Results. You will see a final table with Protein ID, Gene name, protein length and residues.

Let me know if you have any questions.

Cheers

Paulo
```

**Comment by chris-grove** [comment]
My email to user:

`Just to add to Paulo's point:

Here's a screen recording of the step-by-step procedure for getting protein sequences for a list of genes in WormMine:

https://www.dropbox.com/s/s1z9mopew6x4abe/Protein_sequences_for_genes_in_a_list_%28WormMine%29_Dec_13_2019.mov?dl=0

and here's another screen recording of the procedure using WormBase ParaSite BioMart:

https://www.dropbox.com/s/pwj6id1h8xjp1o3/Protein_sequences_for_genes_in_a_list_%28ParaSite_BioMart%29_Dec_13_2019.mov?dl=0

Please let us know if you have any questions. I'd be happy to give a tutorial over a video call.`
