### ISSUE TITLE
WormMine Region search example query results in error

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7461]
When using WormMine's Region search, when I click on the "click to see an example" to see an example entry and then click on "Search" I get an error message:

intermine.wormbase.org says
I:100000..200000  doesn't match any supported format...

Whatever example gets populated should work in search. Here's a video:

https://www.dropbox.com/s/usdfuxtbuyjp6ic/WormMine_Region_search_bug_Dec_13_2019.mov?dl=0

**Comment by nuin** [comment]
I thought I had fixed this one some time ago. Maybe some didn't migrate fine when we upgraded the code. Working on it.

**Comment by nuin** [comment]
@chris-grove I decreased to two regions and it seems to be working on `I'm-dev1` now. Can you check and I will move to production?

**Comment by chris-grove** [comment]
@nuin 
Yep it works now on im-dev1

**Comment by nuin** [comment]
Thanks @chris-grove 

It's on production with the current three examples and it seems to work fine. 

Let me know if you see anything else odd.

**Comment by chris-grove** [comment]
Yes, fixed, thanks!
