### ISSUE TITLE
Life stage pages Overview widget showing "ARRAY" coded text

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7463]
The Overview widget on life stage pages is displaying some "ARRAY" coded text under the term label, for example:

https://wormbase.org/species/all/life_stage/WBls:0000010#0--10
<img width="380" alt="Screenshot 2019-12-16 12 36 44" src="https://user-images.githubusercontent.com/611382/70929320-e0185000-2000-11ea-8637-0fb48e8f0b90.png">

https://wormbase.org/species/all/life_stage/WBls:0000015#0--10
<img width="386" alt="Screenshot 2019-12-16 12 36 50" src="https://user-images.githubusercontent.com/611382/70929332-e8708b00-2000-11ea-9c09-af6d520b50c5.png">

This text should be removed.

**Comment by sibyl229** [comment]
Hi @chris-grove the life staging term definition should now be showing up on staging site, instead of the ARRAY(0x): https://staging.wormbase.org/species/all/life_stage/WBls:0000010#04--10 . Thanks for bringing it up.

**Comment by chris-grove** [comment]
@sibyl229 
Great! Thanks!

Closing
