### ISSUE TITLE
Are the genomes the same between worm base version...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7466]
*Help Desk query collected when no chat operators were online. Follow up required.*

Are the genomes the same between worm base versions. I understand that novel genes are discovered and some protein coding genes are later to be considered non-coding but are the genomic coordinates the same between versions. For instance, could I intersect a bed file made with WS256 with one made from WS273. If not how could I convert between the annotations. 

Thanks for your help and all you do at worm base.

**Reported by:** Will********** (wsch*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Safari 13.0.4

**Comment by epaule** [comment]
assuming you are talking about the C.elegans N2 strain:if you look in Directory->C.elegans you can see in the Genome Assemblies section when which assembly was live.The current WBcel235 has been live since WS235, so all genomic coordinates since WS235 should be on the same reference.
