### ISSUE TITLE
Error displaying premature stop codon effect in Molecular Details widget on Variation pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7468]
For example, on the ad1051 Variation page:
https://www.wormbase.org/species/c_elegans/variation/WBVar00000083#069--10

In the Molecular Details widget, the Protein Change section looks like:

<img width="999" alt="Screenshot 2019-12-18 12 54 33" src="https://user-images.githubusercontent.com/611382/71110578-91e88580-2195-11ea-97ab-16a00e79b70b.png">

The issue is that the mutation results in a "W to STOP" meaning the tryptophan "W" codon turns into a stop and so the "W" should not exist in the mutant protein but it is being displayed as such. Can we change the last red "W" in the mutant protein to "X" or simply end the sequence at the preceding amino acid, in this case "S"?

**Comment by sibyl229** [comment]
@chris-grove display for premature stop codon is fixed now: https://staging.wormbase.org/species/c_elegans/variation/WBVar00000083#06b--10 I agree the way it was shown was erroneous/misleading.

**Comment by chris-grove** [comment]
@sibyl229 
Sorry for the delay! Yes, looks good. Thanks! Closing.
