### ISSUE TITLE
  Access a gene prediction from an earl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7476]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Access a gene prediction from an earlier WormBase release? Thanks!</p>

**Reported by:** Miri********** (mbgo***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by epaule** [comment]
while we do not keep archived versions of our website, we keep the data it is based on here: ftp://ftp.wormbase.org/pub/wormbase/releases/ For each species and release you should be able to get a GFF file with the respective gene models and fasta files with the transcripts/proteins/etc. 
In cases were the underlying assembly hasn't changed, you can also see them on the gene page in the history section (and as Historic Gene Models in the Genome browsers).
