### ISSUE TITLE
can i find sequence of a gene of interest on wormb...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7478]
*Help Desk query collected when no chat operators were online. Follow up required.*

can i find sequence of a gene of interest on wormbase ? For example the gene JU1511 ?

**Reported by:** joe (jmga**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/species/c_elegans/strain/WBStrain00000035#03--10">https://wormbase.org/species/c_elegans/strain/WBStrain00000035#03--10</a>
**Browser:** Chrome 76.0.3809.132

**Comment by WenChenWormBase** [comment]
Dear Joe,

JU1511 is not a gene name. It is a strain name.

Please let us know if you were looking for something else.

Wen Chen, Ph.D.
Curator, WormBase

On Fri, Dec 20, 2019 at 10:33 AM <no-reply@wormbase.org> wrote:

> offline chat can i find sequence of a gene of interest on wormbase ? For
> example the gene JU1511 ?
>
> Submitted From:
>   https://wormbase.org/species/c_elegans/strain/WBStrain00000035#03--10
> https://wormbase.org/species/c_elegans/strain/WBStrain00000035#03--10
> <http://wormbase.org/https://wormbase.org/species/c_elegans/strain/WBStrain00000035#03--10>
>
> This issue has been assigned ticket number: #7478. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/7478>.
>
> Reported by: joe (jmgavazi@gmail.com)
> 20 Dec 19 18:33
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen
Curator, WormBase
