### ISSUE TITLE
I'm curious if the lin-4 host gene officially goes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7484]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'm curious if the lin-4 host gene officially goes by lho-1. If not what its official name? Thanks.

**Reported by:** Kevi********** (kevi**************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/http://dev.wormbase.org:9004/search/gene/lho-1">http://dev.wormbase.org:9004/search/gene/lho-1</a>
**Browser:** Firefox 71.0

**Comment by WenChenWormBase** [comment]
Dear Kevin,

I cannot find any record in WormBase for the name lho-1. After I searched
our complete literature collection via Textpresso, I only found this
tentative name published by Liu FZ  and Ambros VR as meeting abstract and
gazette article. So I suppose this gene was never officially named.

Maybe you can ask Victor Ambros himself? Let me know if you get an answer.

BTW, most of us are gone for the holiday break. Maybe one of my colleagues
will email you more useful information later.

Happy New Year!

Wen Chen
Curator, WormBase

On Sun, Dec 29, 2019 at 5:14 PM <no-reply@wormbase.org> wrote:

> offline chat I'm curious if the lin-4 host gene officially goes by lho-1.
> If not what its official name? Thanks.
>
> Submitted From:
>   http://dev.wormbase.org:9004/search/gene/lho-1
> http://dev.wormbase.org:9004/search/gene/lho-1
> <http://wormbase.org/http://dev.wormbase.org:9004/search/gene/lho-1>
>
> This issue has been assigned ticket number: #7484. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/7484>.
>
> Reported by: Kevin Peterson (kevin.j.peterson@dartmouth.edu)
> 30 Dec 19 01:14
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Hi Wen

thank you very much!

happy holidays

best

Kevin
