### ISSUE TITLE
 Server Error: 500 at  rest/widget/index/c_elegans...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7487]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/rest/widget/index/c_elegans/all/assemblies">rest/widget/index/c_elegans/all/assemblies</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget_class_index "Could not connect to database acedb _WS274, host: b35be15935d5" </p>

**Reported by:** Chri******* (chri**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by tharris** [comment]
Issue resolved; user notified.
