### ISSUE TITLE
  Dear WormBase,  the "Enrichment Analy...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7490]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase, <br/>the "Enrichment Analysis " Tool link is not working. <br/>https://wormbase.org/tools/enrichment/tea/tea.cgi<br/>Thank you<br/>Yi</p>

**Reported by:** Yi W***** (yi.w************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

**Comment by chris-grove** [comment]
Confirmed:
<img width="311" alt="Screenshot 2020-01-06 12 38 58" src="https://user-images.githubusercontent.com/611382/71836406-ed65af00-3081-11ea-8a09-17343c969558.png">

**Comment by chris-grove** [comment]
@raymond91125 
SObA graphs are all down as well

**Comment by raymond91125** [comment]
Hi Yi,

The enrichment tool is now restored. Thanks for the alert.

Cheers,

Raymond

On 06/01/2020 9:36 AM, no-reply@wormbase.org wrote:
> Bug Report
>
>   Dear WormBase,
> the "Enrichment Analysis " Tool link is not working.
> https://wormbase.org/tools/enrichment/tea/tea.cgi
> Thank you
> Yi
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7490. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7490>.
>
> Reported by: Yi Weaver (yi.weaver@utsouthwestern.edu)
> 06 Jan 20 17:36
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 
> Firefox/71.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
for some reason apache2 went dead. restarted and everything seems good. for now.
