### ISSUE TITLE
Tree Display problems

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7492]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): https://wormbase.org/resources/person/WBPerson31635#05--10</br>Chris: Hey Raymond, what's up?</br>visitor_name (visitor_email): Hi Chris, I just want to report that some person pages have broken Tree Display but not others.</br>visitor_name (visitor_email): broken https://wormbase.org/resources/person/WBPerson128#05--10</br>Chris: OK, I think there is a site-wide issue with Tree Display at the moment that Sibyl and Todd are aware of and working on currently</br>visitor_name (visitor_email): OK then. thanks.</br>Chris: Sure

**Reported by:** Raym******* (raym****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/resources/person/WBPerson31635#05--10">https://wormbase.org/resources/person/WBPerson31635#05--10</a>
**Browser:** Firefox 71.0

**Comment by chris-grove** [comment]
Should be resolved with ongoing work. Will leave open until resolved.

**Comment by tharris** [comment]
Issue resolved with dedicated resources for acedb-requiring features.  User contacted.
