### ISSUE TITLE
  I would like to know how to sign up a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7494]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to know how to sign up as a lab head. I already have assigned strain and allele names but my lab does not show up in the list. <br/>Thanks in advance for yuor help, <br/>María Olmedo</p>

**Reported by:** mari******** (mari***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:71.0) Gecko/20100101 Firefox/71.0

**Comment by tharris** [comment]
Invited user to the lab heads mailing list.
