### ISSUE TITLE
 Server Error: 500 at  tools/epcr/run   
  Error M...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7495]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/tools/epcr/run">tools/epcr/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "Could not connect to database acedb _WS274, host: 8cbf1a1a9ee8" </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to precisely locate a PCR product on the genome to confirm my primers design</p>

**Reported by:** Gely* (loic*****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/epcr/run">/tools/epcr/run</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0

**Comment by tharris** [comment]
Issue resolved; user notififed.
