### ISSUE TITLE
  Hi, I've been using your Restful API ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7499]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I've been using your Restful API over the last couple of months, and recently I've been having some problem. For example when I'm sending this http request:http://rest.wormbase.org/rest/widget/gene/WBGene00009160/overview<br/>I'm getting this following error:requests.exceptions.ConnectionError: HTTPConnectionPool(host='rest.wormbase.org', port=80): Max retries exceeded with url: /rest/widget/gene/WBGene00022603/overview (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000001C890566198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))<br/>I was wondering if there was something wrong with my code or is it your service that is having some difficulties?Thank you,visitor_name</p>

**Reported by:** Lira* (lira***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by tharris** [comment]
User contacted. Issue resolved (DNS prob).
