### ISSUE TITLE
  Dear wormbase team, in the protein en...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7509]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase team,<br/>in the protein entry for sequence features, there are nicely shown the domains detected within a given protein, from sources such as hmmpanther, interpro, pfam, pfscan, smart, etc. I only see this as color code, but I never see any legend that gives a clue on the meaning of the color code / identitiy of the different domains. How do I get this annotated, and also, should there be hyperlinks to these databases / protein domain descriptions? <br/>I use Firefox, is this a browser problem?<br/>Alternatively, is this a feature that could be added to wormbase ? I think it would be quite helpful.<br/>Thank you and best,<br/>Alexander </p>

**Reported by:** Alex**************** (a.go****************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0

**Comment by chris-grove** [comment]
My email to user:
"""Thank you for writing in to WormBase. Are you referring to a protein web page like this one:

https://wormbase.org/species/c_elegans/protein/CE06191#05--10

We have a "Motif Details" widget that contains the name of the motif that links to that motif/domain page at WormBase, the description (often times a human-readable name of the domain), the source name that links to the domain page at that respective resource, the start and stop coordinates for the motif within that particular protein sequence and the match score.

<img width="1093" alt="Screenshot 2020-01-13 09 59 05" src="https://user-images.githubusercontent.com/611382/72266033-88fba000-35eb-11ea-90d4-c6a2db6c86a6.png">

Is that what you were looking for?
"""
