### ISSUE TITLE
How should I find the Genomic position of chromoso...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7510]
*Help Desk query collected when no chat operators were online. Follow up required.*

How should I find the Genomic position of chromosome II 7-11Mb on wormbase

**Reported by:** Yang***** (1575***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00018783#04-9f16-3">https://wormbase.org/species/c_elegans/gene/WBGene00018783#04-9f16-3</a>
**Browser:** Chrome 79.0.3945.117

**Comment by chris-grove** [comment]
My email to user:
"""
Could you clarify your question? Are you looking to view that region of the genome in a genome browser? You can open up JBrowse (linkable from the Location widget on any gene page, or discoverable under the Tools menu) and paste in the following address:

II:7000000..11000000

This is a very large region, so will not be able to see much detail:

https://wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=II%3A7000004..11000004&tracks=Landmarks%2CCurated_Genes%2CDNA&highlight=

Let us know if you're looking for something else.
"""
