### ISSUE TITLE
  ftp://ftp.wormbase.org/pub/wormbase/ ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7513]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;ftp://ftp.wormbase.org/pub/wormbase/<br/>this URL is giving me a 'Failed to open page' error.  the error is:<br/>"Redirection to URL with a scheme that is not HTTP(S)"</p><p>What were you doing? <br />&nbsp;&nbsp;trying to find WB's gff to see what values you guys use in col3.  underscores in SO terms or not.  we removed them, but i'm thinking we might need to add them back so i'm seeing what other Alliance groups do in their gff3s.</p>

**Reported by:** Stac*********** (stac***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15

**Comment by chris-grove** [comment]
My email to user:
"""
 Sorry about the error. Were you using Safari by any chance? Can you tell us how you arrived at that URL (from a click or manually typed or pasted in address bar)?

To answer your question, yes we use underscores. Here's a sampling of unique terms from the first 10,000 lines of our current GFF3:

DNAseI_hypersensitive_site
G_quartet
PCR_product
RNAi_reagent
SAGE_tag
SL1_acceptor_site
SL2_acceptor_site
SNP
TF_binding_site
TSS_region
assembly_component
binding_site
biological_region
complex_substitution
deletion
exon
experimental_result_region
expressed_sequence_match
five_prime_UTR
gene
histone_binding_site
insertion_site
intron
inverted_repeat
low_complexity_region
mRNA
mRNA_region
ncRNA
nc_primary_transcript
nucleotide_match
point_mutation
polyA_site
polypeptide_motif
promoter
protein_coding_primary_transcript
protein_match
pseudogenic_transcript
reagent
repeat_region
snoRNA
tandem_duplication
tandem_repeat
three_prime_UTR
transcribed_fragment
transcript_region
transcription_end_site
translated_nucleotide_match
transposable_element
transposable_element_insertion_site

I hope that helps!
"""

**Comment by chris-grove** [comment]
From user:
"""
i just googled wormbase gff and landed on a wiki page https://wiki.wormbase.org/index.php/Downloads

now i see a big warning on that page - did you just add that?  lol i didn’t see it before.

also on that page, this link is bad: C. angaria current release current.gff3.gz
"""

**Comment by chris-grove** [comment]
From @nuin 
"""
How are you trying to connect? Are you trying just to connect to the pub dir or tried a direct link to a file/folder?

The FTP site seems to be working fine for me.
"""

**Comment by chris-grove** [comment]
From user:
"""
yes Safari all the time.  Google search for ‘wormbase gff’, then clicked on ‘Downloads - WormBase Wiki’.  it’s the 6th link in the results for me.

thanks for the gff col3 info.  not sure when our underscores went missing, but i have an inkling.  we’ll add them back.  ...i can’t believe no one else complained to us about it!
"""

**Comment by chris-grove** [comment]
My email to user:
"""
 OK. It's been a known issue that Safari doesn't like to play nice with our FTP site (asks users to login, etc.).

It looks like that warning has been there since 2011 or so, so no we didn't just add it 😉

I see the Google search results (6th for me as well).

OK, glad I could clear up the GFF issue.
"""

**Comment by tharris** [comment]
Closing, as we don't develop Safari; FTP site works fine via, say, ftp clients.
