### ISSUE TITLE
  Hi I'm curious to get the sequence of...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7517]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi<br/>I'm curious to get the sequence of the pSAK4 and pSAK2 plasmids to make a figure for a lecture on RNAi. Is there somewhere where I can download the primary sequences of these two plasmids?<br/>Thanks<br/>Kevin</p><p>What were you doing? <br />&nbsp;&nbsp;Teaching! : )</p>

**Reported by:** Kevi********** (kevi**************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:72.0) Gecko/20100101 Firefox/72.0

**Comment by chris-grove** [comment]
My email to user:
"""
We don't have the sequence of these two plasmids at WormBase, and I didn't see them at Addgene either. Here are the two WormBase pages for the constructs/plasmids:

pSAK2
https://wormbase.org/species/all/construct/WBCnstr00000216#013--10

pSAK4
https://wormbase.org/species/all/construct/WBCnstr00019450#013--10

It seems that the earliest article referencing these plasmids is the 1998 Fire et al. Nature article:

https://wormbase.org/resources/paper/WBPaper00003005#0--10

I suppose your best bet to get the actual sequence would be to reach out to Andy Fire and/or members of his lab to see if the sequence is available.
"""
