### ISSUE TITLE
Protein domain FTP file only includes InterPro domains; should include all others in DB

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7526]
Currently, the protein domains file on the FTP site only includes Interpro domain info even though we have many other domains (from other sources) in the database. We should add in all domains (from all sources) into the FTP file.

Current (WS274) file here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS274.protein_domains.csv.gz

**Comment by epaule** [comment]
resolved for WS276

**Comment by chris-grove** [comment]
Thanks @epaule !
