### ISSUE TITLE
Hi..
I am interested in identifying the location o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7529]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi..
I am interested in identifying the location of number of genes in C. elegans.

could you please help me whether any of the tools in wormbase can be performed ?

(the number of proteins is around 900-1000)

**Reported by:** Poor************ (poor********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/#012-34-5-4">https://wormbase.org/#012-34-5-4</a>
**Browser:** Chrome 79.0.3945.117

**Comment by chris-grove** [comment]
My email to user:
"""
You can get the genomic location for a list of genes using either WormMine or WormBase ParaSite BioMart.

1) For WormMine, navigate to the WormMine homepage (a link to which is discoverable under the WormBase Tools menu):

http://intermine.wormbase.org/tools/wormmine/begin.do

Click on the "Lists" tab, then click on "Upload" (if not already selected), make sure "Gene" is selected under "Select Type" and leave "for Organism" as the default "Any". In the search box, paste in your gene list (WBGene IDs would be most reliable, but you can use public names and/or sequence names) and click on "Create List". You can name your list like "Pooranachithra gene list" and click on "Save a list of # Genes". Next click on the "QueryBuilder" tab, click on "Import query from XML", paste in the following query:

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.strand Gene.chromosomeLocation.start Gene.chromosomeLocation.end" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>


and click on "Submit". Once you see the "Query Overview" and "Model browser", in the Model browser click on the "CONSTRAIN" to the right of "WormBase Gene ID", click the checkbox to the left of "Contained in list:" and select your list "Pooranachithra gene list" from the drop-down menu. Click on "Add to query" and then click on "Show results". You can then export your table as a tab-separated-values or comma-separated-values file.

2) For WormBase ParaSite BioMart, navigate to the homepage (a link to which is discoverable under the WormBase Tools menu):

http://parasite.wormbase.org/biomart/martview

Add your list of genes under the "GENE" section of the "Query Filters" options, and under "Output Attributes" in the GENE -> Gene Attributes section select your Gene stable ID, Gene name, Chromosome/scaffold name, Strand, Gene start (bp), and Gene end (bp), then click on "Results" at the top. Here's the query for all C. elegans genes:

https://bit.ly/36jH99s

You can then download a TSV table of the results.

Let us know if you have any questions.
"""
