### ISSUE TITLE
  Hello, I am visitor_name, M.Sc. stude...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7538]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am visitor_name, M.Sc. student in Turkey. I would like to download whole gene interaction database for C. elegans but could not find it. Could you please provide me the data, or direct me to be able to download the data?<br/>Thanks in advance<br/>visitor_name</p>

**Reported by:** Must*** (must******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
The current interactions file can always be found on our FTP site in this directory:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/

The current file for the WS274 release of WormBase is here:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS274.interactions.txt.gz

The file contains all physical, regulatory, and genetic interactions for the WS274 release. Predicted interactions would have to be queried out of the database separately. Please let me know if you want the predicted interactions as well.
"""
